include::./index.adoc[]

[[v31-3-0]]
=== Lamentações, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Lamentações 3 é um capítulo em que o autor expressa seu lamento e tristeza diante das aflições que está enfrentando. Ele se sente abatido, sofre e clama por ajuda e misericórdia. Abaixo estão cinco versículos relacionados com os temas do capítulo:
* Salmos 22:1 - "Deus meu, Deus meu, por que me desamparaste?" Este versículo é uma expressão de angústia semelhante à do autor de Lamentações 3, que se sente abandonado e sozinho em sua dor.
* Salmos 42:5 - "Por que estás abatida, ó minha alma, e por que te perturbas em mim? Espera em Deus, pois ainda o louvarei pela salvação da sua face." O salmista aqui está encorajando sua alma a confiar em Deus e esperar por sua ajuda, o que é uma mensagem semelhante à do autor de Lamentações 3.
* Isaías 49:15 - "Porventura pode uma mulher esquecer-se tanto do filho que cria, que não se compadeça dele, do filho do seu ventre? Mas ainda que esta se esquecesse dele, contudo eu não me esquecerei de ti." Este versículo é um lembrete do amor incondicional de Deus por seu povo, mesmo em meio às dificuldades.
* 2 Coríntios 4:8-9 - "Em tudo somos atribulados, mas não angustiados; perplexos, mas não desanimados; perseguidos, mas não desamparados; abatidos, mas não destruídos." O apóstolo Paulo aqui fala sobre a natureza das dificuldades que enfrentamos, mas enfatiza que podemos perseverar em Deus, assim como o autor de Lamentações 3.
* Romanos 8:38-39 - "Porque estou certo de que, nem a morte, nem a vida, nem anjos, nem principados, nem coisas presentes, nem futuras, nem potestades, nem a altura, nem a profundidade, nem qualquer outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus nosso Senhor." Este versículo é uma promessa de que o amor de Deus é inabalável e que podemos confiar em sua fidelidade, mesmo quando enfrentamos as maiores dificuldades.
****

[[v31-3-1]]

^<<v31-3-1,1>>^ Álef: Eu sou o homem que conheceu a dor, sob a vara de seu furor.^&#42;1^

[[v31-3-2]]

^<<v31-3-2,2>>^ Conduziu-me e me fez caminhar nas trevas e não na claridade.

[[v31-3-3]]

^<<v31-3-3,3>>^ Ele não cessa de voltar a mão todos os dias contra mim.

[[v31-3-4]]

^<<v31-3-4,4>>^ Bet: Consumiu minha carne e minha pele, partiu meus ossos.

[[v31-3-5]]

^<<v31-3-5,5>>^ Em torno de mim acumulou veneno e dor.

[[v31-3-6]]

^<<v31-3-6,6>>^ Fez-me morar nas trevas como os mortos do tempo antigo.

[[v31-3-7]]

^<<v31-3-7,7>>^ Guímel: Cercou-me com muralhas sem saída, carregou-me de pesados grilhões.

[[v31-3-8]]

^<<v31-3-8,8>>^ Não obstante meus gritos e apelos sufocou a minha prece!

[[v31-3-9]]

^<<v31-3-9,9>>^ Fechou-me a vereda com pedras e obstruiu o meu caminho.

[[v31-3-10]]

^<<v31-3-10,10>>^ Dálet: Foi ele para mim qual urso de emboscada, qual leão traiçoeiro.

[[v31-3-11]]

^<<v31-3-11,11>>^ Desviou-me para me dilacerar, deixando-me no abandono.

[[v31-3-12]]

^<<v31-3-12,12>>^ Retesou o arco e me tomou para alvo de suas setas.

[[v31-3-13]]

^<<v31-3-13,13>>^ Hê: Cravou em meus rins as flechas de sua aljava.

[[v31-3-14]]

^<<v31-3-14,14>>^ Tornei-me escárnio do meu povo, objeto constante de suas canções.

[[v31-3-15]]

^<<v31-3-15,15>>^ Saturou-me de amarguras, saciou-me de absinto.

[[v31-3-16]]

^<<v31-3-16,16>>^ Vaw: Quebrou-me os dentes com cascalhos, mergulhou-me em cinzas.^&#42;1^

[[v31-3-17]]

^<<v31-3-17,17>>^ A paz foi roubada de minha alma, nem sei mais o que é felicidade.

[[v31-3-18]]

^<<v31-3-18,18>>^ E eu penso: perdi minha força e minha esperança no Senhor.

[[v31-3-19]]

^<<v31-3-19,19>>^ Záin: A lembrança de meus tormentos e minhas misérias é para mim absinto e veneno.

[[v31-3-20]]

^<<v31-3-20,20>>^ A pensar nisso sem cessar, minha alma desfalece dentro de mim.

[[v31-3-21]]

^<<v31-3-21,21>>^ Eis, porém, o que vou tomar a peito para recuperar a esperança.^&#42;1^

[[v31-3-22]]

^<<v31-3-22,22>>^ Het: É graças ao Senhor que não fomos aniquilados, porque não se esgotou sua piedade.

[[v31-3-23]]

^<<v31-3-23,23>>^ Cada manhã ele se manifesta e grande é sua fidelidade.

[[v31-3-24]]

^<<v31-3-24,24>>^ Disse-me a alma: o Senhor é minha partilha, e assim nele confio.

[[v31-3-25]]

^<<v31-3-25,25>>^ Tet: O Senhor é bom para quem nele confia, para a alma que o procura.

[[v31-3-26]]

^<<v31-3-26,26>>^ Bom é esperar em silêncio o socorro do Senhor.

[[v31-3-27]]

^<<v31-3-27,27>>^ É bom para o homem carregar seu jugo na mocidade.

[[v31-3-28]]

^<<v31-3-28,28>>^ Yod: Permaneça só e em silêncio, quando Deus lhe determinar!

[[v31-3-29]]

^<<v31-3-29,29>>^ Leve sua boca ao pó; haverá, talvez, esperança?

[[v31-3-30]]

^<<v31-3-30,30>>^ Estenda a face a quem o fere, e se farte de opróbrios!

[[v31-3-31]]

^<<v31-3-31,31>>^ Kaf: Porque o Senhor não repele para sempre.

[[v31-3-32]]

^<<v31-3-32,32>>^ Após haver afligido, ele tem piedade, porque é grande sua misericórdia.

[[v31-3-33]]

^<<v31-3-33,33>>^ Não lhe alegra o coração humilhar e afligir os homens.

[[v31-3-34]]

^<<v31-3-34,34>>^ Lámed: Calcar aos pés todos os cativos da terra;

[[v31-3-35]]

^<<v31-3-35,35>>^ violar o direito de um homem à face do Altíssimo;

[[v31-3-36]]

^<<v31-3-36,36>>^ lesar os direitos de outros... Não vê tudo isso o Senhor?

[[v31-3-37]]

^<<v31-3-37,37>>^ Mem: De quem se executa a ordem, sem que Deus a ordene?

[[v31-3-38]]

^<<v31-3-38,38>>^ Não é da boca do Altíssimo que procedem males e bens?

[[v31-3-39]]

^<<v31-3-39,39>>^ De que pode o homem em vida queixar-se? Que cada um se queixe de seus pecados.^&#42;1^

[[v31-3-40]]

^<<v31-3-40,40>>^ Nun: Examinemos, escrutemos o nosso proceder, e voltemos para o Senhor.

[[v31-3-41]]

^<<v31-3-41,41>>^ Elevemos os corações, tanto quanto as mãos, para Deus lá nos céus.

[[v31-3-42]]

^<<v31-3-42,42>>^ Pecamos, recalcitramos, e não nos perdoastes.

[[v31-3-43]]

^<<v31-3-43,43>>^ Sámec: Cobristes-vos de cólera para nos perseguir. Matastes sem piedade.

[[v31-3-44]]

^<<v31-3-44,44>>^ em uma nuvem vos envolvestes para impedir que a prece a atravessasse.

[[v31-3-45]]

^<<v31-3-45,45>>^ E de nós fizestes raspas, refugo das nações.

[[v31-3-46]]

^<<v31-3-46,46>>^ Pê: Contra nós abrem a boca todos os nossos inimigos.

[[v31-3-47]]

^<<v31-3-47,47>>^ Fosso e terror – é o nosso quinhão, com ruínas e desolação.

[[v31-3-48]]

^<<v31-3-48,48>>^ Rios de lágrimas correm-me dos olhos, por causa da ruína da filha de meu povo.

[[v31-3-49]]

^<<v31-3-49,49>>^ Áin: Não cessam meus olhos de chorar, porque não cessa a desgraça,

[[v31-3-50]]

^<<v31-3-50,50>>^ até que do alto dos céus o Senhor desça seu olhar.

[[v31-3-51]]

^<<v31-3-51,51>>^ Minha alma se amargura, ao ver todas as filhas da minha cidade.

[[v31-3-52]]

^<<v31-3-52,52>>^ Tsade: Caçaram-me como a um pardal os que, sem razão, me odeiam.

[[v31-3-53]]

^<<v31-3-53,53>>^ Quiseram precipitar-me no fosso rolando uma pedra sobre mim.

[[v31-3-54]]

^<<v31-3-54,54>>^ Acima de mim subiam as águas: “Estou perdido!” – exclamei.

[[v31-3-55]]

^<<v31-3-55,55>>^ Qof: Invoquei, Senhor, o vosso nome do profundo fosso.

[[v31-3-56]]

^<<v31-3-56,56>>^ Ouvistes-me gritar: “Não aparteis do meu chamado o vosso ouvido”.

[[v31-3-57]]

^<<v31-3-57,57>>^ E vós viestes no dia em que vos invoquei e dissestes: “Não tenhas medo!”.

[[v31-3-58]]

^<<v31-3-58,58>>^ Resh: Defendestes, Senhor, a minha causa, e minha vida resgatastes.

[[v31-3-59]]

^<<v31-3-59,59>>^ Vistes, Senhor, o mal que me fizeram: fazei-me justiça.

[[v31-3-60]]

^<<v31-3-60,60>>^ Vós vedes seus projetos vingativos e suas tramas contra mim.

[[v31-3-61]]

^<<v31-3-61,61>>^ Shin: Senhor, ouvistes suas injúrias e todos os seus conluios contra mim;

[[v31-3-62]]

^<<v31-3-62,62>>^ As palavras de meus inimigos e o que sem cessar estão tramando contra mim.

[[v31-3-63]]

^<<v31-3-63,63>>^ Observai-os: sentados ou de pé, fazem de mim objeto de suas canções.

[[v31-3-64]]

^<<v31-3-64,64>>^ Taw: Dai-lhes, Senhor, a paga, o que merece o seu proceder.

[[v31-3-65]]

^<<v31-3-65,65>>^ Cegai-lhes o coração; feri-os com a vossa maldição;

[[v31-3-66]]

^<<v31-3-66,66>>^ persegui-os com vossa cólera, e exterminai-os do nosso universo, Senhor!

'''

xref:031-lamentacoes/031-lamentacoes-002.adoc#v31-2-0[&#60; Capítulo Anterior] | <<v31-3-0,Topo>> | xref:031-lamentacoes/031-lamentacoes-004.adoc#v31-4-0[Próximo Capítulo &#62;]