include::./index.adoc[]

[[v31-4-0]]
=== Lamentações, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Lamentações 4 fala sobre a destruição de Jerusalém e a punição que o povo sofreu por causa de seus pecados. O capítulo também descreve a situação desesperadora dos habitantes da cidade, que passaram fome e sofreram outras formas de violência. Aqui estão cinco versículos relacionados com os temas abordados em Lamentações 4:
* Salmos 137:7: "Lembra-te, Senhor, dos filhos de Edom, no dia de Jerusalém, que diziam: Descobri-a, descobri-a até aos seus alicerces." Este salmo é uma lamentação dos judeus que foram levados cativos para a Babilônia, e ele lembra do sofrimento dos habitantes de Jerusalém. O verso citado pede que Deus se lembre daqueles que contribuíram para a destruição da cidade.
* Isaías 3:8: "Jerusalém está arruinada, e Judá caiu; porque a sua língua e as suas obras são contra o Senhor, para provocarem os olhos da sua glória." Este verso descreve a queda de Jerusalém e Judá, e atribui a culpa aos seus habitantes por causa de suas ações pecaminosas.
* Ezequiel 5:10: "Portanto, os pais comerão a seus filhos no meio de ti, e os filhos comerão a seus pais; e executarei em ti juízos, e tudo o que restar de ti espalharei a todos os ventos." Este verso descreve a fome extrema que ocorreu durante o cerco de Jerusalém, que levou as pessoas a recorrerem ao canibalismo.
* Lamentações 4:9: "Os que foram mortos à espada foram mais felizes do que os que morreram de fome; porque estes, esgotados pelos efeitos da fome, iam desfalecendo aos poucos, até expirarem, ao passo que aqueles, atravessados pela espada, morriam subitamente." Este verso descreve a diferença entre as mortes que ocorreram durante o cerco, e afirma que morrer pela espada era preferível à morte lenta e agonizante por causa da fome.
* Jeremias 19:9: "Farei com que comam a carne de seus filhos e a carne de suas filhas, e comerão cada um a carne do seu próximo, durante o cerco e no aperto com que os apertarão os seus inimigos, e os que procuram tirar-lhes a vida." Este verso é uma profecia da destruição de Jerusalém, e afirma que o povo sofrerá tanto durante o cerco que recorrerá ao canibalismo para sobreviver.
****

[[v31-4-1]]

^<<v31-4-1,1>>^ Álef: Como escureceu o ouro, como se alterou o ouro fino! Foram dispersadas as pedras sagradas por todos os cantos da rua?

[[v31-4-2]]

^<<v31-4-2,2>>^ Bet: Os nobres filhos de Sião, tão estimados quanto o ouro fino, ei-los contados como vasos, obra de um oleiro!

[[v31-4-3]]

^<<v31-4-3,3>>^ Guímel: Mesmo chacais dão a mama, a fim de aleitar suas crias; mas a filha do meu povo é cruel, qual avestruz do deserto.^&#42;1^

[[v31-4-4]]

^<<v31-4-4,4>>^ Dálet: A língua dos bebês, de tanta sede, se lhes prega ao palato! As crianças reclamam pão. E ninguém lhe dá.

[[v31-4-5]]

^<<v31-4-5,5>>^ Hê: Aqueles que em comidas finas se compraziam definham pelas ruas. E os que foram educados no fausto têm por leito o esterco.

[[v31-4-6]]

^<<v31-4-6,6>>^ Vaw: O castigo da filha do meu povo é maior que o pecado de Sodoma, em um momento destruída sem que ninguém lhe lançasse a mão.

[[v31-4-7]]

^<<v31-4-7,7>>^ Záin: Os príncipes brilhavam mais que a neve, mais brancos do que o leite. Seus corpos eram mais vermelhos que o coral, e era de safira o seu aspecto.

[[v31-4-8]]

^<<v31-4-8,8>>^ Het: Agora, seus rostos ficaram mais sombrios do que a fuligem; pelas ruas, são irreconhecíveis. A pele se lhes colou aos ossos, e qual madeira ressecou-se.

[[v31-4-9]]

^<<v31-4-9,9>>^ Tet: As vítimas do gládio são mais felizes do que as da fome, que lentamente se esgotam pela falta dos produtos da terra.^&#42;1^

[[v31-4-10]]

^<<v31-4-10,10>>^ Yod: Mãos de mulheres, cheias de ternura, cozinharam os filhos, a fim de servirem de alimento, quando da ruína da filha de meu povo.

[[v31-4-11]]

^<<v31-4-11,11>>^ Kaf: O Senhor saciou o seu furor, e derramou o ardor de sua cólera, acendendo um fogo em Sião que a devorou até os alicerces.

[[v31-4-12]]

^<<v31-4-12,12>>^ Lámed: Não podiam acreditar os reis da terra, e todos os habitantes do mundo, que o inimigo opressor transporia as portas de Jerusalém.

[[v31-4-13]]

^<<v31-4-13,13>>^ Mem: Foi por causa dos pecados de seus profetas e das iniquidades dos sacerdotes, que derramavam em seus muros o sangue dos justos.

[[v31-4-14]]

^<<v31-4-14,14>>^ Nun: Quais cegos erravam pelas ruas, vertendo sangue a tal ponto que ninguém ousava tocar em suas vestes.^&#42;1^

[[v31-4-15]]

^<<v31-4-15,15>>^ Sámec: “Para trás! É um impuro!” – lhes gritavam. “Para trás! Para trás! Não toqueis!” E quando fugiam, errantes entre os pagãos, todos diziam: “Aqui não ficarão”.^&#42;1^

[[v31-4-16]]

^<<v31-4-16,16>>^ Pê: A face do Senhor dispersou-os e para eles não olha mais: nenhuma deferência aos sacerdotes, nem piedade com os anciãos.

[[v31-4-17]]

^<<v31-4-17,17>>^ Áin: Nossos olhos se consumiam, na esperança de um vão socorro. Espreitávamos do alto das torres a vinda de um povo incapaz de nos livrar.^&#42;1^

[[v31-4-18]]

^<<v31-4-18,18>>^ Tsade: Espreitavam os nossos passos; nem mais podíamos andar pela rua. Nosso fim se aproxima. Terminam nossos dias. Sim! Chegou o nosso termo.

[[v31-4-19]]

^<<v31-4-19,19>>^ Qof: Os que nos perseguiam eram mais velozes que as águias do céu. Seguiram-nos pelos montes e nos armaram ciladas no deserto.

[[v31-4-20]]

^<<v31-4-20,20>>^ Resh: O sopro de nossa vida o ungido do Senhor, caiu em suas ciladas. De quem dizíamos: “À sua sombra viveremos entre as nações”.^&#42;1^

[[v31-4-21]]

^<<v31-4-21,21>>^ Shin: Exulta, alegra-te, filha de Edom, habitante da terra de Us! A ti também será passado o cálice, e embriagada descobrirás tua nudez.^&#42;1^

[[v31-4-22]]

^<<v31-4-22,22>>^ Taw: Findou teu castigo, filha de Sião (Deus) não mais te exilará. É a teus crimes que ele vai castigar, filha de Edom, e descobrir os teus pecados.^&#42;1^

'''

xref:031-lamentacoes/031-lamentacoes-003.adoc#v31-3-0[&#60; Capítulo Anterior] | <<v31-4-0,Topo>> | xref:031-lamentacoes/031-lamentacoes-005.adoc#v31-5-0[Próximo Capítulo &#62;]