include::./index.adoc[]

[[v31-2-0]]
=== Lamentações, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Lamentações 2 descreve a destruição de Jerusalém pelo exército babilônico e a aflição do povo que ficou sem abrigo e alimento. O capítulo retrata a cidade de Jerusalém como uma viúva desolada que chora e clama por ajuda, mas ninguém a socorre. Abaixo estão cinco versículos relacionados com os temas abordados em Lamentações 2:
* Salmos 137:5-6: "Se eu me esquecer de ti, ó Jerusalém, esqueça-se a minha direita da sua destreza. Se me não lembrar de ti, apegue-se-me a língua ao paladar; se não preferir Jerusalém à minha maior alegria." Este salmo retrata a dor e a saudade que os judeus exilados sentiam por sua cidade natal, Jerusalém, após a destruição dela pelos babilônios. Essa saudade é uma temática presente em Lamentações 2.
* Isaías 3:26: "E as suas portas gemerão e prantearão; ela, desolada, se assentará no chão." Assim como em Lamentações 2, Isaías 3 descreve uma cidade (Jerusalém) desolada e sem esperança. Isaías também utiliza a imagem de portas gemendo e pranteando, que é uma figura de linguagem presente em Lamentações 2.
* Ezequiel 27:30-31: "E prantearão sobre ti com amargura de alma, e farão sobre ti pranto amargo, dizendo: Quem houve cidade semelhante a Tiro, destruída no meio do mar? Quando os teus negociantes eram príncipes, e os teus mercadores os mais ilustres da terra..." Esse versículo descreve o lamento dos habitantes de Tiro, que também foi destruída. O pranto e a lamentação são temas comuns em Lamentações 2.
* Joel 2:12-13: "Ainda assim, agora mesmo diz o Senhor: Convertei-vos a mim de todo o vosso coração; e isso com jejuns, e com choro, e com pranto. E rasgai o vosso coração, e não as vossas vestes, e convertei-vos ao Senhor vosso Deus; porque ele é misericordioso e compassivo, tardio em irar-se e grande em beneficência, e se arrepende do mal." Joel exorta o povo a se arrepender de seus pecados e se voltar para Deus, que é misericordioso. Essa mensagem é similar àquela presente em Lamentações 2, onde o povo é descrito como merecedor da punição divina.
* Zacarias 1:15: "E estou muito indignado contra as nações em segurança; porque eu estava um pouco indignado, mas eles agravaram o mal." Nesse versículo, Deus se mostra indignado com as nações que se sentem seguras enquanto Jerusalém foi destruída. Essa raiva divina também é presente em Lamentações 2, onde o povo sofre a punição de Deus por seus pecados.
****

[[v31-2-1]]

^<<v31-2-1,1>>^ Álef: Como cobriu irritado o Senhor com uma nuvem a filha de Sião? Precipitou do céu à terra a glória de Israel, e na sua cólera desinteressou-se do escabelo dos seus pés.^&#42;1^

[[v31-2-2]]

^<<v31-2-2,2>>^ Bet: O Senhor destruiu sem piedade todas as moradias de Jacó. E em seu furor arruinou as fortificações da filha de Judá. Lançou por terra e conspurcou o reino e seus príncipes.

[[v31-2-3]]

^<<v31-2-3,3>>^ Guímel: Na violência do seu furor, quebrou todo o poder de Israel. Ao aproximar-se o inimigo, retirou o apoio de sua mão, e provocou um incêndio em Jacó que devora tudo que o cerca.

[[v31-2-4]]

^<<v31-2-4,4>>^ Dálet: Retesou o arco, qual inimigo; firmou o braço, qual adversário; e tudo quanto encantava os olhos ele degolou. Na tenda da filha de Sião lançou o fogo do seu furor.

[[v31-2-5]]

^<<v31-2-5,5>>^ Hê: Semelhante a um inimigo o Senhor destruiu Israel. Demoliu seus edifícios, abateu suas fortalezas; sobre a filha de Sião acumulou dores sobre dores.

[[v31-2-6]]

^<<v31-2-6,6>>^ Vaw: Arrombou-lhe a tenda, como um jardim, e devastou seu santuário. O Senhor aboliu em Sião festas e sábados. E no ardor de sua cólera repeliu rei e sacerdote.

[[v31-2-7]]

^<<v31-2-7,7>>^ Záin: Desgostou-se do altar e rejeitou seu santuário. Entregou nas mãos dos inimigos as muralhas de seus fortes; elevaram-se gritos no templo, como nos dias de festas.^&#42;1^

[[v31-2-8]]

^<<v31-2-8,8>>^ Het: Resolveu o Senhor demolir os muros da filha de Sião. Estendeu o cordel, sem deter-se antes que tudo destruísse, e derrubou o muro e o antemuro que, juntos, desabaram.^&#42;1^

[[v31-2-9]]

^<<v31-2-9,9>>^ Tet: Jazem sob escombros as suas portas que ele quebrou, partindo as traves. Acham-se no estrangeiro seu rei e príncipes. Não há mais oráculos. Mesmo os profetas não mais recebem as visões do Senhor.^&#42;1^

[[v31-2-10]]

^<<v31-2-10,10>>^ Yod Sentados no chão, taciturnos, jazem os anciãos da filha de Sião. Jogaram poeira sobre os cabelos; vestiram-se com sacos; e as virgens de Jerusalém pendem a fronte para a terra.

[[v31-2-11]]

^<<v31-2-11,11>>^ Kaf: Ardiam-me os olhos, de tantas lágrimas; fremiam minhas entranhas. Minha bílis se espalhou por terra, ante a ruína da filha de meu povo, quando nas ruas da cidade desfaleciam os meninos e as crianças de peito.

[[v31-2-12]]

^<<v31-2-12,12>>^ Lámed: “Onde há pão e onde há vinho?!” – diziam eles às mães, desfalecendo, quais feridos, nas ruas da cidade, e entregando a alma no regaço materno.

[[v31-2-13]]

^<<v31-2-13,13>>^ Mem: Que dizer? A quem te comparar, filha de Jerusalém? Quem irá salvar-te e consolar-te, ó virgem, filha de Sião? É imensa como o mar tua ruína: quem poderá curar-te?^&#42;1^

[[v31-2-14]]

^<<v31-2-14,14>>^ Nun: Os teus profetas tinham visões apenas extravagantes e balofas. Não manifestaram tua malícia, o que teria poupado teu exílio. Os oráculos que te davam eram apenas mentiras e enganos.

[[v31-2-15]]

^<<v31-2-15,15>>^ Sámec: Todos os transeuntes, ao te verem, batem palmas, e assobiando meneiam a cabeça sobre a filha de Jerusalém. “Eis a cidade da qual diziam ser a beleza perfeita, a alegria do universo.”

[[v31-2-16]]

^<<v31-2-16,16>>^ Pê: Abrem a boca contra ti todos os teus inimigos. Escarnecem e rangem os dentes. “Nós destruímos” – dizem eles – “eis o dia esperado, estamos nele, estamos vendo!”

[[v31-2-17]]

^<<v31-2-17,17>>^ Áin: Realizou o Senhor o seu desígnio, executando as ameaças que outrora proferira. E destruiu sem piedade. À tua custa contentou o inimigo, exaltando o poder de teus adversários.

[[v31-2-18]]

^<<v31-2-18,18>>^ Tsade: Seu coração clama ao Senhor. Ó muralha da filha de Sião, transborda dia e noite a torrente de tuas lágrimas! Não te dês descanso, e teus olhos não cessem de chorar!

[[v31-2-19]]

^<<v31-2-19,19>>^ Qof: Levanta-te à noite; grita ao início de cada vigília; que se derrame teu coração ante a face do Senhor. Ergue para ele as mãos, pela vida de teus filhos que caem de inanição, em todos os cantos das ruas.

[[v31-2-20]]

^<<v31-2-20,20>>^ Resh: “Olhai, Senhor, e considerai! A quem jamais tratastes assim? Como! Mães a devorar os seus frutos, suas criancinhas de colo! Foram massacrados sacerdotes e profetas no santuário do Senhor!^&#42;1^

[[v31-2-21]]

^<<v31-2-21,21>>^ Shin: Jazem pelo chão nas ruas o menino e o velho. Virgens e jovens pereceram pelo gládio. Matastes, no dia de vossa cólera, imolastes sem piedade.

[[v31-2-22]]

^<<v31-2-22,22>>^ Taw: Convocastes como para uma festa a multidão de terrores. No dia do furor divino ninguém fugiu, nenhum escapou. E aqueles que criei e eduquei meu inimigo os exterminou!’’

'''

xref:031-lamentacoes/031-lamentacoes-001.adoc#v31-1-0[&#60; Capítulo Anterior] | <<v31-2-0,Topo>> | xref:031-lamentacoes/031-lamentacoes-003.adoc#v31-3-0[Próximo Capítulo &#62;]