include::./index.adoc[]

[[v71-1-0]]
=== III São João, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 3 João 1 é um capítulo curto que contém uma carta de João endereçada a Gaio. Na carta, João elogia Gaio por sua fidelidade e hospitalidade para com os irmãos da igreja. Ele também adverte Diótrefes, que estava causando problemas na igreja, e elogia Demétrio. Abaixo estão cinco versículos relacionados com os temas abordados em 3 João 1:
* Provérbios 23:6-7: "Não comas o pão daquele que tem os olhos malignos, nem cobices as suas iguarias gostosas; porque, como imagina em sua alma, assim ele é; ele te diz: Come e bebe; porém o seu coração não está contigo." Esse versículo fala sobre como as intenções de alguém podem ser reveladas por seus olhos e como devemos ter cuidado ao aceitar a comida ou bebida de pessoas com más intenções.
* 1 João 2:9-10: "Aquele que diz que está na luz, e odeia a seu irmão, até agora está em trevas. Aquele que ama a seu irmão está na luz, e nele não há escândalo." João enfatiza a importância do amor e da unidade entre os irmãos da igreja, em contraste com o comportamento odioso de Diótrefes.
* 1 Coríntios 4:6: "E estas coisas, irmãos, eu as apliquei em figura a mim e a Apolo, por amor de vós; para que em nós aprendais a não ir além do que está escrito, não vos ensoberbecendo a favor de um contra outro." Esse versículo fala sobre a importância de não se exceder ou ser orgulhoso, mas sim seguir as Escrituras e manter a humildade, algo que Diótrefes falhou em fazer.
* 1 Timóteo 5:24-25: "Os pecados de alguns homens são manifestos antes de entrarem em juízo, mas em alguns, só depois. Da mesma maneira, as boas obras são manifestas antecipadamente, e as que não o são não podem ficar escondidas para sempre." João elogia a reputação de Demétrio e destaca como as boas obras de alguém podem ser evidentes para todos.
* Tiago 5:9: "Irmãos, não vos queixeis uns dos outros, para que não sejais julgados. Eis que o juiz está à porta." João aconselha seus leitores a não se queixarem uns dos outros, mas a manterem a paz e a unidade na igreja, algo que Gaio parece ter feito bem ao receber os irmãos com amor.
****

[[v71-1-1]]

^<<v71-1-1,1>>^ O ancião ao caríssimo Gaio, a quem amo na verdade.

[[v71-1-2]]

^<<v71-1-2,2>>^ Caríssimo, desejo que prosperes em todos os teus empreendimentos, que estejas bem e igualmente que tua alma prospere.

[[v71-1-3]]

^<<v71-1-3,3>>^ Alegrei-me muito com a vinda dos irmãos e com o testemunho que deram da tua verdade, de como andas na verdade.

[[v71-1-4]]

^<<v71-1-4,4>>^ Não tenho maior alegria do que ouvir dizer que os meus filhos caminham na verdade.

[[v71-1-5]]

^<<v71-1-5,5>>^ Caríssimo, fazes obras de fé em tudo o que realizas para os teus irmãos, mesmo para os irmãos estrangeiros.

[[v71-1-6]]

^<<v71-1-6,6>>^ Estes, perante a comunidade, deram testemunho do teu amor. Farás bem em provê-los para a sua viagem, de um modo digno de Deus.

[[v71-1-7]]

^<<v71-1-7,7>>^ Pois por amor do seu nome partiram, sem nada receber dos pagãos.

[[v71-1-8]]

^<<v71-1-8,8>>^ Devemos, portanto, receber a tais homens, para cooperar com eles pela verdade.

[[v71-1-9]]

^<<v71-1-9,9>>^ Escrevi uma palavra à Igreja. Mas Diótrefes, homem ambicioso do poder, não nos quer receber.

[[v71-1-10]]

^<<v71-1-10,10>>^ Por isso, quando eu for aí, hei de recordar as obras que ele pratica, espalhando contra nós coisas más. Não contente com isso, ele não só recusa receber os irmãos, como até proíbe recebê-los aos que o quereriam fazer, e os exclui da comunidade.

[[v71-1-11]]

^<<v71-1-11,11>>^ Caríssimo, não imites o mal, mas sim o bem. Quem pratica o bem nasceu de Deus. Quem pratica o mal não viu a Deus.

[[v71-1-12]]

^<<v71-1-12,12>>^ A respeito de Demétrio, todos e a mesma verdade dão testemunho, e nós também lhe damos testemunho; e tu sabes que o nosso testemunho é verdadeiro.

[[v71-1-13]]

^<<v71-1-13,13>>^ Tinha muitas coisas para te escrever, mas não quero fazê-lo com tinta e pena.

[[v71-1-14]]

^<<v71-1-14,14>>^ Espero ir ver-te em breve e então falaremos de viva voz.

[[v71-1-15]]

^<<v71-1-15,15>>^ A paz esteja contigo! Os amigos te saúdam. Saúda os amigos cada um em particular!

'''

xref:070-ii-sao-joao/070-ii-sao-joao-001.adoc#v70-1-0[&#60; Capítulo Anterior] | <<v71-1-0,Topo>> | xref:072-sao-judas/072-sao-judas-001.adoc#v72-1-0[Próximo Capítulo &#62;]