include::./index.adoc[]

[[v52-1-0]]
=== Romanos, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Romanos 1 começa com uma apresentação de Paulo e sua mensagem para a igreja em Roma. Ele enfatiza a justiça de Deus e a necessidade de todos os homens se arrependerem e crerem no evangelho. A seguir estão cinco versículos relacionados com os temas abordados em Romanos 1:
* João 3:36: "Aquele que crê no Filho tem a vida eterna; mas aquele que não crê no Filho não verá a vida, mas a ira de Deus sobre ele permanece." Este versículo enfatiza a necessidade de crer no Filho de Deus, Jesus Cristo, e a consequência para aqueles que não creem.
* Romanos 3:23: "Porque todos pecaram e destituídos estão da glória de Deus." Esse versículo ressalta a condição de todos os seres humanos, que são pecadores e não podem alcançar a glória de Deus por seus próprios méritos.
* Romanos 5:8: "Mas Deus prova o seu próprio amor para conosco, pelo fato de ter Cristo morrido por nós, sendo nós ainda pecadores." Este versículo destaca a grande prova de amor de Deus ao enviar seu Filho para morrer por nós, mesmo quando éramos pecadores.
* Romanos 6:23: "Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus nosso Senhor." Esse versículo ensina que o pecado leva à morte, mas Deus oferece o dom gratuito da vida eterna através de Jesus Cristo.
* Efésios 2:8-9: "Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus; não vem das obras, para que ninguém se glorie." Esse versículo enfatiza que a salvação é pela graça de Deus, através da fé em Jesus Cristo, e não pelas obras do homem.
****

[[v52-1-1]]

^<<v52-1-1,1>>^ Paulo, servo de Jesus Cristo, escolhido para ser apóstolo, reservado para anunciar o Evangelho de Deus;^&#42;1^ –

[[v52-1-2]]

^<<v52-1-2,2>>^ este Evangelho Deus prometera outrora pelos seus profetas na Sagrada Escritura,

[[v52-1-3]]

^<<v52-1-3,3>>^ acerca de seu Filho Jesus Cristo, nosso Senhor, descendente de Davi quanto à carne,^&#42;1^

[[v52-1-4]]

^<<v52-1-4,4>>^ que, segundo o Espírito de santidade, foi estabelecido Filho de Deus no poder por sua ressurreição dos mortos;

[[v52-1-5]]

^<<v52-1-5,5>>^ e do qual temos recebido a graça e o apostolado, a fim de levar, em seu nome, todas as nações pagãs à obediência da fé,

[[v52-1-6]]

^<<v52-1-6,6>>^ entre as quais também vós sois os eleitos de Jesus Cristo –,

[[v52-1-7]]

^<<v52-1-7,7>>^ a todos os que estão em Roma, queridos de Deus, chamados a serem santos: a vós, graça e paz da parte de Deus, nosso Pai, e da parte do Senhor Jesus Cristo!

[[v52-1-8]]

^<<v52-1-8,8>>^ Primeiramente, dou graças a meu Deus, por meio de Jesus Cristo, por todos vós, porque em todo o mundo é preconizada a vossa fé.

[[v52-1-9]]

^<<v52-1-9,9>>^ Pois Deus, a quem sirvo em meu espírito, anunciando o Evangelho de seu Filho, me é testemunha de como vos menciono incessantemente em minhas orações.

[[v52-1-10]]

^<<v52-1-10,10>>^ A ele suplico, se for de sua vontade, conceder-me finalmente ocasião favorável de vos visitar.

[[v52-1-11]]

^<<v52-1-11,11>>^ Desejo ardentemente ver-vos, a fim de comunicar-vos alguma graça espiritual, com que sejais confirmados,

[[v52-1-12]]

^<<v52-1-12,12>>^ ou melhor, para me encorajar juntamente convosco naquela vossa e minha fé que nos é comum.

[[v52-1-13]]

^<<v52-1-13,13>>^ Pois não quero que ignoreis, irmãos, como muitas vezes me tenho proposto ir ter convosco. (Eu queria recolher algum fruto entre vós, como entre os outros pagãos), mas até agora tenho sido impedido.

[[v52-1-14]]

^<<v52-1-14,14>>^ Sou devedor a gregos e a bárbaros, a sábios e a simples.^&#42;1^

[[v52-1-15]]

^<<v52-1-15,15>>^ Daí o ardente desejo que eu sinto de vos anunciar o Evangelho também a vós, que habitais em Roma.

[[v52-1-16]]

^<<v52-1-16,16>>^ Com efeito, não me envergonho do Evangelho, pois ele é uma força vinda de Deus para a salvação de todo o que crê, ao judeu em primeiro lugar e depois ao grego.

[[v52-1-17]]

^<<v52-1-17,17>>^ Porque nele se revela a justiça de Deus, que se obtém pela fé e conduz à fé, como está escrito: O justo viverá pela fé (Hab 2,4).

[[v52-1-18]]

^<<v52-1-18,18>>^ A ira de Deus se manifesta do alto do céu contra toda a impiedade e perversidade dos homens, que pela injustiça aprisionam a verdade.

[[v52-1-19]]

^<<v52-1-19,19>>^ Porquanto o que se pode conhecer de Deus eles o leem em si mesmos, pois Deus lhes revelou com evidência.

[[v52-1-20]]

^<<v52-1-20,20>>^ Desde a criação do mundo, as perfeições invisíveis de Deus, o seu sempiterno poder e divindade, se tornam visíveis à inteligência, por suas obras; de modo que não se podem escusar.

[[v52-1-21]]

^<<v52-1-21,21>>^ Porque, conhecendo a Deus, não o glorificaram como Deus, nem lhe deram graças. Pelo contrário, extraviaram-se em seus vãos pensamentos, e se lhes obscureceu o coração insensato.

[[v52-1-22]]

^<<v52-1-22,22>>^ Pretendendo-se sábios, tornaram-se estultos.

[[v52-1-23]]

^<<v52-1-23,23>>^ Mudaram a majestade de Deus incorruptível em representações e figuras de homem corruptível, de aves, quadrúpedes e répteis.

[[v52-1-24]]

^<<v52-1-24,24>>^ Por isso, Deus os entregou aos desejos dos seus corações, à imundície, de modo que desonraram entre si os próprios corpos.^&#42;1^

[[v52-1-25]]

^<<v52-1-25,25>>^ Trocaram a verdade de Deus pela mentira, e adoraram e serviram à criatura em vez do Criador, que é bendito pelos séculos. Amém!

[[v52-1-26]]

^<<v52-1-26,26>>^ Por isso, Deus os entregou a paixões vergonhosas: as suas mulheres mudaram as relações naturais em relações contra a natureza.

[[v52-1-27]]

^<<v52-1-27,27>>^ Do mesmo modo também os homens, deixando o uso natural da mulher, arderam em desejos uns para com os outros, cometendo homens com homens a torpeza, e recebendo em seus corpos a paga devida ao seu desvario.

[[v52-1-28]]

^<<v52-1-28,28>>^ Como não se preocupassem em adquirir o conhecimento de Deus, Deus entregou-os aos sentimentos depravados, e daí o seu procedimento indigno.

[[v52-1-29]]

^<<v52-1-29,29>>^ São repletos de toda espécie de malícia, perversidade, cobiça, maldade; cheios de inveja, homicídio, contenda, engano, malignidade.

[[v52-1-30]]

^<<v52-1-30,30>>^ São difamadores, caluniadores, inimigos de Deus, insolentes, soberbos, altivos, inventores de maldades, rebeldes contra os pais.

[[v52-1-31]]

^<<v52-1-31,31>>^ São insensatos, desleais, sem coração, sem misericórdia.

[[v52-1-32]]

^<<v52-1-32,32>>^ Apesar de conhecerem o justo decreto de Deus que considera dignos de morte aqueles que fazem tais coisas, não somente as praticam, como também aplaudem os que as cometem.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-028.adoc#v51-28-0[&#60; Capítulo Anterior] | <<v52-1-0,Topo>> | xref:052-romanos/052-romanos-002.adoc#v52-2-0[Próximo Capítulo &#62;]