include::./index.adoc[]

[[v52-16-0]]
=== Romanos, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Romanos 16 é o último capítulo da Epístola aos Romanos e apresenta uma série de saudações e recomendações pessoais do apóstolo Paulo. Dentre os temas abordados nesse capítulo, podemos destacar a importância da comunidade cristã, do trabalho em equipe e da valorização do serviço prestado pelos irmãos na fé. Seguem abaixo cinco versículos relacionados com esses temas:
* 1 Coríntios 12:12 - "Porque, assim como o corpo é um e tem muitos membros, e todos os membros, sendo muitos, são um só corpo, assim é Cristo também." Esse versículo faz uma analogia entre o corpo humano e a comunidade cristã, mostrando que cada membro tem uma função importante e que todos juntos formam um só corpo.
* Filipenses 2:2-3 - "Completai a minha alegria, para que sintais o mesmo, tendo o mesmo amor, o mesmo ânimo, sentindo uma mesma coisa. Nada façais por contenda ou por vanglória, mas por humildade; cada um considere os outros superiores a si mesmo." Nesses versículos, Paulo exorta os filipenses a cultivarem a união e a humildade, valorizando os outros irmãos em Cristo.
* 1 Tessalonicenses 5:11 - "Por isso, exortai-vos uns aos outros e edificai-vos uns aos outros, como também o fazeis." Aqui, Paulo ressalta a importância do encorajamento mútuo e da edificação na fé.
* Hebreus 10:24-25 - "E consideremo-nos uns aos outros, para nos estimularmos ao amor e às boas obras, não deixando de congregar-nos, como é costume de alguns; antes, façamos admoestações e tanto mais quanto vedes que o Dia se aproxima." Esse versículo enfatiza a importância da comunhão e do estímulo mútuo para a prática do amor e das boas obras.
* 1 Coríntios 3:8 - "O que planta e o que rega são um; mas cada um receberá o seu galardão segundo o seu trabalho." Aqui, Paulo destaca a importância do trabalho em equipe e da valorização do serviço prestado por cada irmão na comunidade cristã.
****

[[v52-16-1]]

^<<v52-16-1,1>>^ Recomendo-vos a nossa irmã Febe, que é diaconisa da igreja de Cêncris,^&#42;1^

[[v52-16-2]]

^<<v52-16-2,2>>^ para que a recebais no Senhor, de um modo digno dos santos, e a ajudeis em qualquer coisa que de vós venha a precisar; porque ela tem ajudado a muitos e também a mim.

[[v52-16-3]]

^<<v52-16-3,3>>^ Saudai Prisca e Áquila, meus cooperadores em Cristo Jesus;

[[v52-16-4]]

^<<v52-16-4,4>>^ pela minha vida eles expuseram as suas cabeças. E isso lhes agradeço, não só eu, mas também todas as igrejas dos gentios.

[[v52-16-5]]

^<<v52-16-5,5>>^ Saudai também a comunidade que se reúne em sua casa.^&#42;1^ Saudai o meu querido Epêneto, que foi as primícias da Ásia para Cristo.

[[v52-16-6]]

^<<v52-16-6,6>>^ Saudai Maria, que muito trabalhou por vós.

[[v52-16-7]]

^<<v52-16-7,7>>^ Saudai Andrônico e Júnias, meus parentes e companheiros de prisão, os quais são muito estimados entre os apóstolos e se tornaram discípulos de Cristo antes de mim.^&#42;1^

[[v52-16-8]]

^<<v52-16-8,8>>^ Saudai Ampliato, amicíssimo meu no Senhor.

[[v52-16-9]]

^<<v52-16-9,9>>^ Saudai Urbano, nosso colaborador em Cristo Jesus, e o meu amigo Estáquis.

[[v52-16-10]]

^<<v52-16-10,10>>^ Saudai Apeles, provado em Cristo. Saudai aqueles que são da casa de Aristóbulo.

[[v52-16-11]]

^<<v52-16-11,11>>^ Saudai Herodião, meu parente. Saudai os que são da família de Narciso, que estão no Senhor.

[[v52-16-12]]

^<<v52-16-12,12>>^ Saudai Trifena e Trifosa, que trabalham para o Senhor. Saudai a estimada Pérside, que muito trabalhou para o Senhor.

[[v52-16-13]]

^<<v52-16-13,13>>^ Saudai Rufo, escolhido no Senhor, e sua mãe, que considero como minha.^&#42;1^

[[v52-16-14]]

^<<v52-16-14,14>>^ Saudai Asíncrito, Flegonte, Hermes, Pátrobas, Hermas e os irmãos que estão com eles.

[[v52-16-15]]

^<<v52-16-15,15>>^ Saudai Filólogo e Júlia, Nereu e sua irmã, Olímpio e todos os irmãos que estão com eles.

[[v52-16-16]]

^<<v52-16-16,16>>^ Saudai-vos uns aos outros com ósculo santo. Todas as igrejas de Cristo vos saúdam.

[[v52-16-17]]

^<<v52-16-17,17>>^ Rogo-vos, irmãos, que desconfieis daqueles que causam divisões e escândalos, apartando-se da doutrina que recebestes. Evitai-os!

[[v52-16-18]]

^<<v52-16-18,18>>^ Esses tais não servem a Cristo, nosso Senhor, mas ao próprio ventre. E com palavras adocicadas e linguagem lisonjeira, enganam os corações simples.

[[v52-16-19]]

^<<v52-16-19,19>>^ A vossa obediência se tornou notória em toda parte, razão por que eu me alegro a vosso respeito. Mas quero que sejais prudentes no tocante ao bem, e simples no tocante ao mal.

[[v52-16-20]]

^<<v52-16-20,20>>^ O Deus da paz em breve não tardará a esmagar Satanás debaixo dos vossos pés. A graça de nosso Senhor Jesus Cristo esteja convosco!

[[v52-16-21]]

^<<v52-16-21,21>>^ Saúdam-vos Timóteo, meu cooperador, Lúcio, Jasão e Sosípatro, meus parentes.

[[v52-16-22]]

^<<v52-16-22,22>>^ Eu, Tércio, que escrevi esta carta, vos saúdo no Senhor.

[[v52-16-23]]

^<<v52-16-23,23>>^ Saúda-vos Gaio, meu hospedeiro, e de toda a Igreja.

[[v52-16-24]]

^<<v52-16-24,24>>^ Saúda-vos Erasto, tesoureiro da cidade, e Quarto, nosso irmão.

[[v52-16-25]]

^<<v52-16-25,25>>^ Àquele que é poderoso para vos confirmar, segundo o meu Evangelho, na pregação de Jesus Cristo – conforme a revelação do mistério, guardado em segredo durante séculos,

[[v52-16-26]]

^<<v52-16-26,26>>^ mas agora manifestado por ordem do eterno Deus e, por meio das Escrituras proféticas, dado a conhecer a todas as nações, a fim de levá-las à obediência da fé –,

[[v52-16-27]]

^<<v52-16-27,27>>^ a Deus, único, sábio, por Jesus Cristo, glória por toda a eternidade! Amém.

'''

xref:052-romanos/052-romanos-015.adoc#v52-15-0[&#60; Capítulo Anterior] | <<v52-16-0,Topo>> | xref:053-i-corintios/053-i-corintios-001.adoc#v53-1-0[Próximo Capítulo &#62;]