include::./index.adoc[]

[[v52-4-0]]
=== Romanos, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Romanos 4 trata da justificação pela fé e como a justiça de Deus é imputada àqueles que creem em Jesus Cristo. O capítulo destaca a fé de Abraão como um exemplo de justificação pela fé e explica que a justificação não é alcançada por obras, mas sim pela graça de Deus através da fé em Jesus Cristo.
* Gálatas 3:6 - "Assim como Abraão creu em Deus, e isso lhe foi imputado como justiça." Este verso se relaciona diretamente com Romanos 4, onde Abraão é destacado como um exemplo de justificação pela fé. Assim como Abraão, os crentes em Jesus Cristo são justificados pela fé em Deus.
* Efésios 2:8-9 - "Pois vocês são salvos pela graça, por meio da fé, e isso não vem de vocês, é dom de Deus; não por obras, para que ninguém se glorie." Este verso destaca que a salvação é pela graça de Deus e pela fé em Jesus Cristo, não por obras. Isso está em consonância com o que é ensinado em Romanos 4.
* Filipenses 3:9 - "e ser encontrado nele, não tendo a minha própria justiça que procede da Lei, mas a que vem mediante a fé em Cristo, a justiça que procede de Deus e se baseia na fé." Este verso destaca que a justiça que procede de Deus é alcançada através da fé em Jesus Cristo e não por obras da lei. Novamente, isso está em conformidade com o que é ensinado em Romanos 4.
* Hebreus 11:1 - "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos." Este verso destaca a importância da fé em Deus e como a fé é uma parte essencial da justificação pela fé. Isso está em consonância com o que é ensinado em Romanos 4.
* Tiago 2:24 - "Vocês veem que uma pessoa é justificada pelas obras e não somente pela fé." Este verso pode parecer contrário ao que é ensinado em Romanos 4, mas na verdade é complementar. Tiago está destacando que a fé verdadeira sempre produz obras, e que a justificação pela fé é uma justificação viva, que se manifesta em obras. Isso está em harmonia com o que é ensinado em Romanos 4, onde Abraão é um exemplo de fé viva que produz obras.
****

[[v52-4-1]]

^<<v52-4-1,1>>^ Que vantagem diremos, pois, que conseguiu Abraão, nosso pai segundo a carne?

[[v52-4-2]]

^<<v52-4-2,2>>^ Porque, se Abraão foi justificado em virtude de sua observância, tem de que se gloriar; mas não diante de Deus.

[[v52-4-3]]

^<<v52-4-3,3>>^ Ora, que diz a Escritura? Abraão creu em Deus e isso lhe foi imputado em conta de justiça (Gn 15,6).

[[v52-4-4]]

^<<v52-4-4,4>>^ Ora, o salário não é gratificação, mas uma dívida ao trabalhador.

[[v52-4-5]]

^<<v52-4-5,5>>^ Mas aquele que sem obra alguma crê naquele que justifica o ímpio, a sua fé lhe é imputada em conta de justiça.

[[v52-4-6]]

^<<v52-4-6,6>>^ É assim que Davi proclama bem-aventurado o homem a quem Deus atribui justiça, independentemente das obras:

[[v52-4-7]]

^<<v52-4-7,7>>^ Bem-aventurados aqueles cujas iniquidades foram perdoadas e cujos pecados foram cobertos!

[[v52-4-8]]

^<<v52-4-8,8>>^ Bem-aventurado o homem ao qual o Senhor não imputou o seu pecado (Sl 31,1s).

[[v52-4-9]]

^<<v52-4-9,9>>^ Essa bem-aventurança é somente para os circuncisos, ou também para os incircuncisos? Dizemos, com efeito, que a fé foi imputada a Abraão em conta de justiça.

[[v52-4-10]]

^<<v52-4-10,10>>^ Quando lhe foi ela imputada? Depois ou antes de sua circuncisão? Não depois, mas antes de ser circuncidado.

[[v52-4-11]]

^<<v52-4-11,11>>^ Depois é que recebeu o sinal da circuncisão, como selo da justiça que tinha obtido pela fé antes de ser circuncidado. E assim se tornou o pai de todos os incircuncisos que creem, a fim de que também a estes seja imputada a justiça.^&#42;1^

[[v52-4-12]]

^<<v52-4-12,12>>^ Pai também dos circuncisos, que não só trazem o sinal, mas que acompanham as pegadas da fé que nosso pai Abraão possuía antes de ser circuncidado.

[[v52-4-13]]

^<<v52-4-13,13>>^ Com efeito, não foi em virtude da Lei que a promessa de herdar o mundo foi feita a Abraão ou à sua posteridade, mas em virtude da justiça da fé.

[[v52-4-14]]

^<<v52-4-14,14>>^ Porque, se a herança é reservada aos observadores da Lei, a fé já não tem razão de ser e a promessa fica sem valor.

[[v52-4-15]]

^<<v52-4-15,15>>^ Porquanto a Lei produz a ira; e onde não existe Lei, não há transgressão.^&#42;1^

[[v52-4-16]]

^<<v52-4-16,16>>^ Logo, é pela fé que alguém se torna herdeiro. Portanto, gratuitamente; e a promessa é assegurada a toda a posteridade de Abraão, não somente aos que procedem da Lei, mas também aos que possuem a fé de Abraão, que é pai de todos nós.

[[v52-4-17]]

^<<v52-4-17,17>>^ Em verdade, está escrito: Eu te constituí pai de muitas nações (Gn 17,5); (nosso pai, portanto) diante dos olhos daquele em quem acreditou, o Deus que dá vida aos mortos e chama à existência as coisas que estão no nada.^&#42;1^

[[v52-4-18]]

^<<v52-4-18,18>>^ Esperando, contra toda a esperança, Abraão teve fé e se tornou pai de muitas nações, segundo o que lhe fora dito: Assim será a tua descendência (Gn 15,5).^&#42;1^

[[v52-4-19]]

^<<v52-4-19,19>>^ Não vacilou na fé, embora reconhecendo o seu próprio corpo sem vigor – pois tinha quase cem anos – e o seio de Sara igualmente amortecido.

[[v52-4-20]]

^<<v52-4-20,20>>^ Ante a promessa de Deus, não vacilou, não desconfiou, mas conservou-se forte na fé e deu glória a Deus.

[[v52-4-21]]

^<<v52-4-21,21>>^ Estava plenamente convencido de que Deus era poderoso para cumprir o que prometera.

[[v52-4-22]]

^<<v52-4-22,22>>^ Eis por que sua fé lhe foi contada como justiça.

[[v52-4-23]]

^<<v52-4-23,23>>^ Ora, não é só para ele que está escrito que a fé lhe foi imputada em conta de justiça.

[[v52-4-24]]

^<<v52-4-24,24>>^ É também para nós, pois a nossa fé deve ser-nos imputada igualmente, porque cremos naquele que dos mortos ressuscitou Jesus, nosso Senhor,

[[v52-4-25]]

^<<v52-4-25,25>>^ o qual foi entregue por nossos pecados e ressuscitado para a nossa justificação.

'''

xref:052-romanos/052-romanos-003.adoc#v52-3-0[&#60; Capítulo Anterior] | <<v52-4-0,Topo>> | xref:052-romanos/052-romanos-005.adoc#v52-5-0[Próximo Capítulo &#62;]