include::./index.adoc[]

[[v52-11-0]]
=== Romanos, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Romanos 11 trata principalmente sobre a relação entre os judeus e os gentios na fé cristã, enfatizando a soberania de Deus e a sua escolha e chamado para o povo de Israel. Além disso, o capítulo destaca a importância da fé em Cristo e da sua obra redentora para a salvação de todas as pessoas, tanto judeus quanto gentios.
* Isaías 59:20: "Virá o Redentor a Sião e aos que em Jacó se converterem, diz o Senhor." Esse versículo é citado em Romanos 11:26 para enfatizar a promessa de Deus de salvar o seu povo escolhido, incluindo judeus e gentios que creem em Jesus como o Messias e Salvador.
* Salmos 94:14: "Porque o Senhor não desamparará o seu povo, nem desamparará a sua herança." Esse verso destaca a fidelidade de Deus em relação ao seu povo e sua aliança, mesmo quando eles falham. Isso é relevante para o tema de Romanos 11, que destaca a escolha e o chamado de Deus para o povo de Israel, apesar de sua desobediência e incredulidade.
* Deuteronômio 32:21: "Irei, pois, provocá-los a zelos não povo, e a uma nação louca irei provocá-los." Esse versículo é citado em Romanos 10:19 para ilustrar como Deus estendeu a salvação também aos gentios, provocando a inveja e o ciúme dos judeus. Isso é relevante para o tema de Romanos 11, que destaca como Deus tem um propósito maior em estender a salvação a todas as pessoas, incluindo judeus e gentios.
* Salmos 69:22-23: "Torne-se-lhes a sua mesa diante deles em laço, e a sua prosperidade em armadilha. Escureçam-se-lhes os olhos para que não vejam, e faze-lhes tremer os lombos incessantemente." Esse verso é citado em Romanos 11:9-10 para enfatizar o julgamento de Deus sobre os que o rejeitam, incluindo judeus e gentios que não creem em Jesus. Isso destaca a importância da fé em Cristo para a salvação.
* Salmos 117:1: "Louvai ao Senhor, todas as nações, louvai-o, todos os povos." Esse verso destaca a extensão da salvação de Deus a todas as pessoas, independentemente da sua origem ou raça. Isso é relevante para o tema de Romanos 11, que destaca a soberania de Deus e sua escolha de salvar tanto judeus quanto gentios, e a importância da fé em Cristo para a salvação.
****

[[v52-11-1]]

^<<v52-11-1,1>>^ Pergunto, então: Acaso rejeitou Deus o seu povo? De maneira alguma. Pois eu mesmo sou israelita, descendente de Abraão, da tribo de Benjamim.

[[v52-11-2]]

^<<v52-11-2,2>>^ Deus não repeliu o seu povo, que ele de antemão distinguiu! Desconheceis o que narra a Escritura, no episódio de Elias, quando este se queixava de Israel a Deus:

[[v52-11-3]]

^<<v52-11-3,3>>^ Senhor, mataram vossos profetas, destruíram vossos altares. Fiquei apenas eu, e ainda procuram tirar-me a vida (1Rs 19,10)?

[[v52-11-4]]

^<<v52-11-4,4>>^ Que lhe respondeu a voz divina? Reservei para mim sete mil homens, que não dobraram o joelho diante de Baal (1Rs 19,18).

[[v52-11-5]]

^<<v52-11-5,5>>^ É o que continua a acontecer no tempo presente: subsiste um resto, segundo a eleição da graça.

[[v52-11-6]]

^<<v52-11-6,6>>^ E se é pela graça, já não o é pelas obras; de outra maneira, a graça cessaria de ser graça.

[[v52-11-7]]

^<<v52-11-7,7>>^ Consequência? Que Israel não conseguiu o que procura. Os escolhidos, estes sim, o conseguiram. Quanto aos mais, foram obcecados,

[[v52-11-8]]

^<<v52-11-8,8>>^ como está escrito: Deus lhes deu um espírito de torpor, olhos para que não vejam e ouvidos para que não ouçam, até o dia presente (Dt 29,4).

[[v52-11-9]]

^<<v52-11-9,9>>^ Davi também o diz: A mesa se lhes torne em laço, em armadilha, em ocasião de tropeço, em justo castigo!

[[v52-11-10]]

^<<v52-11-10,10>>^ A vista se lhes obscureça para não verem! Dobra-lhes o espinhaço sem cessar (Sl 68,23s)!

[[v52-11-11]]

^<<v52-11-11,11>>^ Pergunto ainda: Tropeçaram acaso para cair? De modo algum. Mas sua queda, tornando a salvação acessível aos pagãos, incitou-os à emulação.

[[v52-11-12]]

^<<v52-11-12,12>>^ Ora, se o seu pecado ocasionou a riqueza do mundo, e a sua decadência a riqueza dos pagãos, que não fará a sua conversão em massa?!

[[v52-11-13]]

^<<v52-11-13,13>>^ Declaro-o a vós, homens de origem pagã: como apóstolo dos pagãos, eu procuro honrar o meu ministério,

[[v52-11-14]]

^<<v52-11-14,14>>^ com o intuito de, eventualmente, excitar à emulação os homens da minha raça e salvar alguns deles.^&#42;1^

[[v52-11-15]]

^<<v52-11-15,15>>^ Porque, se de sua rejeição resultou a reconciliação do mundo, qual será o efeito de sua reintegração, senão uma ressurreição dentre os mortos?

[[v52-11-16]]

^<<v52-11-16,16>>^ Se as primícias são santas, também a massa o é; e se a raiz é santa, os ramos também o são.

[[v52-11-17]]

^<<v52-11-17,17>>^ Se alguns dos ramos foram cortados, e se tu, oliveira selvagem, foste enxertada em seu lugar e agora recebes seiva da raiz da oliveira,^&#42;1^

[[v52-11-18]]

^<<v52-11-18,18>>^ não te envaideças nem menosprezes os ramos. Pois, se te gloriares, sabe que não és tu que sustentas a raiz, mas a raiz a ti.

[[v52-11-19]]

^<<v52-11-19,19>>^ Dirás, talvez: “Os ramos foram cortados para que eu fosse enxertada”.

[[v52-11-20]]

^<<v52-11-20,20>>^ Sem dúvida! É pela incredulidade que foram cortados, ao passo que tu é pela fé que estás firme. Não te ensoberbeças, antes, teme.

[[v52-11-21]]

^<<v52-11-21,21>>^ Se Deus não poupou os ramos naturais, bem poderá não poupar a ti.

[[v52-11-22]]

^<<v52-11-22,22>>^ Considera, pois, a bondade e a severidade de Deus: severidade para com aqueles que caíram, bondade para contigo, suposto que permaneças fiel a essa bondade; do contrário, também tu serás cortada.

[[v52-11-23]]

^<<v52-11-23,23>>^ E eles, se não persistirem na incredulidade, serão enxertados; pois Deus é poderoso para enxertá-los de novo.

[[v52-11-24]]

^<<v52-11-24,24>>^ Se tu, cortada da oliveira de natureza selvagem, contra a tua natureza foste enxertada em boa oliveira, quanto mais eles, que são naturais, poderão ser enxertados na sua própria oliveira!

[[v52-11-25]]

^<<v52-11-25,25>>^ Não quero, irmãos, que ignoreis este mistério, para que não vos gabeis de vossa sabedoria: esta cegueira de uma parte de Israel só durará até que haja entrado a totalidade dos pagãos.

[[v52-11-26]]

^<<v52-11-26,26>>^ Então, Israel em peso será salvo, como está escrito: Virá de Sião o libertador, apartará de Jacó a impiedade.

[[v52-11-27]]

^<<v52-11-27,27>>^ E esta será a minha aliança com eles, quando eu tirar os seus pecados (Is 59,20s; 27,9).

[[v52-11-28]]

^<<v52-11-28,28>>^ Se, quanto ao Evangelho, eles são inimigos de Deus, para proveito vosso, quanto à eleição eles são muito queridos por causa de seus pais.^&#42;1^

[[v52-11-29]]

^<<v52-11-29,29>>^ Pois os dons e o chamado de Deus são irrevogáveis.

[[v52-11-30]]

^<<v52-11-30,30>>^ Assim como vós antes fostes desobedientes a Deus, e agora obtivestes misericórdia com a desobediência deles,

[[v52-11-31]]

^<<v52-11-31,31>>^ assim eles são incrédulos agora, em consequência da misericórdia feita a vós, para que eles também mais tarde alcancem, por sua vez, a misericórdia.

[[v52-11-32]]

^<<v52-11-32,32>>^ Deus encerrou a todos esses homens na desobediência para usar com todos de misericórdia.

[[v52-11-33]]

^<<v52-11-33,33>>^ Ó abismo de riqueza, de sabedoria e de ciência em Deus! Quão impenetráveis são os seus juízos e inexploráveis os seus caminhos!

[[v52-11-34]]

^<<v52-11-34,34>>^ Quem pode compreender o pensamento do Senhor? Quem jamais foi o seu conselheiro?^&#42;1^

[[v52-11-35]]

^<<v52-11-35,35>>^ Quem lhe deu primeiro, para que lhe seja retribuído?^&#42;1^

[[v52-11-36]]

^<<v52-11-36,36>>^ Dele, por ele e para ele são todas as coisas. A ele a glória por toda a eternidade! Amém.

'''

xref:052-romanos/052-romanos-010.adoc#v52-10-0[&#60; Capítulo Anterior] | <<v52-11-0,Topo>> | xref:052-romanos/052-romanos-012.adoc#v52-12-0[Próximo Capítulo &#62;]