include::./index.adoc[]

[[v15-3-0]]
=== Esdras, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Esdras 3 descreve a reconstrução do altar e a celebração da Festa dos Tabernáculos pelos judeus recém-chegados a Jerusalém. O capítulo também menciona o início da construção do templo e a alegria dos sacerdotes e levitas diante desse projeto.
* Salmos 100:4: "Entrai pelas portas dele com gratidão, e em seus átrios com louvor; louvai-o, e bendizei o seu nome." Este versículo incentiva os crentes a entrar no templo de Deus com gratidão e louvor, como os judeus fizeram durante a celebração da Festa dos Tabernáculos.
* Esdras 6:16: "E os filhos de Israel, os sacerdotes e os levitas, e o restante dos filhos da cativeira, fizeram a dedicação desta casa de Deus com alegria." Esse versículo descreve a dedicação do templo reconstruído em Jerusalém, que foi um momento de grande alegria para os judeus.
* Esdras 6:22: "E celebraram a festa dos pães asmos por sete dias com alegria; porque o SENHOR os alegrara, e tinha mudado o coração do rei da Assíria para com eles, a fim de fortalecê-los na obra da casa de Deus, o Deus de Israel." Este versículo descreve como os judeus celebraram a Festa dos Pães Asmos depois de completarem a construção do templo em Jerusalém.
* 1 Crônicas 16:34: "Louvai ao SENHOR, porque ele é bom; porque a sua benignidade dura para sempre." Este versículo é um convite para louvar a bondade de Deus, o que é relevante para a celebração da Festa dos Tabernáculos em Esdras 3.
* Ageu 2:9: "A glória desta última casa será maior do que a da primeira, diz o SENHOR dos Exércitos, e neste lugar darei a paz, diz o SENHOR dos Exércitos." Esse versículo é uma profecia que aponta para a glória do templo reconstruído e é relevante para a emoção sentida pelos judeus durante a construção do templo em Esdras 3.
****

[[v15-3-1]]

^<<v15-3-1,1>>^ Tendo chegado o sétimo mês e estando os filhos de Israel instalados em suas cidades, todo o povo se reuniu como um só homem em Jerusalém.

[[v15-3-2]]

^<<v15-3-2,2>>^ Então, Josué, filho de Josedec e seus irmãos sacerdotes, bem como Zorobabel, filho de Salatiel, e seus irmãos principiaram a reconstrução do altar do Deus de Israel e ofereceram holocaustos, como a Lei de Moisés, homem de Deus, prescrevia.

[[v15-3-3]]

^<<v15-3-3,3>>^ Reconstruíram o altar sobre as antigas bases, porque tinham medo dos habitantes vizinhos e ofereceram holocaustos ao Senhor pela manhã e pela tarde.

[[v15-3-4]]

^<<v15-3-4,4>>^ Em seguida, celebraram a festa dos Tabernáculos, como estava prescrito, e, diariamente, ofereciam holocaustos de acordo com o número prescrito para cada dia.

[[v15-3-5]]

^<<v15-3-5,5>>^ Depois disso, ofereceram o holocausto perpétuo, os das neomênias e de todas as solenidades consagradas ao Senhor, assim como os daqueles que faziam uma oferta ao Senhor.

[[v15-3-6]]

^<<v15-3-6,6>>^ No primeiro dia do sétimo mês, começaram a oferecer holocaustos ao Senhor, mas os fundamentos do Templo do Senhor não estavam ainda colocados.

[[v15-3-7]]

^<<v15-3-7,7>>^ Foram então contratados canteiros e carpinteiros; deram aos sidônios e tírios víveres, azeite e vinho para que trouxessem por mar a madeira dos cedros, desde o Líbano até Jope, segundo a autorização que lhes tinha dado Ciro, rei da Pérsia.

[[v15-3-8]]

^<<v15-3-8,8>>^ No segundo ano de sua chegada ao Templo de Deus em Jerusalém, no segundo mês, Zorobabel, filho de Salatiel, e Josué, filho de Josedec, tendo consigo seus irmãos, os sacerdotes. Os levitas e todos os que haviam voltado do cativeiro para Jerusalém, puseram-se a trabalhar. Os levitas de vinte anos para cima foram encarregados da direção dos trabalhos do Templo do Senhor.

[[v15-3-9]]

^<<v15-3-9,9>>^ Josué, com seus filhos e irmãos, Cadmiel, com seus filhos, filhos de Odovias, propuseram-se unanimemente a dirigir os que trabalhavam na construção da casa de Deus. O mesmo fizeram os filhos de Henadad com seus filhos e seus irmãos que eram levitas.

[[v15-3-10]]

^<<v15-3-10,10>>^ Logo que os pedreiros lançaram os fundamentos do Templo do Senhor, apresentaram-se os sacerdotes ornamentados para assistir à cerimônia, com as trombetas e os levitas, filhos de Asaf, com os címbalos, para louvarem o Senhor, segundo as ordens de Davi, rei de Israel.

[[v15-3-11]]

^<<v15-3-11,11>>^ Entoaram ao Senhor este refrão de louvor: “Porque ele é bom e porque sua misericórdia com Israel permanece para sempre!”. E todo o povo soltou aclamações de alegria para celebrar o Senhor, por ocasião do lançamento dos alicerces de sua casa.

[[v15-3-12]]

^<<v15-3-12,12>>^ Mas, enquanto muitos gritavam de alegria e júbilo, muitos sacerdotes, levitas e chefes de família, já idosos, que tinham visto o primeiro templo, choravam em alta voz, enquanto diante deles eram lançados os alicerces do novo edifício.

[[v15-3-13]]

^<<v15-3-13,13>>^ Era impossível distinguir os gritos de alegria dos clamores daqueles que choravam, pois todo o povo gritava em altos brados e o eco de suas vozes se podia ouvir de longe.

'''

xref:015-esdras/015-esdras-002.adoc#v15-2-0[&#60; Capítulo Anterior] | <<v15-3-0,Topo>> | xref:015-esdras/015-esdras-004.adoc#v15-4-0[Próximo Capítulo &#62;]