include::./index.adoc[]

[[v15-9-0]]
=== Esdras, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Esdras 9 é um capítulo que descreve a tristeza e arrependimento de Esdras e do povo de Israel por terem se misturado com outros povos e adotado seus costumes, desobedecendo a Deus. Esdras lidera um período de arrependimento, confissão e renovação de aliança com Deus. A seguir estão cinco versículos relacionados com os temas deste capítulo:
* Deuteronômio 7:3-4: "Não vos aparentareis com eles; não darás tua filha a seu filho, nem tomarás a filha deles para teu filho. Porque ele fará desviar teu filho de mim, para que sirvam a outros deuses; e a ira do SENHOR se acenderá contra vós, e depressa te destruirá." Esdras reconhece que os filhos de Israel haviam desobedecido a essa lei e se misturado com os povos ao seu redor.
* Neemias 9:1-2: "No dia vinte e quatro do mesmo mês se ajuntaram os filhos de Israel em jejum, e com sacos, e traziam terra sobre si. E a semente de Israel se separou de todos os estranhos, e puseram-se em pé, e fizeram confissão dos seus pecados e das iniquidades de seus pais." Esdras e o povo de Israel jejuam e confessam seus pecados e os pecados de seus antepassados.
* Salmo 106:6: "Pecámos como os nossos pais, cometemos iniquidade, andámos mal." Esdras se identifica com o pecado de seus antepassados e assume a responsabilidade pelo pecado do povo.
* Jeremias 31:19: "Porque depois que me desviei, fiz arrependido; e depois que conheci, bati na minha coxa; envergonhado estou e confundido, porque levo a ignomínia da minha mocidade." Esdras e o povo de Israel se arrependem de seus pecados e buscam a Deus.
* Salmos 41:4: "Eu disse: SENHOR, tem piedade de mim; sara a minha alma, porque pequei contra ti." Esdras pede a Deus por misericórdia e cura para o pecado do povo.
****

[[v15-9-1]]

^<<v15-9-1,1>>^ Após todos esses acontecimentos, os chefes aproximaram-se de mim e disseram-me: “O povo de Israel, os sacerdotes e os levitas não se conservaram afastados dos habitantes desta terra. Imitaram as abominações dos cananeus, dos hiteus, dos ferezeus, dos jebuseus, dos amonitas, dos moabitas, dos egípcios e dos amorreus.

[[v15-9-2]]

^<<v15-9-2,2>>^ Tomaram, entre as filhas deles, mulheres para si e para seus filhos. Assim, a raça santa misturou-se com a dos habitantes dessas terras. Os chefes e os magistrados foram os primeiros a dar a mão a essa transgressão”.

[[v15-9-3]]

^<<v15-9-3,3>>^ Ouvindo essas palavras, rasguei minha túnica e a capa, arranquei os cabelos da cabeça e da barba e me sentei consternado.

[[v15-9-4]]

^<<v15-9-4,4>>^ Ao redor de mim reuniram-se todos aqueles que temiam as palavras do Deus de Israel, por causa da transgressão dos filhos do cativeiro. Quanto a mim, fiquei sentado e angustiado até o sacrifício da tarde.

[[v15-9-5]]

^<<v15-9-5,5>>^ Na hora da oblação da tarde, levantei-me de minha aflição com minhas vestes e meu manto rasgados; então, caindo de joelhos, estendi as mãos ao Senhor, meu Deus,

[[v15-9-6]]

^<<v15-9-6,6>>^ e disse: “Meu Deus, estou coberto de vergonha e de confusão para levantar minha face para vós, meu Deus; porque as nossas iniquidades acumularam-se sobre nossas cabeças e nosso pecado chegou até o céu.

[[v15-9-7]]

^<<v15-9-7,7>>^ Desde o tempo de nossos pais até o dia de hoje, temos sido gravemente culpados. Por causa de nossas iniquidades, fomos escravizados, nós, nossos reis e nossos filhos; fomos entregues à mercê dos reis de outras terras, à espada, ao cativeiro, à pilhagem e à vergonha que nos cobre ainda hoje.

[[v15-9-8]]

^<<v15-9-8,8>>^ Entretanto, o Senhor, nosso Deus, testemunhou-nos por um momento a sua misericórdia, permitindo que subsistisse um resto dentre nós e concedeu-nos um abrigo em seu lugar santo. Nosso Deus quis assim fazer brilhar aos nossos olhos a sua luz e nos dar um pouco de vida no meio de nossa servidão.^&#42;1^

[[v15-9-9]]

^<<v15-9-9,9>>^ Sim, somos escravos; mas nosso Deus não nos abandonou em nosso cativeiro. Ele nos concedeu a benevolência dos reis da Pérsia, dando-nos vida bastante para reconstruir a morada de nosso Deus, reerguer as ruínas; e também nos concedeu um abrigo seguro em Judá e em Jerusalém.

[[v15-9-10]]

^<<v15-9-10,10>>^ Agora, ó Deus nosso, que mais poderemos dizer depois de tudo isso?

[[v15-9-11]]

^<<v15-9-11,11>>^ Abandonamos os mandamentos que vós nos destes por meio de vossos servos, os profetas, que diziam: ‘A terra em que ides entrar para dominar como possessão vossa é uma terra de impureza, contaminada pelas imundícies dos povos dessas regiões, pelas abominações e impurezas com que a encheram de uma extremidade à outra.

[[v15-9-12]]

^<<v15-9-12,12>>^ Não deis, pois, vossas filhas a seus filhos nem tomeis as suas filhas para vossos filhos. Não vos preocupeis com sua prosperidade e seu bem-estar, para que vos torneis fortes e comais os bons produtos dessa terra, a qual transmitireis para sempre como herança aos vossos filhos’.

[[v15-9-13]]

^<<v15-9-13,13>>^ Depois de tudo o que nos aconteceu por causa de nossas más ações e nossa grande culpabilidade, vós nos conservastes, ó nosso Deus, mais do que mereciam as nossas iniquidades e deixastes subsistir um resto dentre nós.

[[v15-9-14]]

^<<v15-9-14,14>>^ Poderíamos recomeçar a violar vossas leis, aliando-nos a esses povos abomináveis? Não vos irritaríeis contra nós, até nos exterminar, sem deixar um sobrevivente que pudesse escapar?

[[v15-9-15]]

^<<v15-9-15,15>>^ Senhor, Deus de Israel, vós sois justo, porque presentemente nada mais somos que um resto de sobreviventes. Eis-nos aqui diante de vós com nossa falta, porque não poderíamos subsistir em vossa presença depois do pecado”.

'''

xref:015-esdras/015-esdras-008.adoc#v15-8-0[&#60; Capítulo Anterior] | <<v15-9-0,Topo>> | xref:015-esdras/015-esdras-010.adoc#v15-10-0[Próximo Capítulo &#62;]