include::./index.adoc[]

[[v15-10-0]]
=== Esdras, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 10 de Esdras fala sobre a restauração da aliança de Deus com o povo de Israel, após a descoberta de que muitos dos líderes judeus haviam se casado com mulheres estrangeiras, o que era proibido pela Lei de Deus. A solução encontrada foi que esses líderes deveriam se divorciar dessas mulheres, a fim de se purificar e se reconciliar com Deus. Aqui estão cinco versículos relacionados com os temas abordados neste capítulo:
* Deuteronômio 7:3-4: "Não se unam em matrimônio com elas, e não permitam que seus filhos se casem com os filhos delas, pois eles os desviariam para adorar outros deuses. Isso levaria à ira do Senhor contra vocês e resultaria na sua destruição rapidamente." Este versículo se relaciona com o tema de Esdras 10, já que os líderes judeus haviam se casado com mulheres estrangeiras, o que era considerado uma violação da Lei de Deus.
* Esdras 9:2: "Eles trouxeram algumas das filhas deles como esposas para os seus filhos, e assim a raça santa ficou misturada com os povos estrangeiros que viviam naquela terra. Os líderes e autoridades judeus foram os primeiros a fazer isso, e isso se tornou um grave pecado." Esse versículo mostra como o casamento com mulheres estrangeiras era considerado um pecado grave pelos líderes judeus.
* Malaquias 2:11: "Judá tem sido infiel, e um ato abominável foi cometido em Israel e em Jerusalém. Judá profanou o santuário do Senhor, o qual ele ama, e se casou com a filha de um deus estrangeiro." Este versículo se relaciona com o tema de Esdras 10, pois mostra como o casamento com mulheres estrangeiras era considerado uma forma de infidelidade e uma profanação do santuário de Deus.
* Esdras 10:3: "Portanto, façamos agora uma aliança com o nosso Deus, para repudiarmos todas essas mulheres estrangeiras e seus filhos, conforme o conselho do meu senhor e dos que tremem diante dos mandamentos do nosso Deus. Que se faça conforme a Lei!" Este versículo mostra como os líderes judeus decidiram se arrepender e se purificar, seguindo a Lei de Deus e repudiando as mulheres estrangeiras.
* 1 Coríntios 7:39: "A mulher está ligada a seu marido enquanto ele viver. Mas se o marido morrer, ela fica livre para se casar com quem quiser, contanto que seja no Senhor." Esse versículo fala sobre a importância de se casar com pessoas que compartilham da mesma fé e valores, o que está relacionado ao tema de Esdras 10, já que os líderes judeus foram exortados a se divorciar das mulheres estrangeiras e buscar uma reconciliação com Deus.
****

[[v15-10-1]]

^<<v15-10-1,1>>^ Enquanto Esdras, prostrado diante da casa de Deus, fazia chorando esta prece e esta confissão, foi se reunindo em torno dele uma multidão numerosa de israelitas. Eram homens, mulheres e crianças, todos chorando.

[[v15-10-2]]

^<<v15-10-2,2>>^ Então, Sequenias, filho de Jaiel, dos filhos de Elam, tomou a palavra e disse a Esdras: “Nós pecamos contra o nosso Deus, tomando por mulheres as estrangeiras pertencentes ao povo da terra. Entretanto, resta ainda uma esperança para Israel.

[[v15-10-3]]

^<<v15-10-3,3>>^ Façamos, agora, uma aliança com nosso Deus: proponhamo-nos a mandar de volta todas essas mulheres e seus filhos, de conformidade com o teu conselho e o daqueles que têm respeito pelos mandamentos de nosso Deus. E que seja feito segundo manda a Lei.

[[v15-10-4]]

^<<v15-10-4,4>>^ Levanta-te, pois, para regulamentar este trabalho. Estaremos contigo. Coragem e mãos à obra!”.

[[v15-10-5]]

^<<v15-10-5,5>>^ Então, Esdras levantou-se e fez com que os chefes dos sacerdotes, dos levitas e de todo o Israel jurassem que agiriam como acabava de ser dito. E todos juraram.

[[v15-10-6]]

^<<v15-10-6,6>>^ Depois, deixando a casa de Deus, foi ao quarto de Joanã, filho de Eliasib. Tendo entrado ali, permaneceu sem comer nem beber, porque chorava o pecado dos filhos do cativeiro.

[[v15-10-7]]

^<<v15-10-7,7>>^ Publicou-se então em Judá e em Jerusalém que todos os filhos do cativeiro viessem reunir-se em Jerusalém.

[[v15-10-8]]

^<<v15-10-8,8>>^ Quem não comparecesse dentro de três dias, conforme as ordens dos anciãos e dos chefes, veria confiscados os seus bens e seria excluído da assembleia dos filhos do cativeiro.

[[v15-10-9]]

^<<v15-10-9,9>>^ Todos os homens de Judá e de Benjamim reuniram-se em Jerusalém nos três dias. Era o vigésimo dia do nono mês. Todo o povo que se encontrava na praça do Templo de Deus tremia, não só pela gravidade da circunstância, mas também porque estava chovendo.

[[v15-10-10]]

^<<v15-10-10,10>>^ Esdras, o sacerdote, levantou-se e disse-lhes: “Vós pecastes tomando mulheres estrangeiras, agravando assim a culpa de Israel.

[[v15-10-11]]

^<<v15-10-11,11>>^ Agora, compenetrai-vos de vossa falta diante do Senhor, o Deus de nossos pais, e fazei a sua vontade. Separai-vos dos povos desta terra e das mulheres estrangeiras”.

[[v15-10-12]]

^<<v15-10-12,12>>^ Toda a assembleia respondeu em alta voz: “Sim, devemos proceder como disseste.

[[v15-10-13]]

^<<v15-10-13,13>>^ Mas o povo é numeroso, é a estação das chuvas e não é, pois, possível ficar-se ao ar livre. Além disso, não é trabalho de um ou dois dias, porque cometemos uma grande transgressão nesse assunto.

[[v15-10-14]]

^<<v15-10-14,14>>^ Que nossos chefes fiquem aqui para representar a assembleia inteira e todos aqueles que, em nossas cidades, receberam em suas casas uma ou mais mulheres estrangeiras, se apresentem nas datas fixadas, com os anciãos de cada cidade e os seus juízes, até que consigamos apartar de nós o fogo da cólera de nosso Deus por causa dessa questão”.

[[v15-10-15]]

^<<v15-10-15,15>>^ Só Jônatas, filho de Asael, e Jaasías, filho de Tícua, se apresentaram para contradizer essa ordem, apoiados por Mesolam e Sebetai, o levita.

[[v15-10-16]]

^<<v15-10-16,16>>^ Os filhos do cativeiro, porém, conformaram-se. Esdras, o sacerdote e alguns homens, chefes de família segundo suas casas, todos designados por seus nomes, puseram-se de parte e, sentando-se, começaram a examinar a questão no primeiro dia do décimo, mês.

[[v15-10-17]]

^<<v15-10-17,17>>^ No primeiro dia do primeiro mês resolveram a questão dos homens que tinham desposado mulheres estrangeiras.

[[v15-10-18]]

^<<v15-10-18,18>>^ Entre os filhos dos sacerdotes, encontravam-se alguns que haviam desposado mulheres estrangeiras, a saber: filhos de Josué, filho de Josedec e de seus irmãos, entre os quais: Maasias, Eliezer, Jarib e Godolias.

[[v15-10-19]]

^<<v15-10-19,19>>^ Estes se comprometeram a repudiar suas mulheres e oferecer um carneiro pela expiação de sua falta.

[[v15-10-20]]

^<<v15-10-20,20>>^ Dos filhos de Emer: Hanani e Zabadias.

[[v15-10-21]]

^<<v15-10-21,21>>^ Dos filhos de Harim: Maasias, Elias, Semeías, Jaiel e Ozias.

[[v15-10-22]]

^<<v15-10-22,22>>^ Dos filhos de Fasur: Elioenai, Maasias, Ismael, Natanael, Jozabed e Elasa.

[[v15-10-23]]

^<<v15-10-23,23>>^ Entre os levitas: Jozabad, Semei, Celaías, chamado também Celita, Petaías, Judá e Eliezer.

[[v15-10-24]]

^<<v15-10-24,24>>^ Entre os cantores: Eliasib. Entre os porteiros: Selum, Telém e Uri.

[[v15-10-25]]

^<<v15-10-25,25>>^ Entre os israelitas: dos filhos de Faros: Remeías, Jezias, Melquias, Miamin, Eleazar, Melquias e Banaías.

[[v15-10-26]]

^<<v15-10-26,26>>^ Dos filhos de Elam: Matanias, Zacarias, Jaiel, Abdi, Jarmut e Elias.

[[v15-10-27]]

^<<v15-10-27,27>>^ Dos filhos de Zetua: Elioenai, Eliasib, Matanias, Jarmut, Zabad e Aziza.

[[v15-10-28]]

^<<v15-10-28,28>>^ Dos filhos de Bebai: Joanã, Hananias, Zabai, Atlai.

[[v15-10-29]]

^<<v15-10-29,29>>^ Dos filhos de Beguai: Mesolam, Meluc, Adaías, Jasub, Saal e Jerimot.

[[v15-10-30]]

^<<v15-10-30,30>>^ Dos filhos de Faat-Moab: Ednas, Calal, Banaías, Maasias, Matanias, Beseleel, Benui e Manassés.

[[v15-10-31]]

^<<v15-10-31,31>>^ Dos filhos de Harim: Eliezer, Jesias, Melquias, Semeías,

[[v15-10-32]]

^<<v15-10-32,32>>^ Simeão, Benjamim, Meluc, Semerias.

[[v15-10-33]]

^<<v15-10-33,33>>^ Dos filhos de Hasum: Matanai, Matatias, Zabad, Elifalet, Jermai, Manassés, Semei.

[[v15-10-34]]

^<<v15-10-34,34>>^ Dos filhos de Bani: Maadai, Amram, Joel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Banaías, Badaías e Quelias,

[[v15-10-36]]

^<<v15-10-36,36>>^ Vanias, Meremot, Eliasib,

[[v15-10-37]]

^<<v15-10-37,37>>^ Matanias, Matanai, Jasi;

[[v15-10-38]]

^<<v15-10-38,38>>^ dos filhos de Benui: Semei,

[[v15-10-39]]

^<<v15-10-39,39>>^ Selemias, Natã e Adaías;

[[v15-10-40]]

^<<v15-10-40,40>>^ dos filhos de Zacai: Sisai, Sarai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Azareel, Selemias, Semerias,

[[v15-10-42]]

^<<v15-10-42,42>>^ Selum, Amarias e José;

[[v15-10-43]]

^<<v15-10-43,43>>^ dos filhos de Nebo: Jeiel, Matatias, Zabad, Zabina, Jedu, Joel e Banaías.

[[v15-10-44]]

^<<v15-10-44,44>>^ Todos esses homens, que haviam desposado mulheres estrangeiras, despediram-nas com seus filhos.^&#42;1^

'''

xref:015-esdras/015-esdras-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-neemias/016-neemias-001.adoc#v16-1-0[Próximo Capítulo &#62;]