include::./index.adoc[]

[[v50-7-0]]
=== São João, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* No capítulo 7 do Evangelho de João, Jesus vai a Jerusalém para a festa dos tabernáculos e ensina no templo. Ele enfrenta a oposição dos líderes religiosos e fala sobre sua missão e sua relação com Deus. Abaixo estão cinco versículos da Bíblia relacionados aos temas abordados em João 7:
* Provérbios 1:22 - "Até quando, ó simples, amareis a simplicidade? E vós escarnecedores, desejareis o escárnio? E vós loucos, aborrecereis o conhecimento?" - Este versículo aborda a rejeição da sabedoria e do conhecimento, temas que são discutidos em João 7, onde os líderes religiosos se opõem à mensagem de Jesus.
* João 5:39 - "Examinai as Escrituras, porque vós cuidais ter nelas a vida eterna, e são elas que de mim testificam" - Jesus usa as Escrituras para mostrar sua relação com Deus e cumprir a profecia. Este versículo destaca a importância da leitura e estudo das Escrituras.
* João 7:16 - "A minha doutrina não é minha, mas daquele que me enviou" - Jesus ensina que sua mensagem vem de Deus e não de si mesmo. Este versículo é importante porque Jesus afirma sua autoridade e sua relação com Deus.
* João 7:37-38 - "No último dia, o grande dia da festa, Jesus pôs-se em pé, e clamou, dizendo: Se alguém tem sede, venha a mim, e beba. Quem crê em mim, como diz a Escritura, rios de água viva correrão do seu ventre." - Este versículo destaca a oferta de Jesus de satisfazer a sede espiritual das pessoas e seu poder para dar vida eterna.
* João 7:52 - "Responderam-lhe eles: És tu também da Galiléia? Examina e vê que da Galiléia nunca se levantou profeta" - Este versículo mostra a descrença dos líderes religiosos em Jesus e sua origem. É um exemplo da oposição que Jesus enfrenta em seu ministério.
****

[[v50-7-1]]

^<<v50-7-1,1>>^ Depois disso, Jesus percorria a Galileia. Ele não queria deter-se na Judeia, porque os judeus procuravam tirar-lhe a vida.

[[v50-7-2]]

^<<v50-7-2,2>>^ Aproximava-se a festa dos judeus chamada dos Tabernáculos.^&#42;1^

[[v50-7-3]]

^<<v50-7-3,3>>^ Seus irmãos disseram-lhe: “Parte daqui e vai para a Judeia, a fim de que também os teus discípulos vejam as obras que fazes.^&#42;1^

[[v50-7-4]]

^<<v50-7-4,4>>^ Pois quem deseja ser conhecido em público não faz coisa alguma ocultamente. Já que fazes essas obras, revela-te ao mundo”.

[[v50-7-5]]

^<<v50-7-5,5>>^ Com efeito, nem mesmo os seus irmãos acreditavam nele.^&#42;1^

[[v50-7-6]]

^<<v50-7-6,6>>^ Disse-lhes Jesus: “O meu tempo ainda não chegou, mas para vós a hora é sempre favorável.

[[v50-7-7]]

^<<v50-7-7,7>>^ O mundo não vos pode odiar, mas odeia-me, porque eu testemunho contra ele que as suas obras são más.

[[v50-7-8]]

^<<v50-7-8,8>>^ Subi vós para a festa. Quanto a mim, eu não irei, porque ainda não chegou o meu tempo”.

[[v50-7-9]]

^<<v50-7-9,9>>^ Dito isso, permaneceu na Galileia.

[[v50-7-10]]

^<<v50-7-10,10>>^ Mas, quando os seus irmãos tinham subido, então subiu também ele à festa, não em público, mas despercebidamente.

[[v50-7-11]]

^<<v50-7-11,11>>^ Buscavam-no os judeus durante a festa e perguntavam: “Onde está ele?”.

[[v50-7-12]]

^<<v50-7-12,12>>^ E na multidão só se discutia a respeito dele. Uns diziam: “É homem de bem.” Outros, porém, diziam: “Não é; ele seduz o povo”.

[[v50-7-13]]

^<<v50-7-13,13>>^ Ninguém, contudo, ousava falar dele livremente com medo dos judeus.^&#42;1^

[[v50-7-14]]

^<<v50-7-14,14>>^ Lá pelo meio da festa, Jesus subiu ao templo e pôs-se a ensinar.

[[v50-7-15]]

^<<v50-7-15,15>>^ Os judeus se admiravam e diziam: “Este homem não fez estudos. Donde lhe vem, pois, este conhecimento das Escrituras?”.

[[v50-7-16]]

^<<v50-7-16,16>>^ Respondeu-lhes Jesus: “A minha doutrina não é minha, mas daquele que me enviou.

[[v50-7-17]]

^<<v50-7-17,17>>^ Se alguém quiser cumprir a vontade de Deus, distinguirá se a minha doutrina é de Deus ou se falo de mim mesmo.

[[v50-7-18]]

^<<v50-7-18,18>>^ Quem fala por própria autoridade busca a própria glória, mas quem procura a glória de quem o enviou é digno de fé e nele não há impostura alguma.

[[v50-7-19]]

^<<v50-7-19,19>>^ Acaso não foi Moisés quem vos deu a Lei? No entanto, ninguém de vós cumpre a Lei!...^&#42;1^

[[v50-7-20]]

^<<v50-7-20,20>>^ Por que procurais tirar-me a vida?”. Respondeu o povo: “Tens um demônio! Quem procura tirar-te a vida?”.

[[v50-7-21]]

^<<v50-7-21,21>>^ Replicou Jesus: “Fiz uma só obra, e todos vós vos maravilhais!

[[v50-7-22]]

^<<v50-7-22,22>>^ Moisés vos deu a circuncisão (se bem que ela não é de Moisés, mas dos patriarcas), e até no sábado circuncidais um homem!

[[v50-7-23]]

^<<v50-7-23,23>>^ Se um homem recebe a circuncisão em dia de sábado, e isso sem violar a Lei de Moisés, por que vos indignais comigo, que tenho curado um homem em todo o seu corpo em dia de sábado?

[[v50-7-24]]

^<<v50-7-24,24>>^ Não julgueis pela aparência, mas julgai conforme a justiça”.

[[v50-7-25]]

^<<v50-7-25,25>>^ Algumas das pessoas de Jerusalém diziam: “Não é este aquele a quem procuram tirar a vida?

[[v50-7-26]]

^<<v50-7-26,26>>^ Todavia, ei-lo que fala em público e não lhe dizem coisa alguma. Porventura reconheceram de fato as autoridades que ele é o Cristo?

[[v50-7-27]]

^<<v50-7-27,27>>^ Mas este nós sabemos de onde vem. Do Cristo, porém, quando vier, ninguém saberá de onde seja”.^&#42;1^

[[v50-7-28]]

^<<v50-7-28,28>>^ Enquanto ensinava no templo, Jesus exclamou: “Ah! Vós me conheceis e sabeis de onde eu sou!... Entretanto, não vim de mim mesmo, mas é verdadeiro aquele que me enviou, e vós não o conheceis.

[[v50-7-29]]

^<<v50-7-29,29>>^ Eu o conheço, porque venho dele e ele me enviou”.

[[v50-7-30]]

^<<v50-7-30,30>>^ Procuraram prendê-lo, mas ninguém lhe deitou as mãos, porque ainda não era chegada a sua hora.

[[v50-7-31]]

^<<v50-7-31,31>>^ Muitos do povo, porém, creram nele e perguntavam: “Quando vier o Cristo, fará mais milagres do que este faz?”.

[[v50-7-32]]

^<<v50-7-32,32>>^ Os fariseus ouviram esse murmúrio que circulava entre o povo a respeito de Jesus. Então, de acordo com eles, os príncipes dos sacerdotes enviaram guardas para prendê-lo.

[[v50-7-33]]

^<<v50-7-33,33>>^ Disse Jesus: “Ainda por um pouco de tempo estou convosco e então vou para aquele que me enviou.

[[v50-7-34]]

^<<v50-7-34,34>>^ Vós me buscareis sem me achar, nem podereis ir para onde estou”.

[[v50-7-35]]

^<<v50-7-35,35>>^ Os judeus perguntavam entre si: “Para onde irá ele, que o não possamos achar? Porventura irá para o meio dos judeus dispersos entre os gregos, para tornar-se o doutor dos estrangeiros?^&#42;1^

[[v50-7-36]]

^<<v50-7-36,36>>^ Que significam essas palavras que nos disse: Vós buscareis sem me achar, e onde estou para lá não podereis ir?”.

[[v50-7-37]]

^<<v50-7-37,37>>^ No último dia, que é o principal dia de festa, estava Jesus de pé e clamava: “Se alguém tiver sede, venha a mim e beba.

[[v50-7-38]]

^<<v50-7-38,38>>^ Quem crê em mim, como diz a Escritura: Do seu interior manarão rios de água viva” (Zc 14,8; Is 58,11).^&#42;1^

[[v50-7-39]]

^<<v50-7-39,39>>^ Dizia isso, referindo-se ao Espírito que haviam de receber os que cressem nele, pois ainda não fora dado o Espírito, visto que Jesus ainda não tinha sido glorificado.

[[v50-7-40]]

^<<v50-7-40,40>>^ Ouvindo essas palavras, alguns daquela multidão diziam: “Este é realmente o profeta”.

[[v50-7-41]]

^<<v50-7-41,41>>^ Outros diziam: “Este é o Cristo”. Mas outros protestavam: “É acaso da Galileia que há de vir o Cristo?

[[v50-7-42]]

^<<v50-7-42,42>>^ Não diz a Escritura: O Cristo há de vir da família de Davi, e da aldeia de Belém, onde vivia Davi?”.^&#42;1^

[[v50-7-43]]

^<<v50-7-43,43>>^ Houve por isso divisão entre o povo por causa dele.

[[v50-7-44]]

^<<v50-7-44,44>>^ Alguns deles queriam prendê-lo, mas ninguém lhe lançou as mãos.

[[v50-7-45]]

^<<v50-7-45,45>>^ Voltaram os guardas para junto dos príncipes dos sacerdotes e fariseus, que lhes perguntaram: “Por que não o trouxestes?”.

[[v50-7-46]]

^<<v50-7-46,46>>^ Os guardas responderam: “Jamais homem algum falou como este homem!...”

[[v50-7-47]]

^<<v50-7-47,47>>^ Replicaram os fariseus: “Porventura também vós fostes seduzidos?

[[v50-7-48]]

^<<v50-7-48,48>>^ Há, acaso, alguém dentre as autoridades ou fariseus que acreditou nele?

[[v50-7-49]]

^<<v50-7-49,49>>^ Este poviléu que não conhece a Lei é amaldiçoado!...”.

[[v50-7-50]]

^<<v50-7-50,50>>^ Replicou-lhes Nicodemos, um deles, o mesmo que de noite o fora procurar:

[[v50-7-51]]

^<<v50-7-51,51>>^ “Condena acaso a nossa Lei algum homem, antes de o ouvir e conhecer o que ele faz?”.

[[v50-7-52]]

^<<v50-7-52,52>>^ Responderam-lhe: “Porventura és também tu galileu? Informa-te bem e verás que da Galileia não saiu profeta”.^&#42;1^

[[v50-7-53]]

^<<v50-7-53,53>>^ E voltaram, cada um para sua casa.^&#42;1^

'''

xref:050-sao-joao/050-sao-joao-006.adoc#v50-6-0[&#60; Capítulo Anterior] | <<v50-7-0,Topo>> | xref:050-sao-joao/050-sao-joao-008.adoc#v50-8-0[Próximo Capítulo &#62;]