include::./index.adoc[]

[[v50-19-0]]
=== São João, 19
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São João 19 relata a crucificação de Jesus. O capítulo descreve em detalhes a cena da condenação de Jesus por Pilatos, sua flagelação e coroação de espinhos, a caminhada para o Gólgota, a crucificação e, finalmente, a morte de Jesus. Aqui estão cinco versículos relacionados aos temas abordados em São João 19:
* Salmos 22:18: "Repartiram entre si as minhas vestes, e sobre a minha túnica lançaram sortes." Este verso profético do Salmo 22 é citado em João 19:24, onde é mencionado como sendo cumprido durante a crucificação de Jesus, quando os soldados romanos lançaram sorte para decidir quem ficaria com suas vestes.
* Isaías 53:3: "Era desprezado, e o mais rejeitado entre os homens, homem de dores, e experimentado nos trabalhos; e, como um de quem os homens escondiam o rosto, era desprezado, e não fizemos dele caso algum." Este verso do livro de Isaías é frequentemente associado a Jesus, especialmente em relação à sua crucificação e sofrimento. Ele reflete a ideia de que Jesus foi rejeitado e menosprezado pelos homens.
* Salmos 69:21: "Deram-me fel por mantimento, e na minha sede me deram a beber vinagre." Este verso do Salmo 69 é citado em João 19:28-29, onde é mencionado como sendo cumprido durante a crucificação de Jesus, quando ele disse "Tenho sede" e os soldados lhe deram vinagre para beber.
* Isaías 53:12: "Pelo que lhe darei a parte de muitos, e com os poderosos repartirá ele o despojo; porquanto derramou a sua alma até a morte, e foi contado com os transgressores; mas ele levou sobre si o pecado de muitos, e pelos transgressores intercedeu." Este verso de Isaías é frequentemente associado a Jesus, especialmente em relação à sua crucificação e morte. Ele reflete a ideia de que Jesus levou sobre si os pecados dos homens e intercedeu por eles.
* Zacarias 12:10: "E sobre a casa de Davi, e sobre os habitantes de Jerusalém, derramarei o espírito de graça e de súplicas; e olharão para mim, a quem traspassaram; e pranteá-lo-ão sobre ele, como quem pranteia pelo filho unigênito; e chorarão amargamente por ele, como se chora amargamente pelo primogênito." Este verso profético de Zacarias é citado em João 19:37, onde é mencionado como sendo cumprido durante a crucificação de Jesus, quando ele foi traspassado com uma lança.
****

[[v50-19-1]]

^<<v50-19-1,1>>^ Pilatos mandou então flagelar Jesus.

[[v50-19-2]]

^<<v50-19-2,2>>^ Os soldados teceram de espinhos uma coroa e puseram-lha sobre a cabeça e cobriram-no com um manto de púrpura.

[[v50-19-3]]

^<<v50-19-3,3>>^ Aproximavam-se dele e diziam: “Salve, rei dos judeus!”. E davam-lhe bofetadas.

[[v50-19-4]]

^<<v50-19-4,4>>^ Pilatos saiu outra vez e disse-lhes: “Eis que vo-lo trago fora, para que saibais que não acho nele nenhum motivo de acusação”.

[[v50-19-5]]

^<<v50-19-5,5>>^ Apareceu então Jesus, trazendo a coroa de espinhos e o manto de púrpura. Pilatos disse: “Eis o homem!”.

[[v50-19-6]]

^<<v50-19-6,6>>^ Quando os pontífices e os guardas o viram, gritaram: “Crucifica-o! Crucifica-o. Falou-lhes Pilatos: “Tomai-o vós e crucificai-o, pois eu não acho nele culpa alguma”.

[[v50-19-7]]

^<<v50-19-7,7>>^ Responderam-lhe os judeus: “Nós temos uma Lei, e segundo essa Lei ele deve morrer, porque se declarou Filho de Deus”.

[[v50-19-8]]

^<<v50-19-8,8>>^ Essas palavras impressionaram Pilatos.

[[v50-19-9]]

^<<v50-19-9,9>>^ Entrou novamente no pretório e perguntou a Jesus: “De onde és tu?”. Mas Jesus não lhe respondeu.

[[v50-19-10]]

^<<v50-19-10,10>>^ Pilatos então lhe disse: “Tu não me respondes? Não sabes que tenho poder para te soltar e para te crucificar?”.

[[v50-19-11]]

^<<v50-19-11,11>>^ Respondeu Jesus: “Não terias poder algum sobre mim, se de cima não te fora dado. Por isso, quem me entregou a ti tem pecado maior”.

[[v50-19-12]]

^<<v50-19-12,12>>^ Desde então Pilatos procurava soltá-lo. Mas os judeus gritavam: “Se o soltares, não és amigo do imperador, porque todo o que se faz rei se declara contra o imperador”.

[[v50-19-13]]

^<<v50-19-13,13>>^ Ouvindo essas palavras, Pilatos trouxe Jesus para fora e sentou-se no tribunal, no lugar chamado Lajeado, em hebraico Gábata.^&#42;1^

[[v50-19-14]]

^<<v50-19-14,14>>^ (Era a Preparação para a Páscoa, cerca da hora sexta.) Pilatos disse aos judeus: “Eis o vosso rei!”.^&#42;1^

[[v50-19-15]]

^<<v50-19-15,15>>^ Mas eles clamavam: “Fora com ele! Fora com ele! Crucifica-o!”. Pilatos perguntou-lhes: “Hei de crucificar o vosso rei?”. Os sumos sacerdotes responderam: “Não temos outro rei senão César!”.

[[v50-19-16]]

^<<v50-19-16,16>>^ Entregou-o então a eles para que fosse crucificado. (= Mt 27,32-56 = Mc 15,21-41 = Lc 23,26-49)

[[v50-19-17]]

^<<v50-19-17,17>>^ Levaram então consigo Jesus. Ele próprio carregava a sua cruz para fora da cidade, em direção ao lugar chamado Calvário, em hebraico Gólgota.^&#42;1^

[[v50-19-18]]

^<<v50-19-18,18>>^ Ali o crucificaram, e com ele outros dois, um de cada lado, e Jesus no meio.

[[v50-19-19]]

^<<v50-19-19,19>>^ Pilatos redigiu também uma inscrição e a fixou por cima da cruz. Nela estava escrito: “Jesus de Nazaré, rei dos judeus”.

[[v50-19-20]]

^<<v50-19-20,20>>^ Muitos dos judeus leram essa inscrição, porque Jesus foi crucificado perto da cidade e a inscrição era redigida em hebraico, em latim e em grego.

[[v50-19-21]]

^<<v50-19-21,21>>^ Os sumos sacerdotes dos judeus disseram a Pilatos: “Não escrevas: Rei dos judeus, mas sim: Este homem disse ser o rei dos judeus”.

[[v50-19-22]]

^<<v50-19-22,22>>^ Respondeu Pilatos: “O que escrevi, escrevi”.

[[v50-19-23]]

^<<v50-19-23,23>>^ Depois de os soldados crucificarem Jesus, tomaram as suas vestes e fizeram delas quatro partes, uma para cada soldado. A túnica, porém, toda tecida de alto a baixo, não tinha costura.

[[v50-19-24]]

^<<v50-19-24,24>>^ Disseram, pois, uns aos outros: “Não a rasguemos, mas deitemos sorte sobre ela, para ver de quem será”. Assim se cumpria a Escritura: Repartiram entre si as minhas vestes e deitaram sorte sobre a minha túnica (Sl 21,19). Isso fizeram os soldados.

[[v50-19-25]]

^<<v50-19-25,25>>^ Junto à cruz de Jesus estavam de pé sua mãe, a irmã de sua mãe, Maria, mulher de Cléofas, e Maria Madalena.

[[v50-19-26]]

^<<v50-19-26,26>>^ Quando Jesus viu sua mãe e perto dela o discípulo que amava, disse à sua mãe: “Mulher, eis aí teu filho”.

[[v50-19-27]]

^<<v50-19-27,27>>^ Depois disse ao discípulo: “Eis aí tua mãe”. E dessa hora em diante o discípulo a recebeu como sua mãe.

[[v50-19-28]]

^<<v50-19-28,28>>^ Em seguida, sabendo Jesus que tudo estava consumado, para se cumprir plenamente a Escritura, disse: “Tenho sede”.

[[v50-19-29]]

^<<v50-19-29,29>>^ Havia ali um vaso cheio de vinagre. Os soldados encheram de vinagre uma esponja e, fixando-a numa vara de hissopo, chegaram-lhe à boca.^&#42;1^

[[v50-19-30]]

^<<v50-19-30,30>>^ Havendo Jesus tomado do vinagre, disse: “Tudo está consumado”. Inclinou a cabeça e entregou o espírito.

[[v50-19-31]]

^<<v50-19-31,31>>^ Os judeus temeram que os corpos ficassem na cruz durante o sábado, porque já era a Preparação e esse sábado era particularmente solene. Rogaram a Pilatos que se lhes quebrassem as pernas e fossem retirados.^&#42;1^

[[v50-19-32]]

^<<v50-19-32,32>>^ Vieram os soldados e quebraram as pernas do primeiro e do outro, que com ele foram crucificados.

[[v50-19-33]]

^<<v50-19-33,33>>^ Chegando, porém, a Jesus, como o vissem já morto, não lhe quebraram as pernas,

[[v50-19-34]]

^<<v50-19-34,34>>^ mas um dos soldados abriu-lhe o lado com uma lança e, imediatamente, saiu sangue e água.

[[v50-19-35]]

^<<v50-19-35,35>>^ O que foi testemunha desse fato o atesta (e o seu testemunho é digno de fé, e ele sabe que diz a verdade), a fim de que vós creiais.

[[v50-19-36]]

^<<v50-19-36,36>>^ Assim se cumpriu a Escritura: Nenhum dos seus ossos será quebrado (Ex 12,46).^&#42;1^

[[v50-19-37]]

^<<v50-19-37,37>>^ E diz em outra parte a Escritura: Olharão para aquele que transpassaram (Zc 12,10). (= Mt 27,57-61 = Mc 15,42-47 = Lc 23,50-56)

[[v50-19-38]]

^<<v50-19-38,38>>^ Depois disso, José de Arimateia, que era discípulo de Jesus, mas ocultamente, por medo dos judeus, rogou a Pilatos a autorização para tirar o corpo de Jesus. Pilatos permitiu. Foi, pois, e tirou o corpo de Jesus.

[[v50-19-39]]

^<<v50-19-39,39>>^ Acompanhou-o Nicodemos (aquele que anteriormente fora de noite ter com Jesus), levando umas cem libras de uma mistura de mirra e aloés.

[[v50-19-40]]

^<<v50-19-40,40>>^ Tomaram o corpo de Jesus e envolveram-no em panos com os aromas, como os judeus costumam sepultar.

[[v50-19-41]]

^<<v50-19-41,41>>^ No lugar em que ele foi crucificado havia um jardim, e no jardim um sepulcro novo, em que ninguém ainda fora depositado.

[[v50-19-42]]

^<<v50-19-42,42>>^ Foi ali que depositaram Jesus por causa da Preparação dos judeus e da proximidade do túmulo. (= Mt 28,1-10 = Mc 16,1-10= Lc 24,1-12)

'''

xref:050-sao-joao/050-sao-joao-018.adoc#v50-18-0[&#60; Capítulo Anterior] | <<v50-19-0,Topo>> | xref:050-sao-joao/050-sao-joao-020.adoc#v50-20-0[Próximo Capítulo &#62;]