include::./index.adoc[]

[[v50-20-0]]
=== São João, 20
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 20 do Evangelho de João narra a ressurreição de Jesus e sua aparição aos discípulos. O tema central é a vitória de Jesus sobre a morte e a confirmação de sua divindade através de sua ressurreição. Abaixo estão cinco versículos relacionados com os temas abordados nesse capítulo:
* Marcos 16:6 - "Vocês estão procurando Jesus, o Nazareno, que foi crucificado. Ele ressuscitou! Não está aqui. Vejam o lugar onde o tinham posto." Esse versículo fala da ressurreição de Jesus, que é o tema central do capítulo 20 de João.
* Romanos 6:9 - "Sabemos que Cristo, tendo sido ressuscitado dos mortos, já não morre; a morte não tem mais domínio sobre ele." Esse versículo reforça a vitória de Jesus sobre a morte e sua posição como Salvador.
* 1 Coríntios 15:17 - "E, se Cristo não ressuscitou, é vã a nossa pregação, e vã é também a vossa fé." Esse versículo destaca a importância da ressurreição de Jesus como base da fé cristã.
* Filipenses 3:10-11 - "Quero conhecer Cristo, o poder da sua ressurreição e a participação em seus sofrimentos, tornando-me como ele em sua morte, para que, de alguma forma, alcance a ressurreição dentre os mortos." Esse versículo destaca a importância da ressurreição de Jesus para a salvação e a busca pela vida eterna.
* Apocalipse 1:18 - "Eu sou o que vivo; fui morto, mas eis que estou vivo pelos séculos dos séculos! E possuo as chaves da morte e do hades." Esse versículo reforça a vitória de Jesus sobre a morte e sua posição como Senhor da vida e da morte.
****

[[v50-20-1]]

^<<v50-20-1,1>>^ No primeiro dia que se seguia ao sábado, Maria Madalena foi ao sepulcro, de manhã cedo, quando ainda estava escuro. Viu a pedra removida do sepulcro.

[[v50-20-2]]

^<<v50-20-2,2>>^ Correu e foi dizer a Simão Pedro e ao outro discípulo a quem Jesus amava: “Tiraram o Senhor do sepulcro, e não sabemos onde o puseram!”.

[[v50-20-3]]

^<<v50-20-3,3>>^ Saiu então Pedro com aquele outro discípulo, e foram ao sepulcro.

[[v50-20-4]]

^<<v50-20-4,4>>^ Corriam juntos, mas aquele outro discípulo correu mais depressa do que Pedro e chegou primeiro ao sepulcro.

[[v50-20-5]]

^<<v50-20-5,5>>^ Inclinou-se e viu ali os panos no chão, mas não entrou.

[[v50-20-6]]

^<<v50-20-6,6>>^ Chegou Simão Pedro que o seguia, entrou no sepulcro e viu os panos postos no chão.

[[v50-20-7]]

^<<v50-20-7,7>>^ Viu também o sudário que estivera sobre a cabeça de Jesus. Não estava, porém, com os panos, mas enrolado num lugar à parte.

[[v50-20-8]]

^<<v50-20-8,8>>^ Então, entrou também o discípulo que havia chegado primeiro ao sepulcro. Viu e creu.

[[v50-20-9]]

^<<v50-20-9,9>>^ Em verdade, ainda não haviam entendido a Escritura, segundo a qual Jesus devia ressuscitar dentre os mortos.

[[v50-20-10]]

^<<v50-20-10,10>>^ Os discípulos, então, voltaram para as suas casas.

[[v50-20-11]]

^<<v50-20-11,11>>^ Entretanto, Maria se conservava do lado de fora perto do sepulcro e chorava. Chorando, inclinou-se para olhar dentro do sepulcro.

[[v50-20-12]]

^<<v50-20-12,12>>^ Viu dois anjos vestidos de branco, sentados onde estivera o corpo de Jesus, um à cabeceira e outro aos pés.

[[v50-20-13]]

^<<v50-20-13,13>>^ Eles lhe perguntaram: “Mulher, por que choras?”. Ela respondeu: “Porque levaram o meu Senhor, e não sei onde o puseram”.

[[v50-20-14]]

^<<v50-20-14,14>>^ Ditas essas palavras, voltou-se para trás e viu Jesus em pé, mas não o reconheceu.

[[v50-20-15]]

^<<v50-20-15,15>>^ Perguntou-lhe Jesus: “Mulher, por que choras? Quem procuras?”. Supondo ela que fosse o jardineiro, respondeu: “Senhor, se tu o tiraste, dize-me onde o puseste e eu o irei buscar”.

[[v50-20-16]]

^<<v50-20-16,16>>^ Disse-lhe Jesus: “Maria!” Voltando-se ela, exclamou em hebraico: “Rabôni!” (que quer dizer Mestre).

[[v50-20-17]]

^<<v50-20-17,17>>^ Disse-lhe Jesus: “Não me retenhas, porque ainda não subi a meu Pai, mas vai a meus irmãos e dize-lhes: Subo para meu Pai e vosso Pai, meu Deus e vosso Deus”.^&#42;1^

[[v50-20-18]]

^<<v50-20-18,18>>^ Maria Madalena correu para anunciar aos discípulos que ela tinha visto o Senhor e contou o que ele lhe tinha falado. (= Mc 16,14-18 = Lc 24,36-49)

[[v50-20-19]]

^<<v50-20-19,19>>^ Na tarde do mesmo dia, que era o primeiro da semana, os discípulos tinham fechado as portas do lugar onde se achavam, por medo dos judeus. Jesus veio e pôs-se no meio deles. Disse-lhes ele: “A paz esteja convosco!”.

[[v50-20-20]]

^<<v50-20-20,20>>^ Dito isso, mostrou-lhes as mãos e o lado. Os discípulos alegraram-se ao ver o Senhor.

[[v50-20-21]]

^<<v50-20-21,21>>^ Disse-lhes outra vez: “A paz esteja convosco! Como o Pai me enviou, assim também eu vos envio a vós”.

[[v50-20-22]]

^<<v50-20-22,22>>^ Depois dessas palavras, soprou sobre eles dizendo-lhes: “Recebei o Espírito Santo.

[[v50-20-23]]

^<<v50-20-23,23>>^ Àqueles a quem perdoardes os pecados, lhes serão perdoados; àqueles a quem os retiverdes, lhes serão retidos”.

[[v50-20-24]]

^<<v50-20-24,24>>^ Tomé, um dos Doze, chamado Dídimo, não estava com eles quando veio Jesus.

[[v50-20-25]]

^<<v50-20-25,25>>^ Os outros discípulos disseram-lhe: “Vimos o Senhor”. Mas ele replicou-lhes: “Se não vir nas suas mãos o sinal dos pregos, e não puser o meu dedo no lugar dos pregos, e não introduzir a minha mão no seu lado, não acreditarei!”.

[[v50-20-26]]

^<<v50-20-26,26>>^ Oito dias depois, estavam os seus discípulos outra vez no mesmo lugar e Tomé com eles. Estando trancadas as portas, veio Jesus, pôs-se no meio deles e disse: “A paz esteja convosco!”.

[[v50-20-27]]

^<<v50-20-27,27>>^ Depois disse a Tomé: “Introduz aqui o teu dedo, e vê as minhas mãos. Põe a tua mão no meu lado. Não sejas incrédulo, mas homem de fé”.

[[v50-20-28]]

^<<v50-20-28,28>>^ Respondeu-lhe Tomé: “Meu Senhor e meu Deus!”.

[[v50-20-29]]

^<<v50-20-29,29>>^ Disse-lhe Jesus: “Creste, porque me viste. Felizes aqueles que creem sem ter visto!”.

[[v50-20-30]]

^<<v50-20-30,30>>^ Fez Jesus, na presença dos seus discípulos, ainda muitos outros milagres que não estão escritos neste livro.

[[v50-20-31]]

^<<v50-20-31,31>>^ Mas estes foram escritos, para que creiais que Jesus é o Cristo, o Filho de Deus, e para que, crendo, tenhais a vida em seu nome.^&#42;1^

'''

xref:050-sao-joao/050-sao-joao-019.adoc#v50-19-0[&#60; Capítulo Anterior] | <<v50-20-0,Topo>> | xref:050-sao-joao/050-sao-joao-021.adoc#v50-21-0[Próximo Capítulo &#62;]