include::./index.adoc[]

[[v50-5-0]]
=== São João, 5
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São João 5 é um capítulo que fala sobre a cura de um homem que estava doente há 38 anos e como isso causou polêmica entre os líderes religiosos da época. Além disso, Jesus se apresenta como Filho de Deus e fala sobre a autoridade que lhe foi dada pelo Pai. A seguir, cinco versículos relacionados com os temas abordados em São João 5:
* João 5:21: "Pois, assim como o Pai ressuscita os mortos e lhes dá vida, assim também o Filho dá vida a quem ele quer." Este versículo mostra a autoridade que Jesus possui para conceder vida e ressuscitar os mortos.
* João 5:24: "Digo a verdade: Quem ouve a minha palavra e crê naquele que me enviou tem a vida eterna e não será condenado, mas já passou da morte para a vida." Neste versículo, Jesus fala sobre a salvação que é alcançada por meio da fé em Deus e em sua mensagem.
* João 5:39: "Vocês estudam cuidadosamente as Escrituras, porque pensam que nelas vocês têm a vida eterna. E são as Escrituras que testemunham a meu respeito." Este versículo mostra como os líderes religiosos da época estavam presos às tradições e à letra da lei, sem entender o verdadeiro significado das Escrituras e da mensagem de Jesus.
* João 5:44: "Como vocês podem crer, se aceitam glória uns dos outros, mas não procuram a glória que vem do Deus único?" Neste versículo, Jesus fala sobre a busca pela glória e reconhecimento humano, em vez de buscar a aprovação e glória de Deus.
* João 5:46-47: "Se vocês cressem em Moisés, creriam em mim, pois ele escreveu a meu respeito. Mas, se não acreditam nos escritos dele, como acreditarão no que eu digo?" Jesus fala sobre como sua mensagem está em conformidade com as Escrituras e que aqueles que não acreditam em suas palavras não estão realmente seguindo os ensinamentos de Moisés e dos profetas.
****

[[v50-5-1]]

^<<v50-5-1,1>>^ Depois disso, houve uma festa dos judeus, e Jesus subiu a Jerusalém.^&#42;1^

[[v50-5-2]]

^<<v50-5-2,2>>^ Há em Jerusalém, junto à porta das Ovelhas, um tanque, chamado em hebraico Betesda, que tem cinco pórticos.

[[v50-5-3]]

^<<v50-5-3,3>>^ Nesses pórticos jazia um grande número de enfermos, de cegos, de coxos e de paralíticos, que esperavam o movimento da água.

[[v50-5-4]]

^<<v50-5-4,4>>^ [Pois de tempos em tempos um anjo do Senhor descia ao tanque e a água se punha em movimento. E o primeiro que entrasse no tanque, depois da agitação da água, ficava curado de qualquer doença que tivesse.]^&#42;1^

[[v50-5-5]]

^<<v50-5-5,5>>^ Estava ali um homem enfermo havia trinta e oito anos.

[[v50-5-6]]

^<<v50-5-6,6>>^ Vendo-o deitado e sabendo que já havia muito tempo que estava enfermo, perguntou-lhe Jesus: “Queres ficar curado?”.

[[v50-5-7]]

^<<v50-5-7,7>>^ O enfermo respondeu-lhe: “Senhor, não tenho ninguém que me ponha no tanque, quando a água é agitada; enquanto vou, já outro desceu antes de mim.”

[[v50-5-8]]

^<<v50-5-8,8>>^ Ordenou-lhe Jesus: “Levanta-te, toma o teu leito e anda”.

[[v50-5-9]]

^<<v50-5-9,9>>^ No mesmo instante, aquele homem ficou curado, tomou o seu leito e foi andando. Ora, aquele dia era sábado.

[[v50-5-10]]

^<<v50-5-10,10>>^ E os judeus diziam ao homem curado: “É sábado, não te é permitido carregar o teu leito.”

[[v50-5-11]]

^<<v50-5-11,11>>^ Respondeu-lhes ele: “Aquele que me curou disse: Toma o teu leito e anda.”

[[v50-5-12]]

^<<v50-5-12,12>>^ Perguntaram-lhe eles: “Quem é o homem que te disse: Toma o teu leito e anda?”.

[[v50-5-13]]

^<<v50-5-13,13>>^ O que havia sido curado, porém, não sabia quem era, porque Jesus se havia retirado da multidão que estava naquele lugar.

[[v50-5-14]]

^<<v50-5-14,14>>^ Mais tarde, Jesus o achou no templo e lhe disse: “Eis que ficaste são; já não peques, para não te acontecer coisa pior”.

[[v50-5-15]]

^<<v50-5-15,15>>^ Aquele homem foi então contar aos judeus que fora Jesus quem o havia curado.

[[v50-5-16]]

^<<v50-5-16,16>>^ Por esse motivo, os judeus perseguiam Jesus, porque fazia esses milagres no dia de sábado.

[[v50-5-17]]

^<<v50-5-17,17>>^ Mas ele lhes disse: “Meu Pai continua agindo até agora, e eu ajo também”.

[[v50-5-18]]

^<<v50-5-18,18>>^ Por essa razão os judeus, com maior ardor, procuravam tirar-lhe a vida, porque não somente violava o repouso do sábado, mas afirmava ainda que Deus era seu Pai e se fazia igual a Deus.

[[v50-5-19]]

^<<v50-5-19,19>>^ Jesus tomou a palavra e disse-lhes: “Em verdade, em verdade vos digo: o Filho de si mesmo não pode fazer coisa alguma; ele só faz o que vê fazer o Pai; e tudo o que o Pai faz, o faz também semelhantemente o Filho.

[[v50-5-20]]

^<<v50-5-20,20>>^ Pois o Pai ama o Filho e mostra-lhe tudo o que faz; e maiores obras do que esta lhe mostrará, para que fiqueis admirados.

[[v50-5-21]]

^<<v50-5-21,21>>^ Com efeito, como o Pai ressuscita os mortos e lhes dá vida, assim também o Filho dá vida a quem ele quer.

[[v50-5-22]]

^<<v50-5-22,22>>^ Assim também o Pai não julga ninguém, mas entregou todo o julgamento ao Filho.

[[v50-5-23]]

^<<v50-5-23,23>>^ Desse modo, todos honrarão o Filho, bem como honram o Pai. Aquele que não honra o Filho não honra o Pai, que o enviou.

[[v50-5-24]]

^<<v50-5-24,24>>^ Em verdade, em verdade vos digo: quem ouve a minha palavra e crê naquele que me enviou tem a vida eterna e não incorre na condenação, mas passou da morte para a vida.

[[v50-5-25]]

^<<v50-5-25,25>>^ Em verdade, em verdade vos digo: vem a hora, e já está aí, em que os mortos ouvirão a voz do Filho de Deus; e os que a ouvirem, viverão.^&#42;1^

[[v50-5-26]]

^<<v50-5-26,26>>^ Pois como o Pai tem a vida em si mesmo, assim também deu ao Filho ter a vida em si mesmo,

[[v50-5-27]]

^<<v50-5-27,27>>^ e lhe conferiu o poder de julgar, porque é o Filho do Homem.^&#42;1^

[[v50-5-28]]

^<<v50-5-28,28>>^ Não vos maravilheis disso, porque vem a hora em que todos os que se acham nos sepulcros sairão deles ao som de sua voz:

[[v50-5-29]]

^<<v50-5-29,29>>^ os que praticaram o bem irão para a ressurreição da vida, e aqueles que praticaram o mal ressuscitarão para serem condenados.

[[v50-5-30]]

^<<v50-5-30,30>>^ De mim mesmo não posso fazer coisa alguma. Julgo como ouço; e o meu julgamento é justo, porque não busco a minha vontade, mas a vontade daquele que me enviou.

[[v50-5-31]]

^<<v50-5-31,31>>^ Se eu der testemunho de mim mesmo, não é digno de fé o meu testemunho.

[[v50-5-32]]

^<<v50-5-32,32>>^ Há outro que dá testemunho de mim, e sei que é digno de fé o testemunho que dá de mim.

[[v50-5-33]]

^<<v50-5-33,33>>^ Vós enviastes mensageiros a João, e ele deu testemunho da verdade.

[[v50-5-34]]

^<<v50-5-34,34>>^ Não invoco, porém, o testemunho de homem algum. Digo-vos essas coisas, a fim de que sejais salvos.

[[v50-5-35]]

^<<v50-5-35,35>>^ João era uma lâmpada que arde e ilumina; vós, porém, só por uma hora quisestes alegrar-vos com a sua luz.

[[v50-5-36]]

^<<v50-5-36,36>>^ Mas tenho maior testemunho do que o de João, porque as obras que meu Pai me deu para executar – essas mesmas obras que faço – testemunham a meu respeito que o Pai me enviou.

[[v50-5-37]]

^<<v50-5-37,37>>^ E o Pai que me enviou, ele mesmo deu testemunho de mim. Vós nunca ouvistes a sua voz nem vistes a sua face...

[[v50-5-38]]

^<<v50-5-38,38>>^ e não tendes a sua palavra permanente em vós, pois não credes naquele que ele enviou.

[[v50-5-39]]

^<<v50-5-39,39>>^ Vós perscrutais as Escrituras, julgando encontrar nelas a vida eterna. Pois bem! São elas mesmas que dão testemunho de mim.^&#42;1^

[[v50-5-40]]

^<<v50-5-40,40>>^ E vós não quereis vir a mim para que tenhais a vida...

[[v50-5-41]]

^<<v50-5-41,41>>^ Não espero a minha glória dos homens,

[[v50-5-42]]

^<<v50-5-42,42>>^ mas sei que não tendes em vós o amor de Deus.

[[v50-5-43]]

^<<v50-5-43,43>>^ Vim em nome de meu Pai, mas não me recebeis. Se vier outro em seu próprio nome, haveis de recebê-lo...

[[v50-5-44]]

^<<v50-5-44,44>>^ Como podeis crer, vós que recebeis a glória uns dos outros, e não buscais a glória que é só de Deus?

[[v50-5-45]]

^<<v50-5-45,45>>^ Não julgueis que vos hei de acusar diante do Pai; há quem vos acuse: Moisés, no qual colocais a vossa esperança.

[[v50-5-46]]

^<<v50-5-46,46>>^ Pois, se crêsseis em Moisés, certamente creríeis em mim, porque ele escreveu a meu respeito.

[[v50-5-47]]

^<<v50-5-47,47>>^ Mas, se não acreditais nos seus escritos, como acreditareis nas minhas palavras?”. (= Mt 14,13-21 = Mc 6,32-44 = Lc 9,10-17)

'''

xref:050-sao-joao/050-sao-joao-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v50-5-0,Topo>> | xref:050-sao-joao/050-sao-joao-006.adoc#v50-6-0[Próximo Capítulo &#62;]