include::./index.adoc[]

[[v50-13-0]]
=== São João, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São João 13 descreve a última ceia de Jesus com seus discípulos, onde Ele lava os pés deles e compartilha suas últimas palavras de ensinamentos antes da crucificação. Abaixo estão cinco versículos relacionados com os temas abordados no capítulo:
* Filipenses 2:3-4: "Não façam nada por ambição egoísta ou por vaidade, mas humildemente considerem os outros superiores a si mesmos. Cada um cuide, não somente dos seus interesses, mas também dos interesses dos outros." Este versículo enfatiza a importância da humildade e do cuidado com os outros, mostrando o exemplo de Jesus ao lavar os pés de seus discípulos.
* João 15:12-13: "O meu mandamento é este: amem-se uns aos outros como eu os amei. Ninguém tem maior amor do que aquele que dá a sua vida pelos seus amigos." Esses versículos reforçam o ensinamento de Jesus sobre o amor ao próximo, que é exemplificado em suas ações durante a última ceia.
* Colossenses 3:13: "Suportem-se uns aos outros e perdoem as queixas que tiverem uns contra os outros. Perdoem como o Senhor lhes perdoou." O ato de Jesus de lavar os pés de seus discípulos mostra seu amor e disposição em servir, e este versículo destaca a importância de perdoar e amar os outros em nossas ações diárias.
* Mateus 20:26-28: "Entre vocês, porém, não será assim. Ao contrário, quem quiser tornar-se importante entre vocês deverá ser servo, e quem quiser ser o primeiro deverá ser escravo; como o Filho do homem, que não veio para ser servido, mas para servir e dar a sua vida em resgate por muitos." Esses versículos mostram o exemplo de Jesus em servir e cuidar dos outros, e como devemos imitar seu exemplo em nossas próprias vidas.
* João 14:15: "Se vocês me amam, obedecerão aos meus mandamentos." Durante a última ceia, Jesus enfatizou a importância de obedecer aos seus ensinamentos e mandamentos, como uma expressão de amor e devoção a Ele.
****

[[v50-13-1]]

^<<v50-13-1,1>>^ Antes da festa da Páscoa, sabendo Jesus que chegara a sua hora de passar deste mundo ao Pai, como amasse os seus que estavam no mundo, até o extremo os amou.

[[v50-13-2]]

^<<v50-13-2,2>>^ Durante a ceia – quando o demônio já tinha lançado no coração de Judas, filho de Simão Iscariotes, o propósito de traí-lo –,

[[v50-13-3]]

^<<v50-13-3,3>>^ sabendo Jesus que o Pai tudo lhe dera nas mãos, e que saíra de Deus e para Deus voltava,

[[v50-13-4]]

^<<v50-13-4,4>>^ levantou-se da mesa, depôs as suas vestes e, pegando duma toalha, cingiu-se com ela.

[[v50-13-5]]

^<<v50-13-5,5>>^ Em seguida, deitou água numa bacia e começou a lavar os pés dos discípulos e a enxugá-los com a toalha com que estava cingido.

[[v50-13-6]]

^<<v50-13-6,6>>^ Chegou a Simão Pedro. Mas Pedro lhe disse: “Senhor, queres lavar-me os pés!...”.

[[v50-13-7]]

^<<v50-13-7,7>>^ Respondeu-lhe Jesus: “O que faço não compreendes agora, mas irás compreendê-lo em breve”.

[[v50-13-8]]

^<<v50-13-8,8>>^ Disse-lhe Pedro: “Jamais me lavarás os pés!...”. Respondeu-lhe Jesus: “Se eu não os lavar, não terás parte comigo”.

[[v50-13-9]]

^<<v50-13-9,9>>^ Exclamou então Simão Pedro: “Senhor, não somente os pés, mas também as mãos e a cabeça”.

[[v50-13-10]]

^<<v50-13-10,10>>^ Disse-lhe Jesus: “Aquele que tomou banho não tem necessidade de lavar-se; está inteiramente puro. Ora, vós estais puros, mas nem todos!...”.^&#42;1^

[[v50-13-11]]

^<<v50-13-11,11>>^ Pois sabia quem o havia de trair; por isso, disse: “Nem todos estais puros”.

[[v50-13-12]]

^<<v50-13-12,12>>^ Depois de lhes lavar os pés e tomar as suas vestes, sentou-se novamente à mesa e perguntou-lhes: “Sabeis o que vos fiz?

[[v50-13-13]]

^<<v50-13-13,13>>^ Vós me chamais Mestre e Senhor, e dizeis bem, porque eu o sou.

[[v50-13-14]]

^<<v50-13-14,14>>^ Logo, se eu, vosso Senhor e Mestre, vos lavei os pés, também vós deveis lavar-vos os pés uns dos outros.^&#42;1^

[[v50-13-15]]

^<<v50-13-15,15>>^ Dei-vos o exemplo para que, como eu vos fiz, assim façais também vós.

[[v50-13-16]]

^<<v50-13-16,16>>^ Em verdade, em verdade vos digo: o servo não é maior do que o seu Senhor, nem o enviado é maior do que aquele que o enviou.

[[v50-13-17]]

^<<v50-13-17,17>>^ Se compreenderdes essas coisas, sereis felizes, sob condição de as praticardes.

[[v50-13-18]]

^<<v50-13-18,18>>^ Não digo isso de vós todos; conheço os que escolhi, mas é preciso que se cumpra essa palavra da Escritura: Aquele que come o pão comigo levantou contra mim o seu calcanhar (Sl 40,10).

[[v50-13-19]]

^<<v50-13-19,19>>^ Desde já vo-lo digo, antes que aconteça, para que, quando acontecer, creiais e reconheçais quem sou eu.

[[v50-13-20]]

^<<v50-13-20,20>>^ Em verdade, em verdade vos digo: quem recebe aquele que eu enviei recebe a mim; e quem me recebe recebe aquele que me enviou”.

[[v50-13-21]]

^<<v50-13-21,21>>^ Dito isso, Jesus ficou perturbado em seu espírito e declarou abertamente: “Em verdade, em verdade vos digo: um de vós me há de trair!...”.

[[v50-13-22]]

^<<v50-13-22,22>>^ Os discípulos olhavam uns para os outros, sem saber de quem falava.

[[v50-13-23]]

^<<v50-13-23,23>>^ Um dos discípulos, a quem Jesus amava, estava à mesa reclinado ao peito de Jesus.^&#42;1^

[[v50-13-24]]

^<<v50-13-24,24>>^ Simão Pedro acenou-lhe para dizer-lhe: “Dize-nos, de quem é que ele fala”.

[[v50-13-25]]

^<<v50-13-25,25>>^ Reclinando-se esse mesmo discípulo sobre o peito de Jesus, interrogou-o: “Senhor, quem é?”.

[[v50-13-26]]

^<<v50-13-26,26>>^ Jesus respondeu: “É aquele a quem eu der o pão embebido”. Em seguida, molhou o pão e deu-o a Judas, filho de Simão Iscariotes.^&#42;1^

[[v50-13-27]]

^<<v50-13-27,27>>^ Logo que ele o engoliu, Satanás entrou nele. Jesus disse-lhe, então: “O que queres fazer, faze-o depressa”.

[[v50-13-28]]

^<<v50-13-28,28>>^ Mas ninguém dos que estavam à mesa soube por que motivo lhe dissera.

[[v50-13-29]]

^<<v50-13-29,29>>^ Pois, como Judas tinha a bolsa, pensavam alguns que Jesus lhe falava: “Compra aquilo de que temos necessidade para a festa”. Ou: “Dá alguma coisa aos pobres”.

[[v50-13-30]]

^<<v50-13-30,30>>^ Tendo Judas recebido o bocado de pão, apressou-se em sair. E era noite...

[[v50-13-31]]

^<<v50-13-31,31>>^ Logo que Judas saiu, Jesus disse: “Agora é glorificado o Filho do Homem, e Deus é glorificado nele.

[[v50-13-32]]

^<<v50-13-32,32>>^ Se Deus foi glorificado nele, também Deus o glorificará em si mesmo, e o glorificará em breve.

[[v50-13-33]]

^<<v50-13-33,33>>^ Filhinhos meus, por um pouco apenas ainda estou convosco. Vós me haveis de procurar, mas, como disse aos judeus, também vos digo agora a vós: para onde eu vou, vós não podeis ir.

[[v50-13-34]]

^<<v50-13-34,34>>^ Dou-vos um novo mandamento: Amai-vos uns aos outros. Como eu vos tenho amado, assim também vós deveis amar-vos uns aos outros.

[[v50-13-35]]

^<<v50-13-35,35>>^ Nisso todos conhecerão que sois meus discípulos, se vos amardes uns aos outros”.

[[v50-13-36]]

^<<v50-13-36,36>>^ Perguntou-lhe Simão Pedro: “Senhor, para onde vais?”. Jesus respondeu-lhe: “Para onde vou, não podes seguir-me agora, mas tu seguirás mais tarde”.

[[v50-13-37]]

^<<v50-13-37,37>>^ Pedro tornou a perguntar: “Senhor, por que te não posso seguir agora? Darei a minha vida por ti!”.

[[v50-13-38]]

^<<v50-13-38,38>>^ Respondeu-lhe Jesus: “Darás a tua vida por mim!... Em verdade, em verdade te digo: não cantará o galo até que me negues três vezes”.

'''

xref:050-sao-joao/050-sao-joao-012.adoc#v50-12-0[&#60; Capítulo Anterior] | <<v50-13-0,Topo>> | xref:050-sao-joao/050-sao-joao-014.adoc#v50-14-0[Próximo Capítulo &#62;]