include::./index.adoc[]

[[v28-28-0]]
=== Eclesiástico, 28
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 28 do livro de Eclesiástico trata do perdão e da importância de evitar a ira e a vingança. O autor adverte que aqueles que procuram vingança experimentarão a ira de Deus, e que é melhor perdoar para evitar conflitos e brigas. Abaixo estão cinco versículos relacionados com esses temas:
* Provérbios 19:11: "A sabedoria do homem lhe dá paciência; sua glória é ignorar ofensas." Este versículo destaca a importância da paciência e da sabedoria na resposta a ofensas, enfatizando que é melhor ignorá-las do que revidar.
* Mateus 6:14-15: "Porque se perdoarem as ofensas uns dos outros, o Pai celestial também lhes perdoará. Mas se não perdoarem uns aos outros, o Pai celestial não lhes perdoará as ofensas." Jesus ensina a importância do perdão, afirmando que aqueles que perdoam serão perdoados pelo Pai Celestial, enquanto aqueles que não perdoam não receberão perdão.
* Romanos 12:19: "Amados, nunca procurem vingar-se, mas deixem com Deus a ira, pois está escrito: "Minha é a vingança; eu retribuirei", diz o Senhor." Paulo encoraja os cristãos a não buscarem vingança, mas a confiarem em Deus para julgar e punir os que fazem o mal.
* Efésios 4:31-32: "Livrem-se de toda amargura, indignação e ira, gritaria e calúnia, bem como de toda maldade. Sejam bondosos e compassivos uns para com os outros, perdoando-se mutuamente, assim como Deus os perdoou em Cristo." Paulo exorta os crentes a abandonar a ira e a maldade e a serem compassivos e perdoadores uns com os outros, como Deus perdoou em Cristo.
* Colossenses 3:13: "Suportem-se uns aos outros e perdoem as queixas que tiverem uns contra os outros. Perdoem como o Senhor lhes perdoou." O apóstolo Paulo incentiva os cristãos a suportarem uns aos outros e a perdoarem uns aos outros, assim como Deus os perdoou em Cristo.
****

[[v28-28-1]]

^<<v28-28-1,1>>^ Aquele que quer vingar sofrerá a vingança do Senhor, que guardará cuidadosamente os seus pecados.

[[v28-28-2]]

^<<v28-28-2,2>>^ Perdoa ao teu próximo o mal que te fez, e teus pecados serão perdoados quando o pedires.

[[v28-28-3]]

^<<v28-28-3,3>>^ Um homem guarda rancor contra outro homem, e pede a Deus a sua cura!

[[v28-28-4]]

^<<v28-28-4,4>>^ Não tem misericórdia para com o seu semelhante, e roga o perdão dos seus pecados!

[[v28-28-5]]

^<<v28-28-5,5>>^ Ele, que é apenas carne, guarda rancor, e pede a Deus que lhe seja propício! Quem, então, lhe conseguirá o perdão de seus pecados?

[[v28-28-6]]

^<<v28-28-6,6>>^ Lembra-te do teu fim, e põe termo às tuas inimizades,

[[v28-28-7]]

^<<v28-28-7,7>>^ pois a decadência e a morte são uma ameaça para aqueles que transgridem os mandamentos.^&#42;1^

[[v28-28-8]]

^<<v28-28-8,8>>^ Lembra-te do temor a Deus, e não fiques irado contra o próximo.^&#42;1^

[[v28-28-9]]

^<<v28-28-9,9>>^ Lembra-te da aliança com o Altíssimo, e passa por cima do erro que o teu próximo cometeu inadvertidamente.

[[v28-28-10]]

^<<v28-28-10,10>>^ Evita a desavença e diminuirás os pecados.

[[v28-28-11]]

^<<v28-28-11,11>>^ O homem irascível provoca as querelas; o pecador espalha a inquietação entre seus amigos, e semeia a inimizade no meio de pessoas que vivem em paz.

[[v28-28-12]]

^<<v28-28-12,12>>^ O fogo queima na proporção da lenha que há na floresta; a ira do homem inflama-se na medida de seu poder, e desenvolve-se em proporção de sua riqueza.

[[v28-28-13]]

^<<v28-28-13,13>>^ Uma querela precipitada acende o fogo; a presteza na disputa derrama sangue; e a língua que presta falso testemunho causa a morte.

[[v28-28-14]]

^<<v28-28-14,14>>^ Sopra sobre uma centelha e ela se abrasará; cospe sobre ela e ela se apagará: ambos saem de tua boca.

[[v28-28-15]]

^<<v28-28-15,15>>^ Maldito o delator e o homem que diz branco e preto, pois semeiam a discórdia entre muita gente que vive em paz.

[[v28-28-16]]

^<<v28-28-16,16>>^ A língua de um terceiro abalou muitos deles, e os afugentou de uma nação a outra.^&#42;1^

[[v28-28-17]]

^<<v28-28-17,17>>^ Ela destruiu as cidades fortes dos ricos, e arrasou as casas dos poderosos.

[[v28-28-18]]

^<<v28-28-18,18>>^ Desbaratou os exércitos dos povos, e dispersou nações valentes.

[[v28-28-19]]

^<<v28-28-19,19>>^ A língua de um terceiro fez repudiar mulheres superiores, e privou-as do fruto de seu labor.

[[v28-28-20]]

^<<v28-28-20,20>>^ Aquele que o ouve não terá paz, não terá amigo em quem tenha confiança.^&#42;1^

[[v28-28-21]]

^<<v28-28-21,21>>^ A chicotada produz um ferimento, porém uma língua má quebra os ossos.

[[v28-28-22]]

^<<v28-28-22,22>>^ Muitos homens morreram a fio de espada, mas não tantos quantos os que pereceram por causa da língua.

[[v28-28-23]]

^<<v28-28-23,23>>^ Feliz aquele que está ao abrigo da língua perversa, que não passou pela cólera dela, que não atraiu sobre si o seu jugo, e que não foi atado pelas suas correntes,

[[v28-28-24]]

^<<v28-28-24,24>>^ pois o jugo dela é um jugo de ferro, e suas correntes, correntes de bronze.

[[v28-28-25]]

^<<v28-28-25,25>>^ A morte que ela dá é morte desastrada, e a moradia dos mortos é-lhe preferível.

[[v28-28-26]]

^<<v28-28-26,26>>^ Ela durará, mas não sempre; ela dominará o proceder dos injustos, e os justos não serão devorados pelas suas chamas.^&#42;1^

[[v28-28-27]]

^<<v28-28-27,27>>^ Aqueles que abandonam Deus lhe serão entregues: ela os consumirá sem se apagar; ela se lançará sobre eles como um leão; e os estraçalhará como um leopardo.

[[v28-28-28]]

^<<v28-28-28,28>>^ Protege teus ouvidos com uma sebe de espinhos; não dês ouvidos à língua maldosa, e põe em tua boca uma porta com ferrolhos.

[[v28-28-29]]

^<<v28-28-29,29>>^ Derrete teu ouro e tua prata; faze uma balança para pesar as tuas palavras, e para a tua boca, um freio bem ajustado.^&#42;1^

[[v28-28-30]]

^<<v28-28-30,30>>^ Tem cuidado para não pecar pela língua, para não caíres na presença dos inimigos que te espreitam, e para que não venha o teu pecado a ser incurável e mortal.

'''

xref:028-eclesiastico/028-eclesiastico-027.adoc#v28-27-0[&#60; Capítulo Anterior] | <<v28-28-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-029.adoc#v28-29-0[Próximo Capítulo &#62;]