include::./index.adoc[]

[[v28-34-0]]
=== Eclesiástico, 34
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 34 de Eclesiástico trata da importância de não colocar a confiança em divindades falsas, da prática da virtude e da justiça, e de evitar o orgulho e a arrogância. A seguir estão cinco versículos relacionados com esses temas:
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." Este versículo destaca a importância de confiar em Deus em vez de seguir nossos próprios desejos e interesses.
* Salmo 33:4-5: "Porque a palavra do Senhor é reta e todas as suas obras são fiéis. Ele ama a justiça e o direito; a terra está cheia da bondade do Senhor." Esse verso enfatiza a importância da justiça e da retidão, que são temas abordados em Eclesiástico 34.
* Provérbios 16:18: "O orgulho precede a ruína, e a arrogância precede a queda." Este versículo adverte contra o perigo do orgulho e da arrogância, o que é discutido em Eclesiástico 34.
* 1 Pedro 3:10: "Pois quem quer amar a vida e ver dias bons, refreie a língua do mal e evite que os seus lábios falem enganosamente." Esse versículo destaca a importância da virtude e da fala honesta, que são temas importantes em Eclesiástico 34.
* Salmo 40:4: "Bem-aventurado é o homem que faz do Senhor a sua confiança e que não se volta para os soberbos, nem para os que se desviam para a mentira." Este versículo destaca a importância de confiar em Deus em vez de se envolver com pessoas orgulhosas e mentirosas, o que é um tema em Eclesiástico 34.
****

[[v28-34-1]]

^<<v28-34-1,1>>^ O insensato vive de esperanças quiméricas; os imprudentes edificam sobre os sonhos.^&#42;1^

[[v28-34-2]]

^<<v28-34-2,2>>^ Como aquele que procura agarrar uma sombra ou perseguir o vento, assim é o que se prende a visões enganadoras.

[[v28-34-3]]

^<<v28-34-3,3>>^ Isto segundo aquilo, eis o que se vê nos sonhos: é como a imagem de um homem diante dele próprio.^&#42;1^

[[v28-34-4]]

^<<v28-34-4,4>>^ Que coisa pura poderá vir do impuro? Que verdade pode vir da mentira?

[[v28-34-5]]

^<<v28-34-5,5>>^ A adivinhação do erro, os augúrios mentirosos e os sonhos dos maus, tudo isso não passa de vaidade.

[[v28-34-6]]

^<<v28-34-6,6>>^ O teu coração, como o de uma mulher que está de parto, sofrerá imaginações. A menos que o Altíssimo te envie uma visão, não detenhas nelas teu pensamento,^&#42;1^

[[v28-34-7]]

^<<v28-34-7,7>>^ pois os sonhos fizeram errar muita gente, que pecou porque neles punham sua esperança;

[[v28-34-8]]

^<<v28-34-8,8>>^ a palavra da Lei se cumpre integralmente, e a sabedoria se tornará evidente na boca do homem fiel.

[[v28-34-9]]

^<<v28-34-9,9>>^ Que sabe aquele que não foi experimentado? O homem de grande experiência tem inúmeras ideias; aquele que muito aprendeu fala com sabedoria.

[[v28-34-10]]

^<<v28-34-10,10>>^ Aquele que não tem experiência pouca coisa sabe, mas o que passou por muitas dificuldades desenvolve a prudência.

[[v28-34-11]]

^<<v28-34-11,11>>^ Que sabe aquele que não foi tentado? O que foi enganado abundará em sagacidade.

[[v28-34-12]]

^<<v28-34-12,12>>^ Vi muitas coisas em minhas viagens, muitos costumes diferentes.^&#42;1^

[[v28-34-13]]

^<<v28-34-13,13>>^ Algumas vezes encontrei-me em perigo de morte, mas fui libertado pela graça de Deus.

[[v28-34-14]]

^<<v28-34-14,14>>^ O espírito daqueles que temem a Deus será procurado, será abençoado quando Deus olhar para eles.^&#42;1^

[[v28-34-15]]

^<<v28-34-15,15>>^ Com efeito, sua esperança está posta naquele que os salva, e os olhos de Deus estão voltados para aqueles que o amam.

[[v28-34-16]]

^<<v28-34-16,16>>^ Aquele que teme o Senhor não tremerá; de nada terá medo, pois o próprio Senhor é sua esperança.

[[v28-34-17]]

^<<v28-34-17,17>>^ Feliz a alma do que teme o Senhor.

[[v28-34-18]]

^<<v28-34-18,18>>^ Para quem olha ela, e quem é a sua força?

[[v28-34-19]]

^<<v28-34-19,19>>^ Os olhos do Senhor estão voltados para aqueles que o temem; ele é um poderoso protetor, um sólido apoio, um abrigo contra o calor, uma tela contra o ardor do meio-dia,

[[v28-34-20]]

^<<v28-34-20,20>>^ um sustentáculo contra os choques, um amparo contra a queda. Ele eleva a alma, ilumina os olhos; dá saúde, vida e bênção.

[[v28-34-21]]

^<<v28-34-21,21>>^ A oferenda daquele que sacrifica um bem, mal adquirido, é maculada. E os insultos dos injustos não são aceitos por Deus.

[[v28-34-22]]

^<<v28-34-22,22>>^ O Senhor (só se dá) àqueles que o aguardam no caminho da verdade e da justiça.

[[v28-34-23]]

^<<v28-34-23,23>>^ O Altíssimo não aprova as dádivas dos injustos, nem olha para as ofertas dos maus; a multidão dos seus sacrifícios não lhes conseguirá o perdão de seus pecados.

[[v28-34-24]]

^<<v28-34-24,24>>^ Aquele que oferece um sacrifício arrancado do dinheiro dos pobres é como o que degola o filho aos olhos do pai.

[[v28-34-25]]

^<<v28-34-25,25>>^ O pão dos indigentes é a vida dos pobres; aquele que o tira é um homicida.

[[v28-34-26]]

^<<v28-34-26,26>>^ Quem tira de um homem o pão de seu trabalho é como o assassino do seu próximo.

[[v28-34-27]]

^<<v28-34-27,27>>^ O que derrama o sangue e o que usa de fraude no pagamento de um operário são irmãos:

[[v28-34-28]]

^<<v28-34-28,28>>^ um constrói, o outro destrói. O que lhes resta senão a fadiga?

[[v28-34-29]]

^<<v28-34-29,29>>^ Um ora, o outro maldiz; de qual ouvirá Deus a voz?

[[v28-34-30]]

^<<v28-34-30,30>>^ Se aquele que se lava após ter tocado num morto torna a tocá-lo, de que lhe serve ter-se lavado?

[[v28-34-31]]

^<<v28-34-31,31>>^ Assim se porta o homem que jejua por causa de seus pecados, e torna a cometê-los: de que lhe serve ter-se humilhado? Quem ouvirá a sua prece?

'''

xref:028-eclesiastico/028-eclesiastico-033.adoc#v28-33-0[&#60; Capítulo Anterior] | <<v28-34-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-035.adoc#v28-35-0[Próximo Capítulo &#62;]