include::./index.adoc[]

[[v28-20-0]]
=== Eclesiástico, 20
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 20 aborda o tema da sabedoria em relação aos comportamentos humanos, enfatizando a importância da humildade e da autocontenção. O capítulo começa com uma discussão sobre a hipocrisia e a imprudência, mostrando como elas podem levar a situações desastrosas. Em seguida, o autor enfatiza a importância de ouvir e aprender com os outros, bem como a necessidade de manter a modéstia e a humildade em todas as situações.
* Provérbios 17:27: "Quem tem conhecimento é comedido em suas palavras; quem tem entendimento é de espírito sereno." Este versículo destaca a importância da autocontenção e da moderação no discurso, um tema abordado em Eclesiástico 20.
* Tiago 1:19: "Meus amados irmãos, cada um deve ser pronto para ouvir, tardio para falar e tardio para se irar." Esse versículo destaca a importância de ouvir e aprender com os outros, um tema que também é abordado em Eclesiástico 20.
* Provérbios 22:4: "O fruto da humildade é o temor do Senhor, riquezas, honra e vida." Este versículo destaca a importância da humildade e da modéstia, um tema central em Eclesiástico 20.
* Provérbios 13:10: "Com arrogância, só se provoca rixas, mas com os que sabem ouvir se evita a contenda." Este versículo enfatiza a importância de evitar a arrogância e a imprudência, temas abordados em Eclesiástico 20.
* Provérbios 19:20: "Ouve o conselho e aceita a correção, para que te tornes sábio no futuro." Este versículo enfatiza a importância de ouvir e aprender com os outros, um tema importante em Eclesiástico 20.
****

[[v28-20-1]]

^<<v28-20-1,1>>^ Oh! Quanto melhor é admoestar que irritar-se, não impedir de falar aquele que quer confessar a sua falta!^&#42;1^

[[v28-20-2]]

^<<v28-20-2,2>>^ Como o eunuco que anseia por violentar uma donzela,

[[v28-20-3]]

^<<v28-20-3,3>>^ assim é o que, por violência, faz um julgamento iníquo.

[[v28-20-4]]

^<<v28-20-4,4>>^ Como é bom que o corrigido manifeste o seu arrependimento! Pois assim se evita um pecado voluntário.

[[v28-20-5]]

^<<v28-20-5,5>>^ Há quem se cale e é considerado sábio, e quem se torne odioso pela intemperança no falar.

[[v28-20-6]]

^<<v28-20-6,6>>^ Há quem se cale por não saber falar, e há quem se cale porque reconhece quando é tempo (de falar).

[[v28-20-7]]

^<<v28-20-7,7>>^ O sábio permanece calado até o momento (oportuno), mas o leviano e imprudente não espera a ocasião.

[[v28-20-8]]

^<<v28-20-8,8>>^ Aquele que se expande em palavras, prejudica-se a si mesmo; quem se permite todo o desregramento torna-se odioso.

[[v28-20-9]]

^<<v28-20-9,9>>^ Para o homem desprovido de instrução há proveito na infelicidade, mas há certas descobertas que lhe acarretam a ruína.

[[v28-20-10]]

^<<v28-20-10,10>>^ Há dom que não é útil e há dom que é duplamente recompensado.

[[v28-20-11]]

^<<v28-20-11,11>>^ Há quem ache a sua perda na própria glória, e há quem levantará a cabeça após uma humilhação.

[[v28-20-12]]

^<<v28-20-12,12>>^ Há quem compre muito por um preço módico, mas que (de fato) o paga pelo sétuplo do seu valor.

[[v28-20-13]]

^<<v28-20-13,13>>^ O sábio torna-se amável por suas palavras, enquanto que os encantos do insensato desaparecem.

[[v28-20-14]]

^<<v28-20-14,14>>^ O donativo do insensato não te trará proveito, pois ele te fixa com sete olhos.

[[v28-20-15]]

^<<v28-20-15,15>>^ Ele dá pouco e censura muitas vezes; quando abre a sua boca é como uma fogueira.

[[v28-20-16]]

^<<v28-20-16,16>>^ Há quem empresta hoje e amanhã o reclama: tal homem é odioso.

[[v28-20-17]]

^<<v28-20-17,17>>^ O insensato não tem amigos, e pelo bem que faz não será bem acatado,^&#42;1^

[[v28-20-18]]

^<<v28-20-18,18>>^ porque os que comem o seu pão têm línguas falsas; quantas e quantas vezes não zombarão dele?

[[v28-20-19]]

^<<v28-20-19,19>>^ Pois não agiu com bom senso, distribuindo o que devia guardar e o que não devia guardar.

[[v28-20-20]]

^<<v28-20-20,20>>^ A queda de uma língua mentirosa é como uma queda na laje; assim a ruína dos maus virá de repente.

[[v28-20-21]]

^<<v28-20-21,21>>^ Um homem desagradável é como uma história ruim, que se acha continuamente na boca das pessoas mal-educadas.

[[v28-20-22]]

^<<v28-20-22,22>>^ Será mal recebida a máxima que sair da boca do insensato, pois que ele a diz fora de tempo.

[[v28-20-23]]

^<<v28-20-23,23>>^ Há quem se abstenha de pecar por falta de meios, mas ressente o aguilhão do pecado até em seu repouso.^&#42;1^

[[v28-20-24]]

^<<v28-20-24,24>>^ Há quem perca a sua alma por causa do respeito humano; perde-a, cedendo a uma pessoa imprudente; perde-se por atender demasiadamente uma pessoa.

[[v28-20-25]]

^<<v28-20-25,25>>^ Há quem, por falsa vergonha, faça uma promessa a um amigo, e dele se faça gratuitamente um inimigo.

[[v28-20-26]]

^<<v28-20-26,26>>^ A mentira é no homem uma vergonhosa mancha: não deixa os lábios das pessoas mal-educadas.

[[v28-20-27]]

^<<v28-20-27,27>>^ Mais vale um ladrão do que um mentiroso contumaz, mas ambos terão a ruína como partilha.

[[v28-20-28]]

^<<v28-20-28,28>>^ O comportamento dos mentirosos é aviltante, sua vergonha jamais os abandonará.

[[v28-20-29]]

^<<v28-20-29,29>>^ O sábio atrai a si a estima por suas palavras; o homem prudente agradará aos poderosos.

[[v28-20-30]]

^<<v28-20-30,30>>^ Quem cultiva sua terra colherá montes de frutos; quem cultiva a justiça será ele próprio elevado; quem agrada aos poderosos fugirá da iniquidade.

[[v28-20-31]]

^<<v28-20-31,31>>^ Os presentes e as dádivas cegam os olhos dos juízes. São em sua boca como um freio que os torna mudos e os impede de castigar.^&#42;1^

[[v28-20-32]]

^<<v28-20-32,32>>^ Sabedoria escondida é tesouro invisível. Para que serve uma e outro?

[[v28-20-33]]

^<<v28-20-33,33>>^ Mais vale aquele que dissimula sua insipiência, do que aquele que esconde sua sabedoria.

'''

xref:028-eclesiastico/028-eclesiastico-019.adoc#v28-19-0[&#60; Capítulo Anterior] | <<v28-20-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-021.adoc#v28-21-0[Próximo Capítulo &#62;]