include::./index.adoc[]

[[v28-16-0]]
=== Eclesiástico, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 16 trata da grandiosidade de Deus, de Sua providência e soberania sobre a criação. O autor destaca a bondade de Deus em dar vida e cuidar de Sua criação, bem como a importância da obediência e do temor a Ele. A seguir estão cinco versículos relacionados com esses temas:
* Salmos 24:1: "Do Senhor é a terra e tudo o que nela existe, o mundo e os que nele vivem." Esse versículo fala da soberania de Deus sobre toda a criação. Ele é o dono da terra e de tudo o que nela existe, inclusive de todos os seres humanos.
* Atos 17:28: "Pois nele vivemos, nos movemos e existimos, como disseram alguns dos poetas de vocês: 'Também somos descendência dele'." Esse versículo destaca a dependência dos seres humanos em relação a Deus. É por meio dEle que vivemos, nos movemos e existimos.
* Jó 38:4: "Onde estavas tu quando eu lancei os alicerces da terra? Dize-mo, se tens entendimento." Essa pergunta de Deus a Jó destaca a grandeza e a sabedoria de Deus na criação. Ele é o autor de tudo o que existe e conhece profundamente cada detalhe da criação.
* Salmos 145:9: "O Senhor é bom para todos; a sua compaixão alcança todas as suas criaturas." Esse versículo fala da bondade de Deus para com a Sua criação. Ele cuida de todas as Suas criaturas, desde as maiores até as menores.
* Provérbios 9:10: "O temor do Senhor é o princípio da sabedoria, e o conhecimento do Santo é entendimento." Esse versículo destaca a importância do temor a Deus e do conhecimento dEle como base para a sabedoria e o entendimento. O autor de Eclesiástico 16 também enfatiza a importância do temor a Deus em sua reflexão sobre a grandiosidade divina.
****

[[v28-16-1]]

^<<v28-16-1,1>>^ Não te regozijes de ter muitos filhos se são maus, nem ponhas neles a tua alegria, se não tiverem o temor de Deus.

[[v28-16-2]]

^<<v28-16-2,2>>^ Não confies na sua vida, nem voltes os teus olhares para os seus trabalhos;

[[v28-16-3]]

^<<v28-16-3,3>>^ pois um único filho temente a Deus vale mais do que mil filhos ímpios.

[[v28-16-4]]

^<<v28-16-4,4>>^ Há mais vantagens em morrer sem filhos, que em deixar após si filhos ímpios.

[[v28-16-5]]

^<<v28-16-5,5>>^ Um único homem sensato fará povoar a pátria, enquanto que um país de maus se tornará deserto.

[[v28-16-6]]

^<<v28-16-6,6>>^ Vi com meus olhos inúmeros exemplos, e meus ouvidos ouviram alguns ainda mais graves.

[[v28-16-7]]

^<<v28-16-7,7>>^ O fogo se acenderá na assembleia dos maus, e a cólera se inflamará sobre um povo incrédulo.

[[v28-16-8]]

^<<v28-16-8,8>>^ Os gigantes não imploraram o perdão de seus pecados, e foram destruídos, apesar de terem confiado na própria força.^&#42;1^

[[v28-16-9]]

^<<v28-16-9,9>>^ Deus não poupou a terra onde residia Ló, mas abominou os seus habitantes por causa de sua insolência.

[[v28-16-10]]

^<<v28-16-10,10>>^ Não teve pena deles, exterminou a nação inteira, que se engrandecia com o orgulho, apesar de seus pecados.^&#42;1^

[[v28-16-11]]

^<<v28-16-11,11>>^ Assim aconteceu com os seiscentos mil homens vivos que se haviam reunido na dureza de coração; ainda que um único se tivesse mostrado obstinado, seria para admirar que não tivesse sido castigado,

[[v28-16-12]]

^<<v28-16-12,12>>^ pois misericórdia e ira estão sempre em Deus, grandemente misereclodioso, porém capaz de cólera.

[[v28-16-13]]

^<<v28-16-13,13>>^ Os seus castigos igualam sua misericórdia; ele julga o homem conforme as suas obras.

[[v28-16-14]]

^<<v28-16-14,14>>^ O pecador não escapará em suas rapinas, e não será postergada a espera daquele que exerce a misericórdia;

[[v28-16-15]]

^<<v28-16-15,15>>^ toda a misericórdia colocará cada um em seu lugar, conforme o mérito de suas obras e a sabedoria de seu comportamento.^&#42;1^

[[v28-16-16]]

^<<v28-16-16,16>>^ Não digas: “Eu me furtarei aos olhos de Deus; quem se lembrará de mim no alto do céu?^&#42;1^

[[v28-16-17]]

^<<v28-16-17,17>>^ Não serei reconhecido no meio da multidão; quem sou eu no meio de uma tal multidão de criaturas?”.

[[v28-16-18]]

^<<v28-16-18,18>>^ Eis que o céu e o céu dos céus, o abismo, a terra inteira e tudo o que encerram se abalarão quando ele aparecer.

[[v28-16-19]]

^<<v28-16-19,19>>^ As montanhas, as colinas e os alicerces da terra tremerão de pavor quando Deus os olhar.

[[v28-16-20]]

^<<v28-16-20,20>>^ No meio de tudo isso, o coração do homem é insensato; Deus, porém, conhece todos os corações.

[[v28-16-21]]

^<<v28-16-21,21>>^ Quem é aquele que compreende os caminhos de Deus, e a tempestade que escapa aos olhos do homem?

[[v28-16-22]]

^<<v28-16-22,22>>^ Com efeito, a maior parte de suas obras está oculta; quem anunciará, quem poderá suportar os efeitos de sua justiça? Pois as sentenças divinas estão longe do pensamento de muitos, e o exame geral só se realizará no último dia.^&#42;1^

[[v28-16-23]]

^<<v28-16-23,23>>^ O homem de coração mesquinho só pensa em vaidades; o imprudente e extraviado só se ocupa de loucuras.

[[v28-16-24]]

^<<v28-16-24,24>>^ Meu filho, ouve-me, adquire uma instrução sadia, torna o teu coração atento às minhas palavras.

[[v28-16-25]]

^<<v28-16-25,25>>^ Eu te darei um ensino muito exato, vou tentar explicar-te o que é a sabedoria; torna o teu coração atento às minhas palavras, pois vou descrever-te com exatidão as maravilhas que Deus, desde o início, fez brilhar nas suas obras, e vou expor, com toda a veracidade, o conhecimento de Deus.

[[v28-16-26]]

^<<v28-16-26,26>>^ Por decreto de Deus suas obras existem desde o começo; desde a criação distinguiu-as em partes. Colocou as principais em suas épocas,^&#42;1^

[[v28-16-27]]

^<<v28-16-27,27>>^ adornou-as para sempre; elas não sentiram necessidade nem fadiga, e nunca interromperam o seu trabalho.

[[v28-16-28]]

^<<v28-16-28,28>>^ Nunca nenhuma delas embaraçou a vizinha.

[[v28-16-29]]

^<<v28-16-29,29>>^ Não sejas incrédulo à palavra do Senhor.^&#42;1^

[[v28-16-30]]

^<<v28-16-30,30>>^ Depois disso, olhou Deus para a terra, e encheu-a de benefícios.

[[v28-16-31]]

^<<v28-16-31,31>>^ É o que revela sobre a terra a alma de todo ser vivo, e é ao seu seio que todos eles voltam.

'''

xref:028-eclesiastico/028-eclesiastico-015.adoc#v28-15-0[&#60; Capítulo Anterior] | <<v28-16-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-017.adoc#v28-17-0[Próximo Capítulo &#62;]