include::./index.adoc[]

[[v28-22-0]]
=== Eclesiástico, 22
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 22 discute o tema da sabedoria e da tolice, bem como a necessidade de ser cauteloso em relação às palavras que se dizem. O capítulo também adverte contra o orgulho e a arrogância, e enfatiza a importância de buscar a orientação de Deus.
* Provérbios 12:15: "O caminho do insensato parece-lhe recto, mas o sábio escuta o conselho." Este versículo destaca a diferença entre os tolos e os sábios, e sugere que a tolice pode levar a um pensamento errado e imprudente.
* Provérbios 29:20: "Tens visto o homem precipitado em suas palavras? Há mais esperança para o insensato do que para ele." Esse versículo adverte contra a imprudência na fala e sugere que pode haver mais esperança para aqueles que são insensatos do que para aqueles que falam sem pensar.
* Provérbios 16:18: "A soberba precede a ruína, e a altivez do espírito precede a queda." Este versículo destaca o perigo da arrogância e do orgulho, enfatizando que aqueles que são soberbos são mais propensos a cair.
* Provérbios 10:19: "Na multidão de palavras não falta pecado, mas o que modera os seus lábios é sábio." Esse versículo sugere que falar demais pode levar a erros e pecados, e enfatiza a importância de escolher cuidadosamente as palavras que se dizem.
* Provérbios 3:5-6: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." Este versículo enfatiza a importância de confiar em Deus e buscar a Sua orientação em todas as coisas, incluindo a sabedoria e a prudência nas palavras e ações.
****

[[v28-22-1]]

^<<v28-22-1,1>>^ Ao preguiçoso é atirado esterco, só se fala dele com desprezo.^&#42;1^

[[v28-22-2]]

^<<v28-22-2,2>>^ O preguiçoso é apedrejado com excremento, quem o tocar sacudirá a mão.

[[v28-22-3]]

^<<v28-22-3,3>>^ O filho mal-educado é a vergonha de seu pai, a filha semelhante não gozará de nenhuma consideração.

[[v28-22-4]]

^<<v28-22-4,4>>^ Uma jovem prudente é uma herança para o marido, mas a filha desavergonhada causa mágoa ao seu pai.^&#42;1^

[[v28-22-5]]

^<<v28-22-5,5>>^ A mulher atrevida cobre de vergonha o pai e o marido; e é igual aos celerados: ambos a desprezam.

[[v28-22-6]]

^<<v28-22-6,6>>^ Uma palavra inoportuna é música em dia de luto; a sabedoria, porém, emprega com oportunidade o chicote e a instrução.

[[v28-22-7]]

^<<v28-22-7,7>>^ Instruir um insensato é tornar a ajustar um vaso quebrado;

[[v28-22-8]]

^<<v28-22-8,8>>^ falar a quem não ouve é como despertar alguém de um sono profundo.

[[v28-22-9]]

^<<v28-22-9,9>>^ Falar da sabedoria com um insensato é conversar com alguém que está adormecendo; no fim da conversa ele dirá: “Que?”.

[[v28-22-10]]

^<<v28-22-10,10>>^ Chora sobre um morto, porque ele perdeu a luz; chora sobre um tolo, porque é falho de juízo.

[[v28-22-11]]

^<<v28-22-11,11>>^ Chora menos sobre um morto, porque ele achou o repouso;

[[v28-22-12]]

^<<v28-22-12,12>>^ a vida criminosa do mau, porém, é pior do que a morte.

[[v28-22-13]]

^<<v28-22-13,13>>^ O luto por um morto dura sete dias, mas por um insensato e um ímpio, dura toda a sua vida.

[[v28-22-14]]

^<<v28-22-14,14>>^ Não fales muito com um estulto; não convivas com o insensato.

[[v28-22-15]]

^<<v28-22-15,15>>^ Acautela-te contra ele, para não seres incomodado; e não te mancharás com o contágio de seu pecado.

[[v28-22-16]]

^<<v28-22-16,16>>^ Afasta-te dele: encontrarás repouso, e a sua loucura não te causará mágoa.

[[v28-22-17]]

^<<v28-22-17,17>>^ O que há de mais pesado que o chumbo? E que outro nome dar-lhe a não ser o de insensato?

[[v28-22-18]]

^<<v28-22-18,18>>^ É mais fácil carregar areia, sal ou uma barra de ferro, do que suportar o imprudente, o tolo e o ímpio.

[[v28-22-19]]

^<<v28-22-19,19>>^ Um encaixamento de madeira adaptado aos alicerces de um edifício não se desconjunta. Assim é o coração firmado por uma decisão bem amadurecida.

[[v28-22-20]]

^<<v28-22-20,20>>^ O desígnio de um homem sensato, em qualquer tempo que seja, não será alterado pelo temor.

[[v28-22-21]]

^<<v28-22-21,21>>^ Como a estacada posta em lugar elevado e a parede sem argamassa não podem resistir à violência do vento,

[[v28-22-22]]

^<<v28-22-22,22>>^ assim um coração tímido, de pensamentos tolos, não pode resistir ao choque do temor.

[[v28-22-23]]

^<<v28-22-23,23>>^ O coração medroso do insensato jamais tem temor em seus pensamentos; assim também o que não se apoia nos preceitos divinos.

[[v28-22-24]]

^<<v28-22-24,24>>^ Quem machuca um olho, dele faz sair lágrimas; quem magoa um coração, nele excita a sensibilidade.

[[v28-22-25]]

^<<v28-22-25,25>>^ Quem lança uma pedra aos pássaros os fará fugir; assim, quem insulta um amigo rompe a amizade.

[[v28-22-26]]

^<<v28-22-26,26>>^ Ainda que tenhas arrancado a espada contra o teu amigo, não desesperes; porque o regresso é possível.

[[v28-22-27]]

^<<v28-22-27,27>>^ Ainda que tenhas dito contra ele palavras desagradáveis, não temas, porque a reconciliação é possível, salvo se se tratar de injúrias, afrontas, insolências, revelação de um segredo ou golpes à traição; em todos esses casos fugirá de ti o teu amigo.

[[v28-22-28]]

^<<v28-22-28,28>>^ Permanece fiel ao teu amigo em sua pobreza, a fim de te alegrares com ele na sua prosperidade.

[[v28-22-29]]

^<<v28-22-29,29>>^ Permanece-lhe fiel no tempo da aflição, a fim de teres parte com ele em sua herança.

[[v28-22-30]]

^<<v28-22-30,30>>^ O vapor e a fumaça elevam-se na fornalha antes do fogo; assim o homicídio e o derramamento de sangue são precedidos de injúrias, ultrajes e ameaças.

[[v28-22-31]]

^<<v28-22-31,31>>^ Não me envergonharei de saudar um amigo, nem me esconderei da sua presença; e, se me acontecer algum mal por isso, eu o suportarei,

[[v28-22-32]]

^<<v28-22-32,32>>^ mas quem o souber, dele desconfiará.

[[v28-22-33]]

^<<v28-22-33,33>>^ Quem porá uma guarda à minha boca, e um selo inviolável nos meus lábios, para que eu não caia por sua causa, e para que minha língua não me perca?

'''

xref:028-eclesiastico/028-eclesiastico-021.adoc#v28-21-0[&#60; Capítulo Anterior] | <<v28-22-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-023.adoc#v28-23-0[Próximo Capítulo &#62;]