include::./index.adoc[]

[[v28-51-0]]
=== Eclesiástico, 51
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 51 de Eclesiástico é uma oração de agradecimento e louvor a Deus, na qual o autor reconhece a ação divina em sua vida e pede perdão por seus pecados. Dessa forma, os versículos selecionados terão relação com essa temática:
* Salmos 30:12: "Para que a minha glória a ti cante louvores, e não se cale. Senhor, Deus meu, eu te louvarei para sempre." Este salmo é uma oração de agradecimento a Deus pela cura e salvação, e pode ser relacionado com o tema de agradecimento presente em Eclesiástico 51.
* Salmos 103:2: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios." Este salmo é uma exortação para que a alma louve e agradeça a Deus por todos os seus benefícios, e pode ser relacionado com a temática de gratidão presente em Eclesiástico 51.
* Isaías 55:6-7: "Buscai o Senhor enquanto se pode achar, invocai-o enquanto está perto. Deixe o ímpio o seu caminho, e o homem maligno os seus pensamentos, e se converta ao Senhor, que se compadecerá dele; e volte para o nosso Deus, porque é rico em perdoar." Este trecho de Isaías é uma exortação ao arrependimento e à busca de Deus, que pode ser relacionado com a temática de confissão presente em Eclesiástico 51.
* 1 João 1:9: "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados, e nos purificar de toda a injustiça." Este versículo de 1 João destaca a importância da confissão dos pecados e do perdão divino, e pode ser relacionado com o tema de arrependimento e perdão presentes em Eclesiástico 51.
* Salmos 51:10: "Cria em mim, ó Deus, um coração puro, e renova em mim um espírito reto." Este salmo é uma oração de arrependimento e confissão dos pecados, e pode ser relacionado com a temática presente em Eclesiástico 51, na qual o autor pede perdão a Deus por seus erros e agradece pela misericórdia divina.
****

[[v28-51-1]]

^<<v28-51-1,1>>^ Eu vos glorificarei, ó Senhor e rei, eu vos louvarei, ó Deus, meu salvador.

[[v28-51-2]]

^<<v28-51-2,2>>^ Glorificarei o vosso nome, porque fostes meu auxílio e meu protetor.

[[v28-51-3]]

^<<v28-51-3,3>>^ Livrastes meu corpo da perdição, das ciladas da língua injusta, e dos lábios dos forjadores de mentira. Fostes meu apoio contra aqueles que me acusavam.

[[v28-51-4]]

^<<v28-51-4,4>>^ Libertastes-me conforme a extensão da misericórdia de vosso nome, dos rugidos dos animais ferozes, prestes a me devorar;

[[v28-51-5]]

^<<v28-51-5,5>>^ da mão daqueles que atacavam a minha vida, do assalto das tribulações que me aturdiam,

[[v28-51-6]]

^<<v28-51-6,6>>^ e da violência das chamas que me rodeavam. Em meio ao fogo não me queimei.^&#42;1^

[[v28-51-7]]

^<<v28-51-7,7>>^ Libertastes-me das profundas entranhas da morada dos mortos, da língua maculada, das palavras mentirosas, do rei iníquo e da língua injusta.^&#42;1^

[[v28-51-8]]

^<<v28-51-8,8>>^ Minha alma louvará o Senhor até a morte,^&#42;1^

[[v28-51-9]]

^<<v28-51-9,9>>^ porque a minha vida estava prestes a cair nas profundezas da região dos mortos.

[[v28-51-10]]

^<<v28-51-10,10>>^ Eles me rodearam de todos os lados, e ninguém lá estava para ajudar-me. Esperava algum auxílio dos homens e nada veio.

[[v28-51-11]]

^<<v28-51-11,11>>^ Lembrei-me, Senhor, da vossa misericórdia, e de vossas obras que datam do princípio do mundo,

[[v28-51-12]]

^<<v28-51-12,12>>^ pois libertais, Senhor, aqueles que esperam em vós, e os salvais das mãos das nações.

[[v28-51-13]]

^<<v28-51-13,13>>^ Exaltastes a minha habitação sobre a terra, e eu vos roguei quando a morte se aproximou de mim;^&#42;1^

[[v28-51-14]]

^<<v28-51-14,14>>^ invoquei o Senhor, pai do meu Senhor, para que não me abandonasse no dia de minha aflição, sem socorro, durante o reinado dos soberbos.

[[v28-51-15]]

^<<v28-51-15,15>>^ Louvarei sem cessar o vosso nome; eu o glorificarei em meus louvores, porque foi ouvida a minha prece,

[[v28-51-16]]

^<<v28-51-16,16>>^ porque me livrastes da perdição, e salvastes-me do perigo num tempo de iniquidade.

[[v28-51-17]]

^<<v28-51-17,17>>^ Eis por que eu vos glorificarei e cantarei vossos louvores e bendirei o nome do Senhor.^&#42;1^

[[v28-51-18]]

^<<v28-51-18,18>>^ Quando eu era ainda jovem, antes de ter viajado, busquei abertamente a sabedoria na oração:

[[v28-51-19]]

^<<v28-51-19,19>>^ pedi-a a Deus no templo, e a buscarei até o fim de minha vida. Ela floresceu como uma videira precoce

[[v28-51-20]]

^<<v28-51-20,20>>^ e meu coração alegrou-se nela. Meus pés andaram por caminho reto: desde a minha juventude tenho procurado encontrá-la.

[[v28-51-21]]

^<<v28-51-21,21>>^ Apliquei um pouco o meu ouvido e logo a recolhi.

[[v28-51-22]]

^<<v28-51-22,22>>^ Encontrei em mim mesmo muita sabedoria, e nela fiz grande progresso.

[[v28-51-23]]

^<<v28-51-23,23>>^ Tributarei glória àquele que a deu a mim,

[[v28-51-24]]

^<<v28-51-24,24>>^ pois resolvi pô-la em prática; fui zeloso no bem e não serei confundido.

[[v28-51-25]]

^<<v28-51-25,25>>^ Lutou minha alma para atingi-la, robusteci-me, pondo-a em prática.

[[v28-51-26]]

^<<v28-51-26,26>>^ Levantei minhas mãos para o alto, e deplorei o erro do meu espírito.

[[v28-51-27]]

^<<v28-51-27,27>>^ Conduzi minha alma para ela, e encontrei-a, ao procurar conhecê-la.^&#42;1^

[[v28-51-28]]

^<<v28-51-28,28>>^ Desde o início, graças a ela, possuí o meu coração; eis por que não serei abandonado.

[[v28-51-29]]

^<<v28-51-29,29>>^ Minhas entranhas comoveram-se em procurá-la, e assim adquiri um bem precioso.

[[v28-51-30]]

^<<v28-51-30,30>>^ O Senhor deu-me como recompensa uma língua, e dela me servirei para louvá-lo.

[[v28-51-31]]

^<<v28-51-31,31>>^ Aproximai-vos de mim, ignorantes, reuni-vos na casa do ensino.

[[v28-51-32]]

^<<v28-51-32,32>>^ Por que tardais? Que direis a isto? Vossas almas estão violentamente perturbadas pela sede.^&#42;1^

[[v28-51-33]]

^<<v28-51-33,33>>^ Abri a boca e falei: Buscai a sabedoria sem dinheiro!

[[v28-51-34]]

^<<v28-51-34,34>>^ Dobrai a cabeça sob o jugo, receba vossa alma a instrução, porque perto se pode encontrá-la.

[[v28-51-35]]

^<<v28-51-35,35>>^ Vede com os vossos olhos o pouco que trabalhei, e como adquiri grande paz.

[[v28-51-36]]

^<<v28-51-36,36>>^ Recebei a instrução como uma grande soma de prata, e possuireis nela grande quantidade de ouro.

[[v28-51-37]]

^<<v28-51-37,37>>^ Que vossa alma se regozije na misericórdia (de Deus)! E não sereis humilhados quando o louvardes.

[[v28-51-38]]

^<<v28-51-38,38>>^ Cumpri vossa tarefa antes que o tempo (passe) e, no devido tempo, ele vos dará a recompensa.

'''

xref:028-eclesiastico/028-eclesiastico-050.adoc#v28-50-0[&#60; Capítulo Anterior] | <<v28-51-0,Topo>> | xref:029-isaias/029-isaias-001.adoc#v29-1-0[Próximo Capítulo &#62;]