include::./index.adoc[]

[[v28-43-0]]
=== Eclesiástico, 43
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 43 é um poema que descreve a grandeza e a beleza da criação divina, enfatizando a majestade do céu e das estrelas, bem como a variedade de seres vivos na terra. Aqui estão cinco versículos da Bíblia que se relacionam com os temas abordados em Eclesiástico 43:
* Salmos 8:3-4: "Quando vejo os teus céus, obra dos teus dedos, a lua e as estrelas que preparaste; Que é o homem mortal para que te lembres dele? E o filho do homem, para que o visites?" Este salmo fala da admiração do salmista pela criação de Deus e a pequenez da humanidade diante dela.
* Salmos 19:1: "Os céus declaram a glória de Deus e o firmamento anuncia a obra das suas mãos." Este versículo destaca a grandiosidade do céu como testemunha da grandeza e do poder divino.
* Jó 12:7-10: "Mas pergunta agora às alimárias, e cada uma delas te ensinará; e às aves dos céus, e elas te farão saber; Ou fala com a terra, e ela te ensinará; até os peixes do mar te declararão. Quem não entende por todas estas coisas que a mão do Senhor fez isto?" Jó reconhece a sabedoria e a grandeza da criação divina e o papel que cada criatura tem em sua obra.
* Provérbios 8:27-28: "Quando ele estabelecia os céus, ali estava eu; quando traçava o horizonte sobre a face do abismo; Quando firmava as nuvens acima; quando fortificava as fontes do abismo;" Este capítulo personifica a sabedoria como tendo um papel na criação divina e descreve como Deus ordenou o universo.
* Romanos 1:20: "Porque as suas coisas invisíveis, desde a criação do mundo, tanto o seu eterno poder, como a sua divindade, se entendem, e claramente se veem pelas coisas que estão criadas, para que eles fiquem inescusáveis;" Paulo afirma que a criação de Deus é um testemunho poderoso da sua existência e divindade.
****

[[v28-43-1]]

^<<v28-43-1,1>>^ O firmamento nas alturas é a sua beleza, o aspecto do céu é uma visão de glória.

[[v28-43-2]]

^<<v28-43-2,2>>^ O sol, aparecendo na aurora, anuncia o dia. A obra do Altíssimo é um instrumento admirável.

[[v28-43-3]]

^<<v28-43-3,3>>^ Ao meio-dia queima a terra: quem resiste ao seu ardor? Ele conserva uma fornalha de fogo por efeito de seu calor.^&#42;1^

[[v28-43-4]]

^<<v28-43-4,4>>^ O sol queima três vezes mais as montanhas, despedindo raios de fogo, cujo resplendor deslumbra os olhos.

[[v28-43-5]]

^<<v28-43-5,5>>^ Grande é o Senhor que o criou; por sua ordem, ele apressa o seu curso.

[[v28-43-6]]

^<<v28-43-6,6>>^ A lua é, em todas as suas fases regulares, a marca do tempo e o sinal do futuro.

[[v28-43-7]]

^<<v28-43-7,7>>^ É a lua que determina os dias de festa; sua luz diminui a partir da lua cheia.

[[v28-43-8]]

^<<v28-43-8,8>>^ É ela que dá nome ao mês; sua claridade cresce de modo admirável, até ficar cheia.

[[v28-43-9]]

^<<v28-43-9,9>>^ É um sinal para os exércitos do céu que lançam no firmamento um glorioso esplendor.

[[v28-43-10]]

^<<v28-43-10,10>>^ O brilho das estrelas faz a beleza do céu; o Senhor ilumina o mundo nas alturas.

[[v28-43-11]]

^<<v28-43-11,11>>^ À palavra do Santo estão prontas para o julgamento: são indefectivelmente vigilantes.

[[v28-43-12]]

^<<v28-43-12,12>>^ Observa o arco-íris e bendiz aquele que o fez: é muito belo no seu resplendor.

[[v28-43-13]]

^<<v28-43-13,13>>^ Faz a volta do céu num círculo de glória: são as mãos do Altíssimo que o estendem.

[[v28-43-14]]

^<<v28-43-14,14>>^ O Senhor com uma ordem faz cair subitamente a neve, acelera a marcha dos raios de seu juízo.

[[v28-43-15]]

^<<v28-43-15,15>>^ Por essa causa se abrem as suas reservas, e voam as nuvens como pássaros.

[[v28-43-16]]

^<<v28-43-16,16>>^ Por sua grandeza condensa as nuvens, e as pedras de granizo caem em estilhaços.

[[v28-43-17]]

^<<v28-43-17,17>>^ As montanhas são abaladas quando ele aparece; por sua vontade sopra o vento do sul.

[[v28-43-18]]

^<<v28-43-18,18>>^ O estrondo do trovão fere a terra, assim como a tempestade do aquilão e o turbilhão dos ventos.

[[v28-43-19]]

^<<v28-43-19,19>>^ Espalha a neve como pássaros que pousam, como gafanhotos que se abatem sobre a terra;

[[v28-43-20]]

^<<v28-43-20,20>>^ o olhar encanta-se com o brilho de sua alvura, o coração fica atônito ao vê-la cair.

[[v28-43-21]]

^<<v28-43-21,21>>^ Deus espalha a geada sobre a terra como sal; quando as águas se congelam tornam-se como pontas de cardo.

[[v28-43-22]]

^<<v28-43-22,22>>^ Quando sopra o vento frio do aquilão, a água gela como cristal, que repousa sobre toda a massa líquida, e veste as águas como se fosse uma couraça.

[[v28-43-23]]

^<<v28-43-23,23>>^ A geada devora os montes, queima os desertos, resseca como o fogo tudo o que é verde.^&#42;1^

[[v28-43-24]]

^<<v28-43-24,24>>^ O remédio para isso é o rápido aparecimento de um aguaceiro. O orvalho após o frio atenua o rigor do gelo.

[[v28-43-25]]

^<<v28-43-25,25>>^ A palavra de Deus faz calar o vento; só com o seu pensar apazigua o abismo, no meio do qual o Senhor plantou as ilhas.

[[v28-43-26]]

^<<v28-43-26,26>>^ Os que navegam sobre o mar contam os seus perigos; ouvindo-os, ficaremos arrebatados de admiração.

[[v28-43-27]]

^<<v28-43-27,27>>^ Ali se encontram grandes obras e maravilhas, animais de toda espécie e criaturas monstruosas.

[[v28-43-28]]

^<<v28-43-28,28>>^ Por ele, tudo tende regularmente para a sua finalidade, tudo foi disposto conforme a sua palavra.

[[v28-43-29]]

^<<v28-43-29,29>>^ Diremos muitas coisas, porém faltarão palavras. Mas o resumo de nosso discurso é este: ele está em tudo.^&#42;1^

[[v28-43-30]]

^<<v28-43-30,30>>^ Que podemos nós fazer para glorificá-lo? Pois o Todo-poderoso está acima de todas as suas obras.

[[v28-43-31]]

^<<v28-43-31,31>>^ O Senhor é terrível e soberanamente grande. Seu poder é maravilhoso.

[[v28-43-32]]

^<<v28-43-32,32>>^ Glorificai o Senhor quanto puderdes, que ele ficará sempre acima, porque é admirável a sua grandeza.

[[v28-43-33]]

^<<v28-43-33,33>>^ Bendizei o Senhor, exaltai-o com todas as vossas forças, pois ele está acima de todo louvor.

[[v28-43-34]]

^<<v28-43-34,34>>^ Enaltecendo-o, reuni todas as vossas forças; não desanimeis; jamais chegareis (ao fim).

[[v28-43-35]]

^<<v28-43-35,35>>^ Quem poderá contar o que dele viu? Quem é capaz de louvá-lo, como ele é, desde os primórdios?

[[v28-43-36]]

^<<v28-43-36,36>>^ Muitos segredos são maiores que tudo isso; só vemos um pequeno número de suas obras.

[[v28-43-37]]

^<<v28-43-37,37>>^ O Senhor fez todas as coisas: ele dá sabedoria àqueles que vivem com piedade.

'''

xref:028-eclesiastico/028-eclesiastico-042.adoc#v28-42-0[&#60; Capítulo Anterior] | <<v28-43-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-044.adoc#v28-44-0[Próximo Capítulo &#62;]