include::./index.adoc[]

[[v28-39-0]]
=== Eclesiástico, 39
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 39 é um capítulo que exalta a sabedoria de Deus e fala sobre a grandeza de suas obras. Nele, é destacada a importância de se buscar a sabedoria divina e de se glorificar o Senhor através de suas obras. Abaixo, seguem cinco versículos relacionados com os temas abordados nesse capítulo:
* Salmos 111:10: "O temor do Senhor é o princípio da sabedoria; todos os que cumprem seus preceitos revelam bom senso. Ele será louvado para sempre." Este versículo destaca a importância de temer a Deus e de obedecer aos seus preceitos como uma forma de adquirir sabedoria e discernimento.
* Jó 28:28: "E ele disse ao homem: 'O temor do Senhor é a sabedoria; o afastar-se do mal é o entendimento'." Aqui, é novamente enfatizada a importância do temor a Deus como base para a sabedoria, mas também é mencionado o papel de se afastar do mal para alcançar o entendimento.
* Provérbios 2:6-7: "Porque o Senhor dá a sabedoria; da sua boca vêm o conhecimento e o entendimento. Ele reserva a sensatez para os justos, é um escudo para os que caminham com integridade." Esses versículos destacam que a sabedoria vem de Deus e que é uma proteção para aqueles que vivem com integridade.
* Salmos 104:24: "Quantas são as tuas obras, Senhor! Fizeste todas elas com sabedoria; a terra está cheia de seres que criaste." Nesse versículo, é enfatizada a grandeza das obras de Deus e a sabedoria com que elas foram feitas.
* Provérbios 3:19: "O Senhor com sabedoria fundou a terra; com entendimento estabeleceu os céus." Aqui, é ressaltado que Deus usou sua sabedoria para criar a terra e estabelecer os céus. Isso reforça a ideia de que a sabedoria vem de Deus e que é importante buscá-la para compreender a grandiosidade de suas obras.
****

[[v28-39-1]]

^<<v28-39-1,1>>^ O sábio procura cuidadosamente a sabedoria de todos os antigos, e aplica-se ao estudo dos profetas.

[[v28-39-2]]

^<<v28-39-2,2>>^ Guarda no coração as narrativas dos homens célebres, e penetra ao mesmo tempo nos mistérios das máximas.

[[v28-39-3]]

^<<v28-39-3,3>>^ Penetra nos segredos dos provérbios, e vive com o sentido oculto das parábolas.

[[v28-39-4]]

^<<v28-39-4,4>>^ Exerce o seu cargo no meio dos poderosos, e comparece perante aqueles que governam.

[[v28-39-5]]

^<<v28-39-5,5>>^ Viaja pela terra de povos estrangeiros, para reconhecer o que há do bem e do mal entre os homens.

[[v28-39-6]]

^<<v28-39-6,6>>^ Desde o alvorecer aplica o coração à vigília para se unir ao Senhor que o criou, e ora na presença do Altíssimo.

[[v28-39-7]]

^<<v28-39-7,7>>^ Abre sua boca para orar, e pede perdão de seus pecados,

[[v28-39-8]]

^<<v28-39-8,8>>^ pois se for da vontade do Senhor que é grande, ele o cumulará do espírito de inteligência.

[[v28-39-9]]

^<<v28-39-9,9>>^ Então, ele espargirá como uma chuva palavras de sabedoria, e louvará o Senhor em sua oração.

[[v28-39-10]]

^<<v28-39-10,10>>^ O Senhor orientará seus conselhos e seus ensinamentos, e ele meditará nos mistérios divinos.

[[v28-39-11]]

^<<v28-39-11,11>>^ Ensinará ele próprio o conhecimento de sua doutrina. Porá sua glória na Lei da aliança do Senhor.

[[v28-39-12]]

^<<v28-39-12,12>>^ Muitos homens louvarão sua sabedoria: jamais cairá ela no esquecimento.

[[v28-39-13]]

^<<v28-39-13,13>>^ A sua memória não desaparecerá; seu nome será repetido de geração em geração.

[[v28-39-14]]

^<<v28-39-14,14>>^ As nações proclamarão sua sabedoria, a assembleia apregoará seu louvor.

[[v28-39-15]]

^<<v28-39-15,15>>^ Enquanto viver, terá maior nome que mil outros, e, quando repousar, será feliz.

[[v28-39-16]]

^<<v28-39-16,16>>^ Refletirei ainda para contá-lo, pois estou cheio de um entusiasmo^&#42;1^

[[v28-39-17]]

^<<v28-39-17,17>>^ que diz: Ouvi-me, rebentos divinos, desabrochai como uma roseira plantada à beira das águas;

[[v28-39-18]]

^<<v28-39-18,18>>^ como o Líbano, espargi suave aroma,

[[v28-39-19]]

^<<v28-39-19,19>>^ dai flores como o lírio, exalai perfume e estendei graciosa folhagem. Cantai cânticos e bendizei o Senhor nas suas obras.

[[v28-39-20]]

^<<v28-39-20,20>>^ Dai ao seu nome magníficos elogios, glorificai-o com a voz de vossos lábios, com os cânticos de vossos lábios e a música das harpas. Direis assim à guisa de louvor:

[[v28-39-21]]

^<<v28-39-21,21>>^ Todas as obras do Senhor são excelentes;^&#42;1^

[[v28-39-22]]

^<<v28-39-22,22>>^ à sua voz conteve-se a água amontoada, a uma palavra de sua boca as águas ajuntaram-se como em reservatórios.

[[v28-39-23]]

^<<v28-39-23,23>>^ À sua ordem, fez-se calmaria, e a salvação que ele dá não será mesquinha.

[[v28-39-24]]

^<<v28-39-24,24>>^ São-lhe apresentadas as ações de todos os viventes, nada é oculto aos seus olhos.

[[v28-39-25]]

^<<v28-39-25,25>>^ Seu olhar abrange de um século a outro: nada é maravilhoso para ele.

[[v28-39-26]]

^<<v28-39-26,26>>^ Não se deve dizer: “O que é isso, o que é aquilo?”. Pois todas as coisas serão examinadas a seu tempo.

[[v28-39-27]]

^<<v28-39-27,27>>^ A bênção dele é como um rio que transborda;

[[v28-39-28]]

^<<v28-39-28,28>>^ como o dilúvio inundou a terra inteira, assim a sua cólera será a sorte dos povos que não o procuram.

[[v28-39-29]]

^<<v28-39-29,29>>^ Assim como ele transformou as águas em aridez e ressecou a terra, e o seu comportamento é determinado pelo deles, assim, em sua ira, seu comportamento é motivo de queda para os pecadores.

[[v28-39-30]]

^<<v28-39-30,30>>^ Assim como os bens, desde o princípio, foram criados para os bons, assim os bens e os males o foram para os maus.

[[v28-39-31]]

^<<v28-39-31,31>>^ As coisas mais necessárias à vida do homem são: a água, o fogo, o ferro, o sal, o leite, o pão da flor de farinha, o mel, a uva, o azeite e o vestuário:

[[v28-39-32]]

^<<v28-39-32,32>>^ todas essas coisas são bens para os fiéis, mas tornam-se males para os ímpios e os pecadores.

[[v28-39-33]]

^<<v28-39-33,33>>^ Há espíritos que foram criados para a vingança: aumentaram seus tormentos pelo seu furor.

[[v28-39-34]]

^<<v28-39-34,34>>^ No tempo do extermínio manifestarão sua força, e apaziguarão a fúria daquele que os criou.

[[v28-39-35]]

^<<v28-39-35,35>>^ Fogo, granizo, fome e morte, tudo isso foi criado para a vingança,

[[v28-39-36]]

^<<v28-39-36,36>>^ como também os dentes dos animais, os escorpiões, as serpentes, e a espada vingadora destinada ao extermínio dos ímpios.

[[v28-39-37]]

^<<v28-39-37,37>>^ Todas essas coisas se regozijam com as ordens do Senhor, e mantêm-se prontas sobre a terra para servir oportunamente, e, chegando o tempo, não omitirão uma só de suas palavras.

[[v28-39-38]]

^<<v28-39-38,38>>^ Por isso, desde o princípio estou firme em minhas ideias; refleti e as escrevi.

[[v28-39-39]]

^<<v28-39-39,39>>^ Todas as obras do Senhor são boas; ele põe cada coisa em prática quando chega o tempo.

[[v28-39-40]]

^<<v28-39-40,40>>^ Não há razão para dizer: “Isto é pior do que aquilo”, porque todas as coisas serão achadas boas a seu tempo.

[[v28-39-41]]

^<<v28-39-41,41>>^ E agora, de todo o coração e com a boca, cantai e bendizei o nome do Senhor!

'''

xref:028-eclesiastico/028-eclesiastico-038.adoc#v28-38-0[&#60; Capítulo Anterior] | <<v28-39-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-040.adoc#v28-40-0[Próximo Capítulo &#62;]