include::./index.adoc[]

[[v28-2-0]]
=== Eclesiástico, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 2 fala sobre a importância de perseverar na fé e na justiça, apesar das dificuldades e tentações que possam surgir ao longo da vida. O capítulo encoraja os fiéis a confiarem em Deus e a se manterem firmes em suas convicções, prometendo que aqueles que permanecem fiéis serão recompensados. Abaixo estão cinco versículos relacionados ao tema:
* Salmos 34:19: "Muitas são as aflições do justo, mas o SENHOR o livra de todas." Este verso fala sobre como os justos podem enfrentar dificuldades em suas vidas, mas Deus sempre os livrará de todas as aflições.
* Romanos 5:3-4: "E não somente isso, mas também nos gloriamos nas tribulações, sabendo que a tribulação produz perseverança; e a perseverança, experiência; e a experiência, esperança." Este verso destaca como as tribulações e dificuldades podem ajudar a fortalecer a fé e a perseverança dos cristãos.
* Tiago 1:2-4: "Meus irmãos, tende por motivo de toda alegria o passardes por várias provações, sabendo que a provação da vossa fé, uma vez confirmada, produz perseverança. Ora, a perseverança deve ter ação completa, para que sejais perfeitos e íntegros, em nada deficientes." Tiago exorta os cristãos a encararem suas provações como oportunidades para fortalecer a fé e a perseverança, levando à perfeição e integridade.
* 1 Pedro 1:7: "para que a prova da vossa fé, mais preciosa do que o ouro que perece e é provado pelo fogo, redunde para louvor, glória e honra na revelação de Jesus Cristo." Este verso destaca como as provações podem provar a fé dos cristãos e levá-los a serem recompensados com louvor, glória e honra.
* Gálatas 6:9: "E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não desfalecermos." Este verso encoraja os cristãos a continuarem a fazer o bem, mesmo quando enfrentam dificuldades e provações, lembrando-os de que serão recompensados no tempo certo.
****

[[v28-2-1]]

^<<v28-2-1,1>>^ Meu filho, se entrares para o serviço de Deus, permanece firme na justiça e no temor, e prepara a tua alma para a provação;

[[v28-2-2]]

^<<v28-2-2,2>>^ humilha teu coração, espera com paciência, dá ouvidos e acolhe as palavras de sabedoria; não te perturbes no tempo da infelicidade,^&#42;1^

[[v28-2-3]]

^<<v28-2-3,3>>^ sofre as demoras de Deus; dedica-te a Deus, espera com paciência, a fim de que no derradeiro momento tua vida se enriqueça.

[[v28-2-4]]

^<<v28-2-4,4>>^ Aceita tudo o que te acontecer. Na dor, permanece firme; na humilhação, tem paciência.

[[v28-2-5]]

^<<v28-2-5,5>>^ Pois é pelo fogo que se experimentam o ouro e a prata, e os homens agradáveis a Deus, pelo cadinho da humilhação.

[[v28-2-6]]

^<<v28-2-6,6>>^ Põe tua confiança em Deus e ele te salvará; orienta bem o teu caminho e espera nele. Conserva o temor dele até na velhice.

[[v28-2-7]]

^<<v28-2-7,7>>^ Vós, que temeis o Senhor, esperai em sua misericórdia, não vos afasteis dele, para que não caiais;

[[v28-2-8]]

^<<v28-2-8,8>>^ vós, que temeis o Senhor, tende confiança nele, a fim de que não se desvaneça vossa recompensa.

[[v28-2-9]]

^<<v28-2-9,9>>^ Vós, que temeis o Senhor, esperai nele; sua misericórdia vos será fonte de alegria.

[[v28-2-10]]

^<<v28-2-10,10>>^ Vós, que temeis o Senhor, amai-o, e vossos corações se encherão de luz.

[[v28-2-11]]

^<<v28-2-11,11>>^ Considerai, meus filhos, as gerações humanas: sabei que nenhum daqueles que confiavam no Senhor foi confundido.

[[v28-2-12]]

^<<v28-2-12,12>>^ Pois quem foi abandonado após ter perseverado em seus mandamentos? Quem é aquele cuja oração foi desprezada?

[[v28-2-13]]

^<<v28-2-13,13>>^ Pois Deus é cheio de bondade e de misericórdia, ele perdoa os pecados no dia da aflição. Ele é o protetor de todos os que verdadeiramente o procuram.

[[v28-2-14]]

^<<v28-2-14,14>>^ Ai do coração fingido, dos lábios perversos, das mãos malfazejas, do pecador que leva na terra uma vida de duplicidade;^&#42;1^

[[v28-2-15]]

^<<v28-2-15,15>>^ ai dos corações tímidos que não confiam em Deus, e que Deus, por essa razão, não protege;

[[v28-2-16]]

^<<v28-2-16,16>>^ ai daqueles que perderam a paciência, que saíram do caminho reto, e se transviaram nos maus caminhos.

[[v28-2-17]]

^<<v28-2-17,17>>^ Que farão eles quando o Senhor começar o exame?

[[v28-2-18]]

^<<v28-2-18,18>>^ Aqueles que temem o Senhor não são incrédulos à sua palavra, e os que o amam permanecem em sua vereda.

[[v28-2-19]]

^<<v28-2-19,19>>^ Aqueles que temem o Senhor procuram agradar-lhe, aqueles que o amam satisfazem-se na sua Lei.

[[v28-2-20]]

^<<v28-2-20,20>>^ Aqueles que temem o Senhor preparam o coração, santificam suas almas na presença dele.

[[v28-2-21]]

^<<v28-2-21,21>>^ Aqueles que temem o Senhor guardam os seus mandamentos, têm paciência até que ele lance os olhos sobre eles,

[[v28-2-22]]

^<<v28-2-22,22>>^ dizendo: “Se não fizermos penitência, cairemos nas mãos do Senhor, e não nas mãos dos homens”,

[[v28-2-23]]

^<<v28-2-23,23>>^ pois a misericórdia dele está na medida de sua grandeza.

'''

xref:028-eclesiastico/028-eclesiastico-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-003.adoc#v28-3-0[Próximo Capítulo &#62;]