include::./index.adoc[]

[[v28-21-0]]
=== Eclesiástico, 21
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 21 fala sobre a sabedoria e os caminhos de Deus, destacando a importância de escolher a justiça e a humildade. O capítulo também aborda os perigos da arrogância e da ignorância. Abaixo estão cinco versículos da Bíblia que abordam temas relacionados a este capítulo.
* Provérbios 3:7: "Não seja sábio aos seus próprios olhos; tema o Senhor e evite o mal." Este versículo enfatiza a importância de temer a Deus e de não confiar na própria sabedoria.
* Salmos 25:9: "Ele guia os humildes na justiça e ensina aos seus caminhos." Deus guia aqueles que são humildes e escolhem o caminho da justiça.
* Provérbios 16:18: "A arrogância precede a ruína, e a altivez do espírito precede a queda." Este versículo adverte sobre os perigos da arrogância e da altivez.
* Provérbios 17:27: "Quem tem conhecimento controla as palavras; quem é prudente e tem discernimento é calmo." A sabedoria vem com o autocontrole e a prudência, permitindo que sejamos calmos e cuidadosos com nossas palavras e ações.
* Tiago 1:5: "Se algum de vocês tem falta de sabedoria, peça a Deus, que a todos dá livremente, de boa vontade; e lhe será concedido." Este versículo destaca a importância de pedir a Deus sabedoria e de confiar nele para nos guiar em nossas decisões.
****

[[v28-21-1]]

^<<v28-21-1,1>>^ Filho, pecaste? Não o faças mais. Mas ora pelas tuas faltas passadas, para que te sejam perdoadas.

[[v28-21-2]]

^<<v28-21-2,2>>^ Foge do pecado como se foge de uma serpente, porque, se dela te aproximares, ela te morderá.

[[v28-21-3]]

^<<v28-21-3,3>>^ Os seus dentes são dentes de leão, que matam as almas dos homens.

[[v28-21-4]]

^<<v28-21-4,4>>^ Todo pecado é como uma espada de dois gumes: a chaga que ele produz é incurável.

[[v28-21-5]]

^<<v28-21-5,5>>^ O ultraje e a violência destroem as riquezas. A mais rica mansão se arruína pelo orgulho; assim será desenraizada a riqueza do orgulhoso.

[[v28-21-6]]

^<<v28-21-6,6>>^ A oração do pobre eleva-se de sua boca até os ouvidos (de Deus), (e Deus) se apressará em lhe fazer justiça.

[[v28-21-7]]

^<<v28-21-7,7>>^ Aquele que odeia a correção segue os passos do pecador, aquele que teme a Deus volta ao seu próprio coração.

[[v28-21-8]]

^<<v28-21-8,8>>^ De longe é conhecido o poderoso de linguagem insolente, mas o homem sábio sabe como se descartar dele.^&#42;1^

[[v28-21-9]]

^<<v28-21-9,9>>^ Quem constrói a sua casa à custa de outrem, é como aquele que amontoa pedras para (construir) no inverno.

[[v28-21-10]]

^<<v28-21-10,10>>^ A reunião dos pecadores é como um amontoado de estopas: seu fim será a fogueira.

[[v28-21-11]]

^<<v28-21-11,11>>^ O caminho dos pecadores é calçado de pedras unidas, mas ele conduz à região dos mortos, às trevas e aos suplícios.

[[v28-21-12]]

^<<v28-21-12,12>>^ Aquele que guarda a justiça penetrará o espírito dela.

[[v28-21-13]]

^<<v28-21-13,13>>^ A sabedoria e o bom senso são a consumação do temor a Deus.

[[v28-21-14]]

^<<v28-21-14,14>>^ Jamais se tornará hábil aquele que não é sábio no bem,

[[v28-21-15]]

^<<v28-21-15,15>>^ pois há uma sabedoria que produz muito mal. E o bom senso não está onde está a amargura.

[[v28-21-16]]

^<<v28-21-16,16>>^ A ciência do sábio espalha-se como a água que transborda, e o conselho que ele dá permanece como fonte de vida.

[[v28-21-17]]

^<<v28-21-17,17>>^ O coração do insensato é como um cântaro lascado, nada retém da sabedoria.

[[v28-21-18]]

^<<v28-21-18,18>>^ Qualquer palavra sábia que ouça o homem sensato, ele a louvará e dela se aproveitará. Que a ouça um voluptuoso, e ela lhe desagradará, e ele a arremessará para trás de si.

[[v28-21-19]]

^<<v28-21-19,19>>^ A conversa do insensato é como um fardo para carregar, mas o encanto se acha nos lábios do homem sensato.

[[v28-21-20]]

^<<v28-21-20,20>>^ A conversação do homem prudente é procurada na sociedade; todos relembrarão suas palavras em seus corações.

[[v28-21-21]]

^<<v28-21-21,21>>^ A sabedoria é para o insensato como uma casa arruinada; a ciência do insensato é feita de palavras incoerentes.

[[v28-21-22]]

^<<v28-21-22,22>>^ A instrução é para o insensato como peias nos pés e como algemas nas mãos.

[[v28-21-23]]

^<<v28-21-23,23>>^ O insensato eleva a voz quando ri, mas o homem sábio sorri discretamente.

[[v28-21-24]]

^<<v28-21-24,24>>^ Para o homem prudente a ciência é um ornato de ouro, uma pulseira que traz no braço direito.

[[v28-21-25]]

^<<v28-21-25,25>>^ O insensato põe facilmente os pés na casa do vizinho, mas aquele que tem educação hesita em visitar um poderoso.

[[v28-21-26]]

^<<v28-21-26,26>>^ O insensato olha dentro de uma casa pela janela; o homem bem-educado permanece fora.

[[v28-21-27]]

^<<v28-21-27,27>>^ É sinal de loucura escutar a uma porta; o homem prudente indigna-se com tal grosseria.

[[v28-21-28]]

^<<v28-21-28,28>>^ Os lábios dos imprudentes só proferem tolices, mas as palavras do sábio têm peso na balança.

[[v28-21-29]]

^<<v28-21-29,29>>^ O coração dos insensatos está na boca, a boca dos sábios está no coração.

[[v28-21-30]]

^<<v28-21-30,30>>^ Quando o ímpio amaldiçoa o adversário, amaldiçoa-se a si mesmo.^&#42;1^

[[v28-21-31]]

^<<v28-21-31,31>>^ O delator macula-se a si próprio, e é odiado por todos; o que mora com ele será odioso, mas o homem sensato que se cala será honrado.

'''

xref:028-eclesiastico/028-eclesiastico-020.adoc#v28-20-0[&#60; Capítulo Anterior] | <<v28-21-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-022.adoc#v28-22-0[Próximo Capítulo &#62;]