include::./index.adoc[]

[[v28-47-0]]
=== Eclesiástico, 47
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 47 de Eclesiástico destaca a figura do rei Davi, sua história e realizações. Davi é reconhecido como um líder forte e sábio, que conduziu o povo de Israel com justiça. Além disso, o capítulo destaca a importância da sabedoria e da fidelidade a Deus para alcançar a prosperidade e a glória. Seguem abaixo cinco versículos relacionados com os temas abordados em Eclesiástico 47:
* 1 Reis 2:10-11: "E Davi dormiu com seus pais, e foi sepultado na cidade de Davi. E o tempo que reinou sobre Israel foi quarenta anos: sete anos reinou em Hebrom, e em Jerusalém reinou trinta e três." Este versículo descreve o fim da vida de Davi e sua importância como rei de Israel.
* 2 Crônicas 1:7-10: "Naquela mesma noite apareceu Deus a Salomão e lhe disse: Pede o que queres que eu te dê. E disse-lhe Salomão: Dá-me agora sabedoria e conhecimento, para que possa sair e entrar perante este povo; pois quem poderia julgar este teu grande povo? E Deus disse a Salomão: Porquanto houve isto em teu coração, e não pediste riquezas, bens, honra, nem a vida dos que te odeiam, nem tampouco pediste muitos dias de vida, mas pediste para ti sabedoria e conhecimento, para poderes julgar o meu povo, sobre o qual te constituí rei;" Este versículo destaca a importância da sabedoria e como a busca por ela pode trazer bênçãos e prosperidade.
* Provérbios 14:34: "A justiça exalta as nações, mas o pecado é a vergonha dos povos." Esse versículo destaca a importância da justiça e da integridade para a prosperidade de um povo.
* Salmos 101:6: "Os meus olhos estarão sobre os fiéis da terra, para que habitem comigo; o que anda num caminho reto, esse me servirá." Este versículo destaca a importância da fidelidade a Deus e à sua vontade.
* Provérbios 28:20: "O homem fiel será coberto de bênçãos, mas o que se apressa a enriquecer não ficará impune." Este versículo destaca a importância da fidelidade e da integridade para a prosperidade e a bênção de Deus.
****

[[v28-47-1]]

^<<v28-47-1,1>>^ Depois disto levantou-se Natã, profeta no tempo de Davi.

[[v28-47-2]]

^<<v28-47-2,2>>^ Assim como a gordura da vitamina se separa da carne, assim foi Davi separado do meio dos israelitas.

[[v28-47-3]]

^<<v28-47-3,3>>^ Ele brincou com os leões como se fossem cordeiros, e tratou os ursos como cordeirinhos.

[[v28-47-4]]

^<<v28-47-4,4>>^ Não foi ele quem, em sua mocidade, matou o gigante, e tirou a vergonha do seu povo?

[[v28-47-5]]

^<<v28-47-5,5>>^ Levantando a mão, com uma pedra de sua funda abateu a insolência de Golias,

[[v28-47-6]]

^<<v28-47-6,6>>^ pois ele invocou o Senhor Todo-poderoso, o qual deu à sua destra força para derrubar o temível guerreiro, e para levantar o poder do seu povo.

[[v28-47-7]]

^<<v28-47-7,7>>^ Assim foi ele festejado por causa (da morte) de dez mil homens. Louvaram-no nas bênçãos do Senhor, e ofereceram-lhe uma coroa de glória,

[[v28-47-8]]

^<<v28-47-8,8>>^ porque ele esmagou os inimigos de todos os lados, exterminou os filisteus, seus adversários, (como se vê) ainda hoje, e abateu o seu poder para sempre.

[[v28-47-9]]

^<<v28-47-9,9>>^ Fez de todas as suas obras uma homenagem ao Santo e ao Altíssimo com palavras de louvor.

[[v28-47-10]]

^<<v28-47-10,10>>^ Louvou o Senhor com todo o coração. Amou a Deus que o criou, e lhe deu poder contra seus inimigos.

[[v28-47-11]]

^<<v28-47-11,11>>^ Estabeleceu cantores diante do altar, e compôs suaves melodias para os seus cânticos.

[[v28-47-12]]

^<<v28-47-12,12>>^ Deu esplendor às festividades, e brilho aos dias solenes, até o fim da vida, para que fosse louvado o santo nome do Senhor, e fosse glorificada desde o amanhecer a santidade de Deus.^&#42;1^

[[v28-47-13]]

^<<v28-47-13,13>>^ O Senhor purificou-o de seus pecados, engrandeceu o seu poder para sempre, e firmou-lhe, por sua aliança, a realeza e um trono de glória em Israel.

[[v28-47-14]]

^<<v28-47-14,14>>^ Depois dele, apareceu seu filho, cheio de sabedoria; por causa dele o Senhor derrubou todo o poder dos inimigos.^&#42;1^

[[v28-47-15]]

^<<v28-47-15,15>>^ Salomão reinou em dias de paz. Deus submeteu a ele todos os seus inimigos,

[[v28-47-16]]

^<<v28-47-16,16>>^ a fim de que ele construísse uma casa ao nome do Senhor, e lhe preparasse um santuário eterno. Quão bem foste instruído na tua juventude! Foste cheio de sabedoria como um rio. Tua alma cobriu toda a terra.

[[v28-47-17]]

^<<v28-47-17,17>>^ Encerraste enigmas em sentenças, teu nome foi glorificado até nas ilhas longínquas, e foste amado na tua paz.

[[v28-47-18]]

^<<v28-47-18,18>>^ Por teus cânticos, provérbios, parábolas e interpretações, foste admirado por toda a terra.

[[v28-47-19]]

^<<v28-47-19,19>>^ Em nome do Senhor Deus, que é chamado o Deus de Israel,

[[v28-47-20]]

^<<v28-47-20,20>>^ ajuntaste montes de ouro como se fosse bronze, amontoaste prata como se faz com o chumbo.

[[v28-47-21]]

^<<v28-47-21,21>>^ Entregaste teus flancos às mulheres, saciaste teu corpo,

[[v28-47-22]]

^<<v28-47-22,22>>^ maculaste tua glória, profanaste tua raça, atraindo assim a cólera sobre teus filhos, e o castigo sobre tua loucura,

[[v28-47-23]]

^<<v28-47-23,23>>^ causando com isso um cisma no reino, e fazendo sair de Efraim uma dominação rebelde.

[[v28-47-24]]

^<<v28-47-24,24>>^ Mas Deus não esqueceu a sua misericórdia, não destruiu nem aniquilou as suas obras; não arrancou pela raiz a posteridade de seu eleito, não exterminou a raça daquele que ama o Senhor.

[[v28-47-25]]

^<<v28-47-25,25>>^ Ao contrário, deixou um resto a Jacó, e a Davi, um rebento de sua raça.

[[v28-47-26]]

^<<v28-47-26,26>>^ E Salomão teve um fim semelhante ao de seus pais.

[[v28-47-27]]

^<<v28-47-27,27>>^ Deixou depois de si um filho que foi a loucura da nação,

[[v28-47-28]]

^<<v28-47-28,28>>^ um homem desprovido de juízo, chamado Roboão, que transviou o povo por seu conselho.

[[v28-47-29]]

^<<v28-47-29,29>>^ E Jeroboão, filho de Nabat, que fez Israel pecar, e abriu para Efraim o caminho da iniquidade. Houve entre eles uma profusão de pecados,

[[v28-47-30]]

^<<v28-47-30,30>>^ que os expulsaram para longe de sua terra.

[[v28-47-31]]

^<<v28-47-31,31>>^ Procuraram todos os meios de fazer o mal, até que veio a vingança, que pôs um termo às suas iniquidades.

'''

xref:028-eclesiastico/028-eclesiastico-046.adoc#v28-46-0[&#60; Capítulo Anterior] | <<v28-47-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-048.adoc#v28-48-0[Próximo Capítulo &#62;]