include::./index.adoc[]

[[v28-46-0]]
=== Eclesiástico, 46
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 46 apresenta uma lista de líderes e heróis bíblicos que foram abençoados por Deus e honrados pelo povo de Israel. Entre eles, destaca-se a figura do rei Davi, que é elogiado por sua coragem, sabedoria e piedade. Os versículos a seguir estão relacionados com os temas abordados neste capítulo:
* 1 Samuel 16:13: "Então Samuel tomou o chifre do azeite, e o ungiu no meio de seus irmãos; e desde aquele dia em diante o Espírito do Senhor se apoderou de Davi; então Samuel se levantou, e voltou para Ramá." Este versículo se refere à unção de Davi como rei de Israel por Samuel, mostrando como ele foi escolhido por Deus para liderar o povo.
* 1 Samuel 17:45: "Então disse Davi ao filisteu: Tu vens a mim com espada, e com lança, e com escudo; porém eu venho a ti em nome do Senhor dos Exércitos, o Deus dos exércitos de Israel, a quem tens afrontado." Este versículo descreve a coragem de Davi ao enfrentar Golias, mostrando como ele confiava em Deus para ajudá-lo a vencer seus inimigos.
* 1 Reis 2:10-11: "E Davi dormiu com seus pais, e foi sepultado na cidade de Davi. E reinou em seu lugar Salomão, seu filho, o qual estabeleceu o trono do reino do Senhor sobre Israel." Este versículo se refere à morte de Davi e sua sucessão por seu filho Salomão, mostrando como Davi deixou um legado duradouro como um grande rei de Israel.
* Salmos 51:10: "Cria em mim, ó Deus, um coração puro, e renova em mim um espírito reto." Este versículo faz referência ao Salmo 51, que é tradicionalmente atribuído a Davi e descreve sua oração de arrependimento após seu pecado com Bate-Seba. Ele mostra a humildade de Davi e seu desejo de ter um coração puro diante de Deus.
* Hebreus 11:32: "E que mais direi? Porque o tempo me faltaria contando de Gideão, e de Baraque, e de Sansão, e de Jefté, e de Davi, e de Samuel e dos profetas." Este versículo faz parte da "Galeria da Fé" em Hebreus 11, que destaca figuras notáveis do Antigo Testamento que viveram pela fé. Davi é incluído nesta lista, mostrando como ele foi reconhecido como um grande herói da fé.
****

[[v28-46-1]]

^<<v28-46-1,1>>^ Josué, filho de Nun, foi um valente na guerra. Sucedeu Moisés entre os profetas; foi ilustre, tão ilustre como o nome que trazia,^&#42;1^

[[v28-46-2]]

^<<v28-46-2,2>>^ muito ilustre salvador dos eleitos de Deus, para derrubar os inimigos que se levantavam, e para conquistar a herança de Israel.

[[v28-46-3]]

^<<v28-46-3,3>>^ Que glória não alcançou ele em levantar as suas mãos, e em brandir a espada contra as cidades!

[[v28-46-4]]

^<<v28-46-4,4>>^ Quem pôde enfrentá-lo? Pois o Senhor mesmo lhe trazia os seus inimigos.

[[v28-46-5]]

^<<v28-46-5,5>>^ Não deteve ele o sol, em sua cólera? Não se tornou um só dia tão longo como dois?

[[v28-46-6]]

^<<v28-46-6,6>>^ Ele invocou o Altíssimo Todo-poderoso, atacando os inimigos de todos os lados: o Deus grande e santo o atendeu com uma chuva de pedras de grande força.

[[v28-46-7]]

^<<v28-46-7,7>>^ Investiu impetuosamente contra as hostes inimigas, e despedaçou-as na descida do vale,

[[v28-46-8]]

^<<v28-46-8,8>>^ para que as nações conhecessem o poder de Deus, e soubessem que não é fácil combater contra Deus, ele seguiu sempre o Todo-poderoso.^&#42;1^

[[v28-46-9]]

^<<v28-46-9,9>>^ No tempo em que Moisés ainda vivia, praticou um ato de piedade com Caleb, filho de Jefoné, permanecendo firme contra o inimigo, impedindo o povo de pecar, e abafando a murmuração excitada pela malícia.

[[v28-46-10]]

^<<v28-46-10,10>>^ Dentre um número de seiscentos mil homens de pé, esses dois foram escolhidos e poupados da morte, para levar o povo à sua herança, nessa terra onde mana leite e mel.

[[v28-46-11]]

^<<v28-46-11,11>>^ O Senhor deu força a Caleb; até a velhice permaneceu ele vigoroso, para subir a um lugar elevado na terra prometida, que a sua descendência recebeu como herança,

[[v28-46-12]]

^<<v28-46-12,12>>^ para que todos os israelitas reconhecessem que é bom obedecer ao Deus santo.

[[v28-46-13]]

^<<v28-46-13,13>>^ Em seguida, vieram os juízes, cada um (designado) pelo seu nome, aqueles cujos corações não se perverteram, e que não se afastaram do Senhor.

[[v28-46-14]]

^<<v28-46-14,14>>^ Que a sua memória seja abençoada, e seus ossos floresçam em seus sepulcros!

[[v28-46-15]]

^<<v28-46-15,15>>^ Que seu nome permaneça eternamente, e passe aos seus filhos com a glória desses santos homens!

[[v28-46-16]]

^<<v28-46-16,16>>^ Amado pelo Senhor, seu Deus, Samuel, o profeta do Senhor, instituiu um novo governo, e ungiu príncipes entre o seu povo.

[[v28-46-17]]

^<<v28-46-17,17>>^ Julgou a assembleia segundo a Lei do Senhor. E o Deus de Jacó o visitou. Por sua fidelidade ele se mostrou verdadeiramente profeta,

[[v28-46-18]]

^<<v28-46-18,18>>^ e foi fiel em suas palavras, porque viu o Deus da luz.

[[v28-46-19]]

^<<v28-46-19,19>>^ Invocou o Deus Todo-poderoso, ofereceu-lhe um cordeiro sem mácula, quando os seus inimigos o perseguiam por todos os lados.

[[v28-46-20]]

^<<v28-46-20,20>>^ O Senhor trovejou do céu, fazendo ouvir sua voz com grande estrondo.

[[v28-46-21]]

^<<v28-46-21,21>>^ Destroçou os príncipes de Tiro, e todos os chefes dos filisteus.

[[v28-46-22]]

^<<v28-46-22,22>>^ Antes de terminar a sua vida neste mundo, tomou como testemunha o Senhor e seu ungido, de que não tinha recebido dinheiro de pessoa alguma, nem mesmo uma sandália, e não achou ninguém que o acusasse.

[[v28-46-23]]

^<<v28-46-23,23>>^ Depois disso, adormeceu e apareceu ao rei, e lhe mostrou seu fim (próximo); levantou a sua voz do seio da terra para profetizar a destruição da impiedade do povo.^&#42;1^

'''

xref:028-eclesiastico/028-eclesiastico-045.adoc#v28-45-0[&#60; Capítulo Anterior] | <<v28-46-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-047.adoc#v28-47-0[Próximo Capítulo &#62;]