include::./index.adoc[]

[[v28-32-0]]
=== Eclesiástico, 32
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 32 de Eclesiástico trata da sabedoria e da orientação que devemos buscar em Deus para viver bem e evitar o erro. É um convite à humildade e à prudência na busca da verdade. Os versículos selecionados estão em ordem de proximidade com esses temas:
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento; em todos os seus caminhos, reconheça-o, e ele endireitará[a] as suas veredas." Este versículo nos ensina a confiar em Deus e buscar sua orientação, em vez de confiar apenas em nossa própria sabedoria.
* Salmos 25:9: "Ele guia os humildes na justiça e lhes ensina o seu caminho." Este verso fala sobre a humildade e a disposição de aprender, que são enfatizadas no capítulo 32 de Eclesiástico.
* Provérbios 16:20: "Quem dá ouvidos à palavra, nela encontra felicidade, e como é grande a felicidade de quem confia no Senhor!" Este versículo enfatiza a importância de ouvir a Palavra de Deus e confiar Nele para encontrar a verdadeira felicidade.
* Provérbios 18:15: "O coração do sábio adquire o conhecimento; o ouvido dos sábios busca conhecimento." Este verso fala sobre a importância de buscar conhecimento e orientação de pessoas sábias e experientes.
* Provérbios 19:20: "Ouça conselho e aceite instruções, e acabará sendo sábio de verdade." Este versículo nos ensina a buscar conselho e orientação de outros para se tornar mais sábio e prudente.
****

[[v28-32-1]]

^<<v28-32-1,1>>^ Fizeram-te rei (do festim)? Não te enalteças. Sê no meio dos outros como qualquer um deles.

[[v28-32-2]]

^<<v28-32-2,2>>^ Ocupa-te com eles e em seguida senta-te. Não tomes lugar à mesa, senão após cumpridos os teus deveres,^&#42;1^

[[v28-32-3]]

^<<v28-32-3,3>>^ assim te regozijarás por causa deles. Receberás a coroa como um gracioso adorno, e ganharás a consideração dos convivas.^&#42;1^

[[v28-32-4]]

^<<v28-32-4,4>>^ Tu, mais idoso, fala, pois convém

[[v28-32-5]]

^<<v28-32-5,5>>^ que sejas o primeiro a falar, com séria competência. Mas não perturbes a música,

[[v28-32-6]]

^<<v28-32-6,6>>^ nem te alongues em discursos, onde não há quem os ouça. Não te engrandeças sem propósito por causa de tua sabedoria.^&#42;1^

[[v28-32-7]]

^<<v28-32-7,7>>^ Como uma pedra de rubi engastada no ouro, assim é a música no meio de uma refeição regada a vinho.

[[v28-32-8]]

^<<v28-32-8,8>>^ Como um sinete de esmeraldas engastadas em ouro, assim é um grupo de músicos no meio de uma alegre e moderada libação.

[[v28-32-9]]

^<<v28-32-9,9>>^ Ouve em silêncio, e tua modéstia provocará a benevolência.

[[v28-32-10]]

^<<v28-32-10,10>>^ Jovem, fala muito pouco de teus assuntos privados.^&#42;1^

[[v28-32-11]]

^<<v28-32-11,11>>^ Se fores duas vezes interrogado, que tua resposta seja concisa.

[[v28-32-12]]

^<<v28-32-12,12>>^ Em muitas coisas, porta-te como se as ignorasses; ouve em silêncio e pergunta.^&#42;1^

[[v28-32-13]]

^<<v28-32-13,13>>^ No meio dos poderosos, não tomes muitas liberdades; não fales muito onde houver anciãos:

[[v28-32-14]]

^<<v28-32-14,14>>^ vê-se o relâmpago antes de se ouvir o estalido, a graça precede o rubor da modéstia. Pelo teu recato serás benquisto.

[[v28-32-15]]

^<<v28-32-15,15>>^ Uma vez chegada a hora de se levantar, não te demores; sê o primeiro a correr para casa,^&#42;1^ onde te regozijarás com os divertimentos.

[[v28-32-16]]

^<<v28-32-16,16>>^ Faze o que te aprouver, porém sem pecado e sem orgulho.

[[v28-32-17]]

^<<v28-32-17,17>>^ E em tudo isso glorifica o Senhor que te criou, e que te cumula de todos os seus bens.

[[v28-32-18]]

^<<v28-32-18,18>>^ Aquele que teme o Senhor aceitará sua doutrina, aqueles que vigiam para procurá-lo serão por ele abençoados.

[[v28-32-19]]

^<<v28-32-19,19>>^ Aquele que busca a Lei, por ela será cumulado. Aquele, porém, que procede com falsidade, nela achará ocasião de pecado.

[[v28-32-20]]

^<<v28-32-20,20>>^ Aqueles que temem o Senhor terão um juízo reto, e farão brilhar como uma tocha a sua justiça.

[[v28-32-21]]

^<<v28-32-21,21>>^ O pecador foge da censura, e encontra precedentes segundo o seu desejo.

[[v28-32-22]]

^<<v28-32-22,22>>^ O homem prudente não perde ocasião alguma para instruir-se, e o estranho ou o orgulhoso não tem nenhum temor;

[[v28-32-23]]

^<<v28-32-23,23>>^ mesmo quando age sozinho e sem conselheiro, ele será castigado pelos seus próprios desígnios.

[[v28-32-24]]

^<<v28-32-24,24>>^ Meu filho, nada faças sem conselho, e não te arrependerás depois de teres agido.

[[v28-32-25]]

^<<v28-32-25,25>>^ Não te embrenhes num caminho de perdição e não tropeçarás nas pedras. Não te metas num caminho escabroso, para não pores diante de ti uma pedra de tropeço.

[[v28-32-26]]

^<<v28-32-26,26>>^ Previne-te contra teus filhos, sê prudente em presença de teus familiares.

[[v28-32-27]]

^<<v28-32-27,27>>^ Em tudo o que fizeres, age com segurança, pois isso é guardar os mandamentos.

[[v28-32-28]]

^<<v28-32-28,28>>^ Aquele que crê em Deus atende ao que ele manda. Aquele que põe sua confiança nele, não será atingido.

'''

xref:028-eclesiastico/028-eclesiastico-031.adoc#v28-31-0[&#60; Capítulo Anterior] | <<v28-32-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-033.adoc#v28-33-0[Próximo Capítulo &#62;]