include::./index.adoc[]

[[v28-13-0]]
=== Eclesiástico, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 13 do livro de Eclesiástico fala sobre as consequências de se fazer alianças com pessoas más e como a amizade pode influenciar nossas escolhas. O autor adverte sobre a importância de escolher sabiamente com quem nos associamos e aconselha a evitar se envolver com pessoas que podem nos levar ao pecado. Abaixo estão cinco versículos da Bíblia que se relacionam com esses temas.
* Provérbios 13:20: "Aquele que anda com os sábios será cada vez mais sábio, mas o companheiro dos tolos acabará mal." Este versículo enfatiza a importância de escolher nossas amizades sabiamente, pois a influência das pessoas ao nosso redor pode ter um grande impacto em nossas vidas.
* 2 Coríntios 6:14: "Não se ponham em jugo desigual com descrentes. Pois o que têm em comum a justiça e a maldade? Ou que comunhão pode ter a luz com as trevas?" Este versículo adverte contra a formação de alianças com pessoas ímpias, enfatizando que os crentes devem se separar daqueles que não seguem a Deus.
* 1 Coríntios 15:33: "Não se deixem enganar: as más companhias corrompem os bons costumes." Este versículo enfatiza a influência negativa que as más companhias podem ter em nossas vidas e como é importante escolher amigos que compartilham de nossos valores.
* Provérbios 22:24-25: "Não faça amizade com quem se irrita facilmente nem ande em companhia de alguém que vive em constantes explosões de raiva; pois você poderá acabar aprendendo os seus maus costumes e ficar preso numa armadilha." Este versículo enfatiza a importância de evitar amizades com pessoas cuja raiva pode nos influenciar negativamente.
* Salmos 1:1-2: "Como é feliz aquele que não segue o conselho dos ímpios, não imita a conduta dos pecadores, nem se assenta na roda dos zombadores! Ao contrário, sua satisfação está na lei do Senhor, e nessa lei medita dia e noite." Este versículo enfatiza a importância de escolher amigos que compartilham de nossos valores e que nos ajudem a crescer em nosso relacionamento com Deus.
****

[[v28-13-1]]

^<<v28-13-1,1>>^ Quem toca no betume ficará manchado; e quem trata com o orgulhoso, se tornará orgulhoso.

[[v28-13-2]]

^<<v28-13-2,2>>^ Quem se liga com um mais poderoso do que ele põe sob os ombros uma pesada carga. Não te tornes amigo de um mais poderoso do que tu.

[[v28-13-3]]

^<<v28-13-3,3>>^ Que ligação pode haver entre um pote de barro e um pote de ferro? Quando houver choque, o pote de barro será quebrado.

[[v28-13-4]]

^<<v28-13-4,4>>^ O rico comete uma injustiça e em seguida se põe a gritar; o pobre, ofendido, guarda silêncio.^&#42;1^

[[v28-13-5]]

^<<v28-13-5,5>>^ Enquanto lhe servires, ele te empregará; quando nada mais tiveres, ele te abandonará.

[[v28-13-6]]

^<<v28-13-6,6>>^ Se tens haveres, ele se banqueteará contigo, te esgotará e não cuidará de tua sorte.

[[v28-13-7]]

^<<v28-13-7,7>>^ Se lhe fores útil, ele te dominará; com um sorriso ele te dará esperanças, com belas palavras te dirá: “De que necessitas?”.

[[v28-13-8]]

^<<v28-13-8,8>>^ Ele te confundirá com seus banquetes, até que te tenha exaurido duas ou três vezes; e, por fim, zombará de ti; depois, vendo-te, te abandonará, e abanará a cabeça, escarnecendo de ti.

[[v28-13-9]]

^<<v28-13-9,9>>^ Humilha-te perante Deus e espera que sua mão execute.

[[v28-13-10]]

^<<v28-13-10,10>>^ Tem cuidado em não te deixares seduzir, para que não caias numa loucura aviltante.^&#42;1^

[[v28-13-11]]

^<<v28-13-11,11>>^ Não te rebaixes em tua sabedoria, para não suceder que esse rebaixamento te arraste à loucura.

[[v28-13-12]]

^<<v28-13-12,12>>^ Se um poderoso te chamar, retira-te, e ele será ainda mais levado a insistir.

[[v28-13-13]]

^<<v28-13-13,13>>^ Não sejas importuno, para não acontecer que ele se canse de ti; não te afastes muito dele, para não suceder que ele te esqueça.

[[v28-13-14]]

^<<v28-13-14,14>>^ Não tenhas a audácia de falar de igual para igual com ele, e não confies em suas longas conversas. Pois fazendo-te falar muito, ele te experimentará, e com um sorriso te interrogará sobre os teus segredos.

[[v28-13-15]]

^<<v28-13-15,15>>^ Seu coração impiedoso relembrará todas as tuas palavras, e não te poupará nem aos maus-tratos nem às cadeias.

[[v28-13-16]]

^<<v28-13-16,16>>^ Cuida de ti e presta bem atenção aos teus ouvidos, pois caminhas à beira de um abismo.^&#42;1^

[[v28-13-17]]

^<<v28-13-17,17>>^ Mas, ouvido tudo isso, encara-o como um sonho, e serás vigilante;

[[v28-13-18]]

^<<v28-13-18,18>>^ ama a Deus durante toda a tua vida, e invoca-o para tua salvação.

[[v28-13-19]]

^<<v28-13-19,19>>^ Todo ser vivo ama o seu semelhante, assim todo homem ama o seu próximo.

[[v28-13-20]]

^<<v28-13-20,20>>^ Toda carne se une a outra carne de sua espécie, e todo homem se associa ao seu semelhante.

[[v28-13-21]]

^<<v28-13-21,21>>^ O lobo jamais terá amizade com o cordeiro: assim é entre o pecador e o justo.

[[v28-13-22]]

^<<v28-13-22,22>>^ Que relação pode haver entre um santo homem e um cão? Que ligação pode ter um rico com um pobre?^&#42;1^

[[v28-13-23]]

^<<v28-13-23,23>>^ O onagro é a presa do leão no deserto: assim os pobres servem de pasto aos ricos.

[[v28-13-24]]

^<<v28-13-24,24>>^ E, como a humanidade é abominada pelo orgulhoso, do mesmo modo o pobre causa horror ao rico.

[[v28-13-25]]

^<<v28-13-25,25>>^ Um rico abalado é apoiado pelos seus amigos. O pobre que tropeça é ainda empurrado pelos seus companheiros.

[[v28-13-26]]

^<<v28-13-26,26>>^ Quando um rico é enganado, numerosos são aqueles que o vêm ajudar; se diz tolices, o apoiam.

[[v28-13-27]]

^<<v28-13-27,27>>^ Quando um pobre é enganado, ainda merece censura, e, se falar com sabedoria, não o levam em consideração.

[[v28-13-28]]

^<<v28-13-28,28>>^ Se fala o rico, todos se calam, e glorificam suas palavras até as nuvens;

[[v28-13-29]]

^<<v28-13-29,29>>^ se fala um pobre, dizem: “Que é este homem?”. E, se ele tropeçar, fazem-no cair.

[[v28-13-30]]

^<<v28-13-30,30>>^ A riqueza é boa para quem não tem a consciência pesada, péssima é a pobreza do mau que se lastima.

[[v28-13-31]]

^<<v28-13-31,31>>^ O coração do homem modifica seu rosto, seja em bem, seja em mal.

[[v28-13-32]]

^<<v28-13-32,32>>^ O sinal de um coração feliz é um rosto alegre, tu o acharás dificilmente e com esforço.^&#42;1^

'''

xref:028-eclesiastico/028-eclesiastico-012.adoc#v28-12-0[&#60; Capítulo Anterior] | <<v28-13-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-014.adoc#v28-14-0[Próximo Capítulo &#62;]