include::./index.adoc[]

[[v28-30-0]]
=== Eclesiástico, 30
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 30 trata da importância de cuidar dos pais na velhice e dos benefícios da felicidade doméstica. O capítulo também fala sobre o valor do trabalho árduo e da moderação em todas as coisas. Aqui estão cinco versículos relacionados com os temas abordados em Eclesiástico 30:
* Provérbios 23:22: "Ouve teu pai, que te gerou; e não desprezes tua mãe, quando ela envelhecer." Este verso enfatiza a importância de cuidar dos pais na velhice e demonstrar respeito e gratidão por tudo que eles fizeram por nós.
* 1 Timóteo 5:8: "Mas, se alguém não tem cuidado dos seus e principalmente dos da sua família, negou a fé e é pior do que o incrédulo." Este verso reforça a importância de cuidar dos membros da família, especialmente dos pais idosos.
* Provérbios 31:28-29: "Levantam-se seus filhos e chamam-na bem-aventurada; seu marido também, e ele a louva, dizendo: Muitas mulheres fizeram o bem, mas tu és a melhor de todas." Este verso celebra a felicidade doméstica e destaca a importância da esposa e mãe em uma família.
* Provérbios 12:11: "O que lavra a sua terra se fartará de pão; mas o que segue os ociosos se encherá de pobreza." Este verso destaca o valor do trabalho árduo e a importância de ser produtivo.
* Filipenses 4:5: "Seja a vossa equidade conhecida de todos os homens. Perto está o Senhor." Este verso fala sobre a importância da moderação e equilíbrio em todas as coisas, como um meio de honrar a Deus e viver uma vida justa.
****

[[v28-30-1]]

^<<v28-30-1,1>>^ Aquele que ama seu filho, castiga-o com frequência, para que se alegre com isso mais tarde, e não tenha de bater à porta dos vizinhos.

[[v28-30-2]]

^<<v28-30-2,2>>^ Aquele que dá ensinamentos a seu filho será louvado por causa dele, e nele mesmo se gloriará entre seus amigos.

[[v28-30-3]]

^<<v28-30-3,3>>^ Aquele que educa o filho torna o seu inimigo invejoso, e entre seus amigos será honrado por causa dele.

[[v28-30-4]]

^<<v28-30-4,4>>^ O pai morre, e é como se não morresse, pois deixa depois de si um seu semelhante.

[[v28-30-5]]

^<<v28-30-5,5>>^ Durante sua vida viu seu filho e nele se alegrou; quando morrer, não ficará aflito; não terá de que se envergonhar perante seus adversários,

[[v28-30-6]]

^<<v28-30-6,6>>^ pois deixou em sua casa um defensor contra os inimigos, alguém que manifestará gratidão aos seus amigos.

[[v28-30-7]]

^<<v28-30-7,7>>^ Aquele que estraga seus filhos com mimos terá que lhes pensar as feridas; a cada palavra suas entranhas se comoverão.^&#42;1^

[[v28-30-8]]

^<<v28-30-8,8>>^ Um cavalo indômito torna-se intratável; a criança entregue a si mesma torna-se temerária.

[[v28-30-9]]

^<<v28-30-9,9>>^ Adula o teu filho e ele te causará medo; brinca com ele e ele te causará desgosto.

[[v28-30-10]]

^<<v28-30-10,10>>^ Não te ponhas a rir com ele, para que não venhas a sofrer com isso, e não acabes rangendo os dentes.

[[v28-30-11]]

^<<v28-30-11,11>>^ Não lhe dês toda a liberdade na juventude, não feches os olhos às suas extravagâncias:

[[v28-30-12]]

^<<v28-30-12,12>>^ obriga-o a curvar a cabeça enquanto jovem, castiga-o com varas enquanto ainda é menino, para que não suceda endurecer-se e não queira mais acreditar em ti, e venha a ser um sofrimento para a tua alma.

[[v28-30-13]]

^<<v28-30-13,13>>^ Educa o teu filho, esforça-te por instruí-lo, para que te não desonre com sua vida vergonhosa.

[[v28-30-14]]

^<<v28-30-14,14>>^ Mais vale um pobre sadio e vigoroso que um rico enfraquecido e atacado de doenças.

[[v28-30-15]]

^<<v28-30-15,15>>^ A saúde da alma na santidade e na justiça vale mais que o ouro e a prata. Um corpo robusto vale mais que imensas riquezas.

[[v28-30-16]]

^<<v28-30-16,16>>^ Não há maior riqueza que a saúde do corpo; não há prazer que se iguale à alegria do coração.

[[v28-30-17]]

^<<v28-30-17,17>>^ Mais vale a morte que uma vida na aflição; e o repouso eterno que um definhamento sem fim.

[[v28-30-18]]

^<<v28-30-18,18>>^ Bens escondidos em uma boca fechada são como preparativos de um festim colocados sobre um túmulo.

[[v28-30-19]]

^<<v28-30-19,19>>^ De que serve ao ídolo a oferenda que lhe fazem? Não pode nem comê-la nem lhe respirar o aroma.

[[v28-30-20]]

^<<v28-30-20,20>>^ Assim é aquele que o Senhor repele, e que carrega o castigo de seu pecado;

[[v28-30-21]]

^<<v28-30-21,21>>^ seus olhos vislumbram o alimento e ele suspira, assim como suspira o eunuco ao abraçar uma virgem.

[[v28-30-22]]

^<<v28-30-22,22>>^ Não entregues tua alma à tristeza, não atormentes a ti mesmo em teus pensamentos.

[[v28-30-23]]

^<<v28-30-23,23>>^ A alegria do coração é a vida do homem, e um inesgotável tesouro de santidade. A alegria do homem torna mais longa a sua vida.

[[v28-30-24]]

^<<v28-30-24,24>>^ Tem compaixão de tua alma, torna-te agradável a Deus, e sê firme; concentra teu coração na santidade, e afasta a tristeza para longe de ti,^&#42;1^

[[v28-30-25]]

^<<v28-30-25,25>>^ pois a tristeza matou a muitos, e não há nela utilidade alguma.

[[v28-30-26]]

^<<v28-30-26,26>>^ A inveja e a ira abreviam os dias, e a inquietação acarreta a velhice antes do tempo.

[[v28-30-27]]

^<<v28-30-27,27>>^ Um coração bondoso e nobre banqueteia-se continuamente, pois seus banquetes são preparados com solicitude.^&#42;1^

'''

xref:028-eclesiastico/028-eclesiastico-029.adoc#v28-29-0[&#60; Capítulo Anterior] | <<v28-30-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-031.adoc#v28-31-0[Próximo Capítulo &#62;]