include::./index.adoc[]

[[v28-35-0]]
=== Eclesiástico, 35
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 35 de Eclesiástico trata principalmente do tema da oração e da generosidade. O autor enfatiza que Deus está sempre ouvindo as nossas orações, mas que a generosidade e a justiça são igualmente importantes para alcançar o favor divino. Abaixo estão cinco versículos da Bíblia que se relacionam com esses temas e que podem ajudar a iluminar o significado do capítulo 35 de Eclesiástico:
* Tiago 5:16b: "A oração de um justo é poderosa e eficaz." Tiago enfatiza que a oração é uma ferramenta poderosa, mas que ela deve ser acompanhada de justiça e retidão.
* Provérbios 11:25: "A alma generosa prosperará e quem saciar os outros, também será saciado." Esse versículo destaca a conexão entre a generosidade e a recompensa divina.
* Salmos 51:17: "O sacrifício aceitável a Deus é um espírito quebrantado; um coração quebrantado e contrito, ó Deus, não desprezarás." Esse salmo ensina que Deus valoriza a humildade e a sinceridade do coração.
* Mateus 6:6: "Mas quando você orar, vá para seu quarto, feche a porta e ore a seu Pai, que está em secreto. Então seu Pai, que vê em secreto, o recompensará." Esse versículo destaca a importância da oração sincera e pessoal, feita em privacidade e sinceridade.
* Provérbios 22:9: "O generoso será abençoado, pois dá do seu pão aos pobres." Esse provérbio enfatiza a importância da generosidade e do cuidado com os mais necessitados, algo que é enfatizado no capítulo 35 de Eclesiástico.
****

[[v28-35-1]]

^<<v28-35-1,1>>^ Aquele que observa a Lei faz numerosas oferendas.

[[v28-35-2]]

^<<v28-35-2,2>>^ É um sacrifício salutar guardar os preceitos, e apartar-se de todo pecado.

[[v28-35-3]]

^<<v28-35-3,3>>^ Afastar-se da injustiça é oferecer um sacrifício de propiciação, que consegue o perdão dos pecados.

[[v28-35-4]]

^<<v28-35-4,4>>^ Aquele que oferece a flor da farinha dá graças, e o que usa de misericórdia oferece um sacrifício.

[[v28-35-5]]

^<<v28-35-5,5>>^ Abster-se do mal é coisa agradável ao Senhor; o fugir da injustiça alcança o perdão dos pecados.

[[v28-35-6]]

^<<v28-35-6,6>>^ Não te apresentarás diante do Senhor com as mãos vazias,

[[v28-35-7]]

^<<v28-35-7,7>>^ pois todos esses ritos se fazem para obedecer aos preceitos divinos.

[[v28-35-8]]

^<<v28-35-8,8>>^ A oblação do justo enriquece o altar; é um suave odor na presença do Senhor.

[[v28-35-9]]

^<<v28-35-9,9>>^ O sacrifício do justo é aceito por Deus. O Senhor não se esquecerá dele.

[[v28-35-10]]

^<<v28-35-10,10>>^ Dá glória a Deus de bom coração e nada suprimas das primícias do produto de tuas mãos.

[[v28-35-11]]

^<<v28-35-11,11>>^ Faze todas as tuas oferendas com um rosto alegre, consagra os dízimos com alegria.

[[v28-35-12]]

^<<v28-35-12,12>>^ Dá ao Altíssimo conforme te foi dado por ele, dá de bom coração de acordo com o que tuas mãos ganharam,

[[v28-35-13]]

^<<v28-35-13,13>>^ pois o Senhor retribui a dádiva, e te recompensará tudo sete vezes mais.

[[v28-35-14]]

^<<v28-35-14,14>>^ Não lhe ofereças dádivas perversas, pois ele não as aceitará.^&#42;1^

[[v28-35-15]]

^<<v28-35-15,15>>^ Nada esperes de um sacrifício injusto, porque o Senhor é teu juiz, e ele não faz distinção de pessoas.

[[v28-35-16]]

^<<v28-35-16,16>>^ O Senhor não faz acepção de pessoa em detrimento do pobre, e ouve a oração do ofendido.

[[v28-35-17]]

^<<v28-35-17,17>>^ Não despreza a oração do órfão, nem os gemidos da viúva.

[[v28-35-18]]

^<<v28-35-18,18>>^ As lágrimas da viúva não correm pela sua face, e seu grito não atinge aquele que as faz derramar?

[[v28-35-19]]

^<<v28-35-19,19>>^ Pois da sua face sobem até o céu; o Senhor que a ouve não se compraz em vê-la chorar.

[[v28-35-20]]

^<<v28-35-20,20>>^ Aquele que adora a Deus na alegria será bem recebido, e sua oração se elevará até as nuvens.

[[v28-35-21]]

^<<v28-35-21,21>>^ A oração do humilde penetra as nuvens; ele não se consolará, enquanto ela não chegar a Deus, e não se afastará, enquanto o Altíssimo não puser nela os olhos.

[[v28-35-22]]

^<<v28-35-22,22>>^ O Senhor não concederá prazo: ele julgará os justos e fará justiça. O fortíssimo não terá paciência com os opressores, mas ele lhes esmagará os rins.

[[v28-35-23]]

^<<v28-35-23,23>>^ Ele se vingará das nações, até suprimir a multidão dos soberbos, e quebrar os cetros dos iníquos;

[[v28-35-24]]

^<<v28-35-24,24>>^ até que ele dê aos homens segundo as suas obras, segundo a conduta de Adão, e segundo a sua presunção;

[[v28-35-25]]

^<<v28-35-25,25>>^ até que faça justiça ao seu povo, e dê alegria aos justos por um efeito de sua misericórdia.

[[v28-35-26]]

^<<v28-35-26,26>>^ A misericórdia divina no tempo da tribulação é bela; é como a nuvem que esparge a chuva na época da seca.

'''

xref:028-eclesiastico/028-eclesiastico-034.adoc#v28-34-0[&#60; Capítulo Anterior] | <<v28-35-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-036.adoc#v28-36-0[Próximo Capítulo &#62;]