include::./index.adoc[]

[[v28-38-0]]
=== Eclesiástico, 38
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 38 é um capítulo que fala sobre a importância da medicina e dos médicos, e sobre a necessidade de cuidarmos bem da nossa saúde. Abaixo estão cinco versículos relacionados com os temas abordados nesse capítulo:
* Provérbios 17:22: "O coração alegre é bom remédio, mas o espírito abatido faz secar os ossos." Esse versículo mostra que a felicidade e o bem-estar emocional podem contribuir para a saúde física.
* Provérbios 4:20-22: "Filho meu, atenta para as minhas palavras, inclina o teu ouvido às minhas instruções. Não as deixes apartar-se dos teus olhos; guarda-as no íntimo do teu coração. Porque são vida para os que as acham e saúde para o seu corpo." Esse versículo mostra que a sabedoria pode trazer vida e saúde ao nosso corpo.
* Isaías 38:21: "Então tomaram um pedaço de figo e o colocaram sobre a úlcera; e ele sarou." Esse versículo mostra a importância das terapias naturais e dos remédios caseiros para a cura de doenças.
* Mateus 9:12: "Mas Jesus, ouvindo, disse-lhes: Não necessitam de médico os sãos, mas sim os doentes." Esse versículo mostra que Jesus reconhecia a importância dos médicos e dos tratamentos médicos.
* Lucas 5:31: "E Jesus, respondendo, disse-lhes: Não necessitam de médico os que estão sãos, mas sim os que estão enfermos." Esse versículo é semelhante ao anterior e também mostra a importância dos médicos e dos tratamentos médicos.
****

[[v28-38-1]]

^<<v28-38-1,1>>^ Honra o médico por causa da necessidade, pois foi o Altíssimo quem o criou.

[[v28-38-2]]

^<<v28-38-2,2>>^ Toda a medicina provém de Deus, e ele recebe presentes do rei:

[[v28-38-3]]

^<<v28-38-3,3>>^ a ciência do médico o eleva em honra; ele é admirado na presença dos grandes.

[[v28-38-4]]

^<<v28-38-4,4>>^ O Senhor fez a terra produzir os medicamentos: o homem sensato não os despreza.

[[v28-38-5]]

^<<v28-38-5,5>>^ Uma espécie de madeira não adoçou o amargor da água? Essa virtude chegou ao conhecimento dos homens.^&#42;1^

[[v28-38-6]]

^<<v28-38-6,6>>^ O Altíssimo deu-lhes a ciência da medicina para ser honrado em suas maravilhas;

[[v28-38-7]]

^<<v28-38-7,7>>^ e dela se serve para acalmar as dores e curá-las; o farmacêutico faz misturas agradáveis, compõe unguentos úteis à saúde, e seu trabalho não terminará,

[[v28-38-8]]

^<<v28-38-8,8>>^ até que a paz divina se estenda sobre a face da terra.

[[v28-38-9]]

^<<v28-38-9,9>>^ Meu filho, se estiveres doente não te descuides de ti, mas ora ao Senhor, que te curará.

[[v28-38-10]]

^<<v28-38-10,10>>^ Afasta-te do pecado, reergue as mãos e purifica teu coração de todo o pecado.

[[v28-38-11]]

^<<v28-38-11,11>>^ Oferece um incenso suave e uma lembrança de flor de farinha; faze a oblação de uma vítima gorda.^&#42;1^

[[v28-38-12]]

^<<v28-38-12,12>>^ Em seguida dá lugar ao médico, pois ele foi criado por Deus; que ele não te deixe, pois sua arte te é necessária.

[[v28-38-13]]

^<<v28-38-13,13>>^ Virá um tempo em que cairás nas mãos deles.^&#42;1^

[[v28-38-14]]

^<<v28-38-14,14>>^ E eles mesmos rogarão ao Senhor que mande por meio deles o alívio e a saúde (ao doente) segundo a finalidade de sua vida.

[[v28-38-15]]

^<<v28-38-15,15>>^ Aquele que peca na presença daquele que o fez cairá nas mãos do médico.

[[v28-38-16]]

^<<v28-38-16,16>>^ Meu filho, derrama lágrimas sobre um morto, e chora como um homem que sofreu cruelmente. Sepulta o seu corpo segundo o costume, e não descuides de sua sepultura.

[[v28-38-17]]

^<<v28-38-17,17>>^ Chora-o amargamente durante um dia, por causa da opinião pública, e depois consola-te de tua tristeza;^&#42;1^

[[v28-38-18]]

^<<v28-38-18,18>>^ toma luto segundo o merecimento da pessoa, um dia ou dois, para evitar as más palavras.

[[v28-38-19]]

^<<v28-38-19,19>>^ Pois a tristeza apressa a morte, tira o vigor, e o desgosto do coração faz inclinar a cabeça.

[[v28-38-20]]

^<<v28-38-20,20>>^ A tristeza permanece quando o corpo é levado; e a vida do pobre é o espelho de seu coração.^&#42;1^

[[v28-38-21]]

^<<v28-38-21,21>>^ Não entregues teu coração à tristeza, mas afasta-a e lembra-te do teu fim.

[[v28-38-22]]

^<<v28-38-22,22>>^ Não te esqueças dele, porque não há retorno; de nada lhe servirás e só causarás dano a ti mesmo.

[[v28-38-23]]

^<<v28-38-23,23>>^ Lembra-te da sentença que me foi dada: a tua será igual; ontem para mim, hoje para ti.

[[v28-38-24]]

^<<v28-38-24,24>>^ Na paz em que o morto entrou, deixa repousar a sua memória, e conforta-o no momento em que exalar o último suspiro.

[[v28-38-25]]

^<<v28-38-25,25>>^ A sabedoria do escriba lhe vem no tempo do lazer. Aquele que pouco se agita adquirirá sabedoria.

[[v28-38-26]]

^<<v28-38-26,26>>^ Que sabedoria poderia ter o homem que conduz a charrua, que faz ponto de honra aguilhoar os bois, que participa de seu labor, e só sabe falar das crias dos touros?

[[v28-38-27]]

^<<v28-38-27,27>>^ Ele põe todo o seu coração em traçar sulcos, e o seu cuidado é engordar novilhas.

[[v28-38-28]]

^<<v28-38-28,28>>^ Igualmente acontece com todo carpinteiro, todo arquiteto, que passa no trabalho os dias e as noites. Assim sucede àquele que grava as marcas dos sinetes, variando as figuras por um trabalho assíduo; que aplica todo o seu coração na imitação da pintura, e põe todo o cuidado no acabamento de seu trabalho.

[[v28-38-29]]

^<<v28-38-29,29>>^ Assim acontece com o ferreiro sentado perto da bigorna, examinando o ferro que vai amoldar; o vapor do fogo queima as suas carnes, e ele resiste ao ardor da fornalha.

[[v28-38-30]]

^<<v28-38-30,30>>^ O barulho do martelo lhe fere o ouvido de golpes repetidos; seus olhos estão fixos no modelo do objeto.

[[v28-38-31]]

^<<v28-38-31,31>>^ Ele aplica o seu coração em aperfeiçoar a sua obra, e põe um cuidado vigilante em torná-la bela e perfeita.

[[v28-38-32]]

^<<v28-38-32,32>>^ O mesmo sucede com o oleiro que, entregue à sua tarefa, gira a roda com os pés, sempre cuidadoso pela sua obra; e todo o seu trabalho visa a produzir uma quantidade determinada.

[[v28-38-33]]

^<<v28-38-33,33>>^ Com o seu braço dá forma ao barro, torna-o maleável com os pés,

[[v28-38-34]]

^<<v28-38-34,34>>^ aplica o seu coração em aperfeiçoar o verniz, e limpa o forno com muita diligência.

[[v28-38-35]]

^<<v28-38-35,35>>^ Todos esses artistas esperam tudo de suas mãos; cada um deles é sábio em sua profissão.

[[v28-38-36]]

^<<v28-38-36,36>>^ Sem eles nenhuma cidade seria construída,

[[v28-38-37]]

^<<v28-38-37,37>>^ nem habitada, nem frequentada; mas eles mesmos não terão parte na assembleia,^&#42;1^

[[v28-38-38]]

^<<v28-38-38,38>>^ não se sentarão nas cadeiras dos juízes, não entenderão as disposições judiciárias, não apregoarão nem a instrução nem o direito, nem serão encontrados a estudar as máximas.

[[v28-38-39]]

^<<v28-38-39,39>>^ Entretanto, sustentam as coisas deste mundo. Sua oração se refere aos trabalhos de sua arte; a eles aplicam sua alma, e estudam juntos a Lei do Altíssimo.^&#42;1^

'''

xref:028-eclesiastico/028-eclesiastico-037.adoc#v28-37-0[&#60; Capítulo Anterior] | <<v28-38-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-039.adoc#v28-39-0[Próximo Capítulo &#62;]