include::./index.adoc[]

[[v28-29-0]]
=== Eclesiástico, 29
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 29 fala sobre a importância da amizade e do empréstimo de dinheiro. O capítulo começa com uma reflexão sobre a felicidade de se ter amigos verdadeiros e confiáveis, e também aborda o tema do empréstimo de dinheiro a amigos e a necessidade de ser cuidadoso nesse assunto. Com base nesses temas, seguem abaixo cinco versículos relacionados:
* Provérbios 17:17: "Em todo tempo ama o amigo e para a hora da angústia nasce o irmão." Este versículo fala sobre a importância da amizade verdadeira, que deve ser cultivada em todos os momentos, especialmente nos momentos difíceis.
* Provérbios 19:17: "Quem trata bem os pobres empresta ao Senhor, que lhe pagará o seu benefício." Esse versículo fala sobre a bondade em ajudar os pobres e necessitados, mostrando que emprestar dinheiro para aqueles que precisam é uma forma de ajudar o próximo.
* Provérbios 22:7: "O rico domina sobre os pobres, e o que toma emprestado é servo do que empresta." Esse versículo aborda o perigo de se endividar e ficar subordinado ao credor, mostrando que é importante agir com sabedoria financeira.
* Lucas 6:34-35: "E, se emprestais àqueles de quem esperais receber, que mérito tendes? Também os pecadores emprestam aos pecadores, para receberem outro tanto. Amai, porém, os vossos inimigos, fazei bem e emprestai, sem nada esperar em troca; e grande será o vosso galardão, e sereis filhos do Altíssimo; porque ele é benigno até para com os ingratos e maus." Esse versículo mostra que devemos emprestar não apenas para aqueles de quem esperamos receber de volta, mas também para aqueles que não são nossos amigos e inimigos, agindo com amor e generosidade.
* Romanos 13:8: "A ninguém devais coisa alguma, a não ser o amor com que vos ameis uns aos outros; porque quem ama aos outros cumpriu a lei." Esse versículo enfatiza a importância de não ficar devendo nada a ninguém, mostrando que é importante ser honesto e justo em todas as nossas relações financeiras e interpessoais.
****

[[v28-29-1]]

^<<v28-29-1,1>>^ Aquele que tem compaixão empresta com juros ao seu próximo; aquele que tem a mão generosa guarda os mandamentos.

[[v28-29-2]]

^<<v28-29-2,2>>^ Empresta a teu próximo quando ele estiver necessitado, e de teu lado, paga-lhe o que lhe deves, no tempo marcado.

[[v28-29-3]]

^<<v28-29-3,3>>^ Cumpre tua palavra e procede lealmente com ele, e acharás em toda ocasião o que te é necessário.

[[v28-29-4]]

^<<v28-29-4,4>>^ Muitos consideraram como um achado o que pediam emprestado, e causaram desgosto àqueles que os ajudaram.

[[v28-29-5]]

^<<v28-29-5,5>>^ Até que se tenha recebido, beija-se a mão de quem empresta; com voz humilde fazem-se promessas;^&#42;1^

[[v28-29-6]]

^<<v28-29-6,6>>^ mas, chegando o tempo de restituir, pedem-se prazos; só se têm palavras pesarosas e queixas; e toma-se como pretexto a dificuldade da época.

[[v28-29-7]]

^<<v28-29-7,7>>^ Se o que pede emprestado pode restituir, nega-se a princípio. Restitui em seguida só a metade da quantia, e a considera como um lucro.

[[v28-29-8]]

^<<v28-29-8,8>>^ Se não tem meios para pagar, priva o que emprestou do seu dinheiro, e dele se faz gratuitamente um inimigo.

[[v28-29-9]]

^<<v28-29-9,9>>^ Ele o paga com ofensas e maldições, e paga com o mal o bem que recebeu.

[[v28-29-10]]

^<<v28-29-10,10>>^ Muitos não emprestam, não por maldade, mas por medo de serem injustamente iludidos.^&#42;1^

[[v28-29-11]]

^<<v28-29-11,11>>^ Todavia, sê indulgente para com o miserável, e não o faças esmorecer depois da esmola.

[[v28-29-12]]

^<<v28-29-12,12>>^ Por causa do mandamento, socorre o pobre; e não o deixes ir com as mãos vazias na sua indigência.

[[v28-29-13]]

^<<v28-29-13,13>>^ Perde o teu dinheiro em favor de teu irmão e de teu amigo; não o escondas debaixo de uma pedra para ficar perdido.

[[v28-29-14]]

^<<v28-29-14,14>>^ Gasta o teu tesouro segundo o preceito do Altíssimo, e isso te aproveitará mais do que o ouro.

[[v28-29-15]]

^<<v28-29-15,15>>^ Encerra a esmola no coração do pobre, e ela rogará por ti, a fim de te preservar de todo o mal.^&#42;1^

[[v28-29-16]]

^<<v28-29-16,16>>^ Para combater o teu inimigo, ela será uma arma mais poderosa do que o escudo e a lança de um homem valente.^&#42;1^

[[v28-29-17]]

^<<v28-29-17,17>>^ 

[[v28-29-18]]

^<<v28-29-18,18>>^ 

[[v28-29-19]]

^<<v28-29-19,19>>^ O homem de bem responsabiliza-se pelo próximo; o homem sem pejo abandona-o a si próprio.

[[v28-29-20]]

^<<v28-29-20,20>>^ Não esqueças o benefício daquele que se responsabiliza por ti, pois ele arriscou a vida para te amparar.

[[v28-29-21]]

^<<v28-29-21,21>>^ O pecador e o impudico fogem de seu fiador;

[[v28-29-22]]

^<<v28-29-22,22>>^ o pecador atribui a si mesmo o benefício de quem por ele se responsabiliza, e com coração ingrato abandona o seu libertador.

[[v28-29-23]]

^<<v28-29-23,23>>^ Um homem se responsabiliza pelo seu próximo, e este, perdendo a vergonha, o abandonará.

[[v28-29-24]]

^<<v28-29-24,24>>^ Um mau penhor perdeu muitas pessoas que prosperavam, e as agitou como as ondas do mar;

[[v28-29-25]]

^<<v28-29-25,25>>^ por uma reviravolta das coisas, ele exilou muitos poderosos, que se tornaram peregrinos em terra estrangeira.

[[v28-29-26]]

^<<v28-29-26,26>>^ O pecador que transgride o mandamento do Senhor se comprometerá a responder inoportunamente por outro; e aquele que tentar muitos empreendimentos não escapará do processo.

[[v28-29-27]]

^<<v28-29-27,27>>^ Ajuda o próximo conforme as tuas posses, e acautela-te para que não caias tu também.

[[v28-29-28]]

^<<v28-29-28,28>>^ O principal para a vida do homem é a água, o pão, o vestuário e uma casa para ocultar a sua nudez.

[[v28-29-29]]

^<<v28-29-29,29>>^ Mais vale o que um pobre come sob um vigamento do que um magnífico banquete em casa alheia para quem não tem domicílio.

[[v28-29-30]]

^<<v28-29-30,30>>^ Contenta-te com o pouco ou muito que tiveres e evitarás a censura de seres um estranho.

[[v28-29-31]]

^<<v28-29-31,31>>^ É uma vida miserável a daquele que vai de casa em casa; em toda parte onde se hospedar, não estará confiante, e não ousará abrir a boca.

[[v28-29-32]]

^<<v28-29-32,32>>^ Recebe-se com hospitalidade, dá-se de comer e de beber a ingratos; e, depois disso, ouvem-se palavras desagradáveis:^&#42;1^

[[v28-29-33]]

^<<v28-29-33,33>>^ “Vamos, intruso, prepara a mesa, e o que tens, dá-o de comer aos outros;

[[v28-29-34]]

^<<v28-29-34,34>>^ retira-te, por causa da homenagem que devo prestar aos meus amigos. Preciso de minha casa para nela receber meu irmão”.^&#42;1^

[[v28-29-35]]

^<<v28-29-35,35>>^ Eis coisas penosas para um homem sensato: ouvir censuras pela hospitalidade e pelo empréstimo que se fez.

'''

xref:028-eclesiastico/028-eclesiastico-028.adoc#v28-28-0[&#60; Capítulo Anterior] | <<v28-29-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-030.adoc#v28-30-0[Próximo Capítulo &#62;]