include::./index.adoc[]

[[v28-49-0]]
=== Eclesiástico, 49
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 49 descreve a história de Israel desde o tempo de Josué até a era dos profetas, enfatizando a importância dos líderes justos e a punição daqueles que abandonaram a lei de Deus. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Deuteronômio 31:7-8: "Então Moisés chamou Josué e lhe disse na presença de todo o Israel: "Seja forte e corajoso, pois você irá com este povo para a terra que o Senhor jurou aos seus antepassados que lhes daria, e você os ajudará a tomá-la posse. O Senhor, Ele mesmo, irá à sua frente e estará com você; Ele nunca o deixará nem o abandonará. Não tenha medo; não se desanime." Este versículo fala sobre a passagem da liderança de Moisés para Josué, destacando a importância da coragem e da confiança em Deus.
* Juízes 2:11-12: "Então os filhos de Israel fizeram o que era mau aos olhos do Senhor e serviram aos baalins, e deixaram ao Senhor Deus de seus pais, que os tinha tirado da terra do Egito, e seguiram outros deuses dentre os deuses dos povos que estavam ao seu redor, e adoraram a eles, e provocaram o Senhor." Este versículo descreve a infidelidade do povo de Israel para com Deus, mostrando as consequências da desobediência.
* 2 Samuel 23:3-4: "O Deus de Israel falou, a Rocha de Israel me disse: 'Quando alguém governa com justiça sobre os homens, quando governa no temor de Deus, é como a luz da manhã quando o sol brilha, como uma manhã sem nuvens quando a chuva faz florescer a relva na terra.'" Este versículo destaca a importância da justiça e do temor a Deus na liderança de um governante.
* Isaías 1:27: "Sião será resgatada com justiça, e aqueles que se arrependem, com retidão." Este versículo fala sobre a importância do arrependimento e da justiça, mostrando que aqueles que se voltam para Deus serão redimidos.
* Jeremias 31:33: "Esta é a aliança que farei com a casa de Israel depois daqueles dias", declara o Senhor. "Porei a minha lei no íntimo deles e a escreverei nos seus corações. Serei o Deus deles, e eles serão o meu povo." Este versículo fala sobre a promessa de Deus de colocar Sua lei no coração do povo de Israel, destacando a importância da obediência e da devoção a Ele.
****

[[v28-49-1]]

^<<v28-49-1,1>>^ A memória de Josias é como uma composição de aromas preparada pelo perfumista.

[[v28-49-2]]

^<<v28-49-2,2>>^ Em toda boca, sua lembrança é doce como o mel, como uma melodia em um festim regado de vinho.

[[v28-49-3]]

^<<v28-49-3,3>>^ Foi divinamente destinado a levar o povo à penitência, e robusteceu a piedade numa época de pecado.

[[v28-49-4]]

^<<v28-49-4,4>>^ Voltou o coração para o Senhor e fez desaparecer as abominações da impiedade.

[[v28-49-5]]

^<<v28-49-5,5>>^ Exceto Davi, Ezequias e Josias, todos pecaram:

[[v28-49-6]]

^<<v28-49-6,6>>^ os reis de Judá abandonaram a Lei do Altíssimo, e desprezaram o temor de Deus;

[[v28-49-7]]

^<<v28-49-7,7>>^ por isso, tiveram de entregar a outros o seu reino, e a sua glória a uma nação estrangeira.

[[v28-49-8]]

^<<v28-49-8,8>>^ Os inimigos queimaram a cidade eleita, a cidade santa, transformaram suas ruas em um deserto, conforme o que predissera Jeremias,

[[v28-49-9]]

^<<v28-49-9,9>>^ pois eles maltrataram aquele que havia sido consagrado profeta desde o ventre de sua mãe, para derrubar, para destruir, para arruinar, mas depois reedificar e renovar.

[[v28-49-10]]

^<<v28-49-10,10>>^ Foi Ezequiel quem teve essa visão gloriosa, que o Senhor lhe mostrou num carro de querubins.

[[v28-49-11]]

^<<v28-49-11,11>>^ Pois ele anunciou com uma chuva a sorte dos inimigos, assim como os bens reservados àquele que seguiam o caminho reto.^&#42;1^

[[v28-49-12]]

^<<v28-49-12,12>>^ Quanto aos doze profetas, refloresçam os seus ossos em seus túmulos, pois fortaleceram Jacó, e redimiram-se da servidão por uma fé corajosa.^&#42;1^

[[v28-49-13]]

^<<v28-49-13,13>>^ Como engrandecer a glória de Zorobabel? Foi ele como um anel na mão direita.

[[v28-49-14]]

^<<v28-49-14,14>>^ Do mesmo modo Josué, filho de Josedec; eles que, em seus dias, reconstruíram a casa de Deus, e tornaram a levantar o Templo Santo do Senhor, destinado a uma glória eterna.

[[v28-49-15]]

^<<v28-49-15,15>>^ Neemias viverá por longo tempo na recordação; ele reergueu nossas muralhas arruinadas, restabeleceu nossas portas e nossos trincos, e reedificou nossas casas.

[[v28-49-16]]

^<<v28-49-16,16>>^ Ninguém nasceu no mundo comparável a Henoc, pois ele também foi arrebatado desta terra;^&#42;1^

[[v28-49-17]]

^<<v28-49-17,17>>^ nem comparável a José, nascido para ser o príncipe de seus irmãos e o sustentáculo de sua raça, o governador de seus irmãos, e o esteio de seu povo.

[[v28-49-18]]

^<<v28-49-18,18>>^ Seus ossos foram conservados com cuidado: depois de sua morte fizeram profecia.

[[v28-49-19]]

^<<v28-49-19,19>>^ Set e Sem foram glorificados entre os homens, porém, acima de qualquer ser vivo da Criação, acha-se Adão.

'''

xref:028-eclesiastico/028-eclesiastico-048.adoc#v28-48-0[&#60; Capítulo Anterior] | <<v28-49-0,Topo>> | xref:028-eclesiastico/028-eclesiastico-050.adoc#v28-50-0[Próximo Capítulo &#62;]