include::./index.adoc[]

[[v5-10-0]]
=== Deuteronômio, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 10 enfatiza a grandeza e a bondade de Deus, bem como a importância de obedecer aos Seus mandamentos. Moisés lembra o povo de como Deus renovou as tábuas da lei depois que eles as quebraram, e de como Ele os guiou pelo deserto durante quarenta anos. Ele também exorta o povo a temer o Senhor, servir a Ele com todo o coração e guardar os mandamentos que Ele lhes deu.
* Salmos 111:10: "O temor do SENHOR é o princípio da sabedoria; bom entendimento têm todos os que cumprem os seus mandamentos; o seu louvor permanece para sempre." Este versículo enfatiza a importância do temor do Senhor e da obediência aos Seus mandamentos, que é um tema central de Deuteronômio 10.
* Provérbios 3:5-6: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." Este versículo encoraja a confiança total em Deus e a busca pela Sua orientação, que também é um tema de Deuteronômio 10.
* Isaías 6:8: "Depois disto ouvi a voz do Senhor, que dizia: A quem enviarei, e quem há de ir por nós? Então disse eu: Eis-me aqui, envia-me a mim." Este versículo fala sobre a disposição de Isaías de ser enviado por Deus em uma missão, uma atitude semelhante àquela que Moisés encoraja no povo de Israel em Deuteronômio 10.
* Josué 22:5: "Tão somente tende cuidado de guardar com diligência o mandamento e a lei que Moisés, o servo do SENHOR, vos ordenou: que ameis ao SENHOR, vosso Deus, e andeis em todos os seus caminhos, e guardeis os seus mandamentos, e vos achegueis a ele, e o sirvais com todo o vosso coração e com toda a vossa alma." Este versículo enfatiza a importância de guardar diligentemente os mandamentos de Deus e de amá-Lo com todo o coração, como também é mencionado em Deuteronômio 10.
* Mateus 22:37-39: "Respondeu-lhe Jesus: Amarás o Senhor, teu Deus, de todo o teu coração, de toda a tua alma e de todo o teu entendimento. Este é o grande e primeiro mandamento. E o segundo, semelhante a este, é: Amarás o teu próximo como a ti mesmo." Este versículo fala sobre os dois maiores mandamentos de Deus: amá-Lo com todo o coração, alma e entendimento, e amar o próximo como a si mesmo, que também são valores enfatizados em Deuteronômio 10.
****

[[v5-10-1]]

^<<v5-10-1,1>>^ ‘‘Naquele mesmo tempo, o Senhor disse-me: ‘Corta duas tábuas de pedra semelhantes às primeiras, e sobe para junto de mim no monte, depois de ter fabricado uma arca de madeira.

[[v5-10-2]]

^<<v5-10-2,2>>^ Escreverei nessas tábuas as palavras que se achavam nas primeiras que quebraste, e tu as porás na arca’.

[[v5-10-3]]

^<<v5-10-3,3>>^ Fiz, pois, uma arca de madeira de acácia, e cortei duas tábuas de pedra semelhantes às primeiras; depois disso, com as duas tábuas na mão, subi ao monte.

[[v5-10-4]]

^<<v5-10-4,4>>^ O Senhor gravou nas novas pedras o que tinha escrito nas primeiras, as dez palavras que ele vos tinha dirigido no monte, do meio do fogo, no dia da assembleia. Devolveu-me em seguida, e

[[v5-10-5]]

^<<v5-10-5,5>>^ desci da montanha para depô-las na arca que tinha feito. E elas lá estão, como o Senhor me tinha ordenado.

[[v5-10-6]]

^<<v5-10-6,6>>^ Os israelitas partiram de Beerot-Benê-Yacan para Mosera, onde morreu Aarão. Seu filho Eleazar exerceu as funções sacerdotais em seu lugar, depois que foi enterrado ali.

[[v5-10-7]]

^<<v5-10-7,7>>^ Dali, foram a Gadgad, de Gadgad a Jotebata, onde havia água e torrentes em abundância.

[[v5-10-8]]

^<<v5-10-8,8>>^ Foi nesse mesmo tempo que o Senhor designou a tribo de Levi para levar a arca da aliança do Senhor, para estar na sua presença, servi-lo e abençoar em seu nome, o que ela continua fazendo sempre.

[[v5-10-9]]

^<<v5-10-9,9>>^ Por isso, Levi não teve parte nem herança com seus irmãos: porque o Senhor mesmo é o seu patrimônio, como lhe prometeu o Senhor, teu Deus.

[[v5-10-10]]

^<<v5-10-10,10>>^ Como da primeira vez, fiquei sobre o monte quarenta dias e quarenta noites, e ainda dessa vez o Senhor ouviu-me e renunciou a destruir-te.

[[v5-10-11]]

^<<v5-10-11,11>>^ Mas disse-me: ‘Vai e marcha à frente do povo, para que entre e possua a terra que jurei a seus pais dar-lhe’.”

[[v5-10-12]]

^<<v5-10-12,12>>^ E agora, ó Israel, o que pede a ti o Senhor, teu Deus, senão que o temas, andando nos seus caminhos, amando-o e servindo-o de todo o teu coração e de toda a tua alma,

[[v5-10-13]]

^<<v5-10-13,13>>^ observando os mandamentos do Senhor e suas leis, que hoje te prescrevo, para que sejas feliz?

[[v5-10-14]]

^<<v5-10-14,14>>^ Vê, ao Senhor, teu Deus, pertencem o céu e o céu dos céus, a terra e tudo o que nela se encontra.

[[v5-10-15]]

^<<v5-10-15,15>>^ Não obstante, só a teus pais se apegou o Senhor com amor, e elegeu a sua posteridade, depois deles, a vós, dentre todas as nações, como o vedes presentemente.

[[v5-10-16]]

^<<v5-10-16,16>>^ Cortai, pois, o prepúcio de vosso coração, e cessai de endurecer vossa cerviz;^&#42;1^

[[v5-10-17]]

^<<v5-10-17,17>>^ porque o Senhor, vosso Deus, é o Deus dos deuses e o Senhor dos senhores, o Deus grande, poderoso e temível, que não faz distinção de pessoas, nem aceita presentes.^&#42;1^

[[v5-10-18]]

^<<v5-10-18,18>>^ Ele faz justiça ao órfão e à viúva, e ama o estrangeiro, ao qual dá alimento e vestuário.

[[v5-10-19]]

^<<v5-10-19,19>>^ Também vós, amai o estrangeiro, porque fostes estrangeiros no Egito.

[[v5-10-20]]

^<<v5-10-20,20>>^ Temerás o Senhor, teu Deus, e o servirás. Estarás unido a ele, e só pelo seu nome farás os teus juramentos.

[[v5-10-21]]

^<<v5-10-21,21>>^ Ele é a tua glória e o teu Deus, que fez por ti estas grandes e terríveis coisas que viste com os teus olhos.

[[v5-10-22]]

^<<v5-10-22,22>>^ Quando os teus pais desceram ao Egito eram em número de setenta pessoas, e agora o Senhor, teu Deus, multiplicou-te como as estrelas do céu.

'''

xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[&#60; Capítulo Anterior] | <<v5-10-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[Próximo Capítulo &#62;]