include::./index.adoc[]

[[v5-12-0]]
=== Deuteronômio, 12
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 12 trata principalmente das orientações dadas por Moisés ao povo de Israel sobre o local e o modo correto de adoração a Deus, destacando a importância de não seguir as práticas pagãs das nações vizinhas. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Josué 24:15: "Porém, se vos parece mal aos vossos olhos servir ao Senhor, escolhei hoje a quem sirvais; se aos deuses a quem serviram vossos pais, que estavam além do Rio, ou aos deuses dos amorreus, em cuja terra habitais; porém eu e a minha casa serviremos ao Senhor." Este versículo mostra a importância da escolha de adorar somente ao Senhor, e não se curvar diante de outros deuses.
* 2 Reis 17:35: "O Senhor fez aliança com eles e lhes ordenou: Não temais outros deuses, nem os adorai, nem os servi, nem lhes ofereçais sacrifícios." Este versículo reforça a importância da aliança entre Deus e seu povo, e destaca a necessidade de não adorar outros deuses.
* Jeremias 7:3-4: "Assim diz o Senhor dos Exércitos, Deus de Israel: Emendai os vossos caminhos e as vossas obras, e vos farei habitar neste lugar. Não confieis em palavras falsas, dizendo: Templo do Senhor, templo do Senhor é este." Este versículo mostra a importância da sinceridade no culto a Deus, em contraste com a mera observância de rituais religiosos.
* Miquéias 6:6-8: "Com que me apresentarei ao Senhor, e me inclinarei diante do Deus altíssimo? Virei perante ele com holocaustos, com bezerros de um ano? Agradar-se-á o Senhor de milhares de carneiros, ou de dez mil ribeiros de azeite? Darei o meu primogênito pela minha transgressão, o fruto do meu corpo pelo pecado da minha alma? Ele te declarou, ó homem, o que é bom; e que é o que o Senhor pede de ti, senão que pratiques a justiça, e ames a benignidade, e andes humildemente com o teu Deus?" Este versículo destaca a importância da justiça, bondade e humildade como elementos centrais da adoração a Deus.
* João 4:23-24: "Mas a hora vem, e agora é, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade; porque o Pai procura a tais que assim o adorem. Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade." Este versículo reforça a importância de adorar a Deus de maneira genuína, em espírito e verdade, em vez de simplesmente seguir rituais vazios.
****

[[v5-12-1]]

^<<v5-12-1,1>>^ “Estas são as leis e preceitos que devereis observar na terra que o Senhor, o Deus de vossos pais, vos deu como propriedade por todos os dias de vossa vida na terra.

[[v5-12-2]]

^<<v5-12-2,2>>^ Todos os lugares em que os povos despojados por vós tiverem dado culto aos seus deuses, nos altos montes e colinas, ou debaixo de qualquer árvore frondosa, vós os destruireis completamente.

[[v5-12-3]]

^<<v5-12-3,3>>^ Derrubareis os seus altares, quebrareis suas estelas, cortareis suas asserás, jogareis no fogo os ídolos de seus deuses e apagareis os seus nomes daqueles lugares.

[[v5-12-4]]

^<<v5-12-4,4>>^ Não fareis assim com o Senhor, vosso Deus,

[[v5-12-5]]

^<<v5-12-5,5>>^ mas irás ao lugar que o Senhor, vosso Deus, escolher entre todas as vossas tribos para aí estabelecer o seu nome e unicamente ali irás procurá-lo.

[[v5-12-6]]

^<<v5-12-6,6>>^ É nesse lugar que apresentareis vossos holocaustos e vossos sacrifícios, vossos dízimos, vossas primícias, vossos votos, vossas ofertas espontâneas, os primogênitos de vossos rebanhos graúdo e miúdo.^&#42;1^

[[v5-12-7]]

^<<v5-12-7,7>>^ É ali que fareis vossos sagrados banquetes em presença do Senhor, vosso Deus, e gozareis, vós e vossas famílias, de todos os bens que vossas mãos produzirem, com a bênção do Senhor vosso Deus.

[[v5-12-8]]

^<<v5-12-8,8>>^ Não fareis nesse lugar o que nós fazemos hoje aqui, onde cada um faz o que bem lhe parece,

[[v5-12-9]]

^<<v5-12-9,9>>^ porque não entrastes ainda em vosso repouso e na possessão que vos dá o Senhor, vosso Deus.

[[v5-12-10]]

^<<v5-12-10,10>>^ Quando tiverdes passado o Jordão e vos tiverdes estabelecido na terra que o Senhor, vosso Deus, vos dá em herança, e ele vos tiver dado repouso, livrando-vos dos inimigos que vos cercam, de sorte que vivais em segurança,

[[v5-12-11]]

^<<v5-12-11,11>>^ então, ao lugar que o Senhor, vosso Deus, escolheu para estabelecer nele o seu nome, ali levareis todas as coisas que vos ordeno: vossos holocaustos, vossos sacrifícios, vossos dízimos, vossas primícias e todas as ofertas escolhidas que tiverdes prometido por voto ao Senhor.

[[v5-12-12]]

^<<v5-12-12,12>>^ Lá vos alegrarei em presença do Senhor, vosso Deus, vós, vossos filhos, vossas filhas, vossos servos e vossas servas, assim como o levita que se encontrar dentro de vossos muros, porque ele não tem parte nem herança em Israel.

[[v5-12-13]]

^<<v5-12-13,13>>^ Guarda-te de oferecer os teus holocaustos em qualquer lugar;

[[v5-12-14]]

^<<v5-12-14,14>>^ oferecerás unicamente no lugar que o Senhor escolher em uma de suas tribos, e é ali que oferecerás teus holocaustos e farás tudo o que te ordeno.

[[v5-12-15]]

^<<v5-12-15,15>>^ Se quiseres, entretanto, poderás comer carne, matar do teu rebanho, em qualquer cidade onde habitares, segundo as bênçãos que o Senhor, teu Deus, te der; tanto pode comê-la o homem impuro como o puro, como se come a gazela e o veado.^&#42;1^

[[v5-12-16]]

^<<v5-12-16,16>>^ Somente vos abstereis do sangue, que espalhareis sobre a terra como água.

[[v5-12-17]]

^<<v5-12-17,17>>^ Não comerás dentro dos teus muros o dízimo de teu trigo, nem de teu vinho, nem de teu óleo, nem os primogênitos de teu gado graúdo ou miúdo, nem aquilo que ofereceres por votos, nem tuas ofertas espontâneas, nem tuas primícias.

[[v5-12-18]]

^<<v5-12-18,18>>^ Mas comerás essas coisas diante do Senhor, teu Deus, no lugar que o Senhor, teu Deus, tiver escolhido, tu, teu filho, tua filha, teu servo e tua serva, assim como o levita que se encontrar dentro dos teus muros, alegrando-te na em presença do Senhor, por todos os bens que tuas mãos tiverem adquirido.

[[v5-12-19]]

^<<v5-12-19,19>>^ Guarda-te de abandonar o levita durante todo o tempo que viveres em teu solo.

[[v5-12-20]]

^<<v5-12-20,20>>^ Quando o Senhor, teu Deus, tiver alargado os teus limites, como te prometeu, e quando disseres, levado pelo desejo de comer carne: ‘Eu gostaria de comer carne’, come-a então quanto quiseres.

[[v5-12-21]]

^<<v5-12-21,21>>^ Se o lugar escolhido pelo Senhor, teu Deus, para nele ser invocado o seu nome, for muito afastado, poderás matar teus bois ou tuas ovelhas, que o Senhor te tiver dado, segundo o que te prescrevi, e poderás comer como te aprouver dentro de teus muros.

[[v5-12-22]]

^<<v5-12-22,22>>^ Como se come a carne da gazela ou do veado, assim comerás essas carnes: poderão comê-la tanto o homem impuro como o puro.

[[v5-12-23]]

^<<v5-12-23,23>>^ Mas guarda-te de absorver o sangue; porque o sangue é a vida, e tu não podes comer a vida com a carne^&#42;1^

[[v5-12-24]]

^<<v5-12-24,24>>^ Não beberás, pois, o sangue, mas o derramarás sobre a terra como água.

[[v5-12-25]]

^<<v5-12-25,25>>^ Não o sorverás, para que sejas feliz, tu e teus filhos depois de ti, por terdes feito o que é reto aos olhos do Senhor.

[[v5-12-26]]

^<<v5-12-26,26>>^ Mas as ofertas que te são impostas, ou as que fizeres em virtude de um voto, tu as tomarás contigo e irás ao lugar escolhido pelo Senhor;

[[v5-12-27]]

^<<v5-12-27,27>>^ ali as oferecerás em holocausto, carne e sangue, sobre o altar do Senhor, teu Deus. Quanto aos outros sacrifícios, o seu sangue será derramado sobre o altar do Senhor, teu Deus, e comerás as suas carnes.

[[v5-12-28]]

^<<v5-12-28,28>>^ Ouve todas essas ordens que te prescrevo e põe-nas em prática, para que sejas feliz perpetuamente, tu e teus filhos depois de ti, por terdes feito o que é bom e reto aos olhos do Senhor.

[[v5-12-29]]

^<<v5-12-29,29>>^ Quando o Senhor, teu Deus, tiver exterminado diante de ti as nações, cujos territórios invadirás para despojá-los, quando ocupares a sua terra,

[[v5-12-30]]

^<<v5-12-30,30>>^ guarda-te de cair no laço, imitando-as, depois de sua destruição. Guarda-te de seguir os seus deuses, dizendo: ‘Como adoravam essas nações os seus deuses, para que também eu faça o mesmo?’.

[[v5-12-31]]

^<<v5-12-31,31>>^ Não farás assim com o Senhor, teu Deus, porque tudo o que o Senhor odeia, tudo o que ele detesta, elas fizeram-no pelos seus deuses, chegando mesmo a queimar em sua honra os seus filhos e filhas.

'''

xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[&#60; Capítulo Anterior] | <<v5-12-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[Próximo Capítulo &#62;]