include::./index.adoc[]

[[v5-21-0]]
=== Deuteronômio, 21
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 21 trata de questões legais e sociais relacionadas a crimes, morte, casamento e herança. O capítulo começa com instruções sobre como lidar com um assassinato não resolvido, estabelecendo um ritual para purificar a terra e encontrar o culpado. Em seguida, são dadas orientações para a escolha de uma esposa de guerra, incluindo um período de luto e a possibilidade de divórcio. O capítulo continua com as regras sobre a primogenitura e a herança, e termina com a punição de um filho desobediente e rebelde.
* Levítico 24:17-18: "Aquele que matar qualquer homem, certamente será morto. E aquele que matar um animal, restituirá; mas aquele que matar um homem, será morto." Esse versículo estabelece a lei da retribuição, que é mencionada em Deuteronômio 21:1-9. Se um assassinato não resolvido ocorresse, a comunidade deveria realizar um ritual para purificar a terra e encontrar o culpado, caso contrário, a culpa seria atribuída a toda a comunidade.
* Juízes 21:10-12: "Então congregaram-se contra aquele lugar doze mil homens, dos filhos de Israel, e enviaram homens para verificar o assunto, os quais, voltando, trouxeram a notícia de que nenhuma pessoa daquela cidade havia escapado." Esse versículo fala sobre a punição de uma cidade inteira por causa do pecado de um indivíduo, que é mencionado em Deuteronômio 21:10-14. Se uma mulher prisioneira de guerra fosse escolhida como esposa, mas o marido não a desejasse mais, ela deveria ser libertada, mas não poderia ser vendida ou maltratada.
* 2 Reis 9:26: "Vês aqui o sangue de Nabote e o sangue de seus filhos, diz o Senhor; também te pagarei neste mesmo pedaço de terra, diz o Senhor. Agora, pois, toma-o e lança-o naquele campo, segundo a palavra do Senhor." Esse versículo fala sobre a punição de um assassino, que é mencionada em Deuteronômio 21:1-9. Se um assassinato não resolvido ocorresse, a comunidade deveria realizar um ritual para purificar a terra e encontrar o culpado, caso contrário, a culpa seria atribuída a toda a comunidade.
* Provérbios 13:24: "O que não faz uso da vara odeia seu filho, mas o que o ama, desde cedo o disciplina." Esse versículo fala sobre a punição de um filho desobediente e rebelde, que é mencionada em Deuteronômio 21:18-21. Se um filho fosse desobediente e rebelde, seus pais deveriam levá-lo aos líderes da cidade para que ele fosse punido.
****

[[v5-21-1]]

^<<v5-21-1,1>>^ “Quando, na terra cuja possessão te há de dar o Senhor, teu Deus, encontrar-se estendido no campo o cadáver de um homem assassinado sem que se saiba quem o feriu,

[[v5-21-2]]

^<<v5-21-2,2>>^ virão teus anciãos e teus juízes e medirão a distância que separa o cadáver das cidades dos arredores.

[[v5-21-3]]

^<<v5-21-3,3>>^ Os anciãos da cidade mais próxima onde foi encontrada a vítima tomarão uma novilha, com a qual não se tenha ainda trabalhado e que não tenha ainda levado o jugo,

[[v5-21-4]]

^<<v5-21-4,4>>^ e a conduzirão a um vale banhado por um córrego, cujas águas nunca sequem, onde não haja nem cultura nem sementeiras. E ali, no córrego, lhe quebrarão a nuca.

[[v5-21-5]]

^<<v5-21-5,5>>^ Chegarão em seguida os sacerdotes levíticos, porque foi a eles que o Senhor, teu Deus, escolheu para serem seus ministros. E abençoarão em seu nome, pois são eles que julgam todo litígio e todo caso de ferimento.

[[v5-21-6]]

^<<v5-21-6,6>>^ Então todos os anciãos da cidade encontrada mais próxima do cadáver lavarão suas mãos sobre a novilha cuja nuca quebraram no vale,

[[v5-21-7]]

^<<v5-21-7,7>>^ e dirão estas palavras: ‘Nossas mãos não derramaram este sangue, nem o viram os nossos olhos.

[[v5-21-8]]

^<<v5-21-8,8>>^ Ó Senhor, perdoai o vosso povo de Israel que resgatastes. Não lhe imputeis o sangue inocente’. Assim será o homicídio expiado por eles.

[[v5-21-9]]

^<<v5-21-9,9>>^ E, desse modo, tirarás do meio de ti o sangue inocente, e farás o que é reto aos olhos do Senhor.”

[[v5-21-10]]

^<<v5-21-10,10>>^ “Quando fores à guerra contra os teus inimigos e o Senhor, teu Deus, os entregar em tuas mãos, se os fizeres cativos,

[[v5-21-11]]

^<<v5-21-11,11>>^ e vires entre eles uma mulher formosa da qual te enamores e a queiras tomar por esposa,

[[v5-21-12]]

^<<v5-21-12,12>>^ tu a conduzirás à tua casa. Ela rapará os cabelos, cortará as unhas,^&#42;1^

[[v5-21-13]]

^<<v5-21-13,13>>^ deporá o vestido com que foi aprisionada e permanecerá em tua casa, chorando o seu pai e a sua mãe durante um mês. Depois disso, irás procurá-la, serás seu marido e ela será tua mulher.

[[v5-21-14]]

^<<v5-21-14,14>>^ Se ela cessar de te agradar, tu a deixarás partir como lhe aprouver, mas não poderás vendê-la por dinheiro, nem maltratá-la, pois fizeste dela tua mulher.”

[[v5-21-15]]

^<<v5-21-15,15>>^ “Se um homem tiver duas mulheres, uma que ele ama, outra que ele desdenha, e lhe tiverem dado filhos, tanto a que é amada como a que é desdenhada e se o filho desta última for o filho primogênito,^&#42;1^

[[v5-21-16]]

^<<v5-21-16,16>>^ esse homem, no dia em que repartir seus bens entre os seus filhos, não poderá dar o direito de primogenitura ao filho da que é amada, em detrimento do primogênito, filho da mulher desdenhada.

[[v5-21-17]]

^<<v5-21-17,17>>^ Mas reconhecerá por primogênito o filho da mulher desprezada, dando-lhe uma porção dupla de todos os seus bens, porque esse filho é o primeiro fruto de seu vigor, é a ele que pertence o direito de primogenitura.”

[[v5-21-18]]

^<<v5-21-18,18>>^ “Se um homem tiver um filho indócil e rebelde, que não atenda às ordens de seu pai nem de sua mãe, permanecendo insensível às suas correções,

[[v5-21-19]]

^<<v5-21-19,19>>^ seu pai e sua mãe o tomarão e o levarão aos anciãos da cidade à porta da localidade onde habitam,^&#42;1^

[[v5-21-20]]

^<<v5-21-20,20>>^ e lhes dirão: ‘Este nosso filho é indócil e rebelde; não nos ouve, e vive na embriaguez e na dissolução’.

[[v5-21-21]]

^<<v5-21-21,21>>^ Então, todos os homens da cidade o apedrejarão até que ele morra. Assim, tirarás o mal do meio de ti, e todo o Israel, ao sabê-lo, será possuído de temor.”

[[v5-21-22]]

^<<v5-21-22,22>>^ “Quando um homem tiver cometido um crime que deve ser punido com a morte, e for executado por enforcamento numa árvore,

[[v5-21-23]]

^<<v5-21-23,23>>^ o seu cadáver não poderá ficar ali durante a noite, mas tu o sepultarás no mesmo dia; pois aquele que é pendurado é um objeto de maldição divina. Assim, não contaminarás a terra que o Senhor, teu Deus, te dá por herança.”^&#42;1^

'''

xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[&#60; Capítulo Anterior] | <<v5-21-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-022.adoc#v5-22-0[Próximo Capítulo &#62;]