include::./index.adoc[]

[[v5-9-0]]
=== Deuteronômio, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 9 destaca a fidelidade de Deus em cumprir suas promessas ao povo de Israel, mesmo que eles tenham sido rebeldes e desobedientes. O capítulo também relembra o episódio em que Moisés intercedeu pelo povo, pedindo a misericórdia de Deus e sua decisão de destruí-los. Abaixo estão cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em Deuteronômio 9.
* Salmos 106:6: "Nós pecamos, como nossos pais; cometemos iniquidades, andamos perversamente." Este salmo reconhece a tendência humana ao pecado e desobediência a Deus, que foi a causa das dificuldades enfrentadas pelo povo de Israel.
* Salmos 130:3-4: "Se tu, Senhor, observares as iniquidades, Senhor, quem subsistirá? Mas contigo está o perdão, para que sejas temido." Este salmo destaca a graça e misericórdia de Deus em perdoar aqueles que se arrependem e confiam nele, como foi o caso de Israel quando Moisés intercedeu por eles.
* Provérbios 28:13: "O que encobre as suas transgressões nunca prosperará, mas o que as confessa e deixa alcançará misericórdia." Este versículo mostra a importância de reconhecer e confessar os pecados a Deus para receber sua misericórdia e perdão, como fez Moisés em nome do povo de Israel.
* Jeremias 31:33: "Mas este é o concerto que farei com a casa de Israel depois daqueles dias, diz o Senhor: Porei a minha lei no seu interior, e a escreverei no seu coração; e eu serei o seu Deus e eles serão o meu povo." Este versículo destaca a promessa de Deus de transformar o coração de seu povo e escrever sua lei em seus corações, para que possam obedecer e ser fiéis a ele.
* Romanos 3:23-24: "Porque todos pecaram e destituídos estão da glória de Deus; Sendo justificados gratuitamente pela sua graça, pela redenção que há em Cristo Jesus." Este versículo reforça a ideia de que todos pecaram e precisam da graça e misericórdia de Deus para serem justificados e salvos, como foi o caso do povo de Israel.
****

[[v5-9-1]]

^<<v5-9-1,1>>^ “Ouve, Israel: Hoje passarás o Jordão para despojar nações maiores e mais fortes do que tu, cidades importantes cujas muralhas sobem até o céu,

[[v5-9-2]]

^<<v5-9-2,2>>^ um povo forte e de alta estatura, descendente dos enacim, que conheces e dos quais ouviste dizer: ‘Quem poderá enfrentar os filhos de Enac?’.

[[v5-9-3]]

^<<v5-9-3,3>>^ Sabe, pois, hoje, que o Senhor, teu Deus, marcha diante de ti como um fogo devorador. É ele quem os destruirá e os esmagará diante de ti, de tal forma que tu os despojarás e os aniquilarás prontamente, como o Senhor te prometeu.

[[v5-9-4]]

^<<v5-9-4,4>>^ Depois que o Senhor, teu Deus, os tiver expulsado de diante de ti, não digas no teu coração: ‘Por causa de minha justiça é que o Senhor me introduziu na posse dessa terra’. Porque é por causa da perversidade dessas nações que o Senhor as despoja diante de ti.

[[v5-9-5]]

^<<v5-9-5,5>>^ Não é pela tua justiça nem pela retidão do teu coração que entrarás na posse de suas terras, mas é por causa da perversidade dessas nações que o Senhor as despoja diante de ti. E é também porque o Senhor, teu Deus, quer cumprir a palavra que deu com juramento a teus pais, Abraão, Isaac e Jacó.

[[v5-9-6]]

^<<v5-9-6,6>>^ Sabe, pois, que não é pela tua justiça que o Senhor, teu Deus, te dá a posse dessa terra excelente, porque és um povo de cabeça dura.

[[v5-9-7]]

^<<v5-9-7,7>>^ Lembra-te, não te esqueças de que modo irritaste o Senhor, teu Deus, no deserto. Desde o dia em que saíste do Egito até que chegaste a este lugar, não cessaste de ser rebelde ao Senhor.

[[v5-9-8]]

^<<v5-9-8,8>>^ Em Horeb, o provocaste de tal forma que ele, irado, quis aniquilar-te.

[[v5-9-9]]

^<<v5-9-9,9>>^ Quando eu subi ao monte para receber as tábuas de pedra, as tábuas da aliança que o Senhor fez convosco, permaneci no monte quarenta dias e quarenta noites, sem comer pão nem beber água.

[[v5-9-10]]

^<<v5-9-10,10>>^ E o Senhor entregou-me as duas tábuas de pedra escritas com o dedo de Deus, nas quais estavam gravadas todas as palavras que o Senhor vos tinha dirigido no monte, no meio do fogo, no dia da assembleia.

[[v5-9-11]]

^<<v5-9-11,11>>^ Passados quarenta dias e quarenta noites, o Senhor entregou-me as duas tábuas de pedra, as tábuas da aliança.

[[v5-9-12]]

^<<v5-9-12,12>>^ O Senhor disse-me: ‘Vamos, desce prontamente daqui, porque o teu povo que tiraste do Egito corrompeu-se. Depressa se desviaram do caminho que lhes mandei seguir: fabricaram para si um ídolo fundido’.

[[v5-9-13]]

^<<v5-9-13,13>>^ ‘Vejo – continuou o Senhor, que essa nação é um povo de cabeça dura.

[[v5-9-14]]

^<<v5-9-14,14>>^ Deixa que eu o aniquile e apague o seu nome de debaixo do céu. Farei de ti uma nação mais forte e mais numerosa do que esta’.

[[v5-9-15]]

^<<v5-9-15,15>>^ Tendo eu descido do monte, o qual ardia em fogo, trazendo na mão as duas tábuas da aliança,

[[v5-9-16]]

^<<v5-9-16,16>>^ verifiquei que vós tínheis de fato pecado contra o Senhor, vosso Deus, fabricando-vos um bezerro de metal fundido, e desviando-vos assim tão depressa do caminho que vos tinha traçado o Senhor.

[[v5-9-17]]

^<<v5-9-17,17>>^ Arrojei então de minhas mãos as duas tábuas e quebrei-as à vossa vista.

[[v5-9-18]]

^<<v5-9-18,18>>^ Prostrei-me em seguida diante do Senhor, como antes, e estive quarenta dias e quarenta noites sem comer pão, nem beber água, por causa de todos os pecados que tínheis cometido, fazendo o que é mau aos olhos do Senhor, e provocando-o à ira.

[[v5-9-19]]

^<<v5-9-19,19>>^ Eu estava aterrado vendo o furor do Senhor contra ti, a ponto de te querer destruir. Entretanto, ainda desta vez ele me ouviu.

[[v5-9-20]]

^<<v5-9-20,20>>^ Também contra Aarão o Senhor estava de tal forma irado que queria matá-lo, mas eu intercedi também por Aarão.

[[v5-9-21]]

^<<v5-9-21,21>>^ Quanto ao objeto de vosso pecado, o bezerro que tínheis feito, tomei-o, atirei-o ao fogo e o fiz em pedaços, esmagando-o até que fosse reduzido a pó; e joguei esse pó na torrente que desce da montanha.

[[v5-9-22]]

^<<v5-9-22,22>>^ Provocastes também o Senhor em Tabera, em Massa e em Quibrot-Hataava.

[[v5-9-23]]

^<<v5-9-23,23>>^ Quando o Senhor quis que partísseis de Cades Barne, dizendo: ‘Subi e tomai posse da terra que vos dei’, vós vos rebelastes contra a ordem do Senhor, desconfiando dele e não ouvistes a sua voz.

[[v5-9-24]]

^<<v5-9-24,24>>^ Desde que vos conheço, fostes sempre rebeldes ao Senhor.

[[v5-9-25]]

^<<v5-9-25,25>>^ Fiquei, portanto, quarenta dias e quarenta noites prostrado diante do Senhor, porque vos queria aniquilar.

[[v5-9-26]]

^<<v5-9-26,26>>^ Orando, eu disse-lhe: Senhor Javé, não destruais vosso povo, vossa herança, que resgatastes com a vossa grandeza e tirastes do Egito com mão forte.

[[v5-9-27]]

^<<v5-9-27,27>>^ Lembrai-vos de vossos servos Abraão, Isaac e Jacó. Não olheis para a dureza desse povo, para sua maldade e seu pecado,

[[v5-9-28]]

^<<v5-9-28,28>>^ para que os habitantes da terra de onde nos tirastes não digam: O Senhor não podia introduzi-los na terra que lhes tinha prometido, ou então: ele os odiava, e por isso tirou-os, a fim de matá-los no deserto.

[[v5-9-29]]

^<<v5-9-29,29>>^ E não obstante, eles são o vosso povo, a vossa herança, que tirastes do Egito com a vossa grande força e com o vosso braço estendido.”

'''

xref:005-deuteronomio/005-deuteronomio-008.adoc#v5-8-0[&#60; Capítulo Anterior] | <<v5-9-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[Próximo Capítulo &#62;]