include::./index.adoc[]

[[v5-30-0]]
=== Deuteronômio, 30
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 30 apresenta a escolha entre a bênção e a maldição, com Deus incentivando Seu povo a escolher a vida e obedecer a Sua lei. A seguir, estão cinco versículos relacionados aos temas abordados neste capítulo:
* Provérbios 10:16: "O salário do justo é a vida, e o rendimento do ímpio é o pecado." Este versículo relaciona-se com a escolha entre a bênção e a maldição apresentada em Deuteronômio 30, incentivando o povo a escolher a vida e seguir o caminho justo.
* Josué 24:15: "Se, porém, não lhes agrada servir ao Senhor, escolham hoje a quem irão servir, se aos deuses que os seus antepassados serviram além do Eufrates, ou aos deuses dos amorreus, em cuja terra vocês estão vivendo. Mas eu e a minha família serviremos ao Senhor". Neste versículo, Josué incentiva o povo a escolher servir ao Senhor e a obedecer Sua lei, o que é semelhante ao que é abordado em Deuteronômio 30.
* Provérbios 3:1-2: "Meu filho, não se esqueça da minha instrução, mas guarde no coração os meus mandamentos, pois eles prolongarão a sua vida por muitos anos e lhe darão prosperidade e paz." Este versículo reforça a ideia de que seguir a lei de Deus leva à vida e à prosperidade, que são bênçãos prometidas em Deuteronômio 30.
* Deuteronômio 10:12-13: "E agora, ó Israel, que é que o Senhor, o seu Deus, pede a vocês? Ele exige apenas que vocês o temam e sigam todos os seus caminhos, que o amem, sirvam ao Senhor, o seu Deus, de todo o coração e com toda a alma, e obedeçam aos seus mandamentos e leis que hoje lhes dou, para o seu próprio bem." Este versículo se relaciona com a escolha entre a bênção e a maldição apresentada em Deuteronômio 30, incentivando o povo a seguir os caminhos de Deus e obedecer a Sua lei para que possam experimentar a bênção prometida.
* Deuteronômio 11:26-28: "Hoje ponho diante de vocês a bênção e a maldição: a bênção, se obedecerem aos mandamentos do Senhor, o seu Deus, que hoje lhes dou; a maldição, se desobedecerem aos mandamentos do Senhor, o seu Deus, e se afastarem do caminho que hoje lhes ordeno que sigam, para seguir outros deuses que não conhecem." Este versículo é uma referência direta ao tema principal de Deuteronômio 30, enfatizando a escolha que o povo tem diante de si e as consequências de suas escolhas.
****

[[v5-30-1]]

^<<v5-30-1,1>>^ “Quando, pois, tiverem acontecido todas essas coisas e postas diante de ti a bênção ou a maldição, se tu as tomares a peito no meio de todas as nações entre as quais o Senhor, teu Deus, te tiver espalhado,

[[v5-30-2]]

^<<v5-30-2,2>>^ e voltares então para o Senhor, e obedeceres à sua voz de todo o teu coração e de toda a tua alma, tu e os teus filhos, conformando-vos a tudo o que hoje vos ordeno,

[[v5-30-3]]

^<<v5-30-3,3>>^ então o Senhor, teu Deus, reconduzirá teus cativos e terá piedade de ti, e te ajuntará de novo do meio das nações entre as quais te houver espalhado.

[[v5-30-4]]

^<<v5-30-4,4>>^ Ainda que os teus exilados se encontrassem na extremidade dos céus, dali te tiraria o Senhor, teu Deus, e ali mesmo iria ele buscar-te.

[[v5-30-5]]

^<<v5-30-5,5>>^ O Senhor, teu Deus, te reconduzirá à terra que possuíam os teus pais e te dará a sua possessão. E te fará prosperar e multiplicar mais que os teus pais.

[[v5-30-6]]

^<<v5-30-6,6>>^ O Senhor, teu Deus, te circuncidará o coração e o de tua descendência, para que ames o Senhor de todo o teu coração e de toda a tua alma, a fim de que possas viver.

[[v5-30-7]]

^<<v5-30-7,7>>^ O Senhor, teu Deus, fará cair todas essas maldições sobre os teus inimigos e sobre aqueles que te perseguem com ódio.

[[v5-30-8]]

^<<v5-30-8,8>>^ Tu, porém, voltarás a ouvir a voz do Senhor, e porás em prática todas as ordens que hoje te prescrevo.

[[v5-30-9]]

^<<v5-30-9,9>>^ O Senhor, teu Deus, te encherá de bens em todas as obras de tuas mãos, no fruto de tuas entranhas, no fruto de teus animais e nos produtos de teu solo, porque o Senhor se comprazerá de novo em fazer-te feliz, como se comprazia no tempo de teus pais,

[[v5-30-10]]

^<<v5-30-10,10>>^ contanto que obedeças à voz do Senhor, teu Deus, observando seus mandamentos e seus preceitos escritos neste livro da lei, e que voltes para o Senhor, teu Deus, de todo o teu coração e de toda a tua alma.

[[v5-30-11]]

^<<v5-30-11,11>>^ O mandamento que hoje te dou não está acima de tuas forças, nem fora de teu alcance.

[[v5-30-12]]

^<<v5-30-12,12>>^ Ele não está nos céus, para que digas: ‘Quem subirá ao céu para no-lo buscar e no-lo fazer ouvir para que o observemos?’.

[[v5-30-13]]

^<<v5-30-13,13>>^ Não está tampouco do outro lado do mar, para que digas: ‘Quem atravessará o mar para no-lo buscar e no-lo fazer ouvir para que o observemos?’.

[[v5-30-14]]

^<<v5-30-14,14>>^ Mas essa palavra está perto de ti, na tua boca e no teu coração, para que possas cumprir.

[[v5-30-15]]

^<<v5-30-15,15>>^ Olha que hoje ponho diante de ti a vida com o bem, e a morte com o mal.

[[v5-30-16]]

^<<v5-30-16,16>>^ Mando-te hoje que ames o Senhor, teu Deus, que andes em seus caminhos, observes seus mandamentos, suas leis e seus preceitos, para que vivas e te multipliques, e que o Senhor, teu Deus, te abençoe na terra em que vais entrar para possuí-la.

[[v5-30-17]]

^<<v5-30-17,17>>^ Se, porém, o teu coração se afastar, se não obedeceres e se te deixares seduzir para te prostrares diante de outros deuses e adorá-los,

[[v5-30-18]]

^<<v5-30-18,18>>^ eu te declaro neste dia: perecereis seguramente e não prolongareis os vossos dias na terra em que ides entrar para possuí-la, ao passar o Jordão.

[[v5-30-19]]

^<<v5-30-19,19>>^ Tomo hoje por testemunhas o céu e a terra contra vós: ponho diante de ti a vida e a morte, a bênção e a maldição. Escolhe, pois, a vida, para que vivas com a tua posteridade,

[[v5-30-20]]

^<<v5-30-20,20>>^ amando o Senhor, teu Deus, obedecendo à sua voz e permanecendo unido a ele. Porque é esta a tua vida e a longevidade dos teus dias na terra que o Senhor jurou dar a Abraão, Isaac e Jacó, teus pais.”

'''

xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[&#60; Capítulo Anterior] | <<v5-30-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[Próximo Capítulo &#62;]