include::./index.adoc[]

[[v5-6-0]]
=== Deuteronômio, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 6 contém a famosa passagem do "Shema Yisrael", que é uma afirmação central da fé judaica. O capítulo exorta os israelitas a amar a Deus com todo o seu coração, alma e força, e a ensinar os mandamentos de Deus a seus filhos e gerações futuras. Também destaca a importância de manter os mandamentos de Deus, lembrar das bênçãos que Deus concedeu ao povo de Israel e não se esquecer de Deus quando se estabelecer na Terra Prometida.
* Êxodo 20:6: "Mas mostro amor a milhares dos que me amam e guardam os meus mandamentos". Este versículo destaca a importância de amar a Deus e obedecer seus mandamentos, que são temas centrais de Deuteronômio 6.
* Deuteronômio 11:18-19: "Ponham estas minhas palavras em seu coração e em sua alma; amarrem-nas como um sinal nas mãos e prendam-nas na testa. Ensinem-nas a seus filhos, conversando a respeito delas quando estiverem sentados em casa e quando estiverem andando pelo caminho, quando se deitarem e quando se levantarem". Esse versículo fala da importância de ensinar os mandamentos de Deus às gerações futuras, um tema central em Deuteronômio 6.
* Deuteronômio 30:16: "Pois lhe ordeno hoje que ame o Senhor, o seu Deus, ande nos seus caminhos e guarde os seus mandamentos, decretos e ordenanças; então você viverá e se multiplicará, e o Senhor, o seu Deus, o abençoará na terra que você está entrando para possuir". Este versículo destaca a importância de amar a Deus e obedecer seus mandamentos para receber bênçãos e prosperidade, um tema importante em Deuteronômio 6.
* Provérbios 22:6: "Ensine a criança no caminho em que deve andar, e mesmo quando envelhecer não se desviará dele". Este versículo fala da importância de ensinar os filhos desde cedo sobre os caminhos de Deus, um tema que é enfatizado em Deuteronômio 6.
* Josué 24:15: "Mas, se não lhes agrada servir ao Senhor, escolham hoje a quem irão servir, se aos deuses que os seus antepassados serviram além do Eufrates, ou aos deuses dos amorreus, em cuja terra vocês estão vivendo. Mas eu e a minha família serviremos ao Senhor". Este versículo destaca a importância de fazer uma escolha consciente de servir a Deus e seguir seus mandamentos, um tema central em Deuteronômio 6.
****

[[v5-6-1]]

^<<v5-6-1,1>>^ “Eis as ordenações, as leis e os preceitos que o Senhor, vosso Deus, me ordenou ensinar-vos, a fim de que os pratiqueis na terra aonde ides entrar para tomar posse dela.

[[v5-6-2]]

^<<v5-6-2,2>>^ Assim, temerás o Senhor, teu Deus, observando todos os dias de tua vida, tu, teu filho e neto, todas as leis e os mandamentos que te prescrevo, e teus dias serão prolongados.

[[v5-6-3]]

^<<v5-6-3,3>>^ Tu os ouvirás, pois, ó Israel, e cuidarás de cumpri-los, para que sejas feliz e te multipliques copiosamente na terra que mana leite e mel, como te prometeu o Senhor, o Deus de teus pais.

[[v5-6-4]]

^<<v5-6-4,4>>^ Ouve, ó Israel! O Senhor, nosso Deus, é o único Senhor.

[[v5-6-5]]

^<<v5-6-5,5>>^ Amarás o Senhor, teu Deus, com todo o teu coração, com toda a tua alma e com todas as tuas forças.^&#42;1^

[[v5-6-6]]

^<<v5-6-6,6>>^ Os mandamentos que hoje te dou serão gravados no teu coração.

[[v5-6-7]]

^<<v5-6-7,7>>^ Tu os inculcarás a teus filhos e deles falarás, seja sentado em tua casa, seja andando pelo caminho, ao te deitares e ao te levantares.

[[v5-6-8]]

^<<v5-6-8,8>>^ Hás de prendê-los à tua mão como sinal, e os levarás como uma faixa frontal diante dos teus olhos.

[[v5-6-9]]

^<<v5-6-9,9>>^ Tu os escreverás nos umbrais e nas portas de tua casa.

[[v5-6-10]]

^<<v5-6-10,10>>^ Quando o Senhor, teu Deus, te tiver introduzido na terra que a teus pais, Abraão, Isaac e Jacó, jurou te dar; grandes e excelentes cidades que não construíste,

[[v5-6-11]]

^<<v5-6-11,11>>^ casas mobiliadas e cheias de toda a sorte de coisas, que não ajuntaste, poços que não cavaste, vinhas e olivais que não plantaste, e quando comeres à saciedade,

[[v5-6-12]]

^<<v5-6-12,12>>^ então, guarda-te de esquecer o Senhor que te tirou do Egito, da casa da servidão.

[[v5-6-13]]

^<<v5-6-13,13>>^ Temerás o Senhor, teu Deus, a ele servirás o teu culto e só jurarás pelo seu nome.^&#42;1^

[[v5-6-14]]

^<<v5-6-14,14>>^ Não seguireis outros deuses entre os das nações que vos cercam,

[[v5-6-15]]

^<<v5-6-15,15>>^ porque o Senhor, teu Deus, que mora no meio de ti, é um Deus zeloso; sua cólera se inflamaria contra ti e te apagaria de sobre a terra.

[[v5-6-16]]

^<<v5-6-16,16>>^ Não provocareis o Senhor, vosso Deus, como o tentastes em Massa.^&#42;1^

[[v5-6-17]]

^<<v5-6-17,17>>^ Observareis suas ordenações, seus preceitos e suas leis.

[[v5-6-18]]

^<<v5-6-18,18>>^ Farás o que é bom e reto diante dos seus olhos, para que sejas feliz e possuas a terra que o Senhor jurou a teus pais dar-te,

[[v5-6-19]]

^<<v5-6-19,19>>^ quando expulsasse de diante de ti todos os teus inimigos, como disse o Senhor.

[[v5-6-20]]

^<<v5-6-20,20>>^ Quando teu filho te perguntar mais tarde: ‘Que são estes mandamentos, estas leis e estes preceitos que o Senhor, nosso Deus, nos prescreveu?’. Tu lhe responderás:

[[v5-6-21]]

^<<v5-6-21,21>>^ ‘Éramos escravos do faraó, no Egito, e a mão poderosa do Senhor libertou-nos.

[[v5-6-22]]

^<<v5-6-22,22>>^ À nossa vista operou o Senhor prodígios e grandes e espantosos sinais contra o Egito, contra o faraó e toda a sua família.

[[v5-6-23]]

^<<v5-6-23,23>>^ Tirou-nos de lá para conduzir-nos à terra que, com juramento, havia prometido a nossos pais dar-nos.

[[v5-6-24]]

^<<v5-6-24,24>>^ O Senhor ordenou-nos que observássemos todas essas leis e temêssemos o Senhor, nosso Deus, para sermos sempre felizes e para que nos conservasse a vida, como o fez até o presente.

[[v5-6-25]]

^<<v5-6-25,25>>^ Seremos, pois, tidos por justos, se tivermos o cuidado de nos conformar a toda essa lei diante do Senhor, nosso Deus, como ele nos mandou’.”

'''

xref:005-deuteronomio/005-deuteronomio-005.adoc#v5-5-0[&#60; Capítulo Anterior] | <<v5-6-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[Próximo Capítulo &#62;]