include::./index.adoc[]

[[v5-24-0]]
=== Deuteronômio, 24
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 24 contém leis sobre o divórcio, o perdão de dívidas, a colheita e a proteção dos direitos dos trabalhadores. O capítulo também enfatiza a importância de tratar os outros com justiça e misericórdia.
* Provérbios 22:22-23: "Não roube o pobre, porque é pobre, nem esmague o necessitado no tribunal, pois o Senhor defenderá a causa deles e tirará a vida daqueles que os roubam." Este versículo enfatiza a importância de tratar os necessitados com justiça e não explorá-los.
* Tiago 5:4: "Eis que o salário dos trabalhadores que ceifaram os vossos campos, e que por vós foi retido com fraude, está clamando; e os clamores dos ceifeiros penetraram até aos ouvidos do Senhor dos Exércitos." Este versículo fala sobre a importância de pagar os trabalhadores de forma justa e não retê-los de seus salários.
* Isaías 61:8: "Porque eu, o Senhor, amo a justiça e odeio o roubo e o mal em suas diversas formas. Eu lhes darei pagamento justo e farei uma aliança eterna com eles." Este versículo destaca a importância da justiça e condena o roubo e a exploração.
* 1 João 3:17: "Mas se alguém tem recursos materiais e vê seu irmão passando necessidade, mas fecha o coração para ele, como pode estar nele o amor de Deus?" Este versículo destaca a importância de ajudar aqueles que estão em necessidade e não ser egoísta com nossos recursos.
* Mateus 6:14-15: "Pois se perdoarem as ofensas uns dos outros, o Pai celestial também perdoará vocês. Mas se não perdoarem uns aos outros, o Pai celestial não perdoará as ofensas de vocês." Este versículo destaca a importância do perdão e da misericórdia, que é enfatizado em Deuteronômio 24 em relação ao cancelamento das dívidas.
****

[[v5-24-1]]

^<<v5-24-1,1>>^ “Se um homem, tendo escolhido uma mulher, casar-se com ela, e vier a odiá-la por descobrir nela qualquer coisa inconveniente, escreverá uma letra de divórcio, lhe entregará na mão e a despedirá de sua casa.^&#42;1^

[[v5-24-2]]

^<<v5-24-2,2>>^ Se ela, depois de ter saído de sua casa, desposar outro homem,

[[v5-24-3]]

^<<v5-24-3,3>>^ e este também a odiar, escrevendo e dando-lhe na mão uma letra de divórcio e despedindo-a de sua casa, ou então, se este segundo marido vier a falecer,

[[v5-24-4]]

^<<v5-24-4,4>>^ não poderá o primeiro marido, que a repudiou, tomá-la de novo por mulher depois de ela se contaminar, porque isso é uma abominação aos olhos do Senhor e não deves comprometer com esse pecado a terra que te dá em herança o Senhor, teu Deus.’’

[[v5-24-5]]

^<<v5-24-5,5>>^ “Quando um homem se tiver casado recentemente, não irá à guerra e não se lhe imporá cargo algum. Durante um ano, estará livremente em seu lar para tornar feliz a mulher que ele desposou.

[[v5-24-6]]

^<<v5-24-6,6>>^ Não se tomarão como penhor as duas pedras do moinho, nem que seja somente a pedra móvel, porque seria tomar como penhor a própria vida.^&#42;1^

[[v5-24-7]]

^<<v5-24-7,7>>^ Se se encontrar um homem que tenha raptado um de seus irmãos israelitas, para fazer dele seu escravo, e o vender, esse raptor será punido de morte. Assim, tirarás o mal do meio de ti.

[[v5-24-8]]

^<<v5-24-8,8>>^ Toma precauções contra a praga da lepra, observando e praticando cuidadosamente tudo o que te ensinarem os sacerdotes levíticos. Cumpre fielmente tudo o que ordenei a esse respeito.

[[v5-24-9]]

^<<v5-24-9,9>>^ Lembra-te do que o Senhor, teu Deus, fez a Maria, quando saíste do Egito.^&#42;1^

[[v5-24-10]]

^<<v5-24-10,10>>^ Se fizeres ao teu próximo um empréstimo qualquer, não entrarás em sua casa para tomar (algum) penhor.

[[v5-24-11]]

^<<v5-24-11,11>>^ Esperarás fora; é ali que o teu devedor te trará esse penhor.

[[v5-24-12]]

^<<v5-24-12,12>>^ Se ele for pobre, o penhor não pernoitará em tua casa,

[[v5-24-13]]

^<<v5-24-13,13>>^ mas tornarás a dar-lho antes que o sol se ponha, a fim de que ele possa dormir com o seu manto e te abençoe, e isso te será contado como um benefício pelo Senhor, teu Deus.^&#42;1^

[[v5-24-14]]

^<<v5-24-14,14>>^ Não prejudicarás o assalariado pobre e necessitado, quer seja um de teus irmãos, quer seja um estrangeiro que mora numa das cidades de tua terra.

[[v5-24-15]]

^<<v5-24-15,15>>^ Dá-lhe o seu salário no mesmo dia, antes do pôr do sol, porque é pobre e espera impacientemente a sua paga. Do contrário clamaria contra ti ao Senhor, e serias culpado de um pecado.

[[v5-24-16]]

^<<v5-24-16,16>>^ Não morrerão os pais pelos filhos, nem os filhos pelos pais. Cada um morrerá pelo seu próprio pecado.

[[v5-24-17]]

^<<v5-24-17,17>>^ Não violarás o direito do estrangeiro nem do órfão, e não tomarás como penhor o vestido de uma viúva.

[[v5-24-18]]

^<<v5-24-18,18>>^ Lembra-te de que foste escravo no Egito e de que o Senhor, teu Deus, te libertou. Por isso, te dou essa ordem.

[[v5-24-19]]

^<<v5-24-19,19>>^ Quando segares a messe no teu campo e deixares por esquecimento algum feixe, não voltarás para levá-lo. Deixa-o para o estrangeiro, o órfão e a viúva, a fim de que o Senhor, teu Deus, abençoe todas as empresas de tuas mãos.

[[v5-24-20]]

^<<v5-24-20,20>>^ Quando sacudires tuas oliveiras, não voltarás a colher o resto que ficou nos galhos; isso será para o estrangeiro, o órfão e a viúva.

[[v5-24-21]]

^<<v5-24-21,21>>^ Quando tiveres vindimado a tua vinha, não voltarás a colher os cachos que ficaram; deixa-os para o estrangeiro, o órfão e a viúva.

[[v5-24-22]]

^<<v5-24-22,22>>^ Lembra-te de que foste escravo no Egito: eis por que te dou essa ordem.”

'''

xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[&#60; Capítulo Anterior] | <<v5-24-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[Próximo Capítulo &#62;]