include::./index.adoc[]

[[v5-7-0]]
=== Deuteronômio, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 7 trata da separação que o povo de Israel deve fazer dos povos que habitam a terra prometida, para evitar que sejam corrompidos por suas práticas e crenças. Além disso, o capítulo destaca a fidelidade de Deus em cumprir suas promessas aos que o amam e guardam seus mandamentos. Abaixo estão cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em Deuteronômio 7.
* Josué 23:6: "Portanto, sede vós muito firmes para guardardes e fazerdes tudo quanto está escrito no livro da lei de Moisés, para que dele não vos desvieis nem para a direita nem para a esquerda," Este versículo mostra a importância da obediência à lei de Deus para permanecer fiel a ele e evitar a corrupção pelas práticas de outros povos.
* Salmos 105:8-11: "Lembrou-se da sua santa palavra, e de Abraão, seu servo. E trouxe para fora o seu povo com alegria, e os seus escolhidos com regozijo. E deu-lhes as terras dos gentios, e herdaram o trabalho dos povos, Para que guardassem os seus preceitos, e observassem as suas leis. Louvai ao Senhor." Este salmo relembra como Deus cumpriu suas promessas ao povo de Israel ao dar-lhes a terra prometida e destaca que essa herança vem com a responsabilidade de guardar os preceitos e leis de Deus.
* 1 Coríntios 15:33: "Não vos enganeis: as más conversações corrompem os bons costumes." Este versículo alerta para o perigo de se misturar com pessoas que têm crenças e práticas diferentes das de Deus e como isso pode levar à corrupção.
* 2 Coríntios 6:14: "Não vos ponhais em jugo desigual com os incrédulos; porque que sociedade tem a justiça com a injustiça? ou que comunhão tem a luz com as trevas?" Este versículo reforça a ideia de separação do povo de Deus dos povos incrédulos para evitar a contaminação espiritual.
* Hebreus 10:23: "Retenhamos firmes a confissão da nossa esperança; porque fiel é o que prometeu." Este versículo destaca a fidelidade de Deus em cumprir suas promessas e encoraja o povo de Deus a permanecer fiel em sua esperança e confiança nele.
****

[[v5-7-1]]

^<<v5-7-1,1>>^ “Quando o Senhor, teu Deus, te tiver introduzido na terra que vais possuir, e tiver despojado em teu favor muitas nações, os heteus, os gergeseus, os amorreus, os cananeus, os ferezeus, os heveus e os jebuseus, sete nações maiores e mais poderosas do que tu;^&#42;1^

[[v5-7-2]]

^<<v5-7-2,2>>^ quando o Senhor, teu Deus, as tiver entregado e tu as tiveres vencido, então as votarás ao interdito. Não farás pacto algum com elas, nem as tratarás com misericórdia.

[[v5-7-3]]

^<<v5-7-3,3>>^ Não contrairás com elas matrimônios: não darás tua filha a seus filhos, e não tomarás de suas filhas para teu filho,

[[v5-7-4]]

^<<v5-7-4,4>>^ pois elas afastariam do Senhor o teu filho, que serviria a outros deuses; a cólera do Senhor se inflamaria contra ele e não vos destruiria prontamente.

[[v5-7-5]]

^<<v5-7-5,5>>^ Mas eis como procedereis a seu respeito: destruireis seus altares, quebrareis suas estelas, cortareis suas asserás de madeira e queimareis suas imagens de escultura,

[[v5-7-6]]

^<<v5-7-6,6>>^ porque és um povo consagrado ao Senhor, teu Deus, o qual te escolheu para seres o seu povo, sua propriedade exclusiva, entre todas as outras nações da terra.

[[v5-7-7]]

^<<v5-7-7,7>>^ Não é porque sois mais numerosos que todos os outros povos que o Senhor se uniu a vós e vos escolheu; ao contrário, sois o menor de todos.

[[v5-7-8]]

^<<v5-7-8,8>>^ Mas o Senhor vos ama e quer guardar o juramento que fez a vossos pais. Por isso, a sua mão poderosa tirou-vos da casa da servidão, e livrou-vos do poder do faraó, rei do Egito.

[[v5-7-9]]

^<<v5-7-9,9>>^ Reconhece, pois, que o Senhor, teu Deus, é verdadeiramente Deus, um Deus fiel, que guarda a sua aliança e a sua misericórdia até a milésima geração para com aqueles que o amam e observam os seus mandamentos,

[[v5-7-10]]

^<<v5-7-10,10>>^ mas castiga diretamente aqueles que o odeiam, exterminando-os, e infligindo sem demora o castigo direto àquele que o odeia.^&#42;1^

[[v5-7-11]]

^<<v5-7-11,11>>^ Observai, pois, as ordenações, as leis e os preceitos que vos prescrevo hoje, e praticai-os.

[[v5-7-12]]

^<<v5-7-12,12>>^ Se ouvirdes esses preceitos e os praticardes fielmente, o Senhor, teu Deus, guardará para contigo a aliança de misericórdia que jurou a teus pais,

[[v5-7-13]]

^<<v5-7-13,13>>^ amando-te, abençoando-te e multiplicando-te: abençoará o fruto de teu ventre e o fruto do solo, teu trigo, teu vinho e teu óleo, as crias de tuas vacas e de tuas ovelhas, na terra que jurou a teus pais dar-te.

[[v5-7-14]]

^<<v5-7-14,14>>^ Serás bendito mais que todos os povos. Não haverá no meio de ti quem seja estéril, macho ou fêmea, tanto entre os homens como entre os animais.

[[v5-7-15]]

^<<v5-7-15,15>>^ O Senhor apartará de ti toda a enfermidade; e não permitirá que te toque nenhuma daquelas funestas epidemias do Egito, que conheceste, mas ferirá com elas todos os que te odeiam.

[[v5-7-16]]

^<<v5-7-16,16>>^ Devorarás todos os povos que o Senhor, teu Deus, te entregar; os teus olhos não terão piedade deles. Não servirás os seus deuses, porque isso te seria um laço.

[[v5-7-17]]

^<<v5-7-17,17>>^ Se disseres no teu coração: ‘Estes povos são mais numerosos do que eu, como poderia eu despojá-los?’.

[[v5-7-18]]

^<<v5-7-18,18>>^ Não os temas; lembra-te do que fez o Senhor, teu Deus, ao faraó e a todos os egípcios,

[[v5-7-19]]

^<<v5-7-19,19>>^ das grandes provas que os teus olhos viram, dos sinais e dos prodígios que o Senhor fez quando te tirou do Egito com sua mão forte e seu braço poderoso. O mesmo fará ele a todos os povos que temes.

[[v5-7-20]]

^<<v5-7-20,20>>^ O Senhor, teu Deus, enviará mesmo vespas contra eles, até destruir e exterminar todos os que tiverem escapado e se houverem ocultado de tua presença.

[[v5-7-21]]

^<<v5-7-21,21>>^ Não te assustes por causa deles, porque tens o Senhor, teu Deus, no meio de ti, um Deus grande e temível.

[[v5-7-22]]

^<<v5-7-22,22>>^ Ele expulsará pouco a pouco essas nações de diante de ti; tu não as destruirás de uma só vez, para que não se multipliquem as feras ao redor de ti.

[[v5-7-23]]

^<<v5-7-23,23>>^ O Senhor, teu Deus, as entregará a ti e semeará o pânico no meio delas até que todas sejam exterminadas.

[[v5-7-24]]

^<<v5-7-24,24>>^ Entregará os seus reis nas tuas mãos, e tu apagarás os seus nomes de debaixo do céu. Ninguém te poderá resistir, até que os tenhas derrotado.

[[v5-7-25]]

^<<v5-7-25,25>>^ Queimareis as imagens esculpidas de seus deuses, mas não cobiçareis a prata nem o ouro de que são revestidas, nem delas tomareis nada, para que isso não te seja um laço, pois são uma abominação para o Senhor.^&#42;1^

[[v5-7-26]]

^<<v5-7-26,26>>^ Não introduzirás em tua casa coisa alguma abominável, porque serias, como ela, votado ao interdito. Considera-a como imunda e abominável porque é votada ao interdito.”

'''

xref:005-deuteronomio/005-deuteronomio-006.adoc#v5-6-0[&#60; Capítulo Anterior] | <<v5-7-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-008.adoc#v5-8-0[Próximo Capítulo &#62;]