include::./index.adoc[]

[[v5-8-0]]
=== Deuteronômio, 8
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 8 fala sobre a importância de lembrar de Deus em todas as circunstâncias e não esquecer que tudo o que temos vem Dele. Também enfatiza a necessidade de obediência para que o povo de Israel possa prosperar na Terra Prometida.
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." Este verso enfatiza a necessidade de confiar em Deus e reconhecê-lo em todos os caminhos da vida, o que é uma mensagem central em Deuteronômio 8.
* Deuteronômio 8:3: "Ele te humilhou e te deixou passar fome, e depois te alimentou com o maná, que nem tu nem teus antepassados conheciam, para te mostrar que o homem não vive só de pão, mas de toda palavra que procede da boca do Senhor." Este verso é um lembrete de que Deus é o provedor de todas as coisas e que o povo de Israel deve confiar nele em todas as circunstâncias.
* Deuteronômio 8:6: "Obedece, pois, aos mandamentos do Senhor, teu Deus, andando nos seus caminhos e temendo-o." Aqui vemos a ênfase na necessidade de obediência aos mandamentos de Deus, que é um tema recorrente em Deuteronômio 8.
* Filipenses 4:19: "E o meu Deus suprirá todas as necessidades de vocês, de acordo com as suas gloriosas riquezas em Cristo Jesus." Este verso é uma promessa de que Deus suprirá todas as necessidades daqueles que confiam nele, o que é uma mensagem central em Deuteronômio 8.
* Deuteronômio 8:18: "Antes te lembrarás do Senhor, teu Deus, porque é ele o que te dá força para adquirires riquezas; para confirmar a sua aliança, que jurou a teus pais, como hoje se vê." Este verso enfatiza que é Deus quem nos dá a força e a capacidade de prosperar, e que devemos lembrar sempre disso.
****

[[v5-8-1]]

^<<v5-8-1,1>>^ “Tereis muito cuidado em praticar tudo o que hoje vos prescrevo, para que possais viver e multiplicar-vos, e entrar na possessão da terra que o Senhor jurou dar a vossos pais.

[[v5-8-2]]

^<<v5-8-2,2>>^ Lembra-te de todo o caminho por onde o Senhor te conduziu durante esses quarenta anos no deserto, para humilhar-te e provar-te, e para conhecer os sentimentos de teu coração, e saber se observarias ou não os seus mandamentos.

[[v5-8-3]]

^<<v5-8-3,3>>^ Humilhou-te com a fome; deu-te por sustento o maná, que não conhecias nem tinham conhecido os teus pais, para ensinar-te que o homem não vive só de pão, mas de tudo o que sai da boca do Senhor.^&#42;1^

[[v5-8-4]]

^<<v5-8-4,4>>^ Tuas vestes não se gastaram sobre ti, e teu pé não se enchou durante estes quarenta anos.

[[v5-8-5]]

^<<v5-8-5,5>>^ Reconhece, pois, em teu coração, que assim como um homem corrige seu filho, assim te corrige o Senhor, teu Deus.

[[v5-8-6]]

^<<v5-8-6,6>>^ Guardarás os mandamentos do Senhor, teu Deus, andando em seus caminhos e temendo-o.

[[v5-8-7]]

^<<v5-8-7,7>>^ Porque o Senhor, teu Deus, vai conduzir-te a uma terra excelente, cheia de torrentes, de fontes e de águas profundas que brotam nos vales e nos montes;

[[v5-8-8]]

^<<v5-8-8,8>>^ uma terra de trigo e de cevada, de vinhas, de figueiras, de romãzeiras, uma terra de óleo de oliva e de mel,

[[v5-8-9]]

^<<v5-8-9,9>>^ uma terra onde não será racionado o pão que comeres, e onde nada faltará; terra cujas pedras são de ferro e de cujas montanhas extrairás o bronze.

[[v5-8-10]]

^<<v5-8-10,10>>^ Comerás à saciedade, e bendirás o Senhor, teu Deus, pela boa terra que te deu.

[[v5-8-11]]

^<<v5-8-11,11>>^ Guarda-te de esquecer o Senhor, teu Deus, negligenciando a observância de suas ordens, seus preceitos e suas leis que hoje te prescrevo.

[[v5-8-12]]

^<<v5-8-12,12>>^ Não suceda que, depois de teres comido à saciedade, de teres construído e habitado formosas casas,

[[v5-8-13]]

^<<v5-8-13,13>>^ de teres visto multiplicar-se teus bois e tuas ovelhas, e aumentar a tua prata, o teu ouro e o teu bem,

[[v5-8-14]]

^<<v5-8-14,14>>^ o teu coração se eleve, e te esqueças do Senhor, teu Deus, que te tirou do Egito, da casa da servidão.

[[v5-8-15]]

^<<v5-8-15,15>>^ Foi ele o teu guia neste vasto e terrível deserto, cheio de serpentes ardentes e escorpiões, terra árida e sem água, onde fez jorrar para ti água do rochedo duríssimo;

[[v5-8-16]]

^<<v5-8-16,16>>^ foi ele quem te alimentou no deserto com um maná desconhecido de teus pais, para humilhar-te e provar-te, a fim de te fazer o bem depois disso.

[[v5-8-17]]

^<<v5-8-17,17>>^ Não digas no teu coração: ‘A minha força e o vigor do meu braço adquiriram-me todos esses bens’.

[[v5-8-18]]

^<<v5-8-18,18>>^ Lembra-te de que é o Senhor, teu Deus, quem te dá a força para adquiri-los, a fim de confirmar, como o faz hoje, a aliança que jurou a teus pais.

[[v5-8-19]]

^<<v5-8-19,19>>^ Se, esquecendo-te do Senhor, teu Deus, seguires outros deuses, rendendo-lhes culto e prostrando-te diante deles, desde hoje vos declaro que perecereis com toda a certeza.

[[v5-8-20]]

^<<v5-8-20,20>>^ Como as nações que o Senhor exterminou diante de vós, assim também perecereis vós, se não ouvirdes a voz do Senhor, vosso Deus.”

'''

xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[&#60; Capítulo Anterior] | <<v5-8-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[Próximo Capítulo &#62;]