include::./index.adoc[]

[[v5-1-0]]
=== Deuteronômio, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 1 é um capítulo onde Moisés relembra a história dos israelitas desde que eles saíram do Egito até chegarem à fronteira da Terra Prometida. Ele também exorta o povo a confiar em Deus e obedecer aos seus mandamentos para que possam receber as bênçãos que Ele prometeu. Aqui estão cinco versículos relacionados com os temas abordados em Deuteronômio 1:
* Êxodo 18:20 - "Ensina-lhes os estatutos e as leis, e mostra-lhes o caminho em que devem andar e a obra que devem fazer." Moisés lembra ao povo que Deus lhes deu leis e estatutos para seguir, e que é importante ensiná-los e obedecê-los.
* Deuteronômio 6:4-6 - "Ouve, Israel, o Senhor nosso Deus é o único Senhor. Amarás, pois, o Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todas as tuas forças. E estas palavras que hoje te ordeno estarão no teu coração." Moisés enfatiza a importância de amar a Deus e guardar seus mandamentos.
* Deuteronômio 8:2-3 - "E te lembrarás de todo o caminho pelo qual o Senhor teu Deus te guiou no deserto estes quarenta anos, para te humilhar, e te provar, para saber o que estava no teu coração, se guardarias os seus mandamentos ou não. E te humilhou, e te deixou ter fome, e te sustentou com o maná, que tu não conhecias, nem teus pais o conheciam; para te dar a entender que o homem não viverá só de pão, mas que de tudo o que sai da boca do Senhor viverá o homem." Moisés lembra o povo de como Deus os guiou e sustentou no deserto, e que isso foi para ensiná-los a confiar nele e obedecer seus mandamentos.
* Deuteronômio 10:12-13 - "Agora, pois, ó Israel, que é que o Senhor teu Deus requer de ti, senão que temas o Senhor teu Deus, que andes em todos os seus caminhos, e o ames, e sirvas ao Senhor teu Deus de todo o teu coração e de toda a tua alma, para guardares os mandamentos do Senhor e os seus estatutos que hoje te ordeno, para o teu bem?" Moisés enfatiza que obedecer a Deus é para nosso próprio bem, e que isso é o que Ele requer de nós.
* Deuteronômio 28:1-2 - "E será que, se ouvires a voz do Senhor teu Deus, tendo cuidado de guardar todos os seus mandamentos que eu hoje te ordeno, o Senhor teu Deus te exaltará sobre todas as nações da terra. E todas estas bênçãos virão sobre ti e te alcançarão, quando ouvires a voz do Senhor teu Deus." Moisés promete ao povo que se eles obedecerem a Deus, Ele os abençoará abundantemente.
****

[[v5-1-1]]

^<<v5-1-1,1>>^ Eis os discursos que Moisés dirigiu a todo o Israel, do outro lado do Jordão, no deserto, na planície que se estende defronte de Suf, entre Farã, Tofel, Labã, Haserot e Dizaab.

[[v5-1-2]]

^<<v5-1-2,2>>^ Desde Horeb até Cades Barne há uma distância de onze jornadas de marcha pelo caminho da montanha de Seir.

[[v5-1-3]]

^<<v5-1-3,3>>^ No quadragésimo ano, no primeiro dia do décimo primeiro mês, diante dos israelitas, Moisés pronunciou todos os discursos que o Senhor lhe tinha ordenado dizer,

[[v5-1-4]]

^<<v5-1-4,4>>^ depois de ter derrotado Seon, rei dos amorreus, que habitava em Hesebon, e Og, rei de Basã, que morava em Astarot e Edrai.

[[v5-1-5]]

^<<v5-1-5,5>>^ Do outro lado do Jordão, na terra de Moab, Moisés começou a expor a lei, dizendo:

[[v5-1-6]]

^<<v5-1-6,6>>^ “O Senhor, nosso Deus, falou-nos nestes termos em Horeb: Tendes-vos demorado muito tempo neste monte.

[[v5-1-7]]

^<<v5-1-7,7>>^ Voltai e parti. Tomai o caminho do monte dos amorreus e das regiões vizinhas; ide às planícies, às montanhas, aos vales, ao Negueb, às costas do mar, à terra dos cananeus, ao Líbano e até o grande rio Eufrates.

[[v5-1-8]]

^<<v5-1-8,8>>^ Eis que eu vos entrego esta terra. Ide e possuí a terra que jurei dar a vossos pais Abraão, Isaac e Jacó, a eles e à sua posteridade.

[[v5-1-9]]

^<<v5-1-9,9>>^ Eu vos disse nessa mesma época: eu sozinho não posso tomar conta de vós.

[[v5-1-10]]

^<<v5-1-10,10>>^ O Senhor, vosso Deus, vos multiplicou de tal modo que sois hoje tão numerosos como as estrelas do céu.

[[v5-1-11]]

^<<v5-1-11,11>>^ Que o Senhor, o Deus de vossos pais, vos multiplique mil vezes mais e vos abençoe como prometeu.

[[v5-1-12]]

^<<v5-1-12,12>>^ Como poderia eu sozinho encarregar-me de vós e levar o fardo de vossas contendas?

[[v5-1-13]]

^<<v5-1-13,13>>^ Escolhei, de cada uma de vossas tribos, homens sábios, prudentes e experimentados, que eu ponha à vossa frente.

[[v5-1-14]]

^<<v5-1-14,14>>^ Vós então me respondestes: ‘É uma boa coisa o que nos propões’.

[[v5-1-15]]

^<<v5-1-15,15>>^ Tomei, pois, dentre vós, homens sábios e experimentados que pus à vossa frente como chefes de milhares, de centenas, de cinquentenas e de dezenas, bem como escribas em vossas tribos.

[[v5-1-16]]

^<<v5-1-16,16>>^ Nesse mesmo tempo, dei esta ordem aos vossos juízes: ‘Dai audiência aos vossos irmãos e julgai com equidade as questões de cada um deles com o seu irmão ou com o estrangeiro que mora com ele.

[[v5-1-17]]

^<<v5-1-17,17>>^ Não fareis distinção de pessoas em vossos julgamentos. Ouvireis o pequeno como o grande, sem temor de ninguém, porque o juízo é de Deus. Se uma questão vos parecer muito complicada, devereis apresentá-la a mim para que eu a ouça.

[[v5-1-18]]

^<<v5-1-18,18>>^ É assim que, naquele tempo, vos ordenei tudo o que devíeis fazer’.”

[[v5-1-19]]

^<<v5-1-19,19>>^ “Depois partimos de Horeb para atravessar esse vasto e terrível deserto que vistes, do monte dos amorreus, como nos havia ordenado o Senhor, nosso Deus. E chegamos a Cades Barne.

[[v5-1-20]]

^<<v5-1-20,20>>^ Eu vos disse então: ‘Eis-vos chegados ao monte dos amorreus que o Senhor, nosso Deus, nos dá.

[[v5-1-21]]

^<<v5-1-21,21>>^ Vê: O Senhor, teu Deus, te entrega a terra. Subi e possuí-a, como o prometeu o Deus de teus pais. Não tenhas medo; não te assustes’.^&#42;1^

[[v5-1-22]]

^<<v5-1-22,22>>^ Vós vos aproximastes de mim e dissestes: ‘Enviemos homens adiante de nós, que explorem a terra e nos informem por que caminho devemos subir e para que cidades devemos ir’.

[[v5-1-23]]

^<<v5-1-23,23>>^ Vosso parecer agradou-me, e escolhi dentre vós doze homens, um de cada tribo.

[[v5-1-24]]

^<<v5-1-24,24>>^ Eles partiram, subiram as montanhas e chegaram ao vale de Escol, explorando a terra.

[[v5-1-25]]

^<<v5-1-25,25>>^ Tomaram consigo frutos da terra e no-los trouxeram dizendo: ‘A terra, que nos dá o Senhor, nosso Deus, é boa’.

[[v5-1-26]]

^<<v5-1-26,26>>^ Mas não quisestes subir a ela, e fostes rebeldes ao mandamento do Senhor, nosso Deus.

[[v5-1-27]]

^<<v5-1-27,27>>^ E murmurastes em vossas tendas, dizendo: ‘O Senhor tem-nos ódio e, por isso, nos tirou da terra do Egito para entregar-nos ao extermínio pelas mãos dos amorreus.

[[v5-1-28]]

^<<v5-1-28,28>>^ Para onde iremos? Nossos irmãos fizeram-nos perder a coragem quando nos disseram ter visto um povo maior e de estatura mais alta que a nossa, e cidades grandes e fortificadas, cujos muros se elevavam até o céu, e vimos até mesmo filhos de Enacim por lá’.

[[v5-1-29]]

^<<v5-1-29,29>>^ Eu, porém, vos respondi: ‘Não vos assusteis nem tenhais medo deles.

[[v5-1-30]]

^<<v5-1-30,30>>^ O Senhor, vosso Deus, que marcha diante de vós, combaterá ele mesmo em vosso lugar, como sempre o fez sob os vossos olhos, no Egito

[[v5-1-31]]

^<<v5-1-31,31>>^ e no deserto. No deserto, tu mesmo viste como o Senhor, teu Deus, te levou por todo caminho por onde andaste, como um homem costuma levar seu filho, até que chegásseis a esse lugar’.

[[v5-1-32]]

^<<v5-1-32,32>>^ E, apesar disso, não tivestes confiança no Senhor, vosso Deus,

[[v5-1-33]]

^<<v5-1-33,33>>^ o qual, procurando-vos um lugar onde acampar, marchava adiante de vós no caminho, de noite no fogo, para vos mostrar o caminho, e de dia na nuvem.

[[v5-1-34]]

^<<v5-1-34,34>>^ O Senhor, tendo ouvido o som de vossas palavras, encolerizou-se e fez este juramento:

[[v5-1-35]]

^<<v5-1-35,35>>^ ‘Nenhum dos homens desta geração perversa verá a boa terra que eu, com juramento, prometi dar a vossos pais,

[[v5-1-36]]

^<<v5-1-36,36>>^ exceto Caleb, filho de Jefoné. Este a verá, e eu darei a ele e a seus filhos o solo que ele pisou, porque cumpriu a vontade do Senhor’.

[[v5-1-37]]

^<<v5-1-37,37>>^ Até contra mim se irritou o Senhor por causa de vós: tu tampouco – disse-me ele – entrarás nessa terra!

[[v5-1-38]]

^<<v5-1-38,38>>^ É Josué, filho de Nun, que ali entrará. Anima-o, pois é ele que introduzirá Israel na possessão da terra.

[[v5-1-39]]

^<<v5-1-39,39>>^ Vossos filhinhos, dos quais dissestes que seriam a presa do deserto, e vossos filhos, que hoje ainda não sabem distinguir o bem do mal, estes entrarão; a eles darei a terra e a possuirão.

[[v5-1-40]]

^<<v5-1-40,40>>^ Quanto a vós, voltai para trás e parti para o deserto na direção do mar Vermelho.

[[v5-1-41]]

^<<v5-1-41,41>>^ Vós respondestes-me: ‘Pecamos contra o Senhor. Vamos combater, como o Senhor, nosso Deus, nos ordenou’. E quando cada um de vós, tomando as suas armas, vos dispusestes inconsideradamente a marchar sobre o monte,

[[v5-1-42]]

^<<v5-1-42,42>>^ o Senhor disse-me: ‘Dize-lhes: Não subais, não entreis em combate algum, porque não estou no meio de vós. Se o fizerdes, sereis vencidos por vossos inimigos’.

[[v5-1-43]]

^<<v5-1-43,43>>^ Em vão vos referi todas essas palavras: não me ouvistes e tivestes a presunção de subir ao monte, a despeito das ordens do Senhor.

[[v5-1-44]]

^<<v5-1-44,44>>^ Então os amorreus que habitavam nessa montanha saíram contra vós, perseguiram-vos como abelhas e retalharam-vos desde Seir até Horma.

[[v5-1-45]]

^<<v5-1-45,45>>^ Voltando, chorastes diante do Senhor, mas o Senhor não ouviu os vossos clamores, nem vos inclinou os seus ouvidos.

[[v5-1-46]]

^<<v5-1-46,46>>^ Por isso é que ficastes tanto tempo em Cades, como o sabeis.”

'''

xref:004-numeros/004-numeros-036.adoc#v4-36-0[&#60; Capítulo Anterior] | <<v5-1-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[Próximo Capítulo &#62;]