include::./index.adoc[]

[[v5-17-0]]
=== Deuteronômio, 17
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 17 de Deuteronômio trata da justiça e da punição para aqueles que desobedecem as leis estabelecidas por Deus. É enfatizado que é importante ter um sistema justo de julgamento, e que as pessoas devem seguir as decisões dos juízes. Também é mencionado que, se houver casos em que a decisão é muito difícil, eles devem recorrer ao sacerdote ou juiz que estiver na época.
* Levítico 19:15: "Não cometerá injustiça no julgamento. Não farás acepção de pessoas com o pobre, nem te inclinarás diante do grande; com justiça julgarás o teu próximo." Este verso enfatiza a importância da justiça no julgamento, sem distinção de riqueza ou posição social.
* Deuteronômio 19:18-19: "Os juízes inquirirão bem; e eis que, sendo a testemunha falsa, testemunhou falsamente contra o seu irmão; Então lhe fareis como cuidou em fazer a seu irmão; assim, tirarás o mal do meio de ti." Aqui é mencionado que as testemunhas falsas devem ser punidas de acordo com a gravidade da sua acusação.
* Provérbios 31:9: "Abre a tua boca, julga retamente e faze justiça aos pobres e necessitados." Este verso enfatiza a importância de ajudar os necessitados e fazer justiça para aqueles que não têm recursos suficientes.
* Isaías 1:17: "Aprendei a fazer o bem; procurai o que é justo; ajudai o oprimido; fazei justiça ao órfão; tratai da causa das viúvas." Este verso destaca a importância de fazer o bem e ajudar os necessitados.
* Tiago 2:9: "Mas, se fazeis acepção de pessoas, cometeis pecado, e sois condenados pela lei como transgressores." Este verso adverte sobre a injustiça em fazer distinção entre as pessoas e a importância de tratar a todos de maneira igual.
****

[[v5-17-1]]

^<<v5-17-1,1>>^ “Não imolarás ao Senhor, teu Deus, touro ou ovelha que tenha defeito ou qualquer outra deformidade, porque isso é abominação aos olhos do Senhor, teu Deus.

[[v5-17-2]]

^<<v5-17-2,2>>^ Se se encontrar no meio de ti, em uma das cidades que te dá o Senhor, teu Deus, um homem ou uma mulher que faça o que é mau aos olhos do Senhor, teu Deus, violando sua aliança,

[[v5-17-3]]

^<<v5-17-3,3>>^ indo servir outros deuses ou adorando o sol, a lua, ou o exército dos céus – o que eu não mandei – se te derem aviso disso, logo que o souberes, farás uma investigação minuciosa.

[[v5-17-4]]

^<<v5-17-4,4>>^ Se for verdade o que se disse, se verificares que realmente se cometeu tal abominação em Israel,

[[v5-17-5]]

^<<v5-17-5,5>>^ farás conduzir às portas da cidade o homem ou a mulher que cometeu essa má ação, e os apedrejarás até que morram.

[[v5-17-6]]

^<<v5-17-6,6>>^ Sobre o depoimento de duas ou três testemunhas morrerá aquele que tiver de ser morto. Mas não será morto sobre o depoimento de uma só.

[[v5-17-7]]

^<<v5-17-7,7>>^ A mão das testemunhas será a primeira a feri-lo para matá-lo, depois a mão de todo o povo. Assim extirparás o mal do meio de ti.”

[[v5-17-8]]

^<<v5-17-8,8>>^ “Se aparecer uma questão cujo juízo te seja muito difícil de fazer: assassinato, disputa, ferida, um processo qualquer em tua cidade, terás o dever de subir ao lugar escolhido pelo Senhor, teu Deus.

[[v5-17-9]]

^<<v5-17-9,9>>^ Irás ter com os sacerdotes da linhagem de Levi e com o juiz que estiver em exercício nesse momento, para consultá-los e eles te dirão a sentença (a pronunciar).

[[v5-17-10]]

^<<v5-17-10,10>>^ Procederás conforme a decisão que eles te comunicarem no lugar escolhido pelo Senhor, e cuidarás de conformar-te às suas instruções.

[[v5-17-11]]

^<<v5-17-11,11>>^ Agirás segundo as instruções que te tiverem dado, e conforme a sentença que te tiverem ditado, sem te apartares do seu parecer nem para a direita nem para a esquerda.

[[v5-17-12]]

^<<v5-17-12,12>>^ Aquele que, por orgulho, recusar ouvir o sacerdote que estiver nesse tempo a serviço do Senhor, teu Deus, ou o juiz, esse homem será punido de morte. Assim tirarás o mal do meio de Israel.

[[v5-17-13]]

^<<v5-17-13,13>>^ O povo, ao sabê-lo, será possuído de temor, e não se deixará levar pelo orgulho.”

[[v5-17-14]]

^<<v5-17-14,14>>^ “Quando tiveres entrado na terra que o Senhor, teu Deus, te dá, e tiveres tomado posse dela, e nela te estabeleceres, se disseres: ‘Quero ter um rei sobre mim, como o têm todas as nações que me cercam’ –

[[v5-17-15]]

^<<v5-17-15,15>>^ elegerás aquele rei que o Senhor, teu Deus, tiver escolhido, e este será um dos teus irmãos: não poderás escolher para rei de Israel um estrangeiro que não seja teu irmão.

[[v5-17-16]]

^<<v5-17-16,16>>^ Somente, que esse rei não possua cavalos, e não reconduza o povo ao Egito, para adquirir numerosa cavalaria, porque o Senhor vos disse: ‘Não volteis mais por esse caminho’.

[[v5-17-17]]

^<<v5-17-17,17>>^ Guarde-se também o rei de multiplicar suas mulheres, para que não suceda que seu coração se desvie (de Deus). Tampouco ajuntará ele grande quantidade de prata e ouro.

[[v5-17-18]]

^<<v5-17-18,18>>^ Quando subir ao trono real, escreverá para si uma cópia desta lei, segundo o texto que os sacerdotes levíticos têm.

[[v5-17-19]]

^<<v5-17-19,19>>^ Conservará essa cópia consigo e a lerá todos os dias de sua vida, para aprender a temer o Senhor, seu Deus, e a observar todos os artigos desta lei, pondo em prática todas as suas prescrições.

[[v5-17-20]]

^<<v5-17-20,20>>^ Assim, não se elevará o seu coração acima de seus irmãos, e ele não se apartará da lei, nem para um lado nem para outro, e desse modo terá, assim como os seus filhos, um longo reinado no meio de Israel.”

'''

xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[&#60; Capítulo Anterior] | <<v5-17-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-018.adoc#v5-18-0[Próximo Capítulo &#62;]