include::./index.adoc[]

[[v5-19-0]]
=== Deuteronômio, 19
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 19 trata das cidades de refúgio, que eram lugares designados para onde alguém que cometeu um homicídio não intencional poderia fugir para se proteger da vingança dos parentes da vítima. As três cidades de refúgio deveriam ser distribuídas de forma equitativa na terra de Israel. O capítulo também instrui que ninguém deve testemunhar falsamente contra o seu próximo, e que aqueles que testemunharem devem ser cuidadosos em suas palavras e ações.
* Provérbios 14:5: "A testemunha fiel não mentirá, mas a falsa testemunha falará mentiras." Este versículo destaca a importância da veracidade do testemunho e a gravidade de testemunhar falsamente contra outra pessoa.
* Mateus 5:21-22: "Ouvistes que foi dito aos antigos: Não matarás; mas qualquer que matar será réu de juízo. Eu, porém, vos digo que qualquer que, sem motivo, se encolerizar contra seu irmão, será réu de juízo; e qualquer que disser a seu irmão: Raca, será réu do sinédrio; e qualquer que lhe disser: Louco, será réu do fogo do inferno." Jesus reitera a importância de não matar, mas também enfatiza a importância de controlar a raiva e ser cuidadoso com as palavras que são ditas.
* Êxodo 23:7: "De palavras de falsidade te afastarás, e não matarás o inocente e o justo; porque não justificarei o ímpio." Este versículo destaca a importância de evitar a falsidade e de não matar injustamente.
* Provérbios 19:5: "A falsa testemunha não ficará impune, e o que respira mentiras não escapará." Este versículo destaca a consequência da falsa testemunha e da mentira, que é a punição divina.
* Isaías 1:17: "Aprendei a fazer bem; procurai o que é justo; ajudai o oprimido; fazei justiça ao órfão; tratai da causa das viúvas." Este versículo enfatiza a importância da justiça e de tratar os vulneráveis com bondade e compaixão, temas que estão relacionados com a ideia de cidades de refúgio em Deuteronômio 19.
****

[[v5-19-1]]

^<<v5-19-1,1>>^ “Quando o Senhor, teu Deus, tiver exterminado as nações cuja terra te dá, quando as tiveres despojado e te tiveres estabelecido em suas cidades e habitações,

[[v5-19-2]]

^<<v5-19-2,2>>^ reservarás três cidades no meio da terra cuja posse o Senhor, teu Deus, te dá.

[[v5-19-3]]

^<<v5-19-3,3>>^ Farás estradas que conduzam a elas e dividirás em três partes a terra que te dá o Senhor, teu Deus, a fim de que todo homicida possa encontrar refúgio nessas cidades.

[[v5-19-4]]

^<<v5-19-4,4>>^ Eis a regra a seguir para o homicida que ali se refugiar, procurando salvar sua vida. Se matou o seu próximo por inadvertência, sem ódio prévio,

[[v5-19-5]]

^<<v5-19-5,5>>^ como, por exemplo, se ele tiver ido à floresta com outro cortar lenha e, no momento de brandir o machado para abater a árvore, o ferro se tenha deslocado do cabo e ferido mortalmente o seu companheiro, esse homem se refugiará em uma dessas cidades para salvar sua vida.

[[v5-19-6]]

^<<v5-19-6,6>>^ De outra forma, o vingador do sangue, no ardor de sua cólera, poderia perseguir o homicida e, se o caminho fosse muito longo, atingi-lo para dar-lhe o golpe mortal. Entretanto, esse homem não merece a morte, pois que não tinha ódio à vítima.

[[v5-19-7]]

^<<v5-19-7,7>>^ Eis por que te ordeno reservar três cidades.

[[v5-19-8]]

^<<v5-19-8,8>>^ Quando o Senhor, teu Deus, tiver alargado os teus limites, como jurou aos teus pais, e tiver dado toda a terra que lhes prometeu –

[[v5-19-9]]

^<<v5-19-9,9>>^ contanto que ponhas fielmente em prática todos os mandamentos que hoje te prescrevo, amando o Senhor, teu Deus, e andando todo o tempo em seus caminhos – juntarás a essas três cidades outras três.

[[v5-19-10]]

^<<v5-19-10,10>>^ Desse modo, não se derramará sangue inocente na terra que o Senhor, teu Deus, te dá por herança, e não haverá sangue sobre ti.^&#42;1^

[[v5-19-11]]

^<<v5-19-11,11>>^ Mas, se um homem, tendo ódio do seu próximo, armar-lhe ciladas, levantar-se contra ele e feri-lo mortalmente, indo em seguida refugiar-se numa dessas cidades,

[[v5-19-12]]

^<<v5-19-12,12>>^ os anciãos de sua cidade mandarão tirá-lo do lugar de seu refúgio, e o entregarão nas mãos do vingador do sangue, para ser morto.

[[v5-19-13]]

^<<v5-19-13,13>>^ Não terás compaixão dele; deves tirar de Israel o sangue inocente, para seres feliz.”

[[v5-19-14]]

^<<v5-19-14,14>>^ “Não removerás os marcos de teu vizinho, que teus predecessores fixaram na herança que te couber na terra, cuja posse te há de dar o Senhor, teu Deus.”

[[v5-19-15]]

^<<v5-19-15,15>>^ “Não será admitida contra um homem somente uma testemunha, qualquer que seja o crime, falta ou delito. Só se tomará a coisa em consideração sobre o depoimento de duas ou três testemunhas.^&#42;1^

[[v5-19-16]]

^<<v5-19-16,16>>^ Se se apresentar uma testemunha falsa contra um homem, acusando-o de uma má ação,

[[v5-19-17]]

^<<v5-19-17,17>>^ ambos os contendores comparecerão diante do Senhor, na presença dos sacerdotes e dos juízes que estiverem em exercício naqueles dias.

[[v5-19-18]]

^<<v5-19-18,18>>^ Depois de uma cuidadosa investigação feita pelos juízes, se se verificar que se trata de um falso testemunho, e que a testemunha fez contra o seu irmão uma falsa deposição,

[[v5-19-19]]

^<<v5-19-19,19>>^ vós o tratareis como premeditara tratar o seu irmão. Assim, tirarás o mal do meio de ti

[[v5-19-20]]

^<<v5-19-20,20>>^ para que os outros, ao sabê-lo, tenham medo, e não ousem mais cometer semelhante falta no meio de ti.

[[v5-19-21]]

^<<v5-19-21,21>>^ Não terás compaixão: vida por vida, olho por olho, dente por dente, mão por mão, pé por pé.”

'''

xref:005-deuteronomio/005-deuteronomio-018.adoc#v5-18-0[&#60; Capítulo Anterior] | <<v5-19-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[Próximo Capítulo &#62;]