include::./index.adoc[]

[[v5-13-0]]
=== Deuteronômio, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Deuteronômio 13 trata da importância de se manter fiel ao Senhor e da punição para aqueles que tentam levar os israelitas para adorar outros deuses. O capítulo adverte sobre a presença de falsos profetas que podem tentar seduzir o povo com sinais e maravilhas para que se voltem contra o Senhor. Abaixo estão cinco versículos relacionados aos temas abordados em Deuteronômio 13:
* Deuteronômio 4:35 - "Foi-te mostrado, para que soubesses que o Senhor é Deus; nenhum outro há senão ele." Este versículo enfatiza a exclusividade do Senhor como Deus e a importância de não se desviar para outros deuses.
* Deuteronômio 6:14-15 - "Não sigais outros deuses, dos deuses dos povos que houver à roda de vós; Porque o Senhor teu Deus é um Deus zeloso no meio de ti, para que a ira do Senhor teu Deus se não acenda contra ti e te destrua de sobre a terra." Este versículo reforça a proibição de adorar outros deuses e as graves consequências que podem ocorrer se alguém se desviar do Senhor.
* Jeremias 23:16 - "Assim diz o Senhor dos exércitos: Não deis ouvidos às palavras dos profetas que entre vós profetizam; fazem-vos desvanecer; falam da visão do seu coração, não da boca do Senhor." Este versículo adverte sobre os falsos profetas que podem tentar enganar o povo com palavras que não vêm do Senhor.
* 2 Coríntios 11:13-15 - "Porque tais falsos apóstolos são obreiros fraudulentos, transfigurando-se em apóstolos de Cristo. E não é maravilha, porque o próprio Satanás se transfigura em anjo de luz. Não é muito, pois, que os seus ministros se transfigurem em ministros da justiça; o fim dos quais será conforme as suas obras." Este versículo destaca a presença de falsos profetas e ensina a importância de discernir a verdadeira mensagem do Senhor.
* João 10:27-28 - "As minhas ovelhas ouvem a minha voz, e eu conheço-as, e elas me seguem; E dou-lhes a vida eterna, e nunca hão de perecer, e ninguém as arrebatará da minha mão." Este versículo fala sobre a importância de ouvir a voz do Senhor e seguir seus caminhos, a fim de evitar ser enganado por falsos profetas ou ensinamentos enganosos.
****

[[v5-13-1]]

^<<v5-13-1,1>>^ Cuidareis de fazer tudo o que vos prescrevo, sem acrescentar nada, nem nada tirar.”

[[v5-13-2]]

^<<v5-13-2,2>>^ “Se se levantar no meio de ti um profeta ou um visionário, anunciando-te um sinal ou prodígio,

[[v5-13-3]]

^<<v5-13-3,3>>^ e suceder o sinal ou o prodígio que anunciou e te disser: ‘Vamos, sigamos outros deuses – que te são desconhecidos – e prestemos-lhes culto’,

[[v5-13-4]]

^<<v5-13-4,4>>^ tu não ouvirás as palavras desse profeta ou desse visionário; porque o Senhor, vosso Deus, vos põe à prova para ver se o amais de todo o vosso coração e de toda a vossa alma.

[[v5-13-5]]

^<<v5-13-5,5>>^ Seguireis o Senhor, vosso Deus, e o temereis; observareis seus mandamentos, obedecereis à sua voz e o servireis com muito zelo.

[[v5-13-6]]

^<<v5-13-6,6>>^ Aquele profeta, aquele visionário, porém, será morto, por ter pregado a revolta contra o Senhor vosso Deus que vos tirou do Egito e vos libertou da casa da servidão, e por ter procurado desviar-vos do caminho que o Senhor, vosso Deus, vos traçou. Assim tirarás o mal do meio de ti.^&#42;1^

[[v5-13-7]]

^<<v5-13-7,7>>^ Se teu irmão, filho de tua mãe, ou teu filho, tua filha, a mulher que repousa no teu seio, ou o amigo a quem amas como a ti mesmo, tentar seduzir-te, dizendo em segredo: ‘Vamos servir outros deuses’ – deuses desconhecidos de ti e de teus pais,

[[v5-13-8]]

^<<v5-13-8,8>>^ ou deuses das nações próximas ou distantes que estão em torno de ti, de uma extremidade da terra a outra –

[[v5-13-9]]

^<<v5-13-9,9>>^ tu não lhe cederás no que te disser, nem o ouvirás. Teu olho não terá compaixão dele, não o pouparás e não ocultarás o seu crime.

[[v5-13-10]]

^<<v5-13-10,10>>^ Tens, ao contrário, o dever de matá-lo: serás o primeiro a levantar a mão para matá-lo, e a levantará em seguida o povo.

[[v5-13-11]]

^<<v5-13-11,11>>^ Tu o apedrejarás até que ele morra, porque tentou desviar-te do Senhor, teu Deus, que te tirou do Egito, da casa da servidão.

[[v5-13-12]]

^<<v5-13-12,12>>^ Todo o Israel será tomado de temor ao sabê-lo, e não se renovará mais tal crime no meio de vós.

[[v5-13-13]]

^<<v5-13-13,13>>^ Se ouvires dizer de uma das cidades que o Senhor, teu Deus, te deu para habitação:

[[v5-13-14]]

^<<v5-13-14,14>>^ alguns malvados saíram do meio de vós e seduziram os habitantes de sua cidade, dizendo: ‘Vamos servir a outros deuses’ – deuses que vós não conheceis –,

[[v5-13-15]]

^<<v5-13-15,15>>^ farás um inquérito, buscarás e tomarás sérias informações. Se for verdade o que se disse, se se verificar que uma tal abominação foi realmente cometida no meio de vós,

[[v5-13-16]]

^<<v5-13-16,16>>^ farás passar a fio de espada os habitantes dessa cidade, juntamente com o seu gado, e a votarás ao interdito com tudo o que nela se encontrar.

[[v5-13-17]]

^<<v5-13-17,17>>^ Juntarás em seguida no meio da praça todo o seu espólio, e queimará juntamente com a cidade em honra do Senhor, teu Deus: ela será para sempre um montão de ruínas que se não reconstruirá mais.

[[v5-13-18]]

^<<v5-13-18,18>>^ Não retenha a tua mão nada do que tiver sido votado ao interdito, para que o Senhor aplaque o ardor de sua cólera, e use de piedade e misericórdia para contigo, e te multiplique, como jurou a teus pais,

[[v5-13-19]]

^<<v5-13-19,19>>^ com condição de que obedeças à voz do Senhor, teu Deus, observando os mandamentos que hoje te prescrevo, e fazendo o que é bom aos olhos do Senhor, teu Deus.”

'''

xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[&#60; Capítulo Anterior] | <<v5-13-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[Próximo Capítulo &#62;]