include::./index.adoc[]

[[v41-2-0]]
=== Naum, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* No capítulo 2 do livro de Naum, é descrita a queda de Nínive, a capital do Império Assírio, através de uma linguagem figurativa e descritiva. O capítulo descreve a aproximação do exército invasor, a destruição das muralhas da cidade, a fuga dos habitantes e o saque do tesouro da cidade. Abaixo seguem cinco versículos relacionados com os temas abordados em Naum 2:
* Isaías 13:17: "Eis que despertarei contra eles os medos, que não se importam com a prata, nem desejam o ouro." O profeta Isaías, em sua mensagem de julgamento contra a Babilônia, anuncia que Deus usará os medos para destruí-la, mesmo que não estejam interessados no saque da cidade.
* Jeremias 50:15: "Gritai contra ela ao redor; ela já se rendeu; caíram as suas torres, as suas muralhas estão derrubadas, pois esta é a vingança do Senhor; vingai-vos dela; como ela fez, fazei-lhe a ela." O profeta Jeremias também anuncia a queda da Babilônia e a destruição de suas muralhas e torres, assim como descrito em Naum 2.
* Ezequiel 21:22: "Na sua mão está a varinha do meu Filho, e ele cortará deles; e a cada árvore escoherá, e a cada um escolherá para si mesmo um ramo verde." Neste verso, o profeta Ezequiel fala da espada de Deus que punirá os habitantes de Jerusalém e também pode ser relacionado com a descrição da destruição em Naum 2.
* Salmos 46:6: "As nações se agitaram, os reinos se moveram; ele levantou a sua voz, e a terra se derreteu." Este salmo descreve a proteção de Deus para com o seu povo e a sua intervenção na história, trazendo juízo às nações rebeldes, o que se assemelha com a mensagem de Naum 2.
* Zacarias 14:14: "E Judá também pelejará em Jerusalém, e se ajuntarão as riquezas de todas as nações circunvizinhas, ouro, e prata, e roupas, em grande abundância." Neste verso, Zacarias fala da vitória de Deus sobre as nações que se levantarão contra Jerusalém e da tomada de seus bens, o que se assemelha com a descrição do saque em Naum 2.
****

[[v41-2-1]]

^<<v41-2-1,1>>^ Eis que vem sobre as montanhas um mensageiro de boa-nova, alguém que anuncia a felicidade. Celebra as tuas festas, ó Judá, cumpre teus votos! Porque o ímpio não passará mais por tua terra; está completamente aniquilado.

[[v41-2-2]]

^<<v41-2-2,2>>^ Um destruidor avança contra ti: guarda a fortaleza, vigia o caminho, fortifica os teus rins, reúne todo o teu vigor,

[[v41-2-3]]

^<<v41-2-3,3>>^ porque o Senhor restaura o esplendor de Jacó, assim como o esplendor de Israel, depois que os saqueadores despojaram e destruíram seus sarmentos.^&#42;1^

[[v41-2-4]]

^<<v41-2-4,4>>^ Os combatentes trazem escudo vermelho, os guerreiros estão vestidos de púrpura, os carros de aço cintilantes avançam no dia em que são postos em linha; e são brandidas as lanças.

[[v41-2-5]]

^<<v41-2-5,5>>^ Os carros se precipitam pelas ruas, saltando através das praças. Ao vê-los, se diria serem tochas ardentes; correm como relâmpagos.

[[v41-2-6]]

^<<v41-2-6,6>>^ Ele se lembra de seus guerreiros valentes, mas estes tropeçam em sua marcha. Precipitam-se para a muralha e preparam o teto protetor.^&#42;1^

[[v41-2-7]]

^<<v41-2-7,7>>^ As portas dos rios são abertas, o palácio cai arruinado.

[[v41-2-8]]

^<<v41-2-8,8>>^ Ela é desnudada e deportada; suas servas gemem como pombas e batem no peito.

[[v41-2-9]]

^<<v41-2-9,9>>^ Nínive é semelhante a um tanque desde a sua origem. Eles fogem. “Parai! Parai!” Mas ninguém volta para trás.

[[v41-2-10]]

^<<v41-2-10,10>>^ Saqueai a prata, saqueai o ouro, porque há inumeráveis tesouros e montes de objetos preciosos.

[[v41-2-11]]

^<<v41-2-11,11>>^ Roubo, pilhagem, devastação! O coração desfalece; os joelhos tremem, a dor oprime todos os rins, todos os rostos estão lívidos.

[[v41-2-12]]

^<<v41-2-12,12>>^ Onde está agora o retiro dos leões, o pasto dos leõezinhos, onde se recolhiam o leão, a leoa e os leõezinhos, sem haver quem os inquietasse?^&#42;1^

[[v41-2-13]]

^<<v41-2-13,13>>^ O leão despedaçava para os seus pequenos, e estrangulava para as suas leoas; enchia de presas os seus antros, e de despojos as suas cavernas.

[[v41-2-14]]

^<<v41-2-14,14>>^ Eis que venho agora contra ti – oráculo do Senhor dos exércitos –; vou incendiar teus carros e reduzi-los à fumaça, a espada vai devorar os teus leõezinhos; porei fim às tuas rapinas na terra, não se ouvirá mais a voz dos teus mensageiros.

'''

xref:041-naum/041-naum-001.adoc#v41-1-0[&#60; Capítulo Anterior] | <<v41-2-0,Topo>> | xref:041-naum/041-naum-003.adoc#v41-3-0[Próximo Capítulo &#62;]