include::./index.adoc[]

[[v41-1-0]]
=== Naum, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Naum 1 trata da justiça e ira divina contra os inimigos de Judá. Deus é apresentado como um Deus zeloso e vingativo, mas também como um refúgio seguro para aqueles que confiam nele. Abaixo estão cinco versículos relacionados com os temas abordados em Naum 1:
* Salmos 7:11 - "Deus é juiz justo, um Deus que se ira todos os dias contra os ímpios." Este versículo mostra que Deus é justo em sua ira contra os ímpios, como retratado em Naum 1.
* Salmos 46:1 - "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia." Este versículo mostra que, apesar da ira divina, Deus é um refúgio seguro para aqueles que confiam nele.
* Provérbios 21:15 - "Fazer justiça é alegria para o justo, mas terror para os que praticam o mal." Este versículo destaca a importância da justiça divina, que é tema central em Naum 1.
* Isaías 63:4 - "Porque o dia da vingança estava no meu coração, e o ano dos meus remidos é chegado." Este versículo retrata a vingança divina contra os inimigos de Judá, que é tema central em Naum 1.
* Hebreus 10:30-31 - "Porque conhecemos aquele que disse: Minha é a vingança, eu darei a recompensa, diz o Senhor. E outra vez: O Senhor julgará o seu povo. Horrenda coisa é cair nas mãos do Deus vivo." Este versículo destaca a natureza da ira divina e como é temido pelos ímpios.
****

[[v41-1-1]]

^<<v41-1-1,1>>^ Oráculo sobre Nínive. Livro da visão de Naum de Elcós.^&#42;1^

[[v41-1-2]]

^<<v41-1-2,2>>^ O Senhor é um Deus zeloso e vingador, o Senhor é um vingador irascível; o Senhor toma vingança de seus adversários e trata com rigor os seus inimigos.^&#42;1^

[[v41-1-3]]

^<<v41-1-3,3>>^ O Senhor é paciente e grande em poder, não deixa impune o culpado. O Senhor caminha em meio à tempestade e sobre o vento impetuoso, as nuvens são a poeira de seus pés.

[[v41-1-4]]

^<<v41-1-4,4>>^ Ele ameaça o mar e torna-o seco, e esgota todos os regatos. O Basã e o Carmelo fenecem, as flores do Líbano murcham.

[[v41-1-5]]

^<<v41-1-5,5>>^ As montanhas vacilam diante dele, desaparecem as colinas; a terra, o mundo e todos os seus habitantes agitam-se diante dele.

[[v41-1-6]]

^<<v41-1-6,6>>^ Quem poderia enfrentar sua cólera? Quem poderia resistir ao ardor de sua ira? Seu furor derrama-se como um fogo, seu aspecto basta para destruir rochedos.

[[v41-1-7]]

^<<v41-1-7,7>>^ O Senhor é bom, é um refúgio na tribulação; conhece os que nele confiam.

[[v41-1-8]]

^<<v41-1-8,8>>^ Como um temporal violento ele destruirá este lugar, e, mesmo nas trevas, acossará seus inimigos.

[[v41-1-9]]

^<<v41-1-9,9>>^ Que tramais contra o Senhor? Ele vai consumar a ruína; esse desastre não se produzirá duas vezes.^&#42;1^

[[v41-1-10]]

^<<v41-1-10,10>>^ Porque, entrelaçados como espinheiros, ébrios do seu vinho, serão consumidos como a palha seca.^&#42;1^

[[v41-1-11]]

^<<v41-1-11,11>>^ De ti saiu o maquinador do mal contra o Senhor, o tramador de maus desígnios.^&#42;1^

[[v41-1-12]]

^<<v41-1-12,12>>^ Eis o que diz o Senhor: Por mais fortes e numerosos que sejam, nem por isso serão menos ceifados, sem apelação. Eu te afligi, mas não te afligirei mais.

[[v41-1-13]]

^<<v41-1-13,13>>^ Vou agora quebrar o jugo que pesava sobre ti, e romper tuas cadeias.

[[v41-1-14]]

^<<v41-1-14,14>>^ Quanto a ti, eis o que ordenou o Senhor: descendência alguma levará teu nome. Farei desaparecer do templo de teus deuses as imagens esculpidas e as imagens fundidas. Vou preparar teu sepulcro, porque és pouca coisa.

'''

xref:040-miqueias/040-miqueias-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-naum/041-naum-002.adoc#v41-2-0[Próximo Capítulo &#62;]