include::./index.adoc[]

[[v65-8-0]]
=== Hebreus, 8
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Hebreus 8 aborda o tema do sacerdócio de Jesus Cristo e a superioridade de seu ministério em relação ao sacerdócio levítico. O capítulo também destaca a nova aliança estabelecida por meio de Jesus Cristo e as promessas divinas que foram cumpridas através dele.
* 2 Coríntios 3:6: "Ele nos capacitou para sermos ministros de uma nova aliança, não da letra, mas do Espírito; pois a letra mata, mas o Espírito vivifica." Esse versículo destaca a diferença entre a nova aliança estabelecida por Jesus Cristo e a antiga aliança baseada na lei. A nova aliança é governada pelo Espírito, enquanto a antiga aliança era governada pela letra da lei.
* Jeremias 31:31: "Está chegando o tempo", declara o Senhor, "quando farei uma nova aliança com a comunidade de Israel e com a comunidade de Judá." Esse versículo é citado em Hebreus 8:8-12 para mostrar que a nova aliança estabelecida por Jesus Cristo foi profetizada pelo profeta Jeremias. Essa nova aliança é superior à antiga aliança estabelecida com Israel.
* Jeremias 31:33: "Esta é a aliança que farei com a comunidade de Israel depois daqueles dias", declara o Senhor. "Porei a minha lei no íntimo deles e a escreverei nos seus corações. Serei o Deus deles, e eles serão o meu povo." Esse versículo é citado em Hebreus 8:10 para mostrar como a nova aliança estabelecida por Jesus Cristo é diferente da antiga aliança. A lei de Deus não é mais escrita em tábuas de pedra, mas é escrita nos corações dos crentes.
* Hebreus 7:26: "Tal sumo sacerdote nos convinha: santo, inculpável, sem mácula, separado dos pecadores e feito mais elevado do que os céus." Esse versículo destaca a superioridade do sacerdócio de Jesus Cristo em relação ao sacerdócio levítico. Jesus Cristo é o sumo sacerdote perfeito que ofereceu um sacrifício único e perfeito pelos pecados da humanidade.
* Hebreus 9:15: "Por isso, Cristo é o mediador de uma nova aliança para que os que são chamados recebam a promessa da herança eterna, visto que ele morreu como resgate pelas transgressões cometidas sob a primeira aliança." Esse versículo destaca que a morte de Jesus Cristo foi o preço pago para estabelecer a nova aliança e cumprir as promessas divinas. Através dele, aqueles que são chamados podem receber a promessa da herança eterna.
****

[[v65-8-1]]

^<<v65-8-1,1>>^ O ponto essencial do que acabamos de dizer é este: temos um Sumo Sacerdote, que está sentado à direita do trono da Majestade divina nos céus,

[[v65-8-2]]

^<<v65-8-2,2>>^ Ministro do santuário e do verdadeiro tabernáculo, erigido pelo Senhor, e não por homens.

[[v65-8-3]]

^<<v65-8-3,3>>^ Todo pontífice é constituído para oferecer dons e sacrifícios. Portanto, é necessário que ele tenha algo para oferecer.

[[v65-8-4]]

^<<v65-8-4,4>>^ Por conseguinte, se ele estivesse na terra, nem mesmo sacerdote seria, porque já existem aqui sacerdotes que têm a missão de oferecer os dons prescritos pela Lei.

[[v65-8-5]]

^<<v65-8-5,5>>^ O culto que estes celebram é, aliás, apenas a imagem, sombra das realidades celestiais, como foi revelado a Moisés quando estava para construir o tabernáculo: Olha, foi-lhe dito, faze todas as coisas conforme o modelo que te foi mostrado no monte (Ex 25,40).

[[v65-8-6]]

^<<v65-8-6,6>>^ Ao nosso Sumo Sacerdote, entretanto, compete ministério tanto mais excelente quanto ele é mediador de uma aliança mais perfeita, selada por melhores promessas.

[[v65-8-7]]

^<<v65-8-7,7>>^ Porque, se a primeira tivesse sido sem defeito, certamente não haveria lugar para outra.

[[v65-8-8]]

^<<v65-8-8,8>>^ Ora, sem dúvida, há uma censura nestas palavras: Eis que virão dias – oráculo do Senhor – em que estabelecerei com a casa de Israel e com a casa de Judá uma aliança nova.

[[v65-8-9]]

^<<v65-8-9,9>>^ Não como a aliança que fiz com os seus pais no dia em que os tomei pela mão para tirá-los da terra do Egito. Como eles não permaneceram fiéis ao pacto, eu me desinteressei deles – oráculo do Senhor.

[[v65-8-10]]

^<<v65-8-10,10>>^ Mas esta é a aliança que estabelecerei com a casa de Israel depois daqueles dias: imprimirei as minhas leis no seu espírito e as gravarei no seu coração. Eu serei seu Deus, e eles serão meu povo.

[[v65-8-11]]

^<<v65-8-11,11>>^ Ninguém mais terá que ensinar a seu concidadão, ninguém a seu irmão, dizendo: “Conhece o Senhor”, porque todos me conhecerão, desde o menor até o maior.

[[v65-8-12]]

^<<v65-8-12,12>>^ Eu lhes perdoarei as suas iniquidades, e já não me lembrarei dos seus pecados (Jr 31,31-34).

[[v65-8-13]]

^<<v65-8-13,13>>^ Se Deus fala de uma aliança nova é que ele declara antiquada a precedente. Ora, o que é antiquado e envelhecido está certamente fadado a desaparecer.

'''

xref:065-hebreus/065-hebreus-007.adoc#v65-7-0[&#60; Capítulo Anterior] | <<v65-8-0,Topo>> | xref:065-hebreus/065-hebreus-009.adoc#v65-9-0[Próximo Capítulo &#62;]