include::./index.adoc[]

[[v65-10-0]]
=== Hebreus, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Hebreus 10 fala sobre a superioridade do sacrifício de Jesus Cristo em relação aos sacrifícios oferecidos pelos sacerdotes do Antigo Testamento. O capítulo destaca a suficiência do sacrifício de Jesus, que foi oferecido uma vez por todas para purificar os pecados da humanidade. A seguir estão cinco versículos relacionados com os temas abordados em Hebreus 10:
* Isaías 53:6: "Todos nós andávamos desgarrados como ovelhas; cada um se desviava pelo caminho, mas o Senhor fez cair sobre ele a iniquidade de nós todos." Este versículo aponta para a natureza pecaminosa da humanidade e como todos nós precisamos de um sacrifício para nos purificar.
* Salmo 40:6-8: "Sacrifício e oferta não quiseste; os meus ouvidos abriste; holocausto e expiação pelo pecado não exigiste. Então eu disse: Eis aqui estou; no rolo do livro está escrito a meu respeito. Deleito-me em fazer a tua vontade, ó Deus meu; sim, a tua lei está dentro do meu coração." Este salmo destaca a obediência de Jesus em oferecer a sua vida como um sacrifício, em vez de seguir o ritual dos sacrifícios oferecidos pelos sacerdotes.
* Levítico 16:34: "Este será para vós um estatuto perpétuo, para fazer expiação pelos filhos de Israel de todos os seus pecados, uma vez por ano." Este versículo destaca a limitação do ritual anual de expiação pelos pecados do povo, em contraste com o sacrifício de Jesus que foi oferecido uma vez por todas para purificar os pecados da humanidade.
* Isaías 52:13-15: "Eis que o meu servo procederá com prudência; será exaltado, será elevado, será mui sublime. Como pasmaram muitos à vista dele, pois o seu aspecto estava tão desfigurado que não era o de um homem, e a sua figura não era a dos filhos dos homens; assim ele aspergirá muitas nações, e os reis cerrarão as suas bocas por causa dele; porque aquilo que não lhes foi anunciado verão, e aquilo que eles não ouviram entenderão." Este versículo aponta para o sofrimento de Jesus na cruz e como isso foi essencial para a purificação dos pecados da humanidade.
* Jeremias 31:33: "Porém este é o pacto que farei com a casa de Israel depois daqueles dias, diz o Senhor: Porei a minha lei no seu interior, e a escreverei no seu coração; e eu serei o seu Deus e eles serão o meu povo." Este versículo destaca a promessa de Deus de escrever a sua lei no coração da humanidade, o que só é possível através do sacrifício de Jesus.
****

[[v65-10-1]]

^<<v65-10-1,1>>^ A Lei, por ser apenas a sombra dos bens futuros, não sua expressão real, é de todo impotente para aperfeiçoar aqueles que assistem aos sacrifícios que se renovam indefinidamente cada ano.

[[v65-10-2]]

^<<v65-10-2,2>>^ Realmente, se os fiéis, uma vez purificados, não tivessem mais pecado algum na consciência, não teriam cessado de oferecê-los?

[[v65-10-3]]

^<<v65-10-3,3>>^ Pelo contrário, pelos sacrifícios se renova cada ano a memória dos pecados.

[[v65-10-4]]

^<<v65-10-4,4>>^ Pois é impossível que o sangue de touros e de carneiros tire pecados.

[[v65-10-5]]

^<<v65-10-5,5>>^ Eis por que, ao entrar no mundo, Cristo diz: Não quiseste sacrifício nem oblação, mas me formaste um corpo.

[[v65-10-6]]

^<<v65-10-6,6>>^ Holocaustos e sacrifícios pelo pecado não te agradam.

[[v65-10-7]]

^<<v65-10-7,7>>^ Então, eu disse: Eis que venho (porque é de mim que está escrito no rolo do livro), venho, ó Deus, para fazer a tua vontade (Sl 39,7ss).^&#42;1^

[[v65-10-8]]

^<<v65-10-8,8>>^ Disse primeiro: Tu não quiseste, tu não recebeste com agrado os sacrifícios nem as ofertas, nem os holocaustos, nem as vítimas pelo pecado (quer dizer, as imolações legais).

[[v65-10-9]]

^<<v65-10-9,9>>^ Em seguida, ajuntou: Eis que venho para fazer a tua vontade. Assim, aboliu o antigo regime e estabeleceu uma nova economia.

[[v65-10-10]]

^<<v65-10-10,10>>^ Foi em virtude desta vontade de Deus que temos sido santificados uma vez para sempre, pela oblação do corpo de Jesus Cristo.

[[v65-10-11]]

^<<v65-10-11,11>>^ Enquanto todo sacerdote se ocupa diariamente com o seu ministério e repete inúmeras vezes os mesmos sacrifícios que, todavia, não conseguem apagar os pecados,

[[v65-10-12]]

^<<v65-10-12,12>>^ Cristo ofereceu pelos pecados um único sacrifício e logo em seguida tomou lugar para sempre à direita de Deus,

[[v65-10-13]]

^<<v65-10-13,13>>^ onde espera de ora em diante que os seus inimigos sejam postos por escabelo dos seus pés (Sl 109,1).

[[v65-10-14]]

^<<v65-10-14,14>>^ Por uma só oblação ele realizou a perfeição definitiva daqueles que recebem a santificação.

[[v65-10-15]]

^<<v65-10-15,15>>^ É o que nos confirma o testemunho do Espírito Santo. Depois de ter dito:

[[v65-10-16]]

^<<v65-10-16,16>>^ Eis a aliança que, depois daqueles dias, farei com eles – oráculo do Senhor: imprimirei as minhas leis nos seus corações e as escreverei no seu espírito,

[[v65-10-17]]

^<<v65-10-17,17>>^ acrescenta: dos seus pecados e das suas iniquidades já não mais me lembrarei (Jr 31,33s).

[[v65-10-18]]

^<<v65-10-18,18>>^ Ora, onde houve plena remissão dos pecados não há por que oferecer sacrifício por eles.

[[v65-10-19]]

^<<v65-10-19,19>>^ Por esse motivo, irmãos, temos ampla confiança de poder entrar no santuário eterno, em virtude do sangue de Jesus,

[[v65-10-20]]

^<<v65-10-20,20>>^ pelo caminho novo e vivo que nos abriu através do véu, isto é, o caminho de seu próprio corpo.

[[v65-10-21]]

^<<v65-10-21,21>>^ E dado que temos um sumo sacerdote estabelecido sobre a casa de Deus,

[[v65-10-22]]

^<<v65-10-22,22>>^ acheguemo-nos a ele com coração sincero, com plena firmeza da fé, o mais íntimo da alma isento de toda mácula de pecado e o corpo lavado com a água purificadora (do batismo).

[[v65-10-23]]

^<<v65-10-23,23>>^ Conservemo-nos firmemente apegados à nossa esperança, porque é fiel aquele cuja promessa aguardamos.

[[v65-10-24]]

^<<v65-10-24,24>>^ Olhemos uns pelos outros para estímulo à caridade e às boas obras.

[[v65-10-25]]

^<<v65-10-25,25>>^ Não abandonemos a nossa assembleia, como é costume de alguns, mas admoestemo-nos mutuamente, e tanto mais quando vedes aproximar-se o Grande Dia.^&#42;1^

[[v65-10-26]]

^<<v65-10-26,26>>^ Depois de termos recebido e conhecido a verdade, se a abandonarmos voluntariamente, já não haverá sacrifício para expiar este pecado.

[[v65-10-27]]

^<<v65-10-27,27>>^ Só teremos que esperar um juízo tremendo e o fogo ardente que há de devorar os rebeldes.

[[v65-10-28]]

^<<v65-10-28,28>>^ Se alguém transgredir a Lei de Moisés – e isto provado com duas ou três testemunhas –, deverá ser morto sem misericórdia.

[[v65-10-29]]

^<<v65-10-29,29>>^ Quanto pior castigo julgais que merece quem calcar aos pés o Filho de Deus, profanar o sangue da aliança, em que foi santificado, e ultrajar o Espírito Santo, autor da graça!

[[v65-10-30]]

^<<v65-10-30,30>>^ Pois bem sabemos quem é que disse: Minha é a vingança; eu a exercerei (Dt 32,35). E ainda: O Senhor julgará o seu povo (Sl 134,14).

[[v65-10-31]]

^<<v65-10-31,31>>^ É horrendo cair nas mãos do Deus vivo.

[[v65-10-32]]

^<<v65-10-32,32>>^ Lembrai-vos dos dias de outrora, logo que fostes iluminados. Quão longas e dolorosas lutas sustentastes.^&#42;1^

[[v65-10-33]]

^<<v65-10-33,33>>^ Seja tornando-vos alvo de toda espécie de opróbrios e humilhações, seja tomando moralmente parte nos sofrimentos daqueles que os tiveram que suportar.

[[v65-10-34]]

^<<v65-10-34,34>>^ Não só vos compadecestes dos encarcerados, mas aceitastes com alegria a confiscação dos vossos bens, pela certeza de possuirdes riquezas muito melhores e imperecíveis.

[[v65-10-35]]

^<<v65-10-35,35>>^ Não percais esta convicção a que está vinculada uma grande recompensa,

[[v65-10-36]]

^<<v65-10-36,36>>^ pois vos é necessária a perseverança para fazerdes a vontade de Deus e alcançardes os bens prometidos.

[[v65-10-37]]

^<<v65-10-37,37>>^ Ainda um pouco de tempo – sem dúvida, bem pouco –, e o que há de vir virá e não tardará.^&#42;1^

[[v65-10-38]]

^<<v65-10-38,38>>^ Meu justo viverá da fé. Porém, se ele desfalecer, meu coração já não se agradará dele (Hab 2,3s).

[[v65-10-39]]

^<<v65-10-39,39>>^ Não somos, absolutamente, de perder o ânimo para nossa ruína; somos de manter a fé, para nossa salvação!

'''

xref:065-hebreus/065-hebreus-009.adoc#v65-9-0[&#60; Capítulo Anterior] | <<v65-10-0,Topo>> | xref:065-hebreus/065-hebreus-011.adoc#v65-11-0[Próximo Capítulo &#62;]