include::./index.adoc[]

[[v65-9-0]]
=== Hebreus, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Hebreus 9 trata principalmente sobre a comparação entre o sistema de sacrifícios do Antigo Testamento e o sacrifício de Jesus Cristo, que se ofereceu a si mesmo como um sacrifício eterno. Além disso, o capítulo também destaca a importância do sangue na remissão dos pecados e a necessidade de uma única morte para expiar os pecados de toda a humanidade.
* Levítico 17:11: "Porque a vida da carne está no sangue. Eu vo-lo dei sobre o altar, para fazer expiação pelas vossas almas, porquanto é o sangue que fará expiação em virtude da vida." Este versículo enfatiza a importância do sangue como meio de expiação pelos pecados.
* Hebreus 9:22: "E quase todas as coisas, segundo a lei, se purificam com sangue; e sem derramamento de sangue não há remissão." Esse versículo reforça a importância do sangue na remissão dos pecados e destaca a necessidade de um sacrifício com derramamento de sangue para obter a remissão.
* Isaías 53:5-6: "Mas ele foi ferido por causa das nossas transgressões, e moído por causa das nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e pelas suas pisaduras fomos sarados. Todos nós andávamos desgarrados como ovelhas; cada um se desviava pelo seu caminho; mas o Senhor fez cair sobre ele a iniquidade de nós todos." Esse versículo descreve a morte de Jesus como um sacrifício pelos pecados da humanidade, destacando a importância da sua morte como expiação pelos pecados.
* Hebreus 10:4: "Porque é impossível que o sangue de touros e de bodes remova pecados." Esse versículo reforça a ideia de que o sistema de sacrifícios do Antigo Testamento não era suficiente para expiar os pecados, destacando a necessidade de um sacrifício perfeito para obter a remissão.
* Hebreus 10:10: "Na qual vontade temos sido santificados pela oblação do corpo de Jesus Cristo, feita uma vez para sempre." Esse versículo destaca a singularidade do sacrifício de Jesus, que se ofereceu a si mesmo como um sacrifício eterno para expiar os pecados da humanidade, enfatizando a superioridade do sacrifício de Jesus em relação aos sacrifícios do Antigo Testamento.
****

[[v65-9-1]]

^<<v65-9-1,1>>^ A primeira aliança, na verdade, teve regulamentos rituais e seu santuário terrestre.

[[v65-9-2]]

^<<v65-9-2,2>>^ Consistia numa tenda: a parte anterior encerrava o candelabro e a mesa com os pães da proposição; chamava-se Santo.

[[v65-9-3]]

^<<v65-9-3,3>>^ Atrás do segundo véu achava-se a parte chamada Santo dos Santos.

[[v65-9-4]]

^<<v65-9-4,4>>^ Aí estava o altar de ouro para os perfumes, e a arca da aliança coberta de ouro por todos os lados; dentro dela, a urna de ouro contendo o maná, a vara de Aarão que floresceu e as tábuas da aliança;

[[v65-9-5]]

^<<v65-9-5,5>>^ em cima da arca, os querubins da glória estendendo a sombra de suas asas sobre o propiciatório. Mas não é aqui o lugar de falarmos destas coisas pormenorizadamente.^&#42;1^

[[v65-9-6]]

^<<v65-9-6,6>>^ Assim sendo, enquanto na primeira parte do tabernáculo entram continuamente os sacerdotes para desempenhar as funções,

[[v65-9-7]]

^<<v65-9-7,7>>^ no segundo entra apenas o sumo sacerdote, somente uma vez ao ano, e ainda levando consigo o sangue para oferecer pelos seus próprios pecados e pelos do povo.

[[v65-9-8]]

^<<v65-9-8,8>>^ Com o que significava o Espírito Santo que o caminho do Santo dos Santos ainda não estava livre, enquanto subsistisse o primeiro tabernáculo.^&#42;1^

[[v65-9-9]]

^<<v65-9-9,9>>^ Isto é também uma figura que se refere ao tempo presente, sinal de que os dons e sacrifícios que se ofereciam eram incapazes de justificar a consciência daquele que praticava o culto.

[[v65-9-10]]

^<<v65-9-10,10>>^ Culto que consistia unicamente em comidas, bebidas e abluções diversas, ritos materiais que só podiam ter valor enquanto não fossem instituídos outros mais perfeitos.^&#42;1^

[[v65-9-11]]

^<<v65-9-11,11>>^ Porém, já veio Cristo, Sumo Sacerdote dos bens vindouros. E através de um tabernáculo mais excelente e mais perfeito, não construído por mãos humanas (não deste mundo),

[[v65-9-12]]

^<<v65-9-12,12>>^ sem levar consigo o sangue de carneiros ou novilhos, mas com seu próprio sangue, entrou de uma vez por todas no santuário, adquirindo-nos uma redenção eterna.

[[v65-9-13]]

^<<v65-9-13,13>>^ Pois se o sangue de carneiros e de touros e a cinza de uma vaca, com que se aspergem os impuros, santificam e purificam pelo menos os corpos,

[[v65-9-14]]

^<<v65-9-14,14>>^ quanto mais o sangue de Cristo, que pelo Espírito eterno se ofereceu como vítima sem mácula a Deus, purificará a nossa consciência das obras mortas para o serviço do Deus vivo?

[[v65-9-15]]

^<<v65-9-15,15>>^ Por isso, ele é mediador do novo testamento. Pela sua morte expiou os pecados cometidos no decorrer do primeiro testamento, para que os eleitos recebam a herança eterna que lhes foi prometida.^&#42;1^

[[v65-9-16]]

^<<v65-9-16,16>>^ Porque, onde há testamento, é necessário que intervenha a morte do testador.

[[v65-9-17]]

^<<v65-9-17,17>>^ Um testamento só entra em vigor depois da morte do testador. Permanece sem efeito enquanto ele vive.

[[v65-9-18]]

^<<v65-9-18,18>>^ Por essa razão, nem mesmo o primeiro testamento foi inaugurado sem uma efusão de sangue.

[[v65-9-19]]

^<<v65-9-19,19>>^ Moisés, ao concluir a proclamação de todos os mandamentos da Lei, em presença de todo o povo reunido, tomou o sangue dos touros e dos cabritos imolados, bem como água, lã escarlate e hissopo, aspergiu com sangue não só o próprio livro, como também todo o povo,

[[v65-9-20]]

^<<v65-9-20,20>>^ dizendo: Este é o sangue da aliança que Deus contraiu convosco (Ex 24,8).

[[v65-9-21]]

^<<v65-9-21,21>>^ E da mesma maneira aspergiu o tabernáculo e todos os objetos do culto.

[[v65-9-22]]

^<<v65-9-22,22>>^ Aliás, conforme a Lei, o sangue é utilizado para quase todas as purificações, e sem efusão de sangue não há perdão.

[[v65-9-23]]

^<<v65-9-23,23>>^ Se os meros símbolos das realidades celestes exigiam uma tal purificação, necessário se tornava que as realidades mesmo fossem purificadas por sacrifícios ainda superiores.

[[v65-9-24]]

^<<v65-9-24,24>>^ Eis por que Cristo entrou, não em santuário feito por mãos de homens, que fosse apenas figura do santuário verdadeiro, mas no próprio céu, para agora se apresentar intercessor nosso ante a face de Deus.

[[v65-9-25]]

^<<v65-9-25,25>>^ E não entrou para se oferecer muitas vezes a si mesmo, como o pontífice que entrava todos os anos no santuário para oferecer sangue alheio.

[[v65-9-26]]

^<<v65-9-26,26>>^ Do contrário, lhe seria necessário padecer muitas vezes desde o princípio do mundo; quando é certo que apareceu uma só vez ao final dos tempos para destruição do pecado pelo sacrifício de si mesmo.

[[v65-9-27]]

^<<v65-9-27,27>>^ Como está determinado que os homens morram uma só vez, e logo em seguida vem o juízo,

[[v65-9-28]]

^<<v65-9-28,28>>^ assim Cristo se ofereceu uma só vez para tomar sobre si os pecados da multidão, e aparecerá uma segunda vez, não porém em razão do pecado, mas para trazer a salvação àqueles que o esperam.

'''

xref:065-hebreus/065-hebreus-008.adoc#v65-8-0[&#60; Capítulo Anterior] | <<v65-9-0,Topo>> | xref:065-hebreus/065-hebreus-010.adoc#v65-10-0[Próximo Capítulo &#62;]