include::./index.adoc[]

[[v73-11-0]]
=== Apocalipse, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 11 do livro de Apocalipse descreve a medição do templo de Deus, a presença de duas testemunhas que profetizam e realizam milagres, a batalha contra a Besta, a ressurreição das testemunhas e o terremoto que destrói a décima cidade. Aqui estão cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em Apocalipse 11:
* Zacarias 4:2-3: "E perguntei: Que é isto? E ele me disse: Isto é o candelabro todo de ouro, que está diante do Senhor de toda a terra. E duas oliveiras há junto dela, uma à direita do vaso do azeite, e outra à sua esquerda." Este versículo fala de um candelabro de ouro, que pode ser relacionado com a medição do templo de Deus em Apocalipse 11.
* 1 Reis 17:1: "Elias, o tesbita, dos moradores de Gileade, disse a Acabe: Vive o Senhor Deus de Israel, perante cuja face estou, que nestes anos nem orvalho nem chuva haverá, senão segundo a minha palavra." As duas testemunhas em Apocalipse 11 têm o poder de fechar o céu para que não chova, como Elias fez.
* 2 Reis 2:11: "E sucedeu que, indo eles andando e falando, eis que um carro de fogo, com cavalos de fogo, os separou um do outro; e Elias subiu ao céu num redemoinho." A ascensão de Elias pode ser comparada com a ascensão das duas testemunhas em Apocalipse 11.
* Daniel 7:21-22: "Eu olhava, quando esse chifre fazia guerra contra os santos, e prevalecia contra eles, até que veio o Ancião de dias, e fez justiça aos santos do Altíssimo; e chegou o tempo em que os santos possuíram o reino." Esse versículo fala da batalha contra os santos, que é semelhante à batalha contra as duas testemunhas em Apocalipse 11.
* Isaías 26:19: "Os teus mortos viverão, juntamente com o meu corpo morto ressuscitarão. Despertai e cantai, os que habitais no pó; porque o teu orvalho, ó Deus, será como o orvalho das ervas, e a terra lançará de si os mortos." A ressurreição das testemunhas em Apocalipse 11 é semelhante à ressurreição mencionada neste versículo.
****

[[v73-11-1]]

^<<v73-11-1,1>>^ Foi-me dada uma vara semelhante a uma vara de agrimensor, e disseram-me: “Levanta-te! Mede o templo de Deus e o altar com seus adoradores.^&#42;1^

[[v73-11-2]]

^<<v73-11-2,2>>^ O átrio fora do templo, porém, deixa-o de lado e não o meças: foi dado aos gentios, que hão de calcar aos pés a Cidade Santa por quarenta e dois meses.

[[v73-11-3]]

^<<v73-11-3,3>>^ Mas incumbirei as minhas duas testemunhas, vestidas de saco, de profetizarem por mil duzentos e sessenta dias”.^&#42;1^

[[v73-11-4]]

^<<v73-11-4,4>>^ São elas as duas oliveiras e os dois candelabros que se mantêm diante do Senhor da terra.

[[v73-11-5]]

^<<v73-11-5,5>>^ Se alguém lhes quiser causar dano, sairá fogo de suas bocas e devorará os inimigos. Com efeito, se alguém os quiser ferir, cumpre que assim seja morto.

[[v73-11-6]]

^<<v73-11-6,6>>^ Esses homens têm o poder de fechar o céu para que não caia chuva durante os dias de sua profecia; têm poder sobre as águas, para transformá-las em sangue, e de ferir a terra, sempre que quiserem, com toda sorte de flagelos.

[[v73-11-7]]

^<<v73-11-7,7>>^ Mas, depois de terem terminado integralmente o seu testemunho, a Fera que sobe do abismo lhes fará guerra, os vencerá e os matará.

[[v73-11-8]]

^<<v73-11-8,8>>^ Seus cadáveres (jazerão) na rua da grande cidade que se chama espiritualmente Sodoma e Egito (onde o seu Senhor foi crucificado).

[[v73-11-9]]

^<<v73-11-9,9>>^ Muitos dentre os povos, tribos, línguas e nações virão para vê-los por três dias e meio, e não permitirão que sejam sepultados.

[[v73-11-10]]

^<<v73-11-10,10>>^ Os habitantes da terra se alegrarão por causa deles, se felicitarão mutuamente e mandarão presentes uns aos outros, porque esses dois profetas tinham sido seu tormento.

[[v73-11-11]]

^<<v73-11-11,11>>^ Mas, depois de três dias e meio, um sopro de vida, vindo de Deus, os penetrou. Puseram-se de pé e grande terror caiu sobre aqueles que os viam.^&#42;1^

[[v73-11-12]]

^<<v73-11-12,12>>^ Ouviram uma forte voz do céu que dizia: “Subi aqui!”. Subiram então para o céu em uma nuvem, enquanto os seus inimigos os olhavam.

[[v73-11-13]]

^<<v73-11-13,13>>^ Naquela mesma hora produziu-se grande terremoto, caiu uma décima parte da cidade e pereceram no terremoto sete mil pessoas. As demais, aterrorizadas, deram glória ao Deus do céu.

[[v73-11-14]]

^<<v73-11-14,14>>^ Terminou assim a segunda desgraça. E eis que depressa sobrevém a terceira.^&#42;1^

[[v73-11-15]]

^<<v73-11-15,15>>^ O sétimo anjo tocou a trombeta. Ressoaram então no céu altas vozes que diziam: “O império de nosso Senhor e de seu Cristo estabeleceu-se sobre o mundo, e ele reinará pelos séculos dos séculos”.

[[v73-11-16]]

^<<v73-11-16,16>>^ Os vinte e quatro Anciãos, que se assentam nos seus tronos diante de Deus, prostraram-se de rosto em terra e adoraram a Deus,

[[v73-11-17]]

^<<v73-11-17,17>>^ dizendo: “Graças te damos, Senhor, Deus Dominador, que és e que eras, porque assumiste a plenitude de teu poder real.

[[v73-11-18]]

^<<v73-11-18,18>>^ Irritaram-se os pagãos, mas eis que sobreveio a tua ira e o tempo de julgar os mortos, de dar a recompensa aos teus servos, aos profetas, aos santos, aos que temem o teu nome, pequenos e grandes, e de exterminar os que corromperam a terra”.

[[v73-11-19]]

^<<v73-11-19,19>>^ Abriu-se o Templo de Deus no céu e apareceu, no seu templo, a arca do seu testamento. Houve relâmpagos, vozes, trovões, terremotos e forte saraiva.

'''

xref:073-apocalipse/073-apocalipse-010.adoc#v73-10-0[&#60; Capítulo Anterior] | <<v73-11-0,Topo>> | xref:073-apocalipse/073-apocalipse-012.adoc#v73-12-0[Próximo Capítulo &#62;]