include::./index.adoc[]

[[v73-16-0]]
=== Apocalipse, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Apocalipse 16 descreve a série de sete taças da ira de Deus que são derramadas sobre a terra, trazendo juízo e destruição sobre aqueles que rejeitaram a salvação e se opuseram a Deus. Os versículos abaixo foram selecionados por sua relação com os temas abordados neste capítulo.
* Jeremias 25:15-16: "Porque assim me disse o Senhor, o Deus de Israel: Toma da minha mão este cálice do vinho da ira e faze-o beber a todas as nações, às quais eu te envio; para que bebam, e cambaleiem, e enlouqueçam, por causa da espada que enviarei entre eles." Este versículo fala sobre a ira de Deus sendo derramada sobre as nações por causa de sua desobediência.
* Salmos 79:6: "Derrama o teu furor sobre as nações que não te conhecem, e sobre os reinos que não invocam o teu nome." Este salmo clama a Deus para trazer juízo sobre aqueles que não o reconhecem como Senhor e Salvador.
* Isaías 51:17: "Desperta, desperta, levanta-te, ó Jerusalém, que bebeste da mão do Senhor o cálice da sua ira; pois o cálice tremendo bebeste até ao fundo." Este versículo descreve o juízo que caiu sobre Jerusalém por causa da desobediência do povo.
* Êxodo 7:20: "Moisés e Arão fizeram como o Senhor ordenara, e, levantando a vara, feriu as águas que estavam no rio, à vista de Faraó e dos seus servos; e todas as águas do rio se tornaram em sangue." Este versículo lembra da praga das águas que se tornaram em sangue, que foi uma das dez pragas enviadas sobre o Egito como juízo divino.
* Apocalipse 11:18: "As nações se iraram; e chegou a tua ira. É chegada a hora de julgares os mortos e de dares recompensa aos teus servos, os profetas, aos santos e aos que temem o teu nome, tanto aos pequenos como aos grandes, e de destruíres os que destroem a terra." Este versículo fala sobre a ira de Deus que será derramada sobre aqueles que destroem a terra, e a recompensa que será dada aos seus servos fiéis.
****

[[v73-16-1]]

^<<v73-16-1,1>>^ Ouvi, então, uma voz forte saindo do templo, que dizia aos sete Anjos: “Ide, e derramai sobre a terra as sete taças da ira de Deus”.

[[v73-16-2]]

^<<v73-16-2,2>>^ O primeiro, portanto, pôs-se a derramar a sua taça sobre a terra. Formou-se uma úlcera atroz e maligna nos homens que tinham o sinal da Fera e que se prostravam diante de sua imagem.

[[v73-16-3]]

^<<v73-16-3,3>>^ O segundo derramou a sua taça sobre o mar. Este tornou-se sangue, como o de um morto, e pereceu todo ser que estava no mar.

[[v73-16-4]]

^<<v73-16-4,4>>^ O terceiro derramou a sua taça sobre os rios e as fontes das águas, que se transformaram em sangue.

[[v73-16-5]]

^<<v73-16-5,5>>^ Ouvi, então, o anjo das águas dizer: “Tu és justo, tu que és e que eras o Santo, que assim julgas.

[[v73-16-6]]

^<<v73-16-6,6>>^ Porque eles derramaram o sangue dos santos e dos profetas, tu lhes deste também sangue para beber. Eles o merecem”.

[[v73-16-7]]

^<<v73-16-7,7>>^ Ouvi o altar dizer: “Sim, Senhor Deus Dominador, são verdadeiros e justos os teus julgamentos”.^&#42;1^

[[v73-16-8]]

^<<v73-16-8,8>>^ O quarto derramou a sua taça sobre o sol, e foi-lhe dado queimar os homens com o fogo.

[[v73-16-9]]

^<<v73-16-9,9>>^ E os homens foram queimados por grande calor, e amaldiçoaram o nome de Deus, que pode desencadear esses flagelos; e não quiseram arrepender-se e dar-lhe glória.

[[v73-16-10]]

^<<v73-16-10,10>>^ O quinto derramou a sua taça sobre o trono da Fera. Seu reino se escureceu e seus súditos mordiam a língua de dor.

[[v73-16-11]]

^<<v73-16-11,11>>^ Amaldiçoaram o Deus do céu por causa de seus sofrimentos e das suas feridas, sem se arrependerem dos seus atos.

[[v73-16-12]]

^<<v73-16-12,12>>^ O sexto derramou a sua taça sobre o grande rio Eufrates, e secaram-se as suas águas para que se abrisse caminho aos reis do Oriente.

[[v73-16-13]]

^<<v73-16-13,13>>^ Vi (saírem) da boca do Dragão, da boca da Fera e da boca do falso profeta três espíritos imundos semelhantes a rãs;^&#42;1^

[[v73-16-14]]

^<<v73-16-14,14>>^ são os espíritos de demônios que realizam prodígios, e vão ter com os reis de toda a terra, a fim de reuni-los para a batalha do Grande Dia do Deus Dominador.

[[v73-16-15]]

^<<v73-16-15,15>>^ (Eis que venho como um ladrão! Feliz aquele que vigia e guarda as suas vestes para que não ande nu, ostentando a sua vergonha!)

[[v73-16-16]]

^<<v73-16-16,16>>^ Eles os reuniram num lugar chamado em hebraico Har-Magedon.^&#42;1^

[[v73-16-17]]

^<<v73-16-17,17>>^ O sétimo derramou a sua taça pelos ares e saiu do templo uma grande voz do trono, que dizia: “Está pronto!”.

[[v73-16-18]]

^<<v73-16-18,18>>^ Houve, então, relâmpagos, vozes e trovões, assim como um terremoto tão grande como jamais houve desde que há homens na terra.

[[v73-16-19]]

^<<v73-16-19,19>>^ A grande cidade foi dividida em três partes, e as cidades das nações caíram, e Deus lembrou-se da grande Babilônia, para lhe dar de beber o cálice do vinho de sua ira ardente.

[[v73-16-20]]

^<<v73-16-20,20>>^ Todas as ilhas fugiram, e montanha alguma foi encontrada.

[[v73-16-21]]

^<<v73-16-21,21>>^ Grandes pedras de gelo, que podiam pesar um talento, caíram do céu sobre os homens. Os homens amaldiçoaram a Deus por causa do flagelo da saraiva, pois este foi terrível.^&#42;1^

'''

xref:073-apocalipse/073-apocalipse-015.adoc#v73-15-0[&#60; Capítulo Anterior] | <<v73-16-0,Topo>> | xref:073-apocalipse/073-apocalipse-017.adoc#v73-17-0[Próximo Capítulo &#62;]