include::./index.adoc[]

[[v73-20-0]]
=== Apocalipse, 20
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Apocalipse 20 descreve a cena em que Satanás é preso por mil anos e Cristo reina com os santos na terra. Cinco versículos relacionados com os temas abordados em Apocalipse 20 são:
* 2 Pedro 3:7: "E os céus e a terra que agora existem pela mesma palavra se reservam como tesouro, e se guardam para o fogo, até o Dia do Juízo, e da perdição dos homens ímpios." Este versículo menciona o Dia do Juízo, que é o evento que ocorre após o reinado de mil anos de Cristo e antes do novo céu e nova terra.
* Mateus 19:28: "Jesus lhes disse: Em verdade vos digo que vós, que me seguistes, quando, na regeneração, o Filho do homem se assentar no trono da sua glória, também vos assentareis sobre doze tronos, para julgar as doze tribos de Israel." Este versículo fala sobre a regeneração, que pode ser interpretada como o reinado de mil anos de Cristo na terra.
* Lucas 22:30: "para que comais e bebais à minha mesa no meu reino, e vos assenteis sobre tronos, julgando as doze tribos de Israel." Este versículo também fala sobre o reino de Cristo e a participação dos santos no julgamento das tribos de Israel.
* 1 Coríntios 6:2: "Ou não sabeis que os santos hão de julgar o mundo? Ora, se o mundo deve ser julgado por vós, sois porventura indignos de julgar as coisas mínimas?" Este versículo reforça a ideia de que os santos participarão do julgamento no reino de Cristo.
* Isaías 2:2: "E acontecerá nos últimos dias que se firmará o monte da casa do SENHOR no cume dos montes, e se elevará por cima dos outeiros; e concorrerão a ele todas as nações." Este versículo fala sobre a universalidade do reino de Cristo, que será estabelecido após o julgamento.
****

[[v73-20-1]]

^<<v73-20-1,1>>^ Vi, então, descer do céu um anjo que tinha na mão a chave do abismo e uma grande algema.

[[v73-20-2]]

^<<v73-20-2,2>>^ Ele apanhou o Dragão, a primitiva Serpente, que é o Demônio e Satanás, e o acorrentou por mil anos.^&#42;1^

[[v73-20-3]]

^<<v73-20-3,3>>^ Atirou-o no abismo, que fechou e selou por cima, para que já não seduzisse as nações, até que se completassem mil anos. Depois disso, ele deve ser solto por um pouco de tempo.

[[v73-20-4]]

^<<v73-20-4,4>>^ Vi também tronos, sobre os quais se assentaram aqueles que receberam o poder de julgar: eram as almas dos que foram decapitados por causa do testemunho de Jesus e da Palavra de Deus, e todos aqueles que não tinham adorado a Fera ou sua imagem, que não tinham recebido o seu sinal na fronte nem nas mãos. Eles viveram uma vida nova e reinaram com Cristo por mil anos.^&#42;1^

[[v73-20-5]]

^<<v73-20-5,5>>^ (Os outros mortos não tornaram à vida até que se completassem os mil anos.) Essa é a primeira ressurreição.

[[v73-20-6]]

^<<v73-20-6,6>>^ Feliz e santo é aquele que toma parte na primeira ressurreição! Sobre eles a segunda morte não tem poder, mas serão sacerdotes de Deus e de Cristo: reinarão com ele durante os mil anos.

[[v73-20-7]]

^<<v73-20-7,7>>^ Depois de se completarem mil anos, Satanás será solto da prisão.^&#42;1^

[[v73-20-8]]

^<<v73-20-8,8>>^ Sairá dela para seduzir as nações dos quatro cantos da terra (Gog e Magog) e reuni-las para o combate. Serão numerosas como a areia do mar.

[[v73-20-9]]

^<<v73-20-9,9>>^ Subiram à superfície da terra e cercaram o acampamento dos santos e a cidade querida. Mas desceu um fogo dos céus e as devorou.

[[v73-20-10]]

^<<v73-20-10,10>>^ O Demônio, sedutor delas, foi lançado num lago de fogo e de enxofre, onde já estavam a Fera e o falso profeta, e onde serão atormentados, dia e noite, pelos séculos dos séculos.

[[v73-20-11]]

^<<v73-20-11,11>>^ Vi, então, um grande trono branco e aquele que nele se assentava. Os céus e a terra fugiram de sua face, e já não se achou lugar para eles.^&#42;1^

[[v73-20-12]]

^<<v73-20-12,12>>^ Vi os mortos, grandes e pequenos, de pé, diante do trono. Abriram-se livros, e ainda outro livro, que é o livro da vida. E os mortos foram julgados conforme o que estava escrito nesse livro, segundo as suas obras.

[[v73-20-13]]

^<<v73-20-13,13>>^ O mar restituiu os mortos que nele estavam. Do mesmo modo, a morte e a morada subterrânea. Cada um foi julgado segundo as suas obras.

[[v73-20-14]]

^<<v73-20-14,14>>^ A morte e a morada subterrânea foram lançadas no tanque de fogo. A segunda morte é esta: o tanque de fogo.

[[v73-20-15]]

^<<v73-20-15,15>>^ Todo o que não foi encontrado inscrito no livro da vida foi lançado ao fogo.

'''

xref:073-apocalipse/073-apocalipse-019.adoc#v73-19-0[&#60; Capítulo Anterior] | <<v73-20-0,Topo>> | xref:073-apocalipse/073-apocalipse-021.adoc#v73-21-0[Próximo Capítulo &#62;]