include::./index.adoc[]

[[v73-18-0]]
=== Apocalipse, 18
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Apocalipse 18 fala sobre a queda da grande cidade, Babilônia, que é vista como uma figura simbólica do sistema mundial de poder e corrupção. A cidade é vista como responsável por todas as coisas malignas e abomináveis que têm ocorrido na terra. Aqui estão cinco versículos de outras partes da Bíblia que se relacionam com os temas abordados em Apocalipse 18:
* Jeremias 50:32: "A soberba de Babilônia cairá e não se levantará mais; destruirei as suas imagens esculpidas e as suas estátuas; e ela será para sempre um objeto de horror." Este versículo fala sobre a queda da cidade de Babilônia e sua soberba, o que é semelhante ao que é descrito em Apocalipse 18.
* Jeremias 51:7: "A Babilônia foi um cálice de ouro nas mãos do Senhor, que embriagou toda a terra. As nações beberam do vinho da sua ira; por isso, elas agora estão loucas." Este versículo descreve como a Babilônia foi usada por Deus para punir outras nações, mas agora ela mesma será punida.
* Jeremias 51:45: "Saiam do meio dela, povo meu! Salvem-se, cada um de vocês, da ira ardente do Senhor." Este versículo é um apelo para que as pessoas saiam da cidade de Babilônia antes que ela seja destruída, o que é semelhante ao que é descrito em Apocalipse 18.
* Isaías 47:8-9: "Agora, porém, ouça isto, ó delicada, que vive despreocupada e diz em seu coração: ‘Eu sou a única, e não há mais ninguém como eu. Não ficarei viúva, nem perderei os meus filhos’. Ambas essas coisas virão sobre você num instante, num mesmo dia: a perda de seus filhos e a viuvez. Elas virão sobre você em toda a sua plenitude, apesar de suas muitas feitiçarias e do grande número de seus encantamentos." Este versículo se refere à cidade de Babilônia como uma figura simbólica de uma mulher arrogante e autoconfiante que será punida por suas maldades.
* Isaías 48:20: "Saiam de Babilônia! Fugam dos babilônios! Anunciem isto com gritos de alegria, e proclamem-no. Mandem-no até os confins da terra; digam: ‘O Senhor resgatou o seu servo Jacó!’" Este versículo é um chamado para as pessoas deixarem a cidade de Babilônia antes que ela seja destruída.
****

[[v73-18-1]]

^<<v73-18-1,1>>^ Depois disso, vi descer do céu outro anjo que tinha grande poder, e a terra foi iluminada por sua glória.

[[v73-18-2]]

^<<v73-18-2,2>>^ Clamou em alta voz, dizendo: “Caiu, caiu Babilônia, a Grande. Tornou-se morada dos demônios, prisão dos espíritos imundos e das aves impuras e abomináveis,

[[v73-18-3]]

^<<v73-18-3,3>>^ porque todas as nações beberam do vinho da ira de sua luxúria, pecaram com ela os reis da terra e os mercadores da terra se enriqueceram com o excesso do seu luxo”.

[[v73-18-4]]

^<<v73-18-4,4>>^ Ouvi outra voz do céu que dizia: “Meu povo, sai de seu meio para que não participes de seus pecados e não tenhas parte nas suas pragas,

[[v73-18-5]]

^<<v73-18-5,5>>^ porque seus pecados se acumularam até o céu, e Deus se lembrou das suas injustiças.

[[v73-18-6]]

^<<v73-18-6,6>>^ Faze com ela o que fez (contigo), e retribui-lhe o dobro de seus malefícios; na taça que ela deu de beber, dá-lhe o dobro.

[[v73-18-7]]

^<<v73-18-7,7>>^ Na mesma proporção em que fez ostentação de luxo, dá-lhe em tormentos e prantos. Pois ela disse no seu coração: Estou no trono como rainha, e não viúva, e nunca conhecerei o luto.

[[v73-18-8]]

^<<v73-18-8,8>>^ Por isso, num só dia virão sobre ela as pragas: morte, pranto, fome. Ela será consumida pelo fogo, porque forte é o Senhor Deus que a condenou”.

[[v73-18-9]]

^<<v73-18-9,9>>^ Hão de chorar e lamentar-se por sua causa os reis da terra que com ela se contaminaram e pecaram, quando avistarem a fumaça do seu incêndio.

[[v73-18-10]]

^<<v73-18-10,10>>^ Parados ao longe, de medo de seus tormentos, eles dirão: “Ai, ai da grande cidade, Babilônia, cidade poderosa! Bastou um momento para tua execução!”.

[[v73-18-11]]

^<<v73-18-11,11>>^ Também os negociantes da terra choram e se lamentam a seu respeito, porque já não há ninguém que lhes compre os carregamentos:

[[v73-18-12]]

^<<v73-18-12,12>>^ carregamento de ouro e prata, pedras preciosas e pérolas, linho e púrpura, seda e escarlate, bem como de toda espécie de madeira odorífera, objetos de marfim e madeira preciosa; de bronze, ferro e mármore;

[[v73-18-13]]

^<<v73-18-13,13>>^ de cinamomo e essência; de aromas, mirra e incenso; de vinho e óleo, de farinha e trigo, de animais de carga, ovelhas, cavalos e carros, escravos e outros homens.

[[v73-18-14]]

^<<v73-18-14,14>>^ Eis que o bom tempo de tuas paixões animalescas se escoou. Toda a magnificência e todo o brilho se apagaram, e jamais serão reencontrados.

[[v73-18-15]]

^<<v73-18-15,15>>^ Os mercadores dessas coisas, que delas se enriqueceram, pararão ao longe, de medo de seus tormentos, e hão de chorar e lamentar-se, dizendo:

[[v73-18-16]]

^<<v73-18-16,16>>^ “Ai, ai da grande cidade, que se revestia de linho, púrpura e escarlate, toda ornada de ouro, pedras preciosas e pérolas.

[[v73-18-17]]

^<<v73-18-17,17>>^ Num só momento toda essa riqueza foi devastada!”. Todos os pilotos e todos os navegantes, os marinheiros e todos os que trabalham no mar paravam ao longe

[[v73-18-18]]

^<<v73-18-18,18>>^ e exclamavam, ao ver a fumaça do incêndio: “Que havia de comparável a essa grande cidade?”.

[[v73-18-19]]

^<<v73-18-19,19>>^ E lançavam pó sobre as cabeças, chorando e lamentando-se com estas palavras: “Ai, ai da grande cidade, de cuja opulência se enriqueceram todos os que tinham navios no mar. Bastou um momento para ser arrasada!

[[v73-18-20]]

^<<v73-18-20,20>>^ Exulta sobre ela, ó céu; e também vós, santos, apóstolos e profetas, porque Deus julgou contra ela a vossa causa”.

[[v73-18-21]]

^<<v73-18-21,21>>^ Então, um anjo poderoso tomou uma pedra do tamanho de uma grande mó de moinho e lançou-a no mar, dizendo: “Com tal ímpeto será precipitada a Babilônia, a grande cidade, e jamais será encontrada.

[[v73-18-22]]

^<<v73-18-22,22>>^ Já não se ouvirá mais em ti o som dos citaristas, dos cantores, dos tocadores de flauta, de trombetas. Nem se encontrará em ti artífice algum de qualquer espécie. Não se ouvirá mais em ti o ruído do moinho,

[[v73-18-23]]

^<<v73-18-23,23>>^ não brilhará mais em ti a luz de lâmpada, não se ouvirá mais em ti a voz do esposo e da esposa; porque teus mercadores eram senhores do mundo, e todas as nações foram seduzidas por teus malefícios.

[[v73-18-24]]

^<<v73-18-24,24>>^ Foi em ti que se encontrou o sangue dos profetas e dos santos, como também de todos aqueles que foram imolados na terra”.

'''

xref:073-apocalipse/073-apocalipse-017.adoc#v73-17-0[&#60; Capítulo Anterior] | <<v73-18-0,Topo>> | xref:073-apocalipse/073-apocalipse-019.adoc#v73-19-0[Próximo Capítulo &#62;]