include::./index.adoc[]

[[v73-3-0]]
=== Apocalipse, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 3 do livro de Apocalipse traz as mensagens de Jesus às igrejas de Sardes, Filadélfia e Laodiceia. Jesus elogia a igreja de Filadélfia por sua fidelidade e exorta as igrejas de Sardes e Laodiceia a se arrependerem e voltarem para Ele. Os cinco versículos relacionados com os temas abordados em Apocalipse 3 são:
* 2 Coríntios 6:17-18: "Por isso, saí do meio deles e separai-vos, diz o Senhor; não toqueis em coisas impuras; e eu vos receberei; eu serei vosso Pai, e vós sereis para mim filhos e filhas, diz o Senhor Todo-Poderoso". Esse versículo se relaciona com a exortação de Jesus para as igrejas de Sardes e Laodiceia se arrependerem e se afastarem da impureza.
* Provérbios 3:11-12: "Não desprezes, filho meu, a correção do Senhor, nem te desanimes quando por ele fores repreendido. Porque o Senhor repreende aquele a quem ama, assim como o pai faz ao filho a quem quer bem". Esse versículo se relaciona com a exortação de Jesus para as igrejas de Sardes e Laodiceia se arrependerem e voltarem para Ele.
* 2 Timóteo 4:7-8: "Combati o bom combate, acabei a corrida, guardei a fé. Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele dia; e não somente a mim, mas também a todos os que amarem a sua vinda". Esse versículo se relaciona com a exortação de Jesus para as igrejas de Sardes e Laodiceia perseverarem na fé e na fidelidade até o fim.
* 1 Coríntios 15:58: "Portanto, meus amados irmãos, sede firmes, inabaláveis e sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor". Esse versículo se relaciona com a exortação de Jesus para a igreja de Filadélfia, que foi fiel e perseverante em sua obra, mesmo em meio a perseguições.
* 2 Pedro 3:9: "Não retarda o Senhor a sua promessa, como alguns a julgam demorada; pelo contrário, ele é longânimo para convosco, não querendo que nenhum pereça, senão que todos cheguem ao arrependimento". Esse versículo se relaciona com a exortação de Jesus para as igrejas de Sardes e Laodiceia se arrependerem e voltarem para Ele, porque Ele é paciente e deseja a salvação de todos.
****

[[v73-3-1]]

^<<v73-3-1,1>>^ “Ao anjo da igreja de Sardes, escreve: Eis o que diz aquele que tem os sete Espíritos de Deus e as sete estrelas. Conheço as tuas obras: és considerado vivo, mas estás morto.

[[v73-3-2]]

^<<v73-3-2,2>>^ Sê vigilante e consolida o resto que ia morrer, pois não achei tuas obras perfeitas diante de meu Deus.

[[v73-3-3]]

^<<v73-3-3,3>>^ Lembra-te de como recebeste e ouviste a doutrina. Observa-a e arrepende-te. Se não vigiares, virei a ti como um ladrão, e não saberás a que horas te surpreenderei.

[[v73-3-4]]

^<<v73-3-4,4>>^ Todavia, tens em Sardes algumas pessoas que não contaminaram suas vestes; andarão comigo vestidas de branco, porque o merecem.^&#42;1^

[[v73-3-5]]

^<<v73-3-5,5>>^ O vencedor será assim revestido de vestes brancas. Jamais apagarei o seu nome do livro da vida, e o proclamarei diante de meu Pai e dos seus anjos.

[[v73-3-6]]

^<<v73-3-6,6>>^ Quem tiver ouvidos, ouça o que o Espírito diz às igrejas.”

[[v73-3-7]]

^<<v73-3-7,7>>^ “Ao anjo da igreja de Filadélfia, escreve: Eis o que diz o Santo e o Verdadeiro, aquele que tem a chave de Davi – que abre e ninguém pode fechar; que fecha e ninguém pode abrir.^&#42;1^

[[v73-3-8]]

^<<v73-3-8,8>>^ Conheço as tuas obras: eu pus diante de ti uma porta aberta, que ninguém pode fechar; porque, apesar de tua fraqueza, guardaste a minha palavra e não renegaste o meu nome.

[[v73-3-9]]

^<<v73-3-9,9>>^ Eu te entrego adeptos da sinagoga de Satanás, desses que se dizem judeus, e não o são, mas mentem. Eis que os farei vir prostrar-se aos teus pés e reconhecerão que eu te amo.

[[v73-3-10]]

^<<v73-3-10,10>>^ Porque guardaste a palavra de minha paciência, também eu te guardarei da hora da provação, que está para sobrevir ao mundo inteiro, para provar os habitantes da terra.

[[v73-3-11]]

^<<v73-3-11,11>>^ Venho em breve. Conserva o que tens, para que ninguém tome a tua coroa.

[[v73-3-12]]

^<<v73-3-12,12>>^ Farei do vencedor uma coluna no Templo de meu Deus, de onde jamais sairá, e escreverei sobre ele o nome de meu Deus, e o nome da cidade de meu Deus, a nova Jerusalém, que desce dos céus enviada por meu Deus, assim como o meu nome novo.^&#42;1^

[[v73-3-13]]

^<<v73-3-13,13>>^ Quem tiver ouvidos, ouça o que o Espírito diz às igrejas.”

[[v73-3-14]]

^<<v73-3-14,14>>^ “Ao anjo da igreja de Laodiceia, escreve: Eis o que diz o Amém, a Testemunha fiel e verdadeira, o Princípio da criação de Deus.

[[v73-3-15]]

^<<v73-3-15,15>>^ Conheço as tuas obras: não és nem frio nem quente. Oxalá fosses frio ou quente!

[[v73-3-16]]

^<<v73-3-16,16>>^ Mas, como és morno, nem frio nem quente, vou vomitar-te.

[[v73-3-17]]

^<<v73-3-17,17>>^ Pois dizes: Sou rico, faço bons negócios, de nada necessito – e não sabes que és infeliz, miserável, pobre, cego e nu.

[[v73-3-18]]

^<<v73-3-18,18>>^ Aconselho-te que compres de mim ouro provado ao fogo, para ficares rico; roupas alvas para te vestires, a fim de que não apareça a vergonha de tua nudez; e um colírio para ungir os olhos, de modo que possas ver claro.^&#42;1^

[[v73-3-19]]

^<<v73-3-19,19>>^ Eu repreendo e castigo aqueles que amo. Reanima, pois, o teu zelo e arrepende-te.

[[v73-3-20]]

^<<v73-3-20,20>>^ Eis que estou à porta e bato: se alguém ouvir a minha voz e me abrir a porta, entrarei em sua casa e cearemos, eu com ele e ele comigo.

[[v73-3-21]]

^<<v73-3-21,21>>^ Ao vencedor concederei assentar-se comigo no meu trono, assim como eu venci e me assentei com meu Pai no seu trono.

[[v73-3-22]]

^<<v73-3-22,22>>^ Quem tiver ouvidos, ouça o que o Espírito diz às igrejas.”

'''

xref:073-apocalipse/073-apocalipse-002.adoc#v73-2-0[&#60; Capítulo Anterior] | <<v73-3-0,Topo>> | xref:073-apocalipse/073-apocalipse-004.adoc#v73-4-0[Próximo Capítulo &#62;]