include::./index.adoc[]

[[v73-7-0]]
=== Apocalipse, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Apocalipse 7 é um capítulo que fala sobre a proteção divina dada a um grupo seleto de pessoas durante o período de tribulação que ocorrerá na terra. Esse grupo é composto por 144.000 judeus, 12.000 de cada uma das 12 tribos de Israel, que são selados por Deus para que não sofram danos durante esse tempo. Além disso, uma grande multidão de todas as nações, povos, tribos e línguas é vista diante do trono de Deus, louvando-O e adorando-O.
* Romanos 8:38-39: "Porque estou certo de que, nem a morte, nem a vida, nem anjos, nem principados, nem coisas presentes, nem futuras, nem potestades, nem a altura, nem a profundidade, nem qualquer outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus nosso Senhor." Esse versículo destaca que nada pode separar os crentes do amor de Deus, incluindo as dificuldades e perseguições que enfrentam durante a tribulação.
* Mateus 24:21-22: "Porque haverá então grande aflição, como nunca houve desde o princípio do mundo até agora, nem jamais haverá. E se aqueles dias não fossem abreviados, ninguém se salvaria; mas por causa dos escolhidos serão abreviados aqueles dias." Esse versículo descreve o período de tribulação e como ele será tão intenso que, se não fosse encurtado por Deus, ninguém sobreviveria.
* 1 Pedro 1:7: "Para que a prova da vossa fé, muito mais preciosa do que o ouro que perece e é provado pelo fogo, vos seja atribuída em louvor, honra e glória na revelação de Jesus Cristo;" Esse versículo fala sobre a importância da prova da fé durante o período de tribulação, que será um teste para os crentes e mostrará a força e a verdadeira natureza da sua fé.
* João 10:16: "Ainda tenho outras ovelhas que não são deste aprisco; também me convém agregar estas, e elas ouvirão a minha voz, e haverá um rebanho e um pastor." Esse versículo fala sobre como pessoas de todas as nações serão salvas e se unirão em um rebanho sob o pastoreio de Jesus Cristo, o que é visto em Apocalipse 7 com a grande multidão de todas as nações, povos, tribos e línguas diante do trono de Deus.
****

[[v73-7-1]]

^<<v73-7-1,1>>^ Depois disso, vi quatro Anjos que se conservavam em pé nos quatro cantos da terra, detendo os quatro ventos da terra, para que nenhum vento soprasse sobre a terra, sobre o mar ou sobre árvore alguma.^&#42;1^

[[v73-7-2]]

^<<v73-7-2,2>>^ Vi ainda outro anjo subir do Oriente; trazia o selo de Deus vivo, e pôs-se a clamar com voz retumbante aos quatro Anjos, aos quais fora dado danificar a terra e o mar, dizendo:

[[v73-7-3]]

^<<v73-7-3,3>>^ “Não danifiqueis a terra, nem o mar, nem as árvores, até que tenhamos assinalado os servos de nosso Deus em suas frontes”.^&#42;1^

[[v73-7-4]]

^<<v73-7-4,4>>^ Ouvi então o número dos assinalados: cento e quarenta e quatro mil assinalados, de toda tribo dos filhos de Israel;^&#42;1^

[[v73-7-5]]

^<<v73-7-5,5>>^ da tribo de Judá, doze mil assinalados; da tribo de Rúben, doze mil; da tribo de Gad, doze mil;

[[v73-7-6]]

^<<v73-7-6,6>>^ da tribo de Aser, doze mil; da tribo de Neftali, doze mil; da tribo de Manassés, doze mil;

[[v73-7-7]]

^<<v73-7-7,7>>^ da tribo de Simeão, doze mil; da tribo de Levi, doze mil; da tribo de Issacar, doze mil;

[[v73-7-8]]

^<<v73-7-8,8>>^ da tribo de Zabulon, doze mil; da tribo de José, doze mil; da tribo de Benjamim, doze mil assinalados.

[[v73-7-9]]

^<<v73-7-9,9>>^ Depois disso, vi uma grande multidão que ninguém podia contar, de toda nação, tribo, povo e língua: conservavam-se em pé diante do trono e diante do Cordeiro, de vestes brancas e palmas na mão,^&#42;1^

[[v73-7-10]]

^<<v73-7-10,10>>^ e bradavam em alta voz: “A salvação é obra de nosso Deus, que está assentado no trono, e do Cordeiro”.

[[v73-7-11]]

^<<v73-7-11,11>>^ E todos os Anjos estavam ao redor do trono, dos Anciãos e dos quatro Animais; prostravam-se de face em terra diante do trono e adoravam a Deus, dizendo:

[[v73-7-12]]

^<<v73-7-12,12>>^ “Amém, louvor, glória, sabedoria, ação de graças, honra, poder e força ao nosso Deus pelos séculos dos séculos! Amém”.

[[v73-7-13]]

^<<v73-7-13,13>>^ Então, um dos Anciãos falou comigo e perguntou-me: “Esses, que estão revestidos de vestes brancas, quem são e de onde vêm?”.

[[v73-7-14]]

^<<v73-7-14,14>>^ Respondi-lhe: “Meu Senhor, tu o sabes”. E ele me disse: “Esses são os sobreviventes da grande tribulação; lavaram as suas vestes e as alvejaram no sangue do Cordeiro.

[[v73-7-15]]

^<<v73-7-15,15>>^ Por isso, estão diante do trono de Deus e o servem, dia e noite, no seu templo. Aquele que está sentado no trono os abrigará em sua tenda. Já não terão fome, nem sede, nem o sol ou calor algum os abrasará,

[[v73-7-16]]

^<<v73-7-16,16>>^ porque o Cordeiro, que está no meio do trono, será o seu pastor e os levará às fontes das águas vivas; e Deus enxugará toda lágrima de seus olhos”.

'''

xref:073-apocalipse/073-apocalipse-006.adoc#v73-6-0[&#60; Capítulo Anterior] | <<v73-7-0,Topo>> | xref:073-apocalipse/073-apocalipse-008.adoc#v73-8-0[Próximo Capítulo &#62;]