include::./index.adoc[]

[[v73-9-0]]
=== Apocalipse, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Apocalipse 9 descreve a abertura do quinto e sexto selos, o que resulta na liberação de pragas terríveis sobre a terra. No quinto selo, é revelada a perseguição dos santos e, no sexto selo, a devastação da terra e do céu. Aqui estão cinco versículos relacionados com os temas abordados em Apocalipse 9:
* Mateus 24:21: "Pois então haverá grande tribulação, como nunca houve desde o princípio do mundo até agora, nem jamais haverá." Este versículo descreve a tribulação que ocorrerá durante o fim dos tempos, semelhante ao que é descrito no quinto selo de Apocalipse 9.
* Lucas 21:25-26: "Haverá sinais no sol, na lua e nas estrelas; sobre a terra, angústia entre as nações em perplexidade por causa do bramido do mar e das ondas; homens desmaiando de terror, na expectativa das coisas que sobrevirão ao mundo." Este versículo descreve o caos e a destruição que ocorrerão durante o fim dos tempos, semelhante ao que é descrito no sexto selo de Apocalipse 9.
* Joel 2:4-5: "A sua aparência é como a de cavalos; e como cavaleiros assim correm. Como o som de carros saltando sobre os cumes dos montes, assim eles saltam; como o som de uma chama de fogo que consome a palha, assim é o povo que vem em multidão." Este versículo descreve uma invasão de gafanhotos, semelhante ao que é descrito na quinta trombeta de Apocalipse 9.
* Êxodo 10:14: "Subiram, pois, os gafanhotos sobre toda a terra do Egito, e pousaram sobre todos os seus termos; eram muitíssimos; antes destes nunca houve tantos, nem depois deles haverá." Este versículo descreve uma praga de gafanhotos que atingiu o Egito, semelhante ao que é descrito na quinta trombeta de Apocalipse 9.
* Isaías 13:10: "Porque as estrelas dos céus e as suas constelações não darão a sua luz; o sol se escurecerá ao nascer, e a lua não resplandecerá com a sua luz." Este versículo descreve a escuridão que cobrirá a terra durante o fim dos tempos, semelhante ao que é descrito no sexto selo de Apocalipse 9.
****

[[v73-9-1]]

^<<v73-9-1,1>>^ O quinto anjo tocou a trombeta. Vi então uma estrela cair do céu na terra, e foi-lhe dada a chave do poço do abismo;^&#42;1^

[[v73-9-2]]

^<<v73-9-2,2>>^ ela o abriu e saiu do poço uma fumaça como a de uma grande fornalha. O sol e o ar obscureceram-se com a fumaça do poço.

[[v73-9-3]]

^<<v73-9-3,3>>^ Da fumaça saíram gafanhotos pela terra, e foi-lhes dado poder semelhante ao dos escorpiões da terra.^&#42;1^

[[v73-9-4]]

^<<v73-9-4,4>>^ Mas foi-lhes dito que não causassem dano à erva, verdura, ou árvore alguma, mas somente aos homens que não têm o selo de Deus na fronte.

[[v73-9-5]]

^<<v73-9-5,5>>^ Foi-lhes ordenado que não os matassem, mas os afligissem por cinco meses. Seu tormento era como o da picada do escorpião.^&#42;1^

[[v73-9-6]]

^<<v73-9-6,6>>^ Naqueles dias, os homens buscarão a morte e não a conseguirão; desejarão morrer, e a morte fugirá deles.

[[v73-9-7]]

^<<v73-9-7,7>>^ O aspecto desses gafanhotos era o de cavalos aparelhados para a guerra. Nas suas cabeças havia uma espécie de coroa com reflexos dourados. Seus rostos eram como rostos de homem,

[[v73-9-8]]

^<<v73-9-8,8>>^ seus cabelos como os de mulher e seus dentes, como os dentes de leão.

[[v73-9-9]]

^<<v73-9-9,9>>^ Seus tórax pareciam envoltos em ferro, e o ruído de suas asas era como o ruído de carros de muitos cavalos, correndo para a guerra.

[[v73-9-10]]

^<<v73-9-10,10>>^ Tinham caudas semelhantes à do escorpião, com ferrões e o poder de afligir os homens por cinco meses.

[[v73-9-11]]

^<<v73-9-11,11>>^ Têm eles por rei o anjo do abismo; chama-se em hebraico Abadon e, em grego, Apolion.^&#42;1^

[[v73-9-12]]

^<<v73-9-12,12>>^ Terminado assim o primeiro “ai”, eis que, depois dele, vêm ainda dois outros.

[[v73-9-13]]

^<<v73-9-13,13>>^ O sexto anjo tocou a trombeta. Ouvi então uma voz que vinha dos quatro cantos do altar de ouro, que está diante de Deus,

[[v73-9-14]]

^<<v73-9-14,14>>^ e que dizia ao sexto anjo que tinha a trombeta: “Solta os quatro Anjos que estão acorrentados à beira do grande rio Eufrates”.^&#42;1^

[[v73-9-15]]

^<<v73-9-15,15>>^ Então, foram soltos os quatro Anjos que se conservavam preparados para a hora, o dia, o mês e o ano da matança da terça parte dos homens...

[[v73-9-16]]

^<<v73-9-16,16>>^ O número de soldados dessa cavalaria era de duzentos milhões. Eu ouvi o seu número.

[[v73-9-17]]

^<<v73-9-17,17>>^ E foi assim que eu vi os cavalos e os que os montavam: estes últimos eram couraçados de uma chama sulfurosa azul. Os cavalos tinham crina como uma juba de leão e de suas narinas saíam fogo, fumaça e enxofre.^&#42;1^

[[v73-9-18]]

^<<v73-9-18,18>>^ E uma terça parte dos homens foi morta por esses três flagelos (fogo, fumaça e enxofre) que lhes saíam das narinas.

[[v73-9-19]]

^<<v73-9-19,19>>^ Porque o poder nocivo dos cavalos estava também nas caudas; tinham cabeças como serpentes e causavam dano com elas.

[[v73-9-20]]

^<<v73-9-20,20>>^ Mas o restante dos homens, que não foram mortos por esses três flagelos, não se arrependeu das obras de suas mãos. Não cessaram de adorar o demônio e os ídolos de ouro, de prata, de bronze, de pedra e de madeira, que não podem ver, nem ouvir, nem andar.

[[v73-9-21]]

^<<v73-9-21,21>>^ Não se arrependeram de seus homicídios, seus malefícios, suas imundícies e furtos.

'''

xref:073-apocalipse/073-apocalipse-008.adoc#v73-8-0[&#60; Capítulo Anterior] | <<v73-9-0,Topo>> | xref:073-apocalipse/073-apocalipse-010.adoc#v73-10-0[Próximo Capítulo &#62;]