include::./index.adoc[]

[[v73-21-0]]
=== Apocalipse, 21
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 21 do livro de Apocalipse fala sobre a nova Jerusalém, a cidade santa de Deus que desce do céu. Ele descreve a beleza e glória dessa cidade eterna, onde não haverá mais dor, morte ou tristeza. Os versículos a seguir foram selecionados por sua relação com os temas abordados neste capítulo.
* Isaías 65:17: "Pois eis que eu crio novos céus e nova terra; e não haverá lembrança das coisas passadas, nem mais se recordarão." Este versículo fala sobre a criação de novos céus e nova terra, que é um tema semelhante ao novo céu e a nova terra mencionados em Apocalipse 21:1.
* 2 Pedro 3:13: "Mas, segundo a sua promessa, esperamos novos céus e nova terra, nos quais habita justiça." Este versículo também fala sobre a criação de novos céus e nova terra e menciona a justiça que habita lá, assim como Apocalipse 21:27 menciona que nada impuro entrará na nova Jerusalém.
* Mateus 5:8: "Bem-aventurados os limpos de coração, porque verão a Deus." Este versículo se relaciona com Apocalipse 21:3, que fala sobre a habitação de Deus com os homens na nova Jerusalém. A pureza de coração é uma condição para ver a Deus.
* Isaías 25:8: "Aniquilará a morte para sempre, e assim enxugará o Senhor DEUS as lágrimas de todos os rostos, e tirará o opróbrio do seu povo de toda a terra; porque o SENHOR o disse." Este versículo fala sobre a eliminação da morte e do sofrimento, um tema comum em Apocalipse 21:4, que menciona a ausência de morte, luto, pranto e dor na nova Jerusalém.
* Hebreus 12:22-24: "Mas tendes chegado ao monte Sião, e à cidade do Deus vivo, à Jerusalém celestial, e aos muitos milhares de anjos; À universal assembléia e igreja dos primogênitos, que estão inscritos nos céus, e a Deus, o juiz de todos, e aos espíritos dos justos aperfeiçoados; E a Jesus, o Mediador de uma nova aliança, e ao sangue da aspersão, que fala melhor do que o de Abel." Este versículo se relaciona com Apocalipse 21:2, que fala sobre a descida da nova Jerusalém do céu. Ambos descrevem a cidade celestial de Deus e a habitação dos santos.
****

[[v73-21-1]]

^<<v73-21-1,1>>^ Vi, então, um novo céu e uma nova terra, pois o primeiro céu e a primeira terra desapareceram e o mar já não existia.

[[v73-21-2]]

^<<v73-21-2,2>>^ Eu vi descer do céu, de junto de Deus, a Cidade Santa, a nova Jerusalém, como uma esposa ornada para o esposo.

[[v73-21-3]]

^<<v73-21-3,3>>^ Ao mesmo tempo, ouvi do trono uma grande voz que dizia: “Eis aqui o tabernáculo de Deus com os homens. Habitará com eles e serão o seu povo, e Deus mesmo estará com eles.

[[v73-21-4]]

^<<v73-21-4,4>>^ Enxugará toda lágrima de seus olhos e já não haverá morte, nem luto, nem grito, nem dor, porque passou a primeira condição”.

[[v73-21-5]]

^<<v73-21-5,5>>^ Então, o que está assentado no trono disse: “Eis que eu renovo todas as coisas”. Disse ainda: “Escreve, porque estas palavras são fiéis e verdadeiras”.

[[v73-21-6]]

^<<v73-21-6,6>>^ Novamente me disse: “Está pronto! Eu sou o Alfa e o Ômega, o Começo e o Fim. A quem tem sede eu darei gratuitamente de beber da fonte da água viva.

[[v73-21-7]]

^<<v73-21-7,7>>^ O vencedor herdará tudo isso; e eu serei seu Deus, e ele será meu filho.

[[v73-21-8]]

^<<v73-21-8,8>>^ Os tíbios, os infiéis, os depravados, os homicidas, os impuros, os maléficos, os idólatras e todos os mentirosos terão como quinhão o tanque ardente de fogo e enxofre, a segunda morte”.

[[v73-21-9]]

^<<v73-21-9,9>>^ Então, veio um dos sete Anjos que tinham as sete taças cheias dos sete últimos flagelos e disse-me: “Vem, e eu te mostrarei a noiva, a esposa do Cordeiro”.^&#42;1^

[[v73-21-10]]

^<<v73-21-10,10>>^ Levou-me em espírito a um grande e alto monte e mostrou-me a Cidade Santa, Jerusalém, que descia do céu, de junto de Deus,

[[v73-21-11]]

^<<v73-21-11,11>>^ revestida da glória de Deus. Assemelhava-se seu esplendor a uma pedra muito preciosa, tal como o jaspe cristalino.

[[v73-21-12]]

^<<v73-21-12,12>>^ Tinha grande e alta muralha com doze portas, guardadas por doze anjos. Nas portas estavam gravados os nomes das doze tribos dos filhos de Israel.^&#42;1^

[[v73-21-13]]

^<<v73-21-13,13>>^ Ao Oriente havia três portas, ao setentrião três portas, ao sul três portas e ao ocidente três portas.

[[v73-21-14]]

^<<v73-21-14,14>>^ A muralha da cidade tinha doze fundamentos com os nomes dos doze apóstolos do Cordeiro.^&#42;1^

[[v73-21-15]]

^<<v73-21-15,15>>^ Quem falava comigo trazia uma vara de ouro como medida para medir a cidade, as suas portas e a sua muralha.

[[v73-21-16]]

^<<v73-21-16,16>>^ A cidade formava um quadrado: o comprimento igualava à largura. Mediu a cidade com a vara: doze mil estádios. O comprimento, a largura e a altura eram iguais.^&#42;1^

[[v73-21-17]]

^<<v73-21-17,17>>^ E mediu a muralha: cento e quarenta e quatro côvados, segundo a medida humana empregada pelo anjo.

[[v73-21-18]]

^<<v73-21-18,18>>^ O material da muralha era jaspe, e a cidade ouro puro, semelhante a puro cristal.

[[v73-21-19]]

^<<v73-21-19,19>>^ Os alicerces da muralha da cidade eram ornados de toda espécie de pedras preciosas: o primeiro era de jaspe, o segundo de safira, o terceiro de calcedônia, o quarto de esmeralda,

[[v73-21-20]]

^<<v73-21-20,20>>^ o quinto de sardônica, o sexto de cornalina, o sétimo de crisólito, o oitavo de berilo, o nono de topázio, o décimo de crisóparo, o undécimo de jacinto e o duodécimo de ametista.

[[v73-21-21]]

^<<v73-21-21,21>>^ Cada uma das doze portas era feita de uma só pérola e a avenida da cidade era de ouro, transparente como cristal.

[[v73-21-22]]

^<<v73-21-22,22>>^ Não vi nela, porém, templo algum, porque o Senhor, Deus Dominador, é o seu templo, assim como o Cordeiro.

[[v73-21-23]]

^<<v73-21-23,23>>^ A cidade não necessita de sol nem de lua para iluminar, porque a glória de Deus a ilumina, e a sua luz é o Cordeiro.

[[v73-21-24]]

^<<v73-21-24,24>>^ As nações andarão à sua luz, e os reis da terra levarão a ela a sua opulência.

[[v73-21-25]]

^<<v73-21-25,25>>^ As suas portas não se fecharão diariamente, pois não haverá noite.

[[v73-21-26]]

^<<v73-21-26,26>>^ Levarão a ela opulência e a honra das nações.

[[v73-21-27]]

^<<v73-21-27,27>>^ Nela não entrará nada de profano nem ninguém que pratique abominações e mentiras, mas unicamente aqueles cujos nomes estão inscritos no livro da vida do Cordeiro.

'''

xref:073-apocalipse/073-apocalipse-020.adoc#v73-20-0[&#60; Capítulo Anterior] | <<v73-21-0,Topo>> | xref:073-apocalipse/073-apocalipse-022.adoc#v73-22-0[Próximo Capítulo &#62;]