include::./index.adoc[]

[[v22-13-0]]
=== I Macabeus, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 13 de 1 Macabeus continua a narrativa da guerra entre Judas Macabeu e os inimigos do povo de Israel. Neste capítulo, Judas lidera uma batalha contra as tropas do rei Antíoco e é bem sucedido em derrotá-las. A seguir estão cinco versículos relacionados com os temas abordados em 1 Macabeus 13:
* 2 Macabeus 15:22-23: "Estando todos assim alegres, passaram a noite no campo. E no dia seguinte, já próximo do meio-dia, marcharam para a fortaleza." Estes versículos mostram a alegria do povo de Israel após a vitória de Judas e a continuação da batalha contra o inimigo.
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Este versículo mostra a confiança que Judas tinha em Deus e como ele confiava em sua ajuda para vencer seus inimigos.
* 2 Samuel 22:33: "Deus é a minha fortaleza e a minha força, e ele perfeitamente desembaraça o meu caminho." Este versículo também mostra a confiança que Judas tinha em Deus e como ele acreditava que Deus o ajudaria em seus conflitos.
* Salmos 144:1: "Bendito seja o Senhor, minha rocha, que ensina as minhas mãos para a peleja e os meus dedos para a guerra." Este versículo mostra como Deus prepara seu povo para a batalha e como Ele é louvado por isso.
* Efésios 6:11: "Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo." Este versículo mostra a importância da preparação espiritual para a batalha e como é importante ter uma armadura forte para lutar contra os inimigos espirituais.
****

[[v22-13-1]]

^<<v22-13-1,1>>^ Simão foi informado de que Trifão havia organizado um poderoso exército para vir à Judeia e devastá-la.

[[v22-13-2]]

^<<v22-13-2,2>>^ Vendo o povo amedrontado e espavorido, subiu a Jerusalém, convocou a população

[[v22-13-3]]

^<<v22-13-3,3>>^ e dirigiu-lhe a palavra nestes termos: “Vós mesmos sabeis bem o que eu, meus irmãos e a casa de meu pai temos feito pelas leis e pelo santuário, assim como as guerras e as dificuldades que temos suportado.

[[v22-13-4]]

^<<v22-13-4,4>>^ Foi assim que meus irmãos foram mortos pela causa de Israel e que fiquei sozinho.

[[v22-13-5]]

^<<v22-13-5,5>>^ Deus me guarde agora de poupar minha vida, quando o inimigo nos oprime, porque não sou melhor que meus irmãos!

[[v22-13-6]]

^<<v22-13-6,6>>^ Por isso, serei o vingador de meu povo, do santuário, de vossas mulheres e vossos filhos, uma vez que todas as nações, por seu ódio, estão coligadas para nos destruir”.

[[v22-13-7]]

^<<v22-13-7,7>>^ A essas palavras, os ânimos inflamaram-se

[[v22-13-8]]

^<<v22-13-8,8>>^ e todos responderam, gritando: “Tu és o nosso chefe em lugar de Judas e de Jônatas, teus irmãos;

[[v22-13-9]]

^<<v22-13-9,9>>^ combate por nós e faremos tudo o que disseres”.

[[v22-13-10]]

^<<v22-13-10,10>>^ Então, Simão reuniu todos os que podiam lutar, apressou-se em terminar os muros de Jerusalém e fortificou o recinto.

[[v22-13-11]]

^<<v22-13-11,11>>^ A Jope enviou Jônatas, filho de Absalão, com consideráveis tropas. Jônatas expulsou seus habitantes e instalou-se na cidade.

[[v22-13-12]]

^<<v22-13-12,12>>^ Todavia, Trifão partiu de Ptolemaida com numeroso exército para invadir a Judeia. Trouxe consigo Jônatas como prisioneiro.

[[v22-13-13]]

^<<v22-13-13,13>>^ Simão, por sua vez, acampou em Adida, em frente à planície.

[[v22-13-14]]

^<<v22-13-14,14>>^ Informado de que Simão havia ocupado o lugar de seu irmão Jônatas e se aprontava para combatê-lo, Trifão enviou-lhe mensageiros, para dizer-lhe:

[[v22-13-15]]

^<<v22-13-15,15>>^ “Guardamos teu irmão por causa do dinheiro que ele deve ao tesouro real, em vista das funções que exercia.

[[v22-13-16]]

^<<v22-13-16,16>>^ Envia, pois, agora, cem talentos de prata e, para que, uma vez livre, não abandone nossa causa, manda também dois de seus filhos como reféns, e nós o deixaremos ir”.

[[v22-13-17]]

^<<v22-13-17,17>>^ Simão percebeu que essas palavras eram falsas, mas mandou buscar o dinheiro e os filhos, com receio de cair na hostilidade do povo, que poderia dizer:

[[v22-13-18]]

^<<v22-13-18,18>>^ “Foi porque eu não mandei o dinheiro e os filhos, que Jônatas morreu”.

[[v22-13-19]]

^<<v22-13-19,19>>^ Remeteu, pois, o dinheiro e os filhos, mas Trifão quebrou a palavra e não libertou Jônatas.

[[v22-13-20]]

^<<v22-13-20,20>>^ Depois, pôs-se ele a caminho para entrar na Judeia e devastá-la, fazendo um rodeio pelo caminho que conduz a Adora, mas Simão se apresentava diante dele em todo lugar por onde passava.

[[v22-13-21]]

^<<v22-13-21,21>>^ Por seu lado, os ocupantes da fortaleza enviaram a Trifão mensageiro pedindo-lhe que se apressasse a ir ter com eles pelo deserto e lhes fornecesse víveres.

[[v22-13-22]]

^<<v22-13-22,22>>^ Trifão aprontou sua cavalaria para partir naquela mesma noite, mas havia ali muita neve e ele não pôde encetar o caminho. Partiu, todavia, e foi à região de Galaad.

[[v22-13-23]]

^<<v22-13-23,23>>^ Quando chegou perto de Bascama, matou Jônatas e o sepultou;

[[v22-13-24]]

^<<v22-13-24,24>>^ em seguida, retrocedeu e voltou à sua terra.

[[v22-13-25]]

^<<v22-13-25,25>>^ Simão mandou recolher os restos de seu irmão Jônatas e os sepultou em Modin, cidade de seus pais.

[[v22-13-26]]

^<<v22-13-26,26>>^ E todo o Israel chorou abundantemente e conservou o luto durante muitos dias.

[[v22-13-27]]

^<<v22-13-27,27>>^ Sobre o túmulo de seu pai e de seus irmãos, Simão edificou um monumento grandioso com pedras polidas, na frente e por trás.

[[v22-13-28]]

^<<v22-13-28,28>>^ Ergueu ali sete pirâmides, uma diante da outra, para seu pai, sua mãe e seus quatro irmãos.^&#42;1^

[[v22-13-29]]

^<<v22-13-29,29>>^ Colocou nelas ornamentos e cercou-as com altas colunas, sobre as quais, para eterna lembrança, colocou muitas armas e, junto a estas, navios esculpidos, que podiam ser vistos por todos os que se achavam no mar.

[[v22-13-30]]

^<<v22-13-30,30>>^ Tal foi a sepultura que ele construiu em Modin e que existe ainda hoje.

[[v22-13-31]]

^<<v22-13-31,31>>^ Trifão, que servia o jovem rei Antíoco, com duplicidade, mandou assassiná-lo,

[[v22-13-32]]

^<<v22-13-32,32>>^ reinou em seu lugar e usurpou o diadema da Ásia. Ele causou muito mal ao país.^&#42;1^

[[v22-13-33]]

^<<v22-13-33,33>>^ Simão reergueu as fortalezas da Judeia, muniu-as com torres altas, com grandes muros e portas. E ferrolhos e as abasteceu com víveres.

[[v22-13-34]]

^<<v22-13-34,34>>^ Escolheu mensageiros e enviou-os ao rei Demétrio, pedindo-lhe que restabelecesse o país porque Trifão o havia submetido inteiramente à pilhagem.

[[v22-13-35]]

^<<v22-13-35,35>>^ O rei Demétrio mandou-lhe sua resposta e escreveu-lhe nestes termos:

[[v22-13-36]]

^<<v22-13-36,36>>^ “O rei Demétrio a Simão, sumo sacerdote e amigo dos reis, aos anciãos e ao povo judeu, saudações!

[[v22-13-37]]

^<<v22-13-37,37>>^ Recebemos a coroa de ouro e a palma que nos enviastes, e estamos dispostos a concluir convosco uma paz sólida, bem como a escrever aos funcionários que vos dispensem dos impostos.

[[v22-13-38]]

^<<v22-13-38,38>>^ Tudo o que foi decidido a vosso favor está confirmado e as fortalezas que construístes são vossas.

[[v22-13-39]]

^<<v22-13-39,39>>^ Nós vos perdoamos todos os erros e as faltas cometidas até o dia de hoje. Renunciamos à coroa que nos devíeis e, se existem ainda em Jerusalém outras dívidas a pagar, não se paguem mais.

[[v22-13-40]]

^<<v22-13-40,40>>^ Finalmente, se existem entre vós alguns que sejam aptos a se alistarem em nossa guarda, que eles o sejam e que a paz reine entre nós”.

[[v22-13-41]]

^<<v22-13-41,41>>^ Foi no ano cento e setenta que o jugo dos pagãos foi afastado de Israel.^&#42;1^

[[v22-13-42]]

^<<v22-13-42,42>>^ O povo começou a datar os atos e os contratos do primeiro ano de Simão, sumo sacerdote, chefe do exército e governador dos judeus.

[[v22-13-43]]

^<<v22-13-43,43>>^ Nessa época, Simão marchou contra Gazara e cercou-a com suas tropas. Construiu uma torre móvel, levou-a para perto da cidade, atacou uma das torres e apoderou-se dela.

[[v22-13-44]]

^<<v22-13-44,44>>^ Da torre móvel os soldados lançaram-se na cidade, causando ali uma grande confusão,

[[v22-13-45]]

^<<v22-13-45,45>>^ de modo que os habitantes, com suas mulheres e filhos, apareceram sobre os muros, rasgaram suas vestes e pediram com altos brados a Simão que os poupasse.

[[v22-13-46]]

^<<v22-13-46,46>>^ “Não nos trates conforme nossas maldades – diziam eles –, mas segundo a tua misericórdia.”

[[v22-13-47]]

^<<v22-13-47,47>>^ Simão perdoou-os e não prosseguiu o ataque. Não obstante, expulsou-os da cidade e mandou purificar todas as casas onde se achavam os ídolos. Em seguida, fez sua entrada triunfal ao som de hinos e de cânticos de louvor.

[[v22-13-48]]

^<<v22-13-48,48>>^ Fez desaparecer dali toda impureza e trouxe de volta os habitantes fiéis à Lei. Fortificou-a e construiu para si mesmo uma morada.

[[v22-13-49]]

^<<v22-13-49,49>>^ Os ocupantes da fortaleza de Jerusalém, que não podiam sair para ir à cidade comprar e vender, achavam-se numa grande miséria e um bom número deles morreu de fome.

[[v22-13-50]]

^<<v22-13-50,50>>^ Suplicaram a Simão para que lhes concedesse a paz. Ele a concedeu, mas os expulsou de lá e purificou a fortaleza de todas as suas contaminações.

[[v22-13-51]]

^<<v22-13-51,51>>^ E entrou nela no dia vinte e três do segundo mês, do ano cento e setenta e um, com cânticos e palmas, harpas, címbalos, liras, hinos e louvores, porque um grande inimigo de Israel tinha sido aniquilado.

[[v22-13-52]]

^<<v22-13-52,52>>^ Ordenou também que esse dia fosse celebrado a cada ano com regozijo.

[[v22-13-53]]

^<<v22-13-53,53>>^ Fortificou a montanha do templo, na parte próxima à fortaleza, e habitou ali com os seus companheiros.

[[v22-13-54]]

^<<v22-13-54,54>>^ Em seguida, verificando que seu filho João se tornara um homem, confiou-lhe o comando de todas as tropas. E João foi residir em Gazara.

'''

xref:022-i-macabeus/022-i-macabeus-012.adoc#v22-12-0[&#60; Capítulo Anterior] | <<v22-13-0,Topo>> | xref:022-i-macabeus/022-i-macabeus-014.adoc#v22-14-0[Próximo Capítulo &#62;]