include::./index.adoc[]

[[v6-8-0]]
=== Josué, 8
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 8 de Josué descreve a conquista da cidade de Ai pelos israelitas. Josué recebeu instruções de Deus sobre como atacar a cidade e, depois de uma emboscada bem-sucedida, Ai foi tomada pelos israelitas. Em seguida, Josué construiu um altar e fez sacrifícios ao Senhor. Aqui estão cinco versículos relacionados aos temas abordados em Josué 8:
* Deuteronômio 7:2: "E, quando o Senhor teu Deus tos tiver entregue, e os ferires, totalmente os destruirás; não farás com eles aliança, nem terás piedade deles." Este versículo se relaciona com a destruição total de Ai pelos israelitas, cumprindo a ordem de Deus para não fazerem aliança com os habitantes da cidade.
* Deuteronômio 27:5: "E ali edificarás um altar ao Senhor teu Deus, um altar de pedras; não levantarás sobre elas ferro." Este versículo se relaciona com o altar que Josué construiu após a conquista de Ai e como foi feito de acordo com as instruções de Deus.
* Josué 6:18: "Todavia, guardai-vos do anátema; tudo o que for anátema será destruído do meio de Israel; nem no roubo fareis coisa alguma, para que não suceda que façais anátema, e o ponhais no meio da vossa tenda." Este versículo se relaciona com a importância de seguir as instruções de Deus e não se apropriar de nada do que foi considerado anátema, como aconteceu com Acã no capítulo anterior.
* Deuteronômio 20:4: "Porque o Senhor vosso Deus é o que vai convosco, a pelejar por vós contra os vossos inimigos, para vos salvar." Este versículo se relaciona com a presença de Deus ao lado dos israelitas na batalha contra Ai e em todas as suas lutas.
* Josué 4:24: "Para que todos os povos da terra conheçam que a mão do Senhor é forte, e para que vós temais ao Senhor vosso Deus para sempre." Este versículo se relaciona com o propósito maior da conquista de Ai, que era mostrar o poder de Deus aos povos da terra e fazer com que eles temessem o Senhor.
****

[[v6-8-1]]

^<<v6-8-1,1>>^ O Senhor disse em seguida a Josué: “Não temas, nem seja covarde. Toma contigo todos os guerreiros e sobe contra Hai. Eis que te entrego o rei de Hai, seu povo, sua cidade e sua terra.

[[v6-8-2]]

^<<v6-8-2,2>>^ Tratarás Hai e seu rei como fizeste com Jericó e seu rei; mas os despojos e os rebanhos os repartirei entre vós. Põe uma emboscada por detrás da cidade”.

[[v6-8-3]]

^<<v6-8-3,3>>^ Josué pôs-se a caminho com todos os guerreiros contra Hai. Escolheu trinta mil homens valentes e fê-los partir durante a noite.

[[v6-8-4]]

^<<v6-8-4,4>>^ Deu-lhes esta ordem: “Atenção! Ponde-vos em emboscada atrás da cidade, mas a pouca distância, e estai preparados.

[[v6-8-5]]

^<<v6-8-5,5>>^ Eu e todo o povo que está comigo nos aproximaremos de Hai, e quando saírem ao nosso encontro como da primeira vez, fugiremos.

[[v6-8-6]]

^<<v6-8-6,6>>^ Eles sairão atrás de nós, longe da cidade, pois dirão: ‘Ei-los que fogem diante de nós como da primeira vez’.

[[v6-8-7]]

^<<v6-8-7,7>>^ Durante essa retirada, saireis de vossa emboscada e tomareis a cidade, que vos entregará o Senhor, vosso Deus.

[[v6-8-8]]

^<<v6-8-8,8>>^ Depois que a tiverdes tomado, incendiai-a segundo a palavra do Senhor. Essas são as minhas ordens”.

[[v6-8-9]]

^<<v6-8-9,9>>^ Josué fê-los partir e eles se postaram em emboscada entre Betel e Hai, ao ocidente. Josué ficou aquela noite no meio do povo.

[[v6-8-10]]

^<<v6-8-10,10>>^ Josué levantou-se bem cedo e passou em revista a sua gente. À frente de sua tropa, subiu contra Hai com os anciãos de Israel.

[[v6-8-11]]

^<<v6-8-11,11>>^ Todos os guerreiros de que dispunha tinham também subido às proximidades. Chegados defronte da cidade, acamparam ao norte, tendo o vale entre eles e Hai.

[[v6-8-12]]

^<<v6-8-12,12>>^ Josué tomou cerca de cinco mil homens e os pôs de emboscada entre Betel e Hai, ao ocidente.

[[v6-8-13]]

^<<v6-8-13,13>>^ Tendo o povo instalado todo o seu acampamento ao norte da cidade, e a emboscada ao ocidente, Josué avançou durante a noite pelo meio do vale.

[[v6-8-14]]

^<<v6-8-14,14>>^ Logo que o rei de Hai viu aquilo, saiu apressadamente da cidade com a sua gente, ao amanhecer, e veio ao encontro de Israel. O rei, seguido de todo o seu povo, saiu para um lugar combinado do lado da planície, ignorando que uma emboscada estava armada contra ele atrás da cidade.

[[v6-8-15]]

^<<v6-8-15,15>>^ Josué e todo o Israel, fingindo bater em retirada, fugiram para os lados do deserto.

[[v6-8-16]]

^<<v6-8-16,16>>^ Então, com grandes clamores, toda a população da cidade, precipitando-se ao encalço de Josué, juntou-se para persegui-los, afastando-se da cidade.

[[v6-8-17]]

^<<v6-8-17,17>>^ Não ficou um homem sequer em Hai que não saísse em perseguição de Israel. Até deixaram escancarada a cidade.

[[v6-8-18]]

^<<v6-8-18,18>>^ O Senhor disse então a Josué: “Levanta a lança que tens na mão contra Hai, porque eu entrego a ti”. E Josué levantou a sua lança contra a cidade.

[[v6-8-19]]

^<<v6-8-19,19>>^ Apenas tinha ele erguido a mão, levantaram-se subitamente os que estavam de emboscada e precipitaram-se sobre a cidade, ocupando-a e ateando-lhe fogo.

[[v6-8-20]]

^<<v6-8-20,20>>^ Os habitantes de Hai, voltando-se, viram que se elevava da cidade uma grande fumaça para o céu, e não puderam fugir para lado algum, porque o povo que dava mostras de fugir para o deserto voltou-se contra eles.

[[v6-8-21]]

^<<v6-8-21,21>>^ Josué e todo o Israel, vendo que os da emboscada tinham tomado a cidade e que dela subia fumaça, voltaram e feriram os habitantes de Hai.

[[v6-8-22]]

^<<v6-8-22,22>>^ E, tendo os outros saído da cidade ao seu encontro, viram-se os inimigos cercados de um lado e de outro pelos israelitas, e foram feridos, de modo que não ficou sobrevivente algum, e não houve sequer um fugitivo.

[[v6-8-23]]

^<<v6-8-23,23>>^ O rei de Hai foi capturado vivo e conduzido a Josué.

[[v6-8-24]]

^<<v6-8-24,24>>^ Terminado o massacre dos habitantes de Hai, tanto no campo como no deserto, aonde tinham vindo em perseguição dos israelitas, depois que todos foram passados a fio da espada, os vencedores voltaram à cidade e mataram toda a população.

[[v6-8-25]]

^<<v6-8-25,25>>^ O total dos que morreram naquele dia, entre homens e mulheres, foi de doze mil, todos da cidade de Hai.

[[v6-8-26]]

^<<v6-8-26,26>>^ Josué não retirou a mão que ele tinha levantado com a sua lança, até que foram mortos todos os habitantes de Hai.

[[v6-8-27]]

^<<v6-8-27,27>>^ Os israelitas só tomaram os rebanhos e o espólio da cidade, conforme o Senhor tinha ordenado a Josué.

[[v6-8-28]]

^<<v6-8-28,28>>^ Josué pôs fogo à cidade de Hai e fez dela para sempre um montão de cinzas, que subsiste ainda hoje.

[[v6-8-29]]

^<<v6-8-29,29>>^ Mandou enforcar o rei de Hai em uma árvore, e deixou-o ali até à tarde. Ao pôr do sol, ordenou que se retirasse da árvore o cadáver e fosse lançado à entrada da cidade, pondo sobre ele um grande monte de pedras, que ali permanece até o dia de hoje.

[[v6-8-30]]

^<<v6-8-30,30>>^ Então Josué construiu um altar ao Senhor, Deus de Israel, no monte Ebal,

[[v6-8-31]]

^<<v6-8-31,31>>^ segundo a ordem que Moisés, servo do Senhor, tinha dado aos filhos de Israel, como está escrito no livro da Lei de Moisés. Construiu-o de pedras brutas ainda não tocadas pelo ferro. Ofereceram sobre ele holocaustos ao Senhor e sacrifícios de ação de graças.

[[v6-8-32]]

^<<v6-8-32,32>>^ Josué gravou em pedras uma cópia da lei que Moisés tinha escrito diante dos israelitas.

[[v6-8-33]]

^<<v6-8-33,33>>^ Todo o Israel, seus anciãos, seus oficiais e seus juízes conservaram-se de pé ao redor da arca, diante dos sacerdotes, dos levitas, que levavam a arca da aliança do Senhor. Ali estavam tanto os estrangeiros como os israelitas, metade deles do lado do monte Garizim, e metade do lado do monte Ebal, segundo a ordem antes dada por Moisés, servo do Senhor, para abençoar o povo de Israel.

[[v6-8-34]]

^<<v6-8-34,34>>^ Depois disso, Josué leu todo o texto da lei, a bênção e a maldição, assim como estão escritas no livro da Lei.

[[v6-8-35]]

^<<v6-8-35,35>>^ De tudo o que Moisés havia prescrito não se omitiu uma palavra sequer nessa leitura feita por Josué diante de toda a assembleia de Israel, incluindo as mulheres, as crianças e os estrangeiros que ali se achavam misturados.

'''

xref:006-josue/006-josue-007.adoc#v6-7-0[&#60; Capítulo Anterior] | <<v6-8-0,Topo>> | xref:006-josue/006-josue-009.adoc#v6-9-0[Próximo Capítulo &#62;]