include::./index.adoc[]

[[v6-2-0]]
=== Josué, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 2 do livro de Josué conta a história de como os espiões israelitas foram enviados a Jericó e encontraram refúgio na casa de Raabe, uma prostituta. Raabe escondeu os espiões dos soldados do rei de Jericó e fez um acordo com eles para poupar a vida dela e de sua família quando os israelitas atacassem a cidade. Os temas abordados nesse capítulo incluem a coragem de Raabe, a espionagem como estratégia militar e a importância da fidelidade a Deus.
* Provérbios 11:3: "A integridade dos justos os guia, mas a falsidade dos infiéis os destrói." Raabe demonstrou integridade ao proteger os espiões israelitas e fazer um acordo com eles, enquanto o rei de Jericó e seus soldados eram infiéis e buscavam destruí-los.
* Hebreus 11:31: "Pela fé, Raabe, a prostituta, não foi destruída com os que foram desobedientes, pois acolheu com paz os espiões." Raabe demonstrou fé em Deus ao proteger os espiões e fazer um acordo com eles, e sua fé foi recompensada quando ela e sua família foram poupados da destruição de Jericó.
* Tiago 2:25: "Do mesmo modo, não foi somente por meio de obras que Raabe, a prostituta, foi considerada justa? Ela acolheu os espiões e os fez sair por outro caminho." Raabe foi considerada justa não apenas por causa de sua fé, mas também por suas ações em acolher e proteger os espiões.
* Josué 2:9: "Eu sei que o Senhor entregou esta terra a vocês e que o medo de vocês caiu sobre nós, e que todos os habitantes desta terra desfalecem de medo diante de vocês." Raabe reconheceu a autoridade e o poder de Deus e reconheceu que os israelitas eram destinados a conquistar a terra.
* Josué 2:24: "Responderam os espiões a Josué: O Senhor entregou toda a terra em nossas mãos; e até todos os habitantes do país estão apavorados diante de nós." Os espiões confirmaram a crença de Raabe de que Deus estava do lado dos israelitas e que eles tinham a autoridade divina para conquistar a terra de Canaã.
****

[[v6-2-1]]

^<<v6-2-1,1>>^ Josué, filho de Nun, despachou de Setim secretamente dois espiões: “Ide –, disse-lhes ele – e examinai a terra e a cidade de Jericó”. Foram e entraram na casa de uma prostituta, chamada Raab, onde se alojaram.

[[v6-2-2]]

^<<v6-2-2,2>>^ E foi avisado ao rei de Jericó: “Entraram aqui de noite alguns israelitas para explorar a terra”.

[[v6-2-3]]

^<<v6-2-3,3>>^ O rei mandou dizer a Raab: “Faze sair esses homens que foram ter contigo e entraram em tua casa; porque vieram espionar a terra”.

[[v6-2-4]]

^<<v6-2-4,4>>^ Mas a mulher ocultou os dois homens e respondeu: “Vieram realmente uns homens à minha casa, mas eu não sabia de onde eram.

[[v6-2-5]]

^<<v6-2-5,5>>^ Pela tarde, quando se iam fechar as portas da cidade, eles partiram. Ignoro para onde foram. Persegui-os vós depressa e os alcançareis”.

[[v6-2-6]]

^<<v6-2-6,6>>^ Ora, ela os fizera subir ao terraço de sua casa e os ocultara sob palhas de linho que ali haviam.

[[v6-2-7]]

^<<v6-2-7,7>>^ Os homens enviados foram atrás deles pelo caminho, que conduz ao vau do Jordão, e as portas da cidade foram fechadas após a partida da patrulha.

[[v6-2-8]]

^<<v6-2-8,8>>^ Antes que se deitassem, Raab subiu ao terraço junto dos espiões e disse-lhes:

[[v6-2-9]]

^<<v6-2-9,9>>^ “Eu sei que o Senhor vos entregou esta terra; o terror de vós apoderou-se de nós, e todos os habitantes da terra estão desanimados por vossa causa.

[[v6-2-10]]

^<<v6-2-10,10>>^ Ouvimos dizer como o Senhor secou as águas do mar Vermelho diante de vós, quando saístes do Egito, e como, além do Jordão, tratastes os dois reis dos amorreus, Seon e Og, os quais votastes ao interdito.

[[v6-2-11]]

^<<v6-2-11,11>>^ Quando ouvimos isso, nosso coração desfaleceu e ninguém mais tem coragem de vos resistir, porque o Senhor, vosso Deus, é o Deus nas alturas dos céus e aqui embaixo na terra.

[[v6-2-12]]

^<<v6-2-12,12>>^ Agora, vo-lo peço, jurai-me pelo Senhor, que, assim como usei de bondade para convosco, do mesmo modo poupareis a casa de meu pai.

[[v6-2-13]]

^<<v6-2-13,13>>^ Dai-me um sinal seguro de que salvareis meu pai, minha mãe, meus irmãos, minhas irmãs e todos os que lhe pertencem e livrareis as nossas vidas da morte”.

[[v6-2-14]]

^<<v6-2-14,14>>^ Eles responderam-lhe: “À custa de nossa vida salvaremos a vossa, contanto que não nos atraiçoeis. Quando o Senhor nos entregar esta terra, fiéis à nossa promessa agiremos contigo com bondade”.

[[v6-2-15]]

^<<v6-2-15,15>>^ Então, servindo-se de uma corda, ela os fez descer pela janela, pois a casa em que morava estava sobre o muro da cidade.

[[v6-2-16]]

^<<v6-2-16,16>>^ “Ide para o monte – disse-lhes ela – para que não vos encontrem os vossos perseguidores. Ocultai-vos ali durante três dias, até que eles voltem; depois retomareis o vosso caminho.”

[[v6-2-17]]

^<<v6-2-17,17>>^ Os homens disseram-lhe: “Eis como havemos de cumprir o juramento a que nos obrigastes:

[[v6-2-18]]

^<<v6-2-18,18>>^ quando tivermos entrado na terra, porás este cordão vermelho na janela por onde nos fizeste descer; reúne em torno de ti, em tua casa, teu pai, tua mãe, teus irmãos e toda a família de teu pai.

[[v6-2-19]]

^<<v6-2-19,19>>^ Se alguém ultrapassar a porta de tua casa e sair para fora, este será responsável pelo que acontecer, e nós seremos inocentes. Mas se alguém puser a mão sobre quem quer que seja que se encontrar contigo em tua casa, é sobre nós que isso cairá.^&#42;1^

[[v6-2-20]]

^<<v6-2-20,20>>^ Se divulgares, porém, o que combinamos contigo, estaremos desobrigados do juramento a que nos obrigaste”.

[[v6-2-21]]

^<<v6-2-21,21>>^ “Seja como dissestes” – respondeu ela. Depois os despediu, e eles partiram. E ela pendurou o cordão vermelho na janela.

[[v6-2-22]]

^<<v6-2-22,22>>^ Eles foram para o monte, onde permaneceram durante três dias, até que voltassem os que os perseguiam. Esses, tendo buscado por todo o caminho os espiões, não os encontraram.

[[v6-2-23]]

^<<v6-2-23,23>>^ Os dois homens desceram então do monte e, voltando, passaram o Jordão. Foram para junto de Josué, filho de Nun, e contaram-lhe tudo o que se tinha passado.

[[v6-2-24]]

^<<v6-2-24,24>>^ “O Senhor – disseram-lhe eles – entregou toda essa terra nas nossas mãos, pois todos os seus habitantes tremem diante de nós.”

'''

xref:006-josue/006-josue-001.adoc#v6-1-0[&#60; Capítulo Anterior] | <<v6-2-0,Topo>> | xref:006-josue/006-josue-003.adoc#v6-3-0[Próximo Capítulo &#62;]