include::./index.adoc[]

[[v6-11-0]]
=== Josué, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 11 de Josué relata a conquista de várias cidades cananitas pelo exército de Israel, liderado por Josué. Os reis dessas cidades uniram suas forças para resistir à invasão de Israel, mas foram derrotados e seus territórios foram conquistados. Abaixo estão cinco versículos relacionados com os temas abordados em Josué 11.
* Salmos 24:1: "Do Senhor é a terra e a sua plenitude, o mundo e aqueles que nele habitam." Esse versículo fala da soberania de Deus sobre todas as coisas, incluindo a terra e seus habitantes. A conquista de Canaã pelos israelitas foi um cumprimento da vontade de Deus.
* Deuteronômio 7:2: "E quando o Senhor, teu Deus, os entregar diante de ti, então, lhes ferirás e destruirás totalmente; não farás aliança com eles, nem lhes terás piedade." Esse versículo fala da ordem de Deus para que os israelitas destruíssem completamente os cananitas e não fizessem aliança com eles. Essa ordem foi cumprida na conquista de Canaã por Josué e seu exército.
* Salmos 44:3: "Pois não pela sua espada conquistaram a terra, nem o seu braço os salvou, mas foi a tua direita, o teu braço e a luz da tua face, porque te agradaste deles." Esse versículo fala da dependência dos israelitas em Deus para conquistar a terra de Canaã. Foi pela vontade de Deus e sua intervenção que Josué e seu exército conseguiram derrotar os cananitas.
* Salmos 121:8: "O Senhor guardará a tua saída e a tua entrada, desde agora e para sempre." Esse versículo fala da proteção de Deus sobre aqueles que confiam nele. Josué e seu exército contaram com a proteção de Deus durante a conquista de Canaã.
* 2 Samuel 22:47: "Viva o Senhor, e bendita seja a minha rocha, e exaltado seja o Deus da minha salvação." Esse versículo fala da adoração e gratidão a Deus pela sua salvação. Os israelitas puderam adorar e agradecer a Deus pela vitória na conquista de Canaã.
****

[[v6-11-1]]

^<<v6-11-1,1>>^ Jabin, rei de Asor, tendo notícias de todos esses acontecimentos, enviou mensageiro a Jobab, rei de Merom, ao rei de Semeron, ao rei de Acsaf,

[[v6-11-2]]

^<<v6-11-2,2>>^ aos reis do norte da montanha e da planície, ao sul de Genesaré, na planície e nos planaltos de Dora, ao ocidente,

[[v6-11-3]]

^<<v6-11-3,3>>^ aos cananeus do oriente e do ocidente, aos amorreus, aos hiteus, aos ferezeus, aos jebuseus na montanha, aos heveus ao pé do Hermon na terra de Masfa.

[[v6-11-4]]

^<<v6-11-4,4>>^ Entraram então em campanha com todos os seus exércitos, povo numeroso como a areia na praia do mar, com sua cavalaria e grande número de carros.

[[v6-11-5]]

^<<v6-11-5,5>>^ Todos esses reis juntaram-se e vieram acampar juntos, perto das águas de Merom, para combater Israel.

[[v6-11-6]]

^<<v6-11-6,6>>^ O Senhor disse a Josué: “Não os temas, porque amanhã, a esta mesma hora, eu os lançarei, ofegantes, diante de Israel. Cortarás os jarretes dos seus cavalos e queimarás os seus carros”.

[[v6-11-7]]

^<<v6-11-7,7>>^ Josué atacou-os repentinamente, com todos os seus guerreiros, junto às águas de Merom e precipitou-se contra eles.

[[v6-11-8]]

^<<v6-11-8,8>>^ O Senhor entregou-os nas mãos de Israel, que os bateu e os perseguiu até Sidon, a Grande, até as águas de Maserefot e até o vale de Masfa, para o oriente. E feriu-os até que não ficou um só.

[[v6-11-9]]

^<<v6-11-9,9>>^ Josué tratou-os como o Senhor lhe tinha dito: cortou os tendões dos cavalos e incendiou seus carros.

[[v6-11-10]]

^<<v6-11-10,10>>^ Voltando, nessa mesma época, Josué tomou Asor e matou à espada seu rei, porque Asor era antigamente a capital de todos esses reinos.

[[v6-11-11]]

^<<v6-11-11,11>>^ Passaram a fio da espada toda alma viva nessa cidade e votaram-na ao interdito. Nada ficou de tudo o que tinha vida e incendiou Asor.

[[v6-11-12]]

^<<v6-11-12,12>>^ Tomou também Josué todas as cidades desses reis (coligados) e passou-as a fio da espada, votando-as ao interdito, como Moisés, servo do Senhor, tinha ordenado.

[[v6-11-13]]

^<<v6-11-13,13>>^ Entretanto, Israel não incendiou nenhuma das cidades situadas nas colinas, exceto Asor, que Josué queimou.

[[v6-11-14]]

^<<v6-11-14,14>>^ Os filhos de Israel apossaram-se de todos os despojos dessas cidades e dos rebanhos. Quanto aos homens, porém, massacraram-nos todos com a espada, até exterminá-los completamente sem deixar ninguém com vida.

[[v6-11-15]]

^<<v6-11-15,15>>^ Como o Senhor tinha ordenado a Moisés, seu servo, assim Moisés ordenou a Josué; e este tudo executou, sem nada omitir do que o Senhor tinha prescrito a Moisés.

[[v6-11-16]]

^<<v6-11-16,16>>^ Conquistou, assim, Josué toda a terra, a montanha, o Negueb, o território de Gósen, a campina e a planície, o planalto de Israel e suas campinas,

[[v6-11-17]]

^<<v6-11-17,17>>^ desde a montanha nua que sobe para Seir até Baal-Gad, no vale do Líbano, ao pé do Hermon. Tomou todos os seus reis, feriu-os e matou-os.

[[v6-11-18]]

^<<v6-11-18,18>>^ Durante muito tempo combateu Josué contra esses reis.

[[v6-11-19]]

^<<v6-11-19,19>>^ Não houve cidade que se rendesse pacificamente aos israelitas, exceto os heveus de Gabaon. Foi necessário que se tomasse tudo à força,

[[v6-11-20]]

^<<v6-11-20,20>>^ porque era o desígnio do Senhor que se endurecesse o coração desses povos e que combatessem Israel; desse modo, Israel pôde votá-los ao interdito sem piedade e exterminá-los, como o Senhor tinha ordenado a Moisés.

[[v6-11-21]]

^<<v6-11-21,21>>^ Naquele tempo, Josué marchou contra os enacim da montanha e os exterminou em Hebron, em Dabir, em Anab e em toda a montanha de Judá e de Israel. E votou-os ao interdito com suas cidades.

[[v6-11-22]]

^<<v6-11-22,22>>^ Não ficou um só enacim na terra dos filhos de Israel; só ficaram alguns em Gaza, em Gat e em Azoto.

[[v6-11-23]]

^<<v6-11-23,23>>^ Conquistou, pois, Josué toda a terra, como o Senhor tinha dito a Moisés, e deu-a em herança a Israel, repartindo-a segundo suas tribos. E a terra repousou da guerra.

'''

xref:006-josue/006-josue-010.adoc#v6-10-0[&#60; Capítulo Anterior] | <<v6-11-0,Topo>> | xref:006-josue/006-josue-012.adoc#v6-12-0[Próximo Capítulo &#62;]