include::./index.adoc[]

[[v6-24-0]]
=== Josué, 24
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 24 de Josué trata da renovação da aliança entre Deus e Israel. Josué reúne todas as tribos de Israel em Siquém e, após relembrar a fidelidade de Deus ao povo ao longo da história, ele pede que o povo escolha a quem servir. O povo responde que escolherá servir a Deus. Abaixo estão cinco versículos relacionados com os temas abordados em Josué 24:
* Gênesis 24:27: "Eu, Abraão, servo do SENHOR, recebi instruções do SENHOR para escolher uma esposa para o filho do meu senhor." Neste versículo, Abraão faz referência à aliança que Deus fez com ele e prometeu abençoar sua descendência. A escolha da esposa para Isaque foi um cumprimento dessa promessa e demonstrou a fidelidade de Deus.
* Êxodo 20:2: "Eu sou o SENHOR, seu Deus, que os tirei da terra do Egito, da casa da escravidão." O início dos Dez Mandamentos estabelece a autoridade de Deus como o libertador de Israel. A fidelidade de Deus ao libertar seu povo do Egito é o fundamento da aliança entre Deus e Israel.
* Deuteronômio 10:12: "E agora, Israel, o que o SENHOR, seu Deus, exige de você, senão que tema o SENHOR, seu Deus, ande em todos os seus caminhos, ame-o e sirva ao SENHOR, seu Deus, com todo o seu coração e com toda a sua alma?" Moisés reitera a importância de servir a Deus com todo o coração e obediência total. Esse versículo reflete a escolha que o povo de Israel faz em Josué 24.
* 2 Reis 17:38: "Não se esqueçam da aliança que fiz com vocês e não adorem outros deuses." Esse versículo é um lembrete para a importância da fidelidade à aliança com Deus. Adorar outros deuses é uma traição à aliança.
* Salmos 119:106: "Juro, e cumprirei, em observar seus justos decretos." O salmista declara sua intenção de obedecer aos mandamentos de Deus. A escolha do povo de Israel de servir a Deus em Josué 24 é uma declaração semelhante de compromisso e obediência.
****

[[v6-24-1]]

^<<v6-24-1,1>>^ Josué convocou a Siquém todas as tribos de Israel, seus anciãos, seus chefes, seus juízes e seus oficiais. Eles apresentaram-se diante de Deus,

[[v6-24-2]]

^<<v6-24-2,2>>^ e Josué disse a todo o povo: “Eis o que diz o Senhor, Deus de Israel: Outrora, vossos ancestrais, Taré, pai de Abraão e de Nacor, habitavam além do rio e serviam a deuses estrangeiros.^&#42;1^

[[v6-24-3]]

^<<v6-24-3,3>>^ Tomei vosso pai Abraão do outro lado do Jordão e conduzi-o à terra de Canaã. Multipliquei sua descendência e dei-lhe Isaac,

[[v6-24-4]]

^<<v6-24-4,4>>^ ao qual dei Jacó e Esaú, e dei a este último a montanha de Seir; Jacó, porém, e seus filhos desceram ao Egito.

[[v6-24-5]]

^<<v6-24-5,5>>^ Depois mandei Moisés e Aarão e feri o Egito com tudo o que fiz no meio dele; e, em seguida, vos tirei de lá.

[[v6-24-6]]

^<<v6-24-6,6>>^ Fiz sair vossos pais do Egito e, quando chegastes ao mar, os egípcios perseguiram vossos pais com carros e cavaleiros até o mar Vermelho.

[[v6-24-7]]

^<<v6-24-7,7>>^ Os israelitas clamaram ao Senhor, o qual pôs trevas entre vós e os egípcios, e fez vir o mar sobre eles, cobrindo-os. Vistes com os vossos olhos o que fiz aos egípcios, e depois disso habitastes muito tempo no deserto.

[[v6-24-8]]

^<<v6-24-8,8>>^ Conduzi-vos em seguida à terra dos amorreus, que habitavam além do Jordão. Eles combateram contra vós, mas eu os entreguei em vossas mãos; tomastes posse de sua terra e eu os exterminei diante de vós.

[[v6-24-9]]

^<<v6-24-9,9>>^ Balac, filho de Sefor, rei de Moab, combateu contra Israel. Mandou chamar Balaão, filho de Beor, para vos amaldiçoar.

[[v6-24-10]]

^<<v6-24-10,10>>^ Mas eu não quis ouvir Balaão, e ele teve de vos abençoar; e tirei-vos da mão de Balac.

[[v6-24-11]]

^<<v6-24-11,11>>^ Passastes o Jordão e chegastes a Jericó. Combateram contra vós os homens dessa cidade, bem como os amorreus, os ferezeus, os cananeus, os hiteus, os gergeseus, os heveus e os jebuseus, e eu os entreguei todos nas vossas mãos.

[[v6-24-12]]

^<<v6-24-12,12>>^ Mandei adiante de vós vespas que expulsaram os dois reis dos amorreus, não com a vossa espada, nem com o vosso arco.

[[v6-24-13]]

^<<v6-24-13,13>>^ Desse modo, dei-vos uma terra que não lavrastes, cidades que não construístes, onde agora habitais, vinhas e oliveiras que não plantastes, das quais comeis agora os frutos.

[[v6-24-14]]

^<<v6-24-14,14>>^ Agora, pois, temei o Senhor e servi-o com toda a retidão e fidelidade. Tirai os deuses que serviram vossos pais além do rio e no Egito, e servi o Senhor.

[[v6-24-15]]

^<<v6-24-15,15>>^ Porém, se vos desagrada servir o Senhor, escolhei hoje a quem quereis servir: se aos deuses, a quem serviram os vossos pais além do rio, se aos deuses dos amorreus, em cuja terra habitais. Porque, quanto a mim, eu e minha casa serviremos o Senhor”.

[[v6-24-16]]

^<<v6-24-16,16>>^ O povo respondeu: “Longe de nós abandonarmos o Senhor para servir outros deuses.

[[v6-24-17]]

^<<v6-24-17,17>>^ O Senhor é o nosso Deus, ele que nos tirou, a nós e a nossos pais, da terra do Egito, da casa da servidão; e que operou à nossa vista maravilhosos prodígios e guardou-nos ao longo de todo o caminho que percorremos, entre todos os povos pelos quais passamos.

[[v6-24-18]]

^<<v6-24-18,18>>^ O Senhor expulsou diante de nós todas essas nações, assim como os amorreus que habitam na terra. Nós também, nós serviremos o Senhor, porque ele é o nosso Deus”.

[[v6-24-19]]

^<<v6-24-19,19>>^ Josué disse ao povo: “Vós não podereis servir o Senhor, porque ele é um Deus santo, um Deus zeloso que não perdoará as vossas rebeliões e os vossos pecados.

[[v6-24-20]]

^<<v6-24-20,20>>^ Se abandonardes o Senhor para servir outros deuses, ele se voltará contra vós e vos fará mal, e vos consumirá, depois de vos ter feito bem”.

[[v6-24-21]]

^<<v6-24-21,21>>^ “Não – clamou o povo – porque é ao Senhor que nós queremos servir!”

[[v6-24-22]]

^<<v6-24-22,22>>^ Josué disse-lhes: “Sois testemunhas contra vós mesmos de que escolhestes o Senhor para prestar-lhe culto”. “Somos testemunhas – responderam eles –.

[[v6-24-23]]

^<<v6-24-23,23>>^ “Agora, pois, tirai os deuses estranhos que estão no meio de vós e inclinai os vossos corações para o Senhor, Deus de Israel.”

[[v6-24-24]]

^<<v6-24-24,24>>^ “Nós serviremos o Senhor, nosso Deus –, respondeu o povo a Josué –, e obedeceremos à sua voz.”

[[v6-24-25]]

^<<v6-24-25,25>>^ Desse modo, Josué fez um pacto naquele dia com o povo e deu-lhe, em Siquém, leis e prescrições.

[[v6-24-26]]

^<<v6-24-26,26>>^ Josué escreveu tudo isso no livro da Lei de Deus, tomou em seguida uma pedra muito grande e erigiu-a ali, debaixo do carvalho que estava no santuário do Senhor.

[[v6-24-27]]

^<<v6-24-27,27>>^ E disse a todo o povo: “Esta pedra servirá de testemunho contra nós, porque ela ouviu todas as palavras que o Senhor nos disse; ela servirá de testemunho contra vós, para que não abandoneis o vosso Deus”.

[[v6-24-28]]

^<<v6-24-28,28>>^ Então, Josué despediu o povo, cada um para a sua propriedade.

[[v6-24-29]]

^<<v6-24-29,29>>^ E aconteceu depois disso que Josué, filho de Nun, servo do Senhor, morreu com a idade de cento e dez anos.

[[v6-24-30]]

^<<v6-24-30,30>>^ Sepultaram-no na terra de sua possessão, em Tamnat-Saré, na montanha de Efraim, ao norte do monte Gaás.

[[v6-24-31]]

^<<v6-24-31,31>>^ Durante todo o tempo da vida de Josué, Israel serviu o Senhor, bem como enquanto viveram depois dele os anciãos que conheciam tudo o que o Senhor tinha feito em favor de Israel.

[[v6-24-32]]

^<<v6-24-32,32>>^ Sepultaram também em Siquém os ossos de José que os israelitas tinham trazido do Egito; depuseram-nos na porção da terra que Jacó havia comprado aos filhos de Hemor, pai de Siquém, por cem peças de prata, e que se tornou propriedade dos filhos de José.

[[v6-24-33]]

^<<v6-24-33,33>>^ Eleazar, filho de Aarão, morreu também. Enterraram-no em Gabaá, cidade de Fineias, seu filho, que lhe tinha sido dada na montanha de Efraim.

'''

xref:006-josue/006-josue-023.adoc#v6-23-0[&#60; Capítulo Anterior] | <<v6-24-0,Topo>> | xref:007-juizes/007-juizes-001.adoc#v7-1-0[Próximo Capítulo &#62;]