include::./index.adoc[]

[[v6-10-0]]
=== Josué, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 10 de Josué descreve a conquista de várias cidades pelo exército israelita, incluindo a batalha contra os cinco reis amorreus que se uniram para lutar contra Gibeom. Deus ajudou os israelitas a vencer a batalha e até mesmo fez o sol parar no céu para dar-lhes mais tempo para completar a vitória. Aqui estão cinco versículos relacionados aos temas abordados em Josué 10:
* Êxodo 23:28: "E enviarei vespas diante de ti, para que lancem fora os heveus, os cananeus e os heteus de diante de ti." Este versículo se relaciona com a ajuda sobrenatural de Deus na luta contra os inimigos dos israelitas em Canaã.
* Deuteronômio 3:22: "Não os temais, porque o Senhor vosso Deus é o que peleja por vós." Este versículo se relaciona com a confiança dos israelitas na ajuda de Deus durante a batalha contra os cinco reis amorreus.
* Salmos 18:39: "Deste-me também o escudo da tua salvação; a tua mão direita me susteve, e a tua mansidão me engrandeceu." Este versículo se relaciona com a proteção de Deus sobre os israelitas durante a batalha e como Ele os susteve e salvou.
* Isaías 30:29: "Tereis uma canção como na noite em que se celebra uma festa santa; e alegria de coração, como a daquele que vai com flauta, para entrar no monte do Senhor, à Rocha de Israel." Este versículo se relaciona com a celebração dos israelitas depois de sua vitória sobre os inimigos e como eles deram graças e louvor a Deus.
* Salmos 46:10: "Aquietai-vos e sabei que eu sou Deus; serei exaltado entre as nações; serei exaltado sobre a terra." Este versículo se relaciona com a soberania de Deus sobre todas as nações e como Ele é exaltado em Suas obras, como a ajuda que Ele deu aos israelitas durante a batalha.
****

[[v6-10-1]]

^<<v6-10-1,1>>^ Sabendo Adonisedec, rei de Jerusalém, que Josué se tinha apoderado de Hai e a havia votado ao interdito, que fizera a Hai e ao seu rei como tinha feito a Jericó e a seu rei, e que os gabaonitas tinham feito paz com Israel e habitavam com ele,

[[v6-10-2]]

^<<v6-10-2,2>>^ teve grande medo. Gabaon era, com efeito, uma grande cidade, uma cidade real, maior que Hai, e toda a sua população muito guerreira.

[[v6-10-3]]

^<<v6-10-3,3>>^ Adonisedec, rei de Jerusalém, mandou dizer a Hoam, rei de Hebron, a Farão, rei de Jarmut, a Jáfia, rei de Laquis, e a Dabir, rei de Eglon:

[[v6-10-4]]

^<<v6-10-4,4>>^ “Vinde comigo e ajudai-me a ferir Gabaon, porque fez paz com Josué e os israelitas”.

[[v6-10-5]]

^<<v6-10-5,5>>^ Unidos assim os cinco reis dos amorreus, o rei de Jerusalém, o rei de Hebron, o rei de Jarmut, o rei de Laquis e o rei de Eglon, saíram com todos os seus exércitos e acamparam diante de Gabaon, sitiando-a.

[[v6-10-6]]

^<<v6-10-6,6>>^ Os habitantes de Gabaon enviaram então a seguinte mensagem a Josué, que estava acampado em Gálgala: “Não abandones os teus servos; vem ao nosso encontro sem demora, traze-nos socorro e livra-nos, porque todos os reis dos amorreus da montanha se coligaram contra nós”.

[[v6-10-7]]

^<<v6-10-7,7>>^ Josué subiu de Gálgala com todos os seus guerreiros e todos os seus valentes.

[[v6-10-8]]

^<<v6-10-8,8>>^ O Senhor disse-lhe: “Não os temas, porque os entreguei em tuas mãos; nenhum deles te poderá resistir”.

[[v6-10-9]]

^<<v6-10-9,9>>^ Josué, tendo passado toda a noite a subir de Gálgala, caiu de repente sobre eles.

[[v6-10-10]]

^<<v6-10-10,10>>^ O Senhor semeou no meio deles o terror diante de Israel, e este infligiu-lhes uma terrível derrota diante de Gabaon, e perseguiu-os pelo caminho que sobe a Bet-Horon, batendo-os até Azeca e Maceda.

[[v6-10-11]]

^<<v6-10-11,11>>^ Enquanto fugiam diante de Israel, na descida de Bet-Horon, o Senhor mandou sobre eles do céu uma tempestade de granizo até Azeca; e foram mais numerosos os que morreram sob essa chuva de pedras do que os que pereceram pela espada dos israelitas.

[[v6-10-12]]

^<<v6-10-12,12>>^ Josué falou ao Senhor no dia em que ele entregou os amorreus nas mãos dos filhos de Israel, e disse em presença dos israelitas: “Sol, detém-te em Gabaon, e tu, ó lua, no vale de Aialon”.

[[v6-10-13]]

^<<v6-10-13,13>>^ E o sol parou e a lua não se moveu até que o povo se vingou de seus inimigos. Isso acha-se escrito no Livro do Justo. O sol parou no meio do céu e não se apressou a pôr-se pelo espaço de quase um dia inteiro.^&#42;1^

[[v6-10-14]]

^<<v6-10-14,14>>^ Não houve, nem antes nem depois, um dia como aquele, em que o Senhor tenha obedecido à voz de um homem, porque o Senhor combatia por Israel.

[[v6-10-15]]

^<<v6-10-15,15>>^ Depois disso, Josué com toda a sua tropa voltou para o acampamento de Gálgala.

[[v6-10-16]]

^<<v6-10-16,16>>^ Ora, os cinco reis tinham fugido e tinham se escondido numa caverna, em Maceda.

[[v6-10-17]]

^<<v6-10-17,17>>^ E noticiaram-no a Josué: “Foram encontrados os cinco reis escondidos numa caverna em Maceda”.

[[v6-10-18]]

^<<v6-10-18,18>>^ Josué respondeu: “Rolai grandes pedras para a entrada da caverna e ponde homens junto a ela em guarda.

[[v6-10-19]]

^<<v6-10-19,19>>^ Vós, porém, não vos detenhais, mas persegui vossos inimigos; não os deixeis entrar em suas cidades, porque o Senhor, vosso Deus, os entregou em vossas mãos”.

[[v6-10-20]]

^<<v6-10-20,20>>^ Tendo Josué e os israelitas acabado de massacrá-los, até o extermínio – apenas uns poucos puderam escapar e recolher-se às suas cidades fortes –,

[[v6-10-21]]

^<<v6-10-21,21>>^ todo o povo voltou tranquilamente ao acampamento, junto de Josué, em Maceda, e ninguém se atreveu a abrir a boca contra os filhos de Israel.

[[v6-10-22]]

^<<v6-10-22,22>>^ Josué disse então: “Abri a entrada da caverna e trazei-me os cinco reis que lá estão”. Assim o fizeram.

[[v6-10-23]]

^<<v6-10-23,23>>^ Foram tirados da caverna os cinco reis, o rei de Jerusalém, o rei de Hebron, o rei de Jarmut, o rei de Laquis e o rei de Eglon.

[[v6-10-24]]

^<<v6-10-24,24>>^ Quando foram conduzidos a Josué, ele chamou todos os homens de Israel e disse aos chefes dos guerreiros que o tinham acompanhado: “Aproximai-vos e ponde o pé sobre o pescoço destes reis”. Tendo-se eles aproximado e posto o pé sobre o pescoço deles,

[[v6-10-25]]

^<<v6-10-25,25>>^ disse-lhes de novo: “Não temais, nem tremais. Tende coragem e sede fortes, porque é assim que fará o Senhor a todos os inimigos que haveis de combater”.

[[v6-10-26]]

^<<v6-10-26,26>>^ Dizendo isso, Josué feriu-os de morte e suspendeu-os em cinco árvores, onde estiveram até a tarde.

[[v6-10-27]]

^<<v6-10-27,27>>^ Ao pôr do sol, mandou que fossem descidos das árvores e lançados na caverna onde se tinham refugiado, e puseram à entrada grandes pedras, que ali se encontram ainda hoje.

[[v6-10-28]]

^<<v6-10-28,28>>^ No mesmo dia apoderou-se Josué de Maceda, e passou-a a fio de espada juntamente com seu rei; votou ao interdito a cidade com todo ser vivo que nela havia, sem nada poupar. E fez ao rei de Maceda como tinha feito ao rei de Jericó.

[[v6-10-29]]

^<<v6-10-29,29>>^ Passou em seguida com todo o Israel a Lebna e atacaram-na.

[[v6-10-30]]

^<<v6-10-30,30>>^ O Senhor entregou-a com seu rei nas mãos de Israel, que passou a fio da espada a cidade com todo ser vivo que nela havia, não deixando escapar nenhum. E fez ao seu rei como tinha feito ao rei de Jericó.

[[v6-10-31]]

^<<v6-10-31,31>>^ De Lebna passou Josué com todo o Israel a Laquis, onde levantou o seu acampamento, sitiando-a.

[[v6-10-32]]

^<<v6-10-32,32>>^ O Senhor lhe entregou, e Israel apoderou-se dela no segundo dia, passando-a a fio da espada com todo ser vivo, como tinha feito a Lebna.

[[v6-10-33]]

^<<v6-10-33,33>>^ Então, Horam, rei de Gazer, veio em socorro de Laquis, mas Josué o derrotou com todo o seu povo até o extermínio completo.

[[v6-10-34]]

^<<v6-10-34,34>>^ De Laquis, passou Josué com todo o seu povo a Eglon; levantaram ali o seu acampamento e atacaram-na.

[[v6-10-35]]

^<<v6-10-35,35>>^ Tomaram-na no mesmo dia e passaram-na a fio da espada, votando ao interdito todo ser vivo, como tinha feito a Laquis.

[[v6-10-36]]

^<<v6-10-36,36>>^ Subiu em seguida com todo o Israel de Eglon a Hebron e atacaram-na.

[[v6-10-37]]

^<<v6-10-37,37>>^ Tomaram Hebron e passaram a fio da espada a cidade com seu rei, seus arrabaldes e todo ser vivo, sem nada deixar escapar, como tinham feito a Eglon. A cidade foi votada ao interdito com todo ser vivo.

[[v6-10-38]]

^<<v6-10-38,38>>^ Dali Josué, com todo o Israel, voltou-se contra Dabir e atacou-a;

[[v6-10-39]]

^<<v6-10-39,39>>^ apoderou-se dela, juntamente com seu rei, e passou-os a fio da espada. Votou ao interdito toda alma viva que nela se achava, sem nada poupar, e fez a Dabir e ao seu rei como tinha feito a Hebron e a Lebna com seus reis.

[[v6-10-40]]

^<<v6-10-40,40>>^ Josué feriu toda a terra: a montanha, o Negueb, a planície, as colinas com todos os seus reis, sem poupar ninguém, votando ao interdito tudo o que respirava, segundo a ordem do Senhor, Deus de Israel.

[[v6-10-41]]

^<<v6-10-41,41>>^ Tudo foi assim ferido por Josué, de Cades Barne a Gaza, toda a terra de Gósen até Gabaon.

[[v6-10-42]]

^<<v6-10-42,42>>^ Josué apoderou-se, de uma só vez, desse país e de seus reis, porque o Senhor, Deus de Israel, combatia por ele.

[[v6-10-43]]

^<<v6-10-43,43>>^ Depois voltou Josué com todo o Israel para o acampamento de Gálgala.

'''

xref:006-josue/006-josue-009.adoc#v6-9-0[&#60; Capítulo Anterior] | <<v6-10-0,Topo>> | xref:006-josue/006-josue-011.adoc#v6-11-0[Próximo Capítulo &#62;]