include::./index.adoc[]

[[v11-12-0]]
=== I Reis, 12
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 12 de 1 Reis descreve a divisão do reino de Israel após a morte de Salomão, quando seu filho Roboão se torna rei. As tribos do norte se rebelam contra Roboão devido à sua recusa em aliviar a carga de trabalho pesado que seu pai havia imposto sobre eles. Jeroboão, que era um servo de Salomão, lidera a rebelião e se torna o rei do reino do norte, que é chamado de Israel, enquanto Roboão governa o reino do sul, chamado de Judá. Os seguintes versículos da Bíblia estão relacionados com os temas abordados em 1 Reis 12:
* 1 Reis 11:11-13: "Então o Senhor disse a Salomão: Porquanto houve isto em ti, e não guardaste a minha aliança e os meus estatutos que te mandei, certamente rasgarei de ti este reino, e o darei a teu servo. Contudo nos teus dias não o farei, por amor de Davi, teu pai; da mão de teu filho o rasgarei. Todavia não rasgarei toda a casa de Davi, mas deixarei a teu filho uma tribo, por amor de Davi, meu servo, e por amor de Jerusalém, que elegi." Este versículo é uma profecia sobre a divisão do reino após a morte de Salomão.
* 1 Reis 12:16: "Vindo, pois, todo o Israel que estava presente, falou ao rei, dizendo: Que parte temos nós com Davi? não temos nós herança no filho de Jessé; cada um para as suas tendas, ó Israel! agora olha pela tua casa, ó Davi." Este versículo mostra a insatisfação das tribos do norte com a liderança de Roboão.
* 1 Reis 12:20: "Ouvindo, pois, todo o Israel que Jeroboão tinha voltado, enviaram chamá-lo à congregação, e o fizeram rei sobre todo o Israel; nenhuma tribo seguiu a casa de Davi, senão a tribo de Judá somente." Este versículo descreve a divisão do reino de Israel, com Jeroboão se tornando o rei do norte e Roboão governando o sul.
* Oséias 13:11: "Eu te dei rei na minha ira, e tirei-o na minha indignação." Este versículo é uma referência à liderança de Jeroboão, que foi escolhido como rei do norte como parte do julgamento divino contra a casa de Davi.
* Mateus 12:25: "Jesus, porém, conhecendo-lhes os pensamentos, disse: Todo reino dividido contra si mesmo será devastado; e toda cidade, ou casa, dividida contra si mesma não subsistirá." Este versículo destaca a ideia de que a divisão e a discórdia levarão à destruição, o que é ilustrado pela divisão do reino de Israel em 1 Reis 12.
****

[[v11-12-1]]

^<<v11-12-1,1>>^ Roboão foi a Siquém, porque todo o Israel se tinha juntado ali para proclamá-lo rei.

[[v11-12-2]]

^<<v11-12-2,2>>^ E chegou essa notícia aos ouvidos de Jeroboão no Egito, onde ainda estava refugiado para escapar à face do rei Salomão.

[[v11-12-3]]

^<<v11-12-3,3>>^ Mandaram, pois, buscá-lo no Egito, onde habitava. Então Jeroboão foi com toda a assembleia de Israel e disseram a Roboão:

[[v11-12-4]]

^<<v11-12-4,4>>^ “Teu pai impôs-nos um jugo pesado; alivia agora a rude servidão e o pesado jugo que teu pai nos impôs e seremos teus servos”.

[[v11-12-5]]

^<<v11-12-5,5>>^ Ele respondeu-lhes: “Ide-vos e voltai à minha presença dentro de três dias”. E o povo retirou-se.

[[v11-12-6]]

^<<v11-12-6,6>>^ O rei Roboão consultou os anciãos que tinham servido ao seu pai Salomão durante a sua vida. Disse-lhes: “Que me aconselhais responder a esse povo?”.

[[v11-12-7]]

^<<v11-12-7,7>>^ “Se hoje fores amável com esse povo – responderam-lhe – e cederes, se lhe falares com benevolência, eles serão para sempre teus servos.”

[[v11-12-8]]

^<<v11-12-8,8>>^ O rei, porém, deixando de lado o conselho dos anciãos, foi consultar os jovens que tinham crescido com ele e eram seus familiares.

[[v11-12-9]]

^<<v11-12-9,9>>^ Disse-lhes: “E vós, que me aconselhais responder ao povo? Ele pede-me que eu alivie o jugo que lhe impôs meu pai”.

[[v11-12-10]]

^<<v11-12-10,10>>^ Os jovens que tinham crescido com ele, responderam-lhe: “Assim dirás a esse povo que te falou, dizendo: ‘Teu pai tornou o nosso jugo pesado; tu, porém, alivia-nos’ – assim lhe dirás: ‘Meu dedo mínimo é mais grosso que os rins de meu pai.

[[v11-12-11]]

^<<v11-12-11,11>>^ Se meu pai vos impôs um jugo pesado, eu o farei ainda mais pesado. Se ele vos castigou com açoites, eu vos castigarei com escorpiões’.”

[[v11-12-12]]

^<<v11-12-12,12>>^ Chegou o terceiro dia. Jeroboão, seguido de uma grande multidão, apresentou-se diante de Roboão, pois ele dissera: “Voltai a mim dentro de três dias”.

[[v11-12-13]]

^<<v11-12-13,13>>^ O rei falou com dureza ao povo. Sem fazer caso algum do conselho dos anciãos,

[[v11-12-14]]

^<<v11-12-14,14>>^ respondeu ao povo como lhe aconselharam os jovens: “Meu pai impôs-vos um jugo pesado? Pois eu o tornarei ainda mais pesado. Meu pai vos castigou com açoites? Pois eu vos castigarei com escorpiões”.

[[v11-12-15]]

^<<v11-12-15,15>>^ E o rei não atendeu ao povo, porque assim o dispusera o Senhor, para realizar a palavra que tinha dito a Jeroboão, filho de Nabat, por meio de Aías de Silo.

[[v11-12-16]]

^<<v11-12-16,16>>^ Vendo que o rei não os atendia, o povo respondeu-lhe: “Que temos nós a ver com Davi? Que temos nós de comum com o filho de Jessé? Vai, pois, para as tuas tendas, ó Israel! Cabe a ti tratar de tua casa, ó Davi!”. E os israelitas retiraram-se para as suas tendas.

[[v11-12-17]]

^<<v11-12-17,17>>^ Roboão reinou, no entanto, sobre os israelitas que habitavam em Judá.

[[v11-12-18]]

^<<v11-12-18,18>>^ O rei Roboão enviou Aduram, superintendente dos trabalhos, mas os israelitas apedrejaram-no e ele morreu. O rei subiu então precipitadamente no seu carro e fugiu para Jerusalém.

[[v11-12-19]]

^<<v11-12-19,19>>^ Desse modo, separou-se Israel da casa de Davi até o dia de hoje.

[[v11-12-20]]

^<<v11-12-20,20>>^ Ouvindo os filhos de Israel que Jeroboão tinha voltado, convidaram-no à sua assembleia e aclamaram-no rei de todo o Israel. Só a tribo de Judá ficou fiel à casa de Davi.

[[v11-12-21]]

^<<v11-12-21,21>>^ Roboão, quando chegou a Jerusalém, reuniu toda a casa de Judá e a tribo de Benjamim, cento e oitenta mil guerreiros de escol, a fim de pelejar contra a casa de Israel e restituir todo o reino a Roboão, filho de Salomão.

[[v11-12-22]]

^<<v11-12-22,22>>^ Mas Deus falou a Semeías, homem de Deus:

[[v11-12-23]]

^<<v11-12-23,23>>^ “Fala a Roboão, filho de Salomão, rei de Judá, bem como a toda a casa de Judá e de Benjamim e a todo o restante do povo. Dize-lhes: Eis o que diz o Senhor:

[[v11-12-24]]

^<<v11-12-24,24>>^ Não façais guerra aos vossos irmãos, os israelitas. Volte cada um para a sua casa. Tudo isso se fez por minha vontade”. Eles obedeceram à palavra do Senhor e voltaram, como lhes ordenara.

[[v11-12-25]]

^<<v11-12-25,25>>^ Jeroboão construiu Siquém na montanha de Efraim e lá fixou residência. Depois deixou Siquém para edificar Fanuel.

[[v11-12-26]]

^<<v11-12-26,26>>^ E disse consigo mesmo: “Pode bem ser que o reino volte para a casa de Davi.

[[v11-12-27]]

^<<v11-12-27,27>>^ Se o povo subir a Jerusalém para oferecer sacrifícios no Templo do Senhor e o seu coração se voltar para o seu senhor, Roboão, rei de Judá. Eles me matarão e se voltarão para Roboão, rei de Judá”.

[[v11-12-28]]

^<<v11-12-28,28>>^ Depois de ter refletido bem, o rei mandou fazer dois bezerros de ouro e disse ao povo: “Basta de peregrinações a Jerusalém! Eis aqui, ó Israel, o teu Deus que te tirou do Egito”.^&#42;1^

[[v11-12-29]]

^<<v11-12-29,29>>^ Pôs um bezerro em Betel e outro em Dã.

[[v11-12-30]]

^<<v11-12-30,30>>^ Isso foi uma ocasião de pecado, porque o povo ia até Dã para adorar um desses bezerros.

[[v11-12-31]]

^<<v11-12-31,31>>^ Jeroboão construiu também templos em lugares altos, onde estabeleceu como sacerdotes homens tirados do meio do povo e que não eram levitas.

[[v11-12-32]]

^<<v11-12-32,32>>^ Instituiu também uma festa no oitavo mês, no décimo quinto dia do mês, à semelhança da que se celebrava em Judá e subiu ao altar. Fez o mesmo em Betel, sacrificando aos bezerros que tinha mandado fazer. Estabeleceu igualmente em Betel sacerdotes para os lugares altos que tinha edificado.

[[v11-12-33]]

^<<v11-12-33,33>>^ No décimo quinto dia do oitavo mês, isto é, no mês que tinha escolhido a seu bel-prazer, subiu ao altar que tinha edificado em Betel para celebrar a festa com os israelitas. Subiu ao altar para queimar o incenso.

'''

xref:011-i-reis/011-i-reis-011.adoc#v11-11-0[&#60; Capítulo Anterior] | <<v11-12-0,Topo>> | xref:011-i-reis/011-i-reis-013.adoc#v11-13-0[Próximo Capítulo &#62;]