include::./index.adoc[]

[[v11-8-0]]
=== I Reis, 8
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 8 de 1 Reis descreve a dedicação do Templo de Salomão em Jerusalém, que foi construído para abrigar a Arca da Aliança e servir como o lugar de adoração do povo de Israel. Durante a cerimônia de dedicação, o rei Salomão oferece uma oração a Deus e pede que Ele abençoe o Templo e o povo de Israel. Os seguintes versículos da Bíblia estão relacionados com os temas abordados em 1 Reis 8:
* Deuteronômio 12:5: "Mas procurai o lugar que o Senhor vosso Deus escolher de todas as vossas tribos para ali pôr o seu nome, para a sua habitação; e ali vireis." Este versículo destaca a importância de ter um lugar central de adoração, como o Templo de Salomão em Jerusalém.
* Salmos 132:13-14: "Pois o Senhor escolheu a Sião; desejou-a para sua habitação. Este é o meu repouso para sempre; aqui habitarei, pois o desejei." Este Salmo é uma referência à escolha de Deus de habitar no Templo de Jerusalém e demonstra a importância do Templo como o lugar de habitação de Deus na terra.
* Isaías 56:7: "Também os levarei ao meu santo monte, e os alegrarei na minha casa de oração; os seus holocaustos e os seus sacrifícios serão aceitos no meu altar; porque a minha casa será chamada casa de oração para todos os povos." Este versículo destaca a ideia de que o Templo de Jerusalém deveria ser um lugar de oração e adoração para todas as nações.
* Mateus 21:13: "E disse-lhes: Está escrito: A minha casa será chamada casa de oração; mas vós a tendes convertido em covil de ladrões." Jesus cita este versículo ao expulsar os cambistas e vendedores do Templo em Jerusalém, enfatizando a importância de manter o Templo como um lugar de adoração e oração.
* João 2:19-21: "Respondeu Jesus, e disse-lhes: Derribai este templo, e em três dias o levantarei. Disseram, pois, os judeus: Em quarenta e seis anos foi edificado este templo, e tu o levantarás em três dias? Mas ele falava do templo do seu corpo." Este versículo é uma referência ao corpo de Jesus como o novo Templo, enfatizando a importância da fé em Cristo como o caminho para a salvação.
****

[[v11-8-1]]

^<<v11-8-1,1>>^ Então convocou Salomão junto de si em Jerusalém os anciãos de Israel e todos os chefes das tribos e os chefes das famílias israelitas, para irem buscar na Cidade de Davi, em Sião, a arca da aliança do Senhor.

[[v11-8-2]]

^<<v11-8-2,2>>^ Todos os israelitas se reuniram junto do rei Salomão no mês de Etanim, que é o sétimo, durante a festa.^&#42;1^

[[v11-8-3]]

^<<v11-8-3,3>>^ Vieram todos os anciãos de Israel e os sacerdotes tomaram a arca do Senhor.

[[v11-8-4]]

^<<v11-8-4,4>>^ Levaram-na, assim como a tenda de reunião e todos os utensílios sagrados que havia no tabernáculo; tudo foi carregado pelos sacerdotes e levitas.

[[v11-8-5]]

^<<v11-8-5,5>>^ O rei Salomão e toda a assembleia de Israel reunida junto dele conservavam-se diante da arca. Sacrificavam tão grande quantidade de ovelhas e bois que não se podia contar.

[[v11-8-6]]

^<<v11-8-6,6>>^ Os sacerdotes levaram a arca da aliança do Senhor para seu lugar, no santuário do templo, no Santo dos Santos, debaixo das asas dos querubins.

[[v11-8-7]]

^<<v11-8-7,7>>^ Com efeito, os querubins estendiam as suas asas sobre o lugar da arca e cobriam por cima a arca e os seus varais.

[[v11-8-8]]

^<<v11-8-8,8>>^ Esses varais eram de tal forma compridos, que se podiam ver as suas extremidades do lugar santo, diante do santuário, mas não de fora e ali ficaram até o dia de hoje.

[[v11-8-9]]

^<<v11-8-9,9>>^ Na arca só havia as duas tábuas de pedra que Moisés ali depusera no monte Horeb, quando o Senhor fez aliança com os israelitas, depois que saíram da terra do Egito.

[[v11-8-10]]

^<<v11-8-10,10>>^ Quando os sacerdotes saíram do lugar santo, a nuvem encheu o Templo do Senhor,

[[v11-8-11]]

^<<v11-8-11,11>>^ de modo tal que os sacerdotes não puderam ali ficar para exercer as funções de seu ministério; porque a glória do Senhor enchia o Templo do Senhor.

[[v11-8-12]]

^<<v11-8-12,12>>^ Então Salomão disse: “O Senhor declarou que habitaria na obscuridade.

[[v11-8-13]]

^<<v11-8-13,13>>^ Por isso, edifiquei uma casa para vossa residência, um lugar onde habitareis para sempre”.

[[v11-8-14]]

^<<v11-8-14,14>>^ Depois o rei virou-se para a assembleia de Israel, que se conservava de pé e a abençoou.

[[v11-8-15]]

^<<v11-8-15,15>>^ “Bendito seja o Senhor, Deus de Israel – disse ele –, que falou pela sua boca ao meu pai Davi e que, pela sua mão, acaba de cumprir a promessa que ele fez quando disse:

[[v11-8-16]]

^<<v11-8-16,16>>^ ‘Desde o dia em que tirei do Egito o meu povo de Israel, não escolhi cidade alguma entre as tribos de Israel, para que aí me fosse edificada uma casa onde residisse o meu nome mas escolhi Davi para reinar sobre o meu povo de Israel’.

[[v11-8-17]]

^<<v11-8-17,17>>^ Davi, meu pai, tinha a intenção de construir um templo ao nome do Senhor, Deus de Israel.

[[v11-8-18]]

^<<v11-8-18,18>>^ Mas o Senhor disse-lhe: ‘Quando tiveste a intenção de edificar um templo ao meu nome, fizeste bem.

[[v11-8-19]]

^<<v11-8-19,19>>^ Tu, porém, não edificarás esse templo; será o teu filho, saído de ti, quem construirá um templo ao meu nome’.

[[v11-8-20]]

^<<v11-8-20,20>>^ O Senhor cumpriu, pois, a palavra que pronunciou. Como o Senhor o disse, eu me sentei sobre o trono de Israel, sucedendo ao meu pai Davi e construí esse templo ao nome do Senhor, Deus de Israel.

[[v11-8-21]]

^<<v11-8-21,21>>^ Preparei um lugar para a arca, onde se encontra a aliança do Senhor, aliança que fez com nossos pais quando os tirou do Egito”.

[[v11-8-22]]

^<<v11-8-22,22>>^ Em seguida, pôs-se Salomão diante do altar do Senhor, em presença de toda a assembleia de Israel, estendeu as mãos para o céu e disse:

[[v11-8-23]]

^<<v11-8-23,23>>^ “Senhor, Deus de Israel, não há Deus semelhante a vós, nem no mais alto dos céus, nem aqui embaixo, na terra; vós sois fiel à vossa misericordiosa aliança com os vossos servos, que caminham diante de vós de todo o seu coração.

[[v11-8-24]]

^<<v11-8-24,24>>^ Cumpristes a promessa que fizestes ao vosso servo Davi, meu pai: o que vossa boca falou, realizou-o vossa mão, como hoje se vê.

[[v11-8-25]]

^<<v11-8-25,25>>^ Agora, Senhor, Deus de Israel, realizai a promessa que fizestes ao vosso servo Davi, meu pai, quando lhe dissestes: ‘Não te faltará jamais diante de mim um sucessor ocupando o trono de Israel, contanto que teus filhos guardem cuidadosamente os teus caminhos, andando diante de mim, como tu mesmo o fizeste’.

[[v11-8-26]]

^<<v11-8-26,26>>^ Cumpra-se, pois, presentemente, ó Deus de Israel, a promessa que fizestes ao vosso servo Davi, meu pai.

[[v11-8-27]]

^<<v11-8-27,27>>^ Mas, será verdade que Deus habita realmente sobre a terra? Se o céu e o céu dos céus não vos podem conter quanto menos esta casa que edifiquei!

[[v11-8-28]]

^<<v11-8-28,28>>^ Entretanto, Senhor Deus meu, atendei à oração e às súplicas de vosso servo; ouvi o clamor e a prece que hoje vos dirijo.

[[v11-8-29]]

^<<v11-8-29,29>>^ Que vossos olhos estejam dia e noite abertos sobre este templo, sobre este lugar, do qual dissestes: ‘O meu nome residirá ali. Ouvi a oração que vosso servo vos faz neste lugar.

[[v11-8-30]]

^<<v11-8-30,30>>^ Ouvi a súplica de vosso servo e de vosso povo de Israel, quando orarem neste lugar. Ouvi-os do alto de vossa morada no céu, ouvi-os e perdoai!’.

[[v11-8-31]]

^<<v11-8-31,31>>^ Se alguém pecar contra o seu próximo e, fazendo-o jurar, for tomado juramento diante de vosso altar, neste templo,

[[v11-8-32]]

^<<v11-8-32,32>>^ vós, do alto dos céus, fareis justiça aos vossos servos, condenando o culpado, fazendo cair sobre ele o seu pecado e justificando o inocente, tratando-o segundo a sua inocência.

[[v11-8-33]]

^<<v11-8-33,33>>^ Quando vosso povo de Israel for derrotado por seus inimigos por ter pecado contra vós, se se voltarem para vós, dando glória ao vosso nome e vierem orar e vos suplicar neste templo,

[[v11-8-34]]

^<<v11-8-34,34>>^ ouvi-os do alto dos céus, perdoai o pecado de vosso povo de Israel e reconduzi-o à terra que destes a seus pais.

[[v11-8-35]]

^<<v11-8-35,35>>^ Quando o céu se fechar e não cair mais a chuva, por terem pecado contra vós, se vierem orar neste lugar, dando glória ao vosso nome e se converterem de seus pecados por causa de sua aflição,

[[v11-8-36]]

^<<v11-8-36,36>>^ ouvi-os do alto dos céus, perdoai o pecado de vossos servos e de vosso povo de Israel. Mostrai-lhes o bom caminho que devem seguir e mandai chuva sobre a terra que destes ao vosso povo como herança.

[[v11-8-37]]

^<<v11-8-37,37>>^ Quando vierem sobre a terra a fome, a peste, a ferrugem, a mangra, os gafanhotos; quando o inimigo cercar o povo nas cidades; quando houver qualquer flagelo ou epidemia,

[[v11-8-38]]

^<<v11-8-38,38>>^ se um homem, se todo o vosso povo recorrer a vós com orações e súplicas e se cada um, reconhecendo a chaga de seu coração, levantar as mãos para este templo,

[[v11-8-39]]

^<<v11-8-39,39>>^ ouvi-os desde vossa morada no alto dos céus e perdoai-lhes. Fazei de modo a dar a cada um segundo o que fez, vós que conheceis o seu coração, porque só vós conheceis o coração de todos os filhos dos homens;

[[v11-8-40]]

^<<v11-8-40,40>>^ e desta sorte eles vos temerão durante todos os dias de sua vida na terra que destes a seus pais.

[[v11-8-41]]

^<<v11-8-41,41>>^ Quanto ao estrangeiro, que não pertence ao vosso povo de Israel, quando vier de uma terra longínqua por causa de vosso nome –

[[v11-8-42]]

^<<v11-8-42,42>>^ porque se ouvirá falar da grandeza de vosso nome, da força de vossa mão e do poder de vosso braço –, quando vier orar neste templo,

[[v11-8-43]]

^<<v11-8-43,43>>^ ouvi-o do alto dos céus, do alto de vossa morada, ouvi-o e fazei tudo o que esse estrangeiro vos pedir. Então, todos os povos da terra conhecerão o vosso nome, vos temerão como o vosso povo de Israel e saberão que o vosso nome é invocado sobre esta casa que edifiquei.

[[v11-8-44]]

^<<v11-8-44,44>>^ Quando o vosso povo partir para a guerra contra os seus inimigos, seguindo o caminho que lhe indicardes, se vos invocarem com o rosto voltado para a cidade que escolhestes, para o templo que edifiquei ao vosso nome,

[[v11-8-45]]

^<<v11-8-45,45>>^ ouvi do alto dos céus as suas preces e súplicas e fazei-lhes justiça.

[[v11-8-46]]

^<<v11-8-46,46>>^ Quando pecarem contra vós – porque não há homem que não peque – e quando em vossa ira os entregardes nas mãos de seus inimigos, de sorte que sejam levados cativos pelos seus vencedores a uma terra inimiga, longínqua ou próxima,

[[v11-8-47]]

^<<v11-8-47,47>>^ se, na terra de seu exílio, entrando em si mesmos, se arrependerem de seus pecados e vos suplicarem no seu cativeiro desta forma: ‘Nós pecamos, cometemos a iniquidade, procedemos mal’,

[[v11-8-48]]

^<<v11-8-48,48>>^ se eles se voltarem para vós de todo o seu coração e de toda a sua alma, na terra de seus inimigos para onde forem levados cativos e se orarem a vós com o rosto voltado para a terra que destes a seus pais, para esta cidade que escolhestes, para este templo que construí ao vosso nome,

[[v11-8-49]]

^<<v11-8-49,49>>^ ouvi, do alto dos céus, do alto de vossa morada, as suas preces e súplicas e fazei-lhes justiça.

[[v11-8-50]]

^<<v11-8-50,50>>^ Perdoai ao vosso povo os seus pecados e as ofensas que cometeu contra vós. Tornai-os simpáticos aos seus vencedores, de sorte que tenham compaixão deles;

[[v11-8-51]]

^<<v11-8-51,51>>^ porque Israel é o vosso povo e a vossa herança, que tirastes do Egito, duma fornalha de ferro!

[[v11-8-52]]

^<<v11-8-52,52>>^ Estejam os vossos olhos abertos às súplicas de vosso servo e de vosso povo de Israel, para ouvi-los quando vos invocarem.

[[v11-8-53]]

^<<v11-8-53,53>>^ Porque vós, ó Senhor Javé, os separastes dentre todos os povos da terra para vossa herança, como o declarastes pela boca de vosso servo Moisés, quando tirastes nossos pais do Egito!”

[[v11-8-54]]

^<<v11-8-54,54>>^ Quando Salomão acabou de fazer ao Senhor essa prece e esta súplica, levantou-se de diante do altar do Senhor, onde estava ajoelhado com as mãos levantadas para o céu.

[[v11-8-55]]

^<<v11-8-55,55>>^ De pé, abençoou toda a assembleia de Israel, dizendo em alta voz:

[[v11-8-56]]

^<<v11-8-56,56>>^ “Bendito seja o Senhor que, como havia prometido, deu a paz ao seu povo de Israel! Não falhou uma palavra sequer de todas as boas palavras que dissera pela boca de seu servo Moisés.

[[v11-8-57]]

^<<v11-8-57,57>>^ Que o Senhor, nosso Deus, esteja convosco como esteve com nossos pais; não nos deixe, nem nos abandone,

[[v11-8-58]]

^<<v11-8-58,58>>^ mas incline os nossos corações para ele, a fim de que andemos em todos os seus caminhos, guardemos as leis, os mandamentos e os preceitos que ele prescreveu a nossos pais.

[[v11-8-59]]

^<<v11-8-59,59>>^ Que estas minhas palavras, que supliquei ao Senhor estejam presentes em sua memória, dia e noite, para que faça justiça ao seu servo e ao seu povo de Israel, conforme as necessidades de cada dia.

[[v11-8-60]]

^<<v11-8-60,60>>^ Assim, todos os povos da terra reconhecerão que é o Senhor que é Deus e que não há outro fora dele.

[[v11-8-61]]

^<<v11-8-61,61>>^ Que o vosso coração seja todo para o Senhor, nosso Deus, sem reserva, a fim de que andeis segundo as suas leis e observeis os seus preceitos, como hoje o fazeis”.

[[v11-8-62]]

^<<v11-8-62,62>>^ O rei e todo o Israel com ele imolaram vítimas diante do Senhor.

[[v11-8-63]]

^<<v11-8-63,63>>^ Salomão imolou, para o sacrifício pacífico que ofereceu ao Senhor, vinte e dois mil bois e cento e vinte mil ovelhas. Assim, o rei e todos os israelitas fizeram a dedicação do Templo do Senhor.

[[v11-8-64]]

^<<v11-8-64,64>>^ Naquele dia, o rei consagrou o interior do átrio, que se encontra diante do Templo do Senhor, pois ofereceu ali os holocaustos e as ofertas, bem como a gordura dos sacrifícios pacíficos, porque o altar de bronze, levantado diante do santuário do Senhor, não bastava para conter os holocaustos, as ofertas e a gordura dos sacrifícios pacíficos.

[[v11-8-65]]

^<<v11-8-65,65>>^ Tal foi a festa que Salomão celebrou naquele tempo e todo o Israel com ele, tendo concorrido uma imensa assembleia vinda desde Emat até a torrente do Egito, diante do Senhor, nosso Deus, durante duas vezes sete dias, isto é, catorze dias.

[[v11-8-66]]

^<<v11-8-66,66>>^ No oitavo dia, despediu o povo. Eles voltaram para as suas casas, abençoando o rei, com o coração alegre e contente por todos os bens que o Senhor tinha feito a Davi, seu servo e ao seu povo de Israel.

'''

xref:011-i-reis/011-i-reis-007.adoc#v11-7-0[&#60; Capítulo Anterior] | <<v11-8-0,Topo>> | xref:011-i-reis/011-i-reis-009.adoc#v11-9-0[Próximo Capítulo &#62;]