include::./index.adoc[]

[[v11-21-0]]
=== I Reis, 21
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Reis 21 relata a história de Nabote, um homem que possuía uma vinha desejada pelo rei Acabe. Quando Nabote recusou vender sua propriedade, a esposa de Acabe, Jezabel, conspirou para que ele fosse condenado à morte por blasfêmia. Depois que Nabote foi executado, Acabe tomou posse da vinha. A seguir, estão cinco versículos relacionados aos temas abordados em 1 Reis 21:
* Provérbios 22:22-23: "Não roube o pobre, porque é pobre, nem oprima o necessitado no tribunal, pois o SENHOR defenderá a causa deles e tirará a vida dos que os tiram." Esse versículo se relaciona com a injustiça cometida contra Nabote, que foi morto injustamente para que Acabe pudesse tomar posse de sua propriedade.
* Isaías 5:8: "Ai daqueles que ajuntam casa a casa, reúnem campo a campo, até que não haja mais lugar, e vocês fiquem morando sozinhos no meio da terra!" Essa passagem se relaciona com a ganância de Acabe, que desejava a vinha de Nabote mesmo sem precisar dela.
* Jeremias 22:13-14: "Ai daquele que constrói a sua casa com injustiça, e os seus aposentos superiores sem direito; que se serve do trabalho do seu próximo sem remunerá-lo, e não lhe dá o salário do seu trabalho. Ai daquele que diz a um pedaço de madeira: 'Desperta!', ou a uma pedra muda: 'Acorde!'" Esse versículo se relaciona com a conspiração de Jezabel para que Nabote fosse condenado à morte, mostrando que Deus se opõe àqueles que usam a injustiça para ganhar poder.
* Miquéias 2:1-2: "Ai daqueles que planejam a iniquidade, que inventam o mal em suas camas! Quando o dia amanhece, eles o executam, porque têm poder em suas mãos. Cobiçam campos e os roubam, casas, e as tomam; oprimem o dono e a sua casa, o homem e a sua herança." Essa passagem se relaciona com a ganância de Acabe e a forma como ele usou seu poder para tomar a vinha de Nabote.
* Mateus 6:19-21: "Não acumulem para vocês tesouros na terra, onde a traça e a ferrugem destroem, e onde os ladrões arrombam e furtam. Mas acumulem para vocês tesouros nos céus, onde a traça e a ferrugem não destroem, e onde os ladrões não arrombam nem furtam. Pois onde estiver o seu tesouro, aí também estará o seu coração." Essa passagem se relaciona com a ganância de Acabe, mostrando que a busca por riquezas terrenas pode levar a atitudes injustas e cruéis.
****

[[v11-21-1]]

^<<v11-21-1,1>>^ Depois disso, aconteceu o seguinte: Nabot de Jezrael possuía uma vinha nessa cidade, ao lado do palácio de Acab, rei de Samaria.

[[v11-21-2]]

^<<v11-21-2,2>>^ Acab disse a Nabot: “Cede-me tua vinha para que eu a transforme numa horta, porque está junto de minha casa. Eu te darei em troca uma vinha melhor ou, se o preferires, te pagarei em dinheiro o seu valor”.

[[v11-21-3]]

^<<v11-21-3,3>>^ Nabot, porém, respondeu a Acab: “Deus me livre de ceder-te a herança de meus pais!”.

[[v11-21-4]]

^<<v11-21-4,4>>^ Acab voltou para a sua casa, sombrio e irritado, por ter Nabot de Jezrael recusado ceder-lhe a herança de seus pais. Estendeu-se na cama com o rosto voltado para a parede e não quis comer.

[[v11-21-5]]

^<<v11-21-5,5>>^ Jezabel, sua mulher, veio ter com ele e disse-lhe: “Por que estás de mau humor e não queres comer?”.

[[v11-21-6]]

^<<v11-21-6,6>>^ Ele respondeu: “Falei a Nabot de Jezrael, propondo-lhe que me vendesse a sua vinha ou, se o preferisse, que a trocasse comigo por outra melhor. Mas ele respondeu-me: ‘Não te cederei a minha vinha!’.”

[[v11-21-7]]

^<<v11-21-7,7>>^ Jezabel, sua mulher, disse-lhe: “Não és tu, porventura, o rei de Israel? Vamos! Come, não te incomodes. Eu te darei a vinha de Nabot de Jezrael”.

[[v11-21-8]]

^<<v11-21-8,8>>^ Escreveu ela, então, uma carta em nome do rei, selou-a com o selo real e mandou-a aos anciãos e aos notáveis da cidade, concidadãos de Nabot.

[[v11-21-9]]

^<<v11-21-9,9>>^ Eis o que dizia na carta: “Promulgai um jejum, fazei sentar Nabot num lugar de honra

[[v11-21-10]]

^<<v11-21-10,10>>^ e mandai vir diante dele dois homens inescrupulosos que o acusem, dizendo: ‘Este amaldiçoou a Deus e ao rei!’. Conduzi-o em seguida para fora da cidade e apedrejai-o até que morra!”.

[[v11-21-11]]

^<<v11-21-11,11>>^ Os homens da cidade, os anciãos e os notáveis, concidadãos de Nabot, fizeram o que ordenava Jezabel, segundo o conteúdo da carta que lhes tinha mandado.

[[v11-21-12]]

^<<v11-21-12,12>>^ Promulgaram um jejum e fizeram Nabot sentar-se num lugar de honra.

[[v11-21-13]]

^<<v11-21-13,13>>^ Vieram então os dois miseráveis, colocaram-se diante dele e fizeram publicamente a seguinte deposição contra ele: “Nabot amaldiçoou a Deus e ao rei”. Depois disso, levaram-no para fora da cidade, onde foi apedrejado e morreu.

[[v11-21-14]]

^<<v11-21-14,14>>^ E mandaram dizer a Jezabel: “Nabot foi apedrejado e morto”.

[[v11-21-15]]

^<<v11-21-15,15>>^ Quando ela soube que Nabot fora apedrejado e morto, foi dizer a Acab: “Vai e toma posse da vinha que Nabot de Jezrael te recusara vender. Ele já não vive; está morto”.

[[v11-21-16]]

^<<v11-21-16,16>>^ Acab, tendo ouvido dizer que Nabot morrera, levantou-se e dirigiu-se para a sua vinha para tomar posse dela.

[[v11-21-17]]

^<<v11-21-17,17>>^ Então, a palavra do Senhor foi dirigida a Elias, o tesbita:

[[v11-21-18]]

^<<v11-21-18,18>>^ “Vai, desce ao encontro de Acab, rei de Israel, que mora em Samaria. Ei-lo que desce a tomar posse da vinha de Nabot.

[[v11-21-19]]

^<<v11-21-19,19>>^ Diz-lhe o seguinte: Isto diz o Senhor: ‘Mataste e agora usurpas!’. E ajuntarás: ‘Eis o que diz o Senhor: No mesmo lugar em que os cães lamberam o sangue de Nabot, lamberão também o teu’.”

[[v11-21-20]]

^<<v11-21-20,20>>^ Acab exclamou: “Encontraste-me de novo, ó meu inimigo?”. “Sim – respondeu Elias –, porque te vendeste para fazer o mal aos olhos do Senhor.

[[v11-21-21]]

^<<v11-21-21,21>>^ Farei cair o mal sobre ti. Vou varrer-te e exterminarei da família de Acab em Israel todo varão, seja escravo ou livre.

[[v11-21-22]]

^<<v11-21-22,22>>^ Farei de tua casa o que fiz da de Jeroboão, filho de Nabat, e da de Baasa, filho de Aías, porque me provocaste à ira e arrastaste Israel ao pecado”.

[[v11-21-23]]

^<<v11-21-23,23>>^ E eis agora o que diz o Senhor contra Jezabel: “Os cães devorarão Jezabel na terra de Jezrael.

[[v11-21-24]]

^<<v11-21-24,24>>^ Todo membro da família de Acab que morrer na cidade será devorado pelos cães e o que morrer no campo será comido pelas aves do céu”.

[[v11-21-25]]

^<<v11-21-25,25>>^ Com efeito, não houve ninguém que praticasse tanto o mal aos olhos do Senhor como Acab, excitado como era por sua mulher Jezabel.

[[v11-21-26]]

^<<v11-21-26,26>>^ Levou a abominação ao extremo, seguindo os ídolos dos amorreus, que o Senhor tinha expulsado de diante dos israelitas.

[[v11-21-27]]

^<<v11-21-27,27>>^ Ouvindo essas palavras, Acab rasgou suas vestes, cobriu-se com um saco e jejuou. Dormia, envolto no saco e andava a passos lentos.

[[v11-21-28]]

^<<v11-21-28,28>>^ Então, a palavra do Senhor foi dirigida a Elias, o tesbita, nestes termos:

[[v11-21-29]]

^<<v11-21-29,29>>^ “Viste como Acab se humilhou diante de mim? Como ele assim procedeu, não mandarei o castigo durante a sua vida, mas nos dias de seu filho farei vir a catástrofe sobre a sua casa”.

'''

xref:011-i-reis/011-i-reis-020.adoc#v11-20-0[&#60; Capítulo Anterior] | <<v11-21-0,Topo>> | xref:011-i-reis/011-i-reis-022.adoc#v11-22-0[Próximo Capítulo &#62;]