include::./index.adoc[]

[[v11-14-0]]
=== I Reis, 14
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 14 do livro de 1 Reis fala sobre o julgamento de Deus sobre o rei Jeroboão de Israel, que havia pecado e levado o povo de Israel a pecar também. O capítulo descreve como Jeroboão perdeu seu filho e sua esposa, além de ser advertido de que sua dinastia seria destruída por causa de sua desobediência.
* 2 Crônicas 13:6: "Mas Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, levantou-se e rebelou-se contra o seu senhor." Este versículo menciona Jeroboão, o foco principal do capítulo 14 de 1 Reis, e como ele se rebelou contra o rei Salomão.
* 1 Reis 12:28: "E, depois de consultar, fez dois bezerros de ouro e disse ao povo: 'Chega de subir a Jerusalém. Aqui estão os seus deuses, ó Israel, que o tiraram do Egito'." Este versículo fala sobre o pecado de Jeroboão de criar bezerros de ouro para adoração em Betel e Dã, levando o povo de Israel a pecar.
* 1 Reis 13:33-34: "Depois disto, Jeroboão não se desviou do seu mau caminho, mas tornou a fazer sacerdotes para os lugares altos dentre o povo em geral; a quem queria, consagrava para que fossem sacerdotes dos lugares altos. E isto foi causa de pecado para a casa de Jeroboão, para extirpá-la e destruí-la da face da terra." Estes versículos descrevem como Jeroboão continuou em seu mau caminho, criando sacerdotes para os lugares altos e levando seu povo a pecar, o que resultou na punição divina sobre a dinastia de Jeroboão.
* 1 Reis 15:29-30: "Assim que Baasa se tornou rei de Israel, matou toda a família de Jeroboão; não deixou ninguém com vida, conforme a palavra do Senhor que dissera por intermédio do seu servo Aías, o silonita, por causa dos pecados que Jeroboão tinha cometido e pelos quais tinha feito Israel pecar, e por causa da sua provocação ao Senhor, o Deus de Israel." Estes versículos descrevem como a dinastia de Jeroboão foi exterminada por causa de seu pecado e desobediência, cumprindo a profecia dada por Deus através do profeta Aías.
****

[[v11-14-1]]

^<<v11-14-1,1>>^ Por aquele tempo, Abias, filho de Jeroboão, caiu doente. Jeroboão disse à sua mulher:

[[v11-14-2]]

^<<v11-14-2,2>>^ “Disfarça-te, para que não saibam que és minha mulher. Vai a Silo, onde está o profeta Aías. É ele que me predisse que eu reinaria sobre este povo.

[[v11-14-3]]

^<<v11-14-3,3>>^ Toma contigo dez pães, bolos e um pote de mel e vai procurá-lo. Ele te dirá o que vai acontecer com o menino”.

[[v11-14-4]]

^<<v11-14-4,4>>^ Assim fez a mulher de Jeroboão: pôs-se a caminho de Silo e foi à casa de Aías. Este já não podia ver, porque a velhice lhe tinha obscurecido os olhos.

[[v11-14-5]]

^<<v11-14-5,5>>^ Mas o Senhor disse-lhe: “Eis que aí vem a mulher de Jeroboão para consultar-te a respeito de seu filho doente. Tu lhe falarás assim e assim. Ao chegar, ela se fará passar por outra”.

[[v11-14-6]]

^<<v11-14-6,6>>^ Ouvindo o ruído dos seus passos, ao entrar pela porta, Aías disse-lhe: “Entra, mulher de Jeroboão! Por que te queres fazer passar por outra? Tenho uma triste mensagem para ti.

[[v11-14-7]]

^<<v11-14-7,7>>^ Vai e dize a Jeroboão: Eis o que diz o Senhor, Deus de lsrael: Elevei-te do meio do povo para fazer de ti o príncipe de meu povo de Israel.

[[v11-14-8]]

^<<v11-14-8,8>>^ Dividi o reino da casa de Davi para dar-te uma parte. Tu, porém, não seguiste o exemplo de meu servo Davi, que guardava os meus mandamentos e me seguia de todo o seu coração, fazendo sempre o que me era agradável.

[[v11-14-9]]

^<<v11-14-9,9>>^ Fizeste maiores males que todos os que te precederam e chegaste até a fazer para ti deuses estranhos e figuras fundidas, provocando a minha ira; lançaste-me para trás das costas!

[[v11-14-10]]

^<<v11-14-10,10>>^ Por isso, farei vir males maiores sobre a casa de Jeroboão; exterminarei de Israel toda a sua família, até o último dos varões, escravo ou livre; varrerei a casa de Jeroboão como se varre o lixo, até que não fique mais nada.

[[v11-14-11]]

^<<v11-14-11,11>>^ Todo membro da casa de Jeroboão que morrer na cidade será devorado pelos cães; e os que morrerem no campo serão comidos pelas aves do céu. É o Senhor quem o diz.

[[v11-14-12]]

^<<v11-14-12,12>>^ Volta, pois, para a tua casa. Logo que puseres os pés na cidade, o menino morrerá.

[[v11-14-13]]

^<<v11-14-13,13>>^ Todo o Israel o chorará e o sepultará, porque este será o único da família de Jeroboão que terá uma sepultura, visto ter sido o único desta família em quem o Senhor, Deus de Israel, encontrou algo de bom.

[[v11-14-14]]

^<<v11-14-14,14>>^ O Senhor suscitará em Israel um rei que exterminará a casa de Jeroboão. Mas que digo? Isso já acontece!

[[v11-14-15]]

^<<v11-14-15,15>>^ O Senhor vai ferir Israel. Como o caniço é levado pelas águas, assim o Senhor os tirará dessa boa terra que ele deu aos seus pais e os dispersará para além do Eufrates, porque fabricaram para si ídolos que provocam a cólera do Senhor.

[[v11-14-16]]

^<<v11-14-16,16>>^ O Senhor abandonará Israel por causa dos pecados de Jeroboão, que pecou e arrastou também Israel ao seu pecado”.

[[v11-14-17]]

^<<v11-14-17,17>>^ A mulher de Jeroboão levantou-se e partiu. Ao entrar em Tersa, no momento em que entrava pela porta da casa, o menino morreu.

[[v11-14-18]]

^<<v11-14-18,18>>^ Sepultaram-no e todo o Israel o pranteou, assim como o Senhor o predisse pelo seu servo, o profeta Aías.

[[v11-14-19]]

^<<v11-14-19,19>>^ O resto das ações de Jeroboão, a história de suas campanhas e de seu governo, tudo isso está consignado no Livro das Crônicas dos reis de Israel.^&#42;1^

[[v11-14-20]]

^<<v11-14-20,20>>^ O seu reinado durou vinte e dois anos. Depois disso, adormeceu com seus pais e seu filho Nadab sucedeu-lhe no trono.

[[v11-14-21]]

^<<v11-14-21,21>>^ Roboão, filho de Salomão, reinou sobre Judá. Tinha quarenta e um anos quando começou a reinar e reinou dezessete anos em Jerusalém, a cidade que o Senhor escolheu entre todas as tribos de Israel para ali estabelecer o seu nome. Sua mãe chamava-se Naama, a amonita.

[[v11-14-22]]

^<<v11-14-22,22>>^ O povo de Judá fez o mal diante do Senhor e com os seus pecados excitaram-lhe o zelo mais do que tinham feito os seus pais.

[[v11-14-23]]

^<<v11-14-23,23>>^ Edificaram para si lugares altos, estelas e ídolos asserás sobre todas as colinas e debaixo de tudo que fosse árvore verde.

[[v11-14-24]]

^<<v11-14-24,24>>^ Até prostitutas sagradas houve na terra. Imitaram todas as abominações dos povos que o Senhor tinha expulsado de diante dos israelitas.

[[v11-14-25]]

^<<v11-14-25,25>>^ No quinto ano do reinado de Roboão, Sesac, rei do Egito, atacou Jerusalém

[[v11-14-26]]

^<<v11-14-26,26>>^ e tomou os tesouros do Templo do Senhor, os do palácio real, roubou tudo, até mesmo os escudos de ouro que Salomão tinha mandado fazer.

[[v11-14-27]]

^<<v11-14-27,27>>^ Em sua substituição, o rei Roboão mandou fazer escudos de bronze e os entregou aos chefes da guarda da porta do palácio real.^&#42;1^

[[v11-14-28]]

^<<v11-14-28,28>>^ Cada vez que o rei se dirigia ao Templo do Senhor, os guardas levavam esses escudos; depois tornavam a colocá-los no corpo da guarda.

[[v11-14-29]]

^<<v11-14-29,29>>^ O restante da história de Roboão e seus atos, tudo está consignado no Livro das Crônicas dos reis de Judá.

[[v11-14-30]]

^<<v11-14-30,30>>^ Jeroboão e Roboão estiveram o tempo todo em guerra.

[[v11-14-31]]

^<<v11-14-31,31>>^ Roboão adormeceu com os seus pais e foi sepultado com eles na Cidade de Davi. Sua mãe chamava-se Naama, a amonita. Seu filho Abião sucedeu-lhe no trono.^&#42;1^

'''

xref:011-i-reis/011-i-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-i-reis/011-i-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]