include::./index.adoc[]

[[v11-20-0]]
=== I Reis, 20
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em 1 Reis 20, o rei Ben-Hadade da Síria e seu exército cercam e atacam Samaria, a capital do reino de Israel. O profeta Eliseu prediz a vitória de Israel e orienta o rei Acabe a lutar contra os sírios. Israel consegue a vitória, mas permite que Ben-Hadade escape, o que desagrada a Deus. Em seguida, um profeta confronta Acabe por não ter matado o inimigo. Seguem abaixo cinco versículos relacionados com os temas abordados em 1 Reis 20:
* 1 Reis 20:13: "Um profeta se aproximou do rei Acabe e disse: Assim diz o Senhor: Você viu essa grande multidão? Hoje eu a entregarei em suas mãos, e você saberá que eu sou o Senhor." O profeta Eliseu assegura a vitória de Israel, mostrando que Deus está do lado de seu povo.
* 1 Reis 20:28: "Então o homem de Deus se aproximou do rei de Israel e disse: Assim diz o Senhor: Porque os sírios disseram: O Senhor é um deus das montanhas, mas não é um deus das planícies, eu entregarei todo este grande exército em suas mãos, e vocês saberão que eu sou o Senhor." Mais uma vez, Deus se revela como o Deus de Israel, capaz de derrotar os inimigos de seu povo.
* 1 Reis 20:42: "Ele [o profeta] disse ao rei: Assim diz o Senhor: Porque você deixou escapar das mãos o homem que eu tinha destinado à destruição, agora a sua vida será tirada em lugar da vida dele, e o seu povo em lugar do povo dele." A mensagem do profeta mostra a importância de obedecer a Deus em tudo, e como um erro pode ter consequências graves.
* 1 Reis 20:48: "Ele [Ben-Hadade] viveu escondido com o rei de Israel por algum tempo." O fato de Ben-Hadade ter sido poupado deixa evidente o problema do rei Acabe em lidar com a questão dos inimigos de Israel. Isso abre espaço para uma nova batalha no futuro.
* 1 Reis 20:28-29: "Então o homem de Deus se aproximou do rei de Israel e disse: Assim diz o Senhor: Porque os sírios disseram: O Senhor é um deus das montanhas, mas não é um deus das planícies, eu entregarei todo este grande exército em suas mãos, e vocês saberão que eu sou o Senhor. Eles ficarão sabendo que eu sou o Senhor." A mensagem principal da passagem é a certeza da vitória de Israel em nome de Deus, mostrando que não importa a força ou a estratégia do inimigo, Deus é mais poderoso.
****

[[v11-20-1]]

^<<v11-20-1,1>>^ Ben-Adad, rei da Síria, mobilizou todo o seu exército. Tinha com ele trinta e dois reis, cavalos e carros. Subiu, pôs o cerco diante de Samaria e atacou-a.^&#42;1^

[[v11-20-2]]

^<<v11-20-2,2>>^ Mandou mensageiros a Acab, rei de Israel, na cidade, com esta mensagem:

[[v11-20-3]]

^<<v11-20-3,3>>^ “Eis o que diz Ben-Adad: A tua prata e teu ouro são meus. São minhas as tuas mulheres e os mais belos de teus filhos”.

[[v11-20-4]]

^<<v11-20-4,4>>^ “Como tu dizes, meu senhor e rei –, respondeu Acab – eu sou teu com tudo o que me pertence.”

[[v11-20-5]]

^<<v11-20-5,5>>^ Mas os mensageiros voltaram e disseram: “Isto diz Ben-Adad: Mandou-te dizer: Dá-me tua prata e teu ouro, tuas mulheres e teus filhos.

[[v11-20-6]]

^<<v11-20-6,6>>^ Amanhã, pois, a esta mesma hora, mandarei os meus servos à tua casa. Eles a revistarão, assim como as casas de teus servos; tomarão com as suas mãos tudo o que lhes aprouver”.

[[v11-20-7]]

^<<v11-20-7,7>>^ Então, o rei de Israel convocou todos os anciãos da terra e disse-lhes: “Considerai e vede que esse homem quer a nossa perda. Quando me mandou pedir minhas mulheres, meus filhos, minha prata e meu ouro, nada lhe recusei”.

[[v11-20-8]]

^<<v11-20-8,8>>^ Os anciãos e todo o povo disseram-lhe: “Não lhe dês ouvidos, nem o atendas em nada”.

[[v11-20-9]]

^<<v11-20-9,9>>^ Acab respondeu aos mensageiros de Ben-Adad: “Dizei ao rei, meu senhor: Estou pronto a fazer o que pediste ao teu servo da primeira vez; mas o que agora exiges, não o posso consentir”. Os mensageiros foram-se e deram tal resposta ao rei.

[[v11-20-10]]

^<<v11-20-10,10>>^ Ben-Adad mandou dizer a Acab: “Que os deuses me tratem com o mais extremo rigor, se o pó de Samaria bastar para encher as mãos dos guerreiros que me seguem!”.

[[v11-20-11]]

^<<v11-20-11,11>>^ O rei de Israel, respondendo, disse: “Dizei-lhe que aquele que põe o seu cinturão não deve gloriar-se como aquele que o tira”.

[[v11-20-12]]

^<<v11-20-12,12>>^ Recebendo essa resposta, Ben-Adad, que estava bebendo nas suas tendas com os reis, disse à sua gente: “Aos vossos postos!”. E eles ordenaram as tropas para o ataque à cidade.

[[v11-20-13]]

^<<v11-20-13,13>>^ Nesse momento, um profeta aproximou-se de Acab, rei de Israel, e disse-lhe: “Eis o que diz o Senhor: Vês esta imensa multidão? Pois declaro-te que hoje te entrego nas mãos, para que saibas que eu sou o Senhor.”

[[v11-20-14]]

^<<v11-20-14,14>>^ Acab perguntou: “Por quem será ela entregue?”. O profeta respondeu: “Assim fala o Senhor: Por meio dos servos dos chefes de províncias”. “Quem começará o combate?” “Tu mesmo.”

[[v11-20-15]]

^<<v11-20-15,15>>^ Acab passou em revista os servos dos chefes de províncias e encontrou duzentos e trinta e dois. Depois contou todo o povo dos israelitas e viu que eram sete mil.

[[v11-20-16]]

^<<v11-20-16,16>>^ Saíram ao meio-dia, quando Ben-Adad bebia e se embriagava nas tendas com os trinta e dois reis, seus auxiliares.

[[v11-20-17]]

^<<v11-20-17,17>>^ Os servos dos chefes de províncias saíram na frente. Ben-Adad mandou ver o que se passava. Disseram-lhe: “São alguns homens que saem de Samaria”.

[[v11-20-18]]

^<<v11-20-18,18>>^ O rei disse: “Venham eles para tratar de paz ou venham para combater, capturai-os vivos”.

[[v11-20-19]]

^<<v11-20-19,19>>^ Os servos dos chefes de províncias saíram, pois, da cidade, seguidos do exército.

[[v11-20-20]]

^<<v11-20-20,20>>^ Cada um deles feriu o seu homem. Os sírios fugiram, perseguidos por Israel; Ben-Adad, rei da Síria, fugiu a cavalo com alguns cavaleiros.

[[v11-20-21]]

^<<v11-20-21,21>>^ Então, o rei de Israel saiu e feriu cavalos e carros, causando uma grande ruína aos sírios.

[[v11-20-22]]

^<<v11-20-22,22>>^ O profeta foi ter com o rei de Israel e disse-lhe: “Vai, cobra ânimo e examina o que te é preciso fazer, porque no próximo ano voltará o rei da Síria para atacar-te”.

[[v11-20-23]]

^<<v11-20-23,23>>^ Os servos do rei da Síria disseram ao seu soberano: “O seu deus é um deus dos montes; por isso, foram mais fortes do que nós. Se os atacarmos na planície, veremos se não somos os mais fortes.

[[v11-20-24]]

^<<v11-20-24,24>>^ Eis o que tens de fazer: Destitui todos os reis e substitui-os por governadores.

[[v11-20-25]]

^<<v11-20-25,25>>^ Levanta um exército semelhante ao que perdeste, uma cavalaria equivalente e outro tanto de carros. Combateremos na planície e com toda a certeza seremos mais fortes do que eles”. O rei ouviu e seguiu o seu conselho.

[[v11-20-26]]

^<<v11-20-26,26>>^ No ano seguinte, Ben-Adad, depois de ter passado em revista os sírios, avançou até Afec para combater Israel.

[[v11-20-27]]

^<<v11-20-27,27>>^ Os israelitas recenseados e providos de víveres foram contra os sírios e acamparam diante deles. Eram como dois pequenos rebanhos de cabras, enquanto os sírios cobriam toda a terra.

[[v11-20-28]]

^<<v11-20-28,28>>^ Então, o homem de Deus aproximou-se do rei de Israel e disse-lhe: “Isto diz o Senhor: Porque os sírios disseram: O Senhor é um deus dos montes e não das planícies – vou entregar-te nas mãos essa imensa multidão, a fim de que saibas que eu sou o Senhor”.

[[v11-20-29]]

^<<v11-20-29,29>>^ Durante sete dias, ficaram acampados um em face do outro. No sétimo dia, deu-se a batalha; os israelitas mataram num só dia cem mil sírios.

[[v11-20-30]]

^<<v11-20-30,30>>^ O resto fugiu para a cidade de Afec, mas as muralhas caíram sobre os vinte e sete mil sobreviventes. Ben-Adad, que se refugiara na cidade, escondia-se de quarto em quarto.

[[v11-20-31]]

^<<v11-20-31,31>>^ Seus servos disseram-lhe: “Nós ouvimos dizer que os reis de Israel são clementes. Ponhamos sacos sobre nossos rins e cordas ao nosso pescoço e vamos ter com o rei de Israel. Talvez ele te poupe a vida”.

[[v11-20-32]]

^<<v11-20-32,32>>^ Cingiram-se, pois, com sacos pelos rins, puseram cordas em volta do pescoço e apresentaram-se ao rei de Israel, dizendo: “Teu servo Ben-Adad roga-te: Concede-me a vida!”. “Ele ainda está vivo?. – perguntou Acab –; mas ele é meu irmão!”.

[[v11-20-33]]

^<<v11-20-33,33>>^ Tomando bom augúrio dessas palavras, os sírios tomaram logo a palavra de sua boca e disseram-lhe: “Ben-Adad é teu irmão!”. “traga-o a mim” – disse o rei. Veio Ben-Adad à presença de Acab e este mandou-o subir ao seu carro.

[[v11-20-34]]

^<<v11-20-34,34>>^ “Vou restituir-te – disse Ben-Adad – as cidades que meu pai tomou do teu. Terás um quarteirão em Damasco, como meu pai o tinha em Samaria.” “Eu –, disse Acab –, feita essa aliança, te deixarei partir.” Acab fez um tratado com Ben-Adad e deixou-o ir livre.^&#42;1^

[[v11-20-35]]

^<<v11-20-35,35>>^ Então, um dos filhos dos profetas disse ao seu companheiro, por ordem do Senhor: “Fere-me”. Mas o outro recusou.^&#42;1^

[[v11-20-36]]

^<<v11-20-36,36>>^ “Porque não ouviste a voz do Senhor – disse-lhe o primeiro –, logo que me tiveres deixado, serás morto por um leão.” Mal se havia afastado, um leão o encontrou e o matou.

[[v11-20-37]]

^<<v11-20-37,37>>^ O profeta, encontrando depois outro homem, disse-lhe: “Fere-me”. Este homem lançou-se contra ele e o feriu.

[[v11-20-38]]

^<<v11-20-38,38>>^ Então, postou-se o profeta no caminho por onde devia passar o rei, pondo nos olhos uma faixa que o tornava irreconhecível.

[[v11-20-39]]

^<<v11-20-39,39>>^ Ao passar o rei, gritou-lhe: “Teu servo estava em pleno combate, quando alguém lhe trouxe um homem, dizendo: ‘Guarda este homem! Se ele escapar, a tua vida responderá pela sua ou então pagarás um talento de prata’.

[[v11-20-40]]

^<<v11-20-40,40>>^ Mas andando o teu servo ocupado daqui e dali, o prisioneiro desapareceu”. O rei de Israel disse-lhe: “Esta é a tua sentença; tu mesmo a pronunciaste”.

[[v11-20-41]]

^<<v11-20-41,41>>^ Então, o outro tirou subitamente a faixa que lhe cobria os olhos e o rei viu que ele era um dos profetas.

[[v11-20-42]]

^<<v11-20-42,42>>^ Ele disse ao rei: “Eis o que diz o Senhor: ‘Pois que deixaste escapar de tuas mãos o homem que eu tinha votado ao interdito, tua vida responderá pela sua e teu povo pelo seu povo’.”

[[v11-20-43]]

^<<v11-20-43,43>>^ O rei de Israel voltou para a sua casa, sombrio e irritado, e chegou a Samaria.

'''

xref:011-i-reis/011-i-reis-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-i-reis/011-i-reis-021.adoc#v11-21-0[Próximo Capítulo &#62;]