include::./index.adoc[]

[[v11-16-0]]
=== I Reis, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Reis 16 trata principalmente sobre a sucessão de reis em Israel e em Judá, e sobre os pecados cometidos por esses reis, que levaram à sua queda e à desgraça de seus reinos. Abaixo, seguem cinco versículos da Bíblia que abordam temas semelhantes aos de 1 Reis 16:
* Provérbios 14:34: "A justiça exalta uma nação, mas o pecado é a vergonha de qualquer povo." Este versículo destaca a importância da justiça e da retidão em uma nação, e como o pecado pode trazer vergonha e ruína.
* Ezequiel 22:30: "Procurei entre eles alguém que construísse um muro e se colocasse na brecha diante de mim e em favor desta terra, para que eu não a destruísse, mas não encontrei nenhum." Este versículo fala sobre como Deus procurou alguém que pudesse interceder por seu povo, mas não encontrou ninguém. Isso pode ser aplicado ao contexto de 1 Reis 16, em que os reis de Israel e Judá não foram capazes de proteger seus reinos da destruição devido aos seus pecados.
* Salmos 89:30-32: "Se os seus filhos abandonarem a minha lei e não seguirem as minhas ordenanças, se violarem os meus decretos e não guardarem os meus mandamentos, então castigarei com vara os seus pecados e com açoites a sua iniquidade." Este versículo fala sobre as consequências do pecado e da desobediência, que incluem punição e disciplina.
* Jeremias 22:24-30: Este trecho do livro de Jeremias fala sobre o rei Jeconias, que foi considerado um rei ímpio e injusto. Deus declara que ele será amaldiçoado e que sua descendência não terá sucesso como reis. Isso se relaciona com 1 Reis 16, em que vários reis ímpios são mencionados e que, por causa de seus pecados, levaram à queda de seus reinos.
* 2 Crônicas 7:14: "Se o meu povo, que se chama pelo meu nome, se humilhar, orar e buscar a minha face e se afastar dos seus maus caminhos, então eu ouvirei dos céus, perdoarei os seus pecados e curarei a sua terra." Este versículo fala sobre a importância do arrependimento e da busca por Deus, e como isso pode levar à cura e restauração da terra. Isso pode ser aplicado ao contexto de 1 Reis 16, em que os reis de Israel e Judá poderiam ter evitado a queda de seus reinos se tivessem se arrependido de seus pecados e buscado a Deus.
****

[[v11-16-1]]

^<<v11-16-1,1>>^ A palavra do Senhor foi dirigida a Jeú, filho de Hanani, contra Baasa, nestes termos:

[[v11-16-2]]

^<<v11-16-2,2>>^ “Levantei-te do pó e estabeleci-te príncipe do meu povo de Israel. Tu, porém, andaste pelo caminho de Jeroboão e levaste meu povo de Israel a cometer pecados que excitam a minha cólera.

[[v11-16-3]]

^<<v11-16-3,3>>^ Por isso, vou varrer Baasa e sua casa e farei da sua casa o que fiz da casa de Jeroboão, filho de Nabat.

[[v11-16-4]]

^<<v11-16-4,4>>^ Todo membro da família de Baasa que morrer na cidade será comido pelos cães; o que morrer no campo, será comido pelas aves do céu”.

[[v11-16-5]]

^<<v11-16-5,5>>^ O restante da história de Baasa, suas ações e seus grandes feitos, tudo isso se acha consignado no Livro das Crônicas dos reis de Israel.

[[v11-16-6]]

^<<v11-16-6,6>>^ Baasa adormeceu com seus pais e foi enterrado em Tersa. Seu filho Ela sucedeu-lhe no trono.

[[v11-16-7]]

^<<v11-16-7,7>>^ O oráculo do Senhor, transmitido pelo profeta Jeú, filho de Hanani, fora pronunciado contra Baasa e sua casa, não só por causa de todo o mal que ele tinha feito aos olhos do Senhor, irritando-o com o seu proceder e imitando a casa de Jeroboão, mas também porque Baasa tinha destruído essa casa.

[[v11-16-8]]

^<<v11-16-8,8>>^ No vigésimo sexto ano de Asa, rei de Judá, Ela, filho de Baasa, tornou-se rei de Israel. Residia em Tersa e reinou dois anos.

[[v11-16-9]]

^<<v11-16-9,9>>^ Seu servo Zambri, que comandava a metade de sua cavalaria, conspirou contra ele. Numa ocasião em que ele bebia e se embriagava em Tersa, na casa de Arsa, intendente de seu palácio nessa cidade,

[[v11-16-10]]

^<<v11-16-10,10>>^ entrou Zambri e o assassinou, sucedendo-lhe no trono, no vigésimo sétimo ano de Asa, rei de Judá.

[[v11-16-11]]

^<<v11-16-11,11>>^ Logo que ficou rei e sentou-se no trono, mandou exterminar toda a casa de Baasa, não deixando vivo nenhum filho varão, nenhum parente, nenhum amigo.

[[v11-16-12]]

^<<v11-16-12,12>>^ Desse modo, exterminou toda a casa de Baasa, assim como o Senhor o predissera contra Baasa pela boca do profeta Jeú.

[[v11-16-13]]

^<<v11-16-13,13>>^ Tal foi o castigo de todos os pecados que Baasa e seu filho Ela tinham cometido e levado Israel a cometer, provocando com o culto dos ídolos a cólera do Senhor, Deus de Israel.

[[v11-16-14]]

^<<v11-16-14,14>>^ O restante da história de Ela e suas ações, tudo está consignado no Livro das Crônicas dos reis de Israel.

[[v11-16-15]]

^<<v11-16-15,15>>^ No vigésimo sétimo ano de Asa, rei de Judá, Zambri reinou em Tersa durante sete dias. O exército sitiava Gebeton dos filisteus.

[[v11-16-16]]

^<<v11-16-16,16>>^ Quando o exército, que estava acampado ali, ouviu dizer que Zambri tinha conspirado contra o rei e o assassinara, todo o Israel constituiu imediatamente como seu rei o general Amri.

[[v11-16-17]]

^<<v11-16-17,17>>^ Este partiu de Gebeton com todo o Israel e veio sitiar Tersa.

[[v11-16-18]]

^<<v11-16-18,18>>^ Zambri, vendo a cidade tomada, retirou-se para o fortim do palácio real e incendiou o palácio. Morreu assim

[[v11-16-19]]

^<<v11-16-19,19>>^ pelos pecados que tinha cometido, fazendo o mal aos olhos do Senhor, imitando o proceder de Jeroboão e entregando-se ao pecado ao qual Jeroboão arrastara Israel.

[[v11-16-20]]

^<<v11-16-20,20>>^ O restante da história de Zambri e sua conjuração, tudo está consignado no Livro das Crônicas dos reis de Israel.

[[v11-16-21]]

^<<v11-16-21,21>>^ Então se dividiu o povo de Israel em duas facções: metade era por Tebni, filho de Ginet e queria fazê-lo rei e metade por Amri.

[[v11-16-22]]

^<<v11-16-22,22>>^ O partido de Amri prevaleceu contra o de Tebni, filho de Ginet. Tebni morreu e reinou Amri.

[[v11-16-23]]

^<<v11-16-23,23>>^ No trigésimo primeiro ano de Asa, rei de Judá, Amri tornou-se rei de Israel e reinou durante doze anos. Depois de ter reinado seis anos em Tersa,

[[v11-16-24]]

^<<v11-16-24,24>>^ comprou de Semer o monte de Samaria por duzentos talentos de prata. Construiu uma cidade nesse monte e chamou-a Samaria, do nome de Semer, a quem pertencera o monte.

[[v11-16-25]]

^<<v11-16-25,25>>^ Amri fez o mal aos olhos do Senhor, mais ainda que todos os seus predecessores.

[[v11-16-26]]

^<<v11-16-26,26>>^ Andou por todo o caminho de Jeroboão, filho de Nabat e nos pecados com que este fizera pecar Israel, provocando com seus ídolos a cólera do Senhor, Deus de Israel.

[[v11-16-27]]

^<<v11-16-27,27>>^ O restante da história de Amri, suas ações e seus grandes feitos, tudo isso se acha consignado no Livro das Crônicas dos reis de Israel.

[[v11-16-28]]

^<<v11-16-28,28>>^ Amri adormeceu com seus pais e foi sepultado em Samaria. Seu filho Acab sucedeu-lhe no trono.

[[v11-16-29]]

^<<v11-16-29,29>>^ No trigésimo oitavo ano de Asa, rei de Judá, Acab, filho de Amri, tornou-se rei de Israel e reinou vinte e dois anos sobre Israel em Samaria.

[[v11-16-30]]

^<<v11-16-30,30>>^ Acab, filho de Amri, fez o mal aos olhos do Senhor e mais ainda que todos os seus predecessores.

[[v11-16-31]]

^<<v11-16-31,31>>^ Como se lhe não bastasse o andar nos pecados de Jeroboão, filho de Nabat, desposou ainda Jezabel, filha de Etbaal, rei dos sidônios e chegou até a render culto a Baal, prostrando-se diante dele.

[[v11-16-32]]

^<<v11-16-32,32>>^ Erigiu um altar a Baal no templo que lhe edificou em Samaria.

[[v11-16-33]]

^<<v11-16-33,33>>^ Acab fez também a asserá, irritando assim o Senhor, Deus de Israel, mais ainda que todos os seus predecessores no trono de Israel.^&#42;1^

[[v11-16-34]]

^<<v11-16-34,34>>^ No tempo de Acab, Hiel de Betel reconstruiu Jericó. Lançou-lhe os alicerces ao preço de Abirão, seu primogênito e pôs-lhe as portas ao preço de Segub, seu último filho, assim como o Senhor o predissera pela boca de Josué, filho de Nun.^&#42;1^

'''

xref:011-i-reis/011-i-reis-015.adoc#v11-15-0[&#60; Capítulo Anterior] | <<v11-16-0,Topo>> | xref:011-i-reis/011-i-reis-017.adoc#v11-17-0[Próximo Capítulo &#62;]