include::./index.adoc[]

[[v11-10-0]]
=== I Reis, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 10 de 1 Reis descreve a visita da rainha de Sabá a Salomão, após ouvir falar de sua sabedoria e riqueza. Durante a visita, Salomão demonstra sua sabedoria em resposta às perguntas da rainha e mostra a ela suas riquezas e o Templo que construiu. Os seguintes versículos da Bíblia estão relacionados com os temas abordados em 1 Reis 10:
* Provérbios 1:7: "O temor do Senhor é o princípio do conhecimento; mas os insensatos desprezam a sabedoria e a instrução." Este versículo destaca a importância do temor a Deus e da sabedoria divina, que é demonstrada por Salomão na visita da rainha de Sabá.
* 2 Crônicas 9:1: "Ora, a rainha de Sabá, ouvindo a fama de Salomão, veio a Jerusalém para prová-lo com questões difíceis; trazia consigo um grande séquito, e camelos carregados de especiarias, e muitíssimo ouro, e pedras preciosas." Este versículo é uma referência à visita da rainha de Sabá a Salomão, que é o tema central de 1 Reis 10.
* Salmos 72:10-11: "Os reis de Társis e das ilhas trarão presentes; os reis de Sabá e de Seba oferecerão dons. E todos os reis se prostrarão diante dele; todas as nações o servirão." Este Salmo profetiza sobre o reinado de um rei justo e poderoso, que é uma referência a Salomão e é relacionado à sua visita da rainha de Sabá.
* 1 Coríntios 3:12-14: "E, se alguém sobre este fundamento formar um edifício de ouro, prata, pedras preciosas, madeira, feno, palha, a obra de cada um se manifestará; pois o Dia a demonstrará, porque será revelado no fogo, e o fogo provará qual seja a obra de cada um." Este versículo destaca a ideia de que as riquezas terrenas, como as mostradas por Salomão à rainha de Sabá, não são duradouras e não são o verdadeiro tesouro.
* Mateus 6:19-21: "Não ajunteis tesouros na terra, onde a traça e a ferrugem os consomem, e onde os ladrões minam e roubam; mas ajuntai tesouros no céu, onde nem a traça nem a ferrugem os consomem, e onde os ladrões não minam nem roubam. Porque onde estiver o teu tesouro, aí estará também o teu coração." Este versículo destaca a ideia de que as riquezas verdadeiras são as que estão no céu e que nosso foco deve estar em Deus, não nas riquezas materiais.
****

[[v11-10-1]]

^<<v11-10-1,1>>^ A rainha de Sabá, tendo ouvido falar de Salomão e da glória do Senhor, veio prová-lo com enigmas.^&#42;1^

[[v11-10-2]]

^<<v11-10-2,2>>^ Chegou a Jerusalém com uma numerosa comitiva, com camelos carregados de aromas e uma grande quantidade de ouro e pedras preciosas. Apresentou-se diante do rei Salomão e disse-lhe tudo o que tinha no espírito.

[[v11-10-3]]

^<<v11-10-3,3>>^ A tudo respondeu o rei. Nenhuma de suas perguntas lhe pareceu obscura e deu solução a todas.

[[v11-10-4]]

^<<v11-10-4,4>>^ Quando a rainha de Sabá viu toda a sabedoria de Salomão, a casa que ele tinha feito,

[[v11-10-5]]

^<<v11-10-5,5>>^ os manjares de sua mesa, os apartamentos de seus servos, as habitações e uniformes de seus oficiais, os copeiros do rei e os holocaustos que ele oferecia no Templo do Senhor, ficou estupefata

[[v11-10-6]]

^<<v11-10-6,6>>^ e disse ao rei: “É bem verdade o que ouvi a teu respeito e de tua sabedoria, na minha terra.

[[v11-10-7]]

^<<v11-10-7,7>>^ Eu não quis acreditar no que me diziam, antes de vir aqui e ver com os meus próprios olhos. Mas eis que não contavam nem a metade: tua sabedoria e tua opulência são muito maiores do que a fama que havia chegado até mim.

[[v11-10-8]]

^<<v11-10-8,8>>^ Felizes os teus homens, felizes os teus servos que estão sempre contigo e ouvem a tua sabedoria!

[[v11-10-9]]

^<<v11-10-9,9>>^ Bendito seja o Senhor, teu Deus, a quem aprouve colocar-te sobre o trono de Israel. Porque o Senhor amou Israel para sempre, por isso constituiu-te rei para governares com justiça e equidade”.

[[v11-10-10]]

^<<v11-10-10,10>>^ Presenteou o rei com cento e vinte talentos de ouro e grande quantidade de perfumes e pedras preciosas. Não apareceu jamais uma quantidade de aromas tão grande como a que a rainha de Sabá deu ao rei Salomão.

[[v11-10-11]]

^<<v11-10-11,11>>^ A frota de Hiram, que trazia o ouro de Ofir, trouxe também grande quantidade de madeira de sândalo e pedras preciosas.

[[v11-10-12]]

^<<v11-10-12,12>>^ Com este sândalo fez o rei balaustradas para o Templo do Senhor, assim como harpas e flautas para os músicos do palácio real. E desde então não se transportou mais dessa madeira de sândalo e não se viu mais até o dia de hoje.

[[v11-10-13]]

^<<v11-10-13,13>>^ O rei Salomão deu à rainha de Sabá tudo o que ela desejou e pediu, além dos presentes que ele mesmo lhe fez com real liberalidade. E a rainha retomou o caminho de volta com a sua comitiva.

[[v11-10-14]]

^<<v11-10-14,14>>^ O peso de ouro, que era levado anualmente a Salomão, era de seiscentos e sessenta e seis talentos,

[[v11-10-15]]

^<<v11-10-15,15>>^ sem contar o que ele recebia dos vendedores ambulantes e do tráfico dos negociantes, dos reis da Arábia e de todos os governadores da terra.

[[v11-10-16]]

^<<v11-10-16,16>>^ O rei Salomão mandou fazer duzentos escudos de ouro batido, empregando em cada um seiscentos siclos de ouro,

[[v11-10-17]]

^<<v11-10-17,17>>^ e trezentos escudos menores de ouro batido, empregando em cada um três minas de ouro. E colocou-os no pavilhão da Floresta do Líbano.

[[v11-10-18]]

^<<v11-10-18,18>>^ Mandou fazer também um grande trono de marfim revestido de ouro fino.

[[v11-10-19]]

^<<v11-10-19,19>>^ O trono tinha seis degraus; a parte superior do espaldar era arredondada; havia de cada lado do assento dois braços, junto dos quais se achavam figuras de dois leões;

[[v11-10-20]]

^<<v11-10-20,20>>^ havia outros doze leões postos nos degraus, seis de cada lado. Nunca se fez coisa semelhante em nenhum outro reino.

[[v11-10-21]]

^<<v11-10-21,21>>^ Todas as taças do rei Salomão eram de ouro, assim como todo o vasilhame do pavilhão da Floresta do Líbano. Não havia nada feito de prata, porque não se fazia caso algum dela no tempo de Salomão.

[[v11-10-22]]

^<<v11-10-22,22>>^ O rei tinha no mar navios de Társis, que acompanhavam a frota de Hiram. De três em três anos, a frota de Társis trazia ouro, prata, marfim, macacos e pavões.^&#42;1^

[[v11-10-23]]

^<<v11-10-23,23>>^ O rei Salomão sobrepujou todos os reis da terra em riquezas e opulência.

[[v11-10-24]]

^<<v11-10-24,24>>^ Todos buscavam a presença de Salomão para ouvir a sabedoria que o Senhor lhe tinha dado.

[[v11-10-25]]

^<<v11-10-25,25>>^ Todos os anos cada um lhe levava presentes: objetos de prata e ouro, vestes, armas, aromas, cavalos e burros.

[[v11-10-26]]

^<<v11-10-26,26>>^ Contou Salomão os seus carros e cavaleiros: havia mil e quatrocentos carros e doze mil cavaleiros, que distribuiu pelas cidades-entrepostos dos carros e por Jerusalém, junto dele.

[[v11-10-27]]

^<<v11-10-27,27>>^ Graças ao rei, tornou-se a prata em Jerusalém tão comum como as pedras e os cedros tão numerosos como os sicômoros que crescem na planície.

[[v11-10-28]]

^<<v11-10-28,28>>^ Vinham do Egito os cavalos de Salomão; uma caravana de mercadores do rei ia comprá-los ali por um preço estabelecido.

[[v11-10-29]]

^<<v11-10-29,29>>^ Uma quadriga trazida do Egito custava-lhe seiscentos siclos de prata e um cavalo cento e cinquenta siclos. Do mesmo modo exportavam cavalos para todos os reis dos hiteus e da Síria.

'''

xref:011-i-reis/011-i-reis-009.adoc#v11-9-0[&#60; Capítulo Anterior] | <<v11-10-0,Topo>> | xref:011-i-reis/011-i-reis-011.adoc#v11-11-0[Próximo Capítulo &#62;]