include::./index.adoc[]

[[v11-1-0]]
=== I Reis, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Reis 1 trata da sucessão de Davi ao trono de Israel. Quando Davi já está velho e debilitado, Adonias, seu filho mais velho, tenta usurpar o trono para si. No entanto, o profeta Natã e Bate-Seba, mãe de Salomão, interferem para garantir que o sucessor escolhido por Davi seja Salomão, o filho mais novo. Abaixo estão cinco versículos relacionados com os temas abordados em 1 Reis 1:
* Provérbios 20:29: "A glória dos jovens é a sua força; e a beleza dos velhos são as cãs." Este versículo destaca a fraqueza física que a idade avançada pode trazer, como é o caso de Davi em 1 Reis 1.
* 1 Crônicas 22:9: "Eis que um filho te nascerá, que será homem de repouso; pois lhe darei descanso de todos os seus inimigos ao redor; porque Salomão será o seu nome, e paz e sossego darei a Israel nos seus dias." Este versículo é uma profecia de Davi sobre Salomão, que se cumpre em 1 Reis 1, quando Salomão é escolhido como sucessor ao trono.
* Provérbios 31:1: "As palavras do rei Lemuel; a instrução que sua mãe lhe deu." Este versículo mostra a importância das mães na educação e formação dos filhos, como é o caso de Bate-Seba em 1 Reis 1.
* 2 Samuel 12:24: "E consolou Bate-Seba, mulher de Urias, seu filho, e a tomou por mulher, e teve com ela um filho; e chamou o seu nome Salomão; e o SENHOR o amou." Este versículo relata o nascimento de Salomão, filho de Davi e Bate-Seba, que mais tarde é escolhido como sucessor ao trono em 1 Reis 1.
* 2 Samuel 23:1-2: "Estas são as últimas palavras de Davi: Diz Davi, filho de Jessé, diz o homem que foi levantado em altura, o ungido do Deus de Jacó, e o suave em salmos de Israel. O Espírito do SENHOR falou por mim, e a sua palavra está na minha boca." Estes versículos mostram a autoridade divina de Davi como rei de Israel e, portanto, a importância de sua escolha de sucessor em 1 Reis 1.
****

[[v11-1-1]]

^<<v11-1-1,1>>^ O rei Davi estava velho e avançado em idade; por mais que o cobrissem de roupas, não se aquecia.

[[v11-1-2]]

^<<v11-1-2,2>>^ Seus servos disseram-lhe: “Busquemos para nosso senhor, o rei, uma donzela virgem que sirva o rei, tenha cuidado dele e durma em seu seio para que ele se aqueça”.

[[v11-1-3]]

^<<v11-1-3,3>>^ Procuraram, pois, em toda a terra de Israel, uma donzela formosa; encontraram Abisag, a sunamita, e a conduziram à presença do rei.

[[v11-1-4]]

^<<v11-1-4,4>>^ Essa donzela era muito formosa. Ela cuidava do rei e o servia, mas ele não a possuiu.

[[v11-1-5]]

^<<v11-1-5,5>>^ Ora, Adonias, filho de Hagit, encheu-se de orgulho e exclamou: “Sou eu quem reinará”. Preparou para si uma carruagem e cavalos e tomou uma escolta de cinquenta homens.

[[v11-1-6]]

^<<v11-1-6,6>>^ Nunca seu pai o contrariou, dizendo: “Por que fazes isso?”. Além disso, ele era muito belo e (na idade) seguia imediatamente a Absalão.

[[v11-1-7]]

^<<v11-1-7,7>>^ Tendo feito reuniões com Joab, filho de Sárvia, e com o sacerdote Abiatar, esses tornaram-se seus adeptos.

[[v11-1-8]]

^<<v11-1-8,8>>^ O sacerdote Sadoc, porém, bem como Banaías, filho de Joiada, o profeta Natã, Semei e Rei, bem como os valentes de Davi, não abraçaram o seu partido.

[[v11-1-9]]

^<<v11-1-9,9>>^ Adonias, tendo imolado ovelhas, bois e bezerros cevados junto à pedra de Zoélet, ao lado de En-Roguel, convidou todos os seus irmãos, filhos do rei e todos os de Judá que estavam a serviço do rei.

[[v11-1-10]]

^<<v11-1-10,10>>^ Mas não convidou o profeta Natã, nem Banaías, nem os valentes, nem o seu irmão Salomão.

[[v11-1-11]]

^<<v11-1-11,11>>^ Disse Natã a Betsabeia, mãe de Salomão: “Não soubeste que Adonias, filho de Hagit, se proclamou rei, sem que o saiba Davi, nosso senhor?

[[v11-1-12]]

^<<v11-1-12,12>>^ Escuta, vou dar-te um conselho para que salves a tua vida e a de teu filho Salomão.

[[v11-1-13]]

^<<v11-1-13,13>>^ Vai ter com o rei Davi e dize-lhe: ‘Ó rei, meu senhor, não juraste à tua serva que Salomão, meu filho, reinaria depois de ti e se sentaria no teu trono? Por que então Adonias se proclamou rei?’.

[[v11-1-14]]

^<<v11-1-14,14>>^ Enquanto estiveres falando assim ao rei, entrarei e confirmarei o que tiveres dito”.

[[v11-1-15]]

^<<v11-1-15,15>>^ Foi Betsabeia ter com o rei no seu quarto. O rei estava já muito velho e Abisag, a sunamita, cuidava dele.

[[v11-1-16]]

^<<v11-1-16,16>>^ Betsabeia inclinou-se e prostrou-se diante do rei. Este disse-lhe: “Que queres?”.

[[v11-1-17]]

^<<v11-1-17,17>>^ Ela respondeu: “Meu senhor, prometeste com juramento à tua serva que meu filho Salomão reinaria depois de ti e se sentaria no teu trono.

[[v11-1-18]]

^<<v11-1-18,18>>^ Ora, eis que Adonias se proclamou rei, sem que o saiba o rei, meu senhor.

[[v11-1-19]]

^<<v11-1-19,19>>^ Imolou bois, bezerros cevados e grande quantidade de ovelhas e convidou todos os príncipes, o sacerdote Abiatar e o general Joab, mas não convidou o teu servo Salomão.

[[v11-1-20]]

^<<v11-1-20,20>>^ Ó rei, meu senhor, todo o Israel tem os olhos postos em ti, esperando que declares quem há de tomar o teu lugar no trono depois de ti.

[[v11-1-21]]

^<<v11-1-21,21>>^ Do contrário, logo que o rei, meu senhor, dormir com os seus pais, eu e meu filho Salomão seremos tratados como criminosos”.

[[v11-1-22]]

^<<v11-1-22,22>>^ Falava ela ainda ao rei, quando se apresentou o profeta Natã.

[[v11-1-23]]

^<<v11-1-23,23>>^ Disseram ao rei: “Está aí o profeta Natã”. Ele entrou e prostrou-se com o rosto por terra diante do rei.

[[v11-1-24]]

^<<v11-1-24,24>>^ Em seguida, disse: “Ó rei, meu senhor, porventura declaraste: Adonias reinará depois de mim e se sentará no meu trono?

[[v11-1-25]]

^<<v11-1-25,25>>^ Pois ele desceu hoje para imolar bois, bezerros cevados e grande quantidade de ovelhas, tendo convidado todos os príncipes, os generais e o sacerdote Abiatar, os quais estão comendo e bebendo com ele e gritando: ‘Viva o rei Adonias!’.

[[v11-1-26]]

^<<v11-1-26,26>>^ Não fomos, porém, convidados nem eu, teu servo, nem o sacerdote Sadoc, nem Banaías, filho de Joiada, nem teu servo Salomão.

[[v11-1-27]]

^<<v11-1-27,27>>^ Será do agrado de meu senhor e rei que assim se faça? Porque não deste a conhecer a teus servos quem deverá sentar-se depois de ti no trono do rei, meu senhor”.

[[v11-1-28]]

^<<v11-1-28,28>>^ O rei respondeu: “Chamai-me Betsabeia”. Ela entrou e ficou de pé diante dele.

[[v11-1-29]]

^<<v11-1-29,29>>^ O rei fez-lhe este juramento: “Pela vida de Deus que me livrou de toda angústia,

[[v11-1-30]]

^<<v11-1-30,30>>^ o que te jurei pelo Senhor, Deus de Israel, dizendo: ‘Teu filho Salomão reinará depois de mim e se sentará no meu trono em meu lugar, isso vou cumprir hoje’.”

[[v11-1-31]]

^<<v11-1-31,31>>^ Betsabeia inclinou-se diante do rei, prostrando-se com a face por terra e disse: “Viva o rei Davi, meu senhor, para sempre!”.

[[v11-1-32]]

^<<v11-1-32,32>>^ O rei Davi disse: “Chamai-me o sacerdote Sadoc, o profeta Natã e Banaías, filho de Joiada”. Tendo-se eles apresentado diante do rei, este disse-lhes:

[[v11-1-33]]

^<<v11-1-33,33>>^ “Tomai convosco os servos de vosso amo, fazei montar na minha mula o meu filho Salomão e levai-o a Gion.^&#42;1^

[[v11-1-34]]

^<<v11-1-34,34>>^ Ali o sacerdote Sadoc e o profeta Natã o ungirão rei de Israel. Tocareis então a trombeta e direis: ‘Viva o rei Salomão!’.

[[v11-1-35]]

^<<v11-1-35,35>>^ Voltareis depois atrás dele e ele virá sentar-se no meu trono para reinar em meu lugar; pois é a ele que estabeleço chefe de Israel e de Judá”.

[[v11-1-36]]

^<<v11-1-36,36>>^ Banaías, filho de Joiada, respondeu ao rei: “Assim seja! Assim queira ordenar o Senhor, Deus de meu senhor e rei!

[[v11-1-37]]

^<<v11-1-37,37>>^ Esteja ele com Salomão assim como esteve com o rei, meu senhor, e eleve o seu trono ainda acima do trono de meu senhor, o rei Davi!”.

[[v11-1-38]]

^<<v11-1-38,38>>^ O sacerdote Sadoc desceu com o profeta Natã, Banaías, filho de Joiada, os cereteus e os feleteus. Fizeram montar Salomão na mula de Davi e conduziram-no a Gion.

[[v11-1-39]]

^<<v11-1-39,39>>^ Tomou o sacerdote Sadoc no tabernáculo o chifre de óleo e ungiu com ele Salomão. A trombeta soou e todo o povo pôs-se a gritar: “Viva o rei Salomão!”.

[[v11-1-40]]

^<<v11-1-40,40>>^ Depois toda a gente acompanhou-o em cortejo, tocando flauta e fazendo grandes festas, de modo que a terra vibrava com suas aclamações.^&#42;1^

[[v11-1-41]]

^<<v11-1-41,41>>^ Quando Adonias e seus convivas terminavam o seu banquete, ouviram aquele clamor. Joab, ouvindo soar a trombeta, disse: “Por que esse barulho de cidade alvoroçada?”.

[[v11-1-42]]

^<<v11-1-42,42>>^ Falava ainda, quando sobreveio Jônatas, filho do sacerdote Abiatar. Adonias disse-lhe: “Vem, pois tu és um homem valente e trazes certamente boas notícias”.

[[v11-1-43]]

^<<v11-1-43,43>>^ “Sim – respondeu Jônatas –, é verdade que o rei Davi, meu senhor, proclamou rei a Salomão.

[[v11-1-44]]

^<<v11-1-44,44>>^ Enviou com ele o sacerdote Sadoc, o profeta Natã, Banaías, filho de Joiada, juntamente com os cereteus e os feleteus, e estes fizeram-no montar na mula do rei.

[[v11-1-45]]

^<<v11-1-45,45>>^ O sacerdote Sadoc e o profeta Natã ungiram-no rei em Gion. Dali voltaram cheios de alegria e a cidade entrou em alvoroço; essa é a algazarra que ouviste.

[[v11-1-46]]

^<<v11-1-46,46>>^ E Salomão até já se assentou no trono do reino.

[[v11-1-47]]

^<<v11-1-47,47>>^ Além disso, os servos do rei foram felicitar o rei Davi, meu senhor, dizendo: ‘Que o teu Deus torne o nome de Salomão maior que o teu e eleve o seu trono ainda acima do teu!’. O rei prostrou-se então sobre o seu leito e disse:

[[v11-1-48]]

^<<v11-1-48,48>>^ ‘Bendito seja o Senhor, Deus de Israel, que hoje pôs sobre o meu trono um sucessor, vendo-o eu com os meus próprios olhos!’.”

[[v11-1-49]]

^<<v11-1-49,49>>^ Os convidados de Adonias, aterrorizados, levantaram-se e foram cada um para o seu lado.

[[v11-1-50]]

^<<v11-1-50,50>>^ Adonias, temendo Salomão, levantou-se também e foi abraçar-se com os chifres do altar.^&#42;1^

[[v11-1-51]]

^<<v11-1-51,51>>^ Disseram-no a Salomão, nestes termos: “Eis que Adonias, temendo o rei Salomão, foi abraçar-se com os chifres do altar, dizendo: ‘Jure-me hoje o rei Salomão que ele não fará morrer o seu servo à espada!’.”

[[v11-1-52]]

^<<v11-1-52,52>>^ “Se ele se mostrar um homem valente – respondeu Salomão –, não lhe cairá por terra um só de seus cabelos; mas se nele se encontrar maldade, morrerá”.

[[v11-1-53]]

^<<v11-1-53,53>>^ O rei Salomão mandou mensageiros e o fizeram descer do altar. Ele veio e prostrou-se diante do rei, que lhe disse: “Volta para a tua casa”.

'''

xref:010-ii-samuel/010-ii-samuel-024.adoc#v10-24-0[&#60; Capítulo Anterior] | <<v11-1-0,Topo>> | xref:011-i-reis/011-i-reis-002.adoc#v11-2-0[Próximo Capítulo &#62;]