include::./index.adoc[]

[[v47-21-0]]
=== São Mateus, 21
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Mateus 21 apresenta a entrada triunfal de Jesus em Jerusalém, bem como a purificação do templo e a controvérsia com os líderes religiosos. Alguns dos temas principais deste capítulo incluem a autoridade de Jesus, a sua missão messiânica e a rejeição dos líderes religiosos. A seguir estão cinco versículos relacionados com esses temas:
* Isaías 62:11: "Eis que o Senhor fez ouvir até às extremidades da terra: Dizei à filha de Sião: Eis que vem o teu Salvador; vem com ele a sua recompensa, e diante dele, o seu galardão." Este versículo profético de Isaías descreve a vinda do Salvador, que é uma referência ao Messias. Jesus é o cumprimento desta profecia e o seu papel como o Salvador é enfatizado em São Mateus 21.
* Salmos 118:22-23: "A pedra que os construtores rejeitaram, essa foi posta como pedra angular. Isso veio do Senhor e é maravilhoso aos nossos olhos." Jesus citou este versículo quando falava sobre a sua rejeição pelos líderes religiosos. Embora eles o tenham rejeitado, ele se tornou a pedra angular da igreja e a fonte da salvação.
* Isaías 56:7: "Fá-los-ei chegar ao meu santo monte e alegrá-los-ei na minha casa de oração; os seus holocaustos e os seus sacrifícios serão aceitos no meu altar; porque a minha casa será chamada casa de oração para todos os povos." Este versículo profético de Isaías fala da casa de oração como um lugar de encontro com Deus para todas as nações. Jesus citou este versículo quando expulsou os vendedores do templo, indicando que o templo deveria ser um lugar de adoração a Deus e não de comércio.
* Salmos 69:9: "Pois o zelo da tua casa me consome, e as afrontas dos que te afrontam caem sobre mim." Este salmo de Davi fala do zelo de Deus pela sua casa e do sofrimento do justo por causa da sua fidelidade a Deus. Jesus demonstrou zelo pela casa de Deus quando expulsou os vendedores do templo, e mais tarde sofreu por sua fidelidade a Deus.
* Isaías 53:3: "Era desprezado e o mais rejeitado entre os homens, homem de dores e experimentado nos sofrimentos; e, como um de quem os homens escondiam o rosto, era desprezado, e não fizemos dele caso algum." Este versículo profético de Isaías descreve o sofrimento do Servo Sofredor, que é uma figura messiânica. Jesus cumpriu esta profecia ao ser rejeitado e sofrer pelos pecados da humanidade. A sua rejeição pelos líderes religiosos é um tema importante em São Mateus 21.
****

[[v47-21-1]]

^<<v47-21-1,1>>^ Aproximavam-se de Jerusalém. Quando chegaram a Betfagé, perto do monte das Oliveiras, Jesus enviou dois de seus discípulos,^&#42;1^

[[v47-21-2]]

^<<v47-21-2,2>>^ dizendo-lhes: “Ide à aldeia que está defronte. Encontrareis logo uma jumenta amarrada e com ela seu jumentinho. Desamarrai-os e trazei-mos.

[[v47-21-3]]

^<<v47-21-3,3>>^ Se alguém vos disser qualquer coisa, respondei-lhe que o Senhor necessita deles e que ele sem demora os devolverá”.

[[v47-21-4]]

^<<v47-21-4,4>>^ Assim, neste acontecimento, cumpria-se o oráculo do profeta:

[[v47-21-5]]

^<<v47-21-5,5>>^ Dizei à filha de Sião: Eis que teu rei vem a ti, cheio de doçura, montado numa jumenta, num jumentinho, filho da que leva o jugo (Zc 9,9).

[[v47-21-6]]

^<<v47-21-6,6>>^ Os discípulos foram e executaram a ordem de Jesus.

[[v47-21-7]]

^<<v47-21-7,7>>^ Trouxeram a jumenta e o jumentinho, cobriram-nos com seus mantos e fizeram-no montar.

[[v47-21-8]]

^<<v47-21-8,8>>^ Então, a multidão estendia os mantos pelo caminho, cortava ramos de árvores e espalhava-os pela estrada.

[[v47-21-9]]

^<<v47-21-9,9>>^ E toda aquela multidão, que o precedia e que o seguia, clamava: “Hosana ao filho de Davi! Bendito seja aquele que vem em nome do Senhor! Hosana no mais alto dos céus!”.^&#42;1^

[[v47-21-10]]

^<<v47-21-10,10>>^ Quando ele entrou em Jerusalém, alvoroçou-se toda a cidade, perguntando: “Quem é este?”.

[[v47-21-11]]

^<<v47-21-11,11>>^ A multidão respondia: “É Jesus, o profeta de Nazaré da Galileia”.

[[v47-21-12]]

^<<v47-21-12,12>>^ Jesus entrou no templo e expulsou dali todos aqueles que se entregavam ao comércio. Derrubou as mesas dos cambistas e os bancos dos negociantes de pombas,^&#42;1^

[[v47-21-13]]

^<<v47-21-13,13>>^ e disse-lhes: “Está escrito: Minha casa é uma casa de oração (Is 56,7), mas vós fizestes dela um covil de ladrões (Jr 7,11)!”.

[[v47-21-14]]

^<<v47-21-14,14>>^ Os cegos e os coxos vieram a ele no templo e ele os curou,

[[v47-21-15]]

^<<v47-21-15,15>>^ com grande indignação dos príncipes dos sacerdotes e dos escribas que assistiam a seus milagres e ouviam os meninos gritarem no templo: “Hosana ao filho de Davi!”.

[[v47-21-16]]

^<<v47-21-16,16>>^ Disseram-lhe eles: “Ouves o que dizem eles?”. “Perfeitamente, respondeu-lhes Jesus. Nunca lestes estas palavras: Da boca dos meninos e das crianças de peito tirastes o vosso louvor” (Sl 8,3)?.

[[v47-21-17]]

^<<v47-21-17,17>>^ Depois os deixou e saiu da cidade para hospedar-se em Betânia.

[[v47-21-18]]

^<<v47-21-18,18>>^ De manhã, voltando à cidade, teve fome.

[[v47-21-19]]

^<<v47-21-19,19>>^ Vendo uma figueira à beira do caminho, aproximou-se dela, mas só achou nela folhas; e disse-lhe: “Jamais nasça fruto de ti!”.

[[v47-21-20]]

^<<v47-21-20,20>>^ E imediatamente a figueira secou. À vista disso, os discípulos ficaram estupefatos e disseram: “Como ficou seca num instante a figueira?!”.

[[v47-21-21]]

^<<v47-21-21,21>>^ Respondeu-lhes Jesus: “Em verdade vos declaro que, se tiverdes fé e não hesitardes, não só fareis o que foi feito a esta figueira, mas ainda se disserdes a esta montanha: Levanta-te daí e atira-te ao mar, isso se fará...^&#42;1^

[[v47-21-22]]

^<<v47-21-22,22>>^ Tudo o que pedirdes com fé na oração, vós o alcançareis”.

[[v47-21-23]]

^<<v47-21-23,23>>^ Dirigiu-se Jesus ao templo. E, enquanto ensinava, os príncipes dos sacerdotes e os anciãos do povo aproximaram-se e perguntaram-lhe: “Com que direito fazes isso? Quem te deu essa autoridade?”.

[[v47-21-24]]

^<<v47-21-24,24>>^ Respondeu-lhes Jesus: “Eu vos proporei também uma questão. Se responderdes, eu vos direi com que direito o faço.

[[v47-21-25]]

^<<v47-21-25,25>>^ Donde procedia o batismo de João: do céu ou dos homens?”. Ora, eles raciocinavam entre si: “Se respondermos: Do céu, ele nos dirá: Por que não crestes nele?

[[v47-21-26]]

^<<v47-21-26,26>>^ E se dissermos: Dos homens, é de temer-se a multidão, porque todo o mundo considera João como profeta”.

[[v47-21-27]]

^<<v47-21-27,27>>^ Responderam a Jesus: “Não sabemos”. “Pois eu tampouco vos digo” – retorquiu Jesus – “com que direito faço essas coisas.”

[[v47-21-28]]

^<<v47-21-28,28>>^ “Que vos parece? Um homem tinha dois filhos. Dirigindo-se ao primeiro, disse-lhe: ‘Meu filho, vai trabalhar hoje na vinha’.

[[v47-21-29]]

^<<v47-21-29,29>>^ Respondeu ele: ‘Não quero’. Mas, em seguida, tocado de arrependimento, foi.

[[v47-21-30]]

^<<v47-21-30,30>>^ Dirigindo-se depois ao outro, disse-lhe a mesma coisa. O filho respondeu: ‘Sim, pai!’. Mas não foi.^&#42;1^

[[v47-21-31]]

^<<v47-21-31,31>>^ Qual dos dois fez a vontade do pai? ‘O primeiro’ – responderam-lhe. E Jesus disse-lhes: ‘Em verdade vos digo: os publicanos e as meretrizes vos precedem no Reino de Deus!

[[v47-21-32]]

^<<v47-21-32,32>>^ João veio a vós no caminho da justiça e não crestes nele. Os publicanos, porém, e as prostitutas creram nele. E vós, vendo isso, nem fostes tocados de arrependimento para crerdes nele’.”

[[v47-21-33]]

^<<v47-21-33,33>>^ “Ouvi outra parábola: havia um pai de família que plantou uma vinha. Cercou-a com uma sebe, cavou um lagar e edificou uma torre. E, tendo-a arrendado a lavradores, deixou o país.^&#42;1^

[[v47-21-34]]

^<<v47-21-34,34>>^ Vindo o tempo da colheita, enviou seus servos aos lavradores para recolher o produto de sua vinha.

[[v47-21-35]]

^<<v47-21-35,35>>^ Mas os lavradores agarraram os servos, feriram um, mataram outro e apedrejaram o terceiro.

[[v47-21-36]]

^<<v47-21-36,36>>^ Enviou outros servos em maior número que os primeiros, e fizeram-lhes o mesmo.

[[v47-21-37]]

^<<v47-21-37,37>>^ Enfim, enviou seu próprio filho, dizendo: Hão de respeitar meu filho.

[[v47-21-38]]

^<<v47-21-38,38>>^ Os lavradores, porém, vendo o filho, disseram uns aos outros: Eis o herdeiro! Matemo-lo e teremos a sua herança!

[[v47-21-39]]

^<<v47-21-39,39>>^ Lançaram-lhe as mãos, conduziram-no para fora da vinha e o assassinaram.

[[v47-21-40]]

^<<v47-21-40,40>>^ Pois bem: quando voltar o senhor da vinha, que fará ele àqueles lavradores?”

[[v47-21-41]]

^<<v47-21-41,41>>^ Responderam-lhe: “Mandará matar sem piedade aqueles miseráveis e arrendará sua vinha a outros lavradores que lhe pagarão o produto em seu tempo”.

[[v47-21-42]]

^<<v47-21-42,42>>^ Jesus acrescentou: “Nunca lestes nas Escrituras: A pedra rejeitada pelos construtores tornou-se a pedra angular; isto é obra do Senhor, e é admirável aos nossos olhos (Sl 117,22)?

[[v47-21-43]]

^<<v47-21-43,43>>^ Por isso, vos digo: será tirado de vós o Reino de Deus, e será dado a um povo que produzirá os frutos dele.

[[v47-21-44]]

^<<v47-21-44,44>>^ [Aquele que tropeçar nesta pedra, far-se-á em pedaços; e aquele sobre quem ela cair será esmagado.]”.

[[v47-21-45]]

^<<v47-21-45,45>>^ Ouvindo isso, os príncipes dos sacerdotes e os fariseus compreenderam que era deles que Jesus falava.^&#42;1^

[[v47-21-46]]

^<<v47-21-46,46>>^ E procuravam prendê-lo; mas temeram o povo, que o tinha por um profeta.

'''

xref:047-sao-mateus/047-sao-mateus-020.adoc#v47-20-0[&#60; Capítulo Anterior] | <<v47-21-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-022.adoc#v47-22-0[Próximo Capítulo &#62;]