include::./index.adoc[]

[[v47-16-0]]
=== São Mateus, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 16 de Mateus apresenta uma série de ensinamentos e eventos importantes na vida de Jesus e de seus discípulos. Inicialmente, Jesus repreende os fariseus e saduceus que pedem um sinal do céu, indicando que eles sabem interpretar o tempo, mas não reconhecem o próprio Filho de Deus. Em seguida, ele faz uma pergunta aos seus discípulos sobre sua identidade, e Pedro responde que ele é o Cristo, o Filho do Deus vivo. Jesus então faz uma promessa a Pedro e dá instruções aos seus discípulos sobre sua missão e sobre a importância de tomar a cruz e seguir a Cristo. A seguir, cinco versículos relacionados com os temas abordados em São Mateus 16:
* João 6:68-69: "Simão Pedro respondeu: Senhor, para quem iremos? Tu tens as palavras da vida eterna. E nós temos crido e conhecido que tu és o Cristo, o Filho do Deus vivente." Assim como em Mateus 16, Pedro declara a identidade de Jesus como o Cristo, o Filho do Deus vivo.
* Marcos 8:34: "E chamando a si a multidão, com os seus discípulos, disse-lhes: Se alguém quiser vir após mim, negue-se a si mesmo, e tome a sua cruz, e siga-me." Neste versículo, Jesus dá instruções semelhantes às que ele deu aos seus discípulos em Mateus 16, sobre a importância de tomar a cruz e seguir a Cristo.
* Lucas 9:23: "E dizia a todos: Se alguém quer vir após mim, negue-se a si mesmo, e tome cada dia a sua cruz, e siga-me." Este versículo apresenta uma versão semelhante da instrução de Jesus sobre tomar a cruz e segui-lo.
* Filipenses 2:5-8: "De sorte que haja em vós o mesmo sentimento que houve também em Cristo Jesus, que, sendo em forma de Deus, não teve por usurpação ser igual a Deus, mas esvaziou-se a si mesmo, tomando a forma de servo, fazendo-se semelhante aos homens; e, achado na forma de homem, humilhou-se a si mesmo, sendo obediente até à morte, e morte de cruz." Este versículo fala sobre a humildade e obediência de Cristo, e a importância de segui-lo em sua humildade.
* Colossenses 1:15-17: "Ele é a imagem do Deus invisível, o primogênito de toda a criação; pois nele foram criadas todas as coisas nos céus e na terra, as visíveis e as invisíveis, sejam tronos, sejam dominações, sejam principados, sejam potestades; tudo foi criado por ele e para ele. Ele é antes de todas as coisas, e nele subsistem todas as coisas." Este versículo fala sobre a posição de Cristo como o Filho de Deus e o criador de todas as coisas.
****

[[v47-16-1]]

^<<v47-16-1,1>>^ Os fariseus e os saduceus achegaram-se a Jesus para submetê-lo à prova e pediram-lhe que lhes mostrasse um milagre do céu.

[[v47-16-2]]

^<<v47-16-2,2>>^ Ele lhes respondeu: “Quando vem a tarde, dizeis: Haverá bom tempo, porque o céu está avermelhado.

[[v47-16-3]]

^<<v47-16-3,3>>^ E de manhã: Hoje haverá tormenta, porque o céu está de um vermelho sombrio.

[[v47-16-4]]

^<<v47-16-4,4>>^ Hipócritas! Sabeis distinguir o aspecto do céu e não podeis discernir os sinais dos tempos? Essa raça perversa e adúltera pede um milagre! Mas não lhe será dado outro sinal senão o de Jonas!”. Depois, deixando-os, partiu.^&#42;1^

[[v47-16-5]]

^<<v47-16-5,5>>^ Ora, passando para a outra margem do lago, os discípulos haviam esquecido de levar pão.

[[v47-16-6]]

^<<v47-16-6,6>>^ Jesus disse-lhes: “Guardai-vos com cuidado do fermento dos fariseus e dos saduceus”.

[[v47-16-7]]

^<<v47-16-7,7>>^ Eles pensavam: “É que não trouxemos pão...”.

[[v47-16-8]]

^<<v47-16-8,8>>^ Jesus, penetrando nos seus pensamentos, disse-lhes: “Homens de pouca fé! Por que julgais que vos falei por não terdes pão?

[[v47-16-9]]

^<<v47-16-9,9>>^ Ainda não compreendeis? Nem vos lembrais dos cinco pães e dos cinco mil homens, e de quantos cestos recolhestes?

[[v47-16-10]]

^<<v47-16-10,10>>^ Nem dos sete pães para os quatro mil homens e de quantos cestos enchestes?

[[v47-16-11]]

^<<v47-16-11,11>>^ Por que não compreendeis que não é do pão que eu vos falava, quando vos disse: Guardai-vos do fermento dos fariseus e dos saduceus?”.

[[v47-16-12]]

^<<v47-16-12,12>>^ Então, entenderam que não dissera que se guardassem do fermento do pão, mas da doutrina dos fariseus e dos saduceus.

[[v47-16-13]]

^<<v47-16-13,13>>^ Chegando ao território de Cesareia de Filipe, Jesus perguntou a seus discípulos: “No dizer do povo, quem é o Filho do Homem?”.

[[v47-16-14]]

^<<v47-16-14,14>>^ Responderam: “Uns dizem que é João Batista; outros, Elias; outros, Jeremias ou um dos profetas”.

[[v47-16-15]]

^<<v47-16-15,15>>^ Disse-lhes Jesus: “E vós quem dizeis que eu sou?”

[[v47-16-16]]

^<<v47-16-16,16>>^ Simão Pedro respondeu: “Tu és o Cristo, o Filho de Deus vivo!”.

[[v47-16-17]]

^<<v47-16-17,17>>^ Jesus, então, lhe disse: “Feliz és, Simão, filho de Jonas, porque não foi a carne nem o sangue que te revelou isto, mas meu Pai que está nos céus.^&#42;1^

[[v47-16-18]]

^<<v47-16-18,18>>^ E eu te declaro: tu és Pedro, e sobre esta pedra edificarei a minha Igreja; as portas do inferno não prevalecerão contra ela.^&#42;1^

[[v47-16-19]]

^<<v47-16-19,19>>^ Eu te darei as chaves do Reino dos Céus: tudo o que ligares na terra será ligado nos céus, e tudo o que desligares na terra será desligado nos céus”.^&#42;1^

[[v47-16-20]]

^<<v47-16-20,20>>^ Depois, ordenou aos seus discípulos que não dissessem a ninguém que ele era o Cristo.

[[v47-16-21]]

^<<v47-16-21,21>>^ Desde então, Jesus começou a manifestar a seus discípulos que precisava ir a Jerusalém e sofrer muito da parte dos anciãos, dos príncipes dos sacerdotes e dos escribas; seria morto e ressuscitaria ao terceiro dia.

[[v47-16-22]]

^<<v47-16-22,22>>^ Pedro, então, começou a interpelá-lo e protestar nestes termos: “Que Deus não permita isso, Senhor! Isso não te acontecerá!”.

[[v47-16-23]]

^<<v47-16-23,23>>^ Mas Jesus, voltando-se para ele, disse-lhe: “Afasta-te, Satanás! Tu és para mim um escândalo; teus pensamentos não são de Deus, mas dos homens!”.

[[v47-16-24]]

^<<v47-16-24,24>>^ Em seguida, Jesus disse a seus discípulos: “Se alguém quiser vir comigo, renuncie-se a si mesmo, tome sua cruz e siga-me.

[[v47-16-25]]

^<<v47-16-25,25>>^ Porque aquele que quiser salvar a sua vida, irá perdê-la; mas aquele que tiver sacrificado a sua vida por minha causa, irá recobrá-la.

[[v47-16-26]]

^<<v47-16-26,26>>^ Que servirá a um homem ganhar o mundo inteiro, se vem a prejudicar a sua vida? Ou que dará um homem em troca de sua vida?...^&#42;1^

[[v47-16-27]]

^<<v47-16-27,27>>^ Porque o Filho do Homem há de vir na glória de seu Pai com seus anjos, e então recompensará a cada um segundo suas obras.

[[v47-16-28]]

^<<v47-16-28,28>>^ Em verdade vos declaro: muitos destes que aqui estão não verão a morte, sem que tenham visto o Filho do Homem voltar na majestade de seu Reino”.

'''

xref:047-sao-mateus/047-sao-mateus-015.adoc#v47-15-0[&#60; Capítulo Anterior] | <<v47-16-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-017.adoc#v47-17-0[Próximo Capítulo &#62;]