include::./index.adoc[]

[[v47-22-0]]
=== São Mateus, 22
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em São Mateus 22, Jesus continua a ensinar as multidões com parábolas e responde a diversas questões dos fariseus e dos saduceus, incluindo a pergunta sobre qual é o maior mandamento da Lei. Jesus enfatiza a importância do amor a Deus e ao próximo, e alerta contra a hipocrisia religiosa. Aqui estão cinco versículos relacionados com os temas abordados neste capítulo:
* Levítico 19:18: "Não se vinguem nem guardem rancor contra alguém do seu povo, mas ame cada um o seu próximo como a si mesmo. Eu sou o Senhor." Jesus cita este mandamento quando questionado sobre qual é o maior mandamento da Lei, enfatizando a importância do amor ao próximo.
* Salmos 118:22-23: "A pedra que os construtores rejeitaram tornou-se a pedra angular. Isso vem do Senhor, e é algo maravilhoso aos nossos olhos." Jesus usa esta passagem para se referir a si mesmo como a pedra angular rejeitada pelos líderes religiosos, mas escolhida por Deus.
* Isaías 45:22-23: "Voltem-se para mim e sejam salvos, todos vocês, confins da terra; pois eu sou Deus, e não há nenhum outro. Jurei por mim mesmo, a minha boca proferiu com toda a integridade uma palavra que não será revogada: diante de mim todo joelho se dobrará e toda língua confessará que sou Deus." Jesus usa este versículo para afirmar sua divindade e a necessidade de se voltar a ele para a salvação.
* Provérbios 22:16: "Aquele que oprime o pobre para aumentar sua riqueza e dá presentes ao rico certamente acabará na pobreza." Jesus condena a hipocrisia religiosa dos fariseus, que ostentam uma aparência de piedade enquanto exploram os pobres e justificam seu comportamento.
* Isaías 64:6: "Todos nós nos tornamos como um ser impuro, e todas as nossas boas obras são como trapos imundos; todos nós murchamos como folhas, e como o vento as nossas iniquidades nos levam para longe." Jesus adverte contra a autojustiça e a confiança em nossas próprias boas obras, enfatizando a necessidade da graça e da misericórdia de Deus para a salvação.
****

[[v47-22-1]]

^<<v47-22-1,1>>^ Jesus tornou a falar-lhes por meio de parábolas:

[[v47-22-2]]

^<<v47-22-2,2>>^ “O Reino dos Céus é comparado a um rei que celebrava as bodas de seu filho.

[[v47-22-3]]

^<<v47-22-3,3>>^ Enviou seus servos para chamar os convidados, mas eles não quiseram vir.

[[v47-22-4]]

^<<v47-22-4,4>>^ Enviou outros ainda, dizendo-lhes: Dizei aos convidados que já está preparado o meu banquete; meus bois e meus animais cevados estão mortos, tudo está preparado. Vinde às bodas!

[[v47-22-5]]

^<<v47-22-5,5>>^ Mas, sem se importarem com aquele convite, foram-se, um a seu campo e outro para seu negócio.

[[v47-22-6]]

^<<v47-22-6,6>>^ Outros lançaram mãos de seus servos, insultaram-nos e os mataram.

[[v47-22-7]]

^<<v47-22-7,7>>^ O rei soube e indignou-se em extremo. Enviou suas tropas, matou aqueles assassinos e incendiou-lhes a cidade.

[[v47-22-8]]

^<<v47-22-8,8>>^ Disse depois a seus servos: O festim está pronto, mas os convidados não foram dignos.

[[v47-22-9]]

^<<v47-22-9,9>>^ Ide às encruzilhadas e convidai para as bodas todos quantos achardes.

[[v47-22-10]]

^<<v47-22-10,10>>^ Espalharam-se eles pelos caminhos e reuniram todos quantos acharam, maus e bons, de modo que a sala do banquete ficou repleta de convidados.

[[v47-22-11]]

^<<v47-22-11,11>>^ O rei entrou para vê-los e viu ali um homem que não trazia a veste nupcial.

[[v47-22-12]]

^<<v47-22-12,12>>^ Perguntou-lhe: Meu amigo, como entraste aqui, sem a veste nupcial? O homem não proferiu palavra alguma.

[[v47-22-13]]

^<<v47-22-13,13>>^ Disse, então, o rei aos servos: Amarrai-lhe os pés e as mãos e lançai-o nas trevas exteriores. Ali haverá choro e ranger de dentes.

[[v47-22-14]]

^<<v47-22-14,14>>^ Porque muitos são os chamados, e poucos os escolhidos”.

[[v47-22-15]]

^<<v47-22-15,15>>^ Reuniram-se então os fariseus para deliberar entre si sobre a maneira de surpreender Jesus nas suas próprias palavras.

[[v47-22-16]]

^<<v47-22-16,16>>^ Enviaram seus discípulos com os herodianos, que lhe disseram: “Mestre, sabemos que és verdadeiro e ensinas o caminho de Deus em toda a verdade, sem te preocupares com ninguém, porque não olhas para a aparência dos homens.^&#42;1^

[[v47-22-17]]

^<<v47-22-17,17>>^ Dize-nos, pois, o que te parece: É permitido ou não pagar o imposto a César?”.

[[v47-22-18]]

^<<v47-22-18,18>>^ Jesus, percebendo a sua malícia, respondeu: “Por que me tentais, hipócritas?

[[v47-22-19]]

^<<v47-22-19,19>>^ Mostrai-me a moeda com que se paga o imposto!”. Apresentaram-lhe um denário.

[[v47-22-20]]

^<<v47-22-20,20>>^ Perguntou Jesus: “De quem é esta imagem e esta inscrição?”.

[[v47-22-21]]

^<<v47-22-21,21>>^ “De César” – responderam-lhe. Disse-lhes então Jesus: “Dai, pois, a César o que é de César e a Deus o que é de Deus”.

[[v47-22-22]]

^<<v47-22-22,22>>^ Esta resposta encheu-os de admiração e, deixando-o, retiraram-se.

[[v47-22-23]]

^<<v47-22-23,23>>^ Naquele mesmo dia, os saduceus, que negavam a ressurreição, interrogaram-no:^&#42;1^

[[v47-22-24]]

^<<v47-22-24,24>>^ “Mestre, Moisés disse: Se um homem morrer sem filhos, seu irmão case-se com a sua viúva e dê-lhe assim uma posteridade (Dt 25,5).

[[v47-22-25]]

^<<v47-22-25,25>>^ Ora, havia entre nós sete irmãos. O primeiro casou-se e morreu. Como não tinha filhos, deixou sua mulher ao seu irmão.

[[v47-22-26]]

^<<v47-22-26,26>>^ O mesmo sucedeu ao segundo, depois ao terceiro, até o sétimo.

[[v47-22-27]]

^<<v47-22-27,27>>^ Por sua vez, depois deles todos, morreu também a mulher.

[[v47-22-28]]

^<<v47-22-28,28>>^ Na ressurreição, de qual dos sete será a mulher, uma vez que todos a tiveram?”.

[[v47-22-29]]

^<<v47-22-29,29>>^ Respondeu-lhes Jesus: “Errais, não compreendendo as Escrituras nem o poder de Deus.

[[v47-22-30]]

^<<v47-22-30,30>>^ Na ressurreição, os homens não terão mulheres nem as mulheres, maridos; mas serão como os anjos de Deus no céu.

[[v47-22-31]]

^<<v47-22-31,31>>^ Quanto à ressurreição dos mortos, não lestes o que Deus vos disse:

[[v47-22-32]]

^<<v47-22-32,32>>^ Eu sou o Deus de Abraão, o Deus de Isaac e o Deus de Jacó (Ex 3,6)? Ora, ele não é Deus dos mortos, mas Deus dos vivos”.^&#42;1^

[[v47-22-33]]

^<<v47-22-33,33>>^ E, ouvindo essa doutrina, as turbas se enchiam de grande admiração.

[[v47-22-34]]

^<<v47-22-34,34>>^ Sabendo os fariseus que Jesus reduzira ao silêncio os saduceus, reuniram-se

[[v47-22-35]]

^<<v47-22-35,35>>^ e um deles, doutor da Lei, fez-lhe esta pergunta para pô-lo à prova:

[[v47-22-36]]

^<<v47-22-36,36>>^ “Mestre, qual é o maior mandamento da Lei?”.

[[v47-22-37]]

^<<v47-22-37,37>>^ Respondeu Jesus: “Amarás o Senhor, teu Deus, de todo o teu o coração, de toda a tua alma e de todo o teu espírito (Dt 6,5).

[[v47-22-38]]

^<<v47-22-38,38>>^ Esse é o maior e o primeiro mandamento.

[[v47-22-39]]

^<<v47-22-39,39>>^ E o segundo, semelhante a este, é: Amarás teu próximo como a ti mesmo (Lv 19,18).

[[v47-22-40]]

^<<v47-22-40,40>>^ Nesses dois mandamentos se resumem toda a Lei e os Profetas”.

[[v47-22-41]]

^<<v47-22-41,41>>^ Como os fariseus se agrupassem, Jesus interrogou-os:

[[v47-22-42]]

^<<v47-22-42,42>>^ “Que pensais vós de Cristo? De quem é filho?”. Responderam: “De Davi!”.

[[v47-22-43]]

^<<v47-22-43,43>>^ “Como então, prosseguiu Jesus, Davi, falando sob inspiração do Espírito, chama-o Senhor, dizendo:

[[v47-22-44]]

^<<v47-22-44,44>>^ O Senhor disse a meu Senhor: Senta-te à minha direita, até que eu ponha teus inimigos por escabelo dos teus pés (Sl 109,1)?

[[v47-22-45]]

^<<v47-22-45,45>>^ Se, pois, Davi o chama Senhor, como é ele seu filho?”

[[v47-22-46]]

^<<v47-22-46,46>>^ Ninguém pôde responder-lhe nada. E, depois daquele dia, ninguém mais ousou interrogá-lo.

'''

xref:047-sao-mateus/047-sao-mateus-021.adoc#v47-21-0[&#60; Capítulo Anterior] | <<v47-22-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-023.adoc#v47-23-0[Próximo Capítulo &#62;]