include::./index.adoc[]

[[v47-6-0]]
=== São Mateus, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Mateus 6 contém o discurso de Jesus sobre práticas religiosas, como a oração, o jejum e a doação de esmolas. Ele ensina seus seguidores a não buscar a atenção dos outros ao praticar essas ações, mas sim fazer tudo em secreto para agradar a Deus. Ele também ensina sobre a importância de confiar em Deus para suprir as necessidades diárias e de não se preocupar com o futuro.
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." Jesus enfatiza a importância da confiança em Deus e não em si mesmo.
* Mateus 6:14-15: "Porque, se perdoarem as ofensas uns dos outros, o Pai celestial também lhes perdoará. Mas se não perdoarem uns aos outros, o Pai celestial não lhes perdoará as ofensas." Jesus ensina a importância do perdão para obter o perdão de Deus.
* Lucas 11:9-10: "Por isso lhes digo: peçam, e lhes será dado; busquem, e encontrarão; batam, e a porta lhes será aberta. Pois todo o que pede, recebe; o que busca, encontra; e àquele que bate, a porta será aberta." Jesus ensina seus seguidores a confiar em Deus para suprir suas necessidades e a pedir em oração.
* Mateus 6:24: "Ninguém pode servir a dois senhores; pois odiará um e amará o outro, ou se dedicará a um e desprezará o outro. Vocês não podem servir a Deus e ao Dinheiro." Jesus adverte seus seguidores sobre a idolatria do dinheiro e a importância de servir somente a Deus.
* Lucas 12:22-23: "Portanto, eu lhes digo: não se preocupem com suas próprias vidas, quanto ao que comer ou beber; nem com seus próprios corpos, quanto ao que vestir. Não é a vida mais importante do que a comida, e o corpo mais importante do que a roupa?" Jesus ensina sobre a importância de confiar em Deus para suprir as necessidades diárias e não se preocupar com o futuro.
****

[[v47-6-1]]

^<<v47-6-1,1>>^ “Guardai-vos de fazer vossas boas obras diante dos homens, para serdes vistos por eles. Do contrário, não tereis recompensa junto de vosso Pai que está no céu.

[[v47-6-2]]

^<<v47-6-2,2>>^ Quando, pois, dás esmola, não toques a trombeta diante de ti, como fazem os hipócritas nas sinagogas e nas ruas, para serem louvados pelos homens. Em verdade eu vos digo: já receberam sua recompensa.

[[v47-6-3]]

^<<v47-6-3,3>>^ Quando deres esmola, que tua mão esquerda não saiba o que fez a direita.^&#42;1^

[[v47-6-4]]

^<<v47-6-4,4>>^ Assim, a tua esmola se fará em segredo; e teu Pai, que vê o escondido, irá recompensar-te.

[[v47-6-5]]

^<<v47-6-5,5>>^ Quando orardes, não façais como os hipócritas, que gostam de orar de pé nas sinagogas e nas esquinas das ruas, para serem vistos pelos homens. Em verdade eu vos digo: já receberam sua recompensa.

[[v47-6-6]]

^<<v47-6-6,6>>^ Quando orares, entra no teu quarto, fecha a porta e ora ao teu Pai em segredo; e teu Pai, que vê num lugar oculto, te recompensará.

[[v47-6-7]]

^<<v47-6-7,7>>^ Nas vossas orações, não multipliqueis as palavras, como fazem os pagãos que julgam que serão ouvidos à força de palavras.

[[v47-6-8]]

^<<v47-6-8,8>>^ Não os imiteis, porque vosso Pai sabe o que vos é necessário, antes que vós lho peçais.

[[v47-6-9]]

^<<v47-6-9,9>>^ Eis como deveis rezar: PAI NOSSO, que estais no céu, santificado seja o vosso nome;

[[v47-6-10]]

^<<v47-6-10,10>>^ venha a nós o vosso Reino; seja feita a vossa vontade, assim na terra como no céu.

[[v47-6-11]]

^<<v47-6-11,11>>^ O pão nosso de cada dia nos dai hoje;^&#42;1^

[[v47-6-12]]

^<<v47-6-12,12>>^ perdoai-nos as nossas ofensas, assim como nós perdoamos aos que nos ofenderam;^&#42;1^

[[v47-6-13]]

^<<v47-6-13,13>>^ e não nos deixeis cair em tentação, mas livrai-nos do mal.

[[v47-6-14]]

^<<v47-6-14,14>>^ Porque, se perdoardes aos homens as suas ofensas, vosso Pai celeste também vos perdoará.

[[v47-6-15]]

^<<v47-6-15,15>>^ Mas, se não perdoardes aos homens, tampouco vosso Pai vos perdoará.

[[v47-6-16]]

^<<v47-6-16,16>>^ Quando jejuardes, não tomeis um ar triste como os hipócritas, que mostram um semblante abatido para manifestar aos homens que jejuam. Em verdade eu vos digo: já receberam sua recompensa.

[[v47-6-17]]

^<<v47-6-17,17>>^ Quando jejuares, perfuma a tua cabeça e lava o teu rosto.

[[v47-6-18]]

^<<v47-6-18,18>>^ Assim, não parecerá aos homens que jejuas, mas somente a teu Pai que está presente ao oculto; e teu Pai, que vê num lugar oculto, te recompensará.”

[[v47-6-19]]

^<<v47-6-19,19>>^ “Não ajunteis para vós tesouros na terra, onde a ferrugem e as traças corroem, onde os ladrões furtam e roubam.

[[v47-6-20]]

^<<v47-6-20,20>>^ Ajuntai para vós tesouros no céu, onde não os consomem nem as traças nem a ferrugem, e os ladrões não furtam nem roubam.

[[v47-6-21]]

^<<v47-6-21,21>>^ Porque onde está o teu tesouro, lá também está teu coração.

[[v47-6-22]]

^<<v47-6-22,22>>^ O olho é a luz do corpo. Se teu olho é são, todo o teu corpo será iluminado.

[[v47-6-23]]

^<<v47-6-23,23>>^ Se teu olho estiver em mau estado, todo o teu corpo estará nas trevas. Se a luz que está em ti são trevas, quão espessas deverão ser as trevas!”

[[v47-6-24]]

^<<v47-6-24,24>>^ “Ninguém pode servir a dois senhores, porque ou odiará a um e amará o outro, ou se dedicará a um e desprezará o outro. Não podeis servir a Deus e à riqueza.^&#42;1^

[[v47-6-25]]

^<<v47-6-25,25>>^ Portanto, eis que vos digo: não vos preocupeis por vossa vida, pelo que comereis, nem por vosso corpo, pelo que vestireis. A vida não é mais do que o alimento e o corpo não é mais que as vestes?

[[v47-6-26]]

^<<v47-6-26,26>>^ Olhai as aves do céu: não semeiam nem ceifam, nem recolhem nos celeiros e vosso Pai celeste as alimenta. Não valeis vós muito mais que elas?

[[v47-6-27]]

^<<v47-6-27,27>>^ Qual de vós, por mais que se esforce, pode acrescentar um só côvado à duração de sua vida?^&#42;1^

[[v47-6-28]]

^<<v47-6-28,28>>^ E por que vos inquietais com as vestes? Considerai como crescem os lírios do campo; não trabalham nem fiam.

[[v47-6-29]]

^<<v47-6-29,29>>^ Entretanto, eu vos digo que o próprio Salomão no auge de sua glória não se vestiu como um deles.

[[v47-6-30]]

^<<v47-6-30,30>>^ Se Deus veste assim a erva dos campos, que hoje cresce e amanhã será lançada ao fogo, quanto mais a vós, homens de pouca fé?

[[v47-6-31]]

^<<v47-6-31,31>>^ Não vos aflijais, nem digais: Que comeremos? Que beberemos? Com que nos vestiremos?

[[v47-6-32]]

^<<v47-6-32,32>>^ São os pagãos que se preocupam com tudo isso. Ora, vosso Pai celeste sabe que necessitais de tudo isso.

[[v47-6-33]]

^<<v47-6-33,33>>^ Buscai em primeiro lugar o Reino de Deus e a sua justiça e todas estas coisas vos serão dadas em acréscimo.

[[v47-6-34]]

^<<v47-6-34,34>>^ Não vos preocupeis, pois, com o dia de amanhã: o dia de amanhã terá as suas preocupações próprias. A cada dia basta o seu cuidado.”

'''

xref:047-sao-mateus/047-sao-mateus-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-007.adoc#v47-7-0[Próximo Capítulo &#62;]