include::./index.adoc[]

[[v47-3-0]]
=== São Mateus, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Mateus 3 apresenta a figura de João Batista, que veio preparar o caminho para a vinda de Jesus Cristo. O capítulo descreve seu ministério no deserto, onde ele pregava o arrependimento e o batismo para a remissão dos pecados. João Batista é um exemplo de humildade e devoção a Deus, que chamou o povo ao arrependimento e à fé. Os versículos selecionados a seguir tratam de temas relacionados a essa mensagem de arrependimento e preparação para a chegada de Jesus:
* Isaías 40:3: "Voz do que clama no deserto: Preparai o caminho do Senhor; endireitai no ermo vereda a nosso Deus." Este versículo é citado em São Mateus 3:3, quando João Batista começa a pregar no deserto. A profecia de Isaías anuncia a chegada de um mensageiro que prepararia o caminho para o Senhor. João Batista cumpre essa profecia ao anunciar a vinda de Jesus Cristo.
* Ezequiel 18:30: "Portanto, eu vos julgarei, a cada um conforme os seus caminhos, ó casa de Israel, diz o Senhor Deus. Tornai-vos, e convertei-vos de todas as vossas transgressões, e a iniquidade não vos servirá de tropeço." Este versículo destaca a importância do arrependimento e da mudança de vida. João Batista pregava a mesma mensagem de conversão e arrependimento, chamando o povo a se voltar para Deus e abandonar seus pecados.
* Jeremias 7:3-4: "Assim diz o Senhor dos exércitos, Deus de Israel: Emendai os vossos caminhos e as vossas obras, e eu vos farei habitar neste lugar. Não confieis em palavras falsas, dizendo: Templo do Senhor, templo do Senhor, templo do Senhor é este." Este versículo adverte o povo contra a confiança vazia na religião, lembrando que Deus busca uma mudança real de coração e atitude. João Batista pregava a mesma mensagem, chamando as pessoas a se arrependerem de fato e a frutificarem em boas obras.
* Mateus 3:8: "Produzi, pois, frutos dignos de arrependimento." Nesse versículo, João Batista exorta o povo a produzir frutos que evidenciem o arrependimento sincero. Ele não se contentava com palavras ou cerimônias religiosas vazias, mas buscava uma mudança real de vida no coração das pessoas.
* Lucas 3:16: "Ele [Jesus] vos batizará com o Espírito Santo e com fogo." Esse versículo faz referência à promessa de Jesus de enviar o Espírito Santo, que batizaria os crentes em seu nome. João Batista, ao preparar o caminho para Jesus, antecipava essa promessa e anunciava que o batismo com o Espírito Santo seria uma das marcas da vinda do Messias.
****

[[v47-3-1]]

^<<v47-3-1,1>>^ Naqueles dias, apareceu João Batista, pregando no deserto da Judeia.

[[v47-3-2]]

^<<v47-3-2,2>>^ Dizia ele: “Fazei penitência porque está próximo o Reino dos Céus.”

[[v47-3-3]]

^<<v47-3-3,3>>^ Este é aquele de quem falou o profeta Isaías, quando disse: Uma voz clama no deserto: Preparai o caminho do Senhor, endireitai as suas veredas (Is 40,3).

[[v47-3-4]]

^<<v47-3-4,4>>^ João usava uma vestimenta de pelos de camelo e um cinto de couro em volta dos rins. Alimentava-se de gafanhotos e mel silvestre.

[[v47-3-5]]

^<<v47-3-5,5>>^ Pessoas de Jerusalém, de toda a Judeia e de toda a circunvizinhança do Jordão vinham a ele.

[[v47-3-6]]

^<<v47-3-6,6>>^ Confessavam seus pecados e eram batizadas por ele nas águas do Jordão.

[[v47-3-7]]

^<<v47-3-7,7>>^ Ao ver, porém, que muitos dos fariseus e dos saduceus vinham ao seu batismo, disse-lhes: “Raça de víboras, quem vos ensinou a fugir da cólera vindoura?^&#42;1^

[[v47-3-8]]

^<<v47-3-8,8>>^ Dai, pois, frutos de verdadeira penitência.

[[v47-3-9]]

^<<v47-3-9,9>>^ Não digais dentro de vós: Nós temos a Abraão por pai! Pois eu vos digo: Deus é poderoso para suscitar destas pedras filhos a Abraão.

[[v47-3-10]]

^<<v47-3-10,10>>^ O machado já está posto à raiz das árvores: toda árvore que não produzir bons frutos será cortada e lançada ao fogo.

[[v47-3-11]]

^<<v47-3-11,11>>^ Eu vos batizo com água, em sinal de penitência, mas aquele que virá depois de mim é mais poderoso do que eu e nem sou digno de carregar seus calçados. Ele vos batizará no Espírito Santo e em fogo.

[[v47-3-12]]

^<<v47-3-12,12>>^ Tem na mão a pá, limpará sua eira e recolherá o trigo ao celeiro. As palhas, porém, serão queimadas num fogo inextinguível”.

[[v47-3-13]]

^<<v47-3-13,13>>^ Da Galileia foi Jesus ao Jordão ter com João, a fim de ser batizado por ele.

[[v47-3-14]]

^<<v47-3-14,14>>^ João recusava-se: “Eu devo ser batizado por ti e tu vens a mim!”.

[[v47-3-15]]

^<<v47-3-15,15>>^ Mas Jesus lhe respondeu: “Deixa por agora, pois convém cumpramos a justiça completa”. Então, João cedeu.^&#42;1^

[[v47-3-16]]

^<<v47-3-16,16>>^ Depois que Jesus foi batizado, saiu logo da água. Eis que os céus se abriram e viu descer sobre ele, em forma de pomba, o Espírito de Deus.

[[v47-3-17]]

^<<v47-3-17,17>>^ E do céu baixou uma voz: “Eis meu Filho muito amado em quem ponho minha afeição”.

'''

xref:047-sao-mateus/047-sao-mateus-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-004.adoc#v47-4-0[Próximo Capítulo &#62;]