include::./index.adoc[]

[[v47-25-0]]
=== São Mateus, 25
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Mateus 25 apresenta três parábolas de Jesus sobre o fim dos tempos e o julgamento final. A primeira é a parábola das dez virgens, que mostra a importância da preparação e vigilância para a vinda do noivo, que simboliza Jesus. A segunda é a parábola dos talentos, que enfatiza a responsabilidade que cada um tem de usar os dons que Deus lhe deu para o bem comum e o crescimento do Reino de Deus. A terceira é a parábola das ovelhas e dos bodes, que mostra que o julgamento final será baseado em nossas ações de amor e serviço aos outros.
* 1 Coríntios 12:7: "A cada um, porém, é dada a manifestação do Espírito para o proveito comum." Assim como a parábola dos talentos ensina, Deus nos deu dons e talentos específicos que devemos usar para o bem dos outros e a glória de Deus.
* Tiago 1:22: "Sede cumpridores da palavra, e não somente ouvintes, enganando-vos com falsos discursos." A parábola das dez virgens enfatiza a importância da vigilância e preparação para a vinda do noivo. Essa vigilância inclui ouvir e obedecer a Palavra de Deus.
* 1 João 3:17: "Ora, aquele que possuir recursos deste mundo, e vir a seu irmão padecer necessidade, e fechar-lhe o seu coração, como pode permanecer nele o amor de Deus?" A parábola das ovelhas e dos bodes ensina que o julgamento final será baseado em nossas ações de amor e serviço aos outros. Esse versículo em particular enfatiza a importância de compartilhar nossos recursos com os necessitados.
* 1 Tessalonicenses 5:6: "Não durmamos, pois, como os demais, mas vigiemos e sejamos sóbrios." A parábola das dez virgens enfatiza a importância da vigilância e preparação para a vinda do noivo. Esse versículo em particular enfatiza a necessidade de estar alerta e vigilante espiritualmente.
* Romanos 12:13: "Comunicai com os santos nas suas necessidades, segui a hospitalidade." A parábola das ovelhas e dos bodes ensina que o julgamento final será baseado em nossas ações de amor e serviço aos outros. Esse versículo em particular enfatiza a importância de mostrar hospitalidade e compartilhar o que temos com os irmãos na fé.
****

[[v47-25-1]]

^<<v47-25-1,1>>^ “Então, o Reino dos Céus será semelhante a dez virgens, que saíram com suas lâmpadas ao encontro do esposo.^&#42;1^

[[v47-25-2]]

^<<v47-25-2,2>>^ Cinco dentre elas eram tolas e cinco, prudentes.

[[v47-25-3]]

^<<v47-25-3,3>>^ Tomando suas lâmpadas, as tolas não levaram óleo consigo.

[[v47-25-4]]

^<<v47-25-4,4>>^ As prudentes, todavia, levaram de reserva vasos de óleo junto com as lâmpadas.

[[v47-25-5]]

^<<v47-25-5,5>>^ Tardando o esposo, cochilaram todas e adormeceram.

[[v47-25-6]]

^<<v47-25-6,6>>^ No meio da noite, porém, ouviu-se um clamor: Eis o esposo, ide-lhe ao encontro.

[[v47-25-7]]

^<<v47-25-7,7>>^ E as virgens levantaram-se todas e prepararam suas lâmpadas.

[[v47-25-8]]

^<<v47-25-8,8>>^ As tolas disseram às prudentes: Dai-nos de vosso óleo, porque nossas lâmpadas se estão apagando.

[[v47-25-9]]

^<<v47-25-9,9>>^ As prudentes responderam: Não temos o suficiente para nós e para vós; é preferível irdes aos vendedores, a fim de o comprar para vós.

[[v47-25-10]]

^<<v47-25-10,10>>^ Ora, enquanto foram comprar, veio o esposo. As que estavam preparadas entraram com ele para a sala das bodas e foi fechada a porta.

[[v47-25-11]]

^<<v47-25-11,11>>^ Mais tarde, chegaram também as outras e diziam: Senhor, senhor, abre-nos!

[[v47-25-12]]

^<<v47-25-12,12>>^ Mas ele respondeu: Em verdade vos digo: não vos conheço!

[[v47-25-13]]

^<<v47-25-13,13>>^ Vigiai, pois, porque não sabeis nem o dia nem a hora.”

[[v47-25-14]]

^<<v47-25-14,14>>^ “Será também como um homem que, tendo de viajar, reuniu seus servos e lhes confiou seus bens.

[[v47-25-15]]

^<<v47-25-15,15>>^ A um deu cinco talentos; a outro, dois; e a outro, um, segundo a capacidade de cada um. Depois partiu.

[[v47-25-16]]

^<<v47-25-16,16>>^ Logo em seguida, o que recebeu cinco talentos negociou com eles; fê-los produzir, e ganhou outros cinco.

[[v47-25-17]]

^<<v47-25-17,17>>^ Do mesmo modo, o que recebeu dois, ganhou outros dois.

[[v47-25-18]]

^<<v47-25-18,18>>^ Mas, o que recebeu apenas um, foi cavar a terra e escondeu o dinheiro de seu senhor.

[[v47-25-19]]

^<<v47-25-19,19>>^ Muito tempo depois, o senhor daqueles servos voltou e pediu-lhes contas.

[[v47-25-20]]

^<<v47-25-20,20>>^ O que recebeu cinco talentos aproximou-se e apresentou outros cinco: ‘Senhor’ – disse-lhe –, ‘confiaste-me cinco talentos; eis aqui outros cinco que ganhei’.

[[v47-25-21]]

^<<v47-25-21,21>>^ Disse-lhe seu senhor: ‘Muito bem, servo bom e fiel; já que foste fiel no pouco, eu te confiarei muito. Vem regozijar-te com teu senhor’.

[[v47-25-22]]

^<<v47-25-22,22>>^ O que recebeu dois talentos adiantou-se também e disse: ‘Senhor, confiaste-me dois talentos; eis aqui os dois outros que lucrei’.

[[v47-25-23]]

^<<v47-25-23,23>>^ Disse-lhe seu senhor: ‘Muito bem, servo bom e fiel; já que foste fiel no pouco, eu te confiarei muito. Vem regozijar-te com teu senhor’.

[[v47-25-24]]

^<<v47-25-24,24>>^ Veio, por fim, o que recebeu só um talento: ‘Senhor, disse-lhe, sabia que és um homem duro, que colhes onde não semeaste e recolhes onde não espalhaste.

[[v47-25-25]]

^<<v47-25-25,25>>^ Por isso, tive medo e fui esconder teu talento na terra. Eis aqui, toma o que te pertence’.

[[v47-25-26]]

^<<v47-25-26,26>>^ Respondeu-lhe seu senhor: ‘Servo mau e preguiçoso! Sabias que colho onde não semeei e que recolho onde não espalhei.

[[v47-25-27]]

^<<v47-25-27,27>>^ Devias, pois, levar meu dinheiro ao banco e, à minha volta, eu receberia com os juros o que é meu.

[[v47-25-28]]

^<<v47-25-28,28>>^ Tirai-lhe este talento e dai-o ao que tem dez.

[[v47-25-29]]

^<<v47-25-29,29>>^ Será dado ao que tem e terá em abundância. Mas ao que não tem será tirado mesmo aquilo que julga ter.

[[v47-25-30]]

^<<v47-25-30,30>>^ E a esse servo inútil, jogai-o nas trevas exteriores; ali haverá choro e ranger de dentes’.”

[[v47-25-31]]

^<<v47-25-31,31>>^ “Quando o Filho do Homem voltar na sua glória e todos os anjos com ele, se sentará no seu trono glorioso.

[[v47-25-32]]

^<<v47-25-32,32>>^ Todas as nações se reunirão diante dele e ele separará uns dos outros, como o pastor separa as ovelhas dos cabritos.

[[v47-25-33]]

^<<v47-25-33,33>>^ Colocará as ovelhas à sua direita e os cabritos à sua esquerda.

[[v47-25-34]]

^<<v47-25-34,34>>^ Então, o Rei dirá aos que estão à direita: ‘Vinde, benditos de meu Pai, tomai posse do Reino que vos está preparado desde a criação do mundo,

[[v47-25-35]]

^<<v47-25-35,35>>^ porque tive fome e me destes de comer; tive sede e me destes de beber; era peregrino e me acolhestes;

[[v47-25-36]]

^<<v47-25-36,36>>^ nu e me vestistes; enfermo e me visitastes; estava na prisão e viestes a mim’.

[[v47-25-37]]

^<<v47-25-37,37>>^ Os justos lhe perguntarão: ‘Senhor, quando foi que te vimos com fome e te demos de comer, com sede e te demos de beber?

[[v47-25-38]]

^<<v47-25-38,38>>^ Quando foi que te vimos peregrino e te acolhemos, nu e te vestimos?

[[v47-25-39]]

^<<v47-25-39,39>>^ Quando foi que te vimos enfermo ou na prisão e te fomos visitar?’.

[[v47-25-40]]

^<<v47-25-40,40>>^ Responderá o Rei: ‘Em verdade eu vos declaro: todas as vezes que fizestes isso a um destes meus irmãos mais pequeninos, foi a mim mesmo que o fizestes.’

[[v47-25-41]]

^<<v47-25-41,41>>^ Ele se voltará em seguida para os da sua esquerda e lhes dirá: ‘Retirai-vos de mim, malditos! Ide para o fogo eterno destinado ao demônio e aos seus anjos.^&#42;1^

[[v47-25-42]]

^<<v47-25-42,42>>^ Porque tive fome e não me destes de comer; tive sede e não me destes de beber;

[[v47-25-43]]

^<<v47-25-43,43>>^ era peregrino e não me acolhestes; nu e não me vestistes; enfermo e na prisão e não me visitastes’.

[[v47-25-44]]

^<<v47-25-44,44>>^ Também estes lhe perguntarão: ‘Senhor, quando foi que te vimos com fome, com sede, peregrino, nu, enfermo, ou na prisão e não te socorremos?’.

[[v47-25-45]]

^<<v47-25-45,45>>^ E ele responderá: ‘Em verdade eu vos declaro: todas as vezes que deixastes de fazer isso a um destes pequeninos, foi a mim que o deixastes de fazer’.

[[v47-25-46]]

^<<v47-25-46,46>>^ “E estes irão para o castigo eterno, e os justos, para a vida eterna.”

'''

xref:047-sao-mateus/047-sao-mateus-024.adoc#v47-24-0[&#60; Capítulo Anterior] | <<v47-25-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-026.adoc#v47-26-0[Próximo Capítulo &#62;]