include::./index.adoc[]

[[v47-10-0]]
=== São Mateus, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 10 de São Mateus trata da escolha e envio dos discípulos por Jesus para proclamarem a mensagem do Reino de Deus, bem como das instruções e advertências que ele lhes dá para a sua missão. Os versículos relacionados com os temas abordados neste capítulo são:
* Marcos 3:14-15: "E escolheu doze, para que estivessem com ele e os mandasse a pregar, e para que tivessem o poder de curar as enfermidades e expulsar os demônios."
Este versículo mostra a escolha dos doze discípulos por Jesus, que também foram enviados para pregar e realizar milagres.
* Mateus 10:5-6: "A estes doze enviou Jesus, e ordenou-lhes, dizendo: Não ireis pelo caminho dos gentios, nem entrareis em cidade de samaritanos; mas ide antes às ovelhas perdidas da casa de Israel."
Neste versículo, Jesus dá instruções específicas aos seus discípulos sobre onde iriam pregar: primeiramente aos judeus, antes de se voltarem para os gentios.
* Lucas 10:1: "Depois disto, designou o Senhor ainda outros setenta, e mandou-os adiante da sua face, de dois em dois, a todas as cidades e lugares aonde ele havia de ir."
Além dos doze discípulos, Jesus também enviou setenta outros discípulos para proclamarem a mensagem do Reino.
* Mateus 10:16: "Eis que vos envio como ovelhas ao meio de lobos; portanto, sede prudentes como as serpentes e simples como as pombas."
Neste versículo, Jesus adverte seus discípulos sobre as dificuldades e perigos que eles enfrentariam em sua missão, e os encoraja a serem sábios e prudentes.
* Lucas 10:16: "Quem vos ouve, a mim me ouve; e quem vos rejeita, a mim me rejeita; e quem me rejeita, rejeita aquele que me enviou."
Este versículo mostra a importância da mensagem dos discípulos, que são enviados em nome de Jesus e em obediência à sua vontade. Aqueles que os rejeitam também estão rejeitando a Jesus e o Pai que o enviou.
****

[[v47-10-1]]

^<<v47-10-1,1>>^ Jesus reuniu seus doze discípulos. Conferiu-lhes o poder de expulsar os espíritos imundos e de curar todo mal e toda enfermidade.

[[v47-10-2]]

^<<v47-10-2,2>>^ Eis os nomes dos doze apóstolos: o primeiro, Simão, chamado Pedro; depois André, seu irmão. Tiago, filho de Zebedeu, e João, seu irmão.^&#42;1^

[[v47-10-3]]

^<<v47-10-3,3>>^ Filipe e Bartolomeu. Tomé e Mateus, o publicano. Tiago, filho de Alfeu, e Tadeu.^&#42;1^

[[v47-10-4]]

^<<v47-10-4,4>>^ Simão, o cananeu, e Judas Iscariotes, que foi o traidor.^&#42;1^

[[v47-10-5]]

^<<v47-10-5,5>>^ Estes são os Doze que Jesus enviou em missão, após lhes ter dado as seguintes instruções: “Não ireis ao meio dos gentios nem entrareis em Samaria;^&#42;1^

[[v47-10-6]]

^<<v47-10-6,6>>^ ide antes às ovelhas que se perderam da casa de Israel.

[[v47-10-7]]

^<<v47-10-7,7>>^ Por onde andardes, anunciai que o Reino dos Céus está próximo.

[[v47-10-8]]

^<<v47-10-8,8>>^ Curai os doentes, ressuscitai os mortos, purificai os leprosos, expulsai os demônios. Recebestes de graça, de graça dai!

[[v47-10-9]]

^<<v47-10-9,9>>^ Não leveis nem ouro, nem prata, nem dinheiro em vossos cintos,

[[v47-10-10]]

^<<v47-10-10,10>>^ nem mochila para a viagem, nem duas túnicas, nem calçados, nem bastão; pois o operário merece o seu sustento.^&#42;1^

[[v47-10-11]]

^<<v47-10-11,11>>^ Nas cidades ou aldeias onde entrardes, informai-vos se há alguém ali digno de vos receber; ficai ali até a vossa partida.

[[v47-10-12]]

^<<v47-10-12,12>>^ Entrando numa casa, saudai-a: Paz a esta casa.

[[v47-10-13]]

^<<v47-10-13,13>>^ Se aquela casa for digna, descerá sobre ela vossa paz; se, porém, não o for, vosso voto de paz retornará a vós.

[[v47-10-14]]

^<<v47-10-14,14>>^ Se não vos receberem e não ouvirem vossas palavras, quando sairdes daquela casa ou daquela cidade, sacudi até mesmo o pó de vossos pés.^&#42;1^

[[v47-10-15]]

^<<v47-10-15,15>>^ Em verdade vos digo: no dia do juízo haverá mais indulgência com Sodoma e Gomorra que com aquela cidade.

[[v47-10-16]]

^<<v47-10-16,16>>^ Eu vos envio como ovelhas no meio de lobos. Sede, pois, prudentes como as serpentes, mas simples como as pombas.

[[v47-10-17]]

^<<v47-10-17,17>>^ Cuidai-vos dos homens. Eles vos levarão aos seus tribunais e sereis açoitados com varas nas suas sinagogas.

[[v47-10-18]]

^<<v47-10-18,18>>^ Sereis por minha causa levados diante dos governadores e dos reis: servireis assim de testemunho para eles e para os pagãos.

[[v47-10-19]]

^<<v47-10-19,19>>^ Quando fordes presos, não vos preocupeis nem pela maneira com que haveis de falar, nem pelo que haveis de dizer: naquele momento vos será inspirado o que haveis de dizer.

[[v47-10-20]]

^<<v47-10-20,20>>^ Porque não sereis vós que falareis, mas é o Espírito de vosso Pai que falará em vós.

[[v47-10-21]]

^<<v47-10-21,21>>^ O irmão entregará seu irmão à morte. O pai, seu filho. Os filhos se levantarão contra seus pais e os matarão.

[[v47-10-22]]

^<<v47-10-22,22>>^ Sereis odiados de todos por causa de meu nome, mas aquele que perseverar até o fim será salvo.

[[v47-10-23]]

^<<v47-10-23,23>>^ Se vos perseguirem numa cidade, fugi para uma outra. Em verdade vos digo: não acabareis de percorrer as cidades de Israel antes que volte o Filho do Homem.

[[v47-10-24]]

^<<v47-10-24,24>>^ “O discípulo não é mais que o mestre, o servidor não é mais que o patrão.

[[v47-10-25]]

^<<v47-10-25,25>>^ Basta ao discípulo ser tratado como seu mestre, e ao servidor como seu patrão. Se chamaram de Beelzebul ao pai de família, quanto mais o farão às pessoas de sua casa!^&#42;1^

[[v47-10-26]]

^<<v47-10-26,26>>^ Não os temais, pois; porque nada há de escondido que não venha à luz, nada de secreto que não se venha a saber.

[[v47-10-27]]

^<<v47-10-27,27>>^ O que vos digo na escuridão, dizei-o às claras. O que vos é dito ao ouvido, publicai-o de cima dos telhados.

[[v47-10-28]]

^<<v47-10-28,28>>^ Não temais aqueles que matam o corpo, mas não podem matar a alma; temei antes aquele que pode precipitar a alma e o corpo na geena.^&#42;1^

[[v47-10-29]]

^<<v47-10-29,29>>^ Não se vendem dois passarinhos por um asse? No entanto, nenhum cai por terra sem a vontade de vosso Pai.^&#42;1^

[[v47-10-30]]

^<<v47-10-30,30>>^ Até os cabelos de vossa cabeça estão todos contados.

[[v47-10-31]]

^<<v47-10-31,31>>^ Não temais, pois! Bem mais que os pássaros valeis vós.

[[v47-10-32]]

^<<v47-10-32,32>>^ Portanto, quem der testemunho de mim diante dos homens, também eu darei testemunho dele diante de meu Pai que está nos céus.

[[v47-10-33]]

^<<v47-10-33,33>>^ Aquele, porém, que me negar diante dos homens, também eu o negarei diante de meu Pai que está nos céus.

[[v47-10-34]]

^<<v47-10-34,34>>^ Não julgueis que vim trazer a paz à terra. Vim trazer não a paz, mas a espada.^&#42;1^

[[v47-10-35]]

^<<v47-10-35,35>>^ Eu vim trazer a divisão entre o filho e o pai, entre a filha e a mãe, entre a nora e a sogra,

[[v47-10-36]]

^<<v47-10-36,36>>^ e os inimigos do homem serão as pessoas de sua própria casa.

[[v47-10-37]]

^<<v47-10-37,37>>^ Quem ama seu pai ou sua mãe mais que a mim não é digno de mim. Quem ama seu filho mais que a mim não é digno de mim.

[[v47-10-38]]

^<<v47-10-38,38>>^ Quem não toma a sua cruz e não me segue não é digno de mim.^&#42;1^

[[v47-10-39]]

^<<v47-10-39,39>>^ Aquele que tentar salvar a sua vida irá perdê-la. Aquele que a perder, por minha causa, irá reencontrá-la.

[[v47-10-40]]

^<<v47-10-40,40>>^ Quem vos recebe, a mim recebe. E quem me recebe recebe aquele que me enviou.

[[v47-10-41]]

^<<v47-10-41,41>>^ Aquele que recebe um profeta, na qualidade de profeta, receberá uma recompensa de profeta. Aquele que recebe um justo, na qualidade de justo, receberá uma recompensa de justo.

[[v47-10-42]]

^<<v47-10-42,42>>^ Todo aquele que der ainda que seja somente um copo de água fresca a um destes pequeninos, porque é meu discípulo, em verdade eu vos digo: não perderá sua recompensa.”

'''

xref:047-sao-mateus/047-sao-mateus-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-011.adoc#v47-11-0[Próximo Capítulo &#62;]