include::./index.adoc[]

[[v47-18-0]]
=== São Mateus, 18
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 18 do Evangelho de Mateus aborda temas relacionados à vida em comunidade e ao perdão. Jesus ensina sobre a importância da humildade, da correção fraterna e do perdão mútuo. Ele também fala sobre a importância de tratar com amor e misericórdia aqueles que erram.
* Colossenses 3:13: "Suportai-vos uns aos outros, perdoai-vos mutuamente, caso alguém tenha motivo de queixa contra outrem. Assim como o Senhor vos perdoou, assim também perdoai vós" Este versículo destaca a importância do perdão mútuo e de seguir o exemplo de Cristo em perdoar.
* Efésios 4:32: "Antes, sede bondosos uns para com os outros, compassivos, perdoando-vos uns aos outros, como também Deus, em Cristo, vos perdoou" Este versículo também enfatiza a importância do perdão mútuo e de seguir o exemplo de Deus em perdoar.
* Provérbios 17:9: "Quem encobre uma ofensa busca amor, mas quem a lança em rosto separa bons amigos." Esse versículo destaca a importância de abordar as ofensas com amor e misericórdia, em vez de se apegar a elas e destruir relacionamentos.
* Romanos 12:10: "Amai-vos cordialmente uns aos outros com amor fraternal, preferindo-vos em honra uns aos outros." Este versículo destaca a importância de amar e respeitar uns aos outros na comunidade cristã.
* Gálatas 6:1: "Irmãos, se alguém for surpreendido em algum pecado, vós que sois espirituais, corrigi-o com espírito de brandura; e guarda-te para que não sejas também tentado." Esse versículo destaca a importância da correção fraterna com amor e gentileza, em vez de julgamento e condenação.
****

[[v47-18-1]]

^<<v47-18-1,1>>^ Neste momento, os discípulos aproximaram-se de Jesus e perguntaram-lhe: “Quem é o maior no Reino dos Céus?”.

[[v47-18-2]]

^<<v47-18-2,2>>^ Jesus chamou uma criancinha, colocou-a no meio deles e disse:

[[v47-18-3]]

^<<v47-18-3,3>>^ “Em verdade vos declaro: se não vos transformardes e vos tornardes como criancinhas, não entrareis no Reino dos Céus.^&#42;1^

[[v47-18-4]]

^<<v47-18-4,4>>^ Aquele que se fizer humilde como esta criança será maior no Reino dos Céus.

[[v47-18-5]]

^<<v47-18-5,5>>^ E o que recebe em meu nome a um menino como este, é a mim que recebe.

[[v47-18-6]]

^<<v47-18-6,6>>^ Mas, se alguém fizer cair em pecado um destes pequenos que creem em mim, melhor fora que lhe atassem ao pescoço a mó de um moinho e o lançassem no fundo do mar.

[[v47-18-7]]

^<<v47-18-7,7>>^ Ai do mundo por causa dos escândalos! Eles são inevitáveis, mas ai do homem que os causa!

[[v47-18-8]]

^<<v47-18-8,8>>^ Por isso, se tua mão ou teu pé te fazem cair em pecado, corta-os e lança-os longe de ti: é melhor para ti entrares na vida coxo ou manco que, tendo dois pés e duas mãos, seres lançado no fogo eterno.

[[v47-18-9]]

^<<v47-18-9,9>>^ Se teu olho te leva ao pecado, arranca-o e lança-o longe de ti: é melhor para ti entrares na vida cego de um olho que seres jogado com teus dois olhos no fogo da geena.^&#42;1^

[[v47-18-10]]

^<<v47-18-10,10>>^ Guardai-vos de menosprezar um só destes pequenos, porque eu vos digo que seus anjos no céu contemplam sem cessar a face de meu Pai que está nos céus.

[[v47-18-11]]

^<<v47-18-11,11>>^ [Porque o Filho do Homem veio salvar o que estava perdido.]^&#42;1^

[[v47-18-12]]

^<<v47-18-12,12>>^ Que vos parece? Um homem possui cem ovelhas: uma delas se desgarra. Não deixa ele as noventa e nove na montanha, para ir buscar aquela que se desgarrou?

[[v47-18-13]]

^<<v47-18-13,13>>^ E se a encontra, sente mais júbilo do que pelas noventa e nove que não se desgarraram.

[[v47-18-14]]

^<<v47-18-14,14>>^ Assim é a vontade de vosso Pai celeste, que não se perca um só destes pequeninos”.

[[v47-18-15]]

^<<v47-18-15,15>>^ “Se teu irmão tiver pecado contra ti, vai e repreende-o entre ti e ele somente; se te ouvir, terás ganho teu irmão.

[[v47-18-16]]

^<<v47-18-16,16>>^ Se não te escutar, toma contigo uma ou duas pessoas, a fim de que toda a questão se resolva pela decisão de duas ou três testemunhas.

[[v47-18-17]]

^<<v47-18-17,17>>^ Se recusa ouvi-los, dize-o à Igreja. E se recusar ouvir também a Igreja, seja ele para ti como um pagão e um publicano.

[[v47-18-18]]

^<<v47-18-18,18>>^ Em verdade vos digo: tudo o que ligardes sobre a terra será ligado no céu, e tudo o que desligardes sobre a terra será também desligado no céu.”

[[v47-18-19]]

^<<v47-18-19,19>>^ “Digo-vos ainda isto: se dois de vós se unirem sobre a terra para pedir, seja o que for, o conseguirão de meu Pai que está nos céus.

[[v47-18-20]]

^<<v47-18-20,20>>^ Porque onde dois ou três estão reunidos em meu nome, aí estou eu no meio deles.”

[[v47-18-21]]

^<<v47-18-21,21>>^ Então, Pedro se aproximou dele e disse: “Senhor, quantas vezes devo perdoar a meu irmão, quando ele pecar contra mim? Até sete vezes?”

[[v47-18-22]]

^<<v47-18-22,22>>^ Respondeu Jesus: “Não te digo até sete vezes, mas até setenta vezes sete”.^&#42;1^

[[v47-18-23]]

^<<v47-18-23,23>>^ “Por isso, o Reino dos Céus é comparado a um rei que quis ajustar contas com seus servos.

[[v47-18-24]]

^<<v47-18-24,24>>^ Quando começou a ajustá-las, trouxeram-lhe um que lhe devia dez mil talentos.^&#42;1^

[[v47-18-25]]

^<<v47-18-25,25>>^ Como ele não tinha com que pagar, seu senhor ordenou que fosse vendido, ele, sua mulher, seus filhos e todos os seus bens para pagar a dívida.

[[v47-18-26]]

^<<v47-18-26,26>>^ Este servo, então, prostrou-se por terra diante dele e suplicava-lhe: ‘Dá-me um prazo e eu te pagarei tudo!’.

[[v47-18-27]]

^<<v47-18-27,27>>^ Cheio de compaixão, o senhor o deixou ir embora e perdoou-lhe a dívida.

[[v47-18-28]]

^<<v47-18-28,28>>^ Apenas saiu dali, encontrou um de seus companheiros de serviço que lhe devia cem denários. Agarrou-o na garganta e quase o estrangulou, dizendo: ‘Paga o que me deves!’

[[v47-18-29]]

^<<v47-18-29,29>>^ O outro caiu-lhe aos pés e pediu-lhe: ‘Dá-me um prazo e eu te pagarei!’.

[[v47-18-30]]

^<<v47-18-30,30>>^ Mas, sem nada querer ouvir, este homem o fez lançar na prisão, até que tivesse pago sua dívida.

[[v47-18-31]]

^<<v47-18-31,31>>^ Vendo isso, os outros servos, profundamente tristes, vieram contar a seu senhor o que se tinha passado.

[[v47-18-32]]

^<<v47-18-32,32>>^ Então, o senhor o chamou e lhe disse: ‘Servo mau, eu te perdoei toda a dívida porque me suplicaste.

[[v47-18-33]]

^<<v47-18-33,33>>^ Não devias também tu compadecer-te de teu companheiro de serviço, como eu tive piedade de ti?’.

[[v47-18-34]]

^<<v47-18-34,34>>^ E o senhor, encolerizado, entregou-o aos algozes, até que pagasse toda a sua dívida.

[[v47-18-35]]

^<<v47-18-35,35>>^ Assim vos tratará meu Pai celeste, se cada um de vós não perdoar a seu irmão, de todo o seu coração.”

'''

xref:047-sao-mateus/047-sao-mateus-017.adoc#v47-17-0[&#60; Capítulo Anterior] | <<v47-18-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-019.adoc#v47-19-0[Próximo Capítulo &#62;]