include::./index.adoc[]

[[v47-5-0]]
=== São Mateus, 5
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Mateus 5 é conhecido como o "Sermão da Montanha", um dos discursos mais famosos de Jesus. Neste capítulo, Jesus fala sobre a natureza do Reino de Deus e ensina sobre a ética cristã, incluindo as bem-aventuranças, o papel do cristão no mundo e o cumprimento da Lei. Aqui estão cinco versículos relacionados aos temas abordados em São Mateus 5:
* Provérbios 16:7: "Quando os caminhos de alguém agradam ao Senhor, até seus inimigos vivem em paz com ele." Este versículo fala sobre a importância de seguir o caminho de Deus para viver em paz com os outros, que é um tema abordado por Jesus na parte do Sermão da Montanha que trata das bem-aventuranças.
* Romanos 12:18: "Se possível, quanto depender de vós, tende paz com todos os homens." Este versículo reforça a ideia de buscar a paz com os outros, que é um tema central das bem-aventuranças em São Mateus 5.
* 1 Pedro 2:9: "Mas vós sois a raça escolhida, o sacerdócio real, a nação santa, o povo adquirido para Deus, a fim de que publiqueis as virtudes daquele que vos chamou das trevas para a sua luz admirável." Este versículo fala sobre o papel do cristão no mundo, que é um tema abordado por Jesus em São Mateus 5.
* Mateus 22:37-39: "Amarás o Senhor, teu Deus, de todo o teu coração, de toda a tua alma e de todo o teu espírito. Este é o maior e o primeiro mandamento. O segundo é semelhante a este: Amarás o teu próximo como a ti mesmo." Este versículo resume a ética cristã em termos de amor a Deus e ao próximo, um tema central do Sermão da Montanha.
* Tiago 1:22: "Sede cumpridores da palavra, e não somente ouvintes, enganando-vos a vós mesmos." Este versículo reforça a ideia de que é importante colocar em prática as palavras de Jesus, que é um tema abordado em São Mateus 5 quando Jesus fala sobre cumprir a Lei e os profetas.
****

[[v47-5-1]]

^<<v47-5-1,1>>^ Vendo aquelas multidões, Jesus subiu à montanha. Sentou-se e seus discípulos aproximaram-se dele.

[[v47-5-2]]

^<<v47-5-2,2>>^ Então, abriu a boca e lhes ensinava, dizendo:

[[v47-5-3]]

^<<v47-5-3,3>>^ “Bem-aventurados os que têm um coração de pobre, porque deles é o Reino dos Céus!

[[v47-5-4]]

^<<v47-5-4,4>>^ Bem-aventurados os que choram, porque serão consolados!

[[v47-5-5]]

^<<v47-5-5,5>>^ Bem-aventurados os mansos, porque possuirão a terra!

[[v47-5-6]]

^<<v47-5-6,6>>^ Bem-aventurados os que têm fome e sede de justiça, porque serão saciados!

[[v47-5-7]]

^<<v47-5-7,7>>^ Bem-aventurados os misericordiosos, porque alcançarão misericórdia!

[[v47-5-8]]

^<<v47-5-8,8>>^ Bem-aventurados os puros de coração, porque verão Deus!

[[v47-5-9]]

^<<v47-5-9,9>>^ Bem-aventurados os pacíficos, porque serão chamados filhos de Deus!

[[v47-5-10]]

^<<v47-5-10,10>>^ Bem-aventurados os que são perseguidos por causa da justiça, porque deles é o Reino dos Céus!

[[v47-5-11]]

^<<v47-5-11,11>>^ Bem-aventurados sereis quando vos caluniarem, quando vos perseguirem e disserem falsamente todo o mal contra vós por causa de mim.

[[v47-5-12]]

^<<v47-5-12,12>>^ Alegrai-vos e exultai, porque será grande a vossa recompensa nos céus, pois assim perseguiram os profetas que vieram antes de vós”.

[[v47-5-13]]

^<<v47-5-13,13>>^ “Vós sois o sal da terra. Se o sal perde o sabor, com que lhe será restituído o sabor? Para nada mais serve senão para ser lançado fora e calcado pelos homens.

[[v47-5-14]]

^<<v47-5-14,14>>^ Vós sois a luz do mundo. Não se pode esconder uma cidade situada sobre uma montanha

[[v47-5-15]]

^<<v47-5-15,15>>^ nem se acende uma luz para colocá-la debaixo do alqueire, mas sim para colocá-la sobre o candeeiro, a fim de que brilhe a todos os que estão em casa.

[[v47-5-16]]

^<<v47-5-16,16>>^ Assim, brilhe vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem vosso Pai que está nos céus.”

[[v47-5-17]]

^<<v47-5-17,17>>^ “Não julgueis que vim abolir a Lei ou os profetas. Não vim para os abolir, mas sim para levá-los à perfeição.

[[v47-5-18]]

^<<v47-5-18,18>>^ Pois em verdade vos digo: passará o céu e a terra, antes que desapareça um iota (menor letra do alfabeto hebraico), um traço da Lei.^&#42;1^

[[v47-5-19]]

^<<v47-5-19,19>>^ Aquele que violar um destes mandamentos, por menor que seja, e ensinar assim aos homens, será declarado o menor no Reino dos Céus. Mas aquele que os guardar e os ensinar será declarado grande no Reino dos Céus.

[[v47-5-20]]

^<<v47-5-20,20>>^ Digo-vos, pois, se vossa justiça não for maior que a dos escribas e fariseus, não entrareis no Reino dos Céus.”

[[v47-5-21]]

^<<v47-5-21,21>>^ “Ouvistes o que foi dito aos antigos: Não matarás, mas quem matar será castigado pelo juízo do tribunal.

[[v47-5-22]]

^<<v47-5-22,22>>^ Mas eu vos digo: todo aquele que se irar contra seu irmão será castigado pelos juízes. Aquele que disser a seu irmão: imbecil, será castigado pelo Grande Conselho. Aquele que lhe disser: Louco, será condenado ao fogo da geena.

[[v47-5-23]]

^<<v47-5-23,23>>^ Se estás, portanto, para fazer a tua oferta diante do altar e te lembrares de que teu irmão tem alguma coisa contra ti,

[[v47-5-24]]

^<<v47-5-24,24>>^ deixa lá a tua oferta diante do altar e vai primeiro reconciliar-te com teu irmão; só então vem fazer a tua oferta.

[[v47-5-25]]

^<<v47-5-25,25>>^ Entra em acordo sem demora com o teu adversário, enquanto estás em caminho com ele, para que não suceda que te entregue ao juiz, e o juiz te entregue ao seu ministro e sejas posto em prisão.

[[v47-5-26]]

^<<v47-5-26,26>>^ Em verdade te digo: dali não sairás antes de teres pago o último centavo.

[[v47-5-27]]

^<<v47-5-27,27>>^ Ouvistes que foi dito aos antigos: Não cometerás adultério.

[[v47-5-28]]

^<<v47-5-28,28>>^ Eu, porém, vos digo: todo aquele que lançar um olhar de cobiça para uma mulher já adulterou com ela em seu coração.

[[v47-5-29]]

^<<v47-5-29,29>>^ Se teu olho direito é para ti causa de queda, arranca-o e lança-o longe de ti, porque te é preferível perder-se um só dos teus membros a que o teu corpo todo seja lançado na geena.

[[v47-5-30]]

^<<v47-5-30,30>>^ E se tua mão direita é para ti causa de queda, corta-a e lança-a longe de ti, porque te é preferível perder-se um só dos teus membros a que o teu corpo inteiro seja atirado na geena.

[[v47-5-31]]

^<<v47-5-31,31>>^ Foi também dito: Todo aquele que rejeitar sua mulher, dê-lhe carta de divórcio.

[[v47-5-32]]

^<<v47-5-32,32>>^ Eu, porém, vos digo: todo aquele que rejeita sua mulher a faz tornar-se adúltera, a não ser que se trate de matrimônio falso; e todo aquele que desposa uma mulher rejeitada comete um adultério.

[[v47-5-33]]

^<<v47-5-33,33>>^ Ouvistes ainda o que foi dito aos antigos: Não jurarás falso, mas cumprirás para com o Senhor os teus juramentos.

[[v47-5-34]]

^<<v47-5-34,34>>^ Eu, porém, vos digo: não jureis de modo algum, nem pelo céu, porque é o trono de Deus;

[[v47-5-35]]

^<<v47-5-35,35>>^ nem pela terra, porque é o escabelo de seus pés; nem por Jerusalém, porque é a cidade do grande Rei.

[[v47-5-36]]

^<<v47-5-36,36>>^ Nem jurarás pela tua cabeça, porque não podes fazer um cabelo tornar-se branco ou negro.

[[v47-5-37]]

^<<v47-5-37,37>>^ Dizei somente: ‘Sim’, se é sim; ‘não’, se é não. Tudo o que passa além disso vem do Maligno.^&#42;1^

[[v47-5-38]]

^<<v47-5-38,38>>^ Tendes ouvido o que foi dito: Olho por olho, dente por dente.

[[v47-5-39]]

^<<v47-5-39,39>>^ Eu, porém, vos digo: não resistais ao mau. Se alguém te ferir a face direita, oferece-lhe também a outra.^&#42;1^

[[v47-5-40]]

^<<v47-5-40,40>>^ Se alguém te citar em justiça para tirar-te a túnica, cede-lhe também a capa.

[[v47-5-41]]

^<<v47-5-41,41>>^ Se alguém vem obrigar-te a andar mil passos com ele, anda dois mil.

[[v47-5-42]]

^<<v47-5-42,42>>^ Dá a quem te pede e não te desvies daquele que te quer pedir emprestado.

[[v47-5-43]]

^<<v47-5-43,43>>^ Tendes ouvido o que foi dito: Amarás o teu próximo e poderás odiar teu inimigo.^&#42;1^

[[v47-5-44]]

^<<v47-5-44,44>>^ Eu, porém, vos digo: amai vossos inimigos, fazei bem aos que vos odeiam, orai pelos que vos [maltratam e] perseguem.

[[v47-5-45]]

^<<v47-5-45,45>>^ Deste modo sereis os filhos de vosso Pai do céu, pois ele faz nascer o sol tanto sobre os maus como sobre os bons, e faz chover sobre os justos e sobre os injustos.

[[v47-5-46]]

^<<v47-5-46,46>>^ Se amais somente os que vos amam, que recompensa tereis? Não fazem assim os próprios publicanos?

[[v47-5-47]]

^<<v47-5-47,47>>^ Se saudais apenas vossos irmãos, que fazeis de extraordinário? Não fazem isso também os pagãos?

[[v47-5-48]]

^<<v47-5-48,48>>^ Portanto, sede perfeitos, assim como vosso Pai celeste é perfeito.”

'''

xref:047-sao-mateus/047-sao-mateus-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-006.adoc#v47-6-0[Próximo Capítulo &#62;]