include::./index.adoc[]

[[v47-23-0]]
=== São Mateus, 23
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Mateus 23 contém uma forte condenação de Jesus aos líderes religiosos da época por sua hipocrisia e arrogância. Ele os acusa de impor fardos pesados sobre o povo enquanto eles mesmos não praticam o que pregam. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Jeremias 7:9-10: "Roubam e matam, cometem adultério e juram falsamente; fazem oferendas a Baal e seguem outros deuses que não conheceram. E ainda vêm ao meu templo e o profanam, a minha casa é chamada por eles de 'santuário', mas transformaram-na em covil de ladrões!" - Jesus acusa os líderes religiosos de hipocrisia por impor regras e fardos sobre o povo enquanto eles mesmos cometem pecados graves.
* Provérbios 23:1-3: "Quando você se assentar para comer com um governante, pense bem no que está diante de você, e ponha uma faca à sua garganta se for dado a muitos apetites. Não cobice seus acepipes finos, pois é uma comida enganosa." - Jesus alerta que os líderes religiosos são motivados pelo desejo de ganho pessoal e poder, em vez de cuidar do povo.
* Isaías 29:13: "Este povo se aproxima de mim com a boca e me honra com os lábios, mas o seu coração está longe de mim. A adoração que me prestam é feita só de regras ensinadas por homens." - Jesus acusa os líderes religiosos de se concentrarem apenas na aparência externa da religião e não na verdadeira adoração a Deus.
* Ezequiel 34:2-3: "Filho do homem, profetiza contra os pastores de Israel; profetiza e dize-lhes: Assim diz o Senhor Deus: Ai dos pastores de Israel que se apascentam a si mesmos! Não devem os pastores apascentar as ovelhas? Comeis a gordura, vestis-vos com a lã, degolais o cevado; mas não apascentais as ovelhas." - Jesus acusa os líderes religiosos de não cuidar adequadamente do povo, mas em vez disso, se concentrar em seu próprio conforto e enriquecimento.
* Mateus 6:1-2: "Cuidado com a prática da justiça diante dos outros, apenas para ser visto por eles. Se vocês agirem assim, não terão nenhuma recompensa do Pai celestial. Portanto, quando você der esmola, não anuncie isso com trombetas, como fazem os hipócritas nas sinagogas e nas ruas, a fim de serem honrados pelos outros. Eu lhes asseguro que eles já receberam sua plena recompensa." - Jesus acusa os líderes religiosos de fazer coisas boas apenas para serem vistos pelos outros, em vez de terem a verdadeira motivação de agradar a Deus.
****

[[v47-23-1]]

^<<v47-23-1,1>>^ Dirigindo-se, então, Jesus à multidão e aos seus discípulos, disse:

[[v47-23-2]]

^<<v47-23-2,2>>^ “Os escribas e os fariseus sentaram-se na cadeira de Moisés.

[[v47-23-3]]

^<<v47-23-3,3>>^ Observai e fazei tudo o que eles dizem, mas não façais como eles, pois dizem e não fazem.

[[v47-23-4]]

^<<v47-23-4,4>>^ Atam fardos pesados e esmagadores e com eles sobrecarregam os ombros dos homens, mas não querem movê-los sequer com o dedo.

[[v47-23-5]]

^<<v47-23-5,5>>^ Fazem todas as suas ações para serem vistos pelos homens, por isso trazem largas faixas e longas franjas nos seus mantos.

[[v47-23-6]]

^<<v47-23-6,6>>^ Gostam dos primeiros lugares nos banquetes e das primeiras cadeiras nas sinagogas.

[[v47-23-7]]

^<<v47-23-7,7>>^ Gostam de ser saudados nas praças públicas e de ser chamados rabi pelos homens.

[[v47-23-8]]

^<<v47-23-8,8>>^ Mas vós não vos façais chamar rabi, porque um só é o vosso preceptor, e vós sois todos irmãos.

[[v47-23-9]]

^<<v47-23-9,9>>^ E a ninguém chameis de pai sobre a terra, porque um só é vosso Pai, aquele que está nos céus.

[[v47-23-10]]

^<<v47-23-10,10>>^ Nem vos façais chamar de mestres, porque só tendes um Mestre, o Cristo.

[[v47-23-11]]

^<<v47-23-11,11>>^ O maior dentre vós será vosso servo.

[[v47-23-12]]

^<<v47-23-12,12>>^ Aquele que se exaltar será humilhado, e aquele que se humilhar será exaltado.

[[v47-23-13]]

^<<v47-23-13,13>>^ Ai de vós, escribas e fariseus hipócritas! Vós fechais aos homens o Reino dos Céus. Vós mesmos não entrais e nem deixais que entrem os que querem entrar.

[[v47-23-14]]

^<<v47-23-14,14>>^ [Ai de vós, escribas e fariseus hipócritas! Devorais as casas das viúvas, fingindo fazer longas orações. Por isso, sereis castigados com muito maior rigor.]^&#42;1^

[[v47-23-15]]

^<<v47-23-15,15>>^ Ai de vós, escribas e fariseus hipócritas! Percorreis mares e terras para fazer um prosélito e, quando o conseguis, fazeis dele um filho do inferno duas vezes pior que vós mesmos.^&#42;1^

[[v47-23-16]]

^<<v47-23-16,16>>^ Ai de vós, guias cegos! Vós dizeis: Se alguém jura pelo templo, isto não é nada; mas, se jura pelo tesouro do templo, é obrigado pelo seu juramento.

[[v47-23-17]]

^<<v47-23-17,17>>^ Insensatos, cegos! Qual é o maior: o ouro ou o templo que santifica o ouro?

[[v47-23-18]]

^<<v47-23-18,18>>^ E dizeis ainda: Se alguém jura pelo altar, não é nada; mas, se jura pela oferta que está sobre ele, é obrigado.

[[v47-23-19]]

^<<v47-23-19,19>>^ Cegos! Qual é o maior: a oferta ou o altar que santifica a oferta?

[[v47-23-20]]

^<<v47-23-20,20>>^ Aquele que jura pelo altar jura ao mesmo tempo por tudo o que está sobre ele.

[[v47-23-21]]

^<<v47-23-21,21>>^ Aquele que jura pelo templo, jura ao mesmo tempo por aquele que nele habita.

[[v47-23-22]]

^<<v47-23-22,22>>^ E aquele que jura pelo céu, jura ao mesmo tempo pelo trono de Deus e por aquele que nele está sentado.

[[v47-23-23]]

^<<v47-23-23,23>>^ “Ai de vós, escribas e fariseus hipócritas! Pagais o dízimo da hortelã, do endro e do cominho e desprezais os preceitos mais importantes da Lei: a justiça, a misericórdia, a fidelidade. Eis o que era preciso praticar em primeiro lugar sem, contudo, deixar o restante.

[[v47-23-24]]

^<<v47-23-24,24>>^ Guias cegos! Filtrais um mosquito e engolis um camelo.

[[v47-23-25]]

^<<v47-23-25,25>>^ Ai de vós, escribas e fariseus hipócritas! Limpais por fora o copo e o prato e por dentro estais cheios de roubo e de intemperança.

[[v47-23-26]]

^<<v47-23-26,26>>^ Fariseu cego! Limpa primeiro o interior do copo e do prato, para que também o que está fora fique limpo.

[[v47-23-27]]

^<<v47-23-27,27>>^ Ai de vós, escribas e fariseus hipócritas! Sois semelhantes aos sepulcros caiados: por fora parecem formosos, mas por dentro estão cheios de ossos, de cadáveres e de toda espécie de podridão.^&#42;1^

[[v47-23-28]]

^<<v47-23-28,28>>^ Assim também vós: por fora pareceis justos aos olhos dos homens, mas por dentro estais cheios de hipocrisia e de iniquidade.

[[v47-23-29]]

^<<v47-23-29,29>>^ Ai de vós, escribas e fariseus hipócritas! Edificais sepulcros aos profetas, adornais os monumentos dos justos

[[v47-23-30]]

^<<v47-23-30,30>>^ e dizeis: Se tivéssemos vivido no tempo de nossos pais, não teríamos manchado nossas mãos como eles no sangue dos profetas...

[[v47-23-31]]

^<<v47-23-31,31>>^ Testemunhais assim contra vós mesmos que sois de fato os filhos dos assassinos dos profetas.

[[v47-23-32]]

^<<v47-23-32,32>>^ Acabai, pois, de encher a medida de vossos pais!^&#42;1^

[[v47-23-33]]

^<<v47-23-33,33>>^ Serpentes! Raça de víboras! Como escapareis ao castigo do inferno?

[[v47-23-34]]

^<<v47-23-34,34>>^ Vede, eu vos envio profetas, sábios, doutores. Matareis e crucificareis uns e açoitareis outros nas vossas sinagogas. Eu os perseguireis de cidade em cidade,

[[v47-23-35]]

^<<v47-23-35,35>>^ para que caia sobre vós todos o sangue inocente derramado sobre a terra, desde o sangue de Abel, o justo, até o sangue de Zacarias, filho de Baraquias, a quem matastes entre o templo e o altar.

[[v47-23-36]]

^<<v47-23-36,36>>^ Em verdade vos digo: todos esses crimes pesam sobre esta raça.

[[v47-23-37]]

^<<v47-23-37,37>>^ Jerusalém, Jerusalém, que matas os profetas e apedrejas aqueles que te são enviados! Quantas vezes eu quis reunir teus filhos, como a galinha reúne seus pintinhos debaixo de suas asas... e tu não quiseste!

[[v47-23-38]]

^<<v47-23-38,38>>^ Pois bem, a vossa casa vos é deixada deserta.

[[v47-23-39]]

^<<v47-23-39,39>>^ Porque eu vos digo: já não me vereis de hoje em diante, até que digais: Bendito seja aquele que vem em nome do Senhor.”

'''

xref:047-sao-mateus/047-sao-mateus-022.adoc#v47-22-0[&#60; Capítulo Anterior] | <<v47-23-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-024.adoc#v47-24-0[Próximo Capítulo &#62;]