include::./index.adoc[]

[[v47-26-0]]
=== São Mateus, 26
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Mateus 26 descreve a conspiração dos líderes religiosos para prender e condenar Jesus, a última ceia, a traição de Judas, a prisão de Jesus e Seu julgamento diante do Sinédrio. Também relata a negação de Pedro e a flagelação de Jesus. Aqui estão cinco versículos relacionados aos temas abordados em São Mateus 26:
* Salmos 2:2 - "Os reis da terra se levantam, e os príncipes conspiram contra o Senhor e contra o seu ungido." Este verso profético mostra que a conspiração dos líderes religiosos contra Jesus estava prevista nas Escrituras.
* Isaías 53:3 - "Era desprezado e o mais rejeitado entre os homens; homem de dores e que sabe o que é padecer; e como um de quem os homens escondem o rosto, era desprezado, e dele não fizemos caso." Este verso profético se aplica a Jesus, que foi rejeitado e maltratado pelos líderes religiosos e pelo povo em geral.
* Salmos 41:9 - "Até o meu amigo íntimo, em quem eu confiava, que comia do meu pão, levantou contra mim o seu calcanhar." Este verso profético se aplica à traição de Judas, que era um dos discípulos mais próximos de Jesus.
* Isaías 50:6 - "Ofereci as minhas costas aos que me feriam, e as minhas faces aos que me arrancavam a barba; não escondi o meu rosto dos que me afrontavam e me cuspiam." Este verso profético se aplica à flagelação de Jesus e à Sua disposição em sofrer pelo bem da humanidade.
* Salmos 22:18 - "Repartem entre si as minhas vestes, e lançam sortes sobre a minha túnica." Este verso profético se aplica à cena da crucificação de Jesus, quando os soldados romanos dividiram as Suas roupas entre si.
****

[[v47-26-1]]

^<<v47-26-1,1>>^ Quando Jesus acabou todos esses discursos, disse a seus discípulos:

[[v47-26-2]]

^<<v47-26-2,2>>^ “Sabeis que daqui a dois dias será a Páscoa, e o Filho do Homem será traído para ser crucificado”.

[[v47-26-3]]

^<<v47-26-3,3>>^ Então, os príncipes dos sacerdotes e os anciãos do povo reuniram-se no pátio do sumo sacerdote, chamado Caifás,

[[v47-26-4]]

^<<v47-26-4,4>>^ e deliberaram sobre os meios de prender Jesus por astúcia e de o matar.

[[v47-26-5]]

^<<v47-26-5,5>>^ E diziam: “Sobretudo, não seja durante a festa. Poderá haver um tumulto entre o povo”.

[[v47-26-6]]

^<<v47-26-6,6>>^ Encontrava-se Jesus em Betânia, na casa de Simão, o leproso.

[[v47-26-7]]

^<<v47-26-7,7>>^ Estando à mesa, aproximou-se dele uma mulher com um vaso de alabastro, cheio de perfume muito caro, e derramou-o na sua cabeça.

[[v47-26-8]]

^<<v47-26-8,8>>^ Vendo isso, os discípulos disseram indignados: “Para que este desperdício?

[[v47-26-9]]

^<<v47-26-9,9>>^ Poderia vender este perfume por um bom preço e dar o dinheiro aos pobres”.

[[v47-26-10]]

^<<v47-26-10,10>>^ Jesus ouviu-os e disse-lhes: “Por que molestais esta mulher? É uma ação boa o que ela me fez.

[[v47-26-11]]

^<<v47-26-11,11>>^ Pobres vós tereis sempre convosco. A mim, porém, nem sempre me tereis.

[[v47-26-12]]

^<<v47-26-12,12>>^ Derramando esse perfume em meu corpo, ela o fez em vista da minha sepultura.^&#42;1^

[[v47-26-13]]

^<<v47-26-13,13>>^ Em verdade eu vos digo: em toda parte onde for pregado este Evangelho pelo mundo inteiro, será contado em sua memória o que ela fez”.

[[v47-26-14]]

^<<v47-26-14,14>>^ Então, um dos Doze, chamado Judas Iscariotes, foi ter com os príncipes dos sacerdotes e perguntou-lhes:

[[v47-26-15]]

^<<v47-26-15,15>>^ “Que quereis dar-me e eu vo-lo entregarei”. Ajustaram com ele trinta moedas de prata.^&#42;1^

[[v47-26-16]]

^<<v47-26-16,16>>^ E desde aquele instante, procurava uma ocasião favorável para entregar Jesus.

[[v47-26-17]]

^<<v47-26-17,17>>^ No primeiro dia dos ázimos, os discípulos aproximaram-se de Jesus e perguntaram-lhe: “Onde queres que preparemos a ceia pascal?”.^&#42;1^

[[v47-26-18]]

^<<v47-26-18,18>>^ Respondeu-lhes Jesus: “Ide à cidade, à casa de um tal, e dizei-lhe: O Mestre manda dizer-te: Meu tempo está próximo. É em tua casa que celebrarei a Páscoa com meus discípulos”.

[[v47-26-19]]

^<<v47-26-19,19>>^ Os discípulos fizeram o que Jesus tinha ordenado e prepararam a Páscoa.

[[v47-26-20]]

^<<v47-26-20,20>>^ Ao declinar da tarde, pôs-se Jesus à mesa com os doze discípulos.

[[v47-26-21]]

^<<v47-26-21,21>>^ Durante a ceia, disse: “Em verdade vos digo: um de vós me há de trair”.

[[v47-26-22]]

^<<v47-26-22,22>>^ Com profunda aflição, cada um começou a perguntar: “Sou eu, Senhor?”.

[[v47-26-23]]

^<<v47-26-23,23>>^ Respondeu ele: “Aquele que pôs comigo a mão no prato, esse me trairá.

[[v47-26-24]]

^<<v47-26-24,24>>^ O Filho do Homem vai, como dele está escrito. Mas ai daquele homem por quem o Filho do Homem é traído! Seria melhor para esse homem que jamais tivesse nascido!”.

[[v47-26-25]]

^<<v47-26-25,25>>^ Judas, o traidor, tomou a palavra e perguntou: “Mestre, serei eu?”. “Sim” – disse Jesus.

[[v47-26-26]]

^<<v47-26-26,26>>^ Durante a refeição, Jesus tomou o pão, benzeu-o, partiu-o e o deu aos discípulos, dizendo: “Tomai e comei, isto é meu corpo”.

[[v47-26-27]]

^<<v47-26-27,27>>^ Tomou depois o cálice, rendeu graças e deu-lho, dizendo: “Bebei dele todos,

[[v47-26-28]]

^<<v47-26-28,28>>^ porque isto é meu sangue, o sangue da Nova Aliança, derramado por muitos homens em remissão dos pecados.^&#42;1^

[[v47-26-29]]

^<<v47-26-29,29>>^ Digo-vos: doravante não beberei mais desse fruto da vinha até o dia em que o beberei de novo convosco no Reino de meu Pai”.

[[v47-26-30]]

^<<v47-26-30,30>>^ Depois do canto dos Salmos, dirigiram-se eles para o monte das Oliveiras.

[[v47-26-31]]

^<<v47-26-31,31>>^ Disse-lhes então Jesus: “Esta noite serei para todos vós uma ocasião de queda; porque está escrito: Ferirei o pastor, e as ovelhas do rebanho serão dispersadas (Zc 13,7).

[[v47-26-32]]

^<<v47-26-32,32>>^ Mas, depois da minha Ressurreição, eu vos precederei na Galileia”.

[[v47-26-33]]

^<<v47-26-33,33>>^ Pedro interveio: “Mesmo que sejas para todos uma ocasião de queda, para mim jamais o serás”.

[[v47-26-34]]

^<<v47-26-34,34>>^ Disse-lhe Jesus: “Em verdade te digo: nesta noite mesma, antes que o galo cante, três vezes me negarás”.

[[v47-26-35]]

^<<v47-26-35,35>>^ Respondeu-lhe Pedro: “Mesmo que seja necessário morrer contigo, jamais te negarei!”. E todos os outros discípulos diziam-lhe o mesmo.

[[v47-26-36]]

^<<v47-26-36,36>>^ Retirou-se Jesus com eles para um lugar chamado Getsêmani e disse-lhes: “Assentai-vos aqui, enquanto eu vou ali orar...^&#42;1^

[[v47-26-37]]

^<<v47-26-37,37>>^ E, tomando consigo Pedro e os dois filhos de Zebedeu, começou a entristecer-se e a angustiar-se.

[[v47-26-38]]

^<<v47-26-38,38>>^ Disse-lhes, então: “Minha alma está triste até a morte. Ficai aqui e vigiai comigo”.

[[v47-26-39]]

^<<v47-26-39,39>>^ Adiantou-se um pouco e, prostrando-se com a face por terra, assim rezou: “Meu Pai, se é possível, afasta de mim este cálice! Todavia, não se faça o que eu quero, mas sim o que tu queres”.

[[v47-26-40]]

^<<v47-26-40,40>>^ Foi ter então com os discípulos e os encontrou dormindo. E disse a Pedro: “Então, não pudestes vigiar uma hora comigo...

[[v47-26-41]]

^<<v47-26-41,41>>^ Vigiai e orai para que não entreis em tentação. O espírito está pronto, mas a carne é fraca”.

[[v47-26-42]]

^<<v47-26-42,42>>^ Afastou-se pela segunda vez e orou, dizendo: “Meu Pai, se não é possível que este cálice passe sem que eu o beba, faça-se a tua vontade!”

[[v47-26-43]]

^<<v47-26-43,43>>^ Voltou ainda e os encontrou novamente dormindo, porque seus olhos estavam pesados.

[[v47-26-44]]

^<<v47-26-44,44>>^ Deixou-os e foi orar pela terceira vez, dizendo as mesmas palavras.

[[v47-26-45]]

^<<v47-26-45,45>>^ Voltou, então, para os seus discípulos e disse-lhes: “Dormi agora e repousai! Chegou a hora: o Filho do Homem vai ser entregue nas mãos dos pecadores...

[[v47-26-46]]

^<<v47-26-46,46>>^ Levantai-vos, vamos! Aquele que me trai está perto daqui”.

[[v47-26-47]]

^<<v47-26-47,47>>^ Jesus ainda falava, quando veio Judas, um dos Doze, e com ele uma multidão de gente armada de espadas e cacetes, enviada pelos príncipes dos sacerdotes e pelos anciãos do povo.

[[v47-26-48]]

^<<v47-26-48,48>>^ O traidor combinara com eles este sinal: “Aquele que eu beijar, é ele. Prendei-o!”.

[[v47-26-49]]

^<<v47-26-49,49>>^ Aproximou-se imediatamente de Jesus e disse: “Salve, Mestre”. E beijou-o.

[[v47-26-50]]

^<<v47-26-50,50>>^ Disse-lhe Jesus: “É, então, para isso que vens aqui?”. Em seguida, adiantaram-se eles e lançaram mão em Jesus para prendê-lo.

[[v47-26-51]]

^<<v47-26-51,51>>^ Mas um dos companheiros de Jesus desembainhou a espada e feriu um servo do sumo sacerdote, decepando-lhe a orelha.

[[v47-26-52]]

^<<v47-26-52,52>>^ Jesus, no entanto, lhe disse: “Embainha tua espada, porque todos aqueles que usarem da espada, pela espada morrerão.

[[v47-26-53]]

^<<v47-26-53,53>>^ Crês tu que não posso invocar meu Pai e ele não me enviaria imediatamente mais de doze legiões de anjos?

[[v47-26-54]]

^<<v47-26-54,54>>^ Mas como se cumpririam então as Escrituras, segundo as quais é preciso que seja assim?”.

[[v47-26-55]]

^<<v47-26-55,55>>^ Depois, voltando-se para a turba, falou: “Saístes armados de espadas e porretes para prender-me, como se eu fosse um malfeitor. Entretanto, todos os dias estava eu sentado entre vós ensinando no templo e não me prendestes.

[[v47-26-56]]

^<<v47-26-56,56>>^ Mas tudo isto aconteceu porque era necessário que se cumprissem os oráculos dos profetas”. Então, os discípulos o abandonaram e fugiram.

[[v47-26-57]]

^<<v47-26-57,57>>^ Os que haviam prendido Jesus levaram-no à casa do sumo sacerdote Caifás, onde estavam reunidos os escribas e os anciãos do povo.

[[v47-26-58]]

^<<v47-26-58,58>>^ Pedro seguia-o de longe, até o pátio do sumo sacerdote. Entrou e sentou-se junto aos criados para ver como terminaria aquilo.

[[v47-26-59]]

^<<v47-26-59,59>>^ Enquanto isso, os príncipes dos sacerdotes e todo o conselho procuravam um falso testemunho contra Jesus, a fim de o levarem à morte.

[[v47-26-60]]

^<<v47-26-60,60>>^ Mas não o conseguiram, embora se apresentassem muitas falsas testemunhas.

[[v47-26-61]]

^<<v47-26-61,61>>^ Por fim, apresentaram-se duas testemunhas, que disseram: “Este homem disse: Posso destruir o Templo de Deus e reedificá-lo em três dias”.^&#42;1^

[[v47-26-62]]

^<<v47-26-62,62>>^ Levantou-se o sumo sacerdote e lhe perguntou: “Nada tens a responder ao que essa gente depõe contra ti?”.

[[v47-26-63]]

^<<v47-26-63,63>>^ Jesus, no entanto, permanecia calado. Disse-lhe o sumo sacerdote: “Por Deus vivo, conjuro-te que nos digas se és o Cristo, o Filho de Deus?”.

[[v47-26-64]]

^<<v47-26-64,64>>^ Jesus respondeu: “Sim. Além disso, eu vos declaro que vereis doravante o Filho do Homem sentar-se à direita do Todo-poderoso, e voltar sobre as nuvens do céu”.

[[v47-26-65]]

^<<v47-26-65,65>>^ A essas palavras, o sumo sacerdote rasgou suas vestes, exclamando: “Que necessidade temos ainda de testemunhas? Acabastes de ouvir a blasfêmia!

[[v47-26-66]]

^<<v47-26-66,66>>^ Qual o vosso parecer?”. Eles responderam: “Merece a morte!”.

[[v47-26-67]]

^<<v47-26-67,67>>^ Cuspiram-lhe então na face, bateram-lhe com os punhos e deram-lhe tapas,

[[v47-26-68]]

^<<v47-26-68,68>>^ dizendo: “Adivinha, ó Cristo: quem te bateu?”. (= Mc 14,66-72 = Lc 22,55-62 = Jo 18,15-27)

[[v47-26-69]]

^<<v47-26-69,69>>^ Enquanto isso, Pedro estava sentado no pátio. Aproximou-se dele uma das servas, dizendo: “Também tu estavas com Jesus, o Galileu”.

[[v47-26-70]]

^<<v47-26-70,70>>^ Mas ele negou publicamente, nestes termos: “Não sei o que dizes”.

[[v47-26-71]]

^<<v47-26-71,71>>^ Dirigia-se ele para a porta, a fim de sair, quando outra criada o viu e disse aos que lá estavam: “Este homem também estava com Jesus de Nazaré”.

[[v47-26-72]]

^<<v47-26-72,72>>^ Pedro, pela segunda vez, negou com juramento: “Eu nem conheço tal homem”.

[[v47-26-73]]

^<<v47-26-73,73>>^ Pouco depois, os que ali estavam aproximaram-se de Pedro e disseram: “Sim, tu és daqueles; teu modo de falar te dá a conhecer”.

[[v47-26-74]]

^<<v47-26-74,74>>^ Pedro, então, começou a fazer imprecações, jurando que nem sequer conhecia tal homem. E, neste momento, cantou o galo.

[[v47-26-75]]

^<<v47-26-75,75>>^ Pedro recordou-se do que Jesus lhe dissera: “Antes que o galo cante, tu me negarás três vezes”. E saindo, chorou amargamente.

'''

xref:047-sao-mateus/047-sao-mateus-025.adoc#v47-25-0[&#60; Capítulo Anterior] | <<v47-26-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-027.adoc#v47-27-0[Próximo Capítulo &#62;]