include::./index.adoc[]

[[v47-27-0]]
=== São Mateus, 27
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Mateus 27 é o capítulo que relata a crucificação e morte de Jesus. Também são narrados alguns eventos que ocorreram durante a sua prisão e julgamento. A seguir, estão cinco versículos relacionados com os temas abordados nesse capítulo:
* Isaías 53:5: "Mas ele foi traspassado por causa das nossas transgressões, foi esmagado por causa de nossas iniquidades; o castigo que nos trouxe paz estava sobre ele, e pelas suas feridas fomos curados." Esse versículo profético de Isaías descreve a morte de Jesus e o propósito dela em nos trazer paz e cura.
* Marcos 15:22-24: "Levaram Jesus ao lugar chamado Gólgota (que significa lugar da Caveira). Ali lhe deram vinho misturado com fel; ele provou, mas não quis beber. Depois de o crucificarem, dividiram as roupas dele, tirando sortes para ver quem ficaria com cada uma." Esse versículo do Evangelho de Marcos descreve o local onde Jesus foi crucificado e o tratamento cruel que ele recebeu dos soldados romanos.
* Lucas 23:34: "Jesus dizia: Pai, perdoa-lhes, porque não sabem o que estão fazendo. Então dividiram as roupas dele, tirando sortes." Esse versículo do Evangelho de Lucas mostra o caráter misericordioso e perdoador de Jesus, mesmo quando estava sendo crucificado.
* João 19:26-27: "Quando Jesus viu sua mãe ali, e perto dela o discípulo a quem ele amava, disse à sua mãe: Mulher, aqui está o seu filho, e ao discípulo: Aqui está a sua mãe. Daquela hora em diante, o discípulo a recebeu em sua casa." Esse versículo do Evangelho de João mostra o cuidado e preocupação de Jesus com sua mãe e sua preocupação em garantir que ela fosse bem cuidada após a sua morte.
* Hebreus 9:28: "Assim também Cristo foi oferecido em sacrifício uma única vez, para tirar os pecados de muitos; e aparecerá segunda vez, não para tirar o pecado, mas para trazer salvação aos que o aguardam." Esse versículo da Epístola aos Hebreus explica o significado da morte de Jesus como um sacrifício pelos nossos pecados e a promessa da sua segunda vinda para trazer a salvação.
****

[[v47-27-1]]

^<<v47-27-1,1>>^ Chegando a manhã, todos os príncipes dos sacerdotes e os anciãos do povo reuniram-se em conselho para entregar Jesus à morte.

[[v47-27-2]]

^<<v47-27-2,2>>^ Ligaram-no e o levaram ao governador Pilatos.^&#42;1^

[[v47-27-3]]

^<<v47-27-3,3>>^ Judas, o traidor, vendo-o então condenado, tomado de remorsos, foi devolver aos príncipes dos sacerdotes e aos anciãos as trinta moedas de prata,

[[v47-27-4]]

^<<v47-27-4,4>>^ dizendo-lhes: “Pequei, entregando o sangue de um justo”. Responderam-lhe: “Que nos importa? Isto é lá contigo!”.

[[v47-27-5]]

^<<v47-27-5,5>>^ Ele jogou então no templo as moedas de prata, saiu e foi enforcar-se.

[[v47-27-6]]

^<<v47-27-6,6>>^ Os príncipes dos sacerdotes tomaram o dinheiro e disseram: “Não é permitido lançá-lo no tesouro sagrado, porque se trata de preço de sangue”.

[[v47-27-7]]

^<<v47-27-7,7>>^ Depois de haverem deliberado, compraram com aquela soma o campo do Oleiro, para que ali se fizesse um cemitério de estrangeiros.

[[v47-27-8]]

^<<v47-27-8,8>>^ Essa é a razão por que aquele terreno é chamado, ainda hoje, “Campo de Sangue”.

[[v47-27-9]]

^<<v47-27-9,9>>^ Assim se cumpriu a profecia do profeta Jeremias: Eles receberam trinta moedas de prata, preço daquele cujo valor foi estimado pelos filhos de Israel;^&#42;1^

[[v47-27-10]]

^<<v47-27-10,10>>^ e deram-no pelo campo do Oleiro, como o Senhor me havia prescrito.

[[v47-27-11]]

^<<v47-27-11,11>>^ Jesus compareceu diante do governador, que o interrogou: “És o rei dos judeus?”. “Sim” –, respondeu-lhe Jesus.

[[v47-27-12]]

^<<v47-27-12,12>>^ Ele, porém, nada respondia às acusações dos príncipes dos sacerdotes e dos anciãos.

[[v47-27-13]]

^<<v47-27-13,13>>^ Perguntou-lhe Pilatos: “Não ouves todos os testemunhos que levantam contra ti?”.

[[v47-27-14]]

^<<v47-27-14,14>>^ Mas, para grande admiração do governador, não quis responder a nenhuma acusação.

[[v47-27-15]]

^<<v47-27-15,15>>^ Era costume que o governador soltasse um preso a pedido do povo em cada festa de Páscoa.

[[v47-27-16]]

^<<v47-27-16,16>>^ Ora, havia naquela ocasião um prisioneiro famoso, chamado Barrabás.

[[v47-27-17]]

^<<v47-27-17,17>>^ Pilatos dirigiu-se ao povo reunido: “Qual quereis que eu vos solte: Barrabás ou Jesus, que se chama Cristo?”.

[[v47-27-18]]

^<<v47-27-18,18>>^ (Ele sabia que tinham entregue Jesus por inveja.)

[[v47-27-19]]

^<<v47-27-19,19>>^ Enquanto estava sentado no tribunal, sua mulher lhe mandou dizer: “Nada faças a esse justo. Fui hoje atormentada por um sonho que lhe diz respeito”.

[[v47-27-20]]

^<<v47-27-20,20>>^ Mas os príncipes dos sacerdotes e os anciãos persuadiram o povo que pedisse a libertação de Barrabás e fizesse morrer Jesus.

[[v47-27-21]]

^<<v47-27-21,21>>^ O governador tomou então a palavra: “Qual dos dois quereis que eu vos solte?”. Responderam: “Barrabás!”.

[[v47-27-22]]

^<<v47-27-22,22>>^ Pilatos perguntou: “Que farei então de Jesus, que é chamado o Cristo?”. Todos responderam: “Seja crucificado!”.

[[v47-27-23]]

^<<v47-27-23,23>>^ O governador tornou a perguntar: “Mas que mal fez ele?”. E gritavam ainda mais forte: “Seja crucificado!”.

[[v47-27-24]]

^<<v47-27-24,24>>^ Pilatos viu que nada adiantava, mas que, ao contrário, o tumulto crescia. Fez com que lhe trouxessem água, lavou as mãos diante do povo e disse: “Sou inocente do sangue deste homem. Isto é lá convosco!”.

[[v47-27-25]]

^<<v47-27-25,25>>^ E todo o povo respondeu: “Caia sobre nós o seu sangue e sobre nossos filhos!”.

[[v47-27-26]]

^<<v47-27-26,26>>^ Libertou então Barrabás, mandou açoitar Jesus e lho entregou para ser crucificado.

[[v47-27-27]]

^<<v47-27-27,27>>^ Os soldados do governador conduziram Jesus para o pretório e rodearam-no com todo o pelotão.

[[v47-27-28]]

^<<v47-27-28,28>>^ Arrancaram-lhe as vestes e colocaram-lhe um manto escarlate.

[[v47-27-29]]

^<<v47-27-29,29>>^ Depois, trançaram uma coroa de espinhos, meteram-lha na cabeça e puseram-lhe na mão uma vara. Dobrando os joelhos diante dele, diziam com escárnio: “Salve, rei dos judeus!”.

[[v47-27-30]]

^<<v47-27-30,30>>^ Cuspiam-lhe no rosto e, tomando da vara, davam-lhe golpes na cabeça.

[[v47-27-31]]

^<<v47-27-31,31>>^ Depois de escarnecerem dele, tiraram-lhe o manto e entregaram-lhe as vestes. Em seguida, levaram-no para o crucificar.

[[v47-27-32]]

^<<v47-27-32,32>>^ Saindo, encontraram um homem de Cirene, chamado Simão, a quem obrigaram a levar a cruz de Jesus.

[[v47-27-33]]

^<<v47-27-33,33>>^ Chegaram ao lugar chamado Gólgota, isto é, lugar do crânio.

[[v47-27-34]]

^<<v47-27-34,34>>^ Deram-lhe de beber vinho misturado com fel. Ele provou, mas se recusou a beber.^&#42;1^

[[v47-27-35]]

^<<v47-27-35,35>>^ Depois de o haverem crucificado, dividiram suas vestes entre si, tirando à sorte. Cumpriu-se assim a profecia do profeta: Repartiram entre si minhas vestes e sobre meu manto lançaram à sorte (Sl 21,19).

[[v47-27-36]]

^<<v47-27-36,36>>^ Sentaram-se e montaram guarda.

[[v47-27-37]]

^<<v47-27-37,37>>^ Por cima de sua cabeça penduraram um escrito trazendo o motivo de sua crucificação: “Este é Jesus, o rei dos judeus”.

[[v47-27-38]]

^<<v47-27-38,38>>^ Ao mesmo tempo foram crucificados com ele dois ladrões, um à sua direita e outro à sua esquerda.

[[v47-27-39]]

^<<v47-27-39,39>>^ Os que passavam o injuriavam, sacudiam a cabeça e diziam:

[[v47-27-40]]

^<<v47-27-40,40>>^ “Tu, que destróis o templo e o reconstróis em três dias, salva-te a ti mesmo! Se és o Filho de Deus, desce da cruz!”.

[[v47-27-41]]

^<<v47-27-41,41>>^ Os príncipes dos sacerdotes, os escribas e os anciãos também zombavam dele:

[[v47-27-42]]

^<<v47-27-42,42>>^ “Ele salvou a outros e não pode salvar-se a si mesmo! Se é rei de Israel, desça agora da cruz e nós creremos nele!

[[v47-27-43]]

^<<v47-27-43,43>>^ Confiou em Deus, Deus o livre agora, se o ama, porque ele disse: Eu sou o Filho de Deus!”.

[[v47-27-44]]

^<<v47-27-44,44>>^ E os ladrões, crucificados com ele, também o ultrajavam.

[[v47-27-45]]

^<<v47-27-45,45>>^ Desde a hora sexta até a nona, cobriu-se toda a terra de trevas.

[[v47-27-46]]

^<<v47-27-46,46>>^ Próximo da hora nona, Jesus exclamou em voz forte: “Eli, Eli, lammá sabactáni?” – o que quer dizer: “Meu Deus, meu Deus, por que me abandonaste?”.^&#42;1^

[[v47-27-47]]

^<<v47-27-47,47>>^ A essas palavras, alguns dos que lá estavam diziam: “Ele chama por Elias”.

[[v47-27-48]]

^<<v47-27-48,48>>^ Imediatamente, um deles tomou uma esponja, embebeu-a em vinagre e apresentou-lha na ponta de uma vara para que bebesse.

[[v47-27-49]]

^<<v47-27-49,49>>^ Os outros diziam: “Deixa! Vejamos se Elias virá socorrê-lo”.

[[v47-27-50]]

^<<v47-27-50,50>>^ Jesus de novo lançou um grande brado, e entregou a alma.

[[v47-27-51]]

^<<v47-27-51,51>>^ E eis que o véu do templo se rasgou em duas partes de alto a baixo, a terra tremeu, fenderam-se as rochas.^&#42;1^

[[v47-27-52]]

^<<v47-27-52,52>>^ Os sepulcros se abriram e os corpos de muitos justos ressuscitaram.

[[v47-27-53]]

^<<v47-27-53,53>>^ Saindo de suas sepulturas, entraram na cidade santa depois da ressurreição de Jesus e apareceram a muitas pessoas.

[[v47-27-54]]

^<<v47-27-54,54>>^ O centurião e seus homens que montavam guarda a Jesus, diante do estremecimento da terra e de tudo o que se passava, disseram entre si, possuídos de grande temor: “Verdadeiramente, este homem era Filho de Deus!”.

[[v47-27-55]]

^<<v47-27-55,55>>^ Havia ali também algumas mulheres que de longe olhavam; tinham seguido Jesus desde a Galileia para o servir.

[[v47-27-56]]

^<<v47-27-56,56>>^ Entre elas se achavam Maria Madalena e Maria, mãe de Tiago e de José, e a mãe dos filhos de Zebedeu.

[[v47-27-57]]

^<<v47-27-57,57>>^ À tardinha, um homem rico de Arimateia, chamado José, que era também discípulo de Jesus,

[[v47-27-58]]

^<<v47-27-58,58>>^ foi procurar Pilatos e pediu-lhe o corpo de Jesus. Pilatos cedeu-o.

[[v47-27-59]]

^<<v47-27-59,59>>^ José tomou o corpo, envolveu-o num lençol branco

[[v47-27-60]]

^<<v47-27-60,60>>^ e o depositou num sepulcro novo, que tinha mandado talhar para si na rocha. Depois rolou uma grande pedra à entrada do sepulcro e foi-se embora.

[[v47-27-61]]

^<<v47-27-61,61>>^ Maria Madalena e a outra Maria ficaram lá, sentadas defronte do túmulo.

[[v47-27-62]]

^<<v47-27-62,62>>^ No dia seguinte, isto é, o dia seguinte ao da Preparação, os príncipes dos sacerdotes e os fariseus dirigiram-se todos juntos à casa de Pilatos.

[[v47-27-63]]

^<<v47-27-63,63>>^ E disseram-lhe: “Senhor, nós nos lembramos de que aquele impostor disse, enquanto vivia: Depois de três dias ressuscitarei.

[[v47-27-64]]

^<<v47-27-64,64>>^ Ordena, pois, que seu sepulcro seja guardado até o terceiro dia. Os seus discípulos poderiam vir roubar o corpo e dizer ao povo: Ressuscitou dos mortos. E esta última impostura seria pior que a primeira”.

[[v47-27-65]]

^<<v47-27-65,65>>^ Respondeu Pilatos: “Tendes uma guarda. Ide e guardai-o como o entendeis”.

[[v47-27-66]]

^<<v47-27-66,66>>^ Foram, pois, e asseguraram o sepulcro, selando a pedra e colocando guardas.

'''

xref:047-sao-mateus/047-sao-mateus-026.adoc#v47-26-0[&#60; Capítulo Anterior] | <<v47-27-0,Topo>> | xref:047-sao-mateus/047-sao-mateus-028.adoc#v47-28-0[Próximo Capítulo &#62;]