include::./index.adoc[]

[[v29-63-0]]
=== Isaías, 63
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 63 de Isaías é uma oração de lamentação em que o profeta clama pela intervenção de Deus em favor de seu povo, lembrando as grandes obras que Ele fez no passado. O capítulo também fala da vingança de Deus sobre seus inimigos e da restauração de Israel. Abaixo estão cinco versículos relacionados com os temas abordados em Isaías 63:
* Salmos 77:12 - "Meditarei em todas as tuas obras, e em teus feitos meditarei." O salmista fala sobre meditar nas obras de Deus, que são evidências de seu poder e fidelidade. Isso se relaciona com o capítulo 63 de Isaías, que lembra as grandes obras de Deus em favor de Israel.
* Êxodo 15:3 - "O Senhor é homem de guerra; o Senhor é o seu nome." Este versículo fala sobre o caráter guerreiro de Deus e sua disposição para lutar em favor de seu povo. Isso se relaciona com o desejo expresso em Isaías 63 de que Deus interviesse em favor de Israel contra seus inimigos.
* Isaías 64:1 - "Oh, se fendesses os céus, e descesses! Os montes tremeriam perante a tua face." Este versículo expressa o desejo de Isaías de que Deus se manifestasse de forma poderosa em favor de seu povo. Isso se relaciona com o tema principal do capítulo 63.
* Salmos 94:1 - "Ó Senhor Deus, a quem a vingança pertence, ó Deus, a quem a vingança pertence, mostra-te resplandecente." Este salmo clama pela intervenção de Deus em favor de seu povo contra seus opressores. Isso se relaciona com o tema da vingança de Deus sobre seus inimigos, que é mencionado em Isaías 63.
* Deuteronômio 32:36 - "Porque o Senhor julgará o seu povo, e se arrependerá por seus servos; quando vir que o poder se foi, e não há ninguém preso nem deixado." Este versículo fala sobre o julgamento de Deus sobre seu povo, mas também sobre sua compaixão e disposição de perdoar. Isso se relaciona com o apelo de Isaías em favor do perdão e da misericórdia de Deus em Isaías 63.
****

[[v29-63-1]]

^<<v29-63-1,1>>^ Quem é aquele que vem de Edom, de Bosra, as vestes tintas, envolvido em um traje magnífico, altaneiro na plenitude de sua força? Sou eu, que luto pela justiça e sou poderoso para salvar.^&#42;1^

[[v29-63-2]]

^<<v29-63-2,2>>^ Por que, pois, tuas roupas estão vermelhas como as vestimentas daquele que pisa num lagar?

[[v29-63-3]]

^<<v29-63-3,3>>^ Eu pisei sozinho o lagar, e ninguém dentre os povos me auxiliou. Então, eu os calquei com cólera, esmaguei-os com fúria; o sangue deles espirrou sobre meu vestuário, manchei todas as minhas roupas.^&#42;1^

[[v29-63-4]]

^<<v29-63-4,4>>^ É que eu desejava um dia de vingança, e o ano da redenção dos meus havia chegado.

[[v29-63-5]]

^<<v29-63-5,5>>^ Olhei, então, e não houve pessoa alguma para me ajudar; estranhei que ninguém me viesse amparar; então, apelei para meu braço e achei forças na minha indignação.

[[v29-63-6]]

^<<v29-63-6,6>>^ Por isso, na minha cólera, arrasei os povos, na minha fúria triturei-os, fazendo correr seu sangue pela terra.

[[v29-63-7]]

^<<v29-63-7,7>>^ Quero celebrar os benefícios do Senhor e seus gloriosos feitos, por tudo o que fez em nosso favor, e por sua grande bondade, com a qual nos cumulou na sua ternura e na riqueza de seu amor.

[[v29-63-8]]

^<<v29-63-8,8>>^ “Verdadeiramente” – dizia de si para si –, “aqueles são meu povo, filhos que não me renegarão.” E tornou-se seu salvador

[[v29-63-9]]

^<<v29-63-9,9>>^ em todas as suas aflições. Não era um mensageiro nem um anjo, mas sua própria face que os salvava. No seu amor e na sua ternura ele mesmo os livrava do perigo. Durante o passado sustentou-os e amparou-os constantemente.^&#42;1^

[[v29-63-10]]

^<<v29-63-10,10>>^ Mas revoltaram-se, ofenderam seu santo espírito, desde então tornou-se inimigo deles, e lhes fez guerra. Então, se lembraram dos dias de outrora, de Moisés, seu servo.^&#42;1^

[[v29-63-11]]

^<<v29-63-11,11>>^ Onde está aquele que tirou dos céus o pastor de seu rebanho? Onde está aquele que pôs nele seu santo Espírito?^&#42;1^

[[v29-63-12]]

^<<v29-63-12,12>>^ Aquele que à direita de Moisés atuou com o seu braço glorioso, e dividiu as águas diante dos seus para assegurar-se um renome eterno;

[[v29-63-13]]

^<<v29-63-13,13>>^ e os conduziu através dos abismos, sem tropeçarem, como o cavalo em descampado.

[[v29-63-14]]

^<<v29-63-14,14>>^ Como ao animal que desce ao vale, o Espírito do Senhor os levava ao repouso. Foi assim que conduzistes vosso povo, para afirmar vosso glorioso renome.^&#42;1^

[[v29-63-15]]

^<<v29-63-15,15>>^ Olhai do alto do céu e vede de vossa santa e gloriosa morada: Que foi feito de vosso amor ciumento e de vosso poder, e da emoção de vosso coração? Dai livre expansão à vossa ternura,^&#42;1^

[[v29-63-16]]

^<<v29-63-16,16>>^ porque sois nosso pai. Abraão, de fato, nos ignora, e Israel não nos conhece; sois vós, Senhor, o nosso pai, nosso Redentor desde os tempos passados.^&#42;1^

[[v29-63-17]]

^<<v29-63-17,17>>^ Por que, Senhor, desviar-nos para longe de vossos caminhos, por que tornar nossos corações insensíveis ao vosso temor? Voltai, por amor de vossos servos e das tribos de vossa herança!

[[v29-63-18]]

^<<v29-63-18,18>>^ Por que pagãos invadiram vosso templo, e nossos inimigos pisaram vosso santuário? Há muito tempo estamos como gente que já não governais, e que não traz vosso nome.

'''

xref:029-isaias/029-isaias-062.adoc#v29-62-0[&#60; Capítulo Anterior] | <<v29-63-0,Topo>> | xref:029-isaias/029-isaias-064.adoc#v29-64-0[Próximo Capítulo &#62;]