include::./index.adoc[]

[[v29-30-0]]
=== Isaías, 30
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 30 é um capítulo que trata da rebeldia do povo de Judá em buscar ajuda no Egito em vez de confiar em Deus. O profeta adverte que essa aliança com o Egito será inútil e que a única esperança do povo está em se arrepender e voltar para Deus. Abaixo estão cinco versículos relacionados com os temas abordados em Isaías 30:
* 2 Crônicas 16:7-9: "Naquele tempo, o vidente Hanani foi ao rei Asa de Judá e lhe disse: 'Por teres confiado no rei da Síria e não no Senhor, teu Deus, o exército do rei da Síria escapou-te das mãos. Acaso não foram os etíopes e os líbios um exército imenso, com numerosos carros de guerra e cavaleiros? No entanto, por teres confiado no Senhor, ele os entregou em tuas mãos'". Este versículo fala da importância de confiar em Deus em vez de buscar ajuda em alianças políticas ou militares.
* Isaías 30:7: "Egito, cujos auxílios são inúteis e vãos; por isso, eu o chamo: ‘Rahab, que se estende deitada’". Este verso se refere ao Egito como "Rahab", um nome que significa orgulhoso ou arrogante. Isaías afirma que o orgulho do Egito e sua confiança em sua própria força serão inúteis diante do poder de Deus.
* Jeremias 2:18: "E agora, que fazes em meio aos caminhos do Egito, para beberes as águas do Nilo? E, que fazes em meio aos caminhos da Assíria, para beberes as águas do rio Eufrates?". Este versículo mostra que o povo de Judá buscava ajuda tanto no Egito quanto na Assíria, em vez de confiar em Deus.
* Isaías 30:15: "Assim diz o Soberano, o Senhor, o Santo de Israel: 'No arrependimento e no descanso está a salvação de vocês, na quietude e na confiança está o seu vigor, mas vocês não quiseram'". Neste versículo, Deus adverte o povo de Judá que a única esperança para eles é se arrepender e confiar nele, mas eles se recusam a fazê-lo.
* Salmo 20:7: "Alguns confiam em carros e outros em cavalos, mas nós confiamos no nome do Senhor, o nosso Deus". Este verso fala da importância de confiar em Deus em vez de confiar em coisas materiais como carros e cavalos (ou alianças políticas e militares) para nossa segurança e proteção.
****

[[v29-30-1]]

^<<v29-30-1,1>>^ “Ai dos filhos rebeldes” – diz o Senhor –, “eles seguem um plano que não vem de mim.” “Concluem alianças sem o meu consentimento, acumulando, assim, falta sobre falta.

[[v29-30-2]]

^<<v29-30-2,2>>^ Eles se voltam para o Egito sem me consultar, para refugiar-se sob a proteção do faraó, para abrigar-se à sombra do Egito.

[[v29-30-3]]

^<<v29-30-3,3>>^ O apoio do faraó vos será decepção e o abrigo à sombra do Egito, uma ignomínia.

[[v29-30-4]]

^<<v29-30-4,4>>^ Ainda que os chefes estejam em Soã e que os embaixadores tenham atingido Tânis,^&#42;1^

[[v29-30-5]]

^<<v29-30-5,5>>^ todo mundo será enganado por esse povo inútil, que não dá nem auxílio nem socorro, e só causa decepção e opróbrio.”

[[v29-30-6]]

^<<v29-30-6,6>>^ Oráculo contra as feras do sul: Para a terra da tribulação e da angústia, de onde vêm o leão e a leoa, a víbora e o dragão voador, conduzirão as riquezas sobre o dorso de jumentos, e os tesouros sobre a corcova de camelos, para ofertá-los a um povo que não lhes serve de nada.^&#42;1^

[[v29-30-7]]

^<<v29-30-7,7>>^ O socorro do Egito é ineficaz e nulo; por isso, eu o chamo Raab, o inerte.^&#42;1^

[[v29-30-8]]

^<<v29-30-8,8>>^ Agora, pois, vai escrever estas coisas de uma prancheta, inscreve-as num livro, a fim de que isso permaneça para o futuro e seja um testemunho eterno.^&#42;1^

[[v29-30-9]]

^<<v29-30-9,9>>^ Porque este é um povo rebelde, são filhos mentirosos, filhos que se recusam a ouvir as instruções do Senhor.

[[v29-30-10]]

^<<v29-30-10,10>>^ E dizem aos videntes: “Não vejais”, e aos profetas: “Não nos anuncieis a verdade, dizei-nos coisas agradáveis, profetizai-nos fantasias.^&#42;1^

[[v29-30-11]]

^<<v29-30-11,11>>^ Afastai-vos do caminho, retirai-vos da vereda, deixai de colocar-nos sob os olhos do Santo de Israel”.

[[v29-30-12]]

^<<v29-30-12,12>>^ Por isso, eis a réplica do Santo de Israel: “Visto que rejeitais esta advertência, para fiar-vos de meios tortuosos e perversos, e procurar aí vosso apoio,

[[v29-30-13]]

^<<v29-30-13,13>>^ acontecerá para vós, por causa desse crime, como uma fenda que forma saliência de uma muralha elevada: de improviso e num instante sobrevém o desabamento;

[[v29-30-14]]

^<<v29-30-14,14>>^ quebra-se como um pote de barro despedaçado sem piedade, de modo que os destroços não ofereçam sequer um caco para apanhar brasas no fogão ou tirar água da cisterna”.

[[v29-30-15]]

^<<v29-30-15,15>>^ Porque aqui está o que disse o Senhor Deus, o Santo de Israel: “É na conversão e na calma que está a vossa salvação; é no repouso e na confiança que reside a vossa força”. Porém, sem nada querer ouvir,^&#42;1^

[[v29-30-16]]

^<<v29-30-16,16>>^ vós dissestes: “Não, galoparemos a cavalo – pois bem, fugireis, portanto; montaremos corcéis ligeiros” – pois bem, sereis perseguidos de uma corrida veloz.^&#42;1^

[[v29-30-17]]

^<<v29-30-17,17>>^ Mil fugirão à ameaça de um só, à ameaça de cinco inimigos, vós vos deitarei a fugir até que não subsista mais do que um vestígio escasso, como um mastro no cume de um monte, como um estandarte sobre uma colina.

[[v29-30-18]]

^<<v29-30-18,18>>^ É por isso que o Senhor está desejoso de vos perdoar; é por isso que ele se ergue para vos poupar; porque o Senhor é um Deus justo; ditosos aqueles que nele esperam.

[[v29-30-19]]

^<<v29-30-19,19>>^ Sim, povo de Sião, que habitas em Jerusalém, não terás mais de que chorar. À voz de tua súplica ele te fará misericórdia; assim que a ouvir, ele te atenderá.

[[v29-30-20]]

^<<v29-30-20,20>>^ Quando o Senhor vos tiver dado o pão da angústia e a água da tribulação aquele que te instrui não se esconderá mais, e verás com teus olhos aquele que te ensina.^&#42;1^

[[v29-30-21]]

^<<v29-30-21,21>>^ Ouvirás com teus ouvidos estas palavras retumbarem atrás de ti: “É aqui o caminho, andai por ele”, quando te desviares quer para a direita, quer para a esquerda.

[[v29-30-22]]

^<<v29-30-22,22>>^ Acharás imundo o revestimento de prata de teus ídolos esculpidos e as aplicações de ouro de tuas estátuas fundidas: tu os arrojarás como imundícies, gritando-lhes: “Fora daqui!”.

[[v29-30-23]]

^<<v29-30-23,23>>^ O Senhor dará chuvas às sementes com que proverdes o solo e o pão que produzir a terra será nutritivo e saboroso. Naquele dia, teu gado pastará em vastas pastagens;

[[v29-30-24]]

^<<v29-30-24,24>>^ os bois e os asnos, que trabalham a terra, comerão uma forragem salgada que será joeirada com a pá e com a peneira.

[[v29-30-25]]

^<<v29-30-25,25>>^ Então, em todo monte alto e em toda colina elevada haverá arroios de água corrente, no dia da grande mortandade, em que desabarão as fortalezas.

[[v29-30-26]]

^<<v29-30-26,26>>^ Então, a luz da lua será viva como a do sol, e a do sol brilhará sete vezes mais como a luz de sete dias, no dia em que o Senhor pensar a chaga de seu povo e curar as contusões dos golpes que recebeu.

[[v29-30-27]]

^<<v29-30-27,27>>^ Vede! É o nome do Senhor que vem de longe, sua cólera é ardente, uma nuvem pesada se levanta, seus lábios respiram furor, e sua língua é como um fogo devorador.

[[v29-30-28]]

^<<v29-30-28,28>>^ Seu sopro assemelha-se a uma torrente transbordante cuja água sobe até o pescoço. Ele passará as nações no crivo destruidor e porá nos queixos dos povos um freio que os desencaminhe.

[[v29-30-29]]

^<<v29-30-29,29>>^ Vós, porém, fareis retumbar vossos cânticos, como na noite em que se celebra festa; e tereis alegria no coração, como o que caminha ao som da flauta, para vir ao monte do Senhor, junto ao rochedo de Israel.

[[v29-30-30]]

^<<v29-30-30,30>>^ O Senhor fará retumbar sua voz majestosa, e mostrará como o seu braço desaba em sua cólera ardente, nas chamas de um fogo devorador, na tempestade, com chuva e granizo.^&#42;1^

[[v29-30-31]]

^<<v29-30-31,31>>^ À voz do Senhor, o assírio tremerá e será ferido pela vara.

[[v29-30-32]]

^<<v29-30-32,32>>^ A cada golpe da vara vingadora que o Senhor lhe infligirá, soarão tamborins e cítaras.^&#42;1^

[[v29-30-33]]

^<<v29-30-33,33>>^ Sim, um lugar de incineração está preparado também para Tofet, cavado, profundo e largo; palha e lenha ali há em quantidade, e o sopro do Senhor, como uma torrente de enxofre, o acenderá.^&#42;1^

'''

xref:029-isaias/029-isaias-029.adoc#v29-29-0[&#60; Capítulo Anterior] | <<v29-30-0,Topo>> | xref:029-isaias/029-isaias-031.adoc#v29-31-0[Próximo Capítulo &#62;]