include::./index.adoc[]

[[v29-51-0]]
=== Isaías, 51
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 51 é um capítulo que traz uma mensagem de encorajamento e consolo para o povo de Deus. O capítulo começa com uma chamada para que o povo ouça a Deus e olhe para o exemplo de Abraão e Sara, que confiaram em Deus apesar das dificuldades. Em seguida, o capítulo destaca a soberania de Deus sobre a terra e a promessa de sua salvação para o povo. O capítulo termina com um convite para que o povo se alegre e louve a Deus por sua fidelidade.
* Salmos 27:14: "Espera no Senhor, anima-te, e ele fortalecerá o teu coração; espera, pois, no Senhor." Este versículo enfatiza a importância da paciência e confiança em Deus, que é um tema importante em Isaías 51.
* Filipenses 4:6-7: "Não estejais inquietos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus, pela oração e súplicas, com ação de graças. E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus." Esse versículo destaca a importância da oração e da gratidão em tempos de ansiedade, o que é relevante para o tema de consolo e encorajamento em Isaías 51.
* Romanos 8:31: "Que diremos, pois, à vista destas coisas? Se Deus é por nós, quem será contra nós?" Esse versículo enfatiza a soberania de Deus e sua proteção sobre seu povo, que é um tema importante em Isaías 51.
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Este versículo enfatiza a presença e ajuda de Deus em tempos de dificuldade, que é um tema importante em Isaías 51.
* Salmos 126:5-6: "Os que semeiam em lágrimas segarão com alegria. Aquele que leva a preciosa semente, andando e chorando, voltará, sem dúvida, com alegria, trazendo consigo os seus molhos." Esse versículo destaca a ideia de que a tristeza e o sofrimento podem ser transformados em alegria e bênçãos através da graça de Deus, que é um tema central em Isaías 51.
****

[[v29-51-1]]

^<<v29-51-1,1>>^ Ouvi-me, vós que seguis a justiça, e que buscais o Senhor! Olhai a rocha de que fostes talhados, a pedreira de onde vos tiraram:

[[v29-51-2]]

^<<v29-51-2,2>>^ considerai Abraão, vosso pai, e Sara, que vos pôs no mundo. Ele estava só, quando o chamei, mas eu o abençoei e o multipliquei,

[[v29-51-3]]

^<<v29-51-3,3>>^ porque o Senhor vai ter piedade de Sião, e reparar todas as suas ruínas. Do deserto em que ela se tornou ele fará um Éden, e da sua estepe um jardim do Senhor. Aí se encontrarão o prazer e a alegria, os cânticos de louvor e as melodias da música.^&#42;1^

[[v29-51-4]]

^<<v29-51-4,4>>^ Povos, escutai bem! Nações, prestai-me atenção! Pois é de mim que emanará a doutrina e a verdadeira religião que será a luz dos povos.^&#42;1^

[[v29-51-5]]

^<<v29-51-5,5>>^ De repente, minha justiça chegará, minha salvação vai aparecer, meu braço fará justiça aos povos, as ilhas em mim terão esperança e contarão com meu braço.^&#42;1^

[[v29-51-6]]

^<<v29-51-6,6>>^ Levantai os olhos para o céu, volvei vosso olhar à terra: os céus vão desvanecer-se como fumaça, como um vestido em farrapos ficará a terra, e seus habitantes morrerão como moscas. Mas minha salvação subsistirá sempre, e minha vitória não terá fim.

[[v29-51-7]]

^<<v29-51-7,7>>^ Ouvi-me, vós que conheceis a justiça, povo meu, em cujo coração está a minha doutrina: não temais os insultos dos homens, não vos deixeis abater pelos seus ultrajes,^&#42;1^

[[v29-51-8]]

^<<v29-51-8,8>>^ porque a traça os comerá como uma vestimenta, e os vermes das traças os roerão como lã. Mas minha vitória subsistirá sempre e meu triunfo persistirá de geração em geração.

[[v29-51-9]]

^<<v29-51-9,9>>^ Desperta, braço do Senhor, desperta, recobra teu vigor! Levanta-te como nos dias do passado, como nos tempos de outrora. Não foste tu que esmagaste Raab e fendeste de alto a baixo o Dragão?^&#42;1^

[[v29-51-10]]

^<<v29-51-10,10>>^ Não foste tu que secaste o mar e estancaste as águas do grande abismo? Tu que abriste no fundo do mar um caminho, para por aí passarem os resgatados?^&#42;1^

[[v29-51-11]]

^<<v29-51-11,11>>^ Por aí voltarão aqueles que o Senhor tiver libertado. Chegarão a Sião com cânticos de triunfo, uma eterna alegria lhes cingirá a cabeça; o júbilo e a alegria os invadirão, a tristeza e os lamentos fugirão.^&#42;1^

[[v29-51-12]]

^<<v29-51-12,12>>^ Sou eu, sou eu quem vos consola! Como podes temer um mortal, um filho do homem, que acabará como a erva?

[[v29-51-13]]

^<<v29-51-13,13>>^ Como esquecer o Senhor, teu Criador, que estendeu os céus e fundou a terra, para não cessares de tremer todo o tempo diante da cólera do opressor que procura fazer-te perecer? Mas de que vale a cólera do opressor?

[[v29-51-14]]

^<<v29-51-14,14>>^ Em breve o prisioneiro vai ser solto, não perecerá no cárcere, e o pão não lhe faltará.

[[v29-51-15]]

^<<v29-51-15,15>>^ Eu sou o Senhor, teu Deus, que revolvo o mar e faço rugir as ondas; eu me chamo o Senhor dos exércitos.

[[v29-51-16]]

^<<v29-51-16,16>>^ Na tua boca coloquei minhas palavras, com a sombra de minha mão eu te cobri, para estender os céus e fundar a terra, e dizer a Sião: “Tu és meu povo”.^&#42;1^

[[v29-51-17]]

^<<v29-51-17,17>>^ Desperta! Desperta! Levanta-te, Jerusalém, tu que bebeste da mão do Senhor a taça de sua cólera, que esgotaste até os resíduos o cálice que dá vertigem.

[[v29-51-18]]

^<<v29-51-18,18>>^ (De todos os filhos que ela pôs no mundo, nenhum a orientou; entre os filhos que ela criou, nenhum a segurou pela mão.)^&#42;1^

[[v29-51-19]]

^<<v29-51-19,19>>^ Esses dois males te sobrevieram –, quem te lastimaria? Saque e ruína, fome e espada – quem te consolaria?

[[v29-51-20]]

^<<v29-51-20,20>>^ Teus filhos jazem desfalecidos (pelos cantos da rua), como um antílope apanhado no laço, tontos com a cólera do Senhor e com as ameaças de teu Deus.

[[v29-51-21]]

^<<v29-51-21,21>>^ Ouve então isto, infeliz, tu que estás embriagada, mas não pelo vinho.

[[v29-51-22]]

^<<v29-51-22,22>>^ Eis o que diz o Senhor, teu Deus, que toma a defesa de seu povo: “Vou retirar de tua mão a taça que dá a vertigem, não mais terás para beber o cálice de minha cólera,

[[v29-51-23]]

^<<v29-51-23,23>>^ e eu vou pô-lo na mão dos tiranos, na mão de teus opressores que te diziam: ‘Curva-te para passarmos’, quando apresentavas teu dorso como o chão que se calca, como uma rua para os viandantes”.^&#42;1^

'''

xref:029-isaias/029-isaias-050.adoc#v29-50-0[&#60; Capítulo Anterior] | <<v29-51-0,Topo>> | xref:029-isaias/029-isaias-052.adoc#v29-52-0[Próximo Capítulo &#62;]