include::./index.adoc[]

[[v29-33-0]]
=== Isaías, 33
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 33 de Isaías começa com uma oração pelo livramento do povo de Judá contra os seus inimigos e continua com uma profecia sobre a vinda do Rei e a restauração da cidade de Sião. Os versículos selecionados a seguir estão relacionados com esses temas:
* Isaías 30:15: "Porque assim diz o Senhor Deus, o Santo de Israel: Em vos converterdes e em repousardes, estaria a vossa salvação; no sossego e na confiança estaria a vossa força, mas não quisestes." Este versículo fala sobre a importância de confiar em Deus para a salvação e a força, algo que é ressaltado no capítulo 33 de Isaías.
* Isaías 32:1: "Eis que um rei reinará com justiça, e os príncipes governarão com retidão." Essa passagem se refere à vinda de um rei justo, o que é um tema importante no capítulo 33 de Isaías.
* Isaías 32:18: "Então, o meu povo habitará em morada de paz, em moradas bem seguras, e em lugares quietos de descanso." Esse verso fala sobre a promessa de Deus de dar segurança e paz ao seu povo, algo que é enfatizado em Isaías 33.
* Isaías 35:10: "E os resgatados do Senhor voltarão e virão a Sião com cânticos de júbilo, e alegria eterna haverá sobre as suas cabeças; gozo e alegria alcançarão, e deles fugirá a tristeza e o gemido." Este versículo fala sobre a alegria e a felicidade que o povo de Deus experimentará após o livramento, um tema que é tratado em Isaías 33.
* Isaías 40:31: "Mas os que esperam no Senhor renovarão as suas forças, subirão com asas como águias; correrão e não se cansarão, caminharão e não se fatigarão." Este versículo fala sobre a importância de esperar em Deus para renovar as forças, algo que é uma mensagem importante em Isaías 33.
****

[[v29-33-1]]

^<<v29-33-1,1>>^ Ai de ti, devastador que ainda não foste devastado, salteador que ainda não foste saqueado! Quando acabares de devastar, serás devastado, quando acabares de saquear, serás saqueado.^&#42;1^

[[v29-33-2]]

^<<v29-33-2,2>>^ Senhor, tende piedade de nós, pois esperamos em vós. Sede nosso auxílio em cada manhã e nosso socorro no tempo da tribulação.

[[v29-33-3]]

^<<v29-33-3,3>>^ Ao fragor de vosso trovão, os povos fogem; quando vós vos ergueis, as nações se dispersam.

[[v29-33-4]]

^<<v29-33-4,4>>^ Recolherão o despojo como se amontoam os gafanhotos, saltam por cima assim como se atiram os gafanhotos.^&#42;1^

[[v29-33-5]]

^<<v29-33-5,5>>^ O Senhor é grande, porque reina no alto; ele enche Sião de retidão e de justiça.

[[v29-33-6]]

^<<v29-33-6,6>>^ Teus dias estarão em segurança. A sabedoria e o conhecimento garantem a salvação, e o temor do Senhor será o seu tesouro.^&#42;1^

[[v29-33-7]]

^<<v29-33-7,7>>^ Eis que a gente de Ariel lamenta nas ruas, os mensageiros de paz choram amargamente.^&#42;1^

[[v29-33-8]]

^<<v29-33-8,8>>^ Os caminhos estão desertos, não há mais transeuntes nas veredas; o inimigo violou o tratado, desprezou as testemunhas, e não teve consideração para com ninguém.^&#42;1^

[[v29-33-9]]

^<<v29-33-9,9>>^ A terra está enlutada e abatida, o Líbano, desonrado e ressequido, Saron assemelha-se a uma estepe, Basã e o Carmelo perdem sua folhagem.

[[v29-33-10]]

^<<v29-33-10,10>>^ “Agora eu me erguerei” – diz o Senhor –, “agora eu me manifestarei em toda a minha sublimidade.

[[v29-33-11]]

^<<v29-33-11,11>>^ Vós concebestes feno e gerareis palha; meu sopro, como um fogo, vos consumirá.

[[v29-33-12]]

^<<v29-33-12,12>>^ Os povos serão calcinados como espinhos cortados que se queimam.

[[v29-33-13]]

^<<v29-33-13,13>>^ Vós, que estais longe, ouvi o que eu fiz; vós, que estais perto, conhecei o meu poder.”

[[v29-33-14]]

^<<v29-33-14,14>>^ Em Sião os pecadores serão aterrados, o medo se apoderará dos ímpios. “Quem de nós poderá permanecer perto deste fogo devorador? Quem de nós poderá permanecer perto das chamas eternas?”^&#42;1^

[[v29-33-15]]

^<<v29-33-15,15>>^ Aquele que procede bem e diz a verdade, que não quer um benefício extorquido, que não quer tocar um presente corruptor, que fecha os ouvidos aos propósitos sanguinários e cerra os olhos para não ver o mal.

[[v29-33-16]]

^<<v29-33-16,16>>^ Semelhante homem habitará nas alturas, e terá por asilo os rochedos fortificados; seu pão lhe é dado e a água lhe é assegurada.

[[v29-33-17]]

^<<v29-33-17,17>>^ Teus olhos verão o rei no seu esplendor, e contemplarão um grande território.

[[v29-33-18]]

^<<v29-33-18,18>>^ Teu coração recordará os terrores passados: “Que foi feito do cobrador? Que foi feito do fiscal? Onde está aquele que inspecionava as fortificações?”.^&#42;1^

[[v29-33-19]]

^<<v29-33-19,19>>^ Tu não verás mais aquele povo insolente, aquele povo de linguagem ininteligível, de língua bárbara que ninguém compreende.

[[v29-33-20]]

^<<v29-33-20,20>>^ Olha para Sião, a cidade de nossas festas; teus olhos verão Jerusalém, habitação tranquila, tenda bem fixada, cujas estacas jamais serão arrancadas, nem as cordas rompidas.

[[v29-33-21]]

^<<v29-33-21,21>>^ Lá, na verdade, temos o arroio do Senhor, que nos serve de rios com largos canais; aí não passa embarcação a remo e nenhum navio imponente o sulca.^&#42;1^

[[v29-33-22]]

^<<v29-33-22,22>>^ Porque o Senhor é nosso juiz, o Senhor é nosso legislador; o Senhor é nosso rei que nos salvará.

[[v29-33-23]]

^<<v29-33-23,23>>^ Teus cordames afrouxaram, não sustentam mais o mastro e não estendem mais a vela. Então, o próprio cego se apoderará da sua parte de um grande despojo, e os próprios coxos se entregarão ao saque;^&#42;1^

[[v29-33-24]]

^<<v29-33-24,24>>^ ninguém mais em Jerusalém se dirá doente: o povo dessa cidade terá seus pecados perdoados.

'''

xref:029-isaias/029-isaias-032.adoc#v29-32-0[&#60; Capítulo Anterior] | <<v29-33-0,Topo>> | xref:029-isaias/029-isaias-034.adoc#v29-34-0[Próximo Capítulo &#62;]