include::./index.adoc[]

[[v29-61-0]]
=== Isaías, 61
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 61 é um capítulo de grande importância teológica, pois apresenta a missão do Messias. Neste capítulo, o profeta anuncia a boa notícia da salvação e libertação para o povo de Deus, por meio da obra do Messias. Ele traz a mensagem de que o Messias irá curar os corações quebrantados, libertar os cativos, proclamar a liberdade aos prisioneiros e consolar os que choram. Abaixo estão cinco versículos relacionados com os temas abordados em Isaías 61:
* Lucas 4:18-19: "O Espírito do Senhor está sobre mim, porque ele me ungiu para pregar boas novas aos pobres. Ele me enviou para proclamar liberdade aos presos e recuperação da vista aos cegos, para libertar os oprimidos e proclamar o ano da graça do Senhor". Jesus citou este versículo ao anunciar sua missão na sinagoga em Nazaré, deixando claro que Ele era o Messias prometido que veio cumprir as Escrituras.
* Mateus 11:28-30: "Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso. Tomem sobre vocês o meu jugo e aprendam de mim, pois sou manso e humilde de coração, e vocês encontrarão descanso para as suas almas. Pois o meu jugo é suave e o meu fardo é leve". Jesus convida todas as pessoas cansadas e sobrecarregadas a irem até Ele para encontrar alívio, cumprindo assim a promessa feita em Isaías 61:1-2.
* João 8:36: "Assim, se o Filho os libertar, vocês de fato serão livres". Jesus afirmou que aqueles que creem Nele são verdadeiramente livres, cumprindo a promessa de Isaías 61:1-2 de proclamar liberdade aos cativos e prisioneiros.
* 2 Coríntios 5:17: "Portanto, se alguém está em Cristo, é nova criação. As coisas antigas já passaram; eis que surgiram coisas novas!". Aqueles que colocam a sua fé em Jesus são transformados, recebendo uma nova vida em Cristo. Isso se relaciona com a promessa de Isaías 61:3 de consolar os que choram e lhes dar uma coroa de beleza em vez de cinzas.
* Apocalipse 21:4: "Ele enxugará dos seus olhos toda lágrima. Não haverá mais morte, nem tristeza, nem choro, nem dor, pois a ordem antiga já passou". Este versículo descreve a promessa de Deus de que um dia não haverá mais sofrimento, morte ou tristeza. Isso se relaciona com a promessa de Isaías 61:1-2 de trazer conforto e alegria para os que choram e estão em luto.
****

[[v29-61-1]]

^<<v29-61-1,1>>^ O Espírito do Senhor repousa sobre mim, porque o Senhor consagrou-me pela unção; enviou-me a levar a boa-nova aos humildes, a curar os corações doloridos, a anunciar aos cativos a redenção, e aos prisioneiros a liberdade;^&#42;1^

[[v29-61-2]]

^<<v29-61-2,2>>^ a proclamar um ano de graças da parte do Senhor, e um dia de vingança de nosso Deus; a consolar todos os aflitos,

[[v29-61-3]]

^<<v29-61-3,3>>^ a dar-lhes um diadema em vez de cinzas, o óleo da alegria em vez de vestidos de luto, cânticos de glória em lugar de desespero. Então, os chamarão as azinheiras da justiça, plantadas pelo Senhor para sua glória.

[[v29-61-4]]

^<<v29-61-4,4>>^ Reconstruirão as ruínas antigas, reerguerão as relíquias do passado, restaurarão as cidades destruídas, repararão as devastações seculares;

[[v29-61-5]]

^<<v29-61-5,5>>^ virão estrangeiros apascentar vosso gado miúdo, gente de fora vos servirá de lavradores e vinhateiros;

[[v29-61-6]]

^<<v29-61-6,6>>^ a vós vos chamarão sacerdotes do Senhor, de ministros de nosso Deus sereis qualificados. Vós vos alimentareis com as riquezas das nações, e brilhareis com sua opulência.

[[v29-61-7]]

^<<v29-61-7,7>>^ Já que tiveram parte dupla de vergonha e tiveram como quinhão opróbrios e escarros, receberão em sua terra parte dupla de herança, e a alegria deles será eterna.^&#42;1^

[[v29-61-8]]

^<<v29-61-8,8>>^ Porque eu, o Senhor, amo a equidade, e detesto o fruto da rapina; por isso, vou dar-lhes fielmente sua recompensa, e concluir com eles uma aliança eterna.

[[v29-61-9]]

^<<v29-61-9,9>>^ Sua raça se tornará célebre entre as nações, e sua descendência entre os povos: todos, vendo-os, reconhecerão que são a abençoada raça do Senhor.

[[v29-61-10]]

^<<v29-61-10,10>>^ “Com grande alegria eu me rejubilarei no Senhor e meu coração exultará de alegria em meu Deus, porque me fez revestir as vestimentas da salvação. Envolveu-me com o manto de justiça, como um neo-esposo cinge o turbante, como uma jovem esposa se enfeita com suas joias.^&#42;1^

[[v29-61-11]]

^<<v29-61-11,11>>^ Porque, quão certo o sol faz germinar seus grãos e um jardim faz brotar suas sementes, o Senhor Deus fará germinar a justiça e a glória diante de todas as nações.”

'''

xref:029-isaias/029-isaias-060.adoc#v29-60-0[&#60; Capítulo Anterior] | <<v29-61-0,Topo>> | xref:029-isaias/029-isaias-062.adoc#v29-62-0[Próximo Capítulo &#62;]