include::./index.adoc[]

[[v29-17-0]]
=== Isaías, 17
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 17 fala sobre a profecia da destruição de Damasco. O capítulo começa com a declaração de que Damasco deixará de ser uma cidade e se tornará um monte de ruínas. Em seguida, o profeta aponta que Israel também será afetado por essa destruição. Os versículos escolhidos são:
* Amós 1:3-4: "Assim diz o Senhor: Por três transgressões de Damasco, e por quatro, não revogarei a sua punição, porque trilharam a Gileade com trilhos de ferro. Por isso, porei fogo à casa de Hazael, o qual consumirá os palácios de Ben-Hadade." Esses versículos mostram que a destruição de Damasco era uma punição divina pelo mal que a cidade havia cometido, como invadir a Gileade e subjugar seu povo.
* Jeremias 49:23-24: "Sobre Damasco. Envergonhada está Hamate e Arpade, porque ouviram más notícias; estão desalentadas. O mar está agitado, não se pode sossegar. Damasco desmaiou, voltou-se para fugir, e o tremor a tomou; angústias e dores se apoderaram dela, como da mulher que está de parto." Esses versículos descrevem a angústia que tomou conta de Damasco quando soube da sua iminente destruição.
* Salmos 83:3-4: "Tramam astutamente contra o teu povo, e conspiram contra os teus protegidos. Dizem: Vinde, e desarraiguemo-los para que não sejam nação, e não haja mais memória do nome de Israel." Esses versículos mostram que os inimigos de Israel, como a Síria, estavam conspirando para destruir a nação.
* Isaías 7:8: "Porque a cabeça da Síria é Damasco, e a cabeça de Damasco é Rezim (e dentro de sessenta e cinco anos Efraim será quebrantado, para que não seja mais povo)." Esse versículo faz uma referência à aliança entre a Síria e Israel, que era uma ameaça para Judá na época de Isaías.
* 2 Reis 16:9: "E o rei da Assíria lhe deu ouvidos; e subiu o rei da Assíria contra Damasco, e tomou-a, levando cativo o povo para Quir, e matando a Rezim." Esse versículo relata como o rei da Assíria conquistou Damasco e levou seu povo cativo para Quir, cumprindo assim a profecia de Isaías.
****

[[v29-17-1]]

^<<v29-17-1,1>>^ Oráculo contra Damasco. Damasco vai ser suprimida do número das cidades, e será reduzida a ruínas abandonadas para sempre.

[[v29-17-2]]

^<<v29-17-2,2>>^ Suas cidades serão abandonadas aos rebanhos que virão repousar aí sem que ninguém os enxote.^&#42;1^

[[v29-17-3]]

^<<v29-17-3,3>>^ Foi tirado o baluarte de Efraim, foi tirada a realeza de Damasco; os restos de Aram perecerão, passarão como a glória de Israel. Oráculo do Senhor dos exércitos.

[[v29-17-4]]

^<<v29-17-4,4>>^ Naquele dia a glória de Jacó declinará, e sua gordura se reduzirá em magreza,

[[v29-17-5]]

^<<v29-17-5,5>>^ como quando o ceifador já colheu o trigo e seu braço cortou as espigas, alguém rebusca as searas no vale dos Rafaítas;

[[v29-17-6]]

^<<v29-17-6,6>>^ aí não haverá para respigar, como quando já se varejou as oliveiras, senão dois ou três bagos no mais alto topo. Oráculo do Senhor, Deus de Israel.

[[v29-17-7]]

^<<v29-17-7,7>>^ Naquele dia, o homem voltará seus olhares para o seu Criador, seus olhos verão o Santo de Israel;

[[v29-17-8]]

^<<v29-17-8,8>>^ e ele não olhará mais aquilo que seus dedos fizeram (as estacas sagradas e as estelas ao sol).^&#42;1^

[[v29-17-9]]

^<<v29-17-9,9>>^ Naquele dia, tuas cidades serão abandonadas como as cidades despovoadas dos amorreus e dos heveus, abandonadas no tempo da invasão dos israelitas. Elas ficarão desabitadas,^&#42;1^

[[v29-17-10]]

^<<v29-17-10,10>>^ porque esqueceste o Deus que te salva, e não te lembraste de tua fortaleza! Tu te esforçarás em vão para plantar jardins de Adônis, e neles semear plantas exóticas;^&#42;1^

[[v29-17-11]]

^<<v29-17-11,11>>^ no dia em que plantares, tu os verás crescer, e numa bela manhã tua planta dará flores; porém, a colheita será nula no dia do infortúnio, e o mal, irremediável.

[[v29-17-12]]

^<<v29-17-12,12>>^ Oh! Esse barulho de povo numeroso, esse rumor semelhante ao do mar! Esse tumulto de nações poderosas, semelhante ao brilhar de águas impetuosas!

[[v29-17-13]]

^<<v29-17-13,13>>^ Ele as ameaça e elas fogem para longe como, nas alturas, a palha levada pelo vento, como a poeira levantada pela tempestade.

[[v29-17-14]]

^<<v29-17-14,14>>^ Quando veio a noite, houve terror, e antes da manhã, nada mais restava deles. Esta será a sorte daqueles que nos saqueiam, tal será o quinhão daqueles que nos despojam.

'''

xref:029-isaias/029-isaias-016.adoc#v29-16-0[&#60; Capítulo Anterior] | <<v29-17-0,Topo>> | xref:029-isaias/029-isaias-018.adoc#v29-18-0[Próximo Capítulo &#62;]