include::./index.adoc[]

[[v29-40-0]]
=== Isaías, 40
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 40 é um capítulo que fala sobre a consolação de Deus para o seu povo. Ele começa com a voz de alguém clamando no deserto preparando o caminho para o Senhor e termina com uma promessa de que aqueles que esperam no Senhor renovarão suas forças. Aqui estão cinco versículos relacionados com os temas abordados em Isaías 40:
* Salmos 31:24 - "Sede fortes, e revigore-se o vosso coração, vós todos que esperais no SENHOR." Este verso encoraja os que esperam no Senhor a serem fortes e a renovar suas forças.
* Isaías 41:10 - "Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Este verso fala sobre a presença constante de Deus com o seu povo, oferecendo-lhes fortalecimento e sustento.
* Salmos 46:1-2 - "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia. Portanto, não temeremos, ainda que a terra se mude, e ainda que os montes se transportem para o meio dos mares." Este verso fala sobre a confiança em Deus como nosso refúgio e fortaleza.
* Isaías 43:2 - "Quando passares pelas águas, estarei contigo, e quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti." Este verso fala sobre a presença protetora de Deus em meio aos desafios da vida.
* Salmos 27:14 - "Espera no SENHOR, anima-te, e ele fortalecerá o teu coração; espera, pois, no SENHOR." Este verso encoraja aqueles que esperam no Senhor a serem animados e fortalecidos pelo seu poder.
****

[[v29-40-1]]

^<<v29-40-1,1>>^ “Consolai, consolai meu povo” – diz vosso Deus.^&#42;1^

[[v29-40-2]]

^<<v29-40-2,2>>^ Animai Jerusalém, dizei-lhe bem alto que suas lidas estão terminadas, que sua falta está expiada, que recebeu, da mão do Senhor, pena dupla por todos os seus pecados.^&#42;1^

[[v29-40-3]]

^<<v29-40-3,3>>^ Uma voz exclama: “Abri no deserto um caminho para o Senhor, traçai reta na estepe uma pista para nosso Deus.^&#42;1^

[[v29-40-4]]

^<<v29-40-4,4>>^ Que todo vale seja aterrado, que toda montanha e colina sejam abaixadas: que os cimos sejam aplainados, que as escarpas sejam niveladas!”.

[[v29-40-5]]

^<<v29-40-5,5>>^ Então, a glória do Senhor se manifestará; todas as criaturas juntas apreciarão o esplendor, porque a boca do Senhor o prometeu.

[[v29-40-6]]

^<<v29-40-6,6>>^ “Clama!” – disse uma voz, e eu respondi –: “Que clamarei?” “Toda criatura é como a erva e toda a sua glória como a flor dos campos!^&#42;1^

[[v29-40-7]]

^<<v29-40-7,7>>^ A erva seca e a flor fenece quando o sopro do Senhor passa sobre elas. (Verdadeiramente o povo é semelhante à erva.)^&#42;1^

[[v29-40-8]]

^<<v29-40-8,8>>^ A erva seca e a flor fenece, mas a palavra de nosso Deus permanece eternamente.”

[[v29-40-9]]

^<<v29-40-9,9>>^ Subi a uma alta montanha, para anunciar a boa-nova a Sião. Elevai com força a voz, para anunciar a boa-nova a Jerusalém. Elevai a voz sem receio, dizei às cidades de Judá: “Eis vosso Deus!^&#42;1^

[[v29-40-10]]

^<<v29-40-10,10>>^ Eis o Senhor Deus que vem com poder, estendendo os braços soberanamente. Eis com ele o preço de sua vitória; faz-se preceder pelos frutos de sua conquista;

[[v29-40-11]]

^<<v29-40-11,11>>^ como um pastor, vai apascentar seu rebanho, reunir os animais dispersos, carregar os cordeiros nas dobras de seu manto, conduzir lentamente as ovelhas que amamentam”.

[[v29-40-12]]

^<<v29-40-12,12>>^ Quem, pois, mediu o mar no côncavo da mão, quem com seus dedos abertos mediu os céus? Quem com o alqueire mediu a matéria terrestre, pesou as montanhas no gancho, e as colinas na balança?^&#42;1^

[[v29-40-13]]

^<<v29-40-13,13>>^ Quem determinou o Espírito do Senhor, e que conselheiro lhe deu lições?^&#42;1^

[[v29-40-14]]

^<<v29-40-14,14>>^ De quem recebeu conselho para julgar bem, para que se lhe indique o caminho da justiça, se lhe ensine a ciência e se lhe mostre a via mais prudente?

[[v29-40-15]]

^<<v29-40-15,15>>^ As nações são para ele apenas uma gota de água num balde, um grão de areia na balança; as ilhas não pesam mais que o pó,^&#42;1^

[[v29-40-16]]

^<<v29-40-16,16>>^ o Líbano não bastaria para o braseiro de seu altar, nem seus animais para os holocaustos.

[[v29-40-17]]

^<<v29-40-17,17>>^ Todas as nações juntas nada são diante dele: a seus olhos são como que inexistentes.

[[v29-40-18]]

^<<v29-40-18,18>>^ A quem poderíeis comparar Deus, e que imagem dele poderíeis oferecer?

[[v29-40-19]]

^<<v29-40-19,19>>^ Um artesão funde uma estátua, o ourives, a placa de ouro, e faz derreter as correntinhas de prata. (4l,6) Prestam-se assistência mútua, dizem um ao outro: “Coragem!”. (4l,7) O fundidor estimula o ourives, e o malhador, o ferreiro: “A solda é boa” – diz. Ele a reforça com rebites para que não oscile.^&#42;1^

[[v29-40-20]]

^<<v29-40-20,20>>^ Aquele que deseja esculpir uma imagem escolhe madeira que não apodrece; põe-se à procura de um operário hábil, a fim de assentar uma estátua que não oscile.^&#42;1^

[[v29-40-21]]

^<<v29-40-21,21>>^ Não o sabíeis? Não o aprendestes? Não vos ensinaram desde a origem? Não compreendestes nada da fundação da terra?

[[v29-40-22]]

^<<v29-40-22,22>>^ Aquele que domina acima do disco terrestre, cujos habitantes vê como se fossem gafanhotos, aquele que estende os céus como um véu de gaze, e como tenda os desdobra para aí se abrigar,^&#42;1^

[[v29-40-23]]

^<<v29-40-23,23>>^ reduz os príncipes a nada, e faz desaparecer os governantes da terra;

[[v29-40-24]]

^<<v29-40-24,24>>^ apenas estejam plantados, apenas sejam semeados, apenas seu talo tenha lançado raízes no solo, sopra sobre eles e os resseca, e o turbilhão os varre como palha.

[[v29-40-25]]

^<<v29-40-25,25>>^ “A quem então poderíeis comparar-me, que possa ser a mim igualado?” – diz o Santo.

[[v29-40-26]]

^<<v29-40-26,26>>^ Levantai os olhos para o céu e olhai. Quem criou todos esses astros? Aquele que faz marchar o exército completo, e a todos chama pelo nome, o qual é tão rico de força e dotado de poder, que ninguém falta ao seu chamado.^&#42;1^

[[v29-40-27]]

^<<v29-40-27,27>>^ Por que dizer-te então, ó Jacó, por que repetir, ó Israel: “Escapa meu destino ao Senhor, passa meu direito despercebido a meu Deus?”.

[[v29-40-28]]

^<<v29-40-28,28>>^ Não o sabes? Não o aprendeste? O Senhor é um Deus eterno. Ele cria os confins da terra, sem jamais fatigar-se nem aborrecer-se; ninguém pode sondar sua sabedoria.^&#42;1^

[[v29-40-29]]

^<<v29-40-29,29>>^ Dá forças ao homem acabrunhado, redobra o vigor do fraco.

[[v29-40-30]]

^<<v29-40-30,30>>^ Até os adolescentes podem esgotar-se, e jovens robustos podem cambalear,

[[v29-40-31]]

^<<v29-40-31,31>>^ mas aqueles que contam com o Senhor renovam suas forças; ele dá-lhes asas de águia. Correm sem se cansar, vão para a frente sem se fatigar.

'''

xref:029-isaias/029-isaias-039.adoc#v29-39-0[&#60; Capítulo Anterior] | <<v29-40-0,Topo>> | xref:029-isaias/029-isaias-041.adoc#v29-41-0[Próximo Capítulo &#62;]