include::./index.adoc[]

[[v29-49-0]]
=== Isaías, 49
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 49 é um capítulo que fala sobre o Servo do Senhor, que é chamado por Deus desde o ventre de sua mãe para ser um instrumento de salvação para as nações. O capítulo apresenta uma mensagem de esperança para os exilados de Israel, prometendo-lhes que Deus irá restaurar sua terra e trazer de volta seu povo disperso. Além disso, o capítulo destaca a missão do Servo em trazer salvação para todas as pessoas, incluindo aqueles que estão fora de Israel.
* Salmos 139:13-14: "Pois tu formaste o meu interior, tu me teceste no seio de minha mãe. Eu te louvo porque me fizeste de modo especial e admirável. Tuas obras são maravilhosas! Disso tenho plena certeza." Este versículo destaca a ideia de que Deus tem um plano para cada pessoa desde o momento em que foram formados no ventre de sua mãe, que é um tema central em Isaías 49.
* Lucas 2:30-32: "Pois os meus olhos já viram a tua salvação, que preparaste diante de todos os povos: luz para revelação aos gentios, e para glória de teu povo Israel." Esse versículo destaca a missão do Servo do Senhor, que é trazer salvação para todas as pessoas, incluindo gentios, como é enfatizado em Isaías 49.
* João 3:16: "Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo aquele que nele crer não pereça, mas tenha a vida eterna." Este versículo fala sobre o amor de Deus por todas as pessoas e sua vontade de trazer salvação para todos, que é um tema importante em Isaías 49.
* Efésios 2:12-13: "Lembrem-se de que naquele tempo vocês estavam sem Cristo, separados da comunidade de Israel, sendo estrangeiros quanto às alianças da promessa, sem esperança e sem Deus no mundo. Mas agora, em Cristo Jesus, vocês, que antes estavam longe, foram aproximados mediante o sangue de Cristo." Este versículo fala sobre a união de todas as pessoas em Cristo, que é um tema central em Isaías 49.
* Atos 13:47: "Porque assim o Senhor nos ordenou: Eu te constituí como luz para os gentios, a fim de que leves a salvação até os confins da terra." Esse versículo destaca a missão do Servo do Senhor em trazer salvação para todas as pessoas, não apenas para aqueles dentro de Israel, que é um tema importante em Isaías 49.
****

[[v29-49-1]]

^<<v29-49-1,1>>^ Ilhas, ouvi-me; povos de longe, prestai atenção! O Senhor chamou-me desde meu nascimento; ainda no seio de minha mãe, ele pronunciou meu nome.^&#42;1^

[[v29-49-2]]

^<<v29-49-2,2>>^ Tornou minha boca semelhante a uma espada afiada, cobriu-me com a sombra de sua mão. Fez de mim uma flecha penetrante, guardou-me na sua aljava.

[[v29-49-3]]

^<<v29-49-3,3>>^ E disse-me: “Tu és meu Servo Israel, em quem me rejubilarei”.^&#42;1^

[[v29-49-4]]

^<<v29-49-4,4>>^ E eu dizia a mim mesmo: “Foi em vão que padeci, foi em vão que gastei minhas forças”. Todavia, meu direito estava nas mãos do Senhor, e no meu Deus estava depositada a minha recompensa.

[[v29-49-5]]

^<<v29-49-5,5>>^ E agora o Senhor fala, ele, que me formou desde meu nascimento para ser seu servo, para trazer-lhe de volta Jacó e reunir-lhe Israel porque o Senhor fez-me esta honra, e meu Deus tornou-se minha força.^&#42;1^

[[v29-49-6]]

^<<v29-49-6,6>>^ Disse-me: “Não basta que sejas meu servo para restaurar as tribos de Jacó e reconduzir os fugitivos de Israel; vou fazer de ti a luz das nações, para propagar minha salvação até os confins do mundo”.^&#42;1^

[[v29-49-7]]

^<<v29-49-7,7>>^ Eis o que diz o Senhor, o Redentor, o Santo de Israel, ao objeto de desprezo dos homens e de horror das nações, ao escravo dos tiranos: diante de ti, reis se levantarão e príncipes se prostrarão, por causa do Senhor, que é fiel, e do Santo de Israel, que te elegeu.

[[v29-49-8]]

^<<v29-49-8,8>>^ Eis o que diz o Senhor: no tempo da graça eu te atenderei, no dia da salvação eu te socorrerei, Eu te formei e designei para fazer a aliança com os povos, para restaurar o país e distribuir as heranças devastadas,^&#42;1^

[[v29-49-9]]

^<<v29-49-9,9>>^ para dizer aos prisioneiros: “Saí!”. E àqueles que mergulham nas trevas: “Vinde à luz!”. Ao longo de todo o trajeto terão o que comer. Sobre todas as dunas encontrarão seu alimento.

[[v29-49-10]]

^<<v29-49-10,10>>^ Não sentirão fome nem sede; o vento quente e o sol não os castigarão, porque aquele que tem piedade deles os guiará e os conduzirá às fontes.

[[v29-49-11]]

^<<v29-49-11,11>>^ Eu lhes tornarei acessíveis todas as montanhas, e caminhos atingirão as alturas.

[[v29-49-12]]

^<<v29-49-12,12>>^ Ei-los que vêm de longe, ei-los do norte e do poente, e outros da terra de Assuã.^&#42;1^

[[v29-49-13]]

^<<v29-49-13,13>>^ Cantai, ó céus; terra, exulta de alegria; montanhas, prorrompei em aclamações! Porque o Senhor consolou seu povo, comoveu-se e teve piedade dos seus na aflição.

[[v29-49-14]]

^<<v29-49-14,14>>^ Sião dizia: “O Senhor abandonou-me, o Senhor esqueceu-me”.

[[v29-49-15]]

^<<v29-49-15,15>>^ Pode uma mulher esquecer-se daquele que amamenta? Não ter ternura pelo fruto de suas entranhas? E mesmo que ela o esquecesse, eu não te esqueceria nunca.

[[v29-49-16]]

^<<v29-49-16,16>>^ Eis que estás gravada na palma de minhas mãos, tenho sempre sob os olhos tuas muralhas.^&#42;1^

[[v29-49-17]]

^<<v29-49-17,17>>^ Acorrem já aqueles que vão reconstruir-te, enquanto teus destruidores e devastadores fogem.

[[v29-49-18]]

^<<v29-49-18,18>>^ Lança o olhar à volta e vê: reúnem-se todos e vêm a ti. “Por minha vida” – diz o Senhor – “de gala te revestirás, como uma noiva te cingirás.”

[[v29-49-19]]

^<<v29-49-19,19>>^ Teus bairros em ruína e devastados, teu território saqueado serão demasiado estreitos para teus habitantes, após a partida daqueles que se aproveitavam de ti.

[[v29-49-20]]

^<<v29-49-20,20>>^ Teus ouvidos ouvirão ainda de teus filhos, que julgavas perdidos: “O espaço é estreito demais para mim; dê-me espaço para que eu me instale!”.

[[v29-49-21]]

^<<v29-49-21,21>>^ Então, dirás a ti mesma: “Quem me gerou estes filhos?”. Não tinha filhos, era estéril: “Quem os criou?”. Eis que eu estava desamparada e só: “De onde vieram eles?”.^&#42;1^

[[v29-49-22]]

^<<v29-49-22,22>>^ Eis o que diz o Senhor Deus: “Com a mão vou fazer sinal às nações, e levantar meu estandarte para alertar os povos. Trarão teus filhos na dobra de seu manto, e em seus ombros carregarão tuas filhas.

[[v29-49-23]]

^<<v29-49-23,23>>^ Reis serão teus aios: prostrados diante de ti, a face contra a terra, lamberão a poeira de teus pés. Saberás então que eu sou o Senhor, e que não serão confundidos os que contam comigo”.^&#42;1^

[[v29-49-24]]

^<<v29-49-24,24>>^ Acaso se tirará a presa ao forte? Ou o que for tomado por um robusto guerreiro lhe escapará das mãos?

[[v29-49-25]]

^<<v29-49-25,25>>^ Eis o que diz o Senhor: “Sim, a presa do bravo lhe será retirada, a presa do robusto guerreiro lhe escapará; sustentarei tua causa contra teu adversário, libertarei eu mesmo teus filhos.^&#42;1^

[[v29-49-26]]

^<<v29-49-26,26>>^ Farei teus opressores comerem sua própria carne, eles se embriagarão com seu próprio sangue, como se fosse vinho. E toda criatura saberá que sou eu o Senhor, teu Salvador, teu Redentor, o Poderoso de Jacó”.^&#42;1^

'''

xref:029-isaias/029-isaias-048.adoc#v29-48-0[&#60; Capítulo Anterior] | <<v29-49-0,Topo>> | xref:029-isaias/029-isaias-050.adoc#v29-50-0[Próximo Capítulo &#62;]