include::./index.adoc[]

[[v29-38-0]]
=== Isaías, 38
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 38 conta a história do Rei Ezequias, que adoece gravemente e recebe a notícia de que morrerá em breve. Ele ora ao Senhor e pede que lhe conceda mais tempo de vida. Deus ouve sua oração e lhe dá mais 15 anos. Os versículos abaixo destacam temas como a cura divina, a misericórdia de Deus e a importância da oração.
* Salmos 30:2 - "Senhor meu Deus, clamei a ti por socorro, e tu me curaste." Este versículo fala sobre a cura divina, que é o que Ezequias pediu ao Senhor. Ele se voltou para Deus em sua aflição e foi curado.
* Salmos 103:3 - "Ele é quem perdoa todas as tuas iniquidades e cura todas as tuas doenças." Este versículo destaca a natureza misericordiosa de Deus, que não apenas perdoa nossos pecados, mas também cura nossas enfermidades.
* Tiago 5:15 - "A oração feita com fé curará o doente; o Senhor o levantará. E se houver cometido pecados, ele será perdoado." Este versículo mostra a importância da oração na busca pela cura. Ezequias orou fervorosamente ao Senhor e foi atendido.
* Salmos 30:5 - "Pois a sua ira dura só um momento, mas o seu favor dura a vida inteira; o choro pode persistir uma noite, mas de manhã irrompe a alegria." Este versículo destaca a misericórdia e o amor de Deus, que apesar da enfermidade de Ezequias, ainda o favoreceu com mais tempo de vida.
* Salmos 116:1-2 - "Amo o Senhor, porque ele ouve a minha voz e a minha súplica. Porque inclinou para mim os seus ouvidos, invocá-lo-ei enquanto eu viver." Este versículo mostra a importância da oração e da confiança em Deus. Ezequias confiou em Deus e orou por cura, e foi ouvido e respondido pelo Senhor.
****

[[v29-38-1]]

^<<v29-38-1,1>>^ Naquele tempo, Ezequias esteve doente, quase à morte. O profeta Isaías, filho de Amós, veio ter com ele e lhe disse: “Eis o que disse o Senhor: põe em ordem a tua casa porque vais morrer, não te restabelecerás”.^&#42;1^

[[v29-38-2]]

^<<v29-38-2,2>>^ Então, Ezequias voltou-se para a parede e se pôs a orar ao Senhor:

[[v29-38-3]]

^<<v29-38-3,3>>^ “Senhor” – disse ele –, “lembrai-vos de que tenho andado diante de vós com lealdade, de todo o coração, segundo a vossa vontade”. E chorava abundantemente.

[[v29-38-4]]

^<<v29-38-4,4>>^ Depois, a palavra do Senhor foi dirigida a Isaías nestes termos:

[[v29-38-5]]

^<<v29-38-5,5>>^ “Vai dizer a Ezequias: eis o que diz o Senhor, o Deus de Davi, teu pai: Ouvi tua oração e vi tuas lágrimas, prolongarei tua vida por quinze anos,

[[v29-38-6]]

^<<v29-38-6,6>>^ eu te livrarei, a ti e a esta cidade, das mãos do rei da Assíria. Protegerei esta cidade.^&#42;1^ [

[[v29-38-7]]

^<<v29-38-7,7>>^ E eis o sinal, da parte do Senhor, para convencer-te de que cumprirá a promessa:

[[v29-38-8]]

^<<v29-38-8,8>>^ farei a sombra recuar os dez graus que o sol já lhe fez descer no relógio solar de Acaz”. E o sol voltou dez graus para trás.

[[v29-38-9]]

^<<v29-38-9,9>>^ Poema composto por Ezequias, rei de Judá, quando esteve doente e se restabeleceu.

[[v29-38-10]]

^<<v29-38-10,10>>^ Eu dizia: “É necessário, pois, que eu me vá, no apogeu de minha vida. Serei encerrado por detrás das portas da habitação dos mortos, durante os anos que me restariam a viver”.

[[v29-38-11]]

^<<v29-38-11,11>>^ Eu dizia: “Não verei mais o Senhor na terra dos viventes. Não verei mais a luz entre os habitantes do mundo.

[[v29-38-12]]

^<<v29-38-12,12>>^ Arrancam as estacas de meu abrigo, arrebatam-me como uma tenda de pastores. Como um tecelão, enrolam a tela de minha vida, depois cortam-lhe o laço. Dia e noite estou desamparado,

[[v29-38-13]]

^<<v29-38-13,13>>^ e grito até o amanhecer. Como um leão, quebram-me todos os ossos.

[[v29-38-14]]

^<<v29-38-14,14>>^ Como a andorinha, dou gritos agudos e gemo como a pomba. Meus olhos se cansam de olhar para o alto. Senhor, estou em agonia, socorrei-me.^&#42;1^

[[v29-38-15]]

^<<v29-38-15,15>>^ Para que falar assim? Que dizer-lhe, uma vez que é ele mesmo quem assim o faz? O tempo que me resta eu o arrasto, vivendo em amargura.

[[v29-38-16]]

^<<v29-38-16,16>>^ Restituí-me a saúde, fazei-me reviver”.

[[v29-38-17]]

^<<v29-38-17,17>>^ Eis que meu sofrimento se mudou em conforto; vós preservastes minha vida do túmulo onde se apodrece, e lançastes para trás de vós todos os meus pecados.

[[v29-38-18]]

^<<v29-38-18,18>>^ Com efeito, não é a morada dos mortos que vos louvará, nem a morte que vos celebrará. O que desce à sepultura não espera mais em vossa bondade.

[[v29-38-19]]

^<<v29-38-19,19>>^ Quem está vivo, somente quem está vivo pode louvar-vos, como eu o faço hoje. O pai dá a conhecer a seus filhos vossa fidelidade, diante da casa do Senhor.

[[v29-38-20]]

^<<v29-38-20,20>>^ Senhor, dignai-vos a nos salvar, e nós faremos soar a corda de nossos instrumentos todos os dias de nossa vida.^&#42;1^

[[v29-38-21]]

^<<v29-38-21,21>>^ Isaías disse então: “Que tragam um cataplasma de figos para aplicar sobre a úlcera, e Ezequias sarará”.

[[v29-38-22]]

^<<v29-38-22,22>>^ Ezequias disse: “Que sinal me garantirá que eu tornarei ao Templo do Senhor?”]

'''

xref:029-isaias/029-isaias-037.adoc#v29-37-0[&#60; Capítulo Anterior] | <<v29-38-0,Topo>> | xref:029-isaias/029-isaias-039.adoc#v29-39-0[Próximo Capítulo &#62;]