include::./index.adoc[]

[[v29-10-0]]
=== Isaías, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 10 descreve o julgamento de Deus sobre o rei da Assíria, que Ele havia usado para disciplinar Seu povo, mas que agora havia se exaltado em seu orgulho e crueldade. O capítulo também fala sobre o papel de Deus como juiz e defensor de Seu povo, prometendo que Ele protegerá e libertará Seu povo do poder opressivo da Assíria. Abaixo estão cinco versículos relacionados com os temas abordados em Isaías 10:
* Salmo 9:7-8: "O Senhor é eterno; estabeleceu o seu trono para julgar. Ele mesmo julga o mundo com justiça; governa os povos com retidão." Este versículo destaca o papel de Deus como juiz justo, um tema central em Isaías 10.
* Salmo 94:22: "Mas o Senhor tem sido a minha fortaleza, e o meu Deus a rocha do meu refúgio." Este versículo fala sobre a proteção que Deus oferece a Seu povo em momentos de perigo e opressão, um tema central em Isaías 10.
* Salmo 121:7: "O Senhor te guardará de todo mal; ele guardará a tua alma." Este versículo também fala sobre a proteção que Deus oferece a Seu povo, um tema central em Isaías 10.
* Salmo 124:1-2: "Se não fora o Senhor, que esteve ao nosso lado, ora, diga Israel; Se não fora o Senhor, que esteve ao nosso lado, quando os homens se levantaram contra nós." Este versículo fala sobre o papel de Deus como defensor e protetor de Seu povo, um tema central em Isaías 10.
* Salmo 146:7: "O Senhor dá liberdade aos cativos; o Senhor abre os olhos aos cegos; o Senhor levanta os abatidos; o Senhor ama os justos." Este versículo fala sobre o poder de Deus para libertar Seu povo da opressão, um tema central em Isaías 10.
****

[[v29-10-1]]

^<<v29-10-1,1>>^ Ai daqueles que fazem leis injustas e dos escribas que redigem sentenças opressivas,^&#42;1^

[[v29-10-2]]

^<<v29-10-2,2>>^ para afastar os pobres dos tribunais e negar direitos aos fracos de meu povo; para fazer das viúvas sua presa e despojar os órfãos.

[[v29-10-3]]

^<<v29-10-3,3>>^ Que fareis vós no dia do ajuste de contas, e da tempestade que virá de longe? Junto de quem procurareis auxílio, e onde deixareis vossas riquezas?

[[v29-10-4]]

^<<v29-10-4,4>>^ A menos que vos curveis entre os cativos, tombareis entre os mortos. Apesar de tudo, sua cólera não se aplacou, e sua mão está prestes a precipitar-se.

[[v29-10-5]]

^<<v29-10-5,5>>^ Ai da Assíria, vara de minha cólera e bastão que maneja o meu furor.

[[v29-10-6]]

^<<v29-10-6,6>>^ Eu o enviei contra uma nação ímpia, e o lancei contra o povo, o objeto de minha cólera, para que o entregasse à pilhagem e lhe levasse os despojos, e o calcasse aos pés como a lama das ruas.

[[v29-10-7]]

^<<v29-10-7,7>>^ Mas ele não entendeu dessa maneira, e este não foi o seu pensamento. Ele só pensa em destruir, em exterminar nações em massa.^&#42;1^

[[v29-10-8]]

^<<v29-10-8,8>>^ Porque disse: “Porventura meus chefes não são todos eles reis?

[[v29-10-9]]

^<<v29-10-9,9>>^ Não teve Calane o destino de Carquemis, Emat, o de Arfad, e Samaria, o de Damasco?^&#42;1^

[[v29-10-10]]

^<<v29-10-10,10>>^ Assim como minha mão se apoderou dos reinos de falsos deuses, cujos ídolos eram mais numerosos que os de Jerusalém e de Samaria,

[[v29-10-11]]

^<<v29-10-11,11>>^ assim como tratei Samaria e seus falsos deuses, não devo tratar também Jerusalém e seus ídolos?”.^&#42;1^

[[v29-10-12]]

^<<v29-10-12,12>>^ Quando o Senhor tiver terminado a sua obra no monte Sião e em Jerusalém, ele punirá a linguagem orgulhosa do rei da Assíria e seus olhares insolentes. Porque ele disse:

[[v29-10-13]]

^<<v29-10-13,13>>^ “Foi pela força de minha mão que eu agi, e pela minha destreza, porque sou hábil. Dilatei as fronteiras, saqueei os tesouros e lancei por terra aqueles que estavam no trono.^&#42;1^

[[v29-10-14]]

^<<v29-10-14,14>>^ Minha mão tomou como um ninho a riqueza dos povos. Assim como se recolhem os ovos abandonados, eu reuni a terra inteira. Ninguém moveu a asa, nem abriu o bico, nem piou”.

[[v29-10-15]]

^<<v29-10-15,15>>^ Acaso o machado se vangloria à custa do lenhador? Ou a serra se levanta contra o serrador? Como se a vara fizesse agitar aquele que a maneja, como se o bastão fizesse mover o braço!

[[v29-10-16]]

^<<v29-10-16,16>>^ Por isso, o Senhor Deus dos exércitos fará enfraquecer seus robustos guerreiros, e debaixo de sua glória se acenderá um fogo como o de um incêndio.

[[v29-10-17]]

^<<v29-10-17,17>>^ A luz de Israel se tornará um fogo e seu Santo, uma chama, para queimar e devorar as suas sarças e seus espinhos em um só dia.

[[v29-10-18]]

^<<v29-10-18,18>>^ O esplendor de seu bosque e de seu jardim ele o aniquilará, corpo e alma. (Será como um doente que definha.)

[[v29-10-19]]

^<<v29-10-19,19>>^ Restarão tão poucas árvores em sua floresta, que um menino poderá contá-las.

[[v29-10-20]]

^<<v29-10-20,20>>^ Naquele tempo, o restante de Israel e os remanescentes da casa de Jacó deixarão de apoiar-se naquele que os fere, mas se apoiarão com confiança no Senhor, o Santo de Israel.^&#42;1^

[[v29-10-21]]

^<<v29-10-21,21>>^ Um resto voltará, um resto de Jacó, para o Deus forte.

[[v29-10-22]]

^<<v29-10-22,22>>^ Ainda que teu povo fosse inumerável como a areia do mar, dele só voltará um resto. A destruição está resolvida, a justiça vai tirar a desforra.

[[v29-10-23]]

^<<v29-10-23,23>>^ Essa sentença de ruína o Senhor, Deus dos exércitos, executará no centro de toda a terra.^&#42;1^

[[v29-10-24]]

^<<v29-10-24,24>>^ Por isso, o Senhor, Deus dos exércitos, disse: “Povo meu, que habitas em Sião, não temas o assírio que te castiga com a vara, e brande seu bastão contra ti, como outrora os egípcios.

[[v29-10-25]]

^<<v29-10-25,25>>^ Porque dentro de muito pouco tempo meu ressentimento contra vós terá fim e minha cólera o aniquilará.

[[v29-10-26]]

^<<v29-10-26,26>>^ O Senhor, Deus dos exércitos, vibrará o açoite contra ele como quando feriu Madiã, no penhasco de Oreb, e quando estendeu seu bastão sobre o mar, contra o Egito.^&#42;1^

[[v29-10-27]]

^<<v29-10-27,27>>^ Naquele tempo, o peso que ele te impôs será tirado de teus ombros, e o seu jugo desaparecerá de teu pescoço...”.^&#42;1^ Ele avança pelo lado de Remon,^&#42;2^

[[v29-10-28]]

^<<v29-10-28,28>>^ vai contra Aiat; passou por Magron, e depositou sua bagagem em Macmas;^&#42;1^

[[v29-10-29]]

^<<v29-10-29,29>>^ transpuseram o desfiladeiro, e acamparam em Gabaá. Ramá está aterrorizada, e Gabaá de Saul, tomada de pânico.

[[v29-10-30]]

^<<v29-10-30,30>>^ Levanta tua voz, ó filha de Galim; escuta, Laisa; responde-lhe Anatot.

[[v29-10-31]]

^<<v29-10-31,31>>^ Madmena está em fuga, e os habitantes de Gabim retiraram-se;

[[v29-10-32]]

^<<v29-10-32,32>>^ mais um dia de pouso em Nobe, e depois ele levantará sua mão contra o monte Sião, contra a colina de Jerusalém.

[[v29-10-33]]

^<<v29-10-33,33>>^ O Senhor, Deus dos exércitos, com um golpe terrível, abate os ramos, as grandes árvores são cortadas, e as mais altas lançadas por terra;

[[v29-10-34]]

^<<v29-10-34,34>>^ a ramagem da floresta tomba pelo ferro, e o Líbano desaba pela força.^&#42;1^

'''

xref:029-isaias/029-isaias-009.adoc#v29-9-0[&#60; Capítulo Anterior] | <<v29-10-0,Topo>> | xref:029-isaias/029-isaias-011.adoc#v29-11-0[Próximo Capítulo &#62;]