include::./index.adoc[]

[[v29-50-0]]
=== Isaías, 50
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 50 de Isaías começa com uma pergunta retórica: "Por acaso, eu me divorciei de vocês, ó Israel?". A partir daí, o profeta explica que os problemas enfrentados pelo povo de Israel foram causados por sua própria infidelidade a Deus e sua desobediência aos seus mandamentos. Isaías enfatiza que Deus ainda está presente para ajudá-los, mas é necessário que o povo se arrependa e volte a segui-lo. Abaixo estão cinco versículos relacionados com os temas abordados em Isaías 50:
* Deuteronômio 31:8: "O Senhor, Ele é quem vai adiante de ti; Ele será contigo, não te deixará, nem te desamparará. Não temas, nem te apavores." Este versículo fala da presença constante de Deus e da sua fidelidade para com o Seu povo.
* Salmos 34:18: "Perto está o Senhor dos que têm o coração quebrantado e salva os contritos de espírito." O Salmo 34:18 fala sobre a proximidade de Deus com aqueles que se arrependem e buscam a Sua ajuda.
* Jeremias 3:22: "Voltai, ó filhos rebeldes, eu curarei as vossas rebeliões." Este versículo mostra a disposição de Deus para perdoar e curar aqueles que se afastaram dele.
* João 14:15: "Se me amais, guardai os meus mandamentos." Esse versículo destaca a importância da obediência aos mandamentos de Deus como prova de amor a Ele.
* Hebreus 12:1-2: "Portanto, também nós, que estamos rodeados de tão grande nuvem de testemunhas, deixemos todo peso e o pecado que tão de perto nos rodeia e corramos, com perseverança, a carreira que nos está proposta, olhando firmemente para o Autor e Consumador da fé, Jesus, o qual, em troca da alegria que Lhe estava proposta, suportou a cruz, desprezando a vergonha, e assentou-se à direita do trono de Deus." Esse versículo incentiva os crentes a perseverarem na fé e a manterem os olhos fixos em Jesus, o exemplo perfeito de obediência e fidelidade a Deus.
****

[[v29-50-1]]

^<<v29-50-1,1>>^ Eis o que diz o Senhor: “Onde está a carta de divórcio pela qual eu teria repudiado vossa mãe? Ou, então, a qual de meus credores eu vos vendi? Está bem claro que por vossos crimes fostes vendidos, e por causa de vossos pecados vossa mãe foi repudiada.^&#42;1^

[[v29-50-2]]

^<<v29-50-2,2>>^ Então, por que não encontrei pessoa alguma quando vim? Por que ninguém respondeu ao meu apelo? Tenho eu realmente a mão demasiado curta para libertar, ou não tenho bastante força para salvar? Contudo, com uma simples ameaça, seco o mar e transformo as ondas em terra firme, de forma tal a faltar água para seus peixes, e seus animais perecerem de sede.^&#42;1^

[[v29-50-3]]

^<<v29-50-3,3>>^ Visto os céus com vestimentas de luto, e os cubro como de um cilício”.

[[v29-50-4]]

^<<v29-50-4,4>>^ O Senhor Deus deu-me a língua de um discípulo para que eu saiba reconfortar pela palavra o que está abatido. Cada manhã ele desperta meus ouvidos para que escute como discípulo;^&#42;1^

[[v29-50-5]]

^<<v29-50-5,5>>^ o Senhor Deus abriu-me o ouvido e eu não relutei, não me esquivei.

[[v29-50-6]]

^<<v29-50-6,6>>^ Aos que me feriam, apresentei as espáduas, e as faces àqueles que me arrancavam a barba; não desviei o rosto dos ultrajes e dos escarros.

[[v29-50-7]]

^<<v29-50-7,7>>^ Mas o Senhor Deus vem em meu auxílio: eis por que não me senti desonrado; enrijeci meu rosto como uma pedra, convicto de não ser desapontado.

[[v29-50-8]]

^<<v29-50-8,8>>^ Aquele que me fará justiça aí está. Quem ousará atacar-me? Vamos medir-nos! Quem será meu adversário? Que se apresente!

[[v29-50-9]]

^<<v29-50-9,9>>^ O Senhor Deus vem em meu auxílio: quem ousaria condenar-me? Cairão em frangalhos como um manto velho; a traça os roerá.

[[v29-50-10]]

^<<v29-50-10,10>>^ Que aqueles dentre vós que temem o Senhor ouçam a voz de seu Servo! Que aqueles que caminham no escuro, privados de luz, confiem no nome do Senhor e contem com o seu Deus!

[[v29-50-11]]

^<<v29-50-11,11>>^ Mas vós, que ateais um incêndio, que preparais projéteis inflamáveis, ide ao fogo do vosso incêndio, e dos projéteis que fizestes arder! É minha mão que vos imporá esse tratamento: sereis prostrados nos tormentos.^&#42;1^

'''

xref:029-isaias/029-isaias-049.adoc#v29-49-0[&#60; Capítulo Anterior] | <<v29-50-0,Topo>> | xref:029-isaias/029-isaias-051.adoc#v29-51-0[Próximo Capítulo &#62;]