include::./index.adoc[]

[[v29-36-0]]
=== Isaías, 36
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 36 narra a história de Senaqueribe, rei da Assíria, que enviou seu comandante para intimidar e ameaçar o povo de Judá, incluindo o rei Ezequias, a fim de conquistar Jerusalém. Ezequias recorre ao profeta Isaías para pedir ajuda e orientação divina. Os versículos relacionados aos temas do capítulo são:
* 2 Reis 18:5: "Ezequias confiou no Senhor, o Deus de Israel. Nenhum rei de Judá foi como ele, nem antes nem depois dele." Este versículo destaca a fidelidade de Ezequias a Deus, mesmo diante das ameaças de Senaqueribe.
* 2 Reis 18:13: "No décimo quarto ano do reinado de Ezequias, Senaqueribe, rei da Assíria, marchou contra todas as cidades fortificadas de Judá e as conquistou." Esse versículo descreve a ofensiva de Senaqueribe contra as cidades de Judá, incluindo Jerusalém.
* 2 Reis 18:17: "O rei da Assíria enviou o seu comandante-chefe com três mil homens de cavalaria e carros de guerra, e eles acamparam junto ao aqueduto do tanque superior, na estrada que vai do campo do lavandeiro à Lavanderia Real." Esse versículo descreve a chegada do comandante assírio e seu exército à Jerusalém.
* Salmos 46:1: "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade." Este versículo destaca a confiança em Deus como fonte de proteção e ajuda em tempos de crise.
* Isaías 37:35: "Eu defenderei esta cidade e a salvarei, por amor de mim e do meu servo Davi!" Este versículo mostra a promessa de Deus a Ezequias de que Ele irá proteger e salvar a cidade de Jerusalém da ameaça assíria.
****

[[v29-36-1]]

^<<v29-36-1,1>>^ No décimo quarto ano do reinado de Ezequias, aconteceu que Senaquerib, rei da Assíria, atacou todas as cidades fortificadas de Judá e se apoderou delas.^&#42;1^

[[v29-36-2]]

^<<v29-36-2,2>>^ O rei da Assíria tinha enviado de Laquis a Jerusalém, contra o rei Ezequias, o general de exército com um poderoso contingente de tropas. Ele tomou posição ao pé do aqueduto do reservatório superior, no caminho do campo do pisoeiro.

[[v29-36-3]]

^<<v29-36-3,3>>^ Eliacim, filho de Helcias, prefeito do palácio, foi ter com ele, junto com o escriba Sobna e o cronista Joaé, filho de Asaf.

[[v29-36-4]]

^<<v29-36-4,4>>^ O general lhes disse: “Eis o que direis a Ezequias: Assim fala o grande rei, o rei da Assíria: de onde te vem tanta confiança?

[[v29-36-5]]

^<<v29-36-5,5>>^ Tu só dizes palavras vãs. Entretanto, é de prudência e de bravura que se precisa na guerra. Sobre quem, então, pões tua confiança para contra mim te revoltares?

[[v29-36-6]]

^<<v29-36-6,6>>^ Eu o vejo: é com o Egito que tu contas, com esse caniço rachado que fere e transpassa a mão quando alguém sobre ele se apoia. Eis o que é o faraó, rei do Egito, para todos os que confiam nele.

[[v29-36-7]]

^<<v29-36-7,7>>^ Vós me direis, sem dúvida, que é no Senhor, vosso Deus, que pondes vossa confiança. Mas não é esse Deus de quem Ezequias suprimiu os lugares altos e os altares, dizendo ao povo de Judá e Jerusalém: ‘É somente diante desse altar que vos prostrareis?’.

[[v29-36-8]]

^<<v29-36-8,8>>^ Pois então, faze uma convenção com meu soberano, o rei da Assíria. Eu fornecerei dois mil cavalos, se puderes encontrar cavaleiros para montá-los.

[[v29-36-9]]

^<<v29-36-9,9>>^ Mas como serás capaz de repelir um só dos menores oficiais de meu soberano? Contas com o Egito para arranjar carros e cavaleiros?

[[v29-36-10]]

^<<v29-36-10,10>>^ Porventura, foi sem o consentimento do Senhor que ataquei esta terra para destruí-la? O Senhor foi quem me disse: ‘Vai contra aquela terra e a destrói’.”

[[v29-36-11]]

^<<v29-36-11,11>>^ Eliacim, Sobna e Joaé disseram ao general: “Fala a teus servos em aramaico, pois nós entendemos esse dialeto; não nos fales em hebraico, posto que a turba que está sobre a muralha pode ouvir-nos”.

[[v29-36-12]]

^<<v29-36-12,12>>^ Porém, o general replicou: “Porventura, é unicamente a teu soberano e a ti que meu soberano me encarregou de transmitir esta mensagem? Não é antes a esses homens que estão sobre as muralhas e que vão ser reduzidos, como vós, a comer seus excrementos e a beber sua urina?”.

[[v29-36-13]]

^<<v29-36-13,13>>^ O general adiantou-se, então, e se pôs a gritar em hebraico: “Escutai o que disse o grande rei, o rei da Assíria!

[[v29-36-14]]

^<<v29-36-14,14>>^ Eis o que disse o rei: Não vos deixeis enganar por Ezequias; ele é incapaz de vos livrar.

[[v29-36-15]]

^<<v29-36-15,15>>^ Que ele não vos leve a confiar no Senhor, dizendo que o Senhor vos livrará e que esta cidade não cairá nas mãos do rei da Assíria!

[[v29-36-16]]

^<<v29-36-16,16>>^ Não escuteis o rei Ezequias! Eis o que vos diz o rei da Assíria: Fazei a paz comigo. Rendei-vos. Cada um de vós poderá comer o fruto de sua vinha e de sua figueira e beber a água de seu poço,

[[v29-36-17]]

^<<v29-36-17,17>>^ até que eu venha conduzir-vos a uma terra semelhante à vossa, uma terra de trigo e de vinho, uma terra de cereais e de vinhas.

[[v29-36-18]]

^<<v29-36-18,18>>^ Que Ezequias não abuse de vós dizendo que o Senhor vos livrará! Porventura, os deuses das outras nações as livraram cada uma das mãos do rei da Assíria?

[[v29-36-19]]

^<<v29-36-19,19>>^ Onde estão os deuses de Emat e Arfad? Onde estão os deuses de Sefarvaim? Porventura, livraram eles a Samaria de minha mão?

[[v29-36-20]]

^<<v29-36-20,20>>^ Dentre todos os deuses dessas terras qual é o que salvou sua terra de minha mão? Por que então o Senhor preservaria Jerusalém?”.

[[v29-36-21]]

^<<v29-36-21,21>>^ O povo guardou silêncio. Não houve uma só palavra de resposta, pois o rei lhes havia proibido responder.

[[v29-36-22]]

^<<v29-36-22,22>>^ Eliacim, filho de Helcias, prefeito do palácio, o escriba Sobna e o cronista Joaé, filho de Asaf, retomaram para junto de Ezequias, com as vestes rasgadas, e lhe relataram as palavras do general.

'''

xref:029-isaias/029-isaias-035.adoc#v29-35-0[&#60; Capítulo Anterior] | <<v29-36-0,Topo>> | xref:029-isaias/029-isaias-037.adoc#v29-37-0[Próximo Capítulo &#62;]