include::./index.adoc[]

[[v29-9-0]]
=== Isaías, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 9 é um capítulo que traz uma mensagem de esperança, prometendo a vinda de um grande líder, que trará a luz para um povo que está em trevas. Este líder é descrito como um filho que será dado a nós, cujo governo trará paz, justiça e segurança. Para encontrar versículos relacionados com os temas abordados em Isaías 9, podemos buscar por passagens que falam sobre a esperança na vinda de um salvador, a luz que ele trará e a paz que seu governo trará.
* Isaías 42:1: "Aqui está o meu servo, a quem sustento, o meu escolhido, em quem tenho prazer. Pus nele o meu Espírito, e ele trará justiça às nações." Este versículo fala sobre o servo escolhido por Deus que trará justiça às nações, semelhante à descrição do líder prometido em Isaías 9.
* Lucas 1:79: "Para iluminar aos que estão sentados em trevas e na sombra da morte, a fim de dirigir nossos pés no caminho da paz." Este versículo fala sobre João Batista, que preparou o caminho para a vinda do Messias, que é a luz para aqueles que estão em trevas, como é descrito em Isaías 9.
* João 14:27: "Deixo-lhes a paz; a minha paz lhes dou. Não a dou como o mundo a dá. Não se perturbe o seu coração, nem tenham medo." Este versículo fala sobre a paz que Jesus deixa para seus discípulos e como essa paz é diferente da paz que o mundo pode oferecer, semelhante à paz que o líder prometido em Isaías 9 trará.
* Atos 26:18: "para que eles recebam o perdão dos pecados e herança entre os que são santificados pela fé em mim". Este versículo fala sobre a herança que é dada a todos aqueles que recebem o perdão de seus pecados pela fé em Jesus, semelhante à promessa de um governo de paz e justiça que é descrito em Isaías 9.
* Apocalipse 21:23: "A cidade não precisa de sol nem de lua para brilhar sobre ela, pois a glória de Deus a ilumina, e o Cordeiro é a sua candeia." Este versículo fala sobre a luz que ilumina a Nova Jerusalém, a cidade de Deus, semelhante à descrição da luz que o líder prometido em Isaías 9 trará.
****

[[v29-9-1]]

^<<v29-9-1,1>>^ O povo que andava nas trevas viu uma grande luz; sobre aqueles que habitavam uma região tenebrosa resplandeceu uma luz.

[[v29-9-2]]

^<<v29-9-2,2>>^ Vós suscitais um grande regozijo, provocais uma imensa alegria; rejubilam-se diante de vós como na alegria da colheita, como exultam na partilha dos despojos.

[[v29-9-3]]

^<<v29-9-3,3>>^ Porque o jugo que pesava sobre ele, a coleira de seu ombro e a vara do feitor, vós os quebrastes, como no dia de Madiã.^&#42;1^

[[v29-9-4]]

^<<v29-9-4,4>>^ Porque todo calçado que se traz na batalha, e todo manto manchado de sangue serão lançados ao fogo e se tornarão presa das chamas;

[[v29-9-5]]

^<<v29-9-5,5>>^ porque um menino nos nasceu, um filho nos foi dado; a soberania repousa sobre seus ombros, e ele se chama: Conselheiro admirável, Deus forte, Pai eterno, Príncipe da paz.^&#42;1^

[[v29-9-6]]

^<<v29-9-6,6>>^ Seu império será grande e a paz sem fim sobre o trono de Davi e em seu reino. Ele o firmará e o manterá pelo direito e pela justiça, desde agora e para sempre. Eis o que fará o zelo do Senhor dos exércitos.

[[v29-9-7]]

^<<v29-9-7,7>>^ O Senhor profere uma palavra contra Jacó, e ela vai cair sobre Israel.

[[v29-9-8]]

^<<v29-9-8,8>>^ Todo o povo conhece seus efeitos, Efraim e os habitantes de Samaria, que dizem no seu orgulho e na sua pretensão:

[[v29-9-9]]

^<<v29-9-9,9>>^ “Os tijolos caíram, nós edificaremos com pedras lavradas, os sicômoros foram cortados, nós os substituiremos por cedros”.

[[v29-9-10]]

^<<v29-9-10,10>>^ O Senhor sustentou seus inimigos contra ele, e estimulou seus adversários.

[[v29-9-11]]

^<<v29-9-11,11>>^ Aram pelo Oriente, os filisteus do Ocidente devoraram Israel com bons dentes. Apesar de tudo, sua cólera não se aplacou, e sua mão está prestes a precipitar-se.

[[v29-9-12]]

^<<v29-9-12,12>>^ O povo, porém, não se voltou para quem o feria, e não buscou o Senhor dos exércitos.

[[v29-9-13]]

^<<v29-9-13,13>>^ Então, o Senhor cortou a cabeça e a cauda de Israel, a palma e o junco em um só dia^&#42;1^

[[v29-9-14]]

^<<v29-9-14,14>>^ a cabeça é o ancião e o respeitável, a cauda é o falso profeta.

[[v29-9-15]]

^<<v29-9-15,15>>^ Aqueles que conduziam esse povo desencaminharam-no, e os que eles conduziam, perderam-se.

[[v29-9-16]]

^<<v29-9-16,16>>^ Por isso, o Senhor não poupa os jovens e não tem piedade dos órfãos nem das viúvas, porque todos eles são ímpios e perversos, e todas as bocas proferem infames palavras. Apesar de tudo, sua cólera não se aplacou, e sua mão está prestes a precipitar-se.

[[v29-9-17]]

^<<v29-9-17,17>>^ Porque a maldade queima como um fogo que devora as sarças e os espinhos, e depois envolve a espessura da floresta, de onde a fumaça se eleva em turbilhões.

[[v29-9-18]]

^<<v29-9-18,18>>^ Pela cólera do Senhor a terra está em fogo, e o povo veio a ser presa das chamas.

[[v29-9-19]]

^<<v29-9-19,19>>^ Cortam à direita, e têm fome, comem à esquerda, e não se satisfazem. Cada um devora a carne de seu próximo, e ninguém tem piedade de seu irmão;

[[v29-9-20]]

^<<v29-9-20,20>>^ Manassés come Efraim, e Efraim, Manassés; depois os dois juntos atacam Judá. Apesar de tudo, sua cólera não se aplacou, e sua mão está prestes a precipitar-se.

'''

xref:029-isaias/029-isaias-008.adoc#v29-8-0[&#60; Capítulo Anterior] | <<v29-9-0,Topo>> | xref:029-isaias/029-isaias-010.adoc#v29-10-0[Próximo Capítulo &#62;]