include::./index.adoc[]

[[v29-58-0]]
=== Isaías, 58
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 58 é um capítulo que trata da verdadeira religiosidade e do jejum que agrada a Deus. O povo de Israel estava realizando seus rituais religiosos, mas não estavam praticando a justiça e a misericórdia, o que era o verdadeiro objetivo de Deus. Portanto, o profeta Isaías exorta o povo a viver uma vida de justiça e amor ao próximo, e a se arrependerem de seus pecados. Os versículos abaixo são relacionados com os temas abordados em Isaías 58:
* Provérbios 21:3: "Fazer justiça e julgar com retidão é mais aceitável ao Senhor do que oferecer sacrifícios." Este versículo mostra que o Senhor valoriza a justiça mais do que rituais religiosos.
* Mateus 9:13: "Mas ide e aprendei o que significa: Misericórdia quero, e não sacrifício. Porque eu não vim a chamar os justos, mas os pecadores, ao arrependimento." Jesus cita uma passagem do Antigo Testamento para enfatizar a importância da misericórdia em vez de sacrifícios.
* Tiago 1:27: "A religião pura e imaculada diante de nosso Deus e Pai é esta: Visitar os órfãos e as viúvas nas suas aflições e guardar-se isento da corrupção do mundo." Este versículo reforça a importância da prática da justiça e da misericórdia.
* 1 João 3:17-18: "Ora, aquele que possuir recursos deste mundo e vir a seu irmão padecer necessidade, e fechar-lhe o seu coração, como pode permanecer nele o amor de Deus? Filhinhos, não amemos de palavra, nem de língua, mas por obras e em verdade." Este versículo exorta os cristãos a demonstrarem amor por seus irmãos através de suas ações.
* Mateus 25:40: "E o Rei lhes responderá: Em verdade vos digo que, sempre que o fizestes a um destes meus irmãos, mesmo dos mais pequeninos, a mim o fizestes." Neste versículo, Jesus ensina que quando ajudamos os outros, estamos servindo a ele.
****

[[v29-58-1]]

^<<v29-58-1,1>>^ Clama em alta voz, sem constrangimento; faze soar a tua voz como a corneta. Denuncia a meu povo suas faltas, e à casa de Jacó seus pecados.^&#42;1^

[[v29-58-2]]

^<<v29-58-2,2>>^ Sem dúvida, eles me procuram dia após dia, desejam conhecer o comportamento que me agrada, como uma nação que houvesse sempre praticado a justiça, sem abandonar a Lei de seu Deus. Informam-se junto a mim sobre as exigências da justiça, desejam a presença de Deus.

[[v29-58-3]]

^<<v29-58-3,3>>^ “De que serve jejuar, se com isso não vos importais? E mortificar-nos, se nisso não prestais atenção?” É que no dia de vosso jejum, só cuidais de vossos negócios, e oprimis todos os vossos operários.^&#42;1^

[[v29-58-4]]

^<<v29-58-4,4>>^ Passais vosso jejum em disputas e altercações, ferindo com o punho o pobre. Não é jejuando assim que fareis chegar lá em cima vossa voz.^&#42;1^

[[v29-58-5]]

^<<v29-58-5,5>>^ O jejum que me agrada porventura consiste em o homem mortificar-se por um dia? Curvar a cabeça como um junco, deitar sobre o saco e a cinza? Podeis chamar isso um jejum, um dia agradável ao Senhor?

[[v29-58-6]]

^<<v29-58-6,6>>^ Sabeis qual é o jejum que eu aprecio? – diz o Senhor Deus: é romper as cadeias injustas, desatar as cordas do jugo, mandar embora livres os oprimidos, e quebrar toda espécie de jugo.

[[v29-58-7]]

^<<v29-58-7,7>>^ É repartir seu alimento com o esfaimado, dar abrigo aos infelizes sem asilo, vestir os maltrapilhos, em lugar de desviar-se de seu semelhante.

[[v29-58-8]]

^<<v29-58-8,8>>^ Então, tua luz surgirá como a aurora, e tuas feridas não tardarão a cicatrizar-se; tua justiça caminhará diante de ti, e a glória do Senhor seguirá na tua retaguarda.

[[v29-58-9]]

^<<v29-58-9,9>>^ Então, às tuas invocações, o Senhor responderá, e a teus gritos dirá: “Eis-me aqui!”. Se expulsares de tua casa toda a opressão, os gestos malévolos e as más conversações;^&#42;1^

[[v29-58-10]]

^<<v29-58-10,10>>^ se deres do teu pão ao faminto, se alimentares os pobres, tua luz se levantará na escuridão, e tua noite resplandecerá como o dia pleno.

[[v29-58-11]]

^<<v29-58-11,11>>^ O Senhor te guiará constantemente, ele te alimentará no árido deserto, renovará teu vigor. Serás como um jardim bem irrigado, como uma fonte de águas inesgotáveis.

[[v29-58-12]]

^<<v29-58-12,12>>^ Reerguerás as ruínas antigas, reedificarás sobre os alicerces seculares; te chamarão o reparador de brechas, o restaurador das moradias em ruínas.

[[v29-58-13]]

^<<v29-58-13,13>>^ Se te abstiveres de calcar aos pés o sábado, de cuidar de teus negócios no dia que me é consagrado, se achares o sábado um dia maravilhoso, se achares respeitável o dia consagrado ao Senhor, se tu o venerares não seguindo os teus caminhos, não te entregando às tuas ocupações e às conversações,^&#42;1^

[[v29-58-14]]

^<<v29-58-14,14>>^ então, encontrarás tua felicidade no Senhor: eu te farei galgar as alturas da terra, e gozar a herança de Jacó, teu pai; porque a boca do Senhor falou.

'''

xref:029-isaias/029-isaias-057.adoc#v29-57-0[&#60; Capítulo Anterior] | <<v29-58-0,Topo>> | xref:029-isaias/029-isaias-059.adoc#v29-59-0[Próximo Capítulo &#62;]