include::./index.adoc[]

[[v29-57-0]]
=== Isaías, 57
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 57 é um capítulo que fala sobre a idolatria e a infidelidade de Israel, bem como a promessa de Deus de trazer cura e salvação para o seu povo. Há também uma advertência para aqueles que confiam em sua própria justiça e desobedecem a Deus. Aqui estão cinco versículos relacionados com esses temas:
* Provérbios 14:12: "Há caminho que parece certo ao homem, mas no final conduz à morte." Este versículo adverte sobre a confiança em nossa própria sabedoria e entendimento, que pode levar à morte espiritual.
* Jeremias 2:13: "Pois o meu povo cometeu dois males: eles me abandonaram, a mim, a fonte de água viva, e cavaram para si cisternas, cisternas rachadas que não retêm água." Aqui, Jeremias fala da infidelidade de Israel em buscar outras fontes de água em vez de confiar em Deus, a fonte verdadeira de vida.
* Oséias 14:1: "Volte, ó Israel, para o Senhor, o seu Deus. Os seus pecados os levaram à queda!" Este versículo chama Israel a se arrepender e retornar a Deus, reconhecendo sua culpa em sua queda espiritual.
* 2 Crônicas 7:14: "Se o meu povo, que se chama pelo meu nome, se humilhar, orar e buscar a minha face e se afastar dos seus maus caminhos, dos céus eu os ouvirei, perdoarei o seu pecado e curarei a sua terra." Este versículo oferece a promessa de Deus de cura e restauração para aqueles que se arrependem e voltam para Ele.
* Ezequiel 36:26: "Darei a vocês um coração novo e porei um espírito novo em vocês; tirarei de vocês o coração de pedra e lhes darei um coração de carne." Este versículo fala da promessa de Deus de transformar os corações daqueles que se voltam para Ele, substituindo a dureza e a frieza por um coração cheio de amor e compaixão.
****

[[v29-57-1]]

^<<v29-57-1,1>>^ E o justo perece sem que ninguém se aperceba; as pessoas de bem são arrebatadas e ninguém se importa;^&#42;1^

[[v29-57-2]]

^<<v29-57-2,2>>^ por causa do mal, o justo é arrebatado para entrar na paz; repousam sobre seus leitos aqueles que seguiam o caminho reto.

[[v29-57-3]]

^<<v29-57-3,3>>^ E vós, aproximai-vos, filhos da feiticeira, descendência da mulher adúltera e devassa!^&#42;1^

[[v29-57-4]]

^<<v29-57-4,4>>^ De quem vos escarneceis? A quem fazeis caretas e mostrais a língua? Não sois filhos do pecado, raça bastarda?

[[v29-57-5]]

^<<v29-57-5,5>>^ Vós vos abrasais sob os arvoredos de terebintos e sob qualquer árvore verde; vós imolais crianças no leito das torrentes e nas cavernas dos rochedos.^&#42;1^

[[v29-57-6]]

^<<v29-57-6,6>>^ As pedras polidas da torrente, eis o que te toca, sim, eis o teu quinhão; tu lhes ofereces libações, preparas-lhes oferendas. Posso a isso resignar-me?^&#42;1^

[[v29-57-7]]

^<<v29-57-7,7>>^ Sobre o cume de elevada montanha preparas teu leito, e é aí que sobes para oferecer sacrifícios.

[[v29-57-8]]

^<<v29-57-8,8>>^ Por trás da porta e seus umbrais, colocas teu emblema, porque não foi para mim que tu te descobriste, que estendeste a cama onde subiste; vais assalariar para ti aqueles com quem desejas ter negócios; admirando o ídolo, multiplicaste com eles as prostituições.^&#42;1^

[[v29-57-9]]

^<<v29-57-9,9>>^ Depois corres a Moloc com óleos, és pródiga em aromas, envias ao longe teus mensageiros, e os fazes descer à morada dos mortos.^&#42;1^

[[v29-57-10]]

^<<v29-57-10,10>>^ De tanto andar assim, tu te fatigas, sem jamais dizer: já basta; encontras ainda força, e segues sem parar.

[[v29-57-11]]

^<<v29-57-11,11>>^ A quem temias, então? De quem tinhas medo, para ser infiel, para não te lembrares de mim nem te preocupares comigo? Sem dúvida, eu me calava e fechava os olhos; por isso, tu não me temias.

[[v29-57-12]]

^<<v29-57-12,12>>^ Pois bem, vou mostrar o que valem tua justiça e tuas obras! Elas não te servirão de coisa alguma,^&#42;1^

[[v29-57-13]]

^<<v29-57-13,13>>^ quando pedires socorro. E não te salvarão teus ídolos: todos serão levados pelo vento. Um sopro as carregará. Aquele, porém, que contar comigo herdará a terra, e possuirá meu monte santo.^&#42;1^

[[v29-57-14]]

^<<v29-57-14,14>>^ Será dito: Abri, abri a estrada, aplanai-a! Retirai do caminho de meu povo todo obstáculo!

[[v29-57-15]]

^<<v29-57-15,15>>^ Porque eis o que diz o Altíssimo, cuja morada é eterna e o nome santo: “Habitando como Santo uma elevada morada, auxilio, todavia, o homem atormentado e humilhado; venho reanimar os humildes, e levantar os ânimos abatidos.

[[v29-57-16]]

^<<v29-57-16,16>>^ Realmente, não desejo controvérsias sem fim, nem persistir sempre no descontentamento, senão o espírito desfalecerá diante de mim, assim como as almas que criei.

[[v29-57-17]]

^<<v29-57-17,17>>^ Por causa do crime de meu povo me irritei um momento; feri-o, dando-lhe as costas na minha indignação, enquanto o rebelde agia segundo sua fantasia.

[[v29-57-18]]

^<<v29-57-18,18>>^ Vi sua conduta, disse o Senhor, e o curarei. Vou guiá-lo e consolá-lo,

[[v29-57-19]]

^<<v29-57-19,19>>^ vou fazer assomar aos lábios dos aflitos a ação de graças. Paz, paz àquele que está longe e àquele que está perto”.^&#42;1^

[[v29-57-20]]

^<<v29-57-20,20>>^ Mas os ímpios são como um mar encapelado, que não pode acalmar-se, cujas ondas revolvem lodo e lama. “Não há paz para os ímpios” – diz meu Deus.

'''

xref:029-isaias/029-isaias-056.adoc#v29-56-0[&#60; Capítulo Anterior] | <<v29-57-0,Topo>> | xref:029-isaias/029-isaias-058.adoc#v29-58-0[Próximo Capítulo &#62;]