include::./index.adoc[]

[[v29-5-0]]
=== Isaías, 5
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 5 apresenta uma parábola em que Deus é comparado a um agricultor que cuida de sua vinha, mas apesar de seus esforços, a vinha produz apenas frutos ruins. O capítulo termina com uma ameaça de julgamento contra Israel por sua infidelidade. Para encontrar versículos relacionados com os temas abordados em Isaías 5, podemos buscar por passagens que falam sobre a justiça de Deus, o julgamento e a infidelidade do povo.
* Provérbios 21:15: "Executar a justiça é motivo de alegria para o justo, mas de terror para os que praticam o mal." Este versículo destaca a importância da justiça e como ela pode trazer alegria ou terror, dependendo de como as pessoas agem.
* Jeremias 5:7: "Por que haveria de perdoar-te? Seus filhos me abandonaram e juraram pelos deuses que não são deuses. Eu os saciei, mas eles cometeram adultério; em casa de prostitutas se amontoaram." Neste versículo, Deus fala sobre a infidelidade do povo de Israel e como eles têm se voltado para outros deuses.
* Ezequiel 15:2-3: "Filho do homem, qual é a vinha que é melhor do que as outras vinhas, a qual as vinhas que estão ao redor dela serviram de ramos? Tiraram-se dela madeira para se fazer algum objeto? Ou dela se tomou um prego para pendurar algo?" Este versículo usa a imagem da vinha para falar sobre a posição especial de Israel entre as nações e como ela deveria ter sido uma fonte de bênção para os outros povos.
* João 15:1-2: "Eu sou a videira verdadeira, e meu Pai é o agricultor. Todo ramo que, estando em mim, não dá fruto, ele corta; e todo que dá fruto ele poda, para que dê mais fruto ainda." Neste versículo, Jesus se apresenta como a videira verdadeira e explica como Deus cuida de seus seguidores, podando aqueles que não produzem frutos e fortalecendo aqueles que o fazem.
* Hebreus 12:5-6: "E vocês esqueceram a palavra de ânimo que ele lhes dirige como a filhos: 'Meu filho, não despreze a disciplina do Senhor, nem desanime quando ele o repreender, pois o Senhor disciplina a quem ama, e castiga todo aquele que aceita como filho'." Este versículo fala sobre a disciplina de Deus e como ela é uma prova de seu amor por seus filhos, assim como a poda na videira pode trazer mais frutos.
****

[[v29-5-1]]

^<<v29-5-1,1>>^ Eu quero cantar para o meu amigo seu canto de amor a respeito de sua vinha: meu amigo possuía uma vinha em um outeiro fértil.^&#42;1^

[[v29-5-2]]

^<<v29-5-2,2>>^ Ele a cavou e tirou dela as pedras; plantou-a de cepas escolhidas. Edificou-lhe uma torre no meio, e construiu aí um lagar. E contava com uma colheita de uvas, mas ela só produziu agraço.^&#42;1^

[[v29-5-3]]

^<<v29-5-3,3>>^ “E agora, habitantes de Jerusalém, e vós, homens de Judá, sede juízes entre mim e minha vinha.

[[v29-5-4]]

^<<v29-5-4,4>>^ Que se poderia fazer por minha vinha, que eu não tenha feito? Por que, quando eu esperava vê-la produzir uvas, só deu agraço?

[[v29-5-5]]

^<<v29-5-5,5>>^ Pois bem, eu vos mostrarei agora o que hei de fazer à minha vinha: eu lhe arrancarei a sebe para que ela sirva de pasto, derrubarei o muro para que seja pisada.

[[v29-5-6]]

^<<v29-5-6,6>>^ Eu a farei devastada; não será podada nem cavada, e nela crescerão apenas sarças e espinhos; vedarei às nuvens derramar chuva sobre ela.”

[[v29-5-7]]

^<<v29-5-7,7>>^ A vinha do Senhor dos exércitos é a casa de Israel, e os homens de Judá são a planta de sua predileção. Esperei deles a prática da justiça, e eis o sangue derramado; esperei a retidão, e eis os gritos de socorro.

[[v29-5-8]]

^<<v29-5-8,8>>^ Ai de vós, que ajuntais casa a casa, e que acrescentais campo a campo, até que não haja mais lugar, e que sejais os únicos proprietários da terra.^&#42;1^

[[v29-5-9]]

^<<v29-5-9,9>>^ Os meus ouvidos ouviram ainda este juramento do Senhor dos exércitos: “Grande número de casas, eu o juro, será devastado, grandes e magníficas herdades ficarão desabitadas”.^&#42;1^

[[v29-5-10]]

^<<v29-5-10,10>>^ Dez jeiras de vinha não produzirão mais que um bato, e um homer de semente não dará mais que um efá.^&#42;1^

[[v29-5-11]]

^<<v29-5-11,11>>^ Ai daqueles que desde a manhã procuram a bebida, e que se retardam à noite nas excitações do vinho!

[[v29-5-12]]

^<<v29-5-12,12>>^ Amantes da cítara e da harpa, do tamborim e da flauta, e do vinho em seus banquetes, mas para as obras do Senhor não têm um olhar sequer, e não enxergam a obra de suas mãos.^&#42;1^

[[v29-5-13]]

^<<v29-5-13,13>>^ Por causa disso meu povo será desterrado sem nada pressentir. Sua nobreza será atenazada pela fome, e a multidão, mirrada pela sede.^&#42;1^

[[v29-5-14]]

^<<v29-5-14,14>>^ Por isso, a morada dos mortos se alargará, e abrirá desmesuradamente a boca. O esplendor de Sião e sua multidão barulhenta, seu alvoroço e sua alegria desaparecerão dela.

[[v29-5-15]]

^<<v29-5-15,15>>^ O homem será curvado, os grandes serão humilhados, os olhares altivos serão abatidos,^&#42;1^

[[v29-5-16]]

^<<v29-5-16,16>>^ e o Senhor dos exércitos triunfará no juízo; o Deus santo se mostrará como tal, fazendo justiça.

[[v29-5-17]]

^<<v29-5-17,17>>^ Os cordeiros serão apascentados nesses lugares como em suas pastagens, e sobre as ruínas pastarão os cabritos.^&#42;1^

[[v29-5-18]]

^<<v29-5-18,18>>^ Ai daqueles que arrastam a correção com as cordas da indisciplina, e a pena do pecado como com os tirantes de um carro!

[[v29-5-19]]

^<<v29-5-19,19>>^ (Ai) daqueles que dizem: “Que ele se avie, que faça já sua obra, a fim de que a vejamos. Que o plano do Santo de Israel se execute para que o conheçamos!”.^&#42;1^

[[v29-5-20]]

^<<v29-5-20,20>>^ Ai daqueles que ao mal chamam bem, e ao bem, mal, que mudam as trevas em luz e a luz em trevas, que tornam doce o que é amargo, e amargo o que é doce!

[[v29-5-21]]

^<<v29-5-21,21>>^ Ai daqueles que são sábios aos próprios olhos, e prudentes em seu próprio juízo!

[[v29-5-22]]

^<<v29-5-22,22>>^ Ai daqueles que põem sua bravura em beber vinho, e sua coragem em misturar licores;

[[v29-5-23]]

^<<v29-5-23,23>>^ (Ai) daqueles que, por uma dádiva, absolvem o culpado, e negam justiça àquele que tem o direito a seu lado!

[[v29-5-24]]

^<<v29-5-24,24>>^ Por isso, assim como a palhoça é devorada por uma língua de fogo, e como a palha é consumida pela chama, assim a raiz deles sucumbirá na podridão e sua flor voará como a poeira, porque repudiaram a Lei do Senhor dos exércitos, e desprezaram a palavra do Santo de Israel.

[[v29-5-25]]

^<<v29-5-25,25>>^ Por isso, o furor do Senhor se inflama contra seu povo, apodera-se dele e o castiga; os montes tremem, seus cadáveres, como carniça, jazem nas ruas. Entretanto, sua cólera não se aplacou, e sua mão está prestes a precipitar-se.

[[v29-5-26]]

^<<v29-5-26,26>>^ Ele arvora uma bandeira para chamar uma nação longínqua, assobia para fazê-la vir dos confins da terra, e ei-la que, ágil, acorre às pressas.^&#42;1^

[[v29-5-27]]

^<<v29-5-27,27>>^ Ninguém dentre eles se arrasta ou tropeça, ninguém dorme nem cochila; ninguém desata a cinta de seus rins, nem desaperta a correia dos sapatos.

[[v29-5-28]]

^<<v29-5-28,28>>^ Agudas são as suas flechas e todos os seus arcos, entesados. Os cascos de seus cavalos são duros como a pederneira, e as rodas de seus carros assemelham-se à tempestade.

[[v29-5-29]]

^<<v29-5-29,29>>^ É como o rugido da leoa, e o rosnar do leãozinho. Ele brame e agarra a sua presa, e a carrega sem que ninguém lha arrebate.

[[v29-5-30]]

^<<v29-5-30,30>>^ Naquele tempo, um estrondo, semelhante ao bramido do mar, retumbará contra ele. Quando olhar a terra, só verá trevas e angústia, e no céu se estenderão nuvens tenebrosas.^&#42;1^

'''

xref:029-isaias/029-isaias-004.adoc#v29-4-0[&#60; Capítulo Anterior] | <<v29-5-0,Topo>> | xref:029-isaias/029-isaias-006.adoc#v29-6-0[Próximo Capítulo &#62;]