include::./index.adoc[]

[[v29-18-0]]
=== Isaías, 18
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 18 trata da visão profética de Isaías sobre a Etiópia. O capítulo começa com uma descrição da terra que é habitada por um povo alto e esbelto, que vive ao longo das margens dos rios. Em seguida, o profeta fala sobre a mensagem que Deus tem para o povo etíope e como essa mensagem será entregue. Os versículos a seguir são relacionados com os temas abordados em Isaías 18:
* Salmo 68:31: "Príncipes virão do Egito; a Etiópia logo estenderá para Deus suas mãos." Este versículo indica que a Etiópia buscará a Deus e se voltará para Ele.
* Jeremias 46:9: "Subam, ó cavalos; furiosos, ó carros de guerra! Saiam, soldados: homens de Cuxe e de Pute que empunham escudos e homens de Lídia que manejam arcos e flechas." Este versículo faz referência aos exércitos etíopes que foram convocados para lutar.
* Salmos 105:23: "Então Israel foi para o Egito, e Jacó viveu como estrangeiro na terra de Cam." Este versículo se refere ao fato de que a Etiópia também é conhecida como a terra de Cam.
* Amós 9:7: "Não são vocês para mim como os filhos dos etíopes, ó israelitas? Declara o Senhor. "Este versículo indica que Deus considera os etíopes tão preciosos quanto os israelitas.
* Sofonias 3:10: "Desde além dos rios da Etiópia, os meus adoradores, a minha dispersão, me trarão ofertas." Este versículo faz referência aos adoradores de Deus vindos da Etiópia que trarão ofertas a Ele.
****

[[v29-18-1]]

^<<v29-18-1,1>>^ Oh! terra em que ressoa o ruído de asas, além dos rios da Etiópia,^&#42;1^

[[v29-18-2]]

^<<v29-18-2,2>>^ tu enviaste mensageiros por mar, em barcos de papiro, sobre a face das águas. Ide, mensageiros velozes, a um povo de alta estatura e de pele luzente, a uma nação temida ao longe, a uma nação poderosa e dominadora, cuja terra é cortada pelos rios.^&#42;1^

[[v29-18-3]]

^<<v29-18-3,3>>^ Vós, que habitais o mundo e povoais a terra, quando o estandarte se erguer nas alturas, olhai. E quando soar a trombeta, ouvi!

[[v29-18-4]]

^<<v29-18-4,4>>^ Pois eis o que o Senhor me disse: “Eu olho com serenidade do lugar onde me encontro, como o calor suave de um dia luminoso, como a nuvem que dá o orvalho durante o calor da messe”.

[[v29-18-5]]

^<<v29-18-5,5>>^ Porque antes da vindima, quando tiver passado a floração, e a flor se tornar um cacho amadurecente, os sarmentos serão cortados com a foice, e as cepas serão aparadas e arrancadas,^&#42;1^

[[v29-18-6]]

^<<v29-18-6,6>>^ e serão todos abandonados aos abutres dos montes, aos animais selvagens da planície; os abutres viverão deles no estio e os animais selvagens da planície os comerão no inverno.

[[v29-18-7]]

^<<v29-18-7,7>>^ Naquele tempo, serão levadas oferendas ao Senhor dos exércitos da parte do povo de alta estatura e pele luzente, do povo temido ao longe, da nação poderosa e dominadora, cuja terra é cortada pelos rios; serão levadas ao lugar onde reside o nome do Senhor dos exércitos, sobre o monte Sião.

'''

xref:029-isaias/029-isaias-017.adoc#v29-17-0[&#60; Capítulo Anterior] | <<v29-18-0,Topo>> | xref:029-isaias/029-isaias-019.adoc#v29-19-0[Próximo Capítulo &#62;]