include::./index.adoc[]

[[v29-60-0]]
=== Isaías, 60
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 60 é um capítulo que trata sobre a restauração e glória de Jerusalém. Nele, o profeta Isaías descreve uma Jerusalém transformada, cheia de luz e beleza, que atrai a atenção e o respeito das nações. Aqui estão cinco versículos relacionados aos temas deste capítulo:
* Salmos 72:10-11: "Os reis de Társis e das regiões costeiras trarão tributos; os reis de Sabá e de Seba oferecerão presentes. Todos os reis se curvarão diante dele, todas as nações o servirão." Este versículo mostra como Isaías 60 descreve a atenção e o respeito das nações por Jerusalém.
* Apocalipse 21:24: "As nações andarão à sua luz, e os reis da terra lhe trarão a sua glória." Este versículo descreve como Isaías 60 descreve a luz de Jerusalém, que é tão brilhante que as nações a seguirão.
* Salmos 72:15: "Viva ele, e receba ouro de Sabá; e continuamente se ore por ele, e bendiga-o todo o dia." Este versículo mostra como Isaías 60 descreve Jerusalém como uma cidade rica e próspera.
* Apocalipse 21:26: "Os portões não se fecharão de dia, pois ali não haverá noite." Este versículo descreve a Jerusalém de Isaías 60 como uma cidade segura, onde as portas estão sempre abertas.
* Zacarias 2:10: "Canta e alegra-te, ó filha de Sião, pois estou chegando para habitar no meio de ti", declara o Senhor." Este versículo mostra como Isaías 60 descreve Jerusalém como o lugar onde Deus habitará e onde seu povo se alegrará.
****

[[v29-60-1]]

^<<v29-60-1,1>>^ Levanta-te, sê radiosa, eis a tua luz! A glória do Senhor se levanta sobre ti.^&#42;1^

[[v29-60-2]]

^<<v29-60-2,2>>^ Vê, a noite cobre a terra e a escuridão, os povos, mas sobre ti levanta-se o Senhor, e sua glória te ilumina.

[[v29-60-3]]

^<<v29-60-3,3>>^ As nações se encaminharão à tua luz, e os reis, ao brilho de tua aurora.^&#42;1^

[[v29-60-4]]

^<<v29-60-4,4>>^ Levanta os olhos e olha à tua volta: todos se reúnem para vir a ti; teus filhos chegam de longe, e tuas filhas são transportadas à garupa.

[[v29-60-5]]

^<<v29-60-5,5>>^ Essa visão te tornará radiante; teu coração palpitará e se dilatará, porque para ti afluirão as riquezas do mar, e a ti virão os tesouros das nações.^&#42;1^

[[v29-60-6]]

^<<v29-60-6,6>>^ Serás invadida por uma multidão de camelos, pelos dromedários de Madiã e de Efá; virão todos de Sabá, trazendo ouro e incenso, e publicando os louvores do Senhor.

[[v29-60-7]]

^<<v29-60-7,7>>^ Todo o gado menor de Cedar se reunirá junto a ti, os carneiros de Nabaiot ficarão à tua disposição; eles os farão subir sobre meu altar para minha satisfação, e para a honra de meu templo glorioso.

[[v29-60-8]]

^<<v29-60-8,8>>^ Quem é que voa assim como as nuvens, ou como as pombas volvendo ao pombal?

[[v29-60-9]]

^<<v29-60-9,9>>^ Sim, as frotas convergem para mim, e os navios de Társis abrem a marcha, para trazer de longe teus filhos, bem como sua prata e seu ouro, para honrar o nome do Senhor, teu Deus, o Santo de Israel, que te cobriu de glória.^&#42;1^

[[v29-60-10]]

^<<v29-60-10,10>>^ Estrangeiros reerguerão tuas muralhas, e seus reis te servirão, pois, se te castiguei na minha cólera, na minha bondade tenho piedade de ti.

[[v29-60-11]]

^<<v29-60-11,11>>^ Tuas portas ficarão abertas permanentemente, nem de dia nem de noite serão fechadas, a fim de deixar afluir as riquezas das nações sob a custódia de seus reis.^&#42;1^

[[v29-60-12]]

^<<v29-60-12,12>>^ Porque a nação ou o reino que recusar servir-te perecerá, e sua terra será devastada.^&#42;1^

[[v29-60-13]]

^<<v29-60-13,13>>^ A glória do Líbano virá a ti, e todos juntos, o cipreste, a faia e o buxo, para ornamentar meu lugar santo e honrar o lugar onde pousam meus pés.^&#42;1^

[[v29-60-14]]

^<<v29-60-14,14>>^ Os próprios filhos de teus opressores a ti virão humilhados; a teus pés se prostrarão todos aqueles que te desprezavam; eles te chamarão a cidade do Senhor, a Sião do Santo de Israel.

[[v29-60-15]]

^<<v29-60-15,15>>^ De abandonada e amaldiçoada, sem ninguém para te socorrer, farei de ti um objeto de admiração para sempre, um motivo de alegria para as gerações futuras.^&#42;1^

[[v29-60-16]]

^<<v29-60-16,16>>^ Sugarás o leite das nações, e mamarás ao peito dos reis: saberás que eu, o Senhor, sou teu salvador, que teu redentor é o Poderoso de Jacó.

[[v29-60-17]]

^<<v29-60-17,17>>^ Em vez de bronze, farei vir ouro; em lugar de ferro, farei vir prata; em vez de madeira, bronze; em vez de pedras, ferro, farei reinar sobre ti a paz, e governar a justiça.

[[v29-60-18]]

^<<v29-60-18,18>>^ Não se ouvirá mais falar de violência em tua terra, nem de devastações e de ruínas em teu território. Chamarás tuas muralhas “Salvação”, tuas portas, “Glória”.

[[v29-60-19]]

^<<v29-60-19,19>>^ Não terás mais necessidade de sol para te alumiar, nem de lua para te iluminar: permanentemente terás por luz o Senhor, e teu Deus por resplendor.

[[v29-60-20]]

^<<v29-60-20,20>>^ Teu sol não mais se deitará, e tua lua não terá mais declínio, porque terás constantemente o Senhor por luz, e teus dias de luto estarão acabados.

[[v29-60-21]]

^<<v29-60-21,21>>^ Teu povo será um povo de justos que possuirá a terra para sempre; será uma planta cultivada pelo Senhor, obra de suas mãos destinada à sua glória.^&#42;1^

[[v29-60-22]]

^<<v29-60-22,22>>^ Do menor nascerá toda uma tribo, e do mínimo, uma nação poderosa, sou eu, o Senhor, que em tempo oportuno realizarei essas coisas.

'''

xref:029-isaias/029-isaias-059.adoc#v29-59-0[&#60; Capítulo Anterior] | <<v29-60-0,Topo>> | xref:029-isaias/029-isaias-061.adoc#v29-61-0[Próximo Capítulo &#62;]