include::./index.adoc[]

[[v29-44-0]]
=== Isaías, 44
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 44 de Isaías começa com uma mensagem de Deus ao povo de Israel, lembrando-os de que Ele é o seu Criador e Redentor, e que eles não devem adorar ídolos ou confiar em outros deuses. Deus promete que irá abençoar e restaurar Israel, e que eles não precisam temer, pois Ele está com eles. A seguir, cinco versículos relacionados com os temas abordados em Isaías 44:
* Salmos 115:4-7: "Os ídolos deles são prata e ouro, obra das mãos do homem. Têm boca, mas não falam; têm olhos, mas não veem; têm ouvidos, mas não ouvem; têm nariz, mas não cheiram." Este salmo descreve os ídolos que as pessoas adoram, contrastando-os com o Deus verdadeiro, que é vivo e ativo.
* Atos 17:24-25: "O Deus que fez o mundo e tudo o que nele há, sendo Senhor do céu e da terra, não habita em templos feitos por mãos de homens, nem é servido por mãos humanas, como se necessitasse de alguma coisa, pois ele mesmo é quem dá a todos a vida, a respiração e todas as coisas." Paulo usa esse discurso em Atenas para explicar que o Deus verdadeiro é o criador de tudo e não pode ser confinado a um templo ou imagem.
* Jeremias 10:6-7: "Não há semelhante a ti, ó Senhor; tu és grande, e grande é o teu nome em poder. Quem não te temerá, ó Rei das nações? Pois isto só a ti se deve; por entre todos os sábios das nações, e em todo o seu reino, não há outro semelhante a ti." Jeremias fala sobre a grandeza e singularidade de Deus, que é superior a todos os outros deuses ou ídolos.
* João 14:6: "Respondeu-lhe Jesus: Eu sou o caminho, e a verdade, e a vida. Ninguém vem ao Pai senão por mim." Jesus afirma que Ele é o único caminho para conhecer a Deus e ter a vida eterna, reforçando a mensagem de Isaías 44 sobre a necessidade de confiar em Deus e não em outros deuses.
* Efésios 2:10: "Porque somos feitura dele, criados em Cristo Jesus para boas obras, as quais Deus antes preparou para que andássemos nelas." Paulo fala sobre a nossa identidade como criaturas de Deus, criados para fazer o bem e glorificar a Ele, em linha com a mensagem de Isaías 44 sobre a importância de reconhecer a Deus como o nosso Criador e Redentor.
****

[[v29-44-1]]

^<<v29-44-1,1>>^ Agora escuta, Jacó, meu servo, Israel, a quem escolhi.

[[v29-44-2]]

^<<v29-44-2,2>>^ Eis o que diz o Senhor que te criou, que te formou desde o seio materno e te socorreu: “Nada temas, Jacó, meu servo, meu Israel, a quem escolhi!

[[v29-44-3]]

^<<v29-44-3,3>>^ Porque derramarei água sobre o solo sequioso, eu a farei correr sobre a terra árida, derramarei meu espírito sobre tua posteridade, e minha bênção sobre teus rebentos.

[[v29-44-4]]

^<<v29-44-4,4>>^ Crescerão como a vegetação irrigada, como os álamos à beira dos arroios.

[[v29-44-5]]

^<<v29-44-5,5>>^ Um dirá: ‘Eu sou do Senhor’, outro reclamará para si o nome de Jacó, um terceiro escreverá na sua mão: ‘Ao Senhor’, e receberá o cognome de Israel”.^&#42;1^

[[v29-44-6]]

^<<v29-44-6,6>>^ Eis o que diz o Senhor, o rei de Israel, seu Redentor, o Senhor dos exércitos: “Eu sou o primeiro e o último, não há outro Deus afora eu.

[[v29-44-7]]

^<<v29-44-7,7>>^ Quem é igual a mim? Que venha sustentar suas pretensões! Que prove e pleiteie contra mim! Quem anunciou o futuro, desde a origem? Que nos predigam o que deve ainda acontecer!

[[v29-44-8]]

^<<v29-44-8,8>>^ Não tenhais medo então, e não tremais! Não vos tenho esclarecido desde há muito tempo? Vós sois minhas testemunhas: existe outro Deus a não ser eu? Haverá outro rochedo além de mim?”.

[[v29-44-9]]

^<<v29-44-9,9>>^ Os fabricantes de ídolos nada são e suas preciosas obras nada valem; para confusão deles, suas testemunhas não sabem ver nem compreender.^&#42;1^

[[v29-44-10]]

^<<v29-44-10,10>>^ Aquele que quer modelar um deus, funde uma estátua que não servirá para nada.

[[v29-44-11]]

^<<v29-44-11,11>>^ Seus fiéis ficarão decepcionados e seus operários são apenas homens. Que todos se congreguem e compareçam. Ficarão assustados e decepcionados.

[[v29-44-12]]

^<<v29-44-12,12>>^ O ferreiro manipula o formão e trabalha no forno; talha o ídolo com golpes de martelo; modela-o com mão vigorosa; mas tem fome, sente-se esgotado, tem sede, está extenuado.

[[v29-44-13]]

^<<v29-44-13,13>>^ O escultor em madeira estica o cordel, traça o esquema a lápis, desbasta a imagem com o cinzel, mede-a com o compasso; dá-lhe forma humana, fá-la um belo tipo de homem, para colocá-la numa casa.

[[v29-44-14]]

^<<v29-44-14,14>>^ Vai cortar madeira, apanha um roble ou um carvalho que tinham deixado crescer entre as árvores da floresta que o Senhor havia plantado, e que a chuva havia feito crescer.

[[v29-44-15]]

^<<v29-44-15,15>>^ Depois faz com a madeira um fogo, e leva-o para se aquecer; queima-a também para cozer o pão; enfim, serve-se dela para fabricar um ídolo diante do qual se prosterna.

[[v29-44-16]]

^<<v29-44-16,16>>^ Queima a metade de sua madeira, sobre a brasa assa a carne, come esse assado até fartar-se. Então, aquece-se e diz: “Como é bom sentir o calor e admirar a chama!”.

[[v29-44-17]]

^<<v29-44-17,17>>^ Com a sobra faz um deus, um ídolo diante do qual se prostra para adorá-lo e orar dizendo: “Salva-me, tu és meu deus”.

[[v29-44-18]]

^<<v29-44-18,18>>^ Falta bom senso e juízo a essa gente; têm os olhos tão fechados que não veem, seus corações não podem compreender.

[[v29-44-19]]

^<<v29-44-19,19>>^ Ninguém reflete nem tem bom senso e inteligência para se dizer: “Queimei metade, cozi pão sobre a brasa, aí assei a carne que comi e iria eu fazer do resto um ídolo miserável? Eu me prostraria diante de um pedaço de madeira?”.

[[v29-44-20]]

^<<v29-44-20,20>>^ Este homem se nutre de cinzas, seu coração desabusado o desencaminha, ele não consegue salvar-se nem dizer: “Não será um logro o que tenho nas mãos?”.^&#42;1^

[[v29-44-21]]

^<<v29-44-21,21>>^ Lembra-te dessas coisas, Jacó! Recorda-te, Israel, que tu és meu servo. Eu te formei, tu és meu servo, Israel, não posso esquecer-te.

[[v29-44-22]]

^<<v29-44-22,22>>^ Fiz desaparecer tuas iniquidades como uma nuvem, e teus pecados como uma neblina: volve a mim, porque te resgatei.

[[v29-44-23]]

^<<v29-44-23,23>>^ Céus, regozijai-vos, pois o Senhor agiu: Ressoai de alegria, profundezas da terra! Explodi de alegria, ó montanhas! E tu também, floresta, com todas as tuas árvores, porque o Senhor resgatou Jacó, e manifestou sua glória em Israel.

[[v29-44-24]]

^<<v29-44-24,24>>^ Eis o que diz o Senhor, teu Redentor, que te formou desde o seio de tua mãe: “Sou eu, o Senhor, que fiz todas as coisas, sozinho estendi os céus. Firmei a terra: quem estava comigo?

[[v29-44-25]]

^<<v29-44-25,25>>^ Confundo os sinais dos falsos profetas, faço delirar os adivinhos, faço voltar atrás os sábios, e transformo sua sabedoria em loucura.

[[v29-44-26]]

^<<v29-44-26,26>>^ Mantenho a palavra de meus servos, cumpro o que predizem meus enviados; digo que Jerusalém deve ser reabitada. Que as cidades de Judá devem ser reedificadas. Delas reerguerei as ruínas.

[[v29-44-27]]

^<<v29-44-27,27>>^ Digo ao abismo: ‘Seca-te, vou estancar tuas torrentes’.

[[v29-44-28]]

^<<v29-44-28,28>>^ Digo de Ciro: ‘É meu pastor, executará em tudo a minha vontade’. Falando de Jerusalém: ‘Que seja reedificada!’. E do templo: ‘Que seja reconstruído!’.”

'''

xref:029-isaias/029-isaias-043.adoc#v29-43-0[&#60; Capítulo Anterior] | <<v29-44-0,Topo>> | xref:029-isaias/029-isaias-045.adoc#v29-45-0[Próximo Capítulo &#62;]