include::./index.adoc[]

[[v29-24-0]]
=== Isaías, 24
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 24 é um capítulo que fala sobre a destruição que virá sobre toda a terra por causa da rebelião contra Deus. O capítulo começa com a descrição da terra sendo completamente devastada e seus habitantes sofrendo as consequências da maldade que praticaram. Em seguida, fala sobre a punição que virá sobre os poderosos da terra e sobre a glória que Deus receberá quando restaurar a ordem. Abaixo estão cinco versículos relacionados com os temas abordados em Isaías 24:
* Salmos 46:8 - "Vinde, contemplai as obras do Senhor; que desolações tem feito na terra!" Este verso fala sobre a capacidade de Deus de causar desolação na terra como forma de punição pelos pecados dos homens.
* Mateus 24:21 - "Porque haverá então grande aflição, como nunca houve desde o princípio do mundo até agora, nem tampouco há de haver." Este verso fala sobre o julgamento vindouro que Deus trará sobre a terra, que será um tempo de grande aflição.
* Jeremias 25:31 - "O estrondo chegará até a extremidade da terra, porque o Senhor tem contenda com as nações, entrará em juízo com toda a carne; os ímpios entregará à espada, diz o Senhor." Este verso fala sobre a contenda de Deus com as nações da terra, e como Ele trará juízo sobre todos os ímpios.
* Apocalipse 19:1-2 - "Depois destas coisas ouvi no céu como que uma grande voz de uma grande multidão, que dizia: Aleluia! A salvação, e a glória, e o poder pertencem ao nosso Deus; porque verdadeiros e justos são os seus juízos, pois julgou a grande prostituta que corrompia a terra com a sua prostituição, e das mãos dela vingou o sangue dos seus servos." Este verso fala sobre a glória que Deus receberá quando trazer juízo sobre a terra e punir os ímpios.
* Isaías 26:21 - "Porque eis que o Senhor sairá do seu lugar, para castigar os moradores da terra, por causa da sua iniqüidade; e a terra descobrirá o seu sangue, e não encobrirá mais os seus mortos." Este verso fala sobre como Deus sairá de seu lugar para punir os moradores da terra por causa de sua iniqüidade.
****

[[v29-24-1]]

^<<v29-24-1,1>>^ Eis que o Senhor devasta a terra e a torna deserta, transtorna a sua face e dispersa seus habitantes.^&#42;1^

[[v29-24-2]]

^<<v29-24-2,2>>^ Isso acontece ao sacerdote como ao leigo, ao senhor como ao escravo, à senhora como à serva, ao vendedor como ao comprador, ao que empresta como ao que toma emprestado, ao credor como ao devedor.

[[v29-24-3]]

^<<v29-24-3,3>>^ A terra será totalmente devastada, inteiramente pilhada, porque o Senhor assim o decidiu.

[[v29-24-4]]

^<<v29-24-4,4>>^ A terra está na desolação, murcha; o mundo definha e esmorece, e os chefes do povo estão aterrados.^&#42;1^

[[v29-24-5]]

^<<v29-24-5,5>>^ A terra foi profanada por seus habitantes, porque transgrediram as leis, violaram as regras e romperam a aliança eterna.^&#42;1^

[[v29-24-6]]

^<<v29-24-6,6>>^ Por isso, a maldição devora a terra e seus habitantes expiam suas penas; os habitantes da terra são consumidos, um pequeno número de homens sobrevive.

[[v29-24-7]]

^<<v29-24-7,7>>^ O mosto está triste, a vinha, murcha, e os que tinham o coração em alegria suspiram.

[[v29-24-8]]

^<<v29-24-8,8>>^ O som alegre dos tamborins cessou, os risos morreram e o som alegre da cítara calou-se.

[[v29-24-9]]

^<<v29-24-9,9>>^ Não se canta mais bebendo vinho. O licor é amargo ao bebedor.

[[v29-24-10]]

^<<v29-24-10,10>>^ A cidade desordenada está em ruínas, todas as casas fechadas, para que ninguém possa entrar nelas.

[[v29-24-11]]

^<<v29-24-11,11>>^ Gritam nas ruas: Não há mais vinho! Acabada a alegria, o regozijo foi banido da terra.

[[v29-24-12]]

^<<v29-24-12,12>>^ Na cidade só restam escombros e a porta arrombada está em pedaços,

[[v29-24-13]]

^<<v29-24-13,13>>^ pois isso acontece na terra, no meio dos povos, como com as oliveiras que alguém vareja, como com as uvas que, acabada a vindima, alguém rebusca.

[[v29-24-14]]

^<<v29-24-14,14>>^ Eles elevam a voz e cantam, do lado do mar aclamam a majestade do Senhor:

[[v29-24-15]]

^<<v29-24-15,15>>^ “Glorificai, pois, ao Senhor, nas regiões da luz, e, nas ilhas do mar, o nome do Senhor, Deus de Israel”.^&#42;1^

[[v29-24-16]]

^<<v29-24-16,16>>^ Dos confins da terra, ouvimos cantar: “Honra ao justo!”. Eu, porém, disse: “Infeliz de mim, infeliz de mim! Ai de mim! Os salteadores saqueiam, os salteadores obstinam-se na pilhagem”.^&#42;1^

[[v29-24-17]]

^<<v29-24-17,17>>^ O terror, a fossa e a cilada vão apanhar-te, habitante da terra.

[[v29-24-18]]

^<<v29-24-18,18>>^ O que fugir para escapar do terror cairá na fossa, o que se livrar da fossa será preso no laço. Porque as comportas lá do alto se abrirão e os fundamentos da terra serão abalados.

[[v29-24-19]]

^<<v29-24-19,19>>^ A terra é feita em pedaços: estala, fende-se, é sacudida,

[[v29-24-20]]

^<<v29-24-20,20>>^ cambaleia como um homem embriagado e balança como uma rede. Seus crimes pesam sobre ela, e ela cairá para não mais se levantar.

[[v29-24-21]]

^<<v29-24-21,21>>^ Naquele tempo, o Senhor, lá do alto, examinará a milícia celeste e os reis do mundo, sobre a terra.^&#42;1^

[[v29-24-22]]

^<<v29-24-22,22>>^ Serão amontoados como prisioneiros num calabouço, serão encerrados numa prisão, e, depois de muitos dias, serão castigados.

[[v29-24-23]]

^<<v29-24-23,23>>^ A lua corará de vergonha e o sol empalidecerá, porque o Senhor dos exércitos reinará sobre o monte Sião e em Jerusalém, e sua glória resplandecerá diante de seus anciãos.

'''

xref:029-isaias/029-isaias-023.adoc#v29-23-0[&#60; Capítulo Anterior] | <<v29-24-0,Topo>> | xref:029-isaias/029-isaias-025.adoc#v29-25-0[Próximo Capítulo &#62;]