include::./index.adoc[]

[[v29-19-0]]
=== Isaías, 19
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 19 fala sobre a profecia do julgamento de Deus sobre o Egito e a promessa de redenção para o povo egípcio. Nesse capítulo, também é mencionado o papel que o Egito terá no futuro plano de Deus para o mundo. Abaixo estão cinco versículos relacionados com os temas abordados em Isaías 19:
* Jeremias 46:25: "O Senhor dos Exércitos, o Deus de Israel, disse: Eis que eu castigarei Amom de No, e a Faraó, e o Egito, juntamente com seus deuses e seus reis; sim, castigarei a Faraó, e a todos os que nele confiam." Este versículo fala sobre o castigo que Deus trará sobre o Egito e seus deuses, que está em linha com a profecia de Isaías 19.
* Ezequiel 29:13: "Porque assim diz o Senhor Deus: Também farei cessar a multidão do Egito pela mão de Nabucodonosor, rei de Babilônia." Este versículo fala sobre a queda do Egito nas mãos do rei Nabucodonosor, o que pode ser visto como uma realização da profecia de Isaías 19.
* Zacarias 10:11: "Ele passará pelo mar de aflição, e ferirá as ondas no mar, e todas as profundezas do rio se secarão; e a soberba da Assíria será derrubada, e o cetro do Egito se retirará." Este versículo fala sobre a soberba do Egito e como seu poder será quebrado por Deus.
* Salmo 87:4: "Farei menção de Raabe e de Babilônia àqueles que me conhecem; eis que da Filístia, e de Tiro, e da Etiópia, se dirá: Este homem nasceu ali." Este versículo pode ser interpretado como uma referência ao papel que o Egito terá no futuro plano de Deus, mencionado em Isaías 19.
* Apocalipse 11:8: "E jazerão os seus corpos na praça da grande cidade que espiritualmente se chama Sodoma e Egito, onde também o seu Senhor foi crucificado." Este versículo fala sobre a cidade em que Jesus foi crucificado, que é comparada a Sodoma e Egito. Embora não esteja diretamente relacionado à profecia de Isaías 19, sugere que o Egito é visto como um símbolo de corrupção e opressão na Bíblia.
****

[[v29-19-1]]

^<<v29-19-1,1>>^ Oráculo contra o Egito. Eis que o Senhor, montado numa nuvem rápida, vem ao Egito. Os ídolos do Egito tremem diante dele e o Egito sente desfalecer sua coragem.

[[v29-19-2]]

^<<v29-19-2,2>>^ Excitarei os egípcios, uns contra os outros, e eles se baterão irmão contra irmão, amigo contra amigo, cidade contra cidade, reino contra reino.

[[v29-19-3]]

^<<v29-19-3,3>>^ O Egito perderá a cabeça, e eu abolirei sua prudência. Consultarão os ídolos e os feiticeiros, os evocadores de mortos e os adivinhos.

[[v29-19-4]]

^<<v29-19-4,4>>^ Entregarei esta terra nas mãos de um soberano cruel, um rei implacável a dominará. Oráculo do Senhor dos exércitos.

[[v29-19-5]]

^<<v29-19-5,5>>^ As águas do mar se estancarão, e o rio se tornará seco e árido.^&#42;1^

[[v29-19-6]]

^<<v29-19-6,6>>^ A água estagnará nos canais, os rios do Egito diminuirão e secarão. Juncos e caniços murcharão^&#42;1^

[[v29-19-7]]

^<<v29-19-7,7>>^ nas campinas à margem do Nilo; tudo o que cresce ao longo do rio secará, cairá e desaparecerá;

[[v29-19-8]]

^<<v29-19-8,8>>^ os pescadores ficarão desolados, os que lançam o anzol no rio se lamentarão, e os que lançam suas redes às águas ficarão consternados.

[[v29-19-9]]

^<<v29-19-9,9>>^ Os que trabalham o linho ficarão decepcionados, os cardadores e os tecelães serão confundidos,

[[v29-19-10]]

^<<v29-19-10,10>>^ os tecedores ficarão à míngua, e todos os trabalhadores em desolação.

[[v29-19-11]]

^<<v29-19-11,11>>^ Os príncipes de Tânis enlouquecerão, os sábios conselheiros do faraó formarão um conselho insensato. Como ousais dizer ao faraó: “Eu sou filho de sábios, filho dos antigos reis?”.^&#42;1^

[[v29-19-12]]

^<<v29-19-12,12>>^ Onde estão agora os teus sábios? Que eles te anunciem e te façam saber os desígnios do Senhor dos exércitos contra o Egito!

[[v29-19-13]]

^<<v29-19-13,13>>^ Os príncipes de Tânis perdem a razão, os príncipes de Mênfis são iludidos; e os chefes das tribos desencaminham o Egito.

[[v29-19-14]]

^<<v29-19-14,14>>^ O Senhor difundiu entre eles um espírito de vertigem, e eles vagueiam por todo o Egito sem desígnio certo, como um bêbado que cambaleia em seu vômito.

[[v29-19-15]]

^<<v29-19-15,15>>^ O Egito não está em condições de decidir o que devem fazer a cabeça e a cauda, a palma e o junco.

[[v29-19-16]]

^<<v29-19-16,16>>^ Naquele tempo, os egípcios serão como mulheres, tremerão de medo sob a ameaça da mão do Senhor levantada sobre eles.

[[v29-19-17]]

^<<v29-19-17,17>>^ Então, a terra de Judá será o terror do Egito; logo que se fale nela, ele se encherá de pavor, por causa dos desígnios que o Senhor dos exércitos formou contra ele.

[[v29-19-18]]

^<<v29-19-18,18>>^ Naquele tempo, haverá no Egito cinco cidades que falarão a língua de Canaã e jurarão pelo Senhor dos exércitos. Uma delas será chamada a Cidade do Sol.^&#42;1^

[[v29-19-19]]

^<<v29-19-19,19>>^ Naquele tempo, haverá um altar erguido ao Senhor, em pleno Egito, e, em suas fronteiras, um obelisco dedicado ao Senhor.

[[v29-19-20]]

^<<v29-19-20,20>>^ E eles servirão de monumento ao Senhor, na terra do Egito. Quando maltratados pelos opressores, invocarão o Senhor, e ele lhes enviará um salvador, um defensor que os libertará.^&#42;1^

[[v29-19-21]]

^<<v29-19-21,21>>^ O Senhor se dará a conhecer ao Egito, os egípcios conhecerão o Senhor naquele tempo, e lhe oferecerão sacrifícios e oblações; farão votos ao Senhor e os cumprirão.

[[v29-19-22]]

^<<v29-19-22,22>>^ Quando o Senhor ferir os egípcios, será para curá-los; eles se voltarão para o Senhor, que se deixará aplacar e os curará.

[[v29-19-23]]

^<<v29-19-23,23>>^ Naquele tempo, haverá um caminho do Egito para a Assíria; os assírios irão ao Egito, e os egípcios, à Assíria. O Egito e a Assíria renderão culto ao Senhor.^&#42;1^

[[v29-19-24]]

^<<v29-19-24,24>>^ Naquele tempo, Israel será, como terceiro, aliado ao Egito e à Assíria, objeto da bênção no meio da terra que o Senhor dos exércitos abençoará nestes termos: “Bendito seja meu povo do Egito, a Assíria, obra de minhas mãos, e Israel, minha herança!”.^&#42;1^

'''

xref:029-isaias/029-isaias-018.adoc#v29-18-0[&#60; Capítulo Anterior] | <<v29-19-0,Topo>> | xref:029-isaias/029-isaias-020.adoc#v29-20-0[Próximo Capítulo &#62;]