include::./index.adoc[]

[[v29-13-0]]
=== Isaías, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 13 fala sobre o julgamento de Deus sobre a Babilônia e os povos vizinhos por causa de sua idolatria e opressão. Os versículos a seguir se relacionam com os temas do capítulo:
* Jeremias 50:15: "Gritem contra ela por todos os lados! Ela se entregou; caíram suas colunas, foram derrubados os seus muros. Este é o castigo do Senhor; vinguemo-nos dela; façamos a ela o que ela merece!" Este versículo mostra o julgamento de Deus sobre a Babilônia, cumprindo a profecia de Isaías 13.
* Isaías 14:22-23: "Eu me levantarei contra eles, diz o Senhor dos Exércitos, e eliminarei o nome e o restante de Babilônia, seus descendentes e seus filhos, diz o Senhor. Farei dela uma posse de ouriços e a molharei com a água do lagar; e não haverá quem aí more, nem quem habite nela, de geração em geração." Este versículo mostra a destruição completa de Babilônia por Deus.
* Apocalipse 18:6-8: "Retribui-lhe como ela vos tem retribuído, e retribui-lhe em dobro, segundo as suas obras; no cálice em que ela misturou, misturai para ela em dobro. Quanto ela se engrandeceu e viveu luxuosamente, tanto lhe dai de tormento e de pranto; porque ela diz em seu coração: Estou sentada como rainha e não sou viúva, e de modo algum verei o pranto. Por isso, num só dia virão as suas pragas: morte, pranto e fome; e será consumida no fogo; porque poderoso é o Senhor Deus que a julga." Este versículo fala sobre o julgamento de Babilônia nos últimos dias, em conformidade com as profecias de Isaías 13.
* Jeremias 51:7: "A Babilônia era um copo de ouro na mão do Senhor, que embriagava toda a terra; as nações beberam do seu vinho, por isso as nações estão enlouquecidas." Este versículo mostra como a Babilônia se tornou um símbolo de opressão e corrupção para todas as nações, e como Deus a julgará por isso.
* Naum 1:2-3: "O Senhor é Deus zeloso e vingador; o Senhor é vingador e cheio de furor; o Senhor toma vingança contra os seus adversários e guarda a ira para os seus inimigos. O Senhor é tardio em irar-se, mas grande em poder, e de modo algum terá por inocente o culpado." Este versículo mostra que Deus é um Deus justo e vingativo, que não permitirá que a injustiça e a opressão continuem impunes.
****

[[v29-13-1]]

^<<v29-13-1,1>>^ Oráculo contra Babilônia, revelado a Isaías, filho de Amós.^&#42;1^

[[v29-13-2]]

^<<v29-13-2,2>>^ Levantai o estandarte sobre a colina escalvada, elevai a voz contra eles. Fazei-lhes sinal com as mãos, para que transponham as portas dos nobres.^&#42;1^

[[v29-13-3]]

^<<v29-13-3,3>>^ Em minha cólera requisitei minhas tropas sagradas, e chamei os meus bravos e meus altivos triunfadores.

[[v29-13-4]]

^<<v29-13-4,4>>^ Escutai esse ruído sobre os montes como vozerio de grande multidão; escutai o tumulto dos reinos e das nações reunidas. É o Senhor dos exércitos que passa em revista suas tropas para a batalha.

[[v29-13-5]]

^<<v29-13-5,5>>^ Chegam de uma terra longínqua, da extremidade dos céus, o Senhor e os instrumentos de seu furor, para devastar toda a terra.

[[v29-13-6]]

^<<v29-13-6,6>>^ Lamentai-vos, porque o dia do Senhor está próximo como uma devastação provocada pelo Todo-poderoso.

[[v29-13-7]]

^<<v29-13-7,7>>^ Por causa disso, deixam cair os braços; todos perdem a coragem;^&#42;1^

[[v29-13-8]]

^<<v29-13-8,8>>^ ficam cheios de terror... Tomados de convulsões e dores, eles se retorcem como uma mulher em parto. Olham uns para os outros e têm o rosto em fogo.

[[v29-13-9]]

^<<v29-13-9,9>>^ Eis que virá o dia do Senhor, dia implacável, de furor e de cólera ardente, para reduzir a terra a um deserto, e dela exterminar os pecadores.

[[v29-13-10]]

^<<v29-13-10,10>>^ Nem as estrelas do céu, nem suas constelações brilhantes, farão resplandecer sua luz; o sol se obscurecerá desde o nascer, e a lua já não enviará sua luz.

[[v29-13-11]]

^<<v29-13-11,11>>^ Punirei o mundo por seus crimes, e os pecadores por suas maldades. Abaterei o orgulho dos arrogantes e humilharei a pretensão dos tiranos.

[[v29-13-12]]

^<<v29-13-12,12>>^ Tornarei os homens mais raros que o ouro fino, e os mortais mais raros que o metal de Ofir.

[[v29-13-13]]

^<<v29-13-13,13>>^ Farei oscilar os céus, e a terra abalada será sacudida pela ira do Senhor, Deus dos exércitos, no dia do seu furor ardente.

[[v29-13-14]]

^<<v29-13-14,14>>^ Então, como uma gazela assustada, como um rebanho que ninguém recolhe, cada um voltará para seu povo, e fugirá para sua terra.^&#42;1^

[[v29-13-15]]

^<<v29-13-15,15>>^ Todos aqueles que forem encontrados serão mortos; os que forem apanhados serão passados à espada.

[[v29-13-16]]

^<<v29-13-16,16>>^ Seus filhinhos serão massacrados diante de seus olhos, suas casas serão saqueadas, e suas mulheres, violadas.^&#42;1^

[[v29-13-17]]

^<<v29-13-17,17>>^ Suscitarei contra eles os medos, que não se interessam pela prata, nem apreciam o ouro.^&#42;1^

[[v29-13-18]]

^<<v29-13-18,18>>^ Seus arcos abaterão os jovens; não terão compaixão pelos frutos das entranhas, nem piedade das crianças.

[[v29-13-19]]

^<<v29-13-19,19>>^ Então Babilônia, a pérola dos reinos, a joia de que os caldeus tanto se orgulham, será destruída por Deus, como Sodoma e Gomorra.

[[v29-13-20]]

^<<v29-13-20,20>>^ Nunca mais será habitada, nem povoada até o fim dos tempos. O árabe não mais erguerá aí sua tenda, os pastores não amalharão aí seus rebanhos,

[[v29-13-21]]

^<<v29-13-21,21>>^ as feras terão aí seu covil, os mochos frequentarão as casas, as avestruzes morarão aí, e os sátiros farão aí suas danças.^&#42;1^

[[v29-13-22]]

^<<v29-13-22,22>>^ Os chacais uivarão nos seus palácios, e os lobos, nas suas casas de prazer. Sua hora está próxima e seus dias estão contados.

'''

xref:029-isaias/029-isaias-012.adoc#v29-12-0[&#60; Capítulo Anterior] | <<v29-13-0,Topo>> | xref:029-isaias/029-isaias-014.adoc#v29-14-0[Próximo Capítulo &#62;]