include::./index.adoc[]

[[v29-15-0]]
=== Isaías, 15
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Isaías 15 descreve a destruição de Moabe, um povo vizinho de Israel. O capítulo narra a aflição e o desespero dos moabitas diante da invasão e do julgamento divino. A seguir, estão cinco versículos relacionados com os temas abordados em Isaías 15:
* Jeremias 48:46: "Ai de ti, Moabe! O povo de Quemós pereceu, porque teus filhos foram levados cativos para o cativeiro, e tuas filhas, para o cativeiro." Este versículo fala sobre a captura e o exílio dos moabitas pelos babilônios, um evento que foi profetizado por Isaías em seu livro.
* Salmos 60:8: "A Moabe lançarei o meu sapato; sobre Edom clamarei em alta voz; faze-me assim, ó Filisteia, por causa de mim." Este verso expressa a ira de Deus contra Moabe e outras nações inimigas de Israel.
* 2 Reis 3:27: "Então, tomou ele a seu primogênito, que devia reinar em seu lugar, e o ofereceu em holocausto sobre o muro. E houve grande indignação em Israel; e retiraram-se dele, e voltaram para a sua terra." Este verso relata um ato extremo de sacrifício humano cometido pelos moabitas em uma tentativa de escapar da derrota.
* Jeremias 48:35: "E porei fim ao que oferece sacrifícios nos altos, e ao que queima incenso aos seus deuses." Este verso é uma profecia sobre a destruição dos altares de adoração a deuses pagãos em Moabe.
* Ezequiel 25:8: "Assim diz o Senhor JEOVÁ: Porquanto Moabe e Seir dizem: Eis que a casa de Judá é como todas as outras nações." Este verso destaca a hostilidade dos moabitas em relação a Judá, a nação irmã de Israel.
****

[[v29-15-1]]

^<<v29-15-1,1>>^ Oráculo contra Moab. Sim, atacada de noite, Ar-Moab foi destruída. Sim, atacada de noite, Quir-Moab foi destruída.^&#42;1^

[[v29-15-2]]

^<<v29-15-2,2>>^ O povo de Dibon subiu aos lugares altos para chorar, ao Nebo e ao Medaba: Moab lamenta-se. Todas as cabeças estão raspadas, todas as barbas cortadas.

[[v29-15-3]]

^<<v29-15-3,3>>^ Na rua vestem burel e lamentam-se nos terraços. Tudo geme e se desfaz em pranto.

[[v29-15-4]]

^<<v29-15-4,4>>^ Hesebon e Elale soltam gritos, e sua voz chega até Jasa. Também Moab sente seus rins fremirem e sua alma desfalecer.

[[v29-15-5]]

^<<v29-15-5,5>>^ Do fundo do coração Moab geme, seus fugitivos alcançam Segor em Eglat-Selísia. Sim, a subida de Luit, fazem-na chorando. Sim, pela estrada de Horonaim soltam gritos de aflição.

[[v29-15-6]]

^<<v29-15-6,6>>^ Ah! As águas de Nemrim se esgotaram. A erva secou, a relva murchou, e as plantas não mais existem.

[[v29-15-7]]

^<<v29-15-7,7>>^ Por isso, levam seus bens e suas provisões para além da torrente dos salgueiros.

[[v29-15-8]]

^<<v29-15-8,8>>^ Porque o clamor circula por todas as fronteiras de Moab, suas lamentações ecoam até Eglaim, suas lamentações atingem Beer-Belim.

[[v29-15-9]]

^<<v29-15-9,9>>^ Porque as águas de Dimon estão cheias de sangue porque enviarei sobre Dimon novos infortúnios, um leão contra os remanescentes de Moab e contra os que restarem no país sobrevivente de Adma.^&#42;1^

'''

xref:029-isaias/029-isaias-014.adoc#v29-14-0[&#60; Capítulo Anterior] | <<v29-15-0,Topo>> | xref:029-isaias/029-isaias-016.adoc#v29-16-0[Próximo Capítulo &#62;]