include::./index.adoc[]

[[v53-14-0]]
=== I Coríntios, 14
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 14 de 1 Coríntios trata do uso correto dos dons espirituais na igreja, especialmente o dom de línguas e profecia. Paulo enfatiza que o objetivo principal dos dons é edificar a igreja e exorta os coríntios a buscarem os dons que mais edificam a comunidade. Ele também orienta sobre a importância da compreensão e interpretação dos dons para que todos possam ser edificados.
* 1 Coríntios 12:31b: "Contudo, eu lhes mostrarei o caminho mais excelente." Paulo destaca a importância da busca pelo amor, que é o caminho mais excelente e fundamental para o uso correto dos dons espirituais.
* Romanos 12:6-8: "Temos diferentes dons, de acordo com a graça que nos foi dada. Se alguém tem o dom de profecia, use-o na proporção da sua fé. Se o seu dom é servir, sirva; se é ensinar, ensine; se é dar ânimo, que assim faça; se é contribuir, contribua generosamente; se é liderar, lidere com zelo; se é mostrar misericórdia, que o faça com alegria." Paulo fala sobre a diversidade de dons e habilidades, enfatizando que cada um deve usar o seu dom para o bem da comunidade.
* 1 Coríntios 14:12: "Assim, visto que vocês estão ansiosos por terem dons espirituais, procurem-os com zelo para que possam contribuir com a igreja." Paulo incentiva os coríntios a buscarem os dons que mais edificam a igreja, mas de forma equilibrada e buscando a edificação mútua.
* 1 Coríntios 14:22: "Assim, as línguas são um sinal não para os crentes, mas para os descrentes; a profecia, porém, é para os crentes, não para os descrentes." Paulo destaca a importância da compreensão e interpretação dos dons para que sejam edificantes para todos, especialmente para os descrentes que podem ser impactados pela manifestação dos dons.
* 1 Coríntios 14:26: "Que faremos, pois, irmãos? Quando vocês se reunirem, cada um de vocês tem um salmo, ou uma palavra de ensino, uma revelação, uma palavra em outra língua ou uma interpretação. Tudo seja feito para a edificação da igreja." Paulo enfatiza que o objetivo principal dos dons é edificar a igreja, e que todos devem contribuir de forma equilibrada e visando a edificação mútua.
****

[[v53-14-1]]

^<<v53-14-1,1>>^ Empenhai-vos em procurar a caridade. Aspirai igualmente aos dons espirituais, mas sobretudo ao de profecia.

[[v53-14-2]]

^<<v53-14-2,2>>^ Aquele que fala em línguas não fala aos homens, senão a Deus: ninguém o entende, pois fala coisas misteriosas, sob a ação do Espírito.

[[v53-14-3]]

^<<v53-14-3,3>>^ Aquele, porém, que profetiza fala aos homens, para edificá-los, exortá-los e consolá-los.

[[v53-14-4]]

^<<v53-14-4,4>>^ Aquele que fala em línguas edifica-se a si mesmo; mas o que profetiza, edifica a assembleia.

[[v53-14-5]]

^<<v53-14-5,5>>^ Ora, desejo que todos faleis em línguas, porém muito mais desejo que profetizeis. Maior é quem profetiza do que quem fala em línguas, a não ser que este as interprete, para que a assembleia receba edificação.

[[v53-14-6]]

^<<v53-14-6,6>>^ Suponhamos, irmãos, que eu fosse ter convosco falando em línguas, de que vos aproveitaria, se minha palavra não vos desse revelação, nem ciência, nem profecia ou doutrina?

[[v53-14-7]]

^<<v53-14-7,7>>^ É o que se dá com os instrumentos inanimados de música, por exemplo a flauta ou a harpa: se não produzirem sons distintos, como se poderá reconhecer a música tocada?

[[v53-14-8]]

^<<v53-14-8,8>>^ Se a trombeta só der sons confusos, quem se preparará para a batalha?

[[v53-14-9]]

^<<v53-14-9,9>>^ Assim também vós: se vossa língua só profere palavras ininteligíveis, como se compreenderá o que dizeis? Sereis como quem fala ao vento.

[[v53-14-10]]

^<<v53-14-10,10>>^ Há no mundo grande quantidade de línguas e todas são compreensíveis.

[[v53-14-11]]

^<<v53-14-11,11>>^ Porém, se desconhecer o sentido das palavras, serei um estrangeiro para quem me fala e ele será também um estrangeiro para mim.^&#42;1^

[[v53-14-12]]

^<<v53-14-12,12>>^ Assim, uma vez que aspirais aos dons espirituais, procurai tê-los em abundância para a edificação da Igreja.

[[v53-14-13]]

^<<v53-14-13,13>>^ Por isso, quem fala em línguas, peça na oração o dom de as interpretar.

[[v53-14-14]]

^<<v53-14-14,14>>^ Se eu oro em virtude do dom das línguas, o meu espírito ora, mas o meu entendimento fica sem fruto.^&#42;1^

[[v53-14-15]]

^<<v53-14-15,15>>^ Então, que fazer? Orarei com o espírito, mas orarei também com o entendimento; cantarei com o espírito, mas cantarei também com o entendimento.

[[v53-14-16]]

^<<v53-14-16,16>>^ De outra forma, se só renderes graças com o espírito, como dirá “Amém” a tuas ações de graças aquele que ocupar o lugar dos simples?

[[v53-14-17]]

^<<v53-14-17,17>>^ Sem dúvida, as tuas ações de graças podem ser belas, mas o outro não é edificado.

[[v53-14-18]]

^<<v53-14-18,18>>^ Graças a Deus que possuo o dom de línguas superior a todos vós.

[[v53-14-19]]

^<<v53-14-19,19>>^ Mas prefiro falar na assembleia cinco palavras que compreendo, para instruir também os outros, a falar dez mil palavras em línguas.

[[v53-14-20]]

^<<v53-14-20,20>>^ Irmãos, não sejais crianças quanto ao modo de julgar: na malícia, sim, sede crianças; mas quanto ao julgamento, sede homens.

[[v53-14-21]]

^<<v53-14-21,21>>^ Na Lei está escrito: Será por gente de língua estrangeira e por lábios estrangeiros que falarei a este povo; e nem assim me ouvirão, diz o Senhor (Is 28,11s).

[[v53-14-22]]

^<<v53-14-22,22>>^ Assim, as línguas são sinal, não para os fiéis, mas para os infiéis; enquanto as profecias são um sinal, não para os infiéis, mas para os fiéis.

[[v53-14-23]]

^<<v53-14-23,23>>^ Se, pois, em uma assembleia da igreja inteira todos falarem em línguas, e se entrarem homens simples ou infiéis, não dirão que estais loucos?

[[v53-14-24]]

^<<v53-14-24,24>>^ Se, porém, todos profetizarem, e entrar ali um infiel ou um homem simples, por todos é convencido, por todos é julgado;

[[v53-14-25]]

^<<v53-14-25,25>>^ os segredos do seu coração tornam-se manifestos. Então, prostrado com a face em terra, adorará a Deus e proclamará que Deus está realmente entre vós.

[[v53-14-26]]

^<<v53-14-26,26>>^ Em suma, que dizer, irmãos? Quando vos reunis, quem dentre vós tem um cântico, um ensinamento, uma revelação, um discurso em línguas, uma interpretação a fazer – que isso se faça de modo a edificar.

[[v53-14-27]]

^<<v53-14-27,27>>^ Se há quem fala em línguas, não falem senão dois ou três, quando muito, e cada um por sua vez, e haja alguém que interprete.

[[v53-14-28]]

^<<v53-14-28,28>>^ Se não houver intérprete, fiquem calados na reunião, e falem consigo mesmos e com Deus.

[[v53-14-29]]

^<<v53-14-29,29>>^ Quanto aos profetas, falem dois ou três, e os outros julguem.

[[v53-14-30]]

^<<v53-14-30,30>>^ Se for feita uma revelação a algum dos assistentes, cale-se o primeiro.

[[v53-14-31]]

^<<v53-14-31,31>>^ Todos, um após outro, podeis profetizar, para todos aprenderem e serem todos exortados.

[[v53-14-32]]

^<<v53-14-32,32>>^ O espírito dos profetas deve estar-lhes submisso,

[[v53-14-33]]

^<<v53-14-33,33>>^ porquanto Deus não é Deus de confusão, mas de paz.

[[v53-14-34]]

^<<v53-14-34,34>>^ Como em todas as igrejas dos santos, as mulheres estejam caladas nas assembleias: não lhes é permitido falar, mas devem estar submissas, como também ordena a lei.

[[v53-14-35]]

^<<v53-14-35,35>>^ Se querem aprender alguma coisa, perguntem-na em casa aos seus maridos, porque é inconveniente para uma mulher falar na assembleia.

[[v53-14-36]]

^<<v53-14-36,36>>^ Porventura foi dentre vós que saiu a Palavra de Deus? Ou veio ela tão somente para vós?

[[v53-14-37]]

^<<v53-14-37,37>>^ Se alguém se julga profeta ou agraciado com dons espirituais, reconheça que as coisas que vos escrevo são um mandamento do Senhor.

[[v53-14-38]]

^<<v53-14-38,38>>^ Mas, se alguém quiser ignorá-lo, que o ignore!

[[v53-14-39]]

^<<v53-14-39,39>>^ Assim, pois, irmãos, aspirai ao dom de profetizar; porém, não impeçais falar em línguas.

[[v53-14-40]]

^<<v53-14-40,40>>^ Mas faça-se tudo com dignidade e ordem.

'''

xref:053-i-corintios/053-i-corintios-013.adoc#v53-13-0[&#60; Capítulo Anterior] | <<v53-14-0,Topo>> | xref:053-i-corintios/053-i-corintios-015.adoc#v53-15-0[Próximo Capítulo &#62;]