include::./index.adoc[]

[[v53-1-0]]
=== I Coríntios, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 1 de 1 Coríntios aborda a questão da sabedoria divina versus sabedoria humana. Paulo exorta os coríntios a não se deixarem levar pelas divisões causadas por diferentes líderes religiosos, mas a permanecerem unidos em Cristo. Ele enfatiza que a sabedoria de Deus é loucura para os homens e que a mensagem da cruz é a força de Deus para a salvação daqueles que creem.
* Provérbios 3:5-6: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." Este versículo enfatiza a importância da confiança em Deus e da busca da sabedoria divina em vez de depender da sabedoria humana limitada.
* Jeremias 9:23-24: "Assim diz o Senhor: Não se glorie o sábio na sua sabedoria, nem se glorie o forte na sua força; não se glorie o rico nas suas riquezas. Mas o que se gloriar, glorie-se nisto: em me conhecer e saber que eu sou o Senhor, que faço beneficência, juízo e justiça na terra; porque destas coisas me agrado, diz o Senhor." Este versículo enfatiza a superioridade da sabedoria divina em relação à sabedoria humana e a importância de conhecer a Deus.
* Isaías 29:14: "Eis que continuarei a fazer obra maravilhosa no meio deste povo, obra maravilhosa e um prodígio; pois a sabedoria dos seus sábios perecerá, e a prudência dos seus prudentes se esconderá." Este versículo destaca a futilidade da sabedoria humana em comparação com a sabedoria divina e a capacidade de Deus de fazer coisas maravilhosas.
* Colossenses 2:8: "Tende cuidado, para que ninguém vos faça presa sua por meio de filosofias e vãs sutilezas, segundo a tradição dos homens, segundo os rudimentos do mundo e não segundo Cristo." Este versículo adverte contra a sabedoria humana vã e o perigo de se afastar da verdade de Cristo.
* Tiago 1:5: "E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não o lança em rosto; e ser-lhe-á dada." Este versículo enfatiza a importância da sabedoria divina e a promessa de Deus de conceder sabedoria aos que a pedem.
****

[[v53-1-1]]

^<<v53-1-1,1>>^ Paulo, apóstolo de Jesus Cristo por chamado e vontade de Deus, e o irmão Sóstenes,

[[v53-1-2]]

^<<v53-1-2,2>>^ à igreja de Deus que está em Corinto, aos fiéis santificados em Jesus Cristo, chamados à santidade, juntamente com todos os que, em qualquer lugar que estejam, invocam o nome de nosso Senhor Jesus Cristo, Senhor deles e nosso;

[[v53-1-3]]

^<<v53-1-3,3>>^ a vós, graça e paz da parte de Deus, nosso Pai, e da parte do Senhor Jesus Cristo!

[[v53-1-4]]

^<<v53-1-4,4>>^ Não cesso de agradecer a Deus por vós, pela graça divina que vos foi dada em Jesus Cristo.

[[v53-1-5]]

^<<v53-1-5,5>>^ Nele fostes ricamente contemplados com todos os dons, com os da palavra e os da ciência,

[[v53-1-6]]

^<<v53-1-6,6>>^ tão solidamente foi confirmado em vós o testemunho de Cristo.

[[v53-1-7]]

^<<v53-1-7,7>>^ Assim, enquanto aguardais a manifestação de nosso Senhor Jesus Cristo, não vos falta dom algum.

[[v53-1-8]]

^<<v53-1-8,8>>^ Ele há de vos confirmar até o fim, para que sejais irrepreensíveis no dia de nosso Senhor Jesus Cristo.^&#42;1^

[[v53-1-9]]

^<<v53-1-9,9>>^ Fiel é Deus, por quem fostes chamados à comunhão de seu Filho Jesus Cristo, nosso Senhor.

[[v53-1-10]]

^<<v53-1-10,10>>^ Rogo-vos, irmãos, em nome de nosso Senhor Jesus Cristo, que todos estejais em pleno acordo e que não haja entre vós divisões. Vivei em boa harmonia, no mesmo espírito e no mesmo sentimento.

[[v53-1-11]]

^<<v53-1-11,11>>^ Pois acerca de vós, irmãos meus, fui informado pelos que são da casa de Cloé, que há contendas entre vós.

[[v53-1-12]]

^<<v53-1-12,12>>^ Refiro-me ao fato de entre vós se usar esta linguagem: “Eu sou discípulo de Paulo; eu, de Apolo; eu, de Cefas; eu, de Cristo”.^&#42;1^

[[v53-1-13]]

^<<v53-1-13,13>>^ Então, estaria Cristo dividido? É Paulo quem foi crucificado por vós? É em nome de Paulo que fostes batizados?

[[v53-1-14]]

^<<v53-1-14,14>>^ Graças a Deus, não batizei nenhum de vós, à exceção de Crispo e Gaio.

[[v53-1-15]]

^<<v53-1-15,15>>^ Assim ninguém poderá dizer que fostes batizados em meu nome.

[[v53-1-16]]

^<<v53-1-16,16>>^ (Aliás, batizei também a família de Estéfanas. Além destes, não me consta ter batizado ninguém mais.)

[[v53-1-17]]

^<<v53-1-17,17>>^ Cristo não me enviou para batizar, mas para pregar o Evangelho; e isso sem recorrer à habilidade da arte oratória, para que não se desvirtue a cruz de Cristo.

[[v53-1-18]]

^<<v53-1-18,18>>^ A linguagem da cruz é loucura para os que se perdem, mas, para os que foram salvos, para nós, é uma força divina.

[[v53-1-19]]

^<<v53-1-19,19>>^ Está escrito: Destruirei a sabedoria dos sábios, e anularei a prudência dos prudentes (Is 29,14).

[[v53-1-20]]

^<<v53-1-20,20>>^ Onde está o sábio? Onde o erudito? Onde o argumentador deste mundo? Acaso não declarou Deus por loucura a sabedoria deste mundo?

[[v53-1-21]]

^<<v53-1-21,21>>^ Já que o mundo, com a sua sabedoria, não reconheceu a Deus na sabedoria divina, aprouve a Deus salvar os que creem pela loucura de sua mensagem.^&#42;1^

[[v53-1-22]]

^<<v53-1-22,22>>^ Os judeus pedem milagres, os gregos reclamam a sabedoria;

[[v53-1-23]]

^<<v53-1-23,23>>^ mas nós pregamos Cristo crucificado, escândalo para os judeus e loucura para os pagãos;

[[v53-1-24]]

^<<v53-1-24,24>>^ mas, para os eleitos – quer judeus quer gregos –, força de Deus e sabedoria de Deus.

[[v53-1-25]]

^<<v53-1-25,25>>^ Pois a loucura de Deus é mais sábia do que os homens, e a fraqueza de Deus é mais forte do que os homens.^&#42;1^

[[v53-1-26]]

^<<v53-1-26,26>>^ Vede, irmãos, o vosso grupo de eleitos: não há entre vós muitos sábios, humanamente falando, nem muitos poderosos, nem muitos nobres.^&#42;1^

[[v53-1-27]]

^<<v53-1-27,27>>^ O que é estulto no mundo, Deus o escolheu para confundir os sábios; e o que é fraco no mundo, Deus o escolheu para confundir os fortes;

[[v53-1-28]]

^<<v53-1-28,28>>^ e o que é vil e desprezível no mundo, Deus o escolheu, como também aquelas coisas que nada são, para destruir as que são.

[[v53-1-29]]

^<<v53-1-29,29>>^ Assim, nenhuma criatura se vangloriará diante de Deus.

[[v53-1-30]]

^<<v53-1-30,30>>^ É por sua graça que estais em Jesus Cristo, que, da parte de Deus, se tornou para nós sabedoria, justiça, santificação e redenção,

[[v53-1-31]]

^<<v53-1-31,31>>^ para que, como está escrito: quem se gloria, glorie-se no Senhor (Jr 9,23).^&#42;1^

'''

xref:052-romanos/052-romanos-016.adoc#v52-16-0[&#60; Capítulo Anterior] | <<v53-1-0,Topo>> | xref:053-i-corintios/053-i-corintios-002.adoc#v53-2-0[Próximo Capítulo &#62;]