include::./index.adoc[]

[[v53-6-0]]
=== I Coríntios, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 6 de 1 Coríntios trata sobre a resolução de conflitos entre irmãos na fé e a importância de viver uma vida de santidade. Paulo repreende os coríntios por levarem suas disputas para tribunais seculares e enfatiza que os crentes deveriam ser capazes de resolver seus conflitos entre si. Ele também alerta sobre o perigo da imoralidade sexual, lembrando que o corpo dos crentes é um templo do Espírito Santo e que devem glorificar a Deus em seus corpos.
* Mateus 18:15-17: "Ora, se teu irmão pecar contra ti, vai e repreende-o entre ti e ele só; se ele te ouvir, ganhaste a teu irmão; mas se não te ouvir, leva ainda contigo um ou dois, para que pela boca de duas ou três testemunhas toda palavra seja confirmada. E, se não as escutar, dize-o à igreja; e, se também não escutar a igreja, considera-o como um gentio e publicano." Este versículo trata da resolução de conflitos entre irmãos na fé, um tema abordado no capítulo 6 de 1 Coríntios.
* 1 Tessalonicenses 4:3-5: "Porque esta é a vontade de Deus, a vossa santificação: que vos abstenhais da prostituição; que cada um de vós saiba possuir o seu vaso em santificação e honra, não na paixão da concupiscência, como os gentios que não conhecem a Deus." Este versículo fala sobre a importância da santidade na vida dos crentes, um tema abordado no capítulo 6 de 1 Coríntios.
* 1 Coríntios 10:31: "Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus." Este versículo enfatiza a importância de glorificar a Deus em tudo o que fazemos, incluindo nossas ações físicas.
* 1 Coríntios 7:4: "A mulher não tem poder sobre o seu próprio corpo, mas tem-no o marido; e também da mesma maneira o marido não tem poder sobre o seu próprio corpo, mas tem-no a mulher." Este versículo fala sobre a relação sexual entre marido e mulher, um tema abordado no capítulo 6 de 1 Coríntios.
* Gálatas 5:19-21: "Ora, as obras da carne são manifestas, as quais são: adultério, prostituição, impureza, lascívia, idolatria, feitiçarias, inimizades, porfias, emulações, iras, pelejas, dissensões, heresias, invejas, homicídios, bebedices, glutonarias e coisas semelhantes a estas, acerca das quais vos declaro, como já antes vos disse, que os que cometem tais coisas não herdarão o reino de Deus." Este versículo fala sobre os pecados da carne, incluindo a imoralidade sexual, um tema abordado no capítulo 6 de 1 Coríntios.
****

[[v53-6-1]]

^<<v53-6-1,1>>^ Quando algum de vós tem litígio contra outro, como é que se atreve a pedir justiça perante os injustos, em vez de recorrer aos (irmãos) santos?^&#42;1^

[[v53-6-2]]

^<<v53-6-2,2>>^ Não sabeis que os santos julgarão o mundo? E, se o mundo há de ser julgado por vós, seríeis indignos de julgar os processos de mínima importância?

[[v53-6-3]]

^<<v53-6-3,3>>^ Não sabeis que julgaremos os anjos? Quanto mais as pequenas questões desta vida!

[[v53-6-4]]

^<<v53-6-4,4>>^ No entanto, quando tendes contendas desse gênero, escolheis para juízes pessoas cuja opinião é tida em nada pela Igreja.

[[v53-6-5]]

^<<v53-6-5,5>>^ Digo-o para confusão vossa. Será possível que não há entre vós um homem sábio, nem um sequer que possa julgar entre seus irmãos?

[[v53-6-6]]

^<<v53-6-6,6>>^ Mas um irmão litiga com outro irmão, e isso diante de infiéis!

[[v53-6-7]]

^<<v53-6-7,7>>^ Na verdade, já é um mal para vós o fato de terdes processos uns contra os outros. Por que não preferis sofrer injustiça? Por que não preferis ser espoliados?

[[v53-6-8]]

^<<v53-6-8,8>>^ Não! Vós é que fazeis injustiça, vós é que espoliais – e isso entre irmãos!

[[v53-6-9]]

^<<v53-6-9,9>>^ Acaso não sabeis que os injustos não hão de possuir o Reino de Deus? Não vos enganeis: nem os impuros, nem os idólatras, nem os adúlteros, nem os efeminados, nem os devassos,

[[v53-6-10]]

^<<v53-6-10,10>>^ nem os ladrões, nem os avarentos, nem os bêbados, nem os difamadores, nem os assaltantes hão de possuir o Reino de Deus.

[[v53-6-11]]

^<<v53-6-11,11>>^ Ao menos alguns de vós têm sido isso. Mas fostes lavados, mas fostes santificados, mas fostes justificados, em nome do Senhor Jesus Cristo e pelo Espírito de nosso Deus.

[[v53-6-12]]

^<<v53-6-12,12>>^ Tudo me é permitido, mas nem tudo convém. Tudo me é permitido, mas eu não me deixarei dominar por coisa alguma.

[[v53-6-13]]

^<<v53-6-13,13>>^ Os alimentos são para o estômago e o estômago para os alimentos: Deus destruirá tanto aqueles como este. O corpo, porém, não é para a impureza, mas para o Senhor e o Senhor para o corpo:

[[v53-6-14]]

^<<v53-6-14,14>>^ Deus, que ressuscitou o Senhor, também nos ressuscitará a nós pelo seu poder.

[[v53-6-15]]

^<<v53-6-15,15>>^ Não sabeis que vossos corpos são membros de Cristo? Tomarei, então, os membros de Cristo e os farei membros de uma prostituta? De modo algum!

[[v53-6-16]]

^<<v53-6-16,16>>^ Ou não sabeis que o que se ajunta a uma prostituta se torna um só corpo com ela? Está escrito: Os dois serão uma só carne (Gn 2,24).

[[v53-6-17]]

^<<v53-6-17,17>>^ Pelo contrário, quem se une ao Senhor torna-se com ele um só espírito.

[[v53-6-18]]

^<<v53-6-18,18>>^ Fugi da fornicação. Qualquer outro pecado que o homem comete é fora do corpo, mas o impuro peca contra o seu próprio corpo.

[[v53-6-19]]

^<<v53-6-19,19>>^ Ou não sabeis que o vosso corpo é templo do Espírito Santo, que habita em vós, o qual recebestes de Deus e que, por isso mesmo, já não vos pertenceis?

[[v53-6-20]]

^<<v53-6-20,20>>^ Porque fostes comprados por um grande preço. Glorificai, pois, a Deus no vosso corpo.^&#42;1^

'''

xref:053-i-corintios/053-i-corintios-005.adoc#v53-5-0[&#60; Capítulo Anterior] | <<v53-6-0,Topo>> | xref:053-i-corintios/053-i-corintios-007.adoc#v53-7-0[Próximo Capítulo &#62;]