include::./index.adoc[]

[[v53-13-0]]
=== I Coríntios, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 13 de 1 Coríntios é conhecido como o "hino ao amor" e trata da importância do amor em todas as coisas, especialmente na vida cristã e nas relações entre irmãos na fé. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Romanos 12:9 - "O amor deve ser sincero. Odeiem o mal e apeguem-se ao bem." - O amor genuíno deve ser verdadeiro e sincero, sem hipocrisia ou falsidade. Isso se relaciona com o capítulo 13 de 1 Coríntios, onde Paulo enfatiza a importância do amor verdadeiro e não fingido.
* 1 João 4:8 - "Quem não ama não conhece a Deus, porque Deus é amor." - O amor é uma característica fundamental de Deus, e aqueles que O conhecem e O amam também devem amar uns aos outros. Isso se relaciona com o capítulo 13 de 1 Coríntios, onde Paulo destaca que sem amor, todas as outras coisas perdem seu valor.
* João 15:13 - "Ninguém tem maior amor do que aquele que dá a sua vida pelos seus amigos." - Jesus deu o exemplo supremo de amor ao sacrificar Sua vida pelos pecadores. Isso se relaciona com o capítulo 13 de 1 Coríntios, onde Paulo enfatiza que o amor não busca seus próprios interesses, mas está disposto a se sacrificar pelos outros.
* Gálatas 5:22-23 - "Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio. Contra essas coisas não há lei." - O amor é uma das manifestações do fruto do Espírito Santo na vida dos crentes. Isso se relaciona com o capítulo 13 de 1 Coríntios, onde Paulo destaca que o amor é um dom divino que deve ser buscado e cultivado.
* Efésios 5:2 - "e vivam em amor, como também Cristo nos amou e se entregou por nós como oferta e sacrifício de aroma agradável a Deus." - O amor é um estilo de vida que deve caracterizar a conduta dos crentes. Isso se relaciona com o capítulo 13 de 1 Coríntios, onde Paulo destaca que o amor é a base para todas as ações e atitudes cristãs.
****

[[v53-13-1]]

^<<v53-13-1,1>>^ Ainda que eu falasse as línguas dos homens e dos anjos, se não tiver caridade, sou como o bronze que soa, ou como o címbalo que retine.

[[v53-13-2]]

^<<v53-13-2,2>>^ Mesmo que eu tivesse o dom da profecia, e conhecesse todos os mistérios e toda a ciência; mesmo que tivesse toda a fé, a ponto de transportar montanhas, se não tiver caridade, não sou nada.

[[v53-13-3]]

^<<v53-13-3,3>>^ Ainda que distribuísse todos os meus bens em sustento dos pobres, e ainda que entregasse o meu corpo para ser queimado, se não tiver caridade, de nada valeria!

[[v53-13-4]]

^<<v53-13-4,4>>^ A caridade é paciente, a caridade é bondosa. Não tem inveja. A caridade não é orgulhosa. Não é arrogante.

[[v53-13-5]]

^<<v53-13-5,5>>^ Nem escandalosa. Não busca os seus próprios interesses, não se irrita, não guarda rancor.

[[v53-13-6]]

^<<v53-13-6,6>>^ Não se alegra com a injustiça, mas se rejubila com a verdade.

[[v53-13-7]]

^<<v53-13-7,7>>^ Tudo desculpa, tudo crê, tudo espera, tudo suporta.

[[v53-13-8]]

^<<v53-13-8,8>>^ A caridade jamais acabará. As profecias desaparecerão, o dom das línguas cessará, o dom da ciência findará.

[[v53-13-9]]

^<<v53-13-9,9>>^ A nossa ciência é parcial, a nossa profecia é imperfeita.

[[v53-13-10]]

^<<v53-13-10,10>>^ Quando chegar o que é perfeito, o imperfeito desaparecerá.

[[v53-13-11]]

^<<v53-13-11,11>>^ Quando eu era criança, falava como criança, pensava como criança, raciocinava como criança. Desde que me tornei homem, eliminei as coisas de criança.

[[v53-13-12]]

^<<v53-13-12,12>>^ Hoje vemos como por um espelho, confusamente; mas então veremos face a face. Hoje conheço em parte; mas então conhecerei totalmente, como eu sou conhecido.

[[v53-13-13]]

^<<v53-13-13,13>>^ Por ora subsistem a fé, a esperança e a caridade – as três. Porém, a maior delas é a caridade.

'''

xref:053-i-corintios/053-i-corintios-012.adoc#v53-12-0[&#60; Capítulo Anterior] | <<v53-13-0,Topo>> | xref:053-i-corintios/053-i-corintios-014.adoc#v53-14-0[Próximo Capítulo &#62;]