include::./index.adoc[]

[[v53-4-0]]
=== I Coríntios, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Coríntios 4 aborda o papel dos líderes cristãos na igreja. Paulo enfatiza que eles devem ser fiéis administradores da mensagem de Cristo, e não buscar sua própria glória ou reconhecimento. Ele também adverte os crentes a não julgarem os líderes de forma precipitada, mas sim esperar pelo julgamento de Deus, que é justo e verdadeiro.
* Jeremias 17:10: "Eu, o Senhor, esquadrinho o coração e provo os pensamentos; e isto para dar a cada um segundo os seus caminhos e segundo o fruto das suas ações." Este versículo destaca que somente Deus conhece verdadeiramente o coração humano e julga justamente.
* Mateus 25:23: "Disse-lhe o seu senhor: Muito bem, servo bom e fiel; foste fiel no pouco, sobre o muito te colocarei; entra no gozo do teu senhor." Este versículo enfatiza a importância da fidelidade e do compromisso na administração das coisas de Deus.
* 2 Coríntios 10:18: "Porque não é aprovado quem a si mesmo se louva, mas, sim, aquele a quem o Senhor louva." Este versículo destaca a importância de não buscar a própria glória ou reconhecimento, mas sim ser aprovado por Deus.
* Mateus 7:1-2: "Não julgueis, para que não sejais julgados. Porque com o juízo com que julgais sereis julgados, e com a medida com que medis vos medirão a vós." Este versículo adverte contra o julgamento precipitado e enfatiza que o julgamento justo vem somente de Deus.
* 1 Timóteo 3:1: "Esta é uma palavra fiel: se alguém deseja o episcopado, excelente obra deseja." Este versículo destaca a importância da liderança na igreja, e enfatiza que os líderes devem buscar esse papel com um coração sincero e comprometido com a obra de Deu
****

[[v53-4-1]]

^<<v53-4-1,1>>^ Que os homens nos considerem, pois, como simples operários de Cristo e administradores dos mistérios de Deus.^&#42;1^

[[v53-4-2]]

^<<v53-4-2,2>>^ Ora, o que se exige dos administradores é que sejam fiéis.

[[v53-4-3]]

^<<v53-4-3,3>>^ A mim pouco se me dá ser julgado por vós ou por tribunal humano, pois nem eu me julgo a mim mesmo.

[[v53-4-4]]

^<<v53-4-4,4>>^ De nada me acusa a consciência; contudo, nem por isso sou justificado. Meu juiz é o Senhor.

[[v53-4-5]]

^<<v53-4-5,5>>^ Por isso, não julgueis antes do tempo; esperai que venha o Senhor. Ele porá às claras o que se acha escondido nas trevas. Ele manifestará as intenções dos corações. Então, cada um receberá de Deus o louvor que merece.

[[v53-4-6]]

^<<v53-4-6,6>>^ Se apliquei tudo isso a mim e a Apolo foi por vossa causa, para que, por meio de nós, aprendais a não ultrapassar o que está escrito e para que vos não ensoberbeçais tomando partido a favor de um e com prejuízo de outrem.

[[v53-4-7]]

^<<v53-4-7,7>>^ O que há de superior em ti? Que é que possuis que não tenhas recebido? E, se o recebeste, por que te glorias, como se o não tivesses recebido?

[[v53-4-8]]

^<<v53-4-8,8>>^ Já estais fartos! Já estais ricos! Sem nós, sois reis! Praza a Deus que reineis, de fato, para que também nós reinemos convosco!^&#42;1^

[[v53-4-9]]

^<<v53-4-9,9>>^ Porque, ao que parece, Deus nos tem posto a nós, apóstolos, na última classe dos homens, por assim dizer sentenciados à morte, visto que fomos entregues em espetáculo ao mundo, aos anjos e aos homens.

[[v53-4-10]]

^<<v53-4-10,10>>^ Nós, estultos por causa de Cristo; e vós, sábios em Cristo! Nós, fracos; e vós, fortes! Vós, honrados; e nós, desprezados!

[[v53-4-11]]

^<<v53-4-11,11>>^ Até esta hora padecemos fome, sede e nudez. Somos esbofeteados, somos errantes,

[[v53-4-12]]

^<<v53-4-12,12>>^ fatigamo-nos, trabalhando com as nossas próprias mãos. Insultados, abençoamos; perseguidos, suportamos; caluniados, consolamos!

[[v53-4-13]]

^<<v53-4-13,13>>^ Chegamos a ser como que o lixo do mundo, a escória de todos até agora...

[[v53-4-14]]

^<<v53-4-14,14>>^ Não vos escrevo estas coisas para vos envergonhar, mas admoesto-vos como meus filhos muito amados.

[[v53-4-15]]

^<<v53-4-15,15>>^ Com efeito, ainda que tivésseis dez mil mestres em Cristo, não tendes muitos pais; ora, fui eu que vos gerei em Cristo Jesus pelo Evangelho.

[[v53-4-16]]

^<<v53-4-16,16>>^ Por isso, vos conjuro a que sejais meus imitadores.

[[v53-4-17]]

^<<v53-4-17,17>>^ Para isso é que vos enviei Timóteo, meu filho muito amado e fiel no Senhor. Ele vos recordará as minhas normas de conduta, tais como as ensino por toda parte, em todas as igrejas.

[[v53-4-18]]

^<<v53-4-18,18>>^ Alguns, presumindo que eu não mais iria ter convosco, encheram-se de orgulho.

[[v53-4-19]]

^<<v53-4-19,19>>^ Mas brevemente irei ter convosco, se Deus quiser, e tomarei conhecimento não do que esses orgulhosos falam, mas do que são capazes.

[[v53-4-20]]

^<<v53-4-20,20>>^ Porque o Reino de Deus não consiste em palavras, mas em atos.

[[v53-4-21]]

^<<v53-4-21,21>>^ Que preferis? Que eu vá visitar-vos com a vara, ou com caridade e espírito de mansidão?

'''

xref:053-i-corintios/053-i-corintios-003.adoc#v53-3-0[&#60; Capítulo Anterior] | <<v53-4-0,Topo>> | xref:053-i-corintios/053-i-corintios-005.adoc#v53-5-0[Próximo Capítulo &#62;]