include::./index.adoc[]

[[v66-4-0]]
=== São Tiago, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 4 de Tiago aborda principalmente o tema da humildade e submissão a Deus, alertando contra a arrogância e a busca pelo prazer mundano. O capítulo também aborda a importância de buscar a vontade de Deus e resistir ao diabo. Seguem abaixo cinco versículos relacionados com os temas abordados em Tiago 4:
* Provérbios 3:34: "Ele zomba dos zombadores, mas concede graça aos humildes". Este versículo fala sobre a importância da humildade e como Deus concede graça aos humildes, mas resiste aos arrogantes.
* 1 Pedro 5:5: "Semelhantemente, jovens, sujeitem-se aos mais velhos. Sejam todos humildes uns para com os outros, porque 'Deus se opõe aos orgulhosos, mas concede graça aos humildes'". Este versículo reforça a importância da humildade e submissão a Deus, citando uma passagem semelhante àquela citada por Tiago em seu capítulo.
* 1 João 2:15-17: "Não amem o mundo nem o que nele há. Se alguém ama o mundo, o amor do Pai não está nele. Pois tudo o que há no mundo — a cobiça da carne, a cobiça dos olhos e a ostentação dos bens — não provém do Pai, mas do mundo. O mundo e a sua cobiça passam, mas aquele que faz a vontade de Deus permanece para sempre". Este versículo alerta sobre a busca pelo prazer mundano e a importância de buscar a vontade de Deus.
* Efésios 4:27: "e não dêem lugar ao Diabo". Este versículo fala sobre a importância de resistir ao diabo, alertando que ele pode encontrar uma brecha se não nos mantivermos firmes em Deus.
* 1 Pedro 5:8: "Sejam sóbrios e vigiem. O Diabo, o inimigo de vocês, anda ao redor como leão, rugindo e procurando a quem possa devorar". Este versículo reforça a importância de estar alerta contra as tentações do diabo, citando uma passagem semelhante àquela citada por Tiago em seu capítulo.
****

[[v66-4-1]]

^<<v66-4-1,1>>^ Donde vêm as lutas e as contendas entre vós? Não vêm elas de vossas paixões, que combatem em vossos membros?

[[v66-4-2]]

^<<v66-4-2,2>>^ Cobiçais, e não recebeis; sois invejosos e ciumentos, e não conseguis o que desejais; litigais e fazeis guerra. Não obtendes, porque não pedis.^&#42;1^

[[v66-4-3]]

^<<v66-4-3,3>>^ Pedis e não recebeis, porque pedis mal, com o fim de satisfazerdes as vossas paixões.

[[v66-4-4]]

^<<v66-4-4,4>>^ Adúlteros, não sabeis que o amor do mundo é abominado por Deus? Todo aquele que quer ser amigo do mundo constitui-se inimigo de Deus.

[[v66-4-5]]

^<<v66-4-5,5>>^ Ou imaginais que em vão diz a Escritura: Sois amados até o ciúme pelo espírito que habita em vós?

[[v66-4-6]]

^<<v66-4-6,6>>^ Deus, porém, dá uma graça ainda mais abundante. Por isso, ele diz: Deus resiste aos soberbos, mas dá sua graça aos humildes (Pr 3,34).

[[v66-4-7]]

^<<v66-4-7,7>>^ Sede submissos a Deus. Resisti ao demônio, e ele fugirá para longe de vós.

[[v66-4-8]]

^<<v66-4-8,8>>^ Aproximai-vos de Deus, e ele se aproximará de vós. Lavai as mãos, pecadores, e purificai os vossos corações, ó homens de dupla atitude.

[[v66-4-9]]

^<<v66-4-9,9>>^ Reconhecei a vossa miséria, afligi-vos e chorai. Converta-se o vosso riso em pranto e a vossa alegria em tristeza.

[[v66-4-10]]

^<<v66-4-10,10>>^ Humilhai-vos na presença do Senhor, e ele vos exaltará.

[[v66-4-11]]

^<<v66-4-11,11>>^ Meus irmãos, não faleis mal uns dos outros. Quem fala mal de seu irmão, ou o julga, fala mal da Lei e julga a Lei. E se julgas a Lei, já não és observador da Lei, mas seu juiz.

[[v66-4-12]]

^<<v66-4-12,12>>^ Não há mais que um legislador e um juiz: aquele que pode salvar e perder. Mas quem és tu, que julgas o teu próximo?

[[v66-4-13]]

^<<v66-4-13,13>>^ Agora dizeis: “Hoje ou amanhã iremos à tal cidade, ficaremos ali um ano, comerciaremos e tiraremos o nosso lucro”.

[[v66-4-14]]

^<<v66-4-14,14>>^ E, entretanto, não sabeis o que acontecerá amanhã! Pois que é a vossa vida? Sois um vapor que aparece por um instante e depois se desvanece.

[[v66-4-15]]

^<<v66-4-15,15>>^ Em vez de dizerdes: “Se Deus quiser, viveremos e faremos esta ou aquela coisa”.

[[v66-4-16]]

^<<v66-4-16,16>>^ Mas agora vós vos jactais das vossas presunções. Toda jactância desse gênero é viciosa.

[[v66-4-17]]

^<<v66-4-17,17>>^ Aquele que souber fazer o bem, e não o faz, peca.

'''

xref:066-sao-tiago/066-sao-tiago-003.adoc#v66-3-0[&#60; Capítulo Anterior] | <<v66-4-0,Topo>> | xref:066-sao-tiago/066-sao-tiago-005.adoc#v66-5-0[Próximo Capítulo &#62;]