include::./index.adoc[]

[[v69-2-0]]
=== I São João, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 2 de 1 São João fala sobre a importância de obedecer aos mandamentos de Deus e seguir o exemplo de Jesus. Além disso, o autor adverte sobre a presença de falsos professores e ensina sobre o amor fraterno entre os irmãos na fé. Seguem abaixo cinco versículos relacionados com esses temas:
* Provérbios 19:16: "O que guarda o mandamento guarda a sua alma; mas o que despreza os seus caminhos morrerá." Este versículo enfatiza a importância de obedecer aos mandamentos de Deus, que trazem vida e proteção para aqueles que os seguem.
* João 15:10: "Se guardardes os meus mandamentos, permanecereis no meu amor; do mesmo modo que eu tenho guardado os mandamentos de meu Pai e permaneço no seu amor." Jesus é o exemplo máximo de obediência aos mandamentos de Deus, e ao segui-lo, também permanecemos no amor de Deus.
* Mateus 7:15: "Acautelai-vos dos falsos profetas, que se vos apresentam disfarçados em ovelhas, mas por dentro são lobos roubadores." Assim como 1 São João 2 adverte sobre a presença de falsos professores, este versículo de Mateus alerta sobre a necessidade de discernir os ensinamentos de quem se apresenta como líder religioso.
* Romanos 13:8: "Não devais a ninguém coisa alguma, a não ser o amor com que vos ameis uns aos outros; pois quem ama ao próximo cumpriu a lei." A prática do amor fraterno é uma das principais mensagens de 1 São João 2, e este versículo de Romanos enfatiza que amar ao próximo é cumprir a lei de Deus.
* Efésios 2:10: "Porque somos feitura sua, criados em Cristo Jesus para boas obras, as quais Deus de antemão preparou para que andássemos nelas." Assim como 1 São João 2 destaca a importância de seguir o exemplo de Jesus, este versículo de Efésios ensina que fomos criados em Cristo para realizar boas obras que foram preparadas por Deus para nós.
****

[[v69-2-1]]

^<<v69-2-1,1>>^ Filhinhos meus, isto vos escrevo para que não pequeis. Mas, se alguém pecar, temos um intercessor junto ao Pai, Jesus Cristo, o Justo.

[[v69-2-2]]

^<<v69-2-2,2>>^ Ele é a expiação pelos nossos pecados, e não somente pelos nossos, mas também pelos de todo o mundo.

[[v69-2-3]]

^<<v69-2-3,3>>^ Eis como sabemos que o conhecemos: se guardamos os seus mandamentos.

[[v69-2-4]]

^<<v69-2-4,4>>^ Aquele que diz conhecê-lo e não guarda os seus mandamentos é mentiroso e a verdade não está nele.

[[v69-2-5]]

^<<v69-2-5,5>>^ Aquele, porém, que guarda a sua palavra, nele o amor de Deus é verdadeiramente perfeito. É assim que conhecemos se estamos nele:

[[v69-2-6]]

^<<v69-2-6,6>>^ aquele que afirma permanecer nele deve também viver como ele viveu.

[[v69-2-7]]

^<<v69-2-7,7>>^ Caríssimos, não vos escrevo nenhum mandamento novo, mas sim o mandamento antigo, que recebestes desde o princípio. Esse mandamento antigo é a palavra que acabais de ouvir.

[[v69-2-8]]

^<<v69-2-8,8>>^ Todavia, eu vos escrevo agora um mandamento novo – verdadeiramente novo, nele como em vós, porque as trevas passam e já resplandece a verdadeira luz.

[[v69-2-9]]

^<<v69-2-9,9>>^ Aquele que diz estar na luz, e odeia seu irmão, jaz ainda nas trevas.

[[v69-2-10]]

^<<v69-2-10,10>>^ Quem ama seu irmão permanece na luz e não se expõe a tropeçar.^&#42;1^

[[v69-2-11]]

^<<v69-2-11,11>>^ Mas quem odeia seu irmão está nas trevas e anda nas trevas, sem saber para onde dirige os passos; as trevas cegaram seus olhos.

[[v69-2-12]]

^<<v69-2-12,12>>^ Filhinhos, eu vos escrevo, porque vossos pecados vos foram perdoados pelo seu nome.

[[v69-2-13]]

^<<v69-2-13,13>>^ Pais, eu vos escrevo, porque conheceis aquele que existe desde o princípio. Jovens, eu vos escrevo, porque vencestes o Maligno.

[[v69-2-14]]

^<<v69-2-14,14>>^ Crianças, eu vos escrevo, porque conheceis o Pai. Pais, eu vos escrevi, porque conheceis aquele que existe desde o princípio. Jovens, eu vos escrevi, porque sois fortes e a Palavra de Deus permanece em vós, e vencestes o Maligno.

[[v69-2-15]]

^<<v69-2-15,15>>^ Não ameis o mundo nem as coisas do mundo. Se alguém ama o mundo, não está nele o amor do Pai.

[[v69-2-16]]

^<<v69-2-16,16>>^ Porque tudo o que há no mundo – a concupiscência da carne, a concupiscência dos olhos e a soberba da vida – não procede do Pai, mas do mundo.^&#42;1^

[[v69-2-17]]

^<<v69-2-17,17>>^ O mundo passa com as suas concupiscências, mas quem cumpre a vontade de Deus permanece eternamente.

[[v69-2-18]]

^<<v69-2-18,18>>^ Filhinhos, esta é a última hora. Vós ouvistes dizer que o Anticristo vem. Eis que já há muitos anticristos, por isso conhecemos que é a última hora.

[[v69-2-19]]

^<<v69-2-19,19>>^ Eles saíram dentre nós, mas não eram dos nossos. Se tivessem sido dos nossos, ficariam certamente conosco. Mas isso se dá para que se conheça que nem todos são dos nossos.

[[v69-2-20]]

^<<v69-2-20,20>>^ Vós, porém, tendes a unção do Santo e sabeis todas as coisas.^&#42;1^

[[v69-2-21]]

^<<v69-2-21,21>>^ Não vos escrevi como se ignorásseis a verdade, mas porque a conheceis, e porque nenhuma mentira vem da verdade.

[[v69-2-22]]

^<<v69-2-22,22>>^ Quem é mentiroso senão aquele que nega que Jesus é o Cristo? Esse é o Anticristo, que nega o Pai e o Filho.

[[v69-2-23]]

^<<v69-2-23,23>>^ Todo aquele que nega o Filho não tem o Pai. Todo aquele que proclama o Filho tem também o Pai.^&#42;1^

[[v69-2-24]]

^<<v69-2-24,24>>^ Que permaneça em vós o que tendes ouvido desde o princípio. Se permanecer em vós o que ouvistes desde o princípio, permanecereis também vós no Filho e no Pai.

[[v69-2-25]]

^<<v69-2-25,25>>^ Eis a promessa que ele nos fez: a vida eterna.

[[v69-2-26]]

^<<v69-2-26,26>>^ Era isso o que eu vos tinha a escrever a respeito dos que vos seduzem.

[[v69-2-27]]

^<<v69-2-27,27>>^ Quanto a vós, a unção que dele recebestes permanece em vós. E não tendes necessidade de que alguém vos ensine; mas, como a sua unção vos ensina todas as coisas, assim é ela verdadeira e não mentira. Permanecei nele, como ela vos ensinou.^&#42;1^

[[v69-2-28]]

^<<v69-2-28,28>>^ E agora, filhinhos, permanecei nele, para que, quando aparecer, tenhamos confiança e não sejamos confundidos por ele, na sua vinda.

[[v69-2-29]]

^<<v69-2-29,29>>^ Se sabeis que ele é justo, sabei também que todo aquele que pratica a justiça é nascido dele.

'''

xref:069-i-sao-joao/069-i-sao-joao-001.adoc#v69-1-0[&#60; Capítulo Anterior] | <<v69-2-0,Topo>> | xref:069-i-sao-joao/069-i-sao-joao-003.adoc#v69-3-0[Próximo Capítulo &#62;]