include::./index.adoc[]

[[v69-3-0]]
=== I São João, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 São João 3 trata da filiação divina, do amor fraternal e da prática do pecado. O capítulo começa destacando o amor do Pai por nós, que somos chamados de filhos de Deus. Em seguida, o autor enfatiza que aquele que pratica o pecado é filho do diabo, pois o diabo peca desde o princípio. Ele também destaca a importância de amar ao próximo e mostra que esse amor é um sinal de que pertencemos a Deus. Por fim, o capítulo fala sobre a prática da justiça e como isso é evidência de que somos nascidos de Deus.
* Romanos 8:16: "O próprio Espírito testemunha ao nosso espírito que somos filhos de Deus." Esse versículo destaca a ideia de filiação divina mencionada em 1 São João 3. O autor de Romanos fala que o Espírito Santo testifica que somos filhos de Deus e, assim, podemos clamar a ele como "Abba, Pai".
* 1 Coríntios 15:33: "Não se deixem enganar: as más companhias corrompem os bons costumes." Esse versículo tem relação com o trecho em que o autor de 1 São João 3 enfatiza a importância de amar ao próximo. As más companhias podem levar uma pessoa a praticar o pecado, enquanto o amor ao próximo deve levá-la a fazer o bem.
* Hebreus 2:14-15: "Visto que os filhos têm em comum a carne e o sangue, também ele participou dessas coisas, para que pela sua morte derrotasse aquele que tem o poder da morte, isto é, o diabo, e libertasse aqueles que durante toda a vida estiveram escravizados pelo medo da morte." Esse versículo fala sobre a derrota do diabo, mencionado em 1 São João 3 como aquele que peca desde o princípio. A morte de Jesus na cruz liberta as pessoas do poder do diabo e do medo da morte.
* Tiago 2:14-17: "De que adianta, meus irmãos, alguém dizer que tem fé, se não tem obras? Acaso a fé pode salvá-lo? Se um irmão ou irmã estiver necessitando de roupas e do alimento de cada dia e um de vocês lhe disser: 'Vá em paz, aqueça-se e alimente-se até satisfazer-se', sem porém lhe dar nada, de que adianta isso? Assim também a fé, por si só, se não for acompanhada de obras, está morta." Esse versículo tem relação com a ideia de que a prática da justiça é evidência de que somos nascidos de Deus, mencionada em 1 São João 3. Tiago enfatiza que a fé sem obras está morta, ou seja, a fé deve ser acompanhada de ações que demonstrem o amor ao próximo.
****

[[v69-3-1]]

^<<v69-3-1,1>>^ Considerai com que amor nos amou o Pai, para que sejamos chamados filhos de Deus. E nós o somos de fato. Por isso, o mundo não nos conhece, porque não o conheceu.

[[v69-3-2]]

^<<v69-3-2,2>>^ Caríssimos, desde agora somos filhos de Deus, mas não se manifestou ainda o que havemos de ser. Sabemos que, quando isso se manifestar, seremos semelhantes a Deus, porquanto o veremos como ele é.^&#42;1^

[[v69-3-3]]

^<<v69-3-3,3>>^ E todo aquele que nele tem essa esperança torna-se puro, como ele é puro.

[[v69-3-4]]

^<<v69-3-4,4>>^ Todo aquele que peca transgride a Lei, porque o pecado é transgressão da Lei.

[[v69-3-5]]

^<<v69-3-5,5>>^ Sabeis que (Jesus) apareceu para tirar os pecados, e que nele não há pecado.

[[v69-3-6]]

^<<v69-3-6,6>>^ Todo aquele que permanece nele não peca; e todo o que peca não o viu, nem o conheceu.

[[v69-3-7]]

^<<v69-3-7,7>>^ Filhinhos, ninguém vos seduza: aquele que pratica a justiça é justo, como também (Jesus) é justo.

[[v69-3-8]]

^<<v69-3-8,8>>^ Aquele que peca é do demônio, porque o demônio peca desde o princípio. Eis por que o Filho de Deus se manifestou: para destruir as obras do demônio.

[[v69-3-9]]

^<<v69-3-9,9>>^ Todo o que é nascido de Deus não peca, porque o germe divino reside nele; e não pode pecar, porque nasceu de Deus.^&#42;1^

[[v69-3-10]]

^<<v69-3-10,10>>^ É nisso que se conhece quais são os filhos de Deus e quais os do demônio: todo o que não pratica a justiça não é de Deus, como também aquele que não ama o seu irmão.

[[v69-3-11]]

^<<v69-3-11,11>>^ Pois esta é a mensagem que tendes ouvido desde o princípio: que nos amemos uns aos outros.

[[v69-3-12]]

^<<v69-3-12,12>>^ Não façamos como Caim, que era do Maligno e matou seu irmão. E por que o matou? Porque as suas obras eram más, e as do seu irmão, justas.

[[v69-3-13]]

^<<v69-3-13,13>>^ Não vos admireis, irmãos, se o mundo vos odeia.

[[v69-3-14]]

^<<v69-3-14,14>>^ Nós sabemos que fomos trasladados da morte para a vida, porque amamos nossos irmãos. Quem não ama permanece na morte.

[[v69-3-15]]

^<<v69-3-15,15>>^ Quem odeia seu irmão é assassino. E sabeis que a vida eterna não permanece em nenhum assassino.

[[v69-3-16]]

^<<v69-3-16,16>>^ Nisto temos conhecido o amor: (Jesus) deu sua vida por nós. Também nós outros devemos dar a nossa vida pelos nossos irmãos.

[[v69-3-17]]

^<<v69-3-17,17>>^ Quem possuir bens deste mundo e vir o seu irmão sofrer necessidade, mas lhe fechar o seu coração, como pode estar nele o amor de Deus?

[[v69-3-18]]

^<<v69-3-18,18>>^ Meus filhinhos, não amemos com palavras nem com a língua, mas por atos e em verdade.

[[v69-3-19]]

^<<v69-3-19,19>>^ Nisso é que conheceremos se somos da verdade, e tranquilizaremos a nossa consciência diante de Deus,^&#42;1^

[[v69-3-20]]

^<<v69-3-20,20>>^ caso nossa consciência nos censure, pois Deus é maior do que nossa consciência e conhece todas as coisas.

[[v69-3-21]]

^<<v69-3-21,21>>^ Caríssimos, se a nossa consciência nada nos censura, temos confiança diante de Deus,

[[v69-3-22]]

^<<v69-3-22,22>>^ e tudo o que lhe pedirmos, receberemos dele porque guardamos os seus mandamentos e fazemos o que é agradável a seus olhos.

[[v69-3-23]]

^<<v69-3-23,23>>^ Eis o seu mandamento: que creiamos no nome do seu Filho Jesus Cristo, e nos amemos uns aos outros, como ele nos mandou.

[[v69-3-24]]

^<<v69-3-24,24>>^ Quem observa os seus mandamentos permanece em (Deus) e (Deus) nele. É nisto que reconhecemos que ele permanece em nós: pelo Espírito que nos deu.

'''

xref:069-i-sao-joao/069-i-sao-joao-002.adoc#v69-2-0[&#60; Capítulo Anterior] | <<v69-3-0,Topo>> | xref:069-i-sao-joao/069-i-sao-joao-004.adoc#v69-4-0[Próximo Capítulo &#62;]