include::./index.adoc[]

[[v40-7-0]]
=== Miquéias, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 7 de Miquéias trata da corrupção do povo de Israel e da esperança de redenção através da misericórdia de Deus. Miquéias clama por justiça, apontando a hipocrisia e a desonestidade daqueles em posições de poder. Ele então se volta para Deus, confiando em Sua bondade e promessa de perdão e restauração. Seguem abaixo cinco versículos relacionados com os temas do capítulo:
* Isaías 1:18: "Vinde, pois, e arrazoemos, diz o Senhor: ainda que os vossos pecados sejam como a escarlata, eles se tornarão brancos como a neve; ainda que sejam vermelhos como o carmesim, se tornarão como a branca lã." Este versículo fala da promessa de perdão e limpeza que Deus oferece a Seu povo, mesmo que seus pecados sejam graves.
* Salmo 103:8-10: "O Senhor é misericordioso e compassivo, paciente e cheio de amor. Não acusa sem cessar nem fica ressentido para sempre; não nos trata conforme os nossos pecados nem nos retribui conforme as nossas iniquidades." Este Salmo descreve a bondade e a misericórdia de Deus, que não nos trata como merecemos, mas oferece perdão e amor.
* Provérbios 28:13: "O que encobre as suas transgressões jamais prosperará, mas o que as confessa e deixa alcançará misericórdia." Este versículo fala da importância de confessar nossos pecados e buscar perdão, ao invés de tentar escondê-los ou justificá-los.
* Jeremias 31:34: "Ninguém mais ensinará ao seu próximo, nem o seu irmão, dizendo: ‘Conheça ao Senhor’, porque todos eles me conhecerão, desde o menor até o maior", diz o Senhor. Pois perdoarei a maldade deles e não me lembrarei mais dos seus pecados." Este versículo fala da promessa de Deus de perdoar e esquecer nossos pecados, tornando-nos verdadeiramente Seu povo.
* Efésios 2:8-9: "Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus. Não vem das obras, para que ninguém se glorie." Este versículo fala da salvação pela graça de Deus, não pelas nossas próprias obras ou méritos. Isso nos lembra que a redenção e o perdão são presentes de Deus para Seu povo, não algo que podemos ganhar ou merecer.
****

[[v40-7-1]]

^<<v40-7-1,1>>^ Ai de mim! Porque sou como quem restolha frutos no verão, como quem respiga depois da vindima: não há sequer um cacho para comer, nenhum desses figos temporões de que tanto gostaria!

[[v40-7-2]]

^<<v40-7-2,2>>^ Desapareceram os homens piedosos da terra, não há quem seja íntegro entre os homens. Todos andam à espreita para derramar sangue, cada um arma laços ao seu irmão.

[[v40-7-3]]

^<<v40-7-3,3>>^ Suas mãos estão prontas para o mal: o príncipe exige um presente, o juiz cobra as suas sentenças, o grande manifesta abertamente suas cobiças, todos tramam suas intrigas.

[[v40-7-4]]

^<<v40-7-4,4>>^ O melhor dentre eles é como um silvedo, o mais íntegro, como uma sebe de espinhos. No dia anunciado por teus vigias, vem o castigo: eles serão completamente destruídos.

[[v40-7-5]]

^<<v40-7-5,5>>^ Não confies em colega, não contes com amigos, nem mesmo com quem dorme contigo. Guarda-te de abrir a boca!

[[v40-7-6]]

^<<v40-7-6,6>>^ Porque o filho trata seu pai de louco, a filha levanta-se contra sua mãe, a nora contra sua sogra; e os inimigos são os da própria casa.

[[v40-7-7]]

^<<v40-7-7,7>>^ Eu, porém, volto meus olhos para o Senhor, ponho minha esperança no Deus de minha salvação; meu Deus me ouvirá.

[[v40-7-8]]

^<<v40-7-8,8>>^ Não te alegres a meu respeito, inimiga minha; se estou caída, eu me levantarei; se estou sentada nas trevas, o Senhor será minha luz.

[[v40-7-9]]

^<<v40-7-9,9>>^ Suportarei a cólera do Senhor, porque tenho pecado contra ele, até que ele tome em suas mãos a minha causa e deponha em meu favor; até que me conduza para a luz e que eu contemple a sua justiça.^&#42;1^

[[v40-7-10]]

^<<v40-7-10,10>>^ Minha inimiga verá isso e ficará coberta de vergonha, ela que me dizia: “Onde está o Senhor, teu Deus?”. Meus olhos a contemplarão, quando for pisada aos pés como a lama das ruas.^&#42;1^

[[v40-7-11]]

^<<v40-7-11,11>>^ Aproxima-se o dia em que se reconstruirão os teus muros, aquele dia em que se ampliarão tuas fronteiras.

[[v40-7-12]]

^<<v40-7-12,12>>^ Nesse dia virão a ti da Assíria e das cidades do Egito, desde o Egito até o rio, de um mar a outro, de uma montanha a outra.^&#42;1^

[[v40-7-13]]

^<<v40-7-13,13>>^ A terra se tornará um deserto, por causa de seus habitantes: tal será o fruto de suas obras.

[[v40-7-14]]

^<<v40-7-14,14>>^ Conduzi com o cajado o vosso povo, o rebanho de vossa herança que se encontra espalhado pelas brenhas, para o meio de vergéis; que ele paste como outrora em Basã e em Galaad.^&#42;1^

[[v40-7-15]]

^<<v40-7-15,15>>^ Como nos dias em que saístes do Egito, fazei-nos ver prodígios.

[[v40-7-16]]

^<<v40-7-16,16>>^ As nações os verão e sentirão vergonha de sua própria bravura; porão a mão na boca e seus ouvidos ficarão surdos;

[[v40-7-17]]

^<<v40-7-17,17>>^ lamberão o pó como as serpentes, como os répteis da terra. Tremendo, sairão de seus retiros, e virão amedrontadas para o Senhor, nosso Deus; e elas vos temerão.

[[v40-7-18]]

^<<v40-7-18,18>>^ Qual é o Deus que, como vós, apaga a iniquidade e perdoa o pecado do resto de seu povo, que não se ira para sempre porque prefere a misericórdia?

[[v40-7-19]]

^<<v40-7-19,19>>^ Uma vez mais, tende piedade de nós! Esquecei as nossas faltas e jogai nossos pecados nas profundezas do mar!

[[v40-7-20]]

^<<v40-7-20,20>>^ Mostrai a vossa fidelidade para com Jacó, e vossa piedade para com Abraão, como jurastes a nossos pais desde os tempos antigos!

'''

xref:040-miqueias/040-miqueias-006.adoc#v40-6-0[&#60; Capítulo Anterior] | <<v40-7-0,Topo>> | xref:041-naum/041-naum-001.adoc#v41-1-0[Próximo Capítulo &#62;]