include::./index.adoc[]

[[v70-1-0]]
=== II São João, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 São João 1 é uma carta escrita por João dirigida a uma comunidade cristã específica, na qual ele adverte sobre falsos professores e pede que eles continuem seguindo os ensinamentos de Jesus Cristo. Seguem abaixo cinco versículos de outros livros da Bíblia relacionados com os temas abordados nessa carta:
* 1 João 4:1 - "Amados, não creiais a todo espírito, mas provai se os espíritos vêm de Deus, porque muitos falsos profetas têm saído pelo mundo." João também alerta para a presença de falsos profetas e a importância de discernir entre o que vem de Deus e o que não vem.
* Mateus 24:24 - "Porque se levantarão falsos cristos e falsos profetas, e farão tão grandes sinais e prodígios, que, se possível fora, enganariam até os escolhidos." Jesus Cristo também prevê a presença de falsos profetas e a capacidade deles de enganar muitos.
* 2 Pedro 2:1 - "E também houve entre o povo falsos profetas, como entre vós haverá também falsos doutores que introduzirão encobertamente heresias de perdição, e negarão o Senhor que os resgatou, trazendo sobre si mesmos repentina perdição." Pedro também alerta sobre falsos doutores e suas heresias.
* João 8:31-32 - "Disse, pois, Jesus aos judeus que haviam crido nele: Se vós permanecerdes na minha palavra, verdadeiramente sereis meus discípulos; e conhecereis a verdade, e a verdade vos libertará." João destaca a importância de permanecer nos ensinamentos de Jesus Cristo para conhecer a verdade.
* 1 João 2:24 - "Portanto, o que desde o princípio ouvistes permaneça em vós. Se em vós permanecer o que desde o princípio ouvistes, também permanecereis no Filho e no Pai." João reforça a ideia de permanecer nos ensinamentos de Jesus Cristo e do Pai.
****

[[v70-1-1]]

^<<v70-1-1,1>>^ O ancião à Senhora eleita e a seus filhos, que amo na verdade. Não somente eu, mas também todos os que conheceram a verdade,

[[v70-1-2]]

^<<v70-1-2,2>>^ por causa da verdade que permanece em nós e que ficará conosco eternamente.

[[v70-1-3]]

^<<v70-1-3,3>>^ Estejam convosco, na verdade e no amor: graça, misericórdia e paz da parte de Deus Pai e de Jesus Cristo, Filho do Pai.

[[v70-1-4]]

^<<v70-1-4,4>>^ Muito me alegrei por ter achado entre teus filhos alguns que andam na verdade, conforme o mandamento que temos recebido do Pai.

[[v70-1-5]]

^<<v70-1-5,5>>^ E agora rogo-te, Senhora, não como quem te escreve um novo mandamento, mas sim o que tivemos desde o princípio: que nos amemos uns aos outros.

[[v70-1-6]]

^<<v70-1-6,6>>^ Nisto consiste o amor: que vivamos segundo seus mandamentos. É esse o mandamento que tendes ouvido desde o princípio, e segundo o qual deveis viver.

[[v70-1-7]]

^<<v70-1-7,7>>^ Muitos sedutores têm saído pelo mundo afora, os quais não proclamam Jesus Cristo que se encarnou. Quem assim proclama é o sedutor e o Anticristo.

[[v70-1-8]]

^<<v70-1-8,8>>^ Acautelai-vos, para que não percais o fruto de nosso trabalho, mas antes possais receber plena recompensa.^&#42;1^

[[v70-1-9]]

^<<v70-1-9,9>>^ Todo aquele que caminha sem rumo e não permanece na doutrina de Cristo não tem Deus. Quem permanece na doutrina, este possui o Pai e o Filho.^&#42;1^

[[v70-1-10]]

^<<v70-1-10,10>>^ Se alguém vier a vós sem trazer essa doutrina, não o recebais em vossa casa, nem o saudeis.

[[v70-1-11]]

^<<v70-1-11,11>>^ Porque quem o saúda toma parte em suas obras más.

[[v70-1-12]]

^<<v70-1-12,12>>^ Apesar de ter mais coisas que vos escrever, não o quis fazer com papel e tinta, mas espero estar entre vós e conversar de viva voz, para que a vossa alegria seja perfeita.

[[v70-1-13]]

^<<v70-1-13,13>>^ Saúdam-te os filhos de tua irmã, a escolhida.

'''

xref:069-i-sao-joao/069-i-sao-joao-005.adoc#v69-5-0[&#60; Capítulo Anterior] | <<v70-1-0,Topo>> | xref:071-iii-sao-joao/071-iii-sao-joao-001.adoc#v71-1-0[Próximo Capítulo &#62;]