include::./index.adoc[]

[[v59-5-0]]
=== I Tessalonicenses, 5
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Tessalonicenses 5 é um capítulo que trata sobre a vinda do Senhor Jesus e o dia do Senhor. Ele encoraja os crentes a se manterem vigilantes e preparados para esse dia, exortando-os a viverem em santidade e amor uns pelos outros. Abaixo estão cinco versículos relacionados com esses temas:
* Mateus 24:42: "Vigiai, pois, porque não sabeis em que dia vem o vosso Senhor." Jesus exorta seus seguidores a permanecerem vigilantes e prontos para sua vinda.
* 2 Pedro 3:10: "Virá, pois, como ladrão o dia do Senhor, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se dissolverão, e a terra, e as obras que nela há, serão descobertas." Pedro descreve a vinda do Senhor como um evento repentino e impactante, e adverte os cristãos a se prepararem para esse dia.
* 1 João 2:28: "E agora, filhinhos, permanecei nele, para que, quando ele se manifestar, tenhamos confiança e não sejamos confundidos por ele na sua vinda." João encoraja os crentes a permanecerem em Cristo, a fim de terem confiança e não serem confundidos em sua vinda.
* 1 Tessalonicenses 4:3: "Porque esta é a vontade de Deus, a vossa santificação; que vos abstenhais da prostituição." Paulo exorta os cristãos a viverem em santidade, em preparação para a vinda do Senhor.
* João 13:34: "Um novo mandamento vos dou: que vos ameis uns aos outros; como eu vos amei a vós, que também vós uns aos outros vos ameis." Jesus ensina a importância do amor mútuo entre os seguidores, um tema enfatizado em 1 Tessalonicenses 5.
****

[[v59-5-1]]

^<<v59-5-1,1>>^ A respeito da época e do momento, não há necessidade, irmãos, de que vos escrevamos.

[[v59-5-2]]

^<<v59-5-2,2>>^ Pois vós mesmos sabeis muito bem que o dia do Senhor virá como um ladrão de noite.

[[v59-5-3]]

^<<v59-5-3,3>>^ Quando os homens disserem: “Paz e segurança!”, então repentinamente lhes sobrevirá a destruição, como as dores à mulher grávida. E não escaparão.

[[v59-5-4]]

^<<v59-5-4,4>>^ Mas vós, irmãos, não estais em trevas, de modo que esse dia vos surpreenda como um ladrão.

[[v59-5-5]]

^<<v59-5-5,5>>^ Porque todos vós sois filhos da luz e filhos do dia. Não somos da noite nem das trevas.

[[v59-5-6]]

^<<v59-5-6,6>>^ Não durmamos, pois, como os demais. Mas vigiemos e sejamos sóbrios.^&#42;1^

[[v59-5-7]]

^<<v59-5-7,7>>^ Porque os que dormem, dormem de noite; e os que se embriagam, embriagam-se de noite.

[[v59-5-8]]

^<<v59-5-8,8>>^ Nós, ao contrário, que somos do dia, sejamos sóbrios. Tomemos por couraça a fé e a caridade, e por capacete a esperança da salvação.

[[v59-5-9]]

^<<v59-5-9,9>>^ Porquanto não nos destinou Deus para a ira, mas para alcançar a salvação por nosso Senhor Jesus Cristo.

[[v59-5-10]]

^<<v59-5-10,10>>^ Ele morreu por nós, a fim de que nós, quer em estado de vigília, quer de sono, vivamos em união com ele.^&#42;1^

[[v59-5-11]]

^<<v59-5-11,11>>^ Assim, pois, consolai-vos mutuamente e edificai-vos uns aos outros, como já o fazeis.

[[v59-5-12]]

^<<v59-5-12,12>>^ Suplicamo-vos, irmãos, que reconheçais aqueles que arduamente trabalham entre vós para dirigir-vos no Senhor e vos admoestar.

[[v59-5-13]]

^<<v59-5-13,13>>^ Tende para com eles singular amor, em vista do cargo que exercem. Conservai a paz entre vós.

[[v59-5-14]]

^<<v59-5-14,14>>^ Pedimo-vos, porém, irmãos, corrigi os desordeiros, encorajai os tímidos, amparai os fracos e tende paciência para com todos.^&#42;1^

[[v59-5-15]]

^<<v59-5-15,15>>^ Vede que ninguém pague a outro mal por mal. Antes, procurai sempre praticar o bem entre vós e para com todos.

[[v59-5-16]]

^<<v59-5-16,16>>^ Vivei sempre contentes.

[[v59-5-17]]

^<<v59-5-17,17>>^ Orai sem cessar.

[[v59-5-18]]

^<<v59-5-18,18>>^ Em todas as circunstâncias, dai graças, porque esta é a vosso respeito a vontade de Deus em Jesus Cristo.

[[v59-5-19]]

^<<v59-5-19,19>>^ Não extingais o Espírito.^&#42;1^

[[v59-5-20]]

^<<v59-5-20,20>>^ Não desprezeis as profecias.

[[v59-5-21]]

^<<v59-5-21,21>>^ Examinai tudo: abraçai o que é bom.

[[v59-5-22]]

^<<v59-5-22,22>>^ Guardai-vos de toda a espécie de mal.

[[v59-5-23]]

^<<v59-5-23,23>>^ O Deus da paz vos conceda santidade perfeita. Que todo o vosso ser, espírito, alma e corpo, seja conservado irrepreensível para a vinda de nosso Senhor Jesus Cristo!^&#42;1^

[[v59-5-24]]

^<<v59-5-24,24>>^ Fiel é aquele que vos chama, e o cumprirá.

[[v59-5-25]]

^<<v59-5-25,25>>^ Irmãos, orai também por nós.

[[v59-5-26]]

^<<v59-5-26,26>>^ Saudai a todos os irmãos com o ósculo santo.

[[v59-5-27]]

^<<v59-5-27,27>>^ Peço-vos encarecidamente, no Senhor, que esta carta seja lida a todos os irmãos.

[[v59-5-28]]

^<<v59-5-28,28>>^ A graça de nosso Senhor Jesus Cristo esteja convosco!

'''

xref:059-i-tessalonicenses/059-i-tessalonicenses-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-ii-tessalonicenses/060-ii-tessalonicenses-001.adoc#v60-1-0[Próximo Capítulo &#62;]