include::./index.adoc[]

[[v59-3-0]]
=== I Tessalonicenses, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 3 de 1 Tessalonicenses descreve como Paulo enviou Timóteo para saber das notícias da igreja em Tessalônica e para encorajá-los em sua fé. Timóteo volta com boas notícias sobre a firmeza da fé dos tessalonicenses, o que traz grande consolo para Paulo. Seguem cinco versículos que se relacionam com os temas abordados em 1 Tessalonicenses 3:
* 2 Coríntios 1:3-4: "Louvado seja o Deus e Pai de nosso Senhor Jesus Cristo, Pai das misericórdias e Deus de toda consolação, que nos consola em todas as nossas tribulações, para que, com a consolação que recebemos de Deus, possamos consolar os que estão passando por tribulações." Esse versículo fala sobre a consolação que Deus nos oferece em momentos difíceis, um tema que também é abordado em 1 Tessalonicenses 3.
* 2 Timóteo 1:7: "Porque Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio." Esse versículo fala sobre a força e coragem que Deus nos concede, um tema que também é enfatizado em 1 Tessalonicenses 3.
* Hebreus 10:24-25: "E consideremos uns aos outros para nos incentivarmos ao amor e às boas obras. Não deixemos de reunir-nos como igreja, segundo o costume de alguns, mas procuremos encorajar-nos uns aos outros, ainda mais quando vocês veem que se aproxima o Dia." Esse versículo fala sobre a importância do encorajamento mútuo na vida cristã, um tema que é enfatizado em 1 Tessalonicenses 3.
* 2 Tessalonicenses 2:16-17: "Ora, que nosso Senhor Jesus Cristo mesmo e Deus, o nosso Pai, que nos amou e nos deu eterna consolação e boa esperança pela graça, console o coração de vocês e os fortaleça para fazerem e dizerem tudo o que é bom." Esse versículo fala sobre a consolação e fortalecimento que Deus nos oferece, um tema que é abordado em 1 Tessalonicenses 3.
* Romanos 1:12: "isto é, que vocês e eu sejamos mutuamente encorajados pela fé que temos um ao outro." Esse versículo destaca a importância do encorajamento mútuo na fé cristã, um tema que é enfatizado em 1 Tessalonicenses 3.
****

[[v59-3-1]]

^<<v59-3-1,1>>^ Assim, não podendo mais esperar, resolvemos ficar sozinhos em Atenas,

[[v59-3-2]]

^<<v59-3-2,2>>^ e enviar-vos Timóteo, nosso irmão e ministro de Deus no Evangelho de Cristo. Ele tem a missão de vos fortalecer e encorajar na vossa fé,

[[v59-3-3]]

^<<v59-3-3,3>>^ a fim de que, em meio às presentes tribulações, ninguém se amedronte. Vós mesmos sabeis que esta é a nossa sorte.

[[v59-3-4]]

^<<v59-3-4,4>>^ Estando ainda convosco, vos predizíamos que haveríamos de padecer tribulações. É o que aconteceu e estais sabendo.

[[v59-3-5]]

^<<v59-3-5,5>>^ É esse o motivo por que, não podendo mais suportar a demora, mandei colher informações a respeito da vossa fé, pois receava que o tentador vos tivesse seduzido e resultasse em nada o nosso trabalho.

[[v59-3-6]]

^<<v59-3-6,6>>^ Mas, agora, Timóteo acaba de voltar da visita que vos fez, trazendo excelentes notícias da vossa fé e caridade. Ele nos falou da afetuosa lembrança que de nós sempre guardais e do desejo que tendes de nos rever, desejo que é também nosso.

[[v59-3-7]]

^<<v59-3-7,7>>^ Assim, irmãos, fomos consolados por vós, no meio de todas as nossas angústias e tribulações, em virtude da vossa fé.

[[v59-3-8]]

^<<v59-3-8,8>>^ Agora, sim, tornamos a viver, porque permaneceis firmes no Senhor.

[[v59-3-9]]

^<<v59-3-9,9>>^ E como poderíamos agradecer a Deus por vós, por toda a alegria que tivemos diante dele por vossa causa?!

[[v59-3-10]]

^<<v59-3-10,10>>^ Noite e dia, com intenso, extremo fervor, oramos para que nos seja dado ver novamente a vossa face e completar o que ainda falta à vossa fé.^&#42;1^

[[v59-3-11]]

^<<v59-3-11,11>>^ Que Deus, nosso Pai, e nosso Senhor Jesus nos preparem o caminho até vós!

[[v59-3-12]]

^<<v59-3-12,12>>^ Que o Senhor vos faça crescer e avantajar na caridade mútua e para com todos os homens, como é o nosso amor para convosco.

[[v59-3-13]]

^<<v59-3-13,13>>^ Que ele confirme os vossos corações, e os torne irrepreensíveis e santos na presença de Deus, nosso Pai, por ocasião da vinda de nosso Senhor Jesus com todos os seus santos!

'''

xref:059-i-tessalonicenses/059-i-tessalonicenses-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-i-tessalonicenses/059-i-tessalonicenses-004.adoc#v59-4-0[Próximo Capítulo &#62;]