include::./index.adoc[]

[[v9-11-0]]
=== I Samuel, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 11 de 1 Samuel narra a história da vitória de Saul sobre os amonitas, que estavam cercando a cidade de Jabes-Gileade. Saul lidera as tribos de Israel em uma batalha bem-sucedida, garantindo a proteção do povo de Jabes-Gileade. Abaixo estão cinco versículos relacionados com temas abordados neste capítulo:
* Juízes 5:8: "Escolheram novos deuses; então, a guerra estava às portas; nem sequer se via escudo ou lança entre quarenta mil em Israel." Este versículo descreve a situação em Israel antes da liderança de Saul, onde o povo havia abandonado a Deus e estava vulnerável a ataques de inimigos.
* Deuteronômio 20:1: "Quando saíres à guerra contra os teus inimigos, e vires cavalos, e carros, e um povo maior do que tu, não os temerás; porque o Senhor teu Deus, que te tirou da terra do Egito, está contigo." Este versículo descreve a confiança que o povo de Israel deve ter em Deus quando enfrenta inimigos mais fortes em uma batalha.
* 2 Crônicas 32:7: "Sê forte e corajoso; não temas, nem te espantes da face do rei da Assíria, nem de toda a multidão que está com ele, porque conosco há mais do que com ele." Este versículo encoraja o povo de Israel a ser forte e corajoso, confiando que Deus está do seu lado.
* Salmo 20:7: "Uns confiam em carros e outros em cavalos, mas nós faremos menção do nome do Senhor nosso Deus." Este versículo fala sobre a importância de confiar em Deus em vez de confiar em recursos materiais em tempos de guerra.
* Provérbios 21:31: "O cavalo prepara-se para o dia da batalha, mas a vitória vem do Senhor." Este versículo destaca que, embora seja importante se preparar para a batalha, a vitória final vem de Deus. Isso se aplica à vitória de Saul sobre os amonitas em 1 Samuel 11, onde foi a ajuda de Deus que garantiu a vitória.
****

[[v9-11-1]]

^<<v9-11-1,1>>^ Naás, o amonita, pôs-se em cam-panha e combateu contra Jabes, em Galaad. Os habitantes de Jabes disseram-lhe: “Façamos aliança e nós te serviremos”.

[[v9-11-2]]

^<<v9-11-2,2>>^ Mas Naás, o amonita, respondeu-lhes: “Só farei aliança convosco com a condição de vos furar a todos o olho direito, para impor assim um opróbrio a todo o Israel”.

[[v9-11-3]]

^<<v9-11-3,3>>^ “Concede-nos sete dias – disseram-lhe os anciãos de Jabes – para que enviemos mensageiros por toda a terra de Israel; se não houver quem nos ajude, nos entregaremos a ti”.

[[v9-11-4]]

^<<v9-11-4,4>>^ Foram os mensageiros a Gabaá, cidade de Saul e contaram isso ao povo e todo o povo pôs-se a chorar em alta voz.

[[v9-11-5]]

^<<v9-11-5,5>>^ Saul voltava então do campo, atrás dos seus bois. “Que tem o povo para chorar dessa forma?” – disse ele. E referiram-lhe as palavras dos habitantes de Jabes.

[[v9-11-6]]

^<<v9-11-6,6>>^ Ouvindo isso, o Espírito do Senhor apoderou-se de Saul e ele encolerizou-se.

[[v9-11-7]]

^<<v9-11-7,7>>^ Tomando uma junta de bois, fê-la em pedaços e mandou-os por mão de mensageiros por todo o território de Israel, com este aviso: “Assim será feito aos bois de todo aquele que se não puser em campanha com Saul e Samuel”. O terror do Senhor apoderou-se do povo e este pôs-se em marcha como um só homem.

[[v9-11-8]]

^<<v9-11-8,8>>^ Saul passou-o em revista em Bezec: havia trezentos mil homens de Israel e trinta mil de Judá.

[[v9-11-9]]

^<<v9-11-9,9>>^ Disseram aos mensageiros que tinham vindo: “Dizei aos habitantes de Jabes, em Galaad, que amanhã, quando o sol estiver na força do seu calor, serão socorridos”. Voltando, deram os mensageiros essa notícia aos habitantes de Jabes, que se alegraram.

[[v9-11-10]]

^<<v9-11-10,10>>^ Esses disseram aos amonitas: “Amanhã nos renderemos a vós e fareis de nós o que vos parecer melhor”.

[[v9-11-11]]

^<<v9-11-11,11>>^ No dia seguinte, Saul dividiu o povo em três partes; penetraram ao raiar do dia no acampamento inimigo e feriram os amonitas até que chegou o grande calor do dia. Aqueles que escaparam foram dispersos, de tal sorte que não ficaram dois deles juntos.

[[v9-11-12]]

^<<v9-11-12,12>>^ O povo disse a Samuel: “Quem é que disse: ‘Saul não reinará sobre nós?’ Dai-nos esses homens para que os matemos.”

[[v9-11-13]]

^<<v9-11-13,13>>^ Porém, Saul respondeu: “Hoje não se matará ninguém, porque é o dia em que o Senhor libertou Israel.”

[[v9-11-14]]

^<<v9-11-14,14>>^ Samuel disse ao povo: “Vamos a Gálgala e renovemos ali a realeza.”

[[v9-11-15]]

^<<v9-11-15,15>>^ Partiu, pois, todo o povo para Gálgala para ali confirmar Saul, em presença do Senhor, no seu título de rei e oferecer naquele lugar sacrifícios de ações de graças. E Saul, com todos os israelitas, alegraram-se grandemente.

'''

xref:009-i-samuel/009-i-samuel-010.adoc#v9-10-0[&#60; Capítulo Anterior] | <<v9-11-0,Topo>> | xref:009-i-samuel/009-i-samuel-012.adoc#v9-12-0[Próximo Capítulo &#62;]