include::./index.adoc[]

[[v9-29-0]]
=== I Samuel, 29
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Samuel 29 narra a história de Davi indo para a batalha com os filisteus, mas sendo rejeitado pelos líderes filisteus. Davi, que se escondeu dos israelitas entre os filisteus, era considerado um aliado deles, mas os outros filisteus não confiavam nele o suficiente para deixá-lo lutar contra os israelitas ao lado deles. Os versículos relacionados com os temas abordados em 1 Samuel 29 são:
* Provérbios 29:25: "O temor do homem armará laços, mas o que confia no Senhor será posto em alto retiro." Os líderes filisteus temiam que Davi mudasse de lado na batalha e, assim, armaram um laço para que ele não pudesse lutar com eles.
* Salmo 118:8-9: "É melhor confiar no Senhor do que confiar no homem. É melhor confiar no Senhor do que confiar em príncipes." Davi confiava no Senhor para protegê-lo, mesmo quando os líderes filisteus o rejeitaram.
* 2 Coríntios 6:14: "Não vos prendais a um jugo desigual com os incrédulos; porque que sociedade tem a justiça com a injustiça? ou que comunhão tem a luz com as trevas?" Davi, que era um servo de Deus, não deveria ter se aliado aos filisteus, que eram inimigos do povo de Deus.
* Filipenses 4:6-7: "Não andeis ansiosos por coisa alguma; antes em tudo sejam os vossos pedidos conhecidos diante de Deus pela oração e súplica com ações de graças; e a paz de Deus, que excede todo o entendimento, guardará os vossos corações e as vossas mentes em Cristo Jesus." Davi poderia ter ficado ansioso com a situação em que se encontrava, mas optou por confiar em Deus e deixar suas preocupações com ele.
* Provérbios 3:5-6: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." Davi confiava em Deus para guiá-lo em seus caminhos e decisões, mesmo quando pareciam não fazer sentido aos olhos dos homens.
****

[[v9-29-1]]

^<<v9-29-1,1>>^ Reuniram os filisteus todas as suas forças em Afec, estando os israelitas acampados junto à fonte de Jezrael.

[[v9-29-2]]

^<<v9-29-2,2>>^ Os príncipes dos filisteus iam à frente com suas tropas, divididas em companhias de cem e de mil homens. Davi e sua gente caminhavam na retaguarda com Aquis.

[[v9-29-3]]

^<<v9-29-3,3>>^ Os chefes dos filisteus disseram: “Quem são esses hebreus?”. “É Davi – respondeu Aquis –, servo de Saul, rei de Israel, que está em minha companhia há muitos dias e mesmo há muitos anos. Nada tenho a censurar-lhe desde o dia em que se refugiou junto de mim até hoje.”

[[v9-29-4]]

^<<v9-29-4,4>>^ Furiosos, os chefes dos filisteus disseram-lhe: “Vá-se embora esse homem; manda que ele volte ao lugar que lhe marcaste, mas que não desça conosco à batalha; não suceda que se volte contra nós no meio do combate. Pois como poderia ele ganhar melhor as graças de seu amo, do que ao preço das cabeças de nossos homens?

[[v9-29-5]]

^<<v9-29-5,5>>^ Não é ele porventura aquele Davi, do qual se cantava dançando: ‘Saul matou seus milhares mas Davi seus dez milhares?’.”

[[v9-29-6]]

^<<v9-29-6,6>>^ Aquis chamou Davi e disse-lhe: “Viva Deus! Tu és um homem reto e teu proceder comigo no acampamento me parece justo. Até hoje nada tive a censurar-te desde que chegaste à minha casa. Mas não és bem visto pelos príncipes.

[[v9-29-7]]

^<<v9-29-7,7>>^ Retira-te, pois, e vai em paz, para não descontentar os príncipes dos filisteus”.

[[v9-29-8]]

^<<v9-29-8,8>>^ Davi disse a Aquis: “Mas, que fiz eu? Que achaste de censurável no teu servo, desde o dia em que cheguei à tua casa até hoje, para que eu não vá combater contra os inimigos do rei, meu senhor?”.

[[v9-29-9]]

^<<v9-29-9,9>>^ “Eu o sei – respondeu Aquis –; “tens sido bom para comigo, como um anjo do Senhor. Mas os chefes dos filisteus é que não querem que vás com eles ao combate.

[[v9-29-10]]

^<<v9-29-10,10>>^ Amanhã cedo, portanto, parti, tu e os servos de teu senhor que te seguiram. Ide, parti bem cedo, ao clarear do dia.”

[[v9-29-11]]

^<<v9-29-11,11>>^ Davi e os seus homens levantaram-se de madrugada e voltaram à terra dos filisteus. Estes, porém, subiram a Jezrael.

'''

xref:009-i-samuel/009-i-samuel-028.adoc#v9-28-0[&#60; Capítulo Anterior] | <<v9-29-0,Topo>> | xref:009-i-samuel/009-i-samuel-030.adoc#v9-30-0[Próximo Capítulo &#62;]