include::./index.adoc[]

[[v9-1-0]]
=== I Samuel, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Samuel 1 relata a história de Ana, uma mulher estéril que orou fervorosamente por um filho. Deus atendeu suas súplicas e ela deu à luz Samuel, que mais tarde se tornou um grande profeta de Israel. Aqui estão cinco versículos relacionados com temas abordados neste capítulo:
* Salmos 113:9: "Ele faz a estéril habitar em casa como mãe de filhos. Aleluia!" Este versículo fala sobre como Deus pode realizar milagres na vida das pessoas, incluindo dar filhos àqueles que são estéreis, como aconteceu com Ana.
* Gênesis 25:21: "Isaque orou ao Senhor em favor de sua esposa, porque era estéril. O Senhor ouviu a sua oração, e Rebeca, sua mulher, concebeu." Este versículo mostra outro exemplo de um casal estéril que orou a Deus por um filho e foi atendido.
* 1 Samuel 2:1: "Então Ana orou e disse: "Meu coração exulta no Senhor! No Senhor minha boca se alegra! Porque eu me alegro na tua salvação." Este é o início do cântico de Ana, que ela entoou após o nascimento de Samuel como uma forma de agradecer a Deus por ter ouvido suas orações.
* Lucas 1:46-47: "E Maria disse: A minha alma engrandece ao Senhor, e o meu espírito se alegra em Deus, meu Salvador." Este é o início do cântico de Maria, a mãe de Jesus, que é semelhante ao cântico de Ana em 1 Samuel 2. Ambas as mulheres expressaram sua gratidão a Deus por sua fidelidade e bondade.
* Tiago 5:16: "Confessai, pois, os vossos pecados uns aos outros e orai uns pelos outros, para serdes curados. A oração feita por um justo pode muito em seus efeitos." Este versículo fala sobre a importância da oração e do apoio mútuo na comunidade cristã, algo que Ana encontrou na casa de Deus, onde ela derramou seu coração diante do Senhor.
****

[[v9-1-1]]

^<<v9-1-1,1>>^ Havia em Ramataim-Sofim um homem das montanhas de Efraim, chamado Elcana, filho de Jeroam, filho de Eliú, filho de Tou, filho de Suf, o efraimita.

[[v9-1-2]]

^<<v9-1-2,2>>^ Tinha ele duas mulheres, uma chamada Ana e outra Fenena. Esta última tinha filhos; Ana, porém, não os tinha.

[[v9-1-3]]

^<<v9-1-3,3>>^ Cada ano subia esse homem de sua cidade para adorar o Senhor dos exércitos e oferecer-lhe um sacrifício em Silo, onde se encontravam os dois filhos de Heli, Hofni e Fineias, sacerdotes do Senhor.^&#42;1^

[[v9-1-4]]

^<<v9-1-4,4>>^ Cada vez que Elcana oferecia um sacrifício, dava porções à sua mulher Fenena, bem como aos filhos e filhas que ela teve;

[[v9-1-5]]

^<<v9-1-5,5>>^ a Ana, porém, dava uma porção dupla, porque a amava, embora o Senhor a tivesse tornado estéril.

[[v9-1-6]]

^<<v9-1-6,6>>^ Sua rival afligia-a duramente, provocando-a a murmurar contra o Senhor que a tinha feito estéril.

[[v9-1-7]]

^<<v9-1-7,7>>^ Isso se repetia cada ano quando ela subia à casa do Senhor; Fenena continuava provocando-a. Então, Ana punha-se a chorar e não comia.

[[v9-1-8]]

^<<v9-1-8,8>>^ Seu marido dizia-lhe: “Ana, por que choras? Por que não comes? Por que estás triste? Não valho eu para ti como dez filhos?”.

[[v9-1-9]]

^<<v9-1-9,9>>^ (Desta vez) Ana levantou-se, depois de ter comido e bebido em Silo. Ora, o sacerdote Heli estava sentado numa cadeira à entrada do Templo do Senhor.

[[v9-1-10]]

^<<v9-1-10,10>>^ Ana, profundamente amargurada, orou ao Senhor e chorou copiosamente.

[[v9-1-11]]

^<<v9-1-11,11>>^ E fez um voto, dizendo: “Senhor dos exércitos, se vos dignardes olhar para a aflição de vossa serva e vos lembrardes de mim; se não vos esquecerdes de vossa escrava e lhe derdes um filho varão, eu o consagrarei ao Senhor durante todos os dias de sua vida e a navalha não passará pela sua cabeça”.

[[v9-1-12]]

^<<v9-1-12,12>>^ Prolongando ela sua oração diante do Senhor, Heli observava o movimento dos seus lábios.

[[v9-1-13]]

^<<v9-1-13,13>>^ Ana, porém, falava no seu coração e apenas se moviam os seus lábios, sem se lhe ouvir a voz.

[[v9-1-14]]

^<<v9-1-14,14>>^ Heli, julgando-a ébria, falou-lhe: “Até quando estarás tu embriagada? Vai-te e deixa passar a tua bebedeira”.

[[v9-1-15]]

^<<v9-1-15,15>>^ “Não é assim, meu Senhor – respondeu ela –, eu sou uma mulher aflita: não bebi nem vinho, nem álcool, mas derramo a minha alma na presença do Senhor.

[[v9-1-16]]

^<<v9-1-16,16>>^ Não tomes a tua escrava por uma pessoa frívola, porque é a grandeza de minha dor e de minha aflição que me fez falar até agora.”

[[v9-1-17]]

^<<v9-1-17,17>>^ Heli respondeu: “Vai em paz e o Deus de Israel te conceda o que lhe pedes”.

[[v9-1-18]]

^<<v9-1-18,18>>^ “Encontre a tua serva graça aos teus olhos” – ajuntou ela. A mulher se foi, comeu e o seu rosto não era mais o mesmo.

[[v9-1-19]]

^<<v9-1-19,19>>^ No dia seguinte, pela manhã, prostraram-se diante do Senhor e voltaram para a sua casa em Ramá.

[[v9-1-20]]

^<<v9-1-20,20>>^ Elcana conheceu Ana, sua mulher, e o Senhor lembrou-se dela. Ana concebeu, e, passado o seu tempo, deu à luz um filho. Chamou-o Samuel, dizendo: “Porque – dizia – eu o pedi ao Senhor”.^&#42;1^

[[v9-1-21]]

^<<v9-1-21,21>>^ Elcana, seu marido, foi com toda a sua casa para oferecer ao Senhor o sacrifício anual.

[[v9-1-22]]

^<<v9-1-22,22>>^ Ana, porém, não foi e disse ao seu marido: “Quando o menino for desmamado, eu o levarei para apresentá-lo ao Senhor e lá ficará para sempre”.

[[v9-1-23]]

^<<v9-1-23,23>>^ “Faze como achares melhor – respondeu-lhe Elcana –, fica até que o tenhas desmamado e que o Senhor se digne confirmar a sua promessa.” Ela ficou e amamentou o seu filho até o desmamar.

[[v9-1-24]]

^<<v9-1-24,24>>^ Após tê-lo desmamado, tomou-o consigo e levando também três novilhos de três anos, um efá de farinha e um odre de vinho, conduziu-o à casa do Senhor, em Silo. O menino era ainda muito criança.

[[v9-1-25]]

^<<v9-1-25,25>>^ Imolaram o novilho e conduziram o menino a Heli.

[[v9-1-26]]

^<<v9-1-26,26>>^ Ana disse-lhe: “Ouve, meu Senhor, por tua vida, eu sou aquela mulher que esteve aqui em tua presença orando ao Senhor.

[[v9-1-27]]

^<<v9-1-27,27>>^ Eis aqui o menino por quem orei e o Senhor ouviu o meu pedido.

[[v9-1-28]]

^<<v9-1-28,28>>^ Portanto, eu também o dou ao Senhor: ele será consagrado ao Senhor para todos os dias de sua vida”. E prostraram-se naquele lugar diante do Senhor.

'''

xref:008-rute/008-rute-004.adoc#v8-4-0[&#60; Capítulo Anterior] | <<v9-1-0,Topo>> | xref:009-i-samuel/009-i-samuel-002.adoc#v9-2-0[Próximo Capítulo &#62;]