include::./index.adoc[]

[[v9-24-0]]
=== I Samuel, 24
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 24 de 1 Samuel narra a história de Davi perdoando Saul. Depois de fugir de Saul por um tempo, Davi teve a oportunidade de matá-lo quando Saul entrou em uma caverna onde Davi e seus homens estavam escondidos. No entanto, Davi escolheu poupar a vida de Saul, mesmo quando seus homens o encorajavam a matá-lo. Aqui estão cinco versículos relacionados com os temas abordados neste capítulo:
* Provérbios 19:11 - "A prudência do homem o faz tardar em irar-se, e sua glória está em esquecer ofensas." Esse versículo destaca a sabedoria de Davi em escolher perdoar Saul em vez de se vingar.
* Mateus 5:44 - "Eu, porém, vos digo: amai a vossos inimigos e orai pelos que vos perseguem." Esse versículo mostra a mensagem de amor e perdão que Jesus ensinou, que Davi parece ter aplicado ao perdoar Saul.
* Romanos 12:19 - "Não vos vingueis a vós mesmos, amados, mas dai lugar à ira de Deus, porque está escrito: Minha é a vingança; eu recompensarei, diz o Senhor." Esse versículo destaca que a vingança não deve ser buscada pelos indivíduos, mas sim pela justiça divina.
* Provérbios 25:21-22 - "Se o teu inimigo tiver fome, dá-lhe pão para comer, e se tiver sede, dá-lhe água para beber, porque assim amontoarás brasas vivas sobre a sua cabeça, e o Senhor te recompensará." Esse versículo incentiva a amar e servir os inimigos em vez de buscar vingança.
* Colossenses 3:13 - "Suportai-vos uns aos outros, perdoai-vos mutuamente, caso alguém tenha motivo de queixa contra outro. Assim como o Senhor vos perdoou, perdoai também vós." Esse versículo destaca a importância do perdão e da misericórdia entre as pessoas, como Davi demonstrou ao perdoar Saul.
****

[[v9-24-1]]

^<<v9-24-1,1>>^ Subindo dali, veio Davi habitar nas alturas de Engadi.

[[v9-24-2]]

^<<v9-24-2,2>>^ Quando Saul voltou da perseguição aos filisteus, foi-lhe anunciado: “Davi está no deserto de Engadi”.

[[v9-24-3]]

^<<v9-24-3,3>>^ Tomou então Saul três mil israelitas de escol e foi em busca de Davi com sua gente nos rochedos dos cabritos monteses.

[[v9-24-4]]

^<<v9-24-4,4>>^ Chegando perto dos apriscos de ovelhas que havia ao longo do caminho, entrou Saul numa gruta para satisfazer suas necessidades. Ora, no fundo dessa mesma gruta se encontrava Davi com seus homens,^&#42;1^

[[v9-24-5]]

^<<v9-24-5,5>>^ os quais disseram-lhe: “Eis o dia anunciado pelo Senhor, que te prometeu entregar o teu inimigo à tua discrição”. Davi, arrastando-se de mansinho, cortou furtivamente a ponta do manto de Saul.

[[v9-24-6]]

^<<v9-24-6,6>>^ E logo depois o seu coração bateu-lhe porque tinha ousado fazer aquilo.

[[v9-24-7]]

^<<v9-24-7,7>>^ E disse aos seus homens: “Deus me guarde de jamais cometer este crime, estendendo a mão contra o ungido do Senhor, meu senhor, pois ele é consagrado ao Senhor!”.

[[v9-24-8]]

^<<v9-24-8,8>>^ Davi conteve os seus homens com essas palavras e impediu que agredissem Saul. O rei levantou-se, deixou a gruta e prosseguiu o seu caminho.

[[v9-24-9]]

^<<v9-24-9,9>>^ Então Davi saiu por sua vez e bradou atrás de Saul: “Ó rei, meu senhor!”. Saul voltou-se para ver e Davi inclinou-se, prostrando-se até a terra.

[[v9-24-10]]

^<<v9-24-10,10>>^ E disse ao rei: “Por que dás ouvidos aos que te dizem: ‘Davi procura fazer-te mal?’.

[[v9-24-11]]

^<<v9-24-11,11>>^ Viste hoje com os teus olhos que o Senhor te entregou a mim na gruta. Meus homens insistiam comigo para que te matasse, mas eu te poupei, dizendo: ‘Não levantarei a mão contra o meu senhor, porque é o ungido do Senhor’.

[[v9-24-12]]

^<<v9-24-12,12>>^ Olha, meu pai, vê a ponta de teu manto em minha mão. Se eu cortei este pano do teu manto e não te matei, reconhece que não há perversidade nem revolta em mim. Jamais pequei contra ti e tu procuras matar-me.

[[v9-24-13]]

^<<v9-24-13,13>>^ Que o Senhor julgue entre mim e ti! O Senhor me vingará de ti, mas eu não levantarei minha mão contra ti.

[[v9-24-14]]

^<<v9-24-14,14>>^ O mal vem dos malvados, como diz o provérbio; por isso, não te tocará a minha mão.

[[v9-24-15]]

^<<v9-24-15,15>>^ Afinal, contra quem saiu o rei de Israel? A quem persegues? Um cão morto! Uma pulga!

[[v9-24-16]]

^<<v9-24-16,16>>^ Pois bem! O Senhor julgará e pronunciará entre mim e ti. Que ele olhe e defenda a minha causa, fazendo-me justiça contra ti!”.

[[v9-24-17]]

^<<v9-24-17,17>>^ Acabando Davi de falar, Saul disse-lhe: “É esta a tua voz, ó meu filho Davi?”. E pôs-se a chorar.

[[v9-24-18]]

^<<v9-24-18,18>>^ “Tu és mais justo do que eu – replicou ele –; fizeste-me bem pelo mal que te fiz.

[[v9-24-19]]

^<<v9-24-19,19>>^ Provaste hoje a tua bondade para comigo, pois o Senhor tinha-me entregue a ti e não me mataste.

[[v9-24-20]]

^<<v9-24-20,20>>^ Qual é o homem que, encontrando o seu inimigo, deixa-o ir embora tranquilamente? Que o Senhor te recompense o que hoje me deste!

[[v9-24-21]]

^<<v9-24-21,21>>^ Agora eu sei que serás rei e que nas tuas mãos será firmada a realeza.

[[v9-24-22]]

^<<v9-24-22,22>>^ Jura-me pelo Senhor que não eliminarás a minha posteridade, nem apagarás o meu nome da casa de meu pai”.

[[v9-24-23]]

^<<v9-24-23,23>>^ Davi prestou-lhe juramento. Depois disso, Saul voltou para a sua casa e Davi com a sua gente voltaram ao seu refúgio.

'''

xref:009-i-samuel/009-i-samuel-023.adoc#v9-23-0[&#60; Capítulo Anterior] | <<v9-24-0,Topo>> | xref:009-i-samuel/009-i-samuel-025.adoc#v9-25-0[Próximo Capítulo &#62;]