include::./index.adoc[]

[[v9-23-0]]
=== I Samuel, 23
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Samuel 23 descreve como Davi salva a cidade de Queila do ataque dos filisteus, mas é traído pelos habitantes da cidade e precisa fugir para o deserto, onde é novamente perseguido por Saul. Os temas abordados neste capítulo incluem liderança, lealdade, traição, proteção divina e confiança em Deus.
* Salmos 18:2: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio. Ele é o meu escudo e o poder que me salva, a minha torre alta." Este versículo destaca a proteção divina que Davi busca em meio à perseguição de Saul.
* Provérbios 11:14: "Onde não há conselho fracassam os projetos, mas com a multidão de conselheiros há bom êxito." Este versículo fala sobre a importância de ouvir conselhos e buscar sabedoria, algo que Davi faz ao consultar a Deus sobre o ataque a Queila.
* Salmos 34:7: "O anjo do Senhor acampa-se ao redor dos que o temem, e os livra." Este versículo destaca a proteção divina que Davi experimenta quando confia em Deus em meio à perseguição.
* Salmos 52:8: "Eu, porém, sou como a oliveira verdejante na casa de Deus; confio no amor de Deus para sempre e para todo o sempre." Este versículo destaca a confiança de Davi em Deus, mesmo quando perseguido por Saul e traído por seus aliados.
* Salmos 118:8: "É melhor buscar refúgio no Senhor do que confiar nos homens." Este versículo fala sobre a importância de confiar em Deus em meio às dificuldades, algo que Davi faz ao buscar a orientação de Deus e confiar na sua proteção em meio à perseguição.
****

[[v9-23-1]]

^<<v9-23-1,1>>^ Disseram a Davi: “Os filisteus estão atacando Ceila e pilhando as eiras”.

[[v9-23-2]]

^<<v9-23-2,2>>^ Davi consultou o Senhor: “Devo ferir os filisteus?”. O Senhor respondeu: “Vai; tu os ferirás e libertarás Ceila”.

[[v9-23-3]]

^<<v9-23-3,3>>^ Os homens de Davi, porém, disseram-lhe: “Mesmo aqui em Judá estamos cheios de medo; quanto mais se formos a Ceila contra as tropas dos filisteus?”.

[[v9-23-4]]

^<<v9-23-4,4>>^ Davi consultou novamente o Senhor, que lhe respondeu: “Vai; desce a Ceila, porque entrego os filisteus nas tuas mãos”.

[[v9-23-5]]

^<<v9-23-5,5>>^ Davi foi a Ceila com os seus homens e atacou os filisteus, tomando-lhes o gado e infligindo-lhes uma grande derrota. Assim libertou os habitantes de Ceila.

[[v9-23-6]]

^<<v9-23-6,6>>^ Ora, quando Abiatar, filho de Abimelec, fugira para junto de Davi a Ceila, levava consigo o efod.

[[v9-23-7]]

^<<v9-23-7,7>>^ Saul foi informado de que Davi se encontrava em Ceila e disse: “Deus entregou-o nas minhas mãos, pois foi encerrar-se em uma cidade com portas e ferrolhos”.

[[v9-23-8]]

^<<v9-23-8,8>>^ O rei convocou todo o povo às armas para descer a Ceila e sitiar Davi com sua tropa.

[[v9-23-9]]

^<<v9-23-9,9>>^ Mas Davi, sabendo que Saul maquinava mata-lo, disse ao sacerdote Abiatar: “Traze o efod!”.

[[v9-23-10]]

^<<v9-23-10,10>>^ E ajuntou: “Senhor, Deus de Israel, vosso servo sabe que Saul pretende penetrar em Ceila para destruir a cidade por causa de mim.

[[v9-23-11]]

^<<v9-23-11,11>>^ Será que os habitantes de Ceila me entregarão nas suas mãos? Saul descerá como o vosso servo ouviu dizer? Senhor, Deus de Israel, fazei-o saber ao vosso servo”. O Senhor respondeu: “Ele descerá”.

[[v9-23-12]]

^<<v9-23-12,12>>^ E Davi ajuntou: “Os habitantes de Ceila me entregarão com meus homens, nas mãos de Saul?”. O Senhor respondeu: “Entregarão”.

[[v9-23-13]]

^<<v9-23-13,13>>^ Então Davi partiu precipitadamente com a sua tropa, em número de aproximadamente seiscentos homens e saíram de Ceila, marchando ao acaso. Saul, informado de que Davi deixara Ceila, renunciou à expedição.

[[v9-23-14]]

^<<v9-23-14,14>>^ Davi permaneceu no deserto, em lugares bem protegidos e habitou no monte do deserto de Zif. Saul procurava-o sem cessar; mas Deus não o entregou nas suas mãos.

[[v9-23-15]]

^<<v9-23-15,15>>^ Davi, sabendo que Saul tinha saído para tirar-lhe a vida, ficou no deserto de Zif, em Horesa.

[[v9-23-16]]

^<<v9-23-16,16>>^ Então Jônatas, filho de Saul, foi ter com ele em Horesa. E confortou-o em Deus, dizendo:

[[v9-23-17]]

^<<v9-23-17,17>>^ “Não temas, porque não te atingirá a mão de meu pai. Tu reinarás sobre Israel e eu serei o teu segundo; meu pai bem o sabe”.

[[v9-23-18]]

^<<v9-23-18,18>>^ Fizeram ambos aliança diante do Senhor. Davi ficou em Horesa e Jônatas voltou para a sua casa.

[[v9-23-19]]

^<<v9-23-19,19>>^ Alguns zifeus subiram a ter com Saul em Gabaá e disseram-lhe: “Davi está escondido entre nós no fortim de Horesa, na colina de Aquila, à direita do deserto.

[[v9-23-20]]

^<<v9-23-20,20>>^ Desce, pois, ó rei, já que tanto o desejas e nós nos encarregamos de entregá-lo nas tuas mãos”.

[[v9-23-21]]

^<<v9-23-21,21>>^ “Que o Senhor vos abençoe – respondeu Saul – porque vos compadecestes de mim.

[[v9-23-22]]

^<<v9-23-22,22>>^ Ide, informai-vos diligentemente e procurai saber o lugar onde ele se encontra ou se alguém o viu, porque me foi dito que ele é muito astuto!

[[v9-23-23]]

^<<v9-23-23,23>>^ Explorai e descobri todos os seus esconderijos e voltai a mim com notícias seguras, a fim de eu ir convosco, pois se ele estiver na terra, eu o descobrirei entre a multidão de Judá.”

[[v9-23-24]]

^<<v9-23-24,24>>^ Partiram antes de Saul para Zif; mas Davi e os seus estavam já no deserto de Maon, na planície ao sul do deserto.

[[v9-23-25]]

^<<v9-23-25,25>>^ Saul partiu com seus homens à sua procura. Mas Davi, informado disso, desceu à rocha e permaneceu no deserto de Maon. Saul o soube e foi persegui-lo ali.

[[v9-23-26]]

^<<v9-23-26,26>>^ Saul ia por um flanco da montanha e Davi com os seus pelo outro, em fuga precipitada para escapar de Saul. No momento, porém, em que Saul com seus homens iam apoderar-se de Davi e sua gente,

[[v9-23-27]]

^<<v9-23-27,27>>^ veio um mensageiro anunciar ao rei: “Vem depressa; os filisteus entraram na terra”.

[[v9-23-28]]

^<<v9-23-28,28>>^ Saul abandonou a perseguição e foi combater os filisteus. Por isso, àquele lugar foi dado o nome de “Rocha da Separação”.

'''

xref:009-i-samuel/009-i-samuel-022.adoc#v9-22-0[&#60; Capítulo Anterior] | <<v9-23-0,Topo>> | xref:009-i-samuel/009-i-samuel-024.adoc#v9-24-0[Próximo Capítulo &#62;]