include::./index.adoc[]

[[v9-8-0]]
=== I Samuel, 8
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 8 de 1 Samuel descreve o momento em que o povo de Israel pede a Samuel que estabeleça um rei para governar sobre eles, mesmo que isso signifique rejeitar a liderança direta de Deus sobre a nação. A questão central do capítulo é a tensão entre a vontade do povo de ter um rei humano e a vontade de Deus de governar Israel diretamente. Abaixo estão cinco versículos relacionados com os temas abordados em 1 Samuel 8:
* Deuteronômio 17:14-15: "Quando entrares na terra que o Senhor teu Deus te dá, e a possuíres, e nela habitares, e disseres: Porei sobre mim um rei, como todas as nações que estão em redor de mim; certamente porás sobre ti um rei, que o Senhor teu Deus escolher; dentre teus irmãos porás rei sobre ti; não poderás por sobre ti um homem estranho, que não seja de teus irmãos." Este versículo descreve a lei de Deus para a escolha de um rei em Israel, indicando que essa decisão não deve ser tomada levianamente e que o rei deve ser escolhido dentre os próprios israelitas.
* 1 Samuel 9:16: "Amanhã, por esta hora, enviar-te-ei um homem da terra de Benjamim, o qual ungirás por príncipe sobre o meu povo Israel, e ele livrará o meu povo da mão dos filisteus; porque tenho olhado para o meu povo, porquanto o seu clamor chegou a mim." Neste versículo, Deus diz a Samuel que ele escolherá um líder para Israel, indicando que a escolha do rei não é uma ideia nova ou estranha, mas que o processo deve ser guiado pela vontade de Deus.
* 1 Samuel 10:24: "Disse Samuel a todo o povo: Vedes já a quem o Senhor escolheu? Pois não há ninguém semelhante a ele entre todo o povo. Então todo o povo gritou, e disse: Viva o rei!" Este versículo descreve a unção de Saul como rei de Israel, confirmando que Deus escolheu um rei para liderar a nação.
* 1 Samuel 12:12: "Vendo, pois, que Naás, rei dos filhos de Amom, vinha contra vós, me dissestes: Não, mas um rei reinará sobre nós; sendo, porém, o Senhor vosso Deus o vosso rei." Neste versículo, Samuel lembra o povo de sua escolha de um rei e destaca a importância de continuar a confiar em Deus como seu verdadeiro líder.
* 1 Crônicas 29:11-12: "Tua, SENHOR, é a grandeza, o poder, a glória, a vitória e a majestade; porque teu é tudo quanto há nos céus e na terra; teu, SENHOR, é o reino, e tu te exaltaste por chefe sobre todos. Riquezas e glória vêm de ti, tu dominas sobre tudo, na tua mão há força e poder; contigo está o engrandecer e a tudo dar força". Esses versículos trazem uma reflexão sobre a soberania de Deus e Sua posição como Rei sobre tudo o que existe, incluindo riquezas e poder. O capítulo 8 de 1 Samuel trata da escolha de um rei terreno pelos israelitas, mas esses versículos de Crônicas 29 destacam que a verdadeira autoridade e poder pertencem a Deus.
****

[[v9-8-1]]

^<<v9-8-1,1>>^ Samuel, tendo envelhecido, estabeleceu seus filhos como juízes de Israel.

[[v9-8-2]]

^<<v9-8-2,2>>^ Seu filho primogênito chamava-se Joel e o segundo Abias; e julgavam em Bersabeia.

[[v9-8-3]]

^<<v9-8-3,3>>^ Os filhos de Samuel, porém, não seguiram as suas pisadas, mas deixaram-se arrastar pela cobiça, recebendo presentes e violando o direito.

[[v9-8-4]]

^<<v9-8-4,4>>^ Todos os anciãos de Israel vieram em grupo ter com Samuel em Ramá,

[[v9-8-5]]

^<<v9-8-5,5>>^ e disseram-lhe: “Estás velho e teus filhos não seguem as tuas pisadas. Dá-nos um rei que nos governe, como o têm todas as nações”.

[[v9-8-6]]

^<<v9-8-6,6>>^ Estas palavras: “Dá-nos um rei que nos governe” desagradaram a Samuel, que se pôs em oração diante do Senhor.

[[v9-8-7]]

^<<v9-8-7,7>>^ O Senhor disse-lhe: “Ouve a voz do povo em tudo o que te disseram. Não é a ti que eles rejeitam, mas a mim, pois já não querem que eu reine sobre eles.

[[v9-8-8]]

^<<v9-8-8,8>>^ Fazem contigo como sempre o têm feito comigo, desde o dia em que os tirei do Egito até o presente: abandonam-me para servir a deuses estranhos.

[[v9-8-9]]

^<<v9-8-9,9>>^ Atende-os, agora; mas declara-lhes solenemente, dando-lhes a conhecer os direitos do rei que reinará sobre eles”.

[[v9-8-10]]

^<<v9-8-10,10>>^ Samuel transmitiu todas as palavras do Senhor ao povo que reclamava um rei:

[[v9-8-11]]

^<<v9-8-11,11>>^ “Eis – disse ele – como vos há de tratar o vosso rei: tomará os vossos filhos para os seus carros e sua cavalaria, ou para correr diante do seu carro.

[[v9-8-12]]

^<<v9-8-12,12>>^ Fará deles chefes de mil e chefes de cinquenta, os empregarás em suas lavouras e em suas colheitas, na fabricação de suas armas de guerra e de seus carros.

[[v9-8-13]]

^<<v9-8-13,13>>^ Fará de vossas filhas suas perfumistas, cozinheiras e padeiras.

[[v9-8-14]]

^<<v9-8-14,14>>^ Tomará também o melhor de vossos campos, de vossas vinhas e de vossos olivais e os dará aos seus servos.

[[v9-8-15]]

^<<v9-8-15,15>>^ Tomará também o dízimo de vossas semeaduras e de vossas vinhas para dá-los aos seus eunucos e aos seus servos.

[[v9-8-16]]

^<<v9-8-16,16>>^ Tomará também vossos servos e vossas servas, vossos melhores bois e vossos jumentos, para empregá-los no seu trabalho.

[[v9-8-17]]

^<<v9-8-17,17>>^ Tomará ainda o dízimo de vossos rebanhos e vós mesmos sereis seus escravos.

[[v9-8-18]]

^<<v9-8-18,18>>^ E no dia em que clamardes ao Senhor por causa do rei, que vós mesmos escolhestes, o Senhor não vos ouvirá”.

[[v9-8-19]]

^<<v9-8-19,19>>^ O povo recusou ouvir a voz de Samuel. “Não – disseram eles –; é preciso que tenhamos um rei!

[[v9-8-20]]

^<<v9-8-20,20>>^ Queremos ser como todas as outras nações. Nosso rei nos julgará, marchará à nossa frente e será nosso chefe na guerra.”

[[v9-8-21]]

^<<v9-8-21,21>>^ Samuel ouviu todas as palavras do povo e referiu-as ao Senhor.

[[v9-8-22]]

^<<v9-8-22,22>>^ E respondeu-lhe o Senhor: “Ouve-os; dá-lhes um rei”. Samuel disse aos israelitas: “Volte cada um para a sua cidade”.

'''

xref:009-i-samuel/009-i-samuel-007.adoc#v9-7-0[&#60; Capítulo Anterior] | <<v9-8-0,Topo>> | xref:009-i-samuel/009-i-samuel-009.adoc#v9-9-0[Próximo Capítulo &#62;]