include::./index.adoc[]

[[v9-2-0]]
=== I Samuel, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 2 de 1 Samuel descreve uma oração de gratidão de Ana, a mãe de Samuel, pela benção de ter um filho depois de anos de infertilidade. Ela exalta a grandeza de Deus, que é o único que concede vida e poder para julgar e governar o mundo. Além disso, ela destaca a importância de seguir os caminhos do Senhor e ser humilde diante dele.
* Salmos 113:7-8: "Ele levanta do pó o necessitado e do monte de cinzas ergue o pobre; faz que se assente com príncipes, com os príncipes do seu povo." Assim como Ana foi levantada da sua condição de infertilidade para ter um filho, Deus é capaz de levantar aqueles que estão em condições difíceis e humildes para uma posição de honra e glória.
* Provérbios 15:33: "O temor do Senhor é a instrução da sabedoria; e diante da honra vai a humildade." Ana destaca a importância da humildade diante de Deus e Provérbios reforça que o temor do Senhor, ou seja, a reverência e respeito a Deus, é a chave para a sabedoria e humildade.
* Eclesiastes 7:14: "No dia da prosperidade, goza do bem, mas no dia da adversidade considera; porque também Deus fez a este em oposição àquele, para que o homem nada ache que tenha de vir depois dele." Ana agradece a Deus por sua benção, mas também reconhece que há momentos difíceis na vida e que Deus é o único que governa todas as coisas, tanto na prosperidade quanto na adversidade.
* Jeremias 9:23-24: "Assim diz o Senhor: Não se glorie o sábio na sua sabedoria, nem o forte na sua força, nem o rico nas suas riquezas; mas o que se gloriar, glorie-se nisto: em entender e conhecer-me, que eu sou o Senhor, que faço benevolência, juízo e justiça na terra; porque destas coisas me agrado, diz o Senhor." Ana reconhece que Deus é o único que governa o mundo e que não há nada para se orgulhar a não ser o conhecimento e entendimento de Deus. Jeremias reforça essa ideia, afirmando que a verdadeira glória está em conhecer a Deus e suas ações na terra.
****

[[v9-2-1]]

^<<v9-2-1,1>>^ Ana pronunciou esta prece: “Exulta o meu coração no Senhor, nele se eleva a minha força; a minha boca desafia os meus adversários, porque me alegro na vossa salvação.

[[v9-2-2]]

^<<v9-2-2,2>>^ Ninguém é santo como o Senhor. Não existe outro Deus, além de vós, nem rochedo semelhante ao nosso Deus.

[[v9-2-3]]

^<<v9-2-3,3>>^ Não multipliqueis palavras orgulhosas, não saia da vossa boca linguagem arrogante, porque o Senhor é um Deus que tudo sabe; por ele são pesadas as ações.

[[v9-2-4]]

^<<v9-2-4,4>>^ Quebra-se o arco dos fortes, enquanto os fracos se revestem de vigor.

[[v9-2-5]]

^<<v9-2-5,5>>^ Os abastados se assalariam para ganhar o que comer, enquanto os famintos são saciados. Sete vezes dá à luz a estéril, enquanto a mãe de numerosos filhos definha.

[[v9-2-6]]

^<<v9-2-6,6>>^ O Senhor dá a morte e a vida, faz descer à habitação dos mortos e de lá voltar.

[[v9-2-7]]

^<<v9-2-7,7>>^ O Senhor empobrece e enriquece; humilha e exalta.

[[v9-2-8]]

^<<v9-2-8,8>>^ Levanta do pó o mendigo, do esterco retira o indigente, para fazê-los sentar-se entre os nobres e outorgar-lhes um trono de honra, porque do Senhor são as colunas da terra. Sobre elas estabeleceu o mundo.

[[v9-2-9]]

^<<v9-2-9,9>>^ Dirige os passos dos seus fiéis, enquanto os ímpios perecem nas trevas; porque homem algum vence pela força.

[[v9-2-10]]

^<<v9-2-10,10>>^ Ó Senhor, sejam esmagados os vossos adversários! Dos céus troveje o Altíssimo contra eles, o Senhor julgue os últimos confins da terra! Dará força ao seu rei e engrandecerá o poder do seu ungido”.^&#42;1^

[[v9-2-11]]

^<<v9-2-11,11>>^ Elcana voltou para a sua casa em Ramá; o menino ficou a serviço do Senhor junto do sacerdote Heli.

[[v9-2-12]]

^<<v9-2-12,12>>^ Os filhos de Heli eram maus; não conheciam o Senhor.^&#42;1^

[[v9-2-13]]

^<<v9-2-13,13>>^ Eis como se comportavam para com o povo: Quando alguém imolava uma vítima, vinha o servo do sacerdote no momento em que se cozia a carne, com um garfo de três dentes,

[[v9-2-14]]

^<<v9-2-14,14>>^ e fincava-o na caldeira, na marmita, na panela ou no tacho e tudo o que o tridente trazia, tomava-o para o sacerdote. Assim faziam a todos os israelitas que vinham a Silo.

[[v9-2-15]]

^<<v9-2-15,15>>^ Antes que queimassem a gordura, vinha o servo do sacerdote dizer ao que sacrificava: “Dá-me a carne de assar para o sacerdote; ele não aceitará carne cozida, mas unicamente a carne crua”.

[[v9-2-16]]

^<<v9-2-16,16>>^ O homem respondia-lhe: “É preciso que se queime antes a gordura; depois disso, tomarás o que quiseres”. “Não – respondia o servo –, dá-me logo, senão tomarei à força.”

[[v9-2-17]]

^<<v9-2-17,17>>^ Era muito grande a iniquidade desses moços aos olhos de Deus, porque atraíam o desprezo sobre as ofertas feitas ao Senhor.

[[v9-2-18]]

^<<v9-2-18,18>>^ Entretanto, Samuel, ainda criança, servia diante do Senhor, trajando um efod de linho.

[[v9-2-19]]

^<<v9-2-19,19>>^ Sua mãe fazia-lhe cada ano uma pequena túnica, que lhe levava quando subia com o seu marido para o sacrifício anual.

[[v9-2-20]]

^<<v9-2-20,20>>^ Heli abençoava Elcana e sua mulher: “Conceda-te o Senhor filhos desta mulher em recompensa do dom que ela lhe faz!”. E voltavam para a sua casa.

[[v9-2-21]]

^<<v9-2-21,21>>^ O Senhor visitou Ana e ela concebeu, dando à luz três filhos e duas filhas. E o menino Samuel crescia na companhia do Senhor.

[[v9-2-22]]

^<<v9-2-22,22>>^ Heli era muito velho; sabia tudo o que faziam os seus filhos com os israelitas e como eles dormiam com as mulheres que estavam de serviço à entrada da tenda da reunião.

[[v9-2-23]]

^<<v9-2-23,23>>^ “Por que – dizia-lhes, procedeis desta forma? Sei que todo o povo fala de vossas desordens.

[[v9-2-24]]

^<<v9-2-24,24>>^ Não façais assim, meus filhos; não são boas as informações que me chegam a vosso respeito. Estais fazendo pecar o povo do Senhor.

[[v9-2-25]]

^<<v9-2-25,25>>^ Se um homem pecar contra outro, Deus o julga; se ele pecar, porém, contra o Senhor, quem intervirá a favor dele?” Mas não ouviam a voz do seu pai, porque Deus os queria perder.

[[v9-2-26]]

^<<v9-2-26,26>>^ Entretanto, o menino Samuel ia crescendo e era agradável tanto ao Senhor como aos homens.

[[v9-2-27]]

^<<v9-2-27,27>>^ Certo dia, um homem de Deus veio ter com Heli e disse-lhe da parte do Senhor: “Não me revelei eu claramente à casa de teu pai, quando eles estavam no Egito a serviço do faraó?

[[v9-2-28]]

^<<v9-2-28,28>>^ Escolhi os teus dentre todas as tribos de Israel para serem sacerdotes, subirem ao meu altar, queimarem o incenso e vestirem o efod diante de mim. Dei à casa de teu pai todos os sacrifícios oferecidos pelos israelitas.

[[v9-2-29]]

^<<v9-2-29,29>>^ Por que desprezais os meus sacrifícios e as minhas oblações que estabeleci em minha morada? Fazes mais caso dos teus filhos que de mim, engordando-vos com o melhor de todas as ofertas de meu povo de Israel.

[[v9-2-30]]

^<<v9-2-30,30>>^ Por isso, eis o que diz o Senhor, Deus de Israel: Eu tinha dito que a tua casa e a casa de teu pai serviriam para sempre diante de mim. Mas agora, diz o Senhor, não será mais assim. Eu honro aqueles que me honram e desprezo os que me desprezam.

[[v9-2-31]]

^<<v9-2-31,31>>^ Virão dias em que abaterei o teu vigor e o vigor da casa de teu pai, de tal modo que já não haverá ancião em tua casa.^&#42;1^

[[v9-2-32]]

^<<v9-2-32,32>>^ Israel estará cumulado de alegria e tu verás a angústia em tua casa. Não haverá jamais ancião em tua família!

[[v9-2-33]]

^<<v9-2-33,33>>^ Entretanto, não cortarei todos os teus do meu altar, para que se consumam de inveja os teus olhos e se desfaleça a tua alma; mas todos os outros morrerão na flor da idade.

[[v9-2-34]]

^<<v9-2-34,34>>^ O que vai acontecer aos teus dois filhos Hofni e Fineias, será para ti um sinal: morrerão ambos no mesmo dia.

[[v9-2-35]]

^<<v9-2-35,35>>^ Suscitarei para mim um sacerdote fiel, que procederá segundo o meu coração e minha vontade. Eu lhe construirei uma casa durável e ele andará sempre diante do meu ungido.^&#42;1^

[[v9-2-36]]

^<<v9-2-36,36>>^ Aqueles que sobreviverem de tua família irão prostrar-se diante dele por uma moeda de prata ou por um pedaço de pão, dizendo-lhe: ‘Admiti-me para alguma função sacerdotal, a fim de que eu tenha um bocado de pão para comer’.”

'''

xref:009-i-samuel/009-i-samuel-001.adoc#v9-1-0[&#60; Capítulo Anterior] | <<v9-2-0,Topo>> | xref:009-i-samuel/009-i-samuel-003.adoc#v9-3-0[Próximo Capítulo &#62;]