include::./index.adoc[]

[[v9-15-0]]
=== I Samuel, 15
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 15 de 1 Samuel narra a ordem de Deus para que Saul destrua completamente os amalequitas e tudo o que pertence a eles. No entanto, Saul não obedece completamente a Deus e poupa o rei amalequita e parte do gado. Como resultado, Deus retira a sua unção de Saul como rei de Israel. Abaixo estão cinco versículos relacionados com temas abordados neste capítulo:
* Provérbios 21:3: "Fazer justiça e julgar com retidão é mais aceitável ao Senhor do que oferecer-lhe sacrifício." Este versículo destaca a importância da obediência à vontade de Deus e da justiça, que é mais valiosa do que qualquer sacrifício que possamos oferecer.
* Isaías 1:19-20: "Se quiserdes e me ouvirdes, comereis o melhor desta terra. Mas, se recusardes e fordes rebeldes, sereis devorados à espada; porque a boca do Senhor o disse." Este versículo destaca a importância da obediência a Deus e a consequência da rebelião contra Ele.
* Oséias 6:6: "Porque eu desejo a misericórdia, e não o sacrifício; e o conhecimento de Deus, mais do que os holocaustos." Este versículo enfatiza que Deus valoriza a misericórdia e a obediência mais do que qualquer sacrifício.
* 1 Samuel 16:7: "Porque o Senhor não vê como vê o homem, pois o homem olha para o que está diante dos olhos, porém o Senhor olha para o coração." Este versículo fala sobre a importância do coração e da motivação por trás das ações, que é o que Deus valoriza.
* 1 João 2:15-17: "Não ameis o mundo, nem o que há no mundo. Se alguém ama o mundo, o amor do Pai não está nele. Porque tudo o que há no mundo, a concupiscência da carne, a concupiscência dos olhos e a soberba da vida, não vem do Pai, mas do mundo. O mundo passa, e a sua concupiscência; mas aquele que faz a vontade de Deus permanece para sempre." Este versículo fala sobre a importância de não amar o mundo e suas coisas passageiras, mas sim fazer a vontade de Deus e permanecer em Sua presença. A desobediência de Saul em 1 Samuel 15 mostra a importância da obediência a Deus e a consequência da desobediência.
****

[[v9-15-1]]

^<<v9-15-1,1>>^ Samuel disse a Saul: “O Senhor enviou-me para que te consagrasse rei de seu povo de Israel. Ouve agora o que diz o Senhor.

[[v9-15-2]]

^<<v9-15-2,2>>^ Assim fala o Senhor dos exércitos: Vou pedir contas a Amalec do que ele fez a Israel, pois lhe barrou o caminho, quando saiu do Egito.

[[v9-15-3]]

^<<v9-15-3,3>>^ Vai, pois, fere Amalec e vota ao interdito tudo o que lhe pertence, sem nada poupar: matarás homens e mulheres, crianças e meninos de peito, bois e ovelhas, camelos e jumentos”.

[[v9-15-4]]

^<<v9-15-4,4>>^ Saul comunicou isso ao povo e fez o seu recenseamento em Telém: havia duzentos mil homens de Israel e dez mil de Judá.

[[v9-15-5]]

^<<v9-15-5,5>>^ Saul avançou até a cidade de Amalec e pôs-se de emboscada no vale.

[[v9-15-6]]

^<<v9-15-6,6>>^ Disse aos cineus: “Retirai-vos, separai-vos dos amalecitas, não suceda que eu vos envolva com eles (no massacre), porque tratastes bem os israelitas quando saíram do Egito”. E os cineus separaram-se dos amalecitas.

[[v9-15-7]]

^<<v9-15-7,7>>^ Saul bateu os amalecitas desde Hévila até Sur, que está ao oriente do Egito.

[[v9-15-8]]

^<<v9-15-8,8>>^ Tomou vivo Agag, rei de Amalec, e votou todo o povo ao interdito, passando-o a fio de espada.

[[v9-15-9]]

^<<v9-15-9,9>>^ Mas, Saul e seus homens pouparam a Agag assim como o melhor do rebanho miúdo e do grande, os animais cevados e os cordeiros e tudo o que havia de melhor; não quiseram votá-los ao interdito. Só exterminaram o que era ordinário e sem valor.

[[v9-15-10]]

^<<v9-15-10,10>>^ O Senhor disse a Samuel:

[[v9-15-11]]

^<<v9-15-11,11>>^ “Arrependo-me de ter feito rei a Saul; ele se desviou de mim e não executou as minhas ordens”. Samuel irritou-se com isso e clamou ao Senhor durante toda a noite.

[[v9-15-12]]

^<<v9-15-12,12>>^ Na manhã seguinte, indo ao encontro de Saul, alguém veio dizer-lhe: “Saul chegou ao Carmelo e erigiu ali uma estela, retomando em seguida o seu caminho para Gálgala”.

[[v9-15-13]]

^<<v9-15-13,13>>^ Samuel foi ter com ele. Saul disse-lhe: “Deus te abençoe! Cumpri a ordem do Senhor”.

[[v9-15-14]]

^<<v9-15-14,14>>^ Samuel disse-lhe: “Mas que balidos de ovelhas são esses que ressoam aos meus ouvidos e esses mugidos de gado que ouço?”.

[[v9-15-15]]

^<<v9-15-15,15>>^ “É a presa tomada aos amalecitas” – respondeu Saul –. “O povo poupou o melhor das ovelhas e dos bois para os sacrificar ao Senhor, teu Deus; o resto, votamo-lo ao interdito.”

[[v9-15-16]]

^<<v9-15-16,16>>^ Samuel disse-lhe: ‘‘Basta! Vou comunicar-te o que o Senhor me disse esta noite.” “Fala” – disse Saul.

[[v9-15-17]]

^<<v9-15-17,17>>^ E Samuel: “Por pequeno que foste aos teus próprios olhos, acaso não te tornaste o chefe das tribos de Israel e não te consagrou o Senhor rei de Israel?

[[v9-15-18]]

^<<v9-15-18,18>>^ O Senhor te havia dado uma ordem e te havia dito que votasses ao interdito esses pecadores, os amalecitas, combatendo-os até o completo extermínio.

[[v9-15-19]]

^<<v9-15-19,19>>^ Por que não ouviste a sua voz? Por que te lançaste sobre os despojos fazendo o mal aos olhos do Senhor?”.

[[v9-15-20]]

^<<v9-15-20,20>>^ “Mas eu obedeci à voz do Senhor – replicou Saul –, fui pelo caminho que ele me traçou, trouxe Agag, rei de Amalec, e votei ao interdito os amalecitas.

[[v9-15-21]]

^<<v9-15-21,21>>^ O povo somente tomou dos despojos algumas ovelhas e bois, à guisa de primícias do interdito, para sacrificá-los ao Senhor, teu Deus, em Gálgala.”

[[v9-15-22]]

^<<v9-15-22,22>>^ Samuel replicou-lhe: “Acaso o Senhor se compraz tanto nos holocaustos e sacrifícios como na obediência à sua voz? A obediência é melhor que o sacrifício e a submissão vale mais que a gordura dos carneiros.

[[v9-15-23]]

^<<v9-15-23,23>>^ A rebelião é tão culpável quanto a superstição; a desobediência é como o pecado de idolatria. Pois que rejeitaste a palavra do Senhor, também ele te rejeita e te despoja da realeza!”.

[[v9-15-24]]

^<<v9-15-24,24>>^ Saul disse: “Pequei! Transgredi a ordem do Senhor e as tuas instruções, pois tive medo do povo e ouvi a sua voz.

[[v9-15-25]]

^<<v9-15-25,25>>^ Agora, peço-te, perdoa o meu pecado e volta comigo para que eu adore o Senhor”.

[[v9-15-26]]

^<<v9-15-26,26>>^ “Não voltarei contigo! – exclamou Samuel –. “Rejeitaste a palavra do Senhor, por isso o Senhor te rejeita e não quer mais que sejas rei de Israel.”

[[v9-15-27]]

^<<v9-15-27,27>>^ Samuel voltou-se e ia se retirando, mas Saul agarrou-o pela ponta do manto, e ele se rasgou.

[[v9-15-28]]

^<<v9-15-28,28>>^ Samuel disse-lhe: “Assim o Senhor arranca hoje de ti a realeza sobre Israel, a fim de dá-la a outro melhor do que tu.

[[v9-15-29]]

^<<v9-15-29,29>>^ Aquele que é a verdade de Israel não mente, nem se arrepende, pois não é um homem para se arrepender”.

[[v9-15-30]]

^<<v9-15-30,30>>^ Saul respondeu: “Pequei, mas rogo-te que (continues) a honrar-me na presença dos anciãos de meu povo e diante de Israel. Volta comigo, para eu adorar o Senhor, teu Deus!”.

[[v9-15-31]]

^<<v9-15-31,31>>^ Samuel voltou, pois, com o rei e este adorou o Senhor.

[[v9-15-32]]

^<<v9-15-32,32>>^ Samuel disse: “Trazei-me Agag, rei de Amalec”. Aproximou-se Agag, cheio de alegria, dizendo: “Certamente passou a amargura da morte!”.

[[v9-15-33]]

^<<v9-15-33,33>>^ “Tua espada – disse-lhe Samuel – privou as mulheres de seus filhos; agora, é tua mãe que será uma mulher sem filho.” E Samuel fê-lo em pedaços diante do Senhor, em Gálgala.

[[v9-15-34]]

^<<v9-15-34,34>>^ Depois disso, Samuel retirou-se para Ramá e Saul voltou para a sua casa, em Gabaá de Saul.

[[v9-15-35]]

^<<v9-15-35,35>>^ O profeta não tornou mais a ver Saul até o dia de sua morte. Samuel afligia-se por causa de Saul, por se ter o Senhor arrependido de tê-lo feito rei de Israel.

'''

xref:009-i-samuel/009-i-samuel-014.adoc#v9-14-0[&#60; Capítulo Anterior] | <<v9-15-0,Topo>> | xref:009-i-samuel/009-i-samuel-016.adoc#v9-16-0[Próximo Capítulo &#62;]