include::./index.adoc[]

[[v9-3-0]]
=== I Samuel, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Samuel 3 narra a chamada de Samuel para ser um profeta de Deus. Deus falou com Samuel pela primeira vez quando ele era ainda uma criança servindo no templo de Deus. O capítulo mostra a importância de ouvir a voz de Deus e obedecê-la. Aqui estão cinco versículos relacionados com temas abordados neste capítulo:
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." Este versículo destaca a importância de confiar em Deus e ouvir Sua orientação, em vez de confiar em nossa própria compreensão limitada.
* Isaías 30:21: "Quando vocês se desviarem para a direita ou para a esquerda, suas orelhas ouvirão uma voz atrás de vocês, dizendo: "Este é o caminho; sigam-no"." Este versículo fala sobre como Deus guia Seu povo, mesmo quando eles se desviam do caminho certo, Ele chama para que voltem ao caminho certo.
* João 10:27: "As minhas ovelhas ouvem a minha voz; eu as conheço, e elas me seguem." Este versículo mostra que, assim como Samuel ouviu a voz de Deus, aqueles que são verdadeiramente de Deus ouvem e seguem a Sua voz.
* Atos 9:6: "Levante-se, entre na cidade e lhe será dito o que você deve fazer". Este versículo mostra como Deus chamou Saulo, mais tarde conhecido como Paulo, para o ministério. Ele obedeceu a voz de Deus, seguindo as instruções dadas a ele.
* Tiago 1:22: "Sejam praticantes da palavra, e não apenas ouvintes, enganando-se a si mesmos." Este versículo enfatiza a importância de não apenas ouvir a palavra de Deus, mas também obedecê-la e colocá-la em prática. Isso é especialmente importante quando se trata de ouvir a voz de Deus e seguir Sua orientação.
****

[[v9-3-1]]

^<<v9-3-1,1>>^ O jovem Samuel servia ao Senhor sob os olhos de Heli. A palavra do Senhor era rara naqueles dias e as visões não eram frequentes.

[[v9-3-2]]

^<<v9-3-2,2>>^ Ora, aconteceu certo dia que Heli estava deitado (seus olhos tinham se enfraquecido e ele mal podia ver)

[[v9-3-3]]

^<<v9-3-3,3>>^ e a lâmpada de Deus ainda não se apagara. Samuel repousava no Templo do Senhor, onde se encontrava a arca de Deus.

[[v9-3-4]]

^<<v9-3-4,4>>^ O Senhor chamou Samuel, o qual respondeu: “Eis-me aqui”.

[[v9-3-5]]

^<<v9-3-5,5>>^ Samuel correu para junto de Heli e disse: “Eis-me aqui: chamaste-me”. “Não te chamei, meu filho, torna a deitar-te.” Ele foi e deitou-se.

[[v9-3-6]]

^<<v9-3-6,6>>^ O Senhor chamou de novo Samuel. Este levantou-se e veio dizer a Heli: “Eis-me aqui, tu me chamaste”. “Eu não te chamei, meu filho, torna a deitar-te.”

[[v9-3-7]]

^<<v9-3-7,7>>^ Samuel ainda não conhecia o Senhor; a palavra do Senhor não lhe tinha sido ainda manifestada.

[[v9-3-8]]

^<<v9-3-8,8>>^ Pela terceira vez, o Senhor chamou Samuel, que se levantou e foi ter com Heli: “Eis-me aqui, tu me chamaste”. Compreendeu então Heli que era o Senhor quem chamava o menino.

[[v9-3-9]]

^<<v9-3-9,9>>^ “Vai e torna a deitar-te – disse-lhe ele – e se ouvires que te chamam de novo, responde: ‘Falai, Senhor, que vosso servo escuta!’.” Voltou Samuel e deitou-se.

[[v9-3-10]]

^<<v9-3-10,10>>^ Veio o Senhor, pôs-se junto dele e chamou-o como das outras vezes: “Samuel! Samuel!”. “Falai – respondeu o menino –, que vosso servo escuta!”

[[v9-3-11]]

^<<v9-3-11,11>>^ O Senhor disse a Samuel: “Eis que vou fazer uma tal coisa em Israel, que a todo o que a ouvir ficará retinindo os ouvidos.

[[v9-3-12]]

^<<v9-3-12,12>>^ Naquele dia, cumprirei contra Heli todas as ameaças que pronunciei contra a sua casa. Começarei e irei até o fim.

[[v9-3-13]]

^<<v9-3-13,13>>^ Anunciei-lhe que eu condenaria para sempre a sua família, por causa dos crimes que ele sabia que os seus filhos cometiam e não os corrigiu.

[[v9-3-14]]

^<<v9-3-14,14>>^ Por isso, jurei à casa de Heli que a sua culpa jamais seria expiada, nem com sacrifícios nem com oblações”.

[[v9-3-15]]

^<<v9-3-15,15>>^ Samuel ficou deitado até pela manhã, quando abriu as portas da casa do Senhor. Ele temia contar a visão a Heli.

[[v9-3-16]]

^<<v9-3-16,16>>^ Heli, porém, chamou-o e disse: “Samuel, meu filho!”. “Eis-me aqui” – respondeu ele.

[[v9-3-17]]

^<<v9-3-17,17>>^ E Heli: “Que te disse ele? Não me ocultes nada. Deus te trate com toda a severidade, se me encobrires algo de tudo o que ele te disse”.

[[v9-3-18]]

^<<v9-3-18,18>>^ Então, Samuel contou-lhe tudo, sem nada ocultar. Heli exclamou: “O Senhor fará o que lhe parecer melhor”.

[[v9-3-19]]

^<<v9-3-19,19>>^ Samuel crescia e o Senhor estava com ele e não negligenciava nenhuma de suas palavras.

[[v9-3-20]]

^<<v9-3-20,20>>^ Todo o Israel, desde Dã até Bersabeia, reconheceu que Samuel era um profeta do Senhor digno de fé.

[[v9-3-21]]

^<<v9-3-21,21>>^ E o Senhor continuou a se manifestar em Silo. É ali que o Senhor aparecia a Samuel, descobrindo-lhe sua palavra.

'''

xref:009-i-samuel/009-i-samuel-002.adoc#v9-2-0[&#60; Capítulo Anterior] | <<v9-3-0,Topo>> | xref:009-i-samuel/009-i-samuel-004.adoc#v9-4-0[Próximo Capítulo &#62;]