include::./index.adoc[]

[[v42-3-0]]
=== Habacuc, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 3 de Habacuque é uma oração do profeta, em que ele expressa sua confiança em Deus, mesmo diante das dificuldades e adversidades que o povo de Judá estava enfrentando. Ele reconhece a grandeza e o poder de Deus e pede que Ele intervenha para salvar o Seu povo. Abaixo estão cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em Habacuque 3:
* Salmos 18:2: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio. Ele é o meu escudo e o poder que me salva, a minha torre alta." Este verso fala da confiança em Deus como protetor e salvador, assim como Habacuque expressa em sua oração.
* Salmos 46:1: "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade." Este verso reforça a ideia de que Deus é um abrigo seguro e constante para aqueles que confiam Nele, mesmo quando enfrentam dificuldades.
* Isaías 40:28: "Vocês não sabem, nunca ouviram? O Senhor é o Deus eterno, o Criador de toda a terra. Ele não se cansa nem fica exausto; sua sabedoria é insondável." Este verso destaca a grandeza e o poder de Deus, temas centrais da oração de Habacuque.
* Salmo 144:5: "Desce, Senhor, dos céus; toca os montes, para que fumeguem." Este verso faz um pedido para que Deus intervenha na terra, assim como Habacuque pede que Ele salve o Seu povo.
* Isaías 35:4: "Digam aos desanimados de coração: 'Sejam fortes, não tenham medo! Vejam o seu Deus: a vingança vem, a retribuição divina; ele vem para salvá-los.'" Este verso traz uma mensagem de encorajamento para aqueles que estão passando por dificuldades, assim como Habacuque busca encorajar o povo de Judá em sua oração.
****

[[v42-3-1]]

^<<v42-3-1,1>>^ Oração do profeta Habacuc. Em tom de lamentação.

[[v42-3-2]]

^<<v42-3-2,2>>^ Senhor, eu ouvi a vossa mensagem e enchi-me de temor diante de vossa obra. Fazei-a reviver no decorrer das idades, no decorrer das idades tornai-a manifesta. Em vossa ira, lembrai-vos da misericórdia!

[[v42-3-3]]

^<<v42-3-3,3>>^ Deus vem de Temã, o Santo vem do monte de Farã. Sua majestade cobre os céus, e a terra se enche de sua glória.^&#42;1^

[[v42-3-4]]

^<<v42-3-4,4>>^ Seu esplendor é deslumbrante como a luz, de suas mãos brotam raios; ali está o véu de seu poder.

[[v42-3-5]]

^<<v42-3-5,5>>^ A calamidade avança diante dele, a febre ardente lhe segue as pegadas.

[[v42-3-6]]

^<<v42-3-6,6>>^ Levantando-se, sacode ele a terra, olha e faz tremer as nações. Deslocam-se as montanhas eternas, desfazem-se as colinas antigas, e lhe abrem amplos caminhos!

[[v42-3-7]]

^<<v42-3-7,7>>^ Vejo em aflição as tendas da Etiópia, tremem os pavilhões de Madiã.

[[v42-3-8]]

^<<v42-3-8,8>>^ Porventura é contra os rios que se inflama o Senhor, é contra os rios que se desencadeia a vossa ira? Ou é contra o mar que se acende o vosso furor, quando montais em vossos cavalos e em vossos carros triunfais?

[[v42-3-9]]

^<<v42-3-9,9>>^ Mostra-se desnudado o vosso arco, vossas flechas são as palavras que jurastes, fendeis a terra e dela saem torrentes.^&#42;1^

[[v42-3-10]]

^<<v42-3-10,10>>^ À vossa vista tremem os montes, cai uma tromba-d’água, o abismo faz ouvir a sua voz, e levanta as mãos para o alto.

[[v42-3-11]]

^<<v42-3-11,11>>^ O sol e a lua ficam em sua morada, ao verem a luz de vossas flechas que voam, e o brilho fulgurante de vossa lança.

[[v42-3-12]]

^<<v42-3-12,12>>^ Vós calcais a terra em vosso furor, com a vossa cólera esmagais as nações.

[[v42-3-13]]

^<<v42-3-13,13>>^ Partistes para a guerra, para a salvação do vosso povo, para a salvação do vosso Ungido. Derrubastes o teto da casa do ímpio, pusestes a nu os seus fundamentos até a base.^&#42;1^

[[v42-3-14]]

^<<v42-3-14,14>>^ Transpassastes com vossas setas a cabeça dos príncipes que se precipitavam para nos dispersar, soltando gritos de alegria, como para devorar o infeliz em seu retiro.^&#42;1^

[[v42-3-15]]

^<<v42-3-15,15>>^ Lançastes vossos cavalos através do mar no turbilhão das muitas águas.

[[v42-3-16]]

^<<v42-3-16,16>>^ Ao ouvir esse tumulto, minhas entranhas comoveram-se; ao seu ruído meus lábios tremeram; a cárie penetra nos meus ossos, e meus passos vacilam debaixo de mim. Esperarei em silêncio o dia da aflição, que se há de levantar sobre o povo que nos oprime,^&#42;1^

[[v42-3-17]]

^<<v42-3-17,17>>^ porque então a figueira não brotará, nulo será o produto das vinhas, faltará o fruto da oliveira, e os campos não darão de comer. Não haverá mais ovelhas no aprisco, nem gado nos estábulos.

[[v42-3-18]]

^<<v42-3-18,18>>^ Eu, porém, me regozijarei no Senhor. Encontrarei minha alegria no Deus de minha salvação.

[[v42-3-19]]

^<<v42-3-19,19>>^ Javé, meu Senhor, é minha força; ele torna meus pés ágeis como os da corça, e me faz andar sobre os cimos.^&#42;1^ Ao mestre do canto. Para instrumentos de corda.

'''

xref:042-habacuc/042-habacuc-002.adoc#v42-2-0[&#60; Capítulo Anterior] | <<v42-3-0,Topo>> | xref:043-sofonias/043-sofonias-001.adoc#v43-1-0[Próximo Capítulo &#62;]