include::./index.adoc[]

[[v68-2-0]]
=== II São Pedro, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 2 de 2 Pedro trata principalmente dos falsos profetas e mestres que surgiriam no meio do povo cristão, trazendo heresias e promovendo a libertinagem. Eles negariam a soberania de Deus e a redenção em Jesus Cristo, levando muitos a seguir suas práticas perniciosas. Abaixo seguem cinco versículos relacionados com esses temas, excluindo os versículos de 2 São Pedro 2:
* Mateus 7:15: "Acautelai-vos dos falsos profetas, que se vos apresentam disfarçados em ovelhas, mas por dentro são lobos roubadores." Jesus Cristo advertiu os seus discípulos sobre a presença de falsos profetas, que se apresentariam como líderes espirituais, mas que, na verdade, buscariam desviar as pessoas da verdade.
* 2 Coríntios 11:13-15: "Porque tais falsos apóstolos são obreiros fraudulentos, transformando-se em apóstolos de Cristo. E não é de admirar, porque o próprio Satanás se transforma em anjo de luz. Não é muito, pois, que os seus próprios ministros se transformem em ministros de justiça; e o fim deles será conforme as suas obras." O apóstolo Paulo também alertou sobre a presença de falsos apóstolos, que fingiam serem enviados por Cristo, mas que na verdade eram enganadores que buscavam enganar o povo de Deus.
* 1 João 4:1: "Amados, não creiais em todo espírito, mas provai se os espíritos vêm de Deus, porque muitos falsos profetas têm saído pelo mundo." O apóstolo João também instruiu os cristãos a examinarem cuidadosamente os ensinamentos que ouviam, a fim de verificar se vinham de Deus ou de falsos profetas.
* 1 Timóteo 4:1: "Ora, o Espírito diz expressamente que, nos últimos tempos, alguns apostatarão da fé, por obedecerem a espíritos enganadores e a ensinos de demônios." O apóstolo Paulo novamente alertou sobre a presença de ensinamentos falsos que seriam promovidos por pessoas que não seguiam a Deus, mas a espíritos enganadores e a ensinamentos demoníacos.
* Judas 1:4: "Porque certos homens, cuja condenação já estava sentenciada há muito tempo, infiltraram-se dissimuladamente no meio de vocês. Estes são ímpios, que transformam a graça de nosso Deus em libertinagem e negam Jesus Cristo, nosso único Soberano e Senhor." O livro de Judas também fala sobre a presença de falsos mestres que negavam a verdade sobre Jesus Cristo e promoviam práticas libertinas.
****

[[v68-2-1]]

^<<v68-2-1,1>>^ Assim como houve entre o povo falsos profetas, assim também haverá entre vós falsos doutores, que introduzirão disfarçadamente seitas perniciosas. Eles, renegando assim o Senhor que os resgatou, atrairão sobre si uma ruína repentina.

[[v68-2-2]]

^<<v68-2-2,2>>^ Muitos os seguirão nas suas desordens e serão desse modo a causa de o caminho da verdade ser caluniado.

[[v68-2-3]]

^<<v68-2-3,3>>^ Movidos por cobiça, eles vos hão de explorar por palavras cheias de astúcia. Há muito tempo a condenação os ameaça, e a sua ruína não dorme.

[[v68-2-4]]

^<<v68-2-4,4>>^ Pois se Deus não poupou os anjos que pecaram, mas os precipitou nos abismos tenebrosos do inferno onde os reserva para o julgamento;

[[v68-2-5]]

^<<v68-2-5,5>>^ se não poupou o mundo antigo, e só preservou oito pessoas, dentre as quais Noé, esse pregador da justiça, quando desencadeou o dilúvio sobre um mundo de ímpios;

[[v68-2-6]]

^<<v68-2-6,6>>^ se condenou à destruição e reduziu a cinzas as cidades de Sodoma e Gomorra para servir de exemplo para os ímpios do porvir;

[[v68-2-7]]

^<<v68-2-7,7>>^ se, enfim, livrou o justo Ló, revoltado com a vida dissoluta daquela gente perversa

[[v68-2-8]]

^<<v68-2-8,8>>^ (esse justo que habitava no meio deles sentia cada dia atormentada sua alma virtuosa, pelo que via e ouvia dos seus procedimentos infames),

[[v68-2-9]]

^<<v68-2-9,9>>^ é porque o Senhor sabe livrar das provações os homens piedosos e reservar os ímpios para serem castigados no dia do juízo,

[[v68-2-10]]

^<<v68-2-10,10>>^ principalmente aqueles que correm com desejos impuros atrás dos prazeres da carne e desprezam a autoridade. Audaciosos, arrogantes, não temem falar injuriosamente das glórias,^&#42;1^

[[v68-2-11]]

^<<v68-2-11,11>>^ embora os anjos, superiores em força e poder, não pronunciem contra elas, aos olhos do Senhor, o julgamento injurioso.

[[v68-2-12]]

^<<v68-2-12,12>>^ Mas estes, quais brutos destinados pela Lei natural para a presa e para a perdição, injuriam o que ignoram, e assim da mesma forma perecerão. Esse será o salário de sua iniquidade.

[[v68-2-13]]

^<<v68-2-13,13>>^ Encontram as suas delícias em se entregar em pleno dia às suas libertinagens. Homens pervertidos e imundos, sentem prazer em enganar, enquanto se banqueteiam convosco.

[[v68-2-14]]

^<<v68-2-14,14>>^ Têm os olhos cheios de adultério e são insaciáveis no pecar. Seduzem pelos seus atrativos as almas inconstantes; têm o coração acostumado à cobiça; são filhos da maldição.

[[v68-2-15]]

^<<v68-2-15,15>>^ Deixaram o caminho reto, para se extraviarem no caminho de Balaão, filho de Bosor, que amou o salário da iniquidade.

[[v68-2-16]]

^<<v68-2-16,16>>^ Mas foi repreendido pela sua desobediência: um animal mudo, falando com voz humana, refreou a loucura do profeta.

[[v68-2-17]]

^<<v68-2-17,17>>^ Estes são fontes sem água e nuvens agitadas por turbilhões, destinados à profundeza das trevas.

[[v68-2-18]]

^<<v68-2-18,18>>^ Com palavras tão vãs quanto enganadoras, atraem pelas paixões carnais e pela devassidão aqueles que mal acabam de escapar dos homens que vivem no erro.

[[v68-2-19]]

^<<v68-2-19,19>>^ Prometem-lhes a liberdade, quando eles mesmos são escravos da corrupção, pois o homem é feito escravo daquele que o venceu.

[[v68-2-20]]

^<<v68-2-20,20>>^ Com efeito, se aqueles que renunciaram às corrupções do mundo pelo conhecimento de Jesus Cristo, nosso Senhor e Salvador, nelas se deixam de novo enredar e vencer, seu último estado torna-se pior do que o primeiro.

[[v68-2-21]]

^<<v68-2-21,21>>^ Melhor fora não terem conhecido o caminho da justiça do que, depois de tê-lo conhecido, tornarem atrás, abandonando a Lei santa que lhes foi ensinada.

[[v68-2-22]]

^<<v68-2-22,22>>^ Aconteceu-lhes o que diz com razão o provérbio: O cão voltou ao seu vômito (Pr 26,11); e: A porca lavada volta a revolver-se no lamaçal.

'''

xref:068-ii-sao-pedro/068-ii-sao-pedro-001.adoc#v68-1-0[&#60; Capítulo Anterior] | <<v68-2-0,Topo>> | xref:068-ii-sao-pedro/068-ii-sao-pedro-003.adoc#v68-3-0[Próximo Capítulo &#62;]