include::./index.adoc[]

[[v33-38-0]]
=== Ezequiel, 38
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 38 descreve uma invasão liderada por Gogue da terra de Magogue contra Israel. Os versículos abaixo são relacionados com a temática do capítulo:
* Apocalipse 20:8: "E sairá a enganar as nações que estão sobre os quatro cantos da terra, Gogue e Magogue, cujo número é como a areia do mar, a fim de ajuntá-las para a batalha." Este versículo faz referência a Gogue e Magogue como uma aliança de nações enganadas por Satanás e que se juntam para a batalha final contra Deus.
* Joel 3:9-11: "Proclamai isto entre as nações; preparai a guerra, suscitai os fortes; cheguem-se, subam todos os homens de guerra. Forjai espadas das vossas relhas de arado, e lanças das vossas podadeiras; diga o fraco: Eu sou forte. Ajuntai-vos e vinde, todos os povos em redor, e congregai-vos; para ali trazei os teus poderosos." Este versículo fala de um convite para que as nações se preparem para a guerra e se unam contra Israel.
* Ezequiel 39:6: "E enviarei um fogo sobre Magogue, e entre os que habitam seguros nas ilhas; e saberão que eu sou o Senhor." Este versículo fala da intervenção de Deus na batalha contra Magogue, mostrando que Ele é o Senhor.
* Zacarias 14:2: "Porque eu ajuntarei todas as nações para a peleja contra Jerusalém; e a cidade será tomada, e as casas serão saqueadas, e as mulheres forçadas; e metade da cidade sairá para o cativeiro, mas o restante do povo não será extirpado da cidade." Este versículo fala de uma invasão contra Jerusalém, que parece estar relacionada com o tema de Ezequiel 38.
* Apocalipse 16:14: "Pois são espíritos de demônios, que operam sinais; os quais vão ao encontro dos reis de todo o mundo para os congregar para a batalha do grande dia do Deus Todo-Poderoso." Este versículo descreve espíritos malignos que convocam as nações para a batalha final, o que se assemelha ao que é descrito em Ezequiel 38.
****

[[v33-38-1]]

^<<v33-38-1,1>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-38-2]]

^<<v33-38-2,2>>^ “Filho do homem, volta os teus olhos contra Gog, na terra de Magog, príncipe soberano de Mosoc e de Tubal, e profere contra ele o seguinte oráculo:^&#42;1^

[[v33-38-3]]

^<<v33-38-3,3>>^ Eis o que diz o Senhor Javé: é contra ti que venho, Gog, príncipe soberano de Mosoc e de Tubal.

[[v33-38-4]]

^<<v33-38-4,4>>^ Vou te fazer ir e vir. Vou armar tua goela de ganchos, vou preparar-te uma expedição com todo o teu exército, cavalos e cavaleiros, todos perfeitamente equipados, horda imensa, munida de escudos, de broquéis e de espadas.

[[v33-38-5]]

^<<v33-38-5,5>>^ Ela terá por aliados a Pérsia, a Etiópia e a Líbia, equipados de escudos e capacetes.

[[v33-38-6]]

^<<v33-38-6,6>>^ Marcharão contigo Gomer e todas as suas tropas, o povo armado de Bet-Togorma, dos confins do Norte, povos numerosos.^&#42;1^

[[v33-38-7]]

^<<v33-38-7,7>>^ Estai atentos, preparai-vos bem, tu e todas as hordas que se agrupam em derredor de ti. Fica à minha disposição.^&#42;1^

[[v33-38-8]]

^<<v33-38-8,8>>^ Ao fim de considerável lapso de tempo, receberás ordem de marcha. Com o correr dos anos, irás contra uma terra, cujos habitantes, subtraídos ao massacre, se acham reunidos de países diversos, nas montanhas de Israel, por tão longo tempo desertas, mas onde vive agora tranquilamente a nação segregada do meio dos povos.

[[v33-38-9]]

^<<v33-38-9,9>>^ Tu te levantarás como uma tempestade, tu e a multidão das tropas de povos diversos que te acompanham, como uma nuvem de tempestade para cobrir a terra.

[[v33-38-10]]

^<<v33-38-10,10>>^ Eis o que diz o Senhor Javé: naquele dia, projetos nascerão em teu coração, e conceberás desígnios perversos.

[[v33-38-11]]

^<<v33-38-11,11>>^ Vou atacar, dirás tu, uma terra indefesa, gente pacífica, que vive tranquilamente em cidades sem muralhas, sem portas, sem ferrolhos.

[[v33-38-12]]

^<<v33-38-12,12>>^ Irás, pois, ali pilhar, para fazer despojo, para pôr a mão sobre essas ruínas agora repovoadas, sobre uma população recolhida dentre pagãos, que, residindo no umbigo da terra, se ocupa agora com a criação e o comércio.^&#42;1^

[[v33-38-13]]

^<<v33-38-13,13>>^ Sabá, Dadã, mercadores de Társis e todos os seus jovens leões te hão de dizer: é para pilhar que vens tu? É para fazer espólio que reuniste as tuas hordas, para levar prata e ouro, para tomar rebanhos e bens, para fazer imensa pilhagem?

[[v33-38-14]]

^<<v33-38-14,14>>^ Eis por que, ó filho do homem, proferirás contra Gog o oráculo seguinte: eis o que diz o Senhor Javé: não é acaso naquele dia, quando o meu povo de Israel habitar sua terra com toda a segurança, que tu te meterás em agitação?

[[v33-38-15]]

^<<v33-38-15,15>>^ Virás de tua terra, dos confins do Norte, seguido de teu poderoso exército, tua horda imensa de cavaleiros.

[[v33-38-16]]

^<<v33-38-16,16>>^ Atacarás o meu povo de Israel como uma nuvem de tempestade que vem cobrir a terra. Isso acontecerá no decorrer dos tempos: eu te farei vir contra a minha terra, a fim de que as nações aprendam a conhecer-me, quando sob meus olhares, ó Gog, eu tiver manifestado a minha santidade pela maneira como eu te tratar.

[[v33-38-17]]

^<<v33-38-17,17>>^ Eis o que diz o Senhor Javé: tu és aquele de quem falei outrora por intermédio dos meus servidores, os profetas de Israel, que, naquele tempo, durante anos, predisseram que eu te enviaria contra eles.

[[v33-38-18]]

^<<v33-38-18,18>>^ Naquele dia futuro, o dia em que Gog penetrar no solo de Israel – oráculo do Senhor Javé –, o furor me subirá ao nariz.

[[v33-38-19]]

^<<v33-38-19,19>>^ Na explosão de meu ciúme e na exasperação de minha raiva, eu o afirmo, naquele dia, eu o juro, haverá terrível abalo na terra de Israel.

[[v33-38-20]]

^<<v33-38-20,20>>^ À minha vista, tremerão de pavor os peixes do mar e os pássaros do céu, os animais dos campos e os répteis que se movem pela terra, assim como todos os homens que vivem na crosta terrestre. As montanhas desmoronarão, os rochedos cairão e todas as muralhas serão derrubadas por terra.

[[v33-38-21]]

^<<v33-38-21,21>>^ Chamarei contra Gog toda espécie de terríveis flagelos – oráculo do Senhor Javé. Cada qual voltará a espada contra seu companheiro.

[[v33-38-22]]

^<<v33-38-22,22>>^ Farei sua condenação com a peste mortífera, farei chover sobre ele, suas tropas e sobre as hordas que o acompanham um aguaceiro, saraiva, fogo e enxofre.

[[v33-38-23]]

^<<v33-38-23,23>>^ É assim que manifestarei a minha glória e a minha santidade, revelando-me aos olhos de inúmeras nações, a fim de que saibam que eu sou o Senhor”.

'''

xref:033-ezequiel/033-ezequiel-037.adoc#v33-37-0[&#60; Capítulo Anterior] | <<v33-38-0,Topo>> | xref:033-ezequiel/033-ezequiel-039.adoc#v33-39-0[Próximo Capítulo &#62;]