include::./index.adoc[]

[[v33-28-0]]
=== Ezequiel, 28
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 28 fala sobre o julgamento de Tiro, uma cidade que se orgulhava de sua riqueza e sabedoria, mas que havia se desviado dos caminhos de Deus. O capítulo também descreve a queda do rei de Tiro, que se considerava um deus e se vangloriava de sua grandeza. Os versículos selecionados abaixo abordam temas relacionados ao orgulho, queda e julgamento de Tiro, bem como à soberania de Deus sobre todas as nações.
* Isaías 2:12: "Porque o dia do Senhor dos Exércitos virá contra todo o soberbo e altivo, e contra todo o que se exalta, para que seja abatido" Este versículo fala sobre o julgamento de Deus contra aqueles que se exaltam e se orgulham.
* Provérbios 16:18: "A soberba precede a ruína, e a altivez do espírito precede a queda" Este versículo fala sobre a conexão entre o orgulho e a queda, algo que é evidente na queda de Tiro.
* Jeremias 25:15-17: "Porque assim me disse o Senhor, Deus de Israel: Toma da minha mão este cálice de vinho da ira, e dá de beber dele a todas as nações, às quais eu te enviar. Para que bebam, e andem cambaleando, e enlouqueçam, por causa da espada que eu envio entre eles. Então tomei o cálice da mão do Senhor, e o dei de beber a todas as nações" Este versículo fala sobre a soberania de Deus sobre todas as nações e sobre a punição que ele traz sobre aqueles que se desviam de seus caminhos.
* Salmos 52:7: "Eis aqui o homem que não tomou a Deus por sua fortaleza; antes confiou na abundância das suas riquezas, e se fortaleceu na sua malícia" Este versículo fala sobre a tolice de confiar na riqueza e na malícia em vez de confiar em Deus, algo que era evidente na vida dos habitantes de Tiro.
* Obadias 1:3-4: "O orgulho do teu coração te enganou, tu que habitas nas fendas das rochas, cuja habitação está nas alturas; que dizes no teu coração: Quem me derrubará por terra? Se elevares o teu ninho como águia, dali te derrubarei, diz o Senhor" Este versículo fala sobre a arrogância e a queda dos que se elevam acima dos outros, algo que também é visto na queda de Tiro.
****

[[v33-28-1]]

^<<v33-28-1,1>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-28-2]]

^<<v33-28-2,2>>^ “Filho do homem, dize ao príncipe de Tiro: Eis o que diz o Senhor Javé: teu coração elevou-se; tu disseste: sou um deus assentado sobre um trono divino no coração do mar. Quando não passas de um homem e não és um deus, tu te julgas em teu coração igual a Deus.^&#42;1^

[[v33-28-3]]

^<<v33-28-3,3>>^ Sem dúvida, eis-te mais sábio que Daniel, nenhum mistério te é obscuro.^&#42;1^

[[v33-28-4]]

^<<v33-28-4,4>>^ É por tua sutil inteligência que adquiriste bens, e cumulaste ouro e prata em teus tesouros.

[[v33-28-5]]

^<<v33-28-5,5>>^ Por tua grande habilidade comercial tens aumentado as tuas riquezas, e teu coração se ensoberbeceu.

[[v33-28-6]]

^<<v33-28-6,6>>^ Por causa disso, eis o que diz o Senhor Javé: já que em teu coração te julgas igual a Deus,

[[v33-28-7]]

^<<v33-28-7,7>>^ farei vir contra ti os estrangeiros, os mais brutais de todos os povos, que tirarão a espada contra os esplendores de tua sabedoria, e empanarão o teu brilho.

[[v33-28-8]]

^<<v33-28-8,8>>^ Eles te farão descer à fossa, morrerás como um decapitado no coração do mar.

[[v33-28-9]]

^<<v33-28-9,9>>^ Dirás ainda diante do algoz: sou um deus, quando tu não és senão um homem e não um deus nas mãos do teu assassino?

[[v33-28-10]]

^<<v33-28-10,10>>^ Morrerás da morte de um incircunciso, sob os golpes do estrangeiro, sou eu que o digo – oráculo do Senhor Javé.”

[[v33-28-11]]

^<<v33-28-11,11>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-28-12]]

^<<v33-28-12,12>>^ “Filho do homem, entoa um cântico fúnebre sobre o rei de Tiro, e dize-lhe: eis o que diz o Senhor Javé: eras um selo de perfeição, cheio de sabedoria, de uma beleza acabada.

[[v33-28-13]]

^<<v33-28-13,13>>^ Estavas no Éden, jardim de Deus, estavas coberto de gemas diversas: sardônica, topázio e diamante, crisólito, ônix e jaspe, safira, carbúnculo e esmeralda; trabalhados em ouro. Tamborins e flautas estavam a teu serviço, prontos desde o dia em que foste criado.^&#42;1^

[[v33-28-14]]

^<<v33-28-14,14>>^ Eras um querubim protetor colocado sobre a montanha santa de Deus; passeavas entre as pedras de fogo.

[[v33-28-15]]

^<<v33-28-15,15>>^ Foste irrepreensível em teu proceder desde o dia em que foste criado, até que a iniquidade apareceu em ti.

[[v33-28-16]]

^<<v33-28-16,16>>^ No desenvolvimento do teu comércio, encheram-se as tuas entranhas de violência e pecado; por isso, eu te bani da montanha de Deus, e te fiz perecer, ó querubim protetor, em meio às pedras de fogo.

[[v33-28-17]]

^<<v33-28-17,17>>^ Teu coração se inflou de orgulho devido à tua beleza, arruinaste a tua sabedoria, por causa do teu esplendor; precipitei-te em terra, e dei com isso um espetáculo aos reis.

[[v33-28-18]]

^<<v33-28-18,18>>^ À força de iniquidade e de desonestidade no teu comércio, profanaste os teus santuários; assim, de ti fiz jorrar o fogo que te devorou e te reduzi a cinza sobre a terra aos olhos dos espectadores.

[[v33-28-19]]

^<<v33-28-19,19>>^ Todos aqueles que te conheciam entre os povos ficaram estupefatos com o teu destino; acabaste sendo um objeto de espanto; foste banido para sempre!”.

[[v33-28-20]]

^<<v33-28-20,20>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-28-21]]

^<<v33-28-21,21>>^ “Filho do homem, volta-te para Sidônia e profetiza contra ela.

[[v33-28-22]]

^<<v33-28-22,22>>^ Dirás: eis o que diz o Senhor Javé: é contra ti que venho, Sidônia; vou fazer brilhar a minha glória em teu meio. Quando contra ti exercer meus julgamentos e em ti manifestar minha santidade, então se saberá que sou eu o Senhor.

[[v33-28-23]]

^<<v33-28-23,23>>^ Despacharei contra ela a peste, inundarei de sangue as suas ruas, onde sucumbirão feridos, golpeados por uma espada que surgirá de toda parte; assim, saberão que sou eu o Senhor.

[[v33-28-24]]

^<<v33-28-24,24>>^ Desde então, não haverá mais, para a casa de Israel, nem silvas ofensivas nem espinhos dolorosos da parte de nenhum dos seus vizinhos que a desprezam; assim se saberá que sou eu o Senhor.

[[v33-28-25]]

^<<v33-28-25,25>>^ Eis o que diz o Senhor Javé: quando eu reunir os israelitas dentre os povos, onde estiverem dispersados, manifestarei com isso a minha santidade aos olhos das nações; habitarão a terra que tenho doado ao meu servo Jacó.

[[v33-28-26]]

^<<v33-28-26,26>>^ Habitarão em segurança; construirão casas e plantarão vinhas; sim, eles habitarão lá com segurança. Quando eu houver exercido meus julgamentos contra todos os vizinhos que os desprezam, se saberá que sou eu, o Senhor, que sou seu Deus!”.

'''

xref:033-ezequiel/033-ezequiel-027.adoc#v33-27-0[&#60; Capítulo Anterior] | <<v33-28-0,Topo>> | xref:033-ezequiel/033-ezequiel-029.adoc#v33-29-0[Próximo Capítulo &#62;]