include::./index.adoc[]

[[v33-14-0]]
=== Ezequiel, 14
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 14 fala sobre a repreensão divina aos líderes idólatras de Israel que buscavam orientação do profeta enquanto ainda mantinham seus ídolos em seus corações. Deus afirma que aqueles que se apegam a seus ídolos não podem esperar ouvir sua voz. Aqui estão cinco versículos relacionados com os temas abordados em Ezequiel 14:
* Jeremias 7:9-10: "Vós fazeis furtos, homicídios, adultérios e juramentos falsos, queimais incenso a Baal, e andais após outros deuses que nunca conhecestes. E depois vindes, e vos apresentais diante de mim, nesta casa, que se chama pelo meu nome, e dizeis: Fomos libertados, para fazermos todas estas abominações?" Este versículo mostra que muitas pessoas em Israel estavam praticando atos pecaminosos e, ainda assim, continuavam a buscar a Deus em seu templo.
* Isaías 1:15: "Quando estenderdes as vossas mãos, esconderei de vós os meus olhos; e ainda que multipliqueis as vossas orações, não as ouvirei, porque as vossas mãos estão cheias de sangue." Este versículo destaca que Deus não ouve as orações daqueles que cometem pecados graves.
* Jeremias 11:11: "Portanto assim diz o Senhor: Eis que trarei sobre eles um mal de que não poderão escapar; e clamarão a mim, mas eu não os ouvirei." Este versículo enfatiza que Deus não atenderá as orações dos que buscam sua ajuda, se eles continuarem a seguir seus próprios caminhos.
* Salmos 66:18: "Se eu no coração contemplara a vaidade, o Senhor não me teria ouvido." Este versículo destaca que a iniquidade no coração de alguém pode impedir que Deus ouça suas orações.
* Provérbios 1:28-29: "Então me chamarão, mas não responderei; procurar-me-ão, porém não me hão de achar. Porquanto aborreceram a ciência e não preferiram o temor do Senhor." Este versículo mostra que aqueles que desprezam a sabedoria e o temor do Senhor não terão suas orações ouvidas.
****

[[v33-14-1]]

^<<v33-14-1,1>>^ Vieram à minha procura alguns anciãos de Israel, e se assentaram junto de mim.

[[v33-14-2]]

^<<v33-14-2,2>>^ A palavra do Senhor foi-me então dirigida nestes termos:

[[v33-14-3]]

^<<v33-14-3,3>>^ “Filho do homem, esses homens têm os ídolos instalados no coração, e eles têm constantemente diante dos olhos o que os leva a cair no pecado. É preciso deixar-me consultar por eles?

[[v33-14-4]]

^<<v33-14-4,4>>^ Pois bem, fala-lhes e anuncia-lhes: eis o que diz o Senhor Javé: se acontecer a um israelita, que tem ídolos instalados no coração e conserva diante dos olhos o que o faz cair no pecado, vir ter com um profeta, sou eu, o Senhor, que lhe responderei pessoalmente segundo a multidão dos seus ídolos,

[[v33-14-5]]

^<<v33-14-5,5>>^ a fim de atingir no coração essa casa de Israel que, por amor aos seus ídolos, se tem afastado de mim.

[[v33-14-6]]

^<<v33-14-6,6>>^ Por isso, diz à casa de Israel: eis o que diz o Senhor Javé: retornai! Renunciai a vossos ídolos, deixai de vez todas as vossas práticas abomináveis.

[[v33-14-7]]

^<<v33-14-7,7>>^ Se efetivamente sucede a algum israelita ou, também, a algum estrangeiro que more em Israel afastar-se de mim e instalar ídolos no coração, conservando diante dos olhos o que o faz cair no pecado, e depois se dirigir a um profeta para me consultar por seu ministério,

[[v33-14-8]]

^<<v33-14-8,8>>^ sou eu, o Senhor, que hei de responder contra esse homem; farei dele um exemplo que se há de tornar proverbial, porque o eliminarei do meu povo, e sabereis por essa forma que eu sou o Senhor.

[[v33-14-9]]

^<<v33-14-9,9>>^ E, se o profeta se deixar seduzir e proferir um oráculo, é que eu, o Senhor, o terei seduzido; estenderei a mão contra ele e o farei seduzir; contra ele estenderei a mão, e o farei desaparecer do meio do meu povo de Israel.^&#42;1^

[[v33-14-10]]

^<<v33-14-10,10>>^ Carregarão o peso da sua falta, tanto o consulente como o profeta,

[[v33-14-11]]

^<<v33-14-11,11>>^ a fim de que a casa de Israel não se afaste para longe de mim, e não se manche por causa de todos os seus delitos. Então, eles serão o meu povo e eu serei o seu Deus – oráculo do Senhor Javé”.

[[v33-14-12]]

^<<v33-14-12,12>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-14-13]]

^<<v33-14-13,13>>^ “Filho do homem, se uma terra pecasse contra mim por infidelidade e eu estendesse contra ela a mão, suprimindo-lhe o pão que fortifica, e a ela enviasse a fome exterminadora dos animais e dos homens,

[[v33-14-14]]

^<<v33-14-14,14>>^ ainda que houvesse nessa terra Noé, Daniel e Jó, esses três homens só salvariam a si próprios, devido à sua justiça – oráculo do Senhor Javé.^&#42;1^

[[v33-14-15]]

^<<v33-14-15,15>>^ Se eu deixasse os animais ferozes percorrerem a terra para devorar as crianças e transformarem-na em deserto, onde ninguém, por temor dessas feras, ousasse passar,

[[v33-14-16]]

^<<v33-14-16,16>>^ e se esses três homens se encontrassem nessa terra – por minha vida! – oráculo do Senhor Javé –, eles não poderiam salvar nem seus filhos nem suas filhas; somente eles escapariam e a terra continuaria deserta.

[[v33-14-17]]

^<<v33-14-17,17>>^ Ou, se eu fizesse vir a espada sobre essa terra, dizendo: que a espada passe por aqui e corte indistintamente homens e animais,

[[v33-14-18]]

^<<v33-14-18,18>>^ e se esses três homens se encontrassem aí – por minha vida – oráculo do Senhor Javé –, não poderiam eles salvar nem seus filhos nem suas filhas; somente eles seriam salvos.

[[v33-14-19]]

^<<v33-14-19,19>>^ Ou, ainda, se eu enviasse a peste sobre essa terra, e fizesse cair sobre ela o meu furor no sangue, exterminando homens e feras,

[[v33-14-20]]

^<<v33-14-20,20>>^ e se Noé, Daniel e Jó se encontrassem aí – por minha vida – oráculo do Senhor Javé –, não poderiam eles garantir por sua justiça nem seus filhos nem suas filhas, mas somente a sua própria vida”.

[[v33-14-21]]

^<<v33-14-21,21>>^ “Assim fala o Senhor Deus: mesmo que lance eu os meus quatro funestos flagelos – a espada, a fome, as feras e a peste – contra Jerusalém, para exterminar dela homens e animais,

[[v33-14-22]]

^<<v33-14-22,22>>^ subsistirão entretanto alguns sobreviventes, filhos e filhas, que sairão da cidade. Eis que eles virão até vós. Quando tiverdes visto seu proceder e seus atos, vós vos consolareis das calamidades que eu houver desencadeado contra Jerusalém, de tudo quanto eu lhe houver infligido,^&#42;1^

[[v33-14-23]]

^<<v33-14-23,23>>^ Eles vos consolarão, quando houverdes observado o seu comportamento e seus atos: reconhecereis não ser sem motivo que eu tratei a cidade como fiz – oráculo do Senhor Javé.”

'''

xref:033-ezequiel/033-ezequiel-013.adoc#v33-13-0[&#60; Capítulo Anterior] | <<v33-14-0,Topo>> | xref:033-ezequiel/033-ezequiel-015.adoc#v33-15-0[Próximo Capítulo &#62;]