include::./index.adoc[]

[[v33-39-0]]
=== Ezequiel, 39
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 39 do livro de Ezequiel fala sobre a destruição dos inimigos de Israel e a restauração da terra. Deus promete punir os invasores que tentaram conquistar Israel e mostrará sua santidade a todas as nações. Ele também promete restaurar a terra e abençoar seu povo. Abaixo estão cinco versículos relacionados com os temas abordados em Ezequiel 39:
* Isaías 66:15: "Porque eis que o Senhor virá com fogo, e os seus carros como um torvelinho; para tornar a sua ira em furor, e a sua repreensão em chamas de fogo." Este versículo fala sobre a vinda do Senhor com fogo para julgar seus inimigos, o que é semelhante à descrição da destruição dos inimigos de Israel em Ezequiel 39.
* Isaías 66:18: "E eu, conhecendo-lhes as obras e seus pensamentos, venho para ajuntar todas as nações e línguas; elas virão e contemplarão a minha glória." Este versículo fala sobre todas as nações vindo para contemplar a glória de Deus, o que é semelhante à promessa de Deus em Ezequiel 39 de mostrar sua santidade a todas as nações.
* Joel 3:17: "E vós sabereis que eu sou o Senhor vosso Deus, que habito em Sião, o meu santo monte; e Jerusalém será santa, e estranhos não passarão mais por ela." Este versículo fala sobre Jerusalém sendo um lugar santo onde Deus habita e nenhuma nação estrangeira poderá passar por ela, o que é semelhante à restauração prometida por Deus em Ezequiel 39.
* Joel 3:20: "Mas Judá será habitada para sempre, e Jerusalém de geração em geração." Este versículo fala sobre Judá e Jerusalém sendo habitados para sempre, o que é semelhante à promessa de Deus em Ezequiel 39 de restaurar a terra e abençoar seu povo.
* Zacarias 8:8: "E os trarei, e habitarão no meio de Jerusalém; e eles serão o meu povo, e eu serei o seu Deus em verdade e em justiça." Este versículo fala sobre Deus trazendo seu povo de volta a Jerusalém para que eles possam habitar ali, o que é semelhante à restauração prometida por Deus em Ezequiel 39.
****

[[v33-39-1]]

^<<v33-39-1,1>>^ “E tu, filho do homem, profetiza contra Gog nestes termos: eis o que diz o Senhor Javé: é contra ti que venho, Gog, príncipe soberano de Mosoc e de Tubal.

[[v33-39-2]]

^<<v33-39-2,2>>^ Eu te vou fazer ir-e-vir, eu te conduzirei, eu te transportarei dos confins do Norte contra as montanhas de Israel.

[[v33-39-3]]

^<<v33-39-3,3>>^ De tua mão esquerda escapará teu arco, que eu quebrarei, e de tua mão direita farei cair tuas flechas.

[[v33-39-4]]

^<<v33-39-4,4>>^ Tombarás sobre os montes de Israel, com tuas tropas e as hordas que te seguirem. Eu te darei por pasto às aves de rapina, aos voláteis de toda espécie e às feras.

[[v33-39-5]]

^<<v33-39-5,5>>^ Serás estirado na terra, porquanto eu disse – oráculo do Senhor Javé.

[[v33-39-6]]

^<<v33-39-6,6>>^ Expedirei fogo a Magog e entre aqueles que ocupam tranquilamente as praias marinhas; eles saberão que sou eu o Senhor.

[[v33-39-7]]

^<<v33-39-7,7>>^ Farei assim conhecer meu santo nome no meio do meu povo de Israel, sem mais deixá-lo profanar. As nações saberão assim que sou eu o Senhor, santo em Israel.

[[v33-39-8]]

^<<v33-39-8,8>>^ Ora, eis o que irá suceder, e isso está próximo – oráculo do Senhor Javé –, eis o dia que eu havia predito.

[[v33-39-9]]

^<<v33-39-9,9>>^ De todas as cidades de Israel sairão cidadãos para acender um fogo onde hão de queimar as armas: capacetes, escudos, arcos, flechas, lanças, dardos, dos quais se fará uma fogueira durante sete anos.

[[v33-39-10]]

^<<v33-39-10,10>>^ Não mais irão aos campos amontoar lenha, não mais hão de fazer derrubada na floresta, porque com as armas é que se farão fogueiras. Pilharão os saqueadores, destruirão os destruidores – oráculo do Senhor Javé.

[[v33-39-11]]

^<<v33-39-11,11>>^ Naquele dia, assinalarei a Gog o local da sepultura em Israel, o vale dos viandantes, ao oriente do mar, que tapará o caminho aos passantes. Aí se enterrará Gog e toda a horda de suas gentes, e esse vale se chamará Hamon-Gog.^&#42;1^

[[v33-39-12]]

^<<v33-39-12,12>>^ Os israelitas gastarão sete meses para enterrá-los e para limpar a terra.

[[v33-39-13]]

^<<v33-39-13,13>>^ Todas as gentes da terra trabalharão nessa sepultura e hão de orgulhar-se do dia em que eu manifestar a minha glória – oráculo do Senhor Javé.

[[v33-39-14]]

^<<v33-39-14,14>>^ Serão designados homens encarregados de percorrer continuamente a terra para a limparem, enterrando os cadáveres que ficarem distendidos pelo solo: essa procura durará sete meses.

[[v33-39-15]]

^<<v33-39-15,15>>^ Quando em suas caminhadas virem eles ossos humanos, de todo lado farão sinal até que os coveiros os tenham enterrado no vale de Hamon-Gog.

[[v33-39-16]]

^<<v33-39-16,16>>^ Uma cidade terá o nome de Multidão. É assim que se purificará a terra.

[[v33-39-17]]

^<<v33-39-17,17>>^ E tu, filho do homem, escuta o que diz o Senhor Javé: dize às aves de toda espécie e a todos os animais dos campos: ajuntai-vos! Vinde, reuni-vos para o sacrifício que vos preparo, um grande sacrifício nas montanhas de Israel: comereis carne e bebereis sangue.

[[v33-39-18]]

^<<v33-39-18,18>>^ Ireis comer a carne dos heróis e beber o sangue dos príncipes da terra: carneiros, cordeiros, cabritos, touros robustos de Basã.

[[v33-39-19]]

^<<v33-39-19,19>>^ Nesse sacrifício ao qual vos convido, comereis gordura até vos fartardes, e bebereis sangue até a embriaguez.

[[v33-39-99]]

^<<v33-39-99,99>>^ À minha mesa vos saciareis de corcéis, cavaleiros, heróis e guerreiros de toda espécie – oráculo do Senhor Javé.”

[[v33-39-21]]

^<<v33-39-21,21>>^ “Desse modo, manifestarei minha glória entre as nações: todas elas me hão de ver executar os meus atos de justiça e pôr a mão sobre elas.

[[v33-39-22]]

^<<v33-39-22,22>>^ E, a partir daquele dia, os israelitas saberão que sou eu o Senhor, seu Deus.

[[v33-39-23]]

^<<v33-39-23,23>>^ As nações reconhecerão que é por causa da sua iniquidade que Israel foi deportado, e que é por causa da sua infidelidade que lhes tenho ocultado a minha face e as tenho entregue nas mãos dos seus inimigos, para que pereçam pela espada.

[[v33-39-24]]

^<<v33-39-24,24>>^ Escondendo-lhes minha face, só lhes fiz o que mereciam por suas iniquidades e prevaricações.

[[v33-39-25]]

^<<v33-39-25,25>>^ E, por isso, eis o que diz o Senhor Javé: dentro em breve vou reconduzir os cavalos de Jacó e apiedar-me de toda a casa de Israel; vou mostrar-me cioso do meu santo nome.^&#42;1^

[[v33-39-26]]

^<<v33-39-26,26>>^ E serão livres de toda vergonha e das infidelidades de que se tornaram culpados para comigo, quando habitarem de novo tranquilamente sua terra, sem que ninguém os inquiete.

[[v33-39-27]]

^<<v33-39-27,27>>^ Logo que os houver reconduzido dentre as nações e reunido dos países inimigos, e que houver manifestado a minha santidade aos olhos das nações numerosas por meu proceder a seu respeito,

[[v33-39-28]]

^<<v33-39-28,28>>^ reconhecerão eles que sou eu o Senhor, que sou seu Deus, porque depois de tê-los exilado entre as nações, eu os reunirei no seu solo sem lá deixar um só.

[[v33-39-29]]

^<<v33-39-29,29>>^ Não esconderei mais deles a minha face, porque espargirei meu Espírito sobre toda a casa de Israel – oráculo do Senhor Javé.”

'''

xref:033-ezequiel/033-ezequiel-038.adoc#v33-38-0[&#60; Capítulo Anterior] | <<v33-39-0,Topo>> | xref:033-ezequiel/033-ezequiel-040.adoc#v33-40-0[Próximo Capítulo &#62;]