include::./index.adoc[]

[[v33-7-0]]
=== Ezequiel, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 7 descreve a chegada do dia do juízo sobre Jerusalém por causa da sua desobediência e pecado. Os versículos selecionados abaixo refletem o julgamento de Deus sobre o povo de Jerusalém e a falta de arrependimento deles:
* Isaías 13:6: "Gritem de dor, pois o dia do Senhor está próximo; como uma destruição vinda do Todo-Poderoso, ele virá!" Este versículo anuncia a chegada do Dia do Senhor, um dia de julgamento para aqueles que se rebelaram contra Deus e sua vontade.
* Jeremias 30:7: "Ah! Que grande dia será aquele! Não haverá outro como ele. Será tempo de angústia para Jacó, mas ele será salvo dessa angústia." Este versículo fala sobre o dia do juízo, que será uma época de grande angústia, mas aqueles que se voltarem para Deus serão salvos.
* Sofonias 1:14-15: "O grande dia do Senhor está próximo, próximo e chegando rapidamente. O som do dia do Senhor é amargo; ali o guerreiro grita. Esse dia será dia de ira, dia de angústia e aflição, dia de devastação e destruição, dia de trevas e escuridão, dia de nuvens e densas trevas." Este versículo descreve vividamente a chegada do dia do juízo, um dia de grande destruição e escuridão.
* Zacarias 14:1-2: "Eis que o dia do Senhor está chegando, e o seu saque será repartido no meio de vocês. Pois eu ajuntarei todas as nações para lutarem contra Jerusalém; a cidade será tomada, as casas serão saqueadas, e as mulheres serão violentadas. Metade da cidade irá para o exílio, mas o restante do povo não será extirpado da cidade." Este versículo profetiza a queda de Jerusalém nas mãos dos seus inimigos por causa do seu pecado e desobediência a Deus.
* Ezequiel 18:30: "Portanto, ó nação de Israel, eu o julgarei a cada um segundo o seu procedimento, declara o Soberano, o Senhor. Arrependam-se! Desviem-se de todos os seus pecados, para que a maldade não seja para vocês motivo de tropeço." Este versículo destaca a importância do arrependimento e mudança de comportamento diante do julgamento de Deus.
****

[[v33-7-1]]

^<<v33-7-1,1>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-7-2]]

^<<v33-7-2,2>>^ “Filho do homem, oráculo do Senhor à terra de Israel: eis o fim. O fim vem para todos os quatro cantos da terra.

[[v33-7-3]]

^<<v33-7-3,3>>^ Chegou o fim para ti, vou desencadear contra ti a minha cólera, vou julgar-te de acordo com o teu procedimento e fazer cair sobre ti o peso de todas as tuas práticas abomináveis.

[[v33-7-4]]

^<<v33-7-4,4>>^ Não te tomarei em consideração, serei sem complacência, pedirei conta de teu proceder, e todos os teus horrores serão manifestos no teu meio. Então sabereis que sou eu o Senhor”.

[[v33-7-5]]

^<<v33-7-5,5>>^ “Eis o que diz o Senhor Javé: uma desgraça única! Eis que irá suceder: uma desgraça!

[[v33-7-6]]

^<<v33-7-6,6>>^ O fim se avizinha, o fim se aproxima, ele desperta para cair sobre ti; ei-lo!

[[v33-7-7]]

^<<v33-7-7,7>>^ Tua vez é chegada, habitante da terra! É vindo o momento, o dia está próximo; não há mais alegria sobre as montanhas; é o pânico.

[[v33-7-8]]

^<<v33-7-8,8>>^ Vou em breve desencadear o meu furor contra ti, fartar a minha cólera, julgar-te segundo o teu proceder; farei cair sobre ti o peso das tuas abominações.

[[v33-7-9]]

^<<v33-7-9,9>>^ Não te tomarei em consideração, serei implacável, pedirei conta de teu proceder, e todos os teus horrores serão manifestos no teu meio. Então, sabereis que sou eu o Senhor que fere.

[[v33-7-10]]

^<<v33-7-10,10>>^ Eis o dia! Ei-lo que chega. Tua vez chegou. A vara floriu, o orgulho produziu seus frutos!^&#42;1^

[[v33-7-11]]

^<<v33-7-11,11>>^ A violência levantou-se com um cetro de impiedade: isso não vem deles, nem da multidão, nem da sua tropa, nem da sua magnificência.

[[v33-7-12]]

^<<v33-7-12,12>>^ Chegou o tempo, o dia se aproxima! Que não se alegre o comprador, que não se aflija o vendedor, pois a cólera vai pesar sobre toda a multidão.

[[v33-7-13]]

^<<v33-7-13,13>>^ O vendedor não recuperará o que houver vendido, mesmo que esteja vivo, porque a visão contra toda a multidão não será revogada, e ninguém terá força de proteger a si mesmo, por causa do seu pecado.^&#42;1^

[[v33-7-14]]

^<<v33-7-14,14>>^ Soa a trombeta; está tudo pronto; mas ninguém marcha para o combate, porque o meu furor se desencadeia sobre toda a multidão.

[[v33-7-15]]

^<<v33-7-15,15>>^ Fora, a espada; dentro, a peste e a fome. Quem estiver no campo perecerá pela espada; o que se encontrar na cidade será devorado pela peste e pela fome.

[[v33-7-16]]

^<<v33-7-16,16>>^ Se alguns chegarem a se refugiar nas montanhas, gemerão como as pombas dos vales, cada qual por causa do seu pecado.

[[v33-7-17]]

^<<v33-7-17,17>>^ Todas as mãos cairão desalentadas, todos os joelhos tremerão.

[[v33-7-18]]

^<<v33-7-18,18>>^ Irão se revestir de saco e tremerão como varas verdes! A vergonha transparecerá em todos os rostos e todas as cabeças serão raspadas.^&#42;1^

[[v33-7-19]]

^<<v33-7-19,19>>^ Deitarão o dinheiro às ruas, seu ouro será como imundície; sua prata e seu ouro não poderão salvá-los no dia da cólera do Senhor. Não saberão eles nem comer à vontade nem encher o ventre, porque é lá que os farei cair no pecado.

[[v33-7-20]]

^<<v33-7-20,20>>^ Punham seu orgulho na beleza das suas joias; fabricavam seus ídolos abomináveis; por isso, farei deles objetos de repugnância.

[[v33-7-21]]

^<<v33-7-21,21>>^ Eu os abandonarei à pilhagem, às mãos de estranhos e, em razão da profanação, farei deles o espólio dos ímpios da terra.

[[v33-7-22]]

^<<v33-7-22,22>>^ Desviarei os olhos e será profanado o meu tesouro; bárbaros penetrarão aí para profaná-lo.^&#42;1^

[[v33-7-23]]

^<<v33-7-23,23>>^ Prepara-te uma cadeia; pois a terra está repleta de crimes, e a cidade cheia de violências.

[[v33-7-24]]

^<<v33-7-24,24>>^ Farei vir também os mais bárbaros pagãos, que se apoderarão de todas as casas; porei termo ao orgulho dos poderosos, e os lugares santos serão profanados.

[[v33-7-25]]

^<<v33-7-25,25>>^ É a ruína que está chegando. A salvação será procurada, sem que se possa encontrá-la.

[[v33-7-26]]

^<<v33-7-26,26>>^ Sobrevirão desastres sobre desastres, má nova sobre má nova. Serão pedidos oráculos ao profeta, faltará a lei para o sacerdote, e o conselho para os anciãos.

[[v33-7-27]]

^<<v33-7-27,27>>^ O rei há de pôr luto, ficará o príncipe cheio de consternação, tremerão as mãos dos homens do povo. Eu os tratarei de conformidade com o proceder que levaram, irei julgá-los conforme houverem merecido. Então saberão que sou o Senhor”.

'''

xref:033-ezequiel/033-ezequiel-006.adoc#v33-6-0[&#60; Capítulo Anterior] | <<v33-7-0,Topo>> | xref:033-ezequiel/033-ezequiel-008.adoc#v33-8-0[Próximo Capítulo &#62;]