include::./index.adoc[]

[[v33-16-0]]
=== Ezequiel, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 16 é um capítulo que usa a metáfora de uma prostituta para descrever a infidelidade de Israel com outros deuses e sua traição a Deus. O capítulo mostra que Deus resgatou Israel do nada e a fez uma nação próspera, mas ela se entregou à idolatria e à imoralidade. Aqui estão cinco versículos relacionados com os temas abordados em Ezequiel 16:
* Êxodo 20:3-5: "Não terás outros deuses diante de mim. Não farás para ti imagem esculpida, nem figura alguma do que há em cima no céu, nem embaixo na terra, nem nas águas debaixo da terra. Não te encurvarás diante delas, nem as servirás; porque eu, o Senhor teu Deus, sou Deus zeloso, que visito a iniquidade dos pais nos filhos até a terceira e quarta geração daqueles que me aborrecem." Este versículo destaca a proibição da idolatria e a advertência de Deus sobre as consequências daqueles que adoram outros deuses.
* Oséias 2:13: "Porque ela diz: Irei após os meus amantes, que me dão o meu pão e a minha água, a minha lã e o meu linho, o meu azeite e as minhas bebidas." Este versículo retrata a atitude de Israel em buscar outros deuses e acreditar que eles são a fonte de seus bens materiais.
* Isaías 1:21: "Como se fez a cidade fiel em uma prostituta! Ela estava cheia de justiça, a retidão habitava nela; mas agora, assassinos." Este versículo usa a metáfora da prostituta para descrever a infidelidade de Israel com outros deuses.
* Jeremias 3:8: "E vi que por causa de tudo isso, por ter cometido adultério a rebelde Israel, a despedi, e lhe dei a sua carta de divórcio, que a aleivosa Judá, sua irmã, não temeu; mas se foi e também ela mesma se prostituiu." Este versículo fala sobre Deus rejeitando Israel por causa de sua infidelidade e o comparando a um marido que se divorcia de sua esposa adúltera.
* Isaías 62:5: "Como o jovem se casa com a virgem, assim teus filhos se casarão contigo; e como o noivo se alegra da noiva, assim se alegrará de ti o teu Deus." Este versículo destaca a restauração de Israel e a reconciliação com Deus depois de seu arrependimento.
****

[[v33-16-1]]

^<<v33-16-1,1>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-16-2]]

^<<v33-16-2,2>>^ “Filho do homem, mostra a Jerusalém os seus crimes abomináveis.^&#42;1^

[[v33-16-3]]

^<<v33-16-3,3>>^ Será dito: eis o que diz o Senhor Javé a respeito de Jerusalém: por tua origem e nascimento, pertences à terra de Canaã; teu pai foi um amorreu e tua mãe, uma hitita.

[[v33-16-4]]

^<<v33-16-4,4>>^ No dia do teu nascimento, teu cordão umbilical não foi cortado; não te banharam com água para te purificar, não te untaram com sal, nem te enfaixaram.

[[v33-16-5]]

^<<v33-16-5,5>>^ Ninguém se inclinou sobre ti para te prestar algum piedoso cuidado. No dia em que nasceste foste exposta em meio das campinas; só havia infortúnio para ti.

[[v33-16-6]]

^<<v33-16-6,6>>^ Passei junto de ti e te percebi banhada em teu sangue. Eu te gritei: vive malgrado o teu sangue, vive malgrado o teu sangue,

[[v33-16-7]]

^<<v33-16-7,7>>^ e eu te fiz multiplicar como a erva dos prados. Cresceste. Ficaste moça. Teus seios se formaram, veio-te o pêlo. Mas estavas nua, inteiramente nua.

[[v33-16-8]]

^<<v33-16-8,8>>^ Passando junto de ti, verifiquei que já havia chegado o teu tempo, o tempo dos amores. Estendi sobre ti o pano do meu manto, cobri tua nudez; depois fiz contigo uma aliança ligando-me a ti pelo juramento – oráculo do Senhor Javé – e tu me pertenceste.^&#42;1^

[[v33-16-9]]

^<<v33-16-9,9>>^ Então, eu te mergulhei na água para limpar o sangue de que estavas coberta, e te ungi com óleo.

[[v33-16-10]]

^<<v33-16-10,10>>^ Eu te vesti de tecidos bordados, calcei-te com sapatos de pele de golfinho, cingi-te com um cinto de fino linho e um véu de seda.

[[v33-16-11]]

^<<v33-16-11,11>>^ Ornei-te de adornos: braceletes nos teus pulsos, colares em teu pescoço,

[[v33-16-12]]

^<<v33-16-12,12>>^ um anel para o teu nariz, brincos para tuas orelhas, uma coroa magnífica para tua cabeça.

[[v33-16-13]]

^<<v33-16-13,13>>^ Teus ornatos eram de ouro, prata, com vestimentas de linho fino, de seda e panos bordados; teu alimento era trigo, mel e óleo. Cada vez mais bela, chegaste à dignidade real.

[[v33-16-14]]

^<<v33-16-14,14>>^ A reputação da tua beleza correu entre as nações, pois essa beleza era perfeita, graças ao esplendor que te havia eu preparado – oráculo do Senhor Javé.

[[v33-16-15]]

^<<v33-16-15,15>>^ Tu, porém, te fiaste na beleza, aproveitaste da tua fama para te prostituíres e ofereceste a tua sensualidade a todo transeunte, a quem te entregaste.

[[v33-16-16]]

^<<v33-16-16,16>>^ Tomaste tuas vestimentas para delas fazeres lugares altos para ti, ornados de panos de variegadas cores, e deste-te à depravação, o que jamais deveria ter sucedido, e que não te sucederá jamais.^&#42;1^

[[v33-16-17]]

^<<v33-16-17,17>>^ Tomaste as esplêndidas joias feitas com o meu ouro e minha prata, joias que eu te havia doado, e fabricaste com elas imagens humanas, com que te prostituíste,

[[v33-16-18]]

^<<v33-16-18,18>>^ cobriste-as com as tuas próprias vestes bordadas, e ofereceste-lhes o meu óleo e os meus aromas.

[[v33-16-19]]

^<<v33-16-19,19>>^ O pão que eu te havia dado, a flor da farinha, o óleo e o mel com que te nutrias, deste-os em oferenda de agradável odor. Eis o que tens feito – oráculo do Senhor Javé.

[[v33-16-20]]

^<<v33-16-20,20>>^ Depois tomaste os teus filhos e tuas filhas, que para mim deste à luz e os ofereceste a eles para sua nutrição. Por acaso são poucas as tuas prostituições?

[[v33-16-21]]

^<<v33-16-21,21>>^ Degolaste os meus filhos e os fizeste passar pelo fogo em sua honra.

[[v33-16-22]]

^<<v33-16-22,22>>^ Em meio a todas essas depravações abomináveis, não te lembraste do tempo de tua juventude, quando estavas toda nua e te rolavas em teu sangue.

[[v33-16-23]]

^<<v33-16-23,23>>^ Para cúmulo de todas essas maldades – Ai! Ai de ti! Oráculo do Senhor –,

[[v33-16-24]]

^<<v33-16-24,24>>^ edificaste uma colina, um lugar alto em todas as encruzilhadas.

[[v33-16-25]]

^<<v33-16-25,25>>^ À entrada de cada rua erigiste um lugar alto, e desonraste a tua beleza, dando teu corpo a todos os que vinham, multiplicando as tuas depravações.

[[v33-16-26]]

^<<v33-16-26,26>>^ Tu te prostituíste com os egípcios, teus vizinhos de corpos vigorosos, e multiplicaste as prostituições para me irritar.

[[v33-16-27]]

^<<v33-16-27,27>>^ Mas eu estendi a mão contra ti; reduzi a tua porção, deixei-te à mercê das tuas inimigas, as filhas dos filisteus, envergonhadas elas próprias do teu infame proceder.^&#42;1^

[[v33-16-28]]

^<<v33-16-28,28>>^ Tu te prostituíste também com os assírios, porque não estavas satisfeita, e ainda assim não te deste por saciada;^&#42;1^

[[v33-16-29]]

^<<v33-16-29,29>>^ multiplicaste as tuas depravações no país dos mercadores, entre os caldeus, sem que, contudo, te tenhas fartado.

[[v33-16-30]]

^<<v33-16-30,30>>^ Como é frouxo o teu coração – oráculo do Senhor Javé –, para teres tido ali o comportamento de uma prostituta,

[[v33-16-31]]

^<<v33-16-31,31>>^ por teres construído um montículo em todas as encruzilhadas, e um lugar alto à entrada de todas as ruas, sem mesmo procurar um salário como meretriz.

[[v33-16-32]]

^<<v33-16-32,32>>^ Tens sido mulher adúltera que acolhe os estranhos em lugar do esposo.

[[v33-16-33]]

^<<v33-16-33,33>>^ A todas as prostitutas se dão presentes, mas tu fizeste brindes a todos os teus amantes, procedeste com largueza para que de todos os lados viessem prostituir-se contigo.

[[v33-16-34]]

^<<v33-16-34,34>>^ Tens sido o avesso das outras mulheres em tuas depravações: não te procuravam; eras tu que pagavas ao invés de receber, fazendo tudo ao contrário do que fazem as outras.

[[v33-16-35]]

^<<v33-16-35,35>>^ Em vista de tudo isto, luxuriosa, escuta o que diz o Senhor:

[[v33-16-36]]

^<<v33-16-36,36>>^ eis o que diz o Senhor Javé: por tua prata dilapidada, por tua nudez descoberta no decurso de tuas prostituições com os teus amantes e com os teus ídolos abomináveis, pelo sangue de teus filhos que lhes deste,

[[v33-16-37]]

^<<v33-16-37,37>>^ vou reunir todos os teus amantes com aquele a quem juraste amor, todos quantos amaste e todos que te detestam, vou reuni-los contra ti de todos os lados, e perante eles descobrirei a tua nudez, a fim de que te contemplem totalmente.

[[v33-16-38]]

^<<v33-16-38,38>>^ Eu infligirei o castigo às adúlteras e às criminosas, e contra ti desencadearei meu furor e meus ciúmes.

[[v33-16-39]]

^<<v33-16-39,39>>^ Irei te entregar nas suas mãos; eles demolirão o teu montículo, abaterão o teu lugar alto; eles te despojarão dos teus vestidos; levarão os teus ornatos e te deixarão nua e despojada.

[[v33-16-40]]

^<<v33-16-40,40>>^ Em seguida, sublevarão contra ti a multidão: serás apedrejada e perecerás pela espada;

[[v33-16-41]]

^<<v33-16-41,41>>^ atearão fogo à tua casa e se fará juízo contra ti, aos olhos de uma multidão de mulheres; porei fim às tuas prostituições e não terás mais salário a dar.^&#42;1^

[[v33-16-42]]

^<<v33-16-42,42>>^ Saciarei o meu furor contra ti e, quando tiveres deixado de ser objeto do meu zelo, eu me acalmarei, e minha cólera terminará.

[[v33-16-43]]

^<<v33-16-43,43>>^ Porque não te lembraste do tempo da tua mocidade, e tudo isso fizeste com o fito de provocar-me, vou fazer cair sobre tua cabeça o peso de teu proceder – oráculo do Senhor Javé –, a fim de que não ajuntes novos crimes às tuas abominações”.

[[v33-16-44]]

^<<v33-16-44,44>>^ “Todos os amigos de provérbios dirão a teu respeito: tal mãe, tal filha.

[[v33-16-45]]

^<<v33-16-45,45>>^ De fato, és bem filha de tua mãe, que tomou aversão a seu marido e a seus filhos; és bem irmã de tuas irmãs, que tomaram aversão a seus maridos e a seus filhos. Tua mãe era uma hitita e teu pai, um amorreu.

[[v33-16-46]]

^<<v33-16-46,46>>^ Tua irmã mais velha é Samaria, que habita à esquerda com suas filhas; tua irmã mais moça é Sodoma, que habita com suas filhas à tua direita.

[[v33-16-47]]

^<<v33-16-47,47>>^ Ainda não estavas contente em seguir seu passo e em imitar seus horrores; era pouco! Foste mais longe que elas na corrupção.

[[v33-16-48]]

^<<v33-16-48,48>>^ Por minha vida – oráculo do Senhor Javé –, tua irmã Sodoma e suas filhas não fizeram o que fizeste tu e tuas filhas.

[[v33-16-49]]

^<<v33-16-49,49>>^ O crime de tua irmã Sodoma era este: opulência, glutonaria, indolência, ociosidade; eis como vivia ela, assim como suas filhas, sem tomar pela mão o miserável e o indigente.

[[v33-16-50]]

^<<v33-16-50,50>>^ Tornaram-se arrogantes e, sob os meus olhos, se entregaram à abominação; por isso, eu as fiz desaparecer, como viste.

[[v33-16-51]]

^<<v33-16-51,51>>^ Quanto à Samaria, não cometeu ela a metade dos teus pecados, porque multiplicaste os teus crimes além dos seus e, por todas essas perversidades que cometeste, justificaste as tuas irmãs.^&#42;1^

[[v33-16-52]]

^<<v33-16-52,52>>^ Carrega, pois, também tu, a vergonha das faltas pelas quais tu as justificaste graças a teus pecados, cuja malvadez superou a dos delas, afiguram-se elas mais justas que tu. De tua parte, carrega a vergonha e suporta a tua ignomínia, pois até fazes parecerem justas as tuas irmãs.

[[v33-16-53]]

^<<v33-16-53,53>>^ No tempo em que eu as tiver restaurado, Sodoma e suas filhas, Samaria e suas filhas, eu te restaurarei entre elas,

[[v33-16-54]]

^<<v33-16-54,54>>^ a fim de que carregues o teu opróbrio e sejas tu confundida por tudo quanto fizeste para seu conforto.^&#42;1^

[[v33-16-55]]

^<<v33-16-55,55>>^ Tua irmã Sodoma e suas filhas retornarão a seu primitivo estado, Samaria e suas filhas igualmente; e tu também, com tuas filhas, voltareis à vossa antiga situação.

[[v33-16-56]]

^<<v33-16-56,56>>^ Ao tempo do teu orgulho, o nome de tua irmã Sodoma não era famoso em tua boca,

[[v33-16-57]]

^<<v33-16-57,57>>^ antes que houvesse sido patenteada a tua perversidade, como no tempo em que recebias os ultrajes das filhas da Síria e de suas vizinhas, das filhas dos filisteus que de toda parte te insultavam.

[[v33-16-58]]

^<<v33-16-58,58>>^ Eis-te carregada do peso dos teus crimes e das tuas abominações – oráculo do Senhor.

[[v33-16-59]]

^<<v33-16-59,59>>^ Pois eis o que diz o Senhor Javé: eu farei a ti conforme fizeste tu, que desprezaste a tua origem violando o pacto.

[[v33-16-60]]

^<<v33-16-60,60>>^ Mas eu me recordarei da aliança que contigo celebrei no tempo de tua juventude, e farei contigo uma eterna aliança.

[[v33-16-61]]

^<<v33-16-61,61>>^ Então, te lembrarás de teu procedimento, e terás vergonha disso, quando eu tomar tuas irmãs mais velhas, juntamente com as mais novas, e tu as der por filhas, mas isso não em virtude de tua aliança.^&#42;1^

[[v33-16-62]]

^<<v33-16-62,62>>^ Sou eu que hei de restabelecer a minha aliança contigo, e tu saberás que sou eu o Senhor,

[[v33-16-63]]

^<<v33-16-63,63>>^ a fim de que te recordes do passado e te envergonhes, e que, em tua vergonha, não tenhas mais a audácia de abrir a boca, quando eu houver perdoado os teus delitos – oráculo do Senhor Javé.”^&#42;1^

'''

xref:033-ezequiel/033-ezequiel-015.adoc#v33-15-0[&#60; Capítulo Anterior] | <<v33-16-0,Topo>> | xref:033-ezequiel/033-ezequiel-017.adoc#v33-17-0[Próximo Capítulo &#62;]