include::./index.adoc[]

[[v33-2-0]]
=== Ezequiel, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 2 de Ezequiel começa com a descrição da visão que o profeta teve de Deus e dos seres celestiais. Deus então chama Ezequiel para ser um mensageiro e profeta, enviado para falar com o povo de Israel e adverti-los sobre a sua conduta pecaminosa. Os versículos abaixo foram selecionados por sua relação com a temática do chamado de Ezequiel como profeta e sua missão de advertir o povo:
* Isaías 6:8: "Então ouvi a voz do Senhor, conclamando: 'Quem enviarei? Quem irá por nós?' E eu respondi: 'Eis-me aqui. Envia-me!'" Este versículo mostra a disposição do profeta Isaías em se oferecer para ser enviado por Deus, semelhante à resposta de Ezequiel quando Deus o chamou para ser um mensageiro.
* Jeremias 1:7-8: "Mas o Senhor me disse: 'Não digas: Eu sou muito jovem. A todos a quem eu te enviar, irás, e tudo o que te mandar, falarás. Não tenhas medo deles, pois estou contigo para livrar-te', diz o Senhor." Deus encoraja Jeremias a não temer, mas a confiar na sua proteção e orientação, assim como ele também encorajou Ezequiel.
* Ezequiel 3:17: "Filho do homem, eu fiz de ti sentinela para a casa de Israel; por isso ouve a palavra que eu te digo e avisa-os da minha parte." Neste versículo, Deus confirma a Ezequiel que o escolheu para ser um sentinela e mensageiro para o povo de Israel, assim como lhe deu a missão de adverti-los dos seus pecados.
* Mateus 10:16: "Eu vos envio como ovelhas no meio de lobos. Portanto, sede prudentes como as serpentes e simples como as pombas." Este versículo mostra a semelhança entre a missão de Ezequiel e a de Jesus, que também enviou seus discípulos para pregar e advertir o povo, mesmo em meio à hostilidade e oposição.
* Atos 20:26-27: "Por isso, neste dia, eu vos declaro que sou inocente do sangue de todos, pois não deixei de proclamar a vocês toda a vontade de Deus." O apóstolo Paulo declarou sua fidelidade ao cumprir a missão de pregar a palavra de Deus, semelhante ao compromisso de Ezequiel de advertir o povo de Israel da vontade de Deus.
****

[[v33-2-1]]

^<<v33-2-1,1>>^ “Filho do homem” – dizia-me –, “fica de pé, porque eu te falo!”^&#42;1^

[[v33-2-2]]

^<<v33-2-2,2>>^ Enquanto ela me falava, entrou o espírito em mim, e ele me fez ficar de pé; então, ouvi aquele que me falava.

[[v33-2-3]]

^<<v33-2-3,3>>^ “Filho do homem” – dizia-me –, “envio-te aos israelitas, a essa nação de rebeldes, revoltada contra mim, a qual, do mesmo modo que seus pais, vem pecando contra mim até este dia.

[[v33-2-4]]

^<<v33-2-4,4>>^ É a esses filhos de testa dura e de coração insensível que te envio, para lhes dizer: oráculo do Senhor Javé.

[[v33-2-5]]

^<<v33-2-5,5>>^ Quer te ouçam ou não (pois é uma raça indomável), hão de ficar sabendo que há um profeta no meio deles!

[[v33-2-6]]

^<<v33-2-6,6>>^ Quanto a ti, filho do homem, não os temas, nem te arreceies dos seus intentos, conquanto estejas entre moitas de abrolhos e de espinhos e vivas entre escorpiões; não te deixes intimidar por suas palavras nem te espantes com sua atitude, porque é uma raça rebelde.

[[v33-2-7]]

^<<v33-2-7,7>>^ Tu lhes transmitirás os meus oráculos, quer te deem ouvidos ou não; é uma raça pertinaz.

[[v33-2-8]]

^<<v33-2-8,8>>^ E tu, filho do homem, escuta o que eu te digo: não sejas rebelde, como essa raça de rebelados. Abre a boca e come o que te vou dar.”

[[v33-2-9]]

^<<v33-2-9,9>>^ Olhei e vi avançando para mim uma mão, que segurava um manuscrito enrolado,

[[v33-2-10]]

^<<v33-2-10,10>>^ que foi desdobrado diante de mim: estava coberto com escrita de um e de outro lado: eram cânticos de luto, de queixumes e de gemidos.^&#42;1^

'''

xref:033-ezequiel/033-ezequiel-001.adoc#v33-1-0[&#60; Capítulo Anterior] | <<v33-2-0,Topo>> | xref:033-ezequiel/033-ezequiel-003.adoc#v33-3-0[Próximo Capítulo &#62;]