include::./index.adoc[]

[[v33-37-0]]
=== Ezequiel, 37
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 37 de Ezequiel fala sobre a visão de Ezequiel do vale dos ossos secos e como Deus os faz reviver. Também fala sobre como Deus unirá as tribos de Israel e as trará de volta para sua terra. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Jeremias 32:27: "Eis que sou o Senhor, o Deus de toda a carne; acaso há alguma coisa impossível para mim?" Este versículo mostra o poder e a capacidade de Deus para realizar milagres, como trazer vida a ossos secos e unir tribos distantes.
* Salmos 126:4: "Restaura-nos, ó Senhor, como as correntes no sul." Este salmo fala sobre a restauração de Israel e como Deus pode trazer de volta alegria e prosperidade ao seu povo.
* Isaías 11:12: "Ele levantará um estandarte para as nações, ajuntará os exilados de Israel e reunirá os dispersos de Judá desde os quatro cantos da terra." Este verso fala sobre como Deus unirá as tribos de Israel e as trará de volta para a terra.
* Ezequiel 34:23: "Estabelecerei sobre elas um único pastor, que as apascentará; meu servo Davi será o seu pastor. Ele cuidará delas, e será o seu pastor." Este verso fala sobre como Deus vai estabelecer um líder justo para guiar seu povo e como isso é importante para sua restauração.
* João 11:25: "Disse-lhe Jesus: Eu sou a ressurreição e a vida. Aquele que crê em mim, ainda que morra, viverá." Este verso fala sobre a promessa de Jesus de dar vida eterna aos que creem nele, reforçando a ideia de que Deus pode trazer vida mesmo a ossos secos e mortos.
****

[[v33-37-1]]

^<<v33-37-1,1>>^ A mão do Senhor desceu sobre mim. Ele me arrebatou em espírito e me colocou no meio de uma planície, que estava coberta de ossos.

[[v33-37-2]]

^<<v33-37-2,2>>^ Ele fez-me circular em todos os sentidos no meio desses ossos numerosos que jaziam na superfície. Vi que estavam inteiramente secos.

[[v33-37-3]]

^<<v33-37-3,3>>^ Disse-me o Senhor: “Filho do homem, poderiam esses ossos retornar à vida?”. “Senhor Javé” – respondi –, “só vós o sabeis.”

[[v33-37-4]]

^<<v33-37-4,4>>^ Ele disse-me então: “Profere um oráculo sobre esses ossos. Ossos dessecados, lhes dirás, escutai a palavra do Senhor:

[[v33-37-5]]

^<<v33-37-5,5>>^ eis o que vos declara o Senhor Javé: vou fazer reentrar em vós o sopro da vida para vos fazer reviver.

[[v33-37-6]]

^<<v33-37-6,6>>^ Porei em vós músculos, farei vir carne sobre vós, vos cobrirei de pele; depois farei entrar em vós o sopro da vida, a fim de que revivais. E sabereis assim que eu sou o Senhor.

[[v33-37-7]]

^<<v33-37-7,7>>^ Profetizei, pois, assim como tinha recebido ordem. No momento em que comecei, um barulho se fez ouvir, em seguida um ruído ensurdecedor, enquanto os ossos se vinham unir aos outros.

[[v33-37-8]]

^<<v33-37-8,8>>^ Prestando atenção, vi que se formavam sobre eles músculos, que nascia neles carne e que uma pele os recobria. Todavia, não tinham espírito.^&#42;1^

[[v33-37-9]]

^<<v33-37-9,9>>^ Profetiza ao espírito, disse-me o Senhor, profetiza, filho do homem, e dirige-te ao espírito: eis o que diz o Senhor Javé: vem, espírito, dos quatro cantos do céu, sopra sobre esses mortos para que reviva”.

[[v33-37-10]]

^<<v33-37-10,10>>^ Proferi o oráculo que ele me havia ditado, e daí a pouco o espírito penetrou neles. Retornando à vida, eles se levantaram sobre seus pés: um grande, um imenso exército.

[[v33-37-11]]

^<<v33-37-11,11>>^ Então, o Senhor me disse: “Filho do homem, esses ossos são toda a raça dos israelitas. Eles dizem: nossos ossos estão secos, nossa esperança está morta; estamos perdidos!

[[v33-37-12]]

^<<v33-37-12,12>>^ Por isso, dirige-lhes o seguinte oráculo: eis o que diz o Senhor Javé: Ó meu povo, vou abrir os vossos túmulos; eu vos farei sair deles para vos transportar à terra de Israel.

[[v33-37-13]]

^<<v33-37-13,13>>^ Sabereis, então, que eu é que sou o Senhor, ó meu povo, quando eu abrir os vossos túmulos e vos fizer sair deles,

[[v33-37-14]]

^<<v33-37-14,14>>^ quando eu colocar em vós o meu espírito para vos fazer voltar à vida e quando vos hei de restabelecer em vossa terra. Sabereis então que sou eu o Senhor, que o disse e o executei – oráculo do Senhor”.

[[v33-37-15]]

^<<v33-37-15,15>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-37-16]]

^<<v33-37-16,16>>^ “Filho do homem, toma um pedaço de madeira e escreve nele: Judá e os israelitas que estão com ele. Em seguida, tomarás outro no qual escreverás: José, madeira de Efraim, e todos os israelitas que estão com ele.

[[v33-37-17]]

^<<v33-37-17,17>>^ Em seguida, os ajuntarás um ao outro, de modo que só formem um pedaço em tua mão.

[[v33-37-18]]

^<<v33-37-18,18>>^ Quando teus compatriotas te perguntarem o que queres dizer com isso,

[[v33-37-19]]

^<<v33-37-19,19>>^ responderás: eis o que diz o Senhor Javé: vou tomar o lenho de José, que está na mão de Efraim, assim como as tribos de Israel que estão com ele, para juntá-lo ao lenho de Judá, de modo que, unidos na mão, não sejam senão um.^&#42;1^

[[v33-37-20]]

^<<v33-37-20,20>>^ Guardarás ostensivamente na mão os pedaços de madeira em que houveres feito essas inscrições,

[[v33-37-21]]

^<<v33-37-21,21>>^ e tu dirás: eis o que diz o Senhor Javé: vou recolher os israelitas de entre as nações onde se acham dispersos; vou congregá-los de toda parte e trazê-los para a sua terra.

[[v33-37-22]]

^<<v33-37-22,22>>^ Farei com que, em sua terra, sobre as montanhas de Israel, não formem mais do que uma só nação, que não possuam mais do que um rei. Não mais existirá a divisão em dois povos e em dois reinos.

[[v33-37-23]]

^<<v33-37-23,23>>^ Não mais se mancharão com seus ídolos nem cometerão infames abominações: eu os libertarei de todas as transgressões de que se tornaram culpados e os purificarei. Eles serão o meu povo, e eu serei o seu Deus.

[[v33-37-24]]

^<<v33-37-24,24>>^ Meu servo Davi será o seu rei; não terão todos senão um só pastor; obedecerão aos meus mandamentos, observarão as minhas leis e as porão em prática.^&#42;1^

[[v33-37-25]]

^<<v33-37-25,25>>^ Habitarão a terra que concedi a meu servidor Jacó, aquela em que vossos pais residiram; eles aí permanecerão; eles, seus filhos e os filhos de seus filhos para sempre. Davi, meu servo, será para sempre o seu rei.

[[v33-37-26]]

^<<v33-37-26,26>>^ Concluirei com eles uma aliança de paz, um tratado eterno. Eu os plantarei e os multiplicarei. Estabelecerei para sempre o meu santuário entre eles.

[[v33-37-27]]

^<<v33-37-27,27>>^ Minha residência será no meio deles. Eu serei o seu Deus, e eles serão o meu povo.

[[v33-37-28]]

^<<v33-37-28,28>>^ E as nações saberão que sou eu, o Senhor, quem santifica Israel, quando o meu santuário se achar constituído para sempre no meio do meu povo”.

'''

xref:033-ezequiel/033-ezequiel-036.adoc#v33-36-0[&#60; Capítulo Anterior] | <<v33-37-0,Topo>> | xref:033-ezequiel/033-ezequiel-038.adoc#v33-38-0[Próximo Capítulo &#62;]