include::./index.adoc[]

[[v33-12-0]]
=== Ezequiel, 12
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 12 descreve a visão do profeta sobre o exílio de Judá e a consequente queda de Jerusalém. Deus instrui Ezequiel a agir como um exilado, fazendo com que as pessoas percebam a inevitabilidade do exílio que se aproxima. Os versículos relacionados com os temas abordados em Ezequiel 12 são:
* Jeremias 29:4-7: "Assim diz o Senhor dos Exércitos, Deus de Israel, a todos os exilados que eu deportei de Jerusalém para a Babilônia: Edificai casas e habitai nelas; plantai jardins e comei os seus frutos. Casai-vos e tende filhos e filhas; casai vossos filhos e filhas e dai-os em casamento; e procurai a paz da cidade para onde vos deportei e orai ao Senhor em seu favor, porque na sua paz vós tereis paz." Este versículo encoraja os exilados a construir uma nova vida para si na Babilônia e a se ajustarem à sua nova realidade.
* Ezequiel 3:17-18: "Filho do homem, eu te dei por atalaia sobre a casa de Israel; quando ouvires uma palavra da minha boca, tu os avisarás da minha parte. Quando eu disser ao ímpio: Certamente morrerás; e tu não o avisares, nem falares para avisar o ímpio de seu caminho ímpio, para salvar a sua vida, aquele ímpio morrerá por sua iniquidade; mas o seu sangue eu o requererei da tua mão." Este versículo fala sobre a responsabilidade de Ezequiel como profeta de alertar o povo sobre o julgamento de Deus, a fim de que possam se arrepender e ser salvos.
* Jeremias 39:1-2: "No nono ano de Zedequias, rei de Judá, no décimo mês, Nabucodonosor, rei da Babilônia, veio com todo o seu exército contra Jerusalém e a sitiou. E no décimo primeiro ano de Zedequias, no quarto mês, no nono dia do mês, a cidade foi arrombada." Este versículo descreve a queda de Jerusalém, que foi o evento que Ezequiel estava profetizando que aconteceria.
* Ezequiel 12:21-23: "E veio a mim a palavra do Senhor, dizendo: Filho do homem, que é esse provérbio que vós tendes na terra de Israel, que diz: Os dias se prolongam, e toda a visão se desvanece? Portanto, dize-lhes: Assim diz o Senhor Deus: Farei cessar esse provérbio, e não se repetirá mais em Israel; mas dize-lhes: Os dias estão próximos, e a visão de todo o profeta se cumprirá." Este versículo mostra que Deus está ciente do pensamento das pessoas de que a profecia nunca se cumprirá e que ele está prestes a agir para provar que suas palavras são verdadeiras.
* Salmos 52:3-4: "Amas o mal mais do que o bem, a mentira mais do que a verdade. Amas toda palavra perniciosa, ó língua enganadora!" Este versículo fala sobre a importância da verdade e da honestidade, algo que Ezequiel enfatiza ao falar das consequências dos pecados do povo.
****

[[v33-12-1]]

^<<v33-12-1,1>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-12-2]]

^<<v33-12-2,2>>^ “Filho do homem, habitas em meio de uma casta de recalcitrantes, de gente que tem olhos para ver e não vê nada, ouvidos para escutar e nada ouve; é uma raça de recalcitrantes.

[[v33-12-3]]

^<<v33-12-3,3>>^ Pois bem, filho do homem, prepara-te uma bagagem de emigrante, e parte, em pleno dia, sob os seus olhos. Parte sob os olhos deles, do lugar onde habitas para outro local. Talvez reconheçam que são eles um bando de recalcitrantes.

[[v33-12-4]]

^<<v33-12-4,4>>^ Prepararás a tua bagagem em pleno dia, sob os seus olhares, como um fardo de emigrante. E depois, à noite, sob os seus olhares, seguirás como um homem que parte para o exílio.

[[v33-12-5]]

^<<v33-12-5,5>>^ Ante as vistas deles, farás um buraco no muro, pelo qual farás passar o teu fardo.

[[v33-12-6]]

^<<v33-12-6,6>>^ À vista deles, o carregarás aos ombros e sairás, quando escurecer, a fronte velada, de modo que não vejas a pátria! Faço assim de ti um símbolo para a casa de Israel”.

[[v33-12-7]]

^<<v33-12-7,7>>^ Fiz como me ordenara. Em pleno dia deixei os meus afazeres e preparei uma espécie de bagagem de emigrante; em seguida, à noite, furei a muralha, com minha própria mão; após isso, quando se fez noite, pus minha bagagem nos ombros, e saí à vista deles.

[[v33-12-8]]

^<<v33-12-8,8>>^ Logo ao amanhecer, a palavra do Senhor foi-me dirigida nestes termos:

[[v33-12-9]]

^<<v33-12-9,9>>^ “Filho do homem, a casa de Israel, esse bando de recalcitrantes, não te perguntou o que fazias lá?

[[v33-12-10]]

^<<v33-12-10,10>>^ Dize-lhes: eis o que diz o Senhor Javé: isto é um oráculo relativo ao príncipe que se acha em Jerusalém e a toda a casa de Israel, que ali se encontra.^&#42;1^

[[v33-12-11]]

^<<v33-12-11,11>>^ Dirás: sou para vós um símbolo; assim como tenho feito, assim lhes há de suceder: irão para o exílio, deportados.

[[v33-12-12]]

^<<v33-12-12,12>>^ O príncipe, que está no meio deles, porá a bagagem às costas e sairá ao anoitecer; fará um buraco no muro para poder sair dele: cobrirá a face para não ver a pátria.

[[v33-12-13]]

^<<v33-12-13,13>>^ Mas eu lançarei sobre ele o meu laço e ele será apanhado em minhas redes. Eu o conduzirei à Babilônia, à terra dos caldeus; ele, porém, não a verá. É lá que terá de morrer.

[[v33-12-14]]

^<<v33-12-14,14>>^ Todo o seu séquito, sua guarda, suas tropas, eu os semearei aos (quatro) ventos e tirarei a espada contra eles.

[[v33-12-15]]

^<<v33-12-15,15>>^ Quando eu os tiver disseminado por entre as nações, e dispersado por todos os países, saberão que sou eu o Senhor.

[[v33-12-16]]

^<<v33-12-16,16>>^ Mas hei de poupar um resto deles; alguns hão de escapar ao gládio, à fome e à peste, para que venham a contar aos povos, entre os quais se estabelecerem, as abominações (de Israel). E conhecerão eles que sou eu o Senhor”.

[[v33-12-17]]

^<<v33-12-17,17>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-12-18]]

^<<v33-12-18,18>>^ “Filho do homem, come o teu pão com tremor, bebe a tua água com (sinais de) inquietação e receio.^&#42;1^

[[v33-12-19]]

^<<v33-12-19,19>>^ E dirás às gentes desta terra: eis o que diz o Senhor Javé para os habitantes de Jerusalém, e da terra de Israel. É na aflição que hão de comer o seu pão e no terror que beberão a sua água, porque a terra será despojada de tudo quanto nela se encontra, devido às violências dos seus habitantes.

[[v33-12-20]]

^<<v33-12-20,20>>^ As cidades habitadas serão despovoadas e a terra há de ser devastada. Sabereis assim que sou eu o Senhor”.

[[v33-12-21]]

^<<v33-12-21,21>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-12-22]]

^<<v33-12-22,22>>^ “Filho do homem, que ditado é esse que corre em Israel: passam os dias, mas as visões ficam sem efeito?^&#42;1^

[[v33-12-23]]

^<<v33-12-23,23>>^ Pois bem, dize-lhes: eis o que diz o Senhor: farei cessar esse provérbio, não se repetirá mais isso em Israel. Dize-lhes, pois: aproximam-se os dias em que todas essas visões se hão de cumprir.

[[v33-12-24]]

^<<v33-12-24,24>>^ Nenhuma visão daqui por diante será vã e nenhum oráculo, ineficaz em Israel,

[[v33-12-25]]

^<<v33-12-25,25>>^ porque sou eu, o Senhor, que falo: o que eu digo sucederá sem mais delongas. É em vosso tempo, raça de rebeldes, que proferirei o oráculo e o executarei – oráculo do Senhor Javé”.

[[v33-12-26]]

^<<v33-12-26,26>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-12-27]]

^<<v33-12-27,27>>^ “Filho do homem, dizem os israelitas: a visão do profeta não diz respeito senão a um longínquo futuro. Pois bem, dize-lhes: eis o que diz o Senhor Javé: não há mais delongas para meus oráculos. O que eu digo vai acontecer, – oráculo do Senhor Javé”.

'''

xref:033-ezequiel/033-ezequiel-011.adoc#v33-11-0[&#60; Capítulo Anterior] | <<v33-12-0,Topo>> | xref:033-ezequiel/033-ezequiel-013.adoc#v33-13-0[Próximo Capítulo &#62;]