include::./index.adoc[]

[[v33-18-0]]
=== Ezequiel, 18
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 18 é um capítulo que trata da responsabilidade pessoal diante de Deus e de como Ele julga as pessoas de acordo com suas próprias ações, e não pelas de seus pais ou filhos. O capítulo responde a uma pergunta comum na época: "Por que os pais sofrem pelas maldades dos filhos?" ou "Por que os filhos sofrem pelas maldades dos pais?" Ezequiel enfatiza que a justiça de Deus é individual e que cada pessoa é responsável por suas próprias escolhas. Aqui estão cinco versículos relacionados com os temas abordados em Ezequiel 18:
* Deuteronômio 24:16: "Os pais não serão mortos em lugar dos filhos, nem os filhos em lugar dos pais; cada um será morto pelo seu próprio pecado." Este versículo destaca a responsabilidade pessoal e a justiça individual diante de Deus.
* Provérbios 22:8: "O que semeia a perversidade segará males; e com a vara da sua própria indignação será extinto." Este versículo fala sobre as consequências das más escolhas e como elas podem afetar a vida da pessoa.
* Gálatas 6:7: "Não vos enganeis: Deus não se deixa escarnecer; porque tudo o que o homem semear, isso também ceifará." Este versículo destaca a responsabilidade pessoal e o fato de que cada pessoa colherá o que semeou.
* Tiago 1:14-15: "Mas cada um é tentado, quando atraído e engodado pela sua própria concupiscência. Depois, havendo a concupiscência concebido, dá à luz o pecado; e o pecado, sendo consumado, gera a morte." Este versículo fala sobre como as tentações podem levar ao pecado e à morte espiritual, e destaca a responsabilidade pessoal de resistir às tentações.
* Romanos 14:12: "Assim, pois, cada um de nós dará conta de si mesmo a Deus." Este versículo destaca novamente a responsabilidade pessoal diante de Deus e como cada pessoa prestará contas de suas próprias ações.
****

[[v33-18-1]]

^<<v33-18-1,1>>^ A palavra do Senhor foi-me dirigida nestes termos: “Por que repetis continuamente esse provérbio entre os israelitas:

[[v33-18-2]]

^<<v33-18-2,2>>^ os pais comeram uvas verdes, mas são os dentes dos filhos que ficam embotados?

[[v33-18-3]]

^<<v33-18-3,3>>^ Por minha vida – oráculo do Senhor Javé –, não tereis mais ocasião de repetir esse provérbio em Israel.

[[v33-18-4]]

^<<v33-18-4,4>>^ É a mim que pertencem as vidas, a vida do pai e a vida do filho. Ora, é o culpado que morrerá.

[[v33-18-5]]

^<<v33-18-5,5>>^ O homem justo – que procede segundo o direito e a equidade,

[[v33-18-6]]

^<<v33-18-6,6>>^ que não participa dos festins das montanhas, que não volve os olhos para os ídolos da casa de Israel, que não desonra a mulher do próximo, e não tem relação com uma mulher durante o tempo de sua impureza,^&#42;1^

[[v33-18-7]]

^<<v33-18-7,7>>^ que não oprime ninguém, que restitui o penhor ao seu devedor, que não exerce a rapina, que dá seu pão aos famintos, e cobre com vestimenta o que está nu,

[[v33-18-8]]

^<<v33-18-8,8>>^ que não empresta à taxa usurária e não recebe com juros, que afasta a sua mão da iniquidade, e julga equitativamente entre um homem e outro,

[[v33-18-9]]

^<<v33-18-9,9>>^ que segue os meus preceitos e observa as minhas leis, para proceder com retidão – certamente viverá. Oráculo do Senhor Javé.

[[v33-18-10]]

^<<v33-18-10,10>>^ Porém, se esse homem gerou um filho violento e sanguinário, que comete (contra seu irmão) uma dessas faltas

[[v33-18-11]]

^<<v33-18-11,11>>^ embora ele próprio não tenha cometido nenhuma; um filho que come nas montanhas e desonra a mulher do próximo,

[[v33-18-12]]

^<<v33-18-12,12>>^ que oprime o infeliz e o indigente, que pratica a rapina e não restitui o penhor, que ergue os olhos para os ídolos e comete abominações,

[[v33-18-13]]

^<<v33-18-13,13>>^ que faz empréstimo com usura e recebe juros, esse rapaz não poderá permanecer em vida. Após as abominações que houver cometido, ele deve perecer, e seu sangue recairá sobre ele.

[[v33-18-14]]

^<<v33-18-14,14>>^ Se, pelo contrário, o homem gerou um filho que, à vista de todas as faltas cometidas por seu pai, tem o cuidado de não imitá-lo,^&#42;1^

[[v33-18-15]]

^<<v33-18-15,15>>^ um filho que não come nas montanhas e não volve os olhos para os ídolos da casa de Israel, que não desonra a mulher do próximo,

[[v33-18-16]]

^<<v33-18-16,16>>^ não oprime ninguém, e não retém o penhor; não pratica a rapinagem, dá pão ao faminto e cobre com vestimenta o que está nu;

[[v33-18-17]]

^<<v33-18-17,17>>^ que se abstém de causar dano ao infeliz, que não empresta com usura e nem recebe juros, mas observa os meus mandamentos e procede de conformidade com as minhas leis – esse filho não perecerá pelas iniquidades de seu pai mas certamente viverá.

[[v33-18-18]]

^<<v33-18-18,18>>^ É seu pai que, pelas violências e rapinas que cometeu contra o próximo e pelo mal que fez no meio do seu povo, há de perecer por causa de suas faltas.

[[v33-18-19]]

^<<v33-18-19,19>>^ Perguntais por que não leva o filho a iniquidade do pai! É que o filho praticou a justiça e a equidade e, como observa e cumpre as minhas leis, também ele viverá.

[[v33-18-20]]

^<<v33-18-20,20>>^ É o pecador que deve perecer. Nem o filho responderá pelas faltas do pai nem o pai pelas do filho. É ao justo que se imputará sua justiça e ao mau a sua malícia.

[[v33-18-21]]

^<<v33-18-21,21>>^ Se, no entanto, o mau renuncia a todos os seus erros para praticar as minhas leis e seguir a justiça e a equidade, então ele viverá decerto, e não há de perecer.

[[v33-18-22]]

^<<v33-18-22,22>>^ Não lhe será tomada em conta qualquer das faltas cometidas: ele há de viver por causa da justiça que praticou.

[[v33-18-23]]

^<<v33-18-23,23>>^ Terei eu prazer com a morte do malvado? – oráculo do Senhor Javé –. Não desejo eu, antes, que ele mude de proceder e viva?^&#42;1^

[[v33-18-24]]

^<<v33-18-24,24>>^ E, se um justo abandonar a sua justiça, se praticar o mal e imitar todas as abominações cometidas pelo malvado, viverá ele? Não será tido em conta qualquer dos atos bons que houver praticado. É em razão da infidelidade da qual se tornou culpado e dos pecados que tiver cometido que deverá morrer.

[[v33-18-25]]

^<<v33-18-25,25>>^ Dizeis: não é justo o modo de proceder do Senhor. Escutai-me então, israelitas: o meu modo de proceder não é justo? Não será o vosso que é injusto?

[[v33-18-26]]

^<<v33-18-26,26>>^ Quando um justo renunciar à sua justiça para cometer o mal e ele morrer, então é devido ao mal praticado que ele perece.

[[v33-18-27]]

^<<v33-18-27,27>>^ Quando um malvado renuncia ao mal para praticar a justiça e a equidade, ele faz reviver a sua alma.

[[v33-18-28]]

^<<v33-18-28,28>>^ Se ele se corrige e renuncia a todas as suas faltas, certamente viverá e não perecerá.

[[v33-18-29]]

^<<v33-18-29,29>>^ E eis que a casa de Israel pretende que o modo de proceder do Senhor não seja justo! Não é acaso o vosso modo de proceder que é injusto?

[[v33-18-30]]

^<<v33-18-30,30>>^ Assim, pois, casa de Israel, é segundo o vosso próprio proceder que julgarei cada um de vós – oráculo do Senhor Javé. Convertei-vos! Renunciai a todas as vossas faltas! Que não haja mais em vós o mal que vos faça cair.

[[v33-18-31]]

^<<v33-18-31,31>>^ Repeli para longe de vós todas as vossas culpas, para criardes em vós um coração novo e um novo espírito. Por que haveríeis de morrer, israelitas?

[[v33-18-32]]

^<<v33-18-32,32>>^ Não sinto prazer com a morte de quem quer que seja – oráculo do Senhor Javé! Convertei-vos e vivereis!”.

'''

xref:033-ezequiel/033-ezequiel-017.adoc#v33-17-0[&#60; Capítulo Anterior] | <<v33-18-0,Topo>> | xref:033-ezequiel/033-ezequiel-019.adoc#v33-19-0[Próximo Capítulo &#62;]