include::./index.adoc[]

[[v33-26-0]]
=== Ezequiel, 26
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 26 contém uma profecia sobre a destruição da cidade de Tiro. Os versículos selecionados abaixo estão relacionados com a soberania de Deus e sua capacidade de julgar as nações:
* Salmos 75:6-7: "Nas mãos do Senhor está um cálice cheio de vinho espumante, misturado com especiarias; ele o derrama, e todos os ímpios da terra o bebem até o fim. Eu o proclamarei para sempre, cantarei louvores ao Deus de Jacó." Este versículo destaca que Deus tem o poder de julgar as nações e punir os ímpios, e que devemos proclamar sua soberania e louvá-lo por isso.
* Isaías 40:15: "Com quem vocês podem comparar a Deus? A que imagem poderão assemelhá-lo?" Este versículo enfatiza a grandeza e singularidade de Deus, destacando que não há nada no mundo que se possa comparar a ele.
* Daniel 4:35: "Todos os povos da terra são como nada diante dele. Ele age como lhe agrada com os exércitos dos céus e com os habitantes da terra. Ninguém é capaz de resistir à sua mão nem de questioná-lo: 'O que você está fazendo?'" Este versículo destaca a soberania de Deus sobre todas as nações e sua capacidade de agir como quiser com as coisas criadas.
* Miqueias 5:15: "Com fúria e ira castigarei as nações que não me obedeceram." Este versículo enfatiza que Deus pode e irá punir as nações que não obedecem seus mandamentos, mostrando sua capacidade de julgar a todos.
* Mateus 28:18: "Então Jesus aproximou-se deles e disse: 'Foi-me dada toda a autoridade no céu e na terra.'" Este versículo destaca a autoridade suprema de Jesus como Senhor e governante de todas as coisas, enfatizando sua soberania sobre todas as nações e poder de julgar.
****

[[v33-26-1]]

^<<v33-26-1,1>>^ No décimo primeiro ano, no primeiro dia do mês, a palavra do Senhor foi-me dirigida nestes termos:^&#42;1^

[[v33-26-2]]

^<<v33-26-2,2>>^ “Filho do homem, sabes o que Tiro disse de Jerusalém: ‘Ah! Ah! Ei-la quebrada, a porta dos povos. É para mim que ela vai voltar-se; vou me enriquecer; ela foi devastada!’^&#42;1^

[[v33-26-3]]

^<<v33-26-3,3>>^ Por isso, eis o que diz o Senhor Javé: Tiro, é contra ti que irei: vou suscitar contra ti nações tão numerosas quanto as ondas que o mar levanta;

[[v33-26-4]]

^<<v33-26-4,4>>^ elas destruirão os muros de Tiro e demolirão as torres, varrerei dela o pó, e dela farei uma rocha desnuda;

[[v33-26-5]]

^<<v33-26-5,5>>^ ela será, no meio do mar, um lugar onde se estendem as redes. Sou eu quem o declara – oráculo do Senhor Javé. Ela será a presa das nações.

[[v33-26-6]]

^<<v33-26-6,6>>^ Suas filhas, em terra firme, serão mortas pelo gládio; e se reconhecerá que sou eu o Senhor.^&#42;1^

[[v33-26-7]]

^<<v33-26-7,7>>^ Eis o que diz o Senhor Javé: do Norte, mando contra Tiro Nabucodonosor, rei da Babilônia, o rei dos reis, com parelhas, carros, cavaleiros e massa enorme de tropas.

[[v33-26-8]]

^<<v33-26-8,8>>^ Ele matará pela espada tuas filhas, que estão em terra firme, comandará o bloqueio contra ti, construirá aterros contra ti, e contra ti empunhará o escudo.

[[v33-26-9]]

^<<v33-26-9,9>>^ Quebrará teus muros a golpes de aríetes, com seus engenhos demolirá tuas torres.

[[v33-26-10]]

^<<v33-26-10,10>>^ Tão numerosos são os seus cavalos, que sua poeira te envolverá. Tremerão as tuas muralhas aos embates de seus cavaleiros, das engrenagens de seus carros, quando ele entrar por tuas portas, como se entra em uma cidade conquistada.

[[v33-26-11]]

^<<v33-26-11,11>>^ Com os pés dos seus cavalos calcará todas as tuas ruas, passará teu povo a fio de espada; teus imponentes obeliscos religiosos serão arremessados por terra.

[[v33-26-12]]

^<<v33-26-12,12>>^ Serão pilhadas as tuas riquezas, pilharão tuas mercadorias, serão demolidas as tuas muralhas, arrasados os teus luxuosos palácios; tuas pedras, tua madeira, tua caliça serão lançadas ao mar.

[[v33-26-13]]

^<<v33-26-13,13>>^ Farei calar a voz dos cânticos, não mais se escutará o som das tuas harpas.

[[v33-26-14]]

^<<v33-26-14,14>>^ Farei de ti uma rocha nua, um lugar onde se estendem redes; tu não serás jamais reconstruída. Sou eu, o Senhor, que o digo – oráculo do Senhor Javé.

[[v33-26-15]]

^<<v33-26-15,15>>^ Eis o que diz a Tiro o Senhor Javé: ao estrondo de tua queda, quando estiverem gemendo os feridos, e quando se proceder à mortandade em teu seio, as ilhas tremerão.

[[v33-26-16]]

^<<v33-26-16,16>>^ Descerão do seu trono os príncipes do mar, deporão seus mantos, deixarão suas vestimentas bordadas, para demonstrar o seu espanto, para se assentarem no chão, e, consternados com o que virem, tremerão sem parar.

[[v33-26-17]]

^<<v33-26-17,17>>^ Proferirão a teu respeito este cântico fúnebre: como pereceste, habitante dos mares? Cidade altiva, tão poderosa no mar, com os teus habitantes, que se faziam temer por todos os povos marítimos!^&#42;1^

[[v33-26-18]]

^<<v33-26-18,18>>^ Eis que tremem as ilhas desde o dia de tua queda; as ilhas do mar estão aterrorizadas com o teu destino.

[[v33-26-19]]

^<<v33-26-19,19>>^ Eis o que diz o Senhor Javé: quando eu tiver feito de ti uma cidade deserta, semelhante às cidades despovoadas, quando eu tiver feito com que o abismo venha sobre ti, e as grandes águas te houverem coberto,

[[v33-26-20]]

^<<v33-26-20,20>>^ eu me precipitarei como os que descem à fossa, com as gentes de outrora; irei instalar-te nas moradas infernais, nas solidões eternas, com os que descem ao túmulo, a fim de que não sejas mais habitada, quando eu devolver o esplendor à terra dos vivos.^&#42;1^

[[v33-26-21]]

^<<v33-26-21,21>>^ De ti farei objeto de horror; não mais existirás; e, quando alguém te procurar, não mais serás encontrada – oráculo do Senhor Javé”.

'''

xref:033-ezequiel/033-ezequiel-025.adoc#v33-25-0[&#60; Capítulo Anterior] | <<v33-26-0,Topo>> | xref:033-ezequiel/033-ezequiel-027.adoc#v33-27-0[Próximo Capítulo &#62;]