include::./index.adoc[]

[[v33-44-0]]
=== Ezequiel, 44
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 44 é um capítulo que trata sobre a restauração do templo e do serviço de adoração a Deus. Neste capítulo, Deus fala sobre a importância de ter sacerdotes fiéis e santos, que cumpram as suas funções de forma adequada e respeitem as suas leis. Também é mencionado o papel dos levitas, que ajudam os sacerdotes nas suas tarefas. A seguir, cinco versículos relacionados com os temas abordados em Ezequiel 44:
* Levítico 10:10-11: "Para que façais a diferença entre o santo e o profano e entre o impuro e o limpo. E para que ensineis aos filhos de Israel todos os estatutos que o Senhor lhes tem falado por meio de Moisés." Este versículo fala sobre a importância de distinguir entre o que é santo e o que é profano, e ensinar os mandamentos de Deus aos filhos de Israel.
* 1 Pedro 2:9: "Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz." Este versículo fala sobre o papel dos cristãos como sacerdotes, que foram chamados para anunciar as virtudes de Deus e viver uma vida santa.
* 1 Timóteo 4:14: "Não desprezes o dom que há em ti, o qual te foi dado por profecia, com a imposição das mãos do presbitério." Este versículo fala sobre a importância de reconhecer e utilizar os dons espirituais que Deus nos deu, para servir ao seu povo e cumprir a sua vontade.
* 2 Crônicas 29:34: "Porém, os sacerdotes eram poucos e não podiam esfolar todos os holocaustos; pelo que seus irmãos, os levitas, os ajudaram, até que a obra se acabou, e até que outros sacerdotes se santificaram, porque os levitas foram mais retos de coração para se santificarem do que os sacerdotes." Este versículo fala sobre o papel dos levitas em ajudar os sacerdotes nas suas tarefas, e como eles eram mais cuidadosos em se santificar do que os próprios sacerdotes.
* Hebreus 7:26-27: "Porque nos convinha tal sumo sacerdote, santo, inocente, imaculado, separado dos pecadores e feito mais sublime do que os céus; que não necessita, como os sumos sacerdotes, de oferecer cada dia sacrifícios, primeiro por seus próprios pecados, e depois pelos do povo; porque isto fez ele uma vez, oferecendo-se a si mesmo." Este versículo fala sobre Jesus Cristo como o nosso sumo sacerdote perfeito, que ofereceu a si mesmo como sacrifício pelos nossos pecados e nos reconciliou com Deus.
****

[[v33-44-1]]

^<<v33-44-1,1>>^ Ele reconduziu-me ao pórtico exterior do santuário, que fica fronteiro ao oriente, o qual se achava fechado.

[[v33-44-2]]

^<<v33-44-2,2>>^ O Senhor disse-me: “Este pórtico ficará fechado. Ninguém o abrirá, ninguém aí passará, porque o Senhor, Deus de Israel, aí passou; ele permanecerá fechado.

[[v33-44-3]]

^<<v33-44-3,3>>^ O príncipe, entretanto, enquanto tal, poderá aí assentar-se para tomar sua refeição diante do Senhor. Ele entrará pelo vestíbulo do pórtico e sairá pelo mesmo caminho”.^&#42;1^

[[v33-44-4]]

^<<v33-44-4,4>>^ Ele conduziu-me em seguida pelo pórtico norte, diante do templo. Lá, pude contemplar a glória do Senhor que enchia o Templo do Senhor; a essa vista, caí com a face em terra.

[[v33-44-5]]

^<<v33-44-5,5>>^ O Senhor disse-me: “Filho do homem, presta bem atenção; olha bem com teus olhos. Fica com o ouvido atento ao que te vou dizer: são as leis e as ordens concernentes ao Templo do Senhor. Vela com cuidado a admissão no templo, assim como a exclusão do santuário.

[[v33-44-6]]

^<<v33-44-6,6>>^ Dirás a esses rebeldes israelitas: eis o que diz o Senhor Javé: israelitas, basta! Chega de abominações!

[[v33-44-7]]

^<<v33-44-7,7>>^ Quando fazíeis a oferenda do meu pão, da gordura e do sangue, introduzistes no meu santuário para profaná-lo estrangeiros cujo coração não é menos incircunciso que a carne; violastes, dessa forma, a minha aliança com todas as vossas abominações.

[[v33-44-8]]

^<<v33-44-8,8>>^ Em vez de vos ocupardes vós mesmos com o serviço do meu santuário, encarregastes esses estrangeiros de fazê-lo em vosso lugar.^&#42;1^

[[v33-44-9]]

^<<v33-44-9,9>>^ Eis o que diz o Senhor Javé: nenhum estrangeiro, cujo coração é incircunciso tanto quanto a carne, penetrará em meu santuário; não, nenhum dos estrangeiros que residem entre os israelitas.^&#42;1^

[[v33-44-10]]

^<<v33-44-10,10>>^ Os levitas, que me deixaram desde o tempo em que Israel se desviava, abandonando-me para seguir os ídolos, esses levitas levarão a pena de sua falta.^&#42;1^

[[v33-44-11]]

^<<v33-44-11,11>>^ Servirão em meu santuário na qualidade de porteiros e farão o serviço da casa; degolarão para o povo as vítimas destinadas aos holocaustos ou aos sacrifícios, e ficarão à disposição do povo para todo o serviço.

[[v33-44-12]]

^<<v33-44-12,12>>^ Porque se puseram a seu serviço diante dos seus infames ídolos, e arrastaram os israelitas ao pecado, por causa disso – oráculo do Senhor Javé – ergo a mão contra eles, e sofrerão a pena de sua falta.

[[v33-44-13]]

^<<v33-44-13,13>>^ Não poderão mais aproximar-se de mim para exercer diante de mim as funções sacerdotais, nem para tocar em minhas coisas santas, nem para entrar no lugar santíssimo: mas carregarão a vergonha que lhes mereceram suas práticas abomináveis.

[[v33-44-14]]

^<<v33-44-14,14>>^ Eu os encarregarei da guarda do templo, de seu serviço e de todos os trabalhos que devem ser feitos aí.

[[v33-44-15]]

^<<v33-44-15,15>>^ Os sacerdotes levíticos, descendentes de Sadoc, que asseguraram a guarda do meu santuário no tempo em que os israelitas se afastavam para longe de mim, são eles que se aproximarão de mim para me servir, são eles que ficarão em minha presença para me oferecerem a gordura e o sangue – oráculo do Senhor Javé.

[[v33-44-16]]

^<<v33-44-16,16>>^ São eles que penetrarão em meu santuário, eles que se aproximarão da minha mesa para o meu serviço, que o cumprirão com fidelidade.

[[v33-44-17]]

^<<v33-44-17,17>>^ Ao passarem as portas do átrio interior, deverão estar vestidos de linho; não terão lã sobre si, quando oficiarem nos pórticos do átrio interior e no templo.

[[v33-44-18]]

^<<v33-44-18,18>>^ Trarão na cabeça turbantes de linho, e sobre os rins calções de linho; não trarão cinto que possa provocar a transpiração,

[[v33-44-19]]

^<<v33-44-19,19>>^ Quando passarem ao átrio exterior, lá onde o povo se encontra, despirão suas vestimentas litúrgicas e as deporão nas câmaras do santuário, e se revestirão de outros hábitos, a fim de que não toquem os leigos com suas vestimentas consagradas.^&#42;1^

[[v33-44-20]]

^<<v33-44-20,20>>^ Não rasparão a cabeça, não deixarão crescer livremente sua cabeleira; apararão porém os cabelos.^&#42;1^

[[v33-44-21]]

^<<v33-44-21,21>>^ Nenhum sacerdote beberá vinho quando tiver de penetrar no átrio interior.

[[v33-44-22]]

^<<v33-44-22,22>>^ Eles não desposarão viúvas nem mulheres repudiadas, mas somente virgens de descendência israelita; poderão, entretanto, casar com a viúva de um sacerdote.

[[v33-44-23]]

^<<v33-44-23,23>>^ Ensinarão meu povo a distinguir o sagrado do profano, a discernir o que é imundo do que é puro.

[[v33-44-24]]

^<<v33-44-24,24>>^ Nos debates, terão de julgar; e o farão de acordo com meu direito. Em todas as solenidades observarão as minhas leis e ordenações e santificarão os meus sábados.

[[v33-44-25]]

^<<v33-44-25,25>>^ Não tocarão em cadáver, para não se contaminarem; entretanto, essa mancha será tolerável para um pai ou uma mãe, um filho ou uma filha, um irmão ou uma irmã não casada.

[[v33-44-26]]

^<<v33-44-26,26>>^ Após sua purificação, serão contados sete dias;

[[v33-44-27]]

^<<v33-44-27,27>>^ depois, no dia em que entrar de novo para o seu serviço no santuário ou no átrio interior, oferecerá um sacrifício de expiação – oráculo do Senhor Javé.

[[v33-44-28]]

^<<v33-44-28,28>>^ Quanto ao seu patrimônio, sou eu que serei o seu patrimônio: não lhes assinalareis propriedade em Israel; sou eu que serei a sua propriedade.^&#42;1^

[[v33-44-29]]

^<<v33-44-29,29>>^ Eles se nutrirão das oferendas e das vítimas oferecidas pelos pecados e pelo delito: será para eles tudo o que tiver sido votado a interdito em Israel.

[[v33-44-30]]

^<<v33-44-30,30>>^ O melhor de todas as primícias e de todas as espécies de oferendas será dos sacerdotes. Vós lhes dareis também as primícias de vossa farinha, para que possais merecer a bênção sobre a vossa casa.

[[v33-44-31]]

^<<v33-44-31,31>>^ Os sacerdotes não comerão carne de nenhum animal morto ou despedaçado, quer seja de um pássaro quer de outro qualquer animal”.

'''

xref:033-ezequiel/033-ezequiel-043.adoc#v33-43-0[&#60; Capítulo Anterior] | <<v33-44-0,Topo>> | xref:033-ezequiel/033-ezequiel-045.adoc#v33-45-0[Próximo Capítulo &#62;]