include::./index.adoc[]

[[v33-36-0]]
=== Ezequiel, 36
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 36 trata do futuro restauração de Israel. Deus diz que trará o povo de volta à sua terra e fará com que a terra seja fértil e produtiva. Além disso, Deus promete limpar o povo de suas impurezas e dar-lhes um novo coração. Aqui estão cinco versículos relacionados aos temas deste capítulo:
* Isaías 44:26 - "Que confirmo a palavra do meu servo e cumpro a promessa dos meus mensageiros; que digo de Jerusalém: Ela será habitada; e das cidades de Judá: Elas serão reconstruídas, e eu as restaurarei;"
Este versículo fala sobre a promessa de Deus de reconstruir a cidade de Jerusalém e as cidades de Judá, que se relaciona com o tema de restauração em Ezequiel 36.
* Joel 2:25 - "E restaurarei para vós os anos que comeu o gafanhoto, a locusta, e o pulgão e a lagarta, meu grande exército que enviei contra vós."
Este versículo fala sobre a restauração que Deus promete após uma época de destruição, que se relaciona com a mensagem de Ezequiel 36.
* Jeremias 31:33 - "Mas este é o pacto que farei com a casa de Israel depois daqueles dias, diz o Senhor: Porei minha lei dentro deles e a escreverei em seus corações. Serei o Deus deles e eles serão o meu povo."
Este versículo fala sobre a promessa de Deus de dar um novo coração ao povo de Israel, que se relaciona com a mensagem de Ezequiel 36.
* Isaías 35:1 - "O deserto e a terra seca se alegrarão; o ermo exultará e florescerá como o narciso."
Este versículo fala sobre a promessa de Deus de fazer a terra fértil novamente, que se relaciona com a mensagem de Ezequiel 36.
* Ezequiel 37:21 - "E dize-lhes: Assim diz o Senhor Deus: Eis que tomarei os filhos de Israel dentre as nações para onde eles foram, e os congregarei de todas as partes, e os levarei à sua própria terra."
Este versículo fala sobre a promessa de Deus de reunir o povo de Israel de volta à sua terra, que se relaciona com a mensagem de restauração em Ezequiel 36.
****

[[v33-36-1]]

^<<v33-36-1,1>>^ “E tu, filho do homem, profere o seguinte oráculo acerca das montanhas de Israel: montes de Israel, ouvi a palavra do Senhor.

[[v33-36-2]]

^<<v33-36-2,2>>^ Eis o que diz o Senhor Javé: o inimigo gritou a respeito de vós. Ah! Ah! As colinas eternas nos hão de ser dadas em propriedade!

[[v33-36-3]]

^<<v33-36-3,3>>^ Profere, pois, o seguinte oráculo: eis o que diz o Senhor Javé: já que de todos os lados tendes sido devastados e tendes vos tornado propriedade de outras nações, pois tendes sido objeto de maledicências e de calúnias dos povos,

[[v33-36-4]]

^<<v33-36-4,4>>^ pois bem, montes de Israel, escutai o que diz o Senhor Javé às montanhas, às colinas, às torrentes, aos vales, às ruínas desoladas e às cidades abandonadas, que foram entregues à pilhagem e às zombarias das nações vizinhas;

[[v33-36-5]]

^<<v33-36-5,5>>^ pois bem, eis o que diz o Senhor Javé: juro que é no ardor do meu zelo que vou falar contra os demais povos e contra Edom todo que, com uma alegria cheia de desprezo, se estão atribuindo a posse de minha terra para saqueá-la.

[[v33-36-6]]

^<<v33-36-6,6>>^ Por isso, pronuncia o teu oráculo sobre a terra de Israel, e dize às montanhas, aos outeiros, às torrentes e aos vales: eis o que diz o Senhor Javé: é no furor do meu zelo que falo. Tendes carregado o desprezo injurioso das nações.

[[v33-36-7]]

^<<v33-36-7,7>>^ Por isso, eis o que diz o Senhor Javé: eu o juro. As nações que vos rodeiam terão também elas que sofrer ignomínia,

[[v33-36-8]]

^<<v33-36-8,8>>^ enquanto vós, montes de Israel, vós lançareis os vossos ramos e trareis vosso fruto para o meu povo de Israel, porque sua volta está próxima.

[[v33-36-9]]

^<<v33-36-9,9>>^ Porque eis que venho até vós, eu me volto para vós, a fim de que sejais novamente cultivados e semeados.

[[v33-36-10]]

^<<v33-36-10,10>>^ Multiplicarei sobre o vosso solo os homens de toda a casa de Israel: as cidades serão repovoadas e as ruínas, reconstruídas.

[[v33-36-11]]

^<<v33-36-11,11>>^ Multiplicarei sobre vosso solo homens e animais, que serão numerosos e fecundos; eu vos repovoarei como outrora e vos tornarei mais prósperos do que nunca. Vós reconhecereis assim que eu é que sou o Senhor.

[[v33-36-12]]

^<<v33-36-12,12>>^ É meu povo de Israel, esses homens que farei nascer sobre o vosso solo; serás a sua posse e herança, e não os privarás mais dos seus filhos.

[[v33-36-13]]

^<<v33-36-13,13>>^ Eis o que diz o Senhor Javé: como se diz de ti que és uma devoradora e que privas a tua nação de seus filhos,^&#42;1^

[[v33-36-14]]

^<<v33-36-14,14>>^ pois bem, por isso não devorarás mais homens e não mais privarás tua nação de seus filhos – oráculo do Senhor Javé.

[[v33-36-15]]

^<<v33-36-15,15>>^ Farei de maneira a não mais ouvires as injúrias das nações pagãs, e que não sofras mais os ultrajes dos povos, e não mais farás tropeçar tua nação – oráculo do Senhor Javé.”^&#42;1^

[[v33-36-16]]

^<<v33-36-16,16>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-36-17]]

^<<v33-36-17,17>>^ “Filho do homem, quando os israelitas habitavam sobre o seu território, eles mancharam-no por seu comportamento e seus atos: seu proceder era, a meus olhos, como a menstruação de uma mulher.

[[v33-36-18]]

^<<v33-36-18,18>>^ Por isso, desencadeei sobre eles o meu furor, devido ao sangue que tinham derramado sobre a terra e aos ídolos com que a profanaram;

[[v33-36-19]]

^<<v33-36-19,19>>^ eu os dispersei no meio das nações e os disseminei entre as nações estrangeiras: foi esse um julgamento apropriado a seu comportamento e aos seus atos.

[[v33-36-20]]

^<<v33-36-20,20>>^ Entre todos os povos aonde foram, aviltaram o meu santo nome, porque se dizia deles: eis o povo do Senhor, eles deixaram a sua terra.

[[v33-36-21]]

^<<v33-36-21,21>>^ Eu, pois, quis salvar a honra do meu santo nome, que os israelitas profanaram entre as nações, às quais tinham ido.

[[v33-36-22]]

^<<v33-36-22,22>>^ Por isso, declara à casa de Israel o que segue: eis o que diz o Senhor Javé: não é por vós que faço isto, ó israelitas, mas por honra do meu santo nome que profanastes entre pagãos, aonde tínheis ido.^&#42;1^

[[v33-36-23]]

^<<v33-36-23,23>>^ Quero manifestar a santidade do meu augusto nome que aviltastes, profanando-o entre as nações pagãs, a fim de que conheçam que eu sou o Senhor – oráculo do Senhor Javé –, quando sob seus olhares eu houver manifestado a minha santidade por meu proceder em relação a vós.

[[v33-36-24]]

^<<v33-36-24,24>>^ Eu vos retirarei do meio das nações, eu vos reunirei de todos os lugares, e vos conduzirei ao vosso solo.

[[v33-36-25]]

^<<v33-36-25,25>>^ Derramarei sobre vós águas puras, que vos purificarão de todas as vossas imundícies e de todas as vossas abominações.

[[v33-36-26]]

^<<v33-36-26,26>>^ Eu vos darei um coração novo e em vós porei um espírito novo; tirarei do vosso peito o coração de pedra e vos darei um coração de carne.

[[v33-36-27]]

^<<v33-36-27,27>>^ Dentro de vós colocarei meu espírito, fazendo com que obedeçais às minhas leis e sigais e observeis os meus preceitos.

[[v33-36-28]]

^<<v33-36-28,28>>^ Habitareis a terra de que fiz presente a vossos pais; sereis meu povo, e serei vosso Deus.

[[v33-36-29]]

^<<v33-36-29,29>>^ Eu vos purificarei de todas as vossas imundícies. Farei vir o trigo, farei com que seja produzido em abundância e vos isentarei da fome.

[[v33-36-30]]

^<<v33-36-30,30>>^ Farei abundar os frutos das árvores e a colheita dos campos, a fim de que não tenhais mais de sofrer entre as nações a vergonha da fome.

[[v33-36-31]]

^<<v33-36-31,31>>^ Então, lembrando-vos de vosso perverso proceder e de vossas ignóbeis ações, vos desgostareis de vós mesmos, por causa das vossas iniquidades e de vossas abominações.

[[v33-36-32]]

^<<v33-36-32,32>>^ Não é por vós que faço isso – oráculo do Senhor Javé –, sabei-o bem. Tende vergonha, enrubescei-vos por causa de vosso comportamento, ó israelitas!

[[v33-36-33]]

^<<v33-36-33,33>>^ Eis o que diz o Senhor Javé: no dia em que eu vos purificar de todas as vossas iniquidades, repovoarei as cidades; as ruínas serão reerguidas,

[[v33-36-34]]

^<<v33-36-34,34>>^ e a terra inculta de novo cultivada, ao invés desse espetáculo de desolação oferecido aos olhares de todos os passantes.

[[v33-36-35]]

^<<v33-36-35,35>>^ Será dito: esta terra que se achava devastada tornou-se um jardim do Éden! Essas cidades em ruínas, desertas e desoladas, estão agora restauradas e repovoadas.

[[v33-36-36]]

^<<v33-36-36,36>>^ Então, as nações que restaram em torno de vós saberão que sou eu o Senhor, que reconstruí o que estava em ruínas e replantei o que estava baldio. Sou eu, o Senhor, que o digo e o farei.

[[v33-36-37]]

^<<v33-36-37,37>>^ Eis o que diz o Senhor Javé: nisto ainda me deixarei abrandar pela casa de Israel e o farei por eles: eu os multiplicarei como um rebanho.

[[v33-36-38]]

^<<v33-36-38,38>>^ Tais como os rebanhos dos animais consagrados, tais como as manadas que se conduzem a Jerusalém, por ocasião das festas solenes, tais serão os rebanhos de homens que povoarão vossas cidades em ruínas. Então se saberá que sou eu o Senhor”.

'''

xref:033-ezequiel/033-ezequiel-035.adoc#v33-35-0[&#60; Capítulo Anterior] | <<v33-36-0,Topo>> | xref:033-ezequiel/033-ezequiel-037.adoc#v33-37-0[Próximo Capítulo &#62;]