include::./index.adoc[]

[[v33-24-0]]
=== Ezequiel, 24
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ezequiel 24 apresenta uma parábola sobre a destruição iminente de Jerusalém e a morte da esposa do profeta. Os versículos selecionados abaixo estão relacionados com a tristeza e a perda, que são temas presentes nesse capítulo:
* Salmos 34:18: "Perto está o Senhor dos que têm o coração quebrantado e salva os de espírito oprimido." Este versículo destaca que Deus está perto daqueles que estão sofrendo e quebrantados, oferecendo-lhes salvação e conforto.
* Isaías 61:2-3: "proclamar o ano aceitável do Senhor e o dia da vingança do nosso Deus; consolar todos os que choram e pôr sobre os que em Sião estão de luto uma coroa em vez de cinzas, óleo de alegria em vez de pranto, e um manto de louvor em vez de espírito deprimido." Este versículo destaca que Deus oferece consolo e alegria para aqueles que choram e sofrem, transformando sua tristeza em louvor.
* 2 Coríntios 1:3-4: "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e Deus de toda a consolação! É ele que nos conforta em toda a nossa tribulação, para podermos consolar os que estiverem em qualquer angústia, com a consolação com que nós mesmos somos contemplados por Deus." Este versículo enfatiza que Deus é o Deus de toda a consolação e que ele pode nos confortar em tempos de tribulação, para que possamos consolar os outros também.
* João 14:27: "Deixo-lhes a paz; a minha paz lhes dou. Não a dou como o mundo a dá. Não se perturbem os seus corações, nem tenham medo." Este versículo destaca que Jesus nos oferece paz, uma paz que é diferente da paz que o mundo pode oferecer, e que essa paz pode acalmar nossos corações em tempos de tristeza e medo.
* Romanos 8:18: "Considero que os nossos sofrimentos atuais não podem ser comparados com a glória que em nós será revelada." Este versículo enfatiza que, apesar do sofrimento atual, há uma glória que será revelada no futuro, dando-nos esperança e conforto.
****

[[v33-24-1]]

^<<v33-24-1,1>>^ No nono ano, no décimo dia do décimo mês, a palavra do Senhor foi-me dirigida nestes termos:

[[v33-24-2]]

^<<v33-24-2,2>>^ “Filho do homem, anota por escrito a data de hoje, pois neste dia o rei da Babilônia ataca Jerusalém.^&#42;1^

[[v33-24-3]]

^<<v33-24-3,3>>^ Expõe contra essa raça rebelde esta parábola: eis o que diz o Senhor Javé:

[[v33-24-4]]

^<<v33-24-4,4>>^ prepara a panela, põe-na no fogo, põe água dentro dela; coloca pedaços dentro, todos pedaços escolhidos, coxa e espádua, enche-a com os melhores ossos;

[[v33-24-5]]

^<<v33-24-5,5>>^ toma as mais belas cabeças do rebanho; amontoa lenha debaixo da panela e faze-a ferver aos borbotões, até que fiquem cozidos os ossos que estão dentro dela.^&#42;1^

[[v33-24-6]]

^<<v33-24-6,6>>^ Eis o que diz o Senhor Javé: ai da cidade sanguinária! Panela enferrujada, de onde a ferrugem não pode ser tirada. Despeja-a, bocado por bocado, sem tirar à sorte.^&#42;1^

[[v33-24-7]]

^<<v33-24-7,7>>^ O sangue que derramou está ainda no meio dela; ela o derramou sobre a rocha nua, e não na terra, para cobri-lo de poeira.^&#42;1^

[[v33-24-8]]

^<<v33-24-8,8>>^ Foi para excitar o meu furor e para que a vingança seja cumprida, que espalhei seu sangue sobre a rocha nua, para que ele não ficasse escondido.

[[v33-24-9]]

^<<v33-24-9,9>>^ Por isso, eis o que diz o Senhor Javé: ai da cidade sanguinária! Também eu vou fazer grande fogueira;

[[v33-24-10]]

^<<v33-24-10,10>>^ amontoa a lenha, atiça o fogo, cozinha bem a carne, prepara o tempero, que os ossos sejam torrados!

[[v33-24-11]]

^<<v33-24-11,11>>^ Em seguida, põe a panela vazia nas brasas, para que ela fique bem quente, e vermelho o seu metal; que seja fundida a sua imundície e tirada a sua ferrugem.^&#42;1^

[[v33-24-12]]

^<<v33-24-12,12>>^ Baldados, porém, são os esforços. A massa da ferrugem não sai. Lance-se ao fogo essa ferrugem!

[[v33-24-13]]

^<<v33-24-13,13>>^ Devido à imundície de teu proceder, eu quis purificar-te; todavia, como não estás purificada, não recobrarás a tua pureza até que eu tenha fartado sobre ti o meu furor.

[[v33-24-14]]

^<<v33-24-14,14>>^ Sou eu, o Senhor, que o digo: isso sucederá, eu farei isso sem hesitação, sem piedade, sem remorso. Serás julgada de acordo com o teu comportamento e os teus atos – oráculo do Senhor Javé”.

[[v33-24-15]]

^<<v33-24-15,15>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-24-16]]

^<<v33-24-16,16>>^ “Filho do homem, vou levar subitamente de ti aquela que faz a delícia de teus olhos. Tu, porém, não darás gemido algum de dor, não chorarás, não deixarás tuas lágrimas correrem.

[[v33-24-17]]

^<<v33-24-17,17>>^ Suspira em silêncio, não celebres o luto habitual dos mortos; conserva o teu turbante na cabeça, põe o calçado nos pés, não cubras a tua barba, não comas o pão das gentes”.

[[v33-24-18]]

^<<v33-24-18,18>>^ De manhã, eu me dirigi ao povo; à tarde, minha mulher morreu. No dia seguinte, fiz o que fora prescrito.

[[v33-24-19]]

^<<v33-24-19,19>>^ Disse-me o povo: “Não irás explicar-nos o que significa esse teu modo de proceder?”.

[[v33-24-20]]

^<<v33-24-20,20>>^ Respondi: “A palavra do Senhor foi-me dirigida nestes termos:

[[v33-24-21]]

^<<v33-24-21,21>>^ Faze esse discurso aos israelitas: eis o que diz o Senhor Javé: vou profanar o meu santuário, o orgulho de vosso poderio, a alegria de vossos olhos, o objeto do vosso amor; vossos filhos e vossas filhas, que deixastes, vão cair sob a espada.

[[v33-24-22]]

^<<v33-24-22,22>>^ Fareis então como acabo de fazer; não cobrireis a vossa barba, não comereis o pão das gentes;

[[v33-24-23]]

^<<v33-24-23,23>>^ conservareis os vossos turbantes na cabeça, e trareis os pés calçados; não poreis luto e não chorareis. Entretanto, definhareis por causa das vossas iniquidades e gemereis uns com os outros.

[[v33-24-24]]

^<<v33-24-24,24>>^ O que Ezequiel está fazendo será para vós um sinal. Quando isso acontecer, fareis exatamente do mesmo modo como ele fez, e sabereis que sou eu o Senhor Javé.^&#42;1^

[[v33-24-25]]

^<<v33-24-25,25>>^ Quanto a ti, filho do homem, no dia em que eu tirar o que faz a sua fortaleza, sua gloriosa arrogância, a alegria dos seus olhos e o objeto do seu amor, seus filhos e suas filhas,

[[v33-24-26]]

^<<v33-24-26,26>>^ naquele dia, digo, um fugitivo virá anunciar-te a nova,

[[v33-24-27]]

^<<v33-24-27,27>>^ naquele dia tua boca se abrirá para falar com aquele que escapou; teu mutismo cessará, falarás. Tua atitude será para eles um símbolo, e conhecerão que sou eu o Senhor Javé”.

'''

xref:033-ezequiel/033-ezequiel-023.adoc#v33-23-0[&#60; Capítulo Anterior] | <<v33-24-0,Topo>> | xref:033-ezequiel/033-ezequiel-025.adoc#v33-25-0[Próximo Capítulo &#62;]