include::./index.adoc[]

[[v33-35-0]]
=== Ezequiel, 35
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 35 de Ezequiel trata da condenação de Edom, um antigo inimigo do povo de Israel. O profeta anuncia a destruição de Edom e a punição de seus líderes, que se alegraram com a queda de Jerusalém. Abaixo seguem cinco versículos relacionados com os temas abordados em Ezequiel 35:
* Obadias 1:10-11: "Por causa da violência contra teu irmão Jacó, cobrir-te-á a vergonha, e serás exterminado para sempre. No dia em que te postaste de longe, no dia em que estranhos levaram cativo o seu exército, quando estranhos entravam pelas suas portas, e lançavam sortes sobre Jerusalém, também tu eras como um deles." Este trecho do livro de Obadias profetiza a punição de Edom por sua violência contra o povo de Israel, incluindo a alegria com a queda de Jerusalém.
* Isaías 34:5-6: "Porque será uma matança de Jeová em Edom, e um grande matar na terra deles. E os unicórnios descerão com eles, e os bois com os touros; e a sua terra embriagar-se-á de sangue, e o seu pó será engrossado de gordura." Este versículo do livro de Isaías anuncia a destruição de Edom e a abundância de sangue derramado em sua terra.
* Jeremias 49:7-8: "Quanto a Edom, assim diz Jeová dos exércitos: Acaso não há mais sabedoria em Temã? Perdeu-se o conselho dos entendidos? Corrompeu-se a sua sabedoria? Fugi, voltai-vos para trás, habitai em profundezas, ó moradores de Dedã; porque trarei sobre ele a calamidade de Esaú, no tempo em que o castigarei." Neste trecho de Jeremias, Deus ameaça punir Edom por sua arrogância e alegria com a queda de Jerusalém.
* Salmos 137:7: "Lembra-te, Jeová, dos filhos de Edom, no dia de Jerusalém, que diziam: Descobri, descobri até os seus alicerces." Este salmo registra as palavras de lamento do povo de Israel durante seu exílio na Babilônia, lembrando da crueldade de Edom em sua hora de aflição.
* Amós 1:11-12: "Assim diz Jeová: Por três transgressões de Edom, e por quatro, não revogarei o castigo, porque perseguiu a seu irmão à espada, e suprimiu toda a compaixão, e a sua ira lhe arrebatou continuamente, e conservou perpetuamente a sua fúria. Por isso enviarei um fogo sobre Temã, que consumirá os palácios de Bozra." Nesta passagem do livro de Amós, Deus condena a violência de Edom contra o povo de Israel e anuncia sua punição.
****

[[v33-35-1]]

^<<v33-35-1,1>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v33-35-2]]

^<<v33-35-2,2>>^ “Filho do homem, volta-te para o lado da montanha de Seir, e profetiza contra ela;^&#42;1^

[[v33-35-3]]

^<<v33-35-3,3>>^ Dize-lhe: eis o que diz o Senhor Javé: é contra ti que venho, monte de Seir; eu vou levantar a mão contra ti. Farei de ti um deserto e uma solidão;

[[v33-35-4]]

^<<v33-35-4,4>>^ reduzirei as tuas cidades a ruínas, a fim de que saibas que sou eu o Senhor.

[[v33-35-5]]

^<<v33-35-5,5>>^ Já que tens nutrido ódio eterno pelos israelitas, e os entregaste a fio de espada no dia de sua aflição, e ao termo da sua iniquidade,

[[v33-35-6]]

^<<v33-35-6,6>>^ pois bem: por minha vida – oráculo do Senhor Javé –, eu te entregarei ao sangue, e o sangue há de perseguir-te; porquanto não te horrorizes em derramar sangue, o sangue há de perseguir-te.

[[v33-35-7]]

^<<v33-35-7,7>>^ Farei da montanha de Seir um deserto e uma solidão, e suprimirei da terra todos os transeuntes.

[[v33-35-8]]

^<<v33-35-8,8>>^ Cobrirei tuas montanhas de cadáveres: sobre teus outeiros, teus vales e tuas torrentes tombarão aqueles a quem corta o gládio.

[[v33-35-9]]

^<<v33-35-9,9>>^ Eu te reduzirei a solidões eternas; tuas cidades serão despovoadas. Assim saberás tu que eu é que sou o Senhor.

[[v33-35-10]]

^<<v33-35-10,10>>^ Já que disseste: as duas nações, os dois países serão meus, e tomarei posse deles, ainda que o Senhor aí resida,^&#42;1^

[[v33-35-11]]

^<<v33-35-11,11>>^ pois bem: por minha vida – oráculo do Senhor Javé –, eu te tratarei com a mesma furiosa cólera com que os trataste, e me farei conhecer no modo por que hei de exercer o meu julgamento contra ti.

[[v33-35-12]]

^<<v33-35-12,12>>^ Saberás que eu, o Senhor, ouvi todas as blasfêmias que proferiste contra as montanhas de Israel quando dizias: ei-las devastadas! Elas nos são dadas como pasto.

[[v33-35-13]]

^<<v33-35-13,13>>^ Haveis-me afrontado com uma multidão de palavras insolentes contra mim. Eu as ouvi.

[[v33-35-14]]

^<<v33-35-14,14>>^ Eis o que diz o Senhor Javé:

[[v33-35-15]]

^<<v33-35-15,15>>^ enquanto toda a terra estiver em alegria, farei de ti uma solidão. Porque te tens alegrado com a devastação da herança da casa de Israel, eu te tratarei do mesmo modo: serás devastada, montanha de Seir, assim como todo o território de Edom. Assim reconhecerás que sou eu o Senhor”.

'''

xref:033-ezequiel/033-ezequiel-034.adoc#v33-34-0[&#60; Capítulo Anterior] | <<v33-35-0,Topo>> | xref:033-ezequiel/033-ezequiel-036.adoc#v33-36-0[Próximo Capítulo &#62;]