include::./index.adoc[]

[[v16-11-0]]
=== Neemias, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 11 de Neemias trata da divisão do povo de Israel em Jerusalém após a reconstrução dos muros. Os líderes foram selecionados por meio de sorteio e uma parte do povo se estabeleceu na cidade, enquanto outros moraram em cidades vizinhas para repovoar a região. A seguir estão cinco versículos relacionados aos temas abordados em Neemias 11:
* Josué 14:1: "Estes são os que receberam a herança na terra de Canaã, que Eleazar, o sacerdote, e Josué, filho de Num, e os cabeças dos pais das tribos dos filhos de Israel, lhes repartiram por sorteio." Este versículo descreve como a terra de Canaã foi dividida entre as tribos de Israel, um processo semelhante ao sorteio que ocorreu em Neemias 11.
* 1 Crônicas 9:2: "Os primeiros habitantes que se estabeleceram nas suas possessões e nas suas cidades foram os israelitas, os sacerdotes, os levitas e os servos do templo." Este versículo fala sobre a importância dos sacerdotes, levitas e servos do templo em Israel, um grupo que também é mencionado em Neemias 11 como parte daqueles que moravam em Jerusalém.
* Neemias 7:4: "E a cidade era grande e espaçosa; mas havia pouca gente dentro dela, e as casas ainda não estavam reconstruídas." Este versículo descreve a situação da cidade de Jerusalém antes da repovoação descrita em Neemias 11.
* Josué 21:2: "Eles falaram a eles em Siló, na terra de Canaã, dizendo: O Senhor mandou por meio de Moisés que nos fossem dadas cidades para habitarmos, e os seus arrabaldes para o nosso gado." Este versículo se relaciona com Neemias 11, pois ambos tratam da necessidade de as tribos de Israel terem cidades para habitar.
* Ezequiel 48:30-31: "E estas são as saídas da cidade: no lado norte, quatro mil e quinhentos côvados por medida. E as portas da cidade serão segundo os nomes das tribos de Israel: três portas para o norte: a porta de Rúben, uma; a porta de Judá, outra; a porta de Levi, outra." Este versículo descreve a cidade de Jerusalém, incluindo sua divisão em tribos. Isso se relaciona com a seleção dos líderes por sorteio em Neemias 11, que representavam as tribos de Israel que habitavam a cidade.
****

[[v16-11-1]]

^<<v16-11-1,1>>^ Estabeleceram-se os chefes do povo em Jerusalém. O resto dos israelitas tirou à sorte, a fim de que um entre dez viesse habitar em Jerusalém, na cidade santa, enquanto que os nove outros ficariam nas demais cidades.

[[v16-11-2]]

^<<v16-11-2,2>>^ O povo abençoou todos aqueles que se decidiram espontaneamente a vir habitar em Jerusalém.^&#42;1^

[[v16-11-3]]

^<<v16-11-3,3>>^ Eis os chefes de família da colônia que se estabeleceu em Jerusalém. Nas cidades de Judá, israelitas, sacerdotes, levitas, natineus e os filhos dos escravos de Salomão estabeleceram-se cada um em sua propriedade, na sua cidade.

[[v16-11-4]]

^<<v16-11-4,4>>^ Estabeleceram-se em Jerusalém filhos de Judá e filhos de Benjamim. Entre os filhos de Judá: Ataías, filho de Ozias, filho de Zacarias, filho de Amarias, filho de Safatias, filho de Malaleel, dos filhos de Farés;^&#42;1^

[[v16-11-5]]

^<<v16-11-5,5>>^ e Maasias, filho de Baruc, filho de Col-Hosa, filho de Hazias, filho de Adaías, filho de Joiarib, filho de Zacarias, filho de Sela.

[[v16-11-6]]

^<<v16-11-6,6>>^ Total dos filhos de Farés que habitaram em Jerusalém: quatrocentos e sessenta e oito homens valentes.

[[v16-11-7]]

^<<v16-11-7,7>>^ Eis os filhos de Benjamim: Salu, filho de Mesolam, filho de Joed, filho de Fadaías, filho de Calaías, filho de Maasias, filho de Eteel, filho de Isaías,

[[v16-11-8]]

^<<v16-11-8,8>>^ e depois dele Gabai, Salai. Ao todo, novecentos e vinte e oito.

[[v16-11-9]]

^<<v16-11-9,9>>^ Joel, filho de Zecri, era o chefe; e Judá, filho de Senua, o segundo comandante da cidade.

[[v16-11-10]]

^<<v16-11-10,10>>^ Entre os sacerdotes: Jedaías, filho de Joiarib, Joaquim,

[[v16-11-11]]

^<<v16-11-11,11>>^ Saraías, filho de Helcias, filho de Mesolam, filho de Sadoc, filho de Maraiot, filho de Aquitob, príncipe da casa de Deus,

[[v16-11-12]]

^<<v16-11-12,12>>^ e seus irmãos que trabalhavam no serviço do templo: oitocentos e vinte e dois; Adaías, filho de Jeroam, filho de Felelias, filho de Amsi, filho de Zacarias, filho de Fasur, filho de Melquias,

[[v16-11-13]]

^<<v16-11-13,13>>^ e seus irmãos, chefes de família: duzentos e quarenta e dois; e Amasai, filho de Azareel, filho de Aazi, filho de Mesolamot, filho de Emer,

[[v16-11-14]]

^<<v16-11-14,14>>^ e seus irmãos, fortes e valentes, em número de cento e vinte e oito. Zabdiel, filho de Agadol, era o seu chefe.

[[v16-11-15]]

^<<v16-11-15,15>>^ Entre os levitas: Semeías, filho de Hasub, filho de Ezricam, filho de Hasabias, filho de Buni;

[[v16-11-16]]

^<<v16-11-16,16>>^ Sabatai e Jozabad, superintendentes dos trabalhos exteriores da casa de Deus, entre os chefes dos levitas;

[[v16-11-17]]

^<<v16-11-17,17>>^ Matanias, filho de Micas, filho de Zabdi, filho de Asaf, o chefe que entoava o cântico de louvores no tempo da oração; Becbecias, o segundo entre os seus irmãos e Abdias, filho de Samua, filho de Galal, filho de Iditun.

[[v16-11-18]]

^<<v16-11-18,18>>^ Total dos levitas residentes na cidade santa: duzentos e oitenta e quatro.

[[v16-11-19]]

^<<v16-11-19,19>>^ E os porteiros: Acub, Telmon e seus irmãos, guardiães das portas: cento e setenta e dois.

[[v16-11-20]]

^<<v16-11-20,20>>^ O restante dos israelitas, sacerdotes e levitas, estabeleceu-se em todas as outras cidades de Judá, cada um em sua propriedade.

[[v16-11-21]]

^<<v16-11-21,21>>^ Os natineus estabeleceram-se no quarteirão de Ofel, tendo à frente Sia e Gasfa.

[[v16-11-22]]

^<<v16-11-22,22>>^ O chefe dos levitas de Jerusalém era Ozi, filho de Bani, filho de Hasabias, filho de Matanias, filho de Micas, um dos cantores filho de Asaf, encarregado do serviço da casa de Deus.

[[v16-11-23]]

^<<v16-11-23,23>>^ Havia uma ordem do rei concernente a eles e um salário determinado era entregue cotidianamente aos seus cantores.

[[v16-11-24]]

^<<v16-11-24,24>>^ Fetaías, filho de Mesezebel, da linhagem de Zara, filho de Judá, era comissário do rei para todos os negócios civis.^&#42;1^

[[v16-11-25]]

^<<v16-11-25,25>>^ Quanto às pequenas cidades e seus arredores, descendentes de Judá, estabeleceram-se em Cariat-Arbe e em suas aldeias, em Dibon e em suas aldeias, em Cabseel e em suas aldeias;

[[v16-11-26]]

^<<v16-11-26,26>>^ em Jesua, em Molada, em Bet-Falet,

[[v16-11-27]]

^<<v16-11-27,27>>^ em Haser-Sual, em Bersabeia e em suas aldeias;

[[v16-11-28]]

^<<v16-11-28,28>>^ em Siceleg, em Mecona e em suas aldeias;

[[v16-11-29]]

^<<v16-11-29,29>>^ em En-Remon, em Saraá, em Jarmut,

[[v16-11-30]]

^<<v16-11-30,30>>^ em Zanoé, em Odolam e em suas aldeias, em Laquis e no seu território; em Azeca e nas suas aldeias. Estabeleceram-se desde Bersabeia até o vale de Enom.

[[v16-11-31]]

^<<v16-11-31,31>>^ Descendentes de Benjamim estabeleceram-se desde Gaba, até Macmas, Aía, Betel e em suas aldeias,

[[v16-11-32]]

^<<v16-11-32,32>>^ em Anatot, em Nob, em Ananias,

[[v16-11-33]]

^<<v16-11-33,33>>^ em Hasor, em Ramá, Getaim,

[[v16-11-34]]

^<<v16-11-34,34>>^ em Hadid, em Seboim, em Nebalat,

[[v16-11-35]]

^<<v16-11-35,35>>^ em Lod e em Ono, no vale dos Operários.

[[v16-11-36]]

^<<v16-11-36,36>>^ Entre os levitas, houve classes pertencentes a Judá que se uniram à tribo de Benjamim.

'''

xref:016-neemias/016-neemias-010.adoc#v16-10-0[&#60; Capítulo Anterior] | <<v16-11-0,Topo>> | xref:016-neemias/016-neemias-012.adoc#v16-12-0[Próximo Capítulo &#62;]