include::./index.adoc[]

[[v16-1-0]]
=== Neemias, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Neemias 1 narra a história de Neemias, que recebe notícias da situação precária de seus irmãos judeus que ainda residiam em Jerusalém, após o retorno de alguns cativos. Ele se abala com a notícia e busca a Deus em oração para buscar uma solução. A seguir estão cinco versículos que tratam dos temas abordados neste capítulo.
* Esdras 9:9: "Pois somos escravos; contudo, no meio da nossa escravidão, o nosso Deus não nos abandonou; Ele nos concedeu favor perante os reis da Pérsia, dando-nos vida para erguermos a Casa do nosso Deus, restaurarmos as suas ruínas e lhe concedermos um muro em Judá e em Jerusalém." Este versículo destaca como Deus não abandonou o povo mesmo durante a escravidão e como Ele os capacitou para reconstruir a Casa de Deus e as ruínas de Jerusalém.
* Isaías 1:9: "Se o Senhor dos Exércitos não nos tivesse deixado alguns sobreviventes, já teríamos sido como Sodoma; já teríamos sido como Gomorra." Este versículo mostra como a sobrevivência de um remanescente é importante para a continuidade da linhagem do povo de Deus e como Ele protege aqueles que são fiéis a Ele.
* Salmo 106:6: "Pecamos, como nossos antepassados; cometemos injustiças, praticamos maldades." Este versículo destaca a confissão de pecado do povo, reconhecendo a falha em seguir os mandamentos de Deus.
* Isaías 58:9: "Então, clamarás, e o Senhor te responderá; gritarás por socorro, e ele dirá: Eis-me aqui. Se tirares do meio de ti o jugo, o dedo que ameaça e a maledicência." Este versículo fala sobre como Deus ouve o clamor de Seu povo e os responde, mas também enfatiza a importância de se livrar de práticas injustas.
* Jeremias 29:12-13: "Então, me invocareis, passareis a orar a mim, e eu vos ouvirei. Buscar-me-eis e me achareis quando me buscardes de todo o vosso coração." Este versículo mostra como Deus ouve a oração de Seu povo e os responde, mas também destaca a importância de buscar a Ele com todo o coração.
****

[[v16-1-1]]

^<<v16-1-1,1>>^ Palavras de Neemias, filho de Hacalias. No mês de Casleu do vigésimo ano, encontrando-me eu em Susa, no palácio,^&#42;1^

[[v16-1-2]]

^<<v16-1-2,2>>^ eis que chegaram de Judá, Hanani, um de meus irmãos, com alguns companheiros. Perguntei-lhes pelos judeus libertados que tinham escapado do cativeiro e a respeito de Jerusalém.

[[v16-1-3]]

^<<v16-1-3,3>>^ “Aqueles que escaparam do cativeiro – disseram-me eles – estão lá na Província, numa grande miséria e humilhação. Os muros de Jerusalém estão em ruínas e suas portas foram incendiadas.”

[[v16-1-4]]

^<<v16-1-4,4>>^ Ouvindo tais palavras, sentei-me para chorar e fiquei vários dias desconsolado; jejuei e orei diante do Deus do céu,^&#42;1^

[[v16-1-5]]

^<<v16-1-5,5>>^ dizendo: “Ah, Senhor, Deus do céu, Deus grande e temível, vós que permaneceis fiel à vossa aliança e exerceis a misericórdia para com aqueles que vos amam e observam os vossos mandamentos,

[[v16-1-6]]

^<<v16-1-6,6>>^ que vossos ouvidos estejam atentos e vossos olhos se abram para ouvirdes a prece que eu, vosso servo, estou fazendo na vossa presença, de noite e de dia, pelos filhos de Israel, vossos servos, confessando os pecados que nós, os israelitas, cometemos contra vós. Porque eu mesmo e a casa de meu pai temos pecado.

[[v16-1-7]]

^<<v16-1-7,7>>^ Nós vos ofendemos gravemente e não observamos as leis, os mandamentos e os preceitos que destes a Moisés, vosso servo.

[[v16-1-8]]

^<<v16-1-8,8>>^ Lembrai-vos da palavra que destes ao vosso servo Moisés, dizendo: ‘Se transgredirdes meus preceitos, eu vos dispersarei entre as nações;

[[v16-1-9]]

^<<v16-1-9,9>>^ mas, se voltardes a mim, se observardes os meus mandamentos e os praticardes, mesmo que estejais deportados às extremidades do céu, eu vos reunirei ali e vos farei retornar ao lugar que escolhi para estabelecer nele a morada de meu nome’.

[[v16-1-10]]

^<<v16-1-10,10>>^ Eles são vossos servos, esse mesmo povo que libertastes com o poder e a força de vossa mão.

[[v16-1-11]]

^<<v16-1-11,11>>^ Ah, Senhor, prestai ouvidos à oração deste vosso servo e à oração dos vossos servos que veneram o vosso nome. Dignai-vos hoje dar bom êxito ao vosso servo e fazei-o ganhar o favor do rei”. Eu era então copeiro do rei.

'''

xref:015-esdras/015-esdras-010.adoc#v15-10-0[&#60; Capítulo Anterior] | <<v16-1-0,Topo>> | xref:016-neemias/016-neemias-002.adoc#v16-2-0[Próximo Capítulo &#62;]