include::./index.adoc[]

[[v16-7-0]]
=== Neemias, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Neemias 7 relata a organização do povo após a reconstrução dos muros de Jerusalém. Neemias é encarregado de selecionar líderes e estabelecer um registro genealógico do povo que retornou do exílio babilônico. Ele nomeia Hanani e Hananias para supervisionar a cidade e os portões, e também designa guardas para proteger a cidade. Abaixo estão cinco versículos relacionados com os temas abordados em Neemias 7:
* Neemias 7:5: "E meu Deus colocou em meu coração reunir os nobres, os oficiais e o povo para que pudessem ser registrados por genealogia." Neemias inicia o processo de registro genealógico do povo que retornou do exílio.
* Esdras 2:59-60: "Estes foram os que subiram de Tel-Melá, Tel-Harsá, Querube, Adom e Imer, mas não puderam provar que suas famílias e seus descendentes eram de Israel: Descendentes de Delaías, dos filhos de Tobias e dos descendentes de Neco." Este versículo faz parte da lista de pessoas que retornaram do exílio babilônico, mas não puderam provar sua genealogia.
* Esdras 2:62: "Eles procuraram seu registro genealógico, mas não o encontraram, então foram excluídos do sacerdócio como impuros." Este versículo fala sobre aqueles que não puderam provar sua genealogia, e portanto, foram excluídos do sacerdócio.
* Neemias 7:2: "Eu coloquei meu irmão Hanani, e Hananias, líder do palácio, sobre Jerusalém, porque ele era um homem fiel e temia a Deus mais do que muitos outros." Neemias escolhe líderes confiáveis ​​para supervisionar a cidade e os portões.
* Neemias 7:3: "E eu lhes disse: não abram as portas de Jerusalém até o sol estar quente, e enquanto os porteiros ainda estiverem lá, trave as portas e trave-as enquanto ainda estiverem em guarda. Nomeei alguns dos habitantes de Jerusalém como guardas e também atribuí a cada um uma seção do muro para reparar." Neemias nomeia guardas para proteger a cidade e designa seções do muro para serem reparadas por cada um deles.
****

[[v16-7-1]]

^<<v16-7-1,1>>^ Logo que foi restaurada a muralha e colocados os batentes das portas foram nomeados os porteiros, cantores e levitas.

[[v16-7-2]]

^<<v16-7-2,2>>^ Confiei a defesa da cidade a Hanani, meu irmão, e a Hananias, comandante da cidadela, porque era um homem fiel e temente a Deus.

[[v16-7-3]]

^<<v16-7-3,3>>^ Ordenei-lhes que não abrissem as portas de Jerusalém enquanto não viesse o calor do sol; à tarde, enquanto os guardas estivessem ainda em seus postos, colocaríamos as trancas e fecharíamos as portas; e durante a noite estabeleceríamos guardas recrutados entre os habitantes de Jerusalém; cada um devia montar guarda em seu posto diante de sua própria casa.

[[v16-7-4]]

^<<v16-7-4,4>>^ A cidade era grande e espaçosa, mas não tinha muitos habitantes e as moradias não estavam ainda todas reconstruídas.

[[v16-7-5]]

^<<v16-7-5,5>>^ Meu Deus inspirou-me então que reunisse as pessoas importantes, os magistrados e o povo para fazer o recenseamento. Descobri um registro genealógico dos que tinham voltado em primeiro lugar, no qual estava escrito o que segue:

[[v16-7-6]]

^<<v16-7-6,6>>^ Entre os exilados que Nabucodonosor, rei da Babilônia, tinha levado cativos, estes são os habitantes da província que se puseram a caminho para retornar a Jerusalém e à Judeia, cada um à sua localidade.

[[v16-7-7]]

^<<v16-7-7,7>>^ Voltaram sob o comando de Zorobabel, Josué, Neemias, Azarias, Raamias, Naamani, Mardoqueu, Belsã, Mesfarat, Beguai, Naume, Baana. Este é o recenseamento dos israelitas:

[[v16-7-8]]

^<<v16-7-8,8>>^ filhos de Faros: dois mil cento e setenta e dois;

[[v16-7-9]]

^<<v16-7-9,9>>^ filhos de Safatias: trezentos e setenta e dois;

[[v16-7-10]]

^<<v16-7-10,10>>^ filhos de Area: seiscentos e cinquenta e dois;

[[v16-7-11]]

^<<v16-7-11,11>>^ filhos de Faat-Moab, descendentes de Josué e de Joab: dois mil oitocentos e dezoito;

[[v16-7-12]]

^<<v16-7-12,12>>^ filhos de Elam: mil duzentos e cinquenta e quatro;

[[v16-7-13]]

^<<v16-7-13,13>>^ filhos de Zetua: oitocentos e quarenta e cinco;

[[v16-7-14]]

^<<v16-7-14,14>>^ filhos de Zacai: setecentos e sessenta;

[[v16-7-15]]

^<<v16-7-15,15>>^ filhos de Benui: seiscentos e quarenta e oito;

[[v16-7-16]]

^<<v16-7-16,16>>^ filhos de Bebai: seiscentos e vinte e oito;

[[v16-7-17]]

^<<v16-7-17,17>>^ filhos de Azgad: dois mil trezentos e vinte e dois;

[[v16-7-18]]

^<<v16-7-18,18>>^ filhos de Adonicam: seiscentos e sessenta e sete;

[[v16-7-19]]

^<<v16-7-19,19>>^ filhos de Beguai: dois mil e sessenta e sete;

[[v16-7-20]]

^<<v16-7-20,20>>^ filhos de Adin: seiscentos e cinquenta e cinco;

[[v16-7-21]]

^<<v16-7-21,21>>^ filhos de Ater, isto é, do ramo de Ezequias: noventa e oito;

[[v16-7-22]]

^<<v16-7-22,22>>^ filhos de Hasum: trezentos e vinte e oito;

[[v16-7-23]]

^<<v16-7-23,23>>^ filhos de Besai: trezentos e vinte e quatro;

[[v16-7-24]]

^<<v16-7-24,24>>^ filhos de Haref: cento e doze;

[[v16-7-25]]

^<<v16-7-25,25>>^ filhos de Gabaon: noventa e cinco;

[[v16-7-26]]

^<<v16-7-26,26>>^ habitantes de Belém e de Netofa: cento e oitenta e oito;

[[v16-7-27]]

^<<v16-7-27,27>>^ habitantes de Anatot: cento e vinte e oito;

[[v16-7-28]]

^<<v16-7-28,28>>^ habitantes de Bet-Azmot: quarenta e dois;

[[v16-7-29]]

^<<v16-7-29,29>>^ habitantes de Cariatarim, de Cafira e de Berot: setecentos e quarenta e tres;

[[v16-7-30]]

^<<v16-7-30,30>>^ habitantes de Ramá e de Gaba: seiscentos e vinte e um;

[[v16-7-31]]

^<<v16-7-31,31>>^ habitantes de Macmas: cento e vinte e dois;

[[v16-7-32]]

^<<v16-7-32,32>>^ habitantes de Betel e Hai: cento e vinte e três;

[[v16-7-33]]

^<<v16-7-33,33>>^ habitantes de Nebo: cinquenta e dois;

[[v16-7-34]]

^<<v16-7-34,34>>^ filhos de um outro Elam: mil duzentos e cinquenta e quatro;

[[v16-7-35]]

^<<v16-7-35,35>>^ filhos de Harim: trezentos e vinte;

[[v16-7-36]]

^<<v16-7-36,36>>^ habitantes de Jericó: trezentos e quarenta e cinco;

[[v16-7-37]]

^<<v16-7-37,37>>^ filhos de Lod, de Hadid e de Ono: setecentos e vinte e um;

[[v16-7-38]]

^<<v16-7-38,38>>^ filhos de Senaá: três mil novecentos e trinta.

[[v16-7-39]]

^<<v16-7-39,39>>^ Sacerdotes: filhos de Jedaías, da casa de Josué: novecentos e setenta e três;

[[v16-7-40]]

^<<v16-7-40,40>>^ filhos de Emer: mil e cinquenta e dois;

[[v16-7-41]]

^<<v16-7-41,41>>^ filhos de Fasur: mil duzentos e quarenta e sete;

[[v16-7-42]]

^<<v16-7-42,42>>^ filhos de Harim: mil e dezesete.

[[v16-7-43]]

^<<v16-7-43,43>>^ Levitas: filhos de Josué e de Cadmiel, descendentes de Odovias: setenta e quatro.

[[v16-7-44]]

^<<v16-7-44,44>>^ Cantores: filhos de Asaf: cento e quarenta e oito.

[[v16-7-45]]

^<<v16-7-45,45>>^ Porteiros: filhos de Selum, filhos de Ater, filhos de Telmon, filhos de Acub, filhos de Hatita, filhos de Sobai: 138.

[[v16-7-46]]

^<<v16-7-46,46>>^ Natineus: filhos de Sia, filhos de Hasufa, filhos de Tabaot,

[[v16-7-47]]

^<<v16-7-47,47>>^ filhos de Ceros, filhos de Siá, filhos de Fadon,

[[v16-7-48]]

^<<v16-7-48,48>>^ filhos de Lebana, filhos de Hagaba, filhos de Selmai,

[[v16-7-49]]

^<<v16-7-49,49>>^ filhos de Hanã, filhos de Guidel, filhos de Gaar,

[[v16-7-50]]

^<<v16-7-50,50>>^ filhos de Raaías, filhos de Rasin, filhos de Necoda,

[[v16-7-51]]

^<<v16-7-51,51>>^ filhos de Gazam, filhos de Oza, filhos de Fasca,

[[v16-7-52]]

^<<v16-7-52,52>>^ filhos de Besai, filhos de Munim, filhos de Nefusim,

[[v16-7-53]]

^<<v16-7-53,53>>^ filhos de Bacbuc, filhos de Hacufa, filhos de Harur,

[[v16-7-54]]

^<<v16-7-54,54>>^ filhos de Baslut, filhos de Meida, filhos de Harsa,

[[v16-7-55]]

^<<v16-7-55,55>>^ filhos de Bercos, filhos de Sísara, filhos de Tema,

[[v16-7-56]]

^<<v16-7-56,56>>^ filhos de Nasias, filhos de Hatifa.

[[v16-7-57]]

^<<v16-7-57,57>>^ Filhos dos servos de Salomão: filhos de Sotai, filhos de Soferet, filhos de Feruda,

[[v16-7-58]]

^<<v16-7-58,58>>^ filhos de Jaala, filhos de Darcon, filhos de Guidel,

[[v16-7-59]]

^<<v16-7-59,59>>^ filhos de Safatias, filhos de Hatil, filhos de Foqueret-Assebaim, filhos de Amon.

[[v16-7-60]]

^<<v16-7-60,60>>^ Total dos natineus e dos filhos dos servos de Salomão: 392.

[[v16-7-61]]

^<<v16-7-61,61>>^ Eis aqueles que, partindo de Tel-Mela, de Tel-Harsa, de Querub, Adon e Emer, não conseguiram provar sua origem israelita, nem tornar conhecidas sua família e descendência:

[[v16-7-62]]

^<<v16-7-62,62>>^ filhos de Dalaías, filhos de Tobias, filhos de Necoda, 642.

[[v16-7-63]]

^<<v16-7-63,63>>^ Dentre os sacerdotes: filhos de Hobias, filhos de Acos, filhos de Berzelai, o qual, tendo desposado uma das filhas de Berzelai, o galaadita, foi chamado pelo seu nome.

[[v16-7-64]]

^<<v16-7-64,64>>^ Procuraram estabelecer sua genealogia, mas não o conseguiram descobrir. Assim, foram excluídos do sacerdócio.

[[v16-7-65]]

^<<v16-7-65,65>>^ O governador proibiu-lhes comer das coisas sagradas, até que se pudesse encontrar um sacerdote qualificado para consultar Deus pelo Urim e Tumim.

[[v16-7-66]]

^<<v16-7-66,66>>^ Toda a assembleia perfazia um total de quarenta e dois mil trezentos e sessenta pessoas,

[[v16-7-67]]

^<<v16-7-67,67>>^ sem contar seus servos e servas, que eram em número de sete mil trezentos e trinta e sete. Havia com eles 245 cantores e cantoras.

[[v16-7-68]]

^<<v16-7-68,68>>^ Tinham setecentos e trinta e seis cavalos, duzentos e quarenta e cinco burros,

[[v16-7-69]]

^<<v16-7-69,69>>^ quatrocentos e trinta e cinco camelos e seis mil setecentos e vinte jumentos.

[[v16-7-70]]

^<<v16-7-70,70>>^ Alguns chefes de família fizeram donativos para os trabalhos. O governador doou ao tesouro mil dáricos de ouro, cinquenta taças e quinhentas e trinta túnicas sacerdotais.

[[v16-7-71]]

^<<v16-7-71,71>>^ Muitos chefes de família doaram ao tesouro vinte mil dáricos de ouro e duas mil e duzentas minas de prata.

[[v16-7-72]]

^<<v16-7-72,72>>^ Enfim, o resto do povo doou vinte mil dáricos de ouro, duas mil minas de prata e sessenta e sete túnicas sacerdotais.

[[v16-7-73]]

^<<v16-7-73,73>>^ Foi assim que os sacerdotes e levitas, os cantores, os porteiros, as pessoas do povo, os natineus e todos os israelitas estabeleceram-se em suas respectivas cidades. Assim, quando chegou o sétimo mês, os israelitas estavam instalados em suas cidades e casas.

'''

xref:016-neemias/016-neemias-006.adoc#v16-6-0[&#60; Capítulo Anterior] | <<v16-7-0,Topo>> | xref:016-neemias/016-neemias-008.adoc#v16-8-0[Próximo Capítulo &#62;]