include::./index.adoc[]

[[v16-9-0]]
=== Neemias, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Neemias 9 é um capítulo em que os levitas fazem uma oração de confissão pelos pecados de Israel e reafirmam a aliança com Deus. Os versículos relacionados aos temas abordados nesse capítulo são:
* Deuteronômio 32:3-4: "Porque apelarei ao nome do Senhor; dai glória ao nosso Deus. Ele é a Rocha, cuja obra é perfeita, porque todos os seus caminhos justos são. Deus é fiel, que não tem iniquidade; justo e reto é ele." Nesse versículo, Moisés exalta a fidelidade e justiça de Deus, temas que são reforçados na oração dos levitas em Neemias 9.
* Salmos 106:6: "Pecamos como nossos pais; cometemos a iniquidade, praticamos a impiedade." Esse salmo retrata a história de Israel e seus pecados contra Deus, tema que é relembrado na oração de confissão dos levitas em Neemias 9.
* Isaías 53:6: "Todos nós, como ovelhas, nos desviamos; cada um se voltou para o seu próprio caminho; e o Senhor fez cair sobre ele a iniquidade de todos nós." Esse versículo destaca a natureza pecaminosa da humanidade e a necessidade de confissão e arrependimento, que são elementos presentes na oração dos levitas em Neemias 9.
* Jeremias 31:33: "Mas esta é a aliança que farei com a casa de Israel depois daqueles dias, diz o Senhor: porei a minha lei no seu interior, e a escreverei no seu coração; e eu serei o seu Deus e eles serão o meu povo." Esse versículo fala da aliança que Deus estabeleceu com Israel e que é reafirmada na oração dos levitas em Neemias 9.
* Daniel 9:4: "E orei ao Senhor, meu Deus, e confessei e disse: Ah! Senhor! Deus grande e tremendo, que guardas a aliança e a misericórdia para com aqueles que te amam e guardam os teus mandamentos." Esse versículo retrata a confissão de Daniel pelos pecados de Israel e sua apelação à misericórdia de Deus, temas que também são abordados na oração dos levitas em Neemias 9.
****

[[v16-9-1]]

^<<v16-9-1,1>>^ No vigésimo quarto dia do mesmo mês, vestidos de sacos e com a cabeça coberta de pó, os israelitas reuniram-se para um jejum.

[[v16-9-2]]

^<<v16-9-2,2>>^ Evitavam o contato com os estrangeiros e se apresentaram para confessar seus pecados e as iniquidades de seus pais.

[[v16-9-3]]

^<<v16-9-3,3>>^ De pé em seus lugares, escutaram a leitura da Lei do Senhor, seu Deus, durante um quarto do dia; durante o outro quarto do dia confessaram seus pecados e prostraram-se diante do Senhor, seu Deus.

[[v16-9-4]]

^<<v16-9-4,4>>^ Josué, Benui, Cadmiel, Sebanias, Buni, Sarebias, Bani e Canani, que haviam tomado lugar no estrado dos levitas, invocaram em alta voz o Senhor, seu Deus.

[[v16-9-5]]

^<<v16-9-5,5>>^ E os levitas Josué, Cadmiel, Bani, Hasabneias, Serebias, Hodias, Sebanias e Fetaías disseram: “Levantai-vos, bendizei ao Senhor, vosso Deus, de eternidade em eternidade! Seja bendito o vosso nome glorioso, com toda a sorte de louvores e bênçãos.

[[v16-9-6]]

^<<v16-9-6,6>>^ Sois vós, Senhor,^&#42;1^ vós somente, que fizestes o céu do céu e todo o seu exército, a terra e tudo o que ela contém, o mar e tudo o que nele se encerra; sois vós quem dais a vida a todos os seres e o exército do céu vos adora.

[[v16-9-7]]

^<<v16-9-7,7>>^ Vós, Senhor Deus, fostes quem escolheu Abrão, quem o fez deixar a terra de Ur, na Caldeia, e quem lhe deu o nome de Abraão.

[[v16-9-8]]

^<<v16-9-8,8>>^ Encontrastes nele um coração fiel e com ele firmastes uma aliança, prometendo dar à sua posteridade a terra dos cananeus, dos hiteus, dos amorreus, dos ferezeus, dos jebuseus e dos gergeseus e cumpristes a vossa palavra, porque sois justo.

[[v16-9-9]]

^<<v16-9-9,9>>^ Vistes a aflição de nossos pais no Egito e ouvistes os seus clamores junto do mar Vermelho.

[[v16-9-10]]

^<<v16-9-10,10>>^ Operastes milagres e prodígios contra o faraó, contra todos os seus servos e todo o povo de sua terra, porque sabíeis que haviam tratado com arrogância os nossos pais; e adquiristes um renome que perdura até os nossos dias.

[[v16-9-11]]

^<<v16-9-11,11>>^ Fendestes o mar diante deles, que passaram a pé enxuto; mas precipitastes nos abismos todos os que os perseguiam, como uma pedra é atirada às profundezas das águas.

[[v16-9-12]]

^<<v16-9-12,12>>^ Vós os guiastes durante o dia por uma coluna de nuvem e de noite por uma coluna de fogo, para iluminar o caminho que deviam seguir.

[[v16-9-13]]

^<<v16-9-13,13>>^ Descestes ao monte Sinai, falastes-lhes do alto do céu e destes-lhes justas ordenações, leis verdadeiras, preceitos e mandamentos excelentes.

[[v16-9-14]]

^<<v16-9-14,14>>^ Fizestes-lhes conhecer o vosso santo sábado e prescrevestes-lhes, pela boca de Moisés, vosso servo, os mandamentos, preceitos e uma Lei.

[[v16-9-15]]

^<<v16-9-15,15>>^ Do alto do céu, destes-lhes pão para saciar a fome; e do rochedo fizestes jorrar água para matar-lhes a sede. E vós os mandastes tomar posse da terra que havíeis jurado dar-lhes.

[[v16-9-16]]

^<<v16-9-16,16>>^ Mas os nossos pais, em seu orgulho, endureceram a cerviz e não observaram os vossos mandamentos.

[[v16-9-17]]

^<<v16-9-17,17>>^ Recusaram-se a ouvir e não mais se incomodaram com as maravilhas que operastes em seu favor. Endureceram a cerviz e, em sua rebelião, elegeram um chefe para retornar à sua escravidão. Mas vós sois um Deus sempre pronto ao perdão, clemente e compassivo, vagaroso em encolerizar-se e rico em bondade e assim não os abandonastes.

[[v16-9-18]]

^<<v16-9-18,18>>^ Mesmo quando fabricaram para si um bezerro de metal fundido e vos ultrajaram grandemente dizendo ser aquilo o Deus que os tirara do Egito,

[[v16-9-19]]

^<<v16-9-19,19>>^ usastes de muita misericórdia e não os abandonastes no deserto; e a coluna de nuvem que os guiava durante o dia em sua viagem, bem como a coluna de fogo que lhes iluminava o caminho que deviam seguir durante a noite, não lhes foi arrebatada.

[[v16-9-20]]

^<<v16-9-20,20>>^ Destes-lhes do vosso bom espírito para torná-los prudentes; não lhes recusastes o vosso maná para seu alimento e destes-lhes água para estancar a sede.

[[v16-9-21]]

^<<v16-9-21,21>>^ Durante quarenta anos provestes as necessidades deles no deserto, sem que nada lhes faltasse. Suas vestes não se estragaram e nem seus pés incharam.^&#42;1^

[[v16-9-22]]

^<<v16-9-22,22>>^ Vós os livrastes dos reinos e dos povos, cujas terras repartistes entre eles. Tomaram posse da terra de Seon, da terra do rei de Hesebon e da terra de Og, rei de Basã.

[[v16-9-23]]

^<<v16-9-23,23>>^ Multiplicastes seus filhos como as estrelas do céu e os fizestes entrar na posse da terra. Havíeis prometido aos seus pais que entrariam e possuiriam essa terra,

[[v16-9-24]]

^<<v16-9-24,24>>^ mas foram seus filhos que a ocuparam. Diante deles humilhastes o orgulho dos habitantes da terra, os cananeus; entregastes em suas mãos tanto os reis como as populações, que ficaram à sua mercê.

[[v16-9-25]]

^<<v16-9-25,25>>^ Eles se apropriaram de cidades fortificadas e de terras férteis. Tomaram posse de casas repletas de bens de toda a sorte, de cisternas já feitas, de vinhas, olivais e muitas árvores frutíferas. Puderam comer até se saciar e engordaram, vivendo nas delícias que lhes outorgava a vossa grande bondade.

[[v16-9-26]]

^<<v16-9-26,26>>^ Entretanto, foram rebeldes e se revoltaram contra vós. Desprezaram vossa Lei; mataram vossos profetas que os conjuravam a retornar a vós. Como cometessem grandes ultrajes para convosco,

[[v16-9-27]]

^<<v16-9-27,27>>^ vós os abandonastes às mãos de seus inimigos, que os oprimiram. Mas quando, no tempo de sua miséria, clamaram a vós, vós os ouvistes do alto do céu, e, em vossa grande misericórdia, enviastes-lhes salvadores que os livraram das mãos de seus inimigos.

[[v16-9-28]]

^<<v16-9-28,28>>^ Mas, assim que voltou a segurança, recomeçaram a fazer o mal diante de vós e os abandonastes às mãos de seus inimigos, que os tiranizaram. Mas clamaram de novo a vós e vós, do alto do céu, os atendestes; assim é que a vossa grande misericórdia operou inúmeras vezes a sua libertação.

[[v16-9-29]]

^<<v16-9-29,29>>^ Vós os conjurastes a voltar à vossa Lei, mas eles, em sua arrogância, desobedeciam aos teus mandamentos, transgrediam vossas ordens, que dão a vida ao homem que as observa. Nada mais mostraram que ombros rebeldes, cerviz altiva e ouvidos surdos.

[[v16-9-30]]

^<<v16-9-30,30>>^ Vossa paciência para com eles durou muitos anos; vós lhes fazíeis admoestações pela inspiração de vosso espírito, que animava os vossos profetas. Então, finalmente, como não vos escutassem, vós os entregastes às mãos dos povos de outras terras.

[[v16-9-31]]

^<<v16-9-31,31>>^ Mas, mesmo assim, vossa grande misericórdia vos impediu de aniquilá-los e não os abandonastes porque sois um Deus clemente e compassivo.

[[v16-9-32]]

^<<v16-9-32,32>>^ E agora, Senhor, o Deus grande, poderoso e temível, vós que mantendes fielmente vossa aliança misericordiosa, não sejais indiferente a todos os sofrimentos que nos atingem, a nós, nossos reis, nossos chefes, nossos sacerdotes e a todo o vosso povo, desde o tempo dos reis da Assíria até o presente.

[[v16-9-33]]

^<<v16-9-33,33>>^ Em tudo aquilo que nos aconteceu, nada mais houve que justiça de vossa parte, porque procedestes com lealdade, enquanto que nós retribuíamos com o mal.

[[v16-9-34]]

^<<v16-9-34,34>>^ Nossos reis, nossos chefes, nossos sacerdotes e nossos pais negligenciaram a prática da vossa Lei, não mais obedeceram aos vossos mandamentos, nem às advertências que lhes fizestes.

[[v16-9-35]]

^<<v16-9-35,35>>^ Malgrado seu reino, apesar dos bens que lhes havíeis dado em abundância e a despeito desta terra vasta e fértil que lhes entregastes, eles não vos serviram, não renunciaram às suas más obras.

[[v16-9-36]]

^<<v16-9-36,36>>^ E eis que hoje somos escravos! Escravos na própria terra que destes aos nossos pais, para usufruir de seus frutos e dos seus produtos.

[[v16-9-37]]

^<<v16-9-37,37>>^ Essa terra multiplica suas messes para reis estrangeiros, que no momento nos tiranizam por causa de nossos pecados e dispõem a seu arbítrio de nossas pessoas e de nossos animais. Sim, estamos numa grande aflição”.

[[v16-9-38]]

^<<v16-9-38,38>>^ “Por todos esses motivos, contratamos uma aliança sagrada, que redigimos por escrito, na qual os nossos chefes, levitas e sacerdotes vão colocar o seu selo.”

'''

xref:016-neemias/016-neemias-008.adoc#v16-8-0[&#60; Capítulo Anterior] | <<v16-9-0,Topo>> | xref:016-neemias/016-neemias-010.adoc#v16-10-0[Próximo Capítulo &#62;]