include::./index.adoc[]

[[v4-25-0]]
=== Números, 25
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 25 de Números descreve como os israelitas começaram a se prostituir com mulheres moabitas e a adorar seus deuses, trazendo a ira de Deus sobre eles. Os versículos a seguir são escolhidos com base na proximidade dos temas do capítulo e estão relacionados com a importância da pureza e da fidelidade na adoração a Deus:
* Êxodo 20:3: "Não terás outros deuses diante de mim." Este é o primeiro mandamento dos Dez Mandamentos, que proíbe a adoração de qualquer outro deus além de Jeová. Isso é relevante para o capítulo de Números 25 porque os israelitas começaram a adorar os deuses dos moabitas, o que trouxe a ira de Deus sobre eles.
* 1 Coríntios 6:18: "Fugi da prostituição. Qualquer outro pecado que uma pessoa cometer é fora do corpo; mas aquele que se prostitui peca contra o seu próprio corpo." Este versículo enfatiza a importância da pureza sexual e da fidelidade a Deus. Os israelitas se prostituíram com as mulheres moabitas, o que trouxe a ira de Deus sobre eles.
* Hebreus 13:4: "Digno de honra entre todos seja o matrimônio e o leito sem mácula; porém aos que se dão à prostituição, e aos adúlteros, Deus os julgará." Este versículo enfatiza a importância da pureza sexual e da fidelidade conjugal. Os israelitas se prostituíram com as mulheres moabitas, violando esses princípios, o que trouxe a ira de Deus sobre eles.
* 2 Coríntios 6:14: "Não vos ponhais em jugo desigual com os incrédulos; pois que sociedade pode haver entre a justiça e a iniquidade? Ou que comunhão, da luz com as trevas?" Este versículo enfatiza a importância da pureza doutrinária e da fidelidade a Deus. Os israelitas se envolveram com as práticas religiosas dos moabitas, o que os levou a adorar outros deuses, violando esses princípios, o que trouxe a ira de Deus sobre eles.
* Efésios 5:11: "E não participais nas obras infrutíferas das trevas, mas antes as reprovai." Este versículo enfatiza a importância de separar-se do pecado e das práticas malignas. Os israelitas se envolveram com as práticas religiosas dos moabitas, o que os levou a adorar outros deuses, violando esses princípios, o que trouxe a ira de Deus sobre eles.
****

[[v4-25-1]]

^<<v4-25-1,1>>^ Habitando os israelitas em Setim, entregaram-se à libertinagem com as filhas de Moab.

[[v4-25-2]]

^<<v4-25-2,2>>^ Estas convidaram o povo aos sacrifícios de seus deuses, e o povo comeu e prostrou-se diante dos seus deuses.^&#42;1^

[[v4-25-3]]

^<<v4-25-3,3>>^ Israel juntou-se a Baal-Fegor, provocando assim contra ele a cólera do Senhor:

[[v4-25-4]]

^<<v4-25-4,4>>^ “Reúne – disse o Senhor a Moisés – todos os chefes do povo, e pendura os culpados em forcas diante de mim, de cara para o sol, a fim de que o fogo de minha cólera se desvie de Israel”.

[[v4-25-5]]

^<<v4-25-5,5>>^ Moisés disse aos juízes de Israel: “Cada um de vós mate os seus que se tenham juntado a Baal-Fegor”.

[[v4-25-6]]

^<<v4-25-6,6>>^ Entretanto, um dos filhos de Israel trouxe para junto de seus irmãos uma madianita, sob os olhos de Moisés e de toda a assembleia que chorava à entrada da tenda de reunião.

[[v4-25-7]]

^<<v4-25-7,7>>^ Vendo isso, Fineias, filho de Eleazar, filho do sacerdote Aarão, levantou-se no meio da assembleia, tomou uma lança,

[[v4-25-8]]

^<<v4-25-8,8>>^ seguiu o israelita até a sua tenda, e ali transpassou-o juntamente com a mulher, ferindo-os no ventre. E deteve-se então o flagelo que se alastrava entre os israelitas.

[[v4-25-9]]

^<<v4-25-9,9>>^ Morreram vinte e quatro mil homens com essa praga.^&#42;1^

[[v4-25-10]]

^<<v4-25-10,10>>^ O Senhor disse a Moisés:

[[v4-25-11]]

^<<v4-25-11,11>>^ “Fineias, filho de Eleazar, filho do sacerdote Aarão, desviou minha cólera de sobre os israelitas, dando provas entre eles do mesmo zelo que eu. Por isso, não os extingui em minha cólera.

[[v4-25-12]]

^<<v4-25-12,12>>^ Dize-lhe, pois, que lhe dou a minha aliança de paz.

[[v4-25-13]]

^<<v4-25-13,13>>^ Isso será para ele e seus descendentes o pacto de um sacerdócio eterno, porque se mostrou cheio de zelo pelo seu Deus e fez expiação pelos israelitas”.

[[v4-25-14]]

^<<v4-25-14,14>>^ Chamava-se Zambri, filho de Salu, o israelita que foi morto com a madianita, o qual era chefe de uma família patriarcal da tribo de Simeão;

[[v4-25-15]]

^<<v4-25-15,15>>^ o nome da madianita morta era Cozbi, filha de Sur, chefe de tribo, de família patriarcal em Madiã.

[[v4-25-16]]

^<<v4-25-16,16>>^ O Senhor disse a Moisés:

[[v4-25-17]]

^<<v4-25-17,17>>^ “Atacai os madianitas e matai-os,

[[v4-25-18]]

^<<v4-25-18,18>>^ porque eles vos atacaram primeiro, enganando-vos artificiosamente por meio do ídolo de Fogor e de Cozbi, sua irmã, filha de um chefe de Madiã, que foi massacrada no dia do flagelo que sobreveio por causa do sacrilégio de Fogor”.

'''

xref:004-numeros/004-numeros-024.adoc#v4-24-0[&#60; Capítulo Anterior] | <<v4-25-0,Topo>> | xref:004-numeros/004-numeros-026.adoc#v4-26-0[Próximo Capítulo &#62;]