include::./index.adoc[]

[[v4-13-0]]
=== Números, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 13 de Números narra o envio dos doze espias à terra de Canaã, a fim de explorá-la antes da invasão. Os versículos selecionados abaixo estão relacionados com temas como fé, coragem, desobediência, confiança em Deus e suas promessas.
* Deuteronômio 1:21: "Veja, o Senhor, o seu Deus, lhe entregou a terra. Suba e tome posse dela, como o Senhor, o Deus dos seus antepassados, lhe prometeu. Não tenha medo; não desanime". Neste versículo, Moisés encoraja o povo de Israel a confiar nas promessas de Deus e a ter coragem para tomar posse da terra que lhes foi prometida.
* Deuteronômio 1:26: "Mas vocês se recusaram a subir; vocês se rebelaram contra a ordem do Senhor, o seu Deus". Este versículo mostra a desobediência do povo de Israel, que se recusou a confiar em Deus e a tomar posse da terra de Canaã.
* Josué 1:9: "Não fui eu que lhe ordenei? Seja forte e corajoso! Não se apavore, nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar". Este versículo foi dito por Deus a Josué, que sucedeu Moisés como líder de Israel. Deus encoraja Josué a ser corajoso e a confiar em suas promessas, assim como Moisés havia encorajado o povo de Israel.
* Josué 2:24: "Reconhecemos que o Senhor entregou toda esta terra nas nossas mãos e que o seu terror caiu sobre nós, e por isso todos os habitantes da terra estão desanimados diante de vocês". Este versículo mostra que, apesar dos obstáculos, a fé e a coragem do povo de Israel foram recompensadas por Deus, que entregou a terra de Canaã em suas mãos.
* Josué 14:12: "Agora, dê-me esta região montanhosa que o Senhor me prometeu naquele dia. Você ouviu naquele dia que os anaquins lá estão e que as cidades são grandes e fortificadas, mas, com o Senhor ao meu lado, eu as expulsarei, como ele prometeu". Neste versículo, Calebe, um dos espias que confiaram em Deus e encorajaram o povo de Israel a invadir Canaã, lembra a Josué da promessa de Deus e reafirma sua fé na ajuda divina para conquistar a terra.
****

[[v4-13-1]]

^<<v4-13-1,1>>^ O Senhor disse a Moisés:

[[v4-13-2]]

^<<v4-13-2,2>>^ “Envia homens para explorar a terra de Canaã, que eu hei de dar aos filhos de Israel. Enviarás um homem de cada tribo patriarcal, tomados todos entre os príncipes”.

[[v4-13-3]]

^<<v4-13-3,3>>^ Enviou-os Moisés do deserto de Farã segundo as ordens do Senhor; todos esses homens eram príncipes em Israel.

[[v4-13-4]]

^<<v4-13-4,4>>^ Eis os seus nomes: da tribo de Rúben, Samua, filho de Zacur;

[[v4-13-5]]

^<<v4-13-5,5>>^ da tribo de Simeão, Safat, filho de Huri;

[[v4-13-6]]

^<<v4-13-6,6>>^ da tribo de Judá, Caleb, filho de Jefoné;

[[v4-13-7]]

^<<v4-13-7,7>>^ da tribo de Issacar, Igal, filho de José;

[[v4-13-8]]

^<<v4-13-8,8>>^ da tribo de Efraim, Oseias, filho de Nun;

[[v4-13-9]]

^<<v4-13-9,9>>^ da tribo de Benjamim, Falti, filho de Rafu;

[[v4-13-10]]

^<<v4-13-10,10>>^ da tribo de Zabulon, Gediel, filho de Sodi;

[[v4-13-11]]

^<<v4-13-11,11>>^ da tribo de José, na tribo de Manassés, Gadi, filho de Susi;

[[v4-13-12]]

^<<v4-13-12,12>>^ da tribo de Dã, Amiel, filho de Gemali;

[[v4-13-13]]

^<<v4-13-13,13>>^ da tribo de Aser, Setur, filho de Miguel;

[[v4-13-14]]

^<<v4-13-14,14>>^ da tribo de Neftali, Naabi, filho de Vapsi;

[[v4-13-15]]

^<<v4-13-15,15>>^ da tribo de Gad, Guel, filho de Maqui.

[[v4-13-16]]

^<<v4-13-16,16>>^ Esses são os nomes dos homens que Moisés enviou como exploradores a Canaã. Moisés deu a Oseias, filho de Nun, o nome de Josué.

[[v4-13-17]]

^<<v4-13-17,17>>^ Enviando-os a explorar a terra de Canaã, Moisés disse-lhes: “Ide pelo Negueb e subi a montanha.^&#42;1^

[[v4-13-18]]

^<<v4-13-18,18>>^ Examinai que terra é essa, e o povo que a habita, se é forte ou fraco, pequeno ou numeroso.

[[v4-13-19]]

^<<v4-13-19,19>>^ Vede como é a terra onde habita, se é boa ou má, e como são as suas cidades, se muradas ou sem muros;

[[v4-13-20]]

^<<v4-13-20,20>>^ examinai igualmente se o terreno é fértil ou estéril, e se há árvores ou não. Coragem! E trazei-nos dos frutos da terra”. Era então a época das primeiras uvas.

[[v4-13-21]]

^<<v4-13-21,21>>^ Partiram, pois, e exploraram a terra desde o deserto de Sin até Roob, no caminho de Emat.

[[v4-13-22]]

^<<v4-13-22,22>>^ Subiram ao Negueb e foram a Hebron, onde se encontravam Aimã, Sesai e Tolmai, filhos de Enac. Hebron fora construída sete anos antes de Tânis, no Egito.^&#42;1^

[[v4-13-23]]

^<<v4-13-23,23>>^ Chegaram ao vale de Escol, onde cortaram um ramo de vide com um cacho de uvas, que dois homens levaram numa vara; tomaram também consigo romãs e figos.

[[v4-13-24]]

^<<v4-13-24,24>>^ Chamou-se a esse lugar vale de Escol, por causa do cacho que nele haviam cortado os israelitas.^&#42;1^

[[v4-13-25]]

^<<v4-13-25,25>>^ Tendo voltado os exploradores, passados quarenta dias,

[[v4-13-26]]

^<<v4-13-26,26>>^ foram ter com Moisés e Aarão e toda a assembleia dos israelitas em Cades, no deserto de Farã. Diante deles e de toda a multidão relataram a sua expedição e mostraram os frutos da terra.

[[v4-13-27]]

^<<v4-13-27,27>>^ Eis como narraram a Moisés a sua exploração: “Fomos à terra aonde nos enviaste. É verdadeiramente uma terra onde corre leite e mel, como se pode ver por esses frutos.

[[v4-13-28]]

^<<v4-13-28,28>>^ Mas os habitantes dessa terra são robustos, suas cidades grandes e bem muradas; vimos ali até mesmo filhos de Enac.

[[v4-13-29]]

^<<v4-13-29,29>>^ Os amalecitas habitam na terra do Negueb; os hiteus, os jebuseus e os amorreus habitam nas montanhas, e os cananeus habitam junto ao mar e ao longo do Jordão”.

[[v4-13-30]]

^<<v4-13-30,30>>^ Caleb fez calar o povo que começava a murmurar contra Moisés, e disse: “Vamos e apoderemo-nos da terra, porque podemos conquistá-la”.

[[v4-13-31]]

^<<v4-13-31,31>>^ Mas os outros, que tinham ido com ele, diziam: “Não somos capazes de atacar esse povo; é mais forte do que nós”.

[[v4-13-32]]

^<<v4-13-32,32>>^ E diante dos filhos de Israel depreciaram a terra que tinham explorado: “A terra – disseram eles – que exploramos devora os seus habitantes: os homens que vimos ali são de uma grande estatura;

[[v4-13-33]]

^<<v4-13-33,33>>^ vimos até mesmo gigantes, filhos de Enac, da raça dos gigantes; parecíamos gafanhotos comparados com eles”.

'''

xref:004-numeros/004-numeros-012.adoc#v4-12-0[&#60; Capítulo Anterior] | <<v4-13-0,Topo>> | xref:004-numeros/004-numeros-014.adoc#v4-14-0[Próximo Capítulo &#62;]