include::./index.adoc[]

[[v4-7-0]]
=== Números, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 7 de Números trata da dedicação do altar do tabernáculo pelos líderes das tribos de Israel. Cada líder apresenta ofertas e sacrifícios para consagrar o altar e expressar sua devoção a Deus. Os versículos relacionados aos temas deste capítulo são:
* Êxodo 29:37 - "Sete dias farás expiação pelo altar, e o santificarás, e o altar será santíssimo; tudo o que tocar o altar será santo." Este versículo fala sobre a importância de santificar o altar, o que é o tema principal do capítulo 7 de Números.
* Levítico 9:22-24 - "Arão levantou as mãos para o povo e o abençoou. Depois de oferecer a oferta pelo pecado, o holocausto e a oferta de comunhão, desceu. Moisés e Arão entraram na Tenda do Encontro. Quando saíram, abençoaram o povo, e a glória do Senhor apareceu a todo o povo." Este versículo fala sobre a cerimônia de dedicação do tabernáculo em geral, que é semelhante à dedicação do altar descrita em Números 7.
* Salmos 51:17 - "Sacrifícios agradáveis a Deus são o espírito quebrantado; coração compungido e contrito, não o desprezarás, ó Deus." Este versículo fala sobre a importância da atitude do coração em relação aos sacrifícios, que é um tema importante em Números 7.
* Hebreus 13:15 - "Por meio de Jesus, portanto, ofereçamos a Deus um sacrifício de louvor, que é fruto de lábios que confessam o seu nome." Este versículo fala sobre como, no Novo Testamento, o sacrifício de louvor substituiu os sacrifícios de animais como uma forma de adoração a Deus.
* Romanos 12:1 - "Rogo-vos, pois, irmãos, pela compaixão de Deus, que apresenteis os vossos corpos como um sacrifício vivo, santo e agradável a Deus, que é o vosso culto racional." Este versículo fala sobre como a vida cristã deve ser uma oferta viva e contínua de adoração a Deus, que é um tema relacionado com a dedicação do altar em Números 7.
****

[[v4-7-1]]

^<<v4-7-1,1>>^ Tendo Moisés acabado de levantar o tabernáculo, de ungi-lo e consagrá-lo com todos os seus utensílios, bem como o altar e todos os seus utensílios, que também ungiu e consagrou,

[[v4-7-2]]

^<<v4-7-2,2>>^ os príncipes de Israel, chefes de suas casas patriarcais, os príncipes das tribos que haviam presidido ao recenseamento, apresentaram sua oferta.

[[v4-7-3]]

^<<v4-7-3,3>>^ Levaram-na diante do Senhor: seis carros cobertos e doze bois, ou seja, um carro para dois príncipes e um boi para cada um; e os ofereceram diante do tabernáculo.

[[v4-7-4]]

^<<v4-7-4,4>>^ Então o Senhor disse a Moisés:

[[v4-7-5]]

^<<v4-7-5,5>>^ “Recebe-os deles para que sejam empregados no serviço da tenda de reunião, e entrega-os aos levitas segundo as funções de cada um”.

[[v4-7-6]]

^<<v4-7-6,6>>^ Moisés tomou os carros e os bois e os entregou aos levitas.

[[v4-7-7]]

^<<v4-7-7,7>>^ Deu aos filhos de Gérson, segundo as suas funções, dois carros e quatro bois.

[[v4-7-8]]

^<<v4-7-8,8>>^ Aos filhos de Merari, segundo as suas funções, sob a vigilância de Itamar, filho do sacerdote Aarão, deu quatro carros e oito bois.

[[v4-7-9]]

^<<v4-7-9,9>>^ Aos filhos de Caat, porém, não deu carros nem bois, porque tinham o cuidado de objetos sagrados que levavam aos ombros.

[[v4-7-10]]

^<<v4-7-10,10>>^ Os príncipes apresentaram sua oferta para a dedicação do altar no dia em que ele foi ungido, e trouxeram-na diante do altar.

[[v4-7-11]]

^<<v4-7-11,11>>^ O Senhor disse a Moisés: “Os príncipes ofereçam, cada um em seu dia, a sua oferta para a dedicação do altar”.

[[v4-7-12]]

^<<v4-7-12,12>>^ No primeiro dia foi Naasson, filho de Abinadab, da tribo de Judá, quem apresentou a oferenda.

[[v4-7-13]]

^<<v4-7-13,13>>^ Ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com óleo, para a oblação;

[[v4-7-14]]

^<<v4-7-14,14>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-15]]

^<<v4-7-15,15>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-16]]

^<<v4-7-16,16>>^ um bode para o sacrifício pelo pecado,

[[v4-7-17]]

^<<v4-7-17,17>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano, para o sacrifício pacífico. Essa foi a oferta de Naasson, filho de Abinadab.

[[v4-7-18]]

^<<v4-7-18,18>>^ No segundo dia, apresentou sua oferta o príncipe de Issacar, Natanael, filho de Suar.

[[v4-7-19]]

^<<v4-7-19,19>>^ Ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;

[[v4-7-20]]

^<<v4-7-20,20>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-21]]

^<<v4-7-21,21>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-22]]

^<<v4-7-22,22>>^ um bode para o sacrifício pelo pecado,

[[v4-7-23]]

^<<v4-7-23,23>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano para o sacrifício pacífico. Essa foi a oferta de Natanael, filho de Suar.

[[v4-7-24]]

^<<v4-7-24,24>>^ No terceiro dia, o príncipe dos filhos de Zabulon, Eliab, filho de Helon,

[[v4-7-25]]

^<<v4-7-25,25>>^ ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com óleo, para a oblação;

[[v4-7-26]]

^<<v4-7-26,26>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-27]]

^<<v4-7-27,27>>^ um novilho, um carneiro e um cordeiro de um ano, para o holocausto;

[[v4-7-28]]

^<<v4-7-28,28>>^ um bode para o sacrifício pelo pecado,

[[v4-7-29]]

^<<v4-7-29,29>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano, para o sacrifício pacífico. Essa foi a oferta de Eliab, filho de Helon.

[[v4-7-30]]

^<<v4-7-30,30>>^ No quarto dia, o príncipe dos filhos de Rúben, Elisur, filho de Sedeur,

[[v4-7-31]]

^<<v4-7-31,31>>^ ofereceu uma bandeja de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com óleo, para a oblação;

[[v4-7-32]]

^<<v4-7-32,32>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-33]]

^<<v4-7-33,33>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-34]]

^<<v4-7-34,34>>^ um bode para o sacrifício pelo pecado,

[[v4-7-35]]

^<<v4-7-35,35>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano, para o sacrifício pacífico. Essa foi a oferta de Elisur, filho de Sedeur.

[[v4-7-36]]

^<<v4-7-36,36>>^ No quinto dia, o príncipe dos filhos de Simeão, Salamiel, filho de Surisadai,

[[v4-7-37]]

^<<v4-7-37,37>>^ ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;

[[v4-7-38]]

^<<v4-7-38,38>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-39]]

^<<v4-7-39,39>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-40]]

^<<v4-7-40,40>>^ um bode para o sacrifício pelo pecado,

[[v4-7-41]]

^<<v4-7-41,41>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano, para o sacrifício pacífico. Essa foi a oferta de Salamiel, filho de Surisadai.

[[v4-7-42]]

^<<v4-7-42,42>>^ No sexto dia, o príncipe dos filhos de Gad, Eliasaf, filho de Reuel,

[[v4-7-43]]

^<<v4-7-43,43>>^ ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com óleo, para a oblação;

[[v4-7-44]]

^<<v4-7-44,44>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-45]]

^<<v4-7-45,45>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-46]]

^<<v4-7-46,46>>^ um bode para o sacrifício pelo pecado,

[[v4-7-47]]

^<<v4-7-47,47>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano, para o sacrifício pacífico. Essa foi a oferta de Eliasaf, filho de Reuel.

[[v4-7-48]]

^<<v4-7-48,48>>^ No sétimo dia, o príncipe dos filhos de Efraim, Elisama, filho de Amiud,

[[v4-7-49]]

^<<v4-7-49,49>>^ ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;

[[v4-7-50]]

^<<v4-7-50,50>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-51]]

^<<v4-7-51,51>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-52]]

^<<v4-7-52,52>>^ um bode para o sacrifício pelo pecado,

[[v4-7-53]]

^<<v4-7-53,53>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano para o sacrifício pacífico. Essa foi a oferta de Elisama, filho de Amiud.

[[v4-7-54]]

^<<v4-7-54,54>>^ No oitavo dia, o príncipe dos filhos de Manassés, Gamaliel, filho de Fadassur,

[[v4-7-55]]

^<<v4-7-55,55>>^ ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;

[[v4-7-56]]

^<<v4-7-56,56>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-57]]

^<<v4-7-57,57>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-58]]

^<<v4-7-58,58>>^ um bode para o sacrifício pelo pecado,

[[v4-7-59]]

^<<v4-7-59,59>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano para o sacrifício pacífico. Essa foi a oferta de Gamaliel, filho de Fadassur.

[[v4-7-60]]

^<<v4-7-60,60>>^ No nono dia, o príncipe dos filhos de Benjamim, Abidã, filho de Gedeão,

[[v4-7-61]]

^<<v4-7-61,61>>^ ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com óleo, para a oblação;

[[v4-7-62]]

^<<v4-7-62,62>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-63]]

^<<v4-7-63,63>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-64]]

^<<v4-7-64,64>>^ um bode para o sacrifício pelo pecado,

[[v4-7-65]]

^<<v4-7-65,65>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano, para o sacrifício pacífico. Essa foi a oferta de Abidã, filho de Gedeão.

[[v4-7-66]]

^<<v4-7-66,66>>^ No décimo dia, o príncipe dos filhos de Dã, Aiezer, filho de Amisadai,

[[v4-7-67]]

^<<v4-7-67,67>>^ ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com óleo, para a oblação;

[[v4-7-68]]

^<<v4-7-68,68>>^ uma taça de ouro pesando dez ciclos, cheia de perfume;

[[v4-7-69]]

^<<v4-7-69,69>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-70]]

^<<v4-7-70,70>>^ um bode para o sacrifício pelo pecado,

[[v4-7-71]]

^<<v4-7-71,71>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano, para o sacrifício pacífico. Essa foi a oferta de Aiezer, filho de Amisadai.

[[v4-7-72]]

^<<v4-7-72,72>>^ No décimo primeiro dia, o príncipe dos filhos de Aser, Fegiel, filho de Ocrã,

[[v4-7-73]]

^<<v4-7-73,73>>^ ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com óleo, para a oblação;

[[v4-7-74]]

^<<v4-7-74,74>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-75]]

^<<v4-7-75,75>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-76]]

^<<v4-7-76,76>>^ um bode para o sacrifício pelo pecado,

[[v4-7-77]]

^<<v4-7-77,77>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano, para o sacrifício pacífico. Essa foi a oferta de Fegiel, filho de Ocrã.

[[v4-7-78]]

^<<v4-7-78,78>>^ No décimo segundo dia, o príncipe dos filhos de Neftali, Aíra, filho de Enã,

[[v4-7-79]]

^<<v4-7-79,79>>^ ofereceu um prato de prata pesando cento e trinta siclos, uma bacia de prata pesando setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com óleo, para a oblação;

[[v4-7-80]]

^<<v4-7-80,80>>^ uma taça de ouro pesando dez siclos, cheia de perfume;

[[v4-7-81]]

^<<v4-7-81,81>>^ um novilho, um carneiro e um cordeiro de um ano para o holocausto;

[[v4-7-82]]

^<<v4-7-82,82>>^ um bode para o sacrifício pelo pecado,

[[v4-7-83]]

^<<v4-7-83,83>>^ e ainda dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano, para o sacrifício pacífico. Essa foi a oferta de Aíra, filho de Enã.

[[v4-7-84]]

^<<v4-7-84,84>>^ Estes foram os presentes que os príncipes de Israel ofereceram para a dedicação do altar no dia em que foi ungido: doze pratos de prata, doze bacias de prata e doze taças de ouro.

[[v4-7-85]]

^<<v4-7-85,85>>^ Cada prato de prata pesava cento e trinta siclos, e cada bacia, setenta siclos; o peso total da prata desses objetos era de dois mil e quatrocentos siclos, segundo o siclo do santuário.

[[v4-7-86]]

^<<v4-7-86,86>>^ As doze taças de ouro para o perfume pesavam cada uma dez siclos, segundo o siclo do santuário; o peso total de ouro das taças era de cento e vinte siclos.

[[v4-7-87]]

^<<v4-7-87,87>>^ O total dos animais para o holocausto era de doze novilhos, doze carneiros, doze cordeiros de um ano com suas oblações e doze bodes em sacrifício pelo pecado.

[[v4-7-88]]

^<<v4-7-88,88>>^ O total de animais para o sacrifício pacífico era de vinte e quatro bois, sessenta carneiros, sessenta bodes e sessenta cordeiros de um ano. Esses foram os presentes oferecidos para a dedicação do altar depois de ungido.

[[v4-7-89]]

^<<v4-7-89,89>>^ Quando Moisés entrava na tenda de reunião para falar com o Senhor, ouvia a voz que lhe falava de cima do propiciatório colocado sobre a arca do testemunho, entre os dois querubins. E falava com o Senhor.

'''

xref:004-numeros/004-numeros-006.adoc#v4-6-0[&#60; Capítulo Anterior] | <<v4-7-0,Topo>> | xref:004-numeros/004-numeros-008.adoc#v4-8-0[Próximo Capítulo &#62;]