include::./index.adoc[]

[[v4-10-0]]
=== Números, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Números 10 descreve a preparação dos filhos de Israel para deixarem o Monte Sinai em direção à Terra Prometida. O capítulo inclui instruções para a fabricação de duas trombetas de prata para serem usadas como sinais para a congregação. Os levitas foram designados para cuidar do tabernáculo e do transporte das tendas. Então, quando as trombetas soavam, os filhos de Israel partiam para a próxima etapa da jornada. Abaixo estão cinco versículos relacionados aos temas abordados em Números 10.
* Números 2:17: "Então a tenda da congregação partirá com o acampamento dos levitas no meio dos acampamentos; assim como eles acampam, assim partirão, cada um na sua posição, segundo as suas bandeiras." Este versículo fala sobre a organização dos filhos de Israel durante a jornada e como eles se moviam em formação. Os levitas eram responsáveis por cuidar do tabernáculo e se posicionavam no meio dos acampamentos.
* Números 9:15-16: "No dia em que foi levantado o tabernáculo, a nuvem cobriu o tabernáculo, a saber, a tenda do testemunho; à tarde havia sobre o tabernáculo uma aparência de fogo, até a manhã. Assim acontecia regularmente; a nuvem cobria-o, e à noite havia aparência de fogo." Este versículo descreve como Deus guiou os filhos de Israel durante a jornada no deserto. A nuvem e o fogo eram sinais visíveis da presença de Deus e indicavam quando era hora de partir.
* Deuteronômio 1:33: "Quem, no caminho, adiante de vós, ia diante de vós, de noite no fogo, para vos mostrar o lugar onde havíeis de acampar, e de dia na nuvem." Este versículo é uma referência à nuvem e ao fogo que guiavam os filhos de Israel durante a jornada no deserto. Mostra que Deus estava presente e os liderava, mesmo em momentos difíceis.
* Salmos 81:3: "Tocai a trombeta na lua nova, no tempo apontado da nossa solenidade." Este versículo menciona o uso da trombeta em celebrações religiosas. As trombetas de prata descritas em Números 10 eram usadas como sinais para a congregação, mas também eram usadas em momentos de adoração e celebração.
* Mateus 24:31: "E ele enviará os seus anjos com rijo clamor de trombeta, os quais ajuntarão os seus escolhidos desde os quatro ventos, de uma à outra extremidade dos céus." Este versículo é uma referência à volta de Jesus e à ressurreição dos mortos. A imagem de anjos tocando trombetas é uma figura simbólica usada para descrever o evento. A trombeta é um símbolo de anúncio e preparação para o grande evento.
****

[[v4-10-1]]

^<<v4-10-1,1>>^ O Senhor disse a Moisés o seguinte:

[[v4-10-2]]

^<<v4-10-2,2>>^ “Faze para ti duas trombetas de prata: faze-as de prata batida. Elas te servirão para convocar a assembleia e para dar o sinal de levantar o acampamento.

[[v4-10-3]]

^<<v4-10-3,3>>^ Quando elas soarem, toda a assembleia se reunirá junto de ti, à entrada da tenda de reunião.

[[v4-10-4]]

^<<v4-10-4,4>>^ Se se tocar uma só, virão e se juntarão a ti os príncipes, os chefes de milhares em Israel.

[[v4-10-5]]

^<<v4-10-5,5>>^ Quando tocardes com força, partirão aqueles que estão acampados ao oriente.

[[v4-10-6]]

^<<v4-10-6,6>>^ E quando tocardes com força uma segunda vez, partirão aqueles que estão acampados ao meio-dia; o sinal para a sua partida será um toque de alarme.

[[v4-10-7]]

^<<v4-10-7,7>>^ Para convocar a assembleia tocareis também, mas não com o toque de alarme.

[[v4-10-8]]

^<<v4-10-8,8>>^ São os filhos de Aarão, os sacerdotes, que tocarão as trombetas. É uma lei perpétua para vós e vossos descendentes.

[[v4-10-9]]

^<<v4-10-9,9>>^ Quando na vossa terra sairdes à guerra contra inimigos que vos atacarem, tocareis com força as trombetas, e o Senhor, vosso Deus, se lembrará de vós, e sereis livres dos vossos inimigos.

[[v4-10-10]]

^<<v4-10-10,10>>^ Nos vossos dias de alegria, vossas festas e vossas luas novas, tocareis as trombetas, oferecendo os holocaustos e os sacrifícios pacíficos, e elas vos lembrarão a memória de vosso Deus. Eu sou o Senhor, vosso Deus”.

[[v4-10-11]]

^<<v4-10-11,11>>^ No vigésimo dia do segundo mês do segundo ano, levantou-se a nuvem do tabernáculo do testemunho.

[[v4-10-12]]

^<<v4-10-12,12>>^ Os israelitas puseram-se em marcha e partiram do deserto do Sinai, e a nuvem parou no deserto de Farã.

[[v4-10-13]]

^<<v4-10-13,13>>^ Partiram, pois, pela primeira vez, conforme a ordem do Senhor transmitida por Moisés.

[[v4-10-14]]

^<<v4-10-14,14>>^ A bandeira do acampamento dos filhos de Judá partiu em primeiro lugar, seguida de suas tropas; e a tropa de Judá era comandada por Naasson, filho de Abinadab.

[[v4-10-15]]

^<<v4-10-15,15>>^ A tropa da tribo dos filhos de Issacar era comandada por Natanael, filho de Suar;

[[v4-10-16]]

^<<v4-10-16,16>>^ e a tropa da tribo dos filhos de Zabulon era comandada por Eliab, filho de Helon.

[[v4-10-17]]

^<<v4-10-17,17>>^ O tabernáculo foi desmontado, e os filhos de Gérson e de Merari partiram, transportando-o.

[[v4-10-18]]

^<<v4-10-18,18>>^ Depois partiu a bandeira do acampamento de Rúben, seguida de suas tropas, e seu comandante era Elisur, filho de Sedeur.

[[v4-10-19]]

^<<v4-10-19,19>>^ A tropa da tribo dos filhos de Simeão era comandada por Salamiel, filho de Surisadai;

[[v4-10-20]]

^<<v4-10-20,20>>^ e a tropa da tribo dos filhos de Gad era comandada por Eliasaf, filho de Reuel.

[[v4-10-21]]

^<<v4-10-21,21>>^ Os caatitas partiram em seguida, levando os objetos sagrados. E, antes que chegassem, era montado o tabernáculo.

[[v4-10-22]]

^<<v4-10-22,22>>^ A bandeira do acampamento dos filhos de Efraim partiu, seguida de suas tropas; e a tropa de Efraim era comandada por Elisama, filho de Amiud.

[[v4-10-23]]

^<<v4-10-23,23>>^ A tropa da tribo dos filhos de Manassés era comandada por Gamaliel, filho de Fadassur;

[[v4-10-24]]

^<<v4-10-24,24>>^ e a tropa da tribo de Benjamim era comandada por Abidã, filho de Gedeão.

[[v4-10-25]]

^<<v4-10-25,25>>^ A bandeira do acampamento dos filhos de Dã, que formavam a retaguarda de todos os acampamentos, partiu, seguida de suas tropas. A tropa de Dã era comandada por Aiezer, filho de Amisadai.

[[v4-10-26]]

^<<v4-10-26,26>>^ A tropa da tribo dos filhos de Aser era comandada por Fegiel, filho de Ocrã;

[[v4-10-27]]

^<<v4-10-27,27>>^ e a tropa dos filhos de Neftali era comandada por Aíra, filho de Enã.

[[v4-10-28]]

^<<v4-10-28,28>>^ Essa foi a ordem de marcha dos israelitas, divididos em tropas, quando levantaram acampamento.

[[v4-10-29]]

^<<v4-10-29,29>>^ Moisés disse a Hobab, filho de Raguel, o madianita, seu sogro: “Nós partimos para o lugar que o Senhor nos prometeu dar. Vem conosco, e te haveremos de tratar bem, porque o Senhor prometeu fazer bem a Israel”.

[[v4-10-30]]

^<<v4-10-30,30>>^ Hobab, porém, respondeu-lhe: “Não irei contigo, mas voltarei para a minha terra e para junto de minha família”.

[[v4-10-31]]

^<<v4-10-31,31>>^ Moisés replicou: “Rogo-te que não te separes de nós. Conheces os lugares onde podemos acampar no deserto e nos servirás de guia.

[[v4-10-32]]

^<<v4-10-32,32>>^ Se vieres conosco, dividiremos contigo os bens que o Senhor nos der”.

[[v4-10-33]]

^<<v4-10-33,33>>^ Partiram da montanha do Senhor e caminharam três dias. Durante esses três dias de marcha, a arca da aliança do Senhor os precedia, para lhes escolher um lugar de repouso.

[[v4-10-34]]

^<<v4-10-34,34>>^ A nuvem do Senhor estava sobre eles de dia, quando partiam do acampamento.

[[v4-10-35]]

^<<v4-10-35,35>>^ Quando a arca se levantava, Moisés dizia: “Levantai-vos, Senhor, e sejam dispersos os vossos inimigos! Fujam de vossa face os que vos aborrecem!”.

[[v4-10-36]]

^<<v4-10-36,36>>^ Quando, porém, se detinha, dizia: “Voltai, Senhor, para a imensa multidão de Israel!”.

'''

xref:004-numeros/004-numeros-009.adoc#v4-9-0[&#60; Capítulo Anterior] | <<v4-10-0,Topo>> | xref:004-numeros/004-numeros-011.adoc#v4-11-0[Próximo Capítulo &#62;]