include::./index.adoc[]

[[v4-4-0]]
=== Números, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 4 de Números trata das responsabilidades dos levitas em relação ao transporte do Tabernáculo e dos objetos sagrados durante a jornada pelo deserto. Os versículos selecionados são:
* Deuteronômio 31:25-26: "que Moisés ordenou aos levitas que transportassem a arca da aliança do Senhor, dizendo: Tomai este livro da lei e colocai-o ao lado da arca da aliança do Senhor, vosso Deus, para que ali esteja como testemunha contra ti." Esses versículos mostram a importância dos levitas no transporte dos objetos sagrados, incluindo a Arca da Aliança.
* 1 Crônicas 15:2: "Então disse Davi: Aqui está a arca de Deus, a qual mandamos buscar, para colocar sob uma tenda que lhe fizemos." Este versículo descreve a transferência da Arca da Aliança para Jerusalém, onde Davi construiu um tabernáculo para abrigá-la.
* 1 Crônicas 23:24-32: "Estas foram as responsabilidades deles em relação ao serviço no tabernáculo da casa de Deus, de acordo com as instruções de Arão, seu pai, como o Senhor, o Deus de Israel, lhe havia ordenado." Esses versículos detalham as responsabilidades dos levitas no serviço do Tabernáculo e como eles foram designados para cumprir essas funções.
* Salmos 84:1-2: "Quão amáveis são os teus tabernáculos, Senhor dos Exércitos! A minha alma anela, e até desfalece pelos átrios do Senhor; o meu coração e o meu corpo cantam de alegria ao Deus vivo." Este salmo descreve o desejo de adorar a Deus no Tabernáculo e como as pessoas se sentiam atraídas pela presença de Deus lá.
* Hebreus 9:1-5: "Ora, a primeira aliança também tinha ordenanças de culto e um santuário terrestre. Pois um tabernáculo foi preparado, o primeiro, em que havia o candelabro, e a mesa, e os pães da proposição; e a este chamavam o lugar santo. Mas, por detrás do segundo véu, estava o tabernáculo que se chama o santo dos santos, o qual tinha um incensário de ouro, e a arca da aliança toda coberta de ouro..." Esses versículos descrevem o Tabernáculo e seus objetos sagrados em detalhes, dando uma compreensão mais profunda de como tudo funcionava e como era importante para a adoração a Deus.
****

[[v4-4-1]]

^<<v4-4-1,1>>^ O Senhor disse a Moisés e a Aarão:

[[v4-4-2]]

^<<v4-4-2,2>>^ “Entre os levitas, farás a contagem dos filhos de Caat, segundo suas famílias e suas casas patriarcais,

[[v4-4-3]]

^<<v4-4-3,3>>^ da idade de trinta anos para cima até os cinquenta, de todos os que estão em condições de servir em qualquer função na tenda de reunião.

[[v4-4-4]]

^<<v4-4-4,4>>^ Este é o serviço dos caatitas na tenda de reunião: cuidar dos objetos santíssimos.

[[v4-4-5]]

^<<v4-4-5,5>>^ Quando se levantar o acampamento, Aarão e seus filhos tirarão o véu e cobrirão com ele a arca do testemunho;

[[v4-4-6]]

^<<v4-4-6,6>>^ porão em cima uma coberta de pele de golfinho, sobre ela estenderão um pano todo de púrpura violeta e porão os varais da arca.

[[v4-4-7]]

^<<v4-4-7,7>>^ Estenderão um pano de púrpura violeta sobre a mesa dos pães da proposição, e porão nela os pratos, os vasos, as taças e os copos para as libações. O pão perpétuo estará sobre ela.

[[v4-4-8]]

^<<v4-4-8,8>>^ Estenderão por cima um pano carmesim, envolto ainda com uma coberta de pele de golfinho; e colocarão os varais da mesa.

[[v4-4-9]]

^<<v4-4-9,9>>^ Tomarão em um pano de púrpura violeta para cobrir o candelabro, suas lâmpadas, suas espevitadeiras, seus cinzeiros e os recipientes de óleo necessários ao seu serviço.

[[v4-4-10]]

^<<v4-4-10,10>>^ Porão o candelabro com todos os seus utensílios em um estojo de pele de golfinho e o colocarão sobre os varais.

[[v4-4-11]]

^<<v4-4-11,11>>^ Estenderão sobre o altar de ouro um pano de púrpura violeta, e porão nele os varais depois de o terem coberto com uma cobertura de pele de golfinho.

[[v4-4-12]]

^<<v4-4-12,12>>^ Tomarão todos os utensílios empregados para o serviço do santuário e os envolverão num pano de púrpura violeta, cobrindo-os, em seguida, com uma cobertura de pele de golfinho, para serem colocados sobre os varais.

[[v4-4-13]]

^<<v4-4-13,13>>^ Tirarão as cinzas do altar e estenderão sobre ele um pano de púrpura escarlate.

[[v4-4-14]]

^<<v4-4-14,14>>^ Porão em cima todos os utensílios destinados ao seu serviço, os incensários, os garfos, as pás, as bacias, todos os utensílios do altar. Estenderão sobre tudo isso uma coberta de pele de golfinho, e lhe enfiarão os varais.

[[v4-4-15]]

^<<v4-4-15,15>>^ Quando Aarão e seus filhos tiverem acabado de cobrir o santuário e todos os seus utensílios, ao levantarem o acampamento, os caatitas virão levá-los, mas não tocarão nas coisas santas, para que não morram. Essas são as coisas que deverão levar os filhos de Caat da tenda de reunião.

[[v4-4-16]]

^<<v4-4-16,16>>^ Eleazar, filho do sacerdote Aarão, cuidará do óleo do candelabro, o incenso aromático, a oblação perpétua e o óleo para a unção, bem como da vigilância de todo o tabernáculo, com tudo o que contém, e do santuário com todos os seus utensílios”.

[[v4-4-17]]

^<<v4-4-17,17>>^ O Senhor disse a Moisés e a Aarão:

[[v4-4-18]]

^<<v4-4-18,18>>^ “Velai para que a família dos caatitas não seja cortada do meio dos levitas.

[[v4-4-19]]

^<<v4-4-19,19>>^ Fazei isso por eles, a fim de que vivam e não morram quando se aproximarem do lugar santíssimo. Aarão e seus filhos entrarão e distribuirão a cada um a carga que ele deverá levar.

[[v4-4-20]]

^<<v4-4-20,20>>^ Não entrarão para olhar as coisas santas, nem mesmo um só instante, para que não morram”.^&#42;1^

[[v4-4-21]]

^<<v4-4-21,21>>^ O Senhor disse a Moisés:

[[v4-4-22]]

^<<v4-4-22,22>>^ “Faça a contagem dos filhos de Gérson, segundo suas casas patriarcais e suas famílias.

[[v4-4-23]]

^<<v4-4-23,23>>^ Recensearás todos aqueles que estão em condições de cumprir uma tarefa na tenda de reunião, da idade de trinta anos para cima até os cinquenta.

[[v4-4-24]]

^<<v4-4-24,24>>^ Eis os encargos que darás à família dos gersonitas, coisas para fazer e cargas para levar.

[[v4-4-25]]

^<<v4-4-25,25>>^ Levarão as cortinas do tabernáculo e a tenda de reunião, a coberta de pele de golfinho que se põe por cima, o véu que está à entrada da tenda de reunião,

[[v4-4-26]]

^<<v4-4-26,26>>^ as cortinas do átrio, os reposteiros da entrada da porta do átrio, em volta do tabernáculo e do altar, suas cordas e todos os utensílios de seu uso; e farão todo o serviço que se relaciona com essas coisas.

[[v4-4-27]]

^<<v4-4-27,27>>^ Todo o serviço dos filhos dos gersonitas, tudo o que eles terão de levar e de fazer, estará sob as ordens de Aarão e seus filhos. Confiareis ao seu cuidado tudo o que eles deverão levar.

[[v4-4-28]]

^<<v4-4-28,28>>^ Esse é o serviço das famílias dos filhos dos gersonitas na tenda de reunião; será executado sob a direção de Itamar, filho do sacerdote Aarão.

[[v4-4-29]]

^<<v4-4-29,29>>^ Recensearás os filhos de Merari, segundo suas famílias e segundo suas casas patriarcais;

[[v4-4-30]]

^<<v4-4-30,30>>^ da idade de trinta anos para cima até os cinquenta, recensearás todos os que estiverem em condições de fazer o serviço na tenda de reunião.

[[v4-4-31]]

^<<v4-4-31,31>>^ Eis o que eles terão de guardar e de levar para cumprir a tarefa que lhes é confiada na tenda de reunião: as tábuas do tabernáculo, suas travessas, suas colunas, seus pedestais;

[[v4-4-32]]

^<<v4-4-32,32>>^ as colunas que estão ao redor do átrio, seus pedestais, suas estacas, suas cordas e todos os seus utensílios com tudo o que se relaciona com esse serviço. Fareis um inventário nominativo do que se lhes der a guardar e a levar.

[[v4-4-33]]

^<<v4-4-33,33>>^ Tal é o serviço das famílias dos filhos de Merari e o que eles terão a fazer na tenda de reunião, sob a fiscalização de Itamar, filho do sacerdote Aarão”.

[[v4-4-34]]

^<<v4-4-34,34>>^ Moisés, Aarão e os principais da assembleia recensearam os filhos dos caatitas segundo suas famílias e segundo suas casas patriarcais,

[[v4-4-35]]

^<<v4-4-35,35>>^ da idade de trinta anos para cima até os cinquenta, todos aqueles que estavam em condições de cumprir uma tarefa na tenda de reunião.

[[v4-4-36]]

^<<v4-4-36,36>>^ O número dos recenseados segundo suas famílias foi de dois mil setecentos e cinquenta.

[[v4-4-37]]

^<<v4-4-37,37>>^ Tais foram os recenseados das famílias dos caatitas, todos os que tinham uma função a exercer na tenda de reunião. Moisés e Aarão fizeram esse recenseamento segundo a ordem que o Senhor tinha dado pela boca de Moisés.

[[v4-4-38]]

^<<v4-4-38,38>>^ Os filhos de Gérson foram recenseados segundo suas famílias e segundo suas casas patriarcais,

[[v4-4-39]]

^<<v4-4-39,39>>^ da idade de trinta anos para cima até os cinquenta – todos os que estavam em condições de cumprir uma tarefa na tenda de reunião –,

[[v4-4-40]]

^<<v4-4-40,40>>^ os que foram recenseados segundo suas famílias e segundo suas casas patriarcais eram em número de dois mil seiscentos e trinta.

[[v4-4-41]]

^<<v4-4-41,41>>^ Tais foram os recenseados dentre as famílias de Gérson, os que tinham uma função a exercer na tenda de reunião. Moisés e Aarão fizeram esse recenseamento por ordem do Senhor.

[[v4-4-42]]

^<<v4-4-42,42>>^ Entre as famílias dos filhos de Merari, os que foram recenseados segundo suas famílias e suas casas patriarcais,

[[v4-4-43]]

^<<v4-4-43,43>>^ da idade de trinta anos para cima até os cinquenta – todos os que estavam em condições de exercer um ofício na tenda de reunião –,

[[v4-4-44]]

^<<v4-4-44,44>>^ os que foram recenseados segundo suas famílias eram em número de tres mil e duzentos.

[[v4-4-45]]

^<<v4-4-45,45>>^ Tais foram os recenseados das famílias dos filhos de Merari. Moisés e Aarão fizeram esse recenseamento segundo a ordem do Senhor a Moisés.

[[v4-4-46]]

^<<v4-4-46,46>>^ Todos os levitas recenseados por Moisés, Aarão e os principais de Israel, segundo suas famílias e segundo suas casas patriarcais,

[[v4-4-47]]

^<<v4-4-47,47>>^ da idade de trinta anos para cima até os cinquenta, todos os que estavam em condições de exercer uma função, seja de servo, seja de transportador, na tenda de reunião,

[[v4-4-48]]

^<<v4-4-48,48>>^ todos os que foram recenseados somaram oito mil quinhentos e oitenta.

[[v4-4-49]]

^<<v4-4-49,49>>^ Fez-se esse recenseamento segundo a ordem do Senhor dada pela boca de Moisés, prescrevendo a cada um a tarefa que ele tinha a cumprir e a carga que devia levar. Fez-se o recenseamento como o Senhor ordenara a Moisés.

'''

xref:004-numeros/004-numeros-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numeros/004-numeros-005.adoc#v4-5-0[Próximo Capítulo &#62;]