include::./index.adoc[]

[[v4-20-0]]
=== Números, 20
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Números 20 narra a morte de Miriã, irmã de Moisés, e a falta de água para a comunidade de Israel, que acaba gerando uma série de conflitos. Moisés e Arão se dirigem até o Tabernáculo para buscar orientação de Deus, e Ele instrui que Moisés fale à rocha para que ela dê água ao povo. Entretanto, Moisés, irritado com as reclamações do povo, acaba ferindo a rocha com sua vara, o que desagrada a Deus. Abaixo estão cinco versículos relacionados com os temas abordados em Números 20:
* Salmos 106:32-33: "Com a água da contenda os fizeram irados, e sucedeu mal a Moisés por causa deles. Pois exacerbaram seu espírito, de modo que falou precipitadamente com seus lábios". Este Salmo faz referência ao episódio narrado em Números 20, no qual o povo de Israel reclama da falta de água e Moisés acaba agindo impulsivamente e ferindo a rocha com sua vara.
* Isaías 48:21: "Eles não tinham sede quando ele os levou pelos desertos; ele fez água fluir da rocha para eles; ele fendia a rocha, e a água jorrava". Este versículo faz referência à época em que os israelitas vagavam pelo deserto e Deus, por intermédio de Moisés, fez brotar água da rocha para saciar a sede do povo.
* João 4:13-14: "Jesus respondeu: 'Quem beber desta água terá sede de novo, mas quem beber da água que eu lhe der nunca mais terá sede. Ao contrário, a água que eu lhe der se tornará nele uma fonte de água a jorrar para a vida eterna'". Este versículo faz referência à água viva que Jesus oferece, que simboliza a vida eterna e a satisfação plena das necessidades espirituais.
* 1 Coríntios 10:4: "e todos beberam da mesma bebida espiritual, pois bebiam da rocha espiritual que os acompanhava, e essa rocha era Cristo". Este versículo faz referência à rocha que foi ferida por Moisés para que a água jorrasse e saciasse a sede do povo de Israel no deserto. Paulo, ao escrever aos coríntios, faz uma conexão entre a rocha que saciava a sede física do povo no deserto e Cristo, que sacia a sede espiritual de todos aqueles que crêem nele.
* Apocalipse 21:6: "E disse-me: 'Está feito. Eu sou o Alfa e o Ômega, o Princípio e o Fim. A quem tiver sede darei de beber gratuitamente da fonte da água da vida'". Este versículo faz referência à Nova Jerusalém, a cidade celestial que Deus criará no fim dos tempos. Nessa cidade, todos os que tiverem sede poderão beber gratuitamente da fonte da água da vida, que simboliza a vida eterna.
****

[[v4-20-1]]

^<<v4-20-1,1>>^ Toda a assembleia dos filhos de Israel chegou ao deserto de Sin no primeiro mês. O povo ficou em Cades; ali morreu Maria, que foi sepultada no mesmo lugar.

[[v4-20-2]]

^<<v4-20-2,2>>^ Como não houvesse água para a assembleia, o povo se ajuntou contra Moisés e Aarão,

[[v4-20-3]]

^<<v4-20-3,3>>^ procurou disputar com Moisés e gritou: “Oxalá tivéssemos perecido com nossos irmãos diante do Senhor!

[[v4-20-4]]

^<<v4-20-4,4>>^ Por que conduziste a assembleia do Senhor a este deserto, para nos deixar morrer aqui com os nossos rebanhos?

[[v4-20-5]]

^<<v4-20-5,5>>^ Por que nos fizeste sair do Egito e nos trouxeste a este péssimo lugar, em que não se pode semear, e onde não há figueira, nem vinha, nem romãzeira, e tampouco há água para beber?”.

[[v4-20-6]]

^<<v4-20-6,6>>^ Moisés e Aarão deixaram a assembleia e dirigiram-se à entrada da tenda de reunião, onde se prostraram com a face por terra. Apareceu-lhes a glória do Senhor,

[[v4-20-7]]

^<<v4-20-7,7>>^ e o Senhor disse a Moisés:

[[v4-20-8]]

^<<v4-20-8,8>>^ “Toma a tua vara e convoca a assembleia, tu e teu irmão Aarão. Ordenareis ao rochedo, diante de todos, que dê as suas águas; farás brotar a água do rochedo e darás de beber à assembleia e aos seus rebanhos”.

[[v4-20-9]]

^<<v4-20-9,9>>^ Tomou Moisés a vara que estava diante do Senhor, como ele lhe tinha ordenado.

[[v4-20-10]]

^<<v4-20-10,10>>^ Em seguida, tendo Moisés e Aarão convocado a assembleia diante do rochedo, disse-lhes Moisés: “Ouvi, rebeldes: Acaso faremos nós brotar água deste rochedo?”.

[[v4-20-11]]

^<<v4-20-11,11>>^ Moisés levantou a mão e feriu o rochedo com a sua vara duas vezes; as águas jorraram em abundância, de sorte que beberam, o povo e os animais.

[[v4-20-12]]

^<<v4-20-12,12>>^ Em seguida, disse o Senhor a Moisés e Aarão: “Porque faltastes à confiança em mim para fazer brilhar a minha santidade aos olhos dos israelitas, não introduzireis esta assembleia na terra que lhe destino”.

[[v4-20-13]]

^<<v4-20-13,13>>^ Estas são as águas de Meriba, onde os israelitas se queixaram do Senhor, e onde este fez resplandecer a sua santidade.^&#42;1^

[[v4-20-14]]

^<<v4-20-14,14>>^ De Cades, Moisés enviou mensageiros ao rei de Edom: “Eis – disseram-lhe eles – as palavras que te dirige o teu irmão Israel: Tu sabes todos os males que temos passado.

[[v4-20-15]]

^<<v4-20-15,15>>^ Nossos pais tinham descido ao Egito, onde habitamos durante muito tempo. Os egípcios, porém, nos maltrataram, a nós e a nossos pais.

[[v4-20-16]]

^<<v4-20-16,16>>^ Clamamos ao Senhor, ele nos ouviu, e mandou-nos um anjo que nos tirou do Egito. Eis-nos agora aqui em Cades, cidade situada nos confins de teu território.^&#42;1^

[[v4-20-17]]

^<<v4-20-17,17>>^ Deixa-nos passar pela tua terra. Não atravessaremos os campos, nem as vinhas e não beberemos a água dos poços; mas seguiremos a estrada real sem nos desviarmos nem para a direita nem para a esquerda, até que tenhamos passado o teu território”.

[[v4-20-18]]

^<<v4-20-18,18>>^ Edom respondeu: “Tu não passarás pela minha terra; do contrário, sairei ao teu encontro com a espada na mão”.

[[v4-20-19]]

^<<v4-20-19,19>>^ Disseram-lhe os israelitas: “Tomaremos a estrada comum, e se bebermos de tua água, eu e os meus rebanhos, te pagarei o preço. Não há perigo algum; só queremos passar”.

[[v4-20-20]]

^<<v4-20-20,20>>^ Edom replicou: “Tu não passarás”. E veio em massa ao encontro deles com as armas na mão.

[[v4-20-21]]

^<<v4-20-21,21>>^ Recusando Edom a passagem através do seu território, Israel tomou outra direção.

[[v4-20-22]]

^<<v4-20-22,22>>^ Partiram de Cades. Toda a assembleia dos israelitas chegou ao monte Hor.

[[v4-20-23]]

^<<v4-20-23,23>>^ Nesse lugar, que está nas fronteiras da terra de Edom, o Senhor disse a Moisés e a Aarão:

[[v4-20-24]]

^<<v4-20-24,24>>^ “Aarão vai ser reunido aos seus, porque ele não entrará na terra que destino aos filhos de Israel, visto terdes sido rebeldes à minha ordem nas águas de Meriba.

[[v4-20-25]]

^<<v4-20-25,25>>^ Toma Aarão e seu filho Eleazar, e leva-os ao monte Hor.

[[v4-20-26]]

^<<v4-20-26,26>>^ Despojarás Aarão de suas vestes e revestirás com elas o seu filho Eleazar. Aarão será reunido aos seus, e aí morrerá”.

[[v4-20-27]]

^<<v4-20-27,27>>^ Moisés fez como ordenou o Senhor: Subiram ao monte Hor à vista da assembleia.

[[v4-20-28]]

^<<v4-20-28,28>>^ Despojando Aarão de suas vestes, Moisés revestiu com elas Eleazar, filho do sacerdote. Aarão morreu ali, no cimo do monte. Moisés e Eleazar desceram de novo,

[[v4-20-29]]

^<<v4-20-29,29>>^ e toda a assembleia, ao saber da morte de Aarão, chorou-o durante trinta dias.

'''

xref:004-numeros/004-numeros-019.adoc#v4-19-0[&#60; Capítulo Anterior] | <<v4-20-0,Topo>> | xref:004-numeros/004-numeros-021.adoc#v4-21-0[Próximo Capítulo &#62;]