include::./index.adoc[]

[[v4-30-0]]
=== Números, 30
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Números 30 trata sobre os votos que as pessoas fazem ao Senhor e a importância de cumpri-los. O capítulo também destaca a importância de honrar os compromissos feitos, especialmente no contexto do casamento. Abaixo estão cinco versículos relacionados com os temas abordados em Números 30:
* Deuteronômio 23:21: "Se fizeres algum voto ao Senhor, teu Deus, não tardes em cumpri-lo; pois o Senhor, teu Deus, certamente o requererá de ti e em ti haverá pecado." Este versículo destaca a importância de cumprir os votos feitos ao Senhor e a seriedade com que Ele os leva.
* Provérbios 20:25: "É uma armadilha para o homem fazer um voto precipitadamente e só refletir sobre ele depois." Este versículo adverte as pessoas para não fazerem votos precipitados, mas sim ponderar cuidadosamente antes de comprometerem-se com algo.
* Mateus 5:33-34: "Também ouvistes o que foi dito aos antigos: Não jurarás falso, mas cumprirás para com o Senhor os teus juramentos. Eu, porém, vos digo que de modo algum jureis; nem pelo céu, por ser o trono de Deus."
* Eclesiastes 5:4-5: "Quando a Deus fizeres algum voto, não tardes em cumpri-lo; porque não se agrada de tolos. Cumpre o voto que fazes. Melhor é que não votes do que votes e não cumpras."
* Efésios 5:21-22: "Sujeitai-vos uns aos outros no temor de Cristo. Vós, mulheres, sujeitai-vos a vossos maridos, como ao Senhor." Este versículo destaca a importância de honrar os compromissos feitos no casamento e de sujeitar-se uns aos outros em amor e respeito.
****

[[v4-30-1]]

^<<v4-30-1,1>>^ Moisés referiu aos israelitas tudo o que o Senhor lhe tinha ordenado.

[[v4-30-2]]

^<<v4-30-2,2>>^ Moisés disse aos chefes das tribos israelitas: “Eis o que o Senhor ordenou:

[[v4-30-3]]

^<<v4-30-3,3>>^ Se um homem fizer um voto ao Senhor ou se se comprometer com juramento a uma obrigação qualquer, não faltará à sua palavra, mas cumprirá toda obrigação que tiver tomado.

[[v4-30-4]]

^<<v4-30-4,4>>^ Se uma donzela, que se encontre ainda na casa de seu pai, fizer um voto ao Senhor, ou se se impuser uma obrigação,

[[v4-30-5]]

^<<v4-30-5,5>>^ e seu pai, tendo conhecimento do voto que ela fez ou da obrigação que tomou, nada disse, todos os seus votos e suas obrigações serão válidos.

[[v4-30-6]]

^<<v4-30-6,6>>^ Porém, se seu pai se opuser no dia em que ele tiver conhecimento disso, todos os seus votos e obrigações serão inválidos, e o Senhor o perdoará, porque seu pai se opôs.

[[v4-30-7]]

^<<v4-30-7,7>>^ Se na ocasião de seu casamento ela estiver ligada por algum voto ou algum compromisso inconsiderado,

[[v4-30-8]]

^<<v4-30-8,8>>^ e seu marido, sabendo-o, não disser nada naquele dia, seus votos serão válidos, assim como os compromissos tomados.

[[v4-30-9]]

^<<v4-30-9,9>>^ Mas se o marido, no dia em que disso tiver conhecimento, desaprová-lo, serão nulos o seu voto e o compromisso tomados inconsideradamente, e o Senhor o perdoará.

[[v4-30-10]]

^<<v4-30-10,10>>^ O voto de uma viúva, ou de uma mulher repudiada, e toda obrigação que ela se impuser a si mesma, será válida para ela.

[[v4-30-11]]

^<<v4-30-11,11>>^ A mulher que está em casa de seu marido, se se obrigar com voto, ou se se impuser uma obrigação, ou juramento,

[[v4-30-12]]

^<<v4-30-12,12>>^ desde que o marido, ao sabê-lo, nada diga, nem se oponha, todos os seus votos serão válidos, bem como todo compromisso que ela tiver tomado.

[[v4-30-13]]

^<<v4-30-13,13>>^ Porém, se seu marido se opuser ao ser informado de seus votos, todos eles serão nulos e, igualmente, todos os compromissos que tiver tomado; serão sem valor, porque foram anulados por seu marido, e o Senhor o perdoará.

[[v4-30-14]]

^<<v4-30-14,14>>^ Seu marido pode ratificar ou anular todo voto ou todo juramento que ela tiver feito para se mortificar.

[[v4-30-15]]

^<<v4-30-15,15>>^ Se seu marido guardar silêncio até o dia seguinte, com isso ratifica todos os seus votos e todos os seus compromissos; e os ratifica porque nada disse no dia em que deles teve conhecimento.

[[v4-30-16]]

^<<v4-30-16,16>>^ Se os anular depois do dia em que o soube, levará a responsabilidade da falta de sua mulher”.

[[v4-30-17]]

^<<v4-30-17,17>>^ Tais são as leis que o Senhor prescreveu a Moisés com relação a marido e mulher, pai e filha, quando esta é ainda jovem e vive na casa de seu pai.

'''

xref:004-numeros/004-numeros-029.adoc#v4-29-0[&#60; Capítulo Anterior] | <<v4-30-0,Topo>> | xref:004-numeros/004-numeros-031.adoc#v4-31-0[Próximo Capítulo &#62;]