include::./index.adoc[]

[[v4-26-0]]
=== Números, 26
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 26 do livro de Números apresenta um censo dos filhos de Israel após a morte da geração que havia sido contada no primeiro censo. Os versículos abaixo se relacionam com temas abordados nesse capítulo:
* Gênesis 46:8: "E estes são os nomes dos filhos de Israel, que entraram no Egito, Jacó e seus filhos: Rúben, o primogênito de Jacó." Este versículo menciona o filho mais velho de Jacó, Rúben, que também é listado como o primogênito de Israel no censo de Números 26.
* Êxodo 6:15: "E estes são os filhos de Levi, segundo as suas gerações: Gérson, Coate e Merari; e os anos da vida de Levi foram cento e trinta e sete anos." Este versículo apresenta os três filhos de Levi, que foram os ancestrais das três famílias levíticas que foram contadas no censo de Números 26.
* Deuteronômio 2:14: "E o tempo que caminhamos desde Cades-Barnéia, até que passamos o ribeiro de Zerede, foi de trinta e oito anos; até que se consumiu toda aquela geração dos homens de guerra, do meio do arraial, como o SENHOR lhes jurara." Este versículo menciona o período de tempo que se passou desde a primeira contagem até a segunda contagem, que é registrada em Números 26.
* Números 1:44: "Estes são os contados, que Moisés e Arão contaram com os doze príncipes de Israel; cada um era chefe da casa dos seus pais." Este versículo se relaciona com o censo anterior, registrado em Números 1, que contou os filhos de Israel antes de partir para o deserto.
* Josué 14:1: "Estes, pois, são os que ficaram dos filhos de Israel na terra de Canaã, os quais Eleazar, o sacerdote, e Josué, filho de Num, e os cabeças dos pais das tribos dos filhos de Israel deram em possessão." Este versículo menciona a distribuição da terra de Canaã entre as tribos de Israel após o censo registrado em Números 26.
****

[[v4-26-1]]

^<<v4-26-1,1>>^ Depois desse flagelo, disse o Se-nhor a Moisés e a Eleazar, filho do sacerdote Aarão:

[[v4-26-2]]

^<<v4-26-2,2>>^ “Fazei o recenseamento de toda a assembleia dos israelitas da idade de vinte anos para cima, família por família, todos os que estiverem em condições de pegar em armas”.

[[v4-26-3]]

^<<v4-26-3,3>>^ Moisés e o sacerdote Eleazar disseram pois nas planícies de Moab, às margens do Jordão, perto de Jericó:

[[v4-26-4]]

^<<v4-26-4,4>>^ “Serão recenseados todos os que tiverem a idade de vinte anos para cima, como o Senhor ordenou a Moisés e aos israelitas ao saírem do Egito”.

[[v4-26-5]]

^<<v4-26-5,5>>^ Rúben, primogênito de Israel. Filhos de Rúben: de Henoc, a família dos henoquitas; de Falu, a família dos faluítas;

[[v4-26-6]]

^<<v4-26-6,6>>^ de Hesron, a família dos hesronitas; de Carmi, a família dos carmitas.

[[v4-26-7]]

^<<v4-26-7,7>>^ Essas são as famílias dos rubenitas; seus recenseados foram em número de quarenta e três mil setecentos e trinta.

[[v4-26-8]]

^<<v4-26-8,8>>^ Filho de Falu, Eliab.

[[v4-26-9]]

^<<v4-26-9,9>>^ Filhos de Eliab, Namuel, Datã e Abiram. Estes são Datã e Abiram, aqueles membros do conselho que se tinham sublevado contra Moisés e Aarão, com os cúmplices de Coré em revolta contra o Senhor.

[[v4-26-10]]

^<<v4-26-10,10>>^ A terra, abrindo sua boca, engoliu-os com Coré, enquanto o seu grupo perecia pelo fogo que devorou os duzentos e cinquenta homens. Isso serviu de exemplo.

[[v4-26-11]]

^<<v4-26-11,11>>^ Os filhos de Coré, porém, não pereceram.

[[v4-26-12]]

^<<v4-26-12,12>>^ Filhos de Simeão, classificados por famílias: de Namuel, a família dos namuelitas; de Jamim, a família dos jaminitas; de Joaquim, a família dos joaquinitas;

[[v4-26-13]]

^<<v4-26-13,13>>^ de Zaré, a família dos zaritas; de Saul, a família dos saulitas.

[[v4-26-14]]

^<<v4-26-14,14>>^ Tais são as famílias dos simeonitas: vinte dois mil e duzentos homens.

[[v4-26-15]]

^<<v4-26-15,15>>^ Filhos de Gad, classificados por famílias: de Sefon, a família dos sefonitas; de Agi, a família dos agitas; de Suni, a família dos sunitas;

[[v4-26-16]]

^<<v4-26-16,16>>^ de Ozni, a família dos oznitas; de Her, a família dos heritas;

[[v4-26-17]]

^<<v4-26-17,17>>^ de Arod, a família dos aroditas; de Ariel, a família dos arielitas.

[[v4-26-18]]

^<<v4-26-18,18>>^ Essas são as famílias dos gaditas. Seus recenseados foram quarenta mil e quinhentos.

[[v4-26-19]]

^<<v4-26-19,19>>^ Filhos de Judá: Her e Onã, que morreram na terra de Canaã.

[[v4-26-20]]

^<<v4-26-20,20>>^ Eis os filhos de Judá, classificados por famílias: de Sela, a família dos selitas; de Farés, a família dos faresitas; de Zara, a família dos zaritas.

[[v4-26-21]]

^<<v4-26-21,21>>^ Os filhos de Farés foram: de Hesron, a família dos hesronitas; de Hamul, a família dos hamulitas.

[[v4-26-22]]

^<<v4-26-22,22>>^ Tais são as famílias de Judá; seus recenseados foram setenta e seis mil e quinhentos.

[[v4-26-23]]

^<<v4-26-23,23>>^ Filhos de Issacar, classificados por famílias: de Tola, a família dos tolaítas; de Fua, a família dos fuaítas;

[[v4-26-24]]

^<<v4-26-24,24>>^ de Jasub, a família dos jasubitas; de Semrã, a família dos semranitas.

[[v4-26-25]]

^<<v4-26-25,25>>^ Essas são as famílias de Issacar; seus recenseados foram sessenta e quatro mil e trezentos.

[[v4-26-26]]

^<<v4-26-26,26>>^ Filhos de Zabulon, classificados por famílias: de Sared, a família dos sareditas; de Elon, a família dos elonitas; de Jalel, a família dos jalelitas.

[[v4-26-27]]

^<<v4-26-27,27>>^ Essas são as famílias de Zabulon; seus recenseados foram sessenta mil e quinhentos.

[[v4-26-28]]

^<<v4-26-28,28>>^ Filhos de José, classificados por famílias: Manassés e Efraim.

[[v4-26-29]]

^<<v4-26-29,29>>^ Filhos de Manassés: de Maquir, a família dos maquiritas. Maquir gerou Galaad; de Galaad, a família dos galaaditas.

[[v4-26-30]]

^<<v4-26-30,30>>^ Eis os filhos de Galaad: de Jezer, a família dos jezeritas; de Helec, a família dos helequitas;

[[v4-26-31]]

^<<v4-26-31,31>>^ de Asriel, a família dos asrielitas; de Siquém, a família dos sequemitas;

[[v4-26-32]]

^<<v4-26-32,32>>^ de Semida, a família dos semidaítas; de Héfer, a família dos héferitas.

[[v4-26-33]]

^<<v4-26-33,33>>^ Salafaad, filho de Héfer, não teve filhos, mas muitas filhas. Eis os nomes das filhas de Salafaad: Maala, Noa, Hegla, Melca e Tersa.

[[v4-26-34]]

^<<v4-26-34,34>>^ Essas são as famílias de Manassés; seus recenseados foram cinquenta e dois mil e setecentos.

[[v4-26-35]]

^<<v4-26-35,35>>^ Eis os filhos de Efraim, classificados por famílias: de Sutala, a família dos sutalaítas; de Bequer, a família dos bequeritas; de Teen, a família dos teenitas.

[[v4-26-36]]

^<<v4-26-36,36>>^ Eis os filhos de Sutala: de Herã, a família dos heranitas.

[[v4-26-37]]

^<<v4-26-37,37>>^ Essas são as famílias dos filhos de Efraim; seus recenseados foram trinta e dois mil e quinhentos. Esses são os filhos de José, classificados por famílias.

[[v4-26-38]]

^<<v4-26-38,38>>^ Filhos de Benjamim, classificados por famílias: de Bela, a família dos belaítas; de Asbel, a família dos asbelitas; de Airam, a família dos airamitas;

[[v4-26-39]]

^<<v4-26-39,39>>^ de Sufam, a família dos sufamitas; de Hufam, a família dos hufamitas.

[[v4-26-40]]

^<<v4-26-40,40>>^ Os filhos de Bela foram Arad e Naamã; de Arad, a família dos hereditas; de Naamã, a família dos naamanitas.

[[v4-26-41]]

^<<v4-26-41,41>>^ Tais são os filhos de Benjamim, classificados por famílias; seus recenseados foram em número de quarenta e cinco mil e seiscentos.

[[v4-26-42]]

^<<v4-26-42,42>>^ Eis os filhos de Dã, classificados por famílias: de Suam, a família dos suamitas. Tais são as famílias de Dã, classificadas por famílias.

[[v4-26-43]]

^<<v4-26-43,43>>^ Total das famílias dos suamitas: seus recenseados foram sessenta e quatro mil e quatrocentos.

[[v4-26-44]]

^<<v4-26-44,44>>^ Filhos de Aser, classificados por famílias: de Jemna, a família dos jemnaítas; de Jessui, a família dos jessuítas; de Beria, a família dos briaítas;

[[v4-26-45]]

^<<v4-26-45,45>>^ de Héber, a família dos heberitas; de Melquiel, a família dos melquielitas.

[[v4-26-46]]

^<<v4-26-46,46>>^ O nome da filha de Aser era Sara.

[[v4-26-47]]

^<<v4-26-47,47>>^ Tais são as famílias dos filhos de Aser; seus recenseados foram cinquenta e tres mil e quatrocentos.

[[v4-26-48]]

^<<v4-26-48,48>>^ Filhos de Neftali, classificados por famílias: de Jesiel, a família dos jesielitas; de Guni, a família dos gunitas;

[[v4-26-49]]

^<<v4-26-49,49>>^ de Jeser, a família dos jeseritas; de Selém, a família dos selemitas.

[[v4-26-50]]

^<<v4-26-50,50>>^ Essas são as famílias de Neftali, classificadas por famílias; seus recenseados foram quarenta e cinco mil e quatrocentos.

[[v4-26-51]]

^<<v4-26-51,51>>^ Eis o total dos israelitas recenseados: seiscentos e um mil setecentos e trinta.

[[v4-26-52]]

^<<v4-26-52,52>>^ O Senhor disse a Moisés:

[[v4-26-53]]

^<<v4-26-53,53>>^ “A terra será dividida entre estes, segundo o número de suas pessoas, para que eles a possuam como herança.

[[v4-26-54]]

^<<v4-26-54,54>>^ Aos mais numerosos darás uma parte maior, e aos que forem menos, uma menor; cada um receberá uma parte proporcional ao número dos recenseados.

[[v4-26-55]]

^<<v4-26-55,55>>^ Todavia, é a sorte que decidirá a divisão da terra. Eles receberão a sua parte segundo os nomes das tribos patriarcais.

[[v4-26-56]]

^<<v4-26-56,56>>^ A propriedade será dividida por sorte entre os grupos numerosos e os grupos menores.

[[v4-26-57]]

^<<v4-26-57,57>>^ Eis os levitas recenseados segundo suas famílias: de Gérson, a família dos gersonitas; de Caat, a família dos caatitas; de Merari, a família dos meraritas.

[[v4-26-58]]

^<<v4-26-58,58>>^ Eis as famílias de Levi: a família dos lobnitas, a dos hebronitas, a dos moolitas, a dos musitas, a dos coritas. (Caat gerou Amram,

[[v4-26-59]]

^<<v4-26-59,59>>^ cuja mulher se chamava Jocabed, filha de Levi, nascida no Egito. Ela deu a Amram: Aarão, Moisés e Maria, sua irmã.

[[v4-26-60]]

^<<v4-26-60,60>>^ Aarão teve os filhos: Nadab, Abiú, Eleazar e Itamar.

[[v4-26-61]]

^<<v4-26-61,61>>^ Nadab e Abiú morreram quando apresentaram diante do Senhor um fogo estranho.)

[[v4-26-62]]

^<<v4-26-62,62>>^ Recenseados os levitas, todos os varões da idade de um mês para cima somaram vinte e três mil. Não foram contados no recenseamento dos israelitas, porque não se lhes havia destinado nenhum patrimônio no meio deles.

[[v4-26-63]]

^<<v4-26-63,63>>^ Tal é o recenseamento dos israelitas que fizeram Moisés e o sacerdote Eleazar nas planícies de Moab, às margens do Jordão, perto de Jericó.

[[v4-26-64]]

^<<v4-26-64,64>>^ Não se achou entre eles nenhum daqueles que tinham sido recenseados antes por Moisés e Aarão, no deserto do Sinai,

[[v4-26-65]]

^<<v4-26-65,65>>^ porque o Senhor dissera deles: “Morrerão no deserto”. Não ficou nenhum deles, exceto Caleb, filho de Jefoné, e Josué, filho de Nun.

'''

xref:004-numeros/004-numeros-025.adoc#v4-25-0[&#60; Capítulo Anterior] | <<v4-26-0,Topo>> | xref:004-numeros/004-numeros-027.adoc#v4-27-0[Próximo Capítulo &#62;]