include::./index.adoc[]

[[v4-11-0]]
=== Números, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 11 de Números apresenta a queixa do povo de Israel no deserto, que se cansaram de comer maná e desejam ter carne para comer. Moisés reclama com Deus sobre o peso de liderar o povo e pede ajuda para governar. Deus então envia um vento que traz codornizes ao acampamento e permite que setenta anciãos ajudem Moisés a governar. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Gênesis 18:14: "Porventura há coisa demasiadamente difícil ao Senhor? Na hora determinada tornarei a ti, por este tempo da vida, e Sara terá um filho." Assim como Deus proveu carne para o povo de Israel no deserto, Ele também cumpriu sua promessa de dar um filho a Sara, mesmo quando ela era velha demais para ter filhos.
* Salmos 78:18: "E tentaram a Deus nos seus corações, pedindo comida segundo o seu apetite." Este versículo se relaciona com a queixa do povo de Israel no deserto, que desejavam ter carne para comer, mesmo depois de Deus ter providenciado maná para eles.
* Êxodo 18:18: "Certamente desfalecerás, assim tu como este povo que está contigo; porque este negócio é mui difícil para ti; tu só não o podes fazer." Assim como Moisés se sentiu sobrecarregado com a tarefa de liderar o povo de Israel, Jetro, seu sogro, também reconheceu que ele precisava de ajuda para governar o povo.
* Deuteronômio 1:9-13: "E naqueles dias eu disse a vocês: 'Não posso, sozinho, carregar todo o peso deste povo; o fardo é pesado demais para mim. Como posso eu, sozinho, enfrentar suas disputas e problemas? Escolham homens sábios, criteriosos e experientes de cada uma de suas tribos para colocar como líderes sobre vocês.' " Este versículo também se relaciona com o pedido de Moisés para ter ajuda na liderança do povo de Israel.
* Mateus 11:28-30: "Venham a mim, todos os que estão cansados e sobrecarregados, e eu os aliviarei. Tomem sobre vocês o meu jugo e aprendam de mim, pois sou manso e humilde de coração, e vocês encontrarão descanso para as suas almas. Pois o meu jugo é suave e o meu fardo é leve." Este versículo se relaciona com o peso que Moisés sentiu na liderança do povo de Israel e a ajuda que Deus providenciou através dos setenta anciãos e do vento que trouxe codornizes. Ele também é uma promessa de descanso e alívio para todos aqueles que se sentem sobrecarregados e cansados.
****

[[v4-11-1]]

^<<v4-11-1,1>>^ O povo pôs-se a murmurar amargamente aos ouvidos do Senhor. O Senhor, ouvindo isso, irou-se: o fogo do Senhor acendeu-se entre eles e devorou a extremidade do acampamento.

[[v4-11-2]]

^<<v4-11-2,2>>^ O povo clamou a Moisés; Moisés orou ao Senhor e o fogo extinguiu-se.

[[v4-11-3]]

^<<v4-11-3,3>>^ Deu-se àquele lugar o nome de Tabeera, porque o fogo do Senhor se tinha acendido no meio deles.

[[v4-11-4]]

^<<v4-11-4,4>>^ A população que estava no meio de Israel foi atacada por um desejo desordenado, de modo que até os israelitas recomeçaram a gemer: “Quem nos dará carne para comer?” – diziam eles –.

[[v4-11-5]]

^<<v4-11-5,5>>^ “Lembramo-nos dos peixes que comíamos de graça no Egito, dos pepinos, melões, verduras, cebolas e alhos.

[[v4-11-6]]

^<<v4-11-6,6>>^ Agora nossa alma está seca. Não há mais nada, e só vemos maná diante de nossos olhos.”

[[v4-11-7]]

^<<v4-11-7,7>>^ O maná assemelhava-se ao grão de coentro e parecia-se com o bdélio.

[[v4-11-8]]

^<<v4-11-8,8>>^ O povo dispersava-se para colhê-lo; moía-o com a mó ou esmagava-o num pilão, cozia-o numa panela e fazia bolos com ele, os quais tinham o sabor de um bolo amassado com óleo.

[[v4-11-9]]

^<<v4-11-9,9>>^ Enquanto de noite caía o orvalho no campo, caía também com ele o maná.

[[v4-11-10]]

^<<v4-11-10,10>>^ Ouviu Moisés o povo que chorava, agrupado por famílias, cada uma à entrada de sua tenda. A cólera do Senhor acendeu-se com violência. Moisés entristeceu-se.

[[v4-11-11]]

^<<v4-11-11,11>>^ E disse ao Senhor: “Por que afligis vosso servo? Por que não acho eu favor a vossos olhos, vós que me impusestes a carga de todo esse povo?

[[v4-11-12]]

^<<v4-11-12,12>>^ Porventura fui eu que concebi esse povo? Ou acaso fui eu que o dei à luz, para me dizerdes: leva-o em teu seio como a ama costuma levar o bebê, para a terra que, com juramento, prometi aos seus pais?

[[v4-11-13]]

^<<v4-11-13,13>>^ Onde encontrarei carne para dar a todo esse povo que vem chorar perto de mim, dizendo: ‘Dá-nos carne para comer?’.

[[v4-11-14]]

^<<v4-11-14,14>>^ Eu sozinho não posso suportar todo esse povo; ele é pesado demais para mim.

[[v4-11-15]]

^<<v4-11-15,15>>^ Em lugar de tratar-me assim, rogo-vos que antes me façais morrer, se achei agrado a vossos olhos, a fim de que eu não veja a minha infelicidade!”.

[[v4-11-16]]

^<<v4-11-16,16>>^ O Senhor respondeu a Moisés: “Junta-me setenta homens entre os anciãos de Israel, que sabes serem os anciãos do povo e tenham autoridade sobre ele. Conduze-os à tenda de reunião, onde estarão contigo.

[[v4-11-17]]

^<<v4-11-17,17>>^ Então descerei e ali falarei contigo. Tomarei do espírito que está em ti e o derramarei sobre eles, para que possam levar contigo a carga do povo e não estejas mais sozinho.

[[v4-11-18]]

^<<v4-11-18,18>>^ Dirás ao povo: Santificai-vos para amanhã, e tereis carne para comer, pois chorastes aos ouvidos do Eterno, dizendo: Quem nos dará carne para comer? Estávamos tão bem no Egito!... O Senhor vos dará carne, e comereis.^&#42;1^

[[v4-11-19]]

^<<v4-11-19,19>>^ E comereis não só um dia, nem dois, nem cinco, nem dez, nem vinte,

[[v4-11-20]]

^<<v4-11-20,20>>^ mas durante um mês inteiro, até que ela vos saia pelas narinas e vos cause nojo: porque rejeitastes o Senhor que está no meio de vós e dissestes-lhe chorando: Por que saímos nós do Egito?”.

[[v4-11-21]]

^<<v4-11-21,21>>^ Moisés disse: “Este povo, no meio do qual estou, conta seiscentos mil homens de pé, e dizeis que lhes dareis carne para que comam um mês inteiro!

[[v4-11-22]]

^<<v4-11-22,22>>^ Porventura se matará tanta quantidade de ovelhas e bois até que tenham bastante? Ou juntarão todos os peixes do mar para fartá-los?”.

[[v4-11-23]]

^<<v4-11-23,23>>^ O Senhor respondeu a Moisés: “Acaso será impotente a mão do Senhor? Verás sem demora se se fará ou não o que eu te disse”.

[[v4-11-24]]

^<<v4-11-24,24>>^ Moisés saiu e referiu ao povo as palavras do Senhor. Reuniu setenta homens dos anciãos do povo e os colocou em volta da tenda.

[[v4-11-25]]

^<<v4-11-25,25>>^ O Senhor desceu na nuvem e falou a Moisés. Tomou uma parte do espírito que o animava e a pôs sobre os setenta anciãos. Apenas repousara o espírito sobre eles, começaram a profetizar; mas não continuaram.^&#42;1^

[[v4-11-26]]

^<<v4-11-26,26>>^ Dois homens tinham ficado no acampamento: um chamava-se Eldad e o outro, Medad, e o espírito repousou também sobre eles, pois tinham sido alistados, mas não tinham ido à tenda; e profetizaram no acampamento.

[[v4-11-27]]

^<<v4-11-27,27>>^ Um jovem correu a dar notícias a Moisés: “Eldad e Medad – disse ele – profetizam no acampamento”.

[[v4-11-28]]

^<<v4-11-28,28>>^ Então Josué, filho de Nun, servo de Moisés desde a sua juventude, tomou a palavra: “Moisés – disse ele – meu senhor, impede-os”.

[[v4-11-29]]

^<<v4-11-29,29>>^ Moisés, porém, respondeu: “Por que és tão zeloso por mim? Prouvera a Deus que todo o povo do Senhor profetizasse, e que o Senhor lhe desse o seu espírito!”.

[[v4-11-30]]

^<<v4-11-30,30>>^ E Moisés retirou-se do acampamento com os anciãos de Israel.

[[v4-11-31]]

^<<v4-11-31,31>>^ Um vento mandado pelo Senhor, vindo das bandas do mar, trouxe consigo codornizes e derramou-as sobre o acampamento, em uma extensão de cerca de um dia de caminho para ambos os lados em volta do acampamento; e cobriam o solo, cerca de dois côvados de alto sobre a superfície da terra.

[[v4-11-32]]

^<<v4-11-32,32>>^ Levantou-se então o povo, e ajuntou durante todo aquele dia, toda a noite e todo o dia seguinte tantas codornizes, que aquele que menos ajuntou conseguiu encher dez homeres. E estenderam-nas, para si mesmos, em toda a volta do acampamento.^&#42;1^

[[v4-11-33]]

^<<v4-11-33,33>>^ Ainda a carne estava nos seus dentes, e ainda não estava mastigada, quando a cólera do Senhor se inflamou contra o povo e o Senhor feriu o povo com um grande flagelo.

[[v4-11-34]]

^<<v4-11-34,34>>^ Chamou-se àquele lugar Quibrot-Hataava (sepulcros da concupiscência, porque ali sepultou-se o povo que se deixara dominar pelo desejo desordenado.^&#42;1^

[[v4-11-35]]

^<<v4-11-35,35>>^ De Quibrot-Hataava, partiu o povo para Haserot, onde se deteve.

'''

xref:004-numeros/004-numeros-010.adoc#v4-10-0[&#60; Capítulo Anterior] | <<v4-11-0,Topo>> | xref:004-numeros/004-numeros-012.adoc#v4-12-0[Próximo Capítulo &#62;]