include::./index.adoc[]

[[v4-18-0]]
=== Números, 18
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 18 de Números é dedicado à tribo de Levi e seu papel como sacerdotes do tabernáculo. Os versículos a seguir estão relacionados aos temas tratados no capítulo:
* Êxodo 29:9: "E cingirás o cinto de ouro puro, e porás o diadema de santidade na sua cabeça." Este versículo descreve a preparação dos sacerdotes para o serviço no tabernáculo, incluindo a vestimenta e o diadema que deveriam usar. Essa passagem está relacionada a Números 18, que trata da designação dos levitas como sacerdotes.
* Êxodo 30:7-8: "E Arão queimará incenso cheiroso sobre ele; todas as manhãs, quando a lâmpada for arrumada, o queimará. E, quando acenderes as lâmpadas à tarde, queimará incenso; será incenso contínuo perante o Senhor pelas vossas gerações." Este versículo descreve a importância do incenso no serviço do tabernáculo. Em Números 18, os levitas foram designados para cuidar do incenso e do altar.
* Números 18:20: "Disse mais o Senhor a Arão: Tu não terás herança na sua terra, nem parte alguma entre eles; eu sou a tua parte e a tua herança no meio dos filhos de Israel." Este versículo destaca a diferença entre a herança dos levitas e a dos demais israelitas. Enquanto as outras tribos receberam terras como herança, os levitas foram separados para servir no tabernáculo e receberam o Senhor como sua herança.
* Números 18:26: "Falarás aos levitas, e lhes dirás: Quando receberdes dos filhos de Israel os dízimos que deles vos tenho dado por vossa herança, deles oferecereis ao Senhor a oferta alçada, os dízimos dos dízimos." Este versículo descreve como os levitas deveriam usar os dízimos que recebiam dos israelitas. Eles deveriam oferecer uma oferta alçada ao Senhor com uma parte desses dízimos.
* Deuteronômio 18:1-2: "Não haverá para os sacerdotes levitas, toda a tribo de Levi, parte nem herança com Israel; das ofertas queimadas do Senhor, e da sua herança, comerão. Não terão, pois, herança entre seus irmãos; o Senhor é a sua herança, como lhes tem dito." Este versículo repete a ideia de que os levitas não teriam uma herança de terra como as outras tribos de Israel. Em vez disso, eles receberiam as ofertas queimadas do Senhor como sua porção.
****

[[v4-18-1]]

^<<v4-18-1,1>>^ O Senhor disse a Aarão: “Tu, teus filhos e tua família contigo, levareis a responsabilidade dos pecados cometidos no santuário. Tu e teus filhos contigo levareis a responsabilidade dos pecados cometidos em vosso sacerdócio.^&#42;1^

[[v4-18-2]]

^<<v4-18-2,2>>^ Farás aproximarem-se do santuário contigo os teus irmãos, a tribo de Levi e a tribo de teu pai, para que se juntem a ti e te ajudem quando estiveres com teus filhos diante da tenda do testemunho.

[[v4-18-3]]

^<<v4-18-3,3>>^ Eles farão o serviço que te é devido e o serviço da tenda, mas não se aproximarão dos objetos sagrados, nem do altar, para que não morram, e vós juntamente com eles.

[[v4-18-4]]

^<<v4-18-4,4>>^ Serão teus auxiliares e terão a seu cuidado a tenda de reunião para fazer todo o seu serviço. Nenhum estrangeiro se aproximará de vós.

[[v4-18-5]]

^<<v4-18-5,5>>^ Fareis o serviço do santuário e do altar, para que não venha de novo a cólera ferir os israelitas.

[[v4-18-6]]

^<<v4-18-6,6>>^ Fui eu que escolhi os levitas, vossos irmãos, entre os israelitas. Dados ao Senhor, vos são de novo entregues para fazerem o serviço da tenda de reunião.

[[v4-18-7]]

^<<v4-18-7,7>>^ Tu, porém, e teus filhos contigo, exercereis o vosso sacerdócio no altar e atrás do véu: esse é o vosso serviço. O sacerdócio é um dom que eu vos faço; o estrangeiro que se aproximar será morto”.

[[v4-18-8]]

^<<v4-18-8,8>>^ O Senhor disse a Aarão: “Dou-te o que se reserva de tudo o que é separado para mim, dentre todas as coisas consagradas dos israelitas. Dou isso a ti e a teus filhos em virtude de uma lei perpétua, por causa da unção que recebeste.

[[v4-18-9]]

^<<v4-18-9,9>>^ Eis o que receberás das coisas santíssimas que não são queimadas; todas as suas ofertas, oblações, sacrifícios pelo pecado, sacrifícios de reparação; todas essas coisas santíssimas serão para ti e teus filhos.

[[v4-18-10]]

^<<v4-18-10,10>>^ Tu as comerás em lugar santíssimo. Todo varão poderá comer delas; e serão para ti coisas sagradas.

[[v4-18-11]]

^<<v4-18-11,11>>^ Eis ainda o que será teu: o que é tomado dentre os dons, dentre toda oferta agitada dos israelitas. Eu o dou a ti, a teus filhos e a tuas filhas em virtude de uma lei perpétua. Todo membro de tua família que estiver puro comerá dessas coisas.

[[v4-18-12]]

^<<v4-18-12,12>>^ Dou-te também as primícias que os israelitas oferecerem ao Senhor: o melhor de seu óleo, de seu vinho e de seu trigo.

[[v4-18-13]]

^<<v4-18-13,13>>^ Serão para ti as primícias dos produtos da terra que trouxerem ao Senhor. Todo membro de tua família que estiver puro poderá comer delas.

[[v4-18-14]]

^<<v4-18-14,14>>^ Tudo o que for votado ao interdito em Israel será teu.

[[v4-18-15]]

^<<v4-18-15,15>>^ Será teu igualmente todo primogênito de toda criatura, homem ou animal, que os israelitas oferecerem ao Senhor; ordenarás, não obstante, que se resgate o primogênito do homem, assim como os primogênitos dos animais impuros.

[[v4-18-16]]

^<<v4-18-16,16>>^ O seu resgate será feito logo que ele tiver um mês, segundo tua estimação, à razão de cinco siclos de prata (conforme o siclo do santuário, que vale vinte gueras).

[[v4-18-17]]

^<<v4-18-17,17>>^ Mas não farás resgatar o primogênito da vaca, nem o da ovelha, nem o da cabra: estes são coisas sagradas. Derramarás o seu sangue sobre o altar e queimarás a sua gordura em sacrifício feito pelo fogo, de agradável odor ao Senhor.

[[v4-18-18]]

^<<v4-18-18,18>>^ Sua carne será para ti da mesma forma que o peito agitado e a perna direita.

[[v4-18-19]]

^<<v4-18-19,19>>^ Tudo o que é tomado das coisas santas que os israelitas oferecem ao Senhor, dou-o a ti, a teus filhos e a tuas filhas em virtude de uma lei perpétua. Essa é uma aliança de sal, que vale perpetuamente diante do Senhor, para ti e para toda a tua posteridade contigo”.^&#42;1^

[[v4-18-20]]

^<<v4-18-20,20>>^ O Senhor disse a Aarão: “Não possuirás nada na terra deles, e não terás parte alguma entre eles. Eu sou a tua parte e a tua herança no meio dos israelitas.

[[v4-18-21]]

^<<v4-18-21,21>>^ Quanto aos levitas, dou-lhes como patrimônio todos os dízimos de Israel pelo serviço que prestam na tenda de reunião.

[[v4-18-22]]

^<<v4-18-22,22>>^ Os israelitas não se aproximarão mais da tenda de reunião, para que não caia sobre eles o peso de um pecado que lhes cause a morte.

[[v4-18-23]]

^<<v4-18-23,23>>^ São os levitas que farão o trabalho na tenda de reunião e que levarão a responsabilidade de suas faltas: essa é uma lei perpétua para todos os vossos descendentes. Eles não terão herança no meio dos israelitas,

[[v4-18-24]]

^<<v4-18-24,24>>^ porque lhes dou como herança os dízimos que os israelitas tomarem para o Senhor. Eis por que declaro que eles não possuirão herança alguma no meio dos israelitas”.

[[v4-18-25]]

^<<v4-18-25,25>>^ O Senhor disse a Moisés:

[[v4-18-26]]

^<<v4-18-26,26>>^ “Dirás aos levitas: Quando receberdes dos israelitas o dízimo que vos dei de seus bens por vossa herança, tomareis dele uma oferta para o Senhor: o dízimo do dízimo.

[[v4-18-27]]

^<<v4-18-27,27>>^ Essa reserva será como o trigo tomado da eira e como o vinho tomado do lagar.

[[v4-18-28]]

^<<v4-18-28,28>>^ Desse modo, fareis também vós uma reserva devida ao Senhor de todos os dízimos que receberdes dos israelitas, e essa oferta reservada para o Senhor, vós a entregareis ao sacerdote Aarão.

[[v4-18-29]]

^<<v4-18-29,29>>^ De todos os dons que receberdes, separareis uma parte para o Senhor, isto é, tomareis a porção consagrada do que houver de melhor em vossos dízimos.

[[v4-18-30]]

^<<v4-18-30,30>>^ Dize-lhes também: Quando tiverdes separado o melhor do dízimo, o resto será para os levitas como o produto da eira ou do lagar.

[[v4-18-31]]

^<<v4-18-31,31>>^ Podereis comê-lo com vossa família, porque é o vosso salário pelo serviço que prestais na tenda de reunião.

[[v4-18-32]]

^<<v4-18-32,32>>^ Não cometereis pecado algum por causa disso, e não profanareis as santas ofertas dos israelitas, quando tiverdes separado o melhor do dízimo, para que não morrais”.

'''

xref:004-numeros/004-numeros-017.adoc#v4-17-0[&#60; Capítulo Anterior] | <<v4-18-0,Topo>> | xref:004-numeros/004-numeros-019.adoc#v4-19-0[Próximo Capítulo &#62;]