include::./index.adoc[]

[[v4-15-0]]
=== Números, 15
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 15 de Números trata sobre a oferta de sacrifícios e ofertas voluntárias que deveriam ser apresentadas ao Senhor, além de instruções sobre a observância dos mandamentos de Deus. A seguir, estão cinco versículos relacionados com os temas abordados em Números 15, em ordem de proximidade com o capítulo:
* Levítico 22:17-18: "E falou o SENHOR a Moisés, dizendo: Fala a Arão e a seus filhos, e a todos os filhos de Israel, e dize-lhes: Qualquer homem da casa de Israel, ou dos estrangeiros em Israel, que oferecer a sua oferta, seja dos seus votos, ou das suas ofertas voluntárias, que oferecem ao SENHOR em holocausto;" Este versículo fala sobre a oferta de sacrifícios que deveriam ser apresentados ao Senhor, o que é semelhante ao que é abordado em Números 15.
* Levítico 23:15-16: "E desde o dia seguinte ao sábado, desde o dia em que trouxerdes o molho da oferta movida, sete semanas inteiras serão. Até ao dia seguinte ao sétimo sábado, contareis cinquenta dias; então, oferecereis nova oferta de alimentos ao SENHOR." Esse versículo fala sobre a observância dos mandamentos de Deus, o que é abordado em Números 15.
* Deuteronômio 26:13: "E dirás diante do Senhor teu Deus: Tirei da minha casa as coisas consagradas e as dei também ao levita, ao estrangeiro, ao órfão e à viúva, conforme a todos os teus mandamentos que me ordenaste; não transgredi os teus mandamentos, nem deles me esqueci." Esse versículo fala sobre a importância de seguir os mandamentos do Senhor com relação às ofertas e sacrifícios, e também mostra a responsabilidade do povo de Israel em cuidar dos menos favorecidos.
* Levítico 23:10: "Fala aos filhos de Israel, e dize-lhes: Quando houverdes entrado na terra que vos hei de dar, e fizerdes a sua colheita, então trareis um molho das primícias da vossa sega ao sacerdote;" Esse versículo faz referência à oferta das primícias, que deveria ser apresentada ao Senhor como uma forma de agradecimento pelas bênçãos recebidas.
* Deuteronômio 14:22-23: "Certamente darás os dízimos de todo o fruto das tuas sementes, que cada ano se recolher do campo. E perante o Senhor teu Deus, no lugar que escolher para ali fazer habitar o seu nome, comerás os dízimos do teu grão, do teu mosto e do teu azeite, e os primogênitos das tuas vacas e das tuas ovelhas; para que aprendas a temer ao Senhor teu Deus todos os dias." Esse versículo fala sobre a obrigação do povo de Israel em dar os dízimos como forma de contribuição para o sustento da tribo de Levi, que era responsável pelo serviço religioso.
****

[[v4-15-1]]

^<<v4-15-1,1>>^ O Senhor disse a Moisés: “Dize aos israelitas o seguinte:

[[v4-15-2]]

^<<v4-15-2,2>>^ Quando entrardes na terra de vossa habitação, que eu vos hei de dar,

[[v4-15-3]]

^<<v4-15-3,3>>^ e oferecerdes ao Senhor algum sacrifício pelo fogo, seja holocausto, seja um simples sacrifício, quer em cumprimento de um voto, quer como oferta espontânea, ou por ocasião de uma festa, para apresentar uma oferta de agradável odor ao Senhor, com vossos bois ou vossas ovelhas,

[[v4-15-4]]

^<<v4-15-4,4>>^ aquele que fizer essa oferta apresentará ao Senhor em oblação um décimo de flor de farinha amassada com um quarto de hin de óleo.

[[v4-15-5]]

^<<v4-15-5,5>>^ E, para a libação, acrescentará um quarto de hin de vinho ao holocausto ou ao sacrifício de cada cordeiro.

[[v4-15-6]]

^<<v4-15-6,6>>^ Para um carneiro oferecerás dois décimos de flor de farinha amassada com um terço de hin de óleo,

[[v4-15-7]]

^<<v4-15-7,7>>^ ajuntando uma libação de um terço de hin de vinho, como oferta de agradável odor ao Senhor.

[[v4-15-8]]

^<<v4-15-8,8>>^ Quando ofereceres um touro em holocausto ou em sacrifício, para o cumprimento de um voto ou em sacrifício pacífico ao Senhor,

[[v4-15-9]]

^<<v4-15-9,9>>^ darás com o touro uma oblação de três décimos de flor de farinha amassada com meio hin de óleo,

[[v4-15-10]]

^<<v4-15-10,10>>^ ajuntando uma libação de meio-hin de vinho; isso é um sacrifício feito pelo fogo, de agradável odor ao Senhor.

[[v4-15-11]]

^<<v4-15-11,11>>^ O mesmo se fará para cada boi, cada carneiro, cordeiro ou cabrito.

[[v4-15-12]]

^<<v4-15-12,12>>^ Assim fareis para cada um desses sacrifícios, seja qual for o número das vítimas que oferecerdes.

[[v4-15-13]]

^<<v4-15-13,13>>^ Todos os nativos procederão do mesmo modo, quando oferecerem um sacrifício pelo fogo de agradável odor ao Senhor.

[[v4-15-14]]

^<<v4-15-14,14>>^ Se um estrangeiro que habita no meio de vós, ou qualquer outro homem que venha mais tarde a se estabelecer entre vós, oferecer um sacrifício pelo fogo de agradável odor ao Senhor, fará o mesmo que vós.

[[v4-15-15]]

^<<v4-15-15,15>>^ Só haverá uma lei, a mesma para vós, para a assembleia e para o estrangeiro que habita no meio de vós. Esta é uma lei perpétua para vossos descendentes: diante do Senhor será a mesma coisa tanto para vós como para o estrangeiro.

[[v4-15-16]]

^<<v4-15-16,16>>^ Haverá uma só lei e uma só regra para vós e para o estrangeiro que habita no meio de vós”.

[[v4-15-17]]

^<<v4-15-17,17>>^ O Senhor disse a Moisés:

[[v4-15-18]]

^<<v4-15-18,18>>^ “Dize aos israelitas o seguinte:

[[v4-15-19]]

^<<v4-15-19,19>>^ Quando chegardes à terra para onde vos levo, e comerdes o pão daquela terra, reservareis uma oferta para o Senhor.

[[v4-15-20]]

^<<v4-15-20,20>>^ Essa oferta será um bolo feito das primícias de vossa farinha: vós a separareis como se separa a oferta da eira.

[[v4-15-21]]

^<<v4-15-21,21>>^ Como primícias de vossa farinha, vós e vossos descendentes separareis uma oferta para o Senhor”.

[[v4-15-22]]

^<<v4-15-22,22>>^ “Se pecardes involuntariamente, deixando de observar um desses mandamentos que o Senhor deu a Moisés, –

[[v4-15-23]]

^<<v4-15-23,23>>^ tudo o que por ele vos ordenou desde o dia em que o Senhor vos deu os seus mandamentos, e daí por diante em vossas gerações futuras –

[[v4-15-24]]

^<<v4-15-24,24>>^ se alguém pecar involuntariamente, e a assembleia não o tiver notado, toda a assembleia oferecerá em holocausto de agradável odor ao Senhor um novilho, com sua oblação e sua libação, segundo o rito prescrito, bem como um bode em sacrifício pelo pecado.

[[v4-15-25]]

^<<v4-15-25,25>>^ O sacerdote fará a expiação por toda a assembleia dos israelitas, e lhes será perdoado, porque é um pecado involuntário, e apresentaram sua oferta ao Senhor, um sacrifício feito pelo fogo e seu sacrifício pelo pecado para reparar o seu erro.

[[v4-15-26]]

^<<v4-15-26,26>>^ Será perdoado a toda a assembleia dos filhos de Israel, e ao estrangeiro que mora no meio deles, porque é uma culpa que todo o povo cometeu involuntariamente.

[[v4-15-27]]

^<<v4-15-27,27>>^ Se for uma só pessoa que pecou involuntariamente, oferecerá uma cabra de um ano em sacrifício pelo pecado.

[[v4-15-28]]

^<<v4-15-28,28>>^ O sacerdote fará a expiação diante do Senhor por essa pessoa que pecou involuntariamente; feita a expiação, será perdoada.

[[v4-15-29]]

^<<v4-15-29,29>>^ Tereis uma só lei para aquele que pecar involuntariamente, quer sejam israelitas, quer sejam estrangeiros que habitem no meio deles.

[[v4-15-30]]

^<<v4-15-30,30>>^ Aquele, porém, que pecar conscientemente, ultraja o Senhor; ele será cortado do meio de seu povo,^&#42;1^

[[v4-15-31]]

^<<v4-15-31,31>>^ porque desprezou a palavra do Senhor e violou o seu preceito; será cortado e levará o peso de sua iniquidade”.

[[v4-15-32]]

^<<v4-15-32,32>>^ Ora, aconteceu que, estando os israelitas no deserto, encontraram um homem ajuntando lenha num dia de sábado.

[[v4-15-33]]

^<<v4-15-33,33>>^ Os que o acharam apanhando lenha, levaram-no a Moisés e a Aarão, diante de toda a assembleia.

[[v4-15-34]]

^<<v4-15-34,34>>^ Eles colocaram-no em guarda, pois não estava ainda determinado o que se lhe devia fazer.

[[v4-15-35]]

^<<v4-15-35,35>>^ O Senhor disse a Moisés: “Que esse homem seja punido de morte, e a assembleia o apedreje fora do acampamento”.

[[v4-15-36]]

^<<v4-15-36,36>>^ Levaram-no para fora do acampamento e toda a assembleia o apedrejou, e ele morreu, como o Senhor tinha ordenado a Moisés.

[[v4-15-37]]

^<<v4-15-37,37>>^ O Senhor disse a Moisés:

[[v4-15-38]]

^<<v4-15-38,38>>^ “Dize aos israelitas que façam para eles e seus descendentes borlas nas extremidades de suas vestes, pondo na borla de cada canto um cordão de púrpura violeta.^&#42;1^

[[v4-15-39]]

^<<v4-15-39,39>>^ Fareis essas borlas para que, vendo-as, vos recordeis de todos os mandamentos do Senhor, e os pratiqueis, e não vos deixeis levar pelos apetites de vosso coração e de vossos olhos que vos arrastam à infidelidade.

[[v4-15-40]]

^<<v4-15-40,40>>^ Desse modo, vós vos lembrareis de todos os meus mandamentos, e os praticareis, e sereis consagrados ao vosso Deus.

[[v4-15-41]]

^<<v4-15-41,41>>^ Eu sou o Senhor, vosso Deus, que vos tirei do Egito para ser o vosso Deus. Eu sou o Senhor, vosso Deus”.

'''

xref:004-numeros/004-numeros-014.adoc#v4-14-0[&#60; Capítulo Anterior] | <<v4-15-0,Topo>> | xref:004-numeros/004-numeros-016.adoc#v4-16-0[Próximo Capítulo &#62;]