include::./index.adoc[]

[[v45-4-0]]
=== Zacarias, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 4 de Zacarias apresenta uma visão que o profeta teve de um candelabro de ouro e duas oliveiras, simbolizando a provisão contínua de Deus para o povo e a unção do Espírito Santo sobre o governador Zorobabel. Além disso, o capítulo enfatiza a importância de depender da força de Deus e não da nossa própria, para cumprir a Sua vontade. A seguir, estão cinco versículos relacionados com os temas abordados em Zacarias 4:
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Este versículo nos lembra da importância de confiar em Deus e depender da Sua força em vez da nossa.
* Filipenses 4:13: "Posso todas as coisas naquele que me fortalece." Assim como o candelabro em Zacarias 4 dependia da provisão de azeite das oliveiras, nós também devemos depender de Deus para receber a força necessária para cumprir a Sua vontade.
* Efésios 6:10: "No demais, irmãos meus, fortalecei-vos no Senhor e na força do seu poder." Este versículo enfatiza a importância de buscar a força em Deus, especialmente em meio às batalhas espirituais que enfrentamos.
* 2 Coríntios 12:9: "E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. De boa vontade, pois, me gloriarei nas minhas fraquezas, para que em mim habite o poder de Cristo." Este versículo nos lembra que a nossa fraqueza pode ser uma oportunidade para experimentar a força de Deus.
* Romanos 12:2: "E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável, e perfeita vontade de Deus." Assim como o candelabro em Zacarias 4 foi chamado a cumprir um propósito específico, também somos chamados a cumprir a vontade de Deus em nossas vidas, e a transformação do nosso entendimento é necessária para isso.
****

[[v45-4-1]]

^<<v45-4-1,1>>^ O anjo voltou e despertou-me, como a um homem a quem tiram do sono.

[[v45-4-2]]

^<<v45-4-2,2>>^ E perguntou-me: “Que vês?”. “Vejo um candelabro todo de ouro” – respondi – “que tem um reservatório no alto, sete lâmpadas em redor e ainda sete bicos para as lâmpadas colocadas em cima do candelabro.

[[v45-4-3]]

^<<v45-4-3,3>>^ Junto deste, duas oliveiras colocadas de um e de outro lado do reservatório.”

[[v45-4-4]]

^<<v45-4-4,4>>^ Perguntei de novo ao porta-voz: “Meu Senhor, que coisas são estas?”.

[[v45-4-5]]

^<<v45-4-5,5>>^ Ele respondeu: “Não sabes o que isso significa?”. Respondi: “Não, meu Senhor”.

[[v45-4-6]]

^<<v45-4-6,6>>^ Então, ele explicou: “Este é o oráculo do Senhor a respeito de Zorobabel: não pelo poder, nem pela violência, mas sim pelo meu Espírito é que ele cumprirá a sua missão – oráculo do Senhor.^&#42;1^

[[v45-4-7]]

^<<v45-4-7,7>>^ Quem és tu, ó grande monte? Diante de Zorobabel não passas de uma planície! Ele porá a pedra de remate em meio de aclamações: Graças, graças a ela!”.

[[v45-4-8]]

^<<v45-4-8,8>>^ A palavra do Senhor foi-me dirigida nestes termos:

[[v45-4-9]]

^<<v45-4-9,9>>^ “As mãos de Zorobabel lançaram os fundamentos desta casa; suas mãos levarão a bom termo a sua construção. Assim saberás que fui enviado a vós pelo Senhor dos exércitos.

[[v45-4-10]]

^<<v45-4-10,10>>^ Por que, pois, desprezar esses humildes começos? Eles se alegrarão quando virem o fio de prumo na mão de Zorobabel”. Então, ele me explicou: “Estes sete olhos são os olhos do Senhor, que discorrem por toda a terra”.

[[v45-4-11]]

^<<v45-4-11,11>>^ Perguntei-lhe ainda: “Que significam as duas oliveiras que estão de um e de outro lado do candelabro?”.

[[v45-4-12]]

^<<v45-4-12,12>>^ E interroguei de novo: “Que significam estes dois ramos de oliveira, que deixam correr o ouro por dois tubos de ouro?”.^&#42;1^

[[v45-4-13]]

^<<v45-4-13,13>>^ “Não sabes o que isto significa?” “Não, meu Senhor.”

[[v45-4-14]]

^<<v45-4-14,14>>^ Ele explicou: “São os dois ungidos do Senhor que assistem diante do Senhor de toda a terra.”

'''

xref:045-zacarias/045-zacarias-003.adoc#v45-3-0[&#60; Capítulo Anterior] | <<v45-4-0,Topo>> | xref:045-zacarias/045-zacarias-005.adoc#v45-5-0[Próximo Capítulo &#62;]