include::./index.adoc[]

[[v45-14-0]]
=== Zacarias, 14
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 14 de Zacarias trata da vinda do Senhor para julgar todas as nações da terra e estabelecer seu reino na Terra. Será um dia de trevas e de grande terremoto, mas também será um dia de esperança para os que crêem no Senhor. Aqui estão cinco versículos relacionados com os temas abordados em Zacarias 14:
* Isaías 2:4: "Ele julgará entre as nações e resolverá as disputas de muitos povos. De suas espadas, forjarão arados e de suas lanças, foices. Nenhuma nação levantará a espada contra a outra, nem aprenderão mais a guerrear." Este verso fala sobre o julgamento do Senhor sobre as nações da terra, o que é um tema importante em Zacarias 14. A paz que ele trará também é mencionada, indicando a estabilização do reinado de Deus.
* Salmos 97:5: "As montanhas se derretem como cera diante do Senhor, diante do Soberano de toda a terra." Este verso fala sobre a presença majestosa do Senhor e sua capacidade de destruir tudo o que se opõe a ele, o que é relevante para o grande terremoto e a escuridão mencionados em Zacarias 14.
* Malaquias 3:2: "Mas quem suportará o dia da sua vinda? Quem ficará em pé quando ele aparecer? Porque ele será como o fogo do ourives e como o sabão dos lavandeiros." Este verso descreve a vinda do Senhor e a intensidade do julgamento que ele trará, o que está em sintonia com os temas de Zacarias 14.
* Mateus 24:29: "Imediatamente após a tribulação daqueles dias, 'o sol escurecerá, a lua não dará a sua luz, as estrelas cairão do céu e os poderes dos céus serão abalados'". Este verso é uma referência direta a Zacarias 14:6-7, que descreve um dia de escuridão e terremoto. É uma confirmação da autenticidade das profecias de Zacarias.
* Apocalipse 22:5: "Não haverá mais noite. Eles não precisarão de luz de lamparina ou de luz do sol, pois o Senhor Deus os iluminará. Eles reinarão para todo o sempre." Este verso é uma referência ao reinado de Deus na terra, que é o tema final de Zacarias 14. É um lembrete da esperança que os crentes têm de um futuro glorioso na presença do Senhor.
****

[[v45-14-1]]

^<<v45-14-1,1>>^ Eis que vem o dia do Senhor, em que os teus despojos serão divididos no meio de ti.

[[v45-14-2]]

^<<v45-14-2,2>>^ Juntarei todas as nações ao redor de Jerusalém: a cidade será atacada e tomada, as casas serão destruídas, as mulheres, violadas; metade da cidade irá para o cativeiro, mas o resto do povo não será expulso.

[[v45-14-3]]

^<<v45-14-3,3>>^ Então, sairá o Senhor e pelejará contra aquelas nações: ele combaterá como o sabe fazer em tempo de guerra.

[[v45-14-4]]

^<<v45-14-4,4>>^ Naquele dia, os seus pés se apoiarão no monte das Oliveiras, defronte de Jerusalém, para o lado do Oriente, e o monte se dividirá em dois pelo meio, do Oriente ao Ocidente, formando assim um grande vale. Uma metade do monte se afastará para o Norte, a outra para o Sul.

[[v45-14-5]]

^<<v45-14-5,5>>^ Fugireis pelo vale aberto entre as montanhas, porque este vale se prolongará até o lugar do julgamento; e fugireis como fugistes do terremoto no tempo de Ozias, rei de Judá. Então, aparecerá o Senhor, vosso Deus, com todos os seus santos.^&#42;1^

[[v45-14-6]]

^<<v45-14-6,6>>^ Naquele dia, não haverá frio nem gelo.

[[v45-14-7]]

^<<v45-14-7,7>>^ Será um dia contínuo conhecido somente do Senhor, e não haverá sucessão de dia e noite, e a noite será clara.

[[v45-14-8]]

^<<v45-14-8,8>>^ Naquele dia, jorrará água corrente de Jerusalém, metade para o mar do nascente e metade para o mar do poente; jorrará tanto no verão como no inverno.

[[v45-14-9]]

^<<v45-14-9,9>>^ O Senhor reinará sobre toda a terra. Naquele dia, o Senhor será o único Deus e só o seu nome será invocado.

[[v45-14-10]]

^<<v45-14-10,10>>^ Toda a terra será aplanada, desde Gabaá até Remon, ao sul de Jerusalém. Jerusalém ocupará o seu lugar, e dominará desde a Porta de Benjamim até o lugar da Primeira Porta, até a Porta do Ângulo, e desde a torre de Hananeel até os lagares do rei.

[[v45-14-11]]

^<<v45-14-11,11>>^ Habitarão nela e não haverá mais interdito: Jerusalém estará verdadeiramente em segurança.

[[v45-14-12]]

^<<v45-14-12,12>>^ Eis a praga com que o Senhor vai ferir todos os povos que atacaram Jerusalém: apodrecerá sua carne, estando eles ainda de pé; seus olhos apodrecerão dentro de suas órbitas, e a língua lhes apodrecerá dentro da boca.

[[v45-14-13]]

^<<v45-14-13,13>>^ Naquele dia, o Senhor semeará o pânico no meio deles, de sorte que se atacarão mutuamente, e levantarão as mãos uns contra os outros.

[[v45-14-14]]

^<<v45-14-14,14>>^ Também Judá combaterá em Jerusalém; as riquezas serão juntadas de todas as nações vizinhas: ouro, prata e vestes em grande quantidade.

[[v45-14-15]]

^<<v45-14-15,15>>^ Cavalos, mulos, camelos, jumentos, e todo animal que se encontrar nos campos, serão feridos com a mesma praga.

[[v45-14-16]]

^<<v45-14-16,16>>^ Os que restarem de todas as nações que tiverem atacado Jerusalém virão todos os anos adorar o rei, Senhor dos exércitos, e celebrar a festa dos Tabernáculos.

[[v45-14-17]]

^<<v45-14-17,17>>^ Toda e qualquer família da terra que não subir a Jerusalém para adorar o rei, Senhor dos exércitos, não receberá chuva!

[[v45-14-18]]

^<<v45-14-18,18>>^ Se a família do Egito não subir nem vier, não haverá chuva para ela, mas será ferida com a praga com que o Senhor ferirá todas as nações que não subirem a Jerusalém para celebrar a festa dos Tabernáculos.

[[v45-14-19]]

^<<v45-14-19,19>>^ Este será o castigo do Egito, como também de toda nação que não subir para celebrar a festa dos Tabernáculos.

[[v45-14-20]]

^<<v45-14-20,20>>^ Naquele dia, se escreverá até mesmo nos chocalhos dos cavalos, consagrado ao Senhor. Os caldeirões ordinários do Templo do Senhor serão consagrados como as taças do altar.

[[v45-14-21]]

^<<v45-14-21,21>>^ Todo caldeirão, tanto em Jerusalém como em Judá, será consagrado ao Senhor dos exércitos; todo aquele que vier oferecer sacrifício poderá servir-se deles para cozinhar; e não haverá mais traficantes naqueles dias na casa do Senhor dos exércitos.

'''

xref:045-zacarias/045-zacarias-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:046-malaquias/046-malaquias-001.adoc#v46-1-0[Próximo Capítulo &#62;]