include::./index.adoc[]

[[v45-1-0]]
=== Zacarias, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Zacarias 1 começa com uma mensagem do Senhor ao profeta Zacarias para que ele convocasse o povo de volta ao arrependimento e à obediência à Lei de Deus. O capítulo também apresenta uma série de visões e revelações dadas ao profeta, incluindo a visão dos cavalos e orelhas de milho. Aqui estão cinco versículos relacionados aos temas abordados em Zacarias 1:
* 2 Crônicas 36:15-16: "E o Senhor Deus de seus pais lhes enviou persistente e constantemente mensageiros, porque tinha compaixão do seu povo e da sua habitação. Mas eles zombaram dos mensageiros de Deus, desprezaram as suas palavras, e mofaram dos seus profetas, até que o furor do Senhor subiu contra o seu povo, e não houve remédio." Este versículo mostra como a mensagem de Zacarias é um apelo para que o povo se arrependa e retorne à obediência a Deus, que enviou muitos profetas antes dele para lembrá-los da Sua vontade.
* Esdras 5:1: "Os profetas Ageu e Zacarias, filho de Ido, profetizaram aos judeus que estavam em Judá e em Jerusalém, no nome do Deus de Israel, que estava sobre eles." Este versículo mostra que Zacarias foi um dos muitos profetas que Deus enviou para falar com o Seu povo, e que a sua mensagem estava em harmonia com a de outros profetas como Ageu.
* Isaías 44:26: "Confirmo a palavra do meu servo, e cumpro o conselho dos meus mensageiros. Eu digo a Jerusalém: 'Você será habitada novamente' e às cidades de Judá: 'Serão reconstruídas'. Eu levantarei de novo suas ruínas." Este versículo mostra como as visões e revelações que Deus dá a Zacarias são uma confirmação da Sua promessa de restauração e renovação para o Seu povo.
* Jeremias 25:11-12: "Toda esta terra se tornará uma desolação e um espanto, e estas nações servirão ao rei de Babilônia setenta anos. E quando se completarem os setenta anos, eu castigarei o rei de Babilônia e aquela nação, diz o Senhor, pelos seus pecados, e castigarei a terra dos caldeus, e a tornarei em ruínas perpétuas." Este versículo mostra como a mensagem de Zacarias sobre a necessidade de arrependimento e obediência está em harmonia com as profecias de outros profetas, como Jeremias, que predisseram o exílio e o castigo de Judá e Babilônia.
* Jeremias 29:11: "Porque eu conheço os planos que tenho para vocês, diz o Senhor, planos de paz e não de mal, para dar-lhes um futuro e uma esperança." Este versículo mostra como a mensagem de Zacarias sobre a restauração e renovação do povo de Deus está em harmonia com a Sua promessa de que Ele tem planos de paz e um futuro e esperança para o Seu povo.
****

[[v45-1-1]]

^<<v45-1-1,1>>^ No oitavo mês do segundo ano do reinado de Dario, a palavra do Senhor foi dirigida ao profeta Zacarias, filho de Baraquias, filho de Ado, nestes termos:

[[v45-1-2]]

^<<v45-1-2,2>>^ “O Senhor estava profundamente irritado contra os vossos pais.^&#42;1^

[[v45-1-3]]

^<<v45-1-3,3>>^ Dize a (este povo): eis o que diz o Senhor dos exércitos: voltai a mim – oráculo do Senhor dos exércitos – e eu voltarei a vós – oráculo do Senhor dos exércitos.

[[v45-1-4]]

^<<v45-1-4,4>>^ Não sejais como vossos pais a quem os profetas de outrora clamaram, dizendo: eis o que diz o Senhor dos exércitos: deixai vossos maus caminhos e vossas más ações; e eles não ouviram, não prestaram atenção aos meus avisos – oráculo do Senhor.

[[v45-1-5]]

^<<v45-1-5,5>>^ Onde estão vossos pais? Podem porventura os profetas viver eternamente? Quanto aos avisos e às ordens que encarreguei os meus servos, os profetas, de transmitir ao povo, não foram eles executados junto de vossos pais?

[[v45-1-6]]

^<<v45-1-6,6>>^ Por isso, vossos pais caíram em si mesmos e, confusos, confessaram: o Senhor dos exércitos tratou-nos como tinha resolvido proceder conosco, segundo o nosso proceder e as nossas obras”.

[[v45-1-7]]

^<<v45-1-7,7>>^ No vigésimo quarto dia do décimo primeiro mês (o mês de Sabat) do segundo ano do reinado de Dario, a palavra do Senhor foi dirigida ao profeta Zacarias, filho de Baraquias, filho de Ado, nestes termos:

[[v45-1-8]]

^<<v45-1-8,8>>^ tive uma visão durante a noite. Percebi, entre as murtas do fundo do vale, um homem montado num cavalo vermelho, e atrás dele estavam cavalos ruços, alazões e brancos.^&#42;1^

[[v45-1-9]]

^<<v45-1-9,9>>^ Eu perguntei: “Meu senhor, que cavalos são estes?”. E o anjo porta-voz respondeu-me: “Vou explicar-te”.

[[v45-1-10]]

^<<v45-1-10,10>>^ O homem que se encontrava entre as murtas respondeu: “Estes são os mensageiros que o Senhor mandou para percorrer a terra”.

[[v45-1-11]]

^<<v45-1-11,11>>^ Então, os cavaleiros disseram ao anjo do Senhor que permanecia entre as murtas: “Acabamos de percorrer toda a terra, e vimos que toda a terra está em tranquilidade e descanso”.

[[v45-1-12]]

^<<v45-1-12,12>>^ O anjo do Senhor disse: “Senhor dos exércitos! Até quando ficareis insensível à sorte de Jerusalém e das cidades de Judá? Já faz setenta anos que estais irritado contra elas!”.

[[v45-1-13]]

^<<v45-1-13,13>>^ O Senhor respondeu ao anjo que me falava, e disse-lhe boas palavras, cheias de consolação.

[[v45-1-14]]

^<<v45-1-14,14>>^ E o anjo disse-me: “Proclama o seguinte: eis o que diz o Senhor dos exércitos: estou animado de ardente amor por Jerusalém e por Sião; porém, sumamente irritado contra as nações que vivem despreocupadas.

[[v45-1-15]]

^<<v45-1-15,15>>^ Eu só estava ligeiramente agastado contra Israel, mas estas nações ultrapassaram a medida.

[[v45-1-16]]

^<<v45-1-16,16>>^ Por isso, eis o que diz o Senhor: volto novamente para Jerusalém cheio de compaixão; minha casa será nela reedificada – oráculo do Senhor dos exércitos – e o cordel será estendido sobre Jerusalém.

[[v45-1-17]]

^<<v45-1-17,17>>^ Farás a proclamação seguinte: eis o que diz o Senhor dos exércitos: minhas cidades terão de novo muitas riquezas; o Senhor será a consolação de Sião, e a sua escolha cairá novamente sobre Jerusalém”.

'''

xref:044-ageu/044-ageu-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v45-1-0,Topo>> | xref:045-zacarias/045-zacarias-002.adoc#v45-2-0[Próximo Capítulo &#62;]