include::./index.adoc[]

[[v45-12-0]]
=== Zacarias, 12
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Zacarias 12 descreve a restauração de Jerusalém e o retorno de Deus para o seu povo. É um capítulo cheio de profecias e visões sobre o papel de Israel e de outras nações nos últimos dias. Aqui estão cinco versículos de diferentes livros da Bíblia que se relacionam com os temas abordados em Zacarias 12:
* Isaías 41:14: "Não temas, ó verme de Jacó, povozinho de Israel; eu te ajudo, diz o Senhor, e o teu redentor é o Santo de Israel." Este versículo traz conforto e segurança para Israel em meio a tempos difíceis, afirmando que Deus é o seu redentor e protetor.
* Ezequiel 37:21-22: "Dize-lhes pois: Assim diz o Senhor Deus: Eis que eu tomarei os filhos de Israel de entre os gentios, para onde eles foram, e os congregarei de todas as partes, e os levarei à sua terra; e deles farei uma nação na terra, nos montes de Israel, e um rei será rei de todos eles; e nunca mais serão duas nações, nem de maneira alguma se dividirão para o futuro em dois reinos." Este versículo fala da restauração de Israel como uma nação unida sob um único rei, uma profecia que se cumpre em Zacarias 12.
* Salmos 83:4: "Vinde, digamos-lhes, vamos destruí-los para que não sejam nação, e não haja mais memória do nome de Israel." Este versículo descreve a intenção de outras nações de destruir Israel, uma ameaça que é confrontada em Zacarias 12.
* Jeremias 30:18: "Assim diz o Senhor: Eis que trarei do cativeiro os cativos das tendas de Jacó, e apiedar-me-ei das suas moradas; a cidade será edificada sobre o seu montão, e o palácio ficará no seu devido lugar." Este versículo fala da restauração de Jerusalém, uma profecia que é cumprida em Zacarias 12.
* Apocalipse 1:7: "Eis que vem com as nuvens, e todo o olho o verá, até mesmo aqueles que o traspassaram; e todas as tribos da terra se lamentarão sobre ele. Certamente. Amém." Este versículo descreve a segunda vinda de Cristo, um evento que é referido em Zacarias 12:10.
****

[[v45-12-1]]

^<<v45-12-1,1>>^ Oráculo. Palavra do Senhor sobre Israel. Oráculo do Senhor, que estendeu os céus, firmou a terra e formou o sopro espírito que o homem tem dentro de si.

[[v45-12-2]]

^<<v45-12-2,2>>^ Eis o que farei de Jerusalém: um copo inebriante para todos os povos circunvizinhos; também Judá será cercado pelo inimigo com Jerusalém.

[[v45-12-3]]

^<<v45-12-3,3>>^ Naquele dia, farei de Jerusalém uma pedra pesada para todas as nações: todo o que se esforçar por levantá-la sairá ferido; todos os povos da terra se juntarão contra ela.

[[v45-12-4]]

^<<v45-12-4,4>>^ Naquele dia – oráculo do Senhor –, ferirei de espanto todos os cavalos, e de delírio os que montam neles. Abrirei os meus olhos sobre a casa de Judá, e cegarei a cavalaria das nações.

[[v45-12-5]]

^<<v45-12-5,5>>^ Os chefes de Judá reconhecerão em seu coração que a força dos habitantes de Jerusalém está em seu Deus, o Senhor dos exércitos.

[[v45-12-6]]

^<<v45-12-6,6>>^ Naquele dia, farei dos chefes de Judá como que um braseiro ardente sobre um monte de lenha, uma tocha acesa no meio dos feixes: devorarão à direita e à esquerda todos os povos da vizinhança, enquanto Jerusalém permanecerá firme e estável.

[[v45-12-7]]

^<<v45-12-7,7>>^ O Senhor libertará primeiramente as tendas de Judá, para que a glória da casa de Davi e dos habitantes de Jerusalém não se eleve demais em detrimento de Judá.

[[v45-12-8]]

^<<v45-12-8,8>>^ Naquele dia, o Senhor protegerá os habitantes de Jerusalém; o mais fraco dentre eles será valente como Davi, e a casa de Davi surgirá como Deus, como um anjo do Senhor.

[[v45-12-9]]

^<<v45-12-9,9>>^ Naquele dia, procurarei exterminar todo o povo que vier contra Jerusalém.

[[v45-12-10]]

^<<v45-12-10,10>>^ Suscitarei sobre a casa de Davi e sobre os habitantes de Jerusalém um espírito de boa vontade e de prece, e eles voltarão os seus olhos para mim. Farão lamentações sobre aquele que traspassaram, como se fosse um filho único; eles o chorarão amargamente como se chora um primogênito!^&#42;1^

[[v45-12-11]]

^<<v45-12-11,11>>^ Naquele dia, haverá um grande luto em Jerusalém, como o luto de Adad-Remom, no vale de Meguido.

[[v45-12-12]]

^<<v45-12-12,12>>^ A terra inteira celebrará esse luto, família por família; a família da casa de Davi à parte, com suas mulheres separadamente;

[[v45-12-13]]

^<<v45-12-13,13>>^ a família da casa de Natã à parte, com suas mulheres separadamente; a família da casa de Levi à parte, com suas mulheres separadamente; a família de Semei à parte, e suas mulheres separadamente;

[[v45-12-14]]

^<<v45-12-14,14>>^ todas as outras famílias, cada uma à parte, e as mulheres separadamente.

'''

xref:045-zacarias/045-zacarias-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-zacarias/045-zacarias-013.adoc#v45-13-0[Próximo Capítulo &#62;]