include::./index.adoc[]

[[v26-6-0]]
=== Cântico dos Cânticos, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Cânticos 6 continua a narrativa do amor entre o noivo e a noiva, destacando a beleza e a atração mútua entre eles. O capítulo começa com a noiva procurando pelo seu amado e, ao encontrá-lo, expressando sua admiração por sua beleza. Em seguida, há uma descrição detalhada da aparência física da noiva, exaltando sua beleza. Abaixo estão cinco versículos relacionados aos temas abordados em Cânticos 6:
* Cânticos 4:7 - "Você é toda linda, minha querida; em você não há defeito algum." Esse verso fala sobre a beleza da noiva, assim como a descrição detalhada em Cânticos 6.
* Provérbios 31:30 - "A beleza é enganosa, e a formosura é passageira; mas a mulher que teme o Senhor será elogiada." Este verso destaca a importância de uma beleza interior que é mais valiosa do que a beleza física.
* 1 Samuel 16:7 - "Mas o Senhor disse a Samuel: Não considere sua aparência nem sua altura, pois eu o rejeitei. O Senhor não vê como o homem vê. O homem vê a aparência, mas o Senhor vê o coração." Este verso mostra que Deus valoriza o coração das pessoas acima de sua aparência.
* Isaías 52:7 - "Como são belos, nos montes, os pés do que traz boas-novas, do que anuncia a paz, do que traz boas-novas de alegria e salvação, e diz a Sião: ‘O seu Deus reina!’” Este verso fala sobre a beleza daqueles que pregam o evangelho, trazendo alegria e salvação.
* 1 Pedro 3:3-4 - "Não seja a beleza exterior a principal qualidade de vocês, como cabelos arrumados, jóias de ouro ou vestidos finos. Ao contrário, seja a interior, que não perece, a beleza de um espírito calmo e tranqüilo, o que é de grande valor para Deus." Esse verso destaca a importância de uma beleza interior que é duradoura, em oposição à beleza física que desvanece com o tempo.
****

[[v26-6-1]]

^<<v26-6-1,1>>^ – Para onde foi o teu amado, ó tu, a mais bela das mulheres? Para onde se retirou o teu amado? Nós o buscaremos contigo.^&#42;1^

[[v26-6-2]]

^<<v26-6-2,2>>^ – O meu bem-amado desceu ao seu jardim, aos canteiros perfumados; para apascentar em meu jardim, e colher lírios.

[[v26-6-3]]

^<<v26-6-3,3>>^ Eu sou do meu amado e meu amado é meu. Ele apascenta entre os lírios.

[[v26-6-4]]

^<<v26-6-4,4>>^ – És formosa, amada minha, como Tirsa, graciosa como Jerusalém, temível como um exército em ordem de batalha.^&#42;1^

[[v26-6-5]]

^<<v26-6-5,5>>^ Desvia de mim os teus olhos, porque eles me fascinam. Teus cabelos são como um rebanho de cabras descendo impetuosamente pelas encostas de Galaad.^&#42;1^

[[v26-6-6]]

^<<v26-6-6,6>>^ Teus dentes são como um rebanho de ovelhas que sobem do banho; cada uma leva dois (cordeirinhos) gêmeos, e nenhuma delas é estéril.

[[v26-6-7]]

^<<v26-6-7,7>>^ Tua face é como um pedaço de romã debaixo do teu véu.

[[v26-6-8]]

^<<v26-6-8,8>>^ Há sessenta rainhas, oitenta concubinas, e inumeráveis jovens mulheres;^&#42;1^

[[v26-6-9]]

^<<v26-6-9,9>>^ uma, porém, é a minha pomba, uma só a minha perfeita; ela é a única de sua mãe, a predileta daquela que a deu à luz. Ao vê-la, as donzelas proclamam-na bem-aventurada, rainhas e concubinas a louvam.

[[v26-6-10]]

^<<v26-6-10,10>>^ Quem é esta que surge como a aurora, bela como a lua, brilhante como o sol, temível como um exército em ordem de batalha?

[[v26-6-11]]

^<<v26-6-11,11>>^ Eu desci ao jardim das nogueiras para ver a nova vegetação dos vales, e para ver se a vinha crescia e se as romãzeiras estavam em flor.

[[v26-6-12]]

^<<v26-6-12,12>>^ Eu não o sabia; minha alma colocou-me nos carros de Aminadab.^&#42;1^

'''

xref:026-cantico-dos-canticos/026-cantico-dos-canticos-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-cantico-dos-canticos/026-cantico-dos-canticos-007.adoc#v26-7-0[Próximo Capítulo &#62;]