include::./index.adoc[]

[[v18-13-0]]
=== Judite, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Judite 13 conta a história de como Judite, uma viúva piedosa e corajosa, salvou sua cidade Betúlia da destruição, assassinando o general assírio Holofernes. Os temas abordados nesse capítulo incluem a coragem, a astúcia e a fé de Judite, bem como a vingança de Deus sobre os inimigos do seu povo.
* Êxodo 15:3: "O Senhor é guerreiro, o seu nome é o Senhor." Esse versículo se relaciona com o tema da coragem de Judite, já que ela enfrentou o general assírio, um homem poderoso e temido, confiando na ajuda divina.
* Provérbios 21:31: "O cavalo é preparado para o dia da batalha, mas a vitória vem do Senhor." Esse versículo destaca que, embora seja importante estar preparado e ter coragem para enfrentar os desafios, a vitória é concedida pelo Senhor. Judite sabia disso e contou com a ajuda divina para derrotar Holofernes.
* Salmos 44:3: "Com a tua ajuda, derrotamos os nossos adversários; em teu nome pisamos os que se levantam contra nós." Esse versículo se relaciona com o tema da astúcia de Judite, já que ela usou sua beleza e inteligência para enganar Holofernes e cortar-lhe a cabeça.
* Salmos 37:28: "Pois o Senhor ama a justiça e não abandona os seus fiéis; eles serão preservados para sempre, mas a descendência dos ímpios será eliminada." Esse versículo destaca a vingança de Deus sobre os inimigos do seu povo, tema presente em Judite 13, quando os israelitas matam os assírios que tentavam atacá-los.
* Romanos 12:19: "Amados, nunca procurem vingar-se, mas deixem com Deus a ira, pois está escrito: 'Minha é a vingança; eu retribuirei', diz o Senhor." Esse versículo ensina que a vingança pertence a Deus e não aos homens. Embora Judite tenha agido em defesa do seu povo, ela também confiou na justiça divina para punir os inimigos.
****

[[v18-13-1]]

^<<v18-13-1,1>>^ Anoiteceu. Os oficiais apressaram-se em voltar aos seus aposentos. Vagao fechou as portas do quarto e foi-se.

[[v18-13-2]]

^<<v18-13-2,2>>^ Estavam todos embriagados pelo vinho.

[[v18-13-3]]

^<<v18-13-3,3>>^ Judite ficou só no seu quarto,

[[v18-13-4]]

^<<v18-13-4,4>>^ enquanto Holofernes repousava em seu leito, mergulhado em vinho.

[[v18-13-5]]

^<<v18-13-5,5>>^ Judite ordenou à sua serva que ficasse do lado de fora do quarto, vigiando.

[[v18-13-6]]

^<<v18-13-6,6>>^ De pé ao lado do leito, movendo em silêncio os lábios, ela orou com lágrimas a Deus, dizendo:

[[v18-13-7]]

^<<v18-13-7,7>>^ “Senhor, Deus de Israel, dai-me força. Olhai agora o que vão fazer minhas mãos, a fim de que, segundo a vossa promessa, levanteis a vossa cidade de Jerusalém e eu realize o que acreditei ser possível graças a vós”.

[[v18-13-8]]

^<<v18-13-8,8>>^ Dizendo essas palavras, aproximou-se da coluna que estava à cabeceira do leito e tomou a espada que ali estava pendurada;

[[v18-13-9]]

^<<v18-13-9,9>>^ desembainhou-a e, tomando os cabelos de Holofernes, disse: “Senhor, dai-me força neste momento!”.

[[v18-13-10]]

^<<v18-13-10,10>>^ Feriu-o duas vezes na nuca e decepou-lhe a cabeça. Desprendeu em seguida o cortinado das colunas e rolou por terra o corpo mutilado.

[[v18-13-11]]

^<<v18-13-11,11>>^ Feito isso, saiu e deu à sua serva a cabeça de Holofernes para que a colocasse dentro da sacola de provisões.

[[v18-13-12]]

^<<v18-13-12,12>>^ Depois saíram ambas, como de costume, como se fossem para a oração. Atravessaram o acampamento, contornaram o vale e chegaram às portas da cidade.

[[v18-13-13]]

^<<v18-13-13,13>>^ De longe, Judite gritou aos guardas das portas: “Abri a porta, porque Deus está conosco; ele manifestou o seu poder em favor de Israel”.

[[v18-13-14]]

^<<v18-13-14,14>>^ Ouvindo essas palavras, os homens chamaram os anciãos da cidade.

[[v18-13-15]]

^<<v18-13-15,15>>^ Toda a população correu para ela, desde o menor até o maior, porque não esperavam mais que ela voltasse.

[[v18-13-16]]

^<<v18-13-16,16>>^ Juntaram-se todos ao redor dela com tochas acesas. Judite, subindo a um lugar mais alto, pediu que se fizesse silêncio. Todos se calaram.

[[v18-13-17]]

^<<v18-13-17,17>>^ “Louvai ao Senhor, nosso Deus – disse-lhes ela –, que não abandonou os que puseram nele a sua esperança,

[[v18-13-18]]

^<<v18-13-18,18>>^ e que cumpriu pelas mãos de sua serva a sua promessa de misericórdia à casa de Israel; esta noite ele matou por minha mão o inimigo de seu povo.”

[[v18-13-19]]

^<<v18-13-19,19>>^ Então, tirando da sacola a cabeça de Holofernes, mostrou-a e disse-lhe: “Eis a cabeça de Holofernes, marechal do exército assírio; eis também o cortinado do baldaquino onde se achava deitado, ébrio a cair, quando o Senhor, nosso Deus, o feriu pela mão de uma mulher.

[[v18-13-20]]

^<<v18-13-20,20>>^ Mas juro-vos, pelo mesmo Senhor, que o seu anjo me protegeu, tanto ao partir, como ao demorar-me lá e como ao voltar e o Senhor não permitiu que sua serva fosse manchada: ele reconduziu-me a vós livre de toda a mancha de pecado, cheia de alegria por sua vitória, pela minha salvação e pela vossa libertação.

[[v18-13-21]]

^<<v18-13-21,21>>^ Dai-lhe glória todos vós, porque é bom, porque a sua misericórdia é eterna!”.

[[v18-13-22]]

^<<v18-13-22,22>>^ Então, todos, adorando o Senhor, disseram a Judite: “O Senhor te abençoou com o seu poder, porque ele por ti aniquilou os nossos inimigos”.

[[v18-13-23]]

^<<v18-13-23,23>>^ Ozias, príncipe do povo de Israel, acrescentou: “Minha filha, tu és bendita do Senhor, Deus Altíssimo, mais que todas as mulheres da terra.

[[v18-13-24]]

^<<v18-13-24,24>>^ Bendito seja o Senhor, criador do céu e da terra, que te guiou para cortar a cabeça de nosso maior inimigo!

[[v18-13-25]]

^<<v18-13-25,25>>^ Ele deu neste dia tanta glória ao teu nome, que nunca o teu louvor cessará de ser celebrado pelos homens, que se lembrarão eternamente do poder do Senhor. Ante os sofrimentos e a angústia de teu povo, não poupaste a tua vida, mas salvaste-nos da ruína, em presença de nosso Deus.”

[[v18-13-26]]

^<<v18-13-26,26>>^ E todo o povo respondeu: “Assim seja! Assim seja!”.

[[v18-13-27]]

^<<v18-13-27,27>>^ Mandaram então vir Aquior e Judite disse-lhe: “O Deus de Israel, de quem testemunhaste que toma vingança dos seus inimigos, cortou esta noite por minha mão a cabeça de todos os infiéis.

[[v18-13-28]]

^<<v18-13-28,28>>^ Para provar-te que assim é, eis a cabeça de Holofernes que, na insolência de seu orgulho, desprezava o Deus de Israel e te ameaçava de morte, dizendo: Quando o povo de Israel for vencido, mandarei passar-te a fio de espada”.

[[v18-13-29]]

^<<v18-13-29,29>>^ Vendo a cabeça de Holofernes, Aquior foi tomado de pavor e caiu com o rosto por terra, sem sentidos.

[[v18-13-30]]

^<<v18-13-30,30>>^ Quando recobrou os sentidos e voltou a si, jogou-se aos pés de Judite em sinal de reverência e disse: “Sê bendita de teu Deus em todas as tendas de Jacó, porque o Deus de Israel será glorificado por causa de ti entre todas as nações que ouvirem o teu nome”.

'''

xref:018-judite/018-judite-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-judite/018-judite-014.adoc#v18-14-0[Próximo Capítulo &#62;]