include::./index.adoc[]

[[v18-7-0]]
=== Judite, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Judite 7 narra a história de como os habitantes de Betúlia foram sitiados pelo exército assírio liderado por Holofernes. Os israelitas ficaram sem água e os líderes da cidade decidiram entregar a cidade a Holofernes se Deus não os livrasse em cinco dias. Judite, uma viúva piedosa, orou a Deus por orientação e decidiu entrar no acampamento inimigo disfarçada para matar Holofernes e salvar a cidade. Abaixo estão cinco versículos relacionados com temas abordados em Judite 7:
* 2 Crônicas 32:20: "Então, o rei Ezequias e o profeta Isaías, filho de Amoz, oraram por isso e clamaram ao céu." Este versículo destaca a importância da oração em tempos de dificuldade, semelhante à oração de Judite por orientação e ajuda em Judite 7.
* Salmos 20:7: "Uns confiam em carros e outros em cavalos, mas nós faremos menção do nome do Senhor, nosso Deus." Este versículo enfatiza a importância de confiar em Deus em vez de nas habilidades ou recursos humanos, semelhante à confiança dos líderes de Betúlia em Deus para salvá-los em Judite 7.
* 1 Samuel 17:49-50: Este trecho descreve como Davi matou Golias com uma pedra, ilustrando como Deus pode usar um indivíduo aparentemente fraco para derrotar um inimigo poderoso. Esse evento é semelhante à maneira como Judite, uma viúva piedosa, entrou no acampamento inimigo disfarçada e matou Holofernes em Judite 7.
* Juízes 4:4-9: Este trecho descreve como a profetisa Débora incentivou Baraque a liderar o exército israelita contra o exército cananeu. Esse evento é semelhante ao papel de liderança que Judite assumiu em Judite 7, incentivando os líderes de Betúlia a confiar em Deus e se preparar para a batalha.
* Isaías 54:17: "Nenhuma arma forjada contra ti prosperará; e toda língua que se levantar contra ti em juízo, tu a condenarás; esta é a herança dos servos do Senhor e a sua justiça que vem de mim, diz o Senhor." Este versículo enfatiza a proteção de Deus sobre aqueles que O seguem e confiam Nele, semelhante à proteção de Deus sobre os habitantes de Betúlia em Judite 7.
****

[[v18-7-1]]

^<<v18-7-1,1>>^ No dia seguinte, Holofernes ordenou às suas tropas que tomassem de assalto Betúlia.

[[v18-7-2]]

^<<v18-7-2,2>>^ Havia cento e setenta mil soldados de infantaria e doze mil cavaleiros, além dos homens de armas que tinha aprisionado e dos jovens que tinha levado das províncias e das cidades.

[[v18-7-3]]

^<<v18-7-3,3>>^ Prepararam-se todos para combater contra os israelitas e partiram pela encosta da montanha até o cume que olha para Dotain, desde o lugar chamado Belbaima até Quiamon, que está fronteiro a Esdrelão.

[[v18-7-4]]

^<<v18-7-4,4>>^ Quando os israelitas viram aquela multidão, prostraram-se por terra e cobriram de cinzas as suas cabeças, orando em comum ao Deus de Israel para que fizesse misericórdia ao seu povo.

[[v18-7-5]]

^<<v18-7-5,5>>^ Tomando então as suas armas de guerra, postaram-se nos lugares em que caminhos estreitos conduziam às passagens entre os montes e ali montaram guarda noite e dia.

[[v18-7-6]]

^<<v18-7-6,6>>^ Entretanto, ao fazer uma ronda pelos arredores, Holofernes descobriu ao sul da cidade a fonte que a abastecia por meio de um aqueduto e mandou cortá-lo.

[[v18-7-7]]

^<<v18-7-7,7>>^ Havia, entretanto, não longe dos muros, algumas fontes aonde iam furtivamente os sitiados buscar água, mais para aliviar um pouco a sede que para beber.

[[v18-7-8]]

^<<v18-7-8,8>>^ Então, os amonitas e os moabitas foram dizer a Holofernes: “Os israelitas não confiam nem nas lanças nem nas flechas, mas são defendidos pelas montanhas e sua verdadeira força são as colinas escarpadas.

[[v18-7-9]]

^<<v18-7-9,9>>^ Para que possas vencê-los sem combate, põe guardas às fontes, para não buscarem água ali e os matareis sem golpes de espada. Ou, pelo menos, esgotados pela sede, entregarão a cidade, a qual, por estar situada nas montanhas, julgavam inexpugnável”.

[[v18-7-10]]

^<<v18-7-10,10>>^ Essa sugestão agradou a Holofernes e aos seus oficiais e ele mandou que cada fonte fosse vigiada por um contingente de cem homens.

[[v18-7-11]]

^<<v18-7-11,11>>^ Passados vinte dias de guarda, secaram-se as fontes e os poços de Betúlia e os habitantes que recebiam cotidianamente a sua medida de água não a tiveram mais nem sequer para um dia.

[[v18-7-12]]

^<<v18-7-12,12>>^ Então, reuniram-se todos os homens, mulheres, jovens e crianças ao redor de Ozias e disseram-lhe a uma voz:

[[v18-7-13]]

^<<v18-7-13,13>>^ “Deus seja juiz entre nós e ti, pois, recusando negociar a paz com os assírios, atraíste a desgraça sobre nós; e por isso entregou-nos Deus nas suas mãos.

[[v18-7-14]]

^<<v18-7-14,14>>^ Também por isso não há quem nos socorra, estando nós aos seus olhos esgotados pela sede.

[[v18-7-15]]

^<<v18-7-15,15>>^ Agora, pois, reúne todos os que estão na cidade e entreguemo-nos espontaneamente aos homens de Holofernes.

[[v18-7-16]]

^<<v18-7-16,16>>^ É melhor que bendigamos a Deus no cativeiro, vivos, do que morrer vergonhosamente diante de todos os homens, vendo morrer sob os nossos olhos nossas mulheres e nossos filhos.

[[v18-7-17]]

^<<v18-7-17,17>>^ O céu e a terra nos são testemunhas, assim como o Deus de nossos pais que toma vingança de nossos pecados: entrega sem demora a cidade ao exército de Holofernes, para que o fio de espada abrevie o nosso fim, retardado pelo ardor da sede!”.

[[v18-7-18]]

^<<v18-7-18,18>>^ Tendo eles assim falado, levantou-se um grande pranto e gritos lancinantes na assembleia e a sua voz elevou-se para Deus durante várias horas:

[[v18-7-19]]

^<<v18-7-19,19>>^ “Pecamos – diziam eles –, nós e nossos pais cometemos a injustiça e a iniquidade.

[[v18-7-20]]

^<<v18-7-20,20>>^ Vós, que sois bom, tende piedade de nós, ou então que vossos castigos tomem vingança de nossas iniquidades; mas não entregueis os que vos invocam a um povo que não vos conhece,

[[v18-7-21]]

^<<v18-7-21,21>>^ para que se não diga entre os pagãos: Onde está o seu Deus?”.

[[v18-7-22]]

^<<v18-7-22,22>>^ Fatigados enfim de gritar e de chorar, eles se calaram.

[[v18-7-23]]

^<<v18-7-23,23>>^ Ozias levantou-se então banhado em lágrimas: “Coragem, meus irmãos!” – disse ele. – “Esperemos ainda cinco dias a misericórdia do Senhor.

[[v18-7-24]]

^<<v18-7-24,24>>^ Talvez se aplaque a sua cólera e dê glória ao seu nome.

[[v18-7-25]]

^<<v18-7-25,25>>^ Entretanto, se depois de cinco dias não nos chegar socorro algum, faremos o que propusestes.”

'''

xref:018-judite/018-judite-006.adoc#v18-6-0[&#60; Capítulo Anterior] | <<v18-7-0,Topo>> | xref:018-judite/018-judite-008.adoc#v18-8-0[Próximo Capítulo &#62;]