include::./index.adoc[]

[[v18-14-0]]
=== Judite, 14
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Judite 14 narra o plano de Judite para derrotar o exército assírio liderado por Holofernes, incluindo o engano que ela usa para se infiltrar no acampamento inimigo. Os versículos a seguir estão relacionados com os temas abordados neste capítulo:
* Juízes 4:21: "Então Jael, mulher de Héber, pegou uma estaca de tenda e, com uma marreta na mão, se aproximou dele sorrateiramente e cravou a estaca na têmpora de Sísera, fazendo-a atravessar a cabeça até o chão. E ele morreu." Esse versículo relata a morte do general inimigo Sísera pelas mãos de uma mulher. A história é semelhante ao enredo de Judite, em que uma mulher usa astúcia para derrotar um líder militar poderoso.
* 2 Reis 19:35: "Naquela noite, o anjo do Senhor saiu e matou cento e oitenta e cinco mil homens no acampamento assírio. Quando os sobreviventes se levantaram de manhã, só encontraram cadáveres." Esse versículo fala sobre a destruição sobrenatural do exército assírio. Embora a abordagem de Judite seja mais sutil, o resultado é o mesmo: a derrota do exército inimigo.
* Jó 12:16: "Com ele está a força e a sabedoria; os enganados e os enganadores são dele." Este versículo fala sobre como Deus é soberano e tem controle sobre todas as coisas, incluindo aqueles que usam engano para alcançar seus objetivos. O plano de Judite envolve enganar Holofernes para que ele se torne complacente e vulnerável, mas a história mostra que Deus ainda está no controle.
* Provérbios 21:30: "Não há sabedoria, nem entendimento, nem conselho que possa opor-se ao Senhor." Esse versículo enfatiza que ninguém pode se opor a Deus e vencer. Embora o plano de Judite seja astuto, é importante lembrar que é a vontade de Deus que finalmente prevalece.
* Ezequiel 13:10: "Porquanto, sim, porquanto andaram enganando o meu povo, dizendo: Paz! Não havendo paz; e um, edificando a parede, e eis que outros a cobriam de argamassa malfeita;" Este versículo fala sobre aqueles que enganam o povo de Deus e constroem com más intenções. Embora Judite esteja lutando pela causa de seu povo, ela usa engano para alcançar seus objetivos. O versículo é um lembrete de que a construção deve ser baseada em fundações sólidas e verdadeiras.
****

[[v18-14-1]]

^<<v18-14-1,1>>^ Então, Judite disse a todo o povo: “Ouvi-me, irmãos, pendurai esta cabeça no alto de nossas muralhas.

[[v18-14-2]]

^<<v18-14-2,2>>^ Quando o sol se levantar, tome cada um as suas armas e saí com ímpeto, não para descerdes simplesmente até o vale, mas como para atacá-los.

[[v18-14-3]]

^<<v18-14-3,3>>^ Será necessário que as sentinelas corram a acordar o seu general para o combate.

[[v18-14-4]]

^<<v18-14-4,4>>^ Quando os seus chefes tiverem corrido à tenda de Holofernes e o encontrarem decapitado, jazendo no seu próprio sangue, serão tomados de pavor.

[[v18-14-5]]

^<<v18-14-5,5>>^ E quando os virdes fugir, persegui-os destemidamente, porque o Senhor os esmagará sob os vossos pés”.

[[v18-14-6]]

^<<v18-14-6,6>>^ Então, Aquior, vendo o poder que manifestara o Deus de Israel, abandonou o culto pagão, creu em Deus, circuncidou-se e foi incorporado ao povo de Israel, assim como toda a sua descendência até o dia de hoje.

[[v18-14-7]]

^<<v18-14-7,7>>^ Logo que raiou o dia, penduraram nas muralhas a cabeça de Holofernes, cada um tomou as suas armas e saíram fazendo um grande alarido e soltando gritos agudos.

[[v18-14-8]]

^<<v18-14-8,8>>^ Vendo isso, correram as sentinelas à tenda de Holofernes.

[[v18-14-9]]

^<<v18-14-9,9>>^ Os que estavam na tenda vieram ver e fizeram grande barulho à porta do quarto para despertá-lo e aumentavam cada vez mais o tumulto para que Holofernes acordasse com o ruído, sem que houvesse necessidade de entrar para acordá-lo.

[[v18-14-10]]

^<<v18-14-10,10>>^ Porque ninguém ousava bater na porta nem entrar no quarto do marechal dos assírios.

[[v18-14-11]]

^<<v18-14-11,11>>^ Mas chegando os generais com os tribunos e com todos os oficiais do exército do rei dos assírios, ordenaram aos camareiros:

[[v18-14-12]]

^<<v18-14-12,12>>^ “Entrai e despertai-o, porque os ratos saíram de seus buracos e se atrevem a nos provocar ao combate”.

[[v18-14-13]]

^<<v18-14-13,13>>^ Então, Vagao, entrando no quarto, parou diante da cortina e bateu com as mãos, porque supunha que ele dormia com Judite.

[[v18-14-14]]

^<<v18-14-14,14>>^ Aplicando, porém, os ouvidos e não percebendo movimento algum de um homem que dorme, aproximou-se da cortina e a levantou. À vista do cadáver de Holofernes decapitado, que jazia por terra num charco de sangue, soltou um forte grito, rompeu em lágrimas e rasgou as suas vestes.

[[v18-14-15]]

^<<v18-14-15,15>>^ Entrou então na tenda de Judite e não a encontrou. Correu para fora e disse ao povo:

[[v18-14-16]]

^<<v18-14-16,16>>^ “Uma judia pôs a confusão na casa do rei Nabucodonosor: Holofernes jaz ali caído por terra e a sua cabeça não está com o corpo!”.

[[v18-14-17]]

^<<v18-14-17,17>>^ Ouvindo essas palavras, todos os oficiais do exército assírio rasgaram suas vestes. Um terror e um espanto extremos os invadiram e os seus espíritos ficaram completamente desorientados. Um clamor indescritível levantou-se do acampamento.

'''

xref:018-judite/018-judite-013.adoc#v18-13-0[&#60; Capítulo Anterior] | <<v18-14-0,Topo>> | xref:018-judite/018-judite-015.adoc#v18-15-0[Próximo Capítulo &#62;]