include::./index.adoc[]

[[v18-4-0]]
=== Judite, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Judite 4 descreve a preparação dos israelitas para a guerra contra os assírios. O capítulo começa com os líderes israelitas convocando o povo para jejuar e orar, pedindo a ajuda de Deus na batalha que estava por vir. Em seguida, o autor descreve a mobilização dos exércitos israelitas e o preparo para a batalha.
* Números 10:9: "E, quando na vossa terra sairdes à peleja contra o inimigo que vos oprimir, tocareis as trombetas de rebate, e perante o SENHOR vosso Deus haverá lembrança de vós, e sereis salvos dos vossos inimigos." Este versículo descreve o uso de trombetas para chamar a atenção de Deus e pedir ajuda na batalha, assim como os israelitas fazem em Judite 4.
* Deuteronômio 20:1: "Quando saíres à peleja contra os teus inimigos, e vires cavalos, e carros, e povo mais numeroso do que tu, não os temerás; pois o SENHOR teu Deus, que te tirou da terra do Egito, está contigo." Este versículo encoraja os soldados israelitas a não terem medo dos exércitos inimigos, mas confiar na ajuda de Deus, como os líderes israelitas pedem em Judite 4.
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te esforço, e te ajudo, e te sustento com a destra da minha justiça." Este versículo é outro exemplo de Deus encorajando seus seguidores a confiar nele em momentos de dificuldade e luta, o que é um tema central em Judite 4.
* Salmos 144:1: "Bendito seja o SENHOR, minha rocha, que ensina as minhas mãos para a peleja e os meus dedos para a guerra." Este salmo fala sobre a capacidade de Deus de preparar seus seguidores para a batalha e ensiná-los a lutar. Isso é algo que os líderes israelitas em Judite 4 também estão buscando, ao pedirem a ajuda de Deus.
* 2 Crônicas 20:15: "e disse: Dai ouvidos todo o Judá, e vós moradores de Jerusalém, e tu, ó rei Jeosafá; assim vos diz o SENHOR: Não temais, nem vos assusteis por causa desta grande multidão; pois a peleja não é vossa, senão de Deus." Este versículo é uma outra afirmação de que Deus é quem luta junto com seus seguidores e que, portanto, não há razão para ter medo dos inimigos. Isso é algo que os líderes israelitas em Judite 4 estão tentando transmitir ao povo.
****

[[v18-4-1]]

^<<v18-4-1,1>>^ Ouvindo isso, os israelitas de Judá ficaram alarmados com a aproximação de Holofernes.

[[v18-4-2]]

^<<v18-4-2,2>>^ O medo e o terror apoderaram-se deles, temendo que ele fizesse a Jerusalém e ao Templo do Senhor o mesmo que ele fizera às outras cidades e aos seus templos.

[[v18-4-3]]

^<<v18-4-3,3>>^ Mandaram mensageiros por toda a Samaria e seus arredores até Jericó e ocuparam todos os cumes dos montes.

[[v18-4-4]]

^<<v18-4-4,4>>^ Cercaram de muros todas as suas cidades e armazenaram trigo para poderem sustentar o combate.

[[v18-4-5]]

^<<v18-4-5,5>>^ De seu lado, o sumo sacerdote Eliacim escreveu a todos os que habitavam defronte de Esdrelão, que está fronteira à grande planície vizinha de Dotaia e a todos os das terras pelas quais havia passagens,

[[v18-4-6]]

^<<v18-4-6,6>>^ pedindo-lhes que ocupassem as vertentes montanhosas que davam acesso a Jerusalém e que pusessem guarnições nos desfiladeiros por onde se pudesse passar.

[[v18-4-7]]

^<<v18-4-7,7>>^ Os israelitas executaram todas as ordens de Eliacim, sacerdote do Senhor.

[[v18-4-8]]

^<<v18-4-8,8>>^ Todo o povo orou fervorosamente ao Senhor. Humilharam suas almas com jejuns e orações, eles e suas mulheres.

[[v18-4-9]]

^<<v18-4-9,9>>^ Os sacerdotes vestiram-se de cilício, as crianças prostraram-se diante do Templo do Senhor e cobriu-se o altar do Senhor com um cilício.

[[v18-4-10]]

^<<v18-4-10,10>>^ Unidos de coração e de alma, clamaram ao Senhor que não entregasse seus filhos à rapina do vencedor, suas mulheres à devassidão, suas cidades ao extermínio, seu templo à profanação e não permitisse que eles próprios se tornassem o opróbrio das nações pagãs.

[[v18-4-11]]

^<<v18-4-11,11>>^ Eliacim, sumo sacerdote do Senhor, percorreu então todo o país de Israel e falou ao povo^&#42;1^

[[v18-4-12]]

^<<v18-4-12,12>>^ nestes termos: “Estai certos de que o Senhor vos ouvirá, se perseverardes jejuando e orando em sua presença.

[[v18-4-13]]

^<<v18-4-13,13>>^ Lembrai-vos de Moisés, servo do Senhor: Amalec, que confiava em sua força, em seu poder, em seu exército, em seus escudos, em seus carros e cavaleiros, foi derrotado por ele, não com a força das armas, mas com o poder da santa oração.

[[v18-4-14]]

^<<v18-4-14,14>>^ Isso mesmo acontecerá a todos os inimigos de Israel, se perseverardes na obra que começastes”.

[[v18-4-15]]

^<<v18-4-15,15>>^ Com tais exortações, os israelitas puseram-se a orar diante do Senhor.

[[v18-4-16]]

^<<v18-4-16,16>>^ Mesmo aqueles que ofereciam holocaustos ao Senhor, faziam-no revestidos de sacos e com a cabeça coberta de cinzas.

[[v18-4-17]]

^<<v18-4-17,17>>^ E todos rogavam a Deus, de todo o seu coração, que visitasse o seu povo de Israel.

'''

xref:018-judite/018-judite-003.adoc#v18-3-0[&#60; Capítulo Anterior] | <<v18-4-0,Topo>> | xref:018-judite/018-judite-005.adoc#v18-5-0[Próximo Capítulo &#62;]