include::./index.adoc[]

[[v54-2-0]]
=== II Coríntios, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Coríntios 2 trata sobre o perdão e a reconciliação entre membros da igreja. O apóstolo Paulo encoraja os coríntios a perdoarem e restaurarem um irmão que havia sido disciplinado anteriormente. Ele também fala sobre a importância de manter a unidade na igreja e de reconhecer a autoridade apostólica. Aqui estão cinco versículos relacionados com os temas abordados em 2 Coríntios 2:
* Romanos 12:18: "Se possível, quanto depender de vós, tende paz com todos os homens." Paulo enfatiza a importância da paz e da unidade entre irmãos, algo que é abordado em 2 Coríntios 2.
* Colossenses 3:13: "Suportai-vos uns aos outros, perdoai-vos mutuamente, caso alguém tenha motivo de queixa contra outrem. Assim como o Senhor vos perdoou, assim também perdoai vós." O perdão é um tema central em 2 Coríntios 2 e este versículo encoraja a perdoar assim como fomos perdoados.
* Mateus 6:14-15: "Porque, se perdoardes aos homens as suas ofensas, também vosso Pai celestial vos perdoará a vós; se, porém, não perdoardes aos homens [as suas ofensas], tampouco vosso Pai vos perdoará as vossas ofensas." Este versículo reforça a importância do perdão e sua relação com a misericórdia de Deus, um tema importante em 2 Coríntios 2.
* Efésios 4:32: "Antes, sede uns para com os outros benignos, compassivos, perdoando-vos uns aos outros, como também Deus vos perdoou em Cristo." Mais uma vez, Paulo enfatiza a importância do perdão e da misericórdia em nossos relacionamentos, algo que ele aborda em 2 Coríntios 2.
* João 20:23: "Àqueles a quem perdoardes os pecados, são-lhes perdoados; àqueles a quem os retiverdes, são-lhes retidos." Este versículo mostra a autoridade dada aos discípulos de Jesus para perdoar pecados e sua relação com a reconciliação, um tema importante em 2 Coríntios 2.
****

[[v54-2-1]]

^<<v54-2-1,1>>^ Eu decidi, pois, comigo mesmo não tornar a visitar-vos, para não vos contristar;^&#42;1^

[[v54-2-2]]

^<<v54-2-2,2>>^ porque, se eu vos entristeço, como poderia esperar alegria daqueles que por mim foram entristecidos?

[[v54-2-3]]

^<<v54-2-3,3>>^ Se vos escrevi estas coisas foi para que, quando eu chegar, não sinta tristeza precisamente da parte dos que me deviam alegrar. Confio em todos vós que a minha alegria seja a de todos.^&#42;1^

[[v54-2-4]]

^<<v54-2-4,4>>^ Foi numa grande aflição, com o coração despedaçado e lágrimas nos olhos, que vos escrevi, não com o propósito de vos contristar, mas para vos fazer conhecer o amor todo particular que vos tenho.

[[v54-2-5]]

^<<v54-2-5,5>>^ Se alguém causou tristeza, não me contristou a mim, mas de certo modo – para não exagerar – a todos vós.^&#42;1^

[[v54-2-6]]

^<<v54-2-6,6>>^ Basta a esse homem o castigo que a maioria dentre vós lhe infligiu.

[[v54-2-7]]

^<<v54-2-7,7>>^ Assim deveis agora perdoar-lhe e consolá-lo para que não sucumba por demasiada tristeza.

[[v54-2-8]]

^<<v54-2-8,8>>^ Peço-vos que tenhais caridade para com ele.

[[v54-2-9]]

^<<v54-2-9,9>>^ Quando vos escrevi, a minha intenção era submeter-vos à prova para ver se éreis totalmente obedientes.

[[v54-2-10]]

^<<v54-2-10,10>>^ A quem vós perdoais, também eu perdoo. Com efeito, o que perdoei – se alguma coisa tenho perdoado – foi por amor de vós, sob o olhar de Cristo.

[[v54-2-11]]

^<<v54-2-11,11>>^ Não quero que sejamos vencidos por Satanás, pois não ignoramos as suas maquinações.

[[v54-2-12]]

^<<v54-2-12,12>>^ Quando cheguei a Trôade para pregar o Evangelho de Cristo, apesar da porta que o Senhor me abriu,^&#42;1^

[[v54-2-13]]

^<<v54-2-13,13>>^ o meu espírito não teve sossego, porque não achei o meu irmão Tito. Despedi-me deles e parti para a Macedônia.

[[v54-2-14]]

^<<v54-2-14,14>>^ Mas graças sejam dadas a Deus, que nos concede sempre triunfar em Cristo, e que por nosso meio difunde o perfume do seu conhecimento em todo lugar.

[[v54-2-15]]

^<<v54-2-15,15>>^ Somos para Deus o perfume de Cristo entre os que se salvam e entre os que se perdem.

[[v54-2-16]]

^<<v54-2-16,16>>^ Para estes, na verdade, odor de morte e que dá a morte; para os primeiros, porém, odor de vida e que dá a vida. E qual o homem capaz de uma tal obra?

[[v54-2-17]]

^<<v54-2-17,17>>^ É que, de fato, não somos, como tantos outros, falsificadores da Palavra de Deus. Mas é na sua integridade, tal como procede de Deus, que nós a pregamos em Cristo, sob os olhares de Deus.

'''

xref:054-ii-corintios/054-ii-corintios-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-ii-corintios/054-ii-corintios-003.adoc#v54-3-0[Próximo Capítulo &#62;]