include::./index.adoc[]

[[v54-12-0]]
=== II Coríntios, 12
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 12 de 2 Coríntios fala sobre a experiência sobrenatural de Paulo de ter sido levado ao terceiro céu e a fim de não se gloriar demasiadamente, ele foi atormentado com um "espinho na carne". Além disso, Paulo defende sua autoridade apostólica e encoraja os coríntios a se arrependerem e se reconciliarem com Deus.
* 2 Coríntios 12:2-4: "Conheço um homem em Cristo que, há catorze anos, foi arrebatado até o terceiro céu. Se foi no corpo ou fora do corpo, não sei, Deus o sabe. E sei que esse homem – se no corpo ou fora dele, não sei, mas Deus o sabe –" Paulo fala de sua própria experiência sobrenatural de ter sido levado ao terceiro céu, mas não está certo se foi em corpo ou espírito.
* 2 Coríntios 12:7: "Para impedir que eu me exaltasse por causa da grandeza dessas revelações, foi-me dado um espinho na carne, um mensageiro de Satanás, para me atormentar." Paulo menciona seu "espinho na carne", que é uma fonte de grande sofrimento, mas que Deus permitiu para mantê-lo humilde.
* 2 Coríntios 12:9: "Mas ele me disse: “Minha graça é suficiente para você, pois o meu poder se aperfeiçoa na fraqueza”. Portanto, eu me gloriarei ainda mais alegremente em minhas fraquezas, para que o poder de Cristo repouse em mim." Deus responde a Paulo dizendo que Sua graça é suficiente para lidar com seu "espinho na carne", e que Seu poder é aperfeiçoado na fraqueza.
* 2 Coríntios 12:10: "Por isso, por amor de Cristo, regozijo-me nas fraquezas, nos insultos, nas necessidades, nas perseguições, nas angústias. Pois, quando sou fraco, é que sou forte." Paulo diz que, em vez de ficar desanimado com suas fraquezas e dificuldades, ele se alegra nelas porque é quando a força de Cristo é mais visível em sua vida.
* 2 Coríntios 12:19: "Será que vocês pensam que temos estado nos justificando diante de vocês? É diante de Deus que temos falado em Cristo, e tudo o que fazemos, amigos amados, é para edificá-los." Paulo reafirma sua autoridade apostólica e seu compromisso de edificar a igreja de Corinto em Cristo.
****

[[v54-12-1]]

^<<v54-12-1,1>>^ Importa que me glorie? Na verdade, não convém! Passarei, entretanto, às visões e revelações do Senhor.

[[v54-12-2]]

^<<v54-12-2,2>>^ Conheço um homem em Cristo que há catorze anos foi arrebatado até o terceiro céu. Se foi no corpo, não sei. Se fora do corpo, também não sei; Deus o sabe.

[[v54-12-3]]

^<<v54-12-3,3>>^ E sei que esse homem – se no corpo ou se fora do corpo, não sei; Deus o sabe –

[[v54-12-4]]

^<<v54-12-4,4>>^ foi arrebatado ao paraíso e lá ouviu palavras inefáveis, que não é permitido a um homem repetir.

[[v54-12-5]]

^<<v54-12-5,5>>^ Desse homem eu me gloriarei, mas de mim mesmo não me gloriarei, a não ser das minhas fraquezas.

[[v54-12-6]]

^<<v54-12-6,6>>^ Pois, ainda que me quisesse gloriar, não seria insensato, porque diria a verdade. Mas abstenho-me, para que ninguém me tenha em conta de mais do que vê em mim ou ouve dizer de mim.

[[v54-12-7]]

^<<v54-12-7,7>>^ Demais, para que a grandeza das revelações não me levasse ao orgulho, foi-me dado um espinho na carne, um anjo de Satanás para me esbofetear e me livrar do perigo da vaidade.^&#42;1^

[[v54-12-8]]

^<<v54-12-8,8>>^ Três vezes roguei ao Senhor que o apartasse de mim.

[[v54-12-9]]

^<<v54-12-9,9>>^ Mas ele me disse: “Basta-te minha graça, porque é na fraqueza que se revela totalmente a minha força”. Portanto, prefiro gloriar-me das minhas fraquezas, para que habite em mim a força de Cristo.

[[v54-12-10]]

^<<v54-12-10,10>>^ Eis por que sinto alegria nas fraquezas, nas afrontas, nas necessidades, nas perseguições, no profundo desgosto sofrido por amor de Cristo. Porque, quando me sinto fraco, então é que sou forte.

[[v54-12-11]]

^<<v54-12-11,11>>^ Tenho-me tornado insensato! Vós a isso me obrigastes. Vós é que deveríeis fazer o meu elogio, visto que em nada fui inferior a esses eminentes apóstolos, se bem que nada sou.

[[v54-12-12]]

^<<v54-12-12,12>>^ Os sinais distintivos do verdadeiro apóstolo se realizaram em vosso meio com uma paciência a toda prova, de sinais, prodígios e milagres.

[[v54-12-13]]

^<<v54-12-13,13>>^ Em que fostes inferiores às outras igrejas, senão no fato de que a vós não vos fui pesado? Relevai-me esta injúria!...

[[v54-12-14]]

^<<v54-12-14,14>>^ Eis que estou pronto a ir ter convosco pela terceira vez. Não vos serei oneroso, porque não busco os vossos bens, mas sim a vós mesmos. Com efeito, não são os filhos que devem entesourar para os pais, mas os pais para os filhos.

[[v54-12-15]]

^<<v54-12-15,15>>^ De muito boa vontade darei o que é meu, e me darei a mim mesmo pelas vossas almas, ainda que, amando-vos mais, seja menos amado por vós.

[[v54-12-16]]

^<<v54-12-16,16>>^ Mas seja! Não vos fui pesado. Como, porém, sou esperto, apanhei-vos pela astúcia...

[[v54-12-17]]

^<<v54-12-17,17>>^ Acaso tirei proveito de vós por meio de algum daqueles que vos enviei?

[[v54-12-18]]

^<<v54-12-18,18>>^ Roguei a Tito, e com ele enviei um irmão que conheceis. Por acaso tirou Tito de vós alguma coisa? Não andamos nós com o mesmo espírito, sobre as mesmas pegadas?

[[v54-12-19]]

^<<v54-12-19,19>>^ Já há muito pensais que nos justificamos diante de vós. Perante Deus, em Cristo, é que nós falamos; mas tudo isso, meus caríssimos, para vossa edificação.

[[v54-12-20]]

^<<v54-12-20,20>>^ Temo que, quando for, não vos ache quais eu quisera, e que vós me acheis qual não quereríeis. Receio encontrar entre vós contendas, invejas, rixas, dissensões, calúnias, murmurações, arrogâncias e desordens.

[[v54-12-21]]

^<<v54-12-21,21>>^ Receio que à minha chegada entre vós Deus me humilhe ainda a vosso respeito; e tenha de chorar por muitos daqueles que pecaram e não fizeram penitência da impureza, fornicação e dissolução que cometeram.

'''

xref:054-ii-corintios/054-ii-corintios-011.adoc#v54-11-0[&#60; Capítulo Anterior] | <<v54-12-0,Topo>> | xref:054-ii-corintios/054-ii-corintios-013.adoc#v54-13-0[Próximo Capítulo &#62;]