include::./index.adoc[]

[[v54-1-0]]
=== II Coríntios, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 1 de 2 Coríntios fala sobre o conforto de Deus em meio às aflições e tribulações que os cristãos enfrentam. Paulo encoraja os coríntios a confiarem em Deus em todos os momentos e compartilha sua própria experiência de sofrimento e consolo divino. Ele enfatiza que Deus é o Pai das misericórdias e o Deus de toda a consolação, que nos consola em todas as nossas tribulações para que possamos consolar os outros que também passam por dificuldades.
* Salmos 46:1: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia." Este versículo mostra que Deus é nosso refúgio e fortaleza, o mesmo tema de 2 Coríntios 1.
* 2 Coríntios 7:6: "Mas Deus, que consola os abatidos, nos consolou com a vinda de Tito." Aqui, Paulo reforça que Deus é quem consola os que estão sofrendo, e Tito foi um instrumento usado por Deus para trazer conforto a Paulo e aos coríntios.
* Isaías 49:13: "Exultai, ó céus, e alegra-te, ó terra, e vós, montes, estalai com júbilo, porque o SENHOR consolou o seu povo, e dos seus aflitos se compadecerá." Este versículo mostra que Deus é aquele que consola seu povo em suas aflições e sofrimentos, assim como Paulo fala em 2 Coríntios 1.
* Salmos 34:18: "Perto está o SENHOR dos que têm o coração quebrantado e salva os contritos de espírito." Este versículo fala sobre como Deus está perto daqueles que têm o coração quebrantado, o que é um tema comum em 2 Coríntios 1.
* 2 Coríntios 4:8-10: "Em tudo somos atribulados, mas não angustiados; perplexos, mas não desanimados. Perseguidos, mas não desamparados; abatidos, mas não destruídos; trazendo sempre no corpo o morrer de Jesus, para que também a sua vida se manifeste em nosso corpo." Este trecho de 2 Coríntios 4 fala sobre as dificuldades que os cristãos enfrentam, mas que não os deixam desanimados, pois a vida de Jesus se manifesta em seus corpos. Esse tema se relaciona com a mensagem de conforto e consolação de 2 Coríntios 1.
****

[[v54-1-1]]

^<<v54-1-1,1>>^ Paulo, apóstolo de Jesus Cristo pela vontade de Deus, e o irmão Timóteo, à igreja de Deus que está em Corinto, e a todos os irmãos santos que estão em toda a Acaia.

[[v54-1-2]]

^<<v54-1-2,2>>^ A vós, graça e paz da parte de Deus, nosso Pai, e da parte do Senhor Jesus Cristo!

[[v54-1-3]]

^<<v54-1-3,3>>^ Bendito seja Deus, o Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias, Deus de toda a consolação,

[[v54-1-4]]

^<<v54-1-4,4>>^ que nos conforta em todas as nossas tribulações, para que, pela consolação com que nós mesmos somos consolados por Deus, possamos consolar os que estão em qualquer angústia!

[[v54-1-5]]

^<<v54-1-5,5>>^ Com efeito, à medida que em nós crescem os sofrimentos de Cristo, crescem também por Cristo as nossas consolações.

[[v54-1-6]]

^<<v54-1-6,6>>^ Se, pois, somos atribulados, é para vossa consolação e salvação. Se somos consolados, é para vossa consolação, a qual se efetua em vós pela paciência em tolerar os sofrimentos que nós mesmos suportamos.

[[v54-1-7]]

^<<v54-1-7,7>>^ A nossa esperança a respeito de vós é firme: sabemos que, como sois companheiros das nossas aflições, assim também o sereis da nossa consolação.

[[v54-1-8]]

^<<v54-1-8,8>>^ Não queremos, irmãos, que ignoreis a tribulação que nos sobreveio na Ásia. Fomos maltratados ali desmedidamente, além das nossas forças, a ponto de termos perdido a esperança de sair com vida.^&#42;1^

[[v54-1-9]]

^<<v54-1-9,9>>^ Sentíamos dentro de nós mesmos a sentença de morte, para que aprendêssemos a pôr a nossa confiança não em nós, mas em Deus, que ressuscita os mortos.

[[v54-1-10]]

^<<v54-1-10,10>>^ Ele nos livrou e nos livrará de tamanhos perigos de morte. Sim, esperamos que ainda nos livrará

[[v54-1-11]]

^<<v54-1-11,11>>^ se nos ajudardes também vós com orações em nossa intenção. Assim essa graça, obtida por intervenção de muitas pessoas, lhes será ocasião de agradecer a Deus a nosso respeito.

[[v54-1-12]]

^<<v54-1-12,12>>^ A razão da nossa glória é esta: o testemunho da nossa consciência de que, no mundo e particularmente entre vós, temos agido com santidade e sinceridade diante de Deus, não conforme o espírito de sabedoria do mundo, mas com o socorro da graça de Deus.^&#42;1^

[[v54-1-13]]

^<<v54-1-13,13>>^ Em verdade, não vos queremos dizer coisa alguma diferente da que ledes em nossas cartas, e que compreendeis. E espero que reconheçais até o fim,

[[v54-1-14]]

^<<v54-1-14,14>>^ como aliás já o tendes em parte reconhecido, que nós somos a vossa glória, exatamente como vós sereis a nossa, no dia do Senhor Jesus.

[[v54-1-15]]

^<<v54-1-15,15>>^ Foi nesta persuasão que eu resolvera primeiro ir ter convosco, para que recebêsseis uma dupla alegria:

[[v54-1-16]]

^<<v54-1-16,16>>^ eu passaria por vós ao dirigir-me à Macedônia e, ao voltar da Macedônia, iria novamente visitar-vos e de lá seria por vós conduzido até a Judeia.

[[v54-1-17]]

^<<v54-1-17,17>>^ Formando esse plano, terei usado de leviandade? Ou são puramente humanas as resoluções que tomo, de modo que haja em mim o “sim” e depois o “não”?

[[v54-1-18]]

^<<v54-1-18,18>>^ Deus é testemunha de que, quando vos dirijo a palavra, não existe um “sim” e depois um “não”.

[[v54-1-19]]

^<<v54-1-19,19>>^ O Filho de Deus, Jesus Cristo, que nós, Silvano, Timóteo e eu, vos temos anunciado, não foi “sim” e depois “não”, mas sempre foi “sim”.

[[v54-1-20]]

^<<v54-1-20,20>>^ Porque todas as promessas de Deus são “sim” em Jesus. Por isso, é por ele que nós dizemos Amém à glória de Deus.

[[v54-1-21]]

^<<v54-1-21,21>>^ Ora, quem nos confirma a nós e a vós em Cristo, e nos consagrou, é Deus.

[[v54-1-22]]

^<<v54-1-22,22>>^ Ele nos marcou com o seu selo e deu aos nossos corações o penhor do Espírito.^&#42;1^

[[v54-1-23]]

^<<v54-1-23,23>>^ Invoco a Deus por testemunha: juro por minha vida que foi para vos poupar que não voltei a Corinto.

[[v54-1-24]]

^<<v54-1-24,24>>^ Não porque pretendamos dominar sobre a vossa fé. Queremos apenas contribuir para a vossa alegria, porque, quanto à fé, estais firmes.

'''

xref:053-i-corintios/053-i-corintios-016.adoc#v53-16-0[&#60; Capítulo Anterior] | <<v54-1-0,Topo>> | xref:054-ii-corintios/054-ii-corintios-002.adoc#v54-2-0[Próximo Capítulo &#62;]