include::./index.adoc[]

[[v54-3-0]]
=== II Coríntios, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em 2 Coríntios 3, Paulo fala sobre a superioridade do ministério do Novo Testamento em relação ao ministério do Antigo Testamento, enfatizando a superioridade da mensagem do evangelho de Cristo sobre a Lei de Moisés. Ele também destaca a natureza transformadora da mensagem de Cristo, que traz liberdade e vida em contraste com a "lei da morte" que a Lei de Moisés representava.
* Romanos 7:6 - "Mas agora, por morrermos para aquilo a que estávamos sujeitos, fomos libertados da lei, para servirmos em novidade de espírito, e não na velhice da letra." Este versículo fala da libertação da Lei de Moisés que o evangelho traz, em contraste com o legalismo que caracterizava o judaísmo.
* Gálatas 3:24-25 - "De maneira que a lei nos serviu de aio, para nos conduzir a Cristo, para que pela fé fôssemos justificados. Mas, depois que veio a fé, já não estamos debaixo de aio." Paulo usa essa metáfora da "lei como aio" para explicar como a Lei de Moisés levou as pessoas a Cristo, mas que agora, com a fé em Cristo, a Lei não é mais necessária.
* 1 Pedro 1:23 - "Sendo de novo gerados, não de semente corruptível, mas da incorruptível, pela palavra de Deus, viva e que permanece para sempre." Pedro destaca a natureza transformadora da Palavra de Deus, que traz vida e renovação.
* 2 Coríntios 5:17 - "Assim que, se alguém está em Cristo, nova criatura é: as coisas velhas já passaram; eis que tudo se fez novo." Paulo enfatiza a transformação radical que ocorre na vida de alguém quando ele é reconciliado com Deus por meio de Cristo.
* Hebreus 8:13 - "Dizendo novo testamento, envelheceu o primeiro. Ora, o que foi tornado velho, e se envelhece, perto está de acabar." Este versículo enfatiza a superioridade do novo pacto em Cristo em relação ao Antigo Testamento, que estava ficando obsoleto.
****

[[v54-3-1]]

^<<v54-3-1,1>>^ Recomeçamos a fazer o nosso próprio elogio? Temos, acaso, como alguns, necessidade de vos apresentar ou receber de vós carta de recomendação?

[[v54-3-2]]

^<<v54-3-2,2>>^ Vós mesmos sois a nossa carta, escrita em nossos corações, conhecida e lida por todos os homens.

[[v54-3-3]]

^<<v54-3-3,3>>^ Não há dúvida de que vós sois uma carta de Cristo, redigida por nosso ministério e escrita, não com tinta, mas com o Espírito de Deus vivo, não em tábuas de pedra, mas em tábuas de carne, isto é, em vossos corações.

[[v54-3-4]]

^<<v54-3-4,4>>^ Tal é a convicção que temos em Deus por Cristo.

[[v54-3-5]]

^<<v54-3-5,5>>^ Não que sejamos capazes por nós mesmos de ter algum pensamento, como de nós mesmos. Nossa capacidade vem de Deus.

[[v54-3-6]]

^<<v54-3-6,6>>^ Ele é que nos fez aptos para ser ministros da Nova Aliança, não a da letra, e sim a do Espírito. Porque a letra mata, mas o Espírito vivifica.

[[v54-3-7]]

^<<v54-3-7,7>>^ Ora, se o ministério da morte, gravado com letras em pedras, se revestiu de tal glória que os filhos de Israel não podiam fitar os olhos no rosto de Moisés, por causa do resplendor de sua face (embora transitório),^&#42;1^

[[v54-3-8]]

^<<v54-3-8,8>>^ quanto mais glorioso não será o ministério do Espírito!^&#42;1^

[[v54-3-9]]

^<<v54-3-9,9>>^ Se o ministério da condenação já foi glorioso, muito mais o há de sobrepujar em glória o ministério da justificação!

[[v54-3-10]]

^<<v54-3-10,10>>^ Aliás, sob esse aspecto e em comparação dessa glória eminentemente superior, empalidece a glória do primeiro ministério.

[[v54-3-11]]

^<<v54-3-11,11>>^ Se o transitório era glorioso, muito mais glorioso é o que permanece!

[[v54-3-12]]

^<<v54-3-12,12>>^ Em posse de tal esperança, procedemos com total desassombro.

[[v54-3-13]]

^<<v54-3-13,13>>^ Não fazemos como Moisés, que cobria o rosto com um véu para que os filhos de Israel não fixassem os olhos no fim daquilo que era transitório.^&#42;1^

[[v54-3-14]]

^<<v54-3-14,14>>^ Em consequência, a inteligência deles permaneceu obscurecida. Ainda agora, quando leem o Antigo Testamento, esse mesmo véu permanece abaixado, porque é só em Cristo que ele deve ser levantado.

[[v54-3-15]]

^<<v54-3-15,15>>^ Por isso, até o dia de hoje, quando leem Moisés, um véu cobre-lhes o coração.

[[v54-3-16]]

^<<v54-3-16,16>>^ Esse véu só será tirado quando se converterem ao Senhor.

[[v54-3-17]]

^<<v54-3-17,17>>^ Ora, o Senhor é Espírito e, onde está o Espírito do Senhor, aí há liberdade.^&#42;1^

[[v54-3-18]]

^<<v54-3-18,18>>^ Mas todos nós temos o rosto descoberto, refletimos como num espelho a glória do Senhor e nos vemos transformados nessa mesma imagem, sempre mais resplandecentes, pela ação do Espírito do Senhor.

'''

xref:054-ii-corintios/054-ii-corintios-002.adoc#v54-2-0[&#60; Capítulo Anterior] | <<v54-3-0,Topo>> | xref:054-ii-corintios/054-ii-corintios-004.adoc#v54-4-0[Próximo Capítulo &#62;]