include::./index.adoc[]

[[v54-9-0]]
=== II Coríntios, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Coríntios 9 trata da generosidade cristã, encorajando os crentes a dar com alegria e de acordo com o que eles têm, sabendo que Deus abençoará e multiplicará seus recursos. O capítulo enfatiza que a doação deve ser feita de livre vontade e não por obrigação, e que o objetivo é abençoar os outros e glorificar a Deus. Abaixo estão cinco versículos relacionados com os temas abordados em 2 Coríntios 9:
* Provérbios 11:25: "A alma generosa prosperará e aquele que regar também será regado." Este versículo destaca que aqueles que são generosos serão abençoados com prosperidade e que aqueles que ajudam os outros também serão ajudados.
* Lucas 6:38: "Dai e dar-se-vos-á; boa medida, recalcada, sacudida e transbordando vos deitarão no regaço; porque com a mesma medida com que medirdes também vos medirão de novo." Jesus ensina aqui que, quando damos, receberemos de volta em proporção ainda maior.
* Provérbios 3:9-10: "Honra ao Senhor com os teus bens, e com a primeira parte de todos os teus ganhos; e se encherão os teus celeiros, e transbordarão de vinho os teus lagares." Este versículo ensina que a generosidade para com Deus e os outros resulta em bênçãos materiais abundantes.
* Mateus 25:40: "Em verdade vos digo que, sempre que o fizestes a um destes meus irmãos, mesmo dos mais pequeninos, a mim o fizestes." Jesus ensina que ajudar os outros é como ajudá-lo pessoalmente, incentivando os crentes a serem generosos e compassivos.
* Atos 20:35: "Em tudo vos tenho mostrado que assim, trabalhando, é necessário auxiliar os enfermos e recordar as palavras do Senhor Jesus, que disse: Mais bem-aventurado é dar do que receber." Paulo cita as palavras de Jesus para enfatizar a alegria e a bênção de dar, encorajando os crentes a viverem em generosidade e serviço aos outros.
****

[[v54-9-1]]

^<<v54-9-1,1>>^ Com respeito ao auxílio a prestar aos irmãos, acho quase supérfluo continuar a escrever-vos.

[[v54-9-2]]

^<<v54-9-2,2>>^ Porquanto estou ciente de vossa boa vontade, que enalteço, para glória vossa, ante os macedônios, dizendo-lhes que a Acaia também está pronta desde o ano passado. O exemplo de vosso zelo tem estimulado a muitos.

[[v54-9-3]]

^<<v54-9-3,3>>^ Eu, porém, vos enviei os nossos irmãos para que o louvor que dissemos a vosso respeito, nesse particular, não se tornasse vão e para que, como tenho dito, estejais prevenidos.

[[v54-9-4]]

^<<v54-9-4,4>>^ Eu temia que, se os macedônios fossem comigo e vós não estivésseis preparados, essa certeza redundasse para confusão nossa, para não dizer vossa.

[[v54-9-5]]

^<<v54-9-5,5>>^ Por esse motivo, julguei necessário rogar aos irmãos que nos precedessem junto de vós e preparassem em tempo a generosidade prometida. Assim, será verdadeiramente uma liberalidade, e não uma mesquinhez.

[[v54-9-6]]

^<<v54-9-6,6>>^ Convém lembrar: aquele que semeia pouco, pouco ceifará. Aquele que semeia em profusão, em profusão ceifará.

[[v54-9-7]]

^<<v54-9-7,7>>^ Dê cada um conforme o impulso do seu coração, sem tristeza nem constrangimento. Deus ama o que dá com alegria.^&#42;1^

[[v54-9-8]]

^<<v54-9-8,8>>^ Poderoso é Deus para cumular-vos com toda a espécie de benefícios, para que, tendo sempre e em todas as coisas o necessário, vos sobre ainda muito para toda espécie de boas obras.

[[v54-9-9]]

^<<v54-9-9,9>>^ Como está escrito: Espalhou, deu aos pobres, a sua justiça subsiste para sempre (Sl 111,9).

[[v54-9-10]]

^<<v54-9-10,10>>^ Aquele que dá a semente ao semeador e o pão para comer, vos dará rica sementeira e aumentará os frutos da vossa justiça.

[[v54-9-11]]

^<<v54-9-11,11>>^ Assim, enriquecidos em todas as coisas, podereis exercer toda espécie de generosidade que, por nosso intermédio, será ocasião de agradecer a Deus.

[[v54-9-12]]

^<<v54-9-12,12>>^ Realmente, o serviço dessa obra de caridade não só provê as necessidades dos irmãos, mas é também uma abundante fonte de ações de graças a Deus.

[[v54-9-13]]

^<<v54-9-13,13>>^ Pois, ao reconhecer a experimentada virtude que essa assistência revela da vossa parte, eles glorificam a Deus pela obediência que professais relativamente ao Evangelho de Cristo e pela generosidade de vossas esmolas em favor deles e em favor de todos.

[[v54-9-14]]

^<<v54-9-14,14>>^ Além disso, eles oram por vós e vos dedicam a mais terna afeição em vista da eminente graça que Deus vos fez.

[[v54-9-15]]

^<<v54-9-15,15>>^ Graças sejam dadas a Deus pelo seu dom inefável!

'''

xref:054-ii-corintios/054-ii-corintios-008.adoc#v54-8-0[&#60; Capítulo Anterior] | <<v54-9-0,Topo>> | xref:054-ii-corintios/054-ii-corintios-010.adoc#v54-10-0[Próximo Capítulo &#62;]