include::./index.adoc[]

[[v54-6-0]]
=== II Coríntios, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 6 de 2 Coríntios trata de questões relacionadas ao ministério cristão e à comunhão com Deus. Paulo fala sobre a necessidade de se separar do mundo e de viver uma vida consagrada a Deus, enfatizando a importância da graça de Deus para isso. Ele também descreve os desafios e dificuldades que enfrenta como apóstolo, mas destaca a esperança e a vitória que tem em Cristo.
* 2 Coríntios 6:1-2 - "E, trabalhando nós juntamente com ele, também vos exortamos a que não recebais a graça de Deus em vão (porque diz: Ouvi-te em tempo aceitável e socorri-te no dia da salvação; eis aqui agora o tempo aceitável, eis aqui agora o dia da salvação)." Paulo enfatiza a importância de receber a graça de Deus e de se arrepender em tempo hábil, destacando a urgência da salvação.
* 2 Coríntios 6:14 - "Não vos prendais a um jugo desigual com os incrédulos; pois que sociedade tem a justiça com a injustiça? ou que comunhão tem a luz com as trevas?" Paulo adverte os coríntios a não se unirem a incrédulos em seus esforços ministeriais ou em suas vidas pessoais, enfatizando a necessidade de manter uma separação do mundo.
* 2 Coríntios 6:17 - "Por isso saí do meio deles, e apartai-vos, diz o Senhor; e não toqueis nada imundo, e eu vos receberei." Paulo cita Isaías para enfatizar a importância de se separar do mundo e de se consagrar a Deus, afirmando que isso resultará em uma comunhão mais profunda com Ele.
* 2 Coríntios 6:4-5 - "Mas em tudo recomendando-nos a nós mesmos como ministros de Deus; na muita paciência, nas aflições, nas necessidades, nas angústias, nos açoites, nas prisões, nos tumultos, nos trabalhos, na vigília, nos jejuns." Paulo descreve os desafios que enfrenta como apóstolo, incluindo perseguições e dificuldades, enfatizando a necessidade de perseverança e de recomendar-se como um ministro de Deus.
* 2 Coríntios 6:18 - "E eu serei para vós Pai, e vós sereis para mim filhos e filhas, diz o Senhor Todo-Poderoso." Paulo encerra o capítulo com uma citação de Isaías, enfatizando a promessa de que aqueles que se separam do mundo e se consagram a Deus serão considerados filhos e filhas Dele.
****

[[v54-6-1]]

^<<v54-6-1,1>>^ Na qualidade de colaboradores seus, exortamo-vos a que não recebais a graça de Deus em vão.

[[v54-6-2]]

^<<v54-6-2,2>>^ Pois ele diz: Eu te ouvi no tempo favorável e te ajudei no dia da salvação (Is 49,8). Agora é o tempo favorável, agora é o dia da salvação.

[[v54-6-3]]

^<<v54-6-3,3>>^ A ninguém damos qualquer motivo de escândalo, para que o nosso ministério não seja criticado.

[[v54-6-4]]

^<<v54-6-4,4>>^ Mas em todas as coisas nos apresentamos como ministros de Deus, por uma grande constância nas tribulações, nas misérias, nas angústias,

[[v54-6-5]]

^<<v54-6-5,5>>^ nos açoites, nos cárceres, nos tumultos populares, nos trabalhos, nas vigílias, nas privações;

[[v54-6-6]]

^<<v54-6-6,6>>^ pela pureza, pela ciência, pela longanimidade, pela bondade, pelo Espírito Santo, por uma caridade sincera,

[[v54-6-7]]

^<<v54-6-7,7>>^ pela palavra da verdade, pelo poder de Deus; pelas armas da justiça ofensivas e defensivas,^&#42;1^

[[v54-6-8]]

^<<v54-6-8,8>>^ por meio da honra e da desonra, da boa e da má fama.

[[v54-6-9]]

^<<v54-6-9,9>>^ Tidos por impostores, somos, no entanto, sinceros; por desconhecidos, somos bem conhecidos; por agonizantes, estamos com vida; por condenados e, no entanto, estamos livres da morte.

[[v54-6-10]]

^<<v54-6-10,10>>^ Somos julgados tristes, nós que estamos sempre contentes; indigentes, porém enriquecendo a muitos; sem posses, nós que tudo possuímos!

[[v54-6-11]]

^<<v54-6-11,11>>^ Ó coríntios, acabamos de vos falar com toda a franqueza. O nosso coração está todo ele aberto.

[[v54-6-12]]

^<<v54-6-12,12>>^ Não é estreito o lugar que nele ocupais. Estreito, isso sim, é vosso íntimo.

[[v54-6-13]]

^<<v54-6-13,13>>^ Correspondei-me com igual ternura. Falo como a meus filhos: também vós outros abri largamente os vossos corações.

[[v54-6-14]]

^<<v54-6-14,14>>^ Não vos prendais ao mesmo jugo com os infiéis. Que união pode haver entre a justiça e a iniquidade? Ou que comunidade entre a luz e as trevas?

[[v54-6-15]]

^<<v54-6-15,15>>^ Que compatibilidade pode haver entre Cristo e Belial? Ou que acordo entre o fiel e o infiel?^&#42;1^

[[v54-6-16]]

^<<v54-6-16,16>>^ Como conciliar o Templo de Deus e os ídolos? Porque somos o Templo de Deus vivo, como o próprio Deus disse: Eu habitarei e andarei entre eles, e serei o seu Deus e eles serão o meu povo (Lv 26,11s).

[[v54-6-17]]

^<<v54-6-17,17>>^ Portanto, saí do meio deles e separai-vos, diz o Senhor. Não toqueis no que é impuro, e vos receberei.

[[v54-6-18]]

^<<v54-6-18,18>>^ Serei para vós um Pai e vós sereis para mim filhos e filhas, diz o Senhor Todo-poderoso (Is 52,11; Jr 31,9).

'''

xref:054-ii-corintios/054-ii-corintios-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:054-ii-corintios/054-ii-corintios-007.adoc#v54-7-0[Próximo Capítulo &#62;]