include::./index.adoc[]

[[v20-11-0]]
=== Jó, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em Jó 11, Zofar, um dos amigos de Jó, expressa sua opinião sobre a situação do seu amigo e oferece conselhos sobre como ele deveria agir. Zofar sugere que Jó está sofrendo porque merece, e que a solução para os seus problemas é arrepender-se e buscar a Deus. Os versículos relacionados aos temas abordados em Jó 11 são:
* Jó 4:7 - "Lembra-te agora: quem jamais pereceu, sendo inocente? Ou onde foram destruídos os retos?" Zofar sugere que o sofrimento de Jó é um castigo merecido, e que ele deve ter cometido algum pecado para estar passando por isso. Este versículo fala sobre a ideia de que as pessoas só sofrem se merecerem, o que é uma crença comum na época de Jó.
* Provérbios 3:11-12 - "Filho meu, não desprezes a correção do SENHOR, nem te desanimes quando por ele fores repreendido; porque o SENHOR repreende a quem ama, assim como o pai, ao filho a quem quer bem." Zofar acredita que o sofrimento de Jó é um castigo de Deus, mas esse versículo mostra que a correção divina não é necessariamente um castigo, mas um ato de amor e cuidado.
* Jó 9:20 - "Ainda que eu fosse justo, a minha própria boca me condenaria; ainda que eu fosse íntegro, ele me provaria perverso." Zofar sugere que Jó deve se arrepender e buscar a Deus para acabar com o seu sofrimento, mas este versículo fala sobre a dificuldade de alguém que é inocente em defender-se de acusações.
* Salmos 34:19 - "Muitas são as aflições do justo, mas o SENHOR o livra de todas." Zofar acredita que Jó só está sofrendo porque merece, mas este versículo mostra que o sofrimento pode acontecer mesmo com pessoas justas, e que Deus é capaz de livrar o justo de todas as suas aflições.
* Isaías 40:31 - "Mas os que esperam no SENHOR renovarão as suas forças e subirão com asas como águias; correrão e não se cansarão; caminharão e não se fatigarão." Zofar sugere que a solução para o sofrimento de Jó é arrepender-se e buscar a Deus, e este versículo fala sobre a importância da esperança e da confiança em Deus para enfrentar os desafios da vida.
****

[[v20-11-1]]

^<<v20-11-1,1>>^ Então, Sofar de Naamat tomou a palavra nestes termos:

[[v20-11-2]]

^<<v20-11-2,2>>^ “Ficará sem resposta o que fala muito? Terá razão o grande falador?

[[v20-11-3]]

^<<v20-11-3,3>>^ Tua loquacidade fará calar os demais? Zombarás sem que ninguém te repreenda?

[[v20-11-4]]

^<<v20-11-4,4>>^ Dizes: ‘Minha opinião é a verdadeira, sou puro aos teus olhos’.

[[v20-11-5]]

^<<v20-11-5,5>>^ Oxalá Deus pudesse falar e abrir seus lábios para te responder.

[[v20-11-6]]

^<<v20-11-6,6>>^ Se te revelasse os mistérios da sabedoria, que são ambíguos para o espírito, saberias então que Deus esquece uma parte de tua iniquidade.^&#42;1^

[[v20-11-7]]

^<<v20-11-7,7>>^ Pretendes sondar as profundezas divinas, atingir a perfeição do Todo-poderoso?

[[v20-11-8]]

^<<v20-11-8,8>>^ Ela é mais alta do que o céu! Que podes tu fazer? É mais profunda que os infernos! Que podes tu saber?

[[v20-11-9]]

^<<v20-11-9,9>>^ É mais longa que a terra, mais larga que o mar.

[[v20-11-10]]

^<<v20-11-10,10>>^ Se ele surge para aprisionar, se apela à justiça, quem o impedirá?

[[v20-11-11]]

^<<v20-11-11,11>>^ Pois ele conhece os malfeitores, descobre a iniquidade, presta atenção.

[[v20-11-12]]

^<<v20-11-12,12>>^ Diante disso, uma pessoa insensata pode criar juízo, e um asno tornar-se criatura humana.^&#42;1^

[[v20-11-13]]

^<<v20-11-13,13>>^ Se voltares teu coração para Deus, e para ele estenderes os braços;

[[v20-11-14]]

^<<v20-11-14,14>>^ se afastares de tuas mãos o mal e não abrigares a iniquidade debaixo de tua tenda,

[[v20-11-15]]

^<<v20-11-15,15>>^ então poderás erguer a fronte sem mancha; serás estável, sem mais nenhum temor.

[[v20-11-16]]

^<<v20-11-16,16>>^ Esquecerás daí por diante as tuas penas, como águas que passaram, serão apenas uma lembrança.

[[v20-11-17]]

^<<v20-11-17,17>>^ O futuro te será mais brilhante do que o meio-dia, as trevas se transformarão em aurora.

[[v20-11-18]]

^<<v20-11-18,18>>^ Terás confiança e ficarás cheio de esperança. Olhando em volta de ti, dormirás tranquilo.

[[v20-11-19]]

^<<v20-11-19,19>>^ Repousarás sem que ninguém te inquiete e muitos acariciarão o teu rosto.

[[v20-11-20]]

^<<v20-11-20,20>>^ Porém, os olhos dos maus serão consumidos, para eles, nenhum refúgio, e não terão outra esperança senão em seu último suspiro”.

'''

xref:020-jo/020-jo-010.adoc#v20-10-0[&#60; Capítulo Anterior] | <<v20-11-0,Topo>> | xref:020-jo/020-jo-012.adoc#v20-12-0[Próximo Capítulo &#62;]