include::./index.adoc[]

[[v20-18-0]]
=== Jó, 18
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jó 18 apresenta o segundo discurso de Bildade, em que ele continua argumentando que a punição de Jó é resultado de seu próprio pecado. Ele descreve a destruição que virá sobre os ímpios e como suas vidas serão arruinadas. Os versículos abaixo são relacionados aos temas abordados em Jó 18:
* Jó 8:13: "Tais são as sendas de todos os que se esquecem de Deus; e a esperança do ímpio perecerá." Bildade acredita que a situação de Jó é resultado de sua falta de lembrança de Deus e de sua esperança ímpia.
* Provérbios 14:32: "No seu mal o ímpio é derribado, mas os justos até na morte têm refúgio." Bildade fala da destruição que virá sobre os ímpios, que serão derrubados em seu mal.
* Salmos 1:4-5: "Os ímpios não são assim; são, porém, como a palha que o vento dispersa. Por isso os ímpios não subsistirão no juízo, nem os pecadores na congregação dos justos." Bildade descreve a destruição que virá sobre os ímpios e sua incapacidade de subsistir no juízo.
* Isaías 8:22: "E olharão para a terra, e eis aí a angústia e escuridão, e sombras de tristeza; e serão empurrados para a escuridão." Bildade fala da escuridão que virá sobre os ímpios e como eles serão empurrados para ela.
* Salmos 35:8: "Caia sobre ele a destruição que não espera, e apanhe-o a rede que escondeu, caia ele na mesma destruição." Bildade fala sobre como a destruição virá sobre os ímpios de uma maneira que não esperam e como eles cairão na mesma destruição que prepararam.
****

[[v20-18-1]]

^<<v20-18-1,1>>^ Bildad de Suás disse então nestes termos:

[[v20-18-2]]

^<<v20-18-2,2>>^ “Quando acabarás de falar a esmo? Terás a sabedoria de nos dizer depois!

[[v20-18-3]]

^<<v20-18-3,3>>^ Por que nos consideras como animais, e por que passamos por estúpidos a teus olhos?

[[v20-18-4]]

^<<v20-18-4,4>>^ Tu, que te rasgas em teu furor, por tua causa a terra ficará abandonada e o rochedo mudará de lugar?

[[v20-18-5]]

^<<v20-18-5,5>>^ Sim, a luz do ímpio se apagará e a chama de seu fogo cessará de alumiar.

[[v20-18-6]]

^<<v20-18-6,6>>^ A luz obscurece na sua tenda e sua lâmpada sobre ele se apagará.

[[v20-18-7]]

^<<v20-18-7,7>>^ Seus passos, antes firmes, serão encurtados, e seus próprios desígnios os farão tropeçar.

[[v20-18-8]]

^<<v20-18-8,8>>^ Seus pés se prendem numa rede, e ele anda sobre malhas.

[[v20-18-9]]

^<<v20-18-9,9>>^ A armadilha agarra seu calcanhar e o alçapão o aperta.

[[v20-18-10]]

^<<v20-18-10,10>>^ Uma corda se esconde na terra para pegá-lo, e uma armadilha, ao longo da vereda.

[[v20-18-11]]

^<<v20-18-11,11>>^ De todas as partes temores o amedrontam e o perseguem passo a passo.

[[v20-18-12]]

^<<v20-18-12,12>>^ A calamidade vem faminta sobre ele e a infelicidade está alerta ao seu lado.

[[v20-18-13]]

^<<v20-18-13,13>>^ A pele de seu corpo é devorada, o filho mais velho da morte devora-lhe os membros.^&#42;1^

[[v20-18-14]]

^<<v20-18-14,14>>^ É arrancado da tenda, onde se sentia seguro, levam-no ao rei dos terrores.^&#42;1^

[[v20-18-15]]

^<<v20-18-15,15>>^ Podes estabelecer-te em sua tenda, que não mais existe; o enxofre é espalhado em seu domínio.

[[v20-18-16]]

^<<v20-18-16,16>>^ Por baixo suas raízes secam, e por cima seus ramos definham.

[[v20-18-17]]

^<<v20-18-17,17>>^ Sua memória apaga-se da terra, nada mais lembra o seu nome na região.

[[v20-18-18]]

^<<v20-18-18,18>>^ É arrojado da luz para as trevas e é desterrado do mundo.

[[v20-18-19]]

^<<v20-18-19,19>>^ Não tem descendente nem posteridade em sua tribo, nem sobrevivente algum em sua morada.

[[v20-18-20]]

^<<v20-18-20,20>>^ O Ocidente está estupefato com sua sorte e o Oriente treme diante dela.

[[v20-18-21]]

^<<v20-18-21,21>>^ Eis o que acontece com as tendas dos ímpios, os lugares habitados pelo homem que não conhece a Deus”.

'''

xref:020-jo/020-jo-017.adoc#v20-17-0[&#60; Capítulo Anterior] | <<v20-18-0,Topo>> | xref:020-jo/020-jo-019.adoc#v20-19-0[Próximo Capítulo &#62;]