include::./index.adoc[]

[[v20-27-0]]
=== Jó, 27
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jó 27 é um capítulo em que Jó continua a falar sobre sua retidão e a injustiça que lhe aconteceu, enquanto seus amigos o acusam de ter feito algo errado para merecer tais aflições. Jó afirma sua inocência e acredita que Deus é justo e irá punir os maus. Abaixo estão cinco versículos relacionados com os temas abordados em Jó 27:
* Provérbios 11:18: "O ímpio recebe salário enganoso, mas quem semeia justiça colherá verdadeira recompensa." Este versículo enfatiza a crença de Jó na justiça divina, que Deus irá punir os ímpios e recompensar os justos.
* Salmos 34:21: "O mal matará o ímpio, e os que odeiam o justo serão condenados." Jó acredita que aqueles que o acusam são ímpios e Deus irá puni-los.
* Salmos 37:28: "Pois o Senhor ama a justiça e não abandona os seus fiéis; eles sempre serão protegidos, mas a descendência dos ímpios será exterminada." Jó acredita que Deus irá proteger os justos e punir os ímpios.
* Provérbios 10:25: "Como a tempestade repentina, que passa e logo se vai, assim é o ímpio que prospera, sem que se saiba de onde vem a desgraça." Jó acredita que a prosperidade dos ímpios é temporária e que a desgraça os atingirá.
* Salmos 9:16: "O Senhor é conhecido pela justiça que exerce; os ímpios caem em suas próprias armadilhas." Este versículo enfatiza a crença de Jó de que Deus é justo e que os ímpios serão punidos por suas más ações.
****

[[v20-27-1]]

^<<v20-27-1,1>>^ Jó continuou seu discurso nestes termos:

[[v20-27-2]]

^<<v20-27-2,2>>^ “Pelo Deus vivo que me recusa justiça, pelo Todo-poderoso, que enche minha alma de amargura.

[[v20-27-3]]

^<<v20-27-3,3>>^ Enquanto em mim restar alento e o sopro de Deus passar por minhas narinas,

[[v20-27-4]]

^<<v20-27-4,4>>^ meus lábios não falarão maldades e minha língua não proferirá mentiras.

[[v20-27-5]]

^<<v20-27-5,5>>^ Longe de mim dar-vos razão! Até meu último suspiro defenderei minha inocência,

[[v20-27-6]]

^<<v20-27-6,6>>^ mantenho firme minha justiça, não a abandonarei; minha consciência não acusa nenhum de meus dias.

[[v20-27-7]]

^<<v20-27-7,7>>^ Que meu inimigo seja tratado como ímpio e meu adversário, como perverso!

[[v20-27-8]]

^<<v20-27-8,8>>^ Que pode esperar o ímpio de sua oração, quando eleva para Deus a sua alma?

[[v20-27-9]]

^<<v20-27-9,9>>^ Deus escutará seu clamor, quando a angústia cair sobre ele?

[[v20-27-10]]

^<<v20-27-10,10>>^ Encontrará ele seu conforto no Todo-poderoso e invocará ele Deus em todo o tempo?

[[v20-27-11]]

^<<v20-27-11,11>>^ Eu vos ensinarei o poder de Deus, não vos ocultarei os desígnios do Todo-poderoso.

[[v20-27-12]]

^<<v20-27-12,12>>^ Mas todos vós já o sabeis; por que proferis palavras vãs?

[[v20-27-13]]

^<<v20-27-13,13>>^ Esta é a sorte que Deus reserva ao ímpio e a parte reservada ao violento pelo Todo-poderoso.^&#42;1^

[[v20-27-14]]

^<<v20-27-14,14>>^ Se seus filhos se multiplicam, é para a espada e seus descendentes não terão o que comer.

[[v20-27-15]]

^<<v20-27-15,15>>^ Seus sobreviventes serão sepultados na ruína e suas viúvas não os chorarão.

[[v20-27-16]]

^<<v20-27-16,16>>^ Se amontoa prata como pó e se ajunta vestimentas como barro,

[[v20-27-17]]

^<<v20-27-17,17>>^ que amontoe, mas é o justo quem as vestirá e o inocente herdará a prata.

[[v20-27-18]]

^<<v20-27-18,18>>^ Constrói sua casa como a casa da aranha, como a choupana que o vigia constrói.^&#42;1^

[[v20-27-19]]

^<<v20-27-19,19>>^ Deita-se rico, mas é pela última vez. Quando abre os olhos, já deixou de sê-lo.

[[v20-27-20]]

^<<v20-27-20,20>>^ O terror o invade como um dilúvio e um redemoinho o arrebata durante a noite.

[[v20-27-21]]

^<<v20-27-21,21>>^ O vento do leste o leva e o faz desaparecer, varrendo-o violentamente de seu lugar.

[[v20-27-22]]

^<<v20-27-22,22>>^ Precipitam-se sobre ele sem compaixão e é arrastado numa fuga desvairada.

[[v20-27-23]]

^<<v20-27-23,23>>^ Sua ruína é aplaudida. De sua própria casa assobiarão sobre ele.

'''

xref:020-jo/020-jo-026.adoc#v20-26-0[&#60; Capítulo Anterior] | <<v20-27-0,Topo>> | xref:020-jo/020-jo-028.adoc#v20-28-0[Próximo Capítulo &#62;]