include::./index.adoc[]

[[v20-29-0]]
=== Jó, 29
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jó 29 é um capítulo em que Jó relembra seus dias de prosperidade, quando era respeitado e admirado por todos ao seu redor. Ele fala sobre a sua reputação, a sua riqueza e as honrarias que recebeu. Os versículos abaixo foram escolhidos por abordarem temas relacionados a essas lembranças e à posição de destaque que Jó tinha na sociedade:
* Provérbios 22:1: "Mais digno de ser escolhido é o bom nome do que as muitas riquezas; e a boa fama vale mais do que a prata e o ouro." Jó tinha um nome respeitado e uma boa fama, que valiam mais do que qualquer riqueza material.
* Salmos 112:1-3: "Bem-aventurado o homem que teme ao Senhor e se compraz nos seus mandamentos. A sua descendência será poderosa na terra; a geração dos retos será abençoada. Na sua casa há prosperidade e riqueza, e a sua justiça permanece para sempre." Jó era um homem justo e temente a Deus, o que lhe trouxe prosperidade e riqueza em sua vida.
* Eclesiastes 7:1: "Melhor é a boa fama do que o melhor perfume, e o dia da morte do que o dia do nascimento." A boa fama de Jó era mais valiosa do que qualquer perfume ou bem material.
* Jó 12:4: "Sou motivo de riso para os meus amigos; eu, que invoco a Deus e ele me responde; sou motivo de zombaria, um justo, um homem íntegro." Jó, mesmo sendo justo e íntegro, passou a ser motivo de riso para seus amigos depois de ter perdido tudo.
* Salmos 25:14: "O segredo do Senhor é para os que o temem, e ele lhes fará saber o seu concerto." Jó tinha um relacionamento profundo com Deus e sabia que a sua justiça e retidão eram reconhecidas por Ele, mesmo que seus amigos não entendessem.
****

[[v20-29-1]]

^<<v20-29-1,1>>^ Jó continuou seu discurso nestes termos:

[[v20-29-2]]

^<<v20-29-2,2>>^ “Quem me dera tornar-me tal como antes, como nos dias em que Deus me protegia,

[[v20-29-3]]

^<<v20-29-3,3>>^ quando a sua lâmpada luzia sobre a minha cabeça e à sua luz me guiava nas trevas!

[[v20-29-4]]

^<<v20-29-4,4>>^ Tal como era nos dias de meu outono, quando Deus velava como um amigo sobre minha tenda!

[[v20-29-5]]

^<<v20-29-5,5>>^ Quando o Todo-poderoso estava ainda comigo e os meus filhos, em volta de mim!

[[v20-29-6]]

^<<v20-29-6,6>>^ Quando os meus pés se banhavam no creme e o rochedo em mim derramava ondas de azeite.

[[v20-29-7]]

^<<v20-29-7,7>>^ Quando saía para ir à porta da cidade e me assentava na praça pública.

[[v20-29-8]]

^<<v20-29-8,8>>^ Viam-me os jovens e se escondiam e os velhos levantavam-se e ficavam de pé.

[[v20-29-9]]

^<<v20-29-9,9>>^ Os chefes interrompiam suas conversas e punham a mão sobre a boca.

[[v20-29-10]]

^<<v20-29-10,10>>^ Calava-se a voz dos príncipes e sua língua se colava ao céu da boca.

[[v20-29-11]]

^<<v20-29-11,11>>^ Quem me ouvia me felicitava, quem me via dava testemunho de mim.^&#42;1^

[[v20-29-12]]

^<<v20-29-12,12>>^ Livrava o pobre que pedia socorro e o órfão, que não tinha apoio.

[[v20-29-13]]

^<<v20-29-13,13>>^ A bênção do moribundo vinha sobre mim e eu alegrava o coração da viúva.

[[v20-29-14]]

^<<v20-29-14,14>>^ Revestia-me de justiça e a equidade era para mim como uma roupa e um turbante.

[[v20-29-15]]

^<<v20-29-15,15>>^ Era os olhos do cego e os pés daquele que manca.

[[v20-29-16]]

^<<v20-29-16,16>>^ Era o pai dos pobres e examinava a fundo a causa dos desconhecidos.

[[v20-29-17]]

^<<v20-29-17,17>>^ Quebrava o queixo do perverso e arrancava-lhe a presa de entre os dentes.

[[v20-29-18]]

^<<v20-29-18,18>>^ E dizia: ‘Morrerei no meu ninho e meus dias serão tão numerosos quanto os da fênix’.^&#42;1^

[[v20-29-19]]

^<<v20-29-19,19>>^ Minha raiz atinge a água e o orvalho ficará durante a noite sobre meus ramos.

[[v20-29-20]]

^<<v20-29-20,20>>^ Minha glória sempre se renovará e meu arco se reforçará em minha mão.

[[v20-29-21]]

^<<v20-29-21,21>>^ Escutavam-me, esperavam e recolhiam em silêncio meu conselho.

[[v20-29-22]]

^<<v20-29-22,22>>^ Quando acabava de falar, não acrescentavam nada e minhas palavras eram recebidas como orvalho.

[[v20-29-23]]

^<<v20-29-23,23>>^ Esperavam-me como se espera a chuva e abriam a boca, como se fosse para a chuva de primavera.

[[v20-29-24]]

^<<v20-29-24,24>>^ Sorria para aqueles que perdiam coragem; ante o meu ar benevolente, deixavam de estar abatidos.

[[v20-29-25]]

^<<v20-29-25,25>>^ Quando ia ter com eles, tinha o primeiro lugar, era importante como um rei no meio de suas tropas, como o consolador dos aflitos.

'''

xref:020-jo/020-jo-028.adoc#v20-28-0[&#60; Capítulo Anterior] | <<v20-29-0,Topo>> | xref:020-jo/020-jo-030.adoc#v20-30-0[Próximo Capítulo &#62;]