include::./index.adoc[]

[[v20-7-0]]
=== Jó, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jó 7 é um capítulo em que Jó continua a lamentar sua situação, expressando seu desespero diante da dor física e emocional que está enfrentando. Ele questiona a razão de sua existência e pede a Deus que o deixe em paz. Abaixo estão cinco versículos relacionados aos temas abordados neste capítulo:
* Salmos 6:6: "Estou cansado de tanto gemer; todas as noites faço nadar a minha cama em lágrimas; inundo de pranto o meu leito." Este versículo fala sobre o cansaço emocional e físico que Jó está sentindo, com suas lágrimas inundando sua cama todas as noites.
* Salmos 13:2: "Até quando, Senhor? Esquecer-te-ás de mim para sempre? Até quando ocultarás de mim o rosto?" Assim como Jó, o salmista se sente esquecido por Deus e questiona quanto tempo ainda terá que suportar a dor.
* Salmos 22:1-2: "Deus meu, Deus meu, por que me desamparaste? Por que estás afastado de me ajudar e das palavras do meu bramido? Deus meu, eu clamo de dia, e não me ouves; de noite, e não tenho sossego." Este salmo começa com um clamor de desespero e abandono, que reflete a dor e solidão que Jó está experimentando.
* Salmos 38:6: "Estou encurvado, estou muito abatido, ando lamentando o dia inteiro." Este versículo descreve a condição física de Jó, que está encurvado e abatido pela dor.
* Salmos 88:14: "Por que, Senhor, rejeitas a minha alma? Por que escondes de mim a tua face?" O salmista se sente abandonado por Deus e questiona a razão pela qual Deus está escondendo seu rosto. Este sentimento é compartilhado por Jó, que sente que Deus o rejeitou e o abandonou.
****

[[v20-7-1]]

^<<v20-7-1,1>>^ Não é, acaso, uma luta a vida do homem sobre a terra? Seus dias não são como os de um mercenário?

[[v20-7-2]]

^<<v20-7-2,2>>^ Como um escravo que suspira pela sombra, e um assalariado que aguarda o pagamento,

[[v20-7-3]]

^<<v20-7-3,3>>^ assim também tive por sorte meses de sofrimento e noites de dor me couberam por partilha.

[[v20-7-4]]

^<<v20-7-4,4>>^ Apenas me deito, digo: ‘Quando chegará o dia?’. Logo que me levanto: ‘Quando chegará a noite?’. E até a noite me farto de angústias.

[[v20-7-5]]

^<<v20-7-5,5>>^ Minha carne se cobre de podridão e de imundície, minha pele racha e supura.

[[v20-7-6]]

^<<v20-7-6,6>>^ Meus dias passam mais depressa do que a lançadeira, e se desvanecem sem deixar esperança.

[[v20-7-7]]

^<<v20-7-7,7>>^ Lembra-te de que minha vida nada mais é do que um sopro, de que meus olhos não mais verão a felicidade;^&#42;1^

[[v20-7-8]]

^<<v20-7-8,8>>^ o olho que me via não mais me verá, o teu me procurará, e já não existirei.

[[v20-7-9]]

^<<v20-7-9,9>>^ A nuvem se dissipa e passa, assim quem desce à região dos mortos não subirá de novo.

[[v20-7-10]]

^<<v20-7-10,10>>^ Não voltará mais à sua casa, sua morada não mais o reconhecerá.

[[v20-7-11]]

^<<v20-7-11,11>>^ E por isso não reprimirei minha língua; falarei na angústia do meu espírito, farei queixa na tristeza de minha alma.

[[v20-7-12]]

^<<v20-7-12,12>>^ Porventura, sou eu o mar, ou algum monstro marinho, para me teres posto um guarda contra mim?

[[v20-7-13]]

^<<v20-7-13,13>>^ Se eu disser: ‘Meu leito me consolará e minha cama me aliviará’,

[[v20-7-14]]

^<<v20-7-14,14>>^ então me aterrarás com sonhos, e me assustarás com visões.

[[v20-7-15]]

^<<v20-7-15,15>>^ Preferiria ser estrangulado; antes a morte do que meus tormentos!

[[v20-7-16]]

^<<v20-7-16,16>>^ Sucumbo, deixo de viver para sempre! Deixa-me em paz, pois meus dias são apenas um sopro!

[[v20-7-17]]

^<<v20-7-17,17>>^ O que é o homem para fazeres tanto caso dele, para te dignares ocupar-te dele,^&#42;1^

[[v20-7-18]]

^<<v20-7-18,18>>^ para visitá-lo todas as manhãs e prová-lo a cada instante?

[[v20-7-19]]

^<<v20-7-19,19>>^ Quando cessarás de olhar para mim, sem dar-me tempo de engolir minha saliva?

[[v20-7-20]]

^<<v20-7-20,20>>^ Se pequei, que mal te fiz, ó guarda dos homens? Por que me tomaste por alvo e me tornei pesado para ti?

[[v20-7-21]]

^<<v20-7-21,21>>^ Por que não toleras meu pecado e não apagas minha culpa? Eis que vou logo me deitar por terra; tu me procurarás, já não existirei”.

'''

xref:020-jo/020-jo-006.adoc#v20-6-0[&#60; Capítulo Anterior] | <<v20-7-0,Topo>> | xref:020-jo/020-jo-008.adoc#v20-8-0[Próximo Capítulo &#62;]