include::./index.adoc[]

[[v20-6-0]]
=== Jó, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* No capítulo 6 de Jó, o personagem continua a expressar sua angústia e tristeza diante de suas circunstâncias difíceis. Ele lamenta sua situação e sua dor, mas também questiona a ajuda que recebe dos amigos e a justiça de Deus. Abaixo estão cinco versículos relacionados aos temas abordados em Jó 6:
* Salmos 38:6: "Estou encurvado, estou muito abatido, ando lamentando o dia todo." Este versículo descreve o sentimento de angústia e desespero que Jó sente diante de suas tribulações. Ele se sente encurvado sob o peso de sua dor e lamenta constantemente.
* Salmos 42:5: "Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei pela salvação que há na sua presença." Este versículo fala sobre a importância de confiar em Deus, mesmo em meio a circunstâncias difíceis. Ele encoraja a esperar em Deus e a louvá-lo pela salvação que ele oferece.
* Salmos 69:29: "Eu, porém, estou aflito e dolorido; que o teu socorro, ó Deus, me levante." Este versículo é uma oração por socorro e ajuda em meio à aflição. É um pedido de ajuda a Deus em momentos de grande sofrimento, assim como Jó faz no capítulo 6.
* Isaías 53:3: "Era desprezado e o mais rejeitado entre os homens; homem de dores e que sabe o que é padecer; e como um de quem os homens escondem o rosto, era desprezado, e dele não fizemos caso." Este versículo fala sobre Jesus, que também experimentou a dor e a rejeição. Ele é um exemplo de alguém que sofreu injustamente e que compreende a dor que Jó está enfrentando.
* Romanos 8:18: "Porque para mim tenho por certo que as aflições deste tempo presente não são para comparar com a glória que em nós há de ser revelada." Este versículo encoraja a olhar para além das aflições presentes e a ter esperança na glória futura que Deus promete. É uma mensagem de encorajamento para Jó e para todos os que enfrentam dificuldades em suas vidas.
****

[[v20-6-1]]

^<<v20-6-1,1>>^ Jó tomou a palavra nestes termos:

[[v20-6-2]]

^<<v20-6-2,2>>^ “Ah! Se pudessem pesar minha aflição e pôr na balança com ela meu infortúnio!

[[v20-6-3]]

^<<v20-6-3,3>>^ Ela seria mais pesada que a areia do mar: eis por que minhas palavras são desvairadas.

[[v20-6-4]]

^<<v20-6-4,4>>^ As setas do Todo-poderoso estão cravadas em mim e meu espírito bebe o veneno delas. Os terrores de Deus me assediam.

[[v20-6-5]]

^<<v20-6-5,5>>^ Porventura zurra o asno montês, quando tem erva? Muge o boi junto de sua forragem?

[[v20-6-6]]

^<<v20-6-6,6>>^ Come-se uma coisa insípida sem pôr sal? Pode alguém saborear aquilo que não tem gosto algum?

[[v20-6-7]]

^<<v20-6-7,7>>^ Minha alma recusa-se a tocar nisso, meu coração está desgostoso.

[[v20-6-8]]

^<<v20-6-8,8>>^ Quem me dera que meu voto se cumpra, e que Deus realize o que eu espero!

[[v20-6-9]]

^<<v20-6-9,9>>^ Que Deus consinta em esmagar-me, que deixe suas mãos cortarem meus dias!

[[v20-6-10]]

^<<v20-6-10,10>>^ Teria pelo menos um consolo, e eu exultaria em seu impiedoso tormento, por não ter renegado as palavras do Santo.

[[v20-6-11]]

^<<v20-6-11,11>>^ Qual é a minha força para esperar? Qual é meu fim, para me portar com paciência?

[[v20-6-12]]

^<<v20-6-12,12>>^ Será que tenho a força das pedras, ou será de bronze minha carne?

[[v20-6-13]]

^<<v20-6-13,13>>^ Não encontro socorro algum, qualquer esperança de salvação me foi tirada.

[[v20-6-14]]

^<<v20-6-14,14>>^ Recusar a piedade a um amigo é abandonar o temor do Todo-poderoso.^&#42;1^

[[v20-6-15]]

^<<v20-6-15,15>>^ Meus irmãos são traiçoeiros como a torrente, como as águas das torrentes que somem.

[[v20-6-16]]

^<<v20-6-16,16>>^ Rolam agitadas pelo gelo, empoçam-se com a neve derretida.

[[v20-6-17]]

^<<v20-6-17,17>>^ No tempo da seca, elas se esgotam, ao vir o calor, seu leito seca.

[[v20-6-18]]

^<<v20-6-18,18>>^ As caravanas se desviam de sua rota, penetram no deserto e perecem.^&#42;1^

[[v20-6-19]]

^<<v20-6-19,19>>^ As caravanas de Temã espreitavam e os comboios de Sabá contavam com elas.

[[v20-6-20]]

^<<v20-6-20,20>>^ Ficaram transtornados nas suas suposições; chegando ao lugar, ficaram confusos.

[[v20-6-21]]

^<<v20-6-21,21>>^ É assim que falhais em cumprir o que de vós se esperava nesta hora; a vista de meu infortúnio vos aterroriza.

[[v20-6-22]]

^<<v20-6-22,22>>^ Porventura, disse-vos eu: ‘Dai-me qualquer coisa de vossos bens, dai-me presentes,

[[v20-6-23]]

^<<v20-6-23,23>>^ livrai-me da mão do inimigo e tirai-me do poder dos violentos?’.

[[v20-6-24]]

^<<v20-6-24,24>>^ Ensinai-me, e me calarei, mostrai-me em que falhei!

[[v20-6-25]]

^<<v20-6-25,25>>^ Como são eficazes os discursos sensatos! Mas em que podereis surpreender-me?

[[v20-6-26]]

^<<v20-6-26,26>>^ Pretendeis censurar palavras? Palavras desesperadas, leva-as o vento.

[[v20-6-27]]

^<<v20-6-27,27>>^ Seríeis capazes de leiloar até mesmo um órfão e traficar até mesmo um amigo.

[[v20-6-28]]

^<<v20-6-28,28>>^ Vamos, peço-vos, olhai para mim face a face e não mentirei.

[[v20-6-29]]

^<<v20-6-29,29>>^ Voltai atrás e não sejais injustos; vinde: estou inocente nessa questão.

[[v20-6-30]]

^<<v20-6-30,30>>^ Haverá iniquidade em minha língua? Meu paladar não sabe discernir o mal?

'''

xref:020-jo/020-jo-005.adoc#v20-5-0[&#60; Capítulo Anterior] | <<v20-6-0,Topo>> | xref:020-jo/020-jo-007.adoc#v20-7-0[Próximo Capítulo &#62;]