include::./index.adoc[]

[[v20-13-0]]
=== Jó, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 13 de Jó é um dos mais dramáticos do livro, onde Jó responde a seus amigos que o acusam de ter cometido algum pecado que justificaria suas aflições. Jó defende sua inocência e até mesmo acusa a Deus de oprimir o justo. Os versículos selecionados estão relacionados a temas como justiça, fé, redenção e esperança em Deus:
* Salmos 119:75: "Eu sei, ó Senhor, que teus juízos são justos, e que com fidelidade me afligiste." Este versículo fala sobre a justiça de Deus e como ele usa as aflições para nos ensinar e nos moldar.
* Hebreus 11:1: "Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que não se veem." Jó é um exemplo de fé inabalável em meio às dificuldades, mesmo sem entender o propósito de suas aflições.
* Salmos 130:7: "Espere Israel no Senhor, porque no Senhor há misericórdia, e nele há abundante redenção." Este versículo fala sobre a esperança em Deus e sua misericórdia, que traz redenção e libertação.
* Isaías 40:31: "Mas os que esperam no Senhor renovarão as suas forças, subirão com asas como águias, correrão e não se cansarão, caminharão e não se fatigarão." Este versículo fala sobre a renovação daqueles que esperam em Deus e como ele fortalece e sustenta aqueles que confiam nele.
* Romanos 5:3-5: "E não somente isso, mas também nos gloriamos nas tribulações, sabendo que a tribulação produz perseverança; e a perseverança, experiência; e a experiência, esperança. E a esperança não nos decepciona, porque o amor de Deus foi derramado em nossos corações pelo Espírito Santo que nos foi dado." Este versículo fala sobre a esperança que nasce em meio às tribulações e como Deus usa as dificuldades para nos moldar e nos dar experiência.
****

[[v20-13-1]]

^<<v20-13-1,1>>^ Meus olhos viram todas essas coisas, meus ouvidos as ouviram e as guardaram.

[[v20-13-2]]

^<<v20-13-2,2>>^ Aquilo que sabeis, eu também o sei, pois não vos sou inferior em nada.

[[v20-13-3]]

^<<v20-13-3,3>>^ Mas é com o Todo-poderoso que eu desejaria falar, com Deus é que eu desejaria discutir.

[[v20-13-4]]

^<<v20-13-4,4>>^ Pois vós não sois mais que impostores, não sois senão curandeiros que não prestam para nada.

[[v20-13-5]]

^<<v20-13-5,5>>^ Se pudésseis guardar silêncio, seríeis considerados sábios.

[[v20-13-6]]

^<<v20-13-6,6>>^ Escutai, pois, a minha defesa, atendei aos quesitos que vou anunciar.

[[v20-13-7]]

^<<v20-13-7,7>>^ Para defender a Deus, ireis dizer mentiras. Será preciso enganardes em seu favor?

[[v20-13-8]]

^<<v20-13-8,8>>^ Tereis, para com ele, juízos preconcebidos e vos ostenteis em ser seus advogados?

[[v20-13-9]]

^<<v20-13-9,9>>^ Não seria bom que ele vos examinasse? Iríeis enganá-lo como se engana uma pessoa qualquer?

[[v20-13-10]]

^<<v20-13-10,10>>^ Ele não deixará de vos castigar, se tomardes seu partido ocultamente.

[[v20-13-11]]

^<<v20-13-11,11>>^ Sua majestade não vos atemorizará? Seus terrores não vos esmagarão?

[[v20-13-12]]

^<<v20-13-12,12>>^ Vossos argumentos são como provérbios de cinza, vossas defesas são obras de barro.

[[v20-13-13]]

^<<v20-13-13,13>>^ Calai-vos! Deixai-me! Quero falar: aconteça depois o que acontecer!

[[v20-13-14]]

^<<v20-13-14,14>>^ Lacero a minha carne com os meus dentes, ponho minha vida em minha mão.^&#42;1^

[[v20-13-15]]

^<<v20-13-15,15>>^ Se ele me mata, nada mais tenho a esperar; assim mesmo, defenderei minha causa diante dele.

[[v20-13-16]]

^<<v20-13-16,16>>^ Isso já será a minha salvação, que o ímpio não seja admitido em sua presença.

[[v20-13-17]]

^<<v20-13-17,17>>^ Escutai bem meu discurso, dai ouvido às minhas explicações!

[[v20-13-18]]

^<<v20-13-18,18>>^ Estou pronto para defender minha causa e sei que sou eu quem tem razão.

[[v20-13-19]]

^<<v20-13-19,19>>^ Se alguém quiser demandar contra mim, no mesmo instante desejarei calar e morrer!

[[v20-13-20]]

^<<v20-13-20,20>>^ Poupai-me apenas duas coisas, ó Deus, e não me esconderei de tua face:^&#42;1^

[[v20-13-21]]

^<<v20-13-21,21>>^ afasta de mim a tua mão, e põe um termo ao medo de teus terrores.

[[v20-13-22]]

^<<v20-13-22,22>>^ Chama por mim e eu te responderei; ou, então, falarei eu, e tu terás a réplica.

[[v20-13-23]]

^<<v20-13-23,23>>^ Quantas faltas e pecados cometi eu? Dá-me a conhecer minhas faltas e minhas ofensas!

[[v20-13-24]]

^<<v20-13-24,24>>^ Por que escondes de mim a tua face e por que me consideras como um inimigo?

[[v20-13-25]]

^<<v20-13-25,25>>^ Queres, então, assustar uma folha carregada pelo vento, ou perseguir uma palha seca?

[[v20-13-26]]

^<<v20-13-26,26>>^ Pois queres ditar contra mim sentenças amargas, e queres que me sejam imputadas as faltas de minha mocidade.

[[v20-13-27]]

^<<v20-13-27,27>>^ Queres prender os meus pés no cepo, espiar todos os meus passos e contar os rastos de meus pés.

[[v20-13-28]]

^<<v20-13-28,28>>^ (E ele se gasta como um pau bichado, como um tecido devorado pela traça).^&#42;1^

'''

xref:020-jo/020-jo-012.adoc#v20-12-0[&#60; Capítulo Anterior] | <<v20-13-0,Topo>> | xref:020-jo/020-jo-014.adoc#v20-14-0[Próximo Capítulo &#62;]