include::./index.adoc[]

[[v20-21-0]]
=== Jó, 21
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 21 de Jó é uma resposta às afirmações de Zofar sobre a punição dos ímpios. Jó argumenta que muitos ímpios prosperam nesta vida, enquanto muitos justos sofrem. Ele afirma que o sofrimento é uma parte da condição humana, e que o sucesso e o fracasso não são necessariamente indicações de virtude ou pecado. A seguir estão cinco versículos que abordam esses temas:
* Salmos 37:7 - "Descansa no Senhor, e espera nele; não te irrites por causa daquele que prospera em seu caminho, por causa do homem que executa astutos intentos." Este versículo fala sobre a importância de confiar em Deus e não se preocupar com o sucesso dos outros.
* Salmos 73:3-5 - "Porque eu tinha inveja dos soberbos, quando via a prosperidade dos ímpios. Pois eles não têm aflição até à sua morte, e estão firmes na posse dos bens. Não se acham em trabalhos como outros homens, nem são afligidos como outros homens." Este verso retrata a inveja de uma pessoa em relação à prosperidade dos ímpios.
* Provérbios 22:16 - "Aquele que oprime o pobre para se engrandecer a si mesmo, e aquele que dá ao rico, certamente empobrecerá." Este versículo afirma que a prosperidade material não é necessariamente um sinal de virtude.
* Eclesiastes 7:15 - "Tudo isto vi nos dias da minha vaidade; há justo que perece na sua justiça, e há ímpio que prolonga os seus dias na sua malícia." Este versículo reflete a ideia de que a justiça nem sempre prevalece nesta vida.
* Lucas 6:20 - "E, levantando ele os olhos para os seus discípulos, dizia: Bem-aventurados vós, os pobres, porque vosso é o reino de Deus." Este versículo fala sobre a importância de buscar recompensas espirituais em vez de material.
****

[[v20-21-1]]

^<<v20-21-1,1>>^ Jó tomou então a palavra nestes termos:

[[v20-21-2]]

^<<v20-21-2,2>>^ “Ouvi atentamente minhas palavras. Que eu tenha pelo menos esse consolo de vossa parte.

[[v20-21-3]]

^<<v20-21-3,3>>^ Permiti que eu fale; quando tiver falado, zombai à vontade.

[[v20-21-4]]

^<<v20-21-4,4>>^ É de um ser humano que me queixo? E como não hei de perder a paciência?

[[v20-21-5]]

^<<v20-21-5,5>>^ Olhai para mim e ficareis estupefatos e poreis a mão sobre a boca.

[[v20-21-6]]

^<<v20-21-6,6>>^ Quando penso nisso, fico estarrecido e todo o meu corpo treme.

[[v20-21-7]]

^<<v20-21-7,7>>^ Por que os ímpios sobrevivem e, ao envelhecer, crescem em poderio?

[[v20-21-8]]

^<<v20-21-8,8>>^ Sua posteridade prospera diante deles, e seus descendentes sob seus olhos.

[[v20-21-9]]

^<<v20-21-9,9>>^ Suas casas estão em paz, livres de perigo, e a vara de Deus não os atinge.

[[v20-21-10]]

^<<v20-21-10,10>>^ Seu touro é cada vez mais fecundo, sua vaca dá cria sem nunca abortar.

[[v20-21-11]]

^<<v20-21-11,11>>^ Deixam os filhos correr como carneiros, e os seus pequenos saltam e brincam alegremente.

[[v20-21-12]]

^<<v20-21-12,12>>^ Cantam ao som do pandeiro e da cítara, divertem-se ao som da flauta.

[[v20-21-13]]

^<<v20-21-13,13>>^ Passam seus dias na alegria e descem tranquilamente à região dos mortos.

[[v20-21-14]]

^<<v20-21-14,14>>^ Ora, dizem a Deus: ‘Afasta-te de nós! Não queremos conhecer os teus caminhos!

[[v20-21-15]]

^<<v20-21-15,15>>^ Quem é o Todo-poderoso, para que o sirvamos? Que vantagem tiramos em lhe fazer orações?’.

[[v20-21-16]]

^<<v20-21-16,16>>^ A felicidade não está em suas mãos? Contudo, longe de mim esteja o modo de pensar dos ímpios!

[[v20-21-17]]

^<<v20-21-17,17>>^ Quantas vezes vemos apagar-se a lâmpada dos ímpios e a ruína desabar sobre eles?

[[v20-21-18]]

^<<v20-21-18,18>>^ Serão eles como a palha ao vento, como a cinza tragada pelo turbilhão?

[[v20-21-19]]

^<<v20-21-19,19>>^ ‘Deus reserva para os filhos o castigo do pai?’ Que ele mesmo o puna, para que o sinta!

[[v20-21-20]]

^<<v20-21-20,20>>^ Que veja com os próprios olhos a sua ruína e ele mesmo beba da cólera do Todo-poderoso!

[[v20-21-21]]

^<<v20-21-21,21>>^ Pois o que lhe importa a sua casa depois dele, se o número de seus meses já está contado?

[[v20-21-22]]

^<<v20-21-22,22>>^ É a Deus que se irá ensinar a sabedoria, a ele, que julga os seres superiores?

[[v20-21-23]]

^<<v20-21-23,23>>^ Um morre em pleno vigor, feliz e tranquilo,

[[v20-21-24]]

^<<v20-21-24,24>>^ os flancos cobertos de gordura e a medula dos ossos cheia de seiva.

[[v20-21-25]]

^<<v20-21-25,25>>^ Outro, porém, morre com a amargura na alma, sem ter gozado a felicidade.

[[v20-21-26]]

^<<v20-21-26,26>>^ Juntos se deitam na terra e os vermes recobrem a ambos.

[[v20-21-27]]

^<<v20-21-27,27>>^ Por certo conheço vossos pensamentos, os julgamentos iníquos que fazeis de mim!

[[v20-21-28]]

^<<v20-21-28,28>>^ Dizeis: ‘Onde está a casa do tirano, onde está a tenda em que habitavam os ímpios?’.

[[v20-21-29]]

^<<v20-21-29,29>>^ Não interrogastes os viajantes? Contestaríeis seus testemunhos?

[[v20-21-30]]

^<<v20-21-30,30>>^ No dia da infelicidade o ímpio é poupado, no dia da cólera ele escapa.

[[v20-21-31]]

^<<v20-21-31,31>>^ Quem reprova diante dele o seu proceder e lhe pede contas de seus atos?

[[v20-21-32]]

^<<v20-21-32,32>>^ Levam-no ao sepulcro, ficarão de vigília em sua câmara funerária.

[[v20-21-33]]

^<<v20-21-33,33>>^ Os torrões do vale são-lhe leves; todos os homens irão em sua companhia e foram inumeráveis seus predecessores.

[[v20-21-34]]

^<<v20-21-34,34>>^ Que significam, pois, essas vãs consolações? Todas as vossas respostas são apenas perfídia”.

'''

xref:020-jo/020-jo-020.adoc#v20-20-0[&#60; Capítulo Anterior] | <<v20-21-0,Topo>> | xref:020-jo/020-jo-022.adoc#v20-22-0[Próximo Capítulo &#62;]