include::./index.adoc[]

[[v20-10-0]]
=== Jó, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* No capítulo 10 de Jó, ele continua a lamentar sua situação e questionar a Deus sobre o porquê de estar sofrendo tanto. Ele se sente injustiçado e desamparado, e clama a Deus por respostas. Os versículos relacionados a esses temas são:
* Salmos 22:1: "Meu Deus, meu Deus, por que me abandonaste? Por que estás tão longe de salvar-me, tão longe dos meus gritos de angústia?" Este versículo retrata a dor de sentir-se abandonado por Deus em meio ao sofrimento, o mesmo sentimento que Jó expressa no capítulo 10.
* Salmos 88:3-4: "Minha alma está saturada de males, e minha vida está à beira do Sheol. Sou contado entre aqueles que descem à cova; sou como um homem sem forças." Este salmo também expressa a sensação de desamparo e tristeza profunda em meio à dor, que Jó sente.
* Isaías 45:9: "Ai daquele que contende com o seu Criador! Ele é como um caco entre outros cacos de barro. Por acaso o barro pode dizer ao oleiro: ‘Que estás fazendo?’ ou: ‘A tua obra não tem alça’?" Este versículo faz referência ao fato de que Deus é soberano e não deve ser questionado ou contestado por sua criação, o que é um ponto que Jó precisava aprender.
* Romanos 9:20: "Mas quem és tu, ó homem, para questionar a Deus? Acaso aquilo que é formado pode dizer ao que o formou: ‘Por que me fizeste assim?’" O apóstolo Paulo também aborda a questão de que a criação não deve questionar seu Criador e deve confiar em sua soberania, uma lição que Jó precisava aprender.
* Filipenses 4:6-7: "Não se preocupem com nada, mas em todas as orações peçam a Deus o que vocês precisam e orem sempre com o coração agradecido. E a paz de Deus, que ninguém consegue entender, guardará o coração e a mente de vocês, pois vocês estão unidos com Cristo Jesus." Este versículo enfatiza a importância da oração e confiança em Deus em meio às adversidades, algo que Jó também demonstra ao clamar por respostas e ajuda.
****

[[v20-10-1]]

^<<v20-10-1,1>>^ A minha alma está desgostosa da vida. Dou livre curso ao meu lamento; falarei na amargura de meu coração.

[[v20-10-2]]

^<<v20-10-2,2>>^ Em lugar de me condenar, direi a Deus: ‘Mostra-me por que razão me tratas assim.

[[v20-10-3]]

^<<v20-10-3,3>>^ Encontras prazer em me oprimir, em renegar a obra de tuas mãos, em favorecer os planos dos maus?

[[v20-10-4]]

^<<v20-10-4,4>>^ Terás porventura olhos de carne, ou vês as coisas como as veem os seres humanos?^&#42;1^

[[v20-10-5]]

^<<v20-10-5,5>>^ Serão os teus dias como os de um mortal e teus anos como os de um humano,

[[v20-10-6]]

^<<v20-10-6,6>>^ para que procures a minha culpa e persigas o meu pecado?

[[v20-10-7]]

^<<v20-10-7,7>>^ No entanto, sabes que não sou culpado e que ninguém me pode livrar de tuas mãos.

[[v20-10-8]]

^<<v20-10-8,8>>^ As tuas mãos formaram-me e fizeram-me; mudando de ideia, queres me destruir!

[[v20-10-9]]

^<<v20-10-9,9>>^ Lembra-te de que me formaste como o barro, e agora queres devolver-me ao pó?

[[v20-10-10]]

^<<v20-10-10,10>>^ Não me derramaste como leite e me coalhaste como um queijo?^&#42;1^

[[v20-10-11]]

^<<v20-10-11,11>>^ De pele e carne me vestiste, de ossos e nervos me teceste.

[[v20-10-12]]

^<<v20-10-12,12>>^ Concedeste-me vida e misericórdia e tua providência conservou o meu espírito.

[[v20-10-13]]

^<<v20-10-13,13>>^ Contudo, eis o que escondias em teu coração, vejo bem o que meditavas.

[[v20-10-14]]

^<<v20-10-14,14>>^ Se peco, me observas, não perdoarás o meu pecado.

[[v20-10-15]]

^<<v20-10-15,15>>^ Se eu for culpado, ai de mim! Se for inocente, não ousarei levantar a cabeça, farto de vergonha e consciente de minha miséria.

[[v20-10-16]]

^<<v20-10-16,16>>^ Esgotado, me caças como um leão. Não cessas de desfraldar contra mim teu estranho poder.

[[v20-10-17]]

^<<v20-10-17,17>>^ Renovas contra mim teus assaltos, teu furor cresce contra mim e vigorosas tropas vêm-me cercar.

[[v20-10-18]]

^<<v20-10-18,18>>^ Por que me tiraste do ventre materno? Tivesse morrido, nenhum olho me teria visto.

[[v20-10-19]]

^<<v20-10-19,19>>^ Teria sido como se nunca tivesse existido, do ventre me teriam levado ao túmulo’.

[[v20-10-20]]

^<<v20-10-20,20>>^ Não são bem curtos os dias de minha vida? Que ele me deixe respirar um instante,

[[v20-10-21]]

^<<v20-10-21,21>>^ antes que eu parta, para não mais voltar, ao tenebroso país das sombras da morte,

[[v20-10-22]]

^<<v20-10-22,22>>^ opaca e sombria região, reino de sombra e de caos, onde a noite faz as vezes de claridade”.

'''

xref:020-jo/020-jo-009.adoc#v20-9-0[&#60; Capítulo Anterior] | <<v20-10-0,Topo>> | xref:020-jo/020-jo-011.adoc#v20-11-0[Próximo Capítulo &#62;]