include::./index.adoc[]

[[v20-33-0]]
=== Jó, 33
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jó 33 é um capítulo em que Eliú, um dos amigos de Jó, faz um discurso defendendo a justiça de Deus e questionando as afirmações de Jó sobre sua inocência. Eliú alega que Deus fala de várias maneiras aos homens e que Jó deveria prestar atenção a essas formas de comunicação divina. Com base nisso, os versículos selecionados têm a ver com a comunicação de Deus com os homens e a importância de ouvir e obedecer à sua voz.
* Salmo 32:8: "Instruir-te-ei e ensinar-te-ei o caminho que deves seguir; guiar-te-ei com os meus olhos." Este versículo destaca a importância de Deus como guia e instrutor, assim como Eliú sugere que Jó deve ouvir a voz de Deus.
* João 10:27: "As minhas ovelhas ouvem a minha voz, e eu conheço-as, e elas me seguem." Jesus usa a imagem de ovelhas ouvindo e seguindo a voz do pastor para mostrar como seus seguidores devem ouvir e obedecer a ele.
* Provérbios 3:6: "Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." Este versículo destaca a importância de reconhecer a Deus em todos os aspectos da vida e seguir o caminho que ele define.
* Isaías 30:21: "E os teus ouvidos ouvirão a palavra do que está por detrás de ti, dizendo: Este é o caminho, andai nele, sem vos desviardes nem para a direita nem para a esquerda." Este versículo fala sobre a voz de Deus guiando as pessoas em seu caminho e como devem prestar atenção para ouvi-la.
* Hebreus 12:25: "Vede que não rejeiteis ao que fala; porque, se não escaparam aqueles que rejeitaram o que na terra os advertia, muito menos escaparemos nós, se nos desviarmos daquele que é dos céus." Este versículo destaca a importância de ouvir e obedecer à voz de Deus, alertando que a rejeição de sua mensagem tem consequências negativas.
****

[[v20-33-1]]

^<<v20-33-1,1>>^ E agora, Jó, ouve as minhas palavras e atende a todos os meus discursos.

[[v20-33-2]]

^<<v20-33-2,2>>^ Eis que abro a minha boca. Minha língua, sob o céu da boca, vai falar.

[[v20-33-3]]

^<<v20-33-3,3>>^ Minhas palavras brotam de um coração reto e meus lábios falarão francamente.

[[v20-33-4]]

^<<v20-33-4,4>>^ O espírito de Deus me criou e o sopro do Todo-poderoso me deu a vida.

[[v20-33-5]]

^<<v20-33-5,5>>^ Se puderes, responde-me. Toma posição e fica firme diante de mim.

[[v20-33-6]]

^<<v20-33-6,6>>^ Em face de Deus somos iguais. Como tu, eu também fui formado do barro!

[[v20-33-7]]

^<<v20-33-7,7>>^ Assim, meu temor não te assustará e o peso de minhas palavras não te acabrunhará.

[[v20-33-8]]

^<<v20-33-8,8>>^ Pois, disseste aos meus ouvidos, e ouvi estas palavras:

[[v20-33-9]]

^<<v20-33-9,9>>^ ‘Sou puro, sem pecado; sou limpo, não há culpa em mim.

[[v20-33-10]]

^<<v20-33-10,10>>^ É ele que inventa pretextos contra mim e considera-me seu inimigo.

[[v20-33-11]]

^<<v20-33-11,11>>^ Prendeu meus pés no cepo e vigiou todos os meus passos’.

[[v20-33-12]]

^<<v20-33-12,12>>^ Responderei que nisto foste injusto, pois Deus é maior do que o ser humano.

[[v20-33-13]]

^<<v20-33-13,13>>^ Por que o acusas de não dar nenhuma resposta a teus discursos?

[[v20-33-14]]

^<<v20-33-14,14>>^ Ora, Deus fala de uma maneira e de outra e não prestas atenção.^&#42;1^

[[v20-33-15]]

^<<v20-33-15,15>>^ Por meio dos sonhos, das visões noturnas, quando o sono profundo cai sobre os homens, enquanto dormem nos seus leitos,

[[v20-33-16]]

^<<v20-33-16,16>>^ então abre os ouvidos dos mortais e os assusta com suas aparições.

[[v20-33-17]]

^<<v20-33-17,17>>^ Isso para desviá-lo do pecado e livrá-lo do orgulho,

[[v20-33-18]]

^<<v20-33-18,18>>^ para salvar-lhe a alma da cova e sua vida, da seta mortífera.

[[v20-33-19]]

^<<v20-33-19,19>>^ Pela dor também é corrigido o homem em seu leito, quando todos os seus membros são agitados,

[[v20-33-20]]

^<<v20-33-20,20>>^ quando recebe o alimento com desgosto e já não pode suportar as iguarias mais deliciosas.

[[v20-33-21]]

^<<v20-33-21,21>>^ Sua carne se consome aos olhares e seus membros emagrecidos se desvanecem.

[[v20-33-22]]

^<<v20-33-22,22>>^ Sua alma aproxima-se da sepultura e sua vida, daqueles que estão mortos.

[[v20-33-23]]

^<<v20-33-23,23>>^ Se perto dele se encontrar um anjo, um intercessor entre mil, para ensinar-lhe o que deve fazer,

[[v20-33-24]]

^<<v20-33-24,24>>^ ter piedade dele e dizer: ‘Poupai-o de descer à cova, pois recebi o resgate de sua vida’.^&#42;1^

[[v20-33-25]]

^<<v20-33-25,25>>^ Sua carne retomará o vigor da mocidade e ele retornará aos dias de sua adolescência.

[[v20-33-26]]

^<<v20-33-26,26>>^ Ele rezará a Deus, que lhe será propício, contemplará com alegria sua face e restituirá ao homem sua justiça.

[[v20-33-27]]

^<<v20-33-27,27>>^ Cantará diante dos homens, dizendo: ‘Pequei, violei o direito, mas Deus não me tratou conforme meus erros.

[[v20-33-28]]

^<<v20-33-28,28>>^ Poupou minha alma de descer à cova e minha alma bem viva goza a luz!’.

[[v20-33-29]]

^<<v20-33-29,29>>^ Eis o que Deus faz duas e três vezes com o ser humano,

[[v20-33-30]]

^<<v20-33-30,30>>^ a fim de tirar-lhe a alma da cova e iluminá-la com a luz da vida.

[[v20-33-31]]

^<<v20-33-31,31>>^ Presta atenção, Jó, escuta-me, cala a boca para que eu fale!

[[v20-33-32]]

^<<v20-33-32,32>>^ Se tens alguma coisa para dizer, responde-me; fala, eu gostaria de te dar razão.

[[v20-33-33]]

^<<v20-33-33,33>>^ Se não, escuta-me, cala-te, e eu te ensinarei a sabedoria”.

'''

xref:020-jo/020-jo-032.adoc#v20-32-0[&#60; Capítulo Anterior] | <<v20-33-0,Topo>> | xref:020-jo/020-jo-034.adoc#v20-34-0[Próximo Capítulo &#62;]