include::./index.adoc[]

[[v57-3-0]]
=== Filipenses, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 3 de Filipenses fala sobre a superioridade de conhecer a Cristo e a busca pela perfeição na vida cristã. Paulo afirma que tudo o que ele considerava importante antes de conhecer a Cristo é como lixo em comparação com o valor de conhecê-lo. Ele também exorta os filipenses a seguir seu exemplo e a buscar a perfeição em Cristo. Com base nesses temas, seguem cinco versículos relacionados:
* Romanos 3:10: "como está escrito: 'Não há nenhum justo, nem um sequer'" - Paulo menciona em Filipenses 3:9 que sua justiça própria não vem da lei, mas da fé em Cristo. Este versículo de Romanos 3 reforça a ideia de que ninguém é justo por si só, todos precisam de Cristo para serem justificados.
* Colossenses 2:8: "Cuidado para que ninguém os escravize com filosofias vãs e enganosas, que se baseiam em tradições humanas e nos princípios elementares deste mundo, e não em Cristo." - Em Filipenses 3, Paulo adverte contra os falsos mestres que ensinam a salvação pela circuncisão. Este versículo de Colossenses destaca a importância de nos mantermos firmes em Cristo e não sermos levados por doutrinas enganosas.
* Mateus 6:33: "Mas busquem primeiro o Reino de Deus e a sua justiça, e todas essas coisas serão acrescentadas a vocês." - Em Filipenses 3:12-14, Paulo enfatiza a importância de prosseguir para o alvo e alcançar a ressurreição dos mortos. Este versículo de Mateus 6:33 nos encoraja a buscar primeiro o Reino de Deus, colocando-o em primeiro lugar em nossas vidas.
* 1 Coríntios 9:24: "Vocês não sabem que, numa corrida, todos os corredores competem, mas apenas um ganha o prêmio? Corram de tal modo que alcancem o prêmio." - Em Filipenses 3:13-14, Paulo usa a analogia de uma corrida para ilustrar a busca pela perfeição em Cristo. Este versículo de 1 Coríntios 9:24 também fala sobre uma corrida e encoraja os cristãos a correrem de tal modo que possam ganhar o prêmio.
* Efésios 2:8-9: "Porque vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus; não por obras, para que ninguém se glorie." - Em Filipenses 3:9, Paulo diz que deseja ser encontrado em Cristo, não tendo justiça própria, mas a que vem pela fé em Cristo. Este versículo de Efésios 2:8-9 destaca que a salvação é um dom de Deus, recebido pela fé em Cristo, e não pelas nossas obras.
****

[[v57-3-1]]

^<<v57-3-1,1>>^ No mais, meus irmãos, alegrai-vos no Senhor. Tornar a escrever-vos as mesmas recomendações, a mim por certo não me é penoso, e a vós vos é conveniente.^&#42;1^

[[v57-3-2]]

^<<v57-3-2,2>>^ Cuidado com esses cães! Cuidado com esses charlatães! Cuidado com esses mutilados!

[[v57-3-3]]

^<<v57-3-3,3>>^ Porque os verdadeiros circuncisos somos nós, que prestamos culto a Deus pelo Espírito de Deus, e pomos nossa glória em Jesus Cristo, e não confiamos na carne.^&#42;1^

[[v57-3-4]]

^<<v57-3-4,4>>^ No entanto, eu poderia confiar também na carne. Se há quem julgue ter motivos humanos para se gloriar, maiores os possuo eu:

[[v57-3-5]]

^<<v57-3-5,5>>^ circuncidado ao oitavo dia, da raça de Israel, da tribo de Benjamim, hebreu e filho de hebreus. Quanto à Lei, fariseu;

[[v57-3-6]]

^<<v57-3-6,6>>^ quanto ao zelo, perseguidor da Igreja; quanto à justiça legal, declaradamente irrepreensível.

[[v57-3-7]]

^<<v57-3-7,7>>^ Mas tudo isso, que para mim eram vantagens, considerei perda por Cristo.

[[v57-3-8]]

^<<v57-3-8,8>>^ Na verdade, julgo como perda todas as coisas, em comparação com este bem supremo: o conhecimento de Jesus Cristo, meu Senhor. Por ele tudo desprezei e tenho em conta de esterco, a fim de ganhar Cristo

[[v57-3-9]]

^<<v57-3-9,9>>^ e estar com ele. Não com minha justiça, que vem da Lei, mas com a justiça que se obtém pela fé em Cristo, a justiça que vem de Deus pela fé.

[[v57-3-10]]

^<<v57-3-10,10>>^ Anseio pelo conhecimento de Cristo e do poder de sua Ressurreição, pela participação em seus sofrimentos, tornando-me semelhante a ele na morte,

[[v57-3-11]]

^<<v57-3-11,11>>^ com a esperança de conseguir a ressurreição dentre os mortos.

[[v57-3-12]]

^<<v57-3-12,12>>^ Não pretendo dizer que já alcancei (esta meta) e que cheguei à perfeição. Não. Mas eu me empenho em conquistá-la, uma vez que também eu fui conquistado por Jesus Cristo.

[[v57-3-13]]

^<<v57-3-13,13>>^ Consciente de não tê-la ainda conquistado, só procuro isto: prescindindo do passado e atirando-me ao que resta para a frente,

[[v57-3-14]]

^<<v57-3-14,14>>^ persigo o alvo, rumo ao prêmio celeste, ao qual Deus nos chama, em Jesus Cristo.

[[v57-3-15]]

^<<v57-3-15,15>>^ Nós, mais aperfeiçoados que somos, ponhamos nisso o nosso afeto; e se tendes outro sentir, sobre isto Deus vos há de esclarecer.

[[v57-3-16]]

^<<v57-3-16,16>>^ Contudo, seja qual for o grau a que chegamos, o que importa é prosseguir decididamente.

[[v57-3-17]]

^<<v57-3-17,17>>^ Irmãos, sede meus imitadores, e olhai atentamente para os que vivem segundo o exemplo que nós vos damos.

[[v57-3-18]]

^<<v57-3-18,18>>^ Porque há muitos por aí, de quem repetidas vezes vos tenho falado e agora o digo chorando, que se portam como inimigos da cruz de Cristo,^&#42;1^

[[v57-3-19]]

^<<v57-3-19,19>>^ e cujo destino é a perdição, cujo deus é o ventre, para quem a própria ignomínia é causa de envaidecimento, e só têm prazer no que é terreno.

[[v57-3-20]]

^<<v57-3-20,20>>^ Nós, porém, somos cidadãos dos céus. É de lá que ansiosamente esperamos o Salvador, o Senhor Jesus Cristo,^&#42;1^

[[v57-3-21]]

^<<v57-3-21,21>>^ que transformará nosso mísero corpo, tornando-o semelhante ao seu corpo glorioso, em virtude do poder que tem de sujeitar a si toda criatura.^&#42;1^

'''

xref:057-filipenses/057-filipenses-002.adoc#v57-2-0[&#60; Capítulo Anterior] | <<v57-3-0,Topo>> | xref:057-filipenses/057-filipenses-004.adoc#v57-4-0[Próximo Capítulo &#62;]