include::./index.adoc[]

[[v49-9-0]]
=== São Lucas, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 9 de São Lucas começa com Jesus enviando seus doze discípulos para pregar o Reino de Deus e realizar curas e milagres em seu nome. Mais tarde, ele alimenta cinco mil pessoas com apenas cinco pães e dois peixes, revela aos seus discípulos que irá sofrer e ser morto, e ensina sobre a importância da humildade e do compromisso com Ele. Abaixo estão cinco versículos relacionados aos temas abordados em São Lucas 9:
* Mateus 10:1 - "Chamando os seus doze discípulos, deu-lhes autoridade para expulsar espíritos imundos e curar todas as doenças e enfermidades." Este versículo é similar à missão que Jesus deu aos seus discípulos em Lucas 9:1-2, onde Ele lhes dá poder e autoridade para curar e expulsar demônios em Seu nome.
* João 6:5-6 - "Quando Jesus ergueu os olhos e viu uma grande multidão que vinha ao encontro dele, disse a Filipe: 'Onde compraremos pão suficiente para dar a todos eles de comer?' E disse isso para o pôr à prova, pois ele mesmo sabia o que ia fazer." Este versículo é similar à história em Lucas 9:12-17, onde Jesus alimenta cinco mil pessoas com apenas cinco pães e dois peixes.
* Marcos 8:34 - "Em seguida, chamou a multidão e os discípulos e disse: 'Se alguém quiser acompanhar-me, negue-se a si mesmo, tome a sua cruz e siga-me.'" Este versículo é similar à mensagem de Jesus em Lucas 9:23, onde Ele diz: "Se alguém quiser vir após mim, negue-se a si mesmo, tome a sua cruz e siga-me."
* João 13:20 - "Em verdade, em verdade vos digo: quem recebe aquele que eu enviei, recebe-me a mim; e quem me recebe, recebe aquele que me enviou." Este versículo é similar ao ensinamento de Jesus em Lucas 9:48: "Aquele que receber esta criança em meu nome, a mim recebe; e aquele que me receber, recebe aquele que me enviou."
* João 14:6 - "Disse-lhe Jesus: 'Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai senão por mim.'" Este versículo é similar ao ensinamento de Jesus em Lucas 9:50, onde Ele diz aos Seus discípulos: "Quem não é contra nós é por nós."
****

[[v49-9-1]]

^<<v49-9-1,1>>^ Reunindo Jesus os doze apóstolos, deu-lhes poder e autoridade sobre todos os demônios, e para curar enfermidades.

[[v49-9-2]]

^<<v49-9-2,2>>^ Enviou-os a pregar o Reino de Deus e a curar os enfermos.

[[v49-9-3]]

^<<v49-9-3,3>>^ Disse-lhes: “Não leveis coisa alguma para o caminho, nem bordão, nem mochila, nem pão, nem dinheiro, nem tenhais duas túnicas.

[[v49-9-4]]

^<<v49-9-4,4>>^ Em qualquer casa em que entrardes, ficai ali até que deixeis aquela localidade.

[[v49-9-5]]

^<<v49-9-5,5>>^ Onde ninguém vos receber, deixai aquela cidade e em testemunho contra eles sacudi a poeira dos vossos pés”.

[[v49-9-6]]

^<<v49-9-6,6>>^ Partiram, pois, e percorriam as aldeias, pregando o Evangelho e fazendo curas por toda parte. (= Mt 14,1s = Mc 6,14ss)

[[v49-9-7]]

^<<v49-9-7,7>>^ O tetrarca Herodes ouviu falar de tudo o que Jesus fazia e ficou perplexo. Uns diziam: “É João que ressurgiu dos mortos”; outros: “É Elias que apareceu”;

[[v49-9-8]]

^<<v49-9-8,8>>^ e ainda outros: “É um dos antigos profetas que ressuscitou”.

[[v49-9-9]]

^<<v49-9-9,9>>^ Mas Herodes dizia: “Eu degolei a João. Quem é, pois, este, de quem ouço tais coisas?”. E procurava ocasião de vê-lo. (= Mt 14,13-21 = Mc 6,30-44 = Jo 6,1-15)

[[v49-9-10]]

^<<v49-9-10,10>>^ Os apóstolos, ao voltarem, contaram a Jesus tudo o que haviam feito. Tomando-os ele consigo à parte, dirigiu-se a um lugar deserto para o lado de Betsaida.

[[v49-9-11]]

^<<v49-9-11,11>>^ Logo que a multidão o soube, o foi seguindo; Jesus recebeu-os e falava-lhes do Reino de Deus. Restabelecia também a saúde dos doentes.

[[v49-9-12]]

^<<v49-9-12,12>>^ Ora, o dia começava a declinar e os Doze foram dizer-lhe: “Despede as turbas, para que vão pelas aldeias e sítios da vizinhança e procurem alimento e hospedagem, porque aqui estamos num lugar deserto”.

[[v49-9-13]]

^<<v49-9-13,13>>^ Jesus replicou-lhes: “Dai-lhes vós mesmos de comer”. Retrucaram eles: “Não temos mais do que cinco pães e dois peixes, a menos que nós mesmos vamos e compremos mantimentos para todo este povo”.

[[v49-9-14]]

^<<v49-9-14,14>>^ (Pois eram quase cinco mil homens.) Jesus disse aos discípulos: “Mandai-os sentar, divididos em grupos de cinquenta”.

[[v49-9-15]]

^<<v49-9-15,15>>^ Assim o fizeram e todos se assentaram.

[[v49-9-16]]

^<<v49-9-16,16>>^ Então, Jesus tomou os cinco pães e os dois peixes, levantou os olhos ao céu, abençoou-os, partiu-os e deu-os a seus discípulos, para que os servissem ao povo.

[[v49-9-17]]

^<<v49-9-17,17>>^ E todos comeram e ficaram fartos. Do que sobrou recolheram ainda doze cestos de pedaços.^&#42;1^ (=Mt 16,13-23 = Mc 8,27-33)

[[v49-9-18]]

^<<v49-9-18,18>>^ Num dia em que ele estava a orar a sós com os discípulos, perguntou-lhes: “Quem dizem que eu sou?”.

[[v49-9-19]]

^<<v49-9-19,19>>^ Responderam-lhe: “Uns dizem que és João Batista; outros, Elias; outros pensam que ressuscitou algum dos antigos profetas”.

[[v49-9-20]]

^<<v49-9-20,20>>^ Perguntou-lhes, então: “E vós, quem dizeis que eu sou?” Pedro respondeu: “O Cristo de Deus”.

[[v49-9-21]]

^<<v49-9-21,21>>^ Ordenou-lhes energicamente que não o dissessem a ninguém. (= Mt 16,24-28 = Mc 8,34–9,1 = Jo 12,25)

[[v49-9-22]]

^<<v49-9-22,22>>^ Ele acrescentou: “É necessário que o Filho do Homem padeça muitas coisas, seja rejeitado pelos anciãos, pelos príncipes dos sacerdotes e pelos escribas. É necessário que seja levado à morte e que ressuscite ao terceiro dia”.

[[v49-9-23]]

^<<v49-9-23,23>>^ Em seguida, dirigiu-se a todos: “Se alguém quer vir após mim, renegue-se a si mesmo, tome cada dia a sua cruz e siga-me.

[[v49-9-24]]

^<<v49-9-24,24>>^ Porque, quem quiser salvar a sua vida, irá perdê-la; mas quem sacrificar a sua vida por amor de mim, irá salvá-la.

[[v49-9-25]]

^<<v49-9-25,25>>^ Pois que aproveita ao homem ganhar o mundo inteiro, se vem a perder-se a si mesmo e se causa a sua própria ruína?

[[v49-9-26]]

^<<v49-9-26,26>>^ Se alguém se envergonhar de mim e das minhas palavras, também o Filho do Homem se envergonhará dele, quando vier na sua glória, na glória de seu Pai e dos santos anjos.

[[v49-9-27]]

^<<v49-9-27,27>>^ Em verdade vos digo: dos que aqui se acham, alguns há que não morrerão, até que vejam o Reino de Deus”. (= Mt 17,1-19 = Mc 9,2-10)

[[v49-9-28]]

^<<v49-9-28,28>>^ Passados uns oito dias, Jesus tomou consigo Pedro, Tiago e João, e subiu ao monte para orar.

[[v49-9-29]]

^<<v49-9-29,29>>^ Enquanto orava, transformou-se o seu rosto e as suas vestes tornaram-se resplandecentes de brancura.

[[v49-9-30]]

^<<v49-9-30,30>>^ E eis que falavam com ele dois personagens: eram Moisés e Elias,

[[v49-9-31]]

^<<v49-9-31,31>>^ que apareceram envoltos em glória, e falavam da morte dele, que se havia de cumprir em Jerusalém.^&#42;1^

[[v49-9-32]]

^<<v49-9-32,32>>^ Entretanto, Pedro e seus companheiros tinham-se deixado vencer pelo sono; ao despertarem, viram a glória de Jesus e os dois personagens em sua companhia.

[[v49-9-33]]

^<<v49-9-33,33>>^ Quando estes se apartaram de Jesus, Pedro disse: “Mestre, é bom estarmos aqui. Podemos levantar três tendas: uma para ti, outra para Moisés e outra para Elias!...”. Ele não sabia o que dizia.

[[v49-9-34]]

^<<v49-9-34,34>>^ Enquanto ainda assim falava, veio uma nuvem e encobriu-os com a sua sombra; e os discípulos, vendo-os desaparecer na nuvem, tiveram um grande pavor.

[[v49-9-35]]

^<<v49-9-35,35>>^ Então, da nuvem saiu uma voz: “Este é o meu Filho muito amado; ouvi-o!”.

[[v49-9-36]]

^<<v49-9-36,36>>^ E, enquanto ainda ressoava esta voz, achou-se Jesus sozinho. Os discípulos calaram-se e a ninguém disseram naqueles dias coisa alguma do que tinham visto. (Mt 17,14-20 = Mc 9,14-29)

[[v49-9-37]]

^<<v49-9-37,37>>^ No dia seguinte, descendo eles do monte, veio ao encontro de Jesus uma grande multidão.

[[v49-9-38]]

^<<v49-9-38,38>>^ Eis que um homem exclamou do meio da multidão: “Mestre, rogo-te que olhes para meu filho, pois é o único que tenho.

[[v49-9-39]]

^<<v49-9-39,39>>^ Um espírito se apodera dele e subitamente dá gritos, lança-o por terra, agita-o com violência, fá-lo espumar e só o larga depois de o deixar todo ofegante.

[[v49-9-40]]

^<<v49-9-40,40>>^ Pedi a teus discípulos que o expelissem, mas não o puderam fazer”.

[[v49-9-41]]

^<<v49-9-41,41>>^ Respondeu Jesus: “Ó geração incrédula e perversa, até quando estarei convosco e vos aturarei? Traze cá teu filho”.

[[v49-9-42]]

^<<v49-9-42,42>>^ E quando ele ia chegando, o demônio lançou-o por terra e agitou-o violentamente. Mas Jesus intimou o espírito imundo, curou o menino e o restituiu a seu pai.

[[v49-9-43]]

^<<v49-9-43,43>>^ Todos ficaram pasmados ante a grandeza de Deus. (= Mt 17,21s = Mc 9,30ss) Como todos se admirassem de tudo o que Jesus fazia, disse ele a seus discípulos:

[[v49-9-44]]

^<<v49-9-44,44>>^ “Gravai nos vossos corações estas palavras: O Filho do Homem há de ser entregue às mãos dos homens!”.

[[v49-9-45]]

^<<v49-9-45,45>>^ Eles, porém, não entendiam essa palavra e era-lhes obscura, de modo que não alcançaram o seu sentido; e tinham medo de lhe perguntar a esse respeito. (= Mt 18,1-6 = Mc 9,33-39)

[[v49-9-46]]

^<<v49-9-46,46>>^ Veio-lhes então o pensamento de qual deles seria o maior.

[[v49-9-47]]

^<<v49-9-47,47>>^ Penetrando Jesus nos pensamentos de seus corações, tomou um menino, colocou-o junto de si e disse-lhes:

[[v49-9-48]]

^<<v49-9-48,48>>^ “Todo o que recebe este menino em meu nome, a mim é que recebe; e quem recebe a mim recebe aquele que me enviou; pois quem dentre vós for o menor, esse será grande”.

[[v49-9-49]]

^<<v49-9-49,49>>^ João tomou a palavra e disse: “Mestre, vimos um homem que expelia demônios em teu nome, e nós lho proibimos, porque não é dos nossos”.

[[v49-9-50]]

^<<v49-9-50,50>>^ Mas Jesus lhe disse: “Não lho proibais; porque, o que não é contra vós é a vosso favor”.

[[v49-9-51]]

^<<v49-9-51,51>>^ Aproximando-se o tempo em que Jesus devia ser arrebatado deste mundo, ele resolveu dirigir-se a Jerusalém.

[[v49-9-52]]

^<<v49-9-52,52>>^ Enviou diante de si mensageiros que, tendo partido, entraram em uma povoação dos samaritanos para lhe arranjar pousada.

[[v49-9-53]]

^<<v49-9-53,53>>^ Mas não o receberam, por ele dar mostras de que ia para Jerusalém.

[[v49-9-54]]

^<<v49-9-54,54>>^ Vendo isso, Tiago e João disseram: “Senhor, queres que mandemos que desça fogo do céu e os consuma?”.

[[v49-9-55]]

^<<v49-9-55,55>>^ Jesus voltou-se e repreendeu-os severamente. [“Não sabeis de que espírito sois animados.^&#42;1^

[[v49-9-56]]

^<<v49-9-56,56>>^ O Filho do Homem não veio para perder as vidas dos homens, mas para salvá-las.”] Foram então para outra povoação.

[[v49-9-57]]

^<<v49-9-57,57>>^ Enquanto caminhavam, um homem lhe disse: “Senhor, te seguirei para onde quer que vás”.

[[v49-9-58]]

^<<v49-9-58,58>>^ Jesus replicou-lhe: “As raposas têm covas e as aves do céu, ninhos, mas o Filho do Homem não tem onde reclinar a cabeça”.

[[v49-9-59]]

^<<v49-9-59,59>>^ A outro disse: “Segue-me”. Mas ele pediu: “Senhor, permite-me ir primeiro enterrar meu pai”.

[[v49-9-60]]

^<<v49-9-60,60>>^ Mas Jesus disse-lhe: “Deixa que os mortos enterrem seus mortos; tu, porém, vai e anuncia o Reino de Deus”.

[[v49-9-61]]

^<<v49-9-61,61>>^ Um outro ainda lhe falou: “Senhor, te seguirei, mas permite primeiro que me despeça dos que estão em casa”.

[[v49-9-62]]

^<<v49-9-62,62>>^ Mas Jesus disse-lhe: “Aquele que põe a mão no arado e olha para trás não é apto para o Reino de Deus”. (= Mt 9,37ss; 10,7-16.40; 11,21-24)

'''

xref:049-sao-lucas/049-sao-lucas-008.adoc#v49-8-0[&#60; Capítulo Anterior] | <<v49-9-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-010.adoc#v49-10-0[Próximo Capítulo &#62;]