include::./index.adoc[]

[[v49-2-0]]
=== São Lucas, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 2 de Lucas descreve o nascimento de Jesus em Belém e eventos que ocorreram logo depois. Os pastores recebem a notícia do nascimento do Salvador, visitam o recém-nascido em sua manjedoura e compartilham a boa notícia. A seguir, Jesus é apresentado no templo, onde é reconhecido como o Messias por Simeão e Ana. Abaixo estão cinco versículos relacionados com esses temas:
* Mateus 1:23: "A virgem ficará grávida e dará à luz um filho, e o chamarão Emanuel" (que significa "Deus conosco"). Este versículo é uma profecia que se cumpre em Lucas 2, quando Maria dá à luz a Jesus.
* Isaías 9:6: "Porque um menino nos nasceu, um filho nos foi dado, e o governo está sobre os seus ombros. E ele será chamado Maravilhoso Conselheiro, Deus Poderoso, Pai Eterno, Príncipe da Paz." Este versículo é uma profecia sobre o nascimento de Jesus e a natureza de seu caráter e obra.
* Lucas 1:32: "Ele será grande e será chamado Filho do Altíssimo. O Senhor Deus lhe dará o trono de seu pai Davi." Este versículo é uma profecia sobre Jesus como o Messias, o cumprimento das promessas de Deus a Davi.
* Mateus 2:11: "E, entrando na casa, viram o menino com Maria, sua mãe, e prostrando-se, o adoraram; e abrindo seus tesouros, eles lhe ofereceram presentes: ouro, incenso e mirra." Este versículo descreve a visita dos magos, que trouxeram presentes ao recém-nascido Jesus.
* Lucas 2:40: "E o menino crescia e se fortalecia, enchendo-se de sabedoria; e a graça de Deus estava sobre ele." Este versículo indica o desenvolvimento da infância de Jesus, que cresceu em sabedoria e graça diante de Deus e dos homens.
****

[[v49-2-1]]

^<<v49-2-1,1>>^ Naqueles tempos, apareceu um decreto de César Augusto, ordenando o recenseamento de toda a terra.

[[v49-2-2]]

^<<v49-2-2,2>>^ Esse recenseamento foi feito antes do governo de Quirino, na Síria.

[[v49-2-3]]

^<<v49-2-3,3>>^ Todos iam alistar-se, cada um na sua cidade.

[[v49-2-4]]

^<<v49-2-4,4>>^ Também José subiu da Galileia, da cidade de Nazaré, à Judeia, à Cidade de Davi, chamada Belém, porque era da casa e família de Davi,

[[v49-2-5]]

^<<v49-2-5,5>>^ para se alistar com a sua esposa, Maria, que estava grávida.

[[v49-2-6]]

^<<v49-2-6,6>>^ Estando eles ali, completaram-se os dias dela.

[[v49-2-7]]

^<<v49-2-7,7>>^ E deu à luz seu filho primogênito, e, envolvendo-o em faixas, reclinou-o num presépio; porque não havia lugar para eles na hospedaria.^&#42;1^

[[v49-2-8]]

^<<v49-2-8,8>>^ Havia nos arredores uns pastores, que vigiavam e guardavam seu rebanho nos campos durante as vigílias da noite.

[[v49-2-9]]

^<<v49-2-9,9>>^ Um anjo do Senhor apareceu-lhes e a glória do Senhor refulgiu ao redor deles, e tiveram grande temor.

[[v49-2-10]]

^<<v49-2-10,10>>^ O anjo disse-lhes: “Não temais, eis que vos anuncio uma Boa-Nova que será alegria para todo o povo:

[[v49-2-11]]

^<<v49-2-11,11>>^ hoje vos nasceu na Cidade de Davi um Salvador, que é o Cristo Senhor.

[[v49-2-12]]

^<<v49-2-12,12>>^ Isto vos servirá de sinal: achareis um recém-nascido envolto em faixas e posto numa manjedoura”.

[[v49-2-13]]

^<<v49-2-13,13>>^ E subitamente ao anjo se juntou uma multidão do exército celeste, que louvava a Deus e dizia:

[[v49-2-14]]

^<<v49-2-14,14>>^ “Glória a Deus no mais alto dos céus e na terra paz aos homens, objetos da benevolência (divina).”^&#42;1^

[[v49-2-15]]

^<<v49-2-15,15>>^ Depois que os anjos os deixaram e voltaram para o céu, falaram os pastores uns com os outros: “Vamos até Belém e vejamos o que se realizou e o que o Senhor nos manifestou”.

[[v49-2-16]]

^<<v49-2-16,16>>^ Foram com grande pressa e acharam Maria e José, e o menino deitado na manjedoura.

[[v49-2-17]]

^<<v49-2-17,17>>^ Vendo-o, contaram o que se lhes havia dito a respeito deste menino.

[[v49-2-18]]

^<<v49-2-18,18>>^ Todos os que os ouviam admiravam-se das coisas que lhes contavam os pastores.

[[v49-2-19]]

^<<v49-2-19,19>>^ Maria conservava todas essas palavras, meditando-as no seu coração.

[[v49-2-20]]

^<<v49-2-20,20>>^ Voltaram os pastores, glorificando e louvando a Deus por tudo o que tinham ouvido e visto, e que estava de acordo com o que lhes fora dito.

[[v49-2-21]]

^<<v49-2-21,21>>^ Completados que foram os oito dias para ser circuncidado o menino, foi-lhe posto o nome de Jesus, como lhe tinha chamado o anjo, antes de ser concebido no seio materno.

[[v49-2-22]]

^<<v49-2-22,22>>^ Concluídos os dias da sua purificação segundo a Lei de Moisés, levaram-no a Jerusalém para o apresentar ao Senhor,

[[v49-2-23]]

^<<v49-2-23,23>>^ conforme o que está escrito na Lei do Senhor: “Todo primogênito do sexo masculino será consagrado ao Senhor” (Ex 13,2);

[[v49-2-24]]

^<<v49-2-24,24>>^ e para oferecerem o sacrifício prescrito pela Lei do Senhor, um par de rolas ou dois pombinhos.

[[v49-2-25]]

^<<v49-2-25,25>>^ Ora, havia em Jerusalém um homem chamado Simeão. Esse homem, justo e piedoso, esperava a consolação de Israel, e o Espírito Santo estava nele.^&#42;1^

[[v49-2-26]]

^<<v49-2-26,26>>^ Fora-lhe revelado pelo Espírito Santo que não morreria sem primeiro ver o Cristo do Senhor.

[[v49-2-27]]

^<<v49-2-27,27>>^ Impelido pelo Espírito Santo, foi ao templo. E tendo os pais apresentado o menino Jesus, para cumprirem a respeito dele os preceitos da Lei,

[[v49-2-28]]

^<<v49-2-28,28>>^ tomou-o em seus braços e louvou a Deus nestes termos:

[[v49-2-29]]

^<<v49-2-29,29>>^ “Agora, Senhor, deixai o vosso servo ir em paz, segundo a vossa palavra.

[[v49-2-30]]

^<<v49-2-30,30>>^ Porque os meus olhos viram a vossa salvação

[[v49-2-31]]

^<<v49-2-31,31>>^ que preparastes diante de todos os povos,

[[v49-2-32]]

^<<v49-2-32,32>>^ como luz para iluminar as nações, e para a glória de vosso povo de Israel”.

[[v49-2-33]]

^<<v49-2-33,33>>^ Seu pai e sua mãe estavam admirados das coisas que dele se diziam.

[[v49-2-34]]

^<<v49-2-34,34>>^ Simeão abençoou-os e disse a Maria, sua mãe: “Eis que este menino está destinado a ser uma causa de queda e de soerguimento para muitos homens em Israel, e a ser um sinal que provocará contradições,

[[v49-2-35]]

^<<v49-2-35,35>>^ a fim de serem revelados os pensamentos de muitos corações. E uma espada transpassará a tua alma”.^&#42;1^

[[v49-2-36]]

^<<v49-2-36,36>>^ Havia também uma profetisa chamada Ana, filha de Fanuel, da tribo de Aser; era de idade avançada.

[[v49-2-37]]

^<<v49-2-37,37>>^ Depois de ter vivido sete anos com seu marido desde a sua virgindade, ficara viúva e agora, com oitenta e quatro anos, não se apartava do templo, servindo a Deus noite e dia em jejuns e orações.

[[v49-2-38]]

^<<v49-2-38,38>>^ Chegando ela à mesma hora, louvava a Deus e falava de Jesus a todos aqueles que em Jerusalém esperavam a libertação.

[[v49-2-39]]

^<<v49-2-39,39>>^ Após terem observado tudo segundo a Lei do Senhor, voltaram para a Galileia, à sua cidade de Nazaré.

[[v49-2-40]]

^<<v49-2-40,40>>^ O menino ia crescendo e se fortificava: estava cheio de sabedoria, e a graça de Deus repousava nele.

[[v49-2-41]]

^<<v49-2-41,41>>^ Seus pais iam todos os anos a Jerusalém para a festa da Páscoa.

[[v49-2-42]]

^<<v49-2-42,42>>^ Tendo ele atingido doze anos, subiram a Jerusalém, segundo o costume da festa.

[[v49-2-43]]

^<<v49-2-43,43>>^ Acabados os dias da festa, quando voltavam, ficou o menino Jesus em Jerusalém, sem que os seus pais o percebessem.

[[v49-2-44]]

^<<v49-2-44,44>>^ Pensando que ele estivesse com os seus companheiros de comitiva, andaram caminho de um dia e o buscaram entre os parentes e conhecidos.

[[v49-2-45]]

^<<v49-2-45,45>>^ Mas não o encontrando, voltaram a Jerusalém, à procura dele.

[[v49-2-46]]

^<<v49-2-46,46>>^ Três dias depois o acharam no templo, sentado no meio dos doutores, ouvindo-os e interrogando-os.

[[v49-2-47]]

^<<v49-2-47,47>>^ Todos os que o ouviam estavam maravilhados da sabedoria de suas respostas.

[[v49-2-48]]

^<<v49-2-48,48>>^ Quando eles o viram, ficaram admirados. E sua mãe disse-lhe: “Meu filho, que nos fizeste?! Eis que teu pai e eu andávamos à tua procura, cheios de aflição”.

[[v49-2-49]]

^<<v49-2-49,49>>^ Respondeu-lhes ele: “Por que me procuráveis? Não sabíeis que devo ocupar-me das coisas de meu Pai?”.^&#42;1^

[[v49-2-50]]

^<<v49-2-50,50>>^ Eles, porém, não compreenderam o que ele lhes dissera.

[[v49-2-51]]

^<<v49-2-51,51>>^ Em seguida, desceu com eles a Nazaré e lhes era submisso. Sua mãe guardava todas essas coisas no seu coração.

[[v49-2-52]]

^<<v49-2-52,52>>^ E Jesus crescia em estatura, em sabedoria e graça, diante de Deus e dos homens. (= Mt 3,1-12 = Mc 1,1-8)

'''

xref:049-sao-lucas/049-sao-lucas-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-003.adoc#v49-3-0[Próximo Capítulo &#62;]