include::./index.adoc[]

[[v49-6-0]]
=== São Lucas, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Lucas 6 apresenta uma série de ensinamentos e ações de Jesus, incluindo a escolha dos doze apóstolos, a cura de um homem com a mão atrofiada e a proclamação das bem-aventuranças. Alguns dos temas abordados no capítulo incluem a lei, a misericórdia, a justiça, a humildade e a oração. Seguem abaixo cinco versículos relacionados a esses temas:
* Provérbios 21:3: "Praticar a justiça e o direito é mais aceitável ao Senhor do que oferecer sacrifícios." Esse versículo destaca a importância da justiça em relação aos rituais religiosos, mostrando que ações concretas são mais valorizadas por Deus do que oferendas vazias.
* Tiago 2:13: "Porque o juízo é sem misericórdia para aquele que não usou de misericórdia. A misericórdia triunfa sobre o juízo." Esse versículo destaca a importância da misericórdia em nossas relações com os outros e mostra que ela é fundamental para a vida cristã.
* Isaías 1:17: "Aprendam a fazer o bem, busquem a justiça, acabem com a opressão. Lutem pelos direitos do órfão, defendam a causa da viúva." Esse versículo enfatiza a necessidade de agir em favor dos mais fracos e vulneráveis da sociedade, buscando justiça e igualdade.
* Filipenses 2:3: "Não façam nada por ambição egoísta ou por vaidade, mas humildemente considerem os outros superiores a si mesmos." Esse versículo destaca a importância da humildade e da renúncia ao egoísmo em nossas relações com os outros.
* 1 Tessalonicenses 5:16-18: "Estejam sempre alegres. Orem sem cessar. Deem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus." Esse versículo destaca a importância da oração e da gratidão em nossa vida cristã, mostrando que devemos buscar sempre nos aproximar de Deus em todas as circunstâncias.
****

[[v49-6-1]]

^<<v49-6-1,1>>^ Em dia de sábado, Jesus atravessava umas plantações; seus discípulos iam colhendo espigas (de trigo), debulhavam-nas na mão e comiam.

[[v49-6-2]]

^<<v49-6-2,2>>^ Alguns dos fariseus lhes diziam: “Por que fazeis o que não é permitido no sábado?”.

[[v49-6-3]]

^<<v49-6-3,3>>^ Jesus respondeu: “Acaso não tendes lido o que fez Davi, quando teve fome, ele e os seus companheiros;

[[v49-6-4]]

^<<v49-6-4,4>>^ como entrou na casa de Deus e tomou os pães da proposição e deles comeu e deu de comer aos seus companheiros, se bem que só aos sacerdotes era permitido comê-los?”^&#42;1^

[[v49-6-5]]

^<<v49-6-5,5>>^ E ajuntou: “O Filho do Homem é senhor também do sábado”. (= Mt 12,9-14 = Mc 3,1-6)

[[v49-6-6]]

^<<v49-6-6,6>>^ Em outro dia de sábado, Jesus entrou na sinagoga e ensinava. Achava-se ali um homem que tinha a mão direita seca.

[[v49-6-7]]

^<<v49-6-7,7>>^ Ora, os escribas e os fariseus observavam Jesus para ver se ele curaria no dia de sábado. Eles teriam então pretexto para acusá-lo.

[[v49-6-8]]

^<<v49-6-8,8>>^ Mas Jesus conhecia os pensamentos deles e disse ao homem que tinha a mão seca: “Levanta-te e põe-te em pé, aqui no meio”. Ele se levantou e ficou em pé.

[[v49-6-9]]

^<<v49-6-9,9>>^ Disse-lhes Jesus: “Pergunto-vos se no sábado é permitido fazer o bem ou o mal; salvar a vida, ou deixá-la perecer”.

[[v49-6-10]]

^<<v49-6-10,10>>^ E, relanceando os olhos sobre todos, disse ao homem: “Estende tua mão”. Ele a estendeu, e foi-lhe restabelecida a mão.

[[v49-6-11]]

^<<v49-6-11,11>>^ Mas eles encheram-se de furor e indagavam uns aos outros o que fariam a Jesus. (= Mt 10,1-4; 12,15-21 = Mc 3,13-19)

[[v49-6-12]]

^<<v49-6-12,12>>^ Naqueles dias, Jesus retirou-se a uma montanha para rezar, e passou aí toda a noite orando a Deus.

[[v49-6-13]]

^<<v49-6-13,13>>^ Ao amanhecer, chamou os seus discípulos e escolheu doze dentre eles que chamou de apóstolos:

[[v49-6-14]]

^<<v49-6-14,14>>^ Simão, a quem deu o sobrenome de Pedro; André, seu irmão; Tiago, João, Filipe, Bartolomeu,

[[v49-6-15]]

^<<v49-6-15,15>>^ Mateus, Tomé, Tiago, filho de Alfeu; Simão, chamado Zelador;

[[v49-6-16]]

^<<v49-6-16,16>>^ Judas, irmão de Tiago; e Judas Iscariotes, aquele que foi o traidor. Multidão de discípulos

[[v49-6-17]]

^<<v49-6-17,17>>^ Descendo com eles, parou numa planície. Aí se achava um grande número de seus discípulos e uma grande multidão de pessoas vindas da Judeia, de Jerusalém, da região marítima, de Tiro e Sidônia, que tinham vindo para ouvi-lo e serem curadas de suas enfermidades.

[[v49-6-18]]

^<<v49-6-18,18>>^ E os que eram atormentados dos espíritos imundos ficavam livres.

[[v49-6-19]]

^<<v49-6-19,19>>^ Todo o povo procurava tocá-lo, pois saía dele uma força que os curava a todos. (= Mt 5ss)

[[v49-6-20]]

^<<v49-6-20,20>>^ Então, ele ergueu os olhos para os seus discípulos e disse: “Bem-aventurados vós que sois pobres, porque vosso é o Reino de Deus!^&#42;1^

[[v49-6-21]]

^<<v49-6-21,21>>^ Bem-aventurados vós que agora tendes fome, porque sereis fartos! Bem-aventurados vós que agora chorais, porque vos alegrareis!

[[v49-6-22]]

^<<v49-6-22,22>>^ Bem-aventurados sereis quando os homens vos odiarem, vos expulsarem, vos ultrajarem, e quando repelirem o vosso nome como infame por causa do Filho do Homem!

[[v49-6-23]]

^<<v49-6-23,23>>^ Alegrai-vos naquele dia e exultai, porque grande é o vosso galardão no céu. Era assim que os pais deles tratavam os profetas.

[[v49-6-24]]

^<<v49-6-24,24>>^ Mas ai de vós, ricos, porque tendes a vossa consolação!

[[v49-6-25]]

^<<v49-6-25,25>>^ Ai de vós, que estais fartos, porque vireis a ter fome! Ai de vós, que agora rides, porque gemereis e chorareis!

[[v49-6-26]]

^<<v49-6-26,26>>^ Ai de vós, quando vos louvarem os homens, porque assim faziam os pais deles aos falsos profetas!

[[v49-6-27]]

^<<v49-6-27,27>>^ Digo-vos a vós que me ouvis: amai os vossos inimigos, fazei bem aos que vos odeiam,

[[v49-6-28]]

^<<v49-6-28,28>>^ abençoai os que vos maldizem e orai pelos que vos injuriam.

[[v49-6-29]]

^<<v49-6-29,29>>^ Ao que te ferir numa face, oferece-lhe também a outra. E ao que te tirar a capa, não impeças de levar também a túnica.

[[v49-6-30]]

^<<v49-6-30,30>>^ Dá a todo o que te pedir; e ao que tomar o que é teu, não lho reclames.

[[v49-6-31]]

^<<v49-6-31,31>>^ O que quereis que os homens vos façam, fazei-o também a eles.^&#42;1^

[[v49-6-32]]

^<<v49-6-32,32>>^ Se amais os que vos amam, que recompensa mereceis? Também os pecadores amam aqueles que os amam.

[[v49-6-33]]

^<<v49-6-33,33>>^ E se fazeis bem aos que vos fazem bem, que recompensa mereceis? Pois o mesmo fazem também os pecadores.

[[v49-6-34]]

^<<v49-6-34,34>>^ Se emprestais àqueles de quem esperais receber, que recompensa mereceis? Também os pecadores emprestam aos pecadores, para receberem outro tanto.

[[v49-6-35]]

^<<v49-6-35,35>>^ Pelo contrário, amai os vossos inimigos, fazei bem e emprestai, sem daí esperar nada. E grande será a vossa recompensa e sereis filhos do Altíssimo, porque ele é bom para com os ingratos e maus.

[[v49-6-36]]

^<<v49-6-36,36>>^ Sede misericordiosos, como também vosso Pai é misericordioso.

[[v49-6-37]]

^<<v49-6-37,37>>^ Não julgueis, e não sereis julgados; não condeneis, e não sereis condenados; perdoai, e sereis perdoados;

[[v49-6-38]]

^<<v49-6-38,38>>^ dai, e vos será dado. Será colocada em vosso regaço medida boa, cheia, recalcada e transbordante, porque, com a mesma medida com que medirdes, sereis medidos vós também”.

[[v49-6-39]]

^<<v49-6-39,39>>^ Propôs-lhes também esta comparação: Pode acaso um cego guiar outro cego? Não cairão ambos na cova?

[[v49-6-40]]

^<<v49-6-40,40>>^ O discípulo não é superior ao mestre; mas todo discípulo perfeito será como o seu mestre.

[[v49-6-41]]

^<<v49-6-41,41>>^ Por que vês tu o argueiro no olho de teu irmão e não reparas na trave que está no teu olho?

[[v49-6-42]]

^<<v49-6-42,42>>^ Ou como podes dizer a teu irmão: Deixa-me, irmão, tirar de teu olho o argueiro, quando tu não vês a trave no teu olho? Hipócrita, tira primeiro a trave do teu olho e depois enxergarás para tirar o argueiro do olho de teu irmão.

[[v49-6-43]]

^<<v49-6-43,43>>^ “Uma árvore boa não dá frutos maus, uma árvore má não dá bom fruto.

[[v49-6-44]]

^<<v49-6-44,44>>^ Porquanto cada árvore se conhece pelo seu fruto. Não se colhem figos dos espinheiros, nem se apanham uvas dos abrolhos.

[[v49-6-45]]

^<<v49-6-45,45>>^ O homem bom tira coisas boas do bom tesouro do seu coração, e o homem mau tira coisas más do seu mau tesouro, porque a boca fala daquilo de que o coração está cheio.

[[v49-6-46]]

^<<v49-6-46,46>>^ Por que me chamais: Senhor, Senhor... e não fazeis o que digo?

[[v49-6-47]]

^<<v49-6-47,47>>^ Todo aquele que vem a mim ouve as minhas palavras e as pratica, eu vos mostrarei a quem é semelhante.

[[v49-6-48]]

^<<v49-6-48,48>>^ É semelhante ao homem que, edificando uma casa, cavou bem fundo e pôs os alicerces sobre a rocha. As águas transbordaram, precipitaram-se as torrentes contra aquela casa e não a puderam abalar, porque ela estava bem construída.

[[v49-6-49]]

^<<v49-6-49,49>>^ Mas aquele que as ouve e não as observa é semelhante ao homem que construiu a sua casa sobre a terra movediça, sem alicerces. A torrente investiu contra ela, e ela logo ruiu; e grande foi a ruína daquela casa.” (= Mt 8,5-13)

'''

xref:049-sao-lucas/049-sao-lucas-005.adoc#v49-5-0[&#60; Capítulo Anterior] | <<v49-6-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-007.adoc#v49-7-0[Próximo Capítulo &#62;]