include::./index.adoc[]

[[v49-7-0]]
=== São Lucas, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em Lucas 7, é apresentada uma série de milagres realizados por Jesus, incluindo a cura de um servo de um centurião e a ressurreição do filho de uma viúva. Também é relatado um diálogo entre Jesus e João Batista, que estava preso e queria saber se Jesus era o Messias. Os versículos relacionados com os temas abordados em Lucas 7 são:
* Mateus 8:13: "E disse Jesus ao centurião: Vai, e como creste te seja feito. E naquela mesma hora o seu servo sarou." Este versículo se relaciona com a cura do servo do centurião em Lucas 7:1-10.
* Lucas 6:19: "E toda a multidão procurava tocar-lhe, porque saía dele virtude, e curava a todos." Este versículo destaca o poder de cura de Jesus, que é evidenciado nos milagres relatados em Lucas 7.
* João 5:21: "Porque, como o Pai ressuscita os mortos, e os vivifica, assim também o Filho vivifica aqueles que quer." Este versículo se relaciona com a ressurreição do filho da viúva em Lucas 7:11-17.
* Lucas 7:47-48: "Por isso, te digo que os seus muitos pecados lhe são perdoados, porque muito amou; mas aquele a quem pouco é perdoado pouco ama. E disse-lhe a ela: Os teus pecados te são perdoados." Este versículo destaca o poder de Jesus para perdoar pecados, que é evidenciado no diálogo com a mulher pecadora em Lucas 7:36-50.
* Mateus 11:2-3: "E João, ouvindo no cárcere falar dos feitos de Cristo, enviou dois dos seus discípulos, a dizer-lhe: És tu aquele que havia de vir, ou esperaremos outro?" Este versículo se relaciona com o diálogo entre Jesus e João Batista em Lucas 7:18-35, em que João pergunta se Jesus é o Messias.
****

[[v49-7-1]]

^<<v49-7-1,1>>^ Tendo Jesus concluído todos os seus discursos ao povo que o escutava, entrou em Cafarnaum.

[[v49-7-2]]

^<<v49-7-2,2>>^ Havia lá um centurião que tinha um servo a quem muito estimava e que estava à morte.

[[v49-7-3]]

^<<v49-7-3,3>>^ Tendo ouvido falar de Jesus, enviou-lhe alguns anciãos dos judeus, rogando-lhe que o viesse curar.

[[v49-7-4]]

^<<v49-7-4,4>>^ Aproximando-se eles de Jesus, rogavam-lhe encarecidamente: “Ele bem merece que lhe faças este favor,

[[v49-7-5]]

^<<v49-7-5,5>>^ pois é amigo da nossa nação e foi ele mesmo quem nos edificou uma sinagoga”.

[[v49-7-6]]

^<<v49-7-6,6>>^ Jesus então foi com eles. E já não estava longe da casa, quando o centurião lhe mandou dizer por amigos seus: “Senhor, não te incomodes tanto assim, porque não sou digno de que entres em minha casa;

[[v49-7-7]]

^<<v49-7-7,7>>^ por isso, nem me achei digno de chegar-me a ti, mas dize somente uma palavra e o meu servo será curado.

[[v49-7-8]]

^<<v49-7-8,8>>^ Pois também eu, simples subalterno, tenho soldados às minhas ordens; e digo a um: Vai ali! E ele vai; e a outro: Vem cá! E ele vem; e ao meu servo: Faze isto! E ele o faz”.

[[v49-7-9]]

^<<v49-7-9,9>>^ Ouvindo essas palavras, Jesus ficou admirado. E, voltando-se para o povo que o ia seguindo, disse: “Em verdade vos digo: nem mesmo em Israel encontrei tamanha fé”.

[[v49-7-10]]

^<<v49-7-10,10>>^ Voltando para a casa do centurião os que haviam sido enviados, encontraram o servo curado.

[[v49-7-11]]

^<<v49-7-11,11>>^ No dia seguinte, dirigiu-se Jesus a uma cidade chamada Naim. Iam com ele diversos discípulos e muito povo.

[[v49-7-12]]

^<<v49-7-12,12>>^ Ao chegar perto da porta da cidade, eis que levavam um defunto a ser sepultado, filho único de uma viúva; acompanhava-a muita gente da cidade.

[[v49-7-13]]

^<<v49-7-13,13>>^ Vendo-a o Senhor, movido de compaixão para com ela, disse-lhe: “Não chores!”.

[[v49-7-14]]

^<<v49-7-14,14>>^ E, aproximando-se, tocou no esquife, e os que o levavam pararam. Disse Jesus: “Moço, eu te ordeno, levanta-te”.

[[v49-7-15]]

^<<v49-7-15,15>>^ Sentou-se o que estivera morto e começou a falar, e Jesus entregou-o à sua mãe.

[[v49-7-16]]

^<<v49-7-16,16>>^ Apoderou-se de todos o temor, e glorificavam a Deus, dizendo: “Um grande profeta surgiu entre nós: Deus voltou os olhos para o seu povo”.

[[v49-7-17]]

^<<v49-7-17,17>>^ A notícia desse fato correu por toda a Judeia e por toda a circunvizinhança. (= Mt 11,2-19)

[[v49-7-18]]

^<<v49-7-18,18>>^ Os discípulos de João contaram-lhe todas estas coisas.

[[v49-7-19]]

^<<v49-7-19,19>>^ E João chamou dois dos seus discípulos e enviou-os a Jesus, perguntando: “És tu o que há de vir ou devemos esperar por outro?”.^&#42;1^

[[v49-7-20]]

^<<v49-7-20,20>>^ Chegando estes homens a ele, disseram: “João Batista enviou-nos a ti, perguntando: És tu o que há de vir ou devemos esperar por outro?”.

[[v49-7-21]]

^<<v49-7-21,21>>^ Ora, naquele momento Jesus havia curado muitas pessoas de enfermidades, de doenças e de espíritos malignos e dado a vista a muitos cegos.

[[v49-7-22]]

^<<v49-7-22,22>>^ Respondeu-lhes ele: “Ide anunciar a João o que tendes visto e ouvido: os cegos veem, os coxos andam, os leprosos ficam limpos, os surdos ouvem, os mortos ressuscitam, aos pobres é anunciado o Evangelho;

[[v49-7-23]]

^<<v49-7-23,23>>^ e bem-aventurado é aquele para quem eu não for ocasião de queda!”

[[v49-7-24]]

^<<v49-7-24,24>>^ Depois que se retiraram os mensageiros de João, ele começou a falar de João ao povo: “Que fostes ver no deserto? Um caniço agitado pelo vento?

[[v49-7-25]]

^<<v49-7-25,25>>^ Mas que fostes ver? Um homem vestido de roupas finas? Mas os que vestem roupas preciosas e vivem no luxo estão nos palácios dos reis.

[[v49-7-26]]

^<<v49-7-26,26>>^ Mas, enfim, que fostes ver? Um profeta? Sim, digo-vos, e mais do que profeta.

[[v49-7-27]]

^<<v49-7-27,27>>^ Este é aquele de quem está escrito: Eis que envio o meu mensageiro ante a tua face; ele preparará o teu caminho diante de ti (Ml 3,1).

[[v49-7-28]]

^<<v49-7-28,28>>^ Pois vos digo: entre os nascidos de mulher não há maior que João. Entretanto, o menor no Reino de Deus é maior do que ele.

[[v49-7-29]]

^<<v49-7-29,29>>^ Ouvindo-o todo o povo, e mesmo os publicanos, deram razão a Deus, fazendo-se batizar com o batismo de João.

[[v49-7-30]]

^<<v49-7-30,30>>^ Os fariseus, porém, e os doutores da Lei, recusando o seu batismo, frustraram o desígnio de Deus a seu respeito.

[[v49-7-31]]

^<<v49-7-31,31>>^ A quem compararei os homens desta geração? Com quem se assemelham?

[[v49-7-32]]

^<<v49-7-32,32>>^ São semelhantes a meninos que, sentados na praça, falam uns com os outros, dizendo: Tocamos a flauta e não dançastes; entoamos lamentações e não chorastes.

[[v49-7-33]]

^<<v49-7-33,33>>^ Pois veio João Batista, que nem comia pão nem bebia vinho, e dizeis: Ele está possuído do demônio.

[[v49-7-34]]

^<<v49-7-34,34>>^ Veio o Filho do Homem, que come e bebe, e dizeis: Eis um comilão e beberrão, amigo dos publicanos e libertinos.

[[v49-7-35]]

^<<v49-7-35,35>>^ Mas a sabedoria foi justificada por todos os seus filhos”.^&#42;1^

[[v49-7-36]]

^<<v49-7-36,36>>^ Um fariseu convidou Jesus a ir comer com ele. Jesus entrou na casa dele e pôs-se à mesa.

[[v49-7-37]]

^<<v49-7-37,37>>^ Uma mulher pecadora da cidade, quando soube que estava à mesa em casa do fariseu, trouxe um vaso de alabastro cheio de perfume;

[[v49-7-38]]

^<<v49-7-38,38>>^ e, estando a seus pés, por detrás dele, começou a chorar. Pouco depois, suas lágrimas banhavam os pés do Senhor e ela os enxugava com os cabelos, beijava-os e os ungia com o perfume.

[[v49-7-39]]

^<<v49-7-39,39>>^ Ao presenciar isso, o fariseu, que o tinha convidado, dizia consigo mesmo: “Se este homem fosse profeta, bem saberia quem e qual é a mulher que o toca, pois é pecadora”.

[[v49-7-40]]

^<<v49-7-40,40>>^ Então, Jesus lhe disse: “Simão, tenho uma coisa a dizer-te”. –. “Fala, Mestre” – disse ele.

[[v49-7-41]]

^<<v49-7-41,41>>^ “Um credor tinha dois devedores: um lhe devia quinhentos denários e o outro, cinquenta.

[[v49-7-42]]

^<<v49-7-42,42>>^ Não tendo eles com que pagar, perdoou a ambos a sua dívida. Qual deles o amará mais?”

[[v49-7-43]]

^<<v49-7-43,43>>^ Simão respondeu: “A meu ver, aquele a quem ele mais perdoou”. Jesus replicou-lhe: “Julgaste bem”.

[[v49-7-44]]

^<<v49-7-44,44>>^ E voltando-se para a mulher, disse a Simão: “Vês esta mulher? Entrei em tua casa e não me deste água para lavar os pés; mas esta, com as suas lágrimas, regou-me os pés e enxugou-os com os seus cabelos.

[[v49-7-45]]

^<<v49-7-45,45>>^ Não me deste o ósculo; mas esta, desde que entrou, não cessou de beijar-me os pés.

[[v49-7-46]]

^<<v49-7-46,46>>^ Não me ungiste a cabeça com óleo; mas esta, com perfume, ungiu-me os pés.

[[v49-7-47]]

^<<v49-7-47,47>>^ Por isso, te digo: seus numerosos pecados lhe foram perdoados, porque ela tem demonstrado muito amor. Mas ao que pouco se perdoa, pouco ama”.^&#42;1^

[[v49-7-48]]

^<<v49-7-48,48>>^ E disse a ela: “Perdoados te são os pecados”.

[[v49-7-49]]

^<<v49-7-49,49>>^ Os que estavam com ele à mesa começaram a dizer, então: “Quem é este homem que até perdoa pecados?”.

[[v49-7-50]]

^<<v49-7-50,50>>^ Mas Jesus, dirigindo-se à mulher, disse-lhe: “Tua fé te salvou; vai em paz”.

'''

xref:049-sao-lucas/049-sao-lucas-006.adoc#v49-6-0[&#60; Capítulo Anterior] | <<v49-7-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-008.adoc#v49-8-0[Próximo Capítulo &#62;]