include::./index.adoc[]

[[v49-21-0]]
=== São Lucas, 21
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Lucas 21 trata sobre os ensinamentos de Jesus acerca dos sinais que precedem a sua segunda vinda e sobre a necessidade de estar preparado para esse momento. Abaixo estão cinco versículos relacionados com os temas abordados no capítulo:
* 2 Pedro 3:10: "Virá, pois, como ladrão o dia do Senhor, no qual os céus passarão com grande estrondo, e os elementos, ardendo, se dissolverão, e a terra, e as obras que nela há, serão descobertas." Esse versículo fala sobre a segunda vinda de Cristo e as consequências que ela terá para a Terra.
* Mateus 24:42: "Vigiai, pois, porque não sabeis em que dia vem o vosso Senhor." Assim como em São Lucas 21, Jesus enfatiza a importância da vigilância e da prontidão para a sua segunda vinda.
* 1 Tessalonicenses 5:2: "Porque vós mesmos sabeis muito bem que o dia do Senhor virá como o ladrão de noite." Neste versículo, Paulo faz uma comparação semelhante à usada por Jesus em São Lucas 21: a segunda vinda de Cristo será repentina e inesperada como um ladrão.
* Apocalipse 1:7: "Eis que vem com as nuvens, e todo o olho o verá, até mesmo aqueles que o traspassaram; e todas as tribos da terra se lamentarão sobre ele. Certamente. Amém." Esse versículo fala sobre a visibilidade e a universalidade da segunda vinda de Cristo.
* Mateus 24:30: "Então aparecerá no céu o sinal do Filho do Homem, e todas as tribos da terra se lamentarão, e verão vir o Filho do Homem sobre as nuvens do céu, com poder e grande glória." Esse versículo se relaciona com a descrição feita por Jesus em São Lucas 21:25-28 sobre os sinais celestiais que precederão a sua segunda vinda.
****

[[v49-21-1]]

^<<v49-21-1,1>>^ Levantando os olhos, viu Jesus os ricos que deitavam as suas ofertas no cofre do templo.

[[v49-21-2]]

^<<v49-21-2,2>>^ Viu também uma viúva pobrezinha deitar duas pequeninas moedas,^&#42;1^

[[v49-21-3]]

^<<v49-21-3,3>>^ e disse: “Em verdade vos digo: esta pobre viúva pôs mais do que os outros.

[[v49-21-4]]

^<<v49-21-4,4>>^ Pois todos aqueles lançaram nas ofertas de Deus o que lhes sobra; esta, porém, deu, da sua indigência, tudo o que lhe restava para o sustento”. (= Mt 24,1-36 = Mc 13,1-37)

[[v49-21-5]]

^<<v49-21-5,5>>^ Como lhe chamassem a atenção para a construção do templo feito de belas pedras e recamado de ricos donativos, Jesus disse:

[[v49-21-6]]

^<<v49-21-6,6>>^ “Dias virão em que destas coisas que vedes não ficará pedra sobre pedra: tudo será destruído”.

[[v49-21-7]]

^<<v49-21-7,7>>^ Então, o interrogaram: “Mestre, quando acontecerá isso? E que sinal haverá para saber-se que isso se vai cumprir?”.

[[v49-21-8]]

^<<v49-21-8,8>>^ Jesus respondeu: “Vede que não sejais enganados. Muitos virão em meu nome, dizendo: Sou eu; e ainda: O tempo está próximo. Não sigais após eles.

[[v49-21-9]]

^<<v49-21-9,9>>^ Quando ouvirdes falar de guerras e de tumultos, não vos assusteis; porque é necessário que isso aconteça primeiro, mas não virá logo o fim”.

[[v49-21-10]]

^<<v49-21-10,10>>^ Disse-lhes também: “Irão levantar-se nação contra nação e reino contra reino.

[[v49-21-11]]

^<<v49-21-11,11>>^ Haverá grandes terremotos por várias partes, fomes e pestes, e aparecerão fenômenos espantosos no céu.

[[v49-21-12]]

^<<v49-21-12,12>>^ Mas, antes de tudo isso, vos lançarão as mãos e vos perseguirão, entregando-vos às sinagogas e aos cárceres, levando-vos à presença dos reis e dos governadores, por causa de mim.

[[v49-21-13]]

^<<v49-21-13,13>>^ Isso vos acontecerá para que vos sirva de testemunho.

[[v49-21-14]]

^<<v49-21-14,14>>^ Gravai bem no vosso espírito: não prepareis vossa defesa,

[[v49-21-15]]

^<<v49-21-15,15>>^ porque eu vos darei uma palavra cheia de sabedoria, à qual não poderão resistir nem contradizer os vossos adversários.

[[v49-21-16]]

^<<v49-21-16,16>>^ Sereis entregues até por vossos pais, vossos irmãos, vossos parentes e vossos amigos, e matarão muitos de vós.

[[v49-21-17]]

^<<v49-21-17,17>>^ Sereis odiados por todos por causa do meu nome.

[[v49-21-18]]

^<<v49-21-18,18>>^ Entretanto, não se perderá um só cabelo de vossa cabeça.

[[v49-21-19]]

^<<v49-21-19,19>>^ É pela vossa constância que alcançareis a vossa salvação.^&#42;1^

[[v49-21-20]]

^<<v49-21-20,20>>^ Quando virdes que Jerusalém foi sitiada por exércitos, então sabereis que está próxima a sua ruína.

[[v49-21-21]]

^<<v49-21-21,21>>^ Os que então se acharem na Judeia fujam para os montes; os que estiverem dentro da cidade retirem-se; os que estiverem nos campos não entrem na cidade.

[[v49-21-22]]

^<<v49-21-22,22>>^ Porque estes serão dias de castigo, para que se cumpra tudo o que está escrito.

[[v49-21-23]]

^<<v49-21-23,23>>^ Ai das mulheres que, naqueles dias, estiverem grávidas ou amamentando, pois haverá grande angústia na terra e grande ira contra o povo.

[[v49-21-24]]

^<<v49-21-24,24>>^ Cairão a fio de espada e serão levados cativos para todas as nações, e Jerusalém será pisada pelos pagãos, até se completarem os tempos das nações pagãs”. (= Mt 24,29-44 = Mc 13,24-37)

[[v49-21-25]]

^<<v49-21-25,25>>^ “Haverá sinais no sol, na lua e nas estrelas. Na terra a aflição e a angústia irão apoderar-se das nações pelo bramido do mar e das ondas.

[[v49-21-26]]

^<<v49-21-26,26>>^ Os homens definharão de medo, na expectativa dos males que devem sobrevir a toda a terra. As próprias forças dos céus serão abaladas.

[[v49-21-27]]

^<<v49-21-27,27>>^ Então, verão o Filho do Homem vir sobre uma nuvem com grande glória e majestade.

[[v49-21-28]]

^<<v49-21-28,28>>^ Quando começarem a acontecer essas coisas, reanimai-vos e levantai as vossas cabeças; porque se aproxima a vossa libertação.”

[[v49-21-29]]

^<<v49-21-29,29>>^ Acrescentou ainda esta comparação: “Olhai para a figueira e para as demais árvores.

[[v49-21-30]]

^<<v49-21-30,30>>^ Quando elas lançam os brotos, vós julgais que está perto o verão.

[[v49-21-31]]

^<<v49-21-31,31>>^ Assim também, quando virdes que vão sucedendo essas coisas, sabereis que está perto o Reino de Deus.^&#42;1^

[[v49-21-32]]

^<<v49-21-32,32>>^ Em verdade vos declaro: não passará esta geração sem que tudo isso se cumpra.

[[v49-21-33]]

^<<v49-21-33,33>>^ Passarão o céu e a terra, mas as minhas palavras não passarão”.

[[v49-21-34]]

^<<v49-21-34,34>>^ “Velai sobre vós mesmos, para que os vossos corações não se tornem pesados com o excesso do comer, com a embriaguez e com as preocupações da vida; para que aquele dia não vos apanhe de improviso.

[[v49-21-35]]

^<<v49-21-35,35>>^ Como um laço cairá sobre aqueles que habitam a face de toda a terra.

[[v49-21-36]]

^<<v49-21-36,36>>^ Vigiai, pois, em todo o tempo e orai, a fim de que vos torneis dignos de escapar a todos esses males que hão de acontecer, e de vos apresentar de pé diante do Filho do Homem.”^&#42;1^

[[v49-21-37]]

^<<v49-21-37,37>>^ Durante o dia, Jesus ensinava no templo e, à tarde, saía para passar a noite no monte chamado das Oliveiras.

[[v49-21-38]]

^<<v49-21-38,38>>^ E todo o povo ia de manhã cedo ter com ele, no templo, para ouvi-lo. (= Mt 26,1-16 = Mc 14,1-11)

'''

xref:049-sao-lucas/049-sao-lucas-020.adoc#v49-20-0[&#60; Capítulo Anterior] | <<v49-21-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-022.adoc#v49-22-0[Próximo Capítulo &#62;]