include::./index.adoc[]

[[v49-16-0]]
=== São Lucas, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Lucas 16 apresenta ensinamentos de Jesus sobre dinheiro e riquezas. Ele fala sobre a parábola do administrador desonesto e destaca a importância da honestidade e fidelidade em relação aos bens materiais. Jesus também fala sobre a impossibilidade de servir a Deus e ao dinheiro ao mesmo tempo. Abaixo estão cinco versículos relacionados com os temas abordados em São Lucas 16:
* Mateus 6:19-21: "Não acumulem para vocês tesouros na terra, onde a traça e a ferrugem destroem, e onde ladrões arrombam e furtam. Mas acumulem para vocês tesouros no céu, onde a traça e a ferrugem não destroem, e onde ladrões não arrombam nem furtam. Pois onde estiver o seu tesouro, aí também estará o seu coração." Este versículo ensina a importância de valorizar as riquezas eternas em vez das temporais.
* Lucas 12:15: "Então lhes disse: 'Cuidado! Fiquem de sobreaviso contra todo tipo de ganância; a vida de um homem não consiste na quantidade dos seus bens'". Este versículo reforça a ideia de que a vida não deve ser definida pela quantidade de bens materiais que uma pessoa possui.
* Provérbios 22:1: "Mais vale ter um bom nome do que muitas riquezas; ser bem avaliado é melhor do que prata e ouro". Este versículo destaca a importância de ter um bom nome e reputação, que é mais valioso do que as riquezas materiais.
* 1 Timóteo 6:10: "Pois o amor ao dinheiro é a raiz de todos os males. Algumas pessoas, por cobiçarem o dinheiro, desviaram-se da fé e se atormentaram com muitos sofrimentos". Este versículo mostra os perigos da ganância e do amor ao dinheiro, que podem levar as pessoas a se afastarem da fé e a sofrerem as consequências disso.
* Hebreus 13:5: "Mantenham-se livres do amor ao dinheiro e contentem-se com o que vocês têm, porque Deus mesmo disse: 'Nunca o deixarei, nunca o abandonarei'". Este versículo enfatiza a importância de se contentar com o que se tem e confiar em Deus, em vez de ser obcecado por dinheiro e posses materiais.
****

[[v49-16-1]]

^<<v49-16-1,1>>^ Jesus disse também a seus discípulos: “Havia um homem rico que tinha um administrador. Este lhe foi denunciado de ter dissipado os seus bens.

[[v49-16-2]]

^<<v49-16-2,2>>^ Ele chamou o administrador e lhe disse: Que é que ouço dizer de ti? Presta contas da tua administração, pois já não poderás administrar meus bens.

[[v49-16-3]]

^<<v49-16-3,3>>^ O administrador refletiu então consigo: Que farei, visto que meu patrão me tira o emprego? Lavrar a terra? Não o posso. Mendigar? Tenho vergonha.

[[v49-16-4]]

^<<v49-16-4,4>>^ Já sei o que fazer, para que haja quem me receba em sua casa, quando eu for despedido do emprego.

[[v49-16-5]]

^<<v49-16-5,5>>^ Chamou, pois, separadamente a cada um dos devedores de seu patrão e perguntou ao primeiro: Quanto deves a meu patrão?

[[v49-16-6]]

^<<v49-16-6,6>>^ Ele respondeu: Cem medidas de azeite. Disse-lhe: Toma a tua conta, senta-te depressa e escreve: cinquenta.

[[v49-16-7]]

^<<v49-16-7,7>>^ Depois perguntou ao outro: Tu, quanto deves? Respondeu: Cem medidas de trigo. Disse-lhe o administrador: Toma os teus papéis e escreve: oitenta.

[[v49-16-8]]

^<<v49-16-8,8>>^ E o proprietário admirou a astúcia do administrador, porque os filhos deste mundo são mais prudentes do que os filhos da luz no trato com seus semelhantes.^&#42;1^

[[v49-16-9]]

^<<v49-16-9,9>>^ Eu vos digo: fazei-vos amigos com a riqueza injusta, para que, no dia em que ela vos faltar, eles vos recebam nos tabernáculos eternos.^&#42;1^

[[v49-16-10]]

^<<v49-16-10,10>>^ Aquele que é fiel nas coisas pequenas será também fiel nas coisas grandes. E quem é injusto nas coisas pequenas o será também nas grandes.

[[v49-16-11]]

^<<v49-16-11,11>>^ Se, pois, não tiverdes sido fiéis nas riquezas injustas, quem vos confiará as verdadeiras?^&#42;1^

[[v49-16-12]]

^<<v49-16-12,12>>^ E se não fostes fiéis no alheio, quem vos dará o que é vosso?

[[v49-16-13]]

^<<v49-16-13,13>>^ Nenhum servo pode servir a dois senhores: ou há de odiar a um e amar o outro, ou há de aderir a um e desprezar o outro. Não podeis servir a Deus e ao dinheiro”.^&#42;1^

[[v49-16-14]]

^<<v49-16-14,14>>^ Ora, ouviam tudo isso os fariseus, que eram avarentos, e zombavam dele.

[[v49-16-15]]

^<<v49-16-15,15>>^ Jesus disse-lhes: “Vós procurais parecer justos aos olhos dos homens, mas Deus vos conhece os corações; pois o que é elevado aos olhos dos homens é abominável aos olhos de Deus.

[[v49-16-16]]

^<<v49-16-16,16>>^ A Lei e os Profetas duraram até João. Desde então é anunciado o Reino de Deus, e cada um faz violência para aí entrar.^&#42;1^

[[v49-16-17]]

^<<v49-16-17,17>>^ Mais facilmente, porém, passará o céu e a terra do que se perderá uma só letra da Lei.

[[v49-16-18]]

^<<v49-16-18,18>>^ Todo o que abandonar sua mulher e casar com outra comete adultério; e quem se casar com a mulher rejeitada, comete adultério também”.

[[v49-16-19]]

^<<v49-16-19,19>>^ “Havia um homem rico que se vestia de púrpura e linho finíssimo, e que todos os dias se banqueteava e se regalava.

[[v49-16-20]]

^<<v49-16-20,20>>^ Havia também um mendigo, por nome Lázaro, todo coberto de chagas, que estava deitado à porta do rico.

[[v49-16-21]]

^<<v49-16-21,21>>^ Ele avidamente desejava matar a fome com as migalhas que caíam da mesa do rico... Até os cães iam lamber-lhe as chagas.

[[v49-16-22]]

^<<v49-16-22,22>>^ Ora, aconteceu morrer o mendigo e ser levado pelos anjos ao seio de Abraão. Morreu também o rico e foi sepultado.

[[v49-16-23]]

^<<v49-16-23,23>>^ E, estando ele nos tormentos do inferno, levantou os olhos e viu, ao longe, Abraão e Lázaro no seu seio.

[[v49-16-24]]

^<<v49-16-24,24>>^ Gritou, então: Pai Abraão, compadece-te de mim e manda Lázaro que molhe em água a ponta de seu dedo, a fim de me refrescar a língua, pois sou cruelmente atormentado nestas chamas.

[[v49-16-25]]

^<<v49-16-25,25>>^ Abraão, porém, replicou: Filho, lembra-te de que recebeste teus bens em vida, mas Lázaro, males; por isso, ele agora aqui é consolado, mas tu estás em tormento.

[[v49-16-26]]

^<<v49-16-26,26>>^ Além de tudo, há entre nós e vós um grande abismo, de maneira que os que querem passar daqui para vós não o podem, nem os de lá passar para cá.

[[v49-16-27]]

^<<v49-16-27,27>>^ O rico disse: Rogo-te então, pai, que mandes Lázaro à casa de meu pai, pois tenho cinco irmãos,

[[v49-16-28]]

^<<v49-16-28,28>>^ para lhes testemunhar que não aconteça virem também eles parar neste lugar de tormentos.

[[v49-16-29]]

^<<v49-16-29,29>>^ Abraão respondeu: Eles lá têm Moisés e os profetas; ouçam-nos!

[[v49-16-30]]

^<<v49-16-30,30>>^ O rico replicou: Não, pai Abraão; mas, se for a eles algum dos mortos, se arrependerão.

[[v49-16-31]]

^<<v49-16-31,31>>^ Abraão respondeu-lhe: Se não ouvirem a Moisés e aos profetas, tampouco se deixarão convencer, ainda que ressuscite algum dos mortos.”

'''

xref:049-sao-lucas/049-sao-lucas-015.adoc#v49-15-0[&#60; Capítulo Anterior] | <<v49-16-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-017.adoc#v49-17-0[Próximo Capítulo &#62;]