include::./index.adoc[]

[[v49-17-0]]
=== São Lucas, 17
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 17 de Lucas começa com Jesus ensinando sobre a importância de evitar o pecado e perdoar os outros, e em seguida, fala sobre a fé e a gratidão. Ele também fala sobre a natureza do reino de Deus e a volta de Jesus. Abaixo estão cinco versículos relacionados aos temas deste capítulo:
* Provérbios 19:11: "A prudência do homem lhe granjeia o favor do SENHOR, mas o homem de coração perverso será objeto de sua ira." Esse versículo está relacionado à primeira parte do capítulo, em que Jesus fala sobre evitar o pecado e perdoar os outros. A prudência mencionada aqui é uma atitude sábia e cautelosa que evita ofender os outros e cometer erros que possam prejudicar a si mesmo e aos outros.
* Marcos 11:24: "Por isso, vos digo que tudo o que pedirdes em oração, crede que recebestes, e será assim convosco." Este versículo está relacionado à segunda parte do capítulo, onde Jesus fala sobre a importância da fé. Aqui, Jesus encoraja seus seguidores a acreditarem que Deus ouvirá suas orações e as atenderá.
* Colossenses 3:15: "E a paz de Cristo, para a qual também fostes chamados em um só corpo, domine em vossos corações; e sede agradecidos." Este versículo está relacionado à terceira parte do capítulo, onde Jesus cura dez leprosos e apenas um deles retorna para agradecer a Jesus. O versículo fala sobre a importância da gratidão e da paz que deve reinar nos corações dos cristãos.
* Romanos 14:17: "Pois o reino de Deus não é comida nem bebida, mas justiça, paz e alegria no Espírito Santo." Este versículo está relacionado à quarta parte do capítulo, onde Jesus fala sobre a natureza do reino de Deus. Aqui, o apóstolo Paulo esclarece que o reino de Deus não é algo material ou físico, mas sim algo espiritual que traz justiça, paz e alegria aos cristãos.
* Mateus 24:44: "Por isso, estai vós também preparados; porque o Filho do Homem virá à hora em que não pensais." Este versículo está relacionado à última parte do capítulo, onde Jesus fala sobre sua segunda vinda. Aqui, Jesus exorta seus seguidores a estarem sempre preparados para sua volta, pois ela pode acontecer a qualquer momento e de forma inesperada.
****

[[v49-17-1]]

^<<v49-17-1,1>>^ Jesus disse também a seus discípulos: “É impossível que não haja escândalos, mas ai daquele por quem eles vêm!

[[v49-17-2]]

^<<v49-17-2,2>>^ Melhor lhe seria que se lhe atasse em volta do pescoço uma pedra de moinho e que fosse lançado ao mar, do que levar para o mal a um só destes pequeninos. Tomai cuidado de vós mesmos.

[[v49-17-3]]

^<<v49-17-3,3>>^ Se teu irmão pecar, repreende-o; se se arrepender, perdoa-lhe.

[[v49-17-4]]

^<<v49-17-4,4>>^ Se pecar sete vezes no dia contra ti e sete vezes no dia vier procurar-te, dizendo: ‘Estou arrependido’, lhe perdoarás.”

[[v49-17-5]]

^<<v49-17-5,5>>^ Os apóstolos disseram ao Senhor: “Aumenta-nos a fé!”.

[[v49-17-6]]

^<<v49-17-6,6>>^ Disse o Senhor: “Se tiverdes fé como um grão de mostarda, direis a esta amoreira: Arranca-te e transplanta-te no mar, e ela vos obedecerá”.

[[v49-17-7]]

^<<v49-17-7,7>>^ “Qual de vós, tendo um servo ocupado em lavrar ou em guardar o gado, quando voltar do campo lhe dirá: Vem depressa sentar-te à mesa?

[[v49-17-8]]

^<<v49-17-8,8>>^ E não lhe dirá ao contrário: Prepara-me a ceia, cinge-te e serve-me, enquanto como e bebo, e depois disso comerás e beberás tu?

[[v49-17-9]]

^<<v49-17-9,9>>^ E, se o servo tiver feito tudo o que lhe ordenara, porventura fica-lhe o senhor devendo alguma obrigação?

[[v49-17-10]]

^<<v49-17-10,10>>^ Assim também vós, depois de terdes feito tudo o que vos foi ordenado, dizei: Somos servos como quaisquer outros; fizemos o que devíamos fazer.”^&#42;1^

[[v49-17-11]]

^<<v49-17-11,11>>^ Sempre em caminho para Jerusalém, Jesus passava pelos confins da Samaria e da Galileia.

[[v49-17-12]]

^<<v49-17-12,12>>^ Ao entrar numa aldeia, vieram-lhe ao encontro dez leprosos, que pararam ao longe e elevaram a voz, clamando:^&#42;1^

[[v49-17-13]]

^<<v49-17-13,13>>^ “Jesus, Mestre, tem compaixão de nós!”.

[[v49-17-14]]

^<<v49-17-14,14>>^ Jesus viu-os e disse-lhes: “Ide, mostrai-vos ao sacerdote”. E, quando eles iam andando, ficaram curados.

[[v49-17-15]]

^<<v49-17-15,15>>^ Um deles, vendo-se curado, voltou, glorificando a Deus em alta voz.

[[v49-17-16]]

^<<v49-17-16,16>>^ Prostrou-se aos pés de Jesus e lhe agradecia. E era um samaritano.

[[v49-17-17]]

^<<v49-17-17,17>>^ Jesus lhe disse: “Não ficaram curados todos os dez? Onde estão os outros nove?

[[v49-17-18]]

^<<v49-17-18,18>>^ Não se achou senão este estrangeiro que voltasse para agradecer a Deus?!”.

[[v49-17-19]]

^<<v49-17-19,19>>^ E acrescentou: “Levanta-te e vai, tua fé te salvou”.

[[v49-17-20]]

^<<v49-17-20,20>>^ Os fariseus perguntaram um dia a Jesus quando viria o Reino de Deus. Respondeu-lhes: “O Reino de Deus não virá de um modo ostensivo.

[[v49-17-21]]

^<<v49-17-21,21>>^ Nem se dirá: Ei-lo aqui; ou: Ei-lo ali. Pois o Reino de Deus já está no meio de vós”.^&#42;1^

[[v49-17-22]]

^<<v49-17-22,22>>^ Mais tarde, ele explicou aos discípulos: “Virão dias em que desejareis ver um só dia o Filho do Homem, e não o vereis.

[[v49-17-23]]

^<<v49-17-23,23>>^ Então, vos dirão: Ei-lo aqui; e: Ei-lo ali. Não deveis sair nem os seguir.

[[v49-17-24]]

^<<v49-17-24,24>>^ Pois como o relâmpago, reluzindo numa extremidade do céu, brilha até a outra, assim será com o Filho do Homem no seu dia.

[[v49-17-25]]

^<<v49-17-25,25>>^ É necessário, porém, que primeiro ele sofra muito e seja rejeitado por esta geração.

[[v49-17-26]]

^<<v49-17-26,26>>^ Como ocorreu nos dias de Noé, acontecerá do mesmo modo nos dias do Filho do Homem.

[[v49-17-27]]

^<<v49-17-27,27>>^ Comiam e bebiam, casavam-se e davam-se em casamento, até o dia em que Noé entrou na arca. Veio o dilúvio e matou a todos.

[[v49-17-28]]

^<<v49-17-28,28>>^ Também do mesmo modo como aconteceu nos dias de Ló. Os homens festejavam, compravam e vendiam, plantavam e edificavam.

[[v49-17-29]]

^<<v49-17-29,29>>^ No dia em que Ló saiu de Sodoma, choveu fogo e enxofre do céu, que exterminou todos eles.

[[v49-17-30]]

^<<v49-17-30,30>>^ Assim será no dia em que se manifestar o Filho do Homem.

[[v49-17-31]]

^<<v49-17-31,31>>^ Naquele dia, quem estiver no terraço e tiver os seus bens em casa não desça para os tirar; da mesma forma, quem estiver no campo não torne atrás.

[[v49-17-32]]

^<<v49-17-32,32>>^ Lembrai-vos da mulher de Ló.^&#42;1^

[[v49-17-33]]

^<<v49-17-33,33>>^ Todo o que procurar salvar a sua vida irá perdê-la; mas todo o que a perder irá encontrá-la.

[[v49-17-34]]

^<<v49-17-34,34>>^ Digo-vos que naquela noite dois estarão em uma cama: um será tomado e o outro será deixado;

[[v49-17-35]]

^<<v49-17-35,35>>^ duas mulheres estarão moendo juntas: uma será tomada e a outra será deixada.

[[v49-17-36]]

^<<v49-17-36,36>>^ Dois homens estarão no campo: um será tomado e o outro será deixado”.

[[v49-17-37]]

^<<v49-17-37,37>>^ Perguntaram-lhe os discípulos: “Onde será isto, Senhor?. Respondeu-lhes: “Onde estiver o cadáver, ali se reunirão também as águias”.^&#42;1^

'''

xref:049-sao-lucas/049-sao-lucas-016.adoc#v49-16-0[&#60; Capítulo Anterior] | <<v49-17-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-018.adoc#v49-18-0[Próximo Capítulo &#62;]