include::./index.adoc[]

[[v49-23-0]]
=== São Lucas, 23
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Lucas 23 relata o julgamento, condenação e crucificação de Jesus. Além disso, o capítulo também apresenta algumas pessoas envolvidas na crucificação, como Pilatos e os criminosos crucificados ao lado de Jesus. Abaixo estão cinco versículos relacionados com os temas abordados em São Lucas 23:
* Isaías 53:5: "Mas ele foi ferido pelas nossas transgressões e moído pelas nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e pelas suas pisaduras fomos sarados." Este verso profético de Isaías se relaciona com a crucificação de Jesus, em que Ele foi ferido e morto pelos pecados da humanidade.
* João 19:11: "Respondeu Jesus: 'Não terias nenhuma autoridade sobre mim, se não te fosse dada de cima; por isso, quem me entregou a ti cometeu pecado maior'". Jesus afirma que Pilatos não teria autoridade sobre Ele se não fosse permitido por Deus, e que a verdadeira culpa recai sobre aqueles que O entregaram.
* Marcos 15:34: "E, à hora nona, bradou Jesus em alta voz, dizendo: Eli, Eli, lemá sabactâni, que quer dizer: Deus meu, Deus meu, por que me desamparaste?" Este verso apresenta as últimas palavras de Jesus na cruz, quando Ele sentiu o abandono de Deus em Sua morte.
* Marcos 15:38: "E o véu do santuário rasgou-se em duas partes, de alto a baixo." Este verso descreve um evento sobrenatural que ocorreu após a morte de Jesus, quando o véu do templo foi rasgado, indicando que agora todos têm acesso direto a Deus.
* Marcos 15:46: "E, tendo comprado um pano de linho e tirando-o da cruz, envolveu-o nele e depositou-o num sepulcro lavrado na rocha; e revolveu uma pedra para a porta do sepulcro." Este verso narra o sepultamento de Jesus, que é um momento crucial na história da salvação, pois marca o início da ressurreição e da vitória sobre a morte.
****

[[v49-23-1]]

^<<v49-23-1,1>>^ Levantou-se a sessão e conduziram Jesus diante de Pilatos,^&#42;1^

[[v49-23-2]]

^<<v49-23-2,2>>^ e puseram-se a acusá-lo: “Temos encontrado este homem excitando o povo à revolta, proibindo pagar imposto ao imperador e dizendo-se Messias e rei”.

[[v49-23-3]]

^<<v49-23-3,3>>^ Pilatos perguntou-lhe: “És tu o rei dos judeus?” Jesus respondeu: “Sim”.

[[v49-23-4]]

^<<v49-23-4,4>>^ Declarou Pilatos aos príncipes dos sacerdotes e ao povo: “Eu não acho neste homem culpa alguma”.

[[v49-23-5]]

^<<v49-23-5,5>>^ Mas eles insistiam fortemente: “Ele revoluciona o povo ensinando por toda a Judeia, a começar da Galileia até aqui”.

[[v49-23-6]]

^<<v49-23-6,6>>^ A essas palavras, Pilatos perguntou se ele era galileu.

[[v49-23-7]]

^<<v49-23-7,7>>^ E, quando soube que era da jurisdição de Herodes, enviou-o a Herodes, pois justamente naqueles dias se achava em Jerusalém.^&#42;1^

[[v49-23-8]]

^<<v49-23-8,8>>^ Herodes alegrou-se muito em ver Jesus, pois de longo tempo desejava vê-lo, por ter ouvido falar dele muitas coisas, e esperava presenciar algum milagre operado por ele.

[[v49-23-9]]

^<<v49-23-9,9>>^ Dirigiu-lhe muitas perguntas, mas Jesus nada respondeu.

[[v49-23-10]]

^<<v49-23-10,10>>^ Ali estavam os príncipes dos sacerdotes e os escribas, acusando-o com violência.

[[v49-23-11]]

^<<v49-23-11,11>>^ Herodes, com a sua guarda, tratou-o com desprezo, escarneceu dele, mandou revesti-lo de uma túnica branca e reenviou-o a Pilatos.

[[v49-23-12]]

^<<v49-23-12,12>>^ Naquele mesmo dia, Pilatos e Herodes fizeram as pazes, pois antes eram inimigos um do outro.

[[v49-23-13]]

^<<v49-23-13,13>>^ Pilatos convocou então os príncipes dos sacerdotes, os magistrados e o povo, e disse-lhes:

[[v49-23-14]]

^<<v49-23-14,14>>^ “Apresentastes-me este homem como agitador do povo, mas, interrogando-o eu diante de vós, não o achei culpado de nenhum dos crimes de que o acusais.

[[v49-23-15]]

^<<v49-23-15,15>>^ Nem tampouco Herodes, pois no-lo devolveu. Portanto, ele nada fez que mereça a morte.

[[v49-23-16]]

^<<v49-23-16,16>>^ Por isso, eu o soltarei depois de o castigar”.

[[v49-23-17]]

^<<v49-23-17,17>>^ [Acontecia que em cada festa ele era obrigado a soltar-lhes um preso.]

[[v49-23-18]]

^<<v49-23-18,18>>^ Todo o povo gritou a uma voz: “À morte com este, e solta-nos Barrabás.”

[[v49-23-19]]

^<<v49-23-19,19>>^ (Este homem fora lançado ao cárcere devido a uma revolta levantada na cidade, por causa de um homicídio.)

[[v49-23-20]]

^<<v49-23-20,20>>^ Pilatos, porém, querendo soltar Jesus, falou-lhes de novo,

[[v49-23-21]]

^<<v49-23-21,21>>^ mas eles vociferavam: “Crucifica-o! Crucifica-o!”.

[[v49-23-22]]

^<<v49-23-22,22>>^ Pela terceira vez, Pilatos ainda interveio: “Mas que mal fez ele, então? Não achei nele nada que mereça a morte; irei, portanto, castigá-lo e, depois, o soltarei”.

[[v49-23-23]]

^<<v49-23-23,23>>^ Mas eles instavam, reclamando em altas vozes que fosse crucificado, e os seus clamores recrudesciam.

[[v49-23-24]]

^<<v49-23-24,24>>^ Pilatos pronunciou então a sentença que lhes satisfazia o desejo.

[[v49-23-25]]

^<<v49-23-25,25>>^ Soltou-lhes aquele que eles reclamavam e que havia sido lançado ao cárcere por causa do homicídio e da revolta, e entregou Jesus à vontade deles. (= Mt 27,32-56 = Mc 15,21-41 = Jo 19,17-37)

[[v49-23-26]]

^<<v49-23-26,26>>^ Enquanto o conduziam, detiveram um certo Simão de Cirene, que voltava do campo, e impuseram-lhe a cruz para que a carregasse atrás de Jesus.

[[v49-23-27]]

^<<v49-23-27,27>>^ Seguia-o uma grande multidão de povo e de mulheres, que batiam no peito e o lamentavam.

[[v49-23-28]]

^<<v49-23-28,28>>^ Voltando-se para elas, Jesus disse: “Filhas de Jerusalém, não choreis sobre mim, mas chorai sobre vós mesmas e sobre vossos filhos.

[[v49-23-29]]

^<<v49-23-29,29>>^ Porque virão dias em que se dirá: Felizes as estéreis, os ventres que não geraram e os peitos que não amamentaram!

[[v49-23-30]]

^<<v49-23-30,30>>^ Então, dirão aos montes: Caí sobre nós! E aos outeiros: Cobri-nos!^&#42;1^

[[v49-23-31]]

^<<v49-23-31,31>>^ Porque, se eles fazem isso ao lenho verde, que acontecerá ao seco?”.

[[v49-23-32]]

^<<v49-23-32,32>>^ Eram conduzidos ao mesmo tempo dois malfeitores para serem mortos com Jesus.

[[v49-23-33]]

^<<v49-23-33,33>>^ Chegados que foram ao lugar chamado Calvário, ali o crucificaram, como também os ladrões, um à direita e outro à esquerda.

[[v49-23-34]]

^<<v49-23-34,34>>^ E Jesus dizia: “Pai, perdoa-lhes; porque não sabem o que fazem”. Eles dividiram as suas vestes e as sortearam.

[[v49-23-35]]

^<<v49-23-35,35>>^ A multidão conservava-se lá e observava. Os príncipes dos sacerdotes escarneciam de Jesus, dizendo: “Salvou a outros, que se salve a si próprio, se é o Cristo, o escolhido de Deus!”.

[[v49-23-36]]

^<<v49-23-36,36>>^ Do mesmo modo zombavam dele os soldados. Aproximavam-se dele, ofereciam-lhe vinagre e diziam:

[[v49-23-37]]

^<<v49-23-37,37>>^ “Se és o rei dos judeus, salva-te a ti mesmo”.

[[v49-23-38]]

^<<v49-23-38,38>>^ Por cima de sua cabeça pendia esta inscrição: “Este é o rei dos judeus”.

[[v49-23-39]]

^<<v49-23-39,39>>^ Um dos malfeitores, ali crucificados, blasfemava contra ele: “Se és o Cristo, salva-te a ti mesmo e salva-nos a nós!”.

[[v49-23-40]]

^<<v49-23-40,40>>^ Mas o outro o repreendeu: “Nem sequer temes a Deus, tu que sofres no mesmo suplício?

[[v49-23-41]]

^<<v49-23-41,41>>^ Para nós isto é justo: recebemos o que mereceram os nossos crimes, mas este não fez mal algum.”

[[v49-23-42]]

^<<v49-23-42,42>>^ E acrescentou: “Jesus, lembra-te de mim, quando tiveres entrado no teu Reino!”.

[[v49-23-43]]

^<<v49-23-43,43>>^ Jesus respondeu-lhe: “Em verdade te digo: hoje estarás comigo no paraíso”.

[[v49-23-44]]

^<<v49-23-44,44>>^ Era quase à hora sexta e em toda a terra houve trevas até a hora nona.^&#42;1^

[[v49-23-45]]

^<<v49-23-45,45>>^ Escureceu-se o sol e o véu do templo rasgou-se pelo meio.

[[v49-23-46]]

^<<v49-23-46,46>>^ Jesus deu então um grande brado e disse: “Pai, nas tuas mãos entrego o meu espírito”. E, dizendo isso, expirou.^&#42;1^

[[v49-23-47]]

^<<v49-23-47,47>>^ Vendo o centurião o que acontecia, deu glória a Deus e disse: “Na verdade, este homem era um justo”.

[[v49-23-48]]

^<<v49-23-48,48>>^ E toda a multidão dos que assistiam a esse espetáculo e viam o que se passava voltou batendo no peito.

[[v49-23-49]]

^<<v49-23-49,49>>^ Os amigos de Jesus, como também as mulheres que o tinham seguido desde a Galileia, conservavam-se a certa distância, e observavam estas coisas. (= Mt 27,57-61 = Mc 15,42-47 = Jo 19,38-42)

[[v49-23-50]]

^<<v49-23-50,50>>^ Havia um homem, por nome José, membro do conselho, homem reto e justo.

[[v49-23-51]]

^<<v49-23-51,51>>^ Ele não havia concordado com a decisão dos outros nem com os atos deles. Originário de Arimateia, cidade da Judeia, esperava ele o Reino de Deus.

[[v49-23-52]]

^<<v49-23-52,52>>^ Foi ter com Pilatos e lhe pediu o corpo de Jesus.

[[v49-23-53]]

^<<v49-23-53,53>>^ Ele o desceu da cruz, envolveu-o em um pano de linho e colocou-o num sepulcro, escavado na rocha, onde ainda ninguém havia sido depositado.

[[v49-23-54]]

^<<v49-23-54,54>>^ Era o dia da Preparação e já ia principiar o sábado.^&#42;1^

[[v49-23-55]]

^<<v49-23-55,55>>^ As mulheres, que tinham vindo com Jesus da Galileia, acompanharam José. Elas viram o túmulo e o modo como o corpo de Jesus ali fora depositado.

[[v49-23-56]]

^<<v49-23-56,56>>^ Elas voltaram e prepararam aromas e bálsamos. No dia de sábado, observaram o preceito do repouso. (= Mt 28,1-8 = Mc 16,1-8)

'''

xref:049-sao-lucas/049-sao-lucas-022.adoc#v49-22-0[&#60; Capítulo Anterior] | <<v49-23-0,Topo>> | xref:049-sao-lucas/049-sao-lucas-024.adoc#v49-24-0[Próximo Capítulo &#62;]