include::./index.adoc[]

[[v55-1-0]]
=== Gálatas, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 1 de Gálatas trata da autoridade apostólica de Paulo e da sua preocupação com o evangelho que está sendo pregado aos gálatas. Ele se surpreende com a rápida mudança que ocorreu neles e os adverte sobre aqueles que estão pregando um evangelho diferente do que eles receberam. Além disso, ele enfatiza que não recebeu o evangelho de homens, mas por meio de uma revelação de Jesus Cristo.
* 1 Coríntios 15:1-2: "Irmãos, quero lembrar-vos do evangelho que vos anunciei, o qual recebestes e no qual permaneceis firmes. Por meio dele também sois salvos, se retiverdes a palavra tal como vo-la anunciei; caso contrário, em vão teríeis crido." Esse versículo se relaciona com Gálatas 1 porque Paulo está preocupado com os gálatas que estão recebendo um evangelho diferente do que ele pregou. Ele quer lembrá-los do evangelho verdadeiro e reiterar sua importância para a salvação.
* 2 Timóteo 1:13-14: "Mantém o padrão das sãs palavras que de mim ouviste com fé e com o amor que há em Cristo Jesus. Guarda o bom depósito por meio do Espírito Santo que habita em nós." Esse versículo se relaciona com Gálatas 1 porque Paulo enfatiza que não recebeu o evangelho de homens, mas por meio de uma revelação de Jesus Cristo. Ele quer que o evangelho verdadeiro seja mantido e guardado com fidelidade e cuidado.
* Romanos 1:16-17: "Porque não me envergonho do evangelho, pois é o poder de Deus para a salvação de todo aquele que crê; primeiro do judeu, e também do grego. Porque no evangelho é revelada a justiça de Deus, uma justiça que do princípio ao fim é pela fé, como está escrito: 'O justo viverá pela fé'." Esse versículo se relaciona com Gálatas 1 porque Paulo enfatiza a importância do evangelho e como ele é o poder de Deus para a salvação. Ele quer que os gálatas entendam que a salvação é pela fé, e não pelas obras da lei.
* 1 Coríntios 1:17-18: "Pois Cristo não me enviou para batizar, mas para pregar o evangelho, não com sabedoria humana, para que a cruz de Cristo não seja esvaziada. Porque a mensagem da cruz é loucura para os que estão perecendo, mas para nós que estamos sendo salvos é o poder de Deus." Esse versículo se relaciona com Gálatas 1 porque Paulo enfatiza a centralidade da cruz de Cristo no evangelho. Ele não foi enviado para batizar, mas para pregar a mensagem da cruz, que é o poder de Deus para a salvação.
* Gálatas 2:15-16: "Nós somos judeus por natureza e não pecadores dentre os gentios. Sabendo, contudo, que o homem não é justificado por obras da lei, mas sim pela fé em Cristo Jesus, também temos crido em Cristo Jesus, para sermos justificados pela fé em Cristo e não por obras da lei, pois por obras da lei nenhuma carne será justificada." Esse versículo reforça a ideia de que a justificação não vem por meio das obras da lei, mas somente pela fé em Jesus Cristo.
****

[[v55-1-1]]

^<<v55-1-1,1>>^ Paulo apóstolo – não da parte de homens, nem por meio de algum homem, mas por Jesus Cristo e por Deus Pai que o ressuscitou dos mortos –

[[v55-1-2]]

^<<v55-1-2,2>>^ e todos os irmãos que estão comigo, às igrejas da Galácia:

[[v55-1-3]]

^<<v55-1-3,3>>^ a vós, graça e paz da parte de Deus, nosso Pai, e da parte do Senhor Jesus Cristo,

[[v55-1-4]]

^<<v55-1-4,4>>^ que se entregou por nossos pecados, para nos libertar da perversidade do mundo presente, segundo a vontade de Deus, nosso Pai,

[[v55-1-5]]

^<<v55-1-5,5>>^ a quem seja dada a glória pelos séculos dos séculos. Amém.

[[v55-1-6]]

^<<v55-1-6,6>>^ Estou admirado de que tão depressa passeis daquele que vos chamou à graça de Cristo para um evangelho diferente.

[[v55-1-7]]

^<<v55-1-7,7>>^ De fato, não há dois (evangelhos): há apenas pessoas que semeiam a confusão entre vós e querem perturbar o Evangelho de Cristo.^&#42;1^

[[v55-1-8]]

^<<v55-1-8,8>>^ Mas, ainda que alguém – nós ou um anjo baixado do céu – vos anunciasse um evangelho diferente do que vos temos anunciado, que ele seja anátema.

[[v55-1-9]]

^<<v55-1-9,9>>^ Repito aqui o que acabamos de dizer: se alguém pregar doutrina diferente da que recebestes, seja ele excomungado!

[[v55-1-10]]

^<<v55-1-10,10>>^ É, porventura, o favor dos homens que eu procuro, ou o de Deus? Por acaso tenho interesse em agradar aos homens? Se quisesse ainda agradar aos homens, não seria servo de Cristo.^&#42;1^

[[v55-1-11]]

^<<v55-1-11,11>>^ Asseguro-vos, irmãos, que o Evangelho pregado por mim não tem nada de humano.

[[v55-1-12]]

^<<v55-1-12,12>>^ Não o recebi nem o aprendi de homem algum, mas mediante uma revelação de Jesus Cristo.^&#42;1^

[[v55-1-13]]

^<<v55-1-13,13>>^ Certamente ouvistes falar de como outrora eu vivia no judaísmo, com que excesso perseguia a Igreja de Deus e a assolava;

[[v55-1-14]]

^<<v55-1-14,14>>^ avantajava-me no judaísmo a muitos dos meus companheiros de idade e nação, extremamente zeloso das tradições de meus pais.

[[v55-1-15]]

^<<v55-1-15,15>>^ Mas, quando aprouve àquele que me reservou desde o seio de minha mãe e me chamou pela sua graça,

[[v55-1-16]]

^<<v55-1-16,16>>^ para revelar seu Filho em minha pessoa, a fim de que eu o tornasse conhecido entre os gentios, imediatamente, sem consultar a ninguém,

[[v55-1-17]]

^<<v55-1-17,17>>^ sem ir a Jerusalém para ver os que eram apóstolos antes de mim, parti para a Arábia; de lá regressei a Damasco.

[[v55-1-18]]

^<<v55-1-18,18>>^ Três anos depois subi a Jerusalém para conhecer Cefas, e fiquei com ele quinze dias.

[[v55-1-19]]

^<<v55-1-19,19>>^ Dos outros apóstolos não vi mais nenhum, a não ser Tiago, irmão do Senhor.

[[v55-1-20]]

^<<v55-1-20,20>>^ Isto que vos escrevo – Deus me é testemunha –, não o estou inventando.

[[v55-1-21]]

^<<v55-1-21,21>>^ Em seguida, fui para as regiões da Síria e da Cilícia.

[[v55-1-22]]

^<<v55-1-22,22>>^ Eu era ainda pessoalmente desconhecido das comunidades cristãs da Judeia;

[[v55-1-23]]

^<<v55-1-23,23>>^ tinham elas apenas ouvido dizer: “Aquele que antes nos perseguia, agora prega a fé que outrora combatia. E glorificavam a Deus por minha causa.

'''

xref:054-ii-corintios/054-ii-corintios-013.adoc#v54-13-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-galatas/055-galatas-002.adoc#v55-2-0[Próximo Capítulo &#62;]