include::./index.adoc[]

[[v19-16-0]]
=== Ester, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Crônicas 16:35 - "E dizei: Salva-nos, ó Deus da nossa salvação, e ajunta-nos, e livra-nos das nações, para que louvemos o teu santo nome e nos gloriemos no teu louvor."
Este versículo fala sobre a salvação de Deus e o louvor que devemos dar a Ele por nos salvar. É uma referência ao reconhecimento daqueles que servem a Deus e que são salvos por Ele.
* Provérbios 3:6 - "Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas."
Este versículo fala sobre a importância de reconhecer a Deus em todas as nossas ações e decisões, confiando que Ele irá guiar nossos passos. Isso pode ser relacionado à fidelidade de Mardoqueu a Deus, mesmo em meio à adversidade.
* Filipenses 2:3 - "Nada façais por contenda ou por vanglória, mas por humildade; cada um considere os outros superiores a si mesmo."
Este versículo fala sobre a humildade e a importância de colocar os outros em primeiro lugar. Pode ser relacionado à atitude de Mardoqueu em colocar a segurança de seu povo acima de seus próprios interesses.
* 1 Pedro 5:6 - "Humilhai-vos, pois, debaixo da potente mão de Deus, para que a seu tempo vos exalte;"
Este versículo fala sobre a importância da humildade e submissão a Deus, confiando que Ele irá exaltar aqueles que são fiéis a Ele. Isso pode ser relacionado à atitude de Mardoqueu em confiar na justiça de Deus e esperar pacientemente pela sua providência.
****

[[v19-16-1]]

^<<v19-16-1,1>>^ Eis a cópia da carta: “Assuero, o grande rei, aos cento e vinte e sete sátrapas, aos governadores das províncias, desde a Índia até a Etiópia, e a todos os que dirigem nossos negócios, saudação.

[[v19-16-2]]

^<<v19-16-2,2>>^ Há muitos que, cumulados de honras pela grande bondade de seus benfeitores, tornaram-se arrogantes.

[[v19-16-3]]

^<<v19-16-3,3>>^ Não somente se deram a oprimir nossos súditos, mas, incapazes de se contentar com as honras recebidas, moveram maquinações contra aqueles que os tinham beneficiado.

[[v19-16-4]]

^<<v19-16-4,4>>^ E não contentes em banir do meio dos homens o sentimento de gratidão, chegam até a imaginar, na inchação faustosa de uma sorte inesperada, poder escapar à justa vingança do Deus que tudo vê.

[[v19-16-5]]

^<<v19-16-5,5>>^ Muitas vezes, as insinuações dos encarregados de administrar os interesses de seus amigos arrastaram a calamidades irremediáveis os que detêm o poder e os tornaram cúmplices da morte de inocentes,

[[v19-16-6]]

^<<v19-16-6,6>>^ abusando, por uma mentirosa malícia, da simplicidade e da probidade dos príncipes.

[[v19-16-7]]

^<<v19-16-7,7>>^ Isso é o que se pode verificar, não tanto pelas relações passadas que chegaram até nós, como acabamos de recordar, quando examinamos os fatos criminosos, de vós conhecidos, perpetrados por essa calamidade de homens indignamente revestidos de autoridade.

[[v19-16-8]]

^<<v19-16-8,8>>^ Em consequência disso, é necessário vigiar para assegurar no futuro, para todos, a tranquilidade e a paz do reino,

[[v19-16-9]]

^<<v19-16-9,9>>^ realizando mudanças e julgando prudentemente os acontecimentos que se apresentam, para enfrentá-los sempre com equidade.

[[v19-16-10]]

^<<v19-16-10,10>>^ Ora, pois, é assim que o macedônio Amã, filho de Amadates, homem verdadeiramente estranho ao sangue dos persas e muito alheio à nossa bondade – embora gozasse de nossa hospitalidade e

[[v19-16-11]]

^<<v19-16-11,11>>^ fosse favorecido de nossa universal benevolência, a ponto de ser chamado nosso pai e de ver todos se curvarem diante dele até a terra, como quem ocupa o lugar da segunda pessoa depois do trono real –

[[v19-16-12]]

^<<v19-16-12,12>>^ não soube conter sua presunção e intentou privar-nos tanto do poder como da vida.

[[v19-16-13]]

^<<v19-16-13,13>>^ Por insinuações cautelosas e sutis, procurou a morte de nosso salvador e grande benfeitor Mardoqueu, como também a de Ester, a irrepreensível companheira de nosso reino e de toda a sua nação.

[[v19-16-14]]

^<<v19-16-14,14>>^ Pensava surpreender-nos assim, isolados, para transferir o império dos persas aos macedônios.

[[v19-16-15]]

^<<v19-16-15,15>>^ Mas esses judeus que o criminoso votava à morte, verificamos que não eram de modo algum malfazejos, mas pelo contrário dirigidos por leis muito cheias de equidade

[[v19-16-16]]

^<<v19-16-16,16>>^ e que eles são os filhos do Altíssimo Deus vivo, o qual nos conserva a nós, como a nossos antepassados este reino em grande prosperidade.

[[v19-16-17]]

^<<v19-16-17,17>>^ Fareis, portanto, bem, não levando em conta as cartas enviadas por Amã, filho de Amadates,

[[v19-16-18]]

^<<v19-16-18,18>>^ visto que o autor desse crime foi suspenso numa forca diante das portas de Susa, com toda a sua família, tendo-lhe Deus, o Senhor universal, infligido prontamente o castigo que merecia.

[[v19-16-19]]

^<<v19-16-19,19>>^ Que uma cópia deste presente edito seja afixada por toda a parte: deixai os judeus observar suas leis com toda a liberdade

[[v19-16-20]]

^<<v19-16-20,20>>^ e prestai-lhes assistência para que se possam defender contra todos os que os ataquem no dia marcado para a ruína deles, isto é, no dia treze do duodécimo mês, chamado Adar.

[[v19-16-21]]

^<<v19-16-21,21>>^ Porque esse dia, marcado para a perda da raça escolhida, Deus, o Senhor universal, o trocou em dia de alegria.

[[v19-16-22]]

^<<v19-16-22,22>>^ Por conseguinte, celebrareis esse dia memorável com grande alegria, como uma de vossas solenidades,

[[v19-16-23]]

^<<v19-16-23,23>>^ a fim de que agora e daqui em diante seja um dia de salvação para nós e para os persas de boa vontade e uma recordação da ruína dos que maquinaram contra nós.

[[v19-16-24]]

^<<v19-16-24,24>>^ Toda cidade e toda província que não observar essas ordens será entregue à furiosa devastação do ferro e do fogo; desse modo, se tornará não somente inacessível aos homens, mas ainda horror perpétuo para os animais selvagens e para as aves”.

'''

xref:019-ester/019-ester-015.adoc#v19-15-0[&#60; Capítulo Anterior] | <<v19-16-0,Topo>> | xref:020-jo/020-jo-001.adoc#v20-1-0[Próximo Capítulo &#62;]