include::./index.adoc[]

[[v19-15-0]]
=== Ester, 15
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Salmos 9:16-17: "O Senhor é conhecido pelo julgamento que faz; o ímpio fica preso nas obras de suas mãos. Os ímpios voltam para o Sheol, todas as nações que se esquecem de Deus." Este versículo fala sobre como Deus julga aqueles que agem injustamente e se esquecem dele.
* Provérbios 11:8: "O justo é libertado da angústia, mas o ímpio toma o seu lugar." Este versículo descreve como o justo é recompensado e o ímpio é punido.
* Isaías 14:24: "O Senhor dos Exércitos jurou, dizendo: Certamente assim como pensei, assim sucederá, e assim como determinei, assim se efetuará." Este versículo destaca a autoridade e poder de Deus sobre todas as coisas.
* 1 Coríntios 15:57: "Mas graças a Deus, que nos dá a vitória por meio de nosso Senhor Jesus Cristo." Este versículo fala sobre a vitória que Deus nos dá através de Jesus Cristo, mesmo em tempos difíceis e de luta.
****

[[v19-15-1]]

^<<v19-15-1,1>>^ Mardoqueu mandou pedir a Ester que fosse ter com o rei para lhe pedir graça e suplicar em favor de sua pátria.

[[v19-15-2]]

^<<v19-15-2,2>>^ Recorda-te – mandou-lhe dizer – do tempo de tua humilhação, como eras alimentada por minhas mãos. Amã, o primeiro dignitário após o rei, falou contra nós para nossa ruína.

[[v19-15-3]]

^<<v19-15-3,3>>^ Roga, pois, ao Senhor e fala ao rei por nós; livra-nos da morte!”

[[v19-15-4]]

^<<v19-15-4,4>>^ No terceiro dia, terminando sua prece, Ester despiu suas vestes de dor e revestiu suas vestiduras de cerimônia.^&#42;1^

[[v19-15-5]]

^<<v19-15-5,5>>^ Assim adornada, depois de ter invocado a Deus, árbitro e salvador universal, tomou consigo duas servas.

[[v19-15-6]]

^<<v19-15-6,6>>^ Apoiava-se sobre uma, como uma pessoa delicada,

[[v19-15-7]]

^<<v19-15-7,7>>^ ao passo que a outra a seguia, levando a cauda de seu vestido.

[[v19-15-8]]

^<<v19-15-8,8>>^ Estava rosada como uma flor de beleza, de rosto alegre e atraente, mas com o coração angustiado pelo temor.

[[v19-15-9]]

^<<v19-15-9,9>>^ Passou, pois, todas as portas e se apresentou diante do rei. Assuero estava assentado em seu trono, revestido de todos os ornamentos de sua majestade, coberto de ouro e de pedrarias e seu aspecto era imponente.

[[v19-15-10]]

^<<v19-15-10,10>>^ Logo que o rei levantou a cabeça radiante de esplendor e dirigiu seu olhar cheio de cólera, a rainha, mudando de cor, desfaleceu e se deixou cair sobre os ombros da criada que a acompanhava.^&#42;1^

[[v19-15-11]]

^<<v19-15-11,11>>^ Deus mudou então em doçura a cólera do rei. Todo perturbado, levantou-se precipitadamente de seu trono e a tomou nos braços até que ela voltou a si, procurando acalmar seu temor com doces palavras:

[[v19-15-12]]

^<<v19-15-12,12>>^ “Que tens, Ester?” – perguntou ele –. “Sou teu irmão. Não temas!

[[v19-15-13]]

^<<v19-15-13,13>>^ Não morrerás, porque nossa ordem não concerne senão ao comum do povo.

[[v19-15-14]]

^<<v19-15-14,14>>^ Vem!”

[[v19-15-15]]

^<<v19-15-15,15>>^ Levantou o cetro de ouro e o aproximou de seu pescoço e a beijou, dizendo: “Fala comigo!”.

[[v19-15-16]]

^<<v19-15-16,16>>^ “Meu Senhor, eu te vi como um anjo de Deus e o temor de tua majestade pôs no avesso meu coração.^&#42;1^

[[v19-15-17]]

^<<v19-15-17,17>>^ Porque és maravilhoso, Senhor, e teu rosto está cheio de graça.”

[[v19-15-18]]

^<<v19-15-18,18>>^ Dizendo essas palavras, desfaleceu de novo sem sentidos,

[[v19-15-19]]

^<<v19-15-19,19>>^ o que encheu o rei de consternação enquanto todos os seus servos procuravam reanimá-la.

'''

xref:019-ester/019-ester-014.adoc#v19-14-0[&#60; Capítulo Anterior] | <<v19-15-0,Topo>> | xref:019-ester/019-ester-016.adoc#v19-16-0[Próximo Capítulo &#62;]