include::./index.adoc[]

[[v19-1-0]]
=== Ester, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Ester 1 descreve um banquete oferecido pelo rei Assuero aos nobres e príncipes do seu reino. Durante sete dias, eles festejaram e beberam em abundância. No sétimo dia, o rei ordenou que sua rainha, Vasti, comparecesse diante dele e dos convidados para mostrar sua beleza. No entanto, Vasti recusou-se a obedecer ao rei, o que o deixou enfurecido. Abaixo estão cinco versículos relacionados com os temas abordados em Ester 1:
* Provérbios 20:1: "O vinho é escarnecedor, a bebida forte alvoroçadora; e todo aquele que neles errar nunca será sábio." O capítulo 1 de Ester descreve o excesso de bebida durante o banquete do rei Assuero. Esse versículo de Provérbios adverte sobre os perigos da bebida alcoólica em excesso.
* Isaías 5:11: "Ai dos que se levantam cedo para seguir a embriaguez e andam em busca de bebida forte, permanecendo até a noite, até que o vinho os esquente!" Este versículo denuncia aqueles que se entregam à bebida e alerta para os males que essa prática pode trazer.
* Provérbios 31:4-5: "Não é próprio dos reis, ó Lemuel, não é próprio dos reis beber vinho, nem dos príncipes desejar bebida forte; para que bebendo esqueçam a lei, e pervertam o direito de todos os aflitos." Este trecho de Provérbios adverte os governantes sobre o perigo do consumo de bebidas alcoólicas, que podem levá-los a esquecer suas obrigações e a prejudicar aqueles sob sua autoridade.
* Provérbios 15:1: "A resposta branda desvia o furor, mas a palavra dura suscita a ira." No capítulo 1 de Ester, o rei fica furioso com a recusa de Vasti em comparecer diante dele e dos convidados. Esse versículo de Provérbios destaca a importância da moderação e do cuidado ao falar para evitar conflitos.
* Provérbios 25:28: "Como cidade derrubada, que não tem muros, assim é o homem que não pode conter o seu espírito." O rei Assuero demonstra falta de autocontrole e temperança ao se enfurecer com Vasti. Esse versículo de Provérbios destaca a importância de controlar as emoções e cultivar a paciência.
****

[[v19-1-1]]

^<<v19-1-1,1>>^ Eis o que aconteceu no tempo de Assuero que reinou desde a Índia até a Etiópia sobre cento e vinte e sete províncias.^&#42;1^

[[v19-1-2]]

^<<v19-1-2,2>>^ Naqueles dias em que ele ocupava o trono real, que está na fortaleza de Susa, sua capital,

[[v19-1-3]]

^<<v19-1-3,3>>^ no terceiro ano de seu reinado, deu um banquete a todos os cortesãos e servos. Tinha reunido em sua presença os chefes do exército dos persas e dos medos, os príncipes e os governadores das províncias,

[[v19-1-4]]

^<<v19-1-4,4>>^ para fazer manifestação da riqueza e do esplendor de seu reino, da rara magnificência de sua grandeza, durante um tempo considerável, de cento e oitenta dias.

[[v19-1-5]]

^<<v19-1-5,5>>^ Passados esses dias, o rei deu um banquete a toda a população que se encontrava na fortaleza de Susa, desde o maior até o menor, durante sete dias, sobre a esplanada do palácio real.

[[v19-1-6]]

^<<v19-1-6,6>>^ Havia cortinas brancas de algodão e de púrpura violeta, presas por cordões brancos e purpúreos sobre anéis de prata e colunas de mármore; havia leitos de ouro e de prata sobre um pavimento de pórfiro, de mármore branco, de nácar e havia pedra preta.

[[v19-1-7]]

^<<v19-1-7,7>>^ A bebida era servida em copos de ouro de variadas formas; o vinho real em abundância era oferecido pela liberalidade do rei.

[[v19-1-8]]

^<<v19-1-8,8>>^ Bebia-se sem ser importunado por ninguém, segundo uma ordem do rei, porque ele tinha recomendado a todos os chefes de sua casa que deixassem cada um proceder como lhe agradasse.

[[v19-1-9]]

^<<v19-1-9,9>>^ Por sua parte, a rainha Vasti ofereceu um banquete para as mulheres do palácio real do rei Assuero.

[[v19-1-10]]

^<<v19-1-10,10>>^ No sétimo dia, o rei, cujo coração estava alegre por causa do vinho, ordenou a Maumã, Bazata, Harbona, Bagata, Abgata, Zetar e Carcas – os sete eunucos a serviço, junto de Assuero –,

[[v19-1-11]]

^<<v19-1-11,11>>^ que trouxessem à sua presença a rainha Vasti, com o diadema real, para mostrar aos povos e aos grandes toda a sua beleza, porque era formosa de aspecto.

[[v19-1-12]]

^<<v19-1-12,12>>^ Mas a rainha Vasti recusou sujeitar-se à ordem do rei transmitida pelos eunucos. O rei enfureceu-se e sua cólera se inflamou.

[[v19-1-13]]

^<<v19-1-13,13>>^ Consultou os sábios versados na ciência dos tempos. (Porque os assuntos reais eram tratados desse modo, com jurisconsultos.

[[v19-1-14]]

^<<v19-1-14,14>>^ Seus assessores eram: Carsena, Setar, Admata, Társis, Mares, Marsana e Mamucã, sete príncipes da Pérsia e da Média, que contemplavam a face do rei e ocupavam os primeiros lugares no reino.)^&#42;1^

[[v19-1-15]]

^<<v19-1-15,15>>^ “Que lei – disse ele – se deve aplicar à rainha Vasti, por não ter obedecido a ordem que o rei Assuero lhe transmitiu pelos eunucos?”

[[v19-1-16]]

^<<v19-1-16,16>>^ “Não foi somente em relação ao rei – respondeu Mamucã – que se comportou mal a rainha Vasti, mas também em relação a todos os príncipes e os povos das províncias do rei Assuero.

[[v19-1-17]]

^<<v19-1-17,17>>^ Porque a conduta da rainha será conhecida de todas as mulheres e as incitará a desprezar seus maridos. Dirão: ‘O rei Assuero mandou trazer à sua presença a rainha Vasti, mas ela não foi!’.

[[v19-1-18]]

^<<v19-1-18,18>>^ Daqui em diante, as mulheres dos príncipes da Pérsia e da Média, sabendo da conduta da rainha, responderão do mesmo modo a todos os grandes do rei e disso resultará, por toda a parte, desprezo e irritação.

[[v19-1-19]]

^<<v19-1-19,19>>^ Se o rei achar bom, publique-se em seu nome um decreto real, que ficará consignado nas leis da Pérsia e da Média como irrevogável, em força do qual Vasti não apareça mais diante de Assuero e o rei confira o título de rainha a outra que seja mais digna.

[[v19-1-20]]

^<<v19-1-20,20>>^ Quando o edito for conhecido na imensidade de seu reino, todas as mulheres respeitarão seus maridos, desde o maior até o mais humilde.”

[[v19-1-21]]

^<<v19-1-21,21>>^ Esse parecer agradou ao rei e aos príncipes, de modo que o rei seguiu o conselho de Mamucã.

[[v19-1-22]]

^<<v19-1-22,22>>^ O rei expediu cartas para todas as províncias reais, a cada uma em sua escrita, e a cada povo em sua língua própria: elas decretavam que todo marido devia ser o senhor em sua casa e fazer-se respeitar por sua mulher.

'''

xref:018-judite/018-judite-016.adoc#v18-16-0[&#60; Capítulo Anterior] | <<v19-1-0,Topo>> | xref:019-ester/019-ester-002.adoc#v19-2-0[Próximo Capítulo &#62;]