include::./index.adoc[]

[[v19-11-0]]
=== Ester, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiástico 8:16: "Não sejas um detrator na presença dos príncipes, nem difames teu amigo na sua ausência." Este versículo aborda a importância da honestidade e da lealdade nas relações pessoais e profissionais.
* Provérbios 15:1: "A resposta branda desvia o furor, mas a palavra dura suscita a ira." Este versículo nos ensina a importância de sermos pacientes e compassivos com os outros, mesmo em situações estressantes.
* Provérbios 25:11: "Como maçãs de ouro em salvas de prata, assim é a palavra dita a seu tempo." Este versículo ressalta a importância da comunicação clara e oportuna nas relações interpessoais.
* Romanos 12:17: "A ninguém torneis mal por mal; procurai fazer o bem perante todos os homens." Este versículo nos ensina a importância de sermos pacíficos e amorosos, mesmo quando somos tratados de forma injusta ou cruel.
****

[[v19-11-1]]

^<<v19-11-1,1>>^ No quarto ano do reino de Ptolomeu e de Cleópatra, Dositeu que se dizia sacerdote e levita e igualmente seu filho, Ptolomeu, trouxeram a presente carta concernente aos Purim, dizendo que ela tinha sido traduzida por Lisímaco, filho de Ptolomeu, em Jerusalém.^&#42;1^

[[v19-11-2]]

^<<v19-11-2,2>>^ No segundo ano do reino de Assuero, o grande rei, no primeiro dia do mês de Nisã, Mardoqueu, filho de Jair, filho de Semei, filho de Cis, da tribo de Benjamim, teve um sonho.

[[v19-11-3]]

^<<v19-11-3,3>>^ Havia um judeu estabelecido em Susa, grande personagem, adido à corte do rei.

[[v19-11-4]]

^<<v19-11-4,4>>^ Era do número dos cativos que Nabucodonosor, rei da Babilônia, tinha deportado de Jerusalém com o rei Jeconias, de Judá.

[[v19-11-5]]

^<<v19-11-5,5>>^ Esta foi sua visão: clamores repentinos, tumultos, trovões, um tremor de terra, o terror por toda a terra.

[[v19-11-6]]

^<<v19-11-6,6>>^ Em seguida, repentinamente, avançaram dois grandes dragões, dispostos para acometer um ao outro.

[[v19-11-7]]

^<<v19-11-7,7>>^ Ao grito que lançaram, as nações se comoveram para combater contra a nação dos justos.

[[v19-11-8]]

^<<v19-11-8,8>>^ Foi um dia de escuridão e trevas: tribulação, angústia, perigo e terror sobre toda a terra.

[[v19-11-9]]

^<<v19-11-9,9>>^ O povo inteiro dos justos, cheio de terror, temendo todos os males, julgou-se a ponto de perecer

[[v19-11-10]]

^<<v19-11-10,10>>^ e clamou a Deus. Enquanto levantavam clamores eis que uma pequenina fonte toma proporções de um grande rio, uma massa de água.

[[v19-11-11]]

^<<v19-11-11,11>>^ A luz apareceu com o sol; os que estavam na humilhação foram exaltados e devoraram os nobres.

[[v19-11-12]]

^<<v19-11-12,12>>^ Depois de ter visto esse sonho e o que Deus queria fazer, Mardoqueu se levantou. Até a noite conservou esse sonho gravado no seu espírito, procurando conhecer o seu sentido.

'''

xref:019-ester/019-ester-010.adoc#v19-10-0[&#60; Capítulo Anterior] | <<v19-11-0,Topo>> | xref:019-ester/019-ester-012.adoc#v19-12-0[Próximo Capítulo &#62;]