include::./index.adoc[]

[[v37-4-0]]
=== Amós, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 4 do livro de Amós é uma mensagem de repreensão a Israel por sua desobediência e falta de arrependimento. Deus traz várias acusações contra o povo, mostrando que Ele os havia disciplinado de diversas formas para que se voltassem para Ele, mas eles persistiram em seus caminhos perversos. Abaixo estão cinco versículos relacionados com os temas abordados em Amós 4:
* Amós 4:6- "Eu lhes dei cereal escasso em todas as cidades, falta de pão em todas as suas aldeias, e mesmo assim vocês não voltaram para mim", Deus mostra como Ele havia tentado chamar a atenção de Israel por meio da escassez de alimento, mas mesmo assim o povo não se arrependeu de seus caminhos.
* Amós 4:8- "Mas ainda assim vocês não voltaram para mim", Deus continua a mostrar como havia enviado pestes e pragas sobre o povo, mas ainda assim eles não se arrependeram e voltaram para Ele.
* Amós 4:12- "Portanto, assim te farei, ó Israel! E porque te farei isso, apronta-te, ó Israel, para te encontrares com o teu Deus", Deus adverte o povo de Israel que, se eles continuarem em seus caminhos perversos, Ele os disciplinará ainda mais severamente.
* Amós 4:13- "Pois é ele quem forma os montes, quem cria o vento, e quem declara ao ser humano qual é o seu pensamento; quem faz a aurora e as trevas, e quem caminha sobre as alturas da terra. O Senhor Deus dos Exércitos é o seu nome", Deus mostra seu poder e autoridade sobre todas as coisas, incluindo a vida e destino de Israel.
* Amós 4:14- "Buscai o bem e não o mal, para que vivais; e assim o Senhor, o Deus dos Exércitos, estará convosco, como dizeis", Deus exorta Israel a buscar o bem e evitar o mal, mostrando que somente assim Ele estará com eles e abençoará suas vidas.
****

[[v37-4-1]]

^<<v37-4-1,1>>^ Ouvi este oráculo, novilhas de Basã, que viveis na montanha da Samaria! Vós que oprimis os fracos e maltratais os pobres, vós que dizeis a vossos maridos: “Trazei, e festejemos!”.

[[v37-4-2]]

^<<v37-4-2,2>>^ O Senhor Javé jurou pela sua santidade: Eis que virão dias para vós, em que vos arrastarão com relhas, e vossa posteridade com arpões.

[[v37-4-3]]

^<<v37-4-3,3>>^ Saireis pelas brechas, a cada uma diante de si, e sereis lançadas para o Hermon – oráculo do Senhor.

[[v37-4-4]]

^<<v37-4-4,4>>^ Ide a Betel e pecai! Ide a Guilgal e pecai ainda mais! Trazei cada manhã vossos sacrifícios, e ao terceiro dia vossos dízimos.^&#42;1^

[[v37-4-5]]

^<<v37-4-5,5>>^ Queimai com fermento vossas ofertas de ação de graças; anunciai, publicai oblações voluntárias! Porque isto é o que amais, filhos de Israel – oráculo do Senhor Javé.

[[v37-4-6]]

^<<v37-4-6,6>>^ Por isso, vos permiti a fome em todas as vossas cidades, a penúria de pão em todas as vossas localidades; mas não vos voltastes para mim – oráculo do Senhor.

[[v37-4-7]]

^<<v37-4-7,7>>^ Também vos suspendi a chuva três meses antes da colheita: fiz que chovesse sobre uma cidade, e não sobre outra; um campo recebeu as chuvas, e outro, sem a chuva, secou.

[[v37-4-8]]

^<<v37-4-8,8>>^ Duas, três cidades foram a uma outra para beber água, e não apagaram a sede; mas não vos voltastes para mim – oráculo do Senhor.

[[v37-4-9]]

^<<v37-4-9,9>>^ Eu vos feri com a ferrugem e a mangra no trigo; vossos numerosos jardins, vossas vinhas, vossas figueiras e vossos olivais foram devorados pelos gafanhotos; mas não vos voltastes para mim – oráculo do Senhor.

[[v37-4-10]]

^<<v37-4-10,10>>^ Mandei-vos uma peste semelhante à de outrora no Egito; feri com a espada os vossos jovens, e vossos cavalos foram tomados como espólio; fiz chegar ao vosso nariz o cheiro infecto de vossos acampamentos, mas não vos voltastes para mim – oráculo do Senhor.^&#42;1^

[[v37-4-11]]

^<<v37-4-11,11>>^ Causei no meio de vós uma confusão semelhante ao cataclismo divino de Sodoma e de Gomorra; ficastes como um tição que se tira do fogo, mas não vos voltastes para mim – oráculo do Senhor.^&#42;1^

[[v37-4-12]]

^<<v37-4-12,12>>^ Por isso, Israel, eis o que te infligirei; e porque te farei isso, prepara-te, Israel, para sair ao encontro de teu Deus!

[[v37-4-13]]

^<<v37-4-13,13>>^ Porque aquele que formou os montes e criou o vento, aquele que revela ao homem seus próprios pensamentos, e que muda as trevas em aurora e que anda por cima das alturas da terra, o seu nome é o Senhor, o Deus dos exércitos!

'''

xref:037-amos/037-amos-003.adoc#v37-3-0[&#60; Capítulo Anterior] | <<v37-4-0,Topo>> | xref:037-amos/037-amos-005.adoc#v37-5-0[Próximo Capítulo &#62;]