include::./index.adoc[]

[[v25-3-0]]
=== Eclesiastes, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiastes 3 é um capítulo que trata da dualidade da vida e do tempo, mostrando que há um tempo certo para tudo debaixo do céu, como nascer, morrer, plantar, colher, amar, odiar, chorar, rir, entre outras coisas. Alguns dos temas abordados são a transitoriedade da vida, a inevitabilidade da morte e a importância de se aproveitar cada momento.
* Salmos 90:12: "Ensina-nos a contar os nossos dias para que o nosso coração alcance sabedoria." O salmista pede a Deus que o ensine a contar seus dias para que ele possa viver de forma sábia e consciente, reconhecendo a brevidade da vida.
* Tiago 4:14: "Vocês nem sabem o que lhes acontecerá amanhã! Que é a sua vida? Vocês são como a neblina que aparece por um pouco de tempo e depois se dissipa." O apóstolo Tiago também destaca a brevidade da vida e sua incerteza, lembrando que a vida humana é como uma neblina que desaparece rapidamente.
* Hebreus 9:27: "E, assim como aos homens está ordenado morrerem uma só vez, vindo, depois disto, o juízo." O autor de Hebreus enfatiza que a morte é inevitável e que todos terão que prestar contas a Deus no juízo final.
* Salmo 39:4: "Faze-me conhecer, Senhor, o meu fim, e qual a medida dos meus dias, para que eu saiba quanto sou frágil." O salmista clama a Deus para que lhe mostre a brevidade da vida e sua fragilidade, reconhecendo que sua existência é finita e que precisa aproveitar cada momento.
* Mateus 6:34: "Portanto, não se preocupem com o amanhã, pois o amanhã trará suas próprias preocupações. Basta a cada dia o seu próprio mal." Jesus ensina que devemos viver um dia de cada vez, sem nos preocuparmos excessivamente com o futuro, mas sim aproveitando o presente.
****

[[v25-3-1]]

^<<v25-3-1,1>>^ Para tudo há um tempo, para cada coisa há um momento debaixo do céu:

[[v25-3-2]]

^<<v25-3-2,2>>^ tempo de nascer e tempo de morrer; tempo de plantar e tempo de arrancar o que se plantou.

[[v25-3-3]]

^<<v25-3-3,3>>^ Tempo de matar e tempo de curar; tempo de demolir e tempo de construir.

[[v25-3-4]]

^<<v25-3-4,4>>^ Tempo de chorar e tempo de rir; tempo de gemer e tempo de dançar.

[[v25-3-5]]

^<<v25-3-5,5>>^ Tempo de atirar pedras e tempo de ajuntá-las; tempo de abraçar e tempo de apartar-se.^&#42;1^

[[v25-3-6]]

^<<v25-3-6,6>>^ Tempo de procurar e tempo de perder; tempo de guardar e tempo de jogar fora.

[[v25-3-7]]

^<<v25-3-7,7>>^ Tempo de rasgar e tempo de costurar; tempo de calar e tempo de falar.

[[v25-3-8]]

^<<v25-3-8,8>>^ Tempo de amar e tempo de odiar; tempo de guerra e tempo de paz.

[[v25-3-9]]

^<<v25-3-9,9>>^ Que proveito tira o trabalhador de sua obra?

[[v25-3-10]]

^<<v25-3-10,10>>^ Vi o trabalho que Deus impôs aos homens, para que nele se ocupassem.

[[v25-3-11]]

^<<v25-3-11,11>>^ As coisas que Deus fez são boas a seu tempo. Ele pôs, além disso, no seu coração, a duração inteira, sem que ninguém possa compreender a obra divina de um extremo ao outro.^&#42;1^

[[v25-3-12]]

^<<v25-3-12,12>>^ Assim, concluí que nada é melhor para o homem do que alegrar-se e procurar o bem-estar durante sua vida.

[[v25-3-13]]

^<<v25-3-13,13>>^ Igualmente é dom de Deus que todos possam comer, beber e gozar do fruto de seu trabalho.

[[v25-3-14]]

^<<v25-3-14,14>>^ Reconheci que tudo o que Deus faz dura para sempre, sem que se possa ajuntar nada, nem nada suprimir. Deus procede dessa maneira para ser temido.^&#42;1^

[[v25-3-15]]

^<<v25-3-15,15>>^ Aquilo que é, já existia, e aquilo que há de ser, já existiu; Deus chama de novo o que passou.

[[v25-3-16]]

^<<v25-3-16,16>>^ Debaixo do sol, observei ainda o seguinte: a injustiça ocupa o lugar do direito, e a iniquidade toma o lugar da justiça.

[[v25-3-17]]

^<<v25-3-17,17>>^ Então, disse comigo mesmo: “Deus julgará o justo e o ímpio, porque há um tempo para cada coisa e um tempo para cada obra”.

[[v25-3-18]]

^<<v25-3-18,18>>^ Eu disse comigo mesmo a respeito dos homens: “Deus quer prová-los e mostrar-lhes que, quanto a eles, são semelhantes aos animais”.

[[v25-3-19]]

^<<v25-3-19,19>>^ Porque o destino dos filhos dos homens e o destino dos animais é o mesmo, um mesmo fim os espera. Tanto morre um como o outro. A ambos foi dado o mesmo sopro. A vantagem do homem sobre o animal é nula, porque tudo é vão.

[[v25-3-20]]

^<<v25-3-20,20>>^ Todos caminham para um mesmo lugar. Todos saem do pó e para o pó voltam.

[[v25-3-21]]

^<<v25-3-21,21>>^ Quem sabe se o sopro de vida dos filhos dos homens se eleva para o alto e o sopro de vida dos animais desce para a terra?^&#42;1^

[[v25-3-22]]

^<<v25-3-22,22>>^ E verifiquei que nada há de melhor para o homem do que alegrar-se com o fruto de seus trabalhos. Esta é a parte que lhe toca. Pois, quem lhe dará a conhecer o que acontecerá com o volver dos anos?

'''

xref:025-eclesiastes/025-eclesiastes-002.adoc#v25-2-0[&#60; Capítulo Anterior] | <<v25-3-0,Topo>> | xref:025-eclesiastes/025-eclesiastes-004.adoc#v25-4-0[Próximo Capítulo &#62;]