include::./index.adoc[]

[[v25-2-0]]
=== Eclesiastes, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Eclesiastes 2 aborda a busca do autor pela felicidade e significado na vida através de várias experiências e empreendimentos, mas no final ele conclui que tudo é vaidade e correr atrás do vento. Para complementar essa temática, seguem cinco versículos relacionados:
* Provérbios 16:9: "O coração do homem planeja o seu caminho, mas o Senhor dirige os seus passos." O autor de Eclesiastes tentou planejar sua vida em busca de felicidade e sucesso, mas acabou percebendo que a direção de Deus é a mais importante.
* Mateus 6:19-21: "Não ajuntem para vocês tesouros na terra, onde a traça e a ferrugem destroem, e onde os ladrões arrombam e furtam. Mas ajuntem para vocês tesouros no céu, onde a traça e a ferrugem não destroem, e onde os ladrões não arrombam nem furtam. Pois onde estiver o seu tesouro, aí também estará o seu coração." Este versículo ressalta a ideia de que a busca por riquezas e bens materiais é em vão, pois não trazem felicidade duradoura.
* Filipenses 4:11-12: "Não digo isto como por necessidade, porque já aprendi a contentar-me com o que tenho. Sei estar abatido, e sei também ter abundância; em toda a maneira, e em todas as coisas estou instruído, tanto a ter fartura, como a ter fome; tanto a ter abundância, como a padecer necessidade." O autor de Eclesiastes tentou preencher seu vazio interior com bens materiais e prazeres, mas este versículo ressalta que a verdadeira felicidade vem do contentamento com o que se tem.
* Romanos 12:2: "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente, para que sejam capazes de experimentar e comprovar a boa, agradável e perfeita vontade de Deus." O autor de Eclesiastes percebeu que seguir os padrões do mundo e buscar a felicidade nos prazeres mundanos é fútil, este versículo aponta para a necessidade de uma renovação da mente para encontrar a verdadeira felicidade.
* Mateus 16:26: "Pois que adiantará o homem ganhar o mundo inteiro e perder a sua alma? Ou, o que o homem poderá dar em troca de sua alma?" O autor de Eclesiastes tentou encontrar significado na vida através de prazeres e conquistas, mas este versículo ressalta a importância de priorizar a vida espiritual e a eternidade.
****

[[v25-2-1]]

^<<v25-2-1,1>>^ Eu disse comigo mesmo: “Vou tentar a alegria e gozar o prazer!”. Mas isso é também fugaz.

[[v25-2-2]]

^<<v25-2-2,2>>^ Do riso eu disse: “Loucura!”, e da alegria: “Para que serve?”.

[[v25-2-3]]

^<<v25-2-3,3>>^ Resolvi entregar minha carne ao vinho, enquanto meu coração se aplicaria ainda à sabedoria. Entreguei-me à loucura até ver o que é bom para os filhos dos homens fazerem durante toda a sua vida debaixo do céu.^&#42;1^

[[v25-2-4]]

^<<v25-2-4,4>>^ Empreendi grandes trabalhos, construí para mim casas e plantei vinhas;

[[v25-2-5]]

^<<v25-2-5,5>>^ fiz jardins e pomares, onde plantei árvores frutíferas de toda espécie.

[[v25-2-6]]

^<<v25-2-6,6>>^ Cavei reservatórios de água para regar o bosque de árvores que germinavam. Comprei escravos e escravas, e possuí outros nascidos em casa.^&#42;1^

[[v25-2-7]]

^<<v25-2-7,7>>^ Possuí muito gado, bois e ovelhas, mais que todos os que me precederam em Jerusalém.

[[v25-2-8]]

^<<v25-2-8,8>>^ Acumulei também prata e ouro, riquezas de reis e de províncias. Arranjei cantores e cantoras, e o que faz as delícias dos filhos dos homens: mulheres e mulheres.^&#42;1^

[[v25-2-9]]

^<<v25-2-9,9>>^ Fui maior que todos os que me precederam em Jerusalém. E, ainda assim, minha sabedoria permaneceu comigo.^&#42;1^

[[v25-2-10]]

^<<v25-2-10,10>>^ Tudo o que meus olhos desejaram não lhes recusei, nem privei meu coração de nenhuma alegria. Meu coração encontrava sua alegria no meu trabalho, e esse foi o fruto que dele tirei.

[[v25-2-11]]

^<<v25-2-11,11>>^ Mas, quando me pus a considerar todas as obras de minhas mãos e o trabalho ao qual me tinha dado para fazê-las, vi que em tudo havia fugacidade e vento que passa. Nada há de proveitoso debaixo do sol.

[[v25-2-12]]

^<<v25-2-12,12>>^ Passei então à meditação da sabedoria, da loucura e da tolice. Qual é o homem, designado desde muito tempo, que virá depois do rei?^&#42;1^

[[v25-2-13]]

^<<v25-2-13,13>>^ Cheguei à conclusão de que a sabedoria leva vantagem sobre a loucura, como a luz leva vantagem sobre as trevas.

[[v25-2-14]]

^<<v25-2-14,14>>^ Os olhos do sábio estão na sua cabeça, mas o insensato anda nas trevas. Mas notei que um mesmo destino espera a ambos.

[[v25-2-15]]

^<<v25-2-15,15>>^ Por isso, disse comigo mesmo: “A minha sorte será a mesma que a do insensato. Então, para que me serve toda a minha sabedoria?”. E concluí comigo mesmo que tudo isso é ainda ilusão.^&#42;1^

[[v25-2-16]]

^<<v25-2-16,16>>^ Porque a memória do sábio não é mais eterna que a do insensato, pois que, passados alguns dias, ambos serão esquecidos. Tanto morre o sábio como morre o louco!

[[v25-2-17]]

^<<v25-2-17,17>>^ E assim detestei a vida, pois a meus olhos tudo é mau no que se passa debaixo do sol; sim, tudo é efêmero e vento que passa.

[[v25-2-18]]

^<<v25-2-18,18>>^ Também se tornou odioso para mim todo o trabalho que produzi debaixo do sol, visto que devo deixá-lo àquele que virá depois de mim.

[[v25-2-19]]

^<<v25-2-19,19>>^ E quem sabe se ele será sábio ou insensato? Contudo, é ele quem disporá de todo o fruto dos meus trabalhos que debaixo do sol me custaram fadiga e sabedoria. Também isso é fugaz.

[[v25-2-20]]

^<<v25-2-20,20>>^ E senti o coração cheio de desgosto por todo o labor que suportei debaixo do sol.

[[v25-2-21]]

^<<v25-2-21,21>>^ Porque há homem que trabalha com sabedoria, ciência e bom êxito, para deixar o fruto de seu ganho a outro que em nada colaborou. Também isso é ilusão e grande desgraça.

[[v25-2-22]]

^<<v25-2-22,22>>^ Com efeito, que resta ao homem de todo o seu labor, de todas as suas azáfamas a que se entregou debaixo do sol?

[[v25-2-23]]

^<<v25-2-23,23>>^ Todos os seus dias são apenas dores, seus trabalhos, apenas tristezas; mesmo durante a noite ele não goza de descanso. Isso é ainda vaidade.

[[v25-2-24]]

^<<v25-2-24,24>>^ Não há nada melhor para o homem do que comer, beber e gozar o bem-estar do seu trabalho. Notei que também isso vem da mão de Deus,

[[v25-2-25]]

^<<v25-2-25,25>>^ pois, quem come e bebe senão graças a ele? Àquele que lhe é agradável Deus dá sabedoria, ciência e alegria; ao passo que ao pecador ele dá a tarefa de juntar e acumular bens, que depois passará a quem lhe agradar. Isso é ainda fugaz e vento que passa.^&#42;1^

'''

xref:025-eclesiastes/025-eclesiastes-001.adoc#v25-1-0[&#60; Capítulo Anterior] | <<v25-2-0,Topo>> | xref:025-eclesiastes/025-eclesiastes-003.adoc#v25-3-0[Próximo Capítulo &#62;]