include::./index.adoc[]

[[v3-25-0]]
=== Levítico, 25
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Levítico 25 trata das leis relativas ao ano sabático e ao ano do jubileu, em que a terra deve descansar, os escravos e as dívidas devem ser liberados e a propriedade da terra deve ser restaurada aos seus proprietários originais. Abaixo estão cinco versículos relacionados aos temas abordados neste capítulo:
* Deuteronômio 15:1-2: "No fim de cada sete anos, você deve cancelar todas as dívidas. Esta é a forma como você deve cancelar as dívidas: Todo credor deve perdoar a dívida que tenha contraído com o seu próximo. Ele não deve exigir pagamento do seu próximo ou do seu irmão, porque o ano do cancelamento das dívidas foi proclamado em honra do Senhor." Este versículo se relaciona com Levítico 25:10, que trata do ano do jubileu, quando todas as dívidas são canceladas e as propriedades são devolvidas aos seus proprietários originais.
* Jeremias 34:8-9: "A palavra do Senhor veio a Jeremias depois que o rei Zedequias fez um acordo com todo o povo de Jerusalém para proclamar a libertação dos escravos. Cada um deveria libertar seu escravo hebreu, homem ou mulher, e nenhum deles deveria continuar a explorar os seus compatriotas judeus." Este versículo se relaciona com Levítico 25:39-41, que trata da libertação dos escravos hebreus no ano do jubileu.
* Isaías 61:1-2: "O Espírito do Soberano Senhor está sobre mim, porque o Senhor me ungiu para pregar boas novas aos pobres. Ele me enviou para cuidar dos que estão com o coração quebrantado, anunciar liberdade aos cativos e libertação das trevas aos prisioneiros, para proclamar o ano da graça do Senhor." Este versículo se relaciona com Levítico 25:10, que trata do ano do jubileu, um ano de libertação e perdão.
* Ezequiel 34:1-4: "A palavra do Senhor veio a mim, dizendo: Filho do homem, profetize contra os pastores de Israel. Profetize e diga-lhes: Assim diz o Senhor: Ai dos pastores de Israel que só cuidam de si mesmos! Não deveriam os pastores cuidar do rebanho? Vocês bebem o leite, vestem a lã e matam a gordura, mas não cuidam do rebanho." Este versículo se relaciona com Levítico 25:1-7, que trata do ano sabático, em que a terra deve descansar e o povo deve confiar na provisão de Deus.
* 2 Crônicas 36:20-21: "Ele [Nabucodonosor] os levou como prisioneiros para a Babilônia. Todos os utensílios sagrados do templo do Senhor, grandes e pequenos, os tesouros da casa do Senhor e os tesouros do rei e dos seus líderes, foram levados para a Babilônia.
****

[[v3-25-1]]

^<<v3-25-1,1>>^ O Senhor disse a Moisés no monte Sinai: “Dize aos israelitas o seguinte:

[[v3-25-2]]

^<<v3-25-2,2>>^ Quando tiverdes entrado na terra que vos hei de dar, a terra repousará: esse será um sábado em honra do Senhor.

[[v3-25-3]]

^<<v3-25-3,3>>^ Durante seis anos semearás a tua terra, durante seis anos podarás a tua vinha e recolherás os seus frutos.

[[v3-25-4]]

^<<v3-25-4,4>>^ Mas o sétimo ano será um sábado, um repouso para a terra, um sábado em honra do Senhor: não semearás o teu campo, nem podarás a tua vinha;

[[v3-25-5]]

^<<v3-25-5,5>>^ não colherás o que nascer dos grãos caídos de tua ceifa, nem as uvas de tua vinha não podada, porque é um ano de repouso para a terra.

[[v3-25-6]]

^<<v3-25-6,6>>^ Mas o que a terra der espontaneamente durante o seu sábado, vos servirá de alimento, a ti, ao teu servo e à tua serva, ao teu operário ou ao estrangeiro que mora contigo;

[[v3-25-7]]

^<<v3-25-7,7>>^ tudo o que nascer servirá de alimento também ao teu rebanho e aos animais que estão em tua terra.

[[v3-25-8]]

^<<v3-25-8,8>>^ Contarás sete anos sabáticos, sete vezes sete anos, cuja duração fará um período de quarenta e nove anos.

[[v3-25-9]]

^<<v3-25-9,9>>^ Tocarás então a trombeta no décimo dia do sétimo mês: tocareis a trombeta no dia das Expiações em toda a vossa terra.

[[v3-25-10]]

^<<v3-25-10,10>>^ Santificareis o quinquagésimo ano e publicareis a liberdade na terra para todos os seus habitantes. Será o vosso jubileu. Voltareis cada um para as suas terras e para a sua família.

[[v3-25-11]]

^<<v3-25-11,11>>^ O quinquagésimo ano será para vós um jubileu: não semeareis, não ceifareis o que a terra produzir espontaneamente, e não vindimareis a vinha não podada,

[[v3-25-12]]

^<<v3-25-12,12>>^ pois é o jubileu que vos será sagrado. Comereis o produto de vossos campos.

[[v3-25-13]]

^<<v3-25-13,13>>^ Nesse ano jubilar, voltareis cada um à sua possessão.

[[v3-25-14]]

^<<v3-25-14,14>>^ Se venderdes ou comprardes alguma coisa de vosso próximo, ninguém dentre vós cause dano ao seu irmão.

[[v3-25-15]]

^<<v3-25-15,15>>^ Comprarás ao teu próximo segundo o número de anos decorridos desde o jubileu, e ele te venderá segundo o número de anos de colheita.

[[v3-25-16]]

^<<v3-25-16,16>>^ Aumentarás o preço em razão dos anos que restarem, e o abaixarás à medida que os anos diminuírem, porque é o número de colheitas que ele te vende.

[[v3-25-17]]

^<<v3-25-17,17>>^ Ninguém prejudique o seu próximo. Teme o teu Deus. Eu sou o Senhor, vosso Deus.

[[v3-25-18]]

^<<v3-25-18,18>>^ Obedecereis às minhas leis; guardareis os meus preceitos e os cumprireis, a fim de habitardes em segurança na terra.

[[v3-25-19]]

^<<v3-25-19,19>>^ A terra vos dará os seus frutos, comereis até vos saciardes e vivereis em segurança.

[[v3-25-20]]

^<<v3-25-20,20>>^ Se disserdes: ‘Que comeremos nós no sétimo ano, se não semearmos, nem recolhermos os nossos frutos?’.

[[v3-25-21]]

^<<v3-25-21,21>>^ Eu vos darei a minha bênção no sexto ano, e a terra produzirá uma colheita para três anos.

[[v3-25-22]]

^<<v3-25-22,22>>^ Semeareis no oitavo ano, e comereis da antiga colheita até o ano-novo: comereis da antiga colheita até que venha a nova”.

[[v3-25-23]]

^<<v3-25-23,23>>^ “A terra não se venderá para sempre, porque a terra é minha, e vós estais em minha casa como estrangeiros ou hóspedes.

[[v3-25-24]]

^<<v3-25-24,24>>^ Portanto, em todo o território de vossa propriedade, concedereis o direito de resgatar a terra.

[[v3-25-25]]

^<<v3-25-25,25>>^ Se teu irmão se tornar pobre e vender uma parte de seu bem, seu parente mais próximo que tiver o direito de resgate se apresentará e resgatará o que o seu irmão vendeu.

[[v3-25-26]]

^<<v3-25-26,26>>^ Se um homem não tiver ninguém que tenha o direito de resgate, mas procurar ele mesmo os meios de fazer o seu resgate,

[[v3-25-27]]

^<<v3-25-27,27>>^ contará os anos desde que fez a venda, restituirá o excedente ao comprador, e se reintegrará na sua propriedade.

[[v3-25-28]]

^<<v3-25-28,28>>^ Se não encontrar, porém, meios de indenizar, a terra vendida ficará nas mãos do comprador até o ano jubilar. Sairá do poder deste, no ano do jubileu, e voltará à posse do seu antigo dono.

[[v3-25-29]]

^<<v3-25-29,29>>^ Se um homem vender uma casa de habitação situada dentro de uma cidade murada, terá o direito de resgatá-la até o fim do ano que se segue à venda: seu direito de resgate será de um ano completo.

[[v3-25-30]]

^<<v3-25-30,30>>^ Se a casa situada na cidade murada não for resgatada antes do fim do ano completo, ela pertencerá sempre ao comprador e aos seus descendentes: não sairá de suas mãos no jubileu.

[[v3-25-31]]

^<<v3-25-31,31>>^ Entretanto, as casas das povoações que não têm muros serão consideradas como fazendo parte do fundo de terras; poderão ser resgatadas e serão livres no ano do jubileu.

[[v3-25-32]]

^<<v3-25-32,32>>^ Quanto às cidades dos levitas e às casas que possuem, terão eles um direito de resgate perpétuo.

[[v3-25-33]]

^<<v3-25-33,33>>^ Quem comprar dos levitas uma casa, sairá no jubileu da casa vendida e da cidade em que a possua, porque as casas das cidades dos levitas são sua propriedade no meio dos israelitas.

[[v3-25-34]]

^<<v3-25-34,34>>^ Os campos dos arrabaldes das cidades dos levitas não serão vendidos, porque são sua propriedade perpétua.”

[[v3-25-35]]

^<<v3-25-35,35>>^ “Se teu irmão se tornar pobre junto de ti, e as suas mãos se enfraquecerem, sustenta-o, mesmo que se trate de um estrangeiro ou de um hóspede, a fim de que ele viva contigo.

[[v3-25-36]]

^<<v3-25-36,36>>^ Não receberás dele juros nem ganho; mas temerás o teu Deus, para que o teu irmão viva contigo.

[[v3-25-37]]

^<<v3-25-37,37>>^ Não lhe emprestarás com juros o teu dinheiro, e não lhe darás os teus víveres por amor ao lucro.

[[v3-25-38]]

^<<v3-25-38,38>>^ Eu sou o Senhor, vosso Deus, que vos tirei do Egito, para vos dar a terra de Canaã e para ser o vosso Deus.

[[v3-25-39]]

^<<v3-25-39,39>>^ Se teu irmão se tornar pobre junto de ti e se se vender a ti, não exigirás dele um serviço de escravo.

[[v3-25-40]]

^<<v3-25-40,40>>^ Estará em tua casa como um operário, e como um hóspede estará a teu serviço até o ano jubilar.

[[v3-25-41]]

^<<v3-25-41,41>>^ E sairá então de tua casa, ele e seus filhos com ele; voltará para a sua família e para a herança de seus pais.

[[v3-25-42]]

^<<v3-25-42,42>>^ Porque são meus servos que tirei do Egito, não devem ser vendidos como se vende um escravo.

[[v3-25-43]]

^<<v3-25-43,43>>^ Não dominarás sobre ele com rigor, mas temerás o teu Deus.

[[v3-25-44]]

^<<v3-25-44,44>>^ Vossos escravos, homens ou mulheres, os tomareis dentre as nações que vos cercam; delas comprareis os vossos escravos, homens ou mulheres.

[[v3-25-45]]

^<<v3-25-45,45>>^ Podereis também comprá-los dentre os filhos dos estrangeiros que habitam no meio de vós, das suas famílias que moram convosco dentre os filhos que eles tiverem gerado em vossa terra serão vossa propriedade.

[[v3-25-46]]

^<<v3-25-46,46>>^ Podereis deixá-los por herança a vossos filhos depois de vós, para que os possuam plenamente como escravos perpétuos. Mas, quanto a vossos irmãos, os israelitas, não dominareis com rigor uns sobre os outros.

[[v3-25-47]]

^<<v3-25-47,47>>^ Se se tornar rico o estrangeiro, estabelecido no meio de ti, e teu irmão, seu vizinho, se tornar pobre e se vender a esse estrangeiro que vive no meio de ti,

[[v3-25-48]]

^<<v3-25-48,48>>^ haverá para aquele que se vende um direito de resgate: um de seus irmãos poderá resgatá-lo.

[[v3-25-49]]

^<<v3-25-49,49>>^ Seu tio, o filho de seu tio, ou um de seus próximos parentes poderá também resgatá-lo. Ou então ele mesmo se resgatará, se conseguir os meios de fazê-lo.

[[v3-25-50]]

^<<v3-25-50,50>>^ Com aquele que o tiver comprado, fará a conta desde o ano em que se vendeu a ele até o ano jubilar, e o preço de venda se estimará segundo o número dos anos, avaliando seus dias de trabalho como os de um operário.

[[v3-25-51]]

^<<v3-25-51,51>>^ Se houver ainda muitos anos, pagará o seu resgate em razão desses anos, segundo o preço pelo qual foi comprado;

[[v3-25-52]]

^<<v3-25-52,52>>^ e se faltarem poucos anos até o ano jubilar, fará a conta disso, e pagará o seu resgate em proporção ao número desses anos.

[[v3-25-53]]

^<<v3-25-53,53>>^ Ele estará em sua casa como um operário que trabalha ano por ano, e o comprador não o tratará com rudeza à tua vista.

[[v3-25-54]]

^<<v3-25-54,54>>^ Se ele não for resgatado de nenhuma dessas maneiras, sairá livre no ano jubilar, ele e seus filhos,

[[v3-25-55]]

^<<v3-25-55,55>>^ porque os filhos de Israel são meus servos. São meus servos que tirei da terra do Egito. Eu sou o Senhor, vosso Deus.”

'''

xref:003-levitico/003-levitico-024.adoc#v3-24-0[&#60; Capítulo Anterior] | <<v3-25-0,Topo>> | xref:003-levitico/003-levitico-026.adoc#v3-26-0[Próximo Capítulo &#62;]