include::./index.adoc[]

[[v3-24-0]]
=== Levítico, 24
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 24 do livro de Levítico trata das leis que envolvem o azeite e o pão da proposição, bem como a punição para aqueles que blasfemam o nome de Deus. Os versículos selecionados são os seguintes:
* Êxodo 27:20-21: "Também ordenarás aos filhos de Israel que te tragam azeite puro de oliveiras, batido, para o candelabro, para que se mantenha acesa a lâmpada continuamente. Na tenda da congregação, fora do véu que está diante do testemunho, Arão e seus filhos a porão em ordem, desde a tarde até pela manhã, perante o Senhor; é estatuto perpétuo para as suas gerações, da parte dos filhos de Israel." Este versículo aborda o uso do azeite puro para manter a lâmpada do candelabro acesa continuamente, como um símbolo da presença de Deus no meio do povo.
* Êxodo 25:30: "E porás sobre a mesa pão da proposição perante a minha face continuamente." Este versículo se refere ao pão da proposição que é colocado na mesa no santuário como uma oferta contínua para Deus.
* Levítico 24:11-12: "E o filho da mulher israelita blasfemou o nome do Senhor, e o amaldiçoou; então o trouxeram a Moisés (e o nome de sua mãe era Selomite, filha de Dibri, da tribo de Dã). E o puseram na prisão, até que se declarasse a sentença pela boca do Senhor." Este versículo descreve a punição para aqueles que blasfemam o nome do Senhor, que é a prisão até que a sentença seja declarada.
* Mateus 12:31-32: "Por isso eu vos digo: Todo o pecado e blasfêmia se perdoará aos homens, mas a blasfêmia contra o Espírito não será perdoada aos homens. E, se qualquer disser alguma palavra contra o Filho do homem, ser-lhe-á perdoado; mas, se alguém falar contra o Espírito Santo, não lhe será perdoado, nem neste século nem no futuro." Este versículo se refere ao pecado da blasfêmia contra o Espírito Santo, que é considerado um pecado imperdoável.
* Tiago 1:26: "Se alguém cuida ser religioso, e não refreia a sua língua, mas engana o seu coração, a religião desse é vã." Este versículo destaca a importância de controlar a língua e não falar de forma blasfema ou enganosa, para que a religião não seja em vão.
****

[[v3-24-1]]

^<<v3-24-1,1>>^ O Senhor disse a Moisés:

[[v3-24-2]]

^<<v3-24-2,2>>^ “Ordena aos israelitas que te tragam óleo puro de olivas esmagadas para manter continuamente acesas as lâmpadas do candelabro.

[[v3-24-3]]

^<<v3-24-3,3>>^ Aarão as preparará fora do véu do testemunho, na tenda de reunião, a fim de que elas queimem ininterruptamente, da tarde à manhã, diante do Senhor.

[[v3-24-4]]

^<<v3-24-4,4>>^ Disporá as lâmpadas no candelabro de ouro puro, para que queimem sempre diante do Senhor.

[[v3-24-5]]

^<<v3-24-5,5>>^ Tomarás também flor de farinha e farás com ela doze bolos cozidos, cada um dos quais com dois décimos de efá,

[[v3-24-6]]

^<<v3-24-6,6>>^ e os colocará em duas pilhas de seis na mesa de ouro puro diante do Senhor.

[[v3-24-7]]

^<<v3-24-7,7>>^ Sobre cada pilha porás incenso puro, que será um memorial oferecido pelo fogo ao Senhor.

[[v3-24-8]]

^<<v3-24-8,8>>^ Esses pães serão colocados diante do Senhor a cada sábado, continuamente, da parte dos israelitas: essa é uma aliança perpétua.

[[v3-24-9]]

^<<v3-24-9,9>>^ Esses pães serão propriedade de Aarão e de seus filhos, que os comerão no lugar santo; isso será para eles uma coisa santíssima entre as ofertas feitas pelo fogo ao Senhor. É uma lei perpétua”.

[[v3-24-10]]

^<<v3-24-10,10>>^ O filho de uma mulher israelita, tendo por pai um egípcio, veio entre os israelitas. E, discutindo no acampamento com um deles,

[[v3-24-11]]

^<<v3-24-11,11>>^ o filho da mulher israelita blasfemou contra o santo nome e o amaldiçoou. Sua mãe chamava-se Salomit, filha de Dabri, da tribo de Dã.

[[v3-24-12]]

^<<v3-24-12,12>>^ Puseram-no em prisão até que Moisés tomasse uma decisão, segundo a ordem do Senhor.

[[v3-24-13]]

^<<v3-24-13,13>>^ Então o Senhor disse a Moisés:

[[v3-24-14]]

^<<v3-24-14,14>>^ “Faze sair do acampamento o blasfemador, e todos aqueles que o ouviram ponham a mão sobre a sua cabeça, e toda a assembleia o apedreje.

[[v3-24-15]]

^<<v3-24-15,15>>^ Dirás aos israelitas: Todo aquele que amaldiçoar o seu Deus levará o seu pecado.

[[v3-24-16]]

^<<v3-24-16,16>>^ Quem blasfemar o nome do Senhor será punido de morte: toda a assembleia o apedrejará. Quer seja ele estrangeiro ou natural, se blasfemar contra o santo nome, será punido de morte”.

[[v3-24-17]]

^<<v3-24-17,17>>^ “Todo aquele que ferir mortalmente um homem será morto.

[[v3-24-18]]

^<<v3-24-18,18>>^ Quem tiver ferido de morte um animal doméstico, dará outro em seu lugar: vida por vida.

[[v3-24-19]]

^<<v3-24-19,19>>^ Se um homem ferir o seu próximo, assim como fez, assim se lhe fará a ele:

[[v3-24-20]]

^<<v3-24-20,20>>^ fratura por fratura, olho por olho e dente por dente. Sofrerá o mesmo que ele fez ao seu próximo.

[[v3-24-21]]

^<<v3-24-21,21>>^ Quem matar um animal restituirá outro, mas o que matar um homem será punido de morte.

[[v3-24-22]]

^<<v3-24-22,22>>^ Só haverá uma lei entre vós tanto para o estrangeiro como para o natural: porque eu sou o Senhor, vosso Deus.”

[[v3-24-23]]

^<<v3-24-23,23>>^ Moisés transmitiu essas normas aos israelitas. Tiraram do acampamento o blasfemo e o apedrejaram, conforme a ordem que o Senhor tinha dado a Moisés.

'''

xref:003-levitico/003-levitico-023.adoc#v3-23-0[&#60; Capítulo Anterior] | <<v3-24-0,Topo>> | xref:003-levitico/003-levitico-025.adoc#v3-25-0[Próximo Capítulo &#62;]