include::./index.adoc[]

[[v3-16-0]]
=== Levítico, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 16 de Levítico trata da cerimônia do Dia da Expiação, na qual o sumo sacerdote fazia uma série de ofertas e purificações para expiar os pecados do povo de Israel. Os versículos selecionados são:
* Êxodo 30:10: "E, uma vez por ano, Arão fará expiação sobre as pontas do altar; com o sangue da oferta pelo pecado da expiação, ele fará expiação sobre ele, uma vez por ano, por todas as vossas gerações. É santíssimo ao Senhor." Este versículo menciona a oferta pelo pecado da expiação, que era usada no Dia da Expiação em Levítico 16.
* Hebreus 9:7: "Mas somente o sumo sacerdote entra no segundo tabernáculo, uma vez por ano, não sem sangue, que ele oferece por si mesmo e pelos pecados do povo que o ignorava." Este versículo se refere ao papel do sumo sacerdote no Dia da Expiação e a necessidade de sangue para expiar os pecados.
* Levítico 4:6: "E ele fará expiação pelo pecado que cometeu a respeito do santuário, e ele fará expiação por causa da impureza dos filhos de Israel, e por causa das suas transgressões, e por todos os seus pecados; e assim ele fará pela tenda da congregação que habita com eles no meio das suas impurezas." Este versículo fala sobre a necessidade de expiação pelos pecados do povo e da tenda da congregação.
* Hebreus 9:14: "Quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo sem mácula a Deus, purificará a nossa consciência das obras mortas para servirmos ao Deus vivo?" Este versículo menciona a purificação pelo sangue de Cristo, que cumpre o papel das ofertas de expiação no Antigo Testamento.
* Levítico 16:34: "E isto será para vós um estatuto perpétuo, para fazer expiação pelos filhos de Israel de todas as suas transgressões, uma vez por ano." Este versículo reforça a importância da cerimônia do Dia da Expiação como uma prática anual para expiar os pecados do povo.
****

[[v3-16-1]]

^<<v3-16-1,1>>^ O Senhor falou a Moisés, depois da morte dos dois filhos de Aarão, que foram mortos por se terem aproximado do Senhor.

[[v3-16-2]]

^<<v3-16-2,2>>^ O Senhor disse-lhe: “Recomenda a teu irmão Aarão que nunca entre no santuário, além do véu, diante do propiciatório que recobre a arca, para que não morra, porque apareço na nuvem por cima do propiciatório.

[[v3-16-3]]

^<<v3-16-3,3>>^ Eis como Aarão entrará no santuário: tomará um novilho para o sacrifício pelo pecado e um carneiro para o holocausto.

[[v3-16-4]]

^<<v3-16-4,4>>^ Vestirá uma túnica sagrada de linho, levará sobre o corpo um calção de linho, cingirá um cinto de linho e porá na cabeça um turbante de linho. Essas são as vestes sagradas, que ele só vestirá depois de se ter lavado.

[[v3-16-5]]

^<<v3-16-5,5>>^ Receberá da assembleia dos israelitas dois bodes destinados ao sacrifício pelo pecado e um carneiro para o holocausto.

[[v3-16-6]]

^<<v3-16-6,6>>^ Aarão oferecerá por si mesmo o touro em sacrifício pelo pecado e fará a expiação por si mesmo e pela sua casa.

[[v3-16-7]]

^<<v3-16-7,7>>^ Tomará os dois bodes e os colocará diante do Senhor, à entrada da tenda de reunião.

[[v3-16-8]]

^<<v3-16-8,8>>^ Lançará sorte sobre os dois bodes, uma para o Senhor, e outra para Azazel.^&#42;1^

[[v3-16-9]]

^<<v3-16-9,9>>^ Oferecerá o bode sobre o qual caiu a sorte para o Senhor e o oferecerá em sacrifício pelo pecado.

[[v3-16-10]]

^<<v3-16-10,10>>^ Quanto ao bode sobre o qual caiu a sorte para Azazel, será apresentado vivo ao Senhor, para que se faça a expiação sobre ele, a fim de enviá-lo a Azazel, no deserto.

[[v3-16-11]]

^<<v3-16-11,11>>^ Aarão oferecerá o touro pelo seu pecado, e fará a expiação por si mesmo e pela sua casa. Degolará o touro destinado ao sacrifício pelo pecado e,

[[v3-16-12]]

^<<v3-16-12,12>>^ tomando o turíbulo, que ele terá enchido de brasas do altar diante do Senhor, bem como dois punhados de perfume aromático em pó, entrará com tudo para dentro do véu.

[[v3-16-13]]

^<<v3-16-13,13>>^ Porá o incenso no fogo diante do Senhor, para que a nuvem do perfume cubra o propiciatório da arca, e Aarão não morra.

[[v3-16-14]]

^<<v3-16-14,14>>^ Tomará o sangue do touro e o aspergirá com dedo sobre o propiciatório, pela frente, e depois aspergirá com o dedo sete vezes defronte do propiciatório.

[[v3-16-15]]

^<<v3-16-15,15>>^ Imolará, enfim, o bode do sacrifício pelo pecado do povo e levará seu sangue para outro lado do véu. Fará com esse sangue como fez com o sangue do touro, aspergindo o propiciatório e a frente dele.

[[v3-16-16]]

^<<v3-16-16,16>>^ É assim que fará a expiação pelo santuário, por causa das impurezas dos israelitas e de suas transgressões, e de todos os seus pecados. Da mesma forma fará pela tenda de reunião, que está com eles no meio de suas imundícies.

[[v3-16-17]]

^<<v3-16-17,17>>^ Ninguém esteja na tenda de reunião quando Aarão entrar para fazer a expiação no santuário até sair. Fará assim a expiação por si mesmo, pela sua família e por toda a assembleia de Israel.

[[v3-16-18]]

^<<v3-16-18,18>>^ Quando tiver saído, irá para o altar que está diante do Senhor e fará a expiação por esse altar: tomará o sangue do touro e do bode e o porá nos chifres do altar em toda a volta.

[[v3-16-19]]

^<<v3-16-19,19>>^ Aspergirá com o dedo sete vezes o altar, para purificá-lo e santificá-lo por causa das imundícies dos israelitas.

[[v3-16-20]]

^<<v3-16-20,20>>^ Concluída a expiação do santuário, da tenda de reunião e do altar, Aarão trará o bode vivo.

[[v3-16-21]]

^<<v3-16-21,21>>^ Imporá as duas mãos sobre a sua cabeça e confessará sobre ele todas as iniquidades dos israelitas, todas as suas desobediências, todos os seus pecados e os porá sobre a cabeça do bode e o envia-rá ao deserto pelas mãos de um homem encarregado disso.

[[v3-16-22]]

^<<v3-16-22,22>>^ O bode levará, pois, sobre si, todas as iniquidades deles para uma terra selvagem. Quando o bode tiver sido mandado para o deserto,

[[v3-16-23]]

^<<v3-16-23,23>>^ Aarão voltará para a tenda de reunião, tirará as vestes de linho que ele pôs à sua entrada no santuário, e as deporá ali.

[[v3-16-24]]

^<<v3-16-24,24>>^ Lavará o seu corpo no lugar santo, retomará depois suas vestes e sairá para imolar o seu holocausto e o povo, fazendo a expiação por ele e pelo povo.

[[v3-16-25]]

^<<v3-16-25,25>>^ Queimará no altar a gordura do sacrifício pelo pecado.

[[v3-16-26]]

^<<v3-16-26,26>>^ O homem que tiver conduzido o bode a Azazel no deserto, lavará suas vestes e tomará banho. Depois disso, poderá voltar ao acampamento.

[[v3-16-27]]

^<<v3-16-27,27>>^ Serão levados para fora do acampamento o touro e o bode oferecidos em sacrifício pelo pecado, cujo sangue terá sido levado ao santuário para fazer a expiação. As peles, carnes e excrementos serão queimados.

[[v3-16-28]]

^<<v3-16-28,28>>^ Aquele que os tiver queimado lavará as suas vestes, tomará banho e depois disso poderá voltar ao acampamento.

[[v3-16-29]]

^<<v3-16-29,29>>^ Essa será para vós uma lei perpétua: No sétimo mês, no décimo dia do mês, jejuareis e não fareis trabalho algum, tanto o nativo como o estrangeiro que habita no meio de vós,^&#42;1^

[[v3-16-30]]

^<<v3-16-30,30>>^ porque nesse dia se fará a expiação por vós, para que vos purifiqueis e sejais livres de todos os vossos pecados diante do Senhor.

[[v3-16-31]]

^<<v3-16-31,31>>^ Será um sábado, um dia de descanso para vós, durante o qual jejuareis. Essa é uma instituição perpétua.

[[v3-16-32]]

^<<v3-16-32,32>>^ A expiação será feita pelo sacerdote que foi ungido e empossado para exercer o sacerdócio em lugar de seu pai. Revestirá as vestes de linho, as vestes sagradas,

[[v3-16-33]]

^<<v3-16-33,33>>^ e fará a expiação pelo santuário sagrado, pela tenda de reunião, pelo altar, pelos sacerdotes e por toda a assembleia.

[[v3-16-34]]

^<<v3-16-34,34>>^ Essa será para vós uma instituição perpétua: uma vez por ano se fará a expiação de todos os pecados dos israelitas”. Aarão fez como o Senhor o tinha ordenado a Moisés.

'''

xref:003-levitico/003-levitico-015.adoc#v3-15-0[&#60; Capítulo Anterior] | <<v3-16-0,Topo>> | xref:003-levitico/003-levitico-017.adoc#v3-17-0[Próximo Capítulo &#62;]