include::./index.adoc[]

[[v3-3-0]]
=== Levítico, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Levítico 3 trata da oferta de sacrifício de paz, que é oferecida voluntariamente como um ato de gratidão e comunhão com Deus. O capítulo descreve os requisitos para o sacrifício de animais de rebanho, como ovelhas, cabras e bovinos. Os versículos selecionados são:
* Levítico 22:29-30: "Quando vocês oferecerem um sacrifício de ação de graças ao Senhor, ofereçam-no de tal forma que seja aceitável. No mesmo dia comam-no. Não deixem nada dele sobrar até a manhã seguinte. Eu sou o Senhor." Este versículo fala sobre a importância de oferecer o sacrifício de ação de graças de forma aceitável a Deus e consumi-lo no mesmo dia, o que é um princípio importante no capítulo 3.
* Hebreus 13:15: "Por meio de Jesus, portanto, ofereçamos continuamente a Deus um sacrifício de louvor, que é fruto de lábios que confessam o seu nome." Este versículo mostra que, embora não sejamos mais obrigados a oferecer sacrifícios de animais, ainda podemos oferecer sacrifícios a Deus, como o sacrifício de louvor.
* Salmo 50:14: "Ofereça a Deus em sacrifício a sua gratidão, cumpra os seus votos para com o Altíssimo," Este versículo nos lembra que o sacrifício de paz era um ato de gratidão e comunhão com Deus, e que podemos oferecer nossos próprios sacrifícios de gratidão e compromisso.
* Isaías 53:5: "Mas ele foi traspassado por causa das nossas transgressões, foi esmagado por causa de nossas iniquidades; o castigo que nos trouxe paz estava sobre ele, e pelas suas feridas fomos curados." Este versículo nos lembra que Jesus é o sacrifício final que traz paz entre Deus e o homem.
* Romanos 5:1: "Tendo sido, pois, justificados pela fé, temos paz com Deus, por nosso Senhor Jesus Cristo," Este versículo destaca a importância da paz com Deus e como ela é alcançada através de Jesus Cristo.
****

[[v3-3-1]]

^<<v3-3-1,1>>^ “Quando alguém oferecer um sacrifício pacífico, e quiser oferecer gado, macho ou fêmea, oferecerá um que seja sem defeito ao Senhor.^&#42;1^

[[v3-3-2]]

^<<v3-3-2,2>>^ Ele porá a mão sobre a cabeça da vítima, e a imolará à entrada da tenda de reunião. Os sacerdotes, filhos de Aarão, aspergirão o sangue ao redor do altar.

[[v3-3-3]]

^<<v3-3-3,3>>^ Desse sacrifício pacífico, oferecerá, à guisa de sacrifício pelo fogo ao Senhor, a gordura que envolve as entranhas e toda gordura aderente a elas,

[[v3-3-4]]

^<<v3-3-4,4>>^ os dois rins com a gordura que os envolve na região lombar e a pele que recobre o fígado, a qual será desprendida de junto dos rins.

[[v3-3-5]]

^<<v3-3-5,5>>^ Os filhos de Aarão queimarão isso no altar, por cima do holocausto colocado sobre a lenha que está no fogo. Esse é um sacrifício consumido pelo fogo, de agradável odor ao Senhor.

[[v3-3-6]]

^<<v3-3-6,6>>^ Se oferecer do gado menor ao Senhor, como sacrifício pacífico, macho ou fêmea, oferecerá um que seja sem defeito.

[[v3-3-7]]

^<<v3-3-7,7>>^ Se oferecer um cordeiro, o apresentará diante do Senhor,

[[v3-3-8]]

^<<v3-3-8,8>>^ porá a mão sobre a cabeça da vítima e a imolará diante da tenda de reunião. Em seguida, os filhos de Aarão derramarão o sangue em volta do altar.

[[v3-3-9]]

^<<v3-3-9,9>>^ Desse sacrifício pacífico oferecerá, à guisa de sacrifício pelo fogo ao Senhor, a gordura, a cauda inteira cortada rente à espinha, a gordura que envolve as entranhas e que se acha aderida a elas,

[[v3-3-10]]

^<<v3-3-10,10>>^ os dois rins com a gordura que os envolve na região lombar e a pele que recobre o fígado, a qual será desprendida de junto dos rins.

[[v3-3-11]]

^<<v3-3-11,11>>^ O sacerdote queimará isso no altar; esse é o alimento de um sacrifício feito pelo fogo ao Senhor.

[[v3-3-12]]

^<<v3-3-12,12>>^ Se a oferta for uma cabra, ele a apresentará diante do Senhor,

[[v3-3-13]]

^<<v3-3-13,13>>^ porá a mão sobre sua cabeça e a imolará diante da tenda de reunião; e os filhos de Aarão derramarão o sangue em torno do altar.

[[v3-3-14]]

^<<v3-3-14,14>>^ Dessa oferta oferecerá, à guisa de sacrifício feito pelo fogo ao Senhor, a gordura que envolve as entranhas e que se acha aderida a elas,

[[v3-3-15]]

^<<v3-3-15,15>>^ os dois rins com a gordura que os recobre na região lombar, e a pele que recobre o fígado, a qual será desprendida de junto dos rins.

[[v3-3-16]]

^<<v3-3-16,16>>^ O sacerdote os queimará sobre o altar; esse é o alimento de um sacrifício oferecido pelo fogo, de agradável odor. Toda a gordura pertence ao Senhor.

[[v3-3-17]]

^<<v3-3-17,17>>^ Essa é uma lei perpétua para vossos descendentes, onde quer que habiteis: Não comereis gordura nem sangue.”

'''

xref:003-levitico/003-levitico-002.adoc#v3-2-0[&#60; Capítulo Anterior] | <<v3-3-0,Topo>> | xref:003-levitico/003-levitico-004.adoc#v3-4-0[Próximo Capítulo &#62;]