include::./index.adoc[]

[[v3-15-0]]
=== Levítico, 15
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Levítico 15 apresenta leis sobre impurezas causadas por fluxos corporais, tanto masculinos quanto femininos. O capítulo trata de como as pessoas que sofrem com esses fluxos devem se purificar para poderem se aproximar de Deus novamente. Abaixo estão cinco versículos relacionados com os temas abordados em Levítico 15:
* Levítico 15:31: "Assim, vocês manterão os israelitas separados daquilo que os contamina e não morrerão por causa de sua impureza, contaminando o meu santuário que está no meio deles." Este versículo mostra que a purificação é necessária para que as pessoas possam se aproximar de Deus e permanecer em um estado de pureza.
* Mateus 9:20-22: "De repente, uma mulher que havia sangrado durante doze anos, chegou por trás dele e tocou na borda do manto de Jesus, pois pensava consigo mesma: 'Se eu tão somente tocar em seu manto, ficarei curada.' Jesus voltou-se e, ao vê-la, disse: 'Coragem, filha! Sua fé a curou.' E a mulher ficou curada naquele mesmo instante." Esse versículo apresenta uma história de cura, onde a mulher que sofria de fluxo de sangue é curada pela fé em Jesus.
* Marcos 5:25-29: "Ora, uma mulher que havia sofrido de hemorragia por doze anos e tinha suportado muito com muitos médicos e gastado tudo o que tinha, mas em vez de melhorar, piorava, tendo ouvido falar de Jesus, veio por trás, entre a multidão, e tocou em sua capa. Pois pensava: 'Se eu tão somente tocar em suas roupas, ficarei curada.' No mesmo instante cessou sua hemorragia, e ela sentiu em seu corpo que estava curada da doença." Esse versículo apresenta uma história semelhante ao anterior, onde outra mulher é curada de seu fluxo de sangue através da fé em Jesus.
* Hebreus 9:14: "Quanto mais o sangue de Cristo, que pelo Espírito eterno se ofereceu de forma imaculada a Deus, purificará a nossa consciência de atos que levam à morte, para que sirvamos ao Deus vivo!" Esse versículo destaca a purificação feita pelo sacrifício de Cristo, que é superior à purificação feita pelos rituais descritos em Levítico.
* 1 João 1:7: "Mas, se andarmos na luz, como ele está na luz, temos comunhão uns com os outros, e o sangue de Jesus, seu Filho, nos purifica de todo pecado." Esse versículo destaca a purificação que vem através do sangue de Jesus, que é capaz de purificar de todo pecado, incluindo impurezas causadas por fluxos corporais.
****

[[v3-15-1]]

^<<v3-15-1,1>>^ O Senhor disse a Moisés e a Aarão:

[[v3-15-2]]

^<<v3-15-2,2>>^ “Dizei aos israelitas o seguinte:

[[v3-15-3]]

^<<v3-15-3,3>>^ Todo homem que tem gonorreia será por isso mesmo impuro. A impureza está no fluxo; quer sua carne deixe correr o fluxo, ou o retenha, há impureza.

[[v3-15-4]]

^<<v3-15-4,4>>^ Qualquer cama em que se deitar aquele que tem gonorreia, bem como qualquer cadeira em que ele se sentar será impura.

[[v3-15-5]]

^<<v3-15-5,5>>^ Quem tocar sua cama deverá lavar suas vestes, tomar banho em água, e ficará impuro até a tarde.

[[v3-15-6]]

^<<v3-15-6,6>>^ Quem sentar sobre a cadeira onde esteve um homem atacado de gonorreia deverá lavar suas vestes, tomar banho e ficará impuro até a tarde.

[[v3-15-7]]

^<<v3-15-7,7>>^ Aquele que tocar o corpo desse homem deverá lavar suas vestes, tomar banho em água e ficará impuro até a tarde.

[[v3-15-8]]

^<<v3-15-8,8>>^ Se um homem que tiver gonorreia cuspir sobre um homem puro, este deverá lavar suas vestes, tomar banho em água, e ficará impuro até a tarde.

[[v3-15-9]]

^<<v3-15-9,9>>^ Qualquer sela que tiver montado aquele que tem gonorreia será impura.

[[v3-15-10]]

^<<v3-15-10,10>>^ Todo aquele que tocar em alguma coisa que tenha estado debaixo dele, ficará impuro até a tarde; quem transportar alguma dessas coisas lavará suas vestes, se banhará em água, e ficará impuro até a tarde.

[[v3-15-11]]

^<<v3-15-11,11>>^ Aquele que for tocado pelo homem que tiver gonorreia, antes de ter este lavado as mãos em água, deverá lavar suas vestes, tomar banho, e ficará impuro até a tarde.

[[v3-15-12]]

^<<v3-15-12,12>>^ Todo recipiente de terra tocado por esse homem será quebrado, e todo vaso de madeira será lavado com água.

[[v3-15-13]]

^<<v3-15-13,13>>^ Quando se tiver purificado aquele que tem gonorreia, contará sete dias para sua purificação; lavará suas vestes, se banhará em água corrente e será puro.

[[v3-15-14]]

^<<v3-15-14,14>>^ No oitavo dia, tomará duas rolas ou dois pombinhos e se apresentará diante do Senhor à entrada da tenda de reunião e entregará ao sacerdote,

[[v3-15-15]]

^<<v3-15-15,15>>^ que os oferecerá, um em sacrifício pelo pecado e outro em holocausto, e fará a expiação ao Senhor em seu favor, por causa de seu fluxo.

[[v3-15-16]]

^<<v3-15-16,16>>^ O homem que tiver um derramamento seminal lavará em água todo o seu corpo, mas ficará impuro até a tarde.

[[v3-15-17]]

^<<v3-15-17,17>>^ Toda veste e toda pele sobre as quais cair o sêmen serão lavadas com água, e ficarão impuras até a tarde.

[[v3-15-18]]

^<<v3-15-18,18>>^ Se uma mulher dormiu com esse homem, ela se lavará na mesma água que ele e ficarão impuros até a tarde”.

[[v3-15-19]]

^<<v3-15-19,19>>^ “Quando uma mulher tiver seu fluxo de sangue, ficará impura durante sete dias: qualquer um que a tocar será impuro até a tarde.

[[v3-15-20]]

^<<v3-15-20,20>>^ Todo móvel que ela se deitar durante sua impureza será impuro, e igualmente aquele em que ela sentar.

[[v3-15-21]]

^<<v3-15-21,21>>^ Quem tocar sua cama deverá lavar suas vestes, tomar banho, e ficará impuro até a tarde.

[[v3-15-22]]

^<<v3-15-22,22>>^ Aquele que tocar em um móvel onde ela se tiver sentado deverá lavar suas vestes, tomar banho, e ficará impuro até a tarde.

[[v3-15-23]]

^<<v3-15-23,23>>^ Aquele que tocar em um objeto encontrado na sua cama ou no móvel onde ela sentou será impuro até a tarde.

[[v3-15-24]]

^<<v3-15-24,24>>^ Se alguém dormir com ela, e for tocado por sua impureza, será impuro durante sete dias, e toda cama na qual se deitar será impura.

[[v3-15-25]]

^<<v3-15-25,25>>^ Quando uma mulher tiver um fluxo de sangue durante vários dias, fora do tempo normal, ou se o fluxo se prolongar além do tempo de sua impureza, ela será impura durante todo o tempo desse fluxo, como se estivesse no tempo de sua impureza.

[[v3-15-26]]

^<<v3-15-26,26>>^ A cama na qual dormir enquanto durar a hemorragia e o móvel em que sentar ficarão impuros, como no tempo do fluxo.

[[v3-15-27]]

^<<v3-15-27,27>>^ Qualquer um que os tocar será impuro; deverá lavar suas vestes, tomar banho, e ficará impuro até a tarde.

[[v3-15-28]]

^<<v3-15-28,28>>^ Quando ela estiver curada de seu fluxo, contará sete dias, e depois será pura.

[[v3-15-29]]

^<<v3-15-29,29>>^ No oitavo dia, tomará duas rolas ou dois pombinhos e os trará ao sacerdote à entrada da tenda de reunião.

[[v3-15-30]]

^<<v3-15-30,30>>^ O sacerdote oferecerá um deles em sacrifício pelo pecado, o outro em holocausto, e fará em seu favor a expiação diante do Senhor, por causa do fluxo de sua impureza.

[[v3-15-31]]

^<<v3-15-31,31>>^ É assim que ajudareis os israelitas a se purificarem de suas imundícies, para que não morram por ter contaminado o meu tabernáculo que está no meio deles.”

[[v3-15-32]]

^<<v3-15-32,32>>^ Essa é a lei relativa ao homem que tem gonorreia ou que é manchado por um fluxo seminal,

[[v3-15-33]]

^<<v3-15-33,33>>^ e relativa à mulher no tempo de sua menstruação, ou toda pessoa, seja homem ou mulher, atingida por um fluxo, e relativa ao homem que dormir com uma mulher impura.

'''

xref:003-levitico/003-levitico-014.adoc#v3-14-0[&#60; Capítulo Anterior] | <<v3-15-0,Topo>> | xref:003-levitico/003-levitico-016.adoc#v3-16-0[Próximo Capítulo &#62;]