include::./index.adoc[]

[[v39-2-0]]
=== Jonas, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jonas 2 conta a história de como Jonas, depois de ser engolido por um grande peixe, clama a Deus por misericórdia e é salvo. Abaixo estão cinco versículos relacionados aos temas abordados neste capítulo:
* Salmos 18:6: "Na minha angústia invoquei o Senhor, gritei por socorro ao meu Deus. Do seu templo ele ouviu a minha voz; meu grito chegou à sua presença, aos seus ouvidos." Assim como Jonas clamou a Deus em sua angústia, o salmista também invoca a ajuda divina em seu sofrimento.
* Salmos 69:1-2: "Salva-me, ó Deus, pois as águas já me chegaram ao pescoço. Estou afundando num lamaçal profundo, e não há onde firmar os pés; entrei em águas profundas, e a correnteza me arrasta." Este salmo é um exemplo de um pedido de ajuda em meio a uma situação difícil, assim como a oração de Jonas enquanto estava dentro do peixe.
* Salmos 116:1-2: "Amo o Senhor, porque ele ouve a minha voz e as minhas súplicas. Porque ele inclina os seus ouvidos para mim, invocarei o seu nome enquanto viver." Este salmo é uma expressão de gratidão a Deus por ouvir e responder às orações, um tema que é central em Jonas 2.
* Isaías 38:10-13: "Eu disse: Na metade da minha vida, tenho que ir à porta da morte. Privado do resto dos meus anos, estou condenado a viver no mundo dos mortos. Eu disse: Não tornarei a ver o Senhor Deus no mundo dos vivos, jamais verei um ser humano na terra dos viventes." O profeta Isaías, como Jonas, clamou a Deus em um momento de grande aflição, pedindo que ele o salvasse da morte.
* 2 Coríntios 1:8-10: "Irmãos, não queremos que ignorem as tribulações que tivemos na província da Ásia, pois fomos esmagados acima das nossas forças, a ponto de perdermos a esperança de sair com vida. Sentimos em nós mesmos a sentença de morte, para que aprendêssemos a não confiar em nós mesmos, mas em Deus, que ressuscita os mortos. Ele nos salvou de uma morte tão terrível, e nos salvará de novo. Temos nele a nossa esperança de que continuará a livrar-nos," Paulo, assim como Jonas, experimentou uma situação de desespero e recorreu a Deus em busca de ajuda e salvação.
****

[[v39-2-1]]

^<<v39-2-1,1>>^ O Senhor fez que ali se encontrasse um grande peixe para engolir Jonas, e este esteve três dias e três noites no ventre do peixe.^&#42;1^

[[v39-2-2]]

^<<v39-2-2,2>>^ Do fundo das entranhas do peixe, Jonas fez esta prece ao Senhor, seu Deus:

[[v39-2-3]]

^<<v39-2-3,3>>^ Em minha aflição, invoquei o Senhor, e ele ouviu-me. Do meio da morada dos mortos, clamei a vós, e ouvistes minha voz.

[[v39-2-4]]

^<<v39-2-4,4>>^ Lançastes-me no abismo, no meio das águas e as ondas me envolviam. Todas as vossas vagas e todas as vossas ondas passavam sobre mim.

[[v39-2-5]]

^<<v39-2-5,5>>^ E eu já dizia: fui rejeitado de diante de vossos olhos. Acaso me será dado ainda rever vosso santo templo?!

[[v39-2-6]]

^<<v39-2-6,6>>^ As águas envolviam-me até a garganta, o abismo me cercava. As algas envolviam-me a cabeça.

[[v39-2-7]]

^<<v39-2-7,7>>^ Eu tinha descido até as raízes das montanhas, até a terra cujos ferrolhos eternos se fecharam sobre mim.

[[v39-2-8]]

^<<v39-2-8,8>>^ Quando desfalecia a minha vida, pensei no Senhor; minha oração chegou a vós, no vosso santo templo.

[[v39-2-9]]

^<<v39-2-9,9>>^ Os que servem a ídolos vãos abandonam a fonte das graças.

[[v39-2-10]]

^<<v39-2-10,10>>^ Eu, porém, oferecerei um sacrifício com cânticos de louvor, e cumprirei o voto que fiz. Do Senhor vem a salvação.

[[v39-2-11]]

^<<v39-2-11,11>>^ Então, o Senhor ordenou ao peixe, e este vomitou Jonas na praia.

'''

xref:039-jonas/039-jonas-001.adoc#v39-1-0[&#60; Capítulo Anterior] | <<v39-2-0,Topo>> | xref:039-jonas/039-jonas-003.adoc#v39-3-0[Próximo Capítulo &#62;]