include::./index.adoc[]

[[v39-1-0]]
=== Jonas, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jonas 1 relata a história do chamado de Deus a Jonas para pregar em Nínive, mas em vez de obedecer, Jonas tenta fugir e acaba sendo lançado ao mar durante uma tempestade. Aqui estão cinco versículos relacionados com os temas abordados em Jonas 1:
* Provérbios 21:30: "Não há sabedoria, nem inteligência, nem conselho contra o Senhor." O capítulo de Jonas 1 ilustra claramente a inutilidade de tentar fugir do chamado de Deus. Jonas achou que poderia escapar da vontade de Deus, mas acabou encontrando-se em apuros. Este versículo de Provérbios reforça que nada pode resistir à vontade de Deus.
* Salmos 139:7-8: "Para onde me ausentarei do teu Espírito? Para onde fugirei da tua face? Se subir ao céu, lá estás; se fizer no Seol a minha cama, eis que tu ali estás também." Este salmo destaca a onipresença de Deus e a impossibilidade de fugir de sua presença. Isso é exatamente o que Jonas tentou fazer, mas descobriu que não era possível.
* Mateus 8:27: "E os homens se maravilharam, dizendo: Que homem é este, que até os ventos e o mar lhe obedecem?" Como Jonas 1 mostra, Deus tem poder sobre as tempestades e os mares. Neste versículo de Mateus, Jesus demonstra o mesmo poder ao acalmar uma tempestade.
* Isaías 45:22: "Olhai para mim, e sereis salvos, vós, todos os termos da terra; porque eu sou Deus, e não há outro." Quando Jonas pediu para ser lançado ao mar para acalmar a tempestade, os marinheiros temeram a Deus e se voltaram para ele em oração. Este versículo de Isaías enfatiza a importância de buscar a salvação em Deus.
* Atos 27:25: "Portanto, ó homens, tende bom ânimo; porque creio em Deus, que há de acontecer assim como me foi dito." Neste capítulo de Atos, Paulo está enfrentando uma tempestade em alto mar e encoraja os outros a confiar em Deus. Assim como Jonas, os marinheiros em Atos aprendem a confiar em Deus durante uma tempestade no mar.
****

[[v39-1-1]]

^<<v39-1-1,1>>^ A palavra do Senhor foi dirigida a Jonas, filho de Amati, nestes termos:

[[v39-1-2]]

^<<v39-1-2,2>>^ “Levanta-te, vai a Nínive, a grande cidade, e profere contra ela os teus oráculos, porque sua iniquidade chegou até a minha presença”.

[[v39-1-3]]

^<<v39-1-3,3>>^ Jonas pôs-se a caminho, mas na direção de Társis, para fugir do Senhor. Desceu a Jope, onde encontrou um navio que partia para Társis; pagou a passagem e embarcou nele para ir com os demais passageiros para Társis, longe da face do Senhor.

[[v39-1-4]]

^<<v39-1-4,4>>^ O Senhor, porém, fez vir sobre o mar um vento impetuoso e levantou no mar uma tempestade tão grande que a embarcação ameaçava espedaçar-se.

[[v39-1-5]]

^<<v39-1-5,5>>^ Aterrorizados, os marinheiros puseram-se a invocar cada qual o seu deus, e atiraram no mar a carga do navio para aliviarem-no. Entretanto, Jonas tinha descido ao porão do navio e, deitando-se ali, dormia profundamente.

[[v39-1-6]]

^<<v39-1-6,6>>^ Veio o capitão e o despertou: “Dorminhoco! Que estás fazendo aqui? Levanta-te e invoca o teu Deus, para ver se ele se lembra talvez de nós e nos livre da morte”.

[[v39-1-7]]

^<<v39-1-7,7>>^ Em seguida, disseram os marinheiros entre si: “Vinde e tiremos à sorte para sabermos quem é a causa deste mal”. Lançaram a sorte e esta caiu sobre Jonas.

[[v39-1-8]]

^<<v39-1-8,8>>^ E perguntaram-lhe: “Tu, por quem nos acontecem estes males, dize-nos qual é a tua profissão? De onde vens? A que país e a que raça pertences?”. –

[[v39-1-9]]

^<<v39-1-9,9>>^ “Sou hebreu”, respondeu ele –. “Adoro o Senhor, Deus dos céus, que criou o mar e todos os continentes.”

[[v39-1-10]]

^<<v39-1-10,10>>^ Ficaram, então, aqueles homens possuídos de grande temor, e disseram-lhe: “Por que fizeste isto?”. Pois tinham compreendido, pela própria declaração de Jonas, que este fugia para escapar à ordem do Senhor.^&#42;1^

[[v39-1-11]]

^<<v39-1-11,11>>^ E disseram-lhe: “Que te havemos de fazer para que o mar se acalme em torno de nós?”. Porque o mar tornava-se cada vez mais ameaçador.

[[v39-1-12]]

^<<v39-1-12,12>>^ Tomai-me, disse Jonas, e lançai-me às águas, e o mar se acalmará. Reconheço que sou eu a causa desta terrível tempestade que vos sobreveio.

[[v39-1-13]]

^<<v39-1-13,13>>^ Os homens remavam para ver se conseguiam ganhar a costa, mas em vão, porque o mar se embravecia cada vez mais contra eles.

[[v39-1-14]]

^<<v39-1-14,14>>^ Então invocaram o Senhor: “Senhor” – disseram eles –, “não nos façais perecer por causa da vida deste homem, nem nos torneis responsáveis pela vida deste homem que não nos fez mal algum. Vós, ó Senhor, fizestes como foi do vosso agrado”.^&#42;1^

[[v39-1-15]]

^<<v39-1-15,15>>^ E, pegando em Jonas, lançaram-no às ondas, e a fúria do mar se acalmou.

[[v39-1-16]]

^<<v39-1-16,16>>^ Tomada de profundo sentimento de temor para com o Senhor, a tripulação ofereceu-lhe um sacrifício, acompanhado de votos.

'''

xref:038-abdias/038-abdias-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v39-1-0,Topo>> | xref:039-jonas/039-jonas-002.adoc#v39-2-0[Próximo Capítulo &#62;]