include::./index.adoc[]

[[v13-25-0]]
=== I Crônicas, 25
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Crônicas 25 trata da organização dos músicos levitas para o serviço no Templo, incluindo a nomeação dos líderes e a divisão dos grupos musicais. Os versículos selecionados abaixo estão relacionados com a música, adoração e culto ao Senhor.
* 1 Crônicas 16:4: "E pôs perante a arca do Senhor alguns dos levitas por ministros, para lembrarem, e para celebrarem, e para louvarem ao Senhor Deus de Israel" Este versículo destaca a importância dos levitas como ministros na adoração e celebração do Senhor, o que está relacionado com o papel dos músicos levitas em 1 Crônicas 25.
* Salmo 33:3: "Cantai-lhe um cântico novo; tocai bem e com júbilo." Este salmo incentiva a criação de novos cânticos para louvar ao Senhor, o que pode ter sido uma prática comum entre os músicos levitas de 1 Crônicas 25.
* Salmo 150:3-5: "Louvai-o com o som de trombeta; louvai-o com o saltério e a harpa. Louvai-o com o adufe e a flauta; louvai-o com instrumentos de cordas e com órgãos. Louvai-o com os címbalos sonoros; louvai-o com címbalos altissonantes." Este salmo lista uma variedade de instrumentos musicais que podem ter sido utilizados pelos músicos levitas em suas apresentações no Templo.
* 1 Crônicas 16:42: "Com eles estavam Hemã e Jedutum, com trombetas e címbalos, para os que haviam de tocar e com outros instrumentos de música de Deus." Este versículo destaca a presença de instrumentos de música de Deus no culto ao Senhor, o que pode ter incluído os instrumentos utilizados pelos músicos levitas.
* 2 Crônicas 5:12-13: "E também os levitas, que eram cantores, todos eles, de Asafe, de Hemã, de Jedutum, e de seus filhos e seus irmãos, vestidos de linho fino, com címbalos, e com saltérios, e com harpas, estavam em pé ao oriente do altar; e com eles cento e vinte sacerdotes, que tocavam trombetas." Este versículo descreve a apresentação dos músicos levitas durante a dedicação do Templo de Salomão, que pode ter seguido um modelo semelhante ao dos músicos levitas de 1 Crônicas 25.
****

[[v13-25-1]]

^<<v13-25-1,1>>^ Davi e os chefes do exército apartaram para o serviço os filhos de Asaf, de Emã e de Iditun, que profetizavam ao som da harpa, da cítara e dos címbalos. Eis a lista dos homens encarregados desse serviço:

[[v13-25-2]]

^<<v13-25-2,2>>^ dos filhos de Asaf: Zacur, José, Natania; e Asarelas; filhos de Asaf, sob a direção de Asaf, que profetizava segundo as ordens do rei.

[[v13-25-3]]

^<<v13-25-3,3>>^ De Iditun: os filhos de Iditun: Godolias, Sari, Jesaías, Hasabias, Matatias e Semei, ao todo seis, sob as ordens de seu pai Iditun, que profetizava com a cítara para cantar e louvar ao Senhor.

[[v13-25-4]]

^<<v13-25-4,4>>^ De Emã: os filhos de Emã: Bocias, Matanias, Oziel, Subael, Jerimot, Hananias, Hanani, Eliata, Gedelti, Romenti-Ezer, Jesbacasa, Meiloti, Otir e Maaziot;

[[v13-25-5]]

^<<v13-25-5,5>>^ eram todos filhos de Emã, que era vidente do rei, para revelar as palavras de Deus e exaltar seu poder: Deus tinha dado a Emã catorze filhos e três filhas.

[[v13-25-6]]

^<<v13-25-6,6>>^ Eis, portanto, os que, sob a direção de seus pais, estavam encarregados do canto no templo. Tinham címbalos, cítaras e harpas para o serviço do templo, sob as ordens de Davi, de Asaf, de Iditun e de Emã.

[[v13-25-7]]

^<<v13-25-7,7>>^ O número deles, juntamente com seus irmãos exercitados em cantar ao Senhor, todos hábeis em sua arte, atingia o número de duzentos e oitenta e oito.

[[v13-25-8]]

^<<v13-25-8,8>>^ Tiraram, pela sorte, a ordem de serviço, pequenos e grandes, mestres e discípulos.

[[v13-25-9]]

^<<v13-25-9,9>>^ A primeira sorte recaiu para Asaf, a José; a segunda a Godolias, com seus irmãos e filhos: doze;

[[v13-25-10]]

^<<v13-25-10,10>>^ a terceira a Zacur, com seus filhos e irmãos: doze;

[[v13-25-11]]

^<<v13-25-11,11>>^ a quarta a Isari, com seus filhos e irmãos: doze;

[[v13-25-12]]

^<<v13-25-12,12>>^ a quinta a Natanias, com seus filhos e seus irmãos: doze;

[[v13-25-13]]

^<<v13-25-13,13>>^ a sexta a Bocias, com seus filhos e irmãos: doze;

[[v13-25-14]]

^<<v13-25-14,14>>^ a sétima, a Isreela, com seus filhos e irmãos: doze;

[[v13-25-15]]

^<<v13-25-15,15>>^ a oitava a Jesaías com seus filhos e irmãos: doze;

[[v13-25-16]]

^<<v13-25-16,16>>^ a nona a Matanias, com seus filhos e irmãos: doze;

[[v13-25-17]]

^<<v13-25-17,17>>^ a décima a Semei, com seus filhos e irmãos: doze;

[[v13-25-18]]

^<<v13-25-18,18>>^ a décima primeira a Azareel, com seus filhos e irmãos: doze;

[[v13-25-19]]

^<<v13-25-19,19>>^ a décima segunda a Hasabias, com seus filhos e irmãos: doze;

[[v13-25-20]]

^<<v13-25-20,20>>^ a décima terceira a Subael, com seus filhos e irmãos: doze;

[[v13-25-21]]

^<<v13-25-21,21>>^ a décima quarta a Matatias, com seus filhos e irmãos: doze;

[[v13-25-22]]

^<<v13-25-22,22>>^ a décima quinta a Jerimot, com seus filhos e irmãos: doze;

[[v13-25-23]]

^<<v13-25-23,23>>^ a décima sexta a Hananias, com seus filhos e irmãos: doze;

[[v13-25-24]]

^<<v13-25-24,24>>^ a décima sétima a Jesbacasa, com seus filhos e irmãos: doze;

[[v13-25-25]]

^<<v13-25-25,25>>^ a décima oitava a Hanani com seus filhos e seus irmãos: doze;

[[v13-25-26]]

^<<v13-25-26,26>>^ a décima nona a Meiloti, com seus filhos e irmãos: doze;

[[v13-25-27]]

^<<v13-25-27,27>>^ a vigésima a Eliata, com seus filhos e irmãos: doze;

[[v13-25-28]]

^<<v13-25-28,28>>^ a vigésima primeira a Otir, com seus filhos e irmãos: doze;

[[v13-25-29]]

^<<v13-25-29,29>>^ a vigésima segunda a Gedelti, com seus filhos e irmãos: doze;

[[v13-25-30]]

^<<v13-25-30,30>>^ a vigésima terceira a Maaziot, com seus filhos e irmãos: doze;

[[v13-25-31]]

^<<v13-25-31,31>>^ a vigésima quarta a Romenti-Ezer, com seus filhos e irmãos: doze.

'''

xref:013-i-cronicas/013-i-cronicas-024.adoc#v13-24-0[&#60; Capítulo Anterior] | <<v13-25-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-026.adoc#v13-26-0[Próximo Capítulo &#62;]