include::./index.adoc[]

[[v13-6-0]]
=== I Crônicas, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 6 de 1 Crônicas apresenta a genealogia dos levitas, incluindo os descendentes de Arão, o primeiro sumo sacerdote. São mencionados os nomes dos chefes das famílias levíticas e a distribuição das cidades de refúgio. A seguir, são apresentados cinco versículos relacionados com os temas abordados em 1 Crônicas 6:
* Êxodo 6:16-20: "Estes são os nomes dos filhos de Levi, segundo as suas gerações: Gérson, Coate e Merari. E os anos da vida de Levi foram cento e trinta e sete anos. Os filhos de Gérson: Libni e Simei, segundo as suas famílias. E os filhos de Coate: Anrão, Izar, Hebrom e Uziel. E os anos da vida de Coate foram cento e trinta e três anos." Este versículo apresenta a origem da tribo de Levi e os nomes dos seus filhos, incluindo Anrão, o pai de Moisés e Arão.
* Números 35:6: "E das cidades que dareis aos levitas, seis cidades de refúgio, que fareis estabelecê-las, para que nelas se acolha o homicida; e além delas dareis quarenta e duas cidades." Este versículo faz referência à distribuição das cidades de refúgio, que é mencionada em 1 Crônicas 6.
* Josué 21:4: "Os filhos de Arão, dos coatitas, dentre os filhos de Levi, porque a sorte caiu sobre eles primeiro." Este versículo destaca a posição privilegiada dos descendentes de Arão entre os levitas, pois eles foram escolhidos para serem os sacerdotes do povo de Israel.
* 1 Crônicas 6:48: "E seus irmãos levitas foram postos sobre toda a obra do tabernáculo da casa de Deus." Este versículo mostra que os levitas eram responsáveis por cuidar do tabernáculo e de todas as suas atividades litúrgicas.
* 1 Crônicas 6:62: "E aos filhos de Gérson, segundo as suas famílias, deram da tribo de Issacar, e da tribo de Aser, e da tribo de Naftali, e da metade da tribo de Manassés em Basã, treze cidades." Este versículo destaca a distribuição territorial das cidades dos levitas, incluindo as cidades atribuídas aos filhos de Gérson.
****

[[v13-6-1]]

^<<v13-6-1,1>>^ Filhos de Levi: Gérson, Caat e Merari.

[[v13-6-2]]

^<<v13-6-2,2>>^ Filhos de Caat: Amram, Isaar, Hebron e Oziel.

[[v13-6-3]]

^<<v13-6-3,3>>^ Filhos de Amram: Aarão, Moisés e Maria. Filhos de Aaram: Nadab, Abiú, Eleazar e Itamar.

[[v13-6-4]]

^<<v13-6-4,4>>^ Eleazar gerou Fineias e Fineias gerou Abisue,

[[v13-6-5]]

^<<v13-6-5,5>>^ Abisue gerou Boci, e Boci gerou Ozi.

[[v13-6-6]]

^<<v13-6-6,6>>^ Ozi gerou Zaraías e Zaraías gerou Meraiot.

[[v13-6-7]]

^<<v13-6-7,7>>^ Meraiot gerou Amarias, e Amarias gerou Aquitob.

[[v13-6-8]]

^<<v13-6-8,8>>^ Aquitob gerou Sadoc, e Sadoc gerou Aquimaás.

[[v13-6-9]]

^<<v13-6-9,9>>^ Aquimaás gerou Azarias, e Azarias gerou Joanã.

[[v13-6-10]]

^<<v13-6-10,10>>^ Joanã gerou Azarias, que exerceu o sacerdócio no templo que Salomão construiu em Jerusalém.

[[v13-6-11]]

^<<v13-6-11,11>>^ Azarias gerou Amarias e Amarias gerou Aquitob.

[[v13-6-12]]

^<<v13-6-12,12>>^ Aquitob gerou Sadoc, e Sadoc gerou Selum.

[[v13-6-13]]

^<<v13-6-13,13>>^ Selum gerou Helcias, Helcias gerou Azarias.

[[v13-6-14]]

^<<v13-6-14,14>>^ Azarias gerou Saraías, e Saraías gerou Josedec.

[[v13-6-15]]

^<<v13-6-15,15>>^ Josedec partiu para o exílio, quando o Senhor fez com que Judá e Jerusalém fossem levados ao cativeiro por Nabucodonosor.

[[v13-6-16]]

^<<v13-6-16,16>>^ Filhos de Levi: Gérson, Caat e Merari.

[[v13-6-17]]

^<<v13-6-17,17>>^ Eis os nomes dos filhos de Gérson: Lobni e Semei.

[[v13-6-18]]

^<<v13-6-18,18>>^ Filhos de Caat: Amram, Isaar, Hebron e Oziel.

[[v13-6-19]]

^<<v13-6-19,19>>^ Filhos de Merari: Mooli e Musi. Eis as famílias de Levi, segundo suas casas patriarcais.

[[v13-6-20]]

^<<v13-6-20,20>>^ De Gérson: Lobni, seu filho, Jaat, seu filho, Zama, seu filho,

[[v13-6-21]]

^<<v13-6-21,21>>^ Joa, seu filho, Ado, seu filho, Zara, seu filho, Jetrai, seu filho.

[[v13-6-22]]

^<<v13-6-22,22>>^ Filhos de Caat: Abinadab, seu filho, Coré, seu filho, Asir, seu filho,

[[v13-6-23]]

^<<v13-6-23,23>>^ Elcana, seu filho, Abiasaf, seu filho, Asir, seu filho,

[[v13-6-24]]

^<<v13-6-24,24>>^ Taat, seu filho, Uriel, seu filho, Ozias, seu filho, Saul, seu filho.

[[v13-6-25]]

^<<v13-6-25,25>>^ Filhos de Elcana: Amasai e Aquimot,

[[v13-6-26]]

^<<v13-6-26,26>>^ Elcana, seu filho, Sofai, seu filho, Naat, seu filho,

[[v13-6-27]]

^<<v13-6-27,27>>^ Eliab, seu filho, Jeroam, seu filho, Elcana, seu filho.

[[v13-6-28]]

^<<v13-6-28,28>>^ Os filhos de Samuel: o primogênito Joel e Abias.

[[v13-6-29]]

^<<v13-6-29,29>>^ Filhos de Merari: Mooli, Lobni, seu filho, Semei, seu filho, Oza, seu filho, Samaá,

[[v13-6-30]]

^<<v13-6-30,30>>^ seu filho, Hagias, seu filho, Asaías, seu filho.

[[v13-6-31]]

^<<v13-6-31,31>>^ Para dirigir o canto na casa do Senhor, depois que a arca foi colocada em lugar de repouso, eis os que Davi escolheu.

[[v13-6-32]]

^<<v13-6-32,32>>^ Eles cumpriram suas funções de cantores diante do tabernáculo da tenda de reunião até que Salomão construiu o Templo do Senhor em Jerusalém. Faziam seu serviço segundo o seu regulamento.

[[v13-6-33]]

^<<v13-6-33,33>>^ Eis os que cumpriam esse ofício juntamente com seus filhos: Dentre os filhos de Caat: Hemã, o cantor, filho de Joel, filho de Samuel,

[[v13-6-34]]

^<<v13-6-34,34>>^ filho de Elcana, filho de Jeroam, filho de Eliel, filho de Toú,

[[v13-6-35]]

^<<v13-6-35,35>>^ filho de Suf, filho de Elcana, filho de Maat, filho de Amasai,

[[v13-6-36]]

^<<v13-6-36,36>>^ filho de Elcana, filho de Joel, filho de Azarias, filho de Sofonias,

[[v13-6-37]]

^<<v13-6-37,37>>^ filho de Taat, filho de Asir, filho de Abiasaf, filho de Coré,

[[v13-6-38]]

^<<v13-6-38,38>>^ filho de Isaar, filho de Caat, filho de Levi, filho de Israel.

[[v13-6-39]]

^<<v13-6-39,39>>^ À direita estava seu irmão Osaf, filho de Baraquias, filho de Samaé,

[[v13-6-40]]

^<<v13-6-40,40>>^ filho de Miguel, filho de Basaías, filho de Melquias,

[[v13-6-41]]

^<<v13-6-41,41>>^ filho de Atanai, filho de Zara, filho de Adaías,

[[v13-6-42]]

^<<v13-6-42,42>>^ filho de Etã, filho de Zama, filho de Semei,

[[v13-6-43]]

^<<v13-6-43,43>>^ filho de Jet, filho de Gérson, filho de Levi.

[[v13-6-44]]

^<<v13-6-44,44>>^ À sua esquerda, estavam seus irmãos, os meraritas: Etã, filho de Cusi, filho de Abdi, filho de Maloc,

[[v13-6-45]]

^<<v13-6-45,45>>^ filho de Hasabias, filho de Amasias, filho de Helcias,

[[v13-6-46]]

^<<v13-6-46,46>>^ filho de Amasai, filho de Boni, filho de Somer,

[[v13-6-47]]

^<<v13-6-47,47>>^ filho de Mooli, filho de Musi, filho de Merari, filho de Levi.

[[v13-6-48]]

^<<v13-6-48,48>>^ Seus irmãos levitas estavam encarregados de todo o serviço do Tabernáculo da casa do Senhor.

[[v13-6-49]]

^<<v13-6-49,49>>^ Aarão e seus filhos queimavam as oblações no altar dos holocaustos e no altar dos perfumes. Eles tomavam sobre si todo o serviço do Santo dos Santos e faziam a expiação por Israel, segundo as prescrições de Moisés, servo de Deus.

[[v13-6-50]]

^<<v13-6-50,50>>^ Eis os filhos de Aarão: Eleazar, seu filho, Fineias, seu filho, Abisue, seu filho,

[[v13-6-51]]

^<<v13-6-51,51>>^ Boci, seu filho, Ozi, seu filho, Zaraías, seu filho,

[[v13-6-52]]

^<<v13-6-52,52>>^ Meraiot, seu filho, Amarias, seu filho, Aquitob, seu filho,

[[v13-6-53]]

^<<v13-6-53,53>>^ Sadoc, seu filho, Aquimaás, seu filho.

[[v13-6-54]]

^<<v13-6-54,54>>^ Eles se estabeleceram nos territórios das seguintes cidades. Aos filhos de Aarão, da família dos caatitas,

[[v13-6-55]]

^<<v13-6-55,55>>^ que por primeiro a sorte designou, foi dada Hebron e suas redondezas, na terra de Judá.

[[v13-6-56]]

^<<v13-6-56,56>>^ Mas foi dado a Caleb, filho de Jefoné, o território da cidade e suas aldeias.

[[v13-6-57]]

^<<v13-6-57,57>>^ Foi, portanto, dada aos filhos de Aarão, a cidade de refúgio, Hebron, Lebna e seus arredores, Jéter, Estemo e seus arredores,

[[v13-6-58]]

^<<v13-6-58,58>>^ Helon e seus arredores, Dabir e seus arredores,

[[v13-6-59]]

^<<v13-6-59,59>>^ Asã e seus arredores, Bet-Sames e seus arredores.

[[v13-6-60]]

^<<v13-6-60,60>>^ Da tribo de Benjamim, Gaba e seus arredores, Almat e seus arredores, Anatot e seus arredores. O número total de suas cidades foi de treze, conforme suas famílias.

[[v13-6-61]]

^<<v13-6-61,61>>^ Os outros filhos de Caat receberam, pela sorte, dez cidades das famílias da tribo (de Efraim, de Dã) e da meia tribo de Manassés.

[[v13-6-62]]

^<<v13-6-62,62>>^ Aos filhos de Gérson, segundo suas famílias, foram dadas treze cidades da tribo de Issacar, de Aser, de Neftali e de Manassés, em Basã.

[[v13-6-63]]

^<<v13-6-63,63>>^ Aos filhos de Merari, segundo suas famílias, foram dadas, pela sorte, doze cidades das tribos de Rúben, de Gad e de Zabulon.

[[v13-6-64]]

^<<v13-6-64,64>>^ Os israelitas deram aos levitas essas cidades e suas pastagens.

[[v13-6-65]]

^<<v13-6-65,65>>^ Da tribo de Judá, de Simeão e de Benjamim foram designadas, por meio da sorte, as cidades indicadas pelo nome.

[[v13-6-66]]

^<<v13-6-66,66>>^ Quanto às famílias dos filhos de Caat, as cidades que lhes couberam eram da tribo de Efraim.

[[v13-6-67]]

^<<v13-6-67,67>>^ Foram-lhes dadas as cidades de refúgio, Siquém e suas redondezas, na montanha de Efraim, Gazer e seus arredores,

[[v13-6-68]]

^<<v13-6-68,68>>^ Jecmaam e seus arredores, Bet-Horon e seus arredores,

[[v13-6-69]]

^<<v13-6-69,69>>^ Aialon e seus arredores, Gat-Remon e seus arredores;

[[v13-6-70]]

^<<v13-6-70,70>>^ e, da meia tribo de Manassés, Aner e seus arredores, Balaam e seus arredores. É o que foi dado às famílias dos outros filhos de Caat.

[[v13-6-71]]

^<<v13-6-71,71>>^ Aos filhos de Gérson foram dadas, na meia tribo de Manassés, Golã, em Basã, e seus arredores, Astarot e seus arredores;

[[v13-6-72]]

^<<v13-6-72,72>>^ da tribo de Issacar, Cedes e seus arredores, Daberet e seus arredores,

[[v13-6-73]]

^<<v13-6-73,73>>^ Ramot e seus arredores, Anem e seus arredores;

[[v13-6-74]]

^<<v13-6-74,74>>^ da tribo de Aser, Masal e seus arredores, Abdon e seus arredores,

[[v13-6-75]]

^<<v13-6-75,75>>^ Hucoc e seus arredores, Roob e seus arredores;

[[v13-6-76]]

^<<v13-6-76,76>>^ da tribo de Neftali, Cedes da Galileia e seus arredores, Hamon e seus arredores e Cariatarim e seus arredores.

[[v13-6-77]]

^<<v13-6-77,77>>^ Aos outros filhos de Merari foram dadas, da tribo de Zabulon, Remon e seus arredores, Tabor e seus arredores;

[[v13-6-78]]

^<<v13-6-78,78>>^ do outro lado do Jordão, de Jericó ao oriente, da tribo de Rúben, Bosor no deserto e seus arredores, Jasa e seus arredores,

[[v13-6-79]]

^<<v13-6-79,79>>^ Cedimot e seus arredores, Mefaat e seus arredores;

[[v13-6-80]]

^<<v13-6-80,80>>^ da tribo de Gad, Ramot em Galaad e seus arredores, Maanaim e seus arredores,

[[v13-6-81]]

^<<v13-6-81,81>>^ Hesebon e seus arredores e Jazer e seus arredores.

'''

xref:013-i-cronicas/013-i-cronicas-005.adoc#v13-5-0[&#60; Capítulo Anterior] | <<v13-6-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-007.adoc#v13-7-0[Próximo Capítulo &#62;]