include::./index.adoc[]

[[v13-23-0]]
=== I Crônicas, 23
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Crônicas 23 trata da organização dos levitas e seus deveres no serviço do Templo. O capítulo começa com Davi envelhecendo e se preparando para transferir a responsabilidade do Templo para seu filho Salomão. Ele faz um levantamento dos levitas e suas funções. Aqui estão cinco versículos relacionados aos temas abordados em 1 Crônicas 23:
* Números 3:5-9: "O Senhor falou a Moisés: Faça o levantamento dos filhos de Levi pelas suas famílias e clãs. Conte todos os homens de um mês para cima. Eles serão consagrados a mim como levitas. Tome Arão e seus filhos para ajudá-lo e consagre-os para me servirem como sacerdotes. Dê aos levitas a seguinte responsabilidade: eles serão responsáveis pelo cuidado do tabernáculo...” Esse versículo é importante porque fala sobre o papel dos levitas no serviço do Tabernáculo, e como eles foram escolhidos por Deus para essa função.
* Números 8:6-14: "Separe os levitas dentre os outros israelitas e purifique-os. Assim você fará com eles para purificá-los: Espirre água pura sobre eles. Depois, mande que passem uma navalha sobre todo o corpo deles e lavem suas roupas. Assim eles ficarão purificados. Tome um novilho com sua oferta de cereal feita com flor de farinha misturada com azeite e um segundo novilho para sacrifício pelo pecado...” Este versículo descreve o processo de purificação dos levitas antes de começarem a servir no Tabernáculo.
* 1 Crônicas 23:2: "Ele reuniu todos os líderes de Israel, bem como os sacerdotes e os levitas." Aqui, Davi convoca os líderes de Israel, sacerdotes e levitas para organizá-los para o serviço do Templo.
* 1 Crônicas 23:27-28: "Para os filhos de Merari: dos levitas, seus clãs e famílias, foram sorteados doze grupos, conforme as listas. Para os filhos de Gérson: dos levitas, seus clãs e famílias, foram sorteados treze grupos, conforme as listas." Esses versículos mostram como os levitas foram divididos em grupos para o serviço no Templo.
* 1 Crônicas 23:30: "Deviam apresentar-se todas as manhãs para dar graças e louvar o Senhor, e todas as tardes para fazer o mesmo." Aqui, Davi ordena que os levitas apresentem-se diariamente para louvar e agradecer a Deus. Isso mostra como o serviço no Templo era uma tarefa contínua e diária.
****

[[v13-23-1]]

^<<v13-23-1,1>>^ Davi, achando-se velho e cheio de dias, constituiu Salomão, seu filho, rei de Israel.

[[v13-23-2]]

^<<v13-23-2,2>>^ Reuniu todos os chefes de Israel, os sacerdotes e os levitas.

[[v13-23-3]]

^<<v13-23-3,3>>^ Foram contados os levitas de trinta anos para cima; contados por cabeça e por homem, eram trinta e oito mil homens.

[[v13-23-4]]

^<<v13-23-4,4>>^ Davi disse: “vinte e quatro mil dentre eles serão colocados a serviço do Templo do Senhor, seis mil serão escribas e juízes,

[[v13-23-5]]

^<<v13-23-5,5>>^ quatro mil porteiros e quatro mil para celebrarem o Senhor com os instrumentos que fiz para louvá-lo”.

[[v13-23-6]]

^<<v13-23-6,6>>^ Davi distribuiu-os em classes, segundo as linhagens de Levi: Gérson, Caat e Merari.

[[v13-23-7]]

^<<v13-23-7,7>>^ Dos gersonitas: Leedã e Semei.

[[v13-23-8]]

^<<v13-23-8,8>>^ Filhos de Leedã: o chefe Jaiel, Zetam e Joel: três.

[[v13-23-9]]

^<<v13-23-9,9>>^ Filhos de Semei: Salomit, Hoziel e Arã: três. Foram estes os chefes das famílias de Jeedã.

[[v13-23-10]]

^<<v13-23-10,10>>^ Filhos de Semei: Jeet, Ziza, Jeús e Berias.

[[v13-23-11]]

^<<v13-23-11,11>>^ Os filhos de Semei foram quatro: Jeet,o chefe, Ziza, o segundo. Jeús e Berias, não tendo muitos filhos, foram contados em uma só classe, segundo a família deles.

[[v13-23-12]]

^<<v13-23-12,12>>^ Filhos de Caat: Amram, Isaar, Hebron e Oziel: quatro.

[[v13-23-13]]

^<<v13-23-13,13>>^ Filhos de Amram: Aarão e Moisés. Aarão foi separado para ser consagrado como santíssimo, ele e seus filhos para sempre, para queimar perfumes diante do Senhor, para servi-lo e para dar a bênção perpetuamente em seu nome.

[[v13-23-14]]

^<<v13-23-14,14>>^ Os filhos de Moisés, homem de Deus, foram contados na tribo de Levi.

[[v13-23-15]]

^<<v13-23-15,15>>^ Filhos de Moisés: Gérson e Eliezer.

[[v13-23-16]]

^<<v13-23-16,16>>^ Filho de Gérson: Subael, o chefe.

[[v13-23-17]]

^<<v13-23-17,17>>^ O filho de Eliezer foi Roobias, o chefe. Eliezer não teve outro filho, mas os filhos de Roobias foram muito numerosos.

[[v13-23-18]]

^<<v13-23-18,18>>^ Filho de Isaar: Salomit, o chefe.

[[v13-23-19]]

^<<v13-23-19,19>>^ Filhos de Hebron: Jerias, o chefe; Amarias, o segundo; Jaaziel, o terceiro e Jecmaam, o quarto.

[[v13-23-20]]

^<<v13-23-20,20>>^ Filhos de Oziel: Micas, o chefe; Jesias, o segundo.

[[v13-23-21]]

^<<v13-23-21,21>>^ Filhos de Merari: Mooli e Musi. Filhos de Mooli: Eleazar e Cis.

[[v13-23-22]]

^<<v13-23-22,22>>^ Eleazar morreu sem deixar filhos, mas somente filhas, que se casaram com os filhos de Cis, seus parentes.

[[v13-23-23]]

^<<v13-23-23,23>>^ Filhos de Musi: Mooli, Éder e Jarmut: três.

[[v13-23-24]]

^<<v13-23-24,24>>^ Estes são os filhos de Levi, classificados por famílias, os chefes de família como foram enumerados, nominalmente e por cabeça. Eram encarregados do serviço do templo, desde a idade de vinte anos para cima.

[[v13-23-25]]

^<<v13-23-25,25>>^ Pois dizia Davi: “O Senhor, Deus de Israel, deu a paz a seu povo; ele habitará para sempre em Jerusalém”.

[[v13-23-26]]

^<<v13-23-26,26>>^ Também os levitas não tiveram mais que transportar a morada e todos os utensílios de seu serviço.

[[v13-23-27]]

^<<v13-23-27,27>>^ Foi segundo as últimas ordens de Davi que se fez o recenseamento dos filhos de Levi, da idade de vinte anos para cima.

[[v13-23-28]]

^<<v13-23-28,28>>^ Colocados juntos dos filhos de Aarão para o serviço da casa do Senhor, estavam encarregados do cuidado dos átrios e das salas, da purificação de todas as coisas santas, de todo o serviço do templo,

[[v13-23-29]]

^<<v13-23-29,29>>^ dos pães de proposição, da flor de farinha para as oblações, dos pães finos sem levedura, das tortas cozidas sobre a chapa e das tortas fritas, de todas as medidas de capacidade e comprimento.

[[v13-23-30]]

^<<v13-23-30,30>>^ Eles deviam apresentar-se cada manhã e cada tarde para louvar e celebrar o Senhor,

[[v13-23-31]]

^<<v13-23-31,31>>^ para oferecer todos os holocaustos ao Senhor, aos sábados, luas novas e nas solenidades, segundo o número que a lei prescreve que se ofereça ao Senhor.

[[v13-23-32]]

^<<v13-23-32,32>>^ Tinham eles que cuidar da manutenção da tenda de reunião, das coisas santas e dos filhos de Aarão, seus irmãos, para o serviço da casa do Senhor.

'''

xref:013-i-cronicas/013-i-cronicas-022.adoc#v13-22-0[&#60; Capítulo Anterior] | <<v13-23-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-024.adoc#v13-24-0[Próximo Capítulo &#62;]