include::./index.adoc[]

[[v13-9-0]]
=== I Crônicas, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Crônicas 9 continua descrevendo a genealogia dos filhos de Israel, com foco especial nos levitas que eram responsáveis pelo serviço no templo. Além disso, também é mencionada a restauração de Jerusalém após o exílio babilônico.
* Neemias 11:20: "O resto de Israel, dos sacerdotes, levitas e servidores do templo, estabeleceram-se em suas cidades ao longo de todo o território de Judá." Este versículo fala sobre a distribuição dos levitas e sacerdotes em diferentes cidades de Judá, o que é semelhante à lista de nomes de 1 Crônicas 9.
* Neemias 11:22: "O líder dos levitas em Jerusalém foi Uzi, filho de Bani, filho de Hasabias, filho de Matanias, filho de Mica. Dos descendentes de Asafe, cantores, ficou encarregado da obra do templo." Este versículo menciona a liderança dos levitas em Jerusalém, que é um tema central em 1 Crônicas 9.
* Neemias 11:36: "Parte dos levitas de Judá foi designada para prestar serviço no templo de Deus em Jerusalém, para a manutenção do culto, conforme prescrito pela lei, a saber, os cantores encarregados dos cânticos de louvor e as portarias do templo." Este versículo fala sobre o serviço dos levitas no templo em Jerusalém, o que é uma preocupação central em 1 Crônicas 9.
* Esdras 2:43: "Os servidores do templo: os filhos de Siá, os filhos de Hassufá, os filhos de Tabaot," Este versículo é parte de uma lista de nomes semelhante àquela encontrada em 1 Crônicas 9.
* Esdras 2:70: "Os sacerdotes, levitas, cantores, porteiros e servidores do templo, juntamente com alguns do povo e os demais levitas, instalaram-se em suas próprias cidades, incluindo todos os descendentes de Israel." Este versículo fala sobre a distribuição dos levitas em diferentes cidades e sua responsabilidade no serviço do templo, o que é semelhante ao que é descrito em 1 Crônicas 9.
****

[[v13-9-1]]

^<<v13-9-1,1>>^ Todo o Israel está registrado nas genealogias: elas encontram-se consignadas no Livro dos Reis de Israel. Em seguida, Judá foi deportado para Babilônia, por causa de suas infidelidades.

[[v13-9-2]]

^<<v13-9-2,2>>^ Os primeiros habitantes que viveram em suas possessões e suas cidades eram israelitas, sacerdotes, levitas e natineus.

[[v13-9-3]]

^<<v13-9-3,3>>^ Em Jerusalém, habitavam filhos de Judá, de Benjamim, de Efraim e de Manassés;

[[v13-9-4]]

^<<v13-9-4,4>>^ de Farés, filho de Judá: Otei, filho de Amiud, filho de Amri, filho de Omrai, filho de Bani;

[[v13-9-5]]

^<<v13-9-5,5>>^ dentre os silonitas: Asaías, filho mais velho e seus filhos;

[[v13-9-6]]

^<<v13-9-6,6>>^ dentre os filhos de Zara: Jeuel e seus irmãos. Ao todo seiscentos.

[[v13-9-7]]

^<<v13-9-7,7>>^ Dentre os filhos de Benjamim: Salo, filho de Mesolam, filho de Oduías, filho de Asana

[[v13-9-8]]

^<<v13-9-8,8>>^ e Joabnias, filho de Jeroam. Ela, filho de Ozi, filho de Mocori; Mesolam, filho de Safatias, filho de Reuel, filho de Jebanias.

[[v13-9-9]]

^<<v13-9-9,9>>^ Com seus irmãos, segundo suas gerações, eram eles novecentos e cinquenta e seis. Todos esses homens eram chefes de famílias em suas casas patriarcais.

[[v13-9-10]]

^<<v13-9-10,10>>^ Entre os sacerdotes: Jedaías, Joiarib, Jaquin,

[[v13-9-11]]

^<<v13-9-11,11>>^ Azarias, filho de Helcias, filho de Mesolam, filho de Sadoc, filho de Maraiot, filho de Aquitob, chefe da casa de Deus;

[[v13-9-12]]

^<<v13-9-12,12>>^ Adaías, filho de Jeroam, filho de Fassur, filho de Melquias; Maasai, filho de Adiel, filho de Jezra, filho de Mesolam, filho de Mesolamot, filho de Emer.

[[v13-9-13]]

^<<v13-9-13,13>>^ Eles e seus irmãos, chefes de suas casas patriarcais, perfaziam um total de mil setecentos e sessenta homens valorosos, ocupados no serviço da casa de Deus.

[[v13-9-14]]

^<<v13-9-14,14>>^ Entre os levitas: Semeías, filho de Hassub, filho de Ezricam, filho de Hasabias, descendente de Merari;

[[v13-9-15]]

^<<v13-9-15,15>>^ Bacbacar, Heres, Galal, Matanias, filho de Micas, filho de Zecri, filho de Asaf;

[[v13-9-16]]

^<<v13-9-16,16>>^ Abdias, filho de Semeías, filho de Galías, filho de Iditun; Baraquias, filho de Asa, filho de Elcana, que morava nas cidades dos netofateus.

[[v13-9-17]]

^<<v13-9-17,17>>^ Entre os porteiros: Selum, Acub, Telmon, Aimã e seus irmãos. Deles o chefe era Selum;

[[v13-9-18]]

^<<v13-9-18,18>>^ era ele ainda o guarda da porta do Rei, ao oriente. São estes os porteiros para o acampamento dos levitas:

[[v13-9-19]]

^<<v13-9-19,19>>^ Selum, filho de Cora, filho de Abiasaf, filho de Coré e seus irmãos; os coritas, da casa de seu pai, ocupavam as funções de guardas das portas do tabernáculo. Seus pais tinham guardado a entrada do acampamento do Senhor.

[[v13-9-20]]

^<<v13-9-20,20>>^ Fineias, filho de Eleazar, outrora tinha sido chefe deles e o Senhor estava com ele.

[[v13-9-21]]

^<<v13-9-21,21>>^ Zacarias, filho de Mesolamias, era porteiro na entrada da tenda de reunião.

[[v13-9-22]]

^<<v13-9-22,22>>^ Esses guardas das portas tinham sido escolhidos em número de duzentos e doze, registrados nas genealogias, segundo suas aldeias. Davi e Samuel, o vidente, os estabeleceram em suas funções.

[[v13-9-23]]

^<<v13-9-23,23>>^ Eles e seus filhos estavam colocados à guarda das portas da casa do Senhor, das casas do tabernáculo.

[[v13-9-24]]

^<<v13-9-24,24>>^ Havia porteiros nos quatro lados do templo: a leste, a oeste, ao norte e ao sul.

[[v13-9-25]]

^<<v13-9-25,25>>^ Seus irmãos, que moravam nas aldeias, vinham para junto deles cada semana, cada um por seu turno.

[[v13-9-26]]

^<<v13-9-26,26>>^ Os quatro chefes dos porteiros, que eram levitas, ficavam de sentinela constantemente, tendo ainda que vigiar os depósitos e os tesouros da casa de Deus.

[[v13-9-27]]

^<<v13-9-27,27>>^ Moravam ao redor da casa de Deus, da qual estavam encarregados da guarda, assim como do cargo de abri-la todas as manhãs.

[[v13-9-28]]

^<<v13-9-28,28>>^ Outros se encarregavam da vigilância dos objetos do culto que inventariavam à entrada e à saída.

[[v13-9-29]]

^<<v13-9-29,29>>^ Outros ainda cuidavam dos utensílios do santuário, da flor de farinha, do vinho, do azeite, do incenso e dos aromas.

[[v13-9-30]]

^<<v13-9-30,30>>^ Os filhos dos sacerdotes confeccionavam as essências aromáticas.

[[v13-9-31]]

^<<v13-9-31,31>>^ Matatias, um levita, primogênito de Selum, ao corita, tinha ao seu cuidado as tortas que se coziam no fogão.

[[v13-9-32]]

^<<v13-9-32,32>>^ Alguns de seus irmãos, filhos dos caatitas, estavam encarregados de preparar a cada sábado os pães da proposição.

[[v13-9-33]]

^<<v13-9-33,33>>^ Eram estes também os cantores, chefes das famílias levíticas: moravam nos apartamentos do templo, isentos de outras funções, para exercerem a sua, dia e noite.

[[v13-9-34]]

^<<v13-9-34,34>>^ São eles os chefes das famílias dos levitas, segundo as suas genealogias. Esses moravam em Jerusalém.

[[v13-9-35]]

^<<v13-9-35,35>>^ O pai dos gabaonitas, Jeiel, habitava em Gabaon; sua mulher se chamava Maaca.

[[v13-9-36]]

^<<v13-9-36,36>>^ Seu filho mais velho, Abdon; em seguida Sur, Cis, Baal, Ner, Nadab,

[[v13-9-37]]

^<<v13-9-37,37>>^ Gedor, Aio, Zacarias e Macelot.

[[v13-9-38]]

^<<v13-9-38,38>>^ Macelot gerou Samam. Eles moravam também com seus irmãos em Jerusalém.

[[v13-9-39]]

^<<v13-9-39,39>>^ Ner gerou Cis, e Cis gerou Saul, e Saul gerou Jônatas, Melquisua, Abinadab e Isbaal.

[[v13-9-40]]

^<<v13-9-40,40>>^ Filho de Jônatas: Meribaal. Meribaal gerou Micas.

[[v13-9-41]]

^<<v13-9-41,41>>^ Filhos de Micas: Fiton, Melec, Taraá.

[[v13-9-42]]

^<<v13-9-42,42>>^ Aaz gerou Jara, e Jara gerou Almat, Azmot e Zambri. Zambri gerou Mosa.

[[v13-9-43]]

^<<v13-9-43,43>>^ Mosa gerou Banaá, Rafaías, seu filho, Elasa, seu filho, Asel, seu filho;

[[v13-9-44]]

^<<v13-9-44,44>>^ Asel teve seis filhos, cujos nomes são: Ezricam, Bocru, Ismael, Sarias, Abdias, Hanã. São estes os filhos de Asel.

'''

xref:013-i-cronicas/013-i-cronicas-008.adoc#v13-8-0[&#60; Capítulo Anterior] | <<v13-9-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-010.adoc#v13-10-0[Próximo Capítulo &#62;]