include::./index.adoc[]

[[v13-4-0]]
=== I Crônicas, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Crônicas 4 descreve a genealogia de Judá, com destaque para uma lista de nomes e as bênçãos que Deus concedeu a alguns deles. Além disso, o capítulo também apresenta a oração de Jabes, que pediu a Deus por bênçãos e proteção.
* Gênesis 12:2: "De ti farei uma grande nação, e te abençoarei, e te engrandecerei o nome. Sê tu uma bênção!" - A bênção de Deus sobre Abraão e sua descendência é reafirmada, o que se relaciona com o tema de bênçãos em 1 Crônicas 4.
* Salmos 20:4: "Conceda-te segundo o teu coração, e cumpra todo o teu desígnio." - Este versículo fala sobre a realização dos desejos do coração de alguém, que é algo que a oração de Jabes busca.
* 2 Crônicas 20:12: "Ó nosso Deus, porventura não julgarás tu? Pois em nós não há força perante esta grande multidão que vem contra nós, e não sabemos nós o que faremos; porém os nossos olhos estão postos em ti." - A oração de Jabes é um exemplo de confiança e dependência de Deus, semelhante à confiança que o rei Josafá depositou em Deus em 2 Crônicas 20.
* Neemias 11:6: "Todos os filhos de Pérez, que habitavam em Jerusalém, eram quatrocentos e sessenta e oito homens valentes." - Este versículo fala sobre os descendentes de Judá que viveram em Jerusalém, que é um tema abordado em 1 Crônicas 4.
* Êxodo 33:15: "Então respondeu Moisés ao Senhor: Se a tua presença não há de ir comigo, não nos faças subir daqui." - Este versículo enfatiza a importância da presença de Deus na vida de Seu povo, o que é uma questão central na oração de Jabes em 1 Crônicas 4.
****

[[v13-4-1]]

^<<v13-4-1,1>>^ Filhos de Judá: Farés, Hesron, Carmi, Hur e Sobal.

[[v13-4-2]]

^<<v13-4-2,2>>^ Reaías, filho de Sobal, gerou Jaat; Jaat gerou Aumai e Laad. Estas são as famílias dos sareus.

[[v13-4-3]]

^<<v13-4-3,3>>^ Eis os descendentes de Etam: Jezrael, Jesema e Jedebos; o nome de sua irmã era Asalelfuni.

[[v13-4-4]]

^<<v13-4-4,4>>^ Fanuel era pai de Gedor e Ezer, pai de Hosa. Estes são os filhos de Hur, o primogênito de Éfrata, pai de Belém.

[[v13-4-5]]

^<<v13-4-5,5>>^ Asur, pai de Tícua, teve duas mulheres: Halaá e Naara.

[[v13-4-6]]

^<<v13-4-6,6>>^ Naara deu-lhe à luz Oozam, Héfer, Temanita e Aastarita; são estes os filhos de Naara.

[[v13-4-7]]

^<<v13-4-7,7>>^ Filhos de Haalá: Seret, Saar e Etnã.

[[v13-4-8]]

^<<v13-4-8,8>>^ Cós gerou Anob e Soboba e as famílias de Aareel, filho de Arum.

[[v13-4-9]]

^<<v13-4-9,9>>^ Jabes foi mais ilustre que seus irmãos. Sua mãe lhe deu o nome de Jabes, dizendo: “É porque o dei à luz com dor”.

[[v13-4-10]]

^<<v13-4-10,10>>^ Jabes invocou o Deus de Israel: “Se vós me abençoardes, alargando meus limites, se vossa mão estiver comigo para me preservar da desgraça e me poupar da aflição”. E Deus lhe concedeu o que tinha pedido.

[[v13-4-11]]

^<<v13-4-11,11>>^ Calub, irmão de Suaá, gerou Mair, pai de Eston.

[[v13-4-12]]

^<<v13-4-12,12>>^ Eston gerou a casa de Rafa, Fesse e Teina, pai da cidade de Irnaás. Foram estes os habitantes de Recab.

[[v13-4-13]]

^<<v13-4-13,13>>^ Filhos de Cenez: Otoniel e Seraías. Filhos de Otoniel: Hatat e Maonati, que gerou Ofra.

[[v13-4-14]]

^<<v13-4-14,14>>^ Seraías gerou Joab, pai de Ge-Harasim, porque eles eram artesãos.

[[v13-4-15]]

^<<v13-4-15,15>>^ Filhos de Caleb, filho de Jefoné: Hir, Ela e Naam. Filho de Ela: Cenez.

[[v13-4-16]]

^<<v13-4-16,16>>^ Filhos de Jaleleel: Zif, Zifa, Tirias e Asrael.

[[v13-4-17]]

^<<v13-4-17,17>>^ Filhos de Ezra: Jeter, Mered, Efer e Jalon. A mulher de Mered deu à luz Maria, Samai e Jesba, pai de Estemo.

[[v13-4-18]]

^<<v13-4-18,18>>^ Sua mulher judaíta deu à luz Jared, pai de Gedor, Héber, pai de Soco e Icutiel, pai de Zanoe. São estes os filhos de Betias, filha do faraó, que Mered desposara.

[[v13-4-19]]

^<<v13-4-19,19>>^ Filhos da mulher de Odias, irmã de Naam: o pai da Ceila, de Garmi e Estemo que era de Macati.

[[v13-4-20]]

^<<v13-4-20,20>>^ Filhos de Simão: Amnon, Rina, Ben-Hanã e Tilon. Os filhos de Jesi: Zoet e Ben-Zoet.

[[v13-4-21]]

^<<v13-4-21,21>>^ Filhos de Sela, filho de Judá: Her, pai de Leca, Laada, pai de Maresa e as famílias da casa onde se fabricava linho fino, casa de Bet-Asbea e Joaquim,

[[v13-4-22]]

^<<v13-4-22,22>>^ e os homens de Cozeba, Joás e Saraf, que dominaram sobre Moab e retornaram a Belém, segundo antigas tradições.

[[v13-4-23]]

^<<v13-4-23,23>>^ Eles eram os oleiros e os habitantes de Nataim e de Gadera; lá habitavam, estando a serviço do rei.

[[v13-4-24]]

^<<v13-4-24,24>>^ Filhos de Simeão: Namuel, Jamin, Jarib, Zara e Saul.

[[v13-4-25]]

^<<v13-4-25,25>>^ Selum, seu filho, Mabsam, seu filho, Masma, seu filho.

[[v13-4-26]]

^<<v13-4-26,26>>^ Filhos de Masma: Hamuel, seu filho, Zacur, Semei, seu filho,

[[v13-4-27]]

^<<v13-4-27,27>>^ Semei teve dezesseis filhos e seis filhas; seus irmãos não tiveram muitos filhos e suas famílias não foram tão numerosas como as dos filhos de Judá.

[[v13-4-28]]

^<<v13-4-28,28>>^ Eles habitavam em Bersabeia, em Molada, em Hasar-Sual,

[[v13-4-29]]

^<<v13-4-29,29>>^ em Bala, em Asem, em Tolad,

[[v13-4-30]]

^<<v13-4-30,30>>^ em Batuel, em Horma, em Siceleg, em Bet-Marcabot,

[[v13-4-31]]

^<<v13-4-31,31>>^ em Hasar-Susim, em Bet-Berai e em Saarim. Estas foram suas cidades até o reinado de Davi.

[[v13-4-32]]

^<<v13-4-32,32>>^ Possuíam ainda Etam, Aen, Remon, Toquen e Asã, cinco cidades

[[v13-4-33]]

^<<v13-4-33,33>>^ e todas as aldeias de suas redondezas, até Baal. Estas foram suas residências e seus registros genealógicos.

[[v13-4-34]]

^<<v13-4-34,34>>^ Masobab, Jemlec, Josa, filho de Amasias,

[[v13-4-35]]

^<<v13-4-35,35>>^ Joel, Jeú, filho de Josabias, filho de Saraías, filho de Asiel,

[[v13-4-36]]

^<<v13-4-36,36>>^ Elioenai, Jacoba, Isuaías, Asaías, Adiel, Isimiel, Banaías,

[[v13-4-37]]

^<<v13-4-37,37>>^ Ziza, filho de Sefei, filho de Alon, filho de Jedaías, filho de Semri, filho de Semeías.

[[v13-4-38]]

^<<v13-4-38,38>>^ Estes homens, indicados por seus nomes, eram príncipes nas suas famílias. Suas casas patriarcais eram grandemente multiplicadas.

[[v13-4-39]]

^<<v13-4-39,39>>^ Eles foram da costa de Gador, até o lado oriental do vale, à procura de pastagens para os rebanhos.

[[v13-4-40]]

^<<v13-4-40,40>>^ Encontraram pastagens abundantes e bons num território amplo, tranquilo e seguro, outrora habitado pelos camitas.

[[v13-4-41]]

^<<v13-4-41,41>>^ Esses homens, indicados por seus nomes, vieram no tempo de Ezequias, rei de Judá: destruíram as tendas dos habitantes dessa terra, assim como os maonitas que lá se encontravam e os votaram ao interdito até o dia de hoje. Estabeleceram-se em seu lugar, porque lá havia pastagens para seus rebanhos.

[[v13-4-42]]

^<<v13-4-42,42>>^ Quinhentos homens da família de Simeão dirigiram-se também para as montanhas de Seir. Eram seus chefes: Faltias, Naarias, Rafaías e Oziel, filhos de Jesi.

[[v13-4-43]]

^<<v13-4-43,43>>^ Destroçaram os amalecitas sobreviventes e lá se estabeleceram até este dia.

'''

xref:013-i-cronicas/013-i-cronicas-003.adoc#v13-3-0[&#60; Capítulo Anterior] | <<v13-4-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-005.adoc#v13-5-0[Próximo Capítulo &#62;]