include::./index.adoc[]

[[v13-5-0]]
=== I Crônicas, 5
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 5 de 1 Crônicas começa com a genealogia de Rúben, o primogênito de Jacó. Em seguida, o capítulo relata a guerra dos filhos de Rúben, Gade e a meia tribo de Manassés contra os hagarenos. A seguir estão cinco versículos relacionados com os temas abordados em 1 Crônicas 5:
* Números 32:1: "Os filhos de Rúben e os filhos de Gade possuíam um grande número de gado. Vendo que as terras de Jazer e Gileade eram adequadas para a criação de animais," Este versículo é importante para entender a situação de prosperidade material dos filhos de Rúben e Gade e como isso influenciou na escolha de suas terras.
* Josué 22:10: "Quando chegaram a Gelilote, na terra de Canaã, os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés construíram ali um grande altar, à vista dos israelitas." Este versículo relata uma ação que desagradou o restante dos israelitas, pois interpretaram como um ato de rebelião e infidelidade à aliança com Deus.
* Números 32:20: "Respondeu-lhes Moisés: Se fizerdes isto, se vos preparardes para a guerra, e passardes armados diante do Senhor," Este versículo é uma resposta de Moisés às tribos de Rúben e Gade, que pediam para ficar com as terras conquistadas a leste do Jordão, mas sem lutar com as outras tribos.
* 1 Samuel 13:14: "Mas agora o teu reino não subsistirá; o Senhor buscou para si um homem segundo o seu coração, e já lhe ordenou que seja príncipe sobre o seu povo, porquanto não guardaste o que o Senhor te ordenara." Este versículo é uma referência ao reinado de Saul, que perdeu a liderança de Israel por desobedecer a Deus. Em 1 Crônicas 5:25, o capítulo menciona que os filhos de Gade habitaram a terra de Golã, que foi um dos lugares onde Saul foi enterrado.
* Isaías 9:1: "Mas haverá um dia em que a escuridão não terá mais lugar na terra de Zebulom e Naftali. Os que sofrem agora serão envolvidos por uma grande luz. Assim como a luz brilha na escuridão, assim brilhará uma grande luz sobre essa terra." Este versículo fala sobre a restauração da terra de Zebulom e Naftali, que foram locais de grande sofrimento para o povo de Israel, mas que serão agraciados com uma grande luz. O capítulo 5 de 1 Crônicas menciona que os filhos de Rúben, Gade e a meia tribo de Manassés possuíam terras em Gileade, que fazia parte da região de Zebulom e Naftali.
****

[[v13-5-1]]

^<<v13-5-1,1>>^ Filhos de Rúben, o primogênito de Israel. Com efeito, era ele o mais velho, mas como tinha manchado o leito de seu pai, seu direito de primogenitura foi dado aos filhos de José, filho de Israel. Mas José não foi inscrito como primogênito nas genealogias.

[[v13-5-2]]

^<<v13-5-2,2>>^ Pois Judá foi poderoso entre seus irmãos e é dele que saiu o príncipe. Mas o direito de primogenitura pertence a José.

[[v13-5-3]]

^<<v13-5-3,3>>^ Filhos de Rúben, primogênito de Israel: Henoc, Falu, Hesron e Carmi.

[[v13-5-4]]

^<<v13-5-4,4>>^ Filhos de Joel: Samaías, seu filho, Gog, seu filho, Semei, seu filho;

[[v13-5-5]]

^<<v13-5-5,5>>^ Micas, seu filho, Reaías, seu filho, Baal, seu filho,

[[v13-5-6]]

^<<v13-5-6,6>>^ Beera, seu filho, que Teglat-Falasar, rei da Assíria, levou cativo. Era ele príncipe dos filhos de Rúben.

[[v13-5-7]]

^<<v13-5-7,7>>^ Irmãos de Beera, segundo suas famílias, assim como estão inscritos nas suas genealogias: o primeiro foi Jeiel, depois Zacarias,

[[v13-5-8]]

^<<v13-5-8,8>>^ mais Bela, filho de Azaz, filho de Hosama, filho de Joel. Bela habitava em Aroer e ia até Nebo e Baal-Meon.

[[v13-5-9]]

^<<v13-5-9,9>>^ Ao oriente, ocupava a terra até a entrada do deserto, que vai até o Eufrates, porque seus rebanhos eram numerosos na terra de Galaad.

[[v13-5-10]]

^<<v13-5-10,10>>^ No tempo de Saul, fizeram guerra contra os agareus que tombaram entre suas mãos. Habitaram suas tendas na costa oriental de Galaad.

[[v13-5-11]]

^<<v13-5-11,11>>^ Os filhos de Galaad habitavam defronte deles na terra de Basã até Selca.

[[v13-5-12]]

^<<v13-5-12,12>>^ Joel, o primeiro, Safam, o segundo, Janaí e Safat, em Basã.

[[v13-5-13]]

^<<v13-5-13,13>>^ Seus irmãos, segundo suas casas patriarcais, eram: Miguel, Mesolam, Sebe, Jorai, Jacã, Zie e Héber, ao todo sete.

[[v13-5-14]]

^<<v13-5-14,14>>^ Eles eram filhos de Abiail, filho de Huri, filho de Jaroe, filho de Galaad, filho de Miguel, filho de Jesesi, filho de Jedo, filho de Buz,

[[v13-5-15]]

^<<v13-5-15,15>>^ Aqui, filho de Abdiel, filho de Guni, era o chefe de sua casa patriarcal.

[[v13-5-16]]

^<<v13-5-16,16>>^ Habitavam em Galaad, em Basã e nas suas aldeias até as extremidades das pastagens de Sarona.

[[v13-5-17]]

^<<v13-5-17,17>>^ Todos foram registrados no tempo de Joatão, rei de Judá, e no tempo de Jeroboão, rei de Israel.

[[v13-5-18]]

^<<v13-5-18,18>>^ Os filhos de Rúben, de Gad e da meia tribo de Manassés tinham em suas fileiras homens valorosos, que traziam escudo e espada, manejavam o arco e eram muito aguerridos, em número de 44.760 homens aptos para o combate.

[[v13-5-19]]

^<<v13-5-19,19>>^ Fizeram guerra aos agareus, em Jetur, em Nafis e em Nodab.

[[v13-5-20]]

^<<v13-5-20,20>>^ Eles venceram e os agareus com todos os seus aliados lhes foram entregues. Durante o combate, com efeito, eles tinham invocado a Deus, que os ouviu, porque eles tinham posto nele sua confiança.

[[v13-5-21]]

^<<v13-5-21,21>>^ Arrebataram seus rebanhos: 50.000 camelos, 250.000 ovelhas, 2.000 jumentos e 100.000 pessoas;

[[v13-5-22]]

^<<v13-5-22,22>>^ muitos caíram mortos, pois essa guerra vinha de Deus. Estabeleceram-se no lugar dos vencidos até o cativeiro.

[[v13-5-23]]

^<<v13-5-23,23>>^ Os filhos da meia tribo de Manassés moravam na terra que vai de Basã até o Baal-Hermon, o Sanir e a montanha do Hermon; eram numerosos.

[[v13-5-24]]

^<<v13-5-24,24>>^ Eis os chefes de suas famílias patriarcais: Éfer, Jesi, Eliel, Ezriel, Jeremias, Odoías e Jediel, homens valentes e poderosos, célebres chefes de suas casas patriarcais.

[[v13-5-25]]

^<<v13-5-25,25>>^ Mas foram infiéis ao Deus de seus pais e prostituíram-se, adorando os deuses dos povos que Deus tinha destruído diante deles.

[[v13-5-26]]

^<<v13-5-26,26>>^ O Deus de Israel suscitou o espírito de Pul, rei da Assíria, e o espírito de Teglat-Falasar, rei da Assíria, que levou cativos os filhos de Rúben, os filhos de Gad e a meia tribo de Manassés: ele os deportou para Hala, para Habor, para Ara e para o rio Gozã, onde permaneceram até o dia de hoje.

'''

xref:013-i-cronicas/013-i-cronicas-004.adoc#v13-4-0[&#60; Capítulo Anterior] | <<v13-5-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-006.adoc#v13-6-0[Próximo Capítulo &#62;]