include::./index.adoc[]

[[v13-13-0]]
=== I Crônicas, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Crônicas 13 descreve a tentativa fracassada de Davi de trazer a arca da aliança para Jerusalém. Embora sua intenção fosse boa, ele não seguiu as instruções de Deus para transportar a arca corretamente e acabou causando a morte de Uzá. A partir deste capítulo, escolhi cinco versículos relacionados aos temas de obediência, reverência, adoração, arrependimento e santidade, que podem ser encontrados em outras partes da Bíblia.
* Deuteronômio 28:1: "E será que, se ouvires a voz do SENHOR teu Deus, tendo cuidado de guardar todos os seus mandamentos que eu hoje te ordeno, o SENHOR teu Deus te exaltará sobre todas as nações da terra." Este versículo de Deuteronômio destaca a importância da obediência aos mandamentos de Deus. Davi falhou em obedecer as instruções de Deus para transportar a arca e, como resultado, enfrentou consequências graves.
* Salmos 89:7: "Deus é muito terrível na assembléia dos santos, e para ser reverenciado por todos os que o cercam." A arca da aliança era um símbolo da presença de Deus, e Davi entendeu a importância de reverenciá-la. Este versículo do Salmo 89 destaca a importância de reverenciar a Deus e sua presença.
* Salmos 96:9: "Adorai ao SENHOR na beleza da santidade; tremei diante dele toda a terra." Davi reconheceu a importância de adorar a Deus de forma apropriada. Este versículo do Salmo 96 destaca a importância de adorar a Deus na beleza da santidade.
* Provérbios 28:13: "O que encobre as suas transgressões nunca prosperará, mas o que as confessa e deixa alcançará misericórdia." Quando Uzá tocou a arca da aliança, ele estava desobedecendo a Deus. Davi reconheceu seu erro e se arrependeu. Este versículo de Provérbios destaca a importância de confessar nossos pecados e nos arrependermos diante de Deus.
* Levítico 10:3: "E disse Moisés a Arão: Isto é o que o SENHOR falou, dizendo: Serei santificado naqueles que se chegam a mim e serei glorificado diante de todo o povo." Davi falhou em transportar a arca de maneira santa e reverente. Este versículo de Levítico destaca a importância da santidade e reverência na adoração a Deus.
****

[[v13-13-1]]

^<<v13-13-1,1>>^ Davi consultou os chefes de milhares e de centenas, com todos os príncipes.

[[v13-13-2]]

^<<v13-13-2,2>>^ E disse a toda a assembleia de Israel: “Se estiverdes de acordo e isso parece vir do Senhor, nosso Deus, enviemos, sem tardar, mensageiros a nossos irmãos, em todas as regiões de Israel, como também aos sacerdotes e levitas, em todas as localidades onde estão suas pastagens para que se juntem a nós,

[[v13-13-3]]

^<<v13-13-3,3>>^ e tornemos a trazer para nós a arca de nosso Deus, pois não cuidamos dela no tempo de Saul.”

[[v13-13-4]]

^<<v13-13-4,4>>^ E toda a assembleia achou bom agir desse modo, porque isso pareceu conveniente a todo o povo.

[[v13-13-5]]

^<<v13-13-5,5>>^ Davi convocou todo o Israel, desde o Sior no Egito até a entrada de Emat, a fim de trazer de Cariatarim a arca de Deus.^&#42;1^

[[v13-13-6]]

^<<v13-13-6,6>>^ Davi, com todo o Israel, subiu a Baala, em Cariatarim de Judá, para trazer de lá a arca do Senhor Deus, do Senhor que tem seu trono sobre os querubins, diante da qual seu nome é invocado.^&#42;1^

[[v13-13-7]]

^<<v13-13-7,7>>^ A arca de Deus foi colocada num carro novo e a trouxeram da casa de Abinadab; Oza e Aio conduziam o carro.

[[v13-13-8]]

^<<v13-13-8,8>>^ Davi e todo o Israel dançavam diante de Deus, com toda a sua alma, cantando com acompanhamento de cítaras, as harpas e tamborins, címbalos e trombetas.

[[v13-13-9]]

^<<v13-13-9,9>>^ Quando chegavam à eira de Quidon, Oza estendeu a mão para suster a arca de Deus, porque os bois, tropeçando, a tinham feito inclinar.

[[v13-13-10]]

^<<v13-13-10,10>>^ A ira do Senhor se inflamou contra Oza e o feriu, porque estendera sua mão para a arca; e Oza morreu ali mesmo diante de Deus.

[[v13-13-11]]

^<<v13-13-11,11>>^ Davi ficou contristado porque o Senhor ferira Oza. E esse lugar traz ainda hoje o nome de Ferés-Oza.

[[v13-13-12]]

^<<v13-13-12,12>>^ Nesse dia, Davi teve medo de Deus: “Como – disse ele – faria eu entrar a arca de Deus em minha casa?”.

[[v13-13-13]]

^<<v13-13-13,13>>^ E Davi não acolheu a arca em sua casa, na Cidade de Davi. Ele a mandou levar à casa de Obed-Edom, de Gat.

[[v13-13-14]]

^<<v13-13-14,14>>^ A arca de Deus ficou durante três meses com a família de Obed-Edom, na sua casa; e o Senhor abençoou a família de Obed-Edom com tudo o que lhe pertencia.

'''

xref:013-i-cronicas/013-i-cronicas-012.adoc#v13-12-0[&#60; Capítulo Anterior] | <<v13-13-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-014.adoc#v13-14-0[Próximo Capítulo &#62;]