include::./index.adoc[]

[[v13-24-0]]
=== I Crônicas, 24
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Crônicas 24 descreve a organização dos sacerdotes em 24 turmas e como elas foram distribuídas para servir no templo. Os versículos abaixo se relacionam com esse tema:
* Êxodo 28:1 - "Chame a si Arão, seu irmão, e seus filhos Nadabe, Abiú, Eleazar e Itamar para que sejam meus sacerdotes." Esse versículo é importante porque estabelece que apenas os descendentes de Arão poderiam servir como sacerdotes, e a organização em turmas era uma forma de garantir que cada sacerdote tivesse a oportunidade de servir no templo.
* Números 3:5-10 - "O Senhor disse a Moisés: Traga a tribo de Levi e apresente-a ao sacerdote Arão para que a ajudem. Eles cuidarão das tarefas do tabernáculo, fazendo tudo o que precisa ser feito ali." Esses versículos mostram que os levitas foram escolhidos para ajudar os sacerdotes no serviço do templo e que havia uma divisão clara de tarefas.
* 1 Crônicas 23:13 - "Arão foi separado para ser consagrado como o mais sagrado dos sacerdotes, ele e seus filhos para sempre, a fim de que oferecessem incenso diante do Senhor, para que o servissem e para que invocassem o seu nome." Esse versículo destaca a importância da consagração dos sacerdotes e a centralidade do serviço de adoração no templo.
* 1 Crônicas 28:13 - "Escolha você também, diante do Senhor, o seu Deus, líderes para o seu povo: homens que sejam sábios, entendidos e experientes, de cada tribo, para que os coloque como chefes sobre o povo." Esse versículo destaca a importância da organização e liderança no serviço religioso, algo que se reflete na organização em turmas dos sacerdotes.
* Neemias 12:1 - "Estes são os sacerdotes e os levitas que voltaram com Zorobabel, filho de Sealtiel, e com Jesua: Seraías, Jeremias, Esdras." Esse versículo destaca a continuidade da organização dos sacerdotes e levitas ao longo do tempo, mostrando como essa estrutura continuou a ser importante mesmo após o exílio babilônico.
****

[[v13-24-1]]

^<<v13-24-1,1>>^ Eis as classes dos filhos de Aarão: Nadab, Abiú, Eleazar e Itamar.

[[v13-24-2]]

^<<v13-24-2,2>>^ Nadab e Abiú morreram antes de seu pai, sem deixar filhos e Eleazar e Itamar exerceram as funções do sacerdócio.

[[v13-24-3]]

^<<v13-24-3,3>>^ Davi, Sadoc, da linhagem de Eleazar, e Abimelec, da linhagem de Itamar, dividiram os filhos de Aarão por classes, segundo o serviço deles.

[[v13-24-4]]

^<<v13-24-4,4>>^ Havia entre os filhos de Eleazar mais chefes que entre os filhos de Itamar; foram assim distribuídos: para os filhos de Eleazar, dezesseis chefes de família, e, para os filhos de Itamar, oito chefes de família.

[[v13-24-5]]

^<<v13-24-5,5>>^ Uns e outros foram distribuídos pela sorte, porque havia príncipes do santuário e príncipes de Deus, tanto entre os filhos de Eleazar, como entre os filhos de Itamar.

[[v13-24-6]]

^<<v13-24-6,6>>^ O escriba levita Semeías, filho de Natanael, inscreveu-os em presença do rei e dos príncipes, do sacerdote Sadoc e de Abimelec, filho de Abiatar, como também de chefes de famílias sacerdotais e levíticas, sendo uma família sorteada para Eleazar, em seguida, uma família para Itamar.

[[v13-24-7]]

^<<v13-24-7,7>>^ A primeira sorte caiu a Joiarib, a segunda a Jedeías,

[[v13-24-8]]

^<<v13-24-8,8>>^ a terceira a Harim, a quarta a Seorim,

[[v13-24-9]]

^<<v13-24-9,9>>^ a quinta a Melquias, a sexta a Mainã,

[[v13-24-10]]

^<<v13-24-10,10>>^ a sétima a Acos, a oitava a Abias,

[[v13-24-11]]

^<<v13-24-11,11>>^ a nona a Jesua, a décima a Sequenias,

[[v13-24-12]]

^<<v13-24-12,12>>^ a décima primeira a Eliasib, a décima segunda a Jacim,

[[v13-24-13]]

^<<v13-24-13,13>>^ a décima terceira a Hofa, a décima quarta a Isbaab,

[[v13-24-14]]

^<<v13-24-14,14>>^ a décima quinta a Belga, a décima sexta a Emer,

[[v13-24-15]]

^<<v13-24-15,15>>^ a décima sétima a Hezir, a décima oitava a Afses,

[[v13-24-16]]

^<<v13-24-16,16>>^ a décima nona a Fetatias, a vigésima a Ezequiel,

[[v13-24-17]]

^<<v13-24-17,17>>^ a vigésima primeira a Jaquin, a vigésima segunda a Gamul,

[[v13-24-18]]

^<<v13-24-18,18>>^ a vigésima terceira a Dalaías, a vigésima quarta a Maazias.

[[v13-24-19]]

^<<v13-24-19,19>>^ Assim, foram eles classificados para seus serviços no Templo do Senhor, segundo as regras estabelecidas por Aarão, seu pai, consoante as ordens do Senhor, Deus de Israel.

[[v13-24-20]]

^<<v13-24-20,20>>^ Dos restantes levitas, os chefes foram: dos filhos de Amram: Subael; filho de Subael: Jeedias;

[[v13-24-21]]

^<<v13-24-21,21>>^ de Roobias, dos filhos de Roobias: o chefe Jesias.

[[v13-24-22]]

^<<v13-24-22,22>>^ Dos isaaritas: Solomot; dos filhos de Solomot: Jaat.

[[v13-24-23]]

^<<v13-24-23,23>>^ Filhos de Hebron: Jerias, Amarias, o segundo, Jaaziel, o terceiro, Jecmaam, o quarto.

[[v13-24-24]]

^<<v13-24-24,24>>^ Filho de Oziel: Micas; dos filhos de Micas: Samir;

[[v13-24-25]]

^<<v13-24-25,25>>^ irmão de Micas: Jesias; filho de Jesias: Zacarias.

[[v13-24-26]]

^<<v13-24-26,26>>^ Filhos de Merari: Mooli e Musi.

[[v13-24-27]]

^<<v13-24-27,27>>^ Filhos de Merari, por Oziau, seu filho: Saão, Zacur e Hebri.

[[v13-24-28]]

^<<v13-24-28,28>>^ De Mooli: Eleazar, que não teve filhos; de Cis, os filhos de Cis:

[[v13-24-29]]

^<<v13-24-29,29>>^ Jerameel.

[[v13-24-30]]

^<<v13-24-30,30>>^ Filhos de Musi: Mooli, Éder e Jarmut.

[[v13-24-31]]

^<<v13-24-31,31>>^ Esses são os filhos de Levi, segundo suas famílias.

[[v13-24-32]]

^<<v13-24-32,32>>^ Também eles, como seus irmãos, os filhos de Aarão, foram tirados pela sorte, em presença do rei Davi, de Sadoc e Abimelec, como também dos chefes de família dos sacerdotes e levitas, estando os mais velhos em mesma igualdade que os mais novos.

'''

xref:013-i-cronicas/013-i-cronicas-023.adoc#v13-23-0[&#60; Capítulo Anterior] | <<v13-24-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-025.adoc#v13-25-0[Próximo Capítulo &#62;]