include::./index.adoc[]

[[v13-21-0]]
=== I Crônicas, 21
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Crônicas 21 relata como Davi, incentivado por Satanás, ordenou um recenseamento de Israel, desafiando a lei de Deus e desafiando a sua confiança em Deus. Como resultado, Deus enviou um anjo para punir o povo de Israel com uma praga. Abaixo estão cinco versículos relacionados com os temas abordados em 1 Crônicas 21:
* Êxodo 30:12: "Quando fizeres o recenseamento dos filhos de Israel, cada um deles dará ao Senhor o resgate da sua vida quando for contado; para que não haja praga entre eles, quando os contares." Este versículo destaca a importância de seguir as leis de Deus, inclusive na realização de recenseamentos, a fim de evitar a ira divina.
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; em todos os seus caminhos reconheça a ele, e ele endireitará as suas veredas." Este versículo destaca a importância da confiança em Deus e na obediência a ele em todas as circunstâncias.
* Salmos 106:29-30: "Provocaram-no com os seus feitos; e uma praga irrompeu entre eles. Então Fineias se levantou e intercedeu, e cessou a praga." Este versículo destaca como a desobediência às leis de Deus pode resultar em uma praga, mas a intercessão pode trazer alívio.
* 2 Samuel 24:10: "Mas, depois de ter contado o povo, Davi sentiu remorsos e disse ao Senhor: 'Eu pequei muito ao fazer isso. Agora, Senhor, apaga a culpa do teu servo, pois agi muito tolo.'" Este versículo mostra que, mesmo quando tomamos decisões erradas, ainda podemos pedir perdão a Deus e buscar sua misericórdia.
* Tiago 4:7-8: "Portanto, submetam-se a Deus. Resistam ao diabo, e ele fugirá de vocês. Aproximem-se de Deus, e ele se aproximará de vocês. Pecadores, limpem as mãos, e vocês, que têm a mente dividida, purifiquem o coração." Este versículo destaca a importância da submissão a Deus, resistência ao diabo e busca pela pureza do coração.
****

[[v13-21-1]]

^<<v13-21-1,1>>^ Levantou-se Satã contra Israel e excitou Davi a fazer o recenseamento de Israel.^&#42;1^

[[v13-21-2]]

^<<v13-21-2,2>>^ Disse Davi a Joab e aos chefes do povo: “Ide e fazei o recenseamento dos israelitas, desde Bersabeia até Dã, e fazei-me o relatório para que eu saiba o número deles”.

[[v13-21-3]]

^<<v13-21-3,3>>^ Respondeu Joab: “O Senhor multiplique seu povo cem vezes mais! Não são todos eles, ó rei, meu senhor, os servos de meu senhor? Por que, no entanto, exige meu senhor isso? Por que sobrecarregar Israel de um pecado?”.

[[v13-21-4]]

^<<v13-21-4,4>>^ Mas o rei persistiu na ordem que dera a Joab. E Joab partiu, percorreu todo o Israel, depois retornou a Jerusalém.

[[v13-21-5]]

^<<v13-21-5,5>>^ Joab entregou a Davi a lista do recenseamento do povo: havia em todo o Israel um milhão e cem mil homens aptos para o manejo da espada. Em Judá havia quatrocentos e setenta mil.

[[v13-21-6]]

^<<v13-21-6,6>>^ Não fez o recenseamento da tribo de Levi nem de Benjamim, porque a ordem do rei lhe repugnava.

[[v13-21-7]]

^<<v13-21-7,7>>^ Deus não viu isso com bons olhos e feriu Israel.^&#42;1^

[[v13-21-8]]

^<<v13-21-8,8>>^ Davi disse a Deus: “Pequei gravemente agindo de tal maneira. Agora dignai-vos perdoar a iniquidade de vosso servo, porque agi em completa insensatez”.

[[v13-21-9]]

^<<v13-21-9,9>>^ Então, o Senhor dirigiu-se a Gad, vidente de Davi, nestes termos:

[[v13-21-10]]

^<<v13-21-10,10>>^ “Vai dizer a Davi: Eis o que diz o Senhor: Eu te proponho três coisas; escolhe uma delas, e eu a farei acontecer”.

[[v13-21-11]]

^<<v13-21-11,11>>^ Gad foi ao encontro de Davi e lhe disse: “Eis o que disse o Senhor:

[[v13-21-12]]

^<<v13-21-12,12>>^ Escolhe: ou três anos de fome, ou três meses durante os quais fugirás de teus inimigos e serás atingido por sua espada ou, ainda, três dias em que a espada do Senhor ou a peste maltratarão a terra e o anjo do Senhor devastará todo o território de Israel. A ti compete ver agora que resposta devo dar àquele que me enviou”.

[[v13-21-13]]

^<<v13-21-13,13>>^ “Estou – respondeu Davi – numa cruel angústia. Ah! Caia eu nas mãos do Senhor, porque imensa é sua misericórdia; mas que eu não caia nas mãos dos homens!”

[[v13-21-14]]

^<<v13-21-14,14>>^ E o Senhor mandou a peste a Israel. Em Israel tombaram setenta mil homens.

[[v13-21-15]]

^<<v13-21-15,15>>^ Deus enviou a Jerusalém um anjo para destruí-la. Enquanto ele a assolava, o Senhor, que olhava, compadeceu-se desse mal e disse ao anjo destruidor: “Basta! Retira agora tua mão!”. Ora, o anjo do Senhor achava-se perto da eira de Ornã, o jebuseu.

[[v13-21-16]]

^<<v13-21-16,16>>^ Davi, tendo levantado os olhos, viu o anjo do Senhor que estava entre o céu e a terra, com uma espada desembainhada em sua mão, dirigida contra Jerusalém. Então, Davi e os anciãos, cobertos de sacos, prostraram-se com o rosto por terra.

[[v13-21-17]]

^<<v13-21-17,17>>^ E Davi disse a Deus: “Não fui eu quem mandou fazer o recenseamento do povo? Fui eu quem pecou, fui eu quem fez esse mal. Mas essas ovelhas, o que fizeram elas? Senhor, meu Deus, que vossa mão caia, portanto, sobre mim e sobre a casa de meu pai para castigar, mas não sobre vosso povo”.

[[v13-21-18]]

^<<v13-21-18,18>>^ O anjo do Senhor mandou Gad dizer a Davi que subisse à eira de Ornã, o jebuseu, para lá levantar um altar ao Senhor.

[[v13-21-19]]

^<<v13-21-19,19>>^ Davi lá subiu, de acordo com a ordem dada por Gad da parte do Senhor.

[[v13-21-20]]

^<<v13-21-20,20>>^ Ornã, voltando-se, viu o anjo e ele com seus quatro filhos esconderam-se: estava, naquela ocasião, debulhando trigo.

[[v13-21-21]]

^<<v13-21-21,21>>^ Quando Davi chegou perto de Ornã, este o viu; saiu da eira e se prostrou diante de Davi, com o rosto contra a terra.

[[v13-21-22]]

^<<v13-21-22,22>>^ Davi disse-lhe: “Cede-me o terreno de tua eira, para nela construir um altar ao Senhor. Cede-me o lugar pelo seu valor em dinheiro, para que o flagelo se retire de cima do povo”.

[[v13-21-23]]

^<<v13-21-23,23>>^ Ornã respondeu: “Toma-o; que meu senhor, o rei, faça o que lhe parecer bom. Vê, eu dou os bois para o holocausto, os carros para lenha e o trigo para a oblação; tudo te dou”.

[[v13-21-24]]

^<<v13-21-24,24>>^ “Não – respondeu Davi –, quero comprá-lo pelo seu inteiro valor em dinheiro; não tomarei o que te pertence para dar ao Senhor e não oferecerei um holocausto que não me custe nada.”

[[v13-21-25]]

^<<v13-21-25,25>>^ Davi deu a Ornã um peso de seiscentos siclos de ouro pelo terreno.^&#42;1^

[[v13-21-26]]

^<<v13-21-26,26>>^ E Davi construiu lá um altar ao Senhor; ofereceu holocaustos e sacrifícios pacíficos. Invocou o Senhor que lhe respondeu enviando fogo do céu sobre o altar dos holocaustos.

[[v13-21-27]]

^<<v13-21-27,27>>^ Então, o Senhor falou ao anjo e este embainhou de novo a espada.

[[v13-21-28]]

^<<v13-21-28,28>>^ Nesse momento, vendo Davi que o Senhor o tinha ouvido na eira de Ornã, o jebuseu, ofereceu ali sacrifícios.

[[v13-21-29]]

^<<v13-21-29,29>>^ O Tabernáculo do Senhor que Moisés construíra no deserto e o altar dos holocaustos se encontravam, nesse tempo, no lugar alto de Gabaon.

[[v13-21-30]]

^<<v13-21-30,30>>^ Mas Davi não pôde dirigir-se a esse altar para rogar a Deus, tão aterrado ficara ao ver a espada do anjo do Senhor.

'''

xref:013-i-cronicas/013-i-cronicas-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-022.adoc#v13-22-0[Próximo Capítulo &#62;]