include::./index.adoc[]

[[v13-27-0]]
=== I Crônicas, 27
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 Crônicas 27 lista os líderes dos exércitos de Israel, bem como os governadores das tribos e outras autoridades no reino de Davi. A seguir estão cinco versículos relacionados aos temas deste capítulo:
* 2 Samuel 23:8: "Estes são os nomes dos valentes de Davi: Jôabe, filho de Zeruia, chefe do exército; Eleazar, filho de Dodô, de Aoí; " Este versículo lista Jôabe como chefe do exército de Davi, o mesmo que é mencionado em 1 Crônicas 27:34.
* 1 Reis 4:1: "E o rei Salomão era rei sobre todo o Israel." Este versículo destaca a autoridade de Salomão sobre todo o reino de Israel, semelhante ao que é retratado na lista de governadores e autoridades em 1 Crônicas 27.
* Números 1:16: "Estes foram os que foram chamados das congregações, os príncipes das suas famílias, as cabeças das tribos de seus pais, que são os príncipes dos filhos de Israel." Este versículo menciona os príncipes das famílias e as cabeças das tribos de Israel, que são semelhantes aos líderes tribais e outras autoridades listados em 1 Crônicas 27.
* 2 Samuel 8:15: "Assim, Davi reinou sobre todo o Israel; e Davi fazia justiça e juízo a todo o seu povo." Este versículo destaca a justiça e o juízo de Davi sobre todo o povo de Israel, semelhante ao que é esperado dos governadores e outras autoridades em 1 Crônicas 27.
* Números 31:14: "E Moisés ficou indignado com os oficiais do exército, com os capitães de milhares e com os capitães de cem, que voltaram da guerra." Este versículo menciona oficiais do exército e capitães de milhares, semelhantes aos líderes militares listados em 1 Crônicas 27.
****

[[v13-27-1]]

^<<v13-27-1,1>>^ Israelitas, segundo o seu número, chefes de famílias, chefes de milhares e de centenas, oficiais a serviço do rei, para tudo que se referia às divisões chegando e partindo mensalmente, tendo cada divisão vinte e quatro mil homens.

[[v13-27-2]]

^<<v13-27-2,2>>^ À frente da primeira divisão, para o primeiro mês, achava-se Jesboam, filho de Zabdiel, e sua divisão era de vinte e quatro mil homens.

[[v13-27-3]]

^<<v13-27-3,3>>^ Ele era da linhagem de Farés e comandava todos os chefes de tropas do primeiro mês.

[[v13-27-4]]

^<<v13-27-4,4>>^ À frente da divisão do segundo mês, achava-se Dudi, o aoíta; Macelot era um dos chefes de sua divisão, que contava vinte e quatro mil homens.

[[v13-27-5]]

^<<v13-27-5,5>>^ O chefe da terceira divisão para o terceiro mês, era Banaías, filho do sacerdote-chefe Joiada, chefe; havia na sua divisão vinte e quatro mil homens.

[[v13-27-6]]

^<<v13-27-6,6>>^ Esse Banaías era um herói dos trinta e um chefe dos trinta; Amizabad, seu filho, era um chefe de sua divisão.

[[v13-27-7]]

^<<v13-27-7,7>>^ Para o quarto mês, havia Asael, irmão de Joab, a quem sucedeu seu filho Zabadias. A divisão contava vinte e quatro mil homens.

[[v13-27-8]]

^<<v13-27-8,8>>^ O quinto, para o quinto mês, era o chefe Samaot, o izraíta; e havia na sua divisão vinte e quatro mil homens.

[[v13-27-9]]

^<<v13-27-9,9>>^ O sexto, para o sexto mês, era Hira, filho de Aces, de Tícua; havia na sua divisão vinte e quatro mil homens.

[[v13-27-10]]

^<<v13-27-10,10>>^ O sétimo, para o sétimo mês, era Heles, o falonita, dos filhos de Efraim; sua divisão contava vinte e quatro mil homens.

[[v13-27-11]]

^<<v13-27-11,11>>^ O oitavo, para o oitavo mês, era Sobocai, o husatita, da família dos zaraítas; e sua divisão compreendia vinte e quatro mil homens.

[[v13-27-12]]

^<<v13-27-12,12>>^ O nono, para o nono mês, era Abiezer, de Anatot dos filhos de Benjamim; e sua divisão contava vinte e quatro mil homens.

[[v13-27-13]]

^<<v13-27-13,13>>^ O décimo, para o décimo mês, era Marai, de Netofa, da família dos zaraítas; e sua divisão contava vinte e quatro mil homens.

[[v13-27-14]]

^<<v13-27-14,14>>^ O décimo primeiro, para o décimo primeiro mês, era Banaías, de Faraton, dos filhos de Efraim; e sua divisão contava vinte e quatro mil homens.

[[v13-27-15]]

^<<v13-27-15,15>>^ O décimo segundo para o décimo segundo mês, era Holdai, de Netofa, da família de Otoniel; e sua divisão contava vinte e quatro mil homens.

[[v13-27-16]]

^<<v13-27-16,16>>^ Eis os chefes das tribos de Israel: chefes dos rubenitas: Eliezer, filho de Zecri; dos simeonitas: Safatias, filho de Maaca;

[[v13-27-17]]

^<<v13-27-17,17>>^ dos levitas: Hasabias, filho de Camuel; da família de Aarão: Sadoc;

[[v13-27-18]]

^<<v13-27-18,18>>^ de Judá: Eliú, irmão de Davi; de Issacar: Amri, filho de Miguel;

[[v13-27-19]]

^<<v13-27-19,19>>^ de Zabulon: Jesmaías, filho de Abdias; de Neftali: Jarmut, filho de Ozriel;

[[v13-27-20]]

^<<v13-27-20,20>>^ dos filhos de Efraim; Oseias, filho de Ozazias; da meia tribo de Manassés: Joel, filho de Fadaías;

[[v13-27-21]]

^<<v13-27-21,21>>^ da meia tribo de Manassés, em Galaad: Jado, filho de Zacarias; de Benjamim: Jasiel, filho de Abner;

[[v13-27-22]]

^<<v13-27-22,22>>^ de Dã: Ezriel, filho de Jeroam. Eram esses os chefes das tribos de Israel.^&#42;1^

[[v13-27-23]]

^<<v13-27-23,23>>^ Não fez Davi a relação daqueles que tinham vinte anos para baixo, porque o Senhor tinha prometido multiplicar Israel como as estrelas do céu.

[[v13-27-24]]

^<<v13-27-24,24>>^ Joab, filho de Sárvia, tinha começado o recenseamento, mas não terminou, porque a ira de Deus viera sobre Israel, por causa do recenseamento. E o número deles não foi relacionado nas crônicas do rei Davi.

[[v13-27-25]]

^<<v13-27-25,25>>^ Azmot, filho de Adiel, estava encarregado dos tesouros do rei; Jônatas, filho de Ozias, dos tesouros que havia nos campos, nas cidades, nas aldeias e nas torres;

[[v13-27-26]]

^<<v13-27-26,26>>^ Ezri, filho de Calub, era superintendente dos camponeses que cultivavam a terra;

[[v13-27-27]]

^<<v13-27-27,27>>^ Semei de Ramá, das vinhas; Zabdi, de Safão, das provisões de vinho nas vinhas;

[[v13-27-28]]

^<<v13-27-28,28>>^ Baalanã, de Gader, das oliveiras e sicômoros de Sefela;

[[v13-27-29]]

^<<v13-27-29,29>>^ Joás, das provisões de azeite; Setrai, de Sarona, dos bois que pastavam em Sarona; Safat, filho de Adli, dos bois dos vales;

[[v13-27-30]]

^<<v13-27-30,30>>^ Ubil, o ismaelita, dos camelos; Jadias, de Meranot, das jumentas;

[[v13-27-31]]

^<<v13-27-31,31>>^ Jaziz, o agareu, das ovelhas; eram esses os intendentes dos bens do rei Davi.

[[v13-27-32]]

^<<v13-27-32,32>>^ Jônatas, tio de Davi, exercia a função de conselheiro; era ele um homem prudente e sábio. Jaiel, filho de Hacamon, estava com os filhos do rei.

[[v13-27-33]]

^<<v13-27-33,33>>^ Aquitofel era conselheiro do rei e Cusai, o araquita, amigo do rei.

[[v13-27-34]]

^<<v13-27-34,34>>^ Depois de Aquitofel, vinham Joiada, filho de Banaías, e Abiatar. Joab era general do exército real.

'''

xref:013-i-cronicas/013-i-cronicas-026.adoc#v13-26-0[&#60; Capítulo Anterior] | <<v13-27-0,Topo>> | xref:013-i-cronicas/013-i-cronicas-028.adoc#v13-28-0[Próximo Capítulo &#62;]