include::./index.adoc[]

[[v67-5-0]]
=== I São Pedro, 5
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 5 de 1 São Pedro trata sobre a exortação aos presbíteros e ao rebanho de Deus, incentivando a humildade, o cuidado com o rebanho e a resistência contra o diabo. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Provérbios 3:34: "Certamente ele zomba dos zombadores, mas dá graça aos humildes." Este versículo destaca a importância da humildade, que é enfatizada no capítulo 5 de 1 São Pedro.
Isaías 40:11: "Como pastor ele cuida do seu rebanho. Com o seu braço ele ajunta os cordeirinhos e os carrega no colo; conduz suavemente as ovelhas que amamentam suas crias." Esse versículo fala sobre o cuidado de Deus pelo seu povo, o que também é uma exortação aos presbíteros para cuidarem bem do rebanho de Deus.
Atos 20:28: "Cuidem de si mesmos e de todo o rebanho sobre o qual o Espírito Santo os colocou como bispos, para pastorearem a igreja de Deus, que ele comprou com o seu próprio sangue." Esse versículo é semelhante ao tema abordado no capítulo 5 de 1 São Pedro, em que o apóstolo exorta os presbíteros a cuidarem do rebanho de Deus.
Tiago 4:7: "Portanto, submetam-se a Deus. Resistam ao Diabo, e ele fugirá de vocês." Este versículo destaca a importância de resistir ao diabo, o que também é mencionado no capítulo 5 de 1 São Pedro.
Efésios 6:11: "Vistam toda a armadura de Deus, para poderem ficar firmes contra as ciladas do Diabo." Esse versículo também fala sobre a resistência ao diabo, que é incentivada no capítulo 5 de 1 São Pedro.
****

[[v67-5-1]]

^<<v67-5-1,1>>^ Eis a exortação que dirijo aos anciãos que estão entre vós; porque sou ancião como eles, fui testemunha dos sofrimentos de Cristo e serei participante com eles daquela glória que se há de manifestar.^&#42;1^

[[v67-5-2]]

^<<v67-5-2,2>>^ Velai sobre o rebanho de Deus, que vos é confiado. Tende cuidado dele, não constrangidos, mas espontaneamente; não por amor de interesse sórdido, mas com dedicação;

[[v67-5-3]]

^<<v67-5-3,3>>^ não como dominadores absolutos sobre as comunidades que vos são confiadas, mas como modelos do vosso rebanho.

[[v67-5-4]]

^<<v67-5-4,4>>^ E, quando aparecer o supremo Pastor, recebereis a coroa imperecível de glória.

[[v67-5-5]]

^<<v67-5-5,5>>^ Semelhantemente, vós outros que sois mais jovens, sede submissos aos anciãos. Todos vós, em vosso mútuo tratamento, revesti-vos de humildade; porque Deus resiste aos soberbos, mas dá a sua graça aos humildes (Pr 3,34).

[[v67-5-6]]

^<<v67-5-6,6>>^ Humilhai-vos, pois, debaixo da poderosa mão de Deus, para que ele vos exalte no tempo oportuno.

[[v67-5-7]]

^<<v67-5-7,7>>^ Confiai-lhe todas as vossas preocupações, porque ele tem cuidado de vós.

[[v67-5-8]]

^<<v67-5-8,8>>^ Sede sóbrios e vigiai. Vosso adversário, o demônio, anda ao redor de vós como o leão que ruge, buscando a quem devorar.

[[v67-5-9]]

^<<v67-5-9,9>>^ Resisti-lhe fortes na fé. Vós sabeis que os vossos irmãos, que estão espalhados pelo mundo, sofrem os mesmos padecimentos que vós.

[[v67-5-10]]

^<<v67-5-10,10>>^ O Deus de toda graça, que vos chamou em Cristo à sua eterna glória, depois que tiverdes padecido um pouco, vos aperfeiçoará, vos tornará inabaláveis, vos fortificará.

[[v67-5-11]]

^<<v67-5-11,11>>^ A ele o poder na eternidade! Amém.

[[v67-5-12]]

^<<v67-5-12,12>>^ Por meio de Silvano, que estimo como a um irmão fiel, vos escrevi essas poucas palavras. Minha intenção é de admoestar-vos e assegurar-vos que essa é a verdadeira graça de Deus, na qual estais firmes.

[[v67-5-13]]

^<<v67-5-13,13>>^ A igreja escolhida da Babilônia saúda-vos, assim como também Marcos, meu filho.^&#42;1^

[[v67-5-14]]

^<<v67-5-14,14>>^ Saudai-vos uns aos outros com o ósculo afeuoso. A paz esteja com todos vós que estais em Cristo.

'''

xref:067-i-sao-pedro/067-i-sao-pedro-004.adoc#v67-4-0[&#60; Capítulo Anterior] | <<v67-5-0,Topo>> | xref:068-ii-sao-pedro/068-ii-sao-pedro-001.adoc#v68-1-0[Próximo Capítulo &#62;]