include::./index.adoc[]

[[v67-2-0]]
=== I São Pedro, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 1 São Pedro 2 trata do tema da identidade dos cristãos como pedras vivas da casa espiritual de Deus, edificados sobre a pedra angular, que é Jesus Cristo. Pedro encoraja seus leitores a rejeitar os valores mundanos e a viver como cidadãos do Reino de Deus. Aqui estão cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em 1 São Pedro 2:
* Efésios 2:19-20: "Assim, vocês já não são estrangeiros nem forasteiros, mas concidadãos dos santos e membros da família de Deus, edificados sobre o fundamento dos apóstolos e dos profetas, tendo Jesus Cristo como pedra angular." Este versículo destaca a conexão entre a família de Deus e a edificação da igreja sobre o fundamento apostólico e profético, com Jesus Cristo como a pedra angular.
* Salmos 118:22: "A pedra que os construtores rejeitaram tornou-se a pedra angular." Este salmo profético fala sobre a rejeição de Jesus pelos líderes religiosos de sua época, mas também antecipa sua exaltação como a pedra angular, que é central na edificação do Reino de Deus.
* Isaías 28:16: "Por isso, assim diz o Soberano, o Senhor: 'Veja, eu assentei em Sião uma pedra, uma pedra escolhida, uma preciosa pedra angular para o alicerce; aquele que confia não será perturbado'". Este versículo fala sobre a escolha de Deus de Jesus Cristo como a pedra angular da salvação, e como aqueles que confiam nele não serão abalados.
* Mateus 5:14: "Vocês são a luz do mundo. Não se pode esconder uma cidade construída sobre um monte". Neste versículo, Jesus fala sobre a identidade dos seus seguidores como luz do mundo, mostrando como o tema da identidade cristã como cidadãos do Reino de Deus é uma preocupação importante na Bíblia.
* Romanos 12:2: "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente, para que sejam capazes de experimentar e comprovar a boa, agradável e perfeita vontade de Deus". Este versículo destaca a importância de rejeitar os valores mundanos e renovar a mente para seguir a vontade de Deus, um tema central em 1 São Pedro 2.
****

[[v67-2-1]]

^<<v67-2-1,1>>^ Deponde, pois, toda malícia, toda astúcia, fingimentos, invejas e toda espécie de maledicência.

[[v67-2-2]]

^<<v67-2-2,2>>^ Como crianças recém-nascidas, desejai com ardor o leite espiritual que vos fará crescer para a salvação,

[[v67-2-3]]

^<<v67-2-3,3>>^ se é que tendes saboreado quão suave é o Senhor (Sl 33,9).

[[v67-2-4]]

^<<v67-2-4,4>>^ Achegai-vos a ele, pedra viva que os homens rejeitaram, mas escolhida e preciosa aos olhos de Deus;

[[v67-2-5]]

^<<v67-2-5,5>>^ e quais outras pedras vivas, vós também vos tornais os materiais deste edifício espiritual, um sacerdócio santo, para oferecer vítimas espirituais, agradáveis a Deus, por Jesus Cristo.

[[v67-2-6]]

^<<v67-2-6,6>>^ Por isso lê-se na Escritura: Eis que ponho em Sião uma pedra angular, escolhida, preciosa: quem nela puser sua confiança não será confundido (Is 28,16).

[[v67-2-7]]

^<<v67-2-7,7>>^ Para vós, portanto, que tendes crido, cabe a honra. Mas, para os incrédulos, a pedra que os edificadores rejeitaram tornou-se a pedra angular, uma pedra de tropeço, uma pedra de escândalo (Sl 117,22; Is 8,14).

[[v67-2-8]]

^<<v67-2-8,8>>^ Nela tropeçam porque não obedecem à palavra; e realmente era tal o seu destino.

[[v67-2-9]]

^<<v67-2-9,9>>^ Vós, porém, sois uma raça escolhida, um sacerdócio régio, uma nação santa, um povo adquirido para Deus, a fim de que publiqueis as virtudes daquele que das trevas vos chamou à sua luz maravilhosa.

[[v67-2-10]]

^<<v67-2-10,10>>^ Vós que outrora não éreis seu povo, mas agora sois povo de Deus; vós que outrora não tínheis alcançado misericórdia (Os 2,25), mas agora alcançastes misericórdia.

[[v67-2-11]]

^<<v67-2-11,11>>^ Caríssimos, rogo-vos que, como estrangeiros e peregrinos, vos abstenhais dos desejos da carne, que combatem contra a alma.

[[v67-2-12]]

^<<v67-2-12,12>>^ Comportai-vos nobremente entre os pagãos. Assim, naquilo em que vos caluniam como malfeitores, chegarão, considerando vossas boas obras, a glorificar a Deus no dia em que ele os visitar.

[[v67-2-13]]

^<<v67-2-13,13>>^ Por amor do Senhor, sede submissos, pois, a toda autoridade humana,

[[v67-2-14]]

^<<v67-2-14,14>>^ quer ao rei como a soberano, quer aos governadores como enviados por ele para castigo dos malfeitores e para favorecer as pessoas honestas.

[[v67-2-15]]

^<<v67-2-15,15>>^ Porque esta é a vontade de Deus que, praticando o bem, façais emudecer a ignorância dos insensatos.

[[v67-2-16]]

^<<v67-2-16,16>>^ Comportai-vos como homens livres, e não à maneira dos que tomam a liberdade como véu para encobrir a malícia, mas vivendo como servos de Deus.

[[v67-2-17]]

^<<v67-2-17,17>>^ Sede educados para com todos, amai os irmãos, temei a Deus, respeitai o rei.

[[v67-2-18]]

^<<v67-2-18,18>>^ Servos, sede obedientes aos senhores com todo o respeito, não só aos bons e moderados, mas também aos de caráter difícil.

[[v67-2-19]]

^<<v67-2-19,19>>^ Com efeito, é coisa agradável a Deus sofrer contrariedades e padecer injustamente, por motivo de consciência para com Deus.^&#42;1^

[[v67-2-20]]

^<<v67-2-20,20>>^ Que mérito teria alguém se suportasse pacientemente os açoites por ter praticado o mal? Ao contrário, se é por ter feito o bem que sois maltratados, e se o suportardes pacientemente, isso é coisa agradável aos olhos de Deus.

[[v67-2-21]]

^<<v67-2-21,21>>^ Ora, é para isso que fostes chamados. Também Cristo padeceu por vós, deixando-vos exemplo para que sigais os seus passos.

[[v67-2-22]]

^<<v67-2-22,22>>^ Ele não cometeu pecado, nem se achou falsidade em sua boca (Is 53,9).

[[v67-2-23]]

^<<v67-2-23,23>>^ Ele, ultrajado, não retribuía com idêntico ultraje; ele, maltratado, não proferia ameaças, mas entregava-se àquele que julga com justiça.

[[v67-2-24]]

^<<v67-2-24,24>>^ Carregou os nossos pecados em seu corpo sobre o madeiro para que, mortos aos nossos pecados, vivamos para a justiça. Por fim, por suas chagas fomos curados (Is 53,5).

[[v67-2-25]]

^<<v67-2-25,25>>^ Porque éreis como ovelhas desgarradas, mas agora retornastes ao Pastor e guarda das vossas almas.

'''

xref:067-i-sao-pedro/067-i-sao-pedro-001.adoc#v67-1-0[&#60; Capítulo Anterior] | <<v67-2-0,Topo>> | xref:067-i-sao-pedro/067-i-sao-pedro-003.adoc#v67-3-0[Próximo Capítulo &#62;]