include::./index.adoc[]

[[v30-35-0]]
=== Jeremias, 35
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jeremias 35 narra a história dos Recabitas, uma família que havia se comprometido a seguir os mandamentos de seu ancestral Jonadabe. Deus usa a fidelidade dos Recabitas como um exemplo para o povo de Judá, que havia se afastado Dele. Os versículos relacionados aos temas deste capítulo são:
* Êxodo 20:12: "Honra teu pai e tua mãe, a fim de que tenhas vida longa na terra que o Senhor,o teu Deus, te dá." Os Recabitas honraram e obedeceram a seu ancestral, Jonadabe, demonstrando respeito pelas tradições e ensinamentos de seus antepassados.
* Provérbios 20:7: "O justo anda na sua integridade; felizes são seus filhos depois dele." Os Recabitas foram recompensados pela sua fidelidade e integridade, sendo prometido a eles que sempre teriam descendentes.
* Neemias 8:1-3: Este capítulo conta sobre a leitura pública da lei de Deus e como as pessoas a ouviram e entenderam. Os Recabitas também mantiveram a tradição oral de sua família e obedeceram a ela com diligência.
* Mateus 7:21: "Nem todo aquele que me diz: 'Senhor, Senhor', entrará no Reino dos céus, mas apenas aquele que faz a vontade de meu Pai que está nos céus." Os Recabitas foram fiéis à vontade de seu ancestral, mostrando que a obediência é mais importante do que simplesmente dizer as palavras certas.
* Atos 5:29: "Pedro e os outros apóstolos responderam: 'É preciso obedecer antes a Deus do que aos homens!'" Os Recabitas escolheram obedecer a Deus e às tradições de sua família, mesmo que isso significasse desobedecer ao rei de Judá.
****

[[v30-35-1]]

^<<v30-35-1,1>>^ Eis a palavra que foi dirigida pelo Senhor a Jeremias, no tempo de Joaquin, filho de Josias, rei de Judá:

[[v30-35-2]]

^<<v30-35-2,2>>^ “Vai procurar a família dos recabitas para falar com eles. Em seguida, tu os conduzirás a uma das salas do templo, onde lhes oferecerás vinho para beber”.^&#42;1^

[[v30-35-3]]

^<<v30-35-3,3>>^ Fui, então, à procura de Jezonias, filho de Habsanias, seus irmãos e filhos, e toda a família dos recabitas,

[[v30-35-4]]

^<<v30-35-4,4>>^ e os conduzi ao templo, à sala dos filhos de Joanã, filho de Jegdalias, homem de Deus, perto da sala dos chefes, acima da de Maasias, filho de Selum, guarda do vestíbulo.^&#42;1^

[[v30-35-5]]

^<<v30-35-5,5>>^ Coloquei diante deles um vaso cheio de vinho e taças, e lhes disse: “Bebei este vinho!”.

[[v30-35-6]]

^<<v30-35-6,6>>^ Responderam eles, porém: “Não bebemos vinho, pois que Jonadab, filho de Recab, e nosso avô, assim nos prescreveu: Jamais bebereis vinho, vós e vossos filhos.

[[v30-35-7]]

^<<v30-35-7,7>>^ Não construireis casa, não semeareis, não plantareis nem possuireis vinhas, mas habitareis sempre em tendas, a fim de que, por muito tempo, possais viver em uma terra onde permanecereis como estrangeiros.

[[v30-35-8]]

^<<v30-35-8,8>>^ Observamos a ordem de Jonadab, filho de Recab, nosso avô, em todos os pontos: abstemo-nos de vinho em todos os nossos dias, nós, nossas mulheres, nossos filhos e filhas;

[[v30-35-9]]

^<<v30-35-9,9>>^ não construímos casa para habitar nelas, não possuímos vinhas, nem campos de sementeiras,

[[v30-35-10]]

^<<v30-35-10,10>>^ vivendo debaixo de tendas. Assim, em tudo temos obedecido ao que nosso avô Jonadab nos prescreveu.

[[v30-35-11]]

^<<v30-35-11,11>>^ Quando, porém, Nabucodonosor, rei da Babilônia, invadiu a terra, uns aos outros dissemos: Vinde e entremos em Jerusalém, a fim de escapar do exército dos caldeus e da Síria. Eis a razão por que nos encontramos em Jerusalém”.

[[v30-35-12]]

^<<v30-35-12,12>>^ Foi, então, dirigida assim a Jeremias a palavra do Senhor:

[[v30-35-13]]

^<<v30-35-13,13>>^ “Eis o que diz o Senhor dos exércitos, Deus de Israel: Vai e dize ao povo de Judá e aos habitantes de Jerusalém: Não aceitareis a minha admoestação e não obedecereis à minha palavra? – oráculo do Senhor. –

[[v30-35-14]]

^<<v30-35-14,14>>^ São observadas as ordens de Jonadab, filho de Recab, que proibiu a seus filhos beberem vinho. Abstiveram-se de beber, a fim de se conformarem com a ordem de seu pai. E a mim, que não cesso de vos falar, não me escutais.

[[v30-35-15]]

^<<v30-35-15,15>>^ Sem descanso, enviei-vos desde o princípio os profetas, meus servos, para dizer-vos: Desviai-vos do mau caminho e reformai a vossa vida. Não andeis a correr atrás de deuses estranhos para lhes render culto. Ficareis, então, na terra que vos dei, a vós e a vossos pais. Não destes, porém, ouvidos, nem obedecestes.

[[v30-35-16]]

^<<v30-35-16,16>>^ Os filhos de Jonadab, filho de Recab, respeitam as prescrições de seus pais, mas esse povo não me escuta!

[[v30-35-17]]

^<<v30-35-17,17>>^ Eis por que, assim diz o Senhor dos exércitos, Deus de Israel, vou lançar sobre Judá e os habitantes de Jerusalém os flagelos de que os ameacei, porquanto lhes falei e não me escutaram, e quando os chamei não me responderam”.

[[v30-35-18]]

^<<v30-35-18,18>>^ A seguir, disse Jeremias à família dos recabitas: “Eis o que diz o Senhor dos exércitos, Deus de Israel: Já que obedecestes à ordem do vosso pai Jonadab, e observastes tudo o que vos prescreveu,

[[v30-35-19]]

^<<v30-35-19,19>>^ promete-vos o Senhor dos exércitos, Deus de Israel, que a Jonadab, filho de Recab, não faltarão descendentes que se hão de conservar na minha presença”.^&#42;1^

'''

xref:030-jeremias/030-jeremias-034.adoc#v30-34-0[&#60; Capítulo Anterior] | <<v30-35-0,Topo>> | xref:030-jeremias/030-jeremias-036.adoc#v30-36-0[Próximo Capítulo &#62;]