include::./index.adoc[]

[[v30-40-0]]
=== Jeremias, 40
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jeremias 40 descreve como o governador da Babilônia, Nabuzaradã, designa Gedalias como governador de Judá após a queda de Jerusalém. Gedalias convida os judeus que haviam fugido para se juntarem a ele em Mizpá, mas um dos líderes, Ismael, conspira contra ele e o mata, levando os habitantes de Mizpá como prisioneiros. Seguem abaixo cinco versículos relacionados com os temas abordados em Jeremias 40:
* 2 Reis 25:22-24: "Então o rei da Babilônia nomeou Gedalias, filho de Aicam, filho de Safã, governador sobre a terra, e confiou-lhe os homens, mulheres e crianças do povo que não haviam sido levados para o exílio na Babilônia. Gedalias jurou perante eles que iria protegê-los e incentivou-os a trabalhar na terra e a obedecer aos caldeus que haviam sido deixados para administrar a região." Este versículo descreve a nomeação de Gedalias como governador por Nabuzaradã.
* Jeremias 39:14: "Gedalias, filho de Aicam, neto de Safã, veio a eles e lhes jurou que não precisavam ter medo dos caldeus que haviam ficado na Babilônia, mas que deveriam se submeter a eles e viver em paz na terra." Este versículo mostra como Gedalias tenta tranquilizar os judeus que haviam fugido e os convida para se juntarem a ele em Mizpá.
* Jeremias 40:7: "Ouvindo todos os comandantes do exército que estavam no campo, eles e os seus homens, que o rei da Babilônia havia nomeado Gedalias, filho de Aicam, governador do país, e que havia confiado a ele homens, mulheres e crianças, dos mais pobres da terra que não haviam sido levados para o exílio na Babilônia," Este versículo mostra como Gedalias é reconhecido como governador pelos líderes do exército.
* Jeremias 41:2: "Ismael, filho de Netanias, e os dez homens que estavam com ele levantaram-se e atacaram Gedalias, filho de Aicam, neto de Safã, matando-o com a espada, juntamente com os caldeus que estavam com ele em Mizpá." Esse versículo descreve o assassinato de Gedalias por Ismael.
* Jeremias 41:10: "Então todo o povo, desde o menor até o maior, e os comandantes do exército, fugiram e foram para o Egito, com medo dos caldeus." Este versículo mostra como os judeus fogem para o Egito após o assassinato de Gedalias, temendo a represália dos babilônios.
****

[[v30-40-1]]

^<<v30-40-1,1>>^ Eis a palavra do Senhor que foi dirigida a Jeremias, depois que Nebuzardã, chefe dos guardas, mandou trazê-lo de Ramá, onde o encontrara carregado de ferros, entre os deportados de Jerusalém e de Judá que eram conduzidos para a Babilônia.

[[v30-40-2]]

^<<v30-40-2,2>>^ Mandou o chefe dos guardas que trouxessem Jeremias e lhe disse: “Havia predito o Senhor, teu Deus, a calamidade que caiu sobre este lugar.

[[v30-40-3]]

^<<v30-40-3,3>>^ Ele a fez vir, fez como havia anunciado; e porque pecastes contra ele e não lhe escutastes a voz, tudo isso aconteceu.

[[v30-40-4]]

^<<v30-40-4,4>>^ Pois bem, agora tiro-te dos grilhões que te prendem as mãos. Se te agradar, vem comigo para a Babilônia; velarei por ti. Se, porém, preferes ficar, deixa. Vê: toda essa terra está ao teu dispor; podes ir para onde melhor te parecer”.

[[v30-40-5]]

^<<v30-40-5,5>>^ (Ele, porém, ainda não se voltava.) “Volta para Godolias, filho de Aicam, filho de Safã, nomeado pelo rei da Babilônia para governador das cidades de Judá, e vai morar com ele no meio do povo, ou aonde melhor te aprouver.” Deu-lhe, então, o chefe dos guardas víveres e presentes, e o deixou ir.

[[v30-40-6]]

^<<v30-40-6,6>>^ Jeremias foi para junto de Godolias, filho de Aicam, em Masfa, e com ele permaneceu entre o povo que havia deixado na terra.

[[v30-40-7]]

^<<v30-40-7,7>>^ Ante a notícia de que o rei da Babilônia nomeara governador da terra Godolias, filho de Aicam, e lhe confiara homens, mulheres, crianças e pobres que não haviam sido deportados, vieram os chefes das tropas, que se tinham dispersado pela terra,

[[v30-40-8]]

^<<v30-40-8,8>>^ procurar o governador, com seus companheiros, em Masfa. Eram eles, Ismael, filho de Natanias, Joanã e Jônatas, filhos de Carea, Sareas, filho de Teneumet, os filhos de Ofi, de Netofa, e Jesonias, filho de Maacati, e suas gentes.

[[v30-40-9]]

^<<v30-40-9,9>>^ Godolias, filho de Aicam, filho de Safã, declarou-lhes sob juramento: “Não tenhais receio de servir aos caldeus. Ficai na terra submissos ao rei da Babilônia, e nada vos acontecerá.

[[v30-40-10]]

^<<v30-40-10,10>>^ Ficarei em Masfa para estar às ordens dos caldeus que para aqui vierem. Recolhei, pois, o vinho, as frutas e o óleo, fazendo deles provisão. E instalai-vos nas cidades para onde voltais”.

[[v30-40-11]]

^<<v30-40-11,11>>^ Sabendo, a seu turno, que o rei da Babilônia deixara em Judá o resto do povo, sob as ordens de Godolias, filho de Aicam, filho de Safã, todos os judeus, que estavam em Moab e entre os filhos de Amon, ou em Edom e nas demais regiões,

[[v30-40-12]]

^<<v30-40-12,12>>^ deixaram esses lugares por onde andavam dispersos e vieram à terra de Judá para junto de Godolias, em Masfa, e lá fizeram abundante colheita de vinho e de frutos.

[[v30-40-13]]

^<<v30-40-13,13>>^ Joanã, filho de Carea, e todos os chefes de tropas, disseminados pelas províncias, vieram procurar Godolias em Masfa.

[[v30-40-14]]

^<<v30-40-14,14>>^ “Sabes” – disseram-lhe então – “que Baalis, rei dos filhos de Amon, encarregou Ismael, filho de Natanias, de tirar-te a vida?” Não quis, porém, Godolias acreditar nisso.

[[v30-40-15]]

^<<v30-40-15,15>>^ Então Joanã, filho de Carea, tomou à parte Godolias, em Masfa, e lhe disse: “E se eu fosse matar Ismael, filho de Natanias, sem que pessoa alguma o soubesse? Por que permitir que te matem? Seria isso a dispersão de todos os judeus que se reuniram em torno de ti e o aniquilamento do que resta de Judá”.

[[v30-40-16]]

^<<v30-40-16,16>>^ Godolias, filho de Aicam, disse porém a Joanã, filho de Carea: “Não faças isso. É falso o que dizes de Ismael”.

'''

xref:030-jeremias/030-jeremias-039.adoc#v30-39-0[&#60; Capítulo Anterior] | <<v30-40-0,Topo>> | xref:030-jeremias/030-jeremias-041.adoc#v30-41-0[Próximo Capítulo &#62;]