include::./index.adoc[]

[[v30-3-0]]
=== Jeremias, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jeremias 3 fala sobre a infidelidade do povo de Israel em relação a Deus e a necessidade de se arrepender e voltar para Ele. O capítulo descreve a situação de Israel como uma esposa infiel que abandona o marido para seguir outros amantes. Abaixo estão cinco versículos relacionados com os temas abordados em Jeremias 3.
* Oséias 6:1: "Venham, voltemos para o Senhor. Ele nos despedaçou, mas nos trará cura; ele nos feriu, mas cuidará de nossas feridas." Este versículo mostra a necessidade de Israel se arrepender e voltar para o Senhor, acreditando que Ele pode curar as feridas causadas pela infidelidade.
* Ezequiel 18:30: "Portanto, ó nação de Israel, eu os julgarei, a cada um conforme o seu caminho, declara o Soberano, o Senhor. Arrependam-se! Afastem-se de todos os seus pecados; então a iniquidade deles não será a sua ruína." Esse versículo destaca a importância do arrependimento e da mudança de vida para evitar a ruína causada pelo pecado.
* Oséias 14:1: "Volte, ó Israel, para o Senhor, o seu Deus. Seus pecados os fizeram tropeçar." Aqui, novamente, vemos a exortação para Israel voltar para o Senhor e abandonar o pecado.
* Joel 2:13: "Rasguem o coração e não as vestes. Voltem-se para o Senhor, o seu Deus, pois ele é misericordioso e compassivo, muito paciente e cheio de amor; arrepende-se, ele não envia a desgraça." Este versículo enfatiza a necessidade de um arrependimento sincero do coração e da confiança na misericórdia de Deus.
* Deuteronômio 30:2: "Então, se voltarem para o Senhor, o seu Deus, e lhe obedecerem de todo o coração e de toda a alma, conforme tudo o que hoje lhes ordeno, o Senhor, o seu Deus, os abençoará." Esse versículo mostra que a bênção de Deus vem para aqueles que se arrependem e obedecem a Ele de todo o coração.
****

[[v30-3-1]]

^<<v30-3-1,1>>^ A palavra do Senhor foi-me dirigida nestes termos: “Se um homem repudia a mulher, e ela o abandona para tornar-se mulher de outro, tornará o marido a recebê-la? Não ficará esta terra gravemente profanada? E tu, após haveres pecado com inúmeros amantes, voltarás para mim? – oráculo do Senhor.

[[v30-3-2]]

^<<v30-3-2,2>>^ Ergue os olhos para os lugares altos e vê: onde não te prostituíste? Sentavas à beira dos caminhos a espreitá-los, qual árabe no deserto; e profanaste a terra com teus vícios e devassidões.

[[v30-3-3]]

^<<v30-3-3,3>>^ Assim foram-te as chuvas recusadas, e as águas da primavera não caíram; tu, porém, com semblante lascivo, não quiseste envergonhar-te.

[[v30-3-4]]

^<<v30-3-4,4>>^ E agora clamas: ‘Pai, amigo de minha juventude!

[[v30-3-5]]

^<<v30-3-5,5>>^ Ficará ele para sempre irritado? E guardará de mim eterno rancor?’. Eis o que dizes, ainda que persistindo em praticar o mal”.

[[v30-3-6]]

^<<v30-3-6,6>>^ No tempo do rei Josias, disse-me o Senhor: “Viste o que fez Israel, a Revoltada? Andou pelas montanhas altaneiras e sob as árvores verdejantes, para entregar-se à prostituição.^&#42;1^

[[v30-3-7]]

^<<v30-3-7,7>>^ E eu pensei comigo mesmo: depois de haver cometido todos esses crimes, ela voltará para mim... Porém, não voltou! Soube disso sua irmã, a Pérfida Judá.

[[v30-3-8]]

^<<v30-3-8,8>>^ E viu como repudiei a Revoltada Israel e lhe concedi a carta de divórcio, em razão de seus adultérios. Contudo, sua irmã, a Pérfida Judá, não se atemorizou, mas também ela se tornou prostituta!^&#42;1^

[[v30-3-9]]

^<<v30-3-9,9>>^ E com sua ardente luxúria maculou a terra, adulterando-se com a pedra e com a madeira.

[[v30-3-10]]

^<<v30-3-10,10>>^ Não obstante tudo isso, sua irmã, a Pérfida Judá, não voltou para mim na inteireza do seu coração. Era apenas hipocrisia” – oráculo do Senhor.^&#42;1^

[[v30-3-11]]

^<<v30-3-11,11>>^ Disse-me em seguida o Senhor: “A Revoltada Israel afigura-se inocente em face da Pérfida Judá. Arrependimento do povo eleito

[[v30-3-12]]

^<<v30-3-12,12>>^ Vai, inclina-te para o norte e profere em altas vozes: volta, Israel, Revoltada – oráculo do Senhor; não te mostrarei mais um semblante enfurecido, pois que sou benigno – oráculo do Senhor; não guardo rancor eterno.

[[v30-3-13]]

^<<v30-3-13,13>>^ Reconhece apenas a tua falta; foste infiel ao Senhor, teu Deus; vagaste à procura de (deuses) estrangeiros sob todas as árvores verdejantes; não escutaste minha voz – oráculo do Senhor.

[[v30-3-14]]

^<<v30-3-14,14>>^ Voltai, filhos rebeldes – oráculo do Senhor –, pois que sou vosso Senhor. Eu vos tomarei, um de cada cidade e dois de cada família e vos reconduzirei a Sião.

[[v30-3-15]]

^<<v30-3-15,15>>^ Eu vos darei pastores segundo o meu coração, os quais vos apascentarão com inteligência e sabedoria.

[[v30-3-16]]

^<<v30-3-16,16>>^ Quando vos multiplicardes e numerosos vos tornardes na terra, naqueles dias – oráculo do Senhor – não mais se falará da arca da aliança do Senhor; nem mais se pensará nela, perdendo-se a lembrança e a saudade; nem a ela se há de referir.^&#42;1^

[[v30-3-17]]

^<<v30-3-17,17>>^ Naquele tempo, Jerusalém será chamada trono do Senhor e todas as nações lá se reunirão em nome do Senhor, sem mais persistir na obstinação do seu coração perverso.

[[v30-3-18]]

^<<v30-3-18,18>>^ Naqueles dias, a casa de Judá se unirá à de Israel, e das regiões do norte voltarão juntas à terra, cuja posse concedi a seus pais”.

[[v30-3-19]]

^<<v30-3-19,19>>^ “Que lugar” – dissera eu – “vou conceder-te entre meus filhos, que terra de delícias vou dar-te como herança, a mais bela joia das nações! E eu acrescentara: Tu me chamarás: meu pai, e não te desviarás de mim.

[[v30-3-20]]

^<<v30-3-20,20>>^ Mas, qual a mulher que trai aquele que a ama, assim me traíste, casa de Israel – oráculo do Senhor.

[[v30-3-21]]

^<<v30-3-21,21>>^ Nas colinas ressoa um clamor: suspiros de súplica dos israelitas, porque seguiram caminhos tortuosos, esquecendo-se do Senhor, seu Deus.

[[v30-3-22]]

^<<v30-3-22,22>>^ Voltai, filhos rebeldes, e eu sanarei as consequências de vossas revoltas. Aqui estamos dizeis, voltamos para vós, porque sois o Senhor, nosso Deus.”

[[v30-3-23]]

^<<v30-3-23,23>>^ Em verdade, é ilusório o culto nas colinas, as festas tumultuosas nas montanhas; é realmente no Senhor, nosso Deus, que se encontra a salvação de Israel.

[[v30-3-24]]

^<<v30-3-24,24>>^ O ídolo infame devora, desde nossa juventude, o produto do labor de nossos pais, o gado e os rebanhos, seus filhos e suas filhas.

[[v30-3-25]]

^<<v30-3-25,25>>^ Deitemo-nos em nossa vergonha, e que nos sirva de coberta nossa ignomínia, pois pecamos, nós e nossos pais, desde a juventude até o dia de hoje, contra o Senhor, nosso Deus, e não escutamos a voz do Senhor, nosso Deus.^&#42;1^

'''

xref:030-jeremias/030-jeremias-002.adoc#v30-2-0[&#60; Capítulo Anterior] | <<v30-3-0,Topo>> | xref:030-jeremias/030-jeremias-004.adoc#v30-4-0[Próximo Capítulo &#62;]