include::./index.adoc[]

[[v30-51-0]]
=== Jeremias, 51
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 51 de Jeremias fala sobre a queda e a destruição da Babilônia, que será punida por Deus por causa de sua arrogância e crueldade. O profeta Jeremias é enviado para proclamar a destruição da Babilônia e encorajar o povo de Deus a sair da cidade antes que seja tarde demais. Aqui estão cinco versículos relacionados com os temas abordados em Jeremias 51:
* Isaías 44:27: "Eu sou aquele que diz a respeito de Ciro: 'Ele é meu pastor e realizará tudo o que me agrada; ele dirá de Jerusalém: "Seja reconstruída", e do templo: "Sejam lançados os seus alicerces"." Este versículo fala da profecia de Deus sobre Ciro, o rei persa que irá derrotar a Babilônia e permitir que o povo de Deus retorne a Jerusalém e reconstrua o templo.
* Apocalipse 18:4: "Então ouvi outra voz dos céus que dizia: 'Saiam dela, povo meu, para que vocês não participem dos seus pecados e não sofram das suas pragas.'" Este versículo fala da chamada de Deus para o seu povo sair da Babilônia antes que seja tarde demais e sofram a punição divina.
* Salmos 137:8-9: "Filha da Babilônia, destinada à destruição, feliz aquele que te retribuir o mal que nos fizeste. Feliz aquele que pegar teus filhos e os esmagar contra as pedras!" Este versículo fala da justiça divina que será feita com a Babilônia por causa de sua crueldade e opressão ao povo de Deus.
* Isaías 13:19: "A Babilônia, joia dos reinos, glória e orgulho dos caldeus, será como Sodoma e Gomorra, quando Deus as destruiu." Este versículo fala da queda da Babilônia, que será punida por sua arrogância e pecados contra Deus.
* Jeremias 50:46: "Ouçam o grito da Babilônia; o som de grande destruição vem da terra dos caldeus." Este versículo fala da destruição iminente da Babilônia e do clamor que será ouvido por toda a terra.
****

[[v30-51-1]]

^<<v30-51-1,1>>^ Eis o que declara o Senhor: “Vou levantar contra a Babilônia e seus cidadãos de Lebcamai um vento de destruição.^&#42;1^

[[v30-51-2]]

^<<v30-51-2,2>>^ Vou enviar para a Babilônia cesteiros que a irão joeirar, e que lhe deixarão vazia a terra, porque, no dia da desgraça, de todos os lados cairão sobre ela.

[[v30-51-3]]

^<<v30-51-3,3>>^ Que o arqueiro não retese seu arco contra o arqueiro nem se pavoneie em sua couraça. Não lhe poupeis a mocidade; exterminai todo o seu exército”.

[[v30-51-4]]

^<<v30-51-4,4>>^ Caiam eles, feridos de morte, na terra dos caldeus, e transpassados nas ruas da Babilônia!

[[v30-51-5]]

^<<v30-51-5,5>>^ Porque Israel e Judá não enviuvaram do seu Deus, o Senhor dos exércitos, se bem que sejam terras cheias de crimes contra o Santo de Israel.

[[v30-51-6]]

^<<v30-51-6,6>>^ Fugi para longe do recinto da Babilônia; que cada um salve a vida e não pereça nos seus crimes, pois chegado é o tempo da vingança do Senhor que lhe vai dar o que mereceu.

[[v30-51-7]]

^<<v30-51-7,7>>^ Era a Babilônia na mão do Senhor qual taça de ouro que embriagava toda a terra; bebiam as nações o seu vinho e enlouqueciam.

[[v30-51-8]]

^<<v30-51-8,8>>^ Caiu, porém, de repente, a Babilônia: está esmagada. Chorai sobre ela! Ide à procura de um bálsamo para a sua ferida; talvez venha a curar-se.

[[v30-51-9]]

^<<v30-51-9,9>>^ “Tentamos curar a Babilônia, mas em vão. Deixai-a! Vamos cada qual para sua terra. Atingem o céu as suas faltas, sobem tão alto quanto as nuvens.

[[v30-51-10]]

^<<v30-51-10,10>>^ Pôs o Senhor em evidência a justiça de nossa causa. Vinde, a fim de que narremos em Sião a obra do Senhor, nosso Deus!”.

[[v30-51-11]]

^<<v30-51-11,11>>^ Aguçai vossas flechas! Colocai vossos escudos! Excitou o Senhor o espírito dos reis dos medos, terra que deseja destruir a Babilônia. É a vingança do Senhor, a vingança do seu templo.

[[v30-51-12]]

^<<v30-51-12,12>>^ Levantai bandeira sobre os muros da Babilônia! Reforçai a guarda! Colocai sentinelas! Armai emboscadas! Porque o Senhor executa o plano que concebeu, a ameaça que proferiu contra os babilônicos.

[[v30-51-13]]

^<<v30-51-13,13>>^ Tu que te assentas sobre as grandes águas, e que possuis imensos tesouros, chegou teu fim. Acabaram-se as tuas rapinas.

[[v30-51-14]]

^<<v30-51-14,14>>^ Jurou-o o Senhor dos exércitos, por si mesmo: “Eu te encherei de homens tão numerosos como gafanhotos, que lançarão gritos triunfantes sobre ti”.

[[v30-51-15]]

^<<v30-51-15,15>>^ Criou ele a terra por seu poderio; firmou o mundo com a sua sabedoria, e em sua inteligência estendeu os céus.^&#42;1^

[[v30-51-16]]

^<<v30-51-16,16>>^ Ao som de sua voz acumularam-se as águas nos céus; dos confins da terra faz subirem as nuvens, resolve em chuvas os relâmpagos, e de seus reservatórios tira os ventos.

[[v30-51-17]]

^<<v30-51-17,17>>^ Atônitos ficam, então, os homens. Envergonha-se o artífice da estátua que modelou, porque os ídolos que fundiu não passam de mentiras, e não possuem vida.

[[v30-51-18]]

^<<v30-51-18,18>>^ São apenas vãos simulacros, que se desvanecerão no dia do castigo.

[[v30-51-19]]

^<<v30-51-19,19>>^ O mesmo não acontecerá àquele que é a herança de Jacó, pois ele criou tudo, e Israel é a tribo do seu patrimônio. Seu nome é Javé dos exércitos.

[[v30-51-20]]

^<<v30-51-20,20>>^ És para mim um martelo, uma arma de guerra. Por teu intermédio esmago nações, aniquilo reinos^&#42;1^

[[v30-51-21]]

^<<v30-51-21,21>>^ e destruo o cavalo e o cavaleiro, o carro e o cocheiro;

[[v30-51-22]]

^<<v30-51-22,22>>^ por meio de ti despedaço homens e mulheres, velhos e crianças e quebranto o jovem e a jovem.

[[v30-51-23]]

^<<v30-51-23,23>>^ Por tuas mãos exterminarei pastores e rebanhos, lavradores e suas juntas, governantes e magistrados.

[[v30-51-24]]

^<<v30-51-24,24>>^ Mas à Babilônia e aos caldeus retribuirei, ante vossos olhos, todo o mal que fizeram a Sião – oráculo do Senhor.

[[v30-51-25]]

^<<v30-51-25,25>>^ É contra ti que me lanço, monte destruidor – oráculo do Senhor –, tu que destróis toda a terra; contra ti vou estender a mão, para precipitar-te do alto dos rochedos, e fazer de ti montanha em chamas.

[[v30-51-26]]

^<<v30-51-26,26>>^ De teus escombros não se poderá tirar pedra de ângulo, nem pedra de alicerce, porque te hás de transformar em eterna ruína – oráculo do Senhor.

[[v30-51-27]]

^<<v30-51-27,27>>^ Por toda a terra erguei o estandarte, tocai a trombeta entre as nações. E contra ela uni os povos em guerra santa, mobilizai os reinos de Ararat, de Meni e Asquenez! Contra ela nomeai escribas recrutadores, e lançai os cavalos, quais gafanhotos eriçados.

[[v30-51-28]]

^<<v30-51-28,28>>^ Recrutai contra ela os povos em guerra santa, os reis da Média, seus governadores e oficiais, e todas as terras de seu domínio.

[[v30-51-29]]

^<<v30-51-29,29>>^ Treme a terra e se turba, porque se cumpre a ameaça do Senhor, contra a Babilônia, de reduzir a terra da Babilônia a um lugar ermo e de horror.

[[v30-51-30]]

^<<v30-51-30,30>>^ Deixaram de lutar os guerreiros da Babilônia, abrigando-se nas fortalezas. Quebrou-se o seu vigor, mais pareciam mulheres. Incendiaram-se as casas, quebraram-se os ferrolhos.

[[v30-51-31]]

^<<v30-51-31,31>>^ Surgem correio sobre correio, mensageiros sobre mensageiros, anunciando ao rei da Babilônia que toda a cidade se acha cercada,

[[v30-51-32]]

^<<v30-51-32,32>>^ que estão fechadas as passagens e os fortins em fogo, e consternados os guerreiros.

[[v30-51-33]]

^<<v30-51-33,33>>^ Porque eis o que falou o Senhor dos exércitos, Deus de Israel: “Assemelha-se a filha da Babilônia à eira do tempo do apisoamento, ainda por um pouco, e para ela logo virá o tempo da colheita.

[[v30-51-34]]

^<<v30-51-34,34>>^ Tragou-me, partiu-me Nabucodonosor, rei da Babilônia, deixou-me qual vaso vazio. Engoliu-me, como o faria um dragão, enchendo o ventre do que de melhor eu possuía, e expulsou-me”.^&#42;1^

[[v30-51-35]]

^<<v30-51-35,35>>^ “Recaia sobre a Babilônia a nossa carne dilacerada!”, dizem os habitantes de Sião. “E sobre a Caldeia o meu sangue derramado!”, diz Jerusalém.

[[v30-51-36]]

^<<v30-51-36,36>>^ Eis por que, assim falou o Senhor: “Vou tomar tua causa em minhas mãos, e hei de vingar-te. Porei teu mar a seco e estancarei suas nascentes.^&#42;1^

[[v30-51-37]]

^<<v30-51-37,37>>^ A Babilônia se tornará um amontoado de pedras, covil de chacais, objeto de horror, lugar ermo, que será escarnecido.

[[v30-51-38]]

^<<v30-51-38,38>>^ Rugem seus homens em multidão como leões, e rosnam como leõezinhos.

[[v30-51-39]]

^<<v30-51-39,39>>^ Quando estiverem sequiosos, eu lhes darei de beber, e os embriagarei, a fim de que se deleitem, adormecendo-os em um sono eterno, do qual não mais despertem – oráculo do Senhor.

[[v30-51-40]]

^<<v30-51-40,40>>^ Eu os farei, como carneiros, descer ao matadouro, quais cordeiros e cabritos”.

[[v30-51-41]]

^<<v30-51-41,41>>^ Como foi tomada Ainolibab, e vencida a glória de toda a terra? Como se tornou a Babilônia objeto de horror, no meio das nações?^&#42;1^

[[v30-51-42]]

^<<v30-51-42,42>>^ Subiu o mar contra a Babilônia, e ela foi coberta pela multidão de suas ondas.

[[v30-51-43]]

^<<v30-51-43,43>>^ Tornaram-se desertos seus arredores, terra árida e desolada, onde ninguém mais há de morar, e nenhum ser humano habitar.

[[v30-51-44]]

^<<v30-51-44,44>>^ Castigarei Bel na Babilônia tirando-lhe da boca o que havia comido. E dela não se acercarão mais as nações. Eis que se desmorona a muralha da Babilônia!

[[v30-51-45]]

^<<v30-51-45,45>>^ Sai de lá, povo meu! Salve cada um a própria vida, ante a cólera ardente do Senhor!

[[v30-51-46]]

^<<v30-51-46,46>>^ Não se desfaleça o vosso coração. Não tenhais medo das notícias que se farão ouvir na terra. Durante um ano um rumor se fará ouvir e outro rumor no ano seguinte: “Violências na terra, tirano contra tirano”.

[[v30-51-47]]

^<<v30-51-47,47>>^ Eis por que virão dias em que me lançarei contra os ídolos da Babilônia: será, então, coberta de vergonha a terra inteira, em cujo meio cairão os homens feridos de morte.

[[v30-51-48]]

^<<v30-51-48,48>>^ O céu, a terra e tudo quanto encerram lançarão sobre a Babilônia exclamações de alegria – oráculo do Senhor – porque contra ela se lançaram os devastadores vindos do Norte.

[[v30-51-49]]

^<<v30-51-49,49>>^ Ó mortos de Israel, necessário é que caia a Babilônia por sua vez, assim como, por causa dela, caíram todos os mortos da terra.

[[v30-51-50]]

^<<v30-51-50,50>>^ Escapai da espada; parti, não vos detenhais. Na terra longínqua, não vos esqueçais do Senhor, e seja Jerusalém o sonho de vossos corações.

[[v30-51-51]]

^<<v30-51-51,51>>^ “Estamos confundidos; ouvimos a injúria, e a vergonha cobriu-nos os rostos, porque estrangeiros penetraram no santuário do templo.”

[[v30-51-52]]

^<<v30-51-52,52>>^ Eis por que virão dias – oráculo do Senhor – em que me lançarei contra os ídolos da Babilônia e em que, na terra inteira, gemerão aqueles que são massacrados.

[[v30-51-53]]

^<<v30-51-53,53>>^ Ainda que a Babilônia atingisse os céus e sua alta fortaleza se tornasse inacessível, os devastadores, sob minhas ordens, não deixarão de alcançá-la – oráculo do Senhor.

[[v30-51-54]]

^<<v30-51-54,54>>^ Eleva-se da Babilônia um clamor, e da Caldeia irrompe um tumulto de grande desastre.

[[v30-51-55]]

^<<v30-51-55,55>>^ É o Senhor quem devasta a Babilônia, fazendo-lhe calar o ruído das vozes. Bramem como torrentes de água as suas ondas e ressoam os seus gritos,

[[v30-51-56]]

^<<v30-51-56,56>>^ porquanto contra a Babilônia se arrojou o devastador. Foram presos os guerreiros e quebrados os seus arcos, porque o Senhor, que é o Deus das contas, não deixará de lhes dar a paga.

[[v30-51-57]]

^<<v30-51-57,57>>^ “Embriagarei seus chefes e seus sábios, seus governantes, oficiais e guerreiros, que dormirão um sono eterno e jamais despertarão!” – Oráculo do rei, cujo nome é Javé dos exércitos.

[[v30-51-58]]

^<<v30-51-58,58>>^ Eis o que diz o Senhor dos exércitos: “As muralhas imensas da Babilônia serão inteiramente arrasadas, e suas portas, altas como são, incendiadas. Assim, de nada valeram os sofrimentos dos povos, e em proveito do fogo esgotaram-se as nações”.

[[v30-51-59]]

^<<v30-51-59,59>>^ Eis a ordem dada pelo profeta Jeremias a Seraías, filho de Neerias, filho de Maasias, ao ir para a Babilônia com Sedecias, rei de Judá, no quarto ano de seu reinado. Era Seraías o camareiro-mor.

[[v30-51-60]]

^<<v30-51-60,60>>^ Havia Jeremias escrito num livro todas as calamidades que haveriam de atingir a Babilônia e todas as predições sobre ela.

[[v30-51-61]]

^<<v30-51-61,61>>^ E disse, então, a Seraías: “Quando chegares à Babilônia, procurarás um meio de ler todas essas palavras.

[[v30-51-62]]

^<<v30-51-62,62>>^ Assim, dirás: ‘Senhor, fostes vós que declarastes a destruição desta cidade, que se tornaria inabitável para homens e animais, transformando-se em solidão eterna’.

[[v30-51-63]]

^<<v30-51-63,63>>^ E quando terminares a leitura do que nele se acha escrito, tu o ligarás a uma pedra e o lançarás ao Eufrates, dizendo: ‘Assim será mergulhada a Babilônia, sem que jamais se possa erguer da calamidade que lançarei contra ela’. (E cairão extenuados.)”.

'''

xref:030-jeremias/030-jeremias-050.adoc#v30-50-0[&#60; Capítulo Anterior] | <<v30-51-0,Topo>> | xref:030-jeremias/030-jeremias-052.adoc#v30-52-0[Próximo Capítulo &#62;]