include::./index.adoc[]

[[v30-20-0]]
=== Jeremias, 20
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jeremias 20 relata o sofrimento e angústia do profeta Jeremias, que é perseguido e ridicularizado por falar a palavra do Senhor. Ele se sente enganado por Deus e desejaria não ter nascido. Abaixo estão cinco versículos relacionados com os temas abordados em Jeremias 20:
* Salmos 31:13: "Pois eu ouvi a maledicência de muitos; terror por todos os lados! Eles se ajuntavam e conspiravam contra mim, planejando tirar-me a vida." Assim como Jeremias, o salmista se encontra cercado por inimigos que tramam contra ele.
* Mateus 5:11-12: "Bem-aventurados sois vós, quando vos injuriarem e perseguiram e, mentindo, disserem todo mal contra vós, por minha causa. Alegrai-vos e exultai, porque é grande o vosso galardão nos céus, pois assim perseguiram aos profetas que foram antes de vós." Jesus fala sobre a perseguição que os seguidores dele sofrerão, lembrando que os profetas também foram perseguidos por falar a verdade.
* 2 Coríntios 4:8-9: "Em tudo somos atribulados, mas não angustiados; perplexos, mas não desesperados; perseguidos, mas não desamparados; abatidos, mas não destruídos." Paulo fala sobre as dificuldades enfrentadas pelos servos de Deus, mas também sobre a presença do Senhor em meio a elas.
* Romanos 8:38-39: "Porque estou certo de que, nem a morte, nem a vida, nem anjos, nem principados, nem coisas presentes, nem futuras, nem potestades, nem a altura, nem a profundidade, nem qualquer outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus nosso Senhor." Este versículo enfatiza a fidelidade de Deus para com seus servos, mesmo em meio às perseguições e sofrimentos.
* Tiago 5:10-11: "Meus irmãos, tomai por exemplo de aflição e paciência os profetas que falaram em nome do Senhor. Eis que temos por bem-aventurados os que sofreram. Ouvistes qual foi a paciência de Jó e vistes o fim que o Senhor lhe deu; porque o Senhor é muito misericordioso e piedoso." Tiago encoraja os crentes a seguir o exemplo dos profetas e a manter a paciência em meio às dificuldades, lembrando que Deus é misericordioso e justo.
****

[[v30-20-1]]

^<<v30-20-1,1>>^ Tendo o sacerdote Fassur, filho de Emer, que era superintendente do templo, ouvido o profeta Jeremias pronunciar esse oráculo,

[[v30-20-2]]

^<<v30-20-2,2>>^ mandou espancá-lo e pô-lo em grilhões na porta superior de Benjamim, que se encontra no Templo do Senhor.

[[v30-20-3]]

^<<v30-20-3,3>>^ No dia seguinte, quando Fassur mandou libertá-lo, disse-lhe Jeremias: “Não é mais Fassur que te chama o Senhor, mas sim Magor-Missabib.^&#42;1^

[[v30-20-4]]

^<<v30-20-4,4>>^ Pois assim diz o Senhor: Vou fazer de ti objeto de pavor, para ti mesmo e teus amigos, os quais, sob teu olhar, perecerão à espada de seus inimigos. Entregarei Judá nas mãos do rei da Babilônia, que os deportará para Babilônia, onde os ferirá à espada.

[[v30-20-5]]

^<<v30-20-5,5>>^ E entregarei todas as riquezas desta cidade, todo o produto de seu trabalho, todas as suas reservas preciosas e todos os tesouros dos reis de Judá, nas mãos de seus inimigos, que os tomarão como presa, e os levarão para Babilônia.

[[v30-20-6]]

^<<v30-20-6,6>>^ E tu, Fassur, serás arrastado, com tua família, para o cativeiro. Ireis a Babilônia para lá morrerem e serem enterrados, tu e teus amigos, aos quais proferiste falsos oráculos”.

[[v30-20-7]]

^<<v30-20-7,7>>^ Seduzistes-me, Senhor; e eu me deixei seduzir! Dominastes-me e obtivestes o triunfo. Sou objeto de contínua irrisão, e todos zombam de mim.^&#42;1^

[[v30-20-8]]

^<<v30-20-8,8>>^ Cada vez que falo é para proclamar a aproximação da violência e da devastação. E dia a dia a palavra do Senhor converte-se para mim em insultos e escárnios.

[[v30-20-9]]

^<<v30-20-9,9>>^ E, a mim mesmo, eu disse: Não mais o mencionarei, nem falarei em seu nome. Mas em meu seio havia um fogo devorador que se me encerrara nos ossos. Esgotei-me em refreá-lo, e não o consegui.^&#42;1^

[[v30-20-10]]

^<<v30-20-10,10>>^ Ouço as invectivas da multidão: “Cerca-nos o terror! Denunciai-o! Vamos denunciá-lo!”. Os que eram meus amigos espiam-me agora os passos. “Se cair em abusos, tiraremos vantagem, e dele nos vingaremos.”

[[v30-20-11]]

^<<v30-20-11,11>>^ O Senhor, porém, está comigo, qual poderoso guerreiro. Por isso, longe de triunfar, serão esmagados meus perseguidores. Sua queda os mergulhará na confusão. Será, então, a vergonha eterna, inesquecível.

[[v30-20-12]]

^<<v30-20-12,12>>^ Senhor, Deus dos exércitos, vós que sondais o justo, e que escrutais os rins e os corações, concedei-me o poder de contemplar a vingança que deles ides tirar! Pois em vossas mãos depositei a minha causa.

[[v30-20-13]]

^<<v30-20-13,13>>^ Cantai ao Senhor, glorificai-o, porque salvou a vida do miserável das mãos do mau.

[[v30-20-14]]

^<<v30-20-14,14>>^ Maldito o dia em que nasci! Nem abençoado seja o dia em que minha mãe me deu à luz.

[[v30-20-15]]

^<<v30-20-15,15>>^ Maldito o homem que levou a notícia a meu pai e que o cumulou de felicidade ao dizer-lhe: “Nasceu-te um menino!”.

[[v30-20-16]]

^<<v30-20-16,16>>^ A ele suceda o que às cidades aconteceu, que o Senhor sem piedade aniquilou! Desde o alvorecer ouça os gritos de alarme e o fragor da batalha ao meio-dia.^&#42;1^

[[v30-20-17]]

^<<v30-20-17,17>>^ Por que não me matou, antes de eu sair do ventre materno?! Minha mãe teria sido meu túmulo e eu ficaria para sempre guardado em suas entranhas!

[[v30-20-18]]

^<<v30-20-18,18>>^ Por que saí do seu seio? Para só contemplar tormentos e misérias, e na vergonha consumir meus dias?

'''

xref:030-jeremias/030-jeremias-019.adoc#v30-19-0[&#60; Capítulo Anterior] | <<v30-20-0,Topo>> | xref:030-jeremias/030-jeremias-021.adoc#v30-21-0[Próximo Capítulo &#62;]