include::./index.adoc[]

[[v30-38-0]]
=== Jeremias, 38
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jeremias 38 narra o momento em que o profeta é preso e jogado em uma cisterna por causa de suas profecias contra a cidade de Jerusalém. Ao longo do capítulo, Jeremias é resgatado por um etíope e tem uma conversa com o rei Zedequias, onde ele reitera sua mensagem de que a cidade seria tomada pelos babilônios. Seguem abaixo cinco versículos relacionados com os temas abordados em Jeremias 38:
* 2 Reis 25:4: "A cidade foi invadida, e todos os soldados fugiram de noite pelo caminho da porta entre as duas muralhas perto do jardim do rei" Este versículo descreve o momento em que Jerusalém é tomada pelos babilônios, confirmando a profecia de Jeremias.
* Jeremias 32:3: "Zedequias, rei de Judá, o mandou prender e perguntou-lhe: «O Senhor não lhe falou, dizendo: "Vou entregar esta cidade nas mãos do rei da Babilônia, que a tomará?"»" Este versículo mostra como Jeremias é preso e levado perante o rei Zedequias, a quem ele já havia profetizado a queda da cidade.
* Jeremias 21:4-7: "Assim diz o Senhor, o Deus de Israel: Eis que virarei contra vós as armas de guerra que estão nas vossas mãos, com as quais vós pelejais fora dos muros, e ajuntarei no meio desta cidade todos os vossos inimigos. Eu mesmo pelejarei contra vós com mão estendida e com braço forte, com ira, furor e grande indignação. Ferirei os habitantes desta cidade, homens e animais; morrerão de grande pestilência." Esses versículos mostram a continuidade da mensagem de Jeremias, que prevê a queda de Jerusalém e a punição do povo pelos seus pecados.
* Jeremias 39:18: "Eu livrarei você naquele dia, diz o Senhor; você não será entregue nas mãos dos homens a quem você tem medo." Esse versículo é uma promessa de Deus para Jeremias, que seria protegido durante a queda de Jerusalém.
* Jeremias 52:7-11: "Então a cidade foi invadida, e todos os soldados fugiram de noite pelo caminho da porta entre as duas muralhas perto do jardim do rei, embora os caldeus estivessem em redor da cidade. E o rei fugiu pelo caminho da Arabá, mas o exército caldeu o perseguiu e alcançou-o nas campinas de Jericó. Todo o seu exército se dispersou e fugiu, deixando-o sozinho. Então prenderam o rei e o levaram ao rei da Babilônia em Ribla, na terra de Hamate, onde foi condenado." Estes versículos descrevem a queda de Jerusalém e a captura do rei Zedequias pelos babilônios, confirmando a profecia de Jeremias.
****

[[v30-38-1]]

^<<v30-38-1,1>>^ Safatias, filho de Matã, Gedalias, filho de Fassur, Jucal, filho de Semeías, e Fassur, filho de Melquias, ouviram as palavras que Jeremias pronunciara diante de todos.

[[v30-38-2]]

^<<v30-38-2,2>>^ “Oráculo do Senhor” – dizia ele –: “Aquele que ficar na cidade morrerá pela espada, fome e peste, ao passo que o que sair, a fim de se entregar aos caldeus, viverá, e a vida a salvo será seu espólio. E viverá.

[[v30-38-3]]

^<<v30-38-3,3>>^ Oráculo do Senhor: A cidade será entregue ao exército do rei da Babilônia, que a tomará de assalto.”

[[v30-38-4]]

^<<v30-38-4,4>>^ Disseram, então, os chefes ao rei: “Seja esse homem eliminado, pois que desencoraja o que resta de guerreiros na cidade em todo o povo, proferindo semelhantes palavras. Não procura ele a salvação do povo mas a sua perdição”.

[[v30-38-5]]

^<<v30-38-5,5>>^ Respondeu-lhes o rei Sedecias: “Ele está em vossas mãos. O rei nada vos pode recusar”.

[[v30-38-6]]

^<<v30-38-6,6>>^ Tomaram então Jeremias e, por meio de cordas, o fizeram descer na cisterna de Melquias, o príncipe real, a qual se encontrava no pátio do cárcere. Não havia água na cisterna; havia, porém, lodo, onde Jeremias se atolou.

[[v30-38-7]]

^<<v30-38-7,7>>^ Um eunuco etíope do palácio real, chamado Ebed-Melec, soube, porém, que haviam lançado Jeremias na cisterna. Como estivesse o rei nesse momento assentado à porta de Benjamim,

[[v30-38-8]]

^<<v30-38-8,8>>^ saiu ele do palácio para ir encontrá-lo.

[[v30-38-9]]

^<<v30-38-9,9>>^ “Ó rei,meu Senhor” – disse-lhe o eunuco –, “andaram mal esses homens, tratando assim o profeta Jeremias e lançando-o na cisterna. Morrerá de fome, pois que não há mais pão na cidade.”

[[v30-38-10]]

^<<v30-38-10,10>>^ Respondeu-lhe então o rei com esta ordem: “Leva daqui contigo trinta homens e faze com que retirem o profeta Jeremias da cisterna, antes que morra”.

[[v30-38-11]]

^<<v30-38-11,11>>^ Ebed-Melec, tomando então os homens consigo, dirigiu-se ao palácio e ao vestiário da tesouraria e de lá tirou pedaços de estofo e velhos andrajos. E, tomando uma corda, fê-los descer até Jeremias, na cisterna.

[[v30-38-12]]

^<<v30-38-12,12>>^ “Coloca” – disse Ebed-Melec a Jeremias – “estes pedaços de estofo e estes retalhos sob tuas axilas embaixo das cordas.” Assim fez o profeta.

[[v30-38-13]]

^<<v30-38-13,13>>^ Então, erguendo-o por meio das cordas, retiraram-no para fora da cisterna. E Jeremias ficou no pátio do cárcere.^&#42;1^

[[v30-38-14]]

^<<v30-38-14,14>>^ Mandou então o rei Sedecias que lhe trouxessem o profeta Jeremias e o conduzissem à terceira porta do templo, e lhe disse: “Tenho algo a perguntar-te; nada me ocultes”.

[[v30-38-15]]

^<<v30-38-15,15>>^ Disse Jeremias ao rei: “Se eu te responder, não me mandarás matar? Aliás, se te der um conselho, não me ouvirás”.

[[v30-38-16]]

^<<v30-38-16,16>>^ Então, o rei Sedecias fez em segredo a Jeremias este juramento: “Pela vida de Deus que nos deu a vida, não te mandarei matar nem te entregarei aos que odeiam a tua vida!”.

[[v30-38-17]]

^<<v30-38-17,17>>^ E Jeremias disse então a Sedecias: “Eis o que diz o Senhor dos exércitos, Deus de Israel: Se te entregares aos oficiais do rei da Babilônia, terás a vida salva e a cidade não será queimada. E sobreviverás, assim como tua família.

[[v30-38-18]]

^<<v30-38-18,18>>^ Mas, se te não entregares aos oficiais do rei da Babilônia, cairá a cidade nas mãos dos caldeus, os quais a incendiarão. E tu não lhes escaparás”.

[[v30-38-19]]

^<<v30-38-19,19>>^ “Temo os judeus” – replicou o rei Sedecias – “que já se aliaram aos caldeus, e que me maltratarão se a eles for entregue.”

[[v30-38-20]]

^<<v30-38-20,20>>^ “Tal não acontecerá” – retorquiu Jeremias –. “Escuta, portanto, a voz do Senhor naquilo que te digo: Nada te acontecerá e terás a vida salva.

[[v30-38-21]]

^<<v30-38-21,21>>^ Mas, se recusares entregar-te, eis (a visão) que o Senhor me mostrou:

[[v30-38-22]]

^<<v30-38-22,22>>^ Todas as mulheres que ficarem no palácio do rei de Judá serão entregues aos oficiais do rei da Babilônia. E elas dirão: Foste enganado, e te subjugaram os teus bons amigos. Desapareceram, enquanto teus pés se atolavam na lama.

[[v30-38-23]]

^<<v30-38-23,23>>^ Todas as tuas mulheres e teus filhos serão entregues aos caldeus. E tu não lhes escaparás. Serás feito prisioneiro pelo rei da Babilônia e a cidade será entregue às chamas!”

[[v30-38-24]]

^<<v30-38-24,24>>^ Disse, então, Sedecias a Jeremias: “Que ninguém saiba do que falamos, senão poderás morrer.

[[v30-38-25]]

^<<v30-38-25,25>>^ Se souberem os ministros que tivemos esta entrevista, se te vierem procurar a fim de perguntar-te, sob ameaça de morte, tudo quanto te disse o rei, sem nada ocultar,

[[v30-38-26]]

^<<v30-38-26,26>>^ tu lhes dirás: Fui suplicar ao rei que não fosse reconduzido à casa de Jônatas, onde encontraria a morte”.

[[v30-38-27]]

^<<v30-38-27,27>>^ Com efeito, todos os ministros foram interrogá-lo, tendo-lhes respondido o profeta exatamente como lhe ordenara o rei. Deixaram-no então tranquilo, porquanto nada transpirou da conversa havida.

[[v30-38-28]]

^<<v30-38-28,28>>^ Assim passou Jeremias a habitar o pátio do cárcere, até o dia da tomada de Jerusalém. De fato, lá estava ele quando foi expugnada Jerusalém...

'''

xref:030-jeremias/030-jeremias-037.adoc#v30-37-0[&#60; Capítulo Anterior] | <<v30-38-0,Topo>> | xref:030-jeremias/030-jeremias-039.adoc#v30-39-0[Próximo Capítulo &#62;]