include::./index.adoc[]

[[v30-50-0]]
=== Jeremias, 50
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jeremias 50 fala sobre a queda de Babilônia e a libertação do povo de Israel do cativeiro. A seguir, são apresentados cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados nesse capítulo:
* Isaías 48:20: "Saí de Babilônia, fugi dos caldeus, com voz de júbilo anunciai, proclamai isto, divulgue-se até ao fim da terra; dizei: O Senhor remiu a seu servo Jacó!" Este versículo fala sobre a libertação do povo de Israel da Babilônia e a alegria que isso traz.
* Isaías 52:11: "Retirai-vos, retirai-vos, saí daí, não toqueis coisa imunda; saí do meio dela, purificai-vos, vós que levais os utensílios do Senhor." Esse versículo também fala sobre a saída do povo de Israel da Babilônia e a necessidade de se purificarem para estar em comunhão com Deus.
* Jeremias 51:6: "Fugi do meio de Babilônia, e cada um salve a sua vida; não sejais exterminados na sua injustiça; porque este é o tempo da vingança do Senhor; ele lhe dará o pago." Aqui, o profeta Jeremias exorta o povo de Israel a fugir de Babilônia e se salvar da destruição iminente.
* Jeremias 51:20-23: "Tu me és um martelo e armas de guerra; contigo despedaçarei nações, e contigo destruirei reinos; contigo despedaçarei o cavalo e seu cavaleiro; contigo despedaçarei o carro e seu condutor; contigo despedaçarei o homem e a mulher; contigo despedaçarei o velho e o moço; contigo despedaçarei o rapaz e a menina." Esses versículos falam sobre a utilização de Babilônia como um instrumento de destruição nas mãos de Deus.
* Apocalipse 18:2: "E clamou fortemente com grande voz, dizendo: Caiu, caiu a grande Babilônia, e se tornou morada de demônios, e guarida de todo espírito imundo, e guarida de toda ave imunda e aborrecível." Esse versículo fala sobre a queda final de Babilônia, que se torna um lugar de habitação de demônios e espíritos imundos.
****

[[v30-50-1]]

^<<v30-50-1,1>>^ Palavra do Senhor pronunciada contra a Babilônia, país dos caldeus, por intermédio do profeta Jeremias.^&#42;1^

[[v30-50-2]]

^<<v30-50-2,2>>^ “Proclamai o que vos digo e publicai-o entre as nações! Erguei um sinal; anunciai-o! Nada oculteis e exclamai: ‘Babilônia foi tomada!’. Bel cobriu-se de confusão; Merodac foi destroçado; e seus ídolos foram confundidos, e abatidas suas imundícies.^&#42;1^

[[v30-50-3]]

^<<v30-50-3,3>>^ Porque um povo vindo do Norte avança contra ela, o qual fará de seu território um deserto inabitado, donde animais e homens fugirão e desaparecerão.

[[v30-50-4]]

^<<v30-50-4,4>>^ Naqueles dias, naqueles tempos – oráculo do Senhor –, voltarão os israelitas e os judeus, e em lágrimas hão de caminhar, procurando o Senhor, seu Deus;

[[v30-50-5]]

^<<v30-50-5,5>>^ eles se porão em procura de Sião, e para lá voltarão seus rostos. ‘Vinde! Unamo-nos ao Senhor por uma eterna aliança que não será jamais esquecida!’

[[v30-50-6]]

^<<v30-50-6,6>>^ Era meu povo qual rebanho de ovelhas perdidas. Seus pastores as tinham perdido ao azar das montanhas; caminhavam por montanhas e colinas, esquecendo-se de seu aprisco.

[[v30-50-7]]

^<<v30-50-7,7>>^ Quantos as encontravam, devoravam-nas; e diziam seus inimigos: ‘Nenhum mal existe nisso, porquanto pecaram contra o Senhor, verdadeiro aprisco, e esperança de seus pais’.

[[v30-50-8]]

^<<v30-50-8,8>>^ Fugi do recinto da Babilônia, abandonai a Caldeia! Sede como os cabritos à frente do rebanho,

[[v30-50-9]]

^<<v30-50-9,9>>^ porque vou suscitar e conduzir contra a Babilônia uma coligação de grandes nações vindas do Norte. Contra ela se hão de enfileirar e a levarão de vencida. Suas setas são as de hábil guerreiro que não dispara sem atingir o alvo.

[[v30-50-10]]

^<<v30-50-10,10>>^ A Caldeia será entregue à pilhagem, e os que a saquearem se fartarão – oráculo do Senhor.”

[[v30-50-11]]

^<<v30-50-11,11>>^ Sim, alegrai-vos! Podeis estar contentes, saqueadores de minha herança! Sim, saltai qual novilha na campina, e relinchai qual garanhão!

[[v30-50-12]]

^<<v30-50-12,12>>^ Ficará coberta de confusão a vossa mãe. Aquela que vos gerou corará de vergonha; ela é colocada no último lugar das nações, porque não é senão deserto, desolado e pantanoso.

[[v30-50-13]]

^<<v30-50-13,13>>^ Priva-a de seus habitantes a cólera do Senhor, ficando reduzida a um estado de solidão. Quem passar pela Babilônia e lhe contemplar a queda assobiará de pasmo.

[[v30-50-14]]

^<<v30-50-14,14>>^ Em marcha para assaltar a Babilônia, vós todos, arqueiros! Atirai contra ela sem poupar as flechas, porquanto pecou contra o Senhor.

[[v30-50-15]]

^<<v30-50-15,15>>^ De todos os cantos, lançai contra ela o grito de guerra! Ela estende a mão; suas torres e muralhas são desmoronadas, pois assim é o castigo do Senhor. Vingai-vos dela, fazendo o mesmo que ela fez.^&#42;1^

[[v30-50-16]]

^<<v30-50-16,16>>^ Exterminai na Babilônia aquele que semeia, e o que maneja a foice no tempo da colheita ante a espada devastadora. Volte cada um para o seu povo, e fuja para a sua terra.

[[v30-50-17]]

^<<v30-50-17,17>>^ Israel é qual ovelha desgarrada perseguida por leões. Um a devorou: o rei da Assíria, e outro lhe partiu os ossos: Nabucodonosor, rei da Babilônia.

[[v30-50-18]]

^<<v30-50-18,18>>^ Eis por que assim fala o Senhor dos exércitos, Deus de Israel: “Vou castigar o rei da Babilônia e a sua terra, assim como castiguei o rei da Assíria.

[[v30-50-19]]

^<<v30-50-19,19>>^ Trarei novamente Israel para as suas pastagens, a fim de que entre nas pastagens do Carmelo e de Basã; e nos montes de Efraim e de Galaad ela se fartará.

[[v30-50-20]]

^<<v30-50-20,20>>^ Naqueles dias e naqueles tempos – oráculo do Senhor – será buscada a iniquidade de Israel, mas ela terá desaparecido, e também o pecado de Judá, mas não o acharão, porque perdoarei ao resto que tiver poupado.

[[v30-50-21]]

^<<v30-50-21,21>>^ Sobe contra a terra de Merataim e contra a população de Facud. Devasta, extermina – oráculo do Senhor – e executa todas as minhas ordens”.^&#42;1^

[[v30-50-22]]

^<<v30-50-22,22>>^ Tumulto de guerra no país, desastre imenso.

[[v30-50-23]]

^<<v30-50-23,23>>^ Como foi feito em pedaços o martelo que feria o mundo inteiro? Como se transformou a Babilônia em objeto de pasmo entre as nações?

[[v30-50-24]]

^<<v30-50-24,24>>^ Lancei-te a rede e, sem o saberes, foste colhida de improviso, ó Babilônia. Eis-te apanhada e presa, por haveres provocado o Senhor.

[[v30-50-25]]

^<<v30-50-25,25>>^ Abriu o Senhor seu arsenal para dele tirar as armas de sua indignação, porque o Senhor dos exércitos tem algo a fazer contra a terra dos caldeus.

[[v30-50-26]]

^<<v30-50-26,26>>^ Vinde contra ela de todos os confins, abri seus celeiros, amontoai em feixes, e tudo exterminai sem que reste coisa alguma.

[[v30-50-27]]

^<<v30-50-27,27>>^ Matai todos os seus touros! Que desçam ao matadouro! Ai deles, porque o seu dia chegou, o tempo do seu castigo!

[[v30-50-28]]

^<<v30-50-28,28>>^ Ouviram-se os gritos dos fugitivos e daqueles que escaparam da terra da Babilônia, a fim de anunciarem em Sião a vingança do Senhor, nosso Deus, a vingança que toma pelo seu templo.

[[v30-50-29]]

^<<v30-50-29,29>>^ Convocai contra a Babilônia os arqueiros, quantos retesam o arco, e sitiai-a, a fim de que ninguém possa escapar. Tratai-a segundo a sua conduta, tomai-lhe tudo o que ela fez, porque ela se levantou contra o Santo de Israel.

[[v30-50-30]]

^<<v30-50-30,30>>^ Por isso, os seus jovens vão cair nas praças e todos os seus guerreiros perecerão nesse dia – oráculo do Senhor.

[[v30-50-31]]

^<<v30-50-31,31>>^ É contra ti que me volto, ó insolente – oráculo do Senhor Javé dos exércitos –, chegou o teu dia, o tempo do teu castigo.

[[v30-50-32]]

^<<v30-50-32,32>>^ A insolente se atordoará, e cairá sem que ninguém mais a levante. Eu lhe lançarei fogo nas suas cidades, e tudo em volta será devorado.

[[v30-50-33]]

^<<v30-50-33,33>>^ Eis o que diz o Senhor dos exércitos: Andam oprimidos os israelitas, assim como os judeus. Aqueles que os levaram ao cativeiro os detêm, recusando-se a libertá-los.

[[v30-50-34]]

^<<v30-50-34,34>>^ É forte, contudo, o seu vingador, cujo nome é Senhor dos exércitos; e ele lhe defenderá com ardor a causa, a fim de que volte a calma ao país, e faça tremer os habitantes da Babilônia.

[[v30-50-35]]

^<<v30-50-35,35>>^ À espada os caldeus – oráculo do Senhor – e a população da Babilônia, os seus chefes e os seus sábios!

[[v30-50-36]]

^<<v30-50-36,36>>^ À espada os seus adivinhos mentirosos, para que enlouqueçam! À espada seus guerreiros, para que deles se aposse o terror!

[[v30-50-37]]

^<<v30-50-37,37>>^ À espada os seus cavalos e os seus carros, e toda a massa de povo que nela se encontra, para que se tornem como mulheres! À espada seus tesouros, para que sejam saqueados!

[[v30-50-38]]

^<<v30-50-38,38>>^ À espada suas águas, para que se esgotem! Porquanto é uma terra de ídolos, de gente apaixonada por seus espantalhos!

[[v30-50-39]]

^<<v30-50-39,39>>^ Por isso, as feras aí farão sua morada com os chacais, e os avestruzes aí fixarão sua habitação. Jamais será ela habitada e para sempre ficará deserta.

[[v30-50-40]]

^<<v30-50-40,40>>^ Irá lhe acontecer como no tempo em que Deus destruiu Sodoma, Gomorra e as cidades vizinhas – oráculo do Senhor. Ninguém mais aí habitará, e nenhum ser humano a povoará.

[[v30-50-41]]

^<<v30-50-41,41>>^ Eis que do Norte acorre um povo: uma grande nação e reis numerosos erguem-se dos confins da terra,

[[v30-50-42]]

^<<v30-50-42,42>>^ armados de arcos e de setas. São cruéis e sem piedade; o barulho que fazem assemelha-se ao rugido do mar. Montados em cavalos alinham-se em ordem de batalha contra ti, filha da Babilônia.

[[v30-50-43]]

^<<v30-50-43,43>>^ Ao chegar-lhe tal notícia, deixou pender os braços o rei da Babilônia, e a angústia o oprimiu, qual a dor de uma mulher ao dar à luz.

[[v30-50-44]]

^<<v30-50-44,44>>^ Qual leão, lança-se o inimigo dos espinheiros do Jordão para uma pastagem perpétua; assim também em um instante eu os farei desaparecer, e aí estabelecerei aquele que escolhi. Porquanto, quem se iguala a mim? Quem poderia citar-me em juízo? Qual o pastor que poderia afrontar-me?

[[v30-50-45]]

^<<v30-50-45,45>>^ Escutai, portanto, a decisão do Senhor a propósito da Babilônia e seus desígnios contra a Caldeia: Sim, serão arrastadas à morte como débeis cordeiros, e seus campos serão devastados.

[[v30-50-46]]

^<<v30-50-46,46>>^ Ao estrondo da queda da Babilônia comoveu-se a terra, e até entre as nações chegou seu eco.

'''

xref:030-jeremias/030-jeremias-049.adoc#v30-49-0[&#60; Capítulo Anterior] | <<v30-50-0,Topo>> | xref:030-jeremias/030-jeremias-051.adoc#v30-51-0[Próximo Capítulo &#62;]