include::./index.adoc[]

[[v30-5-0]]
=== Jeremias, 5
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jeremias 5 é um capítulo em que o profeta Jeremias acusa o povo de Judá de ser infiel a Deus e desobedecer seus mandamentos, resultando em punição divina. O capítulo fala sobre a falta de justiça e honestidade, o orgulho e a arrogância do povo, a corrupção e a idolatria. Abaixo estão cinco versículos relacionados com esses temas:
* Provérbios 10:9: "Quem anda em integridade anda seguro, mas o que perverte os seus caminhos será conhecido." O versículo fala sobre a importância da honestidade e da integridade, algo que o povo de Judá estava negligenciando.
* Miquéias 6:8: "Ele te declarou, ó homem, o que é bom e o que o Senhor requer de ti: que pratiques a justiça, e ames a misericórdia, e andes humildemente com o teu Deus." Este versículo enfatiza a importância da justiça e da humildade diante de Deus, algo que o povo de Judá estava ignorando.
* Jeremias 7:5-6: "Mas se deveras melhorardes os vossos caminhos e as vossas obras; se deveras praticardes a justiça entre o homem e o seu próximo, se não oprimirdes o estrangeiro, e nem ao órfão, nem à viúva, nem derramardes sangue inocente neste lugar, nem andardes após outros deuses para vosso próprio mal, então vos farei habitar neste lugar, na terra que dei a vós e a vossos pais para sempre." Este versículo destaca a importância da justiça social, da compaixão e da adoração exclusiva a Deus.
* Jeremias 6:13-14: "Porque desde o menor deles até ao maior, cada um se dá à avareza; e desde o profeta até ao sacerdote, cada um pratica a falsidade. E curam a ferida do meu povo levianamente, dizendo: Paz, paz; quando não há paz." Este versículo denuncia a corrupção tanto dos líderes religiosos quanto do povo em geral.
* Jeremias 2:11: "Porventura trocou alguma nação os seus deuses, ainda que não eram deuses? Mas o meu povo trocou a sua Glória por aquilo que é de nenhum proveito." Este versículo destaca a idolatria do povo de Judá, que abandonou o verdadeiro Deus para adorar ídolos sem valor.
****

[[v30-5-1]]

^<<v30-5-1,1>>^ Percorrei as ruas de Jerusalém, olhai, perguntai; procurai nas praças, vede se nelas encontrais um homem, um só homem que pratique a justiça e que seja leal; então, eu perdoarei a cidade.

[[v30-5-2]]

^<<v30-5-2,2>>^ Mesmo quando juram: “Pela vida de Deus!”, é para prestar falso juramento.

[[v30-5-3]]

^<<v30-5-3,3>>^ Senhor, não se compraz o vosso olhar em contemplar a lealdade? Vós os feris, e eles não sentem a dor; vós os abateis, e recusam aceitar a correção. Mais duro que o rochedo apresentam o semblante, recusando converter-se.

[[v30-5-4]]

^<<v30-5-4,4>>^ E a mim mesmo eu dizia: são apenas vulgares e insensatos, porque não conhecem os caminhos do Senhor, a Lei do seu Deus.

[[v30-5-5]]

^<<v30-5-5,5>>^ Irei procurar os grandes para falar-lhes, pois que eles conhecem as sendas do Senhor, a Lei do seu Deus. Mas todos esses também quebraram o jugo, e romperam os laços.

[[v30-5-6]]

^<<v30-5-6,6>>^ Eis por que o leão da floresta os ferirá e o lobo da estepe os dizimará; a pantera os espreitará em suas cidades; e aquele que dela sair será despedaçado, porquanto numerosos são os seus delitos, e sem conta suas revoltas.

[[v30-5-7]]

^<<v30-5-7,7>>^ Por que perdoar-te? Teus filhos abandonaram-me; juram por deuses que não o são. Cumulei-os de dons; e eles cometem o adultério, acercando-se das casas de devassidão.

[[v30-5-8]]

^<<v30-5-8,8>>^ Garanhões bem nutridos, no calor do cio, cada qual relincha ante a mulher do próximo.

[[v30-5-9]]

^<<v30-5-9,9>>^ E não os punirei por esses crimes? – oráculo do Senhor. Não se vingaria minha alma de semelhante nação?

[[v30-5-10]]

^<<v30-5-10,10>>^ Escalai muros (de minha videira), destruí-a, mas não a aniquileis completamente. Arrancai-lhe os sarmentos, porquanto não pertencem ao Senhor.^&#42;1^

[[v30-5-11]]

^<<v30-5-11,11>>^ A casa de Israel e a casa de Judá foram-me infiéis – oráculo do Senhor.

[[v30-5-12]]

^<<v30-5-12,12>>^ Renegaram o Senhor, e exclamaram: “Não há Deus! Nenhum mal nos advirá, não veremos a espada e a fome.

[[v30-5-13]]

^<<v30-5-13,13>>^ São apenas vento os profetas, de ninguém são arautos; assim lhes aconteça a eles mesmos”.

[[v30-5-14]]

^<<v30-5-14,14>>^ Por isso, o Senhor, Deus dos exércitos, vos diz: “Já que tendes essa linguagem, vou introduzir minhas palavras como fogo em tua boca, e desse povo fazer lenha que a chama devorará.

[[v30-5-15]]

^<<v30-5-15,15>>^ Ó casa de Israel, vou lançar contra vós uma nação que vem de longe – oráculo do Senhor –, nação antiga e poderosa, da qual não compreendes a linguagem, e ignoras a fala.

[[v30-5-16]]

^<<v30-5-16,16>>^ Sua aljava é qual sepulcro escancarado, e seus homens todos são valentes;

[[v30-5-17]]

^<<v30-5-17,17>>^ ela devorará tuas searas e teu pão, devorará teus filhos e tuas filhas, devorará teus rebanhos e teu gado, devorará tuas vinhas e tuas figueiras, à ponta da espada conquistará as praças fortes nas quais depositas tua confiança”.

[[v30-5-18]]

^<<v30-5-18,18>>^ “Mesmo, porém, naqueles dias” – disse o Senhor –, “não vos exterminarei de todo.”

[[v30-5-19]]

^<<v30-5-19,19>>^ E, quando disserdes: “Por que assim nos tratou o Senhor Deus?” – responderás –: “Assim como me abandonastes para servir em vossa terra a deuses estrangeiros, assim também servireis a es- trangeiros em terra que não é a vossa”.^&#42;1^

[[v30-5-20]]

^<<v30-5-20,20>>^ Anunciai isto à casa de Jacó, proclamai o que segue à terra de Judá:

[[v30-5-21]]

^<<v30-5-21,21>>^ “Escutai bem, povo insensato e sem inteligência: vós que tendes olhos para não ver e ouvidos para não ouvir:

[[v30-5-22]]

^<<v30-5-22,22>>^ Não temeis a minha face? – oráculo do Senhor. Não tremeis diante de mim, eu que fixei a areia como limite ao mar, barreira eterna que não será ultrapassada? Por mais que se lhe agitem as ondas, são impotentes, murmuram, mas não vão além;

[[v30-5-23]]

^<<v30-5-23,23>>^ enquanto tiver esse povo um coração indócil e rebelde, recuará e irá embora”.

[[v30-5-24]]

^<<v30-5-24,24>>^ E em seu coração não dirá: “Temamos ao Senhor, nosso Deus, que no tempo devido nos manda a chuva do outono e a chuva da primavera, e nos garante as semanas destinadas à colheita”.

[[v30-5-25]]

^<<v30-5-25,25>>^ Foram vossas iniquidades que alteraram essa ordem, vossos pecados que vos privaram desses bens.

[[v30-5-26]]

^<<v30-5-26,26>>^ Porquanto perversos se encontram no seio de meu povo, que espreitam, de tocaia, como caçadores de pássaros, armando laços para apanhar os homens.

[[v30-5-27]]

^<<v30-5-27,27>>^ À semelhança de uma gaiola cheia de pássaros, assim estão suas casas repletas de fruto de suas presas. Por esta forma tornam-se ricos e poderosos,

[[v30-5-28]]

^<<v30-5-28,28>>^ e se apresentam nutridos e reluzentes; ultrapassam, porém, os limites do mal. Não procedem com justiça para com o órfão, mas prosperam! E não fazem justiça aos infelizes!

[[v30-5-29]]

^<<v30-5-29,29>>^ Como não repreender tamanhos excessos – oráculo do Senhor –, e não vingar-me de semelhante nação?

[[v30-5-30]]

^<<v30-5-30,30>>^ Coisas horríveis, espantosas, ocorreram nesta terra:

[[v30-5-31]]

^<<v30-5-31,31>>^ mentem os profetas em seus oráculos, os sacerdotes dominam pela força. E meu povo mostra-se satisfeito! Que fareis vós, quando chegar o fim?

'''

xref:030-jeremias/030-jeremias-004.adoc#v30-4-0[&#60; Capítulo Anterior] | <<v30-5-0,Topo>> | xref:030-jeremias/030-jeremias-006.adoc#v30-6-0[Próximo Capítulo &#62;]