include::./index.adoc[]

[[v30-36-0]]
=== Jeremias, 36
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Jeremias 36 narra a época em que o Senhor ordenou a Jeremias que escrevesse todas as palavras que Ele havia falado contra Israel e Judá em um rolo e o lesse em voz alta ao povo no templo. O rolo foi lido ao rei Jeoaquim, mas ele não se arrependeu de seus caminhos. Os versículos relacionados aos temas abordados em Jeremias 36 são os seguintes:
* Salmos 119:11: "Guardo no coração as tuas palavras, para não pecar contra ti." O povo de Judá precisava guardar as palavras de Deus em seus corações para não pecarem contra Ele.
* Provérbios 29:1: "O homem que, depois de repreendido, endurece a cerviz será quebrantado de repente, sem que haja cura." O rei Jeoaquim foi repreendido pelas palavras do rolo, mas ele endureceu seu coração e foi quebrantado.
* Hebreus 4:12: "Porque a palavra de Deus é viva e eficaz, e mais cortante do que qualquer espada de dois gumes, e penetra até a divisão de alma e espírito, e de juntas e medulas, e é apta para discernir os pensamentos e intenções do coração." O rolo com as palavras de Deus era poderoso e capaz de discernir os pensamentos e intenções do coração do povo.
* João 8:32: "E conhecereis a verdade, e a verdade vos libertará." O povo precisava conhecer a verdade das palavras de Deus para serem libertados.
* 1 Pedro 1:25: "Mas a palavra do Senhor permanece para sempre. E esta é a palavra que entre vós foi evangelizada." As palavras de Deus são eternas e permanecem para sempre, e devem ser proclamadas a todos.
****

[[v30-36-1]]

^<<v30-36-1,1>>^ No quarto ano de Joaquin, filho de Josias, rei de Judá, foi a palavra do Senhor dirigida a Jeremias, nestes termos:

[[v30-36-2]]

^<<v30-36-2,2>>^ “Toma um rolo de um livro e nele escreverás todos os oráculos que te ditei a propósito de Israel, de Judá e das nações pagãs, desde que te comecei a falar, no tempo de Josias, até o presente.^&#42;1^

[[v30-36-3]]

^<<v30-36-3,3>>^ Quando o povo de Judá compreender todo o mal que lhe pretendo fazer, talvez cada um se afaste de seu perverso caminho, de sorte que eu lhes possa perdoar as iniquidades e os pecados”.

[[v30-36-4]]

^<<v30-36-4,4>>^ Mandou então Jeremias que viesse Baruc, filho de Neerias, o qual, sob ditado do profeta, escreveu em um rolo todos os oráculos que recebera do Senhor.

[[v30-36-5]]

^<<v30-36-5,5>>^ Em seguida, Jeremias deu esta ordem a Baruc: “Estou impossibilitado de dirigir-me ao templo.^&#42;1^

[[v30-36-6]]

^<<v30-36-6,6>>^ Vai até lá em dias de jejum e, tomando o rolo em que escreveste as palavras que te ditei, lerás os oráculos do Senhor perante o povo e a gente de Judá, vinda de suas cidades.

[[v30-36-7]]

^<<v30-36-7,7>>^ Talvez dirijam eles súplicas ao Senhor e se convertam da má vida, porquanto imensa é a indignação e grande o furor com que o Senhor ameaça esse povo”.

[[v30-36-8]]

^<<v30-36-8,8>>^ E Baruc, filho de Neerias, executou pontualmente a ordem do profeta Jeremias, lendo no templo os oráculos do Senhor inscritos no rolo.

[[v30-36-9]]

^<<v30-36-9,9>>^ No quinto ano do reinado de Joaquin, filho de Josias, rei de Judá, no nono mês, um jejum foi prescrito diante do Senhor, para toda a população de Jerusalém e os habitantes das cidades de Judá que lá se haviam reunido.

[[v30-36-10]]

^<<v30-36-10,10>>^ Então, Baruc leu em seu rolo as palavras de Jeremias, achando-se no templo, na sala do secretário Gamarias, filho de Safã, sala esta situada no vestíbulo superior, à entrada da porta nova do templo. Foi feita essa leitura perante o povo.

[[v30-36-11]]

^<<v30-36-11,11>>^ Miqueias, filho de Gamarias, filho de Safã, ouvindo a leitura de todos esses oráculos do Senhor,

[[v30-36-12]]

^<<v30-36-12,12>>^ desceu ao palácio real, à câmara do secretário, onde se achava reunido um conselho de ministros: o secretário Elisama, Delaías, filho de Semeías, Elnatã, filho de Acobor, Gamarias, filho de Safã, Sedecias, filho de Hananias, assim como todos os ministros.

[[v30-36-13]]

^<<v30-36-13,13>>^ Contou-lhes Miqueias tudo o que ouvira ler Baruc perante o povo.

[[v30-36-14]]

^<<v30-36-14,14>>^ Então, os ministros enviaram Judi, filho de Natanias, filho de Semeías, filho de Cusi, com a missão de dizer a Baruc: “Toma o rolo do qual acabas de ler ao povo, e vem ter conosco”. Munido do rolo, dirigiu-se Baruc, filho de Neerias, para onde o chamavam os ministros.

[[v30-36-15]]

^<<v30-36-15,15>>^ Disseram-lhe então: “Senta-te e lê”. Pôs-se Baruc a ler.

[[v30-36-16]]

^<<v30-36-16,16>>^ Ao ouvirem esses oráculos, entreolharam-se aterrados os ministros. “É preciso” – disseram eles – “que levemos todas estas coisas ao conhecimento do rei.”

[[v30-36-17]]

^<<v30-36-17,17>>^ Em seguida, dirigindo-se a Baruc: “Como” – perguntaram-lhe – “escreveste todos esses oráculos?”.

[[v30-36-18]]

^<<v30-36-18,18>>^ “Ele me ditava” – respondeu Baruc –, “e eu os escrevia com tinta neste rolo.”

[[v30-36-19]]

^<<v30-36-19,19>>^ Então, disseram-lhe os ministros: “Vai e esconde-te, assim como Jeremias, e que ninguém conheça o teu esconderijo”.

[[v30-36-20]]

^<<v30-36-20,20>>^ Em seguida, deixando guardado o rolo na mesa do secretário Elisama, foram procurar o rei em sua casa, a fim de pô-lo a par do assunto.^&#42;1^

[[v30-36-21]]

^<<v30-36-21,21>>^ Mandou este, então, que Judi fosse buscar o rolo; Judi, tendo-o apanhado na sala do secretário Elisama, voltou com ele, a fim de lê-lo em presença do rei, tendo em torno, de pé, os seus ministros.

[[v30-36-22]]

^<<v30-36-22,22>>^ O rei estava assentado em um aposento de inverno – era o nono mês –, com um braseiro aceso em sua frente.

[[v30-36-23]]

^<<v30-36-23,23>>^ À medida que Judi acabava de ler três ou quatro colunas, cortava-as o rei com o canivete do escriba e as atirava às chamas do braseiro, até que todo o rolo foi consumido pelo fogo.

[[v30-36-24]]

^<<v30-36-24,24>>^ Nem o rei nem os ministros presentes à leitura se encheram de temor ou rasgaram suas vestes.

[[v30-36-25]]

^<<v30-36-25,25>>^ Nem mesmo quis o rei escutar os rogos que lhe dirigiram Elnatã, Delaías e Gemarias para que não queimasse o rolo.

[[v30-36-26]]

^<<v30-36-26,26>>^ Ordenou, a seguir, ao príncipe real Jaramiel, a Saraías, filho de Azriel e a Semeías, filho de Abdeel, que prendessem Baruc, o escriba, e o profeta Jeremias. O Senhor, porém, os escondeu.^&#42;1^

[[v30-36-27]]

^<<v30-36-27,27>>^ Depois que o rei queimou o rolo que continha os oráculos escritos por Baruc e que Jeremias lhe ditara, foi a palavra do Senhor dirigida ao profeta nestes termos:

[[v30-36-28]]

^<<v30-36-28,28>>^ “Toma outro rolo, e nele escreverás todos os oráculos contidos no primeiro, que foi queimado por Joaquin, rei de Judá.

[[v30-36-29]]

^<<v30-36-29,29>>^ E dirás ao rei: Eis o que diz o Senhor: Queimaste aquele rolo, dizendo: Por que nele escreveste a ameaça de que o rei da Babilônia viria arruinar esta terra, e exterminar-lhe os homens e os animais?

[[v30-36-30]]

^<<v30-36-30,30>>^ Pois bem, eis o que diz o Senhor a respeito de Joaquin, rei de Judá: Nenhum de seus descendentes ocupará o trono de Davi. Ficará seu cadáver exposto ao calor do dia e ao frio da noite.^&#42;1^

[[v30-36-31]]

^<<v30-36-31,31>>^ Castigarei assim a iniquidade nele, em sua raça e em seus servidores. E sobre eles, sobre os habitantes de Jerusalém e o povo de Judá, farei cair todos os flagelos de que os ameacei, sem que me houvessem escutado”.

[[v30-36-32]]

^<<v30-36-32,32>>^ Tomou Jeremias outro rolo e o entregou a Baruc, filho de Neerias, seu secretário, o qual nele escreveu, sob ditado do profeta, todos os oráculos contidos no rolo atirado ao fogo por Joaquin, rei de Judá. E vários outros oráculos lhes foram acrescentados.

'''

xref:030-jeremias/030-jeremias-035.adoc#v30-35-0[&#60; Capítulo Anterior] | <<v30-36-0,Topo>> | xref:030-jeremias/030-jeremias-037.adoc#v30-37-0[Próximo Capítulo &#62;]