include::./index.adoc[]

[[v14-11-0]]
=== II Crônicas, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 11 descreve a divisão do reino de Israel após a morte do rei Salomão, com dez tribos do norte se rebelando contra Roboão, filho de Salomão, que governou as duas tribos do sul. O capítulo também fala sobre as fortificações construídas por Roboão em Judá para se preparar para a guerra.
* 1 Reis 12:16: "Vendo, pois, todo o Israel que o rei não lhe dava ouvidos, o povo respondeu ao rei, dizendo: Que parte temos nós com Davi? Nem temos nós herança com o filho de Jessé; cada um para as suas tendas, ó Israel! Agora, pois, olha pela tua casa, ó Davi. E Israel se foi para as suas tendas." Este versículo fala sobre a rebelião das dez tribos do norte, que se separaram do reino de Judá.
* 2 Crônicas 12:1: "E sucedeu que, acabando Roboão de consolidar o reino, e fortalecendo-se, deixou a lei do Senhor, e todo o Israel com ele." Este versículo mostra que Roboão, após ter fortalecido seu reino, abandonou a lei de Deus e levou o povo com ele.
* Deuteronômio 20:1: "Quando saíres à peleja contra os teus inimigos, e vires cavalos, e carros, e povo mais numeroso do que tu, não os temerás; pois o Senhor teu Deus, que te tirou da terra do Egito, está contigo." Este versículo fala sobre a importância da confiança em Deus em momentos de guerra, que era uma preocupação para Roboão ao construir as fortificações.
* Provérbios 18:10: "Torre forte é o nome do Senhor; a ela correrá o justo, e estará em alto refúgio." Este versículo reforça o tema da construção de fortificações, mas lembra que a verdadeira segurança e proteção vem do nome do Senhor.
* Jeremias 17:5: "Assim diz o Senhor: Maldito o homem que confia no homem, e faz da carne o seu braço, e aparta o seu coração do Senhor." Este versículo lembra que, apesar das fortificações e preparações para a guerra, a confiança em Deus é a verdadeira chave para a vitória e a proteção.
****

[[v14-11-1]]

^<<v14-11-1,1>>^ De volta a Jerusalém, Roboão mo- bilizou as tribos de Judá e de Benjamim, em número de cento e oitenta mil guerreiros escolhidos, para atacar a casa de Israel e reintegrá-la ao reino de Roboão.

[[v14-11-2]]

^<<v14-11-2,2>>^ Mas a palavra do Senhor foi dirigida ao homem de Deus, Semeías, nestes termos:

[[v14-11-3]]

^<<v14-11-3,3>>^ “Dirige-te a Roboão, filho de Salomão, rei de Judá e a todos os de Israel que habitam em Judá e Benjamim.

[[v14-11-4]]

^<<v14-11-4,4>>^ Dize-lhes: Eis o que diz o Senhor: De modo algum ireis fazer guerra a vossos irmãos. Voltai cada qual para sua casa, pois é por mim que esses acontecimentos se realizaram”. Dóceis à palavra do Senhor, renunciaram a atacar Jeroboão e voltaram.

[[v14-11-5]]

^<<v14-11-5,5>>^ Roboão ficou, portanto, em Jerusalém. Construiu cidades fortes no território de Judá.

[[v14-11-6]]

^<<v14-11-6,6>>^ Construiu Belém, Etam, Tícua,

[[v14-11-7]]

^<<v14-11-7,7>>^ Betsur, Odolam,

[[v14-11-8]]

^<<v14-11-8,8>>^ Gat, Maresa, Zif,

[[v14-11-9]]

^<<v14-11-9,9>>^ Aduram, Laquis, Azeca,

[[v14-11-10]]

^<<v14-11-10,10>>^ Saraá, Aialon e Hebron, todas cidades fortificadas, situadas em Judá e Benjamim.

[[v14-11-11]]

^<<v14-11-11,11>>^ Fortificou esses lugares, nomeou para eles governadores e neles estabeleceu depósitos de víveres, óleo e vinho.

[[v14-11-12]]

^<<v14-11-12,12>>^ Fez em cada cidade um arsenal de escudos e de lanças, fazendo delas verdadeiras praças fortes. Judá e Benjamim ficavam-lhe, portanto, fiéis.

[[v14-11-13]]

^<<v14-11-13,13>>^ Os sacerdotes e levitas que habitavam no território de Israel vieram de todas as partes aderir ao seu partido.

[[v14-11-14]]

^<<v14-11-14,14>>^ Os levitas abandonaram suas terras e suas propriedades para irem habitar em Judá ou em Jerusalém, porque Jeroboão e seus filhos os tinham destituído de sua função de sacerdotes do Senhor.

[[v14-11-15]]

^<<v14-11-15,15>>^ Jeroboão, com efeito, nomeara sacerdotes para os lugares altos, para o culto dos bodes e dos touros que tinha feito.

[[v14-11-16]]

^<<v14-11-16,16>>^ Após os levitas, todos aqueles das tribos de Israel que procuravam de coração o Senhor, Deus de Israel, foram a Jerusalém para oferecer seus sacrifícios ao Senhor, o Deus de seus pais.

[[v14-11-17]]

^<<v14-11-17,17>>^ Vieram assim reforçar o reino de Judá e reafirmar o poder de Roboão, filho de Salomão. Isso durou três anos, pois durante um triênio seguiram o roteiro traçado por Davi e Salomão.

[[v14-11-18]]

^<<v14-11-18,18>>^ Roboão tomou por esposas Maalat, filha de Jarmut, filho de Davi e Abiail, filha de Eliab, filho de Jessé.

[[v14-11-19]]

^<<v14-11-19,19>>^ Esta lhe deu à luz os filhos: Jeús, Somorias e Zoom.

[[v14-11-20]]

^<<v14-11-20,20>>^ Depois dela, tomou por esposa Maaca, filha de Absalão, que lhe deu Abias, Etai, Ziza e Solomit.

[[v14-11-21]]

^<<v14-11-21,21>>^ Dentre todas as suas mulheres e concubinas, Roboão teve mais predileção por Maaca, filha de Absalão. Teve dezoito mulheres e sessenta concubinas; e gerou vinte e oito filhos e sessenta filhas.

[[v14-11-22]]

^<<v14-11-22,22>>^ Deu o primeiro lugar a Abias, filho de Maaca, na qualidade de chefe de seus irmãos, pois ele o destinava ao reino.

[[v14-11-23]]

^<<v14-11-23,23>>^ Teve muita habilidade para distribuir todos os seus filhos pelas praças fortes, pelas diversas regiões de Judá e de Benjamim; assegurou-lhes uma pensão copiosa e deu-lhes muitas mulheres.^&#42;1^

'''

xref:014-ii-cronicas/014-ii-cronicas-010.adoc#v14-10-0[&#60; Capítulo Anterior] | <<v14-11-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-012.adoc#v14-12-0[Próximo Capítulo &#62;]