include::./index.adoc[]

[[v14-33-0]]
=== II Crônicas, 33
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 33 de 2 Crônicas narra a história de Manassés, filho de Ezequias, que reinou em Judá por 55 anos e fez o que era mal aos olhos do Senhor, levando o povo à idolatria e à prática de abominações. A seguir estão cinco versículos relacionados com os temas abordados no capítulo:
* 2 Reis 21:9: "Porém eles não ouviram; e Manassés os fez extraviar mais do que as nações que o Senhor destruíra de diante dos filhos de Israel." Este versículo ilustra a extensão da apostasia de Manassés e como ela afetou não apenas ele, mas todo o povo de Judá.
* Isaías 55:7: "Deixe o ímpio o seu caminho, e o homem maligno os seus pensamentos, e se converta ao Senhor, que se compadecerá dele; torne para o nosso Deus, porque grandioso é em perdoar." Este versículo fala sobre a importância da conversão e do arrependimento, enfatizando que Deus é misericordioso e está disposto a perdoar aqueles que se voltam para ele.
* Salmo 32:5: "Confessei-te o meu pecado, e a minha maldade não encobri. Dizia eu: Confessarei ao Senhor as minhas transgressões; e tu perdoaste a maldade do meu pecado." Este salmo destaca a importância da confissão de pecados e como isso pode levar ao perdão e à restauração.
* 2 Crônicas 34:27: "Porque o teu coração se enterneceu, e te humilhaste perante Deus, ouvindo as suas palavras contra este lugar e contra os seus habitantes, e te humilhaste perante mim, e rasgaste as tuas vestes, e choraste perante mim, também eu te ouvi, diz o Senhor." Este versículo fala sobre a resposta de Deus à humildade e ao arrependimento, indicando que ele está disposto a perdoar e a ouvir aqueles que se voltam para ele.
* 2 Coríntios 7:10: "Porque a tristeza segundo Deus produz arrependimento para a salvação, que a ninguém traz pesar; mas a tristeza do mundo produz morte." Este versículo destaca a importância da tristeza e da dor na vida cristã, apontando que ela pode levar ao arrependimento e à salvação.
****

[[v14-33-1]]

^<<v14-33-1,1>>^ Manassés tinha a idade de doze anos quando começou a reinar e reinou cinquenta e cinco anos em Jerusalém.

[[v14-33-2]]

^<<v14-33-2,2>>^ Fez o mal aos olhos do Senhor, imitando as práticas abomináveis das nações que o Senhor tinha expulsado de diante dos israelitas.

[[v14-33-3]]

^<<v14-33-3,3>>^ Reconstruiu os lugares altos que seu pai Ezequias tinha destruído, erigiu altares ao deus Baal. Mandou fazer ídolos de madeira, asserás e prostrou-se diante do exército do céu ao qual prestou culto.

[[v14-33-4]]

^<<v14-33-4,4>>^ Chegou até a edificar altares no Templo do Senhor, esse templo do qual tinha dito: “Meu nome residirá em Jerusalém para sempre”.

[[v14-33-5]]

^<<v14-33-5,5>>^ Construiu altares para todo o exército do céu nos dois átrios do templo.

[[v14-33-6]]

^<<v14-33-6,6>>^ Fez passar pelo fogo seus próprios filhos no vale de Beninom. Entregou-se à astrologia, à adivinhação e à magia, praticou a necromancia e a bruxaria e multiplicou os atos que desagradavam ao Senhor, provocando-lhe assim a ira.

[[v14-33-7]]

^<<v14-33-7,7>>^ Erigiu no templo o ídolo que mandou fazer, do qual Deus tinha dito a Davi e a seu filho Salomão: “Neste templo e na cidade de Jerusalém, que escolhi dentre todas as tribos de Israel, farei residir meu nome para sempre.

[[v14-33-8]]

^<<v14-33-8,8>>^ Jamais removerei o pé de Israel do solo que dei a seus pais, contanto que ponham todo o cuidado em praticar meus mandamentos e a lei que lhes prescreveu Moisés, meu servo”.

[[v14-33-9]]

^<<v14-33-9,9>>^ Manassés arrastou Judá e os habitantes de Jerusalém a exceder em malícia todas as nações que o Senhor tinha aniquilado diante dos israelitas.

[[v14-33-10]]

^<<v14-33-10,10>>^ Falou, então, o Senhor a Manassés e a seu povo, mas eles não lhe deram atenção.

[[v14-33-11]]

^<<v14-33-11,11>>^ O Senhor fez, então, vir contra ele os generais do rei da Assíria, os quais puseram Manassés em ferros, prenderam-no com uma dupla cadeia de bronze e levaram-no para Babilônia.

[[v14-33-12]]

^<<v14-33-12,12>>^ Na sua angústia, ele implorou ao Senhor, seu Deus, e se humilhou profundamente diante do Deus de seus pais.

[[v14-33-13]]

^<<v14-33-13,13>>^ Ele dirigiu-lhe uma prece e o Senhor ouviu sua oração, reconduzindo-o a Jerusalém sobre seu trono. Manassés reconheceu desse modo que o Senhor era verdadeiramente Deus.

[[v14-33-14]]

^<<v14-33-14,14>>^ Depois disso, construiu um muro exterior na Cidade de Davi, a oeste, voltado para o Gion no vale, até a entrada da Porta dos Peixes. Essa muralha, muito elevada, cercava Ofel. Colocou também oficiais em todas as cidades fortes de Judá.

[[v14-33-15]]

^<<v14-33-15,15>>^ Fez desaparecer do Templo do Senhor os deuses falsos e o ídolo, assim como todos os altares que tinha há pouco tempo construído na montanha do templo e em Jerusalém e atirou-os para fora da cidade.

[[v14-33-16]]

^<<v14-33-16,16>>^ Reconstruiu o altar do Senhor, e ofereceu sacrifícios de ação de graças e louvor. Ordenou a Judá servir ao Senhor, Deus de Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ O povo continuava, todavia, a sacrificar nos lugares altos, mas somente ao Senhor, seu Deus.

[[v14-33-18]]

^<<v14-33-18,18>>^ Os outros atos de Manassés, a prece que dirigiu a seu Deus e as palavras dos videntes que lhe falaram em nome do Senhor, Deus de Israel, tudo isso está consignado nos atos dos reis de Israel.

[[v14-33-19]]

^<<v14-33-19,19>>^ Sua prece, a maneira como foi atendido, todas as suas faltas, suas revoltas, os sítios em que edificou lugares altos e erigiu asserás e outros ídolos, antes de se humilhar, tudo isso está consignado nas Atas de Hozai.

[[v14-33-20]]

^<<v14-33-20,20>>^ Manassés adormeceu entre seus pais e foi sepultado na sua casa. Seu filho Amon sucedeu-lhe no trono.

[[v14-33-21]]

^<<v14-33-21,21>>^ Amon tinha a idade de vinte e dois anos quando começou a reinar e reinou dois anos em Jerusalém.

[[v14-33-22]]

^<<v14-33-22,22>>^ Fez o mal aos olhos do Senhor, como seu pai Manassés, sacrificando e rendendo culto a todos os ídolos levantados por seu pai.

[[v14-33-23]]

^<<v14-33-23,23>>^ Mas não se humilhou diante do Senhor como ele; pelo contrário, sempre multiplicou seus delitos.

[[v14-33-24]]

^<<v14-33-24,24>>^ Seus servos se conjuraram contra ele e o mataram na sua própria casa.

[[v14-33-25]]

^<<v14-33-25,25>>^ Mas o povo da terra feriu os conjurados e proclamou rei, em seu lugar, seu filho Josias.

'''

xref:014-ii-cronicas/014-ii-cronicas-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-034.adoc#v14-34-0[Próximo Capítulo &#62;]