include::./index.adoc[]

[[v14-14-0]]
=== II Crônicas, 14
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 14 narra a história do rei Asa de Judá, que fez o que era bom e reto perante o Senhor, fortalecendo as cidades de Judá e vencendo uma grande batalha contra o exército etíope que o ameaçava. Os versículos selecionados são:
* Deuteronômio 20:4 - "Pois o Senhor, o seu Deus, os acompanha e lutará por vocês contra os seus inimigos, para dar a vitória a vocês." Este versículo ilustra como Asa foi vitorioso na batalha contra os etíopes porque contou com a ajuda de Deus.
* Provérbios 21:31 - "O cavalo é preparado para o dia da batalha, mas a vitória vem do Senhor." Este versículo destaca a importância de se preparar para a batalha, mas a vitória é concedida pelo Senhor.
* Salmos 33:16-17 - "O rei não se salva pelo tamanho do seu exército; o guerreiro não escapa pela sua grande força. O cavalo é vã esperança de vitória; apesar de sua grande força, é incapaz de salvar." Este versículo enfatiza que a vitória não depende apenas do tamanho ou da força do exército, mas da ajuda de Deus.
* 2 Crônicas 20:12 - "Não sabemos o que fazer, mas os nossos olhos se voltam para ti." Este versículo mostra a confiança de Asa em Deus e sua dependência da orientação divina.
* 2 Crônicas 20:17 - "Não precisarão lutar nessa batalha. Tomem suas posições; permaneçam firmes e vejam o livramento que o Senhor lhes dará, ó Judá e Jerusalém. Não tenham medo nem desanimem. Saiam para enfrentá-los amanhã, e o Senhor estará com vocês’". Este versículo mostra como Deus garantiu a vitória para Asa e seu exército sem a necessidade de lutar na batalha.
****

[[v14-14-1]]

^<<v14-14-1,1>>^ Abias adormeceu com seus pais e foi sepultado na Cidade de Davi. Seu filho Asa sucedeu-lhe no trono. Durante sua vida, a terra conheceu dez anos de tranquilidade.

[[v14-14-2]]

^<<v14-14-2,2>>^ Asa fez o que era bom e justo aos olhos do Senhor, seu Deus.

[[v14-14-3]]

^<<v14-14-3,3>>^ Destruiu os altares dos deuses estrangeiros e os lugares altos; quebrou as estelas e cortou as asserás.

[[v14-14-4]]

^<<v14-14-4,4>>^ Ordenou aos filhos de Judá que buscassem o Senhor, o Deus de seus pais, e que pusessem em prática a Lei e seus mandamentos.

[[v14-14-5]]

^<<v14-14-5,5>>^ Fez desaparecer de todas as cidades de Judá os lugares altos e os obeliscos. Sob seu reinado o reino esteve em paz.

[[v14-14-6]]

^<<v14-14-6,6>>^ Durante esse tempo de tranquilidade, construiu cidades fortificadas em Judá. Efetivamente, não houve guerra contra ele durante esses anos, porque o Senhor lhe concedeu descanso.

[[v14-14-7]]

^<<v14-14-7,7>>^ “Construamos – disse ele aos judeus – essas cidades e cerquemo-las de muralhas, torres, portas e ferrolhos. A terra está ainda livre diante de nós porque temos procurado o Senhor, nosso Deus, e por isso ele nos concedeu a paz com todos os nossos vizinhos.” Dispuseram-se, pois, a esse trabalho e o levaram a bom termo.

[[v14-14-8]]

^<<v14-14-8,8>>^ Asa possuía um exército composto de trezentos mil homens de Judá, que carregavam escudo e lança e um de duzentos e oitenta mil de Benjamim, que carregavam escudo e entesavam o arco, todos valentes guerreiros.^&#42;1^

[[v14-14-9]]

^<<v14-14-9,9>>^ Zara, o etíope, atacou-os com um exército de um milhão de homens e trezentos carros e avançou até Maresa.

[[v14-14-10]]

^<<v14-14-10,10>>^ Asa saiu-lhe ao encontro e eles se formaram para a batalha no vale de Sefata, perto de Maresa.

[[v14-14-11]]

^<<v14-14-11,11>>^ Asa invocou o Senhor, seu Deus, nestes termos: “Senhor, não vos é mais difícil ajudar o fraco do que o forte. Vinde em nosso socorro, nosso Deus! É em vós que nos apoiamos, é em vosso nome que viemos contra essa multidão. Senhor, vós sois nosso Deus; que não haja um só homem que prevaleça contra vós!”.

[[v14-14-12]]

^<<v14-14-12,12>>^ O Senhor feriu os etíopes diante de Asa e dos homens de Judá. Os etíopes fugiram.

[[v14-14-13]]

^<<v14-14-13,13>>^ Asa e seu exército os perseguiram até Gerara e deles tombou tão grande número que nem sequer um pôde salvar-se, destruídos como foram diante do Senhor e seu exército. Judá trouxe um grande despojo.

[[v14-14-14]]

^<<v14-14-14,14>>^ Eles feriram todas as cidades dos arredores de Gerara, pois o terror do Senhor se tinha infundido neles. Pilharam-nos, porque eles possuíam um importante despojo.

[[v14-14-15]]

^<<v14-14-15,15>>^ Feriram também os redis dos rebanhos e capturaram grande número de ovelhas e camelos. Em seguida, retornaram a Jerusalém.

'''

xref:014-ii-cronicas/014-ii-cronicas-013.adoc#v14-13-0[&#60; Capítulo Anterior] | <<v14-14-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-015.adoc#v14-15-0[Próximo Capítulo &#62;]