include::./index.adoc[]

[[v14-9-0]]
=== II Crônicas, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 9 relata a visita da rainha de Sabá ao rei Salomão, que impressionou-a com sua sabedoria e riquezas. Ela ofereceu presentes a Salomão, e o capítulo descreve a grandeza do rei e de seu reino.
* Provérbios 10:22: "A bênção do Senhor é que enriquece, e ele não acrescenta dores." Este versículo fala sobre como a verdadeira riqueza vem de Deus, e não pode ser alcançada apenas por meio de bens materiais, como os presentes que a rainha de Sabá ofereceu a Salomão.
* Eclesiastes 7:12: "Porque a sabedoria serve de defesa, como o dinheiro serve de defesa; mas a excelência do conhecimento é que a sabedoria dá vida ao seu possuidor." Este versículo enfatiza a importância da sabedoria, que foi um dos atributos que impressionou a rainha de Sabá em Salomão.
* Mateus 6:33: "Mas buscai primeiro o Reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas." Este versículo lembra-nos que devemos colocar Deus em primeiro lugar em nossas vidas, e que Ele nos fornecerá todas as coisas que precisamos.
* 1 Reis 10:23: "Assim o rei Salomão excedeu a todos os reis da terra, tanto em riquezas como em sabedoria." Este versículo reforça o tema principal de 2 Crônicas 9, que é a grandeza de Salomão como rei e sua sabedoria.
* Salmos 72:1-2: "Ó Deus, dá ao rei os teus juízos, e a tua justiça ao filho do rei. Julgue ele o teu povo com justiça, e os teus pobres com juízo." Este salmo é uma oração pelo bem-estar do rei, que é responsável por governar com justiça e cuidar de seu povo, como Salomão fez em seu reinado.
****

[[v14-9-1]]

^<<v14-9-1,1>>^ A rainha de Sabá, ouvindo falar da fama de Salomão, veio a Jerusalém para prová-lo por meio de enigmas. Ela tinha um séquito considerável, camelos carregados de aromas, grande quantidade de ouro e de pedras preciosas. Quando da sua visita a Salomão, expôs-lhe tudo o que tinha no coração.

[[v14-9-2]]

^<<v14-9-2,2>>^ Salomão respondeu a todas as suas perguntas e nada houve por demais obscuro que não pudesse solucionar.

[[v14-9-3]]

^<<v14-9-3,3>>^ Diante dessa sabedoria do rei, à vista da residência que tinha construído para si,

[[v14-9-4]]

^<<v14-9-4,4>>^ dos manjares de sua mesa, dos aposentos de seus servos, da habitação e vestes de seus domésticos, de seus copeiros e seus trajes, dos holocaustos que oferecia no Templo do Senhor, a rainha de Sabá ficou enlevada de admiração.^&#42;1^

[[v14-9-5]]

^<<v14-9-5,5>>^ “É, pois, verdade – disse ela ao rei – o que tinha ouvido dizer, em minha terra, a respeito de tuas obras e de tua sabedoria.

[[v14-9-6]]

^<<v14-9-6,6>>^ Não queria dar fé a isso antes de vir e ver com meus próprios olhos. Pois bem, o que me tinham descrito não era sequer a metade de tua imensa sabedoria; ultrapassas tudo o que soube de ti pela tua fama!

[[v14-9-7]]

^<<v14-9-7,7>>^ Felizes os teus servos! Felizes esses servos que sempre estão diante de ti e ouvem tua sabedoria!

[[v14-9-8]]

^<<v14-9-8,8>>^ Bendito seja o Senhor, teu Deus, que te tomou como objeto de afeição e te colocou no seu trono, como rei em nome do Senhor, teu Deus! É por causa de seu amor a Israel e porque quer fazê-lo subsistir para sempre que te fez rei, para que faças reinar o direito e a justiça!”

[[v14-9-9]]

^<<v14-9-9,9>>^ Em seguida, deu ao rei cento e vinte talentos de ouro, grande quantidade de aromas e pedras preciosas. Jamais se viram tantos aromas quantos os que a rainha de Sabá deu ao rei Salomão.

[[v14-9-10]]

^<<v14-9-10,10>>^ Os servos de Hiram e os servos de Salomão, que traziam o ouro de Ofir, trouxeram também madeira de sândalo e pedras preciosas.

[[v14-9-11]]

^<<v14-9-11,11>>^ Com essa madeira de sândalo o rei fez degraus para o Templo do Senhor e para o palácio real, harpas e liras para os cantores. Nunca ainda se tinha visto semelhante madeira na terra de Judá.

[[v14-9-12]]

^<<v14-9-12,12>>^ O rei Salomão presenteou a rainha de Sabá com tudo o que ela sonhava ganhar, com muito mais do que ela havia trazido. Depois ela retomou com seus servos o caminho de sua terra.^&#42;1^

[[v14-9-13]]

^<<v14-9-13,13>>^ O peso de ouro que Salomão recebia cada ano era de seiscentos e sessenta e seis talentos,

[[v14-9-14]]

^<<v14-9-14,14>>^ além do que lhe traziam os mercadores e “comerciantes”. Todos os reis da Arábia, como os governadores locais, traziam a Salomão um tributo de ouro e prata.

[[v14-9-15]]

^<<v14-9-15,15>>^ O rei Salomão mandou fabricar duzentos escudos de ouro batido, para cada um dos quais utilizou seiscentos siclos de ouro batido;

[[v14-9-16]]

^<<v14-9-16,16>>^ e trezentos pequenos escudos de ouro batido, para cada um dos quais empregou trezentos siclos de ouro. O rei colocou-os no palácio do Bosque do Líbano.

[[v14-9-17]]

^<<v14-9-17,17>>^ O rei mandou construir um grande trono de marfim, revestido de ouro puro.

[[v14-9-18]]

^<<v14-9-18,18>>^ Esse trono tinha seis degraus, com um escabelo de ouro fixado no trono. Nos dois lados do assento havia encostos flanqueados por leões.

[[v14-9-19]]

^<<v14-9-19,19>>^ Doze leões estavam colocados à direita e à esquerda, nos seis degraus. E não se fez um trono assim em nenhum reino.

[[v14-9-20]]

^<<v14-9-20,20>>^ Todas as taças do rei Salomão eram feitas de ouro e todo o vasilhame do palácio do Bosque do Líbano era de ouro puro. Isso porque no tempo de Salomão a prata não tinha valor.

[[v14-9-21]]

^<<v14-9-21,21>>^ Pois o rei tinha navios que iam a Társis com os servos de Hiram. Cada três anos a frota voltava de Társis, carregada de ouro, prata, marfim, macacos e pavões.

[[v14-9-22]]

^<<v14-9-22,22>>^ Dessa maneira, por sua riqueza e sabedoria, o rei Salomão avantajava-se a todos os reis da terra,

[[v14-9-23]]

^<<v14-9-23,23>>^ e todos procuravam sua presença, a fim de poderem ouvir a sabedoria que Deus lhe tinha infundido no coração.

[[v14-9-24]]

^<<v14-9-24,24>>^ Cada um lhe trazia anualmente seu presente: objetos de prata, objetos de ouro, vestimentas, armas, aromas, cavalos e mulas.

[[v14-9-25]]

^<<v14-9-25,25>>^ Salomão possuía cavalariças para quatro mil cavalos de carros e doze mil (cavalgaduras) para cavaleiros, que ele colocou nas cidades onde estavam abrigados seus carros assim como em Jerusalém, perto de si.

[[v14-9-26]]

^<<v14-9-26,26>>^ Ele dominava sobre todos os reis, desde o Eufrates até a terra dos filisteus e a fronteira do Egito.

[[v14-9-27]]

^<<v14-9-27,27>>^ Graças a ele, a prata tornou-se, em Jerusalém, tão comum como as pedras e os cedros tão numerosos como os sicômoros da planície.

[[v14-9-28]]

^<<v14-9-28,28>>^ Era do Egito e de todas as terras que se importavam cavalos para Salomão.

[[v14-9-29]]

^<<v14-9-29,29>>^ O restante dos feitos de Salomão, dos primeiros aos últimos, está relatado no livro do profeta Natã, na profecia de Aías de Silo e nas visões do vidente Ado a respeito de Jeroboão, filho de Nabat.^&#42;1^

[[v14-9-30]]

^<<v14-9-30,30>>^ O reinado de Salomão sobre todo o Israel durou quarenta anos, em Jerusalém.

[[v14-9-31]]

^<<v14-9-31,31>>^ Depois disso, Salomão adormeceu com seus pais e foi sepultado na Cidade de Davi, seu pai. Seu filho Roboão sucedeu-lhe no trono.

'''

xref:014-ii-cronicas/014-ii-cronicas-008.adoc#v14-8-0[&#60; Capítulo Anterior] | <<v14-9-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-010.adoc#v14-10-0[Próximo Capítulo &#62;]