include::./index.adoc[]

[[v14-7-0]]
=== II Crônicas, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 7 narra a conclusão da construção do Templo de Salomão e a sua dedicação a Deus. O capítulo descreve a glória de Deus que encheu o templo e a resposta de Deus à oração de Salomão. Também são registradas as celebrações realizadas em honra ao Senhor após a dedicação. A seguir estão cinco versículos relacionados aos temas abordados em 2 Crônicas 7:
* Salmos 27:4: "Uma coisa pedi ao Senhor, é o que procuro: que eu possa viver na casa do Senhor todos os dias da minha vida, para contemplar a bondade do Senhor e buscar sua orientação no seu templo." Este versículo destaca a importância do Templo como um lugar de adoração e busca da orientação divina.
* 2 Crônicas 6:40: "Agora, ó meu Deus, que os teus olhos estejam abertos e os teus ouvidos atentos à oração que eu te faço neste lugar." Esse versículo se refere à oração de Salomão pedindo que Deus ouça as orações feitas no Templo. É uma lembrança da importância da oração em um lugar consagrado a Deus.
* 1 Reis 8:11: "Os sacerdotes não puderam continuar a ministrar por causa da nuvem, pois a glória do Senhor encheu a casa do Senhor." Esse versículo descreve a glória de Deus que encheu o Templo após a sua conclusão, mostrando a importância da presença de Deus naquele lugar.
* Salmos 122:1: "Eu me alegrei quando me disseram: 'Vamos à casa do Senhor'". Esse versículo destaca a alegria de ir ao Templo e adorar ao Senhor em comunidade.
* 2 Crônicas 7:3: "Quando todos os filhos de Israel viram o fogo descer e a glória do Senhor sobre o templo, ajoelharam-se com o rosto em terra no pavimento, adoraram e deram graças ao Senhor, dizendo: 'Ele é bom! O seu amor dura para sempre'." Esse versículo registra a resposta do povo à manifestação da glória de Deus no Templo, mostrando a importância da adoração e da gratidão a Deus.
****

[[v14-7-1]]

^<<v14-7-1,1>>^ Quando Salomão terminou essa prece, desceu fogo do céu e consumiu o holocausto com os sacrifícios, e a glória do Senhor encheu o templo.

[[v14-7-2]]

^<<v14-7-2,2>>^ Os sacerdotes não podiam entrar no Templo do Senhor, tanta era a glória que enchia o edifício.

[[v14-7-3]]

^<<v14-7-3,3>>^ À vista do fogo que descia e da glória do Senhor que enchia o templo, toda a multidão de israelitas se prosternou com o rosto em terra sobre o pavimento e, prosternados, puseram-se a cantar: “Louvai o Senhor porque ele é bom, porque sua misericórdia é eterna”.

[[v14-7-4]]

^<<v14-7-4,4>>^ O rei e todo o povo ofereceram então um sacrifício em presença do Senhor.

[[v14-7-5]]

^<<v14-7-5,5>>^ Salomão imolou vinte e dois mil touros e cento e vinte mil ovelhas. Foi desse modo que o rei e o povo fizeram a dedicação do Templo de Deus.

[[v14-7-6]]

^<<v14-7-6,6>>^ Os sacerdotes mantinham-se em seus postos; igualmente os levitas com os instrumentos de música do Senhor, que Davi tinha mandado fazer para celebrar os louvores do Senhor, quando confiou-lhes essa função de cantar os louvores do Senhor: “Porque sua misericórdia é eterna”. Os sacerdotes diante deles tocavam trombetas, enquanto toda a multidão dos israelitas mantinha-se de pé.

[[v14-7-7]]

^<<v14-7-7,7>>^ Salomão consagrou a parte central do átrio, que está em frente da fachada do Templo do Senhor; ofereceu ali holocaustos e a gordura dos sacrifícios pacíficos, porque o altar de bronze que tinha feito não era suficiente para os holocaustos, oferendas e a gordura das vítimas.

[[v14-7-8]]

^<<v14-7-8,8>>^ A celebração dessa festa, presidida então por Salomão, para todo o povo de Israel durou sete dias. A multidão congregada, desde a entrada de Emat até a torrente do Egito, era enorme.

[[v14-7-9]]

^<<v14-7-9,9>>^ No oitavo dia, realizou-se a assembleia solene, pois tinham celebrado a dedicação do altar, assim como a festa, durante sete dias.

[[v14-7-10]]

^<<v14-7-10,10>>^ No vigésimo terceiro dia do sétimo mês, Salomão mandou o povo de volta para suas tendas; estavam todos alegres e contentes por causa dos benefícios que o Senhor tinha feito a Davi, a Salomão e a seu povo de Israel.

[[v14-7-11]]

^<<v14-7-11,11>>^ Acabara, pois, o rei, o templo e o palácio real. Tinha levado a bom termo tudo o que tencionava fazer no Templo do Senhor e em sua própria residência.

[[v14-7-12]]

^<<v14-7-12,12>>^ Durante a noite, o Senhor lhe apareceu: “Ouvi – disse ele – tua oração e escolhi este lugar para que seja o templo no qual me oferecerão sacrifícios.

[[v14-7-13]]

^<<v14-7-13,13>>^ Quando eu cerrar o céu e não houver mais chuva, quando ordenar aos gafanhotos que devorem a terra, ou quando enviar a peste contra meu povo,

[[v14-7-14]]

^<<v14-7-14,14>>^ se meu povo, sobre o qual foi invocado o meu nome, se humilhar, se procurar minha face para orar, se renunciar ao seu mau procedimento, escutarei do alto do céu e sanarei sua terra.

[[v14-7-15]]

^<<v14-7-15,15>>^ Doravante, meus olhos estarão abertos e meus ouvidos atentos às preces feitas neste lugar,

[[v14-7-16]]

^<<v14-7-16,16>>^ pois, para o futuro, escolho e consagro este templo para que meu nome nele resida para sempre; meus olhos e meu coração estarão nele para sempre.

[[v14-7-17]]

^<<v14-7-17,17>>^ Quanto a ti, se andares na minha presença como fez teu pai Davi, se puseres em prática tudo o que prescrevi, se observares minhas leis e meus preceitos,

[[v14-7-18]]

^<<v14-7-18,18>>^ elevarei o trono de tua realeza, como prometi a teu pai, dizendo-lhe que jamais lhe faltaria descendente que ocupasse o trono de Israel.

[[v14-7-19]]

^<<v14-7-19,19>>^ Mas se vos desviardes de mim e negligenciardes os preceitos e mandamentos que vos prescrevi, para servirdes a outros deuses e render-lhes culto,

[[v14-7-20]]

^<<v14-7-20,20>>^ então vos exterminarei da terra que vos dei e arrojarei para longe de mim este templo que consagrei a meu nome e dele farei para todas as nações pagãs objeto de fábula e de riso.

[[v14-7-21]]

^<<v14-7-21,21>>^ Este templo, tão excelso, será para todos os transeuntes um objeto de espanto. Eles dirão: ‘Como tratou o Senhor dessa maneira esta terra e este templo?’.

[[v14-7-22]]

^<<v14-7-22,22>>^ E responderão: ‘É porque abandonaram o Senhor, o Deus de seus pais, que os tinha tirado do Egito e se apegaram a outros deuses, prostrando-se diante deles e rendendo-lhes culto. Eis por que fez sobrevir a eles todas essas calamidades’.”

'''

xref:014-ii-cronicas/014-ii-cronicas-006.adoc#v14-6-0[&#60; Capítulo Anterior] | <<v14-7-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-008.adoc#v14-8-0[Próximo Capítulo &#62;]