include::./index.adoc[]

[[v14-22-0]]
=== II Crônicas, 22
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 22 relata a ascensão ao trono de Judá do rei Acazias, filho de Atalia, que governou por apenas um ano e seguiu o mau exemplo de sua mãe e do rei de Israel, Acabe. Abaixo estão cinco versículos relacionados aos temas abordados neste capítulo:
* 1 Reis 16:30-33: "E Acabe, filho de Onri, fez o que era mau aos olhos do Senhor, mais do que todos os que foram antes dele ... E Acabe fez um poste-ídolo e, assim, Acabe fez mais para provocar o Senhor, Deus de Israel, a ira do que todos os reis de Israel que foram antes dele." Este versículo menciona o rei Acabe de Israel, que é referenciado em 2 Crônicas 22:3 como um exemplo a ser seguido por Acazias.
* 1 Reis 21:25: "Não houve ninguém como Acabe, que se vendeu para fazer o mal aos olhos do Senhor, porque sua esposa, Jezabel, o incitava." Este versículo faz referência à esposa de Acabe, Jezabel, que também é mencionada em 2 Crônicas 22:2 como a mãe de Acazias.
* 2 Reis 9:30-37: Este é um relato da morte de Jezabel, que é mencionada em 2 Crônicas 22:2 como a mãe de Acazias. Embora não seja diretamente relacionado ao reinado de Acazias, é um exemplo de como a maldade de Jezabel afetou aqueles ao seu redor.
* Provérbios 22:8: "Aquele que semeia iniquidade colherá problemas, e a vara de sua raiva será destruída." Este versículo destaca a consequência da maldade, que é um tema presente no reinado de Acazias.
* Isaías 1:4: "Ah, nação pecadora, povo carregado de iniqüidade, descendência de malfeitores, filhos que se corromperam! Eles abandonaram o Senhor, desprezaram o Santo de Israel e o rejeitaram." Este versículo reflete a condição de Judá sob o reinado de Acazias, que se distanciou do Senhor e seguiu a maldade de sua mãe e do rei de Israel.
****

[[v14-22-1]]

^<<v14-22-1,1>>^ Em seu lugar, os habitantes de Jerusalém proclamaram rei Ocozias, seu filho mais jovem, pois o bando de árabes, que havia invadido o acampamento, tinha assassinado os mais velhos. Assim se tornou rei Ocozias, filho de Jorão, rei de Judá.

[[v14-22-2]]

^<<v14-22-2,2>>^ Tinha vinte e dois anos quando começou a reinar e reinou um ano em Jerusalém. Sua mãe chamava-se Atalia, filha de Amri.^&#42;1^

[[v14-22-3]]

^<<v14-22-3,3>>^ Também ele trilhou os caminhos da família de Acab, pois era impelido ao mal por sua mãe, que era sua conselheira.

[[v14-22-4]]

^<<v14-22-4,4>>^ Fez o mal aos olhos do Senhor, como tinham feito os da casa de Acab que, depois da morte de seu pai, o arrastaram à perda, por influência deles.

[[v14-22-5]]

^<<v14-22-5,5>>^ Foi segundo o conselho destes que se dirigiu a Ramot de Galaad com Jorão, filho de Acab, rei de Israel, para fazer a guerra contra Hazael, rei da Síria. Ferido pelos sírios,

[[v14-22-6]]

^<<v14-22-6,6>>^ Jorão retornou a Jezrael para cuidar das feridas recebidas em Ramot, na batalha contra Hazael, rei da Síria. Ocozias, filho de Jorão, rei de Judá, desceu a Jezrael para fazer uma visita a Jorão, filho de Acab, durante a enfermidade.

[[v14-22-7]]

^<<v14-22-7,7>>^ Foi da vontade de Deus que, para sua perda, Ocozias fosse visitar Jorão. Com efeito, tendo chegado lá, saiu com Jorão para combater Jeú, filho de Namsi, que o Senhor tinha ungido para exterminar a casa de Acab.

[[v14-22-8]]

^<<v14-22-8,8>>^ E como Jeú exercia a vingança divina) contra a casa de Acab, encontrou os chefes de Judá e os sobrinhos de Ocozias que estavam a serviço de seu tio e os matou.

[[v14-22-9]]

^<<v14-22-9,9>>^ Agarraram então o próprio Ocozias e o prenderam em Samaria, estava escondido. Levaram-no a Jeú e este o mandou matar. Foi-lhe dada uma sepultura, porque os homens diziam: “É um filho daquele Josafá, que buscara o Senhor de todo o seu coração”. Assim, não havia ninguém da família de Ocozias que estivesse em condições de reinar.

[[v14-22-10]]

^<<v14-22-10,10>>^ Quando Atalia, mãe de Ocozias, viu seu filho morto, resolveu exterminar toda a estirpe real da casa de Judá.

[[v14-22-11]]

^<<v14-22-11,11>>^ Mas Josaba, filha do rei, raptou Joás, filho de Ocozias, dentre os jovens príncipes que estavam sendo massacrados e o escondeu com sua ama de leite no dormitório. Josaba, filha de Jorão, irmã de Ocozias e mulher do sacerdote Joiada, escondeu-o assim das vistas de Atalia e ela não conseguiu matá-lo.

[[v14-22-12]]

^<<v14-22-12,12>>^ A criança esteve escondida junto delas, no templo, durante seis anos, enquanto Atalia reinava sobre a terra.

'''

xref:014-ii-cronicas/014-ii-cronicas-021.adoc#v14-21-0[&#60; Capítulo Anterior] | <<v14-22-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-023.adoc#v14-23-0[Próximo Capítulo &#62;]