include::./index.adoc[]

[[v14-12-0]]
=== II Crônicas, 12
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 12 de 2 Crônicas relata a queda do reino de Judá sob o governo do rei Roboão. Depois de se afastar do caminho do Senhor, o rei e o povo de Judá são punidos por Deus e invadidos pelos egípcios. Roboão e seus líderes se humilham diante do Senhor e buscam a Sua ajuda para livrá-los da opressão estrangeira. Abaixo estão cinco versículos relacionados aos temas abordados no capítulo:
* Salmos 34:18 - "Perto está o Senhor dos que têm o coração quebrantado e salva os de espírito oprimido." Este versículo fala sobre a importância de se humilhar diante de Deus em momentos de dificuldade, assim como Roboão e seus líderes fizeram quando foram invadidos pelos egípcios.
* Provérbios 28:14 - "Feliz é o homem constante no temor ao Senhor, mas o que endurece o coração cairá no mal." A queda de Judá ocorreu porque Roboão se afastou do caminho do Senhor e endureceu seu coração. Este versículo é um lembrete de que aqueles que temem ao Senhor e permanecem em Seus caminhos encontrarão a felicidade.
* 2 Crônicas 7:14 - "Se o meu povo, que se chama pelo meu nome, se humilhar, e orar, e buscar a minha face, e se desviar dos seus maus caminhos, então eu ouvirei do céu, e perdoarei os seus pecados, e sararei a sua terra." Este versículo fala sobre a importância de se arrepender e buscar o Senhor em tempos de dificuldade, assim como Roboão e seu povo fizeram.
* Jeremias 31:18 - "Certo é que, depois de me haver convertido, eu me arrependi; e, depois de ter sido instruído, bati no meu peito; envergonhei-me e confundi-me, porque suportei o opróbrio da minha mocidade." Este versículo mostra a importância do arrependimento e da humildade diante de Deus, mesmo após ter vivido uma vida de pecado, assim como Roboão e seu povo.
* Isaías 57:15 - "Porque assim diz o Alto e o Sublime, que habita na eternidade, e cujo nome é Santo: Num alto e santo lugar habito; como também com o contrito e abatido de espírito, para vivificar o espírito dos abatidos, e para vivificar o coração dos contritos." Este versículo destaca a importância da humildade e do arrependimento diante de Deus, e como Ele está sempre disposto a ouvir e perdoar aqueles que buscam a Sua ajuda.
****

[[v14-12-1]]

^<<v14-12-1,1>>^ Estando seu reino constituído e firmado, Roboão abandonou a Lei do Senhor e todo o Israel seguiu-lhe o exemplo.^&#42;1^

[[v14-12-2]]

^<<v14-12-2,2>>^ Durante o quinto ano de seu reinado, por causa dos pecados de Jerusalém contra o Senhor, Sesac, rei do Egito, veio atacar a cidade

[[v14-12-3]]

^<<v14-12-3,3>>^ com mil e duzentos carros e sessenta mil cavaleiros. Um inumerável exército de líbios, suquitas e etíopes o acompanhavam desde o Egito.

[[v14-12-4]]

^<<v14-12-4,4>>^ Apoderou-se das cidades fortes de Judá e chegou a Jerusalém.

[[v14-12-5]]

^<<v14-12-5,5>>^ O profeta Semeías dirigiu-se a Roboão e aos chefes de Judá que se tinham concentrado em Jerusalém, com a aproximação de Sesac. “Eis – disse-lhes ele – o que diz o Senhor: Vós me abandonastes, e eu também vos abandono nas mãos de Sesac.”

[[v14-12-6]]

^<<v14-12-6,6>>^ Então, os chefes israelitas e o rei se humilharam e disseram: “O Senhor é justo”.

[[v14-12-7]]

^<<v14-12-7,7>>^ Em vista deste ato de humildade, a palavra do Senhor foi dirigida a Semeías nestes termos: “Eles se humilharam e por isso não os destruirei. Vou dar-lhes em breve um meio de salvação. Minha ira não se desencadeará sobre Jerusalém pela mão de Sesac.

[[v14-12-8]]

^<<v14-12-8,8>>^ Mas eles terão que servir para que saibam distinguir entre o meu serviço e o serviço dos reis estrangeiros”.

[[v14-12-9]]

^<<v14-12-9,9>>^ Sesac, rei do Egito, atacou, pois, Jerusalém. Levou os tesouros do Templo do Senhor e os do palácio real, sem nada deixar. Levou especialmente os escudos de ouro que Salomão tinha fabricado.

[[v14-12-10]]

^<<v14-12-10,10>>^ Para substituí-los, o rei Roboão mandou fazer escudos de bronze e os entregou em mãos dos chefes das guardas da porta do palácio real.

[[v14-12-11]]

^<<v14-12-11,11>>^ Cada vez que o rei ia ao Templo do Senhor, esses guardas os levavam; em seguida, devolviam ao corpo da guarda.

[[v14-12-12]]

^<<v14-12-12,12>>^ Portanto, em virtude de seu ato de humildade, a ira do Senhor apartou-se dele e sua ruína não foi total. Em Judá havia ainda coisas boas.

[[v14-12-13]]

^<<v14-12-13,13>>^ Consolidou-se, pois, o rei Roboão, reinando em Jerusalém. Contava quarenta e um anos quando começou a reinar. Reinou dezessete anos em Jerusalém, a cidade que o Senhor tinha escolhido dentre todas as tribos de Israel, para nela estabelecer seu nome. Sua mãe tinha por nome Naama, a amonita.

[[v14-12-14]]

^<<v14-12-14,14>>^ Praticou o mal, não aplicando seu coração à busca do Senhor.

[[v14-12-15]]

^<<v14-12-15,15>>^ Os atos e feitos de Roboão, desde os primeiros até os últimos, estão relatados no livro do profeta Semeías e consignados com exatidão no do vidente Ado. A guerra entre Roboão e Jeroboão foi contínua.

[[v14-12-16]]

^<<v14-12-16,16>>^ Depois disso, Roboão adormeceu com seus pais e foi sepultado na Cidade de Davi. Seu filho Abias sucedeu-lhe no trono.^&#42;1^

'''

xref:014-ii-cronicas/014-ii-cronicas-011.adoc#v14-11-0[&#60; Capítulo Anterior] | <<v14-12-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-013.adoc#v14-13-0[Próximo Capítulo &#62;]