include::./index.adoc[]

[[v14-28-0]]
=== II Crônicas, 28
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 28 narra a história do rei Acaz de Judá, que não seguiu os caminhos do Senhor, mas se entregou à idolatria e à maldade. Ele fez aliança com os assírios, mas isso só trouxe mais problemas para o seu reino. Abaixo estão cinco versículos relacionados aos temas abordados neste capítulo:
* Deuteronômio 12:31: "Não façais, pois, assim para com o Senhor, vosso Deus; porque toda coisa abominável que o Senhor aborrece fizeram eles para com seus deuses; pois até seus filhos e suas filhas queimaram no fogo aos seus deuses." Este versículo fala sobre a importância de não praticar a idolatria e de evitar tudo o que é abominável ao Senhor. Acaz, no entanto, se entregou a essas práticas.
* Salmos 106:36-37: "Serviram a seus ídolos, que se tornaram um laço para eles. Sacrificaram seus filhos e suas filhas aos demônios." Este salmo fala sobre como os filhos de Israel se afastaram de Deus e se entregaram à idolatria, inclusive sacrificando seus filhos aos ídolos. Acaz também sacrificou seus filhos aos deuses pagãos.
* Isaías 7:2: "Então, anunciaram à casa de Davi, dizendo: A Síria fez aliança com Efraim. E tremeu o seu coração e o coração do seu povo, como se tremem as árvores do bosque com o vento." Este versículo fala sobre como Acaz ficou com medo quando soube que a Síria e Efraim haviam feito aliança contra ele. Isso o levou a buscar ajuda dos assírios, em vez de confiar em Deus.
* Jeremias 2:19: "A tua maldade te castigará, e as tuas apostasias te repreenderão; sabe, pois, e vê, que mal e quão amargo é deixares ao Senhor, teu Deus, e não teres em ti o meu temor, diz o Senhor Deus dos Exércitos." Este versículo fala sobre como a maldade e a apostasia trazem consequências amargas. Acaz colheu os frutos da sua desobediência e falta de temor ao Senhor.
* Oséias 8:7: "Porque semearam ventos, e segarão tormentas; não haverá seara; a erva não dará farinha; e se a der, os estrangeiros a engolirão." Este versículo fala sobre como aqueles que plantam sementes de maldade colherão a tempestade. Acaz plantou sementes de idolatria e alianças com nações pagãs, e isso resultou em tormento para o seu povo.
****

[[v14-28-1]]

^<<v14-28-1,1>>^ Acaz tinha a idade de vinte anos quando começou a reinar. Reinou dezesseis anos em Jerusalém. Não fez o bem aos olhos do Senhor, como havia feito Davi, seu pai,

[[v14-28-2]]

^<<v14-28-2,2>>^ mas seguiu o exemplo dos reis de Israel. Fez até imagens de metal fundido aos Baal.

[[v14-28-3]]

^<<v14-28-3,3>>^ Queimou perfumes no vale de Beninon e fez passar seus filhos pelo fogo, segundo o abominável costume das nações que o Senhor tinha afastado de diante dos israelitas.

[[v14-28-4]]

^<<v14-28-4,4>>^ Oferecia sacrifícios e perfumes nos lugares altos, nas colinas e debaixo de toda árvore verdejante.

[[v14-28-5]]

^<<v14-28-5,5>>^ O Senhor, seu Deus, o entregou às mãos do rei da Síria. Os sírios o derrotaram e fizeram um grande número de prisioneiros que foram deportados para Damasco. Ele também foi entregue às mãos do rei de Israel, que lhe infligiu grande derrota.

[[v14-28-6]]

^<<v14-28-6,6>>^ Faceia, filho de Romelias, matou, num só dia, cento e vinte mil homens de Judá, todos aguerridos, porque tinham abandonado o Senhor, o Deus de seus pais.

[[v14-28-7]]

^<<v14-28-7,7>>^ Zecri, um guerreiro de Efraim, matou Maasias, de estirpe real e Ezricam, chefe do palácio, assim como Elcana, o segundo depois do rei.

[[v14-28-8]]

^<<v14-28-8,8>>^ Os israelitas fizeram dentre seus irmãos duzentos mil prisioneiros, mulheres, jovens e donzelas; fizeram também um imenso despojo, que levaram para Samaria.

[[v14-28-9]]

^<<v14-28-9,9>>^ Ora, havia ali um profeta do Senhor, chamado Oded, o qual saiu ao encontro do exército que entrava em Samaria e lhes disse: “Vede! Na sua ira contra Judá, o Senhor, o Deus de vossos pais, vo-los entregou e vós os matastes com uma fúria tal, que subiu até o céu.

[[v14-28-10]]

^<<v14-28-10,10>>^ E agora quereis oprimir os homens de Judá e de Jerusalém até fazer deles vossos escravos e escravas. Mas, entre vós não há também prevaricações contra o Senhor, vosso Deus?

[[v14-28-11]]

^<<v14-28-11,11>>^ Escutai-me! Mandai de volta os cativos que fizestes entre vossos irmãos, pois a ira do Senhor vos ameaça”.

[[v14-28-12]]

^<<v14-28-12,12>>^ Levantaram-se então alguns dos chefes dos efraimitas. Eram eles Azarias, filho de Joanã, Baraquias, filho de Mesolamot, Ezequias, filho de Selum e Amasa, filho de Hadali. Eles se opuseram aos que voltavam do exército.

[[v14-28-13]]

^<<v14-28-13,13>>^ “Não introduzireis aqui esses cativos” – disseram-lhes eles. “Quereis que nos tornemos culpados contra o Senhor e que aumentemos assim as nossas faltas que já são suficientemente numerosas? A ira do Senhor já ameaça Israel.”

[[v14-28-14]]

^<<v14-28-14,14>>^ Então, na presença dos chefes e da multidão, os soldados soltaram os presos e abandonaram os despojos.

[[v14-28-15]]

^<<v14-28-15,15>>^ Em seguida, os homens, cujos nomes acabam de ser citados, acolheram os cativos. Revestiram, com vestes tiradas dos despojos, aqueles que estavam nus e os calçaram; deram-lhes comida e bebida, ungiram-nos e mandaram-nos a Jericó, a cidade das palmeiras, junto de seus irmãos, tendo colocado sobre jumentos todos os que se achavam extenuados. Depois disso, voltaram para Samaria.

[[v14-28-16]]

^<<v14-28-16,16>>^ Naquele tempo, o rei Acaz mandou pedir socorro aos reis da Assíria,

[[v14-28-17]]

^<<v14-28-17,17>>^ pois os edomitas tinham voltado para combater os judeus e levá-los prisioneiros.

[[v14-28-18]]

^<<v14-28-18,18>>^ Os filisteus tinham também invadido as cidades da planície e do Negueb, de Judá; tinham tomado Bet-Sames, Aialon, Gederot, Soco e as cidades que delas dependiam, Tamna e seus arrabaldes, Gamzo e seus arrabaldes e nelas se estabeleceram.

[[v14-28-19]]

^<<v14-28-19,19>>^ O Senhor humilhava Judá por causa de Acaz, rei de Israel, que tinha soltado os freios em Judá e cometido graves delitos contra o Senhor.^&#42;1^

[[v14-28-20]]

^<<v14-28-20,20>>^ Teglat-Falasar, rei da Assíria, em vez de dar-lhe apoio, atacou-o e oprimiu-o.

[[v14-28-21]]

^<<v14-28-21,21>>^ Em vão Acaz tinha despojado o Templo do Senhor, o palácio real e os príncipes para fazer presentes ao rei da Assíria. Tudo isso de nada lhe valeu.

[[v14-28-22]]

^<<v14-28-22,22>>^ Embora estivesse angustiado, o rei Acaz continuou seus crimes contra o Senhor.

[[v14-28-23]]

^<<v14-28-23,23>>^ Oferecia sacrifícios aos deuses de Damasco, que o tinham derrotado: “São – dizia ele – os deuses dos reis da Síria que lhes vêm em auxílio. Portanto, vou lhes oferecer sacrifícios para que me ajudem igualmente”. Mas foram a causa de sua queda e de todo o Israel.

[[v14-28-24]]

^<<v14-28-24,24>>^ Acaz juntou todos os utensílios do templo e os fez em pedaços. Cerrou as portas do Templo do Senhor, fabricou altares em todos os cantos de Jerusalém,

[[v14-28-25]]

^<<v14-28-25,25>>^ assim como lugares altos em cada uma das cidades de Judá para neles oferecer incenso aos deuses falsos. Assim ele exasperava o Senhor, o Deus de seus pais.

[[v14-28-26]]

^<<v14-28-26,26>>^ Seus outros atos, seus feitos e façanhas, dos primeiros aos últimos, tudo isso está relatado no Livro dos Reis de Judá e de Israel.

[[v14-28-27]]

^<<v14-28-27,27>>^ Adormeceu com seus pais e foi sepultado na cidade, em Jerusalém, pois não o colocaram nos sepulcros dos reis de Israel. Seu filho Ezequias sucedeu-lhe no trono.

'''

xref:014-ii-cronicas/014-ii-cronicas-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-029.adoc#v14-29-0[Próximo Capítulo &#62;]