include::./index.adoc[]

[[v14-13-0]]
=== II Crônicas, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 13 narra a guerra entre Abias, rei de Judá, e Jeroboão, rei de Israel, que havia se rebelado contra Roboão e formado um reino separado ao norte. Durante a batalha, Abias faz um discurso em que lembra o povo de Judá da aliança que Deus fez com Davi e seus descendentes, e como essa aliança lhes dava a vantagem moral sobre Israel.
* Salmos 78:9: "Os filhos de Efraim, armados e trazendo arcos, viraram as costas no dia da peleja." Este versículo fala sobre a traição e deserção de uma tribo de Israel durante uma batalha, o que poderia ter sido semelhante à traição de Jeroboão por alguns de seus homens.
* Salmos 78:35: "E se lembraram de que Deus era a sua rocha, e o Deus Altíssimo o seu Redentor." Este versículo lembra a importância de confiar em Deus e lembrar das suas promessas durante momentos difíceis, como a batalha entre Judá e Israel.
* Salmos 78:71: "De após as ovelhas deu-o a pastorear, e a Jacó, seu povo, a Israel, sua herança." Este versículo fala sobre como Deus escolheu Davi, um simples pastor de ovelhas, para ser o rei de Israel e liderar seu povo, lembrando a aliança feita com Davi que Abias menciona em seu discurso.
* Isaías 55:3: "Inclinai os ouvidos, e vinde a mim; ouvi, e a vossa alma viverá; porque convosco farei um pacto perpétuo, dando-vos as firmes beneficências de Davi." Este versículo fala sobre o convite de Deus para seu povo, oferecendo a eles a vida e uma aliança perpétua, que pode ser interpretada como uma referência à aliança de Deus com Davi que Abias menciona.
* Salmos 33:16: "Não há rei que se salve com o grande exército; nem o homem valente se livra pela muita força." Este versículo lembra que a vitória em uma batalha não depende apenas do tamanho ou força do exército, mas também da vontade de Deus e da justiça da causa.
****

[[v14-13-1]]

^<<v14-13-1,1>>^ No décimo oitavo ano do reinado de Jeroboão, Abias tornou-se rei de Judá e reinou três anos em Jerusalém.

[[v14-13-2]]

^<<v14-13-2,2>>^ Sua mãe chamava-se Maaca, filha de Uriel de Gabaá.

[[v14-13-3]]

^<<v14-13-3,3>>^ Abias e Jeroboão fizeram guerra entre si. Abias encetou as operações com um exército de quatrocentos mil valentes guerreiros de escol. Jeroboão dispôs contra ele oitocentos mil valentes guerreiros de escol.

[[v14-13-4]]

^<<v14-13-4,4>>^ De pé, no alto do monte Semaraim, que está na montanha de Efraim, Abias gritou: “Escutai-me, Jeroboão, e todo o Israel!

[[v14-13-5]]

^<<v14-13-5,5>>^ Não deveríeis vós saber que o Senhor, Deus de Israel, deu para sempre o reino de Israel a Davi e a seus filhos, em virtude de uma aliança inviolável?

[[v14-13-6]]

^<<v14-13-6,6>>^ Jeroboão, filho de Nabat, servo de Salomão, filho de Davi, orgulhosamente revoltou-se contra seu senhor.

[[v14-13-7]]

^<<v14-13-7,7>>^ Homens maus e perversos juntaram-se a ele e se opuseram a Roboão, filho de Salomão. Roboão, que era jovem ainda e tímido, não pôde resistir-lhes.

[[v14-13-8]]

^<<v14-13-8,8>>^ E agora, pensais em oferecer resistência ao Reino do Senhor, que está nas mãos do filho de Davi. Vós sois uma grande multidão e tendes convosco os bezerros de ouro que Jeroboão fez para vós à maneira de deuses.

[[v14-13-9]]

^<<v14-13-9,9>>^ Demitistes os sacerdotes do Senhor, os filhos de Aarão e os levitas, instituindo para vós sacerdotes, à maneira dos pagãos. Todo o que veio com um novilho e sete carneiros para se consagrar, tornou-se sacerdote dos falsos deuses.

[[v14-13-10]]

^<<v14-13-10,10>>^ Para nós, é o Senhor o nosso Deus e não o abandonamos. Os filhos de Aarão é que são sacerdotes a serviço do Senhor e são os levitas que desempenham as funções.

[[v14-13-11]]

^<<v14-13-11,11>>^ Cada manhã e cada tarde queimam em honra do Senhor os holocaustos e o incenso aromático. Os pães da proposição são dispostos na mesa pura e cada tarde são acendidas as lâmpadas do candelabro de ouro. É porque nós observamos a Lei do Senhor, nosso Deus, enquanto vós o abandonastes.

[[v14-13-12]]

^<<v14-13-12,12>>^ Vede: Deus e seus sacerdotes estão conosco à nossa frente e temos as trombetas retumbantes para fazê-las soar contra vós. Israelitas, não luteis contra o Senhor, Deus de vossos pais, porque isso não vos trará nenhuma felicidade”.

[[v14-13-13]]

^<<v14-13-13,13>>^ Então, Jeroboão executou uma manobra com as tropas colocadas em emboscada, dando uma volta, para surpreender o inimigo pelas costas, de sorte que seu exército fazia frente a Judá e a emboscada se encontrava à retaguarda.

[[v14-13-14]]

^<<v14-13-14,14>>^ As tropas de Judá, ao se voltarem, viram-se atacadas pela frente e pela retaguarda. Invocaram então o Senhor, enquanto os sacerdotes tocavam a trombeta.

[[v14-13-15]]

^<<v14-13-15,15>>^ Judá soltou o grito de guerra e enquanto ecoava esse clamor, Deus feriu Jeroboão e todo o Israel diante de Abias e de Judá.

[[v14-13-16]]

^<<v14-13-16,16>>^ Os israelitas fugiram diante dos homens de Judá, às mãos dos quais Deus os entregou.

[[v14-13-17]]

^<<v14-13-17,17>>^ Abias e seu exército fizeram uma grande matança: quinhentos mil guerreiros escolhidos do campo de Israel tombaram feridos de morte.

[[v14-13-18]]

^<<v14-13-18,18>>^ Isso foi, naquele tempo, humilhante para os israelitas, enquanto que os filhos de Judá obtiveram a vitória, porque se apoiaram no Senhor, o Deus de seus pais.

[[v14-13-19]]

^<<v14-13-19,19>>^ Abias perseguiu Jeroboão e dele arrebatou várias cidades: Betel, Jesana

[[v14-13-20]]

^<<v14-13-20,20>>^ e Efron, assim como as localidades que delas dependiam. No tempo de Abias, Jeroboão não se restabeleceu.

[[v14-13-21]]

^<<v14-13-21,21>>^ O Senhor o feriu e ele morreu, enquanto o poder de Abias aumentava. Abias tomou por esposas catorze mulheres; gerou vinte e dois filhos e dezesseis filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ O restante dos atos e feitos de Abias, assim como suas palavras, está relatado nos discursos do profeta Ado.

'''

xref:014-ii-cronicas/014-ii-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]