include::./index.adoc[]

[[v14-8-0]]
=== II Crônicas, 8
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 8 relata como Salomão construiu várias cidades e fortalezas, além de estabelecer rotas comerciais e tributos para o reino de Israel. Ele também construiu um palácio para si mesmo e um para a filha do faraó, que se tornou sua esposa. Aqui estão cinco versículos relacionados aos temas abordados em 2 Crônicas 8:
* 1 Reis 9:10-11: "Ao fim de vinte anos, em que Salomão edificou as duas casas, a saber, a casa do SENHOR e a casa do rei, Hirão, rei de Tiro, fornecia a Salomão madeira de cedro e de pinho e ouro, segundo todo o seu desejo; então, deu o rei Salomão a Hirão vinte cidades na terra da Galileia." Este versículo fala sobre o acordo entre Salomão e o rei Hirão para fornecer madeira e ouro para a construção do templo e do palácio, bem como a doação de cidades por Salomão a Hirão.
* 1 Reis 9:14: "E Hirão mandou ao rei cento e vinte talentos de ouro." Este versículo descreve a contribuição do rei Hirão de Tiro para a construção do templo e do palácio.
* 2 Crônicas 9:23: "E todos os reis da terra procuravam ver a face de Salomão, para ouvirem a sabedoria que Deus lhe tinha posto no coração." Este versículo fala sobre a fama e a reputação de Salomão como um sábio rei que era respeitado por outros governantes.
* 1 Reis 9:28: "E vieram seus servos, os que sabiam navegar no mar, juntamente com os servos de Salomão, a Ofir, e tomaram de lá quatrocentos e vinte talentos de ouro e os trouxeram ao rei Salomão." Este versículo descreve uma das expedições comerciais de Salomão para Obir, de onde ele trouxe uma grande quantidade de ouro.
* 1 Reis 10:26: "Também ajuntou Salomão carros e cavaleiros; tinha mil e quatrocentos carros e doze mil cavaleiros; e os distribuiu pelas cidades dos carros e junto ao rei em Jerusalém." Este versículo fala sobre a expansão militar de Salomão, que acumulou uma grande quantidade de carros e cavaleiros para proteger seu reino.
****

[[v14-8-1]]

^<<v14-8-1,1>>^ Ao cabo de vinte anos, Salomão tinha construído o Templo do Senhor e sua própria residência.

[[v14-8-2]]

^<<v14-8-2,2>>^ Reconstruiu também as cidades que Hiram lhe tinha dado e nelas estabeleceu os israelitas.

[[v14-8-3]]

^<<v14-8-3,3>>^ Em seguida, atacou Emat de Soba e se apoderou dela.

[[v14-8-4]]

^<<v14-8-4,4>>^ Construiu Tadmor no deserto e todas as localidades que serviam de entreposto na terra de Emat.

[[v14-8-5]]

^<<v14-8-5,5>>^ Construiu Bet-Horon superior e Bet-Horon inferior, cidades fortificadas providas de muralhas, portas e ferrolhos.

[[v14-8-6]]

^<<v14-8-6,6>>^ Construiu Baalat e todas as localidades que lhe serviam de entrepostos de aprovisionamento, as cidades para os carros, as cidades para a cavalaria e tudo quanto achou bom construir em Jerusalém, no Líbano e em todo o território submetido ao seu poder.

[[v14-8-7]]

^<<v14-8-7,7>>^ Toda a população que tinha sobrevivido dos hititas, dos amorreus, dos ferezeus, dos heveus e dos jebuseus, tudo o que não era de Israel –

[[v14-8-8]]

^<<v14-8-8,8>>^ todos os descendentes desses povos que tinham ficado na terra sem que Israel tivesse podido exterminar –, Salomão submeteu-os como pessoal de trabalho pesado, o que são ainda hoje.

[[v14-8-9]]

^<<v14-8-9,9>>^ Nenhum israelita foi empregado nos trabalhos de Salomão como escravo: foram seus guerreiros, chefes de suas tropas de eleição, comandantes de seus carros e de sua cavalaria.

[[v14-8-10]]

^<<v14-8-10,10>>^ Os contramestres do rei, colocados à frente dos obreiros, eram em número de duzentos e cinquenta.

[[v14-8-11]]

^<<v14-8-11,11>>^ Salomão mandou buscar a filha do faraó da Cidade de Davi para a residência que tinha construído para ela. “Minha mulher – disse ele – não deve habitar na casa de Davi, rei de Israel. Essa habitação, na qual entrou a arca do Senhor, é um santuário.”

[[v14-8-12]]

^<<v14-8-12,12>>^ Então, Salomão ofereceu ao Senhor holocaustos no seu altar, que tinha construído diante do pórtico.

[[v14-8-13]]

^<<v14-8-13,13>>^ Cada dia oferecia os sacrifícios prescritos por Moisés; igualmente, aos sábados, nas neomênias e nas três festas do ano: festa dos Ázimos, festa das Semanas e festa dos Tabernáculos.

[[v14-8-14]]

^<<v14-8-14,14>>^ Conforme as disposições tomadas por seu pai Davi, empossou as diversas classes de sacerdotes em suas funções, assim como os levitas, em seus ministérios de louvar o Senhor e no seu serviço cotidiano em presença dos sacerdotes; finalmente, os porteiros para cada porta, de acordo com sua categoria. Assim tinha mandado Davi, o homem de Deus.

[[v14-8-15]]

^<<v14-8-15,15>>^ Em nada se afastaram das disposições que tinha tomado com referência aos sacerdotes, aos levitas e ao que se relacionava com os tesouros.

[[v14-8-16]]

^<<v14-8-16,16>>^ Dessa forma, foi levada a efeito toda a obra de Salomão, desde a fundação do templo até seu acabamento. O Templo do Senhor estava, pois, terminado.

[[v14-8-17]]

^<<v14-8-17,17>>^ Então, Salomão dirigiu-se a Asiongaber e a Elat, nas praias do mar, na terra de Edom.

[[v14-8-18]]

^<<v14-8-18,18>>^ Hiram enviou-lhe, por meio de seus servos, navios e marinheiros experimentados. Eles foram a Ofir com os servos de Salomão e de lá trouxeram ao rei quatrocentos e cinquenta talentos de ouro.

'''

xref:014-ii-cronicas/014-ii-cronicas-007.adoc#v14-7-0[&#60; Capítulo Anterior] | <<v14-8-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-009.adoc#v14-9-0[Próximo Capítulo &#62;]