include::./index.adoc[]

[[v14-34-0]]
=== II Crônicas, 34
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 34 relata a história do rei Josias, que se tornou rei de Judá aos oito anos de idade. Durante o seu reinado, ele fez uma grande reforma religiosa, restaurando o templo do Senhor e eliminando a idolatria. Aqui estão cinco versículos relacionados aos temas deste capítulo:
* 2 Reis 22:19: "Porquanto o teu coração se enterneceu, e te humilhaste perante o Senhor, quando ouviste o que falei contra este lugar, e contra os seus moradores, que seriam para assolação e para maldição, e rasgaste as tuas vestes, e choraste perante mim, também eu te ouvi, diz o Senhor." Este versículo fala sobre a resposta de Deus à humildade e arrependimento de Josias. Josias demonstrou um coração quebrantado diante do Senhor e Deus ouviu a sua oração.
* Deuteronômio 12:4: "Não fareis assim ao Senhor vosso Deus." Este versículo fala sobre a importância de adorar a Deus da maneira correta e evitar a idolatria. Josias reconheceu a importância de seguir as leis de Deus e eliminou toda forma de idolatria em Judá.
* 2 Reis 22:8: "Então o sumo sacerdote Hilquias disse a Safã, o escrivão: Achei o livro da lei na casa do Senhor. E Hilquias deu o livro a Safã, e ele o leu." Este versículo fala sobre a descoberta do livro da lei no templo. Este foi um momento crucial na reforma religiosa de Josias, pois o livro da lei ajudou a orientar as suas reformas.
* 2 Reis 23:3: "E o rei pôs-se em pé junto à coluna, e fez uma aliança perante o Senhor, de que seguiria ao Senhor, e guardaria os seus mandamentos, e os seus testemunhos, e os seus estatutos, de todo o coração, e de toda a alma, confirmando as palavras desta aliança, que estavam escritas naquele livro; e todo o povo apoiou esta aliança." Este versículo descreve como Josias renovou a aliança com o Senhor e comprometeu-se a seguir os seus mandamentos. Isso foi um passo importante na reforma religiosa que ele liderou em Judá.
* 2 Reis 23:25: "E antes dele não houve rei semelhante a ele, que se convertesse ao Senhor com todo o seu coração, e com toda a sua alma, e com todas as suas forças, conforme toda a lei de Moisés; e depois dele nunca se levantou outro igual." Este versículo fala sobre a importância da liderança de Josias na reforma religiosa em Judá. Ele foi um exemplo de um líder que buscou ao Senhor de todo o coração e incentivou o povo a fazer o mesmo.
****

[[v14-34-1]]

^<<v14-34-1,1>>^ Josias tinha a idade de oito anos quando começou a reinar e reinou trinta e um anos em Jerusalém.

[[v14-34-2]]

^<<v14-34-2,2>>^ Fez o bem aos olhos do Senhor, seguindo as pegadas de Davi, seu pai, sem se afastar nem para a direita, nem para a esquerda.

[[v14-34-3]]

^<<v14-34-3,3>>^ No oitavo ano de seu reinado, quando ele era ainda criança, começou a buscar o Deus de Davi, seu pai, e no décimo segundo ano começou a limpar Judá e Jerusalém dos lugares altos, das asserás e dos outros ídolos de madeira ou de metal fundido.

[[v14-34-4]]

^<<v14-34-4,4>>^ Demoliram, em sua presença, os altares dos baals, e ele próprio destruiu os obeliscos que estavam colocados nesses altares. Fez em pedaços os bosques sagrados, os ídolos, as estelas; ele os reduziu a pó, que aspergiu sobre as tumbas de seus devotos.

[[v14-34-5]]

^<<v14-34-5,5>>^ Queimou os ossos dos sacerdotes nos seus altares. Foi assim que purificou Judá e Jerusalém.

[[v14-34-6]]

^<<v14-34-6,6>>^ Fez o mesmo nas cidades de Manassés, de Efraim e até mesmo de Neftali, no meio de suas ruínas.

[[v14-34-7]]

^<<v14-34-7,7>>^ Demoliu os altares, quebrou e reduziu a pó as asserás e os ídolos e destruiu todos os obeliscos em toda a terra de Israel. Em seguida retornou a Jerusalém.

[[v14-34-8]]

^<<v14-34-8,8>>^ No décimo oitavo ano de seu reinado, depois de ter purificado a terra e o templo, o rei encarregou Safã, filho de Aslias, Maasias, governador da cidade, e o arquivista Joá, filho de Joacaz, da restauração do Templo do Senhor, seu Deus.

[[v14-34-9]]

^<<v14-34-9,9>>^ Apresentaram-se estes ao sumo sacerdote Helcias e lhe entregaram o dinheiro trazido ao templo, o que os levitas tinham recolhido de Manassés, de Efraim, de todo o resto de Israel, assim como de Judá, de Benjamim e dos habitantes de Jerusalém.

[[v14-34-10]]

^<<v14-34-10,10>>^ Puseram esse dinheiro nas mãos dos empreiteiros e dos vigias dos trabalhos do templo, os quais o distribuíram aos que trabalhavam na restauração do edifício.

[[v14-34-11]]

^<<v14-34-11,11>>^ Estes o entregaram aos carpinteiros e aos pedreiros para a compra de pedras de cantaria e madeiras de carpintaria, assim como traves destinadas às construções que os reis de Judá tinham deixado cair em ruínas.

[[v14-34-12]]

^<<v14-34-12,12>>^ Esses homens cumpriram fielmente sua tarefa. Tinham como inspetores para dirigi-los Jaat e Abdias, levitas da linhagem de Merari, Zacarias e Mesolam, da linhagem dos caatitas, assim como outros levitas que eram todos entendidos em música.

[[v14-34-13]]

^<<v14-34-13,13>>^ Estes últimos vigiavam os carregadores e dirigiam todos os trabalhadores, segundo sua especialidade. Havia ainda levitas secretários, comissários e porteiros.

[[v14-34-14]]

^<<v14-34-14,14>>^ No momento em que se retirava o dinheiro que tinha sido levado ao Templo do Senhor, o sacerdote Helcias descobriu o Livro da Lei do Senhor, dada por Moisés.

[[v14-34-15]]

^<<v14-34-15,15>>^ Disse então Helcias ao escriba Safã: “Encontrei o Livro da Lei no templo”. E ele o entregou a Safã.

[[v14-34-16]]

^<<v14-34-16,16>>^ Este o levou ao rei e fez-lhe o seguinte relato: “Teus servos fizeram tudo o que lhes confiaste:

[[v14-34-17]]

^<<v14-34-17,17>>^ tiraram o dinheiro que estava no templo e o puseram nas mãos dos empreiteiros dos trabalhos”.

[[v14-34-18]]

^<<v14-34-18,18>>^ “Por outra parte – acrescentou ele –, o sacerdote Helcias me entregou um livro.” E começou a lê-lo em presença do rei.

[[v14-34-19]]

^<<v14-34-19,19>>^ Ouvindo as palavras da Lei, este rasgou suas vestes.

[[v14-34-20]]

^<<v14-34-20,20>>^ Em seguida, deu esta ordem a Helcias, a Aicam, filho de Safã, a Abdon, filho de Micas, ao escriba Safã e ao seu servo Asaías:

[[v14-34-21]]

^<<v14-34-21,21>>^ “Ide e consultai o Senhor de minha parte e da parte do que resta em Israel e em Judá, a respeito das palavras deste livro que acabam de encontrar; pois grande é a ira do Senhor, que se desencadeou sobre nós porque nossos pais não observaram a palavra do Senhor, não pondo em prática tudo o que está escrito neste livro”.

[[v14-34-22]]

^<<v14-34-22,22>>^ Helcias e aqueles que o rei tinha designado foram ter com a profetisa Hulda, mulher de Selum, filho de Tícua, filho de Haraas, guarda do vestiário, a qual habitava em Jerusalém, no segundo distrito. Quando lhe transmitiram sua mensagem,

[[v14-34-23]]

^<<v14-34-23,23>>^ ela lhes respondeu: “Eis o que diz o Senhor, Deus de Israel: ‘Dizei àquele que vos envia a mim: Eis o que diz o Senhor:

[[v14-34-24]]

^<<v14-34-24,24>>^ Vou fazer vir sobre este lugar e sobre os habitantes todas as calamidades, todas as maldições escritas neste livro que foi lido na presença do rei de Judá,

[[v14-34-25]]

^<<v14-34-25,25>>^ porque eles me abandonaram e ofereceram incenso aos deuses falsos, irritando-me com todas as suas maneiras de agir; meu furor se inflamará contra este lugar, sem que se possa jamais extingui-lo.

[[v14-34-26]]

^<<v14-34-26,26>>^ Ao rei de Judá que vos enviou a consultar o Senhor, assim lhe direis: eis o que diz o Senhor, Deus de Israel, a respeito das palavras que ouviste:

[[v14-34-27]]

^<<v14-34-27,27>>^ porquanto teu coração se comoveu e te humilhaste diante de Deus, escutando o que eu disse contra esta terra e seus habitantes; porquanto te humilhaste diante de mim, rasgaste tuas vestes chorando, eu também te ouvirei – oráculo do Senhor.

[[v14-34-28]]

^<<v14-34-28,28>>^ Vou reunir-te a teus pais; serás depositado em paz nas suas tumbas; teus olhos nada verão da catástrofe que vou mandar a este lugar e aos seus habitantes’.” Eles referiram ao rei esta resposta.

[[v14-34-29]]

^<<v14-34-29,29>>^ Então, Josias convocou todos os anciãos de Judá e de Jerusalém.

[[v14-34-30]]

^<<v14-34-30,30>>^ Depois, ele próprio subiu ao templo, seguido de todos os anciãos de Judá e de Jerusalém, os sacerdotes, os levitas e todo o povo, desde o maior até o menor. E fez-lhes uma leitura integral do Livro da Aliança, encontrado no Templo do Senhor.

[[v14-34-31]]

^<<v14-34-31,31>>^ O rei, de pé num estrado, fez, na presença do Senhor, um pacto no qual se comprometia a seguir o Senhor, a guardar seus mandamentos, suas ordens e seus preceitos, de todo o coração e de toda a sua alma e a pôr em prática todas as palavras da aliança escrita no livro.

[[v14-34-32]]

^<<v14-34-32,32>>^ Fez com que aderissem todos os que se encontravam em Jerusalém e em Benjamim; e os habitantes de Jerusalém fizeram segundo a aliança de Deus, do Deus de seus pais.

[[v14-34-33]]

^<<v14-34-33,33>>^ Josias fez, desse modo, desaparecer as abominações de toda a terra dos israelitas e impôs a todos que lá se encontravam que servissem o Senhor, seu Deus. Enquanto ele viveu, não se afastaram do Senhor, o Deus de seus pais.

'''

xref:014-ii-cronicas/014-ii-cronicas-033.adoc#v14-33-0[&#60; Capítulo Anterior] | <<v14-34-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-035.adoc#v14-35-0[Próximo Capítulo &#62;]