include::./index.adoc[]

[[v14-36-0]]
=== II Crônicas, 36
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 36 de 2 Crônicas narra o fim do reino de Judá e a queda de Jerusalém para a Babilônia, cumprindo as profecias de Deus sobre a punição do povo por sua desobediência. Entre os temas abordados, destacam-se a desobediência do povo, a liderança negligente dos reis, a destruição de Jerusalém e a esperança de restauração futura. A seguir, cinco versículos relacionados com esses temas:
* Jeremias 25:11-12: "Toda esta terra será reduzida a deserto e objeto de zombaria, e estas nações servirão ao rei da Babilônia durante setenta anos. Mas, quando se completarem os setenta anos, castigarei o rei da Babilônia e sua nação, por causa de seus pecados, e farei da terra dos caldeus um deserto perpétuo." Este versículo antecipa a queda da Babilônia após setenta anos e mostra que Deus usou a nação para punir Judá por seus pecados.
* 2 Reis 24:10-11: "Naquele tempo subiram contra Jerusalém os servos de Nabucodonosor, rei da Babilônia, e a cidade foi cercada. Nabucodonosor veio também pessoalmente à cidade enquanto seus servos a sitiavam." Este versículo descreve o cerco de Jerusalém pela Babilônia e a presença do rei Nabucodonosor durante o ataque.
* Jeremias 39:2: "No décimo dia do quarto mês do ano décimo primeiro do reinado de Zedequias, entraram na cidade os oficiais do rei da Babilônia e a ocuparam." Este versículo mostra o momento em que Jerusalém foi tomada pela Babilônia e a cidade foi destruída.
* Lamentações 2:9: "Seus portões caíram por terra; seus ferrolhos foram quebrados e destruídos. Seus reis e seus príncipes estão exilados entre as nações, sem encontrar lei nem profeta. As visões dos profetas não passam de farsas vazias." Este versículo descreve a destruição de Jerusalém e a falta de liderança e orientação espiritual do povo.
* Esdras 1:1-2: "No primeiro ano de Ciro, rei da Pérsia, para que se cumprisse a palavra do Senhor dita pela boca de Jeremias, o Senhor inspirou Ciro, rei da Pérsia, a fazer esta proclamação por escrito em todo o seu reino: ‘Assim fala Ciro, rei da Pérsia: O Senhor, o Deus do céu, entregou-me todos os reinos da terra e encarregou-me de construir um templo para ele em Jerusalém, que fica em Judá." Este versículo traz a esperança de restauração e reconstrução do templo de Jerusalém após o exílio na Babilônia, cumprindo as profecias de Jeremias e mostrando a fidelidade de Deus em cumprir suas promessas.
****

[[v14-36-1]]

^<<v14-36-1,1>>^ A população da terra elegeu então Joacaz, filho de Josias, e o estabeleceu rei no lugar de seu pai, em Jerusalém.

[[v14-36-2]]

^<<v14-36-2,2>>^ Joacaz tinha vinte e três anos quando começou a reinar e reinou três meses em Jerusalém.

[[v14-36-3]]

^<<v14-36-3,3>>^ O rei do Egito destronou-o em Jerusalém e impôs à terra uma contribuição de cem talentos de prata e um talento de ouro.

[[v14-36-4]]

^<<v14-36-4,4>>^ Em seguida, pôs no trono de Jerusalém o irmão de Joacaz, Eliacim, de quem mudou o nome para Joaquim. Quanto ao seu irmão Joacaz, Necao o mandou para o Egito.

[[v14-36-5]]

^<<v14-36-5,5>>^ Joaquim tinha a idade de vinte e cinco anos quando foi elevado ao trono e reinou durante onze anos em Jerusalém. Fez o mal aos olhos do Senhor, seu Deus.

[[v14-36-6]]

^<<v14-36-6,6>>^ Nabucodonosor, rei da Babilônia, atacou-o e o ligou com uma dupla cadeia de bronze para conduzi-lo a Babilônia,

[[v14-36-7]]

^<<v14-36-7,7>>^ levando ao mesmo tempo os objetos do templo para o seu palácio em Babilônia.

[[v14-36-8]]

^<<v14-36-8,8>>^ Os outros atos de Joaquim, suas abominações, tudo o de que ele se tornou culpado, está relatado no Livro dos Reis de Judá e de Israel. Seu filho Joaquin sucedeu-lhe no trono.

[[v14-36-9]]

^<<v14-36-9,9>>^ Joaquin tinha a idade de dezoito anos quando foi elevado ao trono e reinou três meses em Jerusalém. Fez o mal aos olhos do Senhor.^&#42;1^

[[v14-36-10]]

^<<v14-36-10,10>>^ No ano-novo, o rei Nabucodonosor mandou que fosse levado para Babilônia com os objetos preciosos do Templo do Senhor. Substituiu-o, no trono de Judá e de Jerusalém, Sedecias, irmão de seu pai.

[[v14-36-11]]

^<<v14-36-11,11>>^ Sedecias tinha a idade de vinte e um anos quando foi elevado ao trono e reinou onze anos em Jerusalém.

[[v14-36-12]]

^<<v14-36-12,12>>^ Fez o mal aos olhos do Senhor, seu Deus, e não se humilhou diante do profeta Jeremias que lhe tinha vindo falar da parte do Senhor.

[[v14-36-13]]

^<<v14-36-13,13>>^ Revoltou-se contra o rei Nabucodonosor que contudo, lhe tinha feito prestar um juramento em nome de Deus. Endureceu a cerviz e tornou inflexível seu coração para não se converter ao Senhor, Deus de Israel.

[[v14-36-14]]

^<<v14-36-14,14>>^ Todos os chefes dos sacerdotes e o povo continuaram a multiplicar seus delitos, imitando as práticas abomináveis das nações pagãs e profanando o templo que o Senhor tinha consagrado para si em Jerusalém.

[[v14-36-15]]

^<<v14-36-15,15>>^ Em vão o Senhor, o Deus de seus pais, lhes tinha enviado, por meio de seus mensageiros, avisos sobre avisos, pois tinha compaixão de seu povo e de sua própria habitação.

[[v14-36-16]]

^<<v14-36-16,16>>^ Eles zombavam de seus enviados, desprezavam seus conselhos e riam de seus profetas, até que a ira de Deus se desencadeou sobre o seu povo e não houve mais remédio.

[[v14-36-17]]

^<<v14-36-17,17>>^ Então, Deus suscitou contra eles o rei dos caldeus que, no próprio edifício do santuário, mandou matar seus jovens e não poupou o adolescente, nem a donzela, nem o ancião, nem a mulher de cabelos brancos. O Senhor lhe entregou tudo.

[[v14-36-18]]

^<<v14-36-18,18>>^ Nabucodonosor mandou tirar todo o mobiliário do templo, tanto os objetos grandes como os pequenos, os tesouros do templo, os do palácio real e os dos chefes, para transportá-los a Babilônia.

[[v14-36-19]]

^<<v14-36-19,19>>^ Incendiaram o templo, destruíram os muros de Jerusalém, entregaram às chamas seus palácios e todos os tesouros foram lançados à destruição.

[[v14-36-20]]

^<<v14-36-20,20>>^ Nabucodonosor deportou para a Babilônia todos os que tinham escapado à espada e eles se tornaram seus escravos, dele e de seus filhos, até o advento do domínio persa.

[[v14-36-21]]

^<<v14-36-21,21>>^ Assim se cumpria a profecia que o Senhor tinha dado pela boca de Jeremias – Até que a terra desfrutasse os seus sábados –, pois a terra ficou inculta durante todo esse período de desolação, até que se completaram setenta anos.^&#42;1^

[[v14-36-22]]

^<<v14-36-22,22>>^ No primeiro ano de Ciro, rei da Pérsia, a fim de que se cumprisse a profecia do Senhor, posta na boca de Jeremias, o Senhor excitou o espírito de Ciro, rei da Pérsia, e este mandou fazer em todo o seu reino, à viva voz e também por escrito, a seguinte proclamação:

[[v14-36-23]]

^<<v14-36-23,23>>^ “Assim fala Ciro, rei da Pérsia: O Senhor, Deus do céu, deu-me todos os reinos da terra e me encarregou de lhe construir um templo em Jerusalém, que está na terra de Judá. Todo aquele dentre vós que for de seu povo, esteja seu Deus com ele e que ele para lá se dirija!”.^&#42;1^

'''

xref:014-ii-cronicas/014-ii-cronicas-035.adoc#v14-35-0[&#60; Capítulo Anterior] | <<v14-36-0,Topo>> | xref:015-esdras/015-esdras-001.adoc#v15-1-0[Próximo Capítulo &#62;]