include::./index.adoc[]

[[v14-6-0]]
=== II Crônicas, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 6 descreve a dedicação do templo de Salomão, com Salomão pedindo a Deus para abençoar e ouvir as orações daqueles que vêm ao templo para buscar o Senhor. Ele também faz uma oração de dedicação, pedindo a Deus que esteja presente no templo e atenda às orações que são feitas ali. Abaixo estão cinco versículos relacionados aos temas abordados em 2 Crônicas 6:
* 1 Reis 8:27: "Mas, na verdade, habitaria Deus na terra? Eis que os céus, e até o céu dos céus, não te podem conter, quanto menos esta casa que tenho edificado." Esse verso faz parte da oração de Salomão e reconhece que Deus é grande demais para ser contido em um único lugar, como o templo.
* 1 Reis 8:41-43: "E também, acerca do estrangeiro, que não é do teu povo Israel, quando vier de terras remotas, por amor do teu nome (porque ouvirão da tua grandeza, e da tua mão forte, e do teu braço estendido), e orar voltado para esta casa, ouve tu nos céus, lugar da tua habitação, e faze conforme a tudo o que o estrangeiro te pedir; a fim de que todos os povos da terra conheçam o teu nome, para te temerem como o teu povo Israel." Esses versos fazem parte da oração de Salomão, pedindo que Deus ouça as orações daqueles que vêm de outros países para adorá-Lo no templo e que todos os povos conheçam a grandeza de Deus.
* Salmos 132:13-14: "Porque o Senhor escolheu a Sião; desejou-a para a sua habitação, dizendo: Este é o meu lugar de repouso para sempre; aqui habitarei, pois o desejei." Esses versos mostram o desejo de Deus de habitar em Sião, onde o templo de Salomão foi construído.
* Isaías 56:7: "Também os levarei ao meu santo monte, e os alegrarei na minha casa de oração; os seus holocaustos e os seus sacrifícios serão aceitos no meu altar; porque a minha casa será chamada casa de oração para todos os povos." Esse verso mostra como o templo é visto como um lugar de oração e adoração para todos os povos.
* João 4:21-24: "Disse-lhe Jesus: Mulher, crê-me que a hora vem, em que nem neste monte, nem em Jerusalém adorareis o Pai. Vós adorais o que não sabeis; nós adoramos o que sabemos porque a salvação vem dos judeus. Mas a hora vem, e agora é, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade; porque o Pai procura a tais que assim o adorem." Esses versos mostram como a adoração a Deus não está limitada a um lugar físico, mas deve ser em espírito e em verdade.
****

[[v14-6-1]]

^<<v14-6-1,1>>^ Então, disse Salomão: “O Senhor deseja habitar na escuridão.

[[v14-6-2]]

^<<v14-6-2,2>>^ Construí, portanto, uma casa que será vossa morada eterna”.

[[v14-6-3]]

^<<v14-6-3,3>>^ Voltou-se, em seguida, para a assembleia que estava de pé e a abençoou.

[[v14-6-4]]

^<<v14-6-4,4>>^ “Bendito seja – disse ele – o Senhor, Deus de Israel, que pela sua própria boca falou a Davi, meu pai, e que pela sua mão, realizou suas promessas. Ele tinha dito:

[[v14-6-5]]

^<<v14-6-5,5>>^ ‘Desde o dia em que fiz sair meu povo do Egito, não escolhi uma cidade dentre todas as tribos de Israel para nela construir um templo onde meu nome fosse invocado e não escolhi um homem para que fosse chefe de meu povo de Israel.

[[v14-6-6]]

^<<v14-6-6,6>>^ Mas escolhi Jerusalém como lugar de residência para meu nome e Davi como rei de meu povo de Israel’.

[[v14-6-7]]

^<<v14-6-7,7>>^ Ora, meu pai Davi desejava edificar um templo para a glória do Senhor, Deus de Israel.

[[v14-6-8]]

^<<v14-6-8,8>>^ Mas o Senhor lhe disse: ‘Tiveste uma feliz inspiração de edificar um templo para a glória de meu nome.

[[v14-6-9]]

^<<v14-6-9,9>>^ Somente, não és tu que me hás de construir, será teu filho, o filho procedente de tuas entranhas, que o fará’.

[[v14-6-10]]

^<<v14-6-10,10>>^ O Senhor realizou sua predição. Sucedi a meu pai Davi e ocupei o trono de Israel, como disse o Senhor e construí o templo ao nome do Senhor, Deus de Israel.

[[v14-6-11]]

^<<v14-6-11,11>>^ Pus a arca onde se encontra colocada a aliança feita entre o Senhor e os israelitas.”

[[v14-6-12]]

^<<v14-6-12,12>>^ Em seguida, Salomão postou-se diante do altar do Senhor, em presença de toda a assembleia de Israel e estendeu as mãos para o céu.

[[v14-6-13]]

^<<v14-6-13,13>>^ Com efeito, ele mandara construir uma tribuna de bronze, erguida no meio do átrio, de cinco côvados de comprimento, cinco de largura e três de altura. Nela subiu e, de joelhos, voltado para a multidão dos israelitas, com os braços levantados para o céu, disse:

[[v14-6-14]]

^<<v14-6-14,14>>^ “Senhor, Deus de Israel, não há nem no céu nem na terra um deus que seja comparável a vós, que seja fiel à sua aliança com seus servos e cheio de misericórdia para com os que vos servem de todo o coração.

[[v14-6-15]]

^<<v14-6-15,15>>^ Cumpristes a promessa que fizestes a meu pai Davi, vosso servo. Neste dia, vossa mão realizou o que vossa boca havia anunciado.

[[v14-6-16]]

^<<v14-6-16,16>>^ Dignai-vos, portanto, agora, Senhor, Deus de Israel, cumprir também a promessa que fizestes a meu pai Davi, vosso servo, de que jamais lhe faltaria diante de vós um descendente que ocupasse o trono de Israel, contanto que seus filhos atendam ao seu procedimento e observem vossa lei como ele mesmo a observou.

[[v14-6-17]]

^<<v14-6-17,17>>^ Assim, pois, Senhor, Deus de Israel, dignai-vos ratificar a promessa que fizestes a vosso servo Davi!

[[v14-6-18]]

^<<v14-6-18,18>>^ Mas, é verdade que Deus habita com os homens sobre a terra? Se os céus e os céus dos céus não vos podem conter, muito menos ainda esta casa que eu construí!

[[v14-6-19]]

^<<v14-6-19,19>>^ Contudo, Senhor, meu Deus, atendei à prece suplicante de vosso servo, acolhei o clamor e os votos que ele vos dirige.

[[v14-6-20]]

^<<v14-6-20,20>>^ Que de dia e de noite vossos olhos estejam abertos para esta casa, para este lugar em que prometestes fazer a residência de vosso nome. Escutai o pedido que vosso servo vos apresenta.

[[v14-6-21]]

^<<v14-6-21,21>>^ Escutai a súplica de vosso servo e de vosso povo de Israel, quando vierem orar neste lugar. Escutai-os de vossa morada celeste, escutai e perdoai!

[[v14-6-22]]

^<<v14-6-22,22>>^ Se um homem pecar contra seu próximo e lhe for exigido juramento, se ele vier jurar diante de vosso altar, neste templo,

[[v14-6-23]]

^<<v14-6-23,23>>^ escutai-o do alto do céu, agi e julgai vossos servos de modo a condenar o culpado, fazendo recair sobre ele o peso de sua falta e de modo a justificar o inocente tratando-o de acordo com sua inocência.

[[v14-6-24]]

^<<v14-6-24,24>>^ Quando vosso povo de Israel, por ter pecado contra vós, for subjugado pelo inimigo, se ele retornar a vós, render glória ao vosso nome, entrar neste templo para dirigir-vos preces e súplicas,

[[v14-6-25]]

^<<v14-6-25,25>>^ escutai-o do alto do céu e perdoai o pecado de vosso povo de Israel, reconduzindo-o à terra que lhe destes a ele e a seus pais.

[[v14-6-26]]

^<<v14-6-26,26>>^ Se o céu vier a se fechar e não chover mais, por terem eles pecado contra vós e vierem a orar neste lugar, rendendo glória ao vosso nome e arrependendo-se de seu pecado por causa de vosso castigo,

[[v14-6-27]]

^<<v14-6-27,27>>^ escutai-os do alto do céu, perdoai o pecado de vossos servos e de vosso povo de Israel. Mostrai-lhes o reto caminho que devem seguir e concedei chuva à terra que destes como herança a vosso povo.

[[v14-6-28]]

^<<v14-6-28,28>>^ Quando a terra for assolada pela fome, peste, ferrugem, mangra, gafanhoto, pulgão, quando os inimigos cercarem as cidades da terra de Israel, ou se houver uma calamidade ou uma epidemia qualquer,

[[v14-6-29]]

^<<v14-6-29,29>>^ e um homem, ou todo o povo de Israel, vos dirigir uma prece suplicante e cada qual, reconhecendo sua chaga dolorosa, estender as mãos para este templo,

[[v14-6-30]]

^<<v14-6-30,30>>^ escutai-o do alto do céu, de vossa morada e perdoai, concedendo a cada um o que merece, vós que conheceis seu coração, pois só vós conheceis o coração do homem.

[[v14-6-31]]

^<<v14-6-31,31>>^ É assim que eles vos temerão e andarão em vossos caminhos durante toda a sua vida na terra que destes a seus pais.

[[v14-6-32]]

^<<v14-6-32,32>>^ Quando o estrangeiro, sem pertencer a Israel, teu povo, vier de uma terra longínqua, atraído pela fama de vosso nome e do poder de vosso braço, para rezar neste templo,

[[v14-6-33]]

^<<v14-6-33,33>>^ escutai-o do alto do céu, lá onde habitais e concedei a esse estrangeiro tudo o que vos pedir. Todos os povos da terra conhecerão assim vosso nome e vos temerão como vosso povo de Israel, cientes de que vosso nome é invocado sob este templo que vos construí.

[[v14-6-34]]

^<<v14-6-34,34>>^ Quando vosso povo fizer guerra contra seus inimigos em qualquer direção à qual vós o enviardes e ele vos invocar, voltando-se para esta cidade de vossa escolha e para este templo que construí à glória de vosso nome,

[[v14-6-35]]

^<<v14-6-35,35>>^ escutai do alto do céu suas preces suplicantes e fazei-lhe justiça.

[[v14-6-36]]

^<<v14-6-36,36>>^ Quando tiverem pecado contra vós, – pois não há homem algum sem pecado –, quando em vossa ira os entregardes ao inimigo e o vencedor os deportar para uma terra estrangeira, longínqua ou próxima,

[[v14-6-37]]

^<<v14-6-37,37>>^ e lá na terra de seu exílio, entrarem em si e retornarem a vós, dizendo-vos em tom de súplica: ‘Pecamos, cometemos a iniquidade, fizemos o mal’;

[[v14-6-38]]

^<<v14-6-38,38>>^ se eles retornarem a vós de todo o seu coração e de toda a sua alma, na terra do exílio ou onde estiverem deportados e vos dirigirem sua oração, voltando-se para a pátria que destes a seus pais, para a cidade de vossa predileção e para este templo que construí à glória de vosso nome,

[[v14-6-39]]

^<<v14-6-39,39>>^ escutai do alto do céu, lá onde habitais, suas preces súplices, fazei-lhes justiça e perdoai a vosso povo os pecados cometidos contra vós.

[[v14-6-40]]

^<<v14-6-40,40>>^ Por conseguinte, doravante, ó meu Deus, que vossos olhos estejam abertos e vossos ouvidos atentos a (toda) prece feita neste lugar!

[[v14-6-41]]

^<<v14-6-41,41>>^ Senhor Deus, vinde, pois, habitar nesta moradia, vós e a arca onde reside vosso poder. Senhor Deus, que vossos sacerdotes estejam revestidos de força salutar e que vossos devotos desfrutem de sua felicidade!

[[v14-6-42]]

^<<v14-6-42,42>>^ Senhor Deus, não repilais a prece daquele que vos é consagrado, em memória dos favores que concedestes a vosso servo Davi.”

'''

xref:014-ii-cronicas/014-ii-cronicas-005.adoc#v14-5-0[&#60; Capítulo Anterior] | <<v14-6-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-007.adoc#v14-7-0[Próximo Capítulo &#62;]