include::./index.adoc[]

[[v14-16-0]]
=== II Crônicas, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Crônicas 16 descreve a vida do rei Asa de Judá, incluindo seu relacionamento com Deus e suas escolhas políticas. Após um período de paz e prosperidade, Asa entra em uma aliança com o rei da Síria, em vez de confiar em Deus, e se torna doente. Abaixo estão cinco versículos relacionados com os temas abordados em 2 Crônicas 16, em ordem de similaridade:
* Salmos 20:7: "Alguns confiam em carros e outros em cavalos, mas nós confiamos no nome do Senhor nosso Deus." Este versículo fala sobre a importância da confiança em Deus, em vez de confiar em coisas materiais, como carros e cavalos, para nossa segurança e proteção.
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." Este versículo enfatiza a importância de confiar em Deus em vez de em nossa própria compreensão limitada e pede que reconheçamos Deus em todas as áreas da nossa vida.
* Isaías 31:1: "Ai dos que descem ao Egito em busca de ajuda, que confiam em cavalos e confiam em carros porque são muitos, e em cavaleiros porque são poderosos, mas não olham para o Santo de Israel e não buscam o Senhor!" Este versículo adverte contra confiar em alianças políticas e militares em vez de confiar em Deus.
* Jeremias 17:5-6: "Assim diz o Senhor: Maldito é o homem que confia no homem, que faz da carne o seu braço e cujo coração se afasta do Senhor. Ele será como um arbusto no deserto; ele não verá nenhum bem quando vier, mas habitará nas terras secas do deserto, em uma terra salgada e sem habitantes." Este versículo destaca as consequências negativas de confiar no homem e se afastar de Deus, comparando-o a um arbusto no deserto.
* João 14:27: "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize." Este versículo enfatiza a paz que Deus oferece e nos lembra que a paz do mundo é temporária e superficial, em comparação com a paz que vem de Deus.
****

[[v14-16-1]]

^<<v14-16-1,1>>^ No trigésimo sexto ano do reinado de Asa, rei de Israel, Baasa fez guerra contra Judá. Fez fortificações em Ramá, a fim de bloquear todas as comunicações com Asa, rei de Judá.

[[v14-16-2]]

^<<v14-16-2,2>>^ Mas Asa mandou tomar a prata e o ouro dos tesouros do templo e do palácio real e enviou uma delegação a Ben-Adad, rei da Síria, para lhe dizer:

[[v14-16-3]]

^<<v14-16-3,3>>^ “Aliemo-nos, como foram aliados teu pai e o meu. Eu te envio prata e ouro. Rompe tua aliança com Baasa, rei de Israel, para que ele se afaste de mim”.

[[v14-16-4]]

^<<v14-16-4,4>>^ Ben-Adad ouviu o rei Asa: enviou seus generais contra as cidades de Israel. Estes tomaram Aion, Dã, Abel-Maim e todas as cidades de Neftali que serviam de entrepostos.

[[v14-16-5]]

^<<v14-16-5,5>>^ A essa notícia, Baasa interrompeu os trabalhos de fortificação de Ramá.

[[v14-16-6]]

^<<v14-16-6,6>>^ Então, o rei Asa convocou todos os judeus para tirar as pedras e madeiras das quais Baasa se tinha servido para construir Ramá, e com esse material fortificou Gabaá e Masfa.

[[v14-16-7]]

^<<v14-16-7,7>>^ Por essa época, o vidente Hanani veio à procura de Asa, rei de Judá, e lhe disse: “Porque te apoiaste no rei da Síria e não no Senhor, teu Deus, o exército da Síria escapou de tuas mãos.

[[v14-16-8]]

^<<v14-16-8,8>>^ Não formavam os etíopes e os líbios um exército inumerável, com uma multidão de carros e cavaleiros? E, contudo, o Senhor os entregou a ti porque tu te apoiaste nele.

[[v14-16-9]]

^<<v14-16-9,9>>^ Os olhos do Senhor percorrem toda a terra para sustentar aqueles cujo coração lhe é totalmente devotado. Tu te comportaste tolamente nesse negócio, pois doravante terás continuamente guerras”.

[[v14-16-10]]

^<<v14-16-10,10>>^ Irritado contra o vidente, no assomo de ira em que o puseram suas palavras, Asa mandou prendê-lo na prisão. Pelo mesmo tempo, Asa oprimiu também alguns de seus súditos.

[[v14-16-11]]

^<<v14-16-11,11>>^ As ações e os feitos de Asa, desde os primeiros até os últimos, estão relatados no Livro dos Reis de Judá e de Israel.

[[v14-16-12]]

^<<v14-16-12,12>>^ No trigésimo nono ano de seu reinado, Asa tornou-se gotoso e sofreu violentamente. Durante sua doença, ele não procurou o apoio do Senhor, mas o dos médicos.

[[v14-16-13]]

^<<v14-16-13,13>>^ Ele adormeceu com seus pais e morreu no quadragésimo primeiro ano de seu reinado.

[[v14-16-14]]

^<<v14-16-14,14>>^ Foi sepultado na tumba que tinha mandado cavar para si na Cidade de Davi. Estenderam-no num leito que tinham enchido de perfumes aromáticos, preparados segundo a arte do perfumista e queimaram-lhe quantidade considerável desse perfume.

'''

xref:014-ii-cronicas/014-ii-cronicas-015.adoc#v14-15-0[&#60; Capítulo Anterior] | <<v14-16-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-017.adoc#v14-17-0[Próximo Capítulo &#62;]