include::./index.adoc[]

[[v14-25-0]]
=== II Crônicas, 25
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 25 de 2 Crônicas conta a história de Amazias, rei de Judá, e sua guerra contra Edom. Ele contratou soldados de Israel para ajudá-lo, mas um profeta o alertou que Deus não estava com eles. Mesmo assim, Amazias derrotou Edom, mas trouxe de volta seus deuses e adorou-os, desafiando a Deus. Aqui estão cinco versículos relacionados aos temas abordados em 2 Crônicas 25:
* Deuteronômio 17:17: "Também não terá muitas mulheres, para que o seu coração não se desvie; nem prata nem ouro acumulará para si em excesso." Este verso fala sobre a necessidade de um rei não ter muitas mulheres ou acumular riquezas excessivas, para não se desviar do caminho de Deus. Amazias, no entanto, acumulou soldados e lutou por dinheiro, ignorando os avisos do profeta.
* Êxodo 20:3: "Não terás outros deuses diante de mim." Este é um dos Dez Mandamentos, que enfatiza a exclusividade da adoração a Deus. Amazias, após a vitória sobre Edom, trouxe de volta os deuses edomitas e adorou-os, desafiando a Deus.
* 2 Reis 14:7: "Ele matou dez mil edomitas no vale do Sal e conquistou Selá, dando-lhe o nome de Joceteel, como é conhecida até hoje." Este verso descreve uma das conquistas militares de Amazias contra Edom. Essa vitória é mencionada em 2 Crônicas 25 como a motivação de Amazias para contratar soldados de Israel.
* Provérbios 16:18: "O orgulho precede a ruína; o espírito arrogante, a queda." Este verso adverte sobre os perigos do orgulho e da arrogância. Amazias tornou-se orgulhoso após a vitória sobre Edom e não ouviu o aviso do profeta de Deus.
* 2 Crônicas 25:20: "Mas Amazias não quis ouvi-lo, porque isso vinha de Deus para entregá-los nas mãos dos inimigos, já que estes buscavam os deuses de Edom." Este verso mostra a teimosia de Amazias em não ouvir o aviso do profeta e como ele ignorou as consequências de sua desobediência a Deus.
****

[[v14-25-1]]

^<<v14-25-1,1>>^ Amasias tinha vinte e cinco anos quando começou a reinar. Reinou durante vinte e nove anos em Jerusalém. Sua mãe chamava-se Joaden e era de Jerusalém.

[[v14-25-2]]

^<<v14-25-2,2>>^ Fez o bem aos olhos do Senhor, mas não com um coração inteiramente devotado.

[[v14-25-3]]

^<<v14-25-3,3>>^ Desde que se sentiu seguro de seu poder real, mandou matar aqueles servos que tinham assassinado o rei, seu pai.

[[v14-25-4]]

^<<v14-25-4,4>>^ Mas não mandou matar os filhos deles, conforme o que está escrito na Lei de Moisés, onde o Senhor ordena: Os pais não serão mortos por seus filhos, nem os filhos por seus pais, pois cada um morrerá por seu próprio pecado.^&#42;1^

[[v14-25-5]]

^<<v14-25-5,5>>^ Amasias reuniu os homens de Judá e os dividiu por famílias, com os chefes de milhares e os chefes de centenas, para todo o Judá e para todo o Benjamim. Fez o recenseamento deles a partir da idade de vinte anos para cima e encontrou trezentos mil homens escolhidos, aptos para o serviço e capazes de carregar lança e escudo.

[[v14-25-6]]

^<<v14-25-6,6>>^ Em seguida, recrutou a seu soldo, por cem talentos de prata, cem mil valentes guerreiros de Israel.

[[v14-25-7]]

^<<v14-25-7,7>>^ Mas um homem de Deus veio-lhe ao encontro e disse-lhe: “Ó rei, não é preciso que o exército de Israel te acompanhe, porque o Senhor não está com Israel nem com esses filhos de Efraim.

[[v14-25-8]]

^<<v14-25-8,8>>^ Vai sozinho, age e sê valente no combate. De outra forma, Deus te deixará cair diante do inimigo, pois ele tem o poder de socorrer ou de abater”.

[[v14-25-9]]

^<<v14-25-9,9>>^ Disse Amasias ao homem de Deus: “Mas que farei então com respeito aos cem talentos que dei às tropas israelitas?”. “O Senhor – respondeu o homem de Deus – tem para dar-te mais do que isso.”

[[v14-25-10]]

^<<v14-25-10,10>>^ Amasias licenciou, pois e enviou de volta para sua terra a tropa de efraimitas que tinha vindo a ele. Mas apoderou-se deles uma viva irritação contra Judá e eles retornaram furiosos para suas casas.

[[v14-25-11]]

^<<v14-25-11,11>>^ Amasias, cheio de confiança, foi com seu exército para o Vale do Sal, onde matou dez mil seiritas.

[[v14-25-12]]

^<<v14-25-12,12>>^ Os filhos de Judá tinham capturado dez mil homens vivos; conduziram-nos ao alto de um rochedo, de onde os precipitaram e todos ficaram despedaçados.

[[v14-25-13]]

^<<v14-25-13,13>>^ Entretanto, os homens da tropa que Amasias tinha licenciado, não os deixando ir para a guerra com ele, saquearam as cidades de Judá desde Samaria até Bet-Horon. Mataram três mil homens e levaram um considerável despojo.

[[v14-25-14]]

^<<v14-25-14,14>>^ Tendo voltado para casa, depois da derrota dos edomitas, Amasias, que tinha trazido os deuses dos seiritas, fez deles seus próprios deuses. Prostrou-se diante deles, queimou-lhes incenso.

[[v14-25-15]]

^<<v14-25-15,15>>^ Inflamou-se, por isso, a ira do Senhor contra Amasias, e o Senhor enviou-lhe um profeta que lhe disse: “Por que foste procurar esses deuses estranhos que não foram capazes de salvar seu povo de tua mão?”.

[[v14-25-16]]

^<<v14-25-16,16>>^ Enquanto lhe falava o profeta, Amasias lhe disse: “Foste tu nomeado conselheiro do rei? Vai-te embora, se não queres que eu te mate!”. O profeta retirou-se, dizendo: “Sei que Deus decretou tua perda, porque te portaste mal e não queres ouvir minha advertência”.

[[v14-25-17]]

^<<v14-25-17,17>>^ Houve um conselho, depois do qual Amasias mandou dizer a Joás, filho de Joacaz, filho de Jeú, rei de Israel: “Vem, para que nos vejamos face a face”. Joás, rei de Israel, mandou responder a Amasias, rei de Judá:

[[v14-25-18]]

^<<v14-25-18,18>>^ “O espinho do Líbano mandou dizer ao cedro do Líbano: ‘Dá tua filha por esposa ao meu filho’. Mas os animais selvagens do Líbano passaram e pisaram o espinho.

[[v14-25-19]]

^<<v14-25-19,19>>^ Dizes que derrotaste os edomitas e teu coração se enche de orgulho. Vamos! Fica em casa. Por que correres tu à frente do perigo, arriscando-te a uma empresa que te perderá a ti e a Judá contigo?”.

[[v14-25-20]]

^<<v14-25-20,20>>^ Mas Amasias nada quis ouvir. Era o efeito de uma disposição divina, a fim de que fossem entregues a seus inimigos, eles que tinham adorado os deuses de Edom.

[[v14-25-21]]

^<<v14-25-21,21>>^ Joás, rei de Israel, pôs-se a caminho; encontraram-se ele e Amasias, rei de Judá, em Bet-Sames, que está em Judá.

[[v14-25-22]]

^<<v14-25-22,22>>^ Os de Judá foram vencidos por Israel e cada um fugiu para sua tenda.

[[v14-25-23]]

^<<v14-25-23,23>>^ Joás, rei de Israel, aprisionou, em Bet-Sames, Amasias, rei de Judá, filho de Joás, filho de Ocozias. Mandou-o para Jerusalém e abriu na muralha uma brecha de quatrocentos côvados, desde a porta de Efraim até a porta do ângulo.

[[v14-25-24]]

^<<v14-25-24,24>>^ Apoderou-se de todo o ouro e prata, assim como dos utensílios que se encontravam no templo, em casa de Obed-Edom e nos tesouros do palácio real; e retornou a Samaria, levando reféns.

[[v14-25-25]]

^<<v14-25-25,25>>^ Amasias, filho de Joás, rei de Judá, viveu ainda quinze anos depois da morte de Joás, filho de Joacaz, rei de Israel.

[[v14-25-26]]

^<<v14-25-26,26>>^ O restante dos atos de Amasias, dos primeiros aos últimos, está relatado no Livro dos Reis de Judá e de Israel.

[[v14-25-27]]

^<<v14-25-27,27>>^ Depois que Amasias se desviou do Senhor, tramou-se contra ele em Jerusalém uma conspiração e ele fugiu para Laquis. Perseguiram-no, porém, até lá e o mataram.

[[v14-25-28]]

^<<v14-25-28,28>>^ Transportaram-lhe o corpo em cima de cavalos e o sepultaram com seus pais na cidade de Judá.

'''

xref:014-ii-cronicas/014-ii-cronicas-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-ii-cronicas/014-ii-cronicas-026.adoc#v14-26-0[Próximo Capítulo &#62;]