include::./index.adoc[]

[[v34-3-0]]
=== Daniel, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 3 do livro de Daniel narra a história dos três jovens hebreus, Sadraque, Mesaque e Abednego, que se recusaram a adorar a estátua de ouro feita pelo rei Nabucodonosor. Eles foram jogados na fornalha ardente, mas foram protegidos por Deus e saíram ilesos. Abaixo estão cinco versículos relacionados aos temas abordados nesse capítulo:
* Isaías 43:2: "Quando você atravessar as águas, eu estarei com você; quando você atravessar os rios, eles não o encobrirão. Quando você andar através do fogo, você não se queimará; as chamas não o deixarão em brasas." Este versículo fala da presença de Deus com aqueles que confiam Nele em meio às dificuldades e adversidades, o que é exemplificado na história dos três jovens hebreus na fornalha.
* 1 Coríntios 10:13: "Nenhuma tentação os assolou, exceto a que é comum aos homens. E Deus é fiel; ele não permitirá que vocês sejam tentados além do que podem suportar. Mas, quando forem tentados, ele lhes providenciará um escape, para que possam suportá-la." Este versículo fala da fidelidade de Deus em nos ajudar a suportar as tentações, e os três jovens hebreus são um exemplo de como Deus pode nos ajudar a resistir a pressão para ceder à idolatria.
* Êxodo 20:3: "Não terás outros deuses diante de mim." Este versículo é o primeiro dos Dez Mandamentos e aborda o tema da adoração a Deus exclusivamente. É um princípio que os três jovens hebreus seguiram, mesmo diante da ameaça de morte, e nos desafia a fazer o mesmo em nossas vidas.
* Atos 5:29: "Pedro e os outros apóstolos responderam: ‘Devemos obedecer a Deus como governante antes que aos homens." Este versículo é parte da resposta de Pedro e dos apóstolos às autoridades que tentaram impedir sua pregação. É um exemplo de como devemos escolher obedecer a Deus, mesmo que isso signifique desobedecer às autoridades humanas.
* 2 Timóteo 1:7: "Pois Deus não nos deu espírito de covardia, mas de poder, amor e autocontrole." Este versículo fala do poder que Deus nos dá para resistir ao medo e à pressão de conformidade com as expectativas da sociedade. Os três jovens hebreus demonstraram esse poder ao resistir à ordem do rei Nabucodonosor de adorar a estátua de ouro.
****

[[v34-3-1]]

^<<v34-3-1,1>>^ O rei Nabucodonosor fez uma estátua de ouro, de sessenta côvados de altura e seis de largura, e erigiu-a na planície de Dura, na província da Babilônia.

[[v34-3-2]]

^<<v34-3-2,2>>^ Depois convidou os sátrapas, os prefeitos, os governadores, os conselheiros, os tesoureiros, os juristas, os juízes e todas as autoridades das províncias, a comparecerem à inauguração da estátua ereta pelo rei Nabucodonosor.

[[v34-3-3]]

^<<v34-3-3,3>>^ Assim sendo, reuniram-se os sátrapas, os prefeitos, os governadores, os conselheiros, os tesoureiros, os juristas, os juízes e todas as autoridades das províncias para a inauguração da estátua ereta pelo rei, diante da qual todos permaneceram de pé.

[[v34-3-4]]

^<<v34-3-4,4>>^ Então, foi feita por um arauto a seguinte proclamação: “Povos, nações (gentes de todas as línguas), eis o que se traz a vosso conhecimento:

[[v34-3-5]]

^<<v34-3-5,5>>^ no momento em que ouvirdes o som da trombeta, da flauta, da cítara, da lira, da harpa, da cornamusa e de toda espécie de instrumentos de música, vós vos prostrareis em adoração diante da estátua de ouro ereta pelo rei Nabucodonosor.^&#42;1^

[[v34-3-6]]

^<<v34-3-6,6>>^ Quem não se prostrar para adorá-la será precipitado sem demora na fornalha ardente!”.

[[v34-3-7]]

^<<v34-3-7,7>>^ Assim, logo que as pessoas ouviram o som da trombeta, da flauta, da cítara, da lira, da harpa, da cornamusa e de toda espécie de instrumentos de música, prosternaram-se todos, povos, nações e gentes de todas as línguas, em adoração diante da estátua de ouro ereta pelo rei Nabucodonosor.

[[v34-3-8]]

^<<v34-3-8,8>>^ Nesse mesmo momento, alguns caldeus aproximaram-se para caluniar os judeus.^&#42;1^

[[v34-3-9]]

^<<v34-3-9,9>>^ Dirigiram-se ao rei Nabucodonosor: “Senhor” – disseram –, “longa vida ao rei!

[[v34-3-10]]

^<<v34-3-10,10>>^ Tu mesmo, ó rei, proclamaste por edital, que qualquer homem que ouvisse o som da trombeta, da flauta, da cítara, da lira, da harpa, da cornamusa e de toda espécie de instrumentos de música teria de prostrar-se em adoração diante da estátua de ouro,

[[v34-3-11]]

^<<v34-3-11,11>>^ e quem se recusasse seria precipitado na fornalha ardente.

[[v34-3-12]]

^<<v34-3-12,12>>^ Pois bem, há aí alguns judeus, a quem confiaste a administração da província da Babilônia, Sidrac, Misac e Abdênago, os quais não tomaram conhecimento do teu edito, ó rei: não rendem culto algum a teus deuses e não adoram a estátua que erigiste”.

[[v34-3-13]]

^<<v34-3-13,13>>^ Nabucodonosor, dominado por uma cólera violenta, ordenou o comparecimento de Sidrac, Misac e Abdênago, os quais foram imediatamente trazidos à presença do rei.

[[v34-3-14]]

^<<v34-3-14,14>>^ Nabucodonosor disse-lhes: “É verdade, Sidrac, Misac e Abdênago, que recusais o culto a meus deuses e a adoração à estátua de ouro que erigi?

[[v34-3-15]]

^<<v34-3-15,15>>^ Pois bem, estais prontos, no momento em que ouvirdes o som da trombeta, da flauta, da cítara, da lira, da harpa, da cornamusa e de toda espécie de instrumentos de música, a vos prostrardes em adoração diante da estátua que eu fiz?... Se não o fizerdes, sereis precipitados de relance na fornalha ardente; e qual é o deus que poderia livrar-vos de minha mão?”.

[[v34-3-16]]

^<<v34-3-16,16>>^ Sidrac, Misac e Abdênago responderam ao rei Nabucodonosor: “De nada vale responder-te a esse respeito.

[[v34-3-17]]

^<<v34-3-17,17>>^ Se assim deve ser, o Deus a quem nós servimos pode nos livrar da fornalha ardente e mesmo, ó rei, de tua mão.

[[v34-3-18]]

^<<v34-3-18,18>>^ E mesmo que não o fizesse, saibas, ó rei, que nós não renderemos culto algum a teus deuses e que nós não adoraremos a estátua de ouro que erigiste”.

[[v34-3-19]]

^<<v34-3-19,19>>^ Então, a fúria de Nabucodonosor desencadeou-se contra Sidrac, Misac e Abdênago; os traços de seu rosto alteraram-se e ele elevou a voz para ordenar que se aquecesse a fornalha sete vezes mais que de costume.

[[v34-3-20]]

^<<v34-3-20,20>>^ Depois deu ordem aos soldados mais vigorosos de suas tropas para amarrar Sidrac, Misac e Abdênago, e jogá-los na fornalha ardente.

[[v34-3-21]]

^<<v34-3-21,21>>^ Esses homens foram então imediatamente amarrados com suas túnicas, vestes, mantos e suas outras roupas, e jogados na fornalha ardente.

[[v34-3-22]]

^<<v34-3-22,22>>^ Mas os homens que, por ordem urgente do rei, tinham superaquecido a fornalha e lá jogado Sidrac, Misac e Abdênago, foram mortos pelas chamas,

[[v34-3-23]]

^<<v34-3-23,23>>^ no momento em que eram precipitados na fornalha os três jovens amarrados.

[[v34-3-24]]

^<<v34-3-24,24>>^ Ora, estes passeavam dentro das chamas, louvando a Deus e bendizendo o Senhor.^&#42;1^

[[v34-3-25]]

^<<v34-3-25,25>>^ Azarias, em pé bem no meio do fogo, fez a seguinte oração:

[[v34-3-26]]

^<<v34-3-26,26>>^ “Sede bendito e louvado, Senhor, Deus de nossos pais! Que vosso nome seja glorioso pelos séculos!

[[v34-3-27]]

^<<v34-3-27,27>>^ Vós sois justo em todo o vosso proceder; vossas obras são justas, vossos caminhos são retos, vossos julgamentos são equitativos.

[[v34-3-28]]

^<<v34-3-28,28>>^ Exercestes um julgamento equitativo em tudo aquilo que nos infligistes e em tudo aquilo que infligistes à cidade santa de nossos pais, Jerusalém; foi em consequência de um julgamento equitativo que vós nos infligistes tudo isso por causa de nossos pecados.

[[v34-3-29]]

^<<v34-3-29,29>>^ Pecamos, erramos afastando-nos de vós; em tudo agimos mal.

[[v34-3-30]]

^<<v34-3-30,30>>^ Não obedecemos a vossos preceitos, não os pusemos em prática, não observamos as leis que nos destes para nossa felicidade.

[[v34-3-31]]

^<<v34-3-31,31>>^ Em todos os males que enviastes sobre nós, em tudo que nos infligistes, foi um justo julgamento que exercestes,

[[v34-3-32]]

^<<v34-3-32,32>>^ mesmo entregando-nos nas mãos de inimigos injustos, de ímpios enfurecidos, às mãos de um rei, o mais iníquo e o mais perverso de toda a terra.

[[v34-3-33]]

^<<v34-3-33,33>>^ Agora não ousamos nem mesmo abrir a boca: vergonha e ignomínia para vossos servos e a nós que vos adoramos.

[[v34-3-34]]

^<<v34-3-34,34>>^ Pelo amor de vosso nome, não nos abandoneis para sempre; não destruais de modo algum vossa aliança.

[[v34-3-35]]

^<<v34-3-35,35>>^ Não nos retireis vossa misericórdia em consideração a Abraão, vosso amigo, Isaac, vosso servo, Israel, vosso santo,

[[v34-3-36]]

^<<v34-3-36,36>>^ aos quais prometestes multiplicar sua descendência como as estrelas do céu e a areia que se encontra à beira do mar.

[[v34-3-37]]

^<<v34-3-37,37>>^ Senhor, fomos reduzidos a nada diante das nações, fomos humilhados diante de toda a terra: tudo, devido a nossos pecados!

[[v34-3-38]]

^<<v34-3-38,38>>^ Hoje, já não há príncipe, nem profeta, nem chefe, nem holocausto, nem sacrifício, nem oblação, nem incenso, nem mesmo um lugar para vos oferecer nossas primícias e encontrar misericórdia.

[[v34-3-39]]

^<<v34-3-39,39>>^ Entretanto, que a contrição de nosso coração e a humilhação de nosso espírito nos permita achar bom acolhimento junto a vós, Senhor,

[[v34-3-40]]

^<<v34-3-40,40>>^ como se nós nos apresentássemos com um holocausto de carneiros, de touros e milhares de gordos cordeiros! Que assim possa ser hoje o nosso sacrifício em vossa presença! Que possa reconciliar-nos convosco, porque nenhuma confusão existe para aqueles que põem em vós sua confiança.

[[v34-3-41]]

^<<v34-3-41,41>>^ É de todo nosso coração que nós vos seguimos agora, que nós vos reverenciamos, que buscamos vossa face.

[[v34-3-42]]

^<<v34-3-42,42>>^ Não nos confundais; tratai-nos com vossa habitual doçura e com todas as riquezas de vossa misericórdia.

[[v34-3-43]]

^<<v34-3-43,43>>^ Ponde em execução vossos prodígios para nos salvar, Senhor, e cobri vosso nome de glória.

[[v34-3-44]]

^<<v34-3-44,44>>^ Que sejam então confundidos aqueles que maltratam vossos servos, que eles sofram a vergonha de ver a ruína de seu poderio e o aniquilamento de sua força.

[[v34-3-45]]

^<<v34-3-45,45>>^ Assim, saberão que sois o Senhor, o Deus único e glorioso sobre toda a superfície da terra”.

[[v34-3-46]]

^<<v34-3-46,46>>^ Enquanto isso, os homens do rei, que os haviam lá jogado, não cessavam de alimentar a fornalha com nafta, estopa, resina e lenha seca.

[[v34-3-47]]

^<<v34-3-47,47>>^ Então, as chamas, subindo a quarenta e nove côvados acima da fornalha,

[[v34-3-48]]

^<<v34-3-48,48>>^ ultrapassaram a grade e queimaram os caldeus que se achavam perto.

[[v34-3-49]]

^<<v34-3-49,49>>^ Mas o anjo do Senhor havia descido com Azarias e seus companheiros à fornalha e afastava o fogo.

[[v34-3-50]]

^<<v34-3-50,50>>^ Fez do centro da fogueira como um lugar onde soprasse uma brisa matinal: o fogo nem mesmo os tocava, nem lhes fazia mal algum, nem lhes causava a menor dor.

[[v34-3-51]]

^<<v34-3-51,51>>^ Então, os três jovens elevaram suas vozes em uníssono para louvar, glorificar e bendizer a Deus dentro da fornalha, neste cântico:

[[v34-3-52]]

^<<v34-3-52,52>>^ Sede bendito, Senhor Deus de nossos pais, digno de louvor e de eterna glória! Que seja bendito o vosso santo nome glorioso, digno do mais alto louvor e de eterna exaltação!^&#42;1^

[[v34-3-53]]

^<<v34-3-53,53>>^ Sede bendito no templo de vossa glória santa, digno do mais alto louvor e de eterna glória!

[[v34-3-54]]

^<<v34-3-54,54>>^ Sede bendito por penetrardes com o olhar os abismos, e por estardes sentado sobre os querubins, digno do mais alto louvor e de eterna exaltação!

[[v34-3-55]]

^<<v34-3-55,55>>^ Sede bendito sobre vosso régio trono, digno do mais alto louvor e de eterna exaltação!

[[v34-3-56]]

^<<v34-3-56,56>>^ Sede bendito no firmamento dos céus, digno do mais alto louvor e de eterna glória!

[[v34-3-57]]

^<<v34-3-57,57>>^ Obras do Senhor, bendizei todas o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-58]]

^<<v34-3-58,58>>^ Céus, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-59]]

^<<v34-3-59,59>>^ Anjos do Senhor, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-60]]

^<<v34-3-60,60>>^ Águas e tudo o que está sobre os céus, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-61]]

^<<v34-3-61,61>>^ Todos os poderes do Senhor, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-62]]

^<<v34-3-62,62>>^ Sol e lua, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-63]]

^<<v34-3-63,63>>^ Estrelas dos céus, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-64]]

^<<v34-3-64,64>>^ Chuvas e orvalhos, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-65]]

^<<v34-3-65,65>>^ Ó vós, todos os ventos, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-66]]

^<<v34-3-66,66>>^ Fogo e calor, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-67]]

^<<v34-3-67,67>>^ Frio e geada, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-68]]

^<<v34-3-68,68>>^ Orvalhos e gelos, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-69]]

^<<v34-3-69,69>>^ Frios e aragens, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-70]]

^<<v34-3-70,70>>^ Gelos e neves, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-71]]

^<<v34-3-71,71>>^ Noites e dias, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-72]]

^<<v34-3-72,72>>^ Luz e trevas, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-73]]

^<<v34-3-73,73>>^ Raios e nuvens, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-74]]

^<<v34-3-74,74>>^ Que a terra bendiga o Senhor, e o louve e o exalte eternamente!

[[v34-3-75]]

^<<v34-3-75,75>>^ Montes e colinas, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-76]]

^<<v34-3-76,76>>^ Tudo o que germina na terra, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-77]]

^<<v34-3-77,77>>^ Mares e rios, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-78]]

^<<v34-3-78,78>>^ Fontes, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-79]]

^<<v34-3-79,79>>^ Monstros e animais que vivem nas águas, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-80]]

^<<v34-3-80,80>>^ Pássaros todos do céu, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-81]]

^<<v34-3-81,81>>^ Animais e rebanhos, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-82]]

^<<v34-3-82,82>>^ E vós, homens, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-83]]

^<<v34-3-83,83>>^ Que Israel bendiga o Senhor, e o louve e o exalte eternamente!

[[v34-3-84]]

^<<v34-3-84,84>>^ Sacerdotes, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-85]]

^<<v34-3-85,85>>^ Vós que estais a serviço do templo, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-86]]

^<<v34-3-86,86>>^ Espíritos e almas dos justos, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-87]]

^<<v34-3-87,87>>^ Santos e humildes de coração, bendizei o Senhor, louvai-o e exaltai-o eternamente!

[[v34-3-88]]

^<<v34-3-88,88>>^ Hananias, Azarias e Misael, bendizei o Senhor, louvai-o e exaltai-o eternamente, porque ele nos livrou da permanência nas trevas, salvou-nos da mão da morte; tirou-nos da fornalha ardente, e arrancou-nos do meio das chamas.

[[v34-3-89]]

^<<v34-3-89,89>>^ Glorificai o Senhor porque ele é bom, porque eterna é a sua misericórdia.

[[v34-3-90]]

^<<v34-3-90,90>>^ Homens piedosos, bendizei o Senhor, Deus dos deuses, louvai-o, glorificai-o, porque é eterna a sua misericórdia!

[[v34-3-91]]

^<<v34-3-91,91>>^ Então Nabucodonosor, admirado, levantou-se precipitadamente, dizendo a seus conselheiros: “Não foram três homens amarrados que jogamos no fogo?”. “Certamente, majestade” – responderam –.

[[v34-3-92]]

^<<v34-3-92,92>>^ “Pois bem” – replicou o rei – “eu vejo quatro homens soltos, que passeiam impunemente no meio do fogo; o quarto tem a aparência de um filho dos deuses”.

[[v34-3-93]]

^<<v34-3-93,93>>^ Dito isso, Nabucodonosor, aproximando-se da porta da fornalha, exclamou: “Sidrac, Misac, Abdênago, servos do Deus Altíssimo, saí, vinde!”. Então Sidrac, Misac e Abdênago saíram do meio do fogo.

[[v34-3-94]]

^<<v34-3-94,94>>^ Os sátrapas, os prefeitos, os governadores e os conselheiros do rei, em grupos à volta, verificaram que o fogo não tinha tocado nos corpos desses homens, que nenhum cabelo de suas cabeças tinha sido queimado, que suas vestes não tinham sido estragadas e que eles não traziam nem indício do odor de fogo!

[[v34-3-95]]

^<<v34-3-95,95>>^ Nabucodonosor tomou a palavra: “Bendito seja” – disse – “o Deus de Sidrac, de Misac e de Abdênago! Ele enviou seu anjo para salvar seus servos, os quais, depositando nele toda a sua confiança, e transgredindo as ordens do rei, preferiram expor suas vidas a se prostrarem em adoração diante de um deus que não era o seu.

[[v34-3-96]]

^<<v34-3-96,96>>^ Em consequência dou ordem, que todo homem, pertencente a qualquer povo, nação ou língua, que ousar falar mal, seja o que for, contra o Deus de Sidrac, Misac e Abdênago, seja despedaçado e sua casa reduzida a um montão de imundícies; porque não há outro deus capaz de realizar uma libertação assim!”.

[[v34-3-97]]

^<<v34-3-97,97>>^ Depois, o rei ainda melhorou a situação de Sidrac, Misac e Abdênago na província da Babilônia.

[[v34-3-98]]

^<<v34-3-98,98>>^ Do rei Nabucodonosor a todos os povos, nações e pessoas de todas as línguas que habitam a terra, felicidade e prosperidade!^&#42;1^

[[v34-3-99]]

^<<v34-3-99,99>>^ Pareceu-me bom fazer-vos conhecer os milagres e prodígios que o Deus Altíssimo operou em mim.

[[v34-3-100]]

^<<v34-3-100,100>>^ Oh! como são grandes seus milagres e Como são poderosos seus prodígios! Seu reinado é um reinado eterno, e sua dominação perdura de geração em geração.

'''

xref:034-daniel/034-daniel-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:034-daniel/034-daniel-004.adoc#v34-4-0[Próximo Capítulo &#62;]