include::./index.adoc[]

[[v34-1-0]]
=== Daniel, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Daniel 1 narra a história de quatro jovens hebreus que foram levados cativos para a Babilônia e foram instruídos a comerem da comida e vinho do rei, mas recusaram por causa de suas crenças religiosas. Eles pediram para comerem apenas legumes e água, e Deus os abençoou, tornando-os mais saudáveis e fortes do que os outros cativos. A seguir, são apresentados cinco versículos relacionados com os temas deste capítulo:
* 1 Coríntios 10:31: "Portanto, quer comais, quer bebais ou façais qualquer outra coisa, fazei tudo para a glória de Deus." Este versículo fala sobre a importância de viver uma vida que honra a Deus em todas as áreas, incluindo o que comemos.
* Provérbios 23:6-8: "Não coma a comida do avarento, nem deseje as suas iguarias, pois ele é como alguém que pensa consigo mesmo: 'Coma e beba', mas não está de coração com você. Você vomitará a iguaria que comeu e perderá suas amáveis palavras." Este versículo adverte contra a ganância e o amor excessivo pela comida, mostrando que as pessoas egoístas não estão preocupadas com o bem-estar dos outros.
* Atos 10:13-15: "Então uma voz lhe disse: 'Levanta-te, Pedro, mata e come!' Mas Pedro respondeu: 'De maneira nenhuma, Senhor! Nunca comi nada impuro ou imundo.' E a voz lhe falou pela segunda vez: 'Não chames impuro ao que Deus purificou.'" Este versículo fala sobre a pureza da comida, uma preocupação importante para os hebreus no tempo de Daniel.
* Romanos 14:17: "Pois o Reino de Deus não é comida nem bebida, mas justiça, paz e alegria no Espírito Santo." Este versículo enfatiza a importância de coisas mais importantes do que a comida, como a justiça e a paz que vêm de Deus.
* Marcos 7:18-20: "Ele (Jesus) lhes disse: 'Então vocês também são assim? Não entendem que nada que entra no homem pode torná-lo impuro? Pois não entra em seu coração, mas em seu estômago, e vai para a privada'. E assim ele declarou todos os alimentos 'puros'". Este versículo mostra como Jesus explicou que a pureza não está relacionada com a comida, mas com a nossa natureza interior e com o que sai dela.
****

[[v34-1-1]]

^<<v34-1-1,1>>^ No terceiro ano do reinado de Joaquin, rei de Judá, Nabucodonosor, rei da Babilônia, veio sitiar Jerusalém.

[[v34-1-2]]

^<<v34-1-2,2>>^ O Senhor entregou-lhe Joaquin, rei de Judá, bem como parte dos objetos do templo, que Nabucodonosor transportou para a terra de Senaar, para o templo de seu deus: foi na sala do tesouro do templo de seu deus que ele os colocou.

[[v34-1-3]]

^<<v34-1-3,3>>^ O rei deu ordem ao chefe de seus eunucos, Asfenez, para trazer-lhe jovens israelitas, oriundos de raça real ou de família nobre,

[[v34-1-4]]

^<<v34-1-4,4>>^ isentos de qualquer defeito corporal, bem proporcionados, dotados de toda espécie de boas qualidades, instruídos, inteligentes, aptos a ingressarem nos serviços do palácio real; deveria ser ensinado a eles a literatura e a língua dos caldeus.^&#42;1^

[[v34-1-5]]

^<<v34-1-5,5>>^ O rei destinou-lhes uma provisão cotidiana, retirada das iguarias da mesa real e do vinho que ele bebia. A formação deles devia durar três anos, após o que entrariam a serviço do rei.

[[v34-1-6]]

^<<v34-1-6,6>>^ Entre eles, encontravam-se alguns judeus: Daniel, Hananias, Misael e Azarias.

[[v34-1-7]]

^<<v34-1-7,7>>^ O chefe dos eunucos deu-lhes outros nomes: a Daniel, o de Baltazar; a Hananias, o de Sidrac; a Misael, o de Misac; e a Azarias, o de Abdênago.^&#42;1^

[[v34-1-8]]

^<<v34-1-8,8>>^ Daniel tomou a resolução de não se contaminar com os alimentos do rei e com seu vinho. Pediu ao chefe dos eunucos para deles se abster.^&#42;1^

[[v34-1-9]]

^<<v34-1-9,9>>^ Este, graças a Deus, tomado de benevolência para com Daniel, atendeu-o de boa vontade,

[[v34-1-10]]

^<<v34-1-10,10>>^ mas disse-lhe: “Temo que o rei, meu senhor, que estabeleceu vossa alimentação e vossa bebida, venha a notar vossas fisionomias mais abatidas do que as dos outros jovens de vossa idade, e que por vossa causa eu me exponha a uma repreensão da parte do rei”.

[[v34-1-11]]

^<<v34-1-11,11>>^ Mas Daniel disse ao dispenseiro a quem o chefe dos eunucos havia confiado o cuidado de Daniel, Hananias, Misael e Azarias:

[[v34-1-12]]

^<<v34-1-12,12>>^ “Rogo-te, faze uma experiência de dez dias com teus servos: que só nos sejam dados legumes a comer e água a beber.

[[v34-1-13]]

^<<v34-1-13,13>>^ Depois, então, compararás nossos semblantes com os dos jovens que se alimentam com as iguarias da mesa real, e farás com teus servos segundo o que terás observado”.

[[v34-1-14]]

^<<v34-1-14,14>>^ O dispenseiro concordou com essa proposta e os submeteu à prova durante dez dias.

[[v34-1-15]]

^<<v34-1-15,15>>^ No final desse prazo, averiguou-se que tinham melhor aparência e estavam mais gordos do que todos os jovens que comiam das iguarias da mesa real.

[[v34-1-16]]

^<<v34-1-16,16>>^ Em consequência disso, o dispenseiro retirava os alimentos e o vinho que lhes eram destinados e mandava servir-lhes legumes.

[[v34-1-17]]

^<<v34-1-17,17>>^ A esses quatro jovens, Deus concedeu talento e saber no domínio das letras e das ciências. Daniel era particularmente entendido na interpretação de visões e sonhos.

[[v34-1-18]]

^<<v34-1-18,18>>^ Ao fim do prazo fixado pelo rei para a apresentação, o chefe dos eunucos introduziu-os na presença de Nabucodonosor,

[[v34-1-19]]

^<<v34-1-19,19>>^ o qual palestrou com eles. Entre todos os jovens nenhum houve que se comparasse a Daniel, Hananias, Misael e Azarias. Por isso, entraram eles a serviço do rei.

[[v34-1-20]]

^<<v34-1-20,20>>^ Em qualquer negócio que necessitasse de sabedoria e sutileza, e que o rei os consultasse, este achava-os dez vezes superiores a todos os escribas e mágicos do reino.

[[v34-1-21]]

^<<v34-1-21,21>>^ Assim viveu Daniel até o primeiro ano do reinado de Ciro.

'''

xref:033-ezequiel/033-ezequiel-048.adoc#v33-48-0[&#60; Capítulo Anterior] | <<v34-1-0,Topo>> | xref:034-daniel/034-daniel-002.adoc#v34-2-0[Próximo Capítulo &#62;]