include::./index.adoc[]

[[v34-11-0]]
=== Daniel, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Daniel 11 é um capítulo profético que descreve uma série de eventos históricos futuros, incluindo guerras e conflitos entre nações. Esses eventos são apresentados como uma visão dada a Daniel, e muitos estudiosos da Bíblia têm debatido ao longo dos séculos qual é o significado exato de cada evento e personagem mencionado. Aqui estão cinco versículos relacionados com os temas abordados em Daniel 11:
* Isaías 41:21-23: "Apresentem as suas provas, diz o Senhor; tragam seus argumentos, diz o rei de Jacó. Que apresentem suas testemunhas para provar que estão certos, para que se ouça e se diga: ‘Verdade!’". Este versículo se relaciona com a visão de Daniel 11, que apresenta uma série de eventos futuros que serão realizados e comprovados no futuro.
* Mateus 24:6-8: "Vocês ouvirão falar de guerras e rumores de guerras, mas não tenham medo. É necessário que tais coisas aconteçam, mas ainda não é o fim. Nação se levantará contra nação, e reino contra reino. Haverá fomes e terremotos em vários lugares." Este versículo se relaciona com a descrição de conflitos e guerras em Daniel 11, que incluem batalhas entre reinos e nações.
* Apocalipse 12:7: "Então houve uma batalha no céu. Miguel e os seus anjos lutaram contra o dragão, e o dragão e seus anjos lutaram de volta." Este versículo se relaciona com a descrição de conflitos e batalhas entre personagens divinos e demoníacos em Daniel 11.
* Ezequiel 38:8-9: "Depois de muitos dias você será convocado para a batalha. Nos últimos anos você invadirá um país que se recuperou da guerra, cujo povo foi reunido dentre muitas nações nas montanhas de Israel, que foram desertadas há muito tempo. Eles foram trazidos de volta do exílio, e agora vivem em segurança." Este versículo se relaciona com a descrição de conflitos futuros em Daniel 11, incluindo batalhas entre nações e povos.
* 1 João 2:18: "Filhinhos, esta é a última hora; e, conforme ouviram que o anticristo está vindo, já agora muitos anticristos têm surgido. Por isso sabemos que é a última hora." Este versículo se relaciona com a descrição de personagens anticristãos e anticristos em Daniel 11.
****

[[v34-11-1]]

^<<v34-11-1,1>>^ Assim como eu, no primeiro ano do reinado de Dario, o medo, mantive-me junto a ele para auxiliá-lo e protegê-lo.”

[[v34-11-2]]

^<<v34-11-2,2>>^ “Agora vou manifestar-te a verdade. Haverá ainda três reis na Pérsia. O quarto ultrapassará todos os demais em riquezas. Quando suas riquezas o tiverem tornado poderoso, movimentará tudo contra o reino de Javã.^&#42;1^

[[v34-11-3]]

^<<v34-11-3,3>>^ Mas um rei forte se levantará e dominará sobre um vasto império e fará tudo quanto lhe aprouver.^&#42;1^

[[v34-11-4]]

^<<v34-11-4,4>>^ Quando ficar poderoso, seu reino será desmembrado e dividido aos quatro ventos do céu. Não passará à posteridade e não terá mais o mesmo poder; seu reino será desmembrado e entregue a estranhos e não a seus descendentes.^&#42;1^

[[v34-11-5]]

^<<v34-11-5,5>>^ O rei do Sul se tornará poderoso, mas um dos chefes do seu exército ficará ainda mais forte e seu império será grande.^&#42;1^

[[v34-11-6]]

^<<v34-11-6,6>>^ Após alguns anos se aliarão: a filha do rei do Sul virá à casa do rei do Norte para fazer o acordo; mas ela não conservará o apoio de seu pai, cujo poder não se manterá, nem o do seu esposo. Ela será morta com aqueles que a tiverem trazido, aquele que a criou e aquele que a tinha feito poderosa.^&#42;1^

[[v34-11-7]]

^<<v34-11-7,7>>^ Um dos rebentos da mesma raiz se levantará em seu lugar; virá em direção do exército, entrará nas fortalezas do rei do Norte, irá atacá-lo e sairá vencedor.^&#42;1^

[[v34-11-8]]

^<<v34-11-8,8>>^ Levará para o Egito até mesmo seus deuses cativos, assim como seus ídolos e seus objetos preciosos de ouro e de prata. Depois, durante alguns anos, se absterá de atacar o rei do Norte.

[[v34-11-9]]

^<<v34-11-9,9>>^ Este virá contra o rei do Sul, mas voltará para a sua terra.

[[v34-11-10]]

^<<v34-11-10,10>>^ Mas seus filhos prepararão a guerra recrutando um exército numeroso, o qual, precipitando-se como uma torrente, invadirá e levará a batalha até a sua fortaleza.^&#42;1^

[[v34-11-11]]

^<<v34-11-11,11>>^ Irritado, o rei do Sul sairá para atacar o rei do Norte: como porá em campo um numeroso exército, as tropas inimigas lhe serão entregues.^&#42;1^

[[v34-11-12]]

^<<v34-11-12,12>>^ Após o aniquilamento desse exército, se encherá de orgulho. Mandará matar dezenas de milhares de homens, sem ficar mais forte por isso.

[[v34-11-13]]

^<<v34-11-13,13>>^ O rei do Norte organizará novamente um exército mais numeroso ainda que o primeiro, e alguns anos depois avançará em meio a enormes tropas e a um grandioso aparato.^&#42;1^

[[v34-11-14]]

^<<v34-11-14,14>>^ Nesse momento, muitos se levantarão contra o rei do Sul; homens violentos de teu povo se revoltarão para cumprir a visão, mas fracassarão.

[[v34-11-15]]

^<<v34-11-15,15>>^ O rei do Norte virá, então, destruirá trincheiras e tomará fortalezas. Os exércitos do rei do Sul, mesmo as suas tropas de elite, não se manterão; nada poderá resistir.^&#42;1^

[[v34-11-16]]

^<<v34-11-16,16>>^ O invasor agirá à sua vontade sem que ninguém possa enfrentá-lo e se deterá no país que é a joia da terra; e a destruição estará em suas mãos.

[[v34-11-17]]

^<<v34-11-17,17>>^ Empreenderá a conquista do reino do Sul; fará um pacto com seu rei e lhe dará sua filha como mulher, a fim de amenizar a ruína dessa terra; mas isso não dará resultado, e esse reino não lhe pertencerá.^&#42;1^

[[v34-11-18]]

^<<v34-11-18,18>>^ Depois se voltará contra as ilhas e tomará diversas. Porém, um chefe militar porá fim à sua soberba, e o fará pagar sua injúria.^&#42;1^

[[v34-11-19]]

^<<v34-11-19,19>>^ Então, ele se voltará contra as fortalezas de sua terra, mas tropeçará, cairá e acabará desaparecendo.

[[v34-11-20]]

^<<v34-11-20,20>>^ “No lugar deste último será colocado um príncipe, que enviará um fiscal ao país que é a joia da terra. Em poucos dias ele será aniquilado, e não será nem por efeito de cólera nem de batalha.”^&#42;1^

[[v34-11-21]]

^<<v34-11-21,21>>^ “Em seu lugar, um homem vil se elevará, sem nenhuma dignidade real, surgirá repentinamente e se apossará da realeza pelas suas intrigas.^&#42;1^

[[v34-11-22]]

^<<v34-11-22,22>>^ As tropas de invasão serão postas em fuga diante dele e aniquiladas, bem como o chefe da aliança.^&#42;1^

[[v34-11-23]]

^<<v34-11-23,23>>^ A despeito do pacto firmado com ele, agirá com perfídia: atacará e triunfará com poucos homens.

[[v34-11-24]]

^<<v34-11-24,24>>^ Invadirá inesperadamente as regiões mais férteis da terra; fará o que nunca fizeram seus pais nem os antepassados deles: distribuirá com os seus os saques, despojos, riquezas; combinará ofensivas contra as fortalezas, mas apenas por um tempo.^&#42;1^

[[v34-11-25]]

^<<v34-11-25,25>>^ Dará novo impulso a suas forças e a seu valor, atacando o rei do Sul com um exército considerável. Por seu lado, o rei do Sul entrará na luta com um exército importante e valoroso, mas não poderá resistir, devido às intrigas urdidas contra ele.^&#42;1^

[[v34-11-26]]

^<<v34-11-26,26>>^ Seus comensais o aniquilarão; seu exército se dispersará e muitos homens cairão feridos mortalmente.

[[v34-11-27]]

^<<v34-11-27,27>>^ Com o coração repleto de desejos malévolos, os dois reis se enganarão mutuamente à volta da mesma mesa. Mas seus projetos fracassarão, porque o fim só virá no tempo determinado.

[[v34-11-28]]

^<<v34-11-28,28>>^ Volverá à sua terra com grandes riquezas. Seu coração meditará o mal contra a santa aliança; o cometerá, depois entrará novamente em sua terra.”^&#42;1^

[[v34-11-29]]

^<<v34-11-29,29>>^ “No tempo previsto atacará de novo o Sul: mas esta expedição não será semelhante à precedente.

[[v34-11-30]]

^<<v34-11-30,30>>^ Navios de Cetim o atacarão e ele desanimará. Dirigirá novamente sua fúria contra a santa aliança, tomará medidas contra ela, fazendo um pacto com aqueles que a abandonarem.^&#42;1^

[[v34-11-31]]

^<<v34-11-31,31>>^ Tropas sob sua ordem virão profanar o santuário, a fortaleza; farão cessar o holocausto perpétuo e instalarão a abominação do devastador.^&#42;1^

[[v34-11-32]]

^<<v34-11-32,32>>^ Submeterá, com suas lisonjas, os violadores da aliança, mas a multidão daqueles que conhecem seu Deus se manterá firme e resistirá.^&#42;1^

[[v34-11-33]]

^<<v34-11-33,33>>^ Os homens doutos desse povo instruirão um grande número; mas, durante algum tempo, perecerão pela espada, fogo, cativeiro e pilhagem.

[[v34-11-34]]

^<<v34-11-34,34>>^ Enquanto forem caindo dessa maneira, serão um tanto amparados; e um bom número se unirá hipocritamente a eles.^&#42;1^

[[v34-11-35]]

^<<v34-11-35,35>>^ Muitos desses sábios sucumbirão, a fim de que sejam provados, purificados e branqueados até o termo final; ora, esse final só chegará no tempo marcado.

[[v34-11-36]]

^<<v34-11-36,36>>^ O rei fará então tudo o que desejar. Ele se ensoberbecerá, se elevará no seu orgulho acima de qualquer divindade; proferirá até coisas inauditas contra o Deus dos deuses; prosperará até que a cólera divina tenha chegado ao seu termo, porque o que está decretado deverá ser executado.

[[v34-11-37]]

^<<v34-11-37,37>>^ Não respeitará nem os deuses de seus antepassados, nem a deusa querida das mulheres, nem divindade alguma; ele se julgará superior a todos.^&#42;1^

[[v34-11-38]]

^<<v34-11-38,38>>^ Mas venerará o deus das fortalezas, no próprio local, um deus desconhecido de seus antepassados, com ouro, prata, pedras preciosas e joias.^&#42;1^

[[v34-11-39]]

^<<v34-11-39,39>>^ Com o auxílio de um deus estranho, atacará as muralhas das fortalezas; aos que o reconhecerem, multiplicará as honras, ele lhes conferirá autoridade sobre numerosos vassalos e lhes distribuirá terras em recompensa.

[[v34-11-40]]

^<<v34-11-40,40>>^ No final, o rei do Sul e ele entrarão em luta. O rei do Norte cairá sobre ele, como um furacão, com carros, cavaleiros e uma frota considerável. Entrará na terra como uma torrente que transborda.^&#42;1^

[[v34-11-41]]

^<<v34-11-41,41>>^ Invadirá o país que é a joia da terra, onde muitos homens cairão. Mas os edomitas, os moabitas e a maioria dos amonitas lhe escaparão.^&#42;1^

[[v34-11-42]]

^<<v34-11-42,42>>^ Ele se apoderará de diferentes países; o Egito não lhe escapará.

[[v34-11-43]]

^<<v34-11-43,43>>^ Pilhará os tesouros de ouro e de prata bem como tudo o que houver de precioso no Egito. Os líbios e os etíopes se juntarão a ele.

[[v34-11-44]]

^<<v34-11-44,44>>^ Mas, alarmado pelas notícias vindas do Oriente e do Norte, se retirará como uma fúria, para destruir e exterminar uma multidão de povos.^&#42;1^

[[v34-11-45]]

^<<v34-11-45,45>>^ Erguerá os pavilhões de seu palácio entre o mar e a nobre montanha do santuário. Então, alcançará o termo de sua vida e ninguém lhe prestará socorro.”^&#42;1^

'''

xref:034-daniel/034-daniel-010.adoc#v34-10-0[&#60; Capítulo Anterior] | <<v34-11-0,Topo>> | xref:034-daniel/034-daniel-012.adoc#v34-12-0[Próximo Capítulo &#62;]