include::./index.adoc[]

[[v34-6-0]]
=== Daniel, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Daniel 6 é o capítulo que narra a história de Daniel na cova dos leões. O rei Dario havia decretado que ninguém poderia orar a nenhum outro deus ou homem que não ele próprio, mas Daniel desobedeceu essa ordem e continuou orando a Deus, como de costume. Como resultado, foi lançado na cova dos leões, mas Deus o protegeu e ele sobreviveu. Abaixo estão cinco versículos relacionados com os temas abordados nesse capítulo:
* Salmo 55:17: "De tarde, e de manhã, e ao meio-dia, farei as minhas queixas e lamentarei; e ele ouvirá a minha voz." Essa passagem mostra a importância da oração constante, como a que Daniel praticava, mesmo sabendo que poderia ser condenado à morte por isso.
* Mateus 6:6: "Mas tu, quando orares, entra no teu quarto e, fechando a porta, ora a teu Pai que está em secreto; e teu Pai, que vê em secreto, te recompensará." Jesus ensina aqui sobre a importância da oração em segredo, sem se preocupar com a opinião dos outros.
* 1 Pedro 5:8: "Sede sóbrios, vigiai, porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa tragar." Essa passagem fala sobre o diabo agindo como um leão faminto, prontos para devorar aqueles que são fiéis a Deus, como os leões na cova com Daniel.
* Hebreus 11:33-34: "Os quais, pela fé, venceram reinos, praticaram a justiça, alcançaram promessas, fecharam as bocas dos leões, apagaram a força do fogo, escaparam do fio da espada, da fraqueza tiraram forças, na batalha se esforçaram, puseram em fuga os exércitos dos estranhos." Essa passagem descreve os muitos atos de fé que foram praticados pelos heróis da fé, como Daniel, que fechou a boca dos leões pela sua fé em Deus.
* Tiago 1:12: "Bem-aventurado o homem que suporta a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam." Essa passagem encoraja os crentes a perseverar em meio à provação e tribulação, como Daniel fez na cova dos leões, lembrando que Deus prometeu recompensa aos que o amam e o servem fielmente.
****

[[v34-6-1]]

^<<v34-6-1,1>>^ Dario, o medo, recebeu a realeza mais ou menos com a idade de sessenta e dois anos.^&#42;1^

[[v34-6-2]]

^<<v34-6-2,2>>^ Aprouve a Dario, o medo, constituir e espalhar por todo o seu reino cento e vinte sátrapas,

[[v34-6-3]]

^<<v34-6-3,3>>^ submetidos a três ministros, um dos quais era Daniel, a quem eles teriam de prestar contas, a fim de que os interesses do rei nunca fossem lesados.

[[v34-6-4]]

^<<v34-6-4,4>>^ Ora, Daniel, devido à superioridade de seu espírito, levava vantagem sobre os ministros e sátrapas e, com isso, o rei sonhava em pô-lo à frente de todo o reino.

[[v34-6-5]]

^<<v34-6-5,5>>^ Por isso, ministros e sátrapas procuravam um meio de acusar Daniel em relação à sua administração. Mas não puderam descobrir pretexto algum, nem falta, porque ele era íntegro e nada de faltoso e repreensível se encontrava nele.

[[v34-6-6]]

^<<v34-6-6,6>>^ Esses homens disseram, então: “Não acharemos motivo algum de acusação contra esse Daniel, a não ser naquilo que diz respeito à Lei de seu Deus”.

[[v34-6-7]]

^<<v34-6-7,7>>^ Então, ministros e sátrapas vieram tumultuosamente procurar o rei e lhe disseram: “Rei Dario, longa vida ao rei!

[[v34-6-8]]

^<<v34-6-8,8>>^ Os ministros do reino, os prefeitos, os sátrapas, os conselheiros e os governadores estão todos de acordo em que seja publicado um edito real com uma interdição, estabelecendo que aquele que nesses trinta dias dirigir preces a um deus ou homem qualquer que seja, além de ti, ó rei, seja jogado na cova dos leões.

[[v34-6-9]]

^<<v34-6-9,9>>^ Promulga pois, ó rei, esta interdição, e manda fazer um documento, a fim de que, conforme o estabelecido na lei definitiva dos medos e dos persas, não possa ser revogada”.

[[v34-6-10]]

^<<v34-6-10,10>>^ Em consequência, o rei Dario fez redigir o documento contendo a referida interdição.

[[v34-6-11]]

^<<v34-6-11,11>>^ Ouvindo essa notícia, Daniel entrou em sua casa, a qual tinha no quarto de cima janelas que davam para o lado de Jerusalém. Três vezes ao dia, ajoelhado, como antes, continuou a orar e a louvar a Deus.

[[v34-6-12]]

^<<v34-6-12,12>>^ Então, esses homens acorreram amotinados e encontraram Daniel em oração, invocando seu Deus.

[[v34-6-13]]

^<<v34-6-13,13>>^ Foram imediatamente ao palácio do rei e disseram-lhe, a respeito do edito real de interdição: “Não promulgaste, ó rei, uma proibição estabelecendo que quem nesses trinta dias invocasse algum deus ou homem qualquer que fosse, à exceção tua, seria jogado na cova dos leões?”. “Certamente” – respondeu o rei –, “(assim foi feito) segundo a lei dos medos e dos persas, que não pode ser modificada.”

[[v34-6-14]]

^<<v34-6-14,14>>^ “Pois bem” – continuaram –, “Daniel, o deportado de Judá, não tem consideração nem por tua pessoa nem por teu decreto: três vezes ao dia ele faz sua oração.”

[[v34-6-15]]

^<<v34-6-15,15>>^ Ouvindo essas palavras, o rei, bastante contrariado, tomou contudo a resolução de salvar Daniel, e nisso esforçou-se até o pôr do sol.

[[v34-6-16]]

^<<v34-6-16,16>>^ Mas os mesmos homens novamente o vieram procurar em tumulto: “Saibas, ó rei” – disseram-lhe – “que a lei dos medos e dos persas não permite derrogação alguma a uma proibição ou a uma medida publicada em edito pelo rei”.

[[v34-6-17]]

^<<v34-6-17,17>>^ Então, o rei deu ordem para trazerem Daniel e o jogarem na cova dos leões. “Que o Deus, que tu adoras com tanta fidelidade” – disse-lhe – “queira ele mesmo salvar-te!”

[[v34-6-18]]

^<<v34-6-18,18>>^ Trouxeram uma pedra, que foi rolada sobre a abertura da cova; o rei lacrou-a com seu sinete e com o dos grandes, a fim de que nada fosse modificado em relação a Daniel.

[[v34-6-19]]

^<<v34-6-19,19>>^ De volta a seu palácio, o rei passou a noite sem nada tomar, e sem mandar vir concubina alguma para junto de si. Não conseguiu adormecer.

[[v34-6-20]]

^<<v34-6-20,20>>^ Logo ao amanhecer, levantou-se e dirigiu-se a toda pressa à cova dos leões.

[[v34-6-21]]

^<<v34-6-21,21>>^ Quando se aproximou, chamou Daniel com voz cheia de tristeza: “Daniel” – disse-lhe –, “servo de Deus vivo, teu Deus que tu adoras com tanta fidelidade terá podido salvar-te dos leões?!”.

[[v34-6-22]]

^<<v34-6-22,22>>^ Daniel respondeu-lhe: “Senhor, vida longa ao rei!

[[v34-6-23]]

^<<v34-6-23,23>>^ Meu Deus enviou seu anjo e fechou a boca dos leões; eles não me fizeram mal algum, porque a seus olhos eu era inocente e porque contra ti também, ó rei, não cometi falta alguma”.

[[v34-6-24]]

^<<v34-6-24,24>>^ Então o rei, todo feliz, ordenou que se retirasse Daniel da cova. Foi ele assim retirado sem traço algum de ferimento, porque tinha tido fé em seu Deus.

[[v34-6-25]]

^<<v34-6-25,25>>^ Por ordem do rei, mandaram vir então os acusadores de Daniel, que foram jogados na cova dos leões com suas mulheres e seus filhos. Não haviam tocado o fundo da cova, e já os leões os agarraram e lhes trituraram os ossos!

[[v34-6-26]]

^<<v34-6-26,26>>^ Então, o rei Dario escreveu: “A todos os povos, a todas as nações e aos povos de todas as línguas que habitam sobre a terra, felicidade e prosperidade!

[[v34-6-27]]

^<<v34-6-27,27>>^ Por mim é ordenado que em toda a extensão de meu reino se mantenha perante o Deus de Daniel temor e tremor. É o Deus vivo, que subsiste eternamente; seu reino é indestrutível e seu domínio é perpétuo.

[[v34-6-28]]

^<<v34-6-28,28>>^ Ele salva e livra, faz milagres e prodígios no céu e sobre a terra: foi ele quem livrou Daniel das garras dos leões”.

[[v34-6-29]]

^<<v34-6-29,29>>^ Foi assim que Daniel prosperou durante o reinado de Dario e durante o de Ciro, o persa.^&#42;1^

'''

xref:034-daniel/034-daniel-005.adoc#v34-5-0[&#60; Capítulo Anterior] | <<v34-6-0,Topo>> | xref:034-daniel/034-daniel-007.adoc#v34-7-0[Próximo Capítulo &#62;]