include::./index.adoc[]

[[v34-2-0]]
=== Daniel, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 2 de Daniel apresenta o sonho do rei Nabucodonosor e a interpretação dada por Daniel, que revela a ele não só o significado do sonho, mas também detalhes sobre o futuro dos reinos que sucederiam o império babilônico. Os versículos selecionados abaixo abordam temas presentes no capítulo, como sonhos e interpretações, a sabedoria dada por Deus e a sua capacidade de revelar mistérios.
* Provérbios 25:2: "A glória de Deus está em encobrir as coisas, mas a honra dos reis está em descobri-las." Este versículo mostra que Deus é o Senhor dos mistérios e das revelações, e que cabe a ele a decisão de quando e como revelá-los.
* Tiago 1:5: "Se algum de vocês tem falta de sabedoria, peça-a a Deus, que a todos dá livremente, de boa vontade; e lhe será concedida." Este versículo destaca a sabedoria dada por Deus, que é a chave para a interpretação dos sonhos e revelações.
* Colossenses 2:3: "Nele estão escondidos todos os tesouros da sabedoria e do conhecimento." Essa passagem nos lembra que a sabedoria divina é infinita e que, por meio dela, podemos entender os mistérios que nos são revelados.
* Jeremias 33:3: "Clama a mim, e responder-te-ei, e anunciar-te-ei coisas grandes e firmes que não sabes." Esta é uma promessa de Deus para aqueles que buscam a sua sabedoria e conhecimento, mostrando que ele está sempre disposto a revelar seus mistérios.
* Lucas 12:2: "Mas nada há encoberto que não haja de ser descoberto; nem oculto, que não haja de ser sabido." Este versículo mostra que, no final, tudo será revelado, e que a sabedoria divina é capaz de revelar os maiores mistérios, mesmo aqueles que parecem impossíveis de compreender.
****

[[v34-2-1]]

^<<v34-2-1,1>>^ No segundo ano de seu reinado, Nabucodonosor teve sonhos que lhe perturbaram a tal ponto o espírito, que perdeu o sono.^&#42;1^

[[v34-2-2]]

^<<v34-2-2,2>>^ Mandou chamar os escribas, os mágicos, os feiticeiros e os caldeus para lhe fazerem a interpretação. Estes vieram apresentar-se diante do rei.

[[v34-2-3]]

^<<v34-2-3,3>>^ “Tive um sonho”– disse-lhes – “e meu espírito se consome à procura do significado.”

[[v34-2-4]]

^<<v34-2-4,4>>^ Os caldeus responderam ao rei: “Senhor, longa vida ao rei! Narra teu sonho para que teus servos deem a interpretação”.^&#42;1^

[[v34-2-5]]

^<<v34-2-5,5>>^ O rei disse aos caldeus: “Para mim é coisa decidida: se não me explicardes o conteúdo do sonho bem como sua significação, sereis estraçalhados e vossas casas reduzidas a um montão de imundícies.

[[v34-2-6]]

^<<v34-2-6,6>>^ Mas se me revelardes tanto o conteúdo quanto a significação do sonho, recebereis de mim donativos, presentes e grandes testemunhos de honra. Portanto, dizei-me meu sonho e o que ele significa”.

[[v34-2-7]]

^<<v34-2-7,7>>^ De novo responderam: “Que o rei narre o sonho a seus servos e nós faremos a interpretação”.

[[v34-2-8]]

^<<v34-2-8,8>>^ “Sei agora perfeitamente” – continuou o rei – “que procurais ganhar tempo, porque sabeis que estou bem decidido

[[v34-2-9]]

^<<v34-2-9,9>>^ a aplicar-vos a dita sentença, se não me revelardes o conteúdo de meu sonho. Estais combinados a mentir-me e a enganar-me, esperando que as circunstâncias mudem. Vamos, dizei-me o que sonhei e eu saberei se sois capazes de dar a interpretação.”

[[v34-2-10]]

^<<v34-2-10,10>>^ Os caldeus deram ao rei esta resposta: “Não há homem algum sobre a terra que possa fazer o que exige o rei. E, de fato, jamais rei algum, por maior e mais poderoso que tenha sido, pediu tamanha coisa a um escriba, mágico ou caldeu.

[[v34-2-11]]

^<<v34-2-11,11>>^ A questão proposta pelo rei é difícil e ninguém poderia dar a solução ao rei, a não ser os deuses que estão excluídos do trato com os seres carnais”.

[[v34-2-12]]

^<<v34-2-12,12>>^ Com isso, o rei encolerizou-se e, na sua fúria, deu ordem para matarem todos os sábios da Babilônia.

[[v34-2-13]]

^<<v34-2-13,13>>^ A sentença foi publicada e o massacre dos sábios começou. Procuravam Daniel e seus companheiros para matá-los,

[[v34-2-14]]

^<<v34-2-14,14>>^ quando este dirigiu a Arioc, chefe da guarda do rei, que havia saído para executar todos os sábios babilônios, palavras cheias de prudência e sabedoria:

[[v34-2-15]]

^<<v34-2-15,15>>^ “Por que” – perguntou-lhe – “uma sentença tão severa da parte do rei?’’. Arioc expôs-lhe o assunto,

[[v34-2-16]]

^<<v34-2-16,16>>^ e logo Daniel se decidiu ir ao rei, para pedir-lhe a concessão de uma prorrogação: daria então ao rei a interpretação pedida.

[[v34-2-17]]

^<<v34-2-17,17>>^ Logo que voltou do rei, Daniel pôs a par do assunto seus companheiros Hananias, Misael e Azarias.

[[v34-2-18]]

^<<v34-2-18,18>>^ Pediu-lhes para implorarem a misericórdia do Deus dos céus a respeito desse enigma, a fim de que não matassem Daniel e seus companheiros com o resto da Babilônia.^&#42;1^

[[v34-2-19]]

^<<v34-2-19,19>>^ O mistério foi então revelado a Daniel em uma visão noturna. Pelo que, bendizendo o Deus dos céus,

[[v34-2-20]]

^<<v34-2-20,20>>^ Daniel expressou-se como segue: “Bendito seja o nome de Deus de eternidade em eternidade, porque a ele pertencem a sabedoria e o poder!

[[v34-2-21]]

^<<v34-2-21,21>>^ É ele quem faz mudar os tempos e as circunstâncias; é ele quem depõe os reis e os enaltece; é ele quem dá sabedoria aos sábios e talento aos inteligentes.

[[v34-2-22]]

^<<v34-2-22,22>>^ É ele quem revela os profundos e secretos mistérios, quem conhece o que está mergulhado nas trevas, junto ao qual habita a luz.

[[v34-2-23]]

^<<v34-2-23,23>>^ Ó Deus de meus pais, eu vos exalto e vos louvo, porque vós me destes a prudência e a força, e porque vós nos manifestastes o que vos pedimos, revelando-nos o sonho do rei”.

[[v34-2-24]]

^<<v34-2-24,24>>^ Depois disso, Daniel foi procurar Arioc, a quem o rei tinha incumbido do massacre dos sábios da Babilônia. E falou-lhe assim: “Não mandes matar os sábios da Babilônia. Introduze-me à presença do rei para que eu lhe dê a explicação”.

[[v34-2-25]]

^<<v34-2-25,25>>^ Arioc apressou-se em conduzir Daniel junto ao rei, dizendo-lhe: “Achei, entre os deportados da Judeia, um homem que dará ao rei a explicação desejada”.

[[v34-2-26]]

^<<v34-2-26,26>>^ O rei dirigiu a palavra a Daniel que tinha o cognome de Baltazar: “És realmente capaz” disse-lhe “de desvendar-me o sonho que tive e fornecer-me a interpretação?”.

[[v34-2-27]]

^<<v34-2-27,27>>^ “O mistério cuja revelação o rei pede” – respondeu Daniel ao rei – “nem os sábios, nem os mágicos, nem os feiticeiros, nem os astrólogos são capazes de revelar-lhos.

[[v34-2-28]]

^<<v34-2-28,28>>^ Mas no céu existe um Deus que desvenda os mistérios, o qual quis revelar ao rei Nabucodonosor o que deve suceder no decorrer dos tempos. Eis, portanto, teu sonho e as visões que se apresentaram a teu espírito quando estavas em teu leito.

[[v34-2-29]]

^<<v34-2-29,29>>^ Senhor, os pensamentos que vieram ao teu espírito, enquanto estavas em teu leito, são previsões do futuro: aquele que revela os mistérios mostrou-te o futuro.

[[v34-2-30]]

^<<v34-2-30,30>>^ Quanto a mim, se esse mistério me foi desvendado, não é que haja mais sabedoria em mim do que nos outros homens, mas para eu dar ao rei a interpretação, a fim de que se faça luz nos pensamentos do teu coração.”

[[v34-2-31]]

^<<v34-2-31,31>>^ “Senhor: contemplavas, e eis que uma grande, uma enorme estátua erguia-se diante de ti; era de um magnífico esplendor, mas de aspecto aterrador.

[[v34-2-32]]

^<<v34-2-32,32>>^ Sua cabeça era de fino ouro, seu peito e braços de prata, seu ventre e quadris de bronze,

[[v34-2-33]]

^<<v34-2-33,33>>^ suas pernas de ferro, seus pés metade de ferro e metade de barro.

[[v34-2-34]]

^<<v34-2-34,34>>^ Contemplavas essa estátua quando uma pedra se descolou da montanha, sem intervenção de mão alguma, veio bater nos pés, que eram de ferro e barro, e os triturou.^&#42;1^

[[v34-2-35]]

^<<v34-2-35,35>>^ Então o ferro, o barro, o bronze, a prata e o ouro foram com a mesma pancada reduzidos a migalhas, e, como a palha que voa da eira durante o verão, foram levados pelo vento sem deixar traço algum, enquanto que a pedra que havia batido na estátua tornou-se uma alta montanha, ocupando toda a região.

[[v34-2-36]]

^<<v34-2-36,36>>^ Eis o sonho. Agora vamos dar ao rei a interpretação.^&#42;1^

[[v34-2-37]]

^<<v34-2-37,37>>^ Senhor: tu que és o rei dos reis, a quem o Deus dos céus deu realeza, poder, força e glória;

[[v34-2-38]]

^<<v34-2-38,38>>^ a quem ele deu o domínio, onde quer que habitem, sobre os homens, os animais terrestres e os pássaros do céu, tu és a cabeça de ouro.

[[v34-2-39]]

^<<v34-2-39,39>>^ Depois de ti surgirá um outro reino menor que o teu, depois um terceiro reino, o de bronze, que dominará toda a terra.^&#42;1^

[[v34-2-40]]

^<<v34-2-40,40>>^ Um quarto reino será forte como o ferro: do mesmo modo que o ferro esmaga e tritura tudo, da mesma maneira ele esmagará e pulverizará todos os outros.^&#42;1^

[[v34-2-41]]

^<<v34-2-41,41>>^ Os pés e os dedos, parte de terra argilosa de modelar, parte de ferro, indicam que esse reino será dividido: haverá nele algo da solidez do ferro, já que viste ferro misturado ao barro.

[[v34-2-42]]

^<<v34-2-42,42>>^ Mas os dedos, metade de ferro e metade de barro, mostram que esse reino será ao mesmo tempo sólido e frágil.

[[v34-2-43]]

^<<v34-2-43,43>>^ Se viste o ferro misturado ao barro, é que as duas partes se aliarão por casamentos, sem porém se fundirem inteiramente, tal como o ferro que não se amalgama com o barro.^&#42;1^

[[v34-2-44]]

^<<v34-2-44,44>>^ No tempo desses reis, o Deus dos céus suscitará um reino que jamais será destruído e cuja soberania jamais passará a outro povo: destruirá e aniquilará todos os outros, enquanto que ele subsistirá eternamente.^&#42;1^

[[v34-2-45]]

^<<v34-2-45,45>>^ Foi o que pudeste ver na pedra deslocando-se da montanha sem a intervenção de mão alguma, e reduzindo a migalhas o ferro, o bronze, o barro, a prata e o ouro. Deus, que é grande, dá a conhecer ao rei a sucessão dos acontecimentos. O sonho é bem exato, e sua interpretação é digna de fé.”

[[v34-2-46]]

^<<v34-2-46,46>>^ Nesse instante, o rei Nabucodonosor atirou-se de rosto em terra, prostrado diante de Daniel; depois ordenou que lhe fossem oferecidos oblações e perfumes.

[[v34-2-47]]

^<<v34-2-47,47>>^ Dirigindo-se a Daniel, disse o rei: “Vosso Deus é verdadeiramente o Deus dos deuses, o Senhor dos reis; é também o revelador dos mistérios, já que pudeste revelar este”.

[[v34-2-48]]

^<<v34-2-48,48>>^ O rei elevou Daniel em dignidade, deu-lhe numerosos e ricos presentes; constituiu-o governador de toda a província da Babilônia e o tornou chefe supremo de todos os sábios da Babilônia.

[[v34-2-49]]

^<<v34-2-49,49>>^ Daniel pediu ao rei e confiou a Sidrac, Misac e Abdênago a administração da província da Babilônia. E Daniel permaneceu na corte real.^&#42;1^

'''

xref:034-daniel/034-daniel-001.adoc#v34-1-0[&#60; Capítulo Anterior] | <<v34-2-0,Topo>> | xref:034-daniel/034-daniel-003.adoc#v34-3-0[Próximo Capítulo &#62;]