include::./index.adoc[]

[[v1-36-0]]
=== Gênesis, 36
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 36 de Gênesis é dedicado à genealogia de Esaú e seus descendentes, apresentando uma lista de nomes e linhagens. Entre os temas abordados no capítulo, destacam-se a descendência de Esaú, a formação de nações a partir dessas linhagens e a relação entre os edomitas e outros povos.
* Deuteronômio 2:12 - "Haviam morado nela os horeus, povo grande, e numeroso, e alto como os anaquins." Este versículo faz referência aos horeus, um dos povos que habitavam a região de Seir antes da chegada dos edomitas, como mencionado em Gênesis 36:20.
* Isaías 34:5-6 - "Porque será o meu gládio embriagado nos céus; eis que sobre Edom descerá, e sobre o povo do meu anátema para exercer juízo. A espada do Senhor está cheia de sangue, está engordurada da gordura do sangue de carneiros e de bodes, da gordura dos rins de carneiros cordeiros; porque o Senhor tem sacrifício em Bozra, e grande matança na terra de Edom." Esse versículo fala da destruição iminente de Edom pelas mãos de Deus, apresentando um contraponto à glória dos edomitas apresentada no capítulo 36 de Gênesis.
* Ezequiel 25:12-14 - "Assim diz o Senhor Deus: Porquanto Edom se houve vingativamente para com a casa de Judá, e se culpou grandemente vingando-se dela; portanto assim diz o Senhor Deus: Também estenderei a minha mão sobre Edom, e dela eliminarei homens e animais; e a transformarei em desolação; desde Temã até Dedã cairão à espada." Esse versículo apresenta a punição de Deus sobre Edom por ter se vingado de Judá, uma referência aos conflitos entre esses dois povos mencionados em Gênesis 36.
* Obadias 1:8 - "Não naquele dia, diz o Senhor, destruirei os sábios de Edom, e o entendimento do monte de Esaú?" Esse versículo faz referência aos sábios de Edom e sua sabedoria, algo que é destacado em Gênesis 36:15-19.
* Malaquias 1:2-3 - "Eu vos amei, diz o Senhor; mas vós dizeis: Em que nos amaste? Não era Esaú irmão de Jacó? disse o Senhor; todavia amei a Jacó, e aborreci a Esaú; e fiz dos seus montes uma desolação, e dei a sua herança aos chacais do deserto." Esse versículo apresenta o amor de Deus por Jacó e sua descendência, em contraste com a rejeição de Esaú e sua descendência, como apresentado em Gênesis 36.
****

[[v1-36-1]]

^<<v1-36-1,1>>^ Eis a descendência de Esaú, também chamado Edom.

[[v1-36-2]]

^<<v1-36-2,2>>^ Esaú tomou suas mulheres entre as filhas de Canaã: Ada, filha de Elon, o hiteu; Oolibama, filha de Ana, filha de Sebeon, o heveu;

[[v1-36-3]]

^<<v1-36-3,3>>^ e Basemat, filha de Ismael, irmã de Nabaiot.

[[v1-36-4]]

^<<v1-36-4,4>>^ Ada deu a Esaú, Elifaz; Basemat deu à luz Rauel, e Oolibama deu à luz Jeús, Jalam e Coré.

[[v1-36-5]]

^<<v1-36-5,5>>^ Tais são os filhos nascidos a Esaú na terra de Canaã.

[[v1-36-6]]

^<<v1-36-6,6>>^ Esaú tomou suas mulheres, seus filhos e suas filhas, assim como todo o seu pessoal, seus rebanhos, seus animais e todos os bens que tinha adquirido na terra de Canaã, e mudou-se para longe de seu irmão Jacó.

[[v1-36-7]]

^<<v1-36-7,7>>^ Seus bens eram, com efeito, numerosos demais para que pudessem morar juntos, e a terra em que habitavam não lhes bastava, por causa dos seus muitos rebanhos.

[[v1-36-8]]

^<<v1-36-8,8>>^ Esaú estabeleceu-se na montanha de Seir. Esaú chamava-se também Edom.

[[v1-36-9]]

^<<v1-36-9,9>>^ Eis a descendência de Esaú, pai de Edom, na montanha de Seir.

[[v1-36-10]]

^<<v1-36-10,10>>^ Estes são os nomes dos filhos de Esaú: Elifaz, filho de Ada, mulher de Esaú; Rauel, filho de Basemat, mulher de Esaú.

[[v1-36-11]]

^<<v1-36-11,11>>^ Os filhos de Elifaz foram: Temã, Omar, Sefo, Gatam e Cenez.

[[v1-36-12]]

^<<v1-36-12,12>>^ Elifaz, filho de Esaú, tomou uma concubina, Tamna que lhe deu à luz Amalec. Estes são os filhos de Ada, mulher de Esaú.

[[v1-36-13]]

^<<v1-36-13,13>>^ Eis os filhos de Rauel: Naat, Zara, Sama e Meza. São estes os filhos de Basemat, mulher de Esaú.

[[v1-36-14]]

^<<v1-36-14,14>>^ Eis os filhos de Oolibama, filha de Ana, filha de Sebeon, mulher de Esaú: ela deu à luz Esaú, Jeús, Jalam e Coré.

[[v1-36-15]]

^<<v1-36-15,15>>^ Eis os chefes das tribos dos filhos de Esaú. Filhos de Elifaz, primogênito de Esaú: o chefe Temã, o chefe Omar, o chefe Sefo, o chefe Cenez, o chefe Coré,

[[v1-36-16]]

^<<v1-36-16,16>>^ o chefe Gatam, o chefe Amalec. Estes são os chefes saídos de Elifaz, na terra de Edom; tais são os filhos de Ada.

[[v1-36-17]]

^<<v1-36-17,17>>^ Filhos de Rauel, filho de Esaú: o chefe Naat, o chefe Zara, o chefe Sama e o chefe Meza. Tais são os chefes saídos de Rauel, na terra de Edom; estes são os filhos de Basemat, mulher de Esaú.

[[v1-36-18]]

^<<v1-36-18,18>>^ Filhos de Oolibama, mulher de Esaú: o chefe Jeús, o chefe Jalam e o chefe Coré. Estes são os chefes saídos de Oolibama, filha de Ana e mulher de Esaú.

[[v1-36-19]]

^<<v1-36-19,19>>^ Tais são os filhos de Esaú, e estes são os seus chefes; isto é, de Edom.

[[v1-36-20]]

^<<v1-36-20,20>>^ Eis os filhos de Seir, o horreu, que habitava naquela terra: Lotã, Sobal, Sebeon, Ana,

[[v1-36-21]]

^<<v1-36-21,21>>^ Dison, Eser e Disã. Tais são os chefes dos horreus, filhos de Seir, na terra de Edom.

[[v1-36-22]]

^<<v1-36-22,22>>^ Os filhos de Lotã foram Hori e Hemã; a irmã de Lotã era Tamna.

[[v1-36-23]]

^<<v1-36-23,23>>^ Eis os filhos de Sobal: Alvã, Manaat, Ebal, Sefo e Onam.

[[v1-36-24]]

^<<v1-36-24,24>>^ Eis os filhos de Sebeon: Aia e Ana. Foi esta Ana que encontrou no deserto as fontes de água quente, quando pastoreava os jumentos de Sebeon, seu pai.

[[v1-36-25]]

^<<v1-36-25,25>>^ Eis os filhos de Ana: Dison e Oolibama, filha de Ana.

[[v1-36-26]]

^<<v1-36-26,26>>^ Eis os filhos de Dison: Hamdã, Esebã, Jetraã e Caraã.

[[v1-36-27]]

^<<v1-36-27,27>>^ Eis os filhos de Eser: Balaã, Zavã e Acã.

[[v1-36-28]]

^<<v1-36-28,28>>^ Eis os filhos de Disã: Hus e Aram.

[[v1-36-29]]

^<<v1-36-29,29>>^ Eis os chefes dos horreus: o chefe Lotã, o chefe Sobal, o chefe Sebeon, o chefe Aná,

[[v1-36-30]]

^<<v1-36-30,30>>^ o chefe Dison, o chefe Eser, o chefe Disã. Esses são os chefes dos horreus, que governaram na terra de Seir.

[[v1-36-31]]

^<<v1-36-31,31>>^ Estes são os reis que reinaram na terra de Edom, antes que os filhos de Israel tivessem rei:

[[v1-36-32]]

^<<v1-36-32,32>>^ Bela, filho de Beor, reinou em Edom; sua cidade chamava-se Denaba.

[[v1-36-33]]

^<<v1-36-33,33>>^ Morrendo Bela, Jobab, filho de Zara, de Bosra, reinou em seu lugar.

[[v1-36-34]]

^<<v1-36-34,34>>^ Morto Jobab, Husam, da terra dos temanitas, reinou em seu lugar.

[[v1-36-35]]

^<<v1-36-35,35>>^ Morto Husam, Adad, filho de Badad, reinou em seu lugar; ele derrotou Madiã, nas terras de Moab; sua cidade chamava-se Avit.

[[v1-36-36]]

^<<v1-36-36,36>>^ Morto Adad, Semla, de Masreca, reinou em seu lugar.

[[v1-36-37]]

^<<v1-36-37,37>>^ Morto Semla, reinou em seu lugar, Saul, de Rehobot, que está perto do rio.

[[v1-36-38]]

^<<v1-36-38,38>>^ Com a morte de Saul, Baalanã, filho de Acor, reinou em seu lugar.

[[v1-36-39]]

^<<v1-36-39,39>>^ Com a morte de Baalanã, filho de Acor, Hadar reinou em seu lugar; sua cidade chamava-se Fau; sua mulher chamava-se Meetabel, filha de Matred, filha de Mezaab.

[[v1-36-40]]

^<<v1-36-40,40>>^ Eis os nomes dos chefes saídos de Esaú, segundo suas tribos, seus territórios e seus nomes: o chefe Tamna, o chefe Alva, o chefe Jetet,

[[v1-36-41]]

^<<v1-36-41,41>>^ o chefe Oolibama, o chefe Ela, o chefe Finon,

[[v1-36-42]]

^<<v1-36-42,42>>^ o chefe Cenez, o chefe Temã, o chefe Mabsar,

[[v1-36-43]]

^<<v1-36-43,43>>^ o chefe Magdiel, o chefe Iram. Esses são os chefes de Edom, segundo suas residências na terra que ocupavam. Eis aí Esaú, pai de Edom.

'''

xref:001-genesis/001-genesis-035.adoc#v1-35-0[&#60; Capítulo Anterior] | <<v1-36-0,Topo>> | xref:001-genesis/001-genesis-037.adoc#v1-37-0[Próximo Capítulo &#62;]