include::./index.adoc[]

[[v1-43-0]]
=== Gênesis, 43
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 43 continua a narrativa da história de José e seus irmãos. Jacó, o pai dos irmãos, instrui seus filhos a voltarem ao Egito para comprar mais comida, levando consigo o irmão mais jovem, Benjamim, que era o único irmão restante do filho amado de Jacó, José. Os temas abordados neste capítulo incluem amor paterno, arrependimento, sacrifício e providência divina.
* Deuteronômio 6:5: "Amarás, pois, o Senhor teu Deus de todo o teu coração, de toda a tua alma e de todas as tuas forças." A relação amorosa entre Jacó e seus filhos é um tema importante em Gênesis 43. O amor de Jacó por seus filhos é uma imagem do amor de Deus por Seus filhos, e este versículo de Deuteronômio enfatiza a importância do amor a Deus como um princípio fundamental.
* Provérbios 28:13: "O que encobre as suas transgressões nunca prosperará, mas o que as confessa e deixa, alcançará misericórdia." Judá, um dos irmãos de José, assume a responsabilidade de garantir que Benjamim seja mantido em segurança e promete a seu pai que ele o trará de volta. Este versículo enfatiza a importância do arrependimento e da confissão para alcançar a misericórdia.
* Hebreus 13:16: "Não negligencieis a prática do bem e a mútua cooperação, porque com tais sacrifícios Deus se agrada." Quando os irmãos de José voltam ao Egito, eles trazem consigo presentes para José. Este versículo enfatiza a importância do sacrifício e da prática do bem, e como isso agrada a Deus.
* Provérbios 16:9: "Em seu coração, o homem planeja seu caminho, mas o Senhor determina seus passos." A providência divina é um tema importante em Gênesis 43. A viagem dos irmãos de José para o Egito foi planejada por eles mesmos, mas o resultado final foi determinado por Deus. Este versículo enfatiza a soberania de Deus sobre todas as coisas.
* João 10:27-28: "As minhas ovelhas ouvem a minha voz; eu as conheço, e elas me seguem. Eu lhes dou a vida eterna, e jamais perecerão. Ninguém as poderá arrancar de minha mão." José se preocupa profundamente com seu irmão mais novo, Benjamim, e o protege da melhor maneira que pode. Este versículo enfatiza a segurança daqueles que pertencem a Deus e como Ele os protege e cuida deles.
****

[[v1-43-1]]

^<<v1-43-1,1>>^ A fome pesava sobre o país.

[[v1-43-2]]

^<<v1-43-2,2>>^ E tendo acabado o trigo trazido do Egito, o pai disse aos seus filhos: “Voltai e comprai-nos um pouco de víveres”.

[[v1-43-3]]

^<<v1-43-3,3>>^ Judá respondeu-lhe: “Aquele homem nos declarou formalmente que não voltássemos à sua presença sem levar conosco nosso irmão.

[[v1-43-4]]

^<<v1-43-4,4>>^ Se mandas nosso irmão conosco, desceremos para comprar víveres.

[[v1-43-5]]

^<<v1-43-5,5>>^ Mas, se o não deixas ir, não desceremos, porque ele nos disse: Não sereis admitidos em minha presença se vosso irmão não estiver convosco”.

[[v1-43-6]]

^<<v1-43-6,6>>^ Israel disse: “Por que me fizestes este mal, dando-lhe a conhecer que tínheis ainda um irmão?”.

[[v1-43-7]]

^<<v1-43-7,7>>^ “Aquele homem – responderam eles – perguntou por nós e por nossa família, e quis saber se nosso pai vivia ainda, se tínhamos outro irmão; e respondemos às suas perguntas. Podíamos, porventura, adivinhar que ele nos ia mandar levar a ele o nosso irmão?”

[[v1-43-8]]

^<<v1-43-8,8>>^ E Judá disse a Israel, seu pai: “Deixa partir o menino comigo, e nos poremos a caminho para essa viagem. Desse modo poderemos viver, e escaparemos à morte, nós, tu e nossos filhinhos.

[[v1-43-9]]

^<<v1-43-9,9>>^ Eu respondo por ele: é de mim que tu o reclamarás. Se eu não o reconduzir e não o recolocar diante de ti, serei eternamente culpado diante de ti.

[[v1-43-10]]

^<<v1-43-10,10>>^ Se não tivéssemos demorado tanto, certamente já pela segunda vez estaríamos de volta”.

[[v1-43-11]]

^<<v1-43-11,11>>^ “Se assim é – disse-lhes Israel, seu pai – tomai em vossas bagagens os melhores produtos da terra, e levai-os como presente a esse homem: um pouco de bálsamo, um pouco de mel, resina, ládano, nozes de pistácia e amêndoas.

[[v1-43-12]]

^<<v1-43-12,12>>^ Levai também convosco o dinheiro em dobro para restituir a soma que encontrastes na boca dos sacos, certamente por engano.

[[v1-43-13]]

^<<v1-43-13,13>>^ Tomai vosso irmão, parti e ide ter com esse homem.

[[v1-43-14]]

^<<v1-43-14,14>>^ Que o Deus Todo-poderoso vos faça ganhar os favores desse homem, a fim de que ele deixe voltar vosso irmão, juntamente com Benjamim. Quanto a mim, se devo ser privado de meus filhos, paciência, que eu seja privado deles!”

[[v1-43-15]]

^<<v1-43-15,15>>^ Tomaram, pois, consigo o presente e uma soma dobrada de dinheiro, assim como Benjamim, e partiram para o Egito. E apresentaram-se a José.

[[v1-43-16]]

^<<v1-43-16,16>>^ José, vendo-os e com eles Benjamim, disse ao seu intendente: “Faze entrar estes homens na casa, mata um animal, e prepara-o, pois comerão comigo ao meio-dia”.

[[v1-43-17]]

^<<v1-43-17,17>>^ Fez o intendente como José tinha dito: introduziu-os na casa de José.

[[v1-43-18]]

^<<v1-43-18,18>>^ Vendo isso, ficaram amedrontados: “É – diziam eles – por causa do dinheiro, encontrado da outra vez nos nossos sacos, que nos conduzem aqui. Vão-nos assaltar, cair sobre nós, escravizar-nos e apoderar-se de nossos jumentos”.

[[v1-43-19]]

^<<v1-43-19,19>>^ Então, aproximando-se do intendente da casa de José, falaram-lhe à entrada da casa:

[[v1-43-20]]

^<<v1-43-20,20>>^ “Desculpa, meu senhor – disseram eles – viemos já uma vez comprar víveres.

[[v1-43-21]]

^<<v1-43-21,21>>^ Quando chegamos à estalagem e abrimos nossos sacos, o dinheiro de cada um se encontrava na boca de seu saco: era o peso exato do dinheiro. Tornamos a trazê-lo conosco;

[[v1-43-22]]

^<<v1-43-22,22>>^ e trazemos, ao mesmo tempo, outra quantia para comprar víveres. Não sabemos quem tenha metido nosso dinheiro em nossos sacos”.

[[v1-43-23]]

^<<v1-43-23,23>>^ “Ficai tranquilos – respondeu-lhes ele – nada temais. É o vosso Deus, o Deus de vossos pais, quem vos pôs um tesouro em vossos sacos; o vosso dinheiro me foi entregue.” Depois trouxe-lhes Simeão.

[[v1-43-24]]

^<<v1-43-24,24>>^ Fê-los em seguida entrar na casa de José, deu-lhes água para lavarem os pés e forragem para os seus jumentos.

[[v1-43-25]]

^<<v1-43-25,25>>^ E, enquanto esperavam por José, que devia voltar ao meio-dia, preparavam o seu presente, pois foi-lhes anunciado que comeriam em casa dele.

[[v1-43-26]]

^<<v1-43-26,26>>^ Logo que José entrou em casa, ofereceram-lhe os presentes que tinham trazido, prostrando-se diante dele até a terra.

[[v1-43-27]]

^<<v1-43-27,27>>^ Ele perguntou pela saúde deles e ajuntou: “Vosso velho pai, do qual me falastes, vai bem? Ainda vive?”.

[[v1-43-28]]

^<<v1-43-28,28>>^ “Teu servo, nosso pai, está passando bem; e vive ainda” – responderam-lhe inclinando-se até o solo.

[[v1-43-29]]

^<<v1-43-29,29>>^ Então, levantando os olhos, José viu Benjamim, seu irmão, filho de sua mãe. “É este – disse ele – vosso irmão mais novo do qual me falastes?” E ajuntou: “Que Deus te faça misericórdia, meu filho!”.

[[v1-43-30]]

^<<v1-43-30,30>>^ E retirou-se precipitadamente, porque suas entranhas se tinham comovido por causa de seu irmão, e tinha vontade de chorar; entrou em seu quarto e deu livre curso às lágrimas.

[[v1-43-31]]

^<<v1-43-31,31>>^ Depois de ter lavado o rosto saiu e, procurando dominar-se, disse: “Servi a mesa”.

[[v1-43-32]]

^<<v1-43-32,32>>^ Foi-lhe servido à parte, seus irmãos também à parte, e igualmente à parte os egípcios, seus comensais, porque lhes é proibido comer com hebreus, por ser abominável para eles.

[[v1-43-33]]

^<<v1-43-33,33>>^ Os irmãos de José foram colocados diante dele, desde o mais velho até o mais novo, segundo sua idade, o que lhes fez olhar uns para os outros assombrados.

[[v1-43-34]]

^<<v1-43-34,34>>^ José mandou que se lhes trouxessem porções de sua própria mesa, e a parte de Benjamim foi cinco vezes maior que a dos outros. Eles beberam e alegraram-se com ele.

'''

xref:001-genesis/001-genesis-042.adoc#v1-42-0[&#60; Capítulo Anterior] | <<v1-43-0,Topo>> | xref:001-genesis/001-genesis-044.adoc#v1-44-0[Próximo Capítulo &#62;]