include::./index.adoc[]

[[v1-15-0]]
=== Gênesis, 15
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 15 de Gênesis começa com Deus reafirmando sua promessa de dar a Abraão uma descendência numerosa e uma terra para habitarem. Abraão expressa sua preocupação em relação a isso, e Deus faz um pacto com ele, simbolizado pelo sacrifício de animais. Abraão adormece e Deus lhe dá uma visão profética do futuro do seu povo. Abaixo estão cinco versículos relacionados com os temas abordados em Gênesis 15:
* Salmos 105:9-11: "Ele se lembra para sempre da sua aliança, da palavra que ordenou, para mil gerações, da aliança que fez com Abraão, do juramento que fez a Isaque. Ele o confirmou como decreto a Jacó, como aliança eterna a Israel". Este salmo fala da aliança que Deus fez com Abraão e como ela foi estendida a seus descendentes.
* Romanos 4:3: "Pois, que diz a Escritura? Abraão creu em Deus, e isso lhe foi creditado como justiça". Este verso é uma referência ao momento em que Deus fez a promessa de uma grande descendência a Abraão, e ele creu em Deus.
* Hebreus 6:13-14: "Quando Deus fez a promessa a Abraão, como não tinha ninguém maior por quem jurar, jurou por si mesmo, dizendo: Certamente o abençoarei e lhe multiplicarei os descendentes". Este verso destaca o fato de que Deus fez uma promessa a Abraão e a cumpriu.
* Gálatas 3:16: "As promessas foram feitas a Abraão e ao seu descendente. A Escritura não diz: "E aos descendentes", querendo significar muitos, mas "E ao seu descendente", querendo significar um só, que é Cristo". Este verso destaca a importância da descendência de Abraão e sua relação com Jesus Cristo.
* João 8:56: "Abraão, pai de vocês, alegrou-se com o pensamento de ver o meu dia; ele o viu e alegrou-se". Este verso fala da visão profética que Deus deu a Abraão, mostrando-lhe o futuro, inclusive a vinda de Jesus Cristo.
****

[[v1-15-1]]

^<<v1-15-1,1>>^ Depois desses acontecimentos, a palavra do Senhor foi dirigida a Abrão, numa visão, nestes termos: “Nada temas, Abrão! Eu sou o teu protetor; tua recompensa será muito grande”.

[[v1-15-2]]

^<<v1-15-2,2>>^ Abrão respondeu: “Senhor Javé, que me dareis vós? Eu irei sem filhos, e o herdeiro de minha casa é Eliezer de Damasco”.

[[v1-15-3]]

^<<v1-15-3,3>>^ E ajuntou: “Vós não me destes posteridade, e é um escravo nascido em minha casa que será o meu herdeiro”.

[[v1-15-4]]

^<<v1-15-4,4>>^ Então a palavra do Senhor foi-lhe dirigida nestes termos: “Não é ele que será o teu herdeiro, mas aquele que vai sair de tuas entranhas”.

[[v1-15-5]]

^<<v1-15-5,5>>^ E, conduzindo-o fora, disse-lhe: “Levanta os olhos para o céu e conta as estrelas, se és capaz... Pois bem – ajuntou ele – assim será a tua descendência”.^&#42;1^

[[v1-15-6]]

^<<v1-15-6,6>>^ Abrão confiou no Senhor, e o Senhor “lhe imputou isso” “para sua justificação”.^&#42;1^

[[v1-15-7]]

^<<v1-15-7,7>>^ E disse-lhe: “Eu sou o Senhor que te fiz sair de Ur da Caldeia para dar-te esta terra”.

[[v1-15-8]]

^<<v1-15-8,8>>^ “Senhor Javé, como poderei saber se a vou possuí-la?”

[[v1-15-9]]

^<<v1-15-9,9>>^ “Toma uma novilha de três anos – respondeu-lhe o Senhor – uma cabra de três anos, um cordeiro de três anos, uma rola e um pombinho.”

[[v1-15-10]]

^<<v1-15-10,10>>^ Abrão tomou todos esses animais, e dividiu-os pelo meio, colocando suas metades uma defronte da outra; mas não cortou as aves.

[[v1-15-11]]

^<<v1-15-11,11>>^ Vieram as aves de rapina e atiraram-se sobre os cadáveres, mas Abrão as expulsou.

[[v1-15-12]]

^<<v1-15-12,12>>^ E eis que, ao pôr do sol, veio um profundo sono a Abrão, ao mesmo tempo que o assaltou um grande pavor, uma espessa escuridão.

[[v1-15-13]]

^<<v1-15-13,13>>^ O Senhor disse-lhe: “Sabe que teus descendentes habitarão como peregrinos numa terra que não é sua, e que nessa terra eles serão escravizados e oprimidos durante quatrocentos anos.

[[v1-15-14]]

^<<v1-15-14,14>>^ Mas eu julgarei também o povo ao qual estiverem sujeitos, e sairão em seguida dessa terra com grandes riquezas.

[[v1-15-15]]

^<<v1-15-15,15>>^ Quanto a ti, irás em paz juntar-se aos teus pais, e serás sepultado numa ditosa velhice.

[[v1-15-16]]

^<<v1-15-16,16>>^ Somente à quarta geração os teus descendentes voltarão para aqui, porque a iniquidade dos amorreus não chegou ainda ao seu cúmulo”.

[[v1-15-17]]

^<<v1-15-17,17>>^ Quando o sol se pôs, formou-se uma densa escuridão, e eis que um braseiro fumegante e uma tocha ardente passaram pelo meio das carnes divididas.

[[v1-15-18]]

^<<v1-15-18,18>>^ Naquele dia, o Senhor fez aliança com Abrão: “Eu dou – disse ele – esta terra aos teus descendentes, desde a torrente do Egito até o grande rio Eufrates:

[[v1-15-19]]

^<<v1-15-19,19>>^ a terra dos cineus, dos ceneseus, dos cadmoneus,

[[v1-15-20]]

^<<v1-15-20,20>>^ dos heteus, dos ferezeus,

[[v1-15-21]]

^<<v1-15-21,21>>^ dos amorreus, dos cananeus, dos gergeseus e dos jebuseus”.

'''

xref:001-genesis/001-genesis-014.adoc#v1-14-0[&#60; Capítulo Anterior] | <<v1-15-0,Topo>> | xref:001-genesis/001-genesis-016.adoc#v1-16-0[Próximo Capítulo &#62;]