include::./index.adoc[]

[[v1-48-0]]
=== Gênesis, 48
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 48 narra o momento em que Jacó abençoa seus netos Efraim e Manassés, os filhos de José. Jacó concede a bênção da primogenitura a Efraim, o mais novo, em vez de Manassés, o mais velho, o que foi incomum na cultura da época. Os cinco versículos a seguir foram selecionados por sua relevância com os temas abordados neste capítulo.
* 1 Timóteo 4:14: "Não desprezes o dom que há em ti, o qual te foi dado por profecia, com a imposição das mãos do presbítero." A bênção de Jacó sobre Efraim e Manassés é um exemplo de como um líder pode identificar e abençoar aqueles que têm dons e habilidades especiais, mesmo que não sejam os mais velhos ou mais óbvios.
* Romanos 8:17: "E, se nós somos filhos, somos logo herdeiros também, herdeiros de Deus, e co-herdeiros de Cristo: se é certo que com ele padecemos, para que também com ele sejamos glorificados." A bênção da primogenitura concedida a Efraim e não a Manassés é um exemplo de como Deus muitas vezes escolhe os menos óbvios ou aparentemente menos capazes para receber bênçãos e honras.
* Provérbios 17:6: "Coroa dos velhos são os filhos dos filhos; e a glória dos filhos são seus pais." Jacó demonstra amor e cuidado por seus netos, abençoando-os e reconhecendo a importância da próxima geração para a continuidade da família e do legado.
* 1 Pedro 2:9: "Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz." A bênção concedida a Efraim e Manassés é um exemplo de como Deus pode usar a próxima geração para realizar seus propósitos e transmitir seus valores.
* Hebreus 11:21: "Pela fé, Jacó, próximo da morte, abençoou cada um dos filhos de José, e adorou, inclinado sobre a extremidade do seu bordão." A bênção de Jacó sobre seus netos é um exemplo de como a fé pode inspirar um pai ou avô a abençoar e transmitir valores espirituais à próxima geração.
****

[[v1-48-1]]

^<<v1-48-1,1>>^ Depois disso, vieram anunciar a José: “Teu pai está doente”. Tomou então com ele seus dois filhos, Manassés e Efraim.

[[v1-48-2]]

^<<v1-48-2,2>>^ Jacó foi avisado disso: “Eis – disseram-lhe – que o teu filho José vem te ver”. Israel, reunindo suas forças, assentou-se no seu leito.

[[v1-48-3]]

^<<v1-48-3,3>>^ E disse a José: “O Deus Todo-poderoso apareceu-me em Luza, na terra de Canaã, e abençoou-me.

[[v1-48-4]]

^<<v1-48-4,4>>^ Disse-me: ‘Eu te tornarei fecundo e te multiplicarei até fazer de ti uma assembleia de povos, e darei esta terra à tua posteridade em possessão eterna’.

[[v1-48-5]]

^<<v1-48-5,5>>^ Agora, os dois filhos que te nasceram no Egito antes que eu viesse para junto de ti, são meus filhos: Efraim e Manassés são meus, com o mesmo título que Rúben e Simeão.

[[v1-48-6]]

^<<v1-48-6,6>>^ Os filhos, porém, que tiveste depois deles, são teus: é conforme o nome de seus irmãos que eles terão parte na repartição da herança.

[[v1-48-7]]

^<<v1-48-7,7>>^ Quando eu voltava de Padã-Aram, tua mãe Raquel morreu em caminho, perto de mim, na terra de Canaã, a alguma distância de Éfrata; foi ali que a enterrei, no caminho de Éfrata, hoje Belém”.

[[v1-48-8]]

^<<v1-48-8,8>>^ Israel viu os filhos de José e disse: “Quem são estes?”.

[[v1-48-9]]

^<<v1-48-9,9>>^ “São – respondeu José – os filhos que Deus me deu aqui.” “Faze-os aproximarem-se, para que eu os abençoe.”

[[v1-48-10]]

^<<v1-48-10,10>>^ Os olhos de Israel tinham-se enfraquecido tanto pela idade, que já não podia ver. José fê-los aproximarem-se dele e Israel, tomando-os em seus braços, beijou-os.

[[v1-48-11]]

^<<v1-48-11,11>>^ Depois disse a José: “Não esperava mais rever-te, e eis que Deus me fez ver teus filhos”.

[[v1-48-12]]

^<<v1-48-12,12>>^ José tirou-os dos joelhos de seu pai e prostrou-se com o rosto por terra.

[[v1-48-13]]

^<<v1-48-13,13>>^ Tomou depois os dois, Efraim pela mão direita, para colocá-lo à esquerda de Israel, e Manassés pela mão esquerda, para colocá-lo à direita de Israel, e fê-los aproximarem-se.

[[v1-48-14]]

^<<v1-48-14,14>>^ Mas Israel estendeu a mão direita e pô-la sobre a cabeça de Efraim, o caçula, e a mão esquerda sobre a cabeça de Manassés. Cruzou assim as mãos porque Manassés era o primogênito.

[[v1-48-15]]

^<<v1-48-15,15>>^ Israel abençoou José, dizendo: “O Deus em cujo caminho andaram meus pais Abraão e Isaac, o Deus que tem sido o meu pastor durante toda a minha vida até este dia,^&#42;1^

[[v1-48-16]]

^<<v1-48-16,16>>^ o anjo que me guardou de todo o mal, abençoe estes meninos! Seja perpetuado neles o meu nome e o de meus pais Abraão e Isaac, e multipliquem-se abundantemente nesta terra!”.

[[v1-48-17]]

^<<v1-48-17,17>>^ Vendo José que seu pai tinha colocado a mão direita sobre a cabeça de Efraim, contrariou-se e tomou a mão de seu pai para removê-la da cabeça de Efraim para a cabeça de Manassés.

[[v1-48-18]]

^<<v1-48-18,18>>^ E disse-lhe: “Não assim, meu pai; é este aqui o primogênito; põe tua mão direita sobre sua cabeça”.

[[v1-48-19]]

^<<v1-48-19,19>>^ Seu pai, porém, recusou: “Eu sei, meu filho – disse ele – eu sei. Ele também se tornará um povo e será grande; mas seu irmão mais novo crescerá mais do que ele e sua posteridade se tornará uma multidão de nações”.

[[v1-48-20]]

^<<v1-48-20,20>>^ Abençoou-os, pois, naquele dia, e disse: “Israel vos nomeará em suas bênçãos; se dirá: Deus te torne semelhante a Efraim e a Manassés”. Foi assim que ele pôs Efraim na frente de Manassés.

[[v1-48-21]]

^<<v1-48-21,21>>^ Israel disse a José: “Vou morrer. Mas Deus estará convosco e vos reconduzirá à terra de vossos pais.

[[v1-48-22]]

^<<v1-48-22,22>>^ Dou-te a mais que teus irmãos, uma porção que conquistei aos amorreus com minha espada e meu arco”.^&#42;1^

'''

xref:001-genesis/001-genesis-047.adoc#v1-47-0[&#60; Capítulo Anterior] | <<v1-48-0,Topo>> | xref:001-genesis/001-genesis-049.adoc#v1-49-0[Próximo Capítulo &#62;]