include::./index.adoc[]

[[v1-37-0]]
=== Gênesis, 37
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em Gênesis 37, é narrada a história de José, o filho preferido de Jacó, que é vendido como escravo pelos seus próprios irmãos devido a ciúmes e inveja. Os versículos escolhidos são:
* Provérbios 14:30 - "O coração tranquilo é a vida do corpo, mas a inveja é a podridão dos ossos." Os irmãos de José são consumidos pela inveja e ela se torna a raiz de suas más ações.
* Gálatas 5:19-21 - "As obras da carne são manifestas, as quais são: adultério, prostituição, impureza, lascívia, idolatria, feitiçarias, inimizades, porfias, emulações, iras, pelejas, dissensões, heresias, invejas, homicídios, bebedices, glutonarias, e coisas semelhantes a estas, acerca das quais vos declaro, como já antes vos disse, que os que cometem tais coisas não herdarão o Reino de Deus." As más ações dos irmãos de José são um exemplo das obras da carne mencionadas por Paulo.
* 2 Coríntios 12:10 - "Por isso sinto prazer nas fraquezas, nas injúrias, nas necessidades, nas perseguições, nas angústias, por amor de Cristo. Porque quando sou fraco, então é que sou forte." José passa por muitas dificuldades, mas é fortalecido pela sua fé em Deus.
* Romanos 8:28 - "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados por seu decreto." A história de José é uma prova de que mesmo as situações mais difíceis podem ser usadas por Deus para cumprir seus planos.
* Tiago 1:2-4 - "Meus irmãos, tende por motivo de grande gozo o passardes por várias provações, sabendo que a provação da vossa fé opera a paciência; e a paciência tenha a sua obra perfeita, para que sejais perfeitos e completos, sem faltar em coisa alguma." A história de José é um exemplo de como as provações podem fortalecer a fé e a paciência de uma pessoa.
****

[[v1-37-1]]

^<<v1-37-1,1>>^ Jacó habitou na região onde seu pai havia morado, na terra de Canaã.

[[v1-37-2]]

^<<v1-37-2,2>>^ Eis a história da descendência de Jacó: José, ainda jovem, com a idade de dezessete anos, apascentava o rebanho com seus irmãos, os filhos de Bala e os filhos de Zelfa, mulheres de seu pai; e ele contou ao seu pai as más conversas dos irmãos.

[[v1-37-3]]

^<<v1-37-3,3>>^ Israel amava José mais do que todos os outros filhos, porque ele era o filho de sua velhice; e mandara-lhe fazer uma túnica de várias cores.

[[v1-37-4]]

^<<v1-37-4,4>>^ Seus irmãos, vendo que seu pai o preferia a eles, começaram a odiá-lo e não podiam mais tratá-lo com bons modos.

[[v1-37-5]]

^<<v1-37-5,5>>^ Ora, José teve um sonho, e o contou aos seus irmãos, que o detestaram ainda mais. José disse-lhe:

[[v1-37-6]]

^<<v1-37-6,6>>^ “Ouvi o sonho que tive:

[[v1-37-7]]

^<<v1-37-7,7>>^ estávamos ligando feixes no campo, e eis que o meu feixe se levantou e se pôs de pé, enquanto os vossos o cercavam e se prostravam diante dele”.

[[v1-37-8]]

^<<v1-37-8,8>>^ Seus irmãos disseram-lhe: “Quererias, porventura, reinar sobre nós e tornar-te nosso senhor?”. E odiaram-no ainda mais por causa de seus sonhos e de suas palavras.

[[v1-37-9]]

^<<v1-37-9,9>>^ José teve ainda outro sonho, que contou aos seus irmãos. “Tive – disse ele – ainda um sonho: o sol, a lua e onze estrelas prostravam-se diante de mim.”

[[v1-37-10]]

^<<v1-37-10,10>>^ Ele contou isso ao seu pai e aos seus irmãos, mas foi repreendido por seu pai: “Que significa – disse-lhe ele – este sonho que tiveste? Viremos, acaso, eu, tua mãe e teus irmãos, a nos prostrar por terra diante de ti?”.

[[v1-37-11]]

^<<v1-37-11,11>>^ Seus irmãos ficaram, pois, com inveja dele, mas seu pai guardou a lembrança desse acontecimento.

[[v1-37-12]]

^<<v1-37-12,12>>^ Os irmãos de José foram apascentar os rebanhos de seu pai em Siquém.

[[v1-37-13]]

^<<v1-37-13,13>>^ Israel disse a José: “Teus irmãos guardam os rebanhos em Siquém. Vem: vou mandar-te a eles”. “Eis-me aqui” – respondeu José.

[[v1-37-14]]

^<<v1-37-14,14>>^ “Vai, pois, ver se tudo corre bem a teus irmãos e ao rebanho, e traze-me notícias deles.” Enviou-o do vale de Hebron, e José foi a Siquém.

[[v1-37-15]]

^<<v1-37-15,15>>^ Um homem encontrou-o vagando pelo campo: “Que buscas?” – perguntou ele.

[[v1-37-16]]

^<<v1-37-16,16>>^ “Busco meus irmãos – respondeu ele. Dize-me onde apascentam os rebanhos.”

[[v1-37-17]]

^<<v1-37-17,17>>^ E o homem respondeu: “Partiram daqui e ouvi-os dizer: ‘Vamos para Dotain’.” Partiu então José em busca dos seus irmãos e encontrou-os em Dotain.

[[v1-37-18]]

^<<v1-37-18,18>>^ Eles o viram de longe. Antes que José se aproximasse, combinaram entre si como o haveriam de matar;

[[v1-37-19]]

^<<v1-37-19,19>>^ e disseram uns aos outros: “Eis o sonhador que chega.

[[v1-37-20]]

^<<v1-37-20,20>>^ Vamos, matemo-lo e atiremo-lo numa cisterna; diremos depois que uma fera o devorou; e então veremos de que lhe aproveitaram os seus sonhos”.

[[v1-37-21]]

^<<v1-37-21,21>>^ Ouvindo-o, porém, Rúben, quis livrá-lo de suas mãos: “Não lhe tiremos a vida – disse ele.

[[v1-37-22]]

^<<v1-37-22,22>>^ Não derrameis sangue. Jogai-o naquela cisterna, no deserto, mas não levanteis vossa mão contra ele”. Pois Rúben pensava livrá-lo de suas mãos para o reconduzir ao pai.

[[v1-37-23]]

^<<v1-37-23,23>>^ Quando José se aproximou de seus irmãos, eles o despojaram de sua túnica, daquela bela túnica de várias cores que trazia,

[[v1-37-24]]

^<<v1-37-24,24>>^ e jogaram-no numa cisterna velha, que não tinha água.

[[v1-37-25]]

^<<v1-37-25,25>>^ E, sentando-se para comer, eis que, levantando os olhos, viram surgir no horizonte uma caravana de ismaelitas vinda de Galaad. Seus camelos estavam carregados de resina, de bálsamo e de ládano, que transportavam para o Egito.^&#42;1^

[[v1-37-26]]

^<<v1-37-26,26>>^ Então Judá disse aos seus irmãos: “Que nos aproveita matar nosso irmão e ocultar o seu sangue?

[[v1-37-27]]

^<<v1-37-27,27>>^ Vinde e vendamo-lo aos ismaelitas. Não levantemos nossas mãos contra ele, pois, afinal, é nosso irmão, nossa carne”. Seus irmãos concordaram.

[[v1-37-28]]

^<<v1-37-28,28>>^ E, quando passaram os negociantes madianitas, tiraram José da cisterna e venderam-no por vinte moedas de prata aos ismaelitas, que o levaram para o Egito.

[[v1-37-29]]

^<<v1-37-29,29>>^ Rúben voltou à cisterna, e eis que José já não estava ali.

[[v1-37-30]]

^<<v1-37-30,30>>^ Rasgou então suas vestes e voltou para junto dos seus irmãos: “O menino desapareceu – disse ele. E eu, para onde irei?”.

[[v1-37-31]]

^<<v1-37-31,31>>^ Tomaram então a túnica de José, mataram um cabrito e a mergulharam no seu sangue.

[[v1-37-32]]

^<<v1-37-32,32>>^ E mandaram-na levar ao seu pai com esta mensagem: “Eis o que encontramos: vê se não é, porventura, a túnica do teu filho”.

[[v1-37-33]]

^<<v1-37-33,33>>^ Jacó reconheceu-a e exclamou: “É a túnica de meu filho! Uma fera o devorou! José foi estraçalhado!”.

[[v1-37-34]]

^<<v1-37-34,34>>^ E, rasgando as vestes, cobriu-se de um saco, e chorou o seu filho por muito tempo.

[[v1-37-35]]

^<<v1-37-35,35>>^ Todos os seus filhos e filhas vieram consolá-lo, mas ele não aceitou nenhuma condolência: “É chorando – disse ele – que descerei para junto de meu filho na habitação dos mortos”. Foi assim que o seu pai o chorou.^&#42;1^

[[v1-37-36]]

^<<v1-37-36,36>>^ Os madianitas venderam-no a Putifar, no Egito, eunuco do faraó e chefe da guarda.

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]