include::./index.adoc[]

[[v1-2-0]]
=== Gênesis, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 2 é o segundo capítulo da Bíblia e detalha a criação do homem e da mulher por Deus. Ele descreve como Deus criou o homem a partir do pó da terra e soprou em suas narinas o fôlego da vida, criou o jardim do Éden para o homem habitar, colocou o homem no jardim e lhe deu a tarefa de cultivá-lo e guardar, e criou a mulher a partir da costela do homem. A seguir, estão cinco versículos da Bíblia que se relacionam com temas abordados em Gênesis 2:
* Salmos 139:14: "Eu te louvarei, porque de um modo tão admirável e maravilhoso fui formado; maravilhosas são as tuas obras, e a minha alma o sabe muito bem." Esse salmo destaca a criação do homem por Deus, incluindo a forma como ele foi criado a partir do pó da terra, conforme descrito em Gênesis 2.
* Provérbios 18:22: "Quem encontra uma esposa encontra uma coisa boa, e alcança a benevolência do Senhor." Esse versículo se relaciona com a criação da mulher por Deus a partir da costela do homem, conforme descrito em Gênesis 2.
* Efésios 5:25: "Vós, maridos, amai a vossas mulheres, como também Cristo amou a igreja, e a si mesmo se entregou por ela." Esse versículo se relaciona com a criação da mulher por Deus e destaca o papel do marido em amar e cuidar de sua esposa, conforme descrito em Gênesis 2.
* 1 Coríntios 11:8-9: "Porque o homem não provém da mulher, mas a mulher do homem. Porque também o homem não foi criado por causa da mulher, mas a mulher por causa do homem." Esses versículos se relacionam com a criação da mulher por Deus a partir da costela do homem e destacam a ordem divina em relação aos papéis do homem e da mulher.
* Apocalipse 22:2: "No meio da sua praça, de um e de outro lado do rio, estava a árvore da vida, que produz doze frutos, dando o seu fruto de mês em mês; e as folhas da árvore são para a saúde das nações." Esse versículo se relaciona com a criação do jardim do Éden por Deus, conforme descrito em Gênesis 2, e destaca a presença da árvore da vida no paraíso.
****

[[v1-2-1]]

^<<v1-2-1,1>>^ Assim foram concluídos o céu, a terra e todo o seu exército.

[[v1-2-2]]

^<<v1-2-2,2>>^ Tendo Deus terminado no sétimo dia a obra que tinha feito, descansou do seu trabalho.^&#42;1^

[[v1-2-3]]

^<<v1-2-3,3>>^ Ele abençoou o sétimo dia e o consagrou, porque nesse dia descansou de toda a obra da Criação.

[[v1-2-4]]

^<<v1-2-4,4>>^ Tal é a história da criação do céu e da terra. No tempo em que o Senhor Deus fez a terra e o céu,

[[v1-2-5]]

^<<v1-2-5,5>>^ não existia ainda sobre a terra nenhum arbusto nos campos, e nenhuma erva havia ainda brotado nos campos, porque o Senhor Deus não tinha feito chover sobre a terra, nem havia homem que a cultivasse;

[[v1-2-6]]

^<<v1-2-6,6>>^ mas subia da terra um vapor que regava toda a sua superfície.

[[v1-2-7]]

^<<v1-2-7,7>>^ O Senhor Deus formou, pois, o homem do barro da terra, e inspirou-lhe nas narinas o sopro da vida e o homem se tornou um ser vivente.^&#42;1^

[[v1-2-8]]

^<<v1-2-8,8>>^ Ora, o Senhor Deus tinha plantado um jardim no Éden, do lado do oriente, e colocou nele o homem que havia criado.^&#42;1^

[[v1-2-9]]

^<<v1-2-9,9>>^ O Senhor Deus fez brotar da terra toda a sorte de árvores de aspecto agradável, e de frutos bons para comer; e a árvore da vida no meio do jardim, e a árvore da ciência do bem e do mal.

[[v1-2-10]]

^<<v1-2-10,10>>^ Um rio saía do Éden para regar o jardim, e dividia-se em seguida em quatro braços.

[[v1-2-11]]

^<<v1-2-11,11>>^ O nome do primeiro é Fison, e é aquele que contorna toda a região de Hévila, onde se encontra o ouro.

[[v1-2-12]]

^<<v1-2-12,12>>^ (O ouro dessa região é puro; encontra-se ali também o bdélio e a pedra de ônix.)

[[v1-2-13]]

^<<v1-2-13,13>>^ O nome do segundo rio é Geon, e é aquele que contorna toda a região de Cuch.

[[v1-2-14]]

^<<v1-2-14,14>>^ O nome do terceiro rio é Tigre, que corre ao oriente da Assíria. O quarto rio é o Eufrates.

[[v1-2-15]]

^<<v1-2-15,15>>^ O Senhor Deus tomou o homem e o colocou no jardim do Éden, para cultivar o solo e o guardar.

[[v1-2-16]]

^<<v1-2-16,16>>^ Deu-lhe este preceito: “Podes comer do fruto de todas as árvores do jardim;

[[v1-2-17]]

^<<v1-2-17,17>>^ mas não comas do fruto da árvore da ciência do bem e do mal; porque no dia em que dele comeres, morrerás indubitavelmente”.

[[v1-2-18]]

^<<v1-2-18,18>>^ O Senhor Deus disse: “Não é bom que o homem esteja só. Vou dar-lhe uma auxiliar que lhe seja adequada”.

[[v1-2-19]]

^<<v1-2-19,19>>^ Tendo, pois, o Senhor Deus formado da terra todos os animais dos campos, e todas as aves do céu, levou-os ao homem, para ver como ele os havia de chamar; e todo o nome que o homem pôs aos animais vivos, esse é o seu verdadeiro nome.

[[v1-2-20]]

^<<v1-2-20,20>>^ O homem pôs nomes a todos os animais, a todas as aves do céu e a todos os animais do campo; mas não se achava para ele uma auxiliar que lhe fosse adequada.

[[v1-2-21]]

^<<v1-2-21,21>>^ Então, o Senhor Deus mandou ao homem um profundo sono; e enquanto ele dormia, tomou-lhe uma costela e fechou com carne o seu lugar.

[[v1-2-22]]

^<<v1-2-22,22>>^ E da costela que tinha tomado do homem, o Senhor Deus fez uma mulher, e levou-a para junto do homem.^&#42;1^

[[v1-2-23]]

^<<v1-2-23,23>>^ “Eis agora aqui – disse o homem – o osso de meus ossos e a carne de minha carne; ela se chamará mulher, porque foi tomada do homem.”^&#42;1^

[[v1-2-24]]

^<<v1-2-24,24>>^ Por isso, o homem deixa o seu pai e a sua mãe para se unir à sua mulher; e já não são mais que uma só carne.^&#42;1^

[[v1-2-25]]

^<<v1-2-25,25>>^ O homem e a mulher estavam nus, e não se envergonhavam.

'''

xref:001-genesis/001-genesis-001.adoc#v1-1-0[&#60; Capítulo Anterior] | <<v1-2-0,Topo>> | xref:001-genesis/001-genesis-003.adoc#v1-3-0[Próximo Capítulo &#62;]