include::./index.adoc[]

[[v1-29-0]]
=== Gênesis, 29
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 29 relata a chegada de Jacó à terra de Padã-Arã, onde encontra sua parentela e conhece Raquel, por quem se apaixona. Ele então trabalha por sete anos para casar-se com ela, mas é enganado por Labão, que lhe dá Lia em vez de Raquel. Jacó então trabalha por mais sete anos para casar-se com Raquel.
* Provérbios 5:18-19: "Seja bendito o teu manancial, e alegra-te com a mulher da tua mocidade. Como cerva amorosa, e gazela graciosa, os seus seios te saciem em todo o tempo; e pelo seu amor sejas atraído perpetuamente." Jacó amou Raquel à primeira vista e trabalhou sete anos para tê-la como esposa.
* Gênesis 29:20: "Assim, pois, serviu Jacó por Raquel sete anos; e estes lhe pareceram como poucos dias, pelo muito que a amava." Jacó trabalhou por sete anos por amor a Raquel e o tempo passou rapidamente para ele.
* Eclesiastes 4:9: "Melhor é serem dois do que um, porque têm melhor paga do seu trabalho." Jacó trabalhou por sete anos por Raquel, e mais sete anos por Lia e por amor a elas.
* Provérbios 20:14: "Mau, mau, diz o comprador, mas, depois de se ir, então se gaba." Jacó trabalhou sete anos para ter Raquel como esposa, mas foi enganado por Labão, que lhe deu Lia em vez dela.
* 1 Coríntios 13:4-7: "O amor é sofredor, é benigno; o amor não é invejoso; o amor não se vangloria, não se ensoberbece, não se porta inconvenientemente, não busca os seus próprios interesses, não se irrita, não suspeita mal; não se regozija com a injustiça, mas se regozija com a verdade." Jacó amava tanto Raquel que trabalhou por ela por 14 anos, suportando as dificuldades e o engano de Labão.
****

[[v1-29-1]]

^<<v1-29-1,1>>^ Jacó pôs-se de novo a caminho e foi para a terra dos filhos do oriente.

[[v1-29-2]]

^<<v1-29-2,2>>^ Olhando em torno de si, viu no campo um poço junto do qual estavam deitados três rebanhos de ovelhas. Esse poço servia de bebedouro para os rebanhos. Mas, sendo grande a pedra que cobria a abertura do poço

[[v1-29-3]]

^<<v1-29-3,3>>^ somente a removiam de cima quando todos os rebanhos fossem recolhidos. Davam então de beber aos animais e recolocavam a pedra no seu devido lugar.

[[v1-29-4]]

^<<v1-29-4,4>>^ Jacó disse aos pastores: “Meus irmãos, de onde sois?”. “Somos de Harã” – responderam.

[[v1-29-5]]

^<<v1-29-5,5>>^ “Conheceis porventura Labão, filho de Nacor?”. “Sim.”

[[v1-29-6]]

^<<v1-29-6,6>>^ “Como vai ele?”. “Vai muito bem; e eis justamente sua filha Raquel que vem com o rebanho.”

[[v1-29-7]]

^<<v1-29-7,7>>^ “É ainda pleno dia – tornou Jacó – e não é hora de se recolherem os rebanhos. Dai de beber às ovelhas e levai-as de novo ao pasto.”

[[v1-29-8]]

^<<v1-29-8,8>>^ “Não o podemos – responderam eles – antes que todos os rebanhos estejam reunidos. Tiramos então a pedra de cima do poço e damos de beber aos animais.”

[[v1-29-9]]

^<<v1-29-9,9>>^ Falava ainda com eles, quando chegou Raquel com o rebanho do seu pai, porque era pastora.

[[v1-29-10]]

^<<v1-29-10,10>>^ Logo que Jacó viu Raquel, filha de Labão, irmão de sua mãe, aproximou-se, rolou a pedra de cima da boca do poço e deu de beber às ovelhas de Labão.

[[v1-29-11]]

^<<v1-29-11,11>>^ Depois beijou Raquel e pôs-se a chorar.

[[v1-29-12]]

^<<v1-29-12,12>>^ Contou-lhe que era parente de seu pai e filho de Rebeca; e ela correu a anunciar isso ao seu pai.

[[v1-29-13]]

^<<v1-29-13,13>>^ Tendo Labão ouvido falar de Jacó, filho de sua irmã, correu-lhe ao encontro, abraçou-o, beijou-o e o conduziu à sua casa. Jacó contou-lhe tudo o que se tinha passado,

[[v1-29-14]]

^<<v1-29-14,14>>^ e Labão disse-lhe: “Sim, tu és de meus ossos e de minha carne”. Jacó ficou em casa dele um mês inteiro.

[[v1-29-15]]

^<<v1-29-15,15>>^ E Labão disse-lhe: “Acaso, porque és meu parente, me servirás de graça? Dize-me que salário queres”.

[[v1-29-16]]

^<<v1-29-16,16>>^ Ora, Labão tinha duas filhas: a mais velha chamava-se Lia, e a mais nova Raquel.

[[v1-29-17]]

^<<v1-29-17,17>>^ Lia tinha os olhos ternos, e Raquel era bela de corpo e de rosto.

[[v1-29-18]]

^<<v1-29-18,18>>^ Jacó, que amava Raquel, disse a Labão: “Eu te servirei sete anos por Raquel, tua filha mais nova”.

[[v1-29-19]]

^<<v1-29-19,19>>^ “É melhor – respondeu Labão – dá-la a ti que a outro: fica comigo.”

[[v1-29-20]]

^<<v1-29-20,20>>^ Assim, Jacó serviu por Raquel sete anos, que lhe pareceram dias, tão grande era o amor que lhe tinha.

[[v1-29-21]]

^<<v1-29-21,21>>^ Disse, pois, a Labão: “Dá-me minha mulher, porque está completo o meu tempo e quero desposá-la”.

[[v1-29-22]]

^<<v1-29-22,22>>^ Labão reuniu todos os habitantes do lugar e deu um banquete.

[[v1-29-23]]

^<<v1-29-23,23>>^ Mas, à noite, conduziu Lia a Jacó, que se uniu com ela.

[[v1-29-24]]

^<<v1-29-24,24>>^ E deu à sua filha Lia, sua escrava Zelfa.

[[v1-29-25]]

^<<v1-29-25,25>>^ Pela manhã, viu Jacó que tinha ficado com Lia. E disse a Labão: “Que me fizeste? Não foi por Raquel que te servi? Por que me enganaste?”.

[[v1-29-26]]

^<<v1-29-26,26>>^ “Aqui – respondeu Labão – não é costume casar a mais nova antes da mais velha.

[[v1-29-27]]

^<<v1-29-27,27>>^ Acaba a semana com esta, e depois te darei também sua irmã, na condição que me sirvas ainda sete anos.”

[[v1-29-28]]

^<<v1-29-28,28>>^ Assim fez Jacó: acabou a semana com Lia, e depois lhe deu Labão por mulher sua filha Raquel,

[[v1-29-29]]

^<<v1-29-29,29>>^ dando por serva a Raquel sua escrava Bala.

[[v1-29-30]]

^<<v1-29-30,30>>^ Jacó uniu-se também a Raquel, a quem amou mais do que a Lia. E serviu ainda por sete anos em casa de Labão.

[[v1-29-31]]

^<<v1-29-31,31>>^ O Senhor, vendo que Lia era desprezada, tornou-a fecunda, enquanto Raquel permanecia estéril.^&#42;1^

[[v1-29-32]]

^<<v1-29-32,32>>^ Lia concebeu e deu à luz um filho, ao qual chamou Rúben, “porque – dizia ela – o Senhor olhou minha aflição; agora meu marido me amará”.^&#42;1^

[[v1-29-33]]

^<<v1-29-33,33>>^ Concebeu de novo e deu à luz outro filho. “O Senhor – disse ela – vendo que era desprezada, deu-me ainda este.” E pôs-lhe o nome de Simeão.

[[v1-29-34]]

^<<v1-29-34,34>>^ Concebeu ainda e deu à luz mais um filho. “Desta vez – disse ela – meu marido se apegará a mim, porque já lhe dei à luz três filhos.” Por isso, deu-lhe o nome de Levi.

[[v1-29-35]]

^<<v1-29-35,35>>^ Concebeu ainda e deu à luz um filho. E disse: “Desta vez, louvarei ao Senhor”. E chamou-o Judá. Depois cessou de ter filhos.

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]