include::./index.adoc[]

[[v1-45-0]]
=== Gênesis, 45
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 45 conta a história de José, que finalmente revela sua verdadeira identidade aos seus irmãos que o venderam como escravo muitos anos antes. Ele os perdoa e convida toda a sua família para viver com ele no Egito durante a fome que assolava a região. Os cinco versículos abaixo foram selecionados por sua relevância com os temas abordados neste capítulo.
* Gênesis 41:52: "Ao segundo chamou Efraim, porque disse: Deus me fez frutificar na terra da minha aflição." José nomeia seu filho mais novo, Efraim, como uma lembrança da bênção de Deus mesmo em meio à sua aflição no Egito.
* Êxodo 1:7: "E os filhos de Israel frutificaram, e aumentaram muito, e multiplicaram-se, e foram fortalecidos grandemente; de maneira que a terra se encheu deles." A promessa de Deus para Abraão, Isaque e Jacó de que sua descendência seria numerosa começa a se cumprir enquanto a família de José se estabelece no Egito.
* Levítico 19:18: "Não te vingarás, nem guardarás ira contra os filhos do teu povo; mas amarás o teu próximo como a ti mesmo. Eu sou o Senhor." A atitude de perdão de José em relação a seus irmãos é um exemplo vivo do mandamento de amar o próximo e não buscar vingança.
* Deuteronômio 30:3: "Então o Senhor teu Deus te fará voltar do teu cativeiro, e se compadecerá de ti, e tornará a ajuntar-te dentre todas as nações entre as quais te espalhou o Senhor teu Deus." A história de José e sua família sendo reunidos no Egito é um exemplo da fidelidade de Deus em cumprir suas promessas e reunir seu povo de volta para sua terra.
* Josué 24:15: "Porém, se vos parece mal aos vossos olhos servir ao Senhor, escolhei hoje a quem sirvais; se aos deuses a quem serviram vossos pais, que estavam dalém do rio, ou aos deuses dos amorreus, em cuja terra habitais; porém eu e a minha casa serviremos ao Senhor." A decisão de José de servir a Deus e agir com amor e perdão em vez de vingança é um exemplo para nós de como devemos viver nossas vidas e tratar os outros.
****

[[v1-45-1]]

^<<v1-45-1,1>>^ Então José, já não se podendo conter diante de todos os assistentes, exclamou: “Fazei sair todo o mundo”. Desse modo, ninguém ficou com ele, quando se deu a conhecer aos seus irmãos.

[[v1-45-2]]

^<<v1-45-2,2>>^ Pôs-se a chorar tão alto que os egípcios da casa do faraó o ouviram.

[[v1-45-3]]

^<<v1-45-3,3>>^ E disse aos seus irmãos: “Eu sou José! Meu pai vive ainda?” Mas não lhe puderam responder, porque estavam pasmados de se encontrarem diante dele.

[[v1-45-4]]

^<<v1-45-4,4>>^ “Aproximai-vos” – disse-lhes ele –; e eles aproximaram-se. E ele disse-lhes: “Eu sou José, vosso irmão, que vendestes para o Egito.

[[v1-45-5]]

^<<v1-45-5,5>>^ Mas agora não vos entristeçais, nem tenhais remorsos de me terdes vendido para ser conduzido aqui. É para vos conservar a vida que Deus me enviou adiante de vós.

[[v1-45-6]]

^<<v1-45-6,6>>^ Porque eis já dois anos que a fome assola a terra, e haverá ainda cinco anos sem semeadura nem colheita.

[[v1-45-7]]

^<<v1-45-7,7>>^ Deus enviou-me adiante de vós para que subsista um resto de vossa raça na terra, e para vos conservar a vida por uma grande libertação.

[[v1-45-8]]

^<<v1-45-8,8>>^ Não sois vós, pois, que me haveis mandado para aqui, mas Deus mesmo. Ele tornou-me como o pai do faraó, chefe de toda a sua casa e governador de todo o Egito.

[[v1-45-9]]

^<<v1-45-9,9>>^ Apressai-vos em voltar para junto de meu pai e dizei-lhe: ‘Eis o que diz o teu filho José: Deus elevou-me ao cargo de chefe de todo o Egito. Vem para junto de mim sem demora.

[[v1-45-10]]

^<<v1-45-10,10>>^ Habitarás na terra de Gessen, bem perto de mim, com teus filhos, teus netos, tuas ovelhas, teus bois e tudo o que te pertence.

[[v1-45-11]]

^<<v1-45-11,11>>^ Eu te sustentarei, pois haverá ainda cinco anos de fome; e assim não cairás na miséria, nem tu, nem tua casa, nem nada do que te pertence’.

[[v1-45-12]]

^<<v1-45-12,12>>^ Vereis com vossos olhos, e meu irmão Benjamim também, que sou bem eu quem vos fala.

[[v1-45-13]]

^<<v1-45-13,13>>^ Contai ao meu pai as honras que recebo no Egito, e tudo o que vistes, e depois apressai-o para que venha para cá”.

[[v1-45-14]]

^<<v1-45-14,14>>^ Então ele jogou-se ao pescoço de seu irmão Benjamim e pôs-se a chorar; Benjamim também chorou sobre os seus ombros.

[[v1-45-15]]

^<<v1-45-15,15>>^ Beijou em seguida todos os seus irmãos, enquanto os abraçava. Depois os irmãos conversaram com ele.

[[v1-45-16]]

^<<v1-45-16,16>>^ A notícia da chegada dos irmãos de José espalhou-se logo na casa do faraó, e foi bem acolhida pelo faraó e por todo o seu pessoal.

[[v1-45-17]]

^<<v1-45-17,17>>^ Ele disse a José: “Dize a teus irmãos: ‘Eis o que ides fazer: carregai vossos animais e voltai à terra de Canaã.

[[v1-45-18]]

^<<v1-45-18,18>>^ Tomai vosso pai e vossas famílias e vinde para junto de mim. Daremos a vós o que há de melhor no Egito e vos alimentarei com a gordura da terra’.

[[v1-45-19]]

^<<v1-45-19,19>>^ Encarrego-te de dizer-lhes: Eis o que ides fazer: Tomai carros no Egito para vossos filhos e vossas mulheres, trazei vosso pai e vinde!

[[v1-45-20]]

^<<v1-45-20,20>>^ Não façais caso do que tereis de deixar, porque o que há de melhor em todo o Egito é vosso”.

[[v1-45-21]]

^<<v1-45-21,21>>^ Assim fizeram os filhos de Israel. Seguindo a ordem do faraó, José deu-lhes carros e provisões para o caminho.

[[v1-45-22]]

^<<v1-45-22,22>>^ Deu-lhes também a todos mudas de roupas; a Benjamim, porém, deu trezentas moedas de prata e cinco mudas de roupas.

[[v1-45-23]]

^<<v1-45-23,23>>^ Mandou, igualmente, ao seu pai dez jumentos carregados dos melhores produtos do Egito e dez jumentas carregadas de trigo, pão e provisões para sua viagem.

[[v1-45-24]]

^<<v1-45-24,24>>^ E, despedindo seus irmãos que partiam, disse-lhes: “Não vos deixeis abalar pelo caminho”.^&#42;1^

[[v1-45-25]]

^<<v1-45-25,25>>^ Partiram do Egito e chegaram junto de Jacó, seu pai, na terra de Canaã.

[[v1-45-26]]

^<<v1-45-26,26>>^ E anunciaram-lhe a boa-nova: “José vive ainda – disseram-lhe eles –; e é mesmo ele quem governa todo o Egito”. Mas o coração de Jacó permaneceu frio, porque não acreditava no que ouvia.

[[v1-45-27]]

^<<v1-45-27,27>>^ Entretanto, quando lhe disseram todas as palavras que José lhes havia dito, e viu os carros que José tinha enviado para o transportar, seu espírito se reanimou.

[[v1-45-28]]

^<<v1-45-28,28>>^ “Basta! – disse ele –; José, meu filho, vive ainda. Irei e o verei antes de morrer.”

'''

xref:001-genesis/001-genesis-044.adoc#v1-44-0[&#60; Capítulo Anterior] | <<v1-45-0,Topo>> | xref:001-genesis/001-genesis-046.adoc#v1-46-0[Próximo Capítulo &#62;]