include::./index.adoc[]

[[v1-47-0]]
=== Gênesis, 47
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 47 narra a continuação da história de José e como ele ajudou o Faraó a salvar o Egito da fome, por meio da administração da venda de grãos. José também ajuda sua família a estabelecer-se no Egito, fornecendo-lhes terra e alimento. Os cinco versículos abaixo foram selecionados por sua relevância com os temas abordados neste capítulo.
* Provérbios 13:11: "A fazenda que procede da vaidade diminuirá, mas quem a ajunta pelo trabalho terá aumento." O exemplo de José no capítulo 47 de trabalhar duro e administrar com sabedoria a venda de grãos para salvar o Egito da fome é uma ilustração de como o trabalho árduo e a sabedoria podem resultar em prosperidade.
* Salmo 111:5: "Deu mantimento aos que o temem; lembrar-se-á sempre da sua aliança." A ajuda de José para sua família é um exemplo da fidelidade de Deus em cumprir suas promessas de proteção e bênção para a descendência de Abraão.
* Eclesiastes 3:1: "Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu." O momento em que José foi levado para o Egito, sua ascensão ao poder e a oportunidade de salvar o Egito da fome são exemplos de como Deus pode usar os tempos e circunstâncias para cumprir seus propósitos.
* 1 Timóteo 5:8: "Mas, se alguém não tem cuidado dos seus, e principalmente dos da sua família, negou a fé, e é pior do que o infiel." José cuidou de sua família, fornecendo-lhes terra e alimento, mesmo depois de terem sido vendidos como escravos e sofrido muitas dificuldades.
* Filipenses 4:19: "O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades em glória, por Cristo Jesus." A provisão de alimento e terra para a família de Jacó é um exemplo da fidelidade de Deus em suprir todas as nossas necessidades.
****

[[v1-47-1]]

^<<v1-47-1,1>>^ José foi, pois, informar o faraó: “Meu pai – disse ele – e meus irmãos chegaram da terra de Canaã com suas ovelhas, seus bois e tudo o que lhes pertence. Eles estão na terra de Gessen”.

[[v1-47-2]]

^<<v1-47-2,2>>^ José levara cinco de seus irmãos, que apresentou ao faraó.

[[v1-47-3]]

^<<v1-47-3,3>>^ Este disse-lhes: “Qual é vossa profissão?”. Responderam: “Teus servos são pastores, como sempre o foram nossos pais.

[[v1-47-4]]

^<<v1-47-4,4>>^ Viemos – ajuntaram eles – para morar no país porque não há mais pastagem para os rebanhos de teus servos, sendo muito grande a fome na terra de Canaã. Permite, pois, aos teus servos habitarem na terra de Gessen”.

[[v1-47-5]]

^<<v1-47-5,5>>^ O faraó disse a José: “Teu pai e teus irmãos vieram para junto de ti; a terra do Egito está à tua disposição: instala-os na melhor parte do país.

[[v1-47-6]]

^<<v1-47-6,6>>^ Que eles habitem na terra de Gessen; e, se conheces entre eles alguns que sejam capazes, os porás à frente dos rebanhos que me pertencem”.

[[v1-47-7]]

^<<v1-47-7,7>>^ José fez então vir Jacó, seu pai, e o apresentou ao faraó.

[[v1-47-8]]

^<<v1-47-8,8>>^ Jacó abençoou o faraó. Este disse-lhe: “Que idade tens?”.

[[v1-47-9]]

^<<v1-47-9,9>>^ Jacó respondeu-lhe: “O número dos anos de minha peregrinação é de cento e trinta anos. Curtos e maus foram os anos de minha vida, e não atingiriam o número dos que viveram meus pais durante sua peregrinação”.

[[v1-47-10]]

^<<v1-47-10,10>>^ E, depois de ter abençoado o faraó, Jacó despediu-se dele.

[[v1-47-11]]

^<<v1-47-11,11>>^ José instalou seu pai e seus irmãos em uma propriedade do país do Egito, na melhor parte da região, a terra de Ramsés, como o tinha ordenado o faraó.

[[v1-47-12]]

^<<v1-47-12,12>>^ E José forneceu víveres a seu pai, a seus irmãos e a toda sua família, proporcionalmente ao número dos filhos.

[[v1-47-13]]

^<<v1-47-13,13>>^ E faltou pão em toda a terra, porque a fome era tão violenta que a terra do Egito e a terra de Canaã estavam esgotadas.

[[v1-47-14]]

^<<v1-47-14,14>>^ José tinha ajuntado todo o dinheiro que se encontrava no Egito e em Canaã, como preço do trigo que compravam, e o tinha depositado no tesouro do faraó.

[[v1-47-15]]

^<<v1-47-15,15>>^ Quando havia acabado todo o dinheiro do Egito e de Canaã, todos os egípcios vieram dizer a José: “Dá-nos pão. Por que morreremos na tua presença por falta de dinheiro?”.

[[v1-47-16]]

^<<v1-47-16,16>>^ José respondeu: “Trazei vossos animais, se não tendes dinheiro, e vos darei pão em troca”.

[[v1-47-17]]

^<<v1-47-17,17>>^ Trouxeram, pois, seus animais a José, o qual lhes deu pão em troca dos cavalos, dos rebanhos de ovelhas, dos bois e dos jumentos. Dessa forma, naquele ano, fornecera-lhes pão em troca de todos os seus rebanhos.

[[v1-47-18]]

^<<v1-47-18,18>>^ E aquele ano passou. No ano seguinte, voltaram a ele e disseram-lhe: “Não podemos ocultar do meu senhor que o dinheiro, tendo-se esgotado, e nossos animais, tendo já passado para as mãos de meu senhor, não nos restam agora senão nossos corpos e nossas terras para oferecer ao meu senhor.

[[v1-47-19]]

^<<v1-47-19,19>>^ Por que perecermos diante de teus olhos, nós e nossas terras? Compra-nos a nós e a nossas terras em troca de pão, e nós e nossas terras seremos escravos do faraó. Dá-nos sementes, para que vivamos e não morramos, e não seja desolado o nosso solo”.

[[v1-47-20]]

^<<v1-47-20,20>>^ José adquiriu, assim, para o faraó, todas as terras do Egito, porque cada egípcio vendia o seu campo, obrigado pela fome; e o país tornou-se propriedade do faraó.

[[v1-47-21]]

^<<v1-47-21,21>>^ De um extremo a outro do território, ele reduziu a população à servidão.

[[v1-47-22]]

^<<v1-47-22,22>>^ As terras dos sacerdotes foram as únicas que não comprou, porque estes recebiam do faraó uma ração determinada para o seu sustento. Por isso, não venderam suas propriedades.

[[v1-47-23]]

^<<v1-47-23,23>>^ José disse ao povo: “Eu vos comprei hoje, vós e vossas terras, para o faraó. Aqui tendes sementes: semeai vossos campos.

[[v1-47-24]]

^<<v1-47-24,24>>^ No tempo da colheita, dareis a quinta parte ao faraó: as outras quatro partes vos servirão para semente do campo e para vosso alimento com vossos filhos e os que moram convosco”.

[[v1-47-25]]

^<<v1-47-25,25>>^ Eles responderam: “Tu nos salvaste a vida. Tenhamos graça aos olhos de meu senhor e seremos de bom grado escravos do faraó”.

[[v1-47-26]]

^<<v1-47-26,26>>^ José instituiu assim uma lei que ainda hoje está em vigor, em virtude da qual uma quinta parte da colheita pertence ao faraó. Somente as terras dos sacerdotes não se tornaram sua propriedade.

[[v1-47-27]]

^<<v1-47-27,27>>^ Israel estabeleceu-se, pois, no Egito, na terra de Gessen. Adquiriram ali propriedades, foram fecundos e multiplicaram-se grandemente.

[[v1-47-28]]

^<<v1-47-28,28>>^ Jacó viveu ainda dezessete anos no Egito. A duração de sua vida foi de cento e quarenta e sete anos.

[[v1-47-29]]

^<<v1-47-29,29>>^ E, aproximando-se do seu termo os dias de Israel, chamou o seu filho José e disse-lhe: “Se achei graça diante de teus olhos, põe, rogo-te, tua mão debaixo de minha coxa e promete-me, com toda a bondade e fidelidade, que não me enterrarás no Egito.

[[v1-47-30]]

^<<v1-47-30,30>>^ Quando eu me tiver deitado com meus pais, me levarás para fora do Egito e me enterrarás junto deles em seu túmulo”. José respondeu: “Farei como dizes”. “Jura-me” – replicou Jacó.

[[v1-47-31]]

^<<v1-47-31,31>>^ José jurou-lhe e Israel prostrou-se sobre a cabeceira de sua cama.^&#42;1^

'''

xref:001-genesis/001-genesis-046.adoc#v1-46-0[&#60; Capítulo Anterior] | <<v1-47-0,Topo>> | xref:001-genesis/001-genesis-048.adoc#v1-48-0[Próximo Capítulo &#62;]