include::./index.adoc[]

[[v1-12-0]]
=== Gênesis, 12
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 12 narra a história de como Deus chamou Abrão para sair de sua terra natal e ir para uma terra que Ele lhe mostraria. Abrão obedeceu a Deus e, como resultado, Deus prometeu abençoá-lo e fazer dele uma grande nação. Além disso, Deus prometeu abençoar aqueles que abençoassem Abrão e amaldiçoar aqueles que o amaldiçoassem. Aqui estão cinco versículos relacionados com os temas abordados em Gênesis 12:
* Gênesis 15:6: "Abrão creu no Senhor, e isso lhe foi creditado como justiça." Este versículo fala da fé de Abrão em Deus e como essa fé lhe foi creditada como justiça. Essa fé é uma parte fundamental da história de Abrão, que deixou sua terra natal e seguiu as ordens de Deus.
* Gênesis 17:1-2: "Quando Abrão tinha noventa e nove anos, o Senhor apareceu-lhe e disse: Eu sou o Deus todo-poderoso; anda na minha presença e sê íntegro. Estabelecerei a minha aliança contigo e multiplicar-te-ei extraordinariamente". Neste versículo, Deus reafirma a aliança que fez com Abrão, prometendo abençoá-lo e fazer dele uma grande nação.
* Êxodo 23:22: "Se escutares com atenção a sua voz e fizeres tudo o que eu disser, serei inimigo dos teus inimigos e adversário dos teus adversários." Este versículo fala da promessa de Deus de proteger Abrão e seus descendentes, e de lutar em favor deles contra seus inimigos.
* Deuteronômio 1:8: "Veja, eu lhe dei esta terra. Entre e tome posse da terra que o Senhor jurou dar aos seus antepassados, Abraão, Isaque e Jacó, e aos seus descendentes depois deles." Este versículo fala da promessa de Deus a Abrão de uma terra que Ele mostraria a ele, e como essa promessa foi cumprida quando seus descendentes entraram na Terra Prometida.
* Hebreus 11:8: "Pela fé Abraão, quando chamado, obedeceu e saiu para um lugar que ia receber como herança. Ele saiu, sem saber para onde ia." Este versículo fala da fé de Abrão em Deus e de como ele obedeceu às ordens de Deus, mesmo sem saber para onde estava indo. Essa fé é uma das principais características de Abrão em toda a Bíblia.
****

[[v1-12-1]]

^<<v1-12-1,1>>^ O Senhor disse a Abrão: “Deixa tua terra, tua família e a casa de teu pai e vai para a terra que eu te mostrar.^&#42;1^

[[v1-12-2]]

^<<v1-12-2,2>>^ Farei de ti uma grande nação; eu te abençoarei e exaltarei o teu nome, e tu serás uma fonte de bênçãos.

[[v1-12-3]]

^<<v1-12-3,3>>^ Abençoarei aqueles que te abençoarem, e amaldiçoarei aqueles que te amaldiçoarem; todas as famílias da terra serão benditas em ti”.^&#42;1^

[[v1-12-4]]

^<<v1-12-4,4>>^ Abrão partiu como o Senhor lhe tinha dito, e Ló foi com ele. Abrão tinha setenta e cinco anos, quando partiu de Harã.

[[v1-12-5]]

^<<v1-12-5,5>>^ Tomou Sarai, sua mulher, e Ló, filho de seu irmão, assim como todos os bens que possuíam e os escravos que tinham adquirido em Harã, e partiram para a terra de Canaã. Ali chegando,

[[v1-12-6]]

^<<v1-12-6,6>>^ Abrão atravessou a terra até Siquém, até o carvalho de Moré. Os cananeus estavam então naquela terra.

[[v1-12-7]]

^<<v1-12-7,7>>^ O Senhor apareceu a Abrão e disse-lhe: “Darei esta terra à tua posteridade”. Abrão edificou um altar ao Senhor, que lhe tinha aparecido.

[[v1-12-8]]

^<<v1-12-8,8>>^ Em seguida, partindo dali, foi para a montanha que está ao oriente de Betel, onde levantou a sua tenda, tendo Betel ao ocidente e Hai ao oriente. Abrão edificou ali um altar ao Senhor, e invocou o seu nome.

[[v1-12-9]]

^<<v1-12-9,9>>^ Continuou depois sua viagem, de acampamento em acampamento, para Negueb.

[[v1-12-10]]

^<<v1-12-10,10>>^ Sobreveio, porém, uma fome na região; e sendo grande a miséria, Abrão desceu ao Egito para aí viver algum tempo.

[[v1-12-11]]

^<<v1-12-11,11>>^ Quando estava para entrar no Egito, disse a Sarai, sua mulher: “Escuta, sei que és uma mulher formosa.

[[v1-12-12]]

^<<v1-12-12,12>>^ Quando os egípcios te virem, dirão: ‘É sua mulher’, e me matarão, conservando-te a ti em vida.

[[v1-12-13]]

^<<v1-12-13,13>>^ Dize, pois, que és minha irmã, para que eu seja poupado por causa de ti, e me conservem a vida em atenção a ti”.

[[v1-12-14]]

^<<v1-12-14,14>>^ Chegando Abrão ao Egito, os egípcios notaram que sua mulher era extremamente bela.

[[v1-12-15]]

^<<v1-12-15,15>>^ Os grandes da corte, vendo-a, elogiaram-na diante do faraó, e a mulher foi introduzida no seu palácio.

[[v1-12-16]]

^<<v1-12-16,16>>^ Por causa dela, Abrão foi bem tratado pelo faraó, e recebeu ovelhas, bois, jumentos, servos e servas, jumentas e camelos.

[[v1-12-17]]

^<<v1-12-17,17>>^ O Senhor, porém, feriu com grandes pragas o faraó e a sua casa, por causa de Sarai, mulher de Abrão.

[[v1-12-18]]

^<<v1-12-18,18>>^ O faraó mandou chamá-lo e disse-lhe: “Que me levaste a fazer? Por que não me disseste que era tua mulher?

[[v1-12-19]]

^<<v1-12-19,19>>^ Por que disseste que ela era tua irmã, levando-me a tomá-la por esposa? Mas agora, eis tua mulher: toma-a e vai-te!”.

[[v1-12-20]]

^<<v1-12-20,20>>^ Então, o faraó deu ordens aos seus para reconduzir Abrão e sua mulher com tudo o que lhe pertencia.

'''

xref:001-genesis/001-genesis-011.adoc#v1-11-0[&#60; Capítulo Anterior] | <<v1-12-0,Topo>> | xref:001-genesis/001-genesis-013.adoc#v1-13-0[Próximo Capítulo &#62;]