include::./index.adoc[]

[[v1-23-0]]
=== Gênesis, 23
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 23 narra a morte de Sara e a busca de Abraão por um lugar para enterrá-la. Ele pede aos filhos de Hete uma caverna para usá-la como sepultura, e acaba comprando a Caverna de Macpela, onde ele enterra Sara. A história mostra a importância que Abraão dava ao enterro e à honra aos mortos, bem como o respeito aos costumes locais.
* Salmos 116:15: "Preciosa é à vista do SENHOR a morte dos seus santos." Este versículo enfatiza a importância que Deus dá aos seus servos, mesmo após a morte, e pode ser relacionado à maneira como Abraão cuidou do enterro de Sara.
* Eclesiastes 7:2: "Melhor é ir à casa onde há luto do que ir à casa onde há banquete, porque naquela está o fim de todos os homens, e os vivos o aplicam ao seu coração." Esse versículo enfatiza a importância de se lembrar da morte e do valor da vida. Abraão estava claramente ciente desse valor e buscou um lugar adequado para o enterro de Sara.
* Filipenses 3:20: "Mas a nossa cidade está nos céus, donde também esperamos o Salvador, o Senhor Jesus Cristo." Este versículo enfatiza a ideia de que a nossa verdadeira casa não é na terra, mas nos céus. No entanto, assim como Abraão, é importante respeitar as tradições locais e dar a devida honra aos mortos enquanto estamos na terra.
* Hebreus 11:13: "Todos estes morreram na fé, sem terem recebido as promessas; mas vendo-as de longe, e crendo nelas, e abraçando-as, confessaram que eram estrangeiros e peregrinos na terra." Este versículo destaca que os servos de Deus são como estrangeiros nesta terra, apenas de passagem, e nos lembra que devemos tratar a terra com respeito e honrar os costumes locais, mesmo enquanto nos preparamos para nossa verdadeira pátria.
* Apocalipse 14:13: "E ouvi uma voz do céu, que me dizia: Escreve: Bem-aventurados os mortos que desde agora morrem no Senhor. Sim, diz o Espírito, para que descansem dos seus trabalhos, e as suas obras os sigam." Este versículo enfatiza que os mortos que morrem no Senhor serão abençoados e terão descanso. Abraão queria ter certeza de que Sara tivesse um lugar apropriado para descansar em paz.
****

[[v1-23-1]]

^<<v1-23-1,1>>^ Sara viveu cento e vinte e sete anos: essa foi a duração de sua vida.

[[v1-23-2]]

^<<v1-23-2,2>>^ Ela morreu em Cariat-Arbe, hoje Hebron, na terra de Canaã. Abraão veio para prantear e chorar por ela.

[[v1-23-3]]

^<<v1-23-3,3>>^ Abraão, tendo-se retirado de junto da falecida, falou aos filhos de Het, dizendo:

[[v1-23-4]]

^<<v1-23-4,4>>^ “Sou no meio de vós um simples hóspede e estrangeiro; concedei-me, não obstante, a propriedade de uma sepultura na vossa terra, para que eu possa sepultar minha esposa que morreu”.

[[v1-23-5]]

^<<v1-23-5,5>>^ Os filhos de Het responderam a Abraão:

[[v1-23-6]]

^<<v1-23-6,6>>^ “Ouve-nos, meu Senhor! Tu és um príncipe de Deus no meio de nós. Sepulta tua falecida no mais belo de nossos sepulcros. Ninguém de nós te recusará o seu túmulo para aí sepultar tua defunta”.

[[v1-23-7]]

^<<v1-23-7,7>>^ Então Abraão levantou-se e, prostrando-se diante do povo daquela terra, os filhos de Het,

[[v1-23-8]]

^<<v1-23-8,8>>^ disse-lhes: “Se me permitis trazer minha defunta e enterrá-la, ouvi-me: Intercedei por mim junto de Efron, filho de Seor,

[[v1-23-9]]

^<<v1-23-9,9>>^ para que ele me ceda a caverna de Macpela que lhe pertence, e que se encontra na extremidade de sua terra. Que ele me ceda em vossa presença, por seu justo valor, a fim de que eu me torne o proprietário dessa sepultura”.

[[v1-23-10]]

^<<v1-23-10,10>>^ Ora, Efron achava-se assentado no meio dos filhos de Het. Efron, o hiteu, respondeu a Abraão em presença dos filhos de Het e de todos os que entravam pela porta da cidade:

[[v1-23-11]]

^<<v1-23-11,11>>^ “De forma alguma, meu Senhor, será assim, mas ouve-me: dou-te a terra, juntamente com a caverna que nela se encontra; e dou-te essa terra em presença dos filhos do meu povo: enterra tua defunta”.

[[v1-23-12]]

^<<v1-23-12,12>>^ Abraão prostrou-se diante do povo daquela terra

[[v1-23-13]]

^<<v1-23-13,13>>^ e, dirigindo-se a Efron, diante de todos, disse: “Rogo-te que me ouças: eu te dou o preço do campo; aceita-o de minhas mãos, e assim enterrarei nele minha defunta”.

[[v1-23-14]]

^<<v1-23-14,14>>^ Efron respondeu a Abraão:

[[v1-23-15]]

^<<v1-23-15,15>>^ “Ouve-me, meu Senhor: uma terra no valor de quatrocentos siclos de prata, entre ti e mim, o que é isto? Sepulta tua defunta”.

[[v1-23-16]]

^<<v1-23-16,16>>^ Abraão aceitou as condições de Efron, e pesou o dinheiro que ele tinha pedido na presença dos filhos de Het, isto é, quatrocentos siclos de prata em moeda corrente no comércio.

[[v1-23-17]]

^<<v1-23-17,17>>^ A terra de Efron, situada em Macpela, defronte de Mambré, a terra na qual se encontra a caverna, e todas as árvores que crescem ao redor nos limites desta terra,

[[v1-23-18]]

^<<v1-23-18,18>>^ tornaram-se assim propriedade de Abraão, em presença dos filhos de Het e de todos aqueles que entravam pela porta da cidade.

[[v1-23-19]]

^<<v1-23-19,19>>^ E Abraão sepultou Sara, sua mulher, na caverna de Macpela, defronte de Mambré, hoje Hebron, na terra de Canaã.

[[v1-23-20]]

^<<v1-23-20,20>>^ A terra e a caverna que nela se encontra passaram, pois, dos filhos de Het para propriedade de Abraão, a título de lugar de sepultura.

'''

xref:001-genesis/001-genesis-022.adoc#v1-22-0[&#60; Capítulo Anterior] | <<v1-23-0,Topo>> | xref:001-genesis/001-genesis-024.adoc#v1-24-0[Próximo Capítulo &#62;]