include::./index.adoc[]

[[v1-19-0]]
=== Gênesis, 19
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 19 narra a destruição de Sodoma e Gomorra, duas cidades ímpias que foram julgadas por Deus. O capítulo aborda temas como o pecado, a justiça divina, a misericórdia de Deus e a importância de obedecer aos seus mandamentos. Abaixo estão cinco versículos relacionados com esses temas, em ordem de proximidade com o capítulo:
* Romanos 3:23: "pois todos pecaram e estão destituídos da glória de Deus." Este versículo destaca a natureza pecaminosa da humanidade, que é evidenciada em Gênesis 19 pela perversidade dos habitantes de Sodoma e Gomorra.
* Salmos 89:14: "A justiça e o direito são os alicerces do teu trono; o amor e a fidelidade vão à tua frente." Este versículo destaca a justiça divina, que é demonstrada em Gênesis 19 quando Deus julga Sodoma e Gomorra por causa de sua impiedade.
* 2 Pedro 3:9: "O Senhor não demora em cumprir a sua promessa, como julgam alguns. Ao contrário, ele é paciente com vocês, não querendo que ninguém pereça, mas que todos cheguem ao arrependimento." Este versículo destaca a misericórdia de Deus, que é evidenciada em Gênesis 19 quando Deus permite que Ló e sua família escapem antes da destruição das cidades.
* Êxodo 20:3: "Não terás outros deuses além de mim." Este versículo destaca a importância de obedecer aos mandamentos de Deus, o que é enfatizado em Gênesis 19 quando a esposa de Ló olha para trás durante sua fuga e é transformada em uma estátua de sal como punição por sua desobediência.
* João 3:16: "Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo o que nele crer não pereça, mas tenha a vida eterna." Este versículo destaca o amor de Deus pela humanidade, que é evidenciado em Gênesis 19 quando Deus salva Ló e sua família da destruição das cidades.
****

[[v1-19-1]]

^<<v1-19-1,1>>^ Pela tarde chegaram os dois anjos a Sodoma. Ló, que estava assentado à porta da cidade, ao vê-los, levantou-se e foi-lhes ao encontro e prostrou-se com o rosto por terra.^&#42;1^

[[v1-19-2]]

^<<v1-19-2,2>>^ “Meus senhores – disse-lhes ele – vinde, peço-vos, para a casa de vosso servo, e passai nela a noite; lavareis os pés, e amanhã cedo continuareis vosso caminho.” “Não – responderam eles – passaremos a noite na praça.”

[[v1-19-3]]

^<<v1-19-3,3>>^ Mas Ló insistiu tanto com eles que concordaram e entraram em sua casa. Ló preparou-lhes um banquete, mandou cozer pães sem fermento e eles comeram.

[[v1-19-4]]

^<<v1-19-4,4>>^ Mas, antes que se tivessem deitado, eis que os homens da cidade, os homens de Sodoma, se agruparam em torno da casa, desde os jovens até os velhos, toda a população.

[[v1-19-5]]

^<<v1-19-5,5>>^ E chamaram Ló: “Onde estão – disseram-lhe – os homens que entraram esta noite em tua casa? Conduze-os a nós para que os conheçamos”.

[[v1-19-6]]

^<<v1-19-6,6>>^ Saiu Ló a ter com eles no limiar da casa, fechou a porta atrás de si

[[v1-19-7]]

^<<v1-19-7,7>>^ e disse-lhes: “Suplico-vos, meus irmãos, não cometais este crime.

[[v1-19-8]]

^<<v1-19-8,8>>^ Ouvi: tenho duas filhas que são ainda virgens, eu vo-las trarei, e fazei delas o que quiserdes. Mas não façais nada a estes homens, porque se acolheram à sombra de meu teto”.

[[v1-19-9]]

^<<v1-19-9,9>>^ Eles responderam: “Retira-te daí! – e acrescentaram: Eis um indivíduo que não passa de um estrangeiro no meio de nós e se arvora em juiz! Pois bem, verás como te havemos de tratar pior do que a eles”. E, empurrando Ló com violência, avançaram para quebrar a porta.

[[v1-19-10]]

^<<v1-19-10,10>>^ Mas os dois (viajantes) estenderam a mão e, tomando Ló para dentro de casa, fecharam de novo a porta.

[[v1-19-11]]

^<<v1-19-11,11>>^ E feriram de cegueira os homens que estavam fora, jovens e velhos, que se esforçavam em vão por reencontrar a porta.

[[v1-19-12]]

^<<v1-19-12,12>>^ Os dois homens disseram a Ló: “Tens ainda aqui alguns dos teus? Genros, ou filhos, ou filhas, todos os que são teus parentes na cidade, faze-os sair deste lugar,

[[v1-19-13]]

^<<v1-19-13,13>>^ porque vamos destruir este lugar, visto que o clamor que se eleva dos seus habitantes é enorme diante do Senhor, o qual nos enviou para exterminá-los”.

[[v1-19-14]]

^<<v1-19-14,14>>^ Saiu Ló, pois, para falar a seus genros, que tinham desposado suas filhas: “Levantai-vos – disse-lhes – saí daqui, porque o Senhor vai destruir a cidade”. Mas seus genros julgaram que ele gracejava.

[[v1-19-15]]

^<<v1-19-15,15>>^ Ao amanhecer, os anjos instavam com Ló, dizendo: “Levanta-te, toma tua mulher e tuas duas filhas que estão em tua casa, para que não pereças também no castigo da cidade”.

[[v1-19-16]]

^<<v1-19-16,16>>^ E, como ele demorasse, aqueles homens tomaram pela mão a ele, a sua mulher e as suas duas filhas, porque o Senhor queria salvá-los, e o levaram para fora da cidade.

[[v1-19-17]]

^<<v1-19-17,17>>^ Quando já estavam fora, um dos anjos disse-lhe: “Salva-te, se queres conservar a tua vida. Não olhes para trás, e não te detenhas em parte alguma da planície; mas foge para a montanha senão perecerás”.

[[v1-19-18]]

^<<v1-19-18,18>>^ Ló disse-lhes: “Oh, não, Senhor!

[[v1-19-19]]

^<<v1-19-19,19>>^ Já que vosso servo encontrou graça diante de vós, e usastes comigo de grande bondade, conservando-me a vida, vede, eu não posso me salvar na montanha, porque o flagelo me atingiria antes, e eu morreria.

[[v1-19-20]]

^<<v1-19-20,20>>^ Eis uma cidade bem perto onde posso abrigar-me. É uma cidade pequena e eu poderei refugiar-me nela. Permiti que o faça – ela é pequena – e terei a vida salva”.

[[v1-19-21]]

^<<v1-19-21,21>>^ Ele disse-lhe: “Concedo-te ainda esta graça: não destruirei a cidade a favor da qual me pedes.

[[v1-19-22]]

^<<v1-19-22,22>>^ Apressa-te e refugia-te lá porque nada posso fazer antes que lá tenhas chegado”. Por isso, puseram àquela cidade o nome de Segor.^&#42;1^

[[v1-19-23]]

^<<v1-19-23,23>>^ O sol levantava-se sobre a terra quando Ló entrou em Segor.

[[v1-19-24]]

^<<v1-19-24,24>>^ O Senhor fez então cair sobre Sodoma e Gomorra uma chuva de enxofre e de fogo, vinda do Senhor, do céu.

[[v1-19-25]]

^<<v1-19-25,25>>^ E destruiu essas cidades e toda a planície, assim como todos os habitantes das cidades e a vegetação do solo.

[[v1-19-26]]

^<<v1-19-26,26>>^ A mulher de Ló, tendo olhado para trás, transformou-se numa estátua de sal.

[[v1-19-27]]

^<<v1-19-27,27>>^ Abraão levantou-se muito cedo e foi ao lugar onde tinha estado antes com o Senhor.

[[v1-19-28]]

^<<v1-19-28,28>>^ Voltando os olhos para o lado de Sodoma e Gomorra e sobre toda a extensão da planície, viu subir da terra um fumo espesso como a fumaça de uma grande fornalha.

[[v1-19-29]]

^<<v1-19-29,29>>^ Quando Deus destruiu as cidades da planície, lembrou-se de Abraão e livrou Ló do flagelo com que destruiu as cidades onde ele habitava.

[[v1-19-30]]

^<<v1-19-30,30>>^ Ló partiu de Segor e veio estabelecer-se na montanha com suas duas filhas, pois temia ficar em Segor. E habitava numa caverna com suas duas filhas.

[[v1-19-31]]

^<<v1-19-31,31>>^ A mais velha disse à mais nova: “Nosso pai está velho, e não há homem algum na região com quem nos possamos unir, segundo o costume universal.

[[v1-19-32]]

^<<v1-19-32,32>>^ Vem, embriaguemos nosso pai e durmamos com ele, para que possamos nos assegurar uma posteridade”.

[[v1-19-33]]

^<<v1-19-33,33>>^ Elas fizeram, pois, o seu pai beber vinho naquela noite. Então, a mais velha entrou e dormiu com ele; ele, porém, nada notou, nem quando ela se aproximou dele, nem quando se levantou.

[[v1-19-34]]

^<<v1-19-34,34>>^ No dia seguinte, disse ela à sua irmã mais nova: “Dormi ontem com meu pai, façamo-lo beber vinho ainda uma vez, esta noite, e dormirás com ele para nos assegurarmos uma posteridade”.

[[v1-19-35]]

^<<v1-19-35,35>>^ Também naquela noite embriagaram seu pai, e a mais nova dormiu com ele, sem que ele o percebesse, nem quando ela se aproximou, nem quando se levantou.

[[v1-19-36]]

^<<v1-19-36,36>>^ Assim, as duas filhas de Ló conceberam de seu pai.

[[v1-19-37]]

^<<v1-19-37,37>>^ A mais velha deu à luz um filho, ao qual pôs o nome de Moab: este é o pai dos moabitas, que vivem ainda hoje.^&#42;1^

[[v1-19-38]]

^<<v1-19-38,38>>^ A mais nova teve também um filho, ao qual chamou Ben-Ami: este é o pai dos amonitas, que vivem ainda hoje.^&#42;1^

'''

xref:001-genesis/001-genesis-018.adoc#v1-18-0[&#60; Capítulo Anterior] | <<v1-19-0,Topo>> | xref:001-genesis/001-genesis-020.adoc#v1-20-0[Próximo Capítulo &#62;]