include::./index.adoc[]

[[v1-46-0]]
=== Gênesis, 46
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 46 relata a jornada de Jacó e sua família para o Egito, onde José os aguarda para salvá-los da fome que assolava a terra. Jacó oferece sacrifícios a Deus em Beer-Sheba antes de partir e, ao chegar no Egito, ele é apresentado a Faraó. Os cinco versículos abaixo foram selecionados por sua relevância com os temas abordados neste capítulo.
* Gênesis 28:13-15: "E eis que o Senhor estava em cima dela, e disse: Eu sou o Senhor Deus de Abraão teu pai, e o Deus de Isaque; esta terra em que estás deitado, darei a ti e à tua descendência. E a tua descendência será como o pó da terra, e estender-se-á ao ocidente, e ao oriente, e ao norte, e ao sul; e em ti e na tua descendência serão benditas todas as famílias da terra. E eis que estou contigo, e te guardarei por onde quer que fores, e te farei tornar a esta terra; porque não te deixarei, até que haja cumprido aquilo de que te tenho falado." A jornada de Jacó e sua família para o Egito é um exemplo da fidelidade de Deus em cumprir suas promessas de proteção e bênção para a descendência de Abraão.
* Êxodo 1:7: "E os filhos de Israel frutificaram, e aumentaram muito, e multiplicaram-se, e foram fortalecidos grandemente; de maneira que a terra se encheu deles." O cumprimento da promessa de Deus de que a descendência de Abraão seria numerosa começa a ser visto quando Jacó e sua família chegam ao Egito.
* Êxodo 20:12: "Honra a teu pai e a tua mãe, para que se prolonguem os teus dias na terra que o Senhor teu Deus te dá." Jacó honrou seu pai e avô antes dele, e agora ele e sua família estão sendo abençoados pela fidelidade de Deus a essas promessas.
* Êxodo 23:25: "E servireis ao Senhor vosso Deus, e ele abençoará o vosso pão e a vossa água; e eu tirarei do meio de ti as enfermidades." A bênção de Deus sobre Jacó e sua família é evidente no fato de que eles encontraram um lugar para viver no Egito durante a fome e foram recebidos pelo Faraó.
* Josué 24:15: "Porém, se vos parece mal aos vossos olhos servir ao Senhor, escolhei hoje a quem sirvais; se aos deuses a quem serviram vossos pais, que estavam dalém do rio, ou aos deuses dos amorreus, em cuja terra habitais; porém eu e a minha casa serviremos ao Senhor." A decisão de Jacó e sua família de confiar em Deus e seguir seus planos é um exemplo para nós de como devemos confiar em Deus em todas as circunstâncias da vida.
****

[[v1-46-1]]

^<<v1-46-1,1>>^ Israel partiu com tudo o que lhe pertencia. Chegou a Bersabeia, onde ofereceu sacrifícios ao Deus de seu pai Isaac.

[[v1-46-2]]

^<<v1-46-2,2>>^ Em uma visão noturna, Deus disse-lhe: “Jacó! Jacó!”. “Eis-me aqui” – respondeu ele.

[[v1-46-3]]

^<<v1-46-3,3>>^ E Deus disse: “Eu sou Deus, o Deus de teu pai. Não temas descer ao Egito, porque ali farei de ti uma grande nação.

[[v1-46-4]]

^<<v1-46-4,4>>^ Descerei contigo ao Egito, e eu mesmo te farei de novo subir de lá. José te fechará os olhos”.

[[v1-46-5]]

^<<v1-46-5,5>>^ E Jacó deixou Bersabeia. Os filhos de Israel levaram seu pai, assim como seus filhos e suas mulheres, nos carros que o faraó tinha enviado para os transportar.

[[v1-46-6]]

^<<v1-46-6,6>>^ Tomaram também seus rebanhos e os bens que tinham adquirido na terra de Canaã,

[[v1-46-7]]

^<<v1-46-7,7>>^ e Jacó, com toda a sua família, partiu para o Egito. Levou os seus filhos e seus netos, suas filhas e suas netas, enfim, toda a sua família.

[[v1-46-8]]

^<<v1-46-8,8>>^ Eis os nomes dos filhos de Israel que foram para o Egito: Jacó e seus filhos.

[[v1-46-9]]

^<<v1-46-9,9>>^ O primogênito de Jacó: Rúben. Os filhos de Rúben: Henoc, Falu, Hesron e Carmi.

[[v1-46-10]]

^<<v1-46-10,10>>^ Os filhos de Simeão: Jamuel, Jamin, Aod, Jaquin, Soar e Saul, filho da cananeia.

[[v1-46-11]]

^<<v1-46-11,11>>^ Os filhos de Levi: Gérson, Caat e Merari.

[[v1-46-12]]

^<<v1-46-12,12>>^ Os filhos de Judá: Her, Onã, Sela, Farés e Zara. Her e Onã, porém, morreram em Canaã. Os filhos de Farés: Hesron e Hamul.

[[v1-46-13]]

^<<v1-46-13,13>>^ Os filhos de Issacar: Tola, Fua, Jasub e Semron.

[[v1-46-14]]

^<<v1-46-14,14>>^ Os filhos de Zabulon: Sared, Elon e Jaelel.

[[v1-46-15]]

^<<v1-46-15,15>>^ São estes os filhos que Lia deu a Jacó em Padã-Aram, assim como sua filha Dina. Total de seus filhos e filhas: trinta e três pessoas.

[[v1-46-16]]

^<<v1-46-16,16>>^ Os filhos de Gad: Safon, Hagi, Suni, Esebon, Eri, Arodi e Areli.

[[v1-46-17]]

^<<v1-46-17,17>>^ Os filhos de Aser: Jamne, Jesua, Jessui e Beria, assim como sua irmã Sara. Os filhos de Beria: Héber e Melquiel.

[[v1-46-18]]

^<<v1-46-18,18>>^ São estes os filhos que Zelfa, dada por Labão à sua filha Lia, deu à luz a Jacó: dezesseis pessoas.

[[v1-46-19]]

^<<v1-46-19,19>>^ Filhos de Raquel, mulher de Jacó: José e Benjamim.

[[v1-46-20]]

^<<v1-46-20,20>>^ No Egito, José tivera de Asenet, filha de Putifar, sacerdote de On, Manassés e Efraim.

[[v1-46-21]]

^<<v1-46-21,21>>^ Os filhos de Benjamim: Bela, Bocor, Asbel, Gera, Naamã, Equi, Ros, Mofim, Ofim e Ared.

[[v1-46-22]]

^<<v1-46-22,22>>^ São estes os filhos que Raquel deu a Jacó. Total: catorze pessoas.

[[v1-46-23]]

^<<v1-46-23,23>>^ Filho de Dã: Husim.

[[v1-46-24]]

^<<v1-46-24,24>>^ Filhos de Neftali: Jasiee, Guni, Jeser e Salém.

[[v1-46-25]]

^<<v1-46-25,25>>^ São estes os filhos que Bala, dada por Labão à sua filha Raquel, deu à luz a Jacó. Total: sete pessoas.

[[v1-46-26]]

^<<v1-46-26,26>>^ O total das pessoas saídas de Jacó, que vieram com ele para o Egito, sem contar as mulheres de seus filhos, era de setenta ao todo.

[[v1-46-27]]

^<<v1-46-27,27>>^ José teve dois filhos nascidos no Egito. O total das pessoas da família de Jacó que foram para o Egito era de setenta.

[[v1-46-28]]

^<<v1-46-28,28>>^ Jacó tinha enviado Judá adiante dele para informar a José de sua chegada a Gessen. Quando chegaram a Gessen,

[[v1-46-29]]

^<<v1-46-29,29>>^ José mandou preparar o seu carro e montou para ir ao encontro de seu pai em Gessen. E, logo que o viu, lançou-se nos seus braços e chorou longo tempo.

[[v1-46-30]]

^<<v1-46-30,30>>^ “Agora posso morrer – disse-lhe Israel – porque vi o teu rosto, e vives ainda!”

[[v1-46-31]]

^<<v1-46-31,31>>^ José disse aos seus irmãos: “Vou avisar o faraó, dizendo: ‘Meus irmãos e a família de meu pai, que estavam em Canaã, vieram para junto de mim;

[[v1-46-32]]

^<<v1-46-32,32>>^ os homens são pastores, criadores de animais, e trouxeram suas ovelhas e seus bois com tudo o que lhes pertence’.

[[v1-46-33]]

^<<v1-46-33,33>>^ Quando o faraó mandar chamar-vos e vos perguntar qual é vossa profissão,

[[v1-46-34]]

^<<v1-46-34,34>>^ lhes respondereis: ‘Teus servos foram sempre criadores de animais, desde sua juventude até o presente, e nossos pais também’. Desse modo podereis ficar na terra de Gessen, porque os egípcios têm aversão aos pastores”.

'''

xref:001-genesis/001-genesis-045.adoc#v1-45-0[&#60; Capítulo Anterior] | <<v1-46-0,Topo>> | xref:001-genesis/001-genesis-047.adoc#v1-47-0[Próximo Capítulo &#62;]