include::./index.adoc[]

[[v1-39-0]]
=== Gênesis, 39
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Gênesis 39 narra a história de José no Egito, onde ele é vendido como escravo por seus irmãos e se torna servo de Potifar, um oficial egípcio. No capítulo, José é injustamente acusado pela esposa de Potifar de tentar seduzi-la e é lançado na prisão. Apesar de tudo, Deus está com José e o abençoa, permitindo que ele se torne um administrador respeitado na prisão. Aqui estão cinco versículos relacionados aos temas do capítulo:
* Salmos 105:17-18: "Ele enviou um homem diante deles, José, vendido como escravo. Machucaram seus pés com grilhões e o lançaram em ferros" Este versículo relembra o momento em que José foi vendido como escravo por seus próprios irmãos, mostrando a crueldade e injustiça que ele sofreu.
* Provérbios 6:32: "O adúltero não tem juízo; destrói a si mesmo, acabando com a própria vida." A falsa acusação de Potifar contra José é um exemplo de tentação adúltera. Este versículo ressalta a gravidade do pecado e suas consequências.
* Isaías 41:10: "Não temas, pois estou contigo; não te assombres, porque sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Mesmo nas situações mais difíceis, como a prisão injusta de José, Deus permanece ao nosso lado. Este versículo enfatiza a importância da fé em Deus durante as provações.
* 2 Timóteo 2:22: "Fuja das paixões da mocidade e siga a justiça, a fé, o amor e a paz, juntamente com os que, de coração puro, invocam o Senhor." José resistiu à tentação da esposa de Potifar, fugindo da situação. Este versículo nos encoraja a resistir às tentações e seguir um caminho de justiça e santidade.
* Filipenses 4:13: "Tudo posso naquele que me fortalece." Mesmo nas piores circunstâncias, como a prisão injusta de José, Deus nos dá força e nos capacita a superar nossos desafios. Este versículo nos lembra que podemos enfrentar qualquer coisa com a ajuda de Deus.
****

[[v1-39-1]]

^<<v1-39-1,1>>^ José foi conduzido ao Egito, e Putifar, um oficial egípcio do faraó, chefe da guarda, comprou-o aos ismaelitas que o levavam.

[[v1-39-2]]

^<<v1-39-2,2>>^ O Senhor estava com José, e tudo lhe prosperava. Morava na casa do seu senhor, o egípcio.

[[v1-39-3]]

^<<v1-39-3,3>>^ Seu senhor viu que o Senhor estava com ele e lhe fazia prosperar tudo o que empreendia.

[[v1-39-4]]

^<<v1-39-4,4>>^ José conquistou a simpatia do seu senhor, que o empregou a seu serviço, pondo-o à testa de sua casa e confiando-lhe todos os seus bens.

[[v1-39-5]]

^<<v1-39-5,5>>^ Desde o momento em que José tomou o governo de sua casa e de todos os seus bens, o Senhor abençoou a casa do egípcio, por causa de José: a bênção do Senhor desceu sobre tudo o que lhe pertencia, na casa como nos campos.

[[v1-39-6]]

^<<v1-39-6,6>>^ Ele entregou todos os seus negócios a José, sem mais se preocupar de coisa alguma, exceto do que se alimentava. Ora, José era belo de corpo e de rosto.

[[v1-39-7]]

^<<v1-39-7,7>>^ E aconteceu, depois de tudo isso, que a mulher de seu senhor lançou seus olhos em José e disse-lhe: “Dorme comigo”.

[[v1-39-8]]

^<<v1-39-8,8>>^ Mas ele recusou: “Meu senhor – disse-lhe ele – não me pede conta alguma do que se faz na casa, e confiou-me todos os seus bens.

[[v1-39-9]]

^<<v1-39-9,9>>^ Não há maior do que eu nesta casa; ele nada me interdisse, exceto tu, que és sua mulher. Como poderia eu cometer um tão grande crime e pecar contra Deus?”.

[[v1-39-10]]

^<<v1-39-10,10>>^ Em vão se esforçava ela todos os dias, falando a José; ele não consentia em dormir com ela e unir-se a ela.

[[v1-39-11]]

^<<v1-39-11,11>>^ Certo dia, tendo ele entrado na casa para fazer seus serviços, e não se encontrando ali ninguém da casa,

[[v1-39-12]]

^<<v1-39-12,12>>^ ela segurou-o pelo manto, dizendo: “Dorme comigo!”. Mas José, largando-lhe o manto nas mãos, fugiu.

[[v1-39-13]]

^<<v1-39-13,13>>^ Vendo a mulher que ele lhe tinha deixado o manto nas mãos e fugido,

[[v1-39-14]]

^<<v1-39-14,14>>^ chamou a gente de sua casa e disse-lhes: “Vede: trouxeram-nos este hebreu para a casa a fim de que ele abuse de nós. Este homem veio-me procurar para dormir comigo, mas eu gritei.

[[v1-39-15]]

^<<v1-39-15,15>>^ E vendo que eu me punha a gritar, deixou seu manto ao meu lado e fugiu”.

[[v1-39-16]]

^<<v1-39-16,16>>^ E guardou junto de si as vestes de José até a volta de seu senhor.

[[v1-39-17]]

^<<v1-39-17,17>>^ E fez-lhe a mesma narrativa: “O escravo hebreu – disse ela – que nos trouxeste, veio à minha procura para abusar de mim.

[[v1-39-18]]

^<<v1-39-18,18>>^ Mas, pondo-me a gritar, deixou o seu manto ao meu lado e fugiu”.

[[v1-39-19]]

^<<v1-39-19,19>>^ Ao ouvir isso de sua mulher, contando-lhe como se tinha comportado com ela o seu servo, ele enfureceu-se,

[[v1-39-20]]

^<<v1-39-20,20>>^ e lançou José na prisão, onde se encontravam detidos os prisioneiros do rei. E José foi encarcerado.

[[v1-39-21]]

^<<v1-39-21,21>>^ O Senhor estava com ele. Mostrou-lhe sua bondade e fez que ele conquistasse a simpatia do chefe da prisão.

[[v1-39-22]]

^<<v1-39-22,22>>^ Este confiou a José todos os presos que ali se encontravam, e nada se fazia sem sua ordem.

[[v1-39-23]]

^<<v1-39-23,23>>^ O chefe da prisão não fiscalizava nada do que fazia José, porque o Senhor estava com ele e fazia-lhe prosperar tudo o que empreendia.

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]