include::./index.adoc[]

[[v51-16-0]]
=== Atos dos Apóstolos, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 16 de Atos dos Apóstolos relata a jornada missionária de Paulo e Silas na região da Macedônia. Eles pregam o evangelho em Filipos, onde enfrentam oposição e são presos, mas um terremoto liberta-os e eles levam o carcereiro e sua família a crer em Jesus. Depois, eles viajam para Tessalônica, onde mais uma vez enfrentam perseguição, e depois para Bereia, onde são bem recebidos. Aqui estão cinco versículos relacionados com os temas abordados em Atos 16:
* Filipenses 1:6: "Estou plenamente certo de que aquele que começou boa obra em vocês vai completá-la até o dia de Cristo Jesus." Esse versículo destaca a ideia de perseverança e confiança na obra de Deus, mesmo em meio a dificuldades, o que é evidenciado na experiência de Paulo e Silas em Filipos.
* 1 Tessalonicenses 2:2: "Ao contrário do que sabem, depois de termos sofrido e sido ultrajados em Filipos, como sabem, tivemos a coragem em nosso Deus de lhes falar o evangelho de Deus em meio a grande oposição." Neste versículo, Paulo relembra sua experiência em Filipos e como mesmo diante da oposição, eles continuaram a pregar o evangelho.
* Filipenses 4:6-7: "Não fiquem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus. E a paz de Deus, que excede todo o entendimento, guardará o coração e a mente de vocês em Cristo Jesus." Esse versículo pode ser aplicado à experiência de Paulo e Silas em Filipos, onde apesar de estarem na prisão, eles se entregaram à oração e ação de graças, experimentando a paz de Deus em meio à adversidade.
* Atos 16:31: "Eles responderam: ‘Creia no Senhor Jesus, e serão salvos, você e os de sua casa.’" Esse versículo contém a mensagem central do evangelho que Paulo e Silas pregavam em suas viagens missionárias, incluindo sua passagem por Filipos e Tessalônica.
* 1 Tessalonicenses 1:6: "Recebestes a palavra com alegria do Espírito Santo, apesar de muita tribulação." Esse versículo destaca a alegria que os novos convertidos em Tessalônica experimentaram, apesar da perseguição e tribulação que enfrentavam, algo que Paulo e Silas certamente compartilhavam.
****

[[v51-16-1]]

^<<v51-16-1,1>>^ Chegou a Derbe e depois a Listra. Havia ali um discípulo, chamado Timóteo, filho de uma judia cristã, mas de pai grego,

[[v51-16-2]]

^<<v51-16-2,2>>^ que gozava de ótima reputação junto dos irmãos de Listra e de Icônio.

[[v51-16-3]]

^<<v51-16-3,3>>^ Paulo quis que ele fosse em sua companhia. Ao tomá-lo consigo, circuncidou-o, por causa dos judeus daqueles lugares, pois todos sabiam que o seu pai era grego.

[[v51-16-4]]

^<<v51-16-4,4>>^ Nas cidades pelas quais passavam, ensinavam que observassem as decisões que haviam sido tomadas pelos apóstolos e anciãos em Jerusalém.

[[v51-16-5]]

^<<v51-16-5,5>>^ Assim as igrejas eram confirmadas na fé, e cresciam em número dia a dia.

[[v51-16-6]]

^<<v51-16-6,6>>^ Atravessando em seguida a Frígia e a província da Galácia, foram impedidos pelo Espírito Santo de anunciar a Palavra de Deus na (província da) Ásia.

[[v51-16-7]]

^<<v51-16-7,7>>^ Ao chegarem aos confins da Mísia, tencionavam seguir para a Bitínia, mas o Espírito de Jesus não o permitiu.

[[v51-16-8]]

^<<v51-16-8,8>>^ Depois de haverem atravessado rapidamente a Mísia, desceram a Trôade.

[[v51-16-9]]

^<<v51-16-9,9>>^ De noite, Paulo teve uma visão: um macedônio, em pé, diante dele, lhe rogava: “Passa à Macedônia, e vem em nosso auxílio!”.

[[v51-16-10]]

^<<v51-16-10,10>>^ Assim que teve essa visão, procuramos partir para a Macedônia, certos de que Deus nos chamava a pregar-lhes o Evangelho.^&#42;1^

[[v51-16-11]]

^<<v51-16-11,11>>^ Embarcados em Trôade, fomos diretamente à Samotrácia e no outro dia a Neápolis;

[[v51-16-12]]

^<<v51-16-12,12>>^ e dali a Filipos, que é a cidade principal daquele distrito da Macedônia, uma colônia romana. Nessa cidade nos detivemos por alguns dias.

[[v51-16-13]]

^<<v51-16-13,13>>^ No sábado, saímos fora da porta para junto do rio, onde pensávamos haver lugar de oração. Aí nos assentamos e falávamos às mulheres que se haviam reunido.^&#42;1^

[[v51-16-14]]

^<<v51-16-14,14>>^ Uma mulher, chamada Lídia, da cidade dos tiatirenos, vendedora de púrpura, temente a Deus, nos escutava. O Senhor abriu-lhe o coração, para atender às coisas que Paulo dizia.

[[v51-16-15]]

^<<v51-16-15,15>>^ Foi batizada juntamente com a sua família e fez-nos este pedido: “Se julgais que tenho fé no Senhor, entrai em minha casa e ficai comigo”. E obrigou-nos a isso.

[[v51-16-16]]

^<<v51-16-16,16>>^ Certo dia, quando íamos à oração, eis que nos veio ao encontro uma moça escrava que tinha o espírito de Pitão, a qual com as suas adivinhações dava muito lucro a seus senhores.^&#42;1^

[[v51-16-17]]

^<<v51-16-17,17>>^ Pondo-se a seguir a Paulo e a nós, gritava: “Estes homens são servos do Deus Altíssimo, que vos anunciam o caminho da salvação”.

[[v51-16-18]]

^<<v51-16-18,18>>^ Repetiu isto por muitos dias. Por fim, Paulo enfadou-se. Voltou-se para ela e disse ao espírito: “Ordeno-te em nome de Jesus Cristo que saias dela”. E na mesma hora ele saiu.

[[v51-16-19]]

^<<v51-16-19,19>>^ Vendo seus amos que se lhes esvaecera a esperança do lucro, pegaram Paulo e Silas e levaram-nos ao foro, à presença das autoridades.

[[v51-16-20]]

^<<v51-16-20,20>>^ Em seguida, apresentaram-nos aos magistrados, acusando: “Estes homens são judeus; amotinam a nossa cidade

[[v51-16-21]]

^<<v51-16-21,21>>^ e pregam um modo de vida que nós, romanos, não podemos admitir nem seguir”.

[[v51-16-22]]

^<<v51-16-22,22>>^ O povo insurgiu-se contra eles. Os magistrados mandaram arrancar-lhes as vestes para açoitá-los com varas.

[[v51-16-23]]

^<<v51-16-23,23>>^ Depois de lhes terem feito muitas chagas, meteram-nos na prisão, mandando ao carcereiro que os guardasse com segurança.

[[v51-16-24]]

^<<v51-16-24,24>>^ Este, conforme a ordem recebida, meteu-os na prisão inferior e prendeu-lhes os pés ao cepo.

[[v51-16-25]]

^<<v51-16-25,25>>^ Pela meia-noite, Paulo e Silas rezavam e cantavam um hino a Deus, e os prisioneiros os escutavam.

[[v51-16-26]]

^<<v51-16-26,26>>^ Subitamente, sentiu-se um terremoto tão grande que se abalaram até os fundamentos do cárcere. Abriram-se logo todas as portas e soltaram-se as algemas de todos.

[[v51-16-27]]

^<<v51-16-27,27>>^ Acordou o carcereiro e, vendo abertas as portas do cárcere, supôs que os presos haviam fugido. Tirou da espada e queria matar-se.

[[v51-16-28]]

^<<v51-16-28,28>>^ Mas Paulo bradou em alta voz: “Não te faças nenhum mal, pois estamos todos aqui”.

[[v51-16-29]]

^<<v51-16-29,29>>^ Então, o carcereiro pediu luz, entrou e lançou-se trêmulo aos pés de Paulo e Silas.

[[v51-16-30]]

^<<v51-16-30,30>>^ Depois os conduziu para fora e perguntou-lhes: “Senhores, que devo fazer para me salvar?”.

[[v51-16-31]]

^<<v51-16-31,31>>^ Disseram-lhe: “Crê no Senhor Jesus e serás salvo, tu e tua família”.

[[v51-16-32]]

^<<v51-16-32,32>>^ Anunciaram-lhe a Palavra de Deus, a ele e a todos os que estavam em sua casa.

[[v51-16-33]]

^<<v51-16-33,33>>^ Então, naquela mesma hora da noite, ele cuidou deles e lavou-lhes as chagas. Imediatamente foi batizado, ele e toda a sua família.

[[v51-16-34]]

^<<v51-16-34,34>>^ Em seguida, ele os fez subir para sua casa, pôs-lhes a mesa e alegrou-se com toda a sua casa por haver crido em Deus.

[[v51-16-35]]

^<<v51-16-35,35>>^ Quando amanheceu, os magistrados mandaram os lictores dizerem: “Solta esses homens”.

[[v51-16-36]]

^<<v51-16-36,36>>^ O carcereiro transmitiu essa mensagem a Paulo: “Os magistrados mandaram-me dizer que vos ponha em liberdade. Saí, pois, e ide em paz”.

[[v51-16-37]]

^<<v51-16-37,37>>^ Mas Paulo replicou: “Sem nenhum julgamento nos açoitaram publicamente, a nós que somos cidadãos romanos, e meteram-nos no cárcere, e agora nos lançam fora ocultamente... Não há de ser assim! Mas venham e soltem-nos pessoalmente!”.

[[v51-16-38]]

^<<v51-16-38,38>>^ Os lictores deram parte dessas palavras aos magistrados. Estes temeram, ao ouvir dizer que eram romanos.

[[v51-16-39]]

^<<v51-16-39,39>>^ Foram e lhes falaram brandamente. Pedindo desculpas, rogavam-lhes que se retirassem da cidade.

[[v51-16-40]]

^<<v51-16-40,40>>^ Saindo do cárcere, entraram em casa de Lídia, onde reviram e consolaram os irmãos. Depois partiram.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-015.adoc#v51-15-0[&#60; Capítulo Anterior] | <<v51-16-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-017.adoc#v51-17-0[Próximo Capítulo &#62;]