include::./index.adoc[]

[[v51-9-0]]
=== Atos dos Apóstolos, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em Atos dos Apóstolos 9 é narrada a conversão de Saulo de Tarso, que se tornaria o apóstolo Paulo. No capítulo, é descrito como Saulo, que era conhecido por perseguir os cristãos, teve um encontro com Jesus no caminho de Damasco e, a partir daí, passou a pregar o evangelho. Os versículos relacionados com os temas abordados em Atos 9 são:
* Romanos 8:28: "E sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus, daqueles que são chamados segundo o Seu propósito." Este versículo pode ser relacionado à conversão de Saulo, que era um perseguidor dos cristãos, mas que acabou se tornando um grande apóstolo e propagador da mensagem de Jesus.
* Efésios 2:8-9: "Porque pela graça sois salvos, mediante a fé; e isto não vem de vós, é dom de Deus; não de obras, para que ninguém se glorie." A conversão de Saulo é um exemplo claro da graça de Deus, que o escolheu e o transformou, independentemente das suas próprias obras.
* Gálatas 2:20: "Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo na carne, vivo-a pela fé no Filho de Deus, o qual me amou e se entregou a Si mesmo por mim." Este versículo pode ser relacionado à transformação que ocorreu na vida de Saulo, que deixou para trás a sua vida anterior e passou a viver pela fé em Jesus.
* Filipenses 3:7-8: "Mas o que para mim era lucro, isto considerei perda por causa de Cristo. Sim, na verdade, considero tudo como perda, por causa da sublimidade do conhecimento de Cristo Jesus, meu Senhor; por amor do qual perdi todas as coisas e as considero como refugo, para ganhar a Cristo." A história de Saulo mostra claramente como ele abandonou sua posição privilegiada na sociedade judaica e considerou tudo como perda por causa de Cristo.
* Colossenses 1:24: "Agora me regozijo no meio dos meus sofrimentos por vós e cumpro na minha carne o que resta das aflições de Cristo, por causa do seu corpo, que é a igreja." Paulo foi um apóstolo que sofreu muito em sua vida, mas que nunca deixou de se alegrar no Senhor e de se dedicar à propagação do evangelho.
****

[[v51-9-1]]

^<<v51-9-1,1>>^ Enquanto isso, Saulo só respirava ameaças e morte contra os discípulos do Senhor. Apresentou-se ao príncipe dos sacerdotes,

[[v51-9-2]]

^<<v51-9-2,2>>^ e pediu-lhe cartas para as sinagogas de Damasco, com o fim de levar presos a Jerusalém todos os homens e mulheres que achasse seguindo essa doutrina.

[[v51-9-3]]

^<<v51-9-3,3>>^ Durante a viagem, estando já perto de Damasco, subitamente o cercou uma luz resplandecente vinda do céu.

[[v51-9-4]]

^<<v51-9-4,4>>^ Caindo por terra, ouviu uma voz que lhe dizia: “Saulo, Saulo, por que me persegues?”.

[[v51-9-5]]

^<<v51-9-5,5>>^ Saulo disse: “Quem és, Senhor?” Respondeu ele: “Eu sou Jesus, a quem tu persegues. [Duro te é recalcitrar contra o aguilhão”.

[[v51-9-6]]

^<<v51-9-6,6>>^ Então, trêmulo e atônito, disse ele: “Senhor, que queres que eu faça?”. Respondeu-lhe o Senhor:] “Levanta-te, entra na cidade. Aí te será dito o que deves fazer”.^&#42;1^

[[v51-9-7]]

^<<v51-9-7,7>>^ Os homens que o acompanhavam enchiam-se de espanto, pois ouviam perfeitamente a voz, mas não viam ninguém.

[[v51-9-8]]

^<<v51-9-8,8>>^ Saulo levantou-se do chão. Abrindo, porém, os olhos, não via nada. Tomaram-no pela mão e o introduziram em Damasco,

[[v51-9-9]]

^<<v51-9-9,9>>^ onde esteve três dias sem ver, sem comer nem beber.

[[v51-9-10]]

^<<v51-9-10,10>>^ Havia em Damasco um discípulo chamado Ananias. O Senhor, numa visão, lhe disse: “Ananias!” –. “Eis-me aqui, Senhor” – respondeu ele.

[[v51-9-11]]

^<<v51-9-11,11>>^ O Senhor lhe ordenou: “Levanta-te e vai à rua Direita, e pergunta em casa de Judas por um homem de Tarso, chamado Saulo; ele está orando”.

[[v51-9-12]]

^<<v51-9-12,12>>^ (Este via numa visão um homem, chamado Ananias, entrar e impor-lhe as mãos para recobrar a vista.)

[[v51-9-13]]

^<<v51-9-13,13>>^ Ananias respondeu: “Senhor, muitos já me falaram deste homem, quantos males fez aos teus fiéis em Jerusalém.^&#42;1^

[[v51-9-14]]

^<<v51-9-14,14>>^ E aqui ele tem poder dos príncipes dos sacerdotes para prender a todos aqueles que invocam o teu nome”.

[[v51-9-15]]

^<<v51-9-15,15>>^ Mas o Senhor lhe disse: “Vai, porque este homem é para mim um instrumento escolhido, que levará o meu nome diante das nações, dos reis e dos filhos de Israel.

[[v51-9-16]]

^<<v51-9-16,16>>^ Eu lhe mostrarei tudo o que terá de padecer pelo meu nome”.

[[v51-9-17]]

^<<v51-9-17,17>>^ Ananias foi. Entrou na casa e, impondo-lhe as mãos, disse: “Saulo, meu irmão, o Senhor, esse Jesus que te apareceu no caminho, enviou-me para que recobres a vista e fiques cheio do Espírito Santo”.

[[v51-9-18]]

^<<v51-9-18,18>>^ No mesmo instante, caíram dos olhos de Saulo umas como que escamas, e recuperou a vista. Levantou-se e foi batizado.

[[v51-9-19]]

^<<v51-9-19,19>>^ Depois tomou alimento e sentiu-se fortalecido. Demorou-se por alguns dias com os discípulos que se achavam em Damasco.

[[v51-9-20]]

^<<v51-9-20,20>>^ Imediatamente começou a proclamar pelas sinagogas que Jesus é o Filho de Deus.

[[v51-9-21]]

^<<v51-9-21,21>>^ Todos os seus ouvintes pasmavam e diziam: “Este não é aquele que perseguia em Jerusalém os que invocam o nome de Jesus? Não veio cá só para levá-los presos aos sumos sacerdotes?”.

[[v51-9-22]]

^<<v51-9-22,22>>^ Saulo, porém, sentia crescer o seu poder e confundia os judeus de Damasco, demonstrando que Jesus é o Cristo.

[[v51-9-23]]

^<<v51-9-23,23>>^ Decorridos alguns dias, os judeus deliberaram, em conselho, matá-lo.

[[v51-9-24]]

^<<v51-9-24,24>>^ Essas intenções chegaram ao conhecimento de Saulo. Guardavam eles as portas de dia e de noite, para matá-lo.

[[v51-9-25]]

^<<v51-9-25,25>>^ Mas os discípulos, tomando-o de noite, fizeram-no descer pela muralha dentro de um cesto.

[[v51-9-26]]

^<<v51-9-26,26>>^ Chegando a Jerusalém, tentava ajuntar-se aos discípulos, mas todos o temiam, não querendo crer que se tivesse tornado discípulo.

[[v51-9-27]]

^<<v51-9-27,27>>^ Então Barnabé, levando-o consigo, apresentou-o aos apóstolos e contou-lhes como Saulo vira o Senhor no caminho, e que lhe havia falado, e como em Damasco pregara, com desassombro, o nome de Jesus.

[[v51-9-28]]

^<<v51-9-28,28>>^ Daí por diante permaneceu com eles, saindo e entrando em Jerusalém, e pregando, destemidamente, o nome do Senhor.

[[v51-9-29]]

^<<v51-9-29,29>>^ Falava também e discutia com os helenistas. Mas estes procuravam matá-lo.

[[v51-9-30]]

^<<v51-9-30,30>>^ Os irmãos, informados disso, acompanharam-no até Cesareia e dali o fizeram partir para Tarso.

[[v51-9-31]]

^<<v51-9-31,31>>^ A Igreja gozava então de paz por toda a Judeia, Galileia e Samaria. Estabelecia-se ela caminhando no temor do Senhor, e a assistência do Espírito Santo a fazia crescer em número.

[[v51-9-32]]

^<<v51-9-32,32>>^ Pedro, que caminhava por toda parte, de cidade em cidade, desceu também aos fiéis que habitavam em Lida.

[[v51-9-33]]

^<<v51-9-33,33>>^ Ali achou um homem chamado Eneias, que havia oito anos jazia paralítico num leito.

[[v51-9-34]]

^<<v51-9-34,34>>^ Disse-lhe Pedro: “Eneias, Jesus Cristo te cura: levanta-te e faze tua cama”. E levantou-se imediatamente.

[[v51-9-35]]

^<<v51-9-35,35>>^ Viram-no todos os que habitavam em Lida e em Sarona, e converteram-se ao Senhor.

[[v51-9-36]]

^<<v51-9-36,36>>^ Em Jope, havia uma discípula chamada Tabita – em grego, Dorcas. Esta era rica em boas obras e esmolas que dava.^&#42;1^

[[v51-9-37]]

^<<v51-9-37,37>>^ Aconteceu que adoecera naqueles dias e veio a falecer. Depois de a terem lavado, levaram-na para o quarto de cima.

[[v51-9-38]]

^<<v51-9-38,38>>^ Ora, como Lida fica perto de Jope, os discípulos, ouvindo dizer que Pedro aí se encontrava, enviaram-lhe dois homens, rogando-lhe: “Não te demores em vir ter conosco”.

[[v51-9-39]]

^<<v51-9-39,39>>^ Pedro levantou-se imediatamente e foi com eles. Logo que chegou, conduziram-no ao quarto de cima. Cercavam-no todas as viúvas, chorando e mostrando-lhe as túnicas e os vestidos que Dorcas lhes fazia quando viva.

[[v51-9-40]]

^<<v51-9-40,40>>^ , então, tendo feito todos sairem, pôs-se de joelhos e orou. Voltando-se para o corpo, disse: “Tabita, levanta-te!”. Ela abriu os olhos e, vendo Pedro, sentou-se.

[[v51-9-41]]

^<<v51-9-41,41>>^ Ele a fez levantar-se, estendendo-lhe a mão. Chamando os irmãos e as viúvas, entregou-lha viva.

[[v51-9-42]]

^<<v51-9-42,42>>^ Esse fato espalhou-se por toda a Jope e muitos creram no Senhor.

[[v51-9-43]]

^<<v51-9-43,43>>^ Pedro permaneceu ainda muitos dias em Jope, em casa de um curtidor, chamado Simão.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-008.adoc#v51-8-0[&#60; Capítulo Anterior] | <<v51-9-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-010.adoc#v51-10-0[Próximo Capítulo &#62;]