include::./index.adoc[]

[[v51-6-0]]
=== Atos dos Apóstolos, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Atos dos Apóstolos 6 descreve a escolha e a ordenação dos sete diáconos, que seriam responsáveis por servir às mesas dos crentes gregos e, assim, resolver um problema de distribuição de alimentos na igreja. Os versículos a seguir estão relacionados com os temas abordados nesse capítulo:
* Filipenses 1:1 - "Paulo e Timóteo, servos de Cristo Jesus, a todos os santos em Cristo Jesus que estão em Filipos, com os bispos e diáconos." Este versículo destaca que a igreja primitiva tinha uma ordem estabelecida, com diáconos entre seus líderes.
* 1 Timóteo 3:8 - "Da mesma forma, os diáconos sejam dignos, não de língua dobre, não dados a muito vinho, não cobiçosos de desonesto lucro." Aqui, Paulo dá instruções específicas sobre as qualidades que os diáconos devem ter.
* Atos dos Apóstolos 6:5 - "E este parecer contentou a toda a multidão, e elegeram Estêvão, homem cheio de fé e do Espírito Santo, e Filipe, e Prócoro, e Nicanor, e Timão, e Parmenas e Nicolau, prosélito de Antioquia." Este versículo mostra a escolha dos sete diáconos e suas qualidades.
* 1 Pedro 4:10-11 - "Servi uns aos outros conforme o dom que cada um recebeu, como bons despenseiros da multiforme graça de Deus. Se alguém fala, fale segundo as palavras de Deus; se alguém serve, faça-o na força que Deus supre, para que em todas as coisas Deus seja glorificado por meio de Jesus Cristo, a quem pertence a glória e o poder para todo o sempre. Amém." Este versículo destaca a importância do serviço na igreja e como ele deve ser realizado.
* Romanos 16:1-2 - "Recomendo-vos a nossa irmã Febe, a qual está servindo na igreja que está em Cencréia; para que a recebais no Senhor, como convém aos santos, e a ajudeis em tudo em que necessitar de vós; porque ela tem sido protetora de muitos, e de mim em particular." Este versículo destaca o papel das mulheres na igreja e sua contribuição para o serviço e ministério.
****

[[v51-6-1]]

^<<v51-6-1,1>>^ Naqueles dias, como crescesse o número dos discípulos, houve queixas dos gregos contra os hebreus, porque as suas viúvas teriam sido negligenciadas na distribuição diária.^&#42;1^

[[v51-6-2]]

^<<v51-6-2,2>>^ Por isso, os Doze convocaram uma reunião dos discípulos e disseram: “Não é razoável que abandonemos a Palavra de Deus, para administrar.^&#42;1^

[[v51-6-3]]

^<<v51-6-3,3>>^ Portanto, irmãos, escolhei dentre vós sete homens de boa reputação, cheios do Espírito Santo e de sabedoria, aos quais encarregaremos deste ofício.

[[v51-6-4]]

^<<v51-6-4,4>>^ Nós atenderemos sem cessar à oração e ao ministério da palavra”.

[[v51-6-5]]

^<<v51-6-5,5>>^ Esse parecer agradou a toda a reunião. Escolheram Estêvão, homem cheio de fé e do Espírito Santo; Filipe, Prócoro, Nicanor, Timão, Pármenas e Nicolau, prosélito de Antioquia.

[[v51-6-6]]

^<<v51-6-6,6>>^ Apresentaram-nos aos apóstolos, e estes, orando, impuseram-lhes as mãos.

[[v51-6-7]]

^<<v51-6-7,7>>^ Divulgava-se sempre mais a Palavra de Deus. Multiplicava-se consideravelmente o número de discípulos em Jerusalém. Também grande número de sacerdotes aderia à fé.

[[v51-6-8]]

^<<v51-6-8,8>>^ Estêvão, cheio de graça e fortaleza, fazia grandes milagres e prodígios entre o povo.

[[v51-6-9]]

^<<v51-6-9,9>>^ Mas alguns da sinagoga, chamada dos Libertos, dos cirenenses, dos alexandrinos e dos que eram da Cilícia e da Ásia, levantaram-se para disputar com ele.^&#42;1^

[[v51-6-10]]

^<<v51-6-10,10>>^ Não podiam, porém, resistir à sabedoria e ao Espírito que o inspirava.

[[v51-6-11]]

^<<v51-6-11,11>>^ Então, subornaram alguns indivíduos para que dissessem que o tinham ouvido proferir palavras de blasfêmia contra Moisés e contra Deus.

[[v51-6-12]]

^<<v51-6-12,12>>^ Amotinaram assim o povo, os anciãos e os escribas e, investindo contra ele, agarraram-no e o levaram ao Grande Conselho.

[[v51-6-13]]

^<<v51-6-13,13>>^ Apresentaram falsas testemunhas que diziam: “Este homem não cessa de proferir palavras contra o lugar santo e contra a Lei.

[[v51-6-14]]

^<<v51-6-14,14>>^ Nós o ouvimos dizer que Jesus de Nazaré há de destruir este lugar e há de mudar as tradições que Moisés nos legou”.^&#42;1^

[[v51-6-15]]

^<<v51-6-15,15>>^ Fixando nele os olhos, todos os membros do Grande Conselho viram o seu rosto semelhante ao de um anjo.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-005.adoc#v51-5-0[&#60; Capítulo Anterior] | <<v51-6-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-007.adoc#v51-7-0[Próximo Capítulo &#62;]