include::./index.adoc[]

[[v51-7-0]]
=== Atos dos Apóstolos, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Atos dos Apóstolos 7 narra o discurso de Estêvão antes de ser apedrejado até a morte. Ele defende a fé cristã diante dos líderes religiosos judeus, explicando a história do povo de Israel e apontando como Jesus é a realização das promessas de Deus. Abaixo estão cinco versículos relacionados com os temas abordados neste capítulo:
* Gênesis 12:1 - "Então o Senhor disse a Abrão: 'Saia da sua terra, do meio dos seus parentes e da casa de seu pai, e vá para a terra que eu lhe mostrarei'". Estêvão começa sua defesa citando a história de Abraão, que deixou sua terra natal para seguir a Deus.
* Êxodo 3:5 - "Disse Deus: 'Não se aproxime. Tire as sandálias dos pés, pois o lugar em que você está é terra santa'". Estêvão menciona Moisés e sua experiência com Deus na sarça ardente para enfatizar que Deus é santo e digno de adoração.
* Isaías 66:1-2 - "Assim diz o Senhor: 'O céu é o meu trono, e a terra, o estrado dos meus pés. O que vocês construirão para mim? Onde me edificarão um templo? Será que podem construir para mim um templo tão grandioso quanto eu? Desde quando fiz o universo, todas essas coisas existem'". Estêvão argumenta que Deus não pode ser limitado a um único lugar, como o templo em Jerusalém.
* Jeremias 7:2-7 - "Ouçam a palavra do Senhor, todo o povo de Judá que entra por estas portas para adorar o Senhor. Assim diz o Senhor dos Exércitos, o Deus de Israel: 'Corrijam o caminho que estão seguindo e as coisas que estão fazendo, e eu os farei habitar neste lugar. Não confiem em palavras enganosas, dizendo: 'Este é o templo do Senhor, o templo do Senhor, o templo do Senhor!'. Se vocês corrigirem o caminho que estão seguindo e as coisas que estão fazendo, se de fato praticarem a justiça, cada um a seu próximo, e não oprimiram o estrangeiro, o órfão e a viúva, nem derramarem sangue inocente neste lugar, e se vocês não seguirem outros deuses para sua própria ruína, então eu os farei habitar neste lugar, nesta terra que dei aos seus antepassados para sempre'". Estêvão acusa os líderes religiosos de serem hipócritas, pois eles estavam desobedecendo a Deus e confiando em sua posição como líderes do templo em vez de obedecerem a Deus.
* Salmo 110:1 - "O Senhor disse ao meu Senhor: 'Senta-te à minha direita até que eu ponha os teus inimigos como estrado para os teus pés'". Estêvão encerra seu discurso apontando para a exaltação de Jesus, que está à direita de Deus e é o verdadeiro líder e salvador.
****

[[v51-7-1]]

^<<v51-7-1,1>>^ Perguntou-lhe então o sumo sacerdote: “É realmente assim?”.

[[v51-7-2]]

^<<v51-7-2,2>>^ Respondeu ele: “Irmãos e pais, escutai. O Deus da glória apareceu a nosso pai Abraão, quando estava na Mesopotâmia, antes de ir morar em Harã.

[[v51-7-3]]

^<<v51-7-3,3>>^ E disse-lhe: Sai de teu país e de tua parentela, e vai para a terra que eu te mostrar (Gn 12,1).

[[v51-7-4]]

^<<v51-7-4,4>>^ Ele saiu da terra dos caldeus, e foi habitar em Harã. Dali, depois que lhe faleceu o pai, Deus o fez passar para esta terra, em que vós agora habitais.

[[v51-7-5]]

^<<v51-7-5,5>>^ Não lhe deu nela propriedade alguma, nem sequer um palmo de terra, mas prometeu dar-lha em posse, e depois dele à sua posteridade, quando ainda não tinha filho algum.

[[v51-7-6]]

^<<v51-7-6,6>>^ Eis como falou Deus: Sua descendência habitará em terra estranha e será reduzida à escravidão e maltratada pelo espaço de quatrocentos anos.

[[v51-7-7]]

^<<v51-7-7,7>>^ Mas eu julgarei a nação que os dominar – diz o Senhor –, e eles sairão e me prestarão culto neste lugar (Gn 15,13; Ex 3,12).

[[v51-7-8]]

^<<v51-7-8,8>>^ E deu-lhe a aliança da circuncisão. Assim, Abraão teve um filho, Isaac, e, passados oito dias, o circuncidou; e Isaac, a Jacó; e Jacó, os doze patriarcas.

[[v51-7-9]]

^<<v51-7-9,9>>^ “Os patriarcas, invejosos de José, venderam-no para o Egito. Mas Deus estava com ele.

[[v51-7-10]]

^<<v51-7-10,10>>^ Livrou-o de todas as suas tribulações e deu-lhe graça e sabedoria diante do faraó, rei do Egito, que o fez governador do Egito e chefe de sua casa.

[[v51-7-11]]

^<<v51-7-11,11>>^ Sobreveio depois uma fome a todo o Egito e Canaã. Grande era a tribulação, e os nossos pais não achavam o que comer.

[[v51-7-12]]

^<<v51-7-12,12>>^ Mas, quando Jacó soube que havia trigo no Egito, enviou pela primeira vez os nossos pais para lá.

[[v51-7-13]]

^<<v51-7-13,13>>^ Na segunda, foi José reconhecido por seus irmãos, e foi descoberta ao faraó a sua origem.

[[v51-7-14]]

^<<v51-7-14,14>>^ Enviando mensageiros, José mandou vir seu pai Jacó com toda a sua família, que constava de setenta e cinco pessoas.

[[v51-7-15]]

^<<v51-7-15,15>>^ Jacó desceu ao Egito e morreu ali, como também nossos pais.

[[v51-7-16]]

^<<v51-7-16,16>>^ Seus corpos foram trasladados para Siquém, e foram postos no sepulcro que Abraão tinha comprado, a peso de dinheiro, dos filhos de Hemor, de Siquém.

[[v51-7-17]]

^<<v51-7-17,17>>^ Aproximava-se o tempo em que devia realizar-se a promessa que Deus havia jurado a Abraão. O povo cresceu e se multiplicou no Egito

[[v51-7-18]]

^<<v51-7-18,18>>^ até que se levantou outro rei no Egito, o qual nada sabia de José.

[[v51-7-19]]

^<<v51-7-19,19>>^ Este rei, usando de astúcia contra a nossa raça, maltratou nossos pais e obrigou-os a enjeitarem seus filhos para privá-los da vida.

[[v51-7-20]]

^<<v51-7-20,20>>^ Por esse mesmo tempo, nasceu Moisés. Era belo aos olhos de Deus e por três meses foi criado na casa paterna.

[[v51-7-21]]

^<<v51-7-21,21>>^ Depois, quando foi exposto, a filha do faraó o recolheu e o criou como seu próprio filho.

[[v51-7-22]]

^<<v51-7-22,22>>^ Moisés foi instruído em todas as ciências dos egípcios e tornou-se forte em palavras e obras.

[[v51-7-23]]

^<<v51-7-23,23>>^ Quando completou quarenta anos, veio-lhe à mente visitar seus irmãos, os filhos de Israel.

[[v51-7-24]]

^<<v51-7-24,24>>^ Viu que um deles era maltratado; tomou-lhe a defesa e vingou o que padecia a injúria, matando o egípcio.

[[v51-7-25]]

^<<v51-7-25,25>>^ Ele esperava que os seus irmãos compreendessem que Deus se servia de sua mão para livrá-los. Mas não o entenderam.

[[v51-7-26]]

^<<v51-7-26,26>>^ No dia seguinte, dois dentre eles brigavam, e ele procurou reconciliá-los: Amigos, disse ele, sois irmãos, por que vos maltratais um ao outro?

[[v51-7-27]]

^<<v51-7-27,27>>^ Mas o que maltratava seu compatriota o repeliu: Quem te constituiu chefe ou juiz sobre nós?

[[v51-7-28]]

^<<v51-7-28,28>>^ Porventura queres tu matar-me, como ontem mataste o egípcio?

[[v51-7-29]]

^<<v51-7-29,29>>^ A estas palavras, Moisés fugiu. E esteve como estrangeiro na terra de Madiã, onde teve dois filhos.

[[v51-7-30]]

^<<v51-7-30,30>>^ Passados quarenta anos, apareceu-lhe no deserto do monte Sinai um anjo, na chama de uma sarça ardente.

[[v51-7-31]]

^<<v51-7-31,31>>^ Moisés, admirado de uma tal visão, aproximou-se para a examinar. E a voz do Senhor lhe falou:

[[v51-7-32]]

^<<v51-7-32,32>>^ Eu sou o Deus de teus pais, o Deus de Abraão, de Isaac e de Jacó. Moisés, atemorizado, não ousava levantar os olhos.

[[v51-7-33]]

^<<v51-7-33,33>>^ O Senhor lhe disse: Tira o teu calçado, porque o lugar onde estás é uma terra santa.

[[v51-7-34]]

^<<v51-7-34,34>>^ Considerei a aflição do meu povo no Egito, ouvi os seus gemidos e desci para livrá-los. Vem, pois, agora e eu te enviarei ao Egito.

[[v51-7-35]]

^<<v51-7-35,35>>^ Este Moisés, que desprezaram, dizendo: Quem te constituiu chefe ou juiz? A este, Deus enviou como chefe e libertador pela mão do anjo que lhe apareceu na sarça.

[[v51-7-36]]

^<<v51-7-36,36>>^ Ele os fez sair do Egito, operando prodígios e milagres na terra do Egito, no mar Vermelho e no deserto, por espaço de quarenta anos.

[[v51-7-37]]

^<<v51-7-37,37>>^ Foi este Moisés que disse aos filhos de Israel: Deus vos suscitará dentre os vossos irmãos um profeta como eu.

[[v51-7-38]]

^<<v51-7-38,38>>^ Este é o que esteve entre o povo congregado no deserto, e com o anjo que lhe falara no monte Sinai, e com os nossos pais; que recebeu palavras de vida para no-las transmitir.

[[v51-7-39]]

^<<v51-7-39,39>>^ Nossos pais não lhe quiseram obedecer, mas o repeliram. Em seus corações voltaram-se para o Egito,

[[v51-7-40]]

^<<v51-7-40,40>>^ dizendo a Aarão: Faze-nos deuses, que vão diante de nós, porque quanto a este Moisés, que nos tirou da terra do Egito, não sabemos o que foi feito dele.

[[v51-7-41]]

^<<v51-7-41,41>>^ Fizeram, naqueles dias, um bezerro de ouro e ofereceram um sacrifício ao ídolo, e se alegravam diante da obra das suas mãos.

[[v51-7-42]]

^<<v51-7-42,42>>^ Mas Deus afastou-se e os abandonou ao culto dos astros do céu, como está escrito no livro dos profetas: Porventura, casa de Israel, vós me oferecestes vítimas e sacrifícios por quarenta anos no deserto?

[[v51-7-43]]

^<<v51-7-43,43>>^ Aceitastes a tenda de Moloc e a estrela do vosso deus Renfão, figuras que vós fizestes para adorá-las! Assim eu vos deportarei para além da Babilônia (Am 5,25ss).

[[v51-7-44]]

^<<v51-7-44,44>>^ A arca da Aliança esteve com os nossos pais no deserto, como Deus ordenou a Moisés que a fizesse conforme o modelo que tinha visto.

[[v51-7-45]]

^<<v51-7-45,45>>^ Recebendo-a nossos pais, levaram-na sob a direção de Josué às terras dos pagãos, que Deus expulsou da presença de nossos pais. E ali ficou até o tempo de Davi.

[[v51-7-46]]

^<<v51-7-46,46>>^ Este encontrou graça diante de Deus e pediu que pudesse achar uma morada para o Deus de Jacó.

[[v51-7-47]]

^<<v51-7-47,47>>^ Salomão foi quem lhe edificou a casa.

[[v51-7-48]]

^<<v51-7-48,48>>^ O Altíssimo, porém, não habita em casas construídas por mãos humanas. Como diz o profeta:

[[v51-7-49]]

^<<v51-7-49,49>>^ O céu é o meu trono, e a terra o escabelo dos meus pés. Que casa me edificareis vós? – diz o Senhor. Qual é o lugar do meu repouso?

[[v51-7-50]]

^<<v51-7-50,50>>^ Acaso não foi minha mão que fez tudo isto (Is 66,1s)?

[[v51-7-51]]

^<<v51-7-51,51>>^ Homens de dura cerviz, e de corações e ouvidos incircuncisos! Vós sempre resistis ao Espírito Santo. Como procederam os vossos pais, assim procedeis vós também!

[[v51-7-52]]

^<<v51-7-52,52>>^ A qual dos profetas não perseguiram os vossos pais? Mataram os que prediziam a vinda do Justo, do qual vós agora tendes sido traidores e homicidas.

[[v51-7-53]]

^<<v51-7-53,53>>^ Vós que recebestes a Lei pelo ministério dos anjos e não a guardastes...”.^&#42;1^

[[v51-7-54]]

^<<v51-7-54,54>>^ Ao ouvir tais palavras, esbravejaram de raiva e rangiam os dentes contra ele.

[[v51-7-55]]

^<<v51-7-55,55>>^ Mas, cheio do Espírito Santo, Estêvão fitou o céu e viu a glória de Deus e Jesus de pé à direita de Deus:

[[v51-7-56]]

^<<v51-7-56,56>>^ “Eis que vejo” – disse ele – “os céus abertos e o Filho do Homem, de pé, à direita de Deus”.

[[v51-7-57]]

^<<v51-7-57,57>>^ Levantaram então um grande clamor, taparam os ouvidos e todos juntos se atiraram furiosos contra ele.

[[v51-7-58]]

^<<v51-7-58,58>>^ Lançaram-no fora da cidade e começaram a apedrejá-lo. As testemunhas depuseram os seus mantos aos pés de um moço chamado Saulo.

[[v51-7-59]]

^<<v51-7-59,59>>^ E apedrejavam Estêvão, que orava e dizia: “Senhor Jesus, recebe o meu espírito.”

[[v51-7-60]]

^<<v51-7-60,60>>^ Posto de joelhos, exclamou em alta voz: “Senhor, não lhes leves em conta este pecado...”. A estas palavras, expirou.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-006.adoc#v51-6-0[&#60; Capítulo Anterior] | <<v51-7-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-008.adoc#v51-8-0[Próximo Capítulo &#62;]