include::./index.adoc[]

[[v51-8-0]]
=== Atos dos Apóstolos, 8
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em Atos dos Apóstolos 8, é narrado o ministério de Filipe, um dos sete diáconos escolhidos pela igreja em Jerusalém. Ele pregou e realizou milagres na cidade de Samaria, levando muitas pessoas a se converterem ao cristianismo, incluindo um feiticeiro chamado Simão. Posteriormente, Filipe encontra um etíope e o conduz ao batismo após explicar as Escrituras para ele.
* Isaías 53:7-8: "Ele foi oprimido e afligido, mas não abriu a sua boca; como um cordeiro foi levado ao matadouro, e como a ovelha muda perante os seus tosquiadores, assim ele não abriu a sua boca. Da opressão e do juízo foi tirado; e quem contará o tempo da sua vida? Porque foi cortado da terra dos viventes; pela transgressão do meu povo ele foi atingido." Este versículo descreve a submissão de Jesus à vontade de Deus, mesmo que isso signifique sofrer e morrer.
* Atos dos Apóstolos 8:4: "Aqueles que foram dispersos iam por toda parte pregando a palavra." Após a morte de Estêvão, os cristãos foram dispersos por toda a Judeia e Samaria, mas isso não os impediu de continuar pregando o evangelho.
* Atos dos Apóstolos 8:12: "Mas, quando creram em Filipe, que lhes pregava acerca do Reino de Deus e do nome de Jesus Cristo, eram batizados, tanto homens como mulheres." Este versículo mostra como o ministério de Filipe foi bem-sucedido em levar as pessoas a crerem em Jesus e a serem batizadas em seu nome.
* Atos dos Apóstolos 8:20-21: "Disse, porém, Pedro: O teu dinheiro seja contigo para perdição, pois cuidaste que o dom de Deus se alcança por dinheiro. Não tens parte nem sorte nesta palavra, porque o teu coração não é reto diante de Deus." Simão, o feiticeiro, tentou comprar o poder de Deus com dinheiro, mas Pedro o repreendeu e disse que seu coração não estava correto diante de Deus.
* Atos dos Apóstolos 8:39-40: "E, quando saíram da água, o Espírito do Senhor arrebatou a Filipe, e não o viu mais o eunuco; e, jubiloso, continuou o seu caminho. Mas Filipe achou-se em Azoto e, indo passando, anunciava o evangelho em todas as cidades, até que chegou a Cesaréia." Este versículo mostra como o ministério de Filipe não se limitou a Samaria e ao encontro com o etíope, mas ele continuou pregando o evangelho em todas as cidades por onde passava.
****

[[v51-8-1]]

^<<v51-8-1,1>>^ E Saulo havia aprovado a morte de Estêvão. Naquele dia, rompeu uma grande perseguição contra a comunidade de Jerusalém. Todos se dispersaram pelas regiões da Judeia e de Samaria, com exceção dos apóstolos.

[[v51-8-2]]

^<<v51-8-2,2>>^ Entretanto, alguns homens piedosos trataram de enterrar Estêvão e fizeram grande pranto a seu respeito.

[[v51-8-3]]

^<<v51-8-3,3>>^ Saulo, porém, devastava a Igreja. Entrando pelas casas, arrancava delas homens e mulheres e os entregava à prisão.

[[v51-8-4]]

^<<v51-8-4,4>>^ Os que se haviam dispersado iam por toda a parte, anunciando a palavra (de Deus).

[[v51-8-5]]

^<<v51-8-5,5>>^ Assim Filipe desceu à cidade de Samaria, pregando-lhes Cristo.

[[v51-8-6]]

^<<v51-8-6,6>>^ A multidão estava atenta ao que Filipe lhe dizia, escutando-o unanimemente e presenciando os prodígios que fazia.

[[v51-8-7]]

^<<v51-8-7,7>>^ Pois os espíritos imundos de muitos possessos saíam, levantando grandes brados. Igualmente foram curados muitos paralíticos e coxos.

[[v51-8-8]]

^<<v51-8-8,8>>^ Por esse motivo, naquela cidade reinava grande alegria.

[[v51-8-9]]

^<<v51-8-9,9>>^ Ora, havia ali um homem, por nome Simão, que exercia magia na cidade, maravilhando o povo de Samaria, e fazia-se passar por um grande personagem.

[[v51-8-10]]

^<<v51-8-10,10>>^ Todos lhe davam ouvidos, do menor até o maior, comentando: “Este homem é o poder de Deus, chamado o Grande”.

[[v51-8-11]]

^<<v51-8-11,11>>^ Eles o atendiam, porque por muito tempo os havia deslumbrado com as suas artes mágicas.

[[v51-8-12]]

^<<v51-8-12,12>>^ Mas, depois que acreditaram em Filipe, que lhes anunciava o Reino de Deus e o nome de Jesus Cristo, homens e mulheres pediam o batismo.

[[v51-8-13]]

^<<v51-8-13,13>>^ Simão também acreditou e foi batizado. Ele não abandonava Filipe, admirando, estupefato, os grandes milagres e prodígios que eram feitos.

[[v51-8-14]]

^<<v51-8-14,14>>^ Os apóstolos que se achavam em Jerusalém, tendo ouvido que a Samaria recebera a Palavra de Deus, enviaram-lhe Pedro e João.

[[v51-8-15]]

^<<v51-8-15,15>>^ Estes, assim que chegaram, fizeram oração pelos novos fiéis, a fim de receberem o Espírito Santo,

[[v51-8-16]]

^<<v51-8-16,16>>^ visto que não havia descido ainda sobre nenhum deles, mas tinham sido somente batizados em nome do Senhor Jesus.

[[v51-8-17]]

^<<v51-8-17,17>>^ Então, os dois apóstolos lhes impuseram as mãos e receberam o Espírito Santo.

[[v51-8-18]]

^<<v51-8-18,18>>^ Quando Simão viu que se dava o Espírito Santo por meio da imposição das mãos dos apóstolos, ofereceu-lhes dinheiro, dizendo:

[[v51-8-19]]

^<<v51-8-19,19>>^ “Dai-me também este poder, para que todo aquele a quem impuser as mãos receba o Espírito Santo”.

[[v51-8-20]]

^<<v51-8-20,20>>^ Pedro respondeu: “Maldito seja o teu dinheiro e tu também, se julgas poder comprar o dom de Deus com dinheiro!

[[v51-8-21]]

^<<v51-8-21,21>>^ Não terás direito nem parte alguma neste ministério, já que o teu coração não é puro diante de Deus.

[[v51-8-22]]

^<<v51-8-22,22>>^ Arrepende-te desta tua maldade e roga a Deus, para que, sendo possível, te seja perdoado este pensamento do teu coração.

[[v51-8-23]]

^<<v51-8-23,23>>^ Pois estou a ver-te no fel da amargura e nos laços da iniquidade”.

[[v51-8-24]]

^<<v51-8-24,24>>^ Retorquiu Simão: “Rogai vós por mim ao Senhor, para que nada do que haveis dito venha a cair sobre mim .

[[v51-8-25]]

^<<v51-8-25,25>>^ Os apóstolos, depois de terem dado testemunho e anunciado a palavra do Senhor, voltaram para Jerusalém e pregavam a Boa-Nova em muitos lugares dos samaritanos.

[[v51-8-26]]

^<<v51-8-26,26>>^ Um anjo do Senhor dirigiu-se a Filipe e disse: “Levanta-te e vai para o Sul, em direção do caminho que desce de Jerusalém a Gaza, a Deserta”.^&#42;1^

[[v51-8-27]]

^<<v51-8-27,27>>^ Filipe levantou-se e partiu. Ora, um etíope, eunuco, ministro da rainha Candace, da Etiópia, e superintendente de todos os seus tesouros, tinha ido a Jerusalém para adorar.

[[v51-8-28]]

^<<v51-8-28,28>>^ Voltava sentado em seu carro, lendo o profeta Isaías.

[[v51-8-29]]

^<<v51-8-29,29>>^ O Espírito disse a Filipe: “Aproxima-te para bem perto deste carro.

[[v51-8-30]]

^<<v51-8-30,30>>^ Filipe aproximou-se e ouviu que o eunuco lia o profeta Isaías e perguntou-lhe: “Porventura entendes o que estás lendo?”

[[v51-8-31]]

^<<v51-8-31,31>>^ Respondeu-lhe: “Como é que posso, se não há alguém que me explique?”. E rogou a Filipe que subisse e se sentasse junto dele.

[[v51-8-32]]

^<<v51-8-32,32>>^ A passagem da Escritura, que ia lendo, era esta: Como ovelha, foi levado ao matadouro; e, como cordeiro mudo diante do que o tosquia, ele não abriu a sua boca.

[[v51-8-33]]

^<<v51-8-33,33>>^ Na sua humilhação foi consumado o seu julgamento. Quem poderá contar a sua descendência? Pois a sua vida foi tirada da terra (Is 53,7s).

[[v51-8-34]]

^<<v51-8-34,34>>^ O eunuco disse a Filipe: “Rogo-te que me digas de quem disse isto o profeta: de si mesmo ou de outrem?”.

[[v51-8-35]]

^<<v51-8-35,35>>^ Começou então Filipe a falar, e, principiando por essa passagem da Escritura, anunciou-lhe Jesus.

[[v51-8-36]]

^<<v51-8-36,36>>^ Continuando o caminho, encontraram água. Disse então o eunuco: “Eis aí a água. Que impede que eu seja batizado?”.

[[v51-8-37]]

^<<v51-8-37,37>>^ [Filipe respondeu: “Se crês de todo o coração, podes sê-lo.” – “Eu creio”, disse ele, “que Jesus Cristo é o Filho de Deus”.]^&#42;1^

[[v51-8-38]]

^<<v51-8-38,38>>^ E mandou parar o carro. Ambos desceram à água e Filipe batizou o eunuco.

[[v51-8-39]]

^<<v51-8-39,39>>^ Mal saíram da água, o Espírito do Senhor arrebatou Filipe dos olhares do eunuco que, cheio de alegria, continuou o seu caminho.

[[v51-8-40]]

^<<v51-8-40,40>>^ Filipe, entretanto, foi transportado a Azoto. Passando além, pregava o Evangelho em todas as cidades, até que chegou a Cesareia.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-007.adoc#v51-7-0[&#60; Capítulo Anterior] | <<v51-8-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-009.adoc#v51-9-0[Próximo Capítulo &#62;]