include::./index.adoc[]

[[v51-12-0]]
=== Atos dos Apóstolos, 12
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Atos dos Apóstolos 12 relata a prisão de Pedro e sua subsequente libertação sobrenatural pelos anjos de Deus. Também é mencionada a morte de Tiago, irmão de João, pelas mãos de Herodes. Os versículos selecionados são:
* Isaías 43:2: "Quando passares pelas águas, estarei contigo, e quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti." Pedro passou por um momento de grande perigo e angústia ao ser preso e colocado na prisão, mas o Senhor estava com ele, protegendo-o da ira de Herodes.
* Salmos 34:19: "Muitas são as aflições do justo, mas o Senhor o livra de todas." Pedro era um homem justo que foi preso injustamente. No entanto, o Senhor o livrou das mãos de Herodes e o libertou da prisão.
* Provérbios 21:1: "O coração do rei está na mão do Senhor como águas profundas; ele o inclina para onde quer." Herodes estava determinado a matar Pedro, mas Deus tinha outros planos. Ele usou um anjo para libertá-lo da prisão e frustrar os planos do rei.
* João 16:33: "No mundo, tereis aflições; mas tende bom ânimo; eu venci o mundo." A morte de Tiago e a prisão de Pedro são exemplos das aflições que os discípulos de Jesus enfrentaram. No entanto, Jesus lhes deu a promessa de que eles teriam paz em meio às tribulações, pois Ele havia vencido o mundo.
* Atos dos Apóstolos 12:24: "Mas a palavra de Deus crescia e se multiplicava." Apesar da perseguição e das tentativas de silenciar a mensagem do evangelho, a palavra de Deus continuou a se espalhar e a alcançar mais pessoas. A prisão de Pedro e a morte de Tiago não conseguiram deter o avanço do reino de Deus.
****

[[v51-12-1]]

^<<v51-12-1,1>>^ Por aquele mesmo tempo, o rei Herodes mandou prender alguns membros da Igreja para os maltratar.^&#42;1^

[[v51-12-2]]

^<<v51-12-2,2>>^ Assim foi que matou à espada Tiago, irmão de João.

[[v51-12-3]]

^<<v51-12-3,3>>^ Vendo que isso agradava aos judeus, mandou prender Pedro. Eram então os dias dos pães sem fermento.

[[v51-12-4]]

^<<v51-12-4,4>>^ Mandou prendê-lo e lançou-o no cárcere, entregando-o à guarda de quatro grupos, de quatro soldados cada um, com a intenção de apresentá-lo ao povo depois da Páscoa.

[[v51-12-5]]

^<<v51-12-5,5>>^ Pedro estava assim encerrado na prisão, mas a Igreja orava sem cessar por ele a Deus.

[[v51-12-6]]

^<<v51-12-6,6>>^ Na noite anterior que Herodes ia apresentá-lo dormia Pedro entre dois soldados, ligado com duas cadeias. Os guardas, à porta, vigiavam o cárcere.

[[v51-12-7]]

^<<v51-12-7,7>>^ De repente, apresentou-se um anjo do Senhor, e uma luz brilhou no recinto. Tocando no lado de Pedro, o anjo despertou-o: “Levanta-te depressa” – disse ele. Caíram-lhe as cadeias das mãos.

[[v51-12-8]]

^<<v51-12-8,8>>^ O anjo ordenou: “Cinge-te e calça as tuas sandálias”. Ele assim o fez. O anjo acrescentou: “Cobre-te com a tua capa e segue-me”.

[[v51-12-9]]

^<<v51-12-9,9>>^ Pedro saiu e seguiu-o, sem saber se era real o que se fazia por meio do anjo. Julgava estar sonhando.^&#42;1^

[[v51-12-10]]

^<<v51-12-10,10>>^ Passaram o primeiro e o segundo postos da guarda. Chegaram ao portão de ferro, que dá para a cidade, o qual se lhes abriu por si mesmo. Saíram e tomaram juntos uma rua. Em seguida, de súbito, o anjo desapareceu.

[[v51-12-11]]

^<<v51-12-11,11>>^ Então, Pedro tornou a si e disse: “Agora vejo que o Senhor mandou verdadeiramente o seu anjo e me livrou da mão de Herodes e de tudo o que esperava o povo dos judeus”.

[[v51-12-12]]

^<<v51-12-12,12>>^ Refletiu um momento e dirigiu-se para a casa de Maria, mãe de João, que tem por sobrenome Marcos, onde muitos se tinham reunido e faziam oração.

[[v51-12-13]]

^<<v51-12-13,13>>^ Quando bateu à porta de entrada, uma criada, chamada Rode, adiantou-se para escutar.

[[v51-12-14]]

^<<v51-12-14,14>>^ Mal reconheceu a voz de Pedro, de tanta alegria não abriu a porta, mas, correndo para dentro, foi anunciar que era Pedro que estava à porta.

[[v51-12-15]]

^<<v51-12-15,15>>^ Disseram-lhe: “Estás louca!”. Mas ela persistia em afirmar que era verdade. Diziam eles: “Então é o seu anjo”.

[[v51-12-16]]

^<<v51-12-16,16>>^ Pedro continuava a bater. Afinal abriram a porta, viram-no e ficaram atônitos.

[[v51-12-17]]

^<<v51-12-17,17>>^ Ele, acenando-lhes com a mão que se calassem, contou como o Senhor o havia livrado da prisão, e disse: “Comunicai-o a Tiago e aos irmãos”. Em seguida, saiu dali e retirou-se para outro lugar.^&#42;1^

[[v51-12-18]]

^<<v51-12-18,18>>^ Logo que amanheceu, houve um sobressalto pouco comum entre os soldados sobre o que acontecera a Pedro.

[[v51-12-19]]

^<<v51-12-19,19>>^ Herodes, procurando-o e não o achando, instaurou um processo contra os guardas e mandou supliciá-los. Em seguida, desceu da Judeia para a Cesareia, onde permaneceu.

[[v51-12-20]]

^<<v51-12-20,20>>^ Estava Herodes em conflito com os habitantes de Tiro e de Sidônia. Estes, porém, de comum acordo, se apresentaram a ele, e, com o favor de Blasto, que era camareiro do rei, pediram a paz. (Porque a sua região era abastecida por ele.)

[[v51-12-21]]

^<<v51-12-21,21>>^ No dia marcado, Herodes, vestido em traje real, sentou-se no tribunal e lhes dirigiu uma alocução.

[[v51-12-22]]

^<<v51-12-22,22>>^ O povo aplaudia: “É a voz de um deus, e não de um homem!”.

[[v51-12-23]]

^<<v51-12-23,23>>^ No mesmo instante, o anjo do Senhor o feriu, por ele não haver dado honra a Deus. E, roído de vermes, expirou. ^&#42;1^

[[v51-12-24]]

^<<v51-12-24,24>>^ Entretanto, a Palavra de Deus crescia e se espalhava sempre mais.

[[v51-12-25]]

^<<v51-12-25,25>>^ Tendo Barnabé e Saulo concluído a sua missão, voltaram de Jerusalém (a Antioquia), levando consigo João, que tem por sobrenome Marcos.^&#42;1^

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-011.adoc#v51-11-0[&#60; Capítulo Anterior] | <<v51-12-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-013.adoc#v51-13-0[Próximo Capítulo &#62;]