include::./index.adoc[]

[[v51-19-0]]
=== Atos dos Apóstolos, 19
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 19 de Atos dos Apóstolos descreve a chegada de Paulo a Éfeso, onde ele encontra um grupo de discípulos que não tinham ouvido falar do Espírito Santo. Paulo prega o Evangelho na sinagoga e na escola de Tirano, onde Deus realiza muitos milagres e curas pelas mãos de Paulo. Também ocorre um conflito com os filhos de Ceva, que tentam expulsar demônios pelo nome de Jesus sem terem autoridade para isso. Depois disso, a cidade é abalada por um tumulto causado por um ourives que se sente ameaçado pela pregação de Paulo. Os versículos relacionados com os temas do capítulo são:
* Mateus 10:8: "Curai enfermos, ressuscitai mortos, purificai leprosos, expeli demônios; de graça recebestes, de graça dai." Esse versículo se relaciona com a atuação de Paulo em Éfeso, onde Deus realiza muitos milagres e curas pelas mãos de Paulo, mostrando o poder e a autoridade de Deus.
* Marcos 9:38: "E João lhe respondeu, dizendo: Mestre, vimos um que, em teu nome, expulsava demônios, o qual não nos segue; e nós lho proibimos, porque não nos seguia." Esse versículo se relaciona com o conflito entre Paulo e os filhos de Ceva, que tentam expulsar demônios pelo nome de Jesus sem terem autoridade para isso. Paulo demonstra que só aqueles que crêem em Jesus e têm autoridade dada por Ele podem fazer tal obra.
* João 16:33: "Tenho-vos dito isto, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo; eu venci o mundo." Esse versículo se relaciona com o tumulto em Éfeso causado pelo ourives que se sentiu ameaçado pela pregação de Paulo. A perseguição e oposição são uma realidade para aqueles que seguem a Jesus, mas a paz de Cristo e o bom ânimo nos são garantidos, pois Ele já venceu o mundo.
* 2 Timóteo 1:7: "Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação." Esse versículo se relaciona com a pregação de Paulo em Éfeso, onde muitos eram amedrontados pelas práticas ocultas e feitiçarias. Paulo anuncia a verdade de que em Jesus temos a fortaleza, o amor e a moderação que vêm do Espírito Santo.
* 1 Coríntios 14:33: "Porque Deus não é Deus de confusão, senão de paz, como em todas as igrejas dos santos." Esse versículo se relaciona com o conflito em Éfeso causado pelo ourives, que levou a cidade a uma grande confusão. Deus é um Deus de paz, e a mensagem de Cristo traz a paz e a reconciliação para aqueles que crêem.
****

[[v51-19-1]]

^<<v51-19-1,1>>^ Enquanto Apolo estava em Corinto, Paulo atravessou as províncias superiores e chegou a Éfeso, onde achou alguns discípulos e indagou deles:

[[v51-19-2]]

^<<v51-19-2,2>>^ “Recebestes o Espírito Santo, quando abraçastes a fé?”. Responderam-lhe: “Não, nem sequer ouvimos dizer que há um Espírito Santo!” –.

[[v51-19-3]]

^<<v51-19-3,3>>^ “Então, em que batismo fostes batizados?” – perguntou Paulo. Disseram: “No batismo de João.”

[[v51-19-4]]

^<<v51-19-4,4>>^ Paulo então replicou: “João só dava um batismo de penitência, dizendo ao povo que cresse naquele que havia de vir depois dele, isto é, em Jesus”.

[[v51-19-5]]

^<<v51-19-5,5>>^ Ouvindo isso, foram batizados em nome do Senhor Jesus.

[[v51-19-6]]

^<<v51-19-6,6>>^ E quando Paulo lhes impôs as mãos, o Espírito Santo desceu sobre eles, e falavam em línguas estranhas e profetizavam.

[[v51-19-7]]

^<<v51-19-7,7>>^ Eram ao todo uns doze homens.

[[v51-19-8]]

^<<v51-19-8,8>>^ Paulo entrou na sinagoga e falou com desassombro por três meses, disputando e persuadindo-os acerca do Reino de Deus.

[[v51-19-9]]

^<<v51-19-9,9>>^ Mas, como alguns se endurecessem e não cressem, desacreditando a sua doutrina diante da multidão, apartou-se deles e reuniu à parte os discípulos, onde os ensinava diariamente na escola de um certo Tirano.

[[v51-19-10]]

^<<v51-19-10,10>>^ Isso durou dois anos, de tal maneira que todos os habitantes da Ásia, judeus e gentios, puderam ouvir a palavra do Senhor.

[[v51-19-11]]

^<<v51-19-11,11>>^ Deus fazia milagres extraordinários por intermédio de Paulo, de modo que lenços e outros panos que tinham tocado o seu corpo eram levados aos enfermos;

[[v51-19-12]]

^<<v51-19-12,12>>^ e afastavam-se deles as doenças e retiravam-se os espíritos malignos.

[[v51-19-13]]

^<<v51-19-13,13>>^ Alguns judeus exorcistas que percorriam vários lugares inventaram invocar o nome do Senhor Jesus sobre os que se achavam possessos dos espíritos malignos, com as palavras: “Esconjuro-vos por Jesus, a quem Paulo prega”.

[[v51-19-14]]

^<<v51-19-14,14>>^ Assim procediam os sete filhos de um judeu chamado Cevas, sumo sacerdote.

[[v51-19-15]]

^<<v51-19-15,15>>^ Mas o espírito maligno replicou-lhes: “Conheço Jesus e sei quem é Paulo. Mas vós, quem sois?”.

[[v51-19-16]]

^<<v51-19-16,16>>^ Nisso, o homem possuído do espírito maligno, saltando sobre eles, apoderou-se de dois deles e subjugou-os de tal maneira, que tiveram de fugir daquela casa feridos e com as roupas estraçalhadas.

[[v51-19-17]]

^<<v51-19-17,17>>^ Este caso tornou-se (em breve) conhecido de todos os judeus e gregos de Éfeso, e encheu-os de temor e engrandeceram o nome do Senhor Jesus.

[[v51-19-18]]

^<<v51-19-18,18>>^ Muitos dos que haviam acreditado vinham confessar e declarar as suas obras.

[[v51-19-19]]

^<<v51-19-19,19>>^ Muitos também, que tinham exercido artes mágicas, ajuntaram os seus livros e queimaram-nos diante de todos. Calculou-se o seu valor, e achou-se que montava a cinquenta mil moedas de prata.

[[v51-19-20]]

^<<v51-19-20,20>>^ Foi assim que o poder do Senhor fez crescer a palavra e a tornou sempre mais eficaz.

[[v51-19-21]]

^<<v51-19-21,21>>^ Concluídas essas coisas, Paulo resolveu ir a Jerusalém, depois de atravessar a Macedônia e a Acaia. “Depois de eu ter estado lá” – disse ele –, “é necessário que veja também Roma.”

[[v51-19-22]]

^<<v51-19-22,22>>^ Enviou à Macedônia dois dos seus auxiliares, Timóteo e Erasto, mas ele mesmo se demorou ainda por algum tempo na Ásia.

[[v51-19-23]]

^<<v51-19-23,23>>^ Por esse tempo, ocorreu um grande alvoroço a respeito do Evangelho.

[[v51-19-24]]

^<<v51-19-24,24>>^ Um ourives, chamado Demétrio, que fazia de prata templozinhos de Ártemis, dava muito a ganhar aos artífices.

[[v51-19-25]]

^<<v51-19-25,25>>^ Convocou-os, juntamente com os demais operários do mesmo ramo, e disse: “Conheceis o lucro que nos resulta desta indústria.

[[v51-19-26]]

^<<v51-19-26,26>>^ Ora, estais vendo e ouvindo que não só em Éfeso, mas quase em toda a Ásia, esse Paulo tem persuadido e desencaminhado muita gente, dizendo que não são deuses os ídolos que são feitos por mãos de homens.

[[v51-19-27]]

^<<v51-19-27,27>>^ Daí não somente há perigo de que essa nossa corporação caia em descrédito, como também que o templo da grande Ártemis seja desconsiderado, e até mesmo seja despojada de sua majestade aquela que toda a Ásia e o mundo inteiro adoram.”

[[v51-19-28]]

^<<v51-19-28,28>>^ Essas palavras encheram-nos de ira e puseram-se a gritar: “Viva a Ártemis dos efésios!”.

[[v51-19-29]]

^<<v51-19-29,29>>^ A cidade alvoroçou-se e todos correram ao teatro levando consigo Caio e Aristarco, macedônios e companheiros de Paulo.

[[v51-19-30]]

^<<v51-19-30,30>>^ Paulo queria apresentar-se ao povo, mas os discípulos não o deixaram.

[[v51-19-31]]

^<<v51-19-31,31>>^ Até alguns dos asiarcas, que eram seus amigos, enviaram-lhe recado, pedindo que não se aventurasse a ir ao teatro.^&#42;1^

[[v51-19-32]]

^<<v51-19-32,32>>^ Todos gritavam ao mesmo tempo. A assembleia era uma grande confusão e a maioria nem sabia por que se achavam ali reunidos.^&#42;1^

[[v51-19-33]]

^<<v51-19-33,33>>^ Então fizeram sair do meio da turba Alexandre, que os judeus empurravam para a frente. Alexandre, fazendo sinal com a mão, queria dar satisfação ao povo.^&#42;1^

[[v51-19-34]]

^<<v51-19-34,34>>^ Mas quando perceberam que ele era judeu, todos a uma voz gritaram pelo espaço de quase duas horas: “Viva a Ártemis dos efésios!”.

[[v51-19-35]]

^<<v51-19-35,35>>^ Então, o escrivão da cidade (veio) para apaziguar a multidão e disse: “Efésios, que homem há que não saiba que a cidade de Éfeso cultua a grande Ártemis, e que a sua estátua caiu dos céus?

[[v51-19-36]]

^<<v51-19-36,36>>^ Se isso é incontestável, convém que vos sossegueis e nada façais inconsideradamente.

[[v51-19-37]]

^<<v51-19-37,37>>^ Estes homens, que aqui trouxestes, não são sacrílegos nem blasfemadores da vossa deusa.

[[v51-19-38]]

^<<v51-19-38,38>>^ Mas, se Demétrio e os outros artífices têm alguma queixa contra alguém, os tribunais estão abertos e aí estão os magistrados: institua-se um processo contra eles.

[[v51-19-39]]

^<<v51-19-39,39>>^ Se tendes reclamação a fazer, a assembleia legal decidirá.

[[v51-19-40]]

^<<v51-19-40,40>>^ Do que se deu hoje, até corremos risco de sermos acusados de rebelião, porque não há motivo algum que nos permita justificar este concurso”.

[[v51-19-41]]

^<<v51-19-41,41>>^ A essas palavras, dissolveu-se a aglomeração.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-018.adoc#v51-18-0[&#60; Capítulo Anterior] | <<v51-19-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-020.adoc#v51-20-0[Próximo Capítulo &#62;]