include::./index.adoc[]

[[v51-15-0]]
=== Atos dos Apóstolos, 15
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em Atos dos Apóstolos 15, os apóstolos e anciãos se reúnem para discutir a questão da circuncisão entre os gentios convertidos ao cristianismo. Depois de uma discussão, eles chegam a uma decisão de que os gentios não precisam ser circuncidados para serem salvos. Aqui estão cinco versículos relacionados com os temas abordados em Atos dos Apóstolos 15:
* Gálatas 5:2-3: "Eis que eu, Paulo, vos digo que, se vos deixardes circuncidar, Cristo de nada vos aproveitará. E de novo protesto a todo o homem, que se deixar circuncidar, que está obrigado a guardar toda a lei." Neste versículo, Paulo está alertando os cristãos da Galácia sobre os perigos da circuncisão e como isso pode afetar sua salvação.
* Romanos 2:28-29: "Pois não é judeu quem o é exteriormente, nem é circuncisão a que o é exteriormente na carne. Mas é judeu quem o é interiormente, e circuncisão é a do coração, no espírito, não na letra; cujo louvor não provém dos homens, mas de Deus." Aqui, Paulo está explicando que a verdadeira circuncisão é a do coração e que a salvação não depende da circuncisão física.
* Colossenses 2:11: "Nele também fostes circuncidados com circuncisão não feita por mão no despojar do corpo da carne, a circuncisão de Cristo." Este versículo fala sobre a circuncisão espiritual que acontece através da fé em Cristo.
* Filipenses 3:3: "Porque a circuncisão somos nós, que servimos a Deus no espírito, e nos gloriamos em Cristo Jesus, e não confiamos na carne." Neste versículo, Paulo está enfatizando a importância da circuncisão espiritual e como isso é mais importante do que a circuncisão física.
* Atos dos Apóstolos 15:28-29: "Porque pareceu bem ao Espírito Santo e a nós não vos impor mais encargo algum, senão estas coisas necessárias: que vos abstenhais das coisas sacrificadas aos ídolos, e do sangue, e da carne sufocada, e da prostituição, das quais coisas bem fazeis se vos guardardes." Este versículo é parte da decisão tomada pelos apóstolos e anciãos em relação à questão da circuncisão e quais outros requisitos os gentios convertidos precisavam seguir.
****

[[v51-15-1]]

^<<v51-15-1,1>>^ Alguns homens, descendo da Judeia, puseram-se a ensinar aos irmãos o seguinte: “Se não vos circuncidais, segundo o rito de Moisés, não podeis ser salvos”.^&#42;1^

[[v51-15-2]]

^<<v51-15-2,2>>^ Originou-se então grande discussão de Paulo e Barnabé com eles, e resolveu-se que estes dois, com alguns outros irmãos, fossem tratar desta questão com os apóstolos e os anciãos em Jerusalém.

[[v51-15-3]]

^<<v51-15-3,3>>^ Acompanhados (algum tempo) dos membros da comunidade, tomaram o caminho que atravessa a Fenícia e Samaria. Contaram a todos os irmãos a conversão dos gentios, o que causou a todos grande alegria.

[[v51-15-4]]

^<<v51-15-4,4>>^ Chegando a Jerusalém, foram recebidos pela comunidade, pelos apóstolos e anciãos, a quem contaram tudo o que Deus tinha feito com eles.

[[v51-15-5]]

^<<v51-15-5,5>>^ Mas levantaram-se alguns que antes de ter abraçado a fé eram da seita dos fariseus, dizendo que era necessário circuncidar os pagãos e impor-lhes a observância da Lei de Moisés.

[[v51-15-6]]

^<<v51-15-6,6>>^ Reuniram-se os apóstolos e os anciãos para tratar dessa questão.

[[v51-15-7]]

^<<v51-15-7,7>>^ Ao fim de uma grande discussão, Pedro levantou-se e lhes disse: “Irmãos, vós sabeis que já há muito tempo Deus me escolheu dentre vós, para que da minha boca os pagãos ouvissem a palavra do Evangelho e cressem.

[[v51-15-8]]

^<<v51-15-8,8>>^ Ora, Deus, que conhece os corações, testemunhou a seu respeito, dando-lhes o Espírito Santo, da mesma forma que a nós.

[[v51-15-9]]

^<<v51-15-9,9>>^ Nem fez distinção alguma entre nós e eles, purificando pela fé os seus corações.

[[v51-15-10]]

^<<v51-15-10,10>>^ Por que, pois, provocais agora a Deus, impondo aos discípulos um jugo que nem nossos pais nem nós pudemos suportar?

[[v51-15-11]]

^<<v51-15-11,11>>^ Nós cremos que pela graça do Senhor Jesus seremos salvos, exatamente como eles”.

[[v51-15-12]]

^<<v51-15-12,12>>^ Toda a assembleia o ouviu silenciosamente. Em seguida, ouviram Barnabé e Paulo contar quantos milagres e prodígios Deus fizera por meio deles entre os gentios.

[[v51-15-13]]

^<<v51-15-13,13>>^ Depois de terminarem, Tiago tomou a palavra: “Irmãos, ouvi-me” – disse ele.

[[v51-15-14]]

^<<v51-15-14,14>>^ “Simão narrou como Deus começou a olhar para as nações pagãs para tirar delas um povo que trouxesse o seu nome.

[[v51-15-15]]

^<<v51-15-15,15>>^ Ora, com isto concordam as palavras dos profetas, como está escrito:

[[v51-15-16]]

^<<v51-15-16,16>>^ Depois disto voltarei, e reedificarei o tabernáculo de Davi que caiu. E reedificarei as suas ruínas, e o levantarei

[[v51-15-17]]

^<<v51-15-17,17>>^ para que o resto dos homens busque o Senhor, e todas as nações, sobre as quais tem sido invocado o meu nome.

[[v51-15-18]]

^<<v51-15-18,18>>^ Assim fala o Senhor que faz estas coisas, coisas que ele conheceu desde a eternidade (Am 9,11s).

[[v51-15-19]]

^<<v51-15-19,19>>^ Por isso, julgo que não se devem inquietar os que dentre os gentios se convertem a Deus.

[[v51-15-20]]

^<<v51-15-20,20>>^ Mas que se lhes escreva somente que se abstenham das carnes oferecidas aos ídolos, da impureza, das carnes sufocadas e do sangue.^&#42;1^

[[v51-15-21]]

^<<v51-15-21,21>>^ Porque Moisés, desde muitas gerações, tem em cada cidade seus pregadores, pois que ele é lido nas sinagogas todos os sábados”.

[[v51-15-22]]

^<<v51-15-22,22>>^ Então, pareceu bem aos apóstolos e aos anciãos com toda a comunidade escolher homens dentre eles e enviá-los a Antioquia com Paulo e Barnabé: Judas, que tinha o sobrenome de Barsabás, e Silas, homens notáveis entre os irmãos.

[[v51-15-23]]

^<<v51-15-23,23>>^ Por seu intermédio enviaram a seguinte carta: “Os apóstolos e os anciãos aos irmãos de origem pagã, em Antioquia, na Síria e Cilícia, saúde!

[[v51-15-24]]

^<<v51-15-24,24>>^ Temos ouvido que alguns dentre nós vos têm perturbado com palavras, transtornando os vossos espíritos, sem lhes termos dado semelhante incumbência.

[[v51-15-25]]

^<<v51-15-25,25>>^ Assim nós nos reunimos e decidimos escolher delegados e enviá-los a vós, com os nossos amados Barnabé e Paulo,

[[v51-15-26]]

^<<v51-15-26,26>>^ homens que têm exposto suas vidas pelo nome de nosso Senhor Jesus Cristo.

[[v51-15-27]]

^<<v51-15-27,27>>^ Enviamos, portanto, Judas e Silas que de viva voz vos exporão as mesmas coisas.

[[v51-15-28]]

^<<v51-15-28,28>>^ Com efeito, pareceu bem ao Espírito Santo e a nós não vos impor outro peso além do seguinte indispensável:

[[v51-15-29]]

^<<v51-15-29,29>>^ que vos abstenhais das carnes sacrificadas aos ídolos, do sangue, da carne sufocada e da impureza. Dessas coisas fareis bem de vos guardar conscienciosamente. Adeus!”.

[[v51-15-30]]

^<<v51-15-30,30>>^ Tendo-se despedido, a delegação dirigiu-se a Antioquia. Ali reuniram a assembleia e entregaram a carta.

[[v51-15-31]]

^<<v51-15-31,31>>^ À sua leitura, todos se alegraram com o estímulo que ela trazia.

[[v51-15-32]]

^<<v51-15-32,32>>^ Judas e Silas, que eram também profetas, dirigiram aos irmãos muitas palavras de exortação e de animação.

[[v51-15-33]]

^<<v51-15-33,33>>^ Demoraram-se ali por algum tempo. Foram depois pelos irmãos despedidos em paz, voltando aos que lhes tinham enviado.

[[v51-15-34]]

^<<v51-15-34,34>>^ [A Silas, contudo, pareceu bem ficar ali, e Judas partiu sozinho.]^&#42;1^

[[v51-15-35]]

^<<v51-15-35,35>>^ Paulo e Barnabé detiveram-se também em Antioquia, ensinando e pregando com muitos outros a palavra do Senhor.

[[v51-15-36]]

^<<v51-15-36,36>>^ Ao termo de alguns dias, disse Paulo a Barnabé: “Tornemos a visitar os irmãos por todas as cidades onde temos pregado a palavra do Senhor, para ver como estão passando”.^&#42;1^

[[v51-15-37]]

^<<v51-15-37,37>>^ Barnabé queria levar consigo também João, que tinha por sobrenome Marcos.

[[v51-15-38]]

^<<v51-15-38,38>>^ Paulo, porém, achava que não devia ser admitido quem se tinha separado deles em Panfília e não os havia acompanhado no ministério.

[[v51-15-39]]

^<<v51-15-39,39>>^ Houve tal discussão que se separaram um do outro, e Barnabé, levando consigo Marcos, navegou para Chipre.

[[v51-15-40]]

^<<v51-15-40,40>>^ Paulo, porém, tendo escolhido Silas, e depois de ter sido recomendado pelos irmãos à graça do Senhor, partiu. Ele percorreu a Síria, a Cilícia, confirmando as comunidades.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-014.adoc#v51-14-0[&#60; Capítulo Anterior] | <<v51-15-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-016.adoc#v51-16-0[Próximo Capítulo &#62;]