include::./index.adoc[]

[[v51-24-0]]
=== Atos dos Apóstolos, 24
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Atos dos Apóstolos 24 narra a defesa de Paulo perante o governador Félix em Cesareia, após ter sido acusado pelos judeus. Paulo faz sua defesa, afirmando sua inocência e explicando que acredita na ressurreição dos mortos. Félix decide não tomar uma decisão imediata sobre o caso de Paulo e o mantém sob custódia.
* Salmos 15:2 - "Aquele que anda na integridade, pratica a justiça e de coração fala a verdade". Paulo reivindica sua integridade diante do governador Félix, e sua defesa é baseada na verdade dos fatos.
* Provérbios 14:5 - "A testemunha fiel não mentirá, mas a falsa testemunha falará mentiras". Paulo é acusado pelos judeus e precisa defender-se diante de Félix com a verdade, enquanto os acusadores podem estar mentindo.
* Romanos 2:16 - "Deus julgará os segredos dos homens por meio de Jesus Cristo, conforme o meu evangelho". Paulo fala de sua crença na ressurreição dos mortos, um tema importante em sua defesa perante Félix.
* Romanos 12:19 - "Amados, nunca procurem vingar-se, mas deixem com Deus a ira, pois está escrito: "Minha é a vingança; eu retribuirei", diz o Senhor". Paulo não busca vingança contra seus acusadores, mas se defende com integridade diante de Félix, deixando o julgamento nas mãos de Deus.
* 1 Pedro 3:15 - "Estejam sempre preparados para responder a qualquer pessoa que pedir a razão da esperança que há em vocês". Paulo está preparado para responder a Félix e defender-se diante das acusações, apresentando a razão da sua esperança e fé.
****

[[v51-24-1]]

^<<v51-24-1,1>>^ Cinco dias depois, desceu o sumo sacerdote Ananias com alguns anciãos e Tertulo, advogado. Compareceram eles ante o governador para acusar Paulo.

[[v51-24-2]]

^<<v51-24-2,2>>^ Este foi citado e Tertulo começou a acusá-lo nestes termos: “Graças a ti nós gozamos de paz, e pela tua providência se têm corrigido muitos abusos em nossa nação.

[[v51-24-3]]

^<<v51-24-3,3>>^ Nós o reconhecemos em todo o tempo e lugar, excelentíssimo Félix, com toda a gratidão.

[[v51-24-4]]

^<<v51-24-4,4>>^ Mas, para não te enfadar por mais tempo, rogo-te que, na tua bondade, nos ouças por um momento.

[[v51-24-5]]

^<<v51-24-5,5>>^ Encontramos este homem, uma peste, um indivíduo que fomenta discórdia entre os judeus no mundo inteiro. É um dos líderes da seita dos nazarenos.

[[v51-24-6]]

^<<v51-24-6,6>>^ Tentou mesmo profanar o templo. Nós, porém, o prendemos.

[[v51-24-7]]

^<<v51-24-7,7>>^ (Quisemos julgá-lo segundo a nossa Lei, mas, sobrevindo o tribuno Lísias, no-lo tirou das mãos com grande violência, ordenando que os seus acusadores comparecessem diante de ti.)^&#42;1^

[[v51-24-8]]

^<<v51-24-8,8>>^ Tu mesmo, interrogando-o, poderás verificar todas essas coisas de que nós o acusamos”.

[[v51-24-9]]

^<<v51-24-9,9>>^ Os judeus o apoiaram, confirmando que as coisas de fato eram assim.

[[v51-24-10]]

^<<v51-24-10,10>>^ Depois disso, a um sinal do governador, Paulo respondeu: “Sabendo eu que há muitos anos és governador desta nação, é com confiança que farei a minha defesa.

[[v51-24-11]]

^<<v51-24-11,11>>^ Podes verificar que não há mais de doze dias que eu subi a Jerusalém para fazer minhas devoções.^&#42;1^

[[v51-24-12]]

^<<v51-24-12,12>>^ Não me acharam disputando com alguém, nem amotinando o povo, quer no templo, quer nas sinagogas, ou na cidade.

[[v51-24-13]]

^<<v51-24-13,13>>^ Nem tampouco te podem provar as coisas de que agora me acusam.

[[v51-24-14]]

^<<v51-24-14,14>>^ Reconheço na tua presença que, segundo a doutrina que eles chamam de sectária, sirvo a Deus de nossos pais, crendo em todas as coisas que estão escritas na Lei e nos profetas.

[[v51-24-15]]

^<<v51-24-15,15>>^ Tenho esperança em Deus, como também eles esperam, de que há de haver a ressurreição dos justos e dos pecadores.

[[v51-24-16]]

^<<v51-24-16,16>>^ Por isso, procuro ter sempre sem mácula a minha consciência diante de Deus e dos homens.

[[v51-24-17]]

^<<v51-24-17,17>>^ Depois de muitos anos (de ausência) vim trazer à minha nação esmolas e oferendas (rituais).

[[v51-24-18]]

^<<v51-24-18,18>>^ Nessa ocasião, acharam-me no templo, depois de uma purificação, sem aglomeração e sem tumulto.

[[v51-24-19]]

^<<v51-24-19,19>>^ Viram-me ali uns judeus vindos da Ásia, e estes é que deviam comparecer diante de ti e me acusar, se tivessem alguma queixa contra mim.

[[v51-24-20]]

^<<v51-24-20,20>>^ Ou digam estes aqui que crime terão achado em mim, quando eu compareci diante do Grande Conselho.

[[v51-24-21]]

^<<v51-24-21,21>>^ A não ser esta única frase que proferi em voz alta no meio deles: Por causa da ressurreição dos mortos é que sou julgado hoje diante de vós!”.

[[v51-24-22]]

^<<v51-24-22,22>>^ Félix conhecia bem esta religião e, adiando a questão, disse: “Quando descer o tribuno Lísias, então examinarei a fundo a vossa questão”.

[[v51-24-23]]

^<<v51-24-23,23>>^ Ordenou ao centurião que o guardasse e o tratasse com brandura, sem proibir que os seus o servissem.

[[v51-24-24]]

^<<v51-24-24,24>>^ Passados que foram alguns dias, veio Félix com sua mulher Drusila, que era judia. Chamou Paulo e ouvia-o falar da fé em Jesus Cristo.

[[v51-24-25]]

^<<v51-24-25,25>>^ Mas, como Paulo lhe falasse sobre a justiça, a castidade e o juízo futuro, Félix, todo atemorizado, disse-lhe: “Por ora, podes retirar-te. Na primeira ocasião, eu te chamarei.”

[[v51-24-26]]

^<<v51-24-26,26>>^ Esperava outrossim, ao mesmo tempo, que Paulo lhe desse algum dinheiro, pelo que o mandava chamar com frequência e se entretinha com ele.

[[v51-24-27]]

^<<v51-24-27,27>>^ Decorridos dois anos, Félix teve por sucessor a Pórcio Festo. Querendo, porém, agradar aos judeus, deixou Paulo na prisão.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-023.adoc#v51-23-0[&#60; Capítulo Anterior] | <<v51-24-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-025.adoc#v51-25-0[Próximo Capítulo &#62;]