include::./index.adoc[]

[[v51-5-0]]
=== Atos dos Apóstolos, 5
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Atos dos Apóstolos 5 apresenta a história de Ananias e Safira, que venderam uma propriedade e trouxeram apenas uma parte do dinheiro para os apóstolos, mentindo sobre o valor total. Pedro confronta Ananias, que morre imediatamente, e também Safira, que também morre após mentir para Pedro. O capítulo também descreve muitos milagres e curas realizados pelos apóstolos.
* Salmos 5:6: "Destruirás aqueles que falam mentiras; o SENHOR abominará o homem sanguinário e fraudulento." Esse versículo mostra a importância da honestidade e como Deus é contra a mentira, assim como é demonstrado na história de Ananias e Safira.
* Provérbios 12:22: "Os lábios mentirosos são abomináveis ao SENHOR, mas os que agem fielmente são o seu deleite." Novamente, a importância da honestidade é ressaltada nesse versículo, e o destino trágico de Ananias e Safira demonstra a consequência da desonestidade.
* Mateus 5:37: "Seja, porém, o vosso falar: Sim, sim; Não, não; pois o que passa daí, vem do Maligno." Esse versículo enfatiza a importância de falar a verdade e de não se envolver em enganos, assim como Ananias e Safira tentaram fazer.
* Colossenses 3:9: "Não mintais uns aos outros, uma vez que vos despistes do velho homem com os seus feitos," Esse versículo fala da necessidade de se livrar da velha natureza e do pecado, o que inclui a mentira.
* João 8:44: "Vós tendes por pai o Diabo e quereis satisfazer os desejos de vosso pai. Ele foi homicida desde o princípio e não se firmou na verdade, porque não há verdade nele. Quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira." Esse versículo mostra a relação entre a mentira e Satanás, que é chamado de pai da mentira. A história de Ananias e Safira é um exemplo dessa mentira e sua consequência trágica.
****

[[v51-5-1]]

^<<v51-5-1,1>>^ Um certo homem chamado Ananias, de comum acordo com sua mulher Safira, vendeu um campo

[[v51-5-2]]

^<<v51-5-2,2>>^ e, combinando com ela, reteve uma parte da quantia da venda. Levando apenas a outra parte, depositou-a aos pés dos apóstolos.

[[v51-5-3]]

^<<v51-5-3,3>>^ Pedro, porém, disse: “Ananias, por que tomou conta Satanás do teu coração, para que mentisses ao Espírito Santo e enganasses acerca do valor do campo?

[[v51-5-4]]

^<<v51-5-4,4>>^ Acaso não o podias conservar sem vendê-lo? E, depois de vendido, não podias livremente dispor dessa quantia? Por que imaginaste isso em teu coração? Não foi aos homens que mentiste, mas a Deus”.

[[v51-5-5]]

^<<v51-5-5,5>>^ Ao ouvir estas palavras, Ananias caiu morto. Apoderou-se grande terror de todos os que o ouviram.

[[v51-5-6]]

^<<v51-5-6,6>>^ Uns moços retiraram-no dali, levaram-no para fora e o enterraram.

[[v51-5-7]]

^<<v51-5-7,7>>^ Depois de umas três horas, entrou também sua mulher, nada sabendo do ocorrido.

[[v51-5-8]]

^<<v51-5-8,8>>^ Pedro perguntou-lhe: “Dize-me, mulher, foi por tanto que vendestes o vosso campo?”. Respondeu ela: “Sim, por esse preço”.

[[v51-5-9]]

^<<v51-5-9,9>>^ Replicou Pedro: “Por que combinastes para pôr à prova o Espírito do Senhor? Estão ali, à porta, os pés daqueles que sepultaram teu marido. Hão de levar-te também a ti”.

[[v51-5-10]]

^<<v51-5-10,10>>^ Imediatamente caiu aos seus pés e expirou. Entrando aqueles moços, acharam-na morta. Levaram-na para fora e a enterraram junto do seu marido.

[[v51-5-11]]

^<<v51-5-11,11>>^ Sobreveio grande pavor a toda a comunidade e a todos os que ouviram falar desse acontecimento.^&#42;1^

[[v51-5-12]]

^<<v51-5-12,12>>^ Enquanto isso, realizavam-se entre o povo pelas mãos dos apóstolos muitos milagres e prodígios. Reuniam-se eles todos, unânimes, no pórtico de Salomão.^&#42;1^

[[v51-5-13]]

^<<v51-5-13,13>>^ Dos outros ninguém ousava juntar-se a eles, mas o povo lhes tributava grandes louvores.

[[v51-5-14]]

^<<v51-5-14,14>>^ Cada vez mais aumentava a multidão dos homens e mulheres que acreditavam no Senhor.

[[v51-5-15]]

^<<v51-5-15,15>>^ De maneira que traziam os doentes para as ruas e punham-nos em leitos e macas, a fim de que, quando Pedro passasse, ao menos a sua sombra cobrisse alguns deles.

[[v51-5-16]]

^<<v51-5-16,16>>^ Também das cidades vizinhas de Jerusalém afluía muita gente, trazendo os enfermos e os atormentados por espíritos imundos, e todos eles eram curados.

[[v51-5-17]]

^<<v51-5-17,17>>^ Levantaram-se então o sumo sacerdote e seus partidários (isto é, a seita dos saduceus) cheios de inveja,

[[v51-5-18]]

^<<v51-5-18,18>>^ e deitaram as mãos nos apóstolos e meteram-nos na cadeia pública.

[[v51-5-19]]

^<<v51-5-19,19>>^ Mas um anjo do Senhor abriu de noite as portas do cárcere e, conduzindo-os para fora, disse-lhes:

[[v51-5-20]]

^<<v51-5-20,20>>^ “Ide, apresentai-vos no templo e pregai ao povo as palavras desta vida”.

[[v51-5-21]]

^<<v51-5-21,21>>^ Obedecendo a essa ordem, eles entraram no templo ao amanhecer e puseram-se a ensinar. Enquanto isso, o sumo sacerdote e os seus partidários reuniram-se e convocaram o Grande Conselho e todos os anciãos de Israel, e mandaram trazer os apóstolos do cárcere.

[[v51-5-22]]

^<<v51-5-22,22>>^ Dirigiram-se para lá os guardas, mas, ao abrirem o cárcere, não os encontraram, e voltaram a informar:

[[v51-5-23]]

^<<v51-5-23,23>>^ “Achamos o cárcere fechado com toda a segurança e os guardas de pé diante das portas, e, no entanto, abrindo-as, não achamos ninguém lá dentro”.

[[v51-5-24]]

^<<v51-5-24,24>>^ A essa notícia, os sumos sacerdotes e o chefe do templo ficaram perplexos e indagaram entre si sobre o que significava isso.

[[v51-5-25]]

^<<v51-5-25,25>>^ Mas, neste momento, alguém transmitiu-lhes esta notícia: “Aqueles homens que metestes no cárcere estão no templo ensinando o povo!”.

[[v51-5-26]]

^<<v51-5-26,26>>^ Foi então o comandante do templo com seus guardas e trouxe-os sem violência, porque temiam ser apedrejados pelo povo.

[[v51-5-27]]

^<<v51-5-27,27>>^ Trouxeram-nos e os introduziram no Grande Conselho, onde o sumo sacerdote os interrogou, dizendo:

[[v51-5-28]]

^<<v51-5-28,28>>^ “Expressamente vos ordenamos que não ensinásseis nesse nome. Não obstante isso, tendes enchido Jerusalém de vossa doutrina! Quereis fazer recair sobre nós o sangue deste homem?”.

[[v51-5-29]]

^<<v51-5-29,29>>^ Pedro e os apóstolos replicaram: “Importa obedecer antes a Deus do que aos homens.

[[v51-5-30]]

^<<v51-5-30,30>>^ O Deus de nossos pais ressuscitou Jesus, que vós matastes, suspendendo-o num madeiro.

[[v51-5-31]]

^<<v51-5-31,31>>^ Deus elevou-o pela mão direita como Príncipe e Salvador, a fim de dar a Israel o arrependimento e a remissão dos pecados.

[[v51-5-32]]

^<<v51-5-32,32>>^ Deste fato nós somos testemunhas, nós e o Espírito Santo, que Deus deu a todos aqueles que lhe obedecem”.

[[v51-5-33]]

^<<v51-5-33,33>>^ Ao ouvirem essas palavras, enfureceram-se e resolveram matá-los.

[[v51-5-34]]

^<<v51-5-34,34>>^ Levantou-se, porém, um membro do Grande Conselho. Era Gamaliel, um fariseu, doutor da Lei, respeitado por todo o povo.

[[v51-5-35]]

^<<v51-5-35,35>>^ Mandou que se retirassem aqueles homens por um momento, e então lhes disse: “Homens de Israel, considerai bem o que ides fazer com estes homens.

[[v51-5-36]]

^<<v51-5-36,36>>^ Faz algum tempo apareceu um certo Teudas, que se considerava um grande homem. A ele se associaram cerca de quatrocentos homens: foi morto e todos os seus partidários foram dispersados e reduzidos a nada.^&#42;1^

[[v51-5-37]]

^<<v51-5-37,37>>^ Depois deste, levantou-se Judas, o galileu, nos dias do recenseamento, e arrastou o povo consigo, mas também ele pereceu e todos quantos o seguiam foram dispersados.

[[v51-5-38]]

^<<v51-5-38,38>>^ Agora, pois, eu vos aconselho: não vos metais com estes homens. Deixai-os! Se o seu projeto ou a sua obra provém de homens, por si mesma se destruirá;

[[v51-5-39]]

^<<v51-5-39,39>>^ mas se provier de Deus, não podereis desfazê-la. Vós vos arriscaríeis a entrar em luta contra o próprio Deus”. Aceitaram o seu conselho.

[[v51-5-40]]

^<<v51-5-40,40>>^ Chamaram os apóstolos e mandaram açoitá-los. Ordenaram-lhes então que não pregassem mais em nome de Jesus, e os soltaram.

[[v51-5-41]]

^<<v51-5-41,41>>^ Eles saíram da sala do Grande Conselho, cheios de alegria, por terem sido achados dignos de sofrer afrontas pelo nome de Jesus.

[[v51-5-42]]

^<<v51-5-42,42>>^ E todos os dias não cessavam de ensinar e de pregar o Evangelho de Jesus Cristo no templo e pelas casas.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-004.adoc#v51-4-0[&#60; Capítulo Anterior] | <<v51-5-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-006.adoc#v51-6-0[Próximo Capítulo &#62;]