include::./index.adoc[]

[[v51-27-0]]
=== Atos dos Apóstolos, 27
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em Atos dos Apóstolos 27, é relatada a viagem do apóstolo Paulo a Roma, que sofre várias dificuldades e perigos durante a jornada devido às condições climáticas e ao naufrágio do navio em que estava. Os versículos a seguir estão relacionados aos temas abordados neste capítulo:
* Salmo 107:28-30: "Então eles clamaram ao SENHOR na sua angústia, e ele os livrou das suas aflições. Fez cessar a tempestade, e acalmaram-se as ondas. E alegrou-se com a bonança, e assim os guiou ao porto desejado." Este salmo fala sobre o poder de Deus em acalmar as tempestades e livrar as pessoas do perigo, o que se relaciona diretamente com a experiência de Paulo durante a tempestade no mar.
* 2 Coríntios 11:25: "Três vezes fui açoitado com varas, uma vez fui apedrejado, três vezes sofri naufrágio, uma noite e um dia passei no abismo." Paulo menciona em sua carta aos Coríntios que passou por três naufrágios, o que pode se referir à experiência relatada em Atos 27.
* Jonas 1:17: "O SENHOR, porém, enviou um grande peixe para que engolisse Jonas; e esteve Jonas três dias e três noites nas entranhas do peixe." Assim como Jonas ficou três dias e três noites dentro do grande peixe, Paulo e os outros tripulantes do navio ficaram à deriva no mar por três dias antes de serem resgatados.
* Hebreus 6:19: "A qual temos como âncora da alma, segura e firme, e que penetra até ao interior do véu." A âncora é um símbolo de segurança e estabilidade, que pode ser relacionado à ideia de que a fé em Deus pode nos sustentar e nos dar forças em meio às adversidades.
* Isaías 43:2: "Quando passares pelas águas, eu serei contigo; quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti." Este versículo enfatiza a promessa de Deus de estar conosco em meio aos perigos e dificuldades, protegendo-nos e nos guiando em segurança até o outro lado.
****

[[v51-27-1]]

^<<v51-27-1,1>>^ Logo que foi determinado que embarcássemos para a Itália, Paulo foi entregue com outros presos a um centurião da coorte Augusta, chamado Júlio.

[[v51-27-2]]

^<<v51-27-2,2>>^ Embarcamos num navio de Adramito que devia costear as terras da Ásia, e levantamos âncora. Em nossa companhia estava Aristarco, macedônio de Tessalônica.

[[v51-27-3]]

^<<v51-27-3,3>>^ No dia seguinte, fazendo escala em Sidônia, Júlio, usando de bondade com Paulo, permitiu-lhe ir ver os seus amigos e prover-se do que havia de necessário.

[[v51-27-4]]

^<<v51-27-4,4>>^ Dali, fazendo-nos ao mar, fomos navegando perto das costas de Chipre, por nos serem contrários os ventos.

[[v51-27-5]]

^<<v51-27-5,5>>^ Tendo atravessado o mar da Cilícia e da Panfília, chegamos a Mira, cidade da Lícia.

[[v51-27-6]]

^<<v51-27-6,6>>^ O centurião encontrou ali um navio de Alexandria, que rumava para a Itália, e fez-nos passar para ele.

[[v51-27-7]]

^<<v51-27-7,7>>^ Por muitos dias navegamos lentamente e com dificuldade até diante de Cnido, onde o vento não nos permitiu aportar.

[[v51-27-8]]

^<<v51-27-8,8>>^ Fomos então costeando ao sul da ilha de Creta, junto ao cabo Salmona. Navegando com dificuldade ao longo da costa, chegamos afinal a um lugar, a que chamam Bons Portos, perto do qual está a cidade de Lasaia.

[[v51-27-9]]

^<<v51-27-9,9>>^ Passara o tempo – já havia passado a época do jejum – e a navegação se tornava perigosa. Paulo advertiu-os:^&#42;1^

[[v51-27-10]]

^<<v51-27-10,10>>^ “Amigos, vejo que a navegação não se fará sem perigo e sem graves danos, não somente ao navio e à sua carga, mas ainda às nossas vidas”.

[[v51-27-11]]

^<<v51-27-11,11>>^ O centurião, porém, dava mais crédito ao piloto e ao mestre do que ao que Paulo dizia.

[[v51-27-12]]

^<<v51-27-12,12>>^ O porto era impróprio para passar o inverno, pelo que a maior parte deles foi de parecer que se retornasse ao mar, na esperança de chegar a Fenice, para passar ali o inverno, por ser esse um porto de Creta, abrigado dos ventos do Sudeste e do Nordeste.

[[v51-27-13]]

^<<v51-27-13,13>>^ Soprava então brandamente o vento sul. Julgavam poder executar os seus planos. Levantaram a âncora e foram costeando de perto a ilha de Creta.

[[v51-27-14]]

^<<v51-27-14,14>>^ Mas, não muito depois, veio do lado da ilha um tufão chamado Euroaquilão.

[[v51-27-15]]

^<<v51-27-15,15>>^ Sem poder resistir à ventania, o navio foi arrebatado e deixamo-nos arrastar.

[[v51-27-16]]

^<<v51-27-16,16>>^ Impelidos rapidamente para uma pequena ilha chamada Cauda, conseguimos, com muito esforço, recolher o batel.

[[v51-27-17]]

^<<v51-27-17,17>>^ Içaram-no e, depois, como meio de segurança, cingiram o navio com cabos. Então, temendo encalhar em Sirte, arriaram as velas e entregaram-se à mercê dos ventos.^&#42;1^

[[v51-27-18]]

^<<v51-27-18,18>>^ No dia seguinte, sendo a tempestade ainda mais violenta, atiraram fora a carga.

[[v51-27-19]]

^<<v51-27-19,19>>^ No terceiro dia, atiramos para fora com as nossas próprias mãos os acessórios do navio.

[[v51-27-20]]

^<<v51-27-20,20>>^ Ora, não aparecendo por muitos dias nem sol nem estrelas e sendo batidos por forte tempestade, tínhamos por fim perdido toda a esperança de sermos salvos.

[[v51-27-21]]

^<<v51-27-21,21>>^ Desde muito tempo ninguém havia comido nada. Paulo levantou-se no meio deles e disse: “Amigos, deveras devíeis ter-me atendido e não ter saído de Creta, e assim evitar esse perigo e essas perdas.

[[v51-27-22]]

^<<v51-27-22,22>>^ Agora, porém, vos admoesto a que tenhais coragem, pois não perecerá nenhum de vós, mas somente o navio.

[[v51-27-23]]

^<<v51-27-23,23>>^ Esta noite apareceu-me um anjo de Deus, a quem pertenço e a quem sirvo, o qual me disse:

[[v51-27-24]]

^<<v51-27-24,24>>^ Não temas, Paulo. É necessário que compareças diante de César. Deus deu-te todos os que navegam contigo.

[[v51-27-25]]

^<<v51-27-25,25>>^ Por isso, amigos, coragem! Eu confio em Deus que há de acontecer como me foi dito.

[[v51-27-26]]

^<<v51-27-26,26>>^ Encalharemos em uma ilha.

[[v51-27-27]]

^<<v51-27-27,27>>^ Já estávamos na décima quarta noite, pelo mar Adriático, quando, pela meia-noite, os marinheiros pressentiram que estavam perto de alguma terra.^&#42;1^

[[v51-27-28]]

^<<v51-27-28,28>>^ Então, atirando a sonda, perceberam que a profundidade era de vinte braças. Depois, um pouco mais adiante, viram que era de quinze braças.

[[v51-27-29]]

^<<v51-27-29,29>>^ Temendo que déssemos em algum recife, lançaram quatro âncoras da popa, esperando ansiosos que amanhecesse o dia.

[[v51-27-30]]

^<<v51-27-30,30>>^ Imediatamente, os marinheiros procuraram fugir e, sob o pretexto de largar as âncoras da proa, lançaram o bote ao mar.

[[v51-27-31]]

^<<v51-27-31,31>>^ Paulo disse ao centurião e aos soldados: “Se estes homens não permanecerem no navio, não podereis salvar-vos”.

[[v51-27-32]]

^<<v51-27-32,32>>^ Os soldados cortaram, então, os cabos do bote e deixaram-no cair.

[[v51-27-33]]

^<<v51-27-33,33>>^ Enquanto ia amanhecendo, Paulo encorajou a todos que comessem alguma coisa, e disse: “Já faz hoje catorze dias que estais em jejum, sem comer nada.

[[v51-27-34]]

^<<v51-27-34,34>>^ Rogo-vos que comais alguma coisa, no interesse de vossa vida, porque nem um cabelo da cabeça de alguém de vós perecerá”.

[[v51-27-35]]

^<<v51-27-35,35>>^ Tendo dito isso, tomou do pão, pronunciou uma bênção na presença de todos e, depois de parti-lo, começou a comer.^&#42;1^

[[v51-27-36]]

^<<v51-27-36,36>>^ Com isso, todos cobraram ânimo e puseram-se igualmente a comer.

[[v51-27-37]]

^<<v51-27-37,37>>^ No navio éramos ao todo duzentas e setenta e seis pessoas.

[[v51-27-38]]

^<<v51-27-38,38>>^ Depois de terem comido à vontade, aliviaram o navio, atirando o trigo ao mar.

[[v51-27-39]]

^<<v51-27-39,39>>^ Afinal, clareou o dia. Os marinheiros não reconheceram a terra, mas viram uma enseada com uma praia, na qual tencionavam encalhar o navio, caso o pudessem.

[[v51-27-40]]

^<<v51-27-40,40>>^ Levantaram as âncoras e largaram ao mesmo tempo as amarras dos lemes. Desfraldaram ao vento a vela mestra e rumaram para a praia.

[[v51-27-41]]

^<<v51-27-41,41>>^ Mas deram numa língua de terra, e o navio encalhou aí. A proa, encalhada, permanecia imóvel, ao mesmo tempo que a popa se abria com a força do mar.

[[v51-27-42]]

^<<v51-27-42,42>>^ Os soldados tencionavam matar os presos, por temerem que algum deles fugisse a nado.

[[v51-27-43]]

^<<v51-27-43,43>>^ O centurião, porém, querendo salvar Paulo, impediu que o fizessem e ordenou que aqueles que pudessem nadar fossem os primeiros a lançar-se ao mar e alcançar a terra.

[[v51-27-44]]

^<<v51-27-44,44>>^ Os demais, uns atingiram a terra em tábuas, outros em cima dos destroços do navio. Desse modo, todos conseguiram chegar à terra sãos e salvos.

'''

xref:051-atos-dos-apostolos/051-atos-dos-apostolos-026.adoc#v51-26-0[&#60; Capítulo Anterior] | <<v51-27-0,Topo>> | xref:051-atos-dos-apostolos/051-atos-dos-apostolos-028.adoc#v51-28-0[Próximo Capítulo &#62;]