include::./index.adoc[]

[[v60-2-0]]
=== II Tessalonicenses, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* No capítulo 2 de 2 Tessalonicenses, Paulo aborda a questão da volta de Cristo e o surgimento do homem do pecado, um líder enganador que se opõe a Deus e se coloca acima de tudo o que é considerado divino ou sagrado. Ele adverte os tessalonicenses a não se deixarem enganar por falsas doutrinas ou sinais e exorta-os a permanecerem firmes na verdade do evangelho. Seguem cinco versículos que se relacionam com os temas abordados em 2 Tessalonicenses 2:
* Mateus 24:23-26: "Se, então, alguém lhes disser: 'Vejam, aqui está o Cristo!' ou: 'Ali está ele!', não acreditem. Pois surgirão falsos cristos e falsos profetas que realizarão grandes sinais e maravilhas para, se possível, enganar até os eleitos. Vejam que eu os avisei antecipadamente. Portanto, se alguém lhes disser: 'Ele está no deserto!', não saiam; ou: 'Ali está ele!', não acreditem." Esse versículo alerta sobre a existência de falsos cristos e profetas que realizam sinais e maravilhas para enganar as pessoas, um tema que também é abordado em 2 Tessalonicenses 2.
* Mateus 24:42: "Portanto, vigiem, porque vocês não sabem em que dia virá o seu Senhor." Esse versículo enfatiza a necessidade de vigilância e preparação para a volta de Cristo, um tema que é abordado em 2 Tessalonicenses 2.
* 2 Pedro 2:1: "No passado surgiram falsos profetas no meio do povo, como também surgirão entre vocês falsos mestres. Estes introduzirão secretamente heresias destruidoras, chegando a negar o Soberano que os resgatou, trazendo sobre si mesmos repentina destruição." Esse versículo alerta sobre a existência de falsos mestres que introduzem doutrinas destruidoras e negam a soberania de Deus, um tema que é abordado em 2 Tessalonicenses 2.
* 1 João 4:1: "Amados, não creiam em qualquer espírito, mas examinem os espíritos para ver se eles procedem de Deus, porque muitos falsos profetas têm saído pelo mundo." Esse versículo exorta os cristãos a examinar cuidadosamente as doutrinas e os ensinamentos que ouvem, a fim de discernir se são de Deus ou de falsos profetas, um tema que também é abordado em 2 Tessalonicenses 2.
* 1 Tessalonicenses 5:21: "Examinem tudo e fiquem com o que é bom." Esse versículo enfatiza a importância de examinar e avaliar as doutrinas e os ensinamentos à luz da verdade do evangelho, um tema que também é abordado em 2 Tessalonicenses 2.
****

[[v60-2-1]]

^<<v60-2-1,1>>^ No que diz respeito à vinda de nosso Senhor Jesus Cristo e nossa reunião com ele, rogamo-vos, irmãos,

[[v60-2-2]]

^<<v60-2-2,2>>^ não vos deixeis facilmente perturbar o espírito e alarmar-vos, nem por alguma pretensa revelação nem por palavra ou carta tidas como procedentes de nós e que vos afirmassem estar iminente o dia do Senhor.^&#42;1^

[[v60-2-3]]

^<<v60-2-3,3>>^ Ninguém de modo algum vos engane. Porque primeiro deve vir a apostasia, e deve manifestar-se o homem da iniquidade, o filho da perdição,^&#42;1^

[[v60-2-4]]

^<<v60-2-4,4>>^ o adversário, aquele que se levanta contra tudo o que é divino e sagrado, a ponto de tomar lugar no Templo de Deus, e apresentar-se como se fosse Deus.

[[v60-2-5]]

^<<v60-2-5,5>>^ Não vos lembrais de que vos dizia estas coisas, quando estava ainda convosco?

[[v60-2-6]]

^<<v60-2-6,6>>^ Agora, sabeis perfeitamente que algo o detém, de modo que ele só se manifestará a seu tempo.^&#42;1^

[[v60-2-7]]

^<<v60-2-7,7>>^ Porque o mistério da iniquidade já está em ação, apenas esperando o desaparecimento daquele que o detém.

[[v60-2-8]]

^<<v60-2-8,8>>^ Então, o tal ímpio se manifestará. Mas o Senhor Jesus o destruirá com o sopro de sua boca e o aniquilará com o resplendor da sua vinda.^&#42;1^

[[v60-2-9]]

^<<v60-2-9,9>>^ A manifestação do ímpio será acompanhada, graças ao poder de Satanás, de toda a sorte de portentos, sinais e prodígios enganadores.

[[v60-2-10]]

^<<v60-2-10,10>>^ Ele usará de todas as seduções do mal com aqueles que se perdem, por não terem cultivado o amor à verdade que os teria podido salvar.

[[v60-2-11]]

^<<v60-2-11,11>>^ Por isso, Deus lhes enviará um poder que os enganará e os induzirá a acreditar no erro.

[[v60-2-12]]

^<<v60-2-12,12>>^ Desse modo, serão julgados e condenados todos os que não deram crédito à verdade, mas consentiram no mal.

[[v60-2-13]]

^<<v60-2-13,13>>^ Nós, porém, sentimo-nos na obrigação de incessantemente dar graças a Deus a respeito de vós, irmãos queridos de Deus, porque desde o princípio vos escolheu Deus para vos dar a salvação, pela santificação do Espírito e pela fé na verdade.

[[v60-2-14]]

^<<v60-2-14,14>>^ E pelo anúncio do nosso Evangelho vos chamou para tomardes parte na glória de nosso Senhor Jesus Cristo.

[[v60-2-15]]

^<<v60-2-15,15>>^ Assim, pois, irmãos, ficai firmes e conservai os ensinamentos que de nós aprendestes, seja por palavras, seja por carta nossa.

[[v60-2-16]]

^<<v60-2-16,16>>^ Nosso Senhor Jesus Cristo e Deus, nosso Pai, que nos amou e nos deu consolação eterna e boa esperança pela sua graça, consolem os vossos corações e os confirmem para toda boa obra e palavra!

'''

xref:060-ii-tessalonicenses/060-ii-tessalonicenses-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-ii-tessalonicenses/060-ii-tessalonicenses-003.adoc#v60-3-0[Próximo Capítulo &#62;]