include::./index.adoc[]

[[v27-10-0]]
=== Sabedoria, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Sabedoria 10 narra a história de como a sabedoria guiou e protegeu os justos ao longo da história de Israel, desde Adão até Moisés. O capítulo enfatiza a importância da sabedoria para a vida virtuosa e para a busca da justiça.
* Provérbios 2:6 - "Porque o Senhor dá a sabedoria, e da sua boca vem o conhecimento e o entendimento". Este versículo destaca que a sabedoria vem de Deus e é necessária para a vida justa.
* Eclesiastes 2:26 - "Porque ao homem que lhe é agradável, Deus dá sabedoria, e conhecimento e alegria; mas ao pecador dá trabalho, para que ele ajunte e amontoe, a fim de dá-lo ao que é agradável a Deus". Esse versículo enfatiza a importância da sabedoria para a felicidade e a bênção de Deus na vida das pessoas.
* Provérbios 16:16 - "Quanto melhor é adquirir a sabedoria do que o ouro! E quanto mais excelente é adquirir a prudência do que a prata!" Este versículo destaca a superioridade da sabedoria sobre a riqueza material.
* Tiago 1:5 - "E se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não censura, e ser-lhe-á dada." Este versículo enfatiza que Deus é o doador de sabedoria e que as pessoas devem pedir a Ele quando precisam dela.
* Provérbios 3:13 - "Bem-aventurado o homem que acha sabedoria, e o homem que adquire conhecimento". Este versículo destaca a felicidade e a bênção que vêm com a busca e a aquisição da sabedoria.
****

[[v27-10-1]]

^<<v27-10-1,1>>^ O primeiro homem, o pai do mundo, que foi criado sozinho, foi a sabedoria que cuidou dele, tirou-o de seu próprio pecado,^&#42;1^

[[v27-10-2]]

^<<v27-10-2,2>>^ e deu-lhe o poder de reinar sobre todas as coisas.

[[v27-10-3]]

^<<v27-10-3,3>>^ E porque o perverso, na sua ira, dela se afastou, pereceu depois de seu furor fratricida.^&#42;1^

[[v27-10-4]]

^<<v27-10-4,4>>^ E estando a terra submersa por causa dele pelo dilúvio, a sabedoria de novo o salvou, conduzindo o justo num lenho sem valor.^&#42;1^

[[v27-10-5]]

^<<v27-10-5,5>>^ E quando as nações unânimes caíram no mal, foi ela que distinguiu o justo, o manteve irrepreensível diante de Deus, e lhe deu a força para vencer sua ternura pelo seu filho.^&#42;1^

[[v27-10-6]]

^<<v27-10-6,6>>^ Foi ela que, quando do aniquilamento dos ímpios, salvou o justo, subtraindo-o ao fogo que descera sobre a Pentápole,^&#42;1^

[[v27-10-7]]

^<<v27-10-7,7>>^ cuja perversidade ainda no presente é testemunhada por uma terra fumegante e deserta, onde as árvores carregam frutos incapazes de amadurecer, e onde está erigida uma coluna de sal, memorial de uma alma incrédula.

[[v27-10-8]]

^<<v27-10-8,8>>^ Porque aqueles que desprezaram a sabedoria, não somente se prejudicaram em ignorar o bem, mas ainda deixaram aos homens um testemunho de sua loucura, para que seus pecados não fossem esquecidos.

[[v27-10-9]]

^<<v27-10-9,9>>^ Quanto aos que a honram, a sabedoria os liberta de sofrimentos;

[[v27-10-10]]

^<<v27-10-10,10>>^ foi ela que guiou por caminhos retos o justo que fugia à ira de seu irmão; mostrou-lhe o Reino de Deus, e deu-lhe o conhecimento das coisas santas; ajudou-o nos seus trabalhos, e fez frutificar seus esforços;^&#42;1^

[[v27-10-11]]

^<<v27-10-11,11>>^ cuidou dele contra ávidos opressores e o fez conquistar riquezas;

[[v27-10-12]]

^<<v27-10-12,12>>^ ela o protegeu contra seus inimigos e o defendeu dos que lhe armavam ciladas; e, no duro combate, deu-lhe vitória, a fim de que ele soubesse quanto a piedade é mais forte que tudo.

[[v27-10-13]]

^<<v27-10-13,13>>^ Ela não abandonou o justo vendido, mas preservou-o do pecado.^&#42;1^

[[v27-10-14]]

^<<v27-10-14,14>>^ Desceu com ele à prisão, e não o abandonou nas suas cadeias, até que lhe trouxe o cetro do reino e o poder sobre os que o tinham oprimido; revelou-lhe a mentira de seus acusadores, e conferiu-lhe uma glória eterna.

[[v27-10-15]]

^<<v27-10-15,15>>^ Foi ela que livrou das nações que tiranizavam o povo santo e a raça irrepreensível;

[[v27-10-16]]

^<<v27-10-16,16>>^ entrou na alma do servo de Deus, e se opôs, com sinais e prodígios, a reis temíveis.^&#42;1^

[[v27-10-17]]

^<<v27-10-17,17>>^ Deu aos santos o galardão de seus trabalhos, conduziu-os por um caminho miraculoso; durante o dia serviu-lhes de proteção, e deu-lhes a luz dos astros durante a noite.^&#42;1^

[[v27-10-18]]

^<<v27-10-18,18>>^ Fê-los atravessar o mar Vermelho, e deu-lhes passagem através da massa das águas,

[[v27-10-19]]

^<<v27-10-19,19>>^ ao passo que engoliu seus inimigos, e depois os tirou das profundezas do abismo.

[[v27-10-20]]

^<<v27-10-20,20>>^ Também os justos, depois de despojados os ímpios, celebraram, Senhor, vosso santo nome, e louvaram, unidos num só coração, vossa mão protetora,

[[v27-10-21]]

^<<v27-10-21,21>>^ porque a sabedoria abriu a boca aos mudos, e tornou eloquente a língua das crianças.

'''

xref:027-sabedoria/027-sabedoria-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-sabedoria/027-sabedoria-011.adoc#v27-11-0[Próximo Capítulo &#62;]