include::./index.adoc[]

[[v27-14-0]]
=== Sabedoria, 14
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Sabedoria 14 trata da loucura dos povos que adoram ídolos e dos males que isso causa, enquanto exalta a sabedoria em Deus. Aqui estão cinco versículos relacionados com os temas do capítulo:
* Isaías 44:20: "Ele se alimenta de cinzas, o coração enganoso o desvia; ele não consegue salvar-se nem dizer: 'Não é mentira o que tenho nas mãos?'" Este versículo descreve a futilidade da adoração de ídolos e como isso leva à enganação e à falta de salvação.
* Salmos 96:5: "Todos os deuses dos povos são ídolos, mas o Senhor fez os céus." Este versículo destaca a superioridade de Deus sobre os ídolos e aponta para a verdadeira adoração a Ele.
* Isaías 2:18: "E todos os ídolos desaparecerão completamente." Aqui, o profeta Isaías fala do fim dos ídolos e como eles serão deixados para trás quando a verdadeira adoração a Deus for estabelecida.
* Atos 17:29: "Sendo, pois, descendência de Deus, não devemos pensar que a Divindade é semelhante ao ouro, à prata, ou à pedra, esculpida pela arte e imaginação do homem." O apóstolo Paulo fala aos gregos em Atenas sobre a verdadeira natureza de Deus e como Ele não pode ser representado por ídolos feitos por mãos humanas.
* 1 Coríntios 10:19-20: "Será que quero dizer com isso que o sacrifício oferecido aos ídolos é alguma coisa? Ou que um ídolo é alguma coisa? Não! Mas digo que aquilo que os pagãos sacrificam, eles sacrificam aos demônios, e não a Deus. E eu não quero que vocês tenham comunhão com os demônios." O apóstolo Paulo adverte os cristãos em Corinto sobre a perigosa adoração de ídolos e como ela pode levar à comunhão com demônios em vez de Deus.
****

[[v27-14-1]]

^<<v27-14-1,1>>^ Outro, por sua vez, que quer navegar e se prepara para atravessar as impetuosas ondas, invoca um madeiro de pior qualidade que o navio que o leva;^&#42;1^

[[v27-14-2]]

^<<v27-14-2,2>>^ porque o desejo do lucro inventou o navio, e uma hábil sabedoria dirigiu sua construção.

[[v27-14-3]]

^<<v27-14-3,3>>^ Mas sois vós, Pai, que o governais pela vossa Providência, porque, se abristes caminho, mesmo no mar, e uma rota segura no meio das ondas –

[[v27-14-4]]

^<<v27-14-4,4>>^ mostrando por aí que vós podeis tirar do perigo aquele que as afronta mesmo sem meios –,^&#42;1^

[[v27-14-5]]

^<<v27-14-5,5>>^ quereis, entretanto, que não sejam inúteis as obras de vossa sabedoria. Por isso, os homens confiam a própria vida a um pouco de madeira e atravessam em segurança as ondas num navio.

[[v27-14-6]]

^<<v27-14-6,6>>^ Assim, com efeito, quando na origem dos tempos fizestes perecer gigantes orgulhosos, a esperança do universo, refugiando-se num barco, que vossa mão governava, conservou para o mundo o germe de uma geração.^&#42;1^

[[v27-14-7]]

^<<v27-14-7,7>>^ Porque é bendito o madeiro pelo qual se opera a justiça,

[[v27-14-8]]

^<<v27-14-8,8>>^ mas maldito é o ídolo, ele e o que o fez; este porque o formou, aquele porque, sendo corruptível, leva o nome de deus.

[[v27-14-9]]

^<<v27-14-9,9>>^ Com efeito, Deus odeia tanto o ímpio quanto sua impiedade,

[[v27-14-10]]

^<<v27-14-10,10>>^ e a obra sofrerá o mesmo castigo que o autor.

[[v27-14-11]]

^<<v27-14-11,11>>^ Este é o motivo por que também os ídolos das nações serão julgados: na criação de Deus, eles se tornaram uma abominação, objetos de escândalo para os homens, e laços para os pés dos insensatos.^&#42;1^

[[v27-14-12]]

^<<v27-14-12,12>>^ Foi pela idealização dos ídolos que começou a apostasia, e sua invenção foi a perda dos humanos.^&#42;1^

[[v27-14-13]]

^<<v27-14-13,13>>^ Eles não existiam no princípio e não durarão para sempre;

[[v27-14-14]]

^<<v27-14-14,14>>^ a vaidade dos homens os introduziu no mundo. E, por causa disso, Deus decidiu a sua destruição para breve.

[[v27-14-15]]

^<<v27-14-15,15>>^ Um pai aflito por um luto prematuro, tendo mandado fazer a imagem do filho, tão cedo arrebatado, honrou, em seguida, como a um deus aquele que não passava de um morto, e transmitiu aos seus certos ritos secretos e cerimônias.

[[v27-14-16]]

^<<v27-14-16,16>>^ Este costume ímpio, tendo-se firmado com o tempo, foi depois observado como lei.

[[v27-14-17]]

^<<v27-14-17,17>>^ Foi também em consequência das ordens dos príncipes que se adoraram imagens esculpidas, porque aqueles que não podiam honrar pessoalmente, porque moravam longe deles, fizeram representar o que se achava distante, e expuseram publicamente a imagem do rei venerado, a fim de lisonjeá-lo de longe com seu zelo, como se estivesse presente.

[[v27-14-18]]

^<<v27-14-18,18>>^ Isto contribuiu ainda para o estabelecimento deste culto, mesmo entre os que não conheciam o rei; foi a ambição do artista

[[v27-14-19]]

^<<v27-14-19,19>>^ que, talvez, querendo agradar ao soberano, deu-lhe, por sua arte, a semelhança do belo;

[[v27-14-20]]

^<<v27-14-20,20>>^ e a multidão, seduzida pelo encanto da obra, em breve tomou por deus aquele que tinham honrado como homem.

[[v27-14-21]]

^<<v27-14-21,21>>^ E isto foi uma cilada para a humanidade: os homens, sujeitando-se à lei da desgraça e da tirania, deram à pedra e à madeira o nome incomunicável.^&#42;1^

[[v27-14-22]]

^<<v27-14-22,22>>^ Como se não bastasse terem errado acerca do conhecimento de Deus, embora passando a vida numa longa luta de ignorância, eles dão o nome de paz a um estado tão infeliz.

[[v27-14-23]]

^<<v27-14-23,23>>^ Com efeito, sacrificando seus filhos, celebrando mistérios ocultos, ou entregando-se a orgias desenfreadas de religiões exóticas,

[[v27-14-24]]

^<<v27-14-24,24>>^ eles já não guardam a honestidade nem na vida nem no casamento, mas um faz desaparecer o outro pelo ardil, ou o ultraja pelo adultério.

[[v27-14-25]]

^<<v27-14-25,25>>^ Tudo está numa confusão completa – sangue, homicídio, furto, fraude, corrupção, deslealdade, revolta, perjúrio,

[[v27-14-26]]

^<<v27-14-26,26>>^ perseguição dos bons, esquecimento dos benefícios, contaminação das almas, perversão dos sexos, instabilidade das uniões, adultérios e impudicícias –

[[v27-14-27]]

^<<v27-14-27,27>>^ porque o culto de inomináveis ídolos é o começo, a causa e o fim de todo o mal.

[[v27-14-28]]

^<<v27-14-28,28>>^ (Seus adeptos) incitam o prazer até a loucura, ou fazem vaticínios falsos, ou vivem na injustiça, ou, sem escrúpulo, juram falso,

[[v27-14-29]]

^<<v27-14-29,29>>^ porque, confiando em ídolos inanimados, esperam não ser punidos por má-fé.

[[v27-14-30]]

^<<v27-14-30,30>>^ Contudo, o castigo os atingirá por duplo motivo: porque eles desconheceram a Deus, afeiçoando-se aos ídolos, e porque são culpados, por desprezo à santidade da religião, de ter feito juramentos enganadores.

[[v27-14-31]]

^<<v27-14-31,31>>^ Pois não é o poder dos ídolos invocados, mas o castigo reservado ao pecador, que sempre persegue as faltas dos maus.

'''

xref:027-sabedoria/027-sabedoria-013.adoc#v27-13-0[&#60; Capítulo Anterior] | <<v27-14-0,Topo>> | xref:027-sabedoria/027-sabedoria-015.adoc#v27-15-0[Próximo Capítulo &#62;]