include::./index.adoc[]

[[v27-9-0]]
=== Sabedoria, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O livro da Sabedoria 9 apresenta o Rei Salomão fazendo uma oração pedindo a Deus sabedoria e discernimento para governar seu povo. Salomão reconhece sua limitação humana e sua necessidade de sabedoria divina para ser um bom governante. Abaixo estão cinco versículos relacionados aos temas abordados em Sabedoria 9:
* Provérbios 9:10: "O temor do Senhor é o princípio da sabedoria, e o conhecimento do Santo é prudência." Esse versículo destaca a importância do temor do Senhor como base para a sabedoria, reforçando a necessidade da busca pela sabedoria divina.
* Provérbios 2:6: "Porque o Senhor dá a sabedoria; da sua boca é que vem o conhecimento e o entendimento." Esse versículo destaca a fonte da sabedoria, que vem do Senhor e é acessível através da busca por Ele.
* Provérbios 3:13: "Feliz é o homem que acha sabedoria, e o homem que adquire conhecimento." Esse versículo destaca a importância de buscar e adquirir sabedoria, como um bem valioso.
* Provérbios 4:7: "A sabedoria é a coisa principal; adquire, pois, a sabedoria; sim, com tudo o que possuis adquire o entendimento." Esse versículo destaca a supremacia da sabedoria e encoraja a busca constante por ela.
* Provérbios 8:17: "Eu amo os que me amam, e os que cedo me buscarem, me acharão." Esse versículo destaca a disposição de Deus em conceder sabedoria e a importância da busca precoce por ela.
****

[[v27-9-1]]

^<<v27-9-1,1>>^ “Deus de nossos pais, e Senhor de misericórdia, que todas as coisas criastes pela vossa palavra,

[[v27-9-2]]

^<<v27-9-2,2>>^ e que, por vossa sabedoria, formastes o homem para ser o senhor de todas as vossas criaturas,

[[v27-9-3]]

^<<v27-9-3,3>>^ governar o mundo na santidade e na justiça, e proferir seu julgamento na retidão de sua alma,

[[v27-9-4]]

^<<v27-9-4,4>>^ dai-me a sabedoria que partilha do vosso trono, e não me rejeiteis como indigno de ser um de vossos filhos.

[[v27-9-5]]

^<<v27-9-5,5>>^ Sou, com efeito, vosso servo e filho de vossa serva, um homem fraco, cuja existência é breve, incapaz de compreender vosso julgamento e vossas leis;^&#42;1^

[[v27-9-6]]

^<<v27-9-6,6>>^ porque qualquer homem, mesmo perfeito, entre os homens, não será nada, se lhe falta a sabedoria que vem de vós.

[[v27-9-7]]

^<<v27-9-7,7>>^ Ora, vós me escolhestes para ser rei de vosso povo e juiz de vossos filhos e vossas filhas.

[[v27-9-8]]

^<<v27-9-8,8>>^ Vós me ordenastes construir um templo na vossa montanha santa e um altar na cidade em que habitais: imagem da sagrada habitação que preparastes desde o princípio.^&#42;1^

[[v27-9-9]]

^<<v27-9-9,9>>^ Mas ao vosso lado está a sabedoria que conhece vossas obras; ela estava presente quando fizestes o mundo, ela sabe o que vos é agradável, e o que se conforma às vossas ordens.

[[v27-9-10]]

^<<v27-9-10,10>>^ Fazei-a, pois, descer de vosso santo céu, e enviai-a do trono de vossa glória, para que, junto de mim, tome parte em meus trabalhos, e para que eu saiba o que vos agrada.

[[v27-9-11]]

^<<v27-9-11,11>>^ Com efeito, ela sabe e conhece todas as coisas; prudentemente guiará meus passos e me protegerá no brilho de sua glória.

[[v27-9-12]]

^<<v27-9-12,12>>^ Assim, minhas obras vos serão agradáveis; governarei vosso povo com justiça, e serei digno do trono de meu pai.

[[v27-9-13]]

^<<v27-9-13,13>>^ Que homem, pois, pode conhecer os desígnios de Deus, e penetrar nas determinações do Senhor?

[[v27-9-14]]

^<<v27-9-14,14>>^ Tímidos são os pensamentos dos mortais, e incertas as nossas concepções;

[[v27-9-15]]

^<<v27-9-15,15>>^ porque o corpo corruptível torna pesada a alma, e a morada terrestre oprime o espírito carregado de cuidados.

[[v27-9-16]]

^<<v27-9-16,16>>^ Mal podemos compreender o que está sobre a terra, dificilmente encontramos o que temos ao alcance da mão. Quem, portanto, pode descobrir o que se passa no céu?

[[v27-9-17]]

^<<v27-9-17,17>>^ E quem conhece vossas intenções, se vós não lhe dais a sabedoria, e se do mais alto dos céus vós não lhe enviais vosso Espírito Santo?

[[v27-9-18]]

^<<v27-9-18,18>>^ Assim se tornaram direitas as veredas dos que estão na terra; os homens aprenderam as coisas que vos agradam e pela sabedoria foram salvos.”^&#42;1^

'''

xref:027-sabedoria/027-sabedoria-008.adoc#v27-8-0[&#60; Capítulo Anterior] | <<v27-9-0,Topo>> | xref:027-sabedoria/027-sabedoria-010.adoc#v27-10-0[Próximo Capítulo &#62;]