include::./index.adoc[]

[[v27-13-0]]
=== Sabedoria, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 13 do livro de Sabedoria aborda a tolice da idolatria e como ela se opõe à adoração ao verdadeiro Deus. O autor ressalta que a natureza é uma evidência clara da existência de um Criador e que aqueles que se voltam para ídolos estão cometendo um grave erro. Seguem abaixo cinco versículos relacionados com os temas abordados em Sabedoria 13:
* Êxodo 20:3 - "Não terás outros deuses diante de mim." Este é o primeiro dos Dez Mandamentos dados por Deus a Moisés no Monte Sinai, que proíbe a idolatria e enfatiza a exclusividade da adoração ao Senhor.
* Isaías 44:9 - "Aqueles que modelam ídolos são todos eles nada, e suas coisas mais queridas não aproveitam nada. Eles próprios testemunham que não veem nem entendem, para que sejam envergonhados." Este versículo condena a prática da criação de ídolos e destaca sua inutilidade.
* Jeremias 10:14 - "Todo homem é um tolo, sem conhecimento; todo ourives é envergonhado por sua imagem de escultura, pois suas imagens de fundição são falsidade, e nelas não há espírito." Este versículo enfatiza a tolice daqueles que confiam em ídolos e os consideram como deuses.
* Atos dos Apóstolos 17:24-25 - "O Deus que fez o mundo e tudo nele, sendo Senhor do céu e da terra, não habita em templos feitos por mãos humanas, nem é servido por mãos humanas, como se precisasse de alguma coisa, pois ele mesmo dá a todos a vida, o fôlego e todas as coisas." Este versículo destaca a superioridade do Deus verdadeiro em relação aos deuses falsos criados pelos homens.
* 1 Coríntios 8:4 - "Assim, quanto a comer alimentos sacrificados a ídolos, sabemos que 'um ídolo não é nada no mundo' e que 'não há nenhum outro Deus, senão um só'." Este versículo ressalta a importância de reconhecer a futilidade dos ídolos e adorar somente ao verdadeiro Deus.
****

[[v27-13-1]]

^<<v27-13-1,1>>^ São insensatos por natureza todos os que desconheceram a Deus e, através dos bens visíveis, não souberam conhecer aquele que é, nem reconhecer o artista, considerando suas obras.^&#42;1^

[[v27-13-2]]

^<<v27-13-2,2>>^ Tomaram o fogo, ou o vento, ou o ar agitável, ou a esfera estrelada, ou a água impetuosa, ou os astros dos céus, por deuses, regentes do mundo.

[[v27-13-3]]

^<<v27-13-3,3>>^ Se tomaram essas coisas por deuses, encantados pela sua beleza, saibam, então, quanto seu Senhor prevalece sobre elas, porque é o criador da beleza que fez essas coisas.

[[v27-13-4]]

^<<v27-13-4,4>>^ Se o que os impressionou é a sua força e o seu poder, que eles compreendam, por meio delas, que seu criador é mais forte;

[[v27-13-5]]

^<<v27-13-5,5>>^ pois é a partir da grandeza e da beleza das criaturas que, por analogia, se conhece o seu autor.

[[v27-13-6]]

^<<v27-13-6,6>>^ Contudo, estes só incorrem numa ligeira censura, porque, talvez, eles caíram no erro procurando Deus e querendo encontrá-lo:^&#42;1^

[[v27-13-7]]

^<<v27-13-7,7>>^ vivendo entre suas obras, eles as observam com cuidado, e porque eles as consideram belas, deixam-se seduzir pelo seu aspecto.

[[v27-13-8]]

^<<v27-13-8,8>>^ Ainda uma vez, entretanto, eles não são desculpáveis,

[[v27-13-9]]

^<<v27-13-9,9>>^ porque, se eles possuíram luz suficiente para poder perscrutar a ordem do mundo, como não encontraram eles mais facilmente aquele que é seu Senhor?

[[v27-13-10]]

^<<v27-13-10,10>>^ Mas são desgraçados e esperam em mortos, aqueles que chamaram de deuses a obras de mãos humanas: o ouro, a prata, artisticamente trabalhados, figuras de animais, alguma pedra inútil a que, outrora, certa mão deu forma.^&#42;1^

[[v27-13-11]]

^<<v27-13-11,11>>^ Assim, um lenhador cortou e serrou uma árvore fácil de manejar. Habilmente ele lhe tirou toda a casca, e, com a habilidade do seu ofício, fez dela um móvel útil para seu uso.

[[v27-13-12]]

^<<v27-13-12,12>>^ Com as sobras de seu trabalho, cozinhou comida, com que se saciou.

[[v27-13-13]]

^<<v27-13-13,13>>^ O que ainda lhe restava não era bom para nada, não passando de madeira torcida e toda cheia de nós; contudo, ele a tomou e consagrou suas horas de lazer a talhá-la; ele a trabalhou com toda a arte que adquirira, e deu-lhe a semelhança de um homem,^&#42;1^

[[v27-13-14]]

^<<v27-13-14,14>>^ ou o aspecto de algum vil animal. Pôs-lhe vermelhão, uma demão de uma tinta encarnada, e encobriu-lhe cuidadosamente todo defeito.

[[v27-13-15]]

^<<v27-13-15,15>>^ Em seguida, preparou-lhe um nicho digno dele, e o fixou à parede, segurando-o com um prego:

[[v27-13-16]]

^<<v27-13-16,16>>^ foi por medo que caísse, que tomou este cuidado, porque sabe muito bem que ele não pode ajudar-se a si mesmo, pois não passa de uma estátua que tem necessidade de um apoio.

[[v27-13-17]]

^<<v27-13-17,17>>^ Mas quando lhe implora por seus bens, seus casamentos, seus filhos, não se envergonha de falar ao que é inanimado, e pede saúde ao que é desprezível.

[[v27-13-18]]

^<<v27-13-18,18>>^ Reclama a vida ao que é morto, e procura socorro no que é débil; e, para uma viagem, invoca o que não pode andar;

[[v27-13-19]]

^<<v27-13-19,19>>^ para um lucro, um trabalho, o bom êxito de uma obra de suas mãos, pede a força ao que nem é capaz de mover as mãos.

'''

xref:027-sabedoria/027-sabedoria-012.adoc#v27-12-0[&#60; Capítulo Anterior] | <<v27-13-0,Topo>> | xref:027-sabedoria/027-sabedoria-014.adoc#v27-14-0[Próximo Capítulo &#62;]