include::./index.adoc[]

[[v63-1-0]]
=== Tito, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Tito 1 aborda as qualidades necessárias para os líderes da igreja, incluindo bispos e presbíteros. Paulo enfatiza a importância de ter líderes que sejam irrepreensíveis em seu comportamento e ensino, e que sejam capazes de refutar aqueles que ensinam falsas doutrinas. Além disso, ele destaca a necessidade de líderes que sejam bons administradores e que saibam liderar suas famílias. Aqui estão cinco versículos relacionados com os temas abordados em Tito 1:
* 1 Timóteo 3:2: "É necessário, pois, que o bispo seja irrepreensível, marido de uma só mulher, sóbrio, prudente, honesto, hospitaleiro e apto para ensinar." Este versículo se concentra nas qualidades necessárias para ser um bispo, que incluem ser irrepreensível, ter um bom comportamento e ser capaz de ensinar.
* 1 Pedro 5:2: "Apascentai o rebanho de Deus que está entre vós, não por constrangimento, mas espontaneamente, como Deus quer; nem por sórdida ganância, mas de boa vontade." Este versículo destaca a importância de liderar o rebanho de Deus de forma voluntária e com boas intenções, em vez de ser motivado pela ganância.
* 1 Timóteo 3:4-5: "Ele deve governar bem a própria casa, tendo seus filhos em sujeição, com todo o respeito, pois, se alguém não sabe governar a própria casa, como cuidará da igreja de Deus?" Esse versículo enfatiza a importância de um líder ter habilidades de liderança em sua própria família antes de liderar a igreja.
* Tito 2:7: "Em tudo te dá por exemplo de boas obras; na doutrina mostra integridade, sobriedade." Este versículo fala sobre a importância de ter integridade e sobriedade na doutrina, bem como dar um bom exemplo através de boas obras.
* 2 Timóteo 2:15: "Procura apresentar-te a Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade." Este versículo destaca a importância de manejar bem a palavra da verdade e ser aprovado por Deus como um obreiro sem vergonha.
****

[[v63-1-1]]

^<<v63-1-1,1>>^ Paulo, servo de Deus, apóstolo de Jesus Cristo para levar aos eleitos de Deus a fé e o profundo conhecimento da verdade que conduz à piedade,

[[v63-1-2]]

^<<v63-1-2,2>>^ na esperança da vida eterna prometida em tempos longínquos por Deus veraz e fiel,

[[v63-1-3]]

^<<v63-1-3,3>>^ que na ocasião escolhida manifestou a sua palavra mediante a pregação que me foi confiada por ordem de Deus, nosso Salvador,

[[v63-1-4]]

^<<v63-1-4,4>>^ a Tito, meu verdadeiro filho em nossa fé comum: graça e paz da parte de Deus Pai e de Jesus Cristo, nosso Salvador!

[[v63-1-5]]

^<<v63-1-5,5>>^ Eu te deixei em Creta para acabares de organizar tudo e estabeleceres anciãos em cada cidade, de acordo com as normas que te tracei.

[[v63-1-6]]

^<<v63-1-6,6>>^ (Devem ser escolhidos entre) quem seja irrepreensível, casado uma só vez, tenha filhos fiéis e não acusados de má conduta ou insubordinação.

[[v63-1-7]]

^<<v63-1-7,7>>^ Porquanto é mister que o bispo seja irrepreensível, como administrador que é posto por Deus. Não arrogante, nem colérico, nem intemperante, nem violento, nem cobiçoso.

[[v63-1-8]]

^<<v63-1-8,8>>^ Ao contrário, seja hospitaleiro, amigo do bem, prudente, justo, piedoso, continente,

[[v63-1-9]]

^<<v63-1-9,9>>^ firmemente apegado à doutrina da fé tal como foi ensinada, para poder exortar segundo a sã doutrina e rebater os que a contradizem.

[[v63-1-10]]

^<<v63-1-10,10>>^ Com efeito, há muitos insubmissos, charlatães e sedutores, principalmente entre os da circuncisão.

[[v63-1-11]]

^<<v63-1-11,11>>^ É necessário tapar-lhes a boca, porque transtornam famílias inteiras, ensinando o que não convém, e isso por vil espírito de lucro.

[[v63-1-12]]

^<<v63-1-12,12>>^ Um dentre eles, o “profeta” deles disse: “Os cretenses são sempre mentirosos, feras selvagens, glutões preguiçosos”.^&#42;1^

[[v63-1-13]]

^<<v63-1-13,13>>^ Esta asserção reflete a verdade. Portanto, repreende-os severamente, para que se mantenham sãos na fé,

[[v63-1-14]]

^<<v63-1-14,14>>^ e não dêem ouvidos a fábulas judaicas nem a preceitos de homens avessos à verdade.

[[v63-1-15]]

^<<v63-1-15,15>>^ Para os puros todas as coisas são puras. Para os corruptos e descrentes nada é puro: até a sua mente e consciência são corrompidas.

[[v63-1-16]]

^<<v63-1-16,16>>^ Proclamam que conhecem a Deus, mas na prática o renegam, detestáveis que são, rebeldes e incapazes de qualquer boa obra.

'''

xref:062-ii-timoteo/062-ii-timoteo-004.adoc#v62-4-0[&#60; Capítulo Anterior] | <<v63-1-0,Topo>> | xref:063-tito/063-tito-002.adoc#v63-2-0[Próximo Capítulo &#62;]