include::./index.adoc[]

[[v23-8-0]]
=== II Macabeus, 8
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Macabeus 8 narra a batalha dos macabeus contra Nicanor, general do rei Antíoco Epifânio, e a subsequente vitória dos judeus. Alguns temas abordados no capítulo incluem a coragem e fé dos macabeus, a estratégia de guerra e a ajuda divina que eles recebem. Aqui estão cinco versículos relacionados com esses temas:
* 2 Macabeus 8:18: "E invocando o Senhor dos mundos, que sem armas cai o poder diante dos que têm confiança na sua proteção, eles derrubaram os inimigos." Este versículo destaca a importância da confiança em Deus para a vitória na guerra, algo que os macabeus demonstraram ao longo da luta contra os selêucidas.
* Salmo 20:7: "Alguns confiam em carros e outros em cavalos, mas nós confiamos no nome do Senhor nosso Deus." Este salmo reforça a ideia de que a confiança em Deus é mais importante do que a confiança em armas ou estratégias humanas.
* Provérbios 21:31: "O cavalo é preparado para o dia da batalha, mas a vitória vem do Senhor." Este provérbio salienta que, embora a preparação para a guerra seja importante, a vitória é finalmente atribuída a Deus.
* 1 Coríntios 15:57: "Mas graças a Deus, que nos dá a vitória por meio de nosso Senhor Jesus Cristo." Este versículo enfatiza que a vitória é dada por Deus através de Cristo, que é a fonte da força e coragem dos cristãos.
* Efésios 6:10: "Finalmente, fortalecei-vos no Senhor e na força do seu poder." Este verso incentiva os cristãos a se fortalecerem em Deus e na Sua força, assim como os macabeus fizeram durante a batalha contra Nicanor.
****

[[v23-8-1]]

^<<v23-8-1,1>>^ Judas, chamado Macabeu, e seus companheiros penetravam secretamente nas aldeias e convocavam seus parentes. Arrastando consigo todos os que se haviam mantido fiéis ao judaísmo, formaram um grupo de aproximadamente seis mil homens.

[[v23-8-2]]

^<<v23-8-2,2>>^ Suplicavam ao Senhor que olhasse para o povo, desdenhado por todos; que se compadecesse do templo profanado pelos ímpios;

[[v23-8-3]]

^<<v23-8-3,3>>^ que tivesse compaixão da cidade devastada, perto de ser reduzida ao nível do solo; que escutasse a voz do sangue derramado que a ele clamava;

[[v23-8-4]]

^<<v23-8-4,4>>^ que se lembrasse da desumana carnificina de crianças inocentes e que vingasse também as blasfêmias proferidas contra seu nome.

[[v23-8-5]]

^<<v23-8-5,5>>^ Judas tornou-se o chefe da tropa e os gentios viram-se incapazes de resistir-lhe porque a cólera de Deus tinha-se convertido em misericórdia.

[[v23-8-6]]

^<<v23-8-6,6>>^ Atacava de improviso as cidades e aldeias e as incendiava. Ocupava as posições favoráveis, de onde afugentava não poucos de seus inimigos.

[[v23-8-7]]

^<<v23-8-7,7>>^ Era principalmente à noite que ele empreendia essas expedições. A fama de seu valor espalhava-se por toda a parte.

[[v23-8-8]]

^<<v23-8-8,8>>^ Vendo Judas progredir dia a dia e alcançar sempre frequentes vitórias, Filipe escreveu ao governador da Celessíria e da Fenícia, Ptolomeu, e pediu-lhe auxílio para defender os interesses do rei.^&#42;1^

[[v23-8-9]]

^<<v23-8-9,9>>^ Imediatamente, Ptolomeu designou Nicanor, um dos primeiros amigos do rei e filho de Pátroclo, e o enviou à frente de uns vinte mil homens de todas as nações, para exterminar toda a raça judia. Agregou a ele Górgias, general perito em assuntos de guerra.

[[v23-8-10]]

^<<v23-8-10,10>>^ Nicanor esperava obter, com a venda dos judeus que fossem aprisionados, os dois mil talentos que o rei devia como tributo aos romanos.

[[v23-8-11]]

^<<v23-8-11,11>>^ Enviou sem perda de tempo, às cidades da costa, o convite para que viessem comprar judeus, prometendo entregar noventa escravos por um talento. Mas não suspeitava então de que o castigo do Todo-poderoso iria cair sobre ele.

[[v23-8-12]]

^<<v23-8-12,12>>^ A notícia do avanço de Nicanor chegou a Judas, o qual informou aos seus da chegada dos inimigos.

[[v23-8-13]]

^<<v23-8-13,13>>^ Num relance, os que tinham medo ou não tinham confiança na justiça de Deus, fugiram e dispersaram-se.

[[v23-8-14]]

^<<v23-8-14,14>>^ Os outros venderam seus pertences, suplicando ao Senhor que os livrasse do ímpio Nicanor, que os havia vendido antes mesmo de tê-los em mãos.

[[v23-8-15]]

^<<v23-8-15,15>>^ Se não por causa deles, que o fizesse ao menos em consideração às alianças estabelecidas com seus pais e porque seu santo e sublime nome tinha sido invocado sobre eles.

[[v23-8-16]]

^<<v23-8-16,16>>^ Macabeu reuniu então ao redor de si seus homens, em número de seis mil, exortou-os a não se deixarem intimidar pelos inimigos, nem temerem essa massa de gentios que vinha injustamente contra eles, e que combatessem com valentia;

[[v23-8-17]]

^<<v23-8-17,17>>^ que pensassem na indigna profanação infligida por eles ao templo, na humilhação imposta à cidade devastada e na ruína das tradições de seus antepassados.

[[v23-8-18]]

^<<v23-8-18,18>>^ “Eles confiam – dizia ele – nas suas armas e na sua audácia, mas nós colocamos nossa segurança no Deus Todo-poderoso, que pode, com um só leve aceno, desbaratar tanto os que nos atacam como o universo inteiro!”

[[v23-8-19]]

^<<v23-8-19,19>>^ Lembrou-lhes no passado o caso da proteção divina como, por exemplo, do exército de Senaquerib, haviam perecido cento e oitenta mil homens.

[[v23-8-20]]

^<<v23-8-20,20>>^ E, na batalha contra os gálatas, na Babilônia, oito mil judeus tiveram de lutar ao lado de quatro mil macedônios. Como estes se achavam numa situação crítica, os oito mil judeus massacraram cento e vinte mil inimigos, por causa do socorro que lhes foi dado do céu, e ainda recolheram um vasto despojo.

[[v23-8-21]]

^<<v23-8-21,21>>^ Após ter reconfortado seus companheiros e tê-los incitado a morrer pelas leis e pela pátria, dividiu o exército em quatro divisões.

[[v23-8-22]]

^<<v23-8-22,22>>^ Pôs à frente destes seus irmãos Simão, José e Jônatas, como também Eleazar, cada qual chefiando mil e quinhentos homens.^&#42;1^

[[v23-8-23]]

^<<v23-8-23,23>>^ Apenas terminada a leitura do Livro santo e dada a senha: “Socorro de Deus”, ele mesmo pôs-se à frente do primeiro corpo e travou a batalha contra Nicanor.

[[v23-8-24]]

^<<v23-8-24,24>>^ O Todo-poderoso combateu ao lado deles. Massacraram mais de nove mil inimigos, feriram e mutilaram a maior parte dos soldados de Nicanor e os puseram em fuga.

[[v23-8-25]]

^<<v23-8-25,25>>^ Apoderaram-se também do dinheiro dos que tinham vindo para comprá-los, e perseguiram por muito tempo os vencidos, mas tiveram que desistir, impedidos pelo tempo,

[[v23-8-26]]

^<<v23-8-26,26>>^ porque era véspera de sábado, e isso os impedia de prosseguir.

[[v23-8-27]]

^<<v23-8-27,27>>^ Ajuntaram as armas, recolheram os despojos dos inimigos e chegaram assim ao sábado, bendizendo o Senhor à porfia, e glorificando-o por havê-los livrado nesse dia, prenunciando a alvorada de sua misericórdia.

[[v23-8-28]]

^<<v23-8-28,28>>^ Passado o sábado, eles reservaram uma parte dos espólios para os que haviam sofrido com a perseguição, as viúvas e os órfãos. Dividiram o resto entre eles e seus filhos.

[[v23-8-29]]

^<<v23-8-29,29>>^ Feito isso, rezaram ao Senhor em comum, suplicando misericórdia e reconciliação completa com seus servos.

[[v23-8-30]]

^<<v23-8-30,30>>^ Nos diferentes combates com os soldados de Timóteo e de Báquides, eles mataram mais de vinte mil e tornaram-se senhores absolutos de algumas fortalezas em pontos elevados. A abundante presa dividiram-na em duas partes iguais: uma para si mesmos, outra para os perseguidos, as mulheres, os órfãos e também os anciãos.

[[v23-8-31]]

^<<v23-8-31,31>>^ As armas que eles haviam recolhido foram colocadas diligentemente em lugares seguros e levaram a Jerusalém o resto dos despojos.

[[v23-8-32]]

^<<v23-8-32,32>>^ Mataram o chefe dos guardas de Timóteo, um dos homens mais perversos, que havia feito muito mal aos judeus.

[[v23-8-33]]

^<<v23-8-33,33>>^ Quando celebraram a festa da vitória em Jerusalém, queimaram, dentro de uma pequena casa onde se haviam refugiado, Calístenes e os que haviam incendiado as portas do templo, infligindo-lhes assim o justo castigo de seu sacrilégio.

[[v23-8-34]]

^<<v23-8-34,34>>^ O tríplice celerado Nicanor – que fizera vir mil negociantes, para vender-lhes os judeus –

[[v23-8-35]]

^<<v23-8-35,35>>^ humilhado, graças a Deus, por aqueles que ele desprezava profundamente, despojou-se da vestidura de honra, e, atravessando o interior do país sozinho, como um fugitivo, chegou a Antioquia, feliz por ainda ter podido escapar ao desastre de seu exército.

[[v23-8-36]]

^<<v23-8-36,36>>^ E ele, que tinha prometido pagar o tributo aos romanos com o dinheiro que tiraria da venda dos cativos de Jerusalém, publicou que os judeus possuíam um protetor e que se tornavam invulneráveis quando observavam as leis estabelecidas por esse defensor.

'''

xref:023-ii-macabeus/023-ii-macabeus-007.adoc#v23-7-0[&#60; Capítulo Anterior] | <<v23-8-0,Topo>> | xref:023-ii-macabeus/023-ii-macabeus-009.adoc#v23-9-0[Próximo Capítulo &#62;]