include::./index.adoc[]

[[v23-11-0]]
=== II Macabeus, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 11 de 2 Macabeus relata a vitória do exército liderado por Judas Macabeu contra as forças do general babilônico Nicanor, que havia invadido a Judeia com a intenção de destruir o templo de Jerusalém. Os versículos abaixo foram escolhidos por tratarem de temas relacionados a esse episódio de luta e vitória:
* 1 Samuel 17:47: "E toda esta congregação saberá que o Senhor não salva com a espada e com a lança; porque do Senhor é a guerra, e ele vos entregará na nossa mão." Essa passagem é uma declaração de fé de Davi, que confia no poder de Deus para derrotar o gigante Golias. Essa fé em Deus e em sua proteção é compartilhada por Judas Macabeu e seu exército, que sabem que sua vitória não depende apenas de sua habilidade militar, mas da ajuda divina.
* Salmo 20:7: "Uns confiam em carros, outros em cavalos, mas nós faremos menção do nome do Senhor nosso Deus." Essa passagem destaca a importância da confiança em Deus em meio às batalhas. Enquanto outros povos confiavam em seu poderio militar, Judas Macabeu e seus soldados colocavam sua confiança em Deus e em sua proteção.
* Salmo 144:1: "Bendito seja o Senhor, minha rocha, que ensina as minhas mãos para a peleja e os meus dedos para a guerra." Essa passagem destaca a importância da preparação e do treinamento para a guerra. Assim como o salmista atribui sua habilidade na batalha ao ensino de Deus, Judas Macabeu e seus soldados se preparam para a luta e contam com a ajuda divina para alcançar a vitória.
* Isaías 31:5: "Como as aves voam, assim protegerá o Senhor dos exércitos a Jerusalém; protegendo, ele também livrará e salvará, passando por cima, livrando." Essa passagem é uma promessa de proteção divina sobre Jerusalém. Judas Macabeu e seu exército lutam para defender o templo de Jerusalém e proteger seu povo dos invasores estrangeiros.
* Josué 10:25: "Disse-lhes Josué: Não temais, nem vos atemorizeis; esforçai-vos e tende bom ânimo, porque assim fará o Senhor a todos os vossos inimigos, contra os quais pelejardes." Essa passagem é uma mensagem de encorajamento e coragem para os soldados de Judas Macabeu. Assim como Josué encorajou seus homens a serem fortes e corajosos na luta contra os inimigos de Israel, Judas Macabeu inspira seus soldados a lutar com determinação e fé na vitória.
****

[[v23-11-1]]

^<<v23-11-1,1>>^ Decorrido algum tempo, Lísias, tutor e parente do rei, regente do reino, sentindo muito pesar pelo que tinha acontecido,

[[v23-11-2]]

^<<v23-11-2,2>>^ reuniu aproximadamente oitenta mil homens e toda a sua cavalaria e se pôs a caminho contra os judeus. Estava resolvido a transformar Jerusalém numa cidade grega,

[[v23-11-3]]

^<<v23-11-3,3>>^ submeter o templo a um imposto semelhante aos dos templos pagãos e oferecer em leilão, a cada ano, a dignidade de sumo sacerdote.

[[v23-11-4]]

^<<v23-11-4,4>>^ Sem refletir no poder de Deus, ensoberbecia-se com a multidão de sua infantaria, seus milhares de cavaleiros e oitenta elefantes.

[[v23-11-5]]

^<<v23-11-5,5>>^ Penetrando, pois, na Judeia, aproximou-se de Betsur, que é uma praça forte, a cerca de cinco esquenos das vizinhanças de Jerusalém, e sitiou-a.^&#42;1^

[[v23-11-6]]

^<<v23-11-6,6>>^ Logo, porém, que Macabeu e os que estavam com ele souberam que Lísias sitiava suas fortalezas, rogaram ao Senhor, juntamente com o povo, entre gemidos e lágrimas, para que ele se dignasse enviar um bom anjo para salvar Israel.

[[v23-11-7]]

^<<v23-11-7,7>>^ O próprio Macabeu foi o primeiro a pegar em armas, encorajando os demais a se exporem ao perigo com ele, para socorrer seus irmãos. Atacaram todos com ânimo resoluto.

[[v23-11-8]]

^<<v23-11-8,8>>^ Ainda não se haviam afastado de Jerusalém, quando apareceu diante deles um cavaleiro vestido de branco, empunhando armas de ouro.

[[v23-11-9]]

^<<v23-11-9,9>>^ Então, bendisseram todos juntos ao Senhor e, repletos de coragem, sentiram-se prontos a transpassar não só os homens, mas os mais ferozes animais e até muralhas de ferro.

[[v23-11-10]]

^<<v23-11-10,10>>^ Marcharam, pois, em ordem de batalha, com esse auxiliar enviado do céu pelo Senhor misericordioso.

[[v23-11-11]]

^<<v23-11-11,11>>^ Como leões, atiraram-se sobre os inimigos, trucidaram onze mil infantes e seiscentos cavaleiros, e forçaram os demais a fugir.

[[v23-11-12]]

^<<v23-11-12,12>>^ A maior parte destes, feridos, sem armas, pôs-se a salvo. O próprio Lísias salvou-se, fugindo vergonhosamente.

[[v23-11-13]]

^<<v23-11-13,13>>^ Mas Lísias era inteligente. Refletiu, pois, na derrota e concluiu que os hebreus eram invencíveis porque o Deus poderoso combatia com eles.

[[v23-11-14]]

^<<v23-11-14,14>>^ Enviou-lhes uma proposta em condições justas, prometendo-lhes persuadir o rei a tornar-se amigo deles.

[[v23-11-15]]

^<<v23-11-15,15>>^ Macabeu aceitou todas as propostas de Lísias, vendo nisso apenas utilidade, porque tudo o que ele mesmo pedira por carta a Lísias em favor dos judeus, o rei concedera.

[[v23-11-16]]

^<<v23-11-16,16>>^ Eis em que termos Lísias escreveu aos judeus:

[[v23-11-17]]

^<<v23-11-17,17>>^ “Lísias ao povo judeu, saudações! João e Absalão, vossos mensageiros, entregaram-me vossas propostas e rogaram-me que as cumprisse.

[[v23-11-18]]

^<<v23-11-18,18>>^ Expus, portanto, ao rei tudo o que devia comunicar-lhe, e ele anuiu a tudo o que era possível.

[[v23-11-19]]

^<<v23-11-19,19>>^ Se vós, pois, permanecerdes nessas boas disposições para com o Estado, continuarei doravante a obter-vos favores.

[[v23-11-20]]

^<<v23-11-20,20>>^ Eu incumbi vossos mensageiros e os meus de tratarem convosco as cláusulas da proposta e os pormenores.

[[v23-11-21]]

^<<v23-11-21,21>>^ Passai bem. Ano cento e quarenta e oito, aos vinte e quatro do mês de Dióscoro”.

[[v23-11-22]]

^<<v23-11-22,22>>^ Era este o conteúdo da carta do rei: “O rei Antíoco a seu irmão Lísias, saudações!

[[v23-11-23]]

^<<v23-11-23,23>>^ Tendo partido nosso pai para junto dos deuses, desejamos que os povos que pertencem ao nosso reino possam dedicar-se tranquilamente aos seus negócios.

[[v23-11-24]]

^<<v23-11-24,24>>^ Soubemos, no entanto, que os judeus resistem em adotar os costumes helênicos, conforme a decisão de nosso pai, mas preferem conservar suas tradições e pedem que lhes deixemos seus costumes.

[[v23-11-25]]

^<<v23-11-25,25>>^ Querendo, pois, que esse povo viva igualmente em paz, decretamos que o templo lhes seja restituído e que possam viver segundo as leis de seus antepassados.

[[v23-11-26]]

^<<v23-11-26,26>>^ Farás bem em lhes mandar mensageiros, para concluir a paz com eles, de modo que, conhecendo nossas intenções, fiquem tranquilos e voltem sem receio a seus afazeres”.

[[v23-11-27]]

^<<v23-11-27,27>>^ Eis a carta do rei ao povo judeu: “O rei Antíoco, ao conselho dos anciãos e aos demais judeus, saudações!

[[v23-11-28]]

^<<v23-11-28,28>>^ Fazemos votos de que estejais passando bem. Também nós estamos com boa saúde!

[[v23-11-29]]

^<<v23-11-29,29>>^ Contou-nos Menelau que desejais retornar aos vossos negócios.

[[v23-11-30]]

^<<v23-11-30,30>>^ A todos os que vierem para o meio deles até o dia trinta do mês de Xântico, eu estenderei a mão.

[[v23-11-31]]

^<<v23-11-31,31>>^ Permito também aos judeus que usem seus próprios alimentos e sigam seus costumes, como outrora. Nenhum deles será molestado por transgressões passadas.

[[v23-11-32]]

^<<v23-11-32,32>>^ Incumbi Menelau de ir tranquilizar-vos.

[[v23-11-33]]

^<<v23-11-33,33>>^ Passai bem! Ano cento e quarenta e oito, no dia quinze do mês de Xântico”.

[[v23-11-34]]

^<<v23-11-34,34>>^ Do mesmo modo, os romanos enviaram aos judeus uma carta nestes termos: “Quinto Mêmio e Tito Mânio, legados romanos, ao povo judeu, saudações!

[[v23-11-35]]

^<<v23-11-35,35>>^ Damos nosso assentimento a tudo o que Lísias, parente do rei, vos outorgou.

[[v23-11-36]]

^<<v23-11-36,36>>^ Quanto ao que ele julgou necessário submeter ao rei, enviai-nos alguém sem demora, a fim de que, após um exame, possamos falar-lhe de modo mais vantajoso para vós, porque vamos para Antioquia.

[[v23-11-37]]

^<<v23-11-37,37>>^ Apressai-vos, pois, em nos enviar mensageiros para que saibamos bem quais são vossos desejos.

[[v23-11-38]]

^<<v23-11-38,38>>^ Passai bem! Ano cento e quarenta e oito, no dia quinze do mês de Xântico”.

'''

xref:023-ii-macabeus/023-ii-macabeus-010.adoc#v23-10-0[&#60; Capítulo Anterior] | <<v23-11-0,Topo>> | xref:023-ii-macabeus/023-ii-macabeus-012.adoc#v23-12-0[Próximo Capítulo &#62;]