include::./index.adoc[]

[[v23-1-0]]
=== II Macabeus, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 1 de 2 Macabeus começa com uma carta escrita pelos judeus na cidade de Jerusalém para seus irmãos judeus no Egito, pedindo-lhes que celebrem a Festa da Dedicação do Templo. Eles mencionam a história do Templo e como ele foi reconstruído após ser profanado pelos inimigos. Os versículos abaixo são relacionados com o tema da reconstrução do Templo:
* Esdra 5:16: "Então chegaram Sheshbazar, o governador da Judéia, e os anciãos dos judeus, e edificaram-nos, e os fizeram levantar sobre seus fundamentos com a ajuda dos profetas de Deus, que estavam com eles e os ajudaram." Este versículo fala sobre a reconstrução do Templo sob a liderança de Esdras e a ajuda dos profetas.
* Ageu 1:14: "E o Senhor suscitou o espírito de Zorobabel, filho de Salatiel, governador de Judá, e o espírito de Josué, filho de Jozadaque, o sumo sacerdote, e o espírito de todo o restante do povo; e eles vieram e fizeram a obra na casa do Senhor dos Exércitos, seu Deus." Este versículo fala sobre a reconstrução do Templo após o exílio babilônico, onde Deus moveu os corações dos líderes e do povo para realizar a obra.
* Neemias 6:15-16: "Acabou-se, pois, a muralha aos vinte e cinco do mês de Elul, em cinquenta e dois dias. E sucedeu que, ouvindo todos os nossos inimigos isto, temeram todas as nações que estavam em redor de nós, e abateram-se muito em seus próprios olhos; porque reconheceram que fizemos esta obra com o nosso Deus." Este versículo fala sobre a reconstrução dos muros de Jerusalém, que também foi uma obra importante para a proteção do Templo.
* Neemias 8:9: "E Neemias, que era o governador, e Esdras, o sacerdote e escriba, e os levitas que ensinavam o povo, disseram a todo o povo: Este dia é consagrado ao Senhor, vosso Deus; não vos lamenteis, nem choreis. Porque todo o povo chorava, ouvindo as palavras da lei." Este versículo fala sobre a celebração da Festa dos Tabernáculos após a reconstrução dos muros de Jerusalém e a leitura da lei por Esdras.
* Esdras 6:15: "E acabou-se esta casa ao terceiro dia do mês de Adar, no sexto ano do reinado do rei Dario." Este versículo fala sobre a conclusão da reconstrução do Templo durante o reinado do rei Dario.
****

[[v23-1-1]]

^<<v23-1-1,1>>^ Aos nossos irmãos judeus que estão no Egito, saudações! Seus irmãos, os judeus residentes em Jerusalém e no país de Judá, desejam-lhes paz venturosa.

[[v23-1-2]]

^<<v23-1-2,2>>^ Deus vos cumule de bens e se lembre de sua aliança com Abraão, Isaac e Jacó, seus fiéis servidores.

[[v23-1-3]]

^<<v23-1-3,3>>^ Que ele disponha vossa alma à piedade e à observância dos seus mandamentos com um coração generoso e ânimo resoluto.

[[v23-1-4]]

^<<v23-1-4,4>>^ Que ele abra vosso coração à sua Lei e aos seus preceitos e que vos estabeleça na paz!

[[v23-1-5]]

^<<v23-1-5,5>>^ Que ele escute vossas súplicas, reconcilie-se convosco e não vos abandone nas provações!

[[v23-1-6]]

^<<v23-1-6,6>>^ Nós, daqui, rezamos por vós.

[[v23-1-7]]

^<<v23-1-7,7>>^ Sob o reinado de Demétrio, no ano cento e sessenta e nove, nós, judeus, vos escrevemos na tribulação e na aflição em que nos achávamos nessa época, desde o dia em que Jasão e seus partidários abandonaram a terra santa e seu reino.^&#42;1^

[[v23-1-8]]

^<<v23-1-8,8>>^ A porta do templo foi incendiada e derramado o sangue inocente. Então, suplicamos ao Senhor e ele nos ouviu. Oferecemos sacrifício e flor de farinha. Acendemos as lâmpadas e expusemos os pães.^&#42;1^

[[v23-1-9]]

^<<v23-1-9,9>>^ Celebrai, portanto, agora, a festa da cenopégia no mês de Casleu.^&#42;1^ No ano cento e oitenta e oito.

[[v23-1-10]]

^<<v23-1-10,10>>^ Os habitantes de Jerusalém e da Judeia, o senado e Judas, a Aristóbulo, conselheiro do rei Ptolomeu, da linhagem dos sacerdotes consagrados, como também aos judeus do Egito, saudações e votos de boa saúde!^&#42;1^

[[v23-1-11]]

^<<v23-1-11,11>>^ Salvos por Deus de inauditos perigos, nós lhe rendemos grandes ações de graças, porque tivemos um rei a combater.

[[v23-1-12]]

^<<v23-1-12,12>>^ Mas Deus rejeitou aqueles que haviam atacado a cidade santa.

[[v23-1-13]]

^<<v23-1-13,13>>^ Seu chefe, chegado à Pérsia com um exército aparentemente invencível, pereceu no templo de Naneia, vítima de um ardil dos sacerdotes da deusa.

[[v23-1-14]]

^<<v23-1-14,14>>^ Com razão, sob pretexto de esposar aquela, chegou com seus amigos para apoderar-se de suas riquezas, a título de dote.

[[v23-1-15]]

^<<v23-1-15,15>>^ Os sacerdotes expuseram o tesouro, e ele mesmo, com alguns dos seus, penetrou no recinto sagrado, enquanto eles fechavam as portas.

[[v23-1-16]]

^<<v23-1-16,16>>^ Mas, quando Antíoco entrou no interior, abriram uma porta secreta na abóbada e esmagaram o príncipe sob uma saraivada de pedras. Esquartejaram, em seguida, os corpos e degolaram as cabeças, lançando-as aos que estavam do lado de fora.

[[v23-1-17]]

^<<v23-1-17,17>>^ Louvado seja nosso Deus em todas as coisas, porque entregou os ímpios à morte!

[[v23-1-18]]

^<<v23-1-18,18>>^ Em vésperas de celebrarmos, dia vinte e cinco de Casleu, a purificação do templo, julgamos oportuno certificar-vos disso, a fim de que vós também celebreis a festa da cenopégia e a comemoração do fogo que apareceu quando Neemias ofereceu o sacrifício, após ter reconstruído o templo e o altar.

[[v23-1-19]]

^<<v23-1-19,19>>^ Na verdade, quando nossos pais foram levados à Pérsia, os sacerdotes de então, inflamados de piedade, tomaram secretamente o fogo sagrado do altar e o esconderam no fundo de um poço seco, onde eles o ocultaram tão cuidadosamente, que o lugar permaneceu desconhecido de todos.

[[v23-1-20]]

^<<v23-1-20,20>>^ Decorreram muitos anos e, quando aprouve a Deus, Neemias, salvo pelo rei da Pérsia, enviou, para retomar o fogo, os descendentes dos próprios sacerdotes que o haviam ocultado. Ora, segundo a explicação que eles nos deram, não encontraram o fogo, mas um líquido espesso.^&#42;1^

[[v23-1-21]]

^<<v23-1-21,21>>^ Neemias ordenou-lhes que o tirassem e o trouxessem. Uma vez preparada a matéria do sacrifício, disse Neemias aos sacerdotes que derramassem a água sobre a madeira e sobre o que estava ali colocado.

[[v23-1-22]]

^<<v23-1-22,22>>^ A ordem foi executada, e veio o momento em que o sol, a princípio recoberto por nuvens, pôs-se a brilhar; então um grande fogo se acendeu e maravilhou todos os espectadores.

[[v23-1-23]]

^<<v23-1-23,23>>^ Enquanto se consumia o sacrifício, os sacerdotes puseram-se a rezar, e todos rezavam com eles. Jônatas entoava e os outros, inclusive Neemias, juntavam sua voz à dele.

[[v23-1-24]]

^<<v23-1-24,24>>^ Eis a oração: “Senhor, Senhor Deus, criador de todas as coisas, temível e forte, justo e misericordioso, que sois o rei único e bom,

[[v23-1-25]]

^<<v23-1-25,25>>^ único generoso, único justo, Todo-poderoso e eterno, vós que salvastes Israel de todo mal, que fizestes de nossos pais vossos escolhidos e os santificastes,

[[v23-1-26]]

^<<v23-1-26,26>>^ aceitai este sacrifício, oferecido por todo o vosso povo de Israel; guardai vossa parte de eleição e santificai-a.

[[v23-1-27]]

^<<v23-1-27,27>>^ Congregai nossos irmãos dispersos, devolvei a liberdade aos que estão escravizados entre os pagãos, deitai vosso olhar sobre os que são desprezados e abominados, para que as nações saibam que sois nosso Deus.

[[v23-1-28]]

^<<v23-1-28,28>>^ Castigai os que nos oprimem e nos ultrajam com seu orgulho.

[[v23-1-29]]

^<<v23-1-29,29>>^ Plantai, como disse Moisés, vosso povo na vossa terra santa”.^&#42;1^

[[v23-1-30]]

^<<v23-1-30,30>>^ Os sacerdotes então cantaram hinos ao som da harpa.

[[v23-1-31]]

^<<v23-1-31,31>>^ Quando foi consumido o sacrifício, Neemias mandou que se espalhasse o líquido restante sobre grandes pedras.

[[v23-1-32]]

^<<v23-1-32,32>>^ Feito isso, uma chama se acendeu, mas se consumiu, enquanto o fogo que se erguia no altar continuava a brilhar.

[[v23-1-33]]

^<<v23-1-33,33>>^ O acontecimento foi logo divulgado, e contaram ao rei da Pérsia que era no lugar, onde os sacerdotes levados ao cativeiro tinham ocultado o fogo sagrado, que havia aparecido a água com a qual Neemias e seus companheiros obtiveram o fogo purificador das oferendas.

[[v23-1-34]]

^<<v23-1-34,34>>^ Ordenou o rei que se murasse o lugar e o considerassem como sagrado, após ter se certificado da exatidão do acontecido.

[[v23-1-35]]

^<<v23-1-35,35>>^ O rei tinha por hábito tomar posse de muitas coisas, das quais dava uma parte a quem ele queria ser agradável.

[[v23-1-36]]

^<<v23-1-36,36>>^ Os companheiros de Neemias chamaram isso de neftar, que quer dizer purificação, mas a maioria o chama de nafta.

'''

xref:022-i-macabeus/022-i-macabeus-016.adoc#v22-16-0[&#60; Capítulo Anterior] | <<v23-1-0,Topo>> | xref:023-ii-macabeus/023-ii-macabeus-002.adoc#v23-2-0[Próximo Capítulo &#62;]