include::./index.adoc[]

[[v23-13-0]]
=== II Macabeus, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 13 de 2 Macabeus descreve a batalha final entre as forças judaicas lideradas por Judas Macabeu e o exército do rei Antíoco Eupátor. Nessa batalha, Judas e seus homens conseguem uma grande vitória, e o capítulo também destaca a importância da oração e do sacrifício para obter a ajuda de Deus na luta contra os inimigos. Abaixo estão cinco versículos relacionados aos temas abordados em 2 Macabeus 13:
* 2 Crônicas 13:12: "Agora, pois, Deus está conosco à frente, e seus sacerdotes com as trombetas para tocarem o alarme contra vocês. Ó israelitas, não lutem contra o Senhor, o Deus de seus antepassados, pois vocês não terão sucesso". Esse versículo mostra a importância de confiar em Deus e na liderança divina em batalhas, assim como Judas liderou seu povo na batalha contra Antíoco Eupátor.
* Salmos 20:7: "Alguns confiam em carros e outros em cavalos, mas nós confiamos no nome do Senhor, nosso Deus". Esse versículo destaca a importância de confiar em Deus em vez de confiar apenas em recursos materiais ou estratégias humanas, algo que Judas e seus homens também fizeram.
* Isaías 59:19: "Virá como torrente violenta impelida pelo vento do Senhor". Esse versículo fala sobre a ajuda divina que pode vir como uma força poderosa em momentos de necessidade, assim como Judas e seus homens receberam ajuda divina na batalha.
* 1 Samuel 7:8: "Não deixes de clamar ao Senhor nosso Deus por nós, para que nos livre da mão dos filisteus". Esse versículo destaca a importância da oração e do clamor a Deus em momentos de batalha e dificuldade, algo que Judas e seus homens fizeram na batalha contra o exército inimigo.
* 1 Reis 8:44: "Quando o teu povo for à guerra contra o inimigo que tu lhe houveres de enviar, e orarem ao Senhor, voltados para a cidade que escolheste e para o templo que construí para o teu nome". Esse versículo destaca a importância de orar em direção ao templo de Deus, algo que Judas e seus homens também fizeram durante a batalha.
****

[[v23-13-1]]

^<<v23-13-1,1>>^ No ano cento e quarenta e nove, os partidários de Judas souberam que Antíoco Eupátor vinha contra a Judeia, com um considerável exército.

[[v23-13-2]]

^<<v23-13-2,2>>^ Lísias, seu tutor e ministro, acompanhava-o. Eles comandavam as tropas gregas, elevando-se a cento e dez mil infantes, cinco mil e trezentos cavaleiros, vinte e dois elefantes e trezentos carros armados de foices.

[[v23-13-3]]

^<<v23-13-3,3>>^ Menelau havia se unido a eles e intervinha perfidamente junto ao rei, não a favor de sua pátria, mas tendo em mira a confirmação de sua dignidade.

[[v23-13-4]]

^<<v23-13-4,4>>^ Todavia, o Rei dos reis excitou contra esse celerado a cólera de Antíoco e, tendo-o Lísias acusado de ser a causa de todos esses males, mandou o rei conduzi-lo a Bereia, para que fosse morto segundo o costume do país.

[[v23-13-5]]

^<<v23-13-5,5>>^ Ora, havia ali uma torre de cinquenta côvados, cheia de cinza e munida de um instrumento giratório que, de todos os lados, precipitava essa cinza.

[[v23-13-6]]

^<<v23-13-6,6>>^ Era lá que qualquer culpado de roubo sacrílego, ou de algum outro crime particularmente grave, era lançado à morte pela multidão.

[[v23-13-7]]

^<<v23-13-7,7>>^ Foi nesse suplício que morreu Menelau, o prevaricador, que não recebeu assim sepultura alguma.

[[v23-13-8]]

^<<v23-13-8,8>>^ E isso foi justo, porque ele havia pecado bastante contra o altar que sustenta o fogo puro e a cinza, e foi na cinza que ele encontrou a morte.

[[v23-13-9]]

^<<v23-13-9,9>>^ Nesse meio tempo, o rei avançava, imaginando os mais bárbaros planos, decidido a empregar contra os judeus os piores castigos imaginados por seu pai.

[[v23-13-10]]

^<<v23-13-10,10>>^ Sabendo disso, Judas mandou que o povo invocasse o Senhor, noite e dia, para que nessa circunstância, mais do que nunca, ele viesse em socorro daqueles que estavam ameaçados de perder a Lei, a pátria e o templo.

[[v23-13-11]]

^<<v23-13-11,11>>^ Que ele não permitisse que o povo, apenas um pouco aliviado, recaísse sob os golpes das nações perversas.

[[v23-13-12]]

^<<v23-13-12,12>>^ Rezaram todos juntos e invocaram o Senhor misericordioso, entre lágrimas, jejuns, prostrados três dias consecutivos. Judas exortou-os e disse-lhes que estivessem preparados.

[[v23-13-13]]

^<<v23-13-13,13>>^ Entrevistou-se ele com os anciãos e decidiu não esperar que o exército do rei penetrasse na Judeia e se assenhoreasse da cidade, mas sair logo e travar uma batalha decisiva com o auxílio de Deus.

[[v23-13-14]]

^<<v23-13-14,14>>^ Entregou, pois, a sorte das armas ao Criador do mundo e encorajou seus companheiros a combater valentemente até a morte em defesa das leis, do templo, da cidade, da pátria e da nação. Em seguida, levou seu exército até Modin.

[[v23-13-15]]

^<<v23-13-15,15>>^ Depois de ter entregue a seus homens a senha “Vitória de Deus”, tomou consigo os mais corajosos entre os jovens e partiu de noite, a fim de atacar o acampamento que abrigava o rei. Matou cerca de dois mil homens, massacraram o principal elefante e seu condutor.

[[v23-13-16]]

^<<v23-13-16,16>>^ Por fim, espalharam pelo campo o terror e a confusão, e retiraram-se vitoriosos.

[[v23-13-17]]

^<<v23-13-17,17>>^ Despontava o dia, quando cessou este ataque, graças à proteção de Deus.

[[v23-13-18]]

^<<v23-13-18,18>>^ Provando a audácia dos judeus, o rei tentou apoderar-se das fortificações por meio de estratagemas.

[[v23-13-19]]

^<<v23-13-19,19>>^ Partiu, a fim de colocar cerco diante de Betsur, praça forte dos judeus, mas foi rechaçado, sofrendo revés, e vencido,

[[v23-13-20]]

^<<v23-13-20,20>>^ enquanto Judas reabastecia os sitiados.

[[v23-13-21]]

^<<v23-13-21,21>>^ Rôdoco, combatente do exército dos judeus, revelou os segredos dos seus aos inimigos, mas após inquérito foi detido e executado.

[[v23-13-22]]

^<<v23-13-22,22>>^ Pela segunda vez, o rei parlamentou com os habitantes de Betsur, apresentou-lhes a mão, recebeu a deles, partiu para atacar o exército de Judas e foi vencido.

[[v23-13-23]]

^<<v23-13-23,23>>^ Soube então que Filipe, a quem tinha deixado em Antioquia para a direção dos negócios, se revoltara, e ficou muito consternado. Fez propostas aos judeus, aceitou as condições deles e jurou tudo o que lhe pareceu justo. Reconciliados, ofereceu um sacrifício, presenteou o templo e mostrou-se benévolo para com a cidade.

[[v23-13-24]]

^<<v23-13-24,24>>^ Acolheu com agrado Macabeu e deixou como governador na região Hegemônida, desde Ptolemaida até a terra dos gerrênios.^&#42;1^

[[v23-13-25]]

^<<v23-13-25,25>>^ Dirigiu-se a Ptolemaida, porque os habitantes estavam descontentes com esse tratado e indignados com os decretos promulgados.

[[v23-13-26]]

^<<v23-13-26,26>>^ Lísias subiu à tribuna, defendeu-o como pôde, persuadiu e apaziguou o povo, levando-o a benévolos sentimentos, e voltou depois a Antioquia. Assim decorreram a ofensiva e a retirada do rei.

'''

xref:023-ii-macabeus/023-ii-macabeus-012.adoc#v23-12-0[&#60; Capítulo Anterior] | <<v23-13-0,Topo>> | xref:023-ii-macabeus/023-ii-macabeus-014.adoc#v23-14-0[Próximo Capítulo &#62;]