include::./index.adoc[]

[[v23-3-0]]
=== II Macabeus, 3
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 3 de 2 Macabeus narra a história de um homem rico chamado Simão, que havia emprestado uma grande quantia de dinheiro ao Tesoureiro Público Heliodoro, para que este a entregasse ao rei. Heliodoro, no entanto, tentou roubar o dinheiro do Templo e foi impedido por uma aparição divina. Os versículos abaixo são relacionados com os temas do capítulo:
* Êxodo 20:15: "Não furtarás." Este é um dos mandamentos dados por Deus a Moisés no Monte Sinai, que condena o roubo de propriedade alheia. Heliodoro desobedeceu a esse mandamento ao tentar roubar o dinheiro do Templo.
* Levítico 19:11: "Não furtareis, nem mentireis, nem usareis de falsidade cada um com o seu próximo." Este versículo reforça a proibição de roubar e acrescenta a proibição de mentir e usar falsidade. A tentativa de Heliodoro de roubar o dinheiro do Templo envolveu uma mentira, já que ele afirmou estar agindo por ordem do rei.
* Provérbios 11:1: "O peso falso é abominação para o Senhor, mas o peso justo é o seu prazer." Este versículo se refere à prática de usar pesos e medidas justos na compra e venda de mercadorias, mas pode ser aplicado ao roubo de dinheiro também. Heliodoro tentou usar um peso falso para pesar o dinheiro do Templo, o que é uma abominação para o Senhor.
* Isaías 56:7: "Também os levarei ao meu santo monte, e os alegrarei na minha casa de oração; os seus holocaustos e os seus sacrifícios serão aceitos sobre o meu altar; porque a minha casa será chamada casa de oração para todos os povos." Este versículo fala sobre a importância do Templo como uma casa de oração para todos os povos, onde os sacrifícios e holocaustos são oferecidos a Deus. Heliodoro desrespeitou a santidade do Templo ao tentar roubá-lo.
* Malaquias 3:10: "Trazei todos os dízimos à casa do tesouro, para que haja mantimento na minha casa, e depois fazei prova de mim, diz o Senhor dos Exércitos, se eu não vos abrir as janelas do céu e não derramar sobre vós uma bênção tal, que dela vos advenha a maior abastança." Este versículo fala sobre a importância de trazer os dízimos e ofertas para a casa do tesouro, para que haja mantimento na casa de Deus. A tentativa de roubo de Heliodoro foi uma ameaça à manutenção do Templo.
****

[[v23-3-1]]

^<<v23-3-1,1>>^ Enquanto os habitantes de Jerusalém gozavam de uma paz perfeita, por causa da piedade e retidão do sumo sacerdote Onias, na exata observância das leis,^&#42;1^

[[v23-3-2]]

^<<v23-3-2,2>>^ o templo era respeitado, mesmo pelos reis estrangeiros. Estes honravam o santuário com os mais ricos presentes,

[[v23-3-3]]

^<<v23-3-3,3>>^ a tal ponto que Seleuco, rei da Ásia, subministrava com suas rendas pessoais toda a despesa necessária às liturgias dos sacrifícios.

[[v23-3-4]]

^<<v23-3-4,4>>^ Todavia, um certo Simão, da tribo de Belga, nomeado prefeito do templo, desentendeu-se com o sumo sacerdote por causa da inspeção do mercado público.^&#42;1^

[[v23-3-5]]

^<<v23-3-5,5>>^ Como não pudesse vencer Onias, foi procurar Apolônio de Társis então governador militar da Celessíria e da Fenícia.^&#42;1^

[[v23-3-6]]

^<<v23-3-6,6>>^ Declarou-lhe que o tesouro do templo transbordava de imensas riquezas, a não poder enumerá-las; que nada tinham a ver com os sacrifícios, e que ele daria um jeito de fazê-las passar ao erário real.

[[v23-3-7]]

^<<v23-3-7,7>>^ Tendo uma audiência com o rei, Apolônio comunicou-lhe o que soubera a respeito das riquezas que lhe haviam sido declaradas, e este, tomando uma decisão, enviou seu intendente Heliodoro, com a ordem de confiscar as ditas riquezas.

[[v23-3-8]]

^<<v23-3-8,8>>^ Imediatamente, Heliodoro pôs-se a caminho, simulando visitas às cidades da Celessíria e da Fenícia; na realidade, porém, era para executar a ordem do rei.

[[v23-3-9]]

^<<v23-3-9,9>>^ Tendo chegado a Jerusalém, e sendo recebido amigavelmente pelo sumo sacerdote da cidade, transmitiu-lhe as revelações recebidas e comunicou-lhe o sentido de sua visita; contudo, indagou se tudo isso correspondia à realidade.

[[v23-3-10]]

^<<v23-3-10,10>>^ O sumo sacerdote fez-lhe ver que se tratava do depósito das viúvas e dos órfãos

[[v23-3-11]]

^<<v23-3-11,11>>^ e que somente um dos depósitos pertencia a Hircano, filho de Tobias, homem de grande projeção; que era falsa a notícia dada pelo ímpio Simão, pois todas as riquezas se reduziam a uma soma de quatrocentos talentos de prata e duzentos talentos de ouro.

[[v23-3-12]]

^<<v23-3-12,12>>^ Era completamente impossível defraudar os que haviam depositado confiança na santidade do lugar e no caráter sagrado e inviolável do templo venerado no mundo inteiro.

[[v23-3-13]]

^<<v23-3-13,13>>^ Firme nas ordens do rei, Heliodoro respondeu que essas riquezas deveriam ser recolhidas ao tesouro real.

[[v23-3-14]]

^<<v23-3-14,14>>^ E, num dia por ele fixado, entrou com a intenção de organizar o inventário. A partir dessa hora, uma grande inquietude se espalhou pela cidade toda.

[[v23-3-15]]

^<<v23-3-15,15>>^ Revestidos de suas vestes sacerdotais e prostrados diante do altar, os sacerdotes invocavam ao céu e imploravam ao Autor da Lei acerca dos depósitos, rogando-lhe que os conservasse intatos para seus depositantes.^&#42;1^

[[v23-3-16]]

^<<v23-3-16,16>>^ Já o aspecto do sumo sacerdote causava pena ver, do mesmo modo seu semblante. E a alteração de seus traços manifestava sua angústia interior.

[[v23-3-17]]

^<<v23-3-17,17>>^ O susto que o havia tolhido agitava seu corpo com um tremor que mostrava o sofrimento íntimo de sua alma.

[[v23-3-18]]

^<<v23-3-18,18>>^ Diante da profanação que ameaçava o templo, o povo se precipitava em multidão para fora das casas, a fim de se ajuntarem à prece comum.

[[v23-3-19]]

^<<v23-3-19,19>>^ As mulheres, cingidas com sacos pela altura dos seios, enchiam as ruas. Quanto às jovens, retidas nas casas, corriam umas para as portas, outras para as muralhas, outras ainda se debruçavam nas janelas.

[[v23-3-20]]

^<<v23-3-20,20>>^ Todas erguiam as mãos para o céu com gritos de súplica.

[[v23-3-21]]

^<<v23-3-21,21>>^ Causava dó observar toda a confusão desse povo abatido e a angústia em que jazia o sumo sacerdote.

[[v23-3-22]]

^<<v23-3-22,22>>^ Enquanto suplicavam assim a proteção do Todo-poderoso para que conservasse invioláveis os depósitos que lhes haviam sido confiados,

[[v23-3-23]]

^<<v23-3-23,23>>^ Heliodoro executava o seu intento.

[[v23-3-24]]

^<<v23-3-24,24>>^ Já se achava ali, com seus homens armados, quando o Senhor dos espíritos e soberano detentor de todo poder suscitou uma tal aparição que todos os que tinham ousado vir ali desfaleceram de espanto, atingidos de pavor ante a majestade de Deus.

[[v23-3-25]]

^<<v23-3-25,25>>^ Viram eles, montado num cavalo ricamente ajaezado e guiado furiosamente, um cavaleiro de terrível aspecto, que lançava em Heliodoro as patas dianteiras do cavalo. O que vinha nele montado parecia ter uma armadura de ouro.

[[v23-3-26]]

^<<v23-3-26,26>>^ Ao mesmo tempo, apareceram-lhe outros dois jovens, de extraordinário vigor, fulgurantes de luz e ricamente vestidos. Colocando-se dos dois lados, puseram-se a açoitá-lo sem interrupção e descarregaram sobre ele uma saraivada de golpes.

[[v23-3-27]]

^<<v23-3-27,27>>^ Atirado subitamente por terra, Heliodoro foi envolvido por espessas trevas. Seus companheiros ergueram-no e o depositaram numa liteira.

[[v23-3-28]]

^<<v23-3-28,28>>^ E ele, que vinha para penetrar no mencionado tesouro com uma numerosa escolta e guardas pessoais, incapaz de se ajudar a si mesmo, foi levado por pessoas que reconheciam o manifesto poder de Deus.

[[v23-3-29]]

^<<v23-3-29,29>>^ Enquanto Heliodoro se achava estendido e ferido pela força de Deus, sem fala e sem esperança alguma de salvação,

[[v23-3-30]]

^<<v23-3-30,30>>^ os habitantes de Jerusalém bendiziam o Senhor, que havia glorificado seu templo. O santuário, que pouco antes estava cheio de confusão e de tumulto, logo que o Senhor manifestou sua onipotência encheu-se de regozijo e de alegria.

[[v23-3-31]]

^<<v23-3-31,31>>^ Todavia, alguns dos companheiros de Heliodoro suplicavam a Onias que invocasse ao Todo-poderoso, para restituir-lhe a vida, prestes, na verdade, a apagar-se.

[[v23-3-32]]

^<<v23-3-32,32>>^ Receando que o rei suspeitasse de que os judeus houvessem organizado um atentado contra Heliodoro, o sumo sacerdote ofereceu um sacrifício pela salvação daquele homem.

[[v23-3-33]]

^<<v23-3-33,33>>^ Ora, enquanto o pontífice executava a cerimônia expiatória, os mesmos jovens apareceram a Heliodoro, revestidos das mesmas vestes. Achegaram-se a ele e disseram-lhe: “Sê reconhecido ao sumo sacerdote, pois é por causa dele que Deus te dá a vida.

[[v23-3-34]]

^<<v23-3-34,34>>^ Proclama diante de todos seu grande poder, tu que foste açoitado por Deus”. Ditas estas palavras, desapareceram.

[[v23-3-35]]

^<<v23-3-35,35>>^ Após ter oferecido um sacrifício ao Senhor, erguido abundantes preces ao que lhe havia poupado a vida, e agradecido a Onias, Heliodoro regressou com suas tropas para junto do rei.

[[v23-3-36]]

^<<v23-3-36,36>>^ Testemunhava, diante de todos, os prodígios operados pelo grandioso Deus, aos seus olhos

[[v23-3-37]]

^<<v23-3-37,37>>^ e, como o rei lhe perguntasse que homem julgava ele que pudesse enviar ainda uma vez a Jerusalém, respondeu:

[[v23-3-38]]

^<<v23-3-38,38>>^ “Se tens algum inimigo ou alguém que maquina contra ti, envia-o para lá. Tu o receberás de volta ferido, se ainda viver, porque há verdadeiramente, naquele lugar, uma força divina.

[[v23-3-39]]

^<<v23-3-39,39>>^ O que habita no céu zela por aquele templo. Protege-o e arruína mortalmente os que aí vêm com más intenções”.

[[v23-3-40]]

^<<v23-3-40,40>>^ Foi assim que se passaram esses fatos a respeito de Heliodoro e da conservação do tesouro sagrado.

'''

xref:023-ii-macabeus/023-ii-macabeus-002.adoc#v23-2-0[&#60; Capítulo Anterior] | <<v23-3-0,Topo>> | xref:023-ii-macabeus/023-ii-macabeus-004.adoc#v23-4-0[Próximo Capítulo &#62;]