include::./index.adoc[]

[[v23-14-0]]
=== II Macabeus, 14
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em 2 Macabeus 14, Judas Macabeu e seus homens planejam uma batalha contra Nicanor e seus soldados. Durante esse capítulo, vemos a estratégia de Judas e sua confiança em Deus para obter a vitória. Os versículos selecionados abaixo falam sobre coragem em batalha, a importância da oração e confiança em Deus para a vitória.
* 1 Samuel 17:47: "E toda esta congregação saberá que o Senhor salva, não com espada, nem com lança; porque do Senhor é a guerra, e ele vos entregará na nossa mão." Esse verso fala sobre a importância de reconhecer que Deus é o único que pode nos dar a vitória, mesmo em uma batalha física.
* Efésios 6:18: "Orando em todo o tempo com toda a oração e súplica no Espírito e vigiando nisto com toda a perseverança e súplica por todos os santos." Esse verso fala sobre a importância da oração em todos os momentos e situações, incluindo batalhas.
* Josué 1:9: "Não te mandei eu? Esforça-te e tem bom ânimo; não temas, nem te espantes; porque o Senhor teu Deus é contigo, por onde quer que andares." Esse verso fala sobre a coragem que vem da confiança em Deus e na sua presença constante.
* Salmos 33:16-17: "Não há rei que se salve com a multidão dos seus exércitos, nem o homem valente se livra pela muita força. O cavalo é vão para a segurança; não livra ninguém com a sua grande força." Esse verso fala sobre como a vitória não depende apenas de força física ou números, mas sim da ajuda de Deus.
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Esse verso fala sobre como Deus é o nosso protetor e provedor em todos os momentos, incluindo momentos de batalha e dificuldade.
****

[[v23-14-1]]

^<<v23-14-1,1>>^ Três anos mais tarde, Judas e seus companheiros souberam que Demétrio, filho de Seleuco, tinha chegado pelo porto de Trípolis com um poderoso exército e uma grande esquadra.

[[v23-14-2]]

^<<v23-14-2,2>>^ Soube também que o país caíra em suas mãos e que havia causado a perda de Antíoco e de seu tutor Lísias.

[[v23-14-3]]

^<<v23-14-3,3>>^ Ora, certo Alcimo, outrora sumo sacerdote, mas voluntariamente comprometido por ocasião da introdução dos costumes pagãos, vendo que de nenhum lado lhe restava esperança de salvação, nem possibilidade de achegar-se ainda ao altar,

[[v23-14-4]]

^<<v23-14-4,4>>^ veio ter com o rei Demétrio. Isso foi pelo ano cento e cinquenta e um. Ofereceu-lhe uma coroa de ouro, uma palma e, além disso, alguns ramos de oliveira, dos que se oferecem no templo. Naquele dia, contudo, não disse nada.^&#42;1^

[[v23-14-5]]

^<<v23-14-5,5>>^ Encontrou, porém, ocasião oportuna para executar sua maldade, quando foi chamado ao conselho por Demétrio e interrogado sobre as disposições e os intentos dos judeus.

[[v23-14-6]]

^<<v23-14-6,6>>^ Respondeu ele: “Aqueles judeus, que se chamam assideus, em cuja frente se encontra Judas Macabeu, fomentam a guerra e as sedições e impedem que o reino goze de paz.

[[v23-14-7]]

^<<v23-14-7,7>>^ Eis por que, despojado de minha dignidade hereditária, quero dizer do sumo sacerdócio: vim aqui

[[v23-14-8]]

^<<v23-14-8,8>>^ primeiramente porque tenho realmente cuidado dos interesses do rei; depois, em consideração aos meus compatriotas, porque a irreflexão dos que citei mergulha toda a nossa raça num grande mal.

[[v23-14-9]]

^<<v23-14-9,9>>^ Reconhecido isso, ó rei, pela benevolência que testemunhas a todos, toma as medidas necessárias para a salvação de nosso país e de nossa raça ameaçada,

[[v23-14-10]]

^<<v23-14-10,10>>^ porque, enquanto Judas estiver vivo, é impossível que haja paz”.

[[v23-14-11]]

^<<v23-14-11,11>>^ Mal acabara ele de falar, os demais amigos do rei, hostis à causa de Judas, puseram-se a incitar Demétrio.

[[v23-14-12]]

^<<v23-14-12,12>>^ Este designou imediatamente Nicanor, ex-comandante do corpo de elefantes, e promoveu-o a general da Judeia, ordenando-lhe

[[v23-14-13]]

^<<v23-14-13,13>>^ que partisse a fim de matar Judas, dispersar suas tropas e restabelecer Alcimo como sacerdote do grande templo.

[[v23-14-14]]

^<<v23-14-14,14>>^ Aqueles que na Judeia tinham fugido de Judas colocaram-se ao lado dos gentios sob a chefia de Nicanor, como se os infortúnios e males dos judeus lhes devessem redundar em outros tantos êxitos.

[[v23-14-15]]

^<<v23-14-15,15>>^ Os judeus, ao ouvirem falar da expedição de Nicanor e do ataque dos gentios, cobriram a cabeça de pó e imploraram àquele que estabelecera seu povo para sempre e que continuamente, de modo visível, defendia sua herança.

[[v23-14-16]]

^<<v23-14-16,16>>^ Por ordem do chefe, partiu logo o exército e encontrou o inimigo perto da aldeia de Dessau.

[[v23-14-17]]

^<<v23-14-17,17>>^ Embora Simão, irmão de Judas, estivesse em presença de Nicanor, adiou o ataque em vista do súbito terror produzido aos seus pelo inimigo.

[[v23-14-18]]

^<<v23-14-18,18>>^ De seu lado, Nicanor, conhecendo a coragem dos homens de Judas e a grandeza de ânimo com que eles se atiravam ao combate pela pátria, temeu expor-se a uma decisão pelo sangue.

[[v23-14-19]]

^<<v23-14-19,19>>^ Enviou, pois, Posidônio, Teódoto e Matatias, para oferecer a mão aos judeus e receber a deles.

[[v23-14-20]]

^<<v23-14-20,20>>^ As propostas de paz foram por muito tempo examinadas. Cada chefe as comunicou às suas tropas e foram aceitas unanimemente.

[[v23-14-21]]

^<<v23-14-21,21>>^ Foi fixado um dia para uma conferência dos chefes sobre esse assunto. De um lado e de outro avançou um carro e colocaram cadeiras de honra.

[[v23-14-22]]

^<<v23-14-22,22>>^ Judas postou homens armados em lugares estratégicos, prontos para qualquer eventualidade, se os adversários os viessem trair. A conferência dos chefes foi satisfatória.

[[v23-14-23]]

^<<v23-14-23,23>>^ Nicanor passou a residir em Jerusalém, sem fazer ali mal algum. Despediu até mesmo a multidão das tropas que ele havia trazido consigo.

[[v23-14-24]]

^<<v23-14-24,24>>^ Estava constantemente em companhia de Judas, sentindo amizade para com ele.

[[v23-14-25]]

^<<v23-14-25,25>>^ Instou para que ele se casasse e que tivesse filhos. Judas casou-se, gozou de tranquilidade e desfrutou a vida.

[[v23-14-26]]

^<<v23-14-26,26>>^ Verificando Alcimo os sentimentos recíprocos de ambos os chefes, investigou as cláusulas do tratado e dirigiu-se a Demétrio, acusando Nicanor de conjurar contra o Estado, porque havia designado para seu lugar-tenente Judas, o próprio inimigo do reino.

[[v23-14-27]]

^<<v23-14-27,27>>^ Exasperado e excitado pelas calúnias desse bandido, escreveu o rei a Nicanor, dizendo-lhe que estava descontente com os tratados realizados e ordenava-lhe que lhe enviasse preso Macabeu o mais depressa possível, para Antioquia.

[[v23-14-28]]

^<<v23-14-28,28>>^ Ao receber a carta, Nicanor ficou consternado e triste por ter de romper seus contratos, sem que Judas tivesse agido mal.

[[v23-14-29]]

^<<v23-14-29,29>>^ Mas, como ele não podia contrariar as ordens do rei, procurava uma ocasião para executar essa ordem por algum ardil.

[[v23-14-30]]

^<<v23-14-30,30>>^ Reparando Macabeu que Nicanor se mostrava mais rude para com sua pessoa e com uma atitude mais indiferente, achou que esse procedimento nada indicava de bom. Reunindo, pois, um grupo dos seus partidários, ocultou-se de Nicanor.

[[v23-14-31]]

^<<v23-14-31,31>>^ Quando o outro reconheceu que havia sido logrado, dirigiu-se ao grande e sublime templo, no momento em que os sacerdotes ofereciam o sacrifício e deu-lhes ordem de entregarem esse homem.

[[v23-14-32]]

^<<v23-14-32,32>>^ Os sacerdotes, porém, juraram-lhe que não sabiam onde se achava o que ele procurava.

[[v23-14-33]]

^<<v23-14-33,33>>^ Então, estendendo a mão para o templo, jurou: “Se não me entregardes Judas preso, arrasarei até o solo este santuário de Deus, derribarei o altar e no mesmo lugar edificarei um magnífico templo a Dioniso”.

[[v23-14-34]]

^<<v23-14-34,34>>^ Ditas essas palavras, ele se retirou. Os sacerdotes, então, ergueram as mãos para o céu e invocaram aquele que sempre pelejou pelo nosso povo:

[[v23-14-35]]

^<<v23-14-35,35>>^ “Senhor do universo – exclamaram eles –, vós, que bastais a vós mesmo, quisestes possuir entre nós um templo por habitação.

[[v23-14-36]]

^<<v23-14-36,36>>^ Ó fonte santa de toda santidade, conservai, pois, sempre livre de toda profanação esta casa que há pouco foi purificada”.

[[v23-14-37]]

^<<v23-14-37,37>>^ Aconteceu também que Razias, um dos anciãos de Jerusalém, foi denunciado a Nicanor. Era um homem dedicado aos seus concidadãos, de grande reputação e cognominado “pai dos judeus”, por causa de sua benevolência.

[[v23-14-38]]

^<<v23-14-38,38>>^ Anteriormente, por ocasião da resistência ao paganismo, havia sido acusado de judaísmo e pelo judaísmo ele se havia exposto de corpo e alma com extremo zelo.

[[v23-14-39]]

^<<v23-14-39,39>>^ Nicanor, que pretendia dar uma prova de sua hostilidade para com os judeus, enviou mais de quinhentos homens para apoderar-se dele,

[[v23-14-40]]

^<<v23-14-40,40>>^ supondo que, prendendo-o, causaria aos judeus um golpe penoso.

[[v23-14-41]]

^<<v23-14-41,41>>^ Como essa tropa foi apoderar-se da torre e forçar a entrada, uma vez que havia sido dada a ordem de atear fogo e incendiar as portas, Razias, quando ia ser preso, transpassou-se com a própria espada,

[[v23-14-42]]

^<<v23-14-42,42>>^ preferindo morrer honradamente antes que cair nas mãos dos ímpios e padecer ultrajes indignos de seu nobre nascimento.

[[v23-14-43]]

^<<v23-14-43,43>>^ Na precipitação, porém, dirigiu mal o golpe e, enquanto os soldados forçavam do lado de fora contra as portas, ele correu animosamente para cima do muro e, com coragem, atirou-se sobre a multidão.

[[v23-14-44]]

^<<v23-14-44,44>>^ As pessoas afastaram-se com rapidez e Razias tombou no espaço deixado vazio.

[[v23-14-45]]

^<<v23-14-45,45>>^ Todavia, ainda respirando, cheio de ardor, ergueu-se e, embora o sangue lhe jorrasse como uma fonte de suas horríveis feridas, atravessou a multidão numa carreira. Em seguida, de pé sobre uma rocha escarpada

[[v23-14-46]]

^<<v23-14-46,46>>^ e já inteiramente exangue, arrancou com as próprias mãos as entranhas que saíam, e lançou-as sobre os inimigos. Foi assim seu fim, pedindo ao Senhor da vida e do espírito que lhos restituísse um dia.

'''

xref:023-ii-macabeus/023-ii-macabeus-013.adoc#v23-13-0[&#60; Capítulo Anterior] | <<v23-14-0,Topo>> | xref:023-ii-macabeus/023-ii-macabeus-015.adoc#v23-15-0[Próximo Capítulo &#62;]