include::./index.adoc[]

[[v23-4-0]]
=== II Macabeus, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 4 de 2 Macabeus retrata a corrupção e o paganismo que permeavam o judaísmo na época do Sumo Sacerdote Jasão. Ele havia subornado o governador da Síria para obter o cargo e instituiu práticas pagãs no Templo de Jerusalém. Além disso, ele perseguiu ferozmente os judeus fiéis que resistiam a essas mudanças. Abaixo estão cinco versículos relacionados aos temas abordados no capítulo:
* Eclesiastes 5:8 - "Se vires em alguma província opressão do pobre e violência do direito e da justiça, não te admires de tal procedimento; pois quem está altamente colocado tem superior que o vigia, e há mais altos ainda sobre eles." Este versículo reflete a corrupção e a injustiça que aconteciam na época de Jasão, onde a opressão dos pobres e a violência contra os justos eram comuns.
* Isaías 56:10-11 - "Os seus atalaias são cegos, todos eles ignorantes; são cães mudos, não podem ladrar; andam adormecidos, estão deitados, e gostam do sono. E estes cães são gulosos, não se podem fartar; e eles são pastores que nada compreendem; todos eles se tornam para o seu caminho, cada um para a sua ganância, cada um por sua parte." Este versículo denuncia a liderança religiosa corrupta que negligenciava suas responsabilidades em favor de seus próprios interesses egoístas.
* Ezequiel 22:26 - "Os seus sacerdotes violentam a minha lei e profanam as minhas coisas santas; entre o santo e o profano não fazem diferença, nem discernem o impuro do puro, e de meus sábados escondem os seus olhos, e assim sou profanado no meio deles." Esse versículo ilustra como Jasão e seus seguidores profanaram o Templo de Jerusalém, misturando práticas pagãs com a adoração ao Deus de Israel.
* Salmos 10:15 - "Quebre o braço do ímpio e malvado; esquadrinha-lhe a sua impiedade até que dela não aches mais nada." Este versículo reflete a esperança dos judeus piedosos de que Deus julgaria os ímpios e restauraria a pureza do Templo.
* Daniel 12:10 - "Muitos serão purificados, e embranquecidos, e provados; mas os ímpios procederão impiamente, e nenhum dos ímpios entenderá, mas os sábios entenderão." Este versículo indica que, embora os ímpios estivessem em ascensão na época de Jasão, ainda havia aqueles que permaneciam fiéis e que seriam purificados através de suas provações.
****

[[v23-4-1]]

^<<v23-4-1,1>>^ O já mencionado Simão, delator do tesouro e de sua pátria, caluniava Onias, dizendo que era ele quem tinha se lançado sobre Heliodoro e que era ele o autor de seus males.

[[v23-4-2]]

^<<v23-4-2,2>>^ Ousava chamar de inimigo do Estado o benfeitor da cidade, o defensor de seus concidadãos, o ardoroso observante das leis.

[[v23-4-3]]

^<<v23-4-3,3>>^ O ódio foi tão longe que um dos partidários de Simão cometeu até mesmo assassinatos.

[[v23-4-4]]

^<<v23-4-4,4>>^ Considerando o lado lamentável dessa questão e vendo o governador da Celessíria, Apolônio, filho de Menesteu, excitar a malícia de Simão,^&#42;1^

[[v23-4-5]]

^<<v23-4-5,5>>^ dirigiu-se Onias para junto do rei, não que ele tivesse a intenção de acusar seus concidadãos, mas para advertir acerca dos interesses públicos e privados de todo o seu povo.

[[v23-4-6]]

^<<v23-4-6,6>>^ Via muito bem que, sem uma intervenção do rei, seria impossível restabelecer a paz e pôr termo aos desatinos de Simão.

[[v23-4-7]]

^<<v23-4-7,7>>^ Após a morte de Seleuco e tendo subido ao trono Antíoco, chamado Epífanes, Jasão, irmão de Onias, usurpou fraudulentamente o cargo de sumo sacerdote.^&#42;1^

[[v23-4-8]]

^<<v23-4-8,8>>^ Em entrevista com o rei, ele lhe prometeu trezentos e sessenta talentos de prata e oitenta talentos de outras rendas.

[[v23-4-9]]

^<<v23-4-9,9>>^ Prometia-lhe, além disso, pagar outros cento e cinquenta talentos, se lhe fosse dado o poder de fundar um ginásio e uma efebia e de receber as inscrições dos antioquenos de Jerusalém.^&#42;1^

[[v23-4-10]]

^<<v23-4-10,10>>^ O rei consentiu. Logo que subiu ao poder, Jasão arrastou seus concidadãos para o helenismo.

[[v23-4-11]]

^<<v23-4-11,11>>^ Apesar dos privilégios obtidos do poder real por João, pai de Eupólemo, que foi enviado aos romanos para concluir um pacto de aliança e de amizade, ele introduziu costumes contrários, desdenhando as leis nacionais.^&#42;1^

[[v23-4-12]]

^<<v23-4-12,12>>^ Foi com alegria que fundou um ginásio ao pé da própria Acrópole, alistou os mais nobres dentre os jovens e os educou ao pétaso.^&#42;1^

[[v23-4-13]]

^<<v23-4-13,13>>^ Por causa da perversidade inaudita do ímpio Jasão, que não era de modo algum pontífice, obteve o helenismo tal êxito e os costumes pagãos uma atualidade tão crescente,

[[v23-4-14]]

^<<v23-4-14,14>>^ que os sacerdotes descuidavam o serviço do altar, menosprezavam o templo, negligenciavam os sacrifícios, corriam, fascinados pelo disco, a tomar parte na palestra e nos jogos proibidos.

[[v23-4-15]]

^<<v23-4-15,15>>^ Não faziam caso das honras da pátria e amavam muito mais os títulos helênicos.

[[v23-4-16]]

^<<v23-4-16,16>>^ Foi por essa razão que logo uma atmosfera penosa os cercou, porque naqueles mesmos, cuja forma de vida invejavam e a quem ambicionavam igualar-se em tudo, encontraram inimigos e os instrumentos para seu castigo.

[[v23-4-17]]

^<<v23-4-17,17>>^ O seguinte fato mostrará que não foi fácil violar as leis divinas.

[[v23-4-18]]

^<<v23-4-18,18>>^ Como em Tiro se celebrassem os jogos quinquenais, com a presença do rei,

[[v23-4-19]]

^<<v23-4-19,19>>^ o ímpio Jasão mandou um grupo de antioquenos de Jerusalém levar trezentas dracmas de prata para o sacrifício de Héracles, mas os próprios portadores julgaram a coisa inconveniente e acharam melhor empregá-las em outras despesas.

[[v23-4-20]]

^<<v23-4-20,20>>^ A vontade de Jasão era de que elas fossem destinadas ao sacrifício de Héracles, mas, por causa dos que as levavam, foram destinadas à construção das galeras.

[[v23-4-21]]

^<<v23-4-21,21>>^ Apolônio, filho de Menesteu, tinha sido enviado ao Egito, por ocasião da posse do rei Filométor. Antíoco soube que este rei se lhe tornara hostil e procurou pôr-se em segurança. Veio, pois, a Jope e de lá dirigiu-se a Jerusalém.

[[v23-4-22]]

^<<v23-4-22,22>>^ Recebido magnificamente por Jasão e por toda a cidade, fez sua entrada à luz de fachos, entre aclamações. Depois disso, transportou o seu acampamento para a Fenícia.

[[v23-4-23]]

^<<v23-4-23,23>>^ Três anos mais tarde, Jasão enviou Menelau, irmão de Simão, já mencionado, para levar o dinheiro ao rei e lembrar-lhe os negócios urgentes;

[[v23-4-24]]

^<<v23-4-24,24>>^ mas, uma vez admitido à presença do rei, cumulou-o de encômios sobre a extensão do seu poder e, oferecendo trezentos talentos a mais que Jasão, obteve para si mesmo o pontificado.

[[v23-4-25]]

^<<v23-4-25,25>>^ Recebidas as ordens do rei, voltou, nada tendo em si que fosse digno do pontificado, mas excitado por sentimentos de um desumano tirano e de uma besta feroz.

[[v23-4-26]]

^<<v23-4-26,26>>^ Desse modo Jasão, que havia suplantado seu próprio irmão, suplantado por sua vez, viu-se forçado a exilar-se no país dos amonitas.

[[v23-4-27]]

^<<v23-4-27,27>>^ Quanto a Menelau, achava-se bem na posse da dignidade, mas não entregava de modo algum ao rei o dinheiro prometido,

[[v23-4-28]]

^<<v23-4-28,28>>^ se bem que ele lhe fosse reclamado por Sóstrato, governador da Acrópole, encarregado das cobranças dos impostos. Por esse motivo, ambos foram chamados a comparecer diante do rei.

[[v23-4-29]]

^<<v23-4-29,29>>^ Menelau designou para substituí-lo como sumo sacerdote seu irmão Lisímaco; Sóstrato deixou Crates, comandante dos cipriotas.

[[v23-4-30]]

^<<v23-4-30,30>>^ Entrementes, os habitantes de Tarso e de Malos se revoltaram, porque suas cidades haviam sido entregues a Antioquide, concubina do rei.

[[v23-4-31]]

^<<v23-4-31,31>>^ Partiu pois este a toda a pressa, para restabelecer a calma, deixando como seu lugar-tenente Andrônico, um de seus dignitários.

[[v23-4-32]]

^<<v23-4-32,32>>^ Menelau viu que a circunstância lhe era favorável e se reconciliou com Andrônico por meio de objetos de ouro roubados ao templo. Chegou igualmente a vendê-los em Tiro e nas cidades vizinhas.

[[v23-4-33]]

^<<v23-4-33,33>>^ Quando soube disso com clareza, Onias repreendeu-o, conservando-se retirado no território inviolável de Dafne, perto de Antioquia.

[[v23-4-34]]

^<<v23-4-34,34>>^ Por causa disso, Menelau tomou à parte Andrônico, e induziu-o a matar Onias. Andrônico dirigiu-se, pois, para junto dele, enganou-o com astúcia, deu-lhe garantias, que confirmou por juramento, levou-o a deixar seu esconderijo e matou-o no mesmo instante, sem nenhuma consideração pela justiça.^&#42;1^

[[v23-4-35]]

^<<v23-4-35,35>>^ Não só os judeus, mas também muitos estrangeiros ficaram indignados e consternados com esse assassínio iníquo

[[v23-4-36]]

^<<v23-4-36,36>>^ e, quando o rei entrou nas cidades de Cilícia, tanto os judeus da cidade, como os gregos contrários à violência, vieram investigar o motivo da morte arbitrária de Onias.

[[v23-4-37]]

^<<v23-4-37,37>>^ Antíoco ficou profundamente abatido e, tocado de compaixão, chorou ao lembrar-se da sabedoria e da grande moderação do finado.

[[v23-4-38]]

^<<v23-4-38,38>>^ Excitado assim por uma cólera violenta, despojou imediatamente Andrônico de suas púrpuras, rasgou-lhe as vestes, mandou que levassem através de toda a cidade até o lugar onde havia lançado a mão sacrílega sobre Onias. E ali acabou com a vida do homicida. Assim o Senhor deu-lhe o merecido castigo.

[[v23-4-39]]

^<<v23-4-39,39>>^ Ora, em Jerusalém, Lisímaco, de acordo com Menelau, multiplicou os roubos sacrílegos e, divulgado o rumor, o povo revoltou-se contra Lisímaco, porque muitos objetos de ouro haviam sido levados.

[[v23-4-40]]

^<<v23-4-40,40>>^ Como a multidão se houvesse sublevado em cólera, Lisímaco armou cerca de três mil homens e deu o sinal para uma injusta repressão, sob a chefia de um certo Aurano, homem avançado em idade e não menos em loucura.

[[v23-4-41]]

^<<v23-4-41,41>>^ Todavia, o povo tomou conhecimento da trama de Lisímaco, uns se muniram de pedras, outros de paus, alguns ajuntaram o pó da terra e atiraram sobre os homens de Lisímaco.

[[v23-4-42]]

^<<v23-4-42,42>>^ Desse modo, muitos foram os feridos, alguns mortos e os restantes postos em fuga. Quanto ao próprio sacrílego, mataram-no junto ao tesouro.

[[v23-4-43]]

^<<v23-4-43,43>>^ Por todas essas desordens, foi instaurado um processo contra Menelau.

[[v23-4-44]]

^<<v23-4-44,44>>^ Quando o rei veio a Tiro, três enviados da assembleia dos anciãos sustentaram a acusação diante dele.

[[v23-4-45]]

^<<v23-4-45,45>>^ Mas Menelau, que se julgava já derrotado, prometeu grande soma de dinheiro a Ptolomeu, filho de Dorimeno, para que ele lhe granjeasse o favor do rei.

[[v23-4-46]]

^<<v23-4-46,46>>^ Ptolomeu conduziu pois o rei para debaixo de um peristilo, como se fosse para tomar ar fresco, e fê-lo mudar de sentimento,

[[v23-4-47]]

^<<v23-4-47,47>>^ de modo que Menelau, posto que responsável por todo o mal, foi considerado pelo rei inocente de todas as acusações que pesavam sobre ele, e condenou à morte os infelizes que teriam sido julgados inocentes, mesmo se tivessem pleiteado diante dos citas.^&#42;1^

[[v23-4-48]]

^<<v23-4-48,48>>^ Assim, os que só tinham tomado a palavra para defender os interesses da cidade, do povo e dos objetos sagrados sofreram essa pena injusta.

[[v23-4-49]]

^<<v23-4-49,49>>^ Por isso, os próprios tírios ficaram de tal maneira encolerizados com esse crime, que subvencionaram magnificamente os gastos de suas sepulturas.

[[v23-4-50]]

^<<v23-4-50,50>>^ Quanto a Menelau, por causa da cobiça dos poderosos, conservou seu cargo, mas cresceu em malícia e tornou-se o verdadeiro inimigo de seus concidadãos.

'''

xref:023-ii-macabeus/023-ii-macabeus-003.adoc#v23-3-0[&#60; Capítulo Anterior] | <<v23-4-0,Topo>> | xref:023-ii-macabeus/023-ii-macabeus-005.adoc#v23-5-0[Próximo Capítulo &#62;]