include::./index.adoc[]

[[v23-15-0]]
=== II Macabeus, 15
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 15 de 2 Macabeus narra a batalha final entre os judeus liderados por Judas Macabeu e as forças do rei Antíoco. Durante a batalha, Judas e seus homens confiam em Deus para protegê-los e vencer a guerra. Abaixo estão cinco versículos relacionados aos temas abordados nesse capítulo:
* 2 Samuel 22:33: "É Deus que me cinge de força e torna perfeito o meu caminho." Judas e seus homens confiam em Deus para lhes dar a força e a orientação necessárias para vencer a batalha.
* Salmos 18:2: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador." Os judeus confiam em Deus como sua rocha e fortaleza, sabendo que Ele os protegerá e os libertará.
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Deus promete estar com Judas e seus homens durante a batalha, fortalecê-los, ajudá-los e sustentá-los com a Sua mão direita.
* 1 Coríntios 15:57: "Mas graças a Deus que nos dá a vitória por meio de nosso Senhor Jesus Cristo." Judas e seus homens reconhecem que a vitória só é possível através de Deus, e agradecem a Ele por lhes dar a vitória.
* 2 Timóteo 4:7: "Combati o bom combate, acabei a carreira, guardei a fé." Judas e seus homens lutam corajosamente a batalha final, confiando em Deus para protegê-los e, no final, conseguem vencer o bom combate.
****

[[v23-15-1]]

^<<v23-15-1,1>>^ Ouvindo falar que Judas e seus aliados estavam nas fronteiras da Samaria, resolveu Nicanor atacá-los com toda a segurança no dia do repouso sabático.

[[v23-15-2]]

^<<v23-15-2,2>>^ Os judeus, obrigados por ele a segui-lo, disseram-lhe: “Não faças um massacre tão selvagem e tão bárbaro, mas respeita por teu lado o dia escolhido e especialmente santificado por aquele que tudo vê”.

[[v23-15-3]]

^<<v23-15-3,3>>^ Mas esse tríplice celerado perguntou se existia no céu um soberano que houvesse prescrito observar o dia de sábado.

[[v23-15-4]]

^<<v23-15-4,4>>^ Como eles respondessem: “Foi o mesmo Senhor vivo, Todo-poderoso no céu, quem ordenou a celebração do sétimo dia”.

[[v23-15-5]]

^<<v23-15-5,5>>^ O outro replicou: “Também eu sou poderoso na terra e ordeno que se tomem as armas e se executem as ordens do rei”. Todavia, não pôde executar seu desígnio criminoso.

[[v23-15-6]]

^<<v23-15-6,6>>^ Enquanto Nicanor, no auge de seu orgulho, decidia erigir um troféu com os despojos de Judas e seus companheiros,

[[v23-15-7]]

^<<v23-15-7,7>>^ Macabeu, ao contrário, deixava-se levar por uma inteira confiança de que haveria de obter auxílio do Senhor.

[[v23-15-8]]

^<<v23-15-8,8>>^ Exortava os seus companheiros a que não temessem o ataque dos gentios, a que se lembrassem dos auxílios já obtidos do céu e a que esperassem, pois também agora o Todo-poderoso lhes concederia a vitória.

[[v23-15-9]]

^<<v23-15-9,9>>^ Encorajou-os citando a Lei e os profetas, lembrou-lhes os combates outrora sustentados e inflamou-os desse modo com um novo ardor.

[[v23-15-10]]

^<<v23-15-10,10>>^ Após ter-lhes reanimado o espírito, estimulou-os ainda, apresentando aos seus olhos a perfídia dos gentios e o desprezo da palavra dada.

[[v23-15-11]]

^<<v23-15-11,11>>^ Assim armou a todos não com a segurança que vem das lanças e dos escudos, mas com a coragem que suscitam as boas palavras. Narrou-lhes ainda uma visão digna de fé, uma espécie de visão que os cumulou de alegria.

[[v23-15-12]]

^<<v23-15-12,12>>^ Eis o que tinha visto: Onias, que foi sumo sacerdote, homem nobre e bom, modesto em seu aspecto, de caráter ameno, distinto em sua linguagem e exercitado desde menino na prática de todas as virtudes, com as mãos levantadas, orava por todo o povo judeu.

[[v23-15-13]]

^<<v23-15-13,13>>^ Em seguida, apareceu do mesmo modo um homem com os cabelos todos brancos, de aparência muito venerável e nimbado por uma admirável e magnífica majestade.

[[v23-15-14]]

^<<v23-15-14,14>>^ Então, tomando a palavra, disse-lhe Onias: “Eis o amigo de seus irmãos, aquele que reza muito pelo povo e pela cidade santa, Jeremias, o profeta de Deus”.

[[v23-15-15]]

^<<v23-15-15,15>>^ E Jeremias, estendendo a mão, entregou a Judas uma espada de ouro, dizendo estas palavras ao entregá-la:

[[v23-15-16]]

^<<v23-15-16,16>>^ “Toma esta santa espada que Deus te concede e com a qual esmagarás os inimigos”.

[[v23-15-17]]

^<<v23-15-17,17>>^ Entusiasmados pelas palavras de Judas, tão nobres e tão capazes de excitar a coragem e robustecer as almas dos jovens, decidiram os judeus não acampar, mas arrojar-se para a frente, travar com valor a batalha e obter assim uma decisão, porque a cidade, a religião e o templo estavam em perigo.

[[v23-15-18]]

^<<v23-15-18,18>>^ Não lhes causavam tanta preocupação as mulheres, as crianças, seus irmãos e seus parentes. A primeira e principal inquietação que tinham era a purificação do templo.

[[v23-15-19]]

^<<v23-15-19,19>>^ Não era menor a angústia dos que tinham ficado na cidade, ansiosos pela luta que ia ser travada fora, na planície.

[[v23-15-20]]

^<<v23-15-20,20>>^ Todos já aguardavam a batalha decisiva, prestes a se iniciar. Os inimigos também já se tinham reunido para o combate, os elefantes estavam postados no lugar conveniente, a cavalaria disposta nas alas.

[[v23-15-21]]

^<<v23-15-21,21>>^ Macabeu, à vista dessa multidão imensa, do aparato de armas tão diversas e do aspecto temível dos elefantes, estendeu as mãos para o céu e invocou o Senhor que opera prodígios. Sabia muito bem que não é o poderio das armas que obtém a vitória, senão que Deus a decide, outorgando-a aos que ele julga dignos dela.

[[v23-15-22]]

^<<v23-15-22,22>>^ Eis como foi sua oração: “Senhor, vós, que no tempo de Ezequias, rei da Judeia, enviastes vosso anjo e fizestes perecer cento e oitenta e cinco mil homens do exército de Senaquerib,

[[v23-15-23]]

^<<v23-15-23,23>>^ enviai, pois, ainda agora, ó soberano dos céus, um bom anjo que nos preceda, infundindo temor e espanto.

[[v23-15-24]]

^<<v23-15-24,24>>^ Que vosso braço se estenda e extermine aqueles que, blasfemando, vieram atacar vosso povo santo”. E, com essas palavras, concluiu sua prece.

[[v23-15-25]]

^<<v23-15-25,25>>^ De um lado, as tropas de Nicanor avançavam ao som das trombetas e dos hinos guerreiros;

[[v23-15-26]]

^<<v23-15-26,26>>^ do outro lado, os de Judas travavam a batalha entre invocações e orações.

[[v23-15-27]]

^<<v23-15-27,27>>^ Enquanto pelejavam com as mãos, oravam ao Senhor no coração, e assim derribaram por terra nada menos que trinta e cinco mil homens e alegraram-se por verem Deus manifestar-se desse modo.

[[v23-15-28]]

^<<v23-15-28,28>>^ Concluída a batalha, dispersaram-se felizes, quando reconheceram Nicanor prostrado com a sua armadura.

[[v23-15-29]]

^<<v23-15-29,29>>^ Então, entre gritos e alvoroço, louvaram o Senhor na língua paterna.

[[v23-15-30]]

^<<v23-15-30,30>>^ Aquele que se consagrara de corpo e alma a serviço de seus concidadãos e conservara para com seus compatriotas o amor de sua juventude, ordenou que degolassem a cabeça de Nicanor, como também a mão e o braço, e os levassem a Jerusalém.

[[v23-15-31]]

^<<v23-15-31,31>>^ Chegado à cidade, convocou seus compatriotas, dispôs os sacerdotes diante do altar e mandou aproximarem-se também os que se achavam na fortaleza.

[[v23-15-32]]

^<<v23-15-32,32>>^ Apresentou-lhes a cabeça do impuro Nicanor e a mão, que este maldito havia insolentemente estendido contra a morada do Todo-poderoso.

[[v23-15-33]]

^<<v23-15-33,33>>^ Depois mandou cortar a língua do ímpio para lançá-la em pedaços aos pássaros e mandou suspender diante do templo o braço decepado, como castigo de sua insensatez.

[[v23-15-34]]

^<<v23-15-34,34>>^ E todos puseram-se a louvar nestes termos o Senhor que se tinha manifestado: “Bendito seja aquele que preservou sua morada de toda a impureza”.

[[v23-15-35]]

^<<v23-15-35,35>>^ Judas suspendeu do mesmo modo a cabeça de Nicanor, na parte exterior da fortaleza, como sinal palpável e evidente da proteção do Senhor.

[[v23-15-36]]

^<<v23-15-36,36>>^ De comum acordo, foi estabelecido que, doravante, não se deixaria passar esse dia sem festejá-lo e que seria celebrada no dia treze do duodécimo mês, chamado Adar em língua siríaca, a vigília do dia de Mardoqueu.^&#42;1^

[[v23-15-37]]

^<<v23-15-37,37>>^ Assim se desenrolaram os acontecimentos relativos a Nicanor, e já que a partir dessa época Jerusalém permaneceu em poder dos hebreus, finalizarei aqui minha narração.

[[v23-15-38]]

^<<v23-15-38,38>>^ Se ela está felizmente concebida e ordenada, era este o meu desejo. Se ela está imperfeita e medíocre, é porque não pude fazer melhor.

[[v23-15-39]]

^<<v23-15-39,39>>^ Assim como é nocivo beber somente o vinho ou somente a água, mas agradável e verdadeiramente proveitoso beber a água e o vinho misturados, assim também a disposição agradável do relato é o que causa prazer aos ouvidos do leitor. E aqui termino.

'''

xref:023-ii-macabeus/023-ii-macabeus-014.adoc#v23-14-0[&#60; Capítulo Anterior] | <<v23-15-0,Topo>> | xref:024-proverbios/024-proverbios-001.adoc#v24-1-0[Próximo Capítulo &#62;]