include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 37 do livro de Êxodo descreve a fabricação do altar de incenso, da arca da aliança e da mesa dos pães da proposição, todos com suas respectivas medidas e ornamentos. Para encontrar cinco versículos relacionados com os temas abordados neste capítulo, foram selecionados trechos de outros livros da Bíblia que também falam sobre a construção desses objetos sagrados.
* 1 Reis 7:48: "Salomão fez também todos os utensílios que pertenciam à casa do SENHOR: o altar de ouro; a mesa de ouro em que se punham os pães da proposição;” Este versículo menciona a mesa dos pães da proposição, objeto que foi fabricado no capítulo 37 de Êxodo.
* 2 Crônicas 4:19: "Salomão fez todos os utensílios que pertenciam à Casa de Deus; o altar de ouro; as mesas em que se colocavam os pães da proposição;” Esse versículo também menciona as mesas dos pães da proposição, assim como o anterior.
* Hebreus 9:4: "que tinha o altar de ouro do incenso, e a arca da aliança, coberta de ouro por todos os lados, na qual estava um vaso de ouro contendo o maná, a vara de Arão que floresceu e as tábuas da aliança" Esse versículo fala sobre a arca da aliança, que também foi fabricada no capítulo 37 de Êxodo.
* 1 Reis 6:20: "O oráculo, que estava no fundo da casa, tinha vinte côvados de comprimento, vinte de largura e vinte de altura; recobriu-o de ouro puro e também recobriu de ouro o altar de cedro." Esse versículo fala sobre o revestimento de ouro que foi feito no altar de incenso, objeto que também é mencionado no capítulo 37 de Êxodo.
* 2 Crônicas 5:10: "Nada havia nas tábuas que Moisés colocara na arca da aliança, senão somente as duas tábuas que foram postas ali por Moisés, em Horebe, quando o SENHOR fez aliança com os filhos de Israel, ao saírem eles do Egito." Esse versículo fala sobre as tábuas da aliança, que foram colocadas dentro da arca da aliança, objeto que foi fabricado no capítulo 37 de Êxodo.
****

[[v2-37-1]]

^<<v2-37-1,1>>^ Beseleel fez a arca de madeira de acácia; seu comprimento era de dois côvados e meio, sua largura de um côvado e meio, e sua altura de um côvado e meio.

[[v2-37-2]]

^<<v2-37-2,2>>^ Cobriu-a de ouro puro por dentro e fez-lhe por fora, ao redor, uma bordadura de ouro.

[[v2-37-3]]

^<<v2-37-3,3>>^ Fundiu para ela quatro argolas de ouro e pô-las nos seus quatro pés, duas de um lado e duas de outro.

[[v2-37-4]]

^<<v2-37-4,4>>^ Fez varais de madeira de acácia, revestidos de ouro,

[[v2-37-5]]

^<<v2-37-5,5>>^ que passou nas argolas colocadas dos lados da arca, para poder transportá-la.

[[v2-37-6]]

^<<v2-37-6,6>>^ Fez uma tampa de ouro puro, cujo comprimento era de dois côvados e meio, e a largura de um côvado e meio.

[[v2-37-7]]

^<<v2-37-7,7>>^ Fez dois querubins de ouro, feitos de ouro batido, nas duas extremidades da tampa,

[[v2-37-8]]

^<<v2-37-8,8>>^ um de um lado, outro de outro, de maneira que faziam corpo com as duas extremidades da tampa.

[[v2-37-9]]

^<<v2-37-9,9>>^ Esses querubins, com as faces voltadas um para o outro, tinham as asas estendidas para o alto, e protegiam com elas a tampa para a qual tinham as faces inclinadas.

[[v2-37-10]]

^<<v2-37-10,10>>^ Fez a mesa de madeira de acácia; seu comprimento era de dois côvados, sua largura de um côvado e sua altura de um côvado e meio.

[[v2-37-11]]

^<<v2-37-11,11>>^ Recobriu-a de ouro puro e fez ao seu redor uma bordadura de ouro.

[[v2-37-12]]

^<<v2-37-12,12>>^ Cercou-a de uma orla de um palmo de largura, com uma bordadura de ouro corrente em toda a volta.

[[v2-37-13]]

^<<v2-37-13,13>>^ Fundiu para a mesa quatro argolas de ouro, que fixou aos quatro ângulos de seus pés.

[[v2-37-14]]

^<<v2-37-14,14>>^ Essas argolas, colocadas à altura da orla, eram destinadas a receber os varais que serviriam para transportar a mesa.

[[v2-37-15]]

^<<v2-37-15,15>>^ Fez varais de madeira de acácia revestidos de ouro, para servir ao transporte da mesa.

[[v2-37-16]]

^<<v2-37-16,16>>^ Fez de ouro puro os utensílios que deviam ser colocados sobre a mesa: os vasos, as xícaras, os copos e as taças necessários às libações.

[[v2-37-17]]

^<<v2-37-17,17>>^ Fez o candelabro de ouro puro, de ouro batido, com seu pé e sua haste: seus cálices, seus botões e suas flores formavam um todo com ele.

[[v2-37-18]]

^<<v2-37-18,18>>^ Seis braços saíam de seus lados, três de um lado e três de outro.

[[v2-37-19]]

^<<v2-37-19,19>>^ Em um braço havia três cálices em forma de flor de amendoeira, com um botão e uma flor; na segunda haste havia três cálices, em forma de flor de amendoeira, com um botão e uma flor, e assim por diante para os seis braços que saíam do candelabro.

[[v2-37-20]]

^<<v2-37-20,20>>^ No próprio candelabro havia quatro cálices em forma de flor de amendoeira, com seus botões e suas flores:

[[v2-37-21]]

^<<v2-37-21,21>>^ um botão sob os dois primeiros braços que saíam do candelabro, um botão sob os dois braços seguintes, e um botão sob os dois últimos; e assim era com os seis braços que saíam do candelabro.

[[v2-37-22]]

^<<v2-37-22,22>>^ Esses botões e esses braços faziam corpo com o candelabro, formando ao todo uma só peça de ouro puro batido.

[[v2-37-23]]

^<<v2-37-23,23>>^ Fez sete lâmpadas de ouro puro; e fez de ouro puro as suas espevitadeiras e os seus cinzeiros.

[[v2-37-24]]

^<<v2-37-24,24>>^ Empregou um talento de ouro puro na confecção do candelabro e seus acessórios.

[[v2-37-25]]

^<<v2-37-25,25>>^ Fez o altar dos perfumes de madeira de acácia. Seu comprimento foi de um côvado, e sua largura de um côvado; era quadrado e tinha dois côvados de altura; seus chifres faziam corpo com ele.

[[v2-37-26]]

^<<v2-37-26,26>>^ Cobriu de ouro puro a sua parte superior, os seus lados ao redor e os seus chifres; e pôs uma bordadura de ouro ao redor.

[[v2-37-27]]

^<<v2-37-27,27>>^ Fez para ele duas argolas de ouro, que foram colocadas abaixo da bordadura, dos dois lados, e serviriam para receber os dois varais destinados ao seu transporte.

[[v2-37-28]]

^<<v2-37-28,28>>^ Fez varais de madeira de acácia, revestidos de ouro,

[[v2-37-29]]

^<<v2-37-29,29>>^ e fez também o óleo para a unção santa e o perfume aromático, composto segundo a arte do perfumista.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]