include::./index.adoc[]

[[v2-7-0]]
=== Êxodo, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em Êxodo 7, Deus começa a mostrar seu poder diante do faraó e do povo egípcio através de Moisés e Aarão, enviando diversas pragas sobre o Egito para libertar os hebreus da escravidão. Alguns temas abordados incluem a autoridade de Deus sobre os deuses egípcios, o endurecimento do coração do faraó e a libertação dos hebreus da escravidão. Abaixo seguem cinco versículos relacionados com esses temas:
* Êxodo 7:5 - "E os egípcios conhecerão que eu sou o Senhor, quando estender a minha mão sobre o Egito, e tirar os filhos de Israel do meio deles." Neste versículo, Deus declara seu poder e autoridade sobre os deuses egípcios e o povo, mostrando que ele é o único verdadeiro Deus.
* Êxodo 7:13 - "E o coração do faraó se endureceu, e não os ouviu, como o Senhor tinha dito." Esse versículo ilustra a resistência do faraó à mensagem de Moisés e Aarão e como Deus permitiu que seu coração se endurecesse para cumprir sua vontade.
* Êxodo 7:17 - "Assim diz o Senhor: Nisto saberás que eu sou o Senhor; eis que eu com esta vara que tenho na mão ferirei as águas que estão no rio, e tornar-se-ão em sangue." Aqui, Deus anuncia a primeira praga que enviará sobre o Egito, transformando as águas do rio Nilo em sangue.
* Êxodo 7:22 - "Então os magos do Egito fizeram o mesmo com os seus encantamentos; e o coração do faraó se endureceu, e não os ouviu, como o Senhor tinha dito." Esse versículo mostra como os magos egípcios conseguiram replicar a transformação da água em sangue através de seus próprios encantamentos, mas mesmo assim o faraó não se convenceu a libertar os hebreus.
* Êxodo 7:25 - "E sete dias se passaram, depois que o Senhor feriu o rio." Este versículo marca o fim da primeira praga, e mostra como as pragas de Deus foram progressivamente piorando e durando mais tempo, intensificando a pressão sobre o faraó para que libertasse os hebreus.
****

[[v2-7-1]]

^<<v2-7-1,1>>^ O Senhor disse a Moisés: “Vê, eu vou fazer de ti um deus para o faraó, e teu irmão Aarão será teu profeta.

[[v2-7-2]]

^<<v2-7-2,2>>^ Dirás tudo o que eu te mandar, e teu irmão Aarão falará ao rei para que ele deixe sair de sua terra os israelitas.

[[v2-7-3]]

^<<v2-7-3,3>>^ Mas eu endurecerei o coração do faraó, e multiplicarei meus sinais e meus prodígios no Egito.

[[v2-7-4]]

^<<v2-7-4,4>>^ Ele não vos ouvirá. Então estenderei minha mão sobre o Egito e farei sair dele os meus exércitos, meu povo, os israelitas, com uma grandiosa manifestação de justiça.

[[v2-7-5]]

^<<v2-7-5,5>>^ Os egípcios saberão que eu sou o Senhor, quando eu estender a mão sobre o Egito e fizer sair dele os israelitas”.

[[v2-7-6]]

^<<v2-7-6,6>>^ Moisés e Aarão fizeram o que o Senhor tinha ordenado, e obedeceram.

[[v2-7-7]]

^<<v2-7-7,7>>^ Moisés tinha oitenta anos e Aarão oitenta e três, quando falaram ao faraó.

[[v2-7-8]]

^<<v2-7-8,8>>^ O Senhor disse a Moisés e a Aarão:

[[v2-7-9]]

^<<v2-7-9,9>>^ “Se o faraó vos pedir um prodígio, tu dirás a Aarão: toma tua vara e joga-a diante do faraó; ela se tornará uma serpente”.

[[v2-7-10]]

^<<v2-7-10,10>>^ Tendo Moisés e Aarão chegado à presença do faraó, fizeram o que o Senhor tinha ordenado. Aarão jogou sua vara diante do rei e de sua gente, e ela se tornou uma serpente.

[[v2-7-11]]

^<<v2-7-11,11>>^ Mas o faraó, mandando vir os sábios, os encantadores e os mágicos, estes fizeram o mesmo com os seus encantamentos:

[[v2-7-12]]

^<<v2-7-12,12>>^ jogaram cada um suas varas, que se transformaram em serpentes. Mas a vara de Aarão engoliu as deles.

[[v2-7-13]]

^<<v2-7-13,13>>^ Entretanto, como o Senhor o havia anunciado, endureceu-se o coração do faraó e ele não quis ouvi-los.

[[v2-7-14]]

^<<v2-7-14,14>>^ O Senhor disse a Moisés: “O faraó endureceu o coração: ele se obstina em não querer deixar partir o povo.

[[v2-7-15]]

^<<v2-7-15,15>>^ Vai procurá-lo amanhã cedo, no momento em que ele sair para ir à margem do rio; os esperarão à beira do Nilo, tomarás na mão a vara que se mudou em serpente,

[[v2-7-16]]

^<<v2-7-16,16>>^ e lhes dirás: O Senhor, o Deus dos hebreus, mandou-me a ti para dizer-te: Deixa ir o meu povo, para que me preste culto no deserto. Até agora não me escutaste.

[[v2-7-17]]

^<<v2-7-17,17>>^ Eis o que diz o Senhor: nisto reconhecerás que eu sou o Senhor: vou ferir as águas do Nilo com a vara que tenho na mão e elas se mudarão em sangue.

[[v2-7-18]]

^<<v2-7-18,18>>^ Os peixes do Nilo morrerão, o rio se tornará tão poluído que os egípcios terão nojo de beber suas águas”.

[[v2-7-19]]

^<<v2-7-19,19>>^ O Senhor disse a Moisés: “Dize a Aarão: toma a tua vara e estende a mão sobre as águas do Egito, sobre os seus rios e seus canais, sobre seus lagos e seus reservatórios, para que essas águas se tornem sangue. Haverá sangue em todo o Egito, assim nos recipientes de madeira como nos de pedra”.

[[v2-7-20]]

^<<v2-7-20,20>>^ Moisés e Aarão obedeceram à ordem do Senhor. Sob os olhos do faraó e de sua gente, Aarão levantou sua vara e feriu a água do Nilo, que se mudou toda em sangue.

[[v2-7-21]]

^<<v2-7-21,21>>^ Morreram os peixes do Nilo, e o rio tornou-se tão poluído que os egípcios não podiam beber de suas águas. Houve sangue em todo o Egito.

[[v2-7-22]]

^<<v2-7-22,22>>^ Mas os mágicos do Egito fizeram outro tanto com seus encantamentos; o coração do faraó permaneceu endurecido e, como o Senhor havia predito, ele não ouviu Moisés e Aarão.

[[v2-7-23]]

^<<v2-7-23,23>>^ Voltou e entrou em sua casa sem mais se cuidar do acontecido.

[[v2-7-24]]

^<<v2-7-24,24>>^ Todos os egípcios cavaram o solo nas proximidades do Nilo procurando água potável, porque não se podia beber a água do rio.

[[v2-7-25]]

^<<v2-7-25,25>>^ Sete dias se passaram depois que o Senhor feriu o Nilo.

[[v2-7-26]]

^<<v2-7-26,26>>^ O Senhor disse a Moisés: “Vai procurar o faraó e dize-lhe: Deixa ir o meu povo, para que ele me preste um culto.

[[v2-7-27]]

^<<v2-7-27,27>>^ Se recusas, infestarei de rãs todo o teu território.

[[v2-7-28]]

^<<v2-7-28,28>>^ O Nilo ferverá de rãs que subirão para invadir tua habitação, teu quarto, teu leito, as casas de teu povo, os teus fornos e tuas amassadeiras.

[[v2-7-29]]

^<<v2-7-29,29>>^ As rãs subirão sobre ti, sobre teu povo e sobre todos os teus servos”.

'''

xref:002-exodo/002-exodo-006.adoc#v2-6-0[&#60; Capítulo Anterior] | <<v2-7-0,Topo>> | xref:002-exodo/002-exodo-008.adoc#v2-8-0[Próximo Capítulo &#62;]