include::./index.adoc[]

[[v2-10-0]]
=== Êxodo, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 10 de Êxodo narra a continuação das pragas do Egito, com a chegada da praga dos gafanhotos. Moisés e Arão tentam convencer o faraó a libertar os hebreus, mas ele ainda se recusa. Os versículos selecionados são:
* Deuteronômio 28:38: "Lançarás muita semente ao campo, porém colherás pouco, porque o gafanhoto a consumirá." Este versículo fala sobre o prejuízo causado pelos gafanhotos à agricultura, tema que é abordado no capítulo 10 de Êxodo.
* Joel 2:25: "E restituir-vos-ei os anos que foram consumidos pelo gafanhoto." Este versículo também trata dos gafanhotos, mas mostra que Deus tem o poder de restaurar o que foi perdido.
* Provérbios 30:27: "As locustas não têm rei, contudo todas elas saem em bandos." Este versículo aborda a natureza das locustas, que agem em conjunto, o que pode ser observado na praga dos gafanhotos em Êxodo 10.
* Joel 1:4: "O que ficou da lagarta, o gafanhoto o comeu; o que ficou do gafanhoto, a locusta o comeu; e o que ficou da locusta, o pulgão o comeu." Este versículo mostra a cadeia alimentar dos insetos, o que pode ser relacionado à praga dos gafanhotos em Êxodo 10.
* Deuteronômio 28:42: "O gafanhoto consumirá todas as tuas árvores e o fruto da tua terra." Este versículo também fala sobre os prejuízos causados pelos gafanhotos, que destroem a vegetação, tema que é abordado no capítulo 10 de Êxodo.
****

[[v2-10-1]]

^<<v2-10-1,1>>^ O Senhor disse a Moisés: “Vai procurar o faraó, porque lhe endureci o coração e o de sua gente para manifestar os meus prodígios no meio deles,

[[v2-10-2]]

^<<v2-10-2,2>>^ para que contes aos teus filhos e aos teus netos as maravilhas que fiz no Egito e os prodígios que operei no meio deles, e para que saibais que eu sou o Senhor”.

[[v2-10-3]]

^<<v2-10-3,3>>^ Moisés e Aarão foram procurar o rei e disseram-lhe: “Eis o que diz o Senhor, Deus dos hebreus: Até quando recusarás humilhar-te diante de mim? Deixa ir o meu povo para que ele me preste o seu culto.

[[v2-10-4]]

^<<v2-10-4,4>>^ Se recusares, farei vir amanhã gafanhotos sobre o teu território.

[[v2-10-5]]

^<<v2-10-5,5>>^ Cobrirão a superfície da terra de tal modo que se não poderá mais ver o solo. Devorarão o resto das colheitas que escapou ao granizo, e devorarão todas as árvores de vossos campos.

[[v2-10-6]]

^<<v2-10-6,6>>^ Encherão tuas casas, as casas de todos os teus servos e a de todos os egípcios. Será uma calamidade tão grande como nunca viram teus pais nem os pais de teus pais, desde sua chegada ao país até o dia de hoje”. Voltou-se, pois, Moisés e retirou-se da casa do faraó.

[[v2-10-7]]

^<<v2-10-7,7>>^ Os servos do faraó disseram-lhe: “Até quando nos servirá de laço este homem? Deixa partir essa gente para que preste seu culto ao Senhor, seu Deus. Não compreendeste ainda que o Egito vai ser arruinado?”.

[[v2-10-8]]

^<<v2-10-8,8>>^ Mandaram então vir Moisés e Aarão à presença do rei que lhes disse: “Ide fazer vossas devoções ao Senhor, vosso Deus. Quem são os que hão de partir?”.

[[v2-10-9]]

^<<v2-10-9,9>>^ “Iremos – respondeu Moisés – com nossos jovens e nossos velhos, nossos filhos e nossas filhas. Iremos com nossas ovelhas e nossos bois, porque temos de celebrar uma festa em honra do Senhor.”

[[v2-10-10]]

^<<v2-10-10,10>>^ O faraó replicou: “O Senhor esteja convosco, do mesmo modo como vos deixarei partir com vossos filhos! Tomai cuidado, porque tendes más intenções.^&#42;1^

[[v2-10-11]]

^<<v2-10-11,11>>^ Não há de ser assim. Ide vós, os homens, e prestai o vosso culto ao Senhor, pois é isso o que desejais”. E foram expulsos da presença do faraó.

[[v2-10-12]]

^<<v2-10-12,12>>^ O Senhor disse a Moisés: “Estende tua mão sobre o Egito para que venham gafanhotos sobre ele, e invadam o Egito, e devorem toda a erva da terra, tudo o que o granizo deixou”.

[[v2-10-13]]

^<<v2-10-13,13>>^ Moisés estendeu sua vara sobre o Egito, e o Senhor fez soprar sobre o país, todo aquele dia e toda aquela noite, um vento do oriente. E, chegando a manhã, o vento do oriente tinha trazido os gafanhotos.

[[v2-10-14]]

^<<v2-10-14,14>>^ Espalharam-se eles sobre todo o Egito, e invadiram todo o território egípcio em tão grande quantidade como nunca houve nem haverá jamais invasão semelhante.

[[v2-10-15]]

^<<v2-10-15,15>>^ Eles cobriram toda a superfície do solo em todo o país, de modo que a terra se escureceu. Devoraram toda a vegetação da terra e todos os frutos das árvores que tinha poupado o granizo. Nada de verde ficou nas árvores, nem nas plantas do campo, em toda a extensão do Egito.

[[v2-10-16]]

^<<v2-10-16,16>>^ O rei mandou imediatamente chamar Moisés e Aarão e disse-lhes: “Pequei contra o Senhor, vosso Deus, e contra vós.

[[v2-10-17]]

^<<v2-10-17,17>>^ Mas perdoa ainda esta vez o meu pecado, e roga ao Senhor, vosso Deus, que afaste ao menos de mim este flagelo mortal”.

[[v2-10-18]]

^<<v2-10-18,18>>^ Moisés saiu da casa do faraó e intercedeu junto ao Senhor.

[[v2-10-19]]

^<<v2-10-19,19>>^ O Senhor fez soprar do ocidente um vento fortíssimo que levou os gafanhotos e os precipitou no mar Vermelho, sem que ficasse um só em todo o território do Egito.

[[v2-10-20]]

^<<v2-10-20,20>>^ Mas o Senhor endureceu o coração do faraó, que não deixou partir os israelitas.

[[v2-10-21]]

^<<v2-10-21,21>>^ O Senhor disse a Moisés: “Estende a mão para o céu, e que se formem sobre todo o Egito trevas (tão espessas) que se possam apalpar”.

[[v2-10-22]]

^<<v2-10-22,22>>^ Moisés estendeu a mão para o céu, e durante três dias espessas trevas cobriram todo o Egito.

[[v2-10-23]]

^<<v2-10-23,23>>^ Durante esses três dias, não se via um ao outro, e ninguém se levantou do lugar onde estava. Ao passo que todos os israelitas tinham luz nos lugares onde habitavam.

[[v2-10-24]]

^<<v2-10-24,24>>^ O faraó mandou chamar Moisés e disse-lhe: “Ide fazer vossas devoções ao Senhor. Somente vossas ovelhas e vossos bois ficarão neste lugar; podeis levar convosco vossos filhinhos”.

[[v2-10-25]]

^<<v2-10-25,25>>^ Moisés respondeu: “Tu mesmo nos porás nas mãos o que precisamos para oferecermos sacrifícios e holocaustos ao Senhor, nosso Deus.

[[v2-10-26]]

^<<v2-10-26,26>>^ Além disso, nossos animais virão conosco; nem uma unha ficará, porque é deles que devemos tomar o que precisamos para fazer nosso culto ao Senhor, nosso Deus. Enquanto não tivermos chegado lá, não sabemos de que nos serviremos para prestar nosso culto ao Senhor”.

[[v2-10-27]]

^<<v2-10-27,27>>^ Mas o Senhor endureceu o coração do faraó, que não quis deixá-los partir.

[[v2-10-28]]

^<<v2-10-28,28>>^ O faraó disse a Moisés: “Fora de minha casa! Guarda-te de me rever, porque no dia em que vires o meu rosto morrerás!”.

[[v2-10-29]]

^<<v2-10-29,29>>^ “Tu o disseste – replicou Moisés – já não verei o teu rosto.”

'''

xref:002-exodo/002-exodo-009.adoc#v2-9-0[&#60; Capítulo Anterior] | <<v2-10-0,Topo>> | xref:002-exodo/002-exodo-011.adoc#v2-11-0[Próximo Capítulo &#62;]