include::./index.adoc[]

[[v2-25-0]]
=== Êxodo, 25
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Êxodo 25 descreve as instruções dadas por Deus a Moisés sobre a construção do tabernáculo, o lugar onde o povo de Israel adoraria a Deus durante sua jornada no deserto. Deus instrui Moisés a coletar ofertas do povo para construir o tabernáculo e todos os seus móveis. Os cinco versículos relacionados aos temas abordados em Êxodo 25 são:
* Êxodo 25:8: "E me farão um santuário, e habitarei no meio deles." Deus ordena que um santuário seja construído para que Ele possa habitar no meio do Seu povo.
* Êxodo 25:16: "E porás na arca o testemunho que eu te darei." Deus ordena que Moisés construa uma arca de madeira de acácia e coloque nela as tábuas com os Dez Mandamentos, que são o testemunho de Deus.
* Êxodo 25:22: "E ali virei a ti, e falarei contigo de cima do propiciatório, do meio dos dois querubins que estão sobre a arca do testemunho, tudo o que eu te ordenar para os filhos de Israel." Deus promete aparecer no santuário e falar com Moisés de cima do propiciatório, que ficaria acima da arca do testemunho.
* Êxodo 25:30: "E porás sobre a mesa o pão da proposição perante a minha face continuamente." Deus instrui Moisés a construir uma mesa de madeira de acácia e colocar nela o pão da proposição, que seria renovado semanalmente e servido como oferta a Deus.
* Êxodo 25:40: "E olha que o faças conforme o seu modelo, que te foi mostrado no monte." Deus instrui Moisés a seguir cuidadosamente as instruções e desenhos que Ele lhe deu no monte Sinai para a construção do tabernáculo, móveis e utensílios, enfatizando a importância da obediência às Suas instruções precisas.
****

[[v2-25-1]]

^<<v2-25-1,1>>^ O Senhor disse a Moisés:

[[v2-25-2]]

^<<v2-25-2,2>>^ “Dize aos israelitas que me façam uma oferta. Aceitareis essa oferenda de todo homem que a fizer de bom coração.

[[v2-25-3]]

^<<v2-25-3,3>>^ Eis o que aceitareis à guisa de oferta: ouro, prata, cobre,

[[v2-25-4]]

^<<v2-25-4,4>>^ púrpura violeta e escarlate, carmesim, linho fino, peles de cabra,

[[v2-25-5]]

^<<v2-25-5,5>>^ peles de carneiro tingidas de vermelho, peles de golfinho, madeira de acácia,

[[v2-25-6]]

^<<v2-25-6,6>>^ azeite para candeeiro, aromas para o óleo de unção e para os incensos odoríferos,

[[v2-25-7]]

^<<v2-25-7,7>>^ pedras de ônix e outras pedras para os cabochões do efod e do peitoral.

[[v2-25-8]]

^<<v2-25-8,8>>^ Eles me farão um santuário e habitarei no meio deles.

[[v2-25-9]]

^<<v2-25-9,9>>^ Construireis o tabernáculo e todo o seu mobiliário exatamente segundo o modelo que vou mostrar-vos”.

[[v2-25-10]]

^<<v2-25-10,10>>^ “Farão uma arca de madeira de acácia; seu comprimento será de dois côvados e meio, sua largura de um côvado e meio, e sua altura de um côvado e meio.

[[v2-25-11]]

^<<v2-25-11,11>>^ Tu a recobrirás de ouro puro por dentro, e farás por fora, em volta dela, uma bordadura de ouro.

[[v2-25-12]]

^<<v2-25-12,12>>^ Fundirás para a arca quatro argolas de ouro, que porás nos seus quatro pés, duas de um lado e duas de outro.

[[v2-25-13]]

^<<v2-25-13,13>>^ Farás dois varais de madeira de acácia, revestidos de ouro,

[[v2-25-14]]

^<<v2-25-14,14>>^ que passarás nas argolas fixadas dos lados da arca, para se poder transportá-la.

[[v2-25-15]]

^<<v2-25-15,15>>^ Uma vez passados os varais nas argolas, delas não serão mais removidos.

[[v2-25-16]]

^<<v2-25-16,16>>^ Porás na arca o testemunho que eu te der.^&#42;1^

[[v2-25-17]]

^<<v2-25-17,17>>^ Farás também uma tampa de ouro puro, cujo comprimento será de dois côvados e meio, e a largura de um côvado e meio.^&#42;1^

[[v2-25-18]]

^<<v2-25-18,18>>^ Farás dois querubins de ouro; e os farás de ouro batido, nas duas extremidades da tampa, um de um lado e outro de outro,

[[v2-25-19]]

^<<v2-25-19,19>>^ fixando-os de modo a formar uma só peça com as extremidades da tampa.

[[v2-25-20]]

^<<v2-25-20,20>>^ Terão esses querubins suas asas estendidas para o alto, e protegerão com elas a tampa, sobre a qual terão a face inclinada.

[[v2-25-21]]

^<<v2-25-21,21>>^ Colocarás a tampa sobre a arca e porás dentro da arca o testemunho que eu te der.

[[v2-25-22]]

^<<v2-25-22,22>>^ Ali virei ter contigo, e é de cima da tampa, do meio dos querubins que estão sobre a arca da aliança, que te darei todas as minhas ordens para os israelitas.”

[[v2-25-23]]

^<<v2-25-23,23>>^ “Farás uma mesa de madeira de acácia, cujo comprimento será de dois côvados, a largura de um côvado e a altura de um côvado e meio.

[[v2-25-24]]

^<<v2-25-24,24>>^ Tu a recobrirás de ouro puro e farás em volta dela uma bordadura de ouro.

[[v2-25-25]]

^<<v2-25-25,25>>^ Farás em volta dela uma orla de um palmo de largura com uma bordadura de ouro corrente ao redor.

[[v2-25-26]]

^<<v2-25-26,26>>^ Farás para essa mesa quatro argolas de ouro, que fixarás nos quatro ângulos de seus pés.

[[v2-25-27]]

^<<v2-25-27,27>>^ Essas argolas, colocadas à altura da orla, receberão os varais destinados a transportar a mesa.

[[v2-25-28]]

^<<v2-25-28,28>>^ Farás, de madeira de acácia, varais revestidos de ouro, que servirão para o transporte da mesa.

[[v2-25-29]]

^<<v2-25-29,29>>^ Farás de ouro puro os seus pratos, seus incensários, seus copos e suas taças, que servirão para as libações.

[[v2-25-30]]

^<<v2-25-30,30>>^ Porás sobre essa mesa os pães da proposição, que ficarão constantemente diante de mim.”

[[v2-25-31]]

^<<v2-25-31,31>>^ “Farás um candelabro de ouro puro; e o farás de ouro batido, com o seu pedestal e sua haste: seus cálices, seus botões e suas flores formarão uma só peça com ele.

[[v2-25-32]]

^<<v2-25-32,32>>^ Seis braços sairão dos seus lados, três de um lado e três de outro.

[[v2-25-33]]

^<<v2-25-33,33>>^ Num braço haverá três cálices em forma de flor de amendoeira, com um botão e uma flor; noutro haverá três cálices em forma de flor de amendoeira, com um botão e uma flor e assim por diante para os seis braços do candelabro.

[[v2-25-34]]

^<<v2-25-34,34>>^ No próprio candelabro haverá quatro cálices em forma de flor de amendoeira, com seus botões e suas flores:

[[v2-25-35]]

^<<v2-25-35,35>>^ um botão sob os dois primeiros braços do candelabro, um botão sob os dois braços seguintes e um botão sob os dois últimos: e assim será com os seis braços que saem do candelabro.

[[v2-25-36]]

^<<v2-25-36,36>>^ Esses botões e esses braços formarão um todo com o candelabro, tudo formando uma só peça de ouro puro batido.

[[v2-25-37]]

^<<v2-25-37,37>>^ Farás sete lâmpadas, que serão colocadas em cima, de maneira a alumiar a frente do candelabro.

[[v2-25-38]]

^<<v2-25-38,38>>^ Seus espevitadores e seus cinzeiros serão de ouro puro.

[[v2-25-39]]

^<<v2-25-39,39>>^ Será empregado um talento de ouro puro para confeccionar o candelabro e seus acessórios.

[[v2-25-40]]

^<<v2-25-40,40>>^ Cuida para que se execute esse trabalho segundo o modelo que te mostrei no monte.”^&#42;1^

'''

xref:002-exodo/002-exodo-024.adoc#v2-24-0[&#60; Capítulo Anterior] | <<v2-25-0,Topo>> | xref:002-exodo/002-exodo-026.adoc#v2-26-0[Próximo Capítulo &#62;]