include::./index.adoc[]

[[v2-40-0]]
=== Êxodo, 40
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Êxodo 40 narra a conclusão da construção do Tabernáculo, seguida pela sua montagem e consagração. Moisés segue as instruções dadas por Deus e monta o Tabernáculo exatamente como lhe foi ordenado, e a glória do Senhor preenche o espaço sagrado. Abaixo estão cinco versículos relacionados com os temas abordados em Êxodo 40:
* Números 9:15-16: "No dia em que foi erguido o tabernáculo, a nuvem cobriu-o, isto é, a tenda do testemunho; e desde a tarde até a manhã, houve sobre o tabernáculo como que uma aparência de fogo. Assim acontecia regularmente: a nuvem o cobria de dia, e à noite parecia haver fogo." Este versículo relata a presença constante da glória de Deus no Tabernáculo, que é um tema central de Êxodo 40.
* Levítico 8:10-11: "Depois Moisés pegou o óleo da unção e ungiu o tabernáculo e tudo o que havia nele, consagrando-os. Com sete vezes de unção ele aspergiu o altar e ungiu o altar e todos os seus utensílios e a bacia com a sua base, consagrando-os." Este versículo descreve a consagração do Tabernáculo e seus utensílios, como descrito em Êxodo 40.
* Salmo 26:8: "Senhor, eu amo o lugar da tua habitação, o tabernáculo onde a tua glória habita." Este salmo expressa o amor e a adoração pelo Tabernáculo e a presença de Deus nele.
* João 1:14: "E o Verbo se fez carne, e habitou entre nós, cheio de graça e de verdade; e vimos a sua glória, como a glória do unigênito do Pai." Este versículo faz referência à habitação de Deus entre os seres humanos, que é um tema relacionado com a presença de Deus no Tabernáculo.
* Hebreus 9:11: "Mas Cristo, tendo vindo como sumo sacerdote dos bens já realizados, por meio do maior e mais perfeito tabernáculo, não feito por mãos, isto é, não desta criação." Este versículo faz uma comparação entre o Tabernáculo terreno construído por Moisés e o Tabernáculo celestial que é a habitação de Deus, sugerindo uma conexão entre os temas de Êxodo 40 e a obra redentora de Cristo.
****

[[v2-40-1]]

^<<v2-40-1,1>>^ O Senhor disse a Moisés:

[[v2-40-2]]

^<<v2-40-2,2>>^ “No primeiro dia do primeiro mês, levantarás o tabernáculo, a tenda de reunião.

[[v2-40-3]]

^<<v2-40-3,3>>^ Porás nele a arca da aliança e a ocultarás com o véu.

[[v2-40-4]]

^<<v2-40-4,4>>^ Trarás a mesa e disporás nela as coisas que devem estar sobre ela. Trarás o candelabro e porás nele suas lâmpadas.

[[v2-40-5]]

^<<v2-40-5,5>>^ Colocarás o altar de ouro para o perfume diante da arca da aliança e pendurarás o véu à entrada do tabernáculo.

[[v2-40-6]]

^<<v2-40-6,6>>^ Colocarás o altar dos holocaustos diante da entrada do tabernáculo, da tenda de reunião.

[[v2-40-7]]

^<<v2-40-7,7>>^ Colocarás a bacia entre a tenda de reunião e o altar, e porás água nela.

[[v2-40-8]]

^<<v2-40-8,8>>^ Farás o recinto do átrio e disporás a cortina à entrada do átrio.

[[v2-40-9]]

^<<v2-40-9,9>>^ Tomarás o óleo da unção e ungirás com ele o tabernáculo com tudo o que ele contém; tu o consagrarás com todo o seu mobiliário, para que ele se torne uma coisa santa.

[[v2-40-10]]

^<<v2-40-10,10>>^ Ungirás o altar dos holocaustos e todos os seus utensílios; em virtude de tua consagração, o altar se tornará um local santíssimo.

[[v2-40-11]]

^<<v2-40-11,11>>^ Ungirás a bacia com seu pedestal e a consagrarás.

[[v2-40-12]]

^<<v2-40-12,12>>^ Farás em seguida Aarão e seus filhos aproximarem-se da entrada da tenda de reunião, onde os lavarás com água.

[[v2-40-13]]

^<<v2-40-13,13>>^ Revestirás Aarão com os ornamentos sagrados; tu o ungirás e o consagrarás e ele será sacerdote a meu serviço.

[[v2-40-14]]

^<<v2-40-14,14>>^ Farás seus filhos aproximarem-se e, depois de os teres revestido de túnicas,

[[v2-40-15]]

^<<v2-40-15,15>>^ tu os ungirás como o fizeste com seu pai; e serão sacerdotes a meu serviço. Essa unção lhes conferirá o sacerdócio para sempre, de geração em geração”.

[[v2-40-16]]

^<<v2-40-16,16>>^ Moisés fez tudo o que o Senhor lhe havia mandado e se conformou a tudo.

[[v2-40-17]]

^<<v2-40-17,17>>^ Assim, no segundo ano, no primeiro dia do primeiro mês, o tabernáculo foi erigido.

[[v2-40-18]]

^<<v2-40-18,18>>^ Moisés levantou o tabernáculo: pôs suas bases, suas tábuas, suas travessas e ergueu suas colunas.

[[v2-40-19]]

^<<v2-40-19,19>>^ Estendeu a tenda sobre o tabernáculo e pôs a coberta da tenda por cima, como o Senhor lhe tinha ordenado.

[[v2-40-20]]

^<<v2-40-20,20>>^ Tomou o testemunho e colocou-o na arca; meteu os varais na arca e colocou nela a tampa.

[[v2-40-21]]

^<<v2-40-21,21>>^ Introduziu a arca no tabernáculo; e, tendo pendurado o véu da separação, cobriu com ele a arca da aliança, como o Senhor tinha ordenado a Moisés.

[[v2-40-22]]

^<<v2-40-22,22>>^ Colocou a mesa na tenda de reunião, do lado norte do tabernáculo, diante da cortina;

[[v2-40-23]]

^<<v2-40-23,23>>^ e dispôs nela em ordem os pães diante do Senhor, como o Senhor lhe tinha ordenado.

[[v2-40-24]]

^<<v2-40-24,24>>^ Pôs o candelabro na tenda de reunião, diante da mesa, do lado sul do tabernáculo,

[[v2-40-25]]

^<<v2-40-25,25>>^ e dispôs nele as lâmpadas diante do Senhor, como o Senhor lhe tinha ordenado.

[[v2-40-26]]

^<<v2-40-26,26>>^ Colocou o altar de ouro na tenda de reunião, diante do véu,

[[v2-40-27]]

^<<v2-40-27,27>>^ e queimou nele o incenso, como o Senhor lhe tinha ordenado.

[[v2-40-28]]

^<<v2-40-28,28>>^ Colocou a cortina à entrada do tabernáculo.

[[v2-40-29]]

^<<v2-40-29,29>>^ Colocou o altar dos holocaustos à entrada do tabernáculo, da tenda de reunião, e ofereceu sobre ele o holocausto e a oblação, como o Senhor lhe tinha ordenado.

[[v2-40-30]]

^<<v2-40-30,30>>^ Colocou a bacia entre a tenda de reunião e o altar, e pôs nela a água para as abluções.

[[v2-40-31]]

^<<v2-40-31,31>>^ Moisés, Aarão e seus filhos lavaram aí as mãos e os pés.

[[v2-40-32]]

^<<v2-40-32,32>>^ Quando entravam na tenda de reunião e se aproximavam do altar, faziam suas abluções, como o Senhor tinha ordenado a Moisés.

[[v2-40-33]]

^<<v2-40-33,33>>^ Enfim, fez o recinto do átrio em torno do tabernáculo e do altar e colocou a cortina na porta do átrio. Assim Moisés deu por concluída a obra.

[[v2-40-34]]

^<<v2-40-34,34>>^ Então a nuvem cobriu a tenda de reunião e a glória do Senhor encheu o tabernáculo.

[[v2-40-35]]

^<<v2-40-35,35>>^ E era impossível a Moisés entrar na tenda de reunião, porque a nuvem pairava sobre ela, e a glória do Senhor enchia o tabernáculo.

[[v2-40-36]]

^<<v2-40-36,36>>^ Durante todo o curso de suas peregrinações, os israelitas se punham a caminho quando se elevava a nuvem que estava sobre o tabernáculo;

[[v2-40-37]]

^<<v2-40-37,37>>^ do contrário, eles não partiam até o dia em que ela se elevasse.

[[v2-40-38]]

^<<v2-40-38,38>>^ E, enquanto duraram as suas peregrinações, a nuvem do Senhor pairou sobre o tabernáculo durante o dia; e, durante a noite, havia um fogo na nuvem, que era visível a todos os israelitas.

'''

xref:002-exodo/002-exodo-039.adoc#v2-39-0[&#60; Capítulo Anterior] | <<v2-40-0,Topo>> | xref:003-levitico/003-levitico-001.adoc#v3-1-0[Próximo Capítulo &#62;]