include::./index.adoc[]

[[v2-27-0]]
=== Êxodo, 27
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 27 de Êxodo descreve as especificações do altar do holocausto e do átrio do tabernáculo. O altar deveria ser feito de madeira de acácia e revestido de bronze, com quatro chifres nos cantos. O átrio deveria ser cercado por cortinas de linho branco e sustentado por colunas de bronze. A seguir estão cinco versículos relacionados com temas abordados em Êxodo 27:
* Levítico 1:5: "E degolará o novilho perante o Senhor, e os sacerdotes, filhos de Arão, oferecerão o sangue e espargirão o sangue em redor sobre o altar, que está diante da porta da tenda da congregação." Este versículo se relaciona com Êxodo 27, pois fala do uso do altar do holocausto para sacrifícios, que seria construído de acordo com as especificações detalhadas nesse capítulo.
* Números 3:37: "E as colunas do pátio ao redor, com as suas bases, e as suas estacas, e as suas cordas." Esse versículo se relaciona com Êxodo 27, pois descreve as colunas de bronze que sustentariam as cortinas do átrio, as bases em que elas seriam fixadas e as estacas e cordas que as manteriam no lugar.
* Isaías 60:18: "Nunca mais se ouvirá de violência na tua terra, desolação nem destruição nos teus termos; mas aos teus muros chamarás Salvação, e às tuas portas Louvor." Esse versículo se relaciona com Êxodo 27, pois fala da importância de proteger e cercar a área do tabernáculo, como é descrito no capítulo 27.
* Ezequiel 43:15: "E o altar terá quatro côvados, e de quatro em quatro côvados será o seu chifre; e será todo o altar de quatro côvados." Esse versículo se relaciona com Êxodo 27, pois descreve as especificações do altar do holocausto, que deve ter quatro chifres, como é descrito no capítulo 27.
* Hebreus 13:10: "Temos um altar, de que não têm direito de comer os que servem ao tabernáculo." Esse versículo se relaciona com Êxodo 27, pois fala da importância do altar do Novo Testamento, que é superior ao altar do Antigo Testamento, mas que tem suas raízes nas especificações do altar do holocausto descritas no capítulo 27.
****

[[v2-27-1]]

^<<v2-27-1,1>>^ “Farás o altar de madeira de acácia. Será quadrado e seu comprimento será de cinco côvados, sua largura de cinco côvados (será quadrado) e sua altura será de três côvados.

[[v2-27-2]]

^<<v2-27-2,2>>^ Porás em seus quatro ângulos chifres, que farão corpo com o altar; e o cobrirás de bronze.

[[v2-27-3]]

^<<v2-27-3,3>>^ Farás para esse altar cinzeiros, pás, bacias, garfos e braseiros: todos esses utensílios serão feitos de bronze.

[[v2-27-4]]

^<<v2-27-4,4>>^ Farás no altar uma grelha de bronze em forma de grade, e porás nos seus quatro cantos quatro argolas de bronze.

[[v2-27-5]]

^<<v2-27-5,5>>^ Tu colocarás embaixo, sob o rebordo saliente do altar, de modo que essa grelha se eleve até a metade da altura do altar.

[[v2-27-6]]

^<<v2-27-6,6>>^ Farás para o altar varais de madeira de acácia, revestidos de bronze.

[[v2-27-7]]

^<<v2-27-7,7>>^ Esses varais serão introduzidos nas argolas, e estarão de um e outro lado do altar, quando for transportado.

[[v2-27-8]]

^<<v2-27-8,8>>^ O altar será oco e de tábuas, segundo o modelo que te dei sobre o monte.”

[[v2-27-9]]

^<<v2-27-9,9>>^ “Farás o átrio para o tabernáculo. Do lado meridional, ao sul do átrio, haverá cortinas de linho fino retorcido, numa extensão de cem côvados,

[[v2-27-10]]

^<<v2-27-10,10>>^ e igualmente vinte colunas sobre vinte pedestais de bronze; os pregos das colunas, bem como suas vergas, serão de prata.

[[v2-27-11]]

^<<v2-27-11,11>>^ Também para o norte haverá cortinas, numa extensão de cem côvados, bem como vinte colunas com seus pedestais de bronze, sendo de prata os pregos das colunas e suas vergas.

[[v2-27-12]]

^<<v2-27-12,12>>^ Do lado do ocidente a largura do átrio comportará cinquenta côvados de cortinas, com dez colunas e dez pedestais.

[[v2-27-13]]

^<<v2-27-13,13>>^ Na frente, do lado oriental, a largura do átrio será de cinquenta côvados.

[[v2-27-14]]

^<<v2-27-14,14>>^ De um lado haverá quinze côvados de cortinas, com três colunas e três pedestais,

[[v2-27-15]]

^<<v2-27-15,15>>^ e de outro lado quinze côvados de cortinas, com três colunas e três pedestais.

[[v2-27-16]]

^<<v2-27-16,16>>^ Na porta do átrio haverá uma cortina bordada, de vinte côvados, em púrpura violeta e escarlate, em carmesim e em linho fino retorcido, com quatro colunas e quatro pedestais.

[[v2-27-17]]

^<<v2-27-17,17>>^ Todas as colunas que formam o recinto do átrio serão unidas por vergas de prata; seus pregos serão de prata e seus pedestais de bronze.

[[v2-27-18]]

^<<v2-27-18,18>>^ O comprimento do átrio será de cem côvados, sua largura de cinquenta, e sua altura de cinco côvados; a cortina será de linho fino retorcido e os pedestais de bronze.

[[v2-27-19]]

^<<v2-27-19,19>>^ Todos os utensílios destinados ao serviço do tabernáculo, todas as suas estacas, como também as do átrio, serão de bronze.

[[v2-27-20]]

^<<v2-27-20,20>>^ Ordenarás aos israelitas que tragam para o candelabro óleo puro de olivas esmagadas, a fim de manter a lâmpada sempre acesa.

[[v2-27-21]]

^<<v2-27-21,21>>^ Na tenda de reunião, diante do véu que oculta a arca da aliança, Aarão e seus filhos prepararão esse óleo para que ele se queime desde a tarde até pela manhã em presença do Senhor. Essa é uma lei perpétua para os israelitas e suas gerações vindouras.”^&#42;1^

'''

xref:002-exodo/002-exodo-026.adoc#v2-26-0[&#60; Capítulo Anterior] | <<v2-27-0,Topo>> | xref:002-exodo/002-exodo-028.adoc#v2-28-0[Próximo Capítulo &#62;]