include::./index.adoc[]

[[v2-4-0]]
=== Êxodo, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 4 de Êxodo narra a continuação da conversa entre Deus e Moisés, após este ter sido chamado para libertar o povo de Israel da escravidão no Egito. Moisés expressa suas dúvidas e preocupações em relação à sua capacidade de liderar o povo e convencer o faraó a deixá-los partir. Deus então realiza alguns sinais e milagres para provar seu poder a Moisés e mostrar que estará com ele em sua missão. A seguir, cinco versículos relacionados com os temas abordados em Êxodo 4:
* Gênesis 12:2: "E farei de ti uma grande nação, e abençoar-te-ei e engrandecerei o teu nome; e tu serás uma bênção." Este versículo destaca como Deus prometeu abençoar e multiplicar a descendência de Abraão, e como essa promessa é relevante para a história de Êxodo, pois o povo de Israel é descendente de Abraão e é a nação que Deus prometeu a ele.
* Isaías 41:20: "Para que todos vejam e saibam, e considerem e juntamente entendam que a mão do Senhor fez isto, e o Santo de Israel o criou." Este versículo destaca como Deus usa sinais e milagres para mostrar seu poder e provar que está com seus seguidores. Isso é relevante para o capítulo 4 de Êxodo, onde Deus realiza sinais e milagres para convencer Moisés e o povo de Israel de seu poder.
* Salmos 77:14: "Tu és o Deus que fazes maravilhas; fizeste conhecida a tua força entre os povos." Este versículo também destaca a capacidade de Deus de realizar sinais e milagres para mostrar seu poder e fazer sua vontade conhecida. Isso é relevante para a história de Êxodo, onde Deus usa sinais e milagres para libertar o povo de Israel da escravidão no Egito.
* Isaías 42:8: "Eu sou o Senhor; este é o meu nome; a minha glória, pois, a outrem não darei, nem o meu louvor às imagens de escultura." Este versículo destaca a singularidade e exclusividade de Deus como o único Deus verdadeiro. Isso é relevante para a história de Êxodo, pois a libertação do povo de Israel da escravidão no Egito é um testemunho do poder único e exclusivo de Deus.
* Salmos 121:2: "O meu socorro vem do Senhor, que fez o céu e a terra." Este versículo destaca a importância de confiar em Deus para obter ajuda e proteção, em vez de confiar em nossas próprias habilidades ou recursos. Isso é relevante para o capítulo 4 de Êxodo, onde Moisés expressa dúvidas e preocupações em relação à sua capacidade de liderar o povo de Israel, e Deus lhe mostra que estará com ele em sua missão.
****

[[v2-4-1]]

^<<v2-4-1,1>>^ Moisés respondeu: “Eles não me crerão, nem me ouvirão, e vão dizer que o Senhor não me apareceu”.

[[v2-4-2]]

^<<v2-4-2,2>>^ O Senhor disse-lhe: “O que tens na mão?”. “Uma vara.”

[[v2-4-3]]

^<<v2-4-3,3>>^ “Joga-a por terra.” Ele jogou-a por terra; e a vara transformou-se numa serpente, de modo que Moisés recuou.

[[v2-4-4]]

^<<v2-4-4,4>>^ O Senhor disse-lhe: “Estende tua mão e toma-a pela cauda – ele estendeu a mão e tomou-a, e a serpente tornou-se de novo uma vara em sua mão –;

[[v2-4-5]]

^<<v2-4-5,5>>^ é para que creiam que o Senhor, o Deus de seus pais, o Deus de Abraão, o Deus de Isaac e o Deus de Jacó, realmente te apareceu”.

[[v2-4-6]]

^<<v2-4-6,6>>^ O Senhor continuou: “Mete a tua mão no teu seio”. Ele meteu a mão em seu seio e, quando a retirou, sua mão estava leprosa, tão branca como a neve.

[[v2-4-7]]

^<<v2-4-7,7>>^ O Senhor disse-lhe: “Mete de novo a mão em teu seio”. Ele meteu de novo a mão em seu seio e, retirando-a, eis que ela se tornara como o restante de sua carne.

[[v2-4-8]]

^<<v2-4-8,8>>^ “Se não te crerem, nem obedecerem à voz do primeiro prodígio, crerão à voz do segundo.

[[v2-4-9]]

^<<v2-4-9,9>>^ Se ainda permanecerem incrédulos diante desses dois prodígios, nem te ouvirem, tomarás da água do Nilo e a derramarás por terra; a água tirada do rio se tornará sangue sobre a terra.”

[[v2-4-10]]

^<<v2-4-10,10>>^ Moisés disse ao Senhor: “Ah! Senhor! Eu não tenho o dom da palavra; nunca o tive, nem mesmo depois que falastes ao vosso servo; tenho a boca e a língua pesadas”.

[[v2-4-11]]

^<<v2-4-11,11>>^ O Senhor disse-lhe: “Quem deu uma boca ao homem? Quem o faz mudo ou surdo, o faz ver ou o faz cego? Não sou eu, o Senhor?

[[v2-4-12]]

^<<v2-4-12,12>>^ Vai, pois, eu estarei contigo quando falares, e te ensinarei o que terás de dizer”.

[[v2-4-13]]

^<<v2-4-13,13>>^ “Ah! Senhor! – disse Moisés – mandai quem quiserdes!”^&#42;1^

[[v2-4-14]]

^<<v2-4-14,14>>^ Então o Senhor irritou-se contra Moisés: “Não tens Aarão – disse ele – teu irmão, o levita? Eu sei que ele fala bem. Ei-lo justamente que vem ao teu encontro e, vendo-te, se alegrará o seu coração.

[[v2-4-15]]

^<<v2-4-15,15>>^ Tu lhe falarás, lhe porás as palavras na boca. E, quando falardes, eu estarei contigo e com ele, e vos ensinarei o que tereis a fazer.

[[v2-4-16]]

^<<v2-4-16,16>>^ É ele quem falará ao povo em teu lugar: ele te servirá de boca e tu lhe servirás de Deus.

[[v2-4-17]]

^<<v2-4-17,17>>^ Toma em tua mão esta vara, com a qual operarás prodígios”.

[[v2-4-18]]

^<<v2-4-18,18>>^ Moisés partiu. De volta para junto de Jetro, seu sogro, disse-lhe: “Rogo-te que me deixes partir, e voltar para junto de meus irmãos no Egito; vou ver se ainda vivem”. Jetro disse a Moisés: “Vai em paz”.

[[v2-4-19]]

^<<v2-4-19,19>>^ O Senhor disse a Moisés em Madiã: “Vai, volta ao Egito, porque todos aqueles que atentavam contra a tua vida estão mortos”.

[[v2-4-20]]

^<<v2-4-20,20>>^ Moisés tomou consigo sua mulher e seus filhos, fê-los montar em jumentos e voltou para o Egito. Levava na mão a vara de Deus.

[[v2-4-21]]

^<<v2-4-21,21>>^ O Senhor disse a Moisés: “Agora que voltas ao Egito, cuida para que todos os prodígios, que te concedi o poder de operar, tu os faças na presença do faraó. Mas endurecerei o seu coração e ele não deixará partir o povo.

[[v2-4-22]]

^<<v2-4-22,22>>^ Tu lhe dirás: Assim fala o Senhor: Israel é meu filho primogênito.

[[v2-4-23]]

^<<v2-4-23,23>>^ Eu te digo: Deixa ir o meu filho, para que ele me preste um culto. Se te recusas a deixá-lo partir, farei perecer teu filho primogênito”.^&#42;1^

[[v2-4-24]]

^<<v2-4-24,24>>^ Estando Moisés a caminho, numa estalagem, o Senhor atacou Moisés, procurando matá-lo.^&#42;1^

[[v2-4-25]]

^<<v2-4-25,25>>^ Sefra tomou então uma pedra afiada, cortou o prepúcio de seu filho e atirou-o aos pés de Moisés, dizendo: “Tu me és um esposo de sangue!”.

[[v2-4-26]]

^<<v2-4-26,26>>^ Assim o Senhor o deixou. Sefra havia dito: “esposo de sangue”, por causa da circuncisão.^&#42;1^

[[v2-4-27]]

^<<v2-4-27,27>>^ O Senhor disse a Aarão: “Vai ao encontro de Moisés no deserto”. Aarão foi e, encontrando seu irmão na montanha de Deus, beijou-o.

[[v2-4-28]]

^<<v2-4-28,28>>^ Moisés contou-lhe tudo o que lhe tinha dito o Senhor ao enviá-lo, e todos os prodígios que lhe tinha ordenado fazer.

[[v2-4-29]]

^<<v2-4-29,29>>^ Moisés e Aarão continuaram seu caminho e reuniram todos os anciãos de Israel.

[[v2-4-30]]

^<<v2-4-30,30>>^ Aarão repetiu todas as palavras que o Senhor tinha dito a Moisés, e este fez os prodígios em presença do povo.

[[v2-4-31]]

^<<v2-4-31,31>>^ O povo acreditou. E, tendo ouvido que o Senhor viera visitar os filhos de Israel, e que vira sua aflição, inclinaram-se e prostraram-se.

'''

xref:002-exodo/002-exodo-003.adoc#v2-3-0[&#60; Capítulo Anterior] | <<v2-4-0,Topo>> | xref:002-exodo/002-exodo-005.adoc#v2-5-0[Próximo Capítulo &#62;]