include::./index.adoc[]

[[v2-19-0]]
=== Êxodo, 19
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Êxodo 19 trata do momento em que Deus se revela ao povo de Israel no monte Sinai. Ele instrui Moisés a subir a montanha e receber os mandamentos da lei, para que o povo saiba como se comportar diante da presença divina. O capítulo é marcado por uma forte sensação de santidade e temor, e mostra como Deus se comunica com seu povo de maneira direta e poderosa. A partir dessa premissa, podemos encontrar os seguintes versículos relacionados:
* Salmos 68:8: "A terra estremeceu, e os céus gotejaram perante a face de Deus; o próprio Sinai tremeu perante a face de Deus, o Deus de Israel." Este versículo descreve a intensidade da presença divina no monte Sinai, como se fosse um evento sísmico que abalou toda a região.
* Mateus 5:17: "Não penseis que vim revogar a lei ou os profetas; não vim revogar, vim cumprir." Jesus, em seu discurso do sermão da montanha, reafirma a importância da lei de Deus como um guia para a conduta humana, assim como foi revelada a Moisés no monte Sinai.
* Hebreus 12:18-21: "Pois não chegastes ao fogo palpável, nem à escuridão, nem à tempestade, nem ao som de trombeta, nem à voz de palavras, a qual os que a ouviram pediram que não se lhes falasse mais; porque não podiam suportar o que lhes era ordenado: Se até um animal tocar o monte, será apedrejado." Este trecho do Novo Testamento faz referência ao momento em que Deus se revelou a Moisés no monte Sinai, descrevendo a santidade e o temor que envolviam essa experiência.
* Atos 7:38: "Este é o que esteve entre a congregação no deserto, com o anjo que lhe falava no monte Sinai, e com nossos pais, e recebeu palavras vivas para no-las transmitir." Este versículo se refere a Moisés como o intermediário entre Deus e o povo de Israel, que recebeu as leis divinas diretamente no monte Sinai e as transmitiu aos demais.
* Apocalipse 19:16: "Na sua veste e na sua coxa tem escrito este nome: REI DOS REIS E SENHOR DOS SENHORES." Esse versículo descreve a figura divina de Jesus, que é representado como o rei supremo que governa sobre toda a criação, incluindo a lei que foi revelada a Moisés no monte Sinai.
****

[[v2-19-1]]

^<<v2-19-1,1>>^ No terceiro mês depois de sua saída do Egito, naquele dia, os israelitas entraram no deserto do Sinai.

[[v2-19-2]]

^<<v2-19-2,2>>^ Tendo partido de Rafidim, chegaram ao deserto do Sinai, onde acamparam. Ali se estabeleceu Israel em frente ao monte.

[[v2-19-3]]

^<<v2-19-3,3>>^ Moisés subiu em direção a Deus, e o Senhor o chamou do alto da montanha nestes termos: “Eis o que dirás à família de Jacó, eis o que anunciarás aos filhos de Israel:

[[v2-19-4]]

^<<v2-19-4,4>>^ Vistes o que fiz aos egípcios, e como vos tenho trazido sobre asas de águia para junto de mim.

[[v2-19-5]]

^<<v2-19-5,5>>^ Agora, pois, se obedecerdes à minha voz, e guardardes a minha aliança, sereis o meu povo particular entre todos os povos. Toda a terra é minha,

[[v2-19-6]]

^<<v2-19-6,6>>^ mas vós me sereis um reino de sacerdotes e uma nação consagrada. Tais são as palavras que dirás aos israelitas”.^&#42;1^

[[v2-19-7]]

^<<v2-19-7,7>>^ Veio Moisés e, convocando os anciãos do povo, comunicou-lhes as palavras que o Senhor lhe ordenara repetir.

[[v2-19-8]]

^<<v2-19-8,8>>^ E todo o povo respondeu a uma voz: “Faremos tudo o que o Senhor disse”. Moisés referiu ao Senhor as palavras do povo.

[[v2-19-9]]

^<<v2-19-9,9>>^ Então o Senhor lhe disse: “Eis que me vou aproximar de ti na obscuridade de uma nuvem, a fim de que o povo ouça quando eu te falar, e para que também confie em ti para sempre”. E Moisés referiu as palavras do povo ao Senhor,

[[v2-19-10]]

^<<v2-19-10,10>>^ o qual lhe disse: “Vai ter com o povo, e santifica-o hoje e amanhã. Que lavem as suas vestes^&#42;1^

[[v2-19-11]]

^<<v2-19-11,11>>^ e estejam prontos para o terceiro dia, porque, depois de amanhã, o Senhor descerá à vista de todo o povo sobre o monte Sinai.

[[v2-19-12]]

^<<v2-19-12,12>>^ Fixarás ao redor limites ao povo, e lhe dirás: Guardai-vos de subir ao monte ou de tocar a sua base! Se alguém tocar o monte, será morto.

[[v2-19-13]]

^<<v2-19-13,13>>^ Não se lhe tocará com a mão, mas ele será apedrejado ou perecerá pelas flechas: homem ou animal, não ficará vivo. Quando soar a trombeta, somente então subirão eles ao monte”.

[[v2-19-14]]

^<<v2-19-14,14>>^ Moisés desceu do monte para junto do povo e o santificou; e lavaram as suas vestes.

[[v2-19-15]]

^<<v2-19-15,15>>^ Em seguida, disse-lhes: “Estai prontos para depois de amanhã, não vos aproximeis de mulher alguma”.

[[v2-19-16]]

^<<v2-19-16,16>>^ Na manhã do terceiro dia, houve um estrondo de trovões e de relâmpagos; uma espessa nuvem cobria a montanha e o som da trombeta soou com força. Toda a multidão que estava no acampamento tremia.

[[v2-19-17]]

^<<v2-19-17,17>>^ Moisés levou o povo para fora do acampamento ao encontro de Deus, e pararam ao pé do monte.

[[v2-19-18]]

^<<v2-19-18,18>>^ Todo o monte Sinai fumegava, porque o Senhor tinha descido sobre ele no meio de chamas; o fumo que subia do monte era como a fumaça de uma fornalha, e toda a montanha tremia com violência.

[[v2-19-19]]

^<<v2-19-19,19>>^ O som da trombeta soava ainda mais forte; Moisés falava e os trovões divinos respondiam-lhe.

[[v2-19-20]]

^<<v2-19-20,20>>^ O Senhor desceu sobre o cume do monte Sinai; e chamou Moisés ao cume do monte. Moisés subiu,

[[v2-19-21]]

^<<v2-19-21,21>>^ e o Senhor lhe disse: “Desce e proíbe expressamente o povo de precipitar-se para ver o Senhor, para que não morra um grande número deles.

[[v2-19-22]]

^<<v2-19-22,22>>^ Também os sacerdotes, que são autorizados a se aproximar do Senhor, santifiquem-se, para que o Senhor não os fira”.

[[v2-19-23]]

^<<v2-19-23,23>>^ Moisés respondeu ao Senhor: “O povo não poderia subir ao monte Sinai, pois vós no-lo ordenastes expressamente, dizendo: fixa limites ao redor do monte, e declara-o sagrado”.

[[v2-19-24]]

^<<v2-19-24,24>>^ “Vai – disse-lhe o Senhor – desce. Subirás em seguida com Aarão; porém, não ultrapassem os limites os sacerdotes e o povo ao subir junto do Senhor, para não acontecer que ele os fira.”

[[v2-19-25]]

^<<v2-19-25,25>>^ Moisés desceu então ao povo e falou-lhe.^&#42;1^

'''

xref:002-exodo/002-exodo-018.adoc#v2-18-0[&#60; Capítulo Anterior] | <<v2-19-0,Topo>> | xref:002-exodo/002-exodo-020.adoc#v2-20-0[Próximo Capítulo &#62;]