include::./index.adoc[]

[[v2-22-0]]
=== Êxodo, 22
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 22 do livro de Êxodo contém leis sobre compensação financeira para roubos, danos, empréstimos, dentre outras questões relacionadas ao tratamento justo e equitativo entre os membros da comunidade. Abaixo estão cinco versículos relacionados com esses temas:
* Deuteronômio 24:6 - "Não tomarás em penhor a mó de mão nem a deita do sol, porque isso seria tomar em penhor a própria vida do devedor." Este versículo aborda a questão do penhor, mencionada em Êxodo 22:26-27, e destaca a importância de proteger a vida e os meios de subsistência dos devedores.
* Provérbios 20:10 - "Dois pesos, duas medidas, tanto um como outro são abomináveis ao Senhor." Esse versículo trata da questão da justiça e da equidade na aplicação da lei, que é um tema recorrente em Êxodo 22.
* Levítico 19:13 - "Não oprimirás o teu próximo, nem o roubarás; não reterás o salário do jornaleiro contigo até pela manhã." Este versículo destaca a importância de tratar os trabalhadores com justiça e pagar-lhes o que lhes é devido, o que é relevante para algumas leis em Êxodo 22:10-15.
* Provérbios 22:22-23 - "Não roubes ao pobre, porque é pobre, nem esmagues ao aflito à porta; porque o Senhor defenderá a sua causa em detrimento da tua vida." Esse versículo aborda a questão do roubo e da exploração dos vulneráveis, que também é abordada em Êxodo 22:21-24.
* Deuteronômio 22:1-4 - "Se vires extraviado o boi ou a ovelha de teu irmão, não te furtarás a trazê-los de volta; será teu irmão que perdeste; não te furtarás a fazer o mesmo com o seu jumento. [...] Não porás mordaça no boi, quando debulha." Esses versículos destacam a importância da responsabilidade comunitária e do cuidado com os animais, temas que são relevantes para algumas leis em Êxodo 22:5-6 e 19.
****

[[v2-22-1]]

^<<v2-22-1,1>>^ (Se o ladrão, surpreendido de noite em flagrante delito de arrombamento, for ferido de morte, não haverá homicídio;

[[v2-22-2]]

^<<v2-22-2,2>>^ mas se o sol já se tiver levantado, haverá homicídio.) Ele fará a restituição: se não tiver nada, será vendido em compensação do seu roubo.

[[v2-22-3]]

^<<v2-22-3,3>>^ Se o que ele roubou, boi, jumento ou ovelha, estiver ainda vivo em suas mãos, restituirá o dobro.

[[v2-22-4]]

^<<v2-22-4,4>>^ Se um homem fizer estragos num campo ou numa vinha, ou deixar seus animais pastarem no campo de outro, compensará o dano com o melhor de seu campo e de sua vinha.

[[v2-22-5]]

^<<v2-22-5,5>>^ Se um fogo se acender, alastrar-se pelos espinheiros e consumir o trigo enfeixado ou de pé, ou então todo o campo, o autor do incêndio pagará indenização (pelos danos).

[[v2-22-6]]

^<<v2-22-6,6>>^ Se um homem confiar dinheiro ou objetos à guarda de outro, e estes forem roubados na casa deste último, o ladrão, uma vez descoberto, restituirá o dobro.

[[v2-22-7]]

^<<v2-22-7,7>>^ Se o ladrão não for descoberto, o dono da casa se apresentará diante de Deus (para jurar) que ele não pôs a mão sobre os bens do seu próximo.

[[v2-22-8]]

^<<v2-22-8,8>>^ Em toda questão fraudulenta, quer se trate de um boi, de um jumento, de uma ovelha, de uma veste, quer se trate de qualquer outro objeto perdido, do qual se dirá: esta é a coisa, o litígio entre as duas partes irá diante de Deus, e aquele que Deus declarar culpado restituirá o dobro ao seu próximo.

[[v2-22-9]]

^<<v2-22-9,9>>^ Se um homem confiar à guarda de outro um boi, uma ovelha ou um animal qualquer, e este morrer, ou quebrar um membro, ou for roubado sem que haja testemunha,

[[v2-22-10]]

^<<v2-22-10,10>>^ o juramento do Senhor intervirá entre as duas partes para que se saiba se o responsável pela guarda do animal não pôs a mão sobre o bem do seu próximo. O proprietário aceitará esse juramento, sem que haja restituição.

[[v2-22-11]]

^<<v2-22-11,11>>^ Se o animal foi roubado de sua casa, ele indenizará o proprietário.

[[v2-22-12]]

^<<v2-22-12,12>>^ Se foi dilacerado por uma fera, a trará como testemunho e não terá de pagar pelo animal dilacerado.

[[v2-22-13]]

^<<v2-22-13,13>>^ Se um homem emprestar a outro um animal, e este quebrar um membro ou morrer na ausência do seu proprietário, terá de haver indenização.

[[v2-22-14]]

^<<v2-22-14,14>>^ Se o proprietário estiver presente, não haverá indenização. Se o animal tiver sido alugado, o preço do aluguel bastará.”

[[v2-22-15]]

^<<v2-22-15,15>>^ “Se um homem seduzir uma virgem que não é noiva, e dormir com ela, pagará o seu dote e a desposará.

[[v2-22-16]]

^<<v2-22-16,16>>^ Se o pai recusar ceder-lha, pagará em dinheiro o valor do dote das virgens.

[[v2-22-17]]

^<<v2-22-17,17>>^ Não deixarás viver uma feiticeira.

[[v2-22-18]]

^<<v2-22-18,18>>^ Quem tiver comércio com um animal, será morto.

[[v2-22-19]]

^<<v2-22-19,19>>^ Aquele que oferecer sacrifícios a outros deuses fora do Senhor, será votado ao interdito.

[[v2-22-20]]

^<<v2-22-20,20>>^ Não maltratarás o estrangeiro e não o oprimirás, porque foste estrangeiro no Egito.^&#42;1^

[[v2-22-21]]

^<<v2-22-21,21>>^ Não prejudicareis a viúva e o órfão.

[[v2-22-22]]

^<<v2-22-22,22>>^ Se os prejudicardes, eles clamarão a mim e eu os ouvirei;

[[v2-22-23]]

^<<v2-22-23,23>>^ minha cólera se inflamará e vos farei perecer pela espada; vossas mulheres ficarão viúvas e vossos filhos, órfãos.

[[v2-22-24]]

^<<v2-22-24,24>>^ Se emprestares dinheiro a alguém do meu povo, ao pobre que está contigo, não lhe serás como um credor: não lhe exigirás juros.

[[v2-22-25]]

^<<v2-22-25,25>>^ Se tomares como penhor o manto de teu próximo, tu o devolverás a ele antes do pôr do sol,

[[v2-22-26]]

^<<v2-22-26,26>>^ porque é a sua única cobertura, é a veste com que cobre sua nudez; com que dormirá ele? Se me invocasse, eu o ouviria, porque sou misericordioso.

[[v2-22-27]]

^<<v2-22-27,27>>^ Não amaldiçoarás Deus; não amaldiçoarás um príncipe de teu povo.

[[v2-22-28]]

^<<v2-22-28,28>>^ Não tardarás a oferecer-me as primícias de tua colheita e de tua vindima. Tu me darás o primogênito de teus filhos.

[[v2-22-29]]

^<<v2-22-29,29>>^ Da mesma forma, farás com o primogênito de tua vaca e de tua ovelha: ficará sete dias com sua mãe e no oitavo dia tu o entregarás a mim.

[[v2-22-30]]

^<<v2-22-30,30>>^ Vós sereis para mim homens consagrados. Não comereis carne de um animal dilacerado no campo: vós os jogareis aos cães.”

'''

xref:002-exodo/002-exodo-021.adoc#v2-21-0[&#60; Capítulo Anterior] | <<v2-22-0,Topo>> | xref:002-exodo/002-exodo-023.adoc#v2-23-0[Próximo Capítulo &#62;]