include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Êxodo 14 narra a história da travessia do Mar Vermelho pelo povo de Israel, enquanto eles fugiam da escravidão no Egito. O capítulo começa com Deus dando instruções a Moisés sobre como acampar diante do mar e continua com a perseguição do faraó e seu exército até a chegada do momento em que o Mar Vermelho é dividido e o povo de Israel é salvo. Abaixo estão cinco versículos relacionados aos temas abordados em Êxodo 14:
* Salmos 77:19: "Teu caminho passou pelo mar, o teu caminho pelas águas poderosas, e ninguém conheceu as tuas pegadas." Este versículo fala sobre a maravilhosa intervenção de Deus na travessia do Mar Vermelho, destacando a grandeza e o poder do seu caminho.
* Isaías 43:2: "Quando passares pelas águas, estarei contigo, e quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti." Este versículo traz a promessa de Deus de que estará com o seu povo em todos os momentos, inclusive nas situações mais difíceis e perigosas.
* 1 Coríntios 10:1-2: "Porque não quero, irmãos, que ignoreis que nossos pais estiveram todos debaixo da nuvem, e todos passaram pelo mar; e todos foram batizados em Moisés, na nuvem e no mar." Este versículo faz referência ao evento da travessia do Mar Vermelho como um batismo, simbolizando a separação do povo de Israel da escravidão e sua união com Deus.
* Hebreus 11:29: "Pela fé atravessaram o Mar Vermelho como por terra seca; tentando-o os egípcios, foram tragados pelas águas." Este versículo destaca a importância da fé na travessia do Mar Vermelho, mostrando que foi a confiança no poder e na fidelidade de Deus que permitiu que o povo de Israel passasse a salvo.
* Salmos 106:9: "Repreendeu o Mar Vermelho, e este se secou; ele os fez caminhar pelos abismos como pelo deserto." Este salmo faz referência ao evento que aconteceu em Êxodo 14:21, quando Deus abriu o Mar Vermelho para que os israelitas pudessem atravessá-lo a pé enxuto.
****

[[v2-14-1]]

^<<v2-14-1,1>>^ O Senhor disse a Moisés:

[[v2-14-2]]

^<<v2-14-2,2>>^ “Dize aos israelitas que mudem de direção e venham acampar diante de Piairot, entre Magdol e o mar, defronte de Baal Sefon: acampareis defronte desse lugar, perto do mar.

[[v2-14-3]]

^<<v2-14-3,3>>^ O faraó vai pensar: os israelitas perderam-se no país, e o deserto fechou-lhes a passagem.

[[v2-14-4]]

^<<v2-14-4,4>>^ Endurecerei o coração do faraó, e ele os perseguirá; mas eu triunfarei gloriosamente sobre o faraó e sobre todo o seu exército, e os egípcios saberão que eu sou o Senhor”. Os israelitas obedeceram.

[[v2-14-5]]

^<<v2-14-5,5>>^ Quando se anunciou ao rei do Egito que o povo tinha fugido, o coração do faraó e de seus servos voltou-se contra o povo: “Que fizemos – disseram eles – deixando partir Israel e renunciando assim ao seu serviço!”.

[[v2-14-6]]

^<<v2-14-6,6>>^ O faraó mandou preparar seu carro e levou com ele suas tropas.

[[v2-14-7]]

^<<v2-14-7,7>>^ Escolheu seiscentos carros dos melhores e todos os carros egípcios com homens de guerra em cada um deles.

[[v2-14-8]]

^<<v2-14-8,8>>^ O Senhor endureceu o coração do faraó, rei do Egito, e este se pôs a perseguir os filhos de Israel. Eles haviam partido de cabeça erguida.^&#42;1^

[[v2-14-9]]

^<<v2-14-9,9>>^ Puseram-se os egípcios a persegui-los e alcançaram-nos em seu acampamento à beira do mar: todos os cavalos dos carros do faraó, seus cavaleiros e seu exército alcançaram-nos perto de Piairot, defronte de Baal Sefon.

[[v2-14-10]]

^<<v2-14-10,10>>^ Aproximando-se o faraó, os israelitas, ao levantarem os olhos, viram os egípcios que vinham ao seu encalço. Foram tomados de espanto e invocaram o Senhor, clamando em alta voz.

[[v2-14-11]]

^<<v2-14-11,11>>^ E disseram a Moisés: “Não havia, porventura, túmulos no Egito, para que nos conduzisses a morrer no deserto? Por que nos fizeste isso, tirando-nos do Egito?

[[v2-14-12]]

^<<v2-14-12,12>>^ Não te dizíamos no Egito: deixa-nos servir os egípcios! É melhor ser escravos dos egípcios do que morrer no deserto”.

[[v2-14-13]]

^<<v2-14-13,13>>^ Moisés respondeu ao povo: “Não temais! Tende ânimo, e vereis a libertação que o Senhor vai operar hoje em vosso favor. Os egípcios que hoje vedes, não os tornareis a ver jamais.

[[v2-14-14]]

^<<v2-14-14,14>>^ O Senhor combaterá por vós; quanto a vós, nada tereis a fazer”.

[[v2-14-15]]

^<<v2-14-15,15>>^ O Senhor disse a Moisés: “Por que clamas a mim? Dize aos filhos de Israel que se ponham a caminho.

[[v2-14-16]]

^<<v2-14-16,16>>^ E tu, levanta a tua vara, estende a mão sobre o mar e fere-o, para que os israelitas possam atravessá-lo a pé enxuto.

[[v2-14-17]]

^<<v2-14-17,17>>^ Vou endurecer o coração dos egípcios, para que se ponham ao teu encalço, e triunfarei gloriosamente sobre o faraó e sobre todo o seu exército, seus carros e seus cavaleiros.

[[v2-14-18]]

^<<v2-14-18,18>>^ Os egípcios saberão que eu sou o Senhor quando tiver alcançado esse glorioso triunfo sobre o faraó, seus carros e seus cavaleiros”.

[[v2-14-19]]

^<<v2-14-19,19>>^ O anjo de Deus, que marchava à frente do exército dos israelitas, mudou de lugar e passou para trás; a coluna de nuvens que os precedia pôs-se detrás deles,

[[v2-14-20]]

^<<v2-14-20,20>>^ entre o acampamento dos egípcios e o de Israel. Era obscura, e alumiava a noite. E não puderam aproximar-se um do outro, durante a noite inteira.^&#42;1^

[[v2-14-21]]

^<<v2-14-21,21>>^ Moisés estendeu a mão sobre o mar. O Senhor fê-lo recuar com um vento impetuoso vindo do oriente, que soprou toda a noite. E pôs o mar a seco. As águas dividiram-se

[[v2-14-22]]

^<<v2-14-22,22>>^ e os israelitas desceram a pé enxuto no meio do mar, enquanto as águas formavam uma muralha à direita e à esquerda.

[[v2-14-23]]

^<<v2-14-23,23>>^ Os egípcios os perseguiram: todos os cavalos do faraó, seus carros e seus cavaleiros internaram-se após eles no leito do mar.

[[v2-14-24]]

^<<v2-14-24,24>>^ À vigília da manhã, o Senhor, do alto da coluna de fogo e da de nuvens, olhou para o acampamento dos egípcios e semeou o pânico no meio deles.^&#42;1^

[[v2-14-25]]

^<<v2-14-25,25>>^ Embaraçou-lhes as rodas dos carros de tal sorte que, só dificilmente, conseguiam avançar. Disseram então os egípcios: “Fujamos diante de Israel, porque o Senhor combate por eles contra o Egito”.

[[v2-14-26]]

^<<v2-14-26,26>>^ O Senhor disse a Moisés: “Estende tua mão sobre o mar, e as águas se voltarão sobre os egípcios, seus carros e seus cavaleiros”.

[[v2-14-27]]

^<<v2-14-27,27>>^ Moisés estendeu a mão sobre o mar, e este, ao romper da manhã, voltou ao seu nível habitual. Os egípcios que fugiam foram de encontro a ele, e o Senhor derribou os egípcios no meio do mar.

[[v2-14-28]]

^<<v2-14-28,28>>^ As águas voltaram e cobriram os carros, os cavaleiros e todo o exército do faraó que havia descido no mar ao encalço dos israelitas. Não ficou um sequer.

[[v2-14-29]]

^<<v2-14-29,29>>^ Mas os israelitas tinham andado a pé enxuto no leito do mar, enquanto as águas formavam uma muralha à direita e à esquerda.

[[v2-14-30]]

^<<v2-14-30,30>>^ Foi assim que naquele dia o Senhor livrou Israel da mão dos egípcios. E Israel viu os cadáveres dos egípcios na praia do mar.

[[v2-14-31]]

^<<v2-14-31,31>>^ Viu Israel o grande poder que o Senhor tinha exercido contra os egípcios. Por isso, o povo temeu o Senhor e confiou nele e em seu servo Moisés.

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]