include::./index.adoc[]

[[v2-26-0]]
=== Êxodo, 26
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 26 de Êxodo descreve as especificações para a construção do tabernáculo. Ele deve ser feito com cortinas de linho fino, com querubins de tecido azul, vermelho e púrpura bordados nelas. As cortinas devem ser suspensas por colunas de madeira de acácia revestidas de ouro e fixadas com ganchos e barras. A seguir estão cinco versículos relacionados com temas abordados em Êxodo 26:
* Hebreus 9:11: "Mas vindo Cristo, o sumo sacerdote dos bens futuros, por um maior e mais perfeito tabernáculo, não feito por mãos, isto é, não desta criação," Este versículo se relaciona com Êxodo 26, pois fala sobre o tabernáculo celestial, que é superior ao tabernáculo terreno construído de acordo com as especificações detalhadas no capítulo 26.
* 1 Coríntios 6:19: "Ou não sabeis que o nosso corpo é o templo do Espírito Santo, que habita em vós, proveniente de Deus, e que não sois de vós mesmos?" Esse versículo se relaciona com Êxodo 26, pois o tabernáculo terreno era um símbolo do lugar onde Deus habitava com o seu povo, assim como o Espírito Santo habita nos cristãos.
* João 1:14: "E o Verbo se fez carne, e habitou entre nós, e vimos a sua glória, como a glória do unigênito do Pai, cheio de graça e de verdade." Esse versículo se relaciona com Êxodo 26, pois o tabernáculo terreno era o lugar onde Deus habitava com o seu povo, assim como Jesus, que é a encarnação de Deus, habitou entre os homens.
* 1 Pedro 2:5: "Vós também, como pedras vivas, sois edificados casa espiritual e sacerdócio santo, para oferecer sacrifícios espirituais agradáveis a Deus por Jesus Cristo." Esse versículo se relaciona com Êxodo 26, pois o tabernáculo terreno era o lugar onde o povo oferecia sacrifícios a Deus, assim como os cristãos oferecem sacrifícios espirituais em suas próprias vidas como parte do sacerdócio santo.
* Apocalipse 21:3: "E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles, e será o seu Deus." Esse versículo se relaciona com Êxodo 26, pois o tabernáculo terreno era um símbolo do lugar onde Deus habitava com o seu povo, assim como o tabernáculo celestial descrito em Apocalipse será o lugar onde Deus habitará com os seus escolhidos.
****

[[v2-26-1]]

^<<v2-26-1,1>>^ “Farás o tabernáculo com dez cortinas de linho fino retorcido de púrpura violeta, púrpura escarlate e de carmesim, sobre as quais alguns querubins serão artisticamente bordados.

[[v2-26-2]]

^<<v2-26-2,2>>^ Cada cortina terá vinte e oito côvados de comprimento e quatro côvados de largura: terão todas as mesmas dimensões.

[[v2-26-3]]

^<<v2-26-3,3>>^ Cinco dessas cortinas serão juntas uma à outra, e as cinco outras igualmente.

[[v2-26-4]]

^<<v2-26-4,4>>^ Na orla da cortina que está na extremidade do primeiro grupo, porás laços de púrpura violeta; farás a mesma coisa na orla da cortina que remata o segundo grupo.

[[v2-26-5]]

^<<v2-26-5,5>>^ Farás cinquenta laços para a primeira cortina, e cinquenta para a extremidade da última cortina do segundo grupo, de modo que se correspondam.

[[v2-26-6]]

^<<v2-26-6,6>>^ Farás também cinquenta colchetes de ouro, com os quais juntarás as duas cortinas, a fim de que o tabernáculo forme um todo.

[[v2-26-7]]

^<<v2-26-7,7>>^ Farás também cortinas de peles de cabra para servirem de tenda sobre o tabernáculo: farás onze dessas cortinas.

[[v2-26-8]]

^<<v2-26-8,8>>^ O comprimento de uma dessas cortinas será de trinta côvados, e sua largura de quatro côvados. As onze cortinas terão todas as mesmas dimensões.

[[v2-26-9]]

^<<v2-26-9,9>>^ Juntarás de uma parte cinco dessas cortinas, e seis de outra parte, estando a sexta dobrada na parte dianteira da tenda.

[[v2-26-10]]

^<<v2-26-10,10>>^ Porás cinquenta laços na orla de cada uma das duas cortinas que estão na extremidade de cada grupo.

[[v2-26-11]]

^<<v2-26-11,11>>^ Farás cinquenta colchetes de bronze que introduzirás nos laços, e ajuntarás assim a tenda de modo que ela forme uma só peça.

[[v2-26-12]]

^<<v2-26-12,12>>^ E como essas cortinas terão um excedente de comprimento, o que sobrar cairá sobre o lado posterior do tabernáculo.

[[v2-26-13]]

^<<v2-26-13,13>>^ E o côvado excedente dos dois lados, no comprimento das cortinas da tenda, cairá sobre cada um dos dois lados do tabernáculo para cobri-lo.

[[v2-26-14]]

^<<v2-26-14,14>>^ Farás para a tenda uma cobertura de peles de carneiro, tingidas de vermelho, e por cima uma cobertura de peles de golfinho.

[[v2-26-15]]

^<<v2-26-15,15>>^ Farás também para o tabernáculo tábuas de madeira de acácia, que serão colocadas verticalmente.

[[v2-26-16]]

^<<v2-26-16,16>>^ O comprimento de uma tábua será de dez côvados, e a largura de um côvado e meio.

[[v2-26-17]]

^<<v2-26-17,17>>^ Cada tábua terá dois encaixes, unidos um ao outro. Assim farás com todas as tábuas do tabernáculo.

[[v2-26-18]]

^<<v2-26-18,18>>^ Farás, pois, para o tabernáculo vinte tábuas para o lado meridional, ao sul.

[[v2-26-19]]

^<<v2-26-19,19>>^ Porás sob essas vinte tábuas quarenta suportes de prata, dois sob cada tábua, para os seus dois encaixes.

[[v2-26-20]]

^<<v2-26-20,20>>^ Para o segundo lado do tabernáculo, ao norte, farás vinte tábuas,

[[v2-26-21]]

^<<v2-26-21,21>>^ com quarenta suportes de prata, à razão de dois por tábua.

[[v2-26-22]]

^<<v2-26-22,22>>^ Para o fundo do tabernáculo, ao ocidente, farás seis tábuas.

[[v2-26-23]]

^<<v2-26-23,23>>^ Para os ângulos do tabernáculo, farás duas tábuas;

[[v2-26-24]]

^<<v2-26-24,24>>^ serão emparelhadas desde a base, formando juntas uma só peça até o cimo, na primeira argola. Assim se fará com as duas tábuas colocadas nos ângulos.

[[v2-26-25]]

^<<v2-26-25,25>>^ Haverá, pois, oito tábuas, com seus suportes de prata em número de dezesseis, dois sob cada tábua.

[[v2-26-26]]

^<<v2-26-26,26>>^ Farás depois cinco travessas de madeira de acácia para as tábuas de um dos lados do tabernáculo,

[[v2-26-27]]

^<<v2-26-27,27>>^ cinco para as tábuas do segundo lado, e cinco para as tábuas que estão do lado posterior do tabernáculo, ao ocidente.

[[v2-26-28]]

^<<v2-26-28,28>>^ A travessa central passará pelo meio das tábuas, de uma extremidade à outra.

[[v2-26-29]]

^<<v2-26-29,29>>^ Recobrirás de ouro essas tábuas, e lhes porás argolas de ouro, por onde passarão as travessas que recobrirás também de ouro.

[[v2-26-30]]

^<<v2-26-30,30>>^ Levantarás o tabernáculo segundo o modelo que te foi mostrado sobre o monte.

[[v2-26-31]]

^<<v2-26-31,31>>^ Farás um véu de púrpura violeta, de púrpura escarlate, de carmesim e de linho retorcido, sobre o qual serão artisticamente bordados querubins.

[[v2-26-32]]

^<<v2-26-32,32>>^ Tu o suspenderás sobre quatro colunas de madeira de acácia revestidas de ouro, com pregos de ouro, sobre quatro pedestais de prata.

[[v2-26-33]]

^<<v2-26-33,33>>^ Colocarás o véu debaixo dos colchetes, e é ali, atrás do véu, que colocarás a arca da aliança. Esse véu servirá para separar o ‘santo’ do ‘santo dos santos’.

[[v2-26-34]]

^<<v2-26-34,34>>^ É no santo dos santos que colocarás a tampa sobre a arca da aliança.

[[v2-26-35]]

^<<v2-26-35,35>>^ Porás a mesa diante do véu, e o candelabro defronte da mesa, do lado meridional do tabernáculo; colocarás a mesa do lado norte.

[[v2-26-36]]

^<<v2-26-36,36>>^ Farás para a entrada da tenda um véu de púrpura violeta, de púrpura escarlate, de carmesim e de linho retorcido, artisticamente bordado.

[[v2-26-37]]

^<<v2-26-37,37>>^ E farás, para suspender ali esse véu, cinco colunas de acácia recobertas de ouro, munidas de colchetes de ouro; e para essas colunas fundirás cinco pedestais de bronze.”

'''

xref:002-exodo/002-exodo-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodo/002-exodo-027.adoc#v2-27-0[Próximo Capítulo &#62;]