include::./index.adoc[]

[[v2-6-0]]
=== Êxodo, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 6 do livro de Êxodo narra a continuação da conversa entre Deus e Moisés, na qual Deus reafirma sua promessa de libertar o povo de Israel da escravidão no Egito. Moisés então relata a mensagem divina para os israelitas, mas eles não acreditam nele devido à sua aflição. Em seguida, a genealogia de Moisés e Arão é registrada. Aqui estão cinco versículos relacionados aos temas abordados em Êxodo 6:
* Gênesis 15:13-14: "Então o Senhor disse a Abrão: "Saiba com certeza que seus descendentes serão estrangeiros em um país que não é deles, e eles serão escravizados e oprimidos por quatrocentos anos. Mas eu também julgarei a nação que servirão como escravos, e depois disso eles sairão com grande riqueza." Este versículo antecipa o destino dos descendentes de Abraão, que foram escravizados no Egito por 400 anos antes de serem libertados por Deus por meio de Moisés.
* Deuteronômio 7:8: "Mas foi porque o Senhor os amou e manteve o juramento que fez aos seus antepassados que ele os tirou com mão poderosa e os resgatou da escravidão no Egito." Este versículo destaca o amor de Deus por seu povo e a fidelidade à sua promessa de libertá-los da escravidão.
* Salmos 81:6-7: "Eu os removi dos ombros do opressor; suas mãos foram liberadas dos cestos de trabalho. Na sua angústia, vocês clamaram por mim e eu os livrei, eu os respondi da colina sagrada, eu os salvei." Este salmo lembra o povo de Israel da libertação que Deus lhes concedeu do Egito e como ele os libertou de sua opressão.
* Isaías 43:1-2: "Mas agora, assim diz o Senhor, aquele que criou você, ó Jacó, aquele que formou você, ó Israel: 'Não tenha medo, pois eu o redimi; eu o chamei pelo nome; você é meu. Quando você passar pelas águas, eu estarei com você; e quando você passar pelos rios, eles não o inundarão. Quando você andar através do fogo, você não será queimado; as chamas não o consumirão." Este versículo é um lembrete do cuidado de Deus pelo povo de Israel, mesmo durante os momentos difíceis, e sua promessa de estar sempre com eles.
* Jeremias 32:20-21: "Você realizou milagres e maravilhas no Egito e os realizou até hoje, tanto em Israel como entre outras pessoas, e se tornou famoso. Com sua mão poderosa e braço estendido, você redimiu seu povo, os descendentes de Jacó e José." Este versículo destaca o poder de Deus e a libertação que ele concedeu ao povo de Israel no Egito, que continuou a ser lembrada e celebrada.
****

[[v2-6-1]]

^<<v2-6-1,1>>^ O Senhor respondeu: “Verás o que vou fazer ao faraó: forçado por mão poderosa, ele os deixará partir; forçado por mão poderosa, ele os expulsará de sua terra”.

[[v2-6-2]]

^<<v2-6-2,2>>^ Deus disse a Moisés: “Eu sou o Senhor.

[[v2-6-3]]

^<<v2-6-3,3>>^ Apareci a Abraão, a Isaac e a Jacó como o Deus Todo-poderoso, mas não me dei a conhecer a eles pelo meu nome, Javé.

[[v2-6-4]]

^<<v2-6-4,4>>^ Eu me comprometi com eles a lhes dar a terra de Canaã, a terra onde levaram uma vida errante e habitaram como estrangeiros.

[[v2-6-5]]

^<<v2-6-5,5>>^ Ouvi o clamor dos israelitas oprimidos pelos egípcios, e lembrei-me de minha aliança.

[[v2-6-6]]

^<<v2-6-6,6>>^ Por isso, dize aos israelitas: Eu sou o Senhor; vou libertar-vos do jugo dos egípcios e livrar-vos de sua servidão. Estenderei o braço para essa libertação e manifestarei uma terrível justiça.

[[v2-6-7]]

^<<v2-6-7,7>>^ Eu vos tomarei para meu povo e serei o vosso Deus, e sabereis que eu sou o Senhor, vosso Deus, que vos terei libertado do jugo dos egípcios.

[[v2-6-8]]

^<<v2-6-8,8>>^ Eu vos introduzirei na terra que jurei dar a Abraão, a Isaac e a Jacó: e vos darei a possessão dessa terra, eu, o Senhor”.

[[v2-6-9]]

^<<v2-6-9,9>>^ Moisés repetiu essas palavras aos israelitas, mas estes não o ouviram, tão grande era o abatimento de sua alma e penosa a sua servidão.

[[v2-6-10]]

^<<v2-6-10,10>>^ O Senhor disse então a Moisés:

[[v2-6-11]]

^<<v2-6-11,11>>^ “Vai pedir ao faraó, rei do Egito, que deixe sair de sua terra os israelitas”.

[[v2-6-12]]

^<<v2-6-12,12>>^ Moisés respondeu ao Senhor: “Os israelitas não me ouviram; como me ouvirá o faraó, a mim que não tenho o dom da palavra?”.^&#42;1^

[[v2-6-13]]

^<<v2-6-13,13>>^ O Senhor falou a Moisés e a Aarão, e deu-lhes a ordem de irem ter com o faraó, rei do Egito, a fim de tirarem da terra do Egito os filhos de Israel.

[[v2-6-14]]

^<<v2-6-14,14>>^ Eis os chefes das famílias dos israelitas: filhos de Rúben, primogênito de Israel: Henoc, Falu, Hesron e Carmi. Estas são as famílias de Rúben.

[[v2-6-15]]

^<<v2-6-15,15>>^ Filhos de Simeão: Jamuel, Jamin, Aod, Jaquin, Soar e Saul, filho da cananeia. Estas são as famílias de Simeão.

[[v2-6-16]]

^<<v2-6-16,16>>^ Eis os nomes dos filhos de Levi, por ordem de gerações: Gérson, Caat e Merari. A duração da vida de Levi foi de cento e trinta e sete anos.

[[v2-6-17]]

^<<v2-6-17,17>>^ Filhos de Gérson: Lobni e Semei, e suas famílias.

[[v2-6-18]]

^<<v2-6-18,18>>^ Filhos de Caat: Amram, Isaar, Hebron e Oziel. A duração de vida de Caat foi de cento e trinta e três anos.

[[v2-6-19]]

^<<v2-6-19,19>>^ Filhos de Merari: Mooli e Musi. Tais são as famílias de Levi por ordem de gerações.

[[v2-6-20]]

^<<v2-6-20,20>>^ Amram desposou Jocabed, sua tia, que lhe deu Aarão e Moisés. A duração de vida de Amram foi de cento e trinta e sete anos.

[[v2-6-21]]

^<<v2-6-21,21>>^ Filhos de Isaar: Coré, Nefeg e Zecri.

[[v2-6-22]]

^<<v2-6-22,22>>^ Filhos de Oziel: Misael, Elisafã e Setri.

[[v2-6-23]]

^<<v2-6-23,23>>^ Aarão desposou Isabel, filha de Aminadab, irmã de Naasson; ela lhe deu Nadab, Abiú, Eleazar e Itamar.

[[v2-6-24]]

^<<v2-6-24,24>>^ Filhos de Coré: Aser, Elcana e Abiasaf; estas são as famílias dos coreítas.

[[v2-6-25]]

^<<v2-6-25,25>>^ Eleazar, filho de Aarão, desposou uma das filhas de Futiel, que lhe deu Fineias. Tais são os chefes das famílias dos levitas, com suas famílias.

[[v2-6-26]]

^<<v2-6-26,26>>^ Estes são Aarão e Moisés, a quem o Senhor disse: “Fazei sair do Egito os israelitas, segundo os seus exércitos”.

[[v2-6-27]]

^<<v2-6-27,27>>^ Foram eles que falaram ao faraó, rei do Egito, para tirar do Egito os israelitas. São estes Moisés e Aarão.

[[v2-6-28]]

^<<v2-6-28,28>>^ Quando o Senhor falou a Moisés no Egito,

[[v2-6-29]]

^<<v2-6-29,29>>^ ele o fez nestes termos: “Eu sou o Senhor. Repete ao faraó, rei do Egito, tudo o que te digo”.

[[v2-6-30]]

^<<v2-6-30,30>>^ E Moisés respondeu-lhe: “Eu não tenho o dom da palavra; como me ouvirá o faraó?”.

'''

xref:002-exodo/002-exodo-005.adoc#v2-5-0[&#60; Capítulo Anterior] | <<v2-6-0,Topo>> | xref:002-exodo/002-exodo-007.adoc#v2-7-0[Próximo Capítulo &#62;]