include::./index.adoc[]

[[v2-32-0]]
=== Êxodo, 32
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Êxodo 32 descreve a infidelidade do povo de Israel ao fazer um bezerro de ouro para adorar, enquanto Moisés estava no Monte Sinai recebendo os mandamentos de Deus. O capítulo mostra a ira de Deus diante dessa idolatria e a intercessão de Moisés em favor do povo. Abaixo seguem cinco versículos relacionados com os temas abordados em Êxodo 32:
* Deuteronômio 9:16-17: "E vi que havíeis pecado contra o Senhor vosso Deus; havíeis feito para vós um bezerro de fundição; depressa vos desviastes do caminho que o Senhor vos tinha ordenado. Então peguei nas duas tábuas, lancei-as das minhas mãos e as despedacei diante dos vossos olhos." Este versículo descreve como Moisés quebra as tábuas com os mandamentos de Deus, quando vê a idolatria do povo de Israel. Isso mostra a gravidade do pecado do povo e a ira de Deus diante dessa infidelidade.
* Deuteronômio 9:18: "Depois prostrei-me perante o Senhor, como antes, quarenta dias e quarenta noites; não comi pão, nem bebi água, por causa de todo o vosso pecado que havíeis cometido, fazendo o mal aos olhos do Senhor, para o provocar à ira." Aqui, vemos a intercessão de Moisés em favor do povo, mostrando sua compaixão e sua disposição em jejuar e orar por eles, mesmo diante da gravidade de seus pecados.
* Deuteronômio 9:21: "Então tomei o vosso pecado, o bezerro que tínheis feito, e o queimei a fogo, e o despedacei, moendo-o muito bem, até que se fez em pó; e o seu pó lancei ao ribeiro que descia do monte." Este versículo descreve como Moisés queima e destrói o bezerro de ouro que o povo havia feito para adorar, como um ato de purificação e arrependimento diante de Deus.
* Deuteronômio 9:26: "Então orei ao Senhor, dizendo: Ó Senhor Deus, não destruas o teu povo e a tua herança, que resgataste com a tua grandeza, que tiraste do Egito com mão poderosa." Aqui, vemos mais uma vez a intercessão de Moisés em favor do povo, mostrando sua preocupação com a salvação deles e sua confiança na misericórdia de Deus.
* Deuteronômio 9:29: "Mas são o teu povo e a tua herança, que tiraste com a tua grande força e com o teu braço estendido." Este versículo destaca a relação especial entre Deus e o povo de Israel, lembrando como Deus os libertou do Egito com grande poder e demonstrando sua fidelidade e compromisso com eles.
****

[[v2-32-1]]

^<<v2-32-1,1>>^ Vendo que Moisés tardava a descer da montanha, o povo agrupou-se em volta de Aarão e disse-lhe: “Vamos: faze-nos um deus que marche à nossa frente, porque esse Moisés, que nos tirou do Egito, não sabemos o que é feito dele”.^&#42;1^

[[v2-32-2]]

^<<v2-32-2,2>>^ Aarão respondeu-lhes: “Tirai os brincos de ouro que estão nas orelhas de vossas mulheres, vossos filhos e vossas filhas e trazei-me”.

[[v2-32-3]]

^<<v2-32-3,3>>^ Tiraram todos os brincos de ouro que tinham nas orelhas e os trouxeram a Aarão,

[[v2-32-4]]

^<<v2-32-4,4>>^ o qual, tomando-os em suas mãos, pôs o ouro em um molde e fez dele um bezerro de metal fundido. Então exclamaram: “Eis, ó Israel, o teu Deus que te tirou do Egito”.^&#42;1^

[[v2-32-5]]

^<<v2-32-5,5>>^ Aarão, vendo isso, construiu um altar diante dele e exclamou: “Amanhã haverá uma festa em honra do Senhor”.

[[v2-32-6]]

^<<v2-32-6,6>>^ No dia seguinte, pela manhã, ofereceram holocaustos e sacrifícios pacíficos. O povo assentou-se para comer e beber, e depois levantaram-se para se divertir.^&#42;1^

[[v2-32-7]]

^<<v2-32-7,7>>^ O Senhor disse a Moisés: “Vai, desce, porque se corrompeu o povo que tiraste do Egito.

[[v2-32-8]]

^<<v2-32-8,8>>^ Desviaram-se depressa do caminho que lhes prescrevi; fizeram para si um bezerro de metal fundido, prostraram-se diante dele e ofereceram-lhe sacrifícios, dizendo: Eis, ó Israel, o teu Deus que te tirou do Egito.

[[v2-32-9]]

^<<v2-32-9,9>>^ Vejo – continuou o Senhor – que esse povo tem a cabeça dura.

[[v2-32-10]]

^<<v2-32-10,10>>^ Deixa, pois, que se acenda minha cólera contra eles e os reduzirei a nada; mas de ti farei uma grande nação”.

[[v2-32-11]]

^<<v2-32-11,11>>^ Moisés tentou aplacar o Senhor, seu Deus, dizendo-lhe: “Por que, Senhor, se inflama a vossa ira contra o vosso povo que tirastes do Egito com o vosso poder e à força de vossa mão?

[[v2-32-12]]

^<<v2-32-12,12>>^ Não é bom que digam os egípcios: Com um mau desígnio os levou, para matá-los nas montanhas e suprimi-los da face da terra! Aplaque-se vosso furor, e abandonai vossa decisão de fazer mal ao vosso povo.

[[v2-32-13]]

^<<v2-32-13,13>>^ Lembrai-vos de Abraão, de Isaac e de Israel, vossos servos, aos quais jurastes por vós mesmo de tornar sua posteridade tão numerosa como as estrelas do céu e de dar aos seus descendentes essa terra de que falastes, como uma herança eterna”.

[[v2-32-14]]

^<<v2-32-14,14>>^ E o Senhor se arrependeu das ameaças que tinha proferido contra o seu povo.

[[v2-32-15]]

^<<v2-32-15,15>>^ Moisés desceu da montanha segurando nas mãos as duas tábuas da lei, que estavam escritas dos dois lados, sobre uma e outra face.

[[v2-32-16]]

^<<v2-32-16,16>>^ Eram obra de Deus, e a escritura nelas gravada era a escritura de Deus.

[[v2-32-17]]

^<<v2-32-17,17>>^ Ouvindo o barulho que o povo fazia com suas aclamações, Josué disse a Moisés: “Há gritos de guerra no acampamento!”.

[[v2-32-18]]

^<<v2-32-18,18>>^ “Não – respondeu Moisés – não são gritos de vitória, nem gritos de derrota: o que ouço são cantos.”

[[v2-32-19]]

^<<v2-32-19,19>>^ Aproximando-se do acampamento, viu o bezerro e as danças. Sua cólera se inflamou, arrojou de suas mãos as tábuas e quebrou-as ao pé da montanha.

[[v2-32-20]]

^<<v2-32-20,20>>^ Em seguida, tomando o bezerro que tinham feito, queimou-o e esmagou-o até reduzi-lo a pó, que lançou na água e a deu de beber aos israelitas.

[[v2-32-21]]

^<<v2-32-21,21>>^ Moisés disse a Aarão: “Que te fez este povo para que tenhas atraído sobre ele um tão grande pecado?”.

[[v2-32-22]]

^<<v2-32-22,22>>^ Aarão respondeu: “Não se irrite o meu senhor. Tu mesmo sabes quanto este povo é inclinado ao mal.

[[v2-32-23]]

^<<v2-32-23,23>>^ Eles disseram-me: ‘Faze-nos um deus que marche à nossa frente, porque este Moisés, que nos tirou do Egito, não sabemos o que é feito dele’.

[[v2-32-24]]

^<<v2-32-24,24>>^ Eu lhes disse: Todos aqueles que têm ouro, despojem-se dele! E mo entregaram: joguei-o ao fogo e saiu esse bezerro”.

[[v2-32-25]]

^<<v2-32-25,25>>^ Moisés viu que o povo estava desenfreado, porque Aarão tinha-lhe soltado as rédeas, expondo-o assim à zombaria de seus adversários.

[[v2-32-26]]

^<<v2-32-26,26>>^ Pôs-se de pé à entrada do acampamento e exclamou: “Venham a mim todos aqueles que são pelo Senhor!”. Todos os filhos de Levi se ajuntaram em torno dele.

[[v2-32-27]]

^<<v2-32-27,27>>^ Ele disse-lhes: “Eis o que diz o Senhor, o Deus de Israel: Cada um de vós coloque a espada sobre sua coxa. Passai e repassai através do acampamento, de uma porta à outra, e cada um de vós mate o seu irmão, seu amigo, seu parente!”.

[[v2-32-28]]

^<<v2-32-28,28>>^ Os filhos de Levi fizeram o que ordenou Moisés, e cerca de três mil homens morreram naquele dia entre o povo.

[[v2-32-29]]

^<<v2-32-29,29>>^ Moisés disse: “Consagrai-vos desde hoje ao Senhor, porque cada um de vós, ao preço de seu filho e de seu irmão, tendes atraído sobre vós hoje uma bênção”.

[[v2-32-30]]

^<<v2-32-30,30>>^ No dia seguinte, Moisés disse ao povo: “Cometestes um grande pecado. Mas vou subir hoje ao Senhor; talvez obtenha o perdão de vossa culpa”.

[[v2-32-31]]

^<<v2-32-31,31>>^ Moisés voltou junto do Senhor e disse: “Oh, esse povo cometeu um grande pecado: fizeram para si um deus de ouro.

[[v2-32-32]]

^<<v2-32-32,32>>^ Rogo-vos que lhes perdoeis agora esse pecado! Senão, apagai-me do livro que escrevestes”.

[[v2-32-33]]

^<<v2-32-33,33>>^ O Senhor disse a Moisés: “Aquele que pecou contra mim, este apagarei do meu livro.

[[v2-32-34]]

^<<v2-32-34,34>>^ Vai agora e conduze o povo aonde eu te disse: meu anjo marchará diante de ti. Mas, no dia de minha visita, eu punirei seu pecado”.

[[v2-32-35]]

^<<v2-32-35,35>>^ Feriu o Senhor o povo, por ter arrastado Aarão a fabricar o bezerro.

'''

xref:002-exodo/002-exodo-031.adoc#v2-31-0[&#60; Capítulo Anterior] | <<v2-32-0,Topo>> | xref:002-exodo/002-exodo-033.adoc#v2-33-0[Próximo Capítulo &#62;]