include::./index.adoc[]

[[v2-1-0]]
=== Êxodo, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Êxodo 1 é o início do livro de Êxodo, onde é relatada a opressão dos israelitas no Egito e o início do plano de Deus para libertá-los. O capítulo começa com a introdução da história dos israelitas no Egito, que haviam se multiplicado muito e foram vistos como uma ameaça pelos egípcios. O faraó então decide oprimi-los, escravizando-os e ordenando que as parteiras matem os recém-nascidos do sexo masculino. Abaixo seguem cinco versículos relacionados com os temas abordados em Êxodo 1:
* Êxodo 2:24: "E ouviu Deus o seu gemido, e lembrou-se Deus da sua aliança com Abraão, com Isaque, e com Jacó." Este versículo mostra que Deus ouviu o clamor dos israelitas e se lembrou de sua aliança com Abraão, Isaque e Jacó, prometendo libertá-los do Egito.
* Deuteronômio 26:7: "E clamamos ao SENHOR Deus de nossos pais; e o SENHOR ouviu a nossa voz, e viu a nossa aflição, e o nosso trabalho, e a nossa opressão." Aqui, vemos que os israelitas clamaram ao Senhor durante sua opressão no Egito, e Deus os ouviu e viu sua aflição e opressão.
* Salmos 81:6: "Eu tirei do ombro dele a carga, as suas mãos foram livres dos cestos." Este versículo fala da libertação dos israelitas do Egito, onde Deus tirou a carga da opressão de seus ombros e os libertou para que tivessem mãos livres.
* Êxodo 3:7: "E disse o SENHOR: Tenho visto atentamente a aflição do meu povo, que está no Egito, e tenho ouvido o seu clamor por causa dos seus exatores, porque conheci as suas dores." Aqui, Deus fala diretamente com Moisés e afirma ter visto a aflição do seu povo no Egito e ouvido seu clamor por causa da opressão.
* Isaías 43:1: "Mas agora assim diz o SENHOR que te criou, ó Jacó, e que te formou, ó Israel: Não temas, porque eu te remi; chamei-te pelo teu nome, tu és meu." Este versículo fala da libertação e redenção de Israel pelo Senhor, que os chamou pelo nome e prometeu não abandoná-los.
****

[[v2-1-1]]

^<<v2-1-1,1>>^ Eis os nomes dos filhos de Israel que vieram para o Egito com Jacó, cada um com sua família:

[[v2-1-2]]

^<<v2-1-2,2>>^ Rúben, Simeão, Levi, Judá,

[[v2-1-3]]

^<<v2-1-3,3>>^ Issacar, Zabulon, Benjamim,

[[v2-1-4]]

^<<v2-1-4,4>>^ Dã, Neftali, Gad e Aser.

[[v2-1-5]]

^<<v2-1-5,5>>^ Todas as pessoas saídas de Jacó eram em número de setenta. José estava já no Egito.

[[v2-1-6]]

^<<v2-1-6,6>>^ E, morto José, assim como todos os seus irmãos e toda aquela geração,

[[v2-1-7]]

^<<v2-1-7,7>>^ os israelitas foram fecundos e multiplicaram-se; tornaram-se tão numerosos e tão fortes, que a terra ficou repleta deles.

[[v2-1-8]]

^<<v2-1-8,8>>^ Entretanto, subiu ao trono do Egito um novo rei, que não tinha conhecido José.

[[v2-1-9]]

^<<v2-1-9,9>>^ Ele disse ao seu povo: ‘‘Vede: os israelitas tornaram-se numerosos e fortes demais para nós.

[[v2-1-10]]

^<<v2-1-10,10>>^ Vamos! É preciso tomar precaução contra eles e impedir que se multipliquem, para não acontecer que, sobrevindo uma guerra, se unam com os nossos inimigos e combatam contra nós, e se retirem do país”.

[[v2-1-11]]

^<<v2-1-11,11>>^ Estabeleceu, pois, sobre eles, feitores para acabrunhá-los com trabalhos penosos: eles construíram para o faraó as cidades de Pitom e Ramsés, que deviam servir de entreposto.

[[v2-1-12]]

^<<v2-1-12,12>>^ Quanto mais os oprimiam, porém, tanto mais eles se multiplicavam e se espalhavam, a ponto de os egípcios os aborrecerem.

[[v2-1-13]]

^<<v2-1-13,13>>^ Impunham-lhes a mais dura servidão,

[[v2-1-14]]

^<<v2-1-14,14>>^ e amarguravam-lhes a vida com duros trabalhos na argamassa e na fabricação de tijolos, bem como com toda a sorte de trabalhos nos campos e todas as tarefas que se lhes impunham tiranicamente.

[[v2-1-15]]

^<<v2-1-15,15>>^ O rei do Egito dirigiu-se, igualmente, às parteiras dos hebreus (uma se chamava Sefra e a outra, Fua),

[[v2-1-16]]

^<<v2-1-16,16>>^ e disse-lhes: ‘‘Quando assistirdes às mulheres dos hebreus, e as virdes sobre o leito, se for um filho, matai-o; mas se for uma filha, deixai-a viver’’.^&#42;1^

[[v2-1-17]]

^<<v2-1-17,17>>^ Mas as parteiras temiam a Deus, e não executaram as ordens do rei do Egito, deixando viver os meninos.

[[v2-1-18]]

^<<v2-1-18,18>>^ O rei mandou-as chamar então e disse-lhes: ‘‘Por que agistes assim, e deixastes viver os meninos?’’.

[[v2-1-19]]

^<<v2-1-19,19>>^ ‘‘Porque – responderam elas ao faraó – as mulheres dos hebreus não são como as dos egípcios: elas são vigorosas, e já dão à luz antes que chegue a parteira.’’

[[v2-1-20]]

^<<v2-1-20,20>>^ Deus beneficiou as parteiras: o povo continuou a multiplicar-se e a espalhar-se.

[[v2-1-21]]

^<<v2-1-21,21>>^ Porque elas haviam temido a Deus, ele fez prosperar suas famílias.

[[v2-1-22]]

^<<v2-1-22,22>>^ Então o faraó deu esta ordem a todo o seu povo: ‘‘Todo menino que nascer, vós o atirareis ao Nilo. Deixareis, porém, viver todas as meninas’’.

'''

xref:001-genesis/001-genesis-050.adoc#v1-50-0[&#60; Capítulo Anterior] | <<v2-1-0,Topo>> | xref:002-exodo/002-exodo-002.adoc#v2-2-0[Próximo Capítulo &#62;]