include::./index.adoc[]

[[v2-36-0]]
=== Êxodo, 36
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Êxodo 36 narra a construção do Tabernáculo por Bezalel e Ooliabe, de acordo com as instruções que Deus deu a Moisés. Os versículos abaixo estão relacionados aos temas abordados em Êxodo 36:
* Êxodo 25:8: "E me farão um santuário, para que eu possa habitar no meio deles." Este versículo é a primeira instrução de Deus para Moisés sobre a construção do Tabernáculo, mostrando a importância de ter um lugar para a presença de Deus no meio do povo.
* Êxodo 35:35: "Encheu-os de sabedoria de coração, para que fizessem toda a obra do serviço do santuário, segundo tudo o que o Senhor tinha ordenado." Este versículo destaca a habilidade e a sabedoria que Deus deu a Bezalel e Ooliabe para construir o Tabernáculo de acordo com as instruções divinas.
* Salmos 84:1: "Quão amáveis são os teus tabernáculos, Senhor dos Exércitos!" Este versículo é um exemplo da admiração que os salmistas tinham pelo Tabernáculo como um lugar de adoração e da presença de Deus.
* Hebreus 9:11: "Mas, vindo Cristo como sumo sacerdote dos bens futuros, por um maior e mais perfeito tabernáculo, não feito por mãos, isto é, não desta criação." Este versículo fala do Tabernáculo como uma pré-figuração do próprio Cristo, o verdadeiro sumo sacerdote e o lugar de encontro com Deus.
* Apocalipse 21:3: "E ouvi uma grande voz do céu, que dizia: Eis aqui o tabernáculo de Deus com os homens, pois com eles habitará, e eles serão o seu povo, e o mesmo Deus estará com eles, e será o seu Deus." Este versículo fala do cumprimento da promessa do Tabernáculo, quando Deus habitará para sempre com o seu povo e será o seu Deus.
****

[[v2-36-1]]

^<<v2-36-1,1>>^ Beseleel, Ooliab e todos os homens prudentes que o Senhor dotou de inteligência e habilidade, para saberem executar todos os trabalhos necessários a serviço do santuário, conformaram-se inteiramente às instruções recebidas do Senhor.

[[v2-36-2]]

^<<v2-36-2,2>>^ Moisés chamou Beseleel, Ooliab e todos os homens prudentes que o Senhor tinha dotado de inteligência, todos os que eram impelidos pelo seu coração a empreender a execução desse trabalho.

[[v2-36-3]]

^<<v2-36-3,3>>^ Levaram todas as ofertas que os israelitas haviam trazido a Moisés para a execução dos trabalhos necessários a serviço do santuário. E, como o povo continuasse, cada manhã, a trazer espontaneamente ofertas,

[[v2-36-4]]

^<<v2-36-4,4>>^ os homens prudentes que executavam os trabalhos do santuário deixaram a obra que estavam fazendo, e vieram dizer a Moisés:

[[v2-36-5]]

^<<v2-36-5,5>>^ “O povo traz muito mais do que é necessário para a execução do trabalho que o Senhor ordenou”.

[[v2-36-6]]

^<<v2-36-6,6>>^ Então, por ordem de Moisés, fez-se no acampamento esta proclamação: “Que ninguém, nem homem nem mulher, traga mais ofertas para o santuário”. Assim, o povo foi proibido de trazer mais.

[[v2-36-7]]

^<<v2-36-7,7>>^ O material trazido era mais que suficiente para tudo o que tinha que ser feito.

[[v2-36-8]]

^<<v2-36-8,8>>^ Os mais hábeis entre os operários construíram o tabernáculo: dez cortinas de linho fino retorcido, púrpura violeta e escarlate, e carmesim com querubins artisticamente bordados.

[[v2-36-9]]

^<<v2-36-9,9>>^ O comprimento de cada cortina era de vinte e oito côvados, sua largura de quatro côvados; e tinham todas as mesmas dimensões.

[[v2-36-10]]

^<<v2-36-10,10>>^ Juntaram as cortinas cinco por cinco.

[[v2-36-11]]

^<<v2-36-11,11>>^ Laços de púrpura violeta foram colocados na orla da cortina que rematava esses dois grupos.

[[v2-36-12]]

^<<v2-36-12,12>>^ Foram postos cinquenta laços na primeira cortina, e cinquenta na extremidade da última cortina do segundo grupo, situadas bem em face umas das outras.

[[v2-36-13]]

^<<v2-36-13,13>>^ As cortinas foram presas umas às outras, por meio de cinquenta colchetes de ouro, de modo que o tabernáculo formou um todo.

[[v2-36-14]]

^<<v2-36-14,14>>^ Fizeram-se, em seguida, cortinas de peles de cabra, para formar uma tenda sobre o tabernáculo; foram feitas onze dessas cortinas.

[[v2-36-15]]

^<<v2-36-15,15>>^ O comprimento de uma delas era de trinta côvados, e sua largura de quarenta côvados; e tinham todas as mesmas dimensões.

[[v2-36-16]]

^<<v2-36-16,16>>^ Cinco dessas cortinas foram juntadas de um lado, e seis de outro.

[[v2-36-17]]

^<<v2-36-17,17>>^ Cinquenta colchetes foram colocados na orla da última cortina de um desses grupos e cinquenta na orla da última cortina do segundo.

[[v2-36-18]]

^<<v2-36-18,18>>^ Depois fizeram cinquenta colchetes de bronze para unir as peças, de modo que a tenda formasse um todo.

[[v2-36-19]]

^<<v2-36-19,19>>^ Foi feita a cobertura da tenda de peles de carneiros tingidas de vermelho, sobre as quais se colocou uma cobertura de peles de golfinhos.

[[v2-36-20]]

^<<v2-36-20,20>>^ As tábuas do tabernáculo foram feitas de madeira de acácia, colocadas verticalmente.

[[v2-36-21]]

^<<v2-36-21,21>>^ As tábuas tinham dez côvados de comprimento e um côvado e meio de largura.

[[v2-36-22]]

^<<v2-36-22,22>>^ Cada tábua tinha dois encaixes ligados um ao outro. Assim se fez com todas as tábuas do tabernáculo.

[[v2-36-23]]

^<<v2-36-23,23>>^ Fizeram para o lado meridional do tabernáculo, ao sul, vinte tábuas.

[[v2-36-24]]

^<<v2-36-24,24>>^ Puseram sob essas vinte tábuas quarenta suportes de prata, dois sob cada tábua, para seus dois encaixes.

[[v2-36-25]]

^<<v2-36-25,25>>^ Para o segundo lado do tabernáculo, ao norte, fizeram vinte tábuas,

[[v2-36-26]]

^<<v2-36-26,26>>^ com quarenta suportes de prata, à razão de dois por tábua.

[[v2-36-27]]

^<<v2-36-27,27>>^ Para o fundo do tabernáculo, ao ocidente, fizeram seis tábuas.

[[v2-36-28]]

^<<v2-36-28,28>>^ Para os ângulos do tabernáculo, ao fundo, fizeram duas tábuas.

[[v2-36-29]]

^<<v2-36-29,29>>^ Elas eram emparelhadas desde a base, formando juntas um só todo até o alto, na primeira argola. O mesmo se fez com as duas tábuas colocadas nos ângulos.

[[v2-36-30]]

^<<v2-36-30,30>>^ Havia, pois, oito tábuas com seus suportes de prata, em número de dezesseis, dois sob cada tábua.

[[v2-36-31]]

^<<v2-36-31,31>>^ Fizeram em seguida cinco travessas de madeira de acácia para as tábuas de um dos lados do tabernáculo,

[[v2-36-32]]

^<<v2-36-32,32>>^ cinco para as tábuas do segundo lado e cinco para as que estavam do lado posterior do tabernáculo, ao ocidente.

[[v2-36-33]]

^<<v2-36-33,33>>^ A travessa central estendia-se ao longo das tábuas, de uma extremidade à outra.

[[v2-36-34]]

^<<v2-36-34,34>>^ Recobriram de ouro essas tábuas e se lhes puseram argolas de ouro, pelas quais passaram as travessas, recobertas também de ouro.

[[v2-36-35]]

^<<v2-36-35,35>>^ Foi feito o véu de púrpura violeta e escarlate, de carmesim e linho retorcido, onde foram bordados artisticamente alguns querubins.

[[v2-36-36]]

^<<v2-36-36,36>>^ Fizeram para ele quatro colunas de madeira de acácia revestidas de ouro, com pregos de ouro e fundiram para elas quatro pedestais de prata.

[[v2-36-37]]

^<<v2-36-37,37>>^ Para a entrada da tenda foi feito o véu de púrpura violeta e escarlate, de carmesim e linho retorcido, artisticamente bordado.

[[v2-36-38]]

^<<v2-36-38,38>>^ Fizeram, para suspender esse véu, cinco colunas munidas de ganchos; recobriram de ouro seus capitéis e suas vergas; seus cinco pedestais foram feitos de bronze.

'''

xref:002-exodo/002-exodo-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodo/002-exodo-037.adoc#v2-37-0[Próximo Capítulo &#62;]