include::./index.adoc[]

[[v2-11-0]]
=== Êxodo, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Em Êxodo 11, Deus anuncia a última praga que será lançada sobre o Egito, a morte de todos os primogênitos. Moisés comunica isso ao faraó e à nação egípcia. Aqui estão cinco versículos relacionados com os temas abordados neste capítulo:
* Salmos 105:36: "Ele feriu a todos os primogênitos no Egito, as primícias da força deles nas tendas de Cão." Este salmo relembra as ações de Deus durante a libertação do povo de Israel do Egito, incluindo a morte dos primogênitos.
* Êxodo 12:12: "Naquela noite passarei pelo Egito e matarei todos os primogênitos, tanto dos homens como dos animais, e executarei juízo sobre todos os deuses do Egito. Eu sou o Senhor." Este versículo é uma continuação da última praga que será lançada sobre o Egito.
* Números 3:12-13: "Eu tomei todos os primogênitos dos filhos de Israel para mim, tanto dos homens como dos animais; no dia em que feri todo primogênito na terra do Egito, eu os separei para mim. Mas tomei os levitas em lugar de todos os primogênitos dos filhos de Israel." Aqui, Deus explica que os levitas serão escolhidos para servi-lo em vez dos primogênitos dos filhos de Israel.
* João 1:29: "No dia seguinte, João viu Jesus aproximando-se e disse: 'Eis o Cordeiro de Deus, que tira o pecado do mundo!'" Este versículo faz uma conexão entre a morte do primogênito em Êxodo e a morte de Jesus como o cordeiro de Deus que tira o pecado do mundo.
* Hebreus 11:28: "Pela fé, ele celebrou a Páscoa e aplicou o sangue, para que o destruidor não tocasse nos primogênitos dos israelitas." Este versículo destaca a importância da celebração da Páscoa e da aplicação do sangue do cordeiro para proteger os primogênitos dos filhos de Israel da última praga no Egito.
****

[[v2-11-1]]

^<<v2-11-1,1>>^ O Senhor disse a Moisés: “Mandarei ainda outra praga sobre o faraó e sobre o Egito, e em consequência dela vos deixará partir daqui. Quando vos deixar partir, será definitivamente, será mesmo expulsando-vos daqui.

[[v2-11-2]]

^<<v2-11-2,2>>^ Dirás ao povo que cada homem peça ao seu vizinho, cada mulher à sua vizinha, objetos de prata e de ouro”.

[[v2-11-3]]

^<<v2-11-3,3>>^ O Senhor fez que o povo ganhasse o favor dos egípcios. Moisés mesmo era muito considerado no Egito pelos servos do faraó e por todo o povo.

[[v2-11-4]]

^<<v2-11-4,4>>^ Moisés disse: “Eis o que diz o Senhor: Pela meia-noite passarei através do Egito,

[[v2-11-5]]

^<<v2-11-5,5>>^ e morrerá todo primogênito na terra do Egito, desde o primogênito do faraó, que deveria assentar-se no seu trono, até o primogênito do escravo que faz girar a mó, assim como todo primogênito dos animais.

[[v2-11-6]]

^<<v2-11-6,6>>^ Haverá em toda a terra do Egito um clamor tal como nunca houve nem haverá jamais.

[[v2-11-7]]

^<<v2-11-7,7>>^ Quanto aos israelitas, porém, desde os homens até os animais, ninguém, nem mesmo um cão moverá a sua língua. Sabereis assim como o Senhor fez distinção entre os egípcios e os israelitas.

[[v2-11-8]]

^<<v2-11-8,8>>^ Então todos esses teus servos virão procurar-me e se prostrarão diante de mim, dizendo: ‘Vai-te, tu e todo o povo que te acompanha!’. E depois disso partirei”. Moisés, grandemente irado, saiu da casa do faraó.

[[v2-11-9]]

^<<v2-11-9,9>>^ O Senhor disse a Moisés: “O faraó não vos ouvirá, a fim de que meus prodígios se multipliquem no Egito”.

[[v2-11-10]]

^<<v2-11-10,10>>^ Moisés e Aarão tinham operado todos esses prodígios em presença do faraó. Mas o Senhor endureceu o coração do faraó, que não permitiu aos israelitas partirem de sua terra.

'''

xref:002-exodo/002-exodo-010.adoc#v2-10-0[&#60; Capítulo Anterior] | <<v2-11-0,Topo>> | xref:002-exodo/002-exodo-012.adoc#v2-12-0[Próximo Capítulo &#62;]