include::./index.adoc[]

[[v2-39-0]]
=== Êxodo, 39
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 39 de Êxodo detalha a confecção das vestes sacerdotais para o serviço no tabernáculo. Foram feitos o manto, o colete sacerdotal, a tiara, a túnica bordada, o cinto e as vestes de linho fino para serem usadas durante as cerimônias de adoração a Deus. Os versículos a seguir estão relacionados a temas abordados em Êxodo 39:
* Levítico 8:7 - "Ele vestiu Arão com a túnica, ajustou o cinto ao seu redor, vestiu-o com o colete sacerdotal e ajustou o mesmo ao seu redor." Esse versículo descreve a vestimenta que Arão, o primeiro sumo sacerdote, usou durante a sua ordenação.
* Ezequiel 44:17- " Quando eles entrarem nas portas internas do pátio, eles deverão usar roupas de linho; não devem vestir nada de lã enquanto estiverem servindo no interior do pátio, junto ao altar e às paredes do templo." Esse versículo fala sobre as roupas que os sacerdotes deveriam usar quando estivessem no templo.
* Hebreus 4:14 - "Portanto, visto que temos um grande sumo sacerdote que adentrou os céus, Jesus, o Filho de Deus, apeguemo-nos com toda a firmeza à fé que professamos, tendo grande sacerdote sobre a casa de Deus." Esse versículo faz referência a Jesus como sumo sacerdote, que é superior a qualquer outro sacerdote.
* Apocalipse 1:6 - "e nos constituiu reino e sacerdotes para servir a seu Deus e Pai, a ele seja glória e poder para todo o sempre! Amém." Esse versículo fala sobre o papel dos cristãos como sacerdotes de Deus, servindo a ele em seu reino.
* Colossenses 3:12 - "Portanto, como povo escolhido de Deus, santo e amado, revistam-se de profunda compaixão, bondade, humildade, mansidão e paciência." Esse versículo fala sobre a importância de os cristãos se vestirem com as virtudes do caráter de Deus, assim como os sacerdotes do Antigo Testamento se vestiam com as suas vestes sagradas.
****

[[v2-39-1]]

^<<v2-39-1,1>>^ Com a púrpura violeta, a púrpura escarlate e o carmesim, fizeram-se as vestes de cerimônia para o serviço do santuário, e os ornamentos sagrados para Aarão, como o Senhor havia ordenado a Moisés.

[[v2-39-2]]

^<<v2-39-2,2>>^ Fez-se o efod de ouro, de púrpura violeta e escarlate, de carmesim e linho fino retorcido.

[[v2-39-3]]

^<<v2-39-3,3>>^ Reduziu-se o ouro a lâminas, e estas foram cortadas em fios para serem entrelaçados com a púrpura violeta e escarlate, o carmesim e o linho fino, fazendo disso um artístico bordado.

[[v2-39-4]]

^<<v2-39-4,4>>^ Fizeram-se alças que o uniam, e aos quais era preso pelas duas extremidades.

[[v2-39-5]]

^<<v2-39-5,5>>^ O cinto que passava sobre o efod, para prendê-lo, formava uma só peça com ele e era do mesmo tecido: ouro, púrpura violeta e escarlate, carmesim e linho fino retorcido, como o Senhor tinha ordenado a Moisés.

[[v2-39-6]]

^<<v2-39-6,6>>^ Fizeram-se as pedras de ônix, engastadas em filigranas de ouro, nas quais foram gravados, à maneira de sinetes, os nomes dos filhos de Israel.

[[v2-39-7]]

^<<v2-39-7,7>>^ Colocaram-se nas alças do efod essas pedras para serem um memorial dos filhos de Israel, como o Senhor o tinha ordenado a Moisés.

[[v2-39-8]]

^<<v2-39-8,8>>^ Fez-se o peitoral, obra de arte como o efod, de ouro, púrpura violeta e escarlate, carmesim e linho fino retorcido. Era quadrado e dobrado em dois;

[[v2-39-9]]

^<<v2-39-9,9>>^ seu comprimento era de um palmo e sua largura de um palmo; e era duplo.

[[v2-39-10]]

^<<v2-39-10,10>>^ Adornou-se de quatro fileiras de pedras. Primeira fila: um sárdio, um topázio e uma esmeralda;

[[v2-39-11]]

^<<v2-39-11,11>>^ segunda fileira: um rubi, uma safira, um diamante;

[[v2-39-12]]

^<<v2-39-12,12>>^ terceira fileira: uma opala, uma ágata e uma ametista;

[[v2-39-13]]

^<<v2-39-13,13>>^ quarta fileira: um crisólito, um ônix e um jaspe. Elas estavam engastadas em filigranas de ouro.

[[v2-39-14]]

^<<v2-39-14,14>>^ E, correspondendo aos nomes dos filhos de Israel, eram em número de doze, e em cada uma estava gravado o nome de uma das doze tribos, à maneira de um sinete.

[[v2-39-15]]

^<<v2-39-15,15>>^ Fizeram-se umas correntinhas de ouro puro para o peitoral, entrelaçadas em forma de cordão,

[[v2-39-16]]

^<<v2-39-16,16>>^ e também dois engastes de ouro e duas argolas de ouro que se fixaram nas duas extremidades do peitoral.

[[v2-39-17]]

^<<v2-39-17,17>>^ Foram os dois cordões de ouro passados nas duas argolas, nas extremidades do peitoral,

[[v2-39-18]]

^<<v2-39-18,18>>^ e presas as duas pontas dos dois cordões aos dois engastes, pondo-os para o lado da frente nas duas alças do efod.

[[v2-39-19]]

^<<v2-39-19,19>>^ Fizeram-se ainda duas argolas de ouro que se fixaram às duas extremidades do peitoral, na orla interior que se aplica contra o efod.

[[v2-39-20]]

^<<v2-39-20,20>>^ E enfim duas outras argolas de ouro, que se fixaram na parte dianteira, por baixo das duas alças do efod, no lugar da junção, no cinto do efod.

[[v2-39-21]]

^<<v2-39-21,21>>^ Prenderam-se as argolas às do efod por meio de uma fita de púrpura violeta, a fim de fixar o peitoral no cinto do efod, de sorte que não pudesse separar-se dele. Foi assim que o Senhor tinha ordenado a Moisés.

[[v2-39-22]]

^<<v2-39-22,22>>^ Fez-se o manto do efod, tecido inteiramente de púrpura violeta.

[[v2-39-23]]

^<<v2-39-23,23>>^ Havia no meio uma abertura para a cabeça, como a de um corselete; a beirada estava protegida por uma orla, para que não se rompesse.

[[v2-39-24]]

^<<v2-39-24,24>>^ A orla inferior do manto foi adornada com romãs de púrpura violeta e escarlate, de carmesim e linho fino retorcido.

[[v2-39-25]]

^<<v2-39-25,25>>^ Fizeram-se campainhas de ouro puro que se colocaram entre as romãs em toda a orla inferior do manto:

[[v2-39-26]]

^<<v2-39-26,26>>^ uma campainha, uma romã, outra campainha, outra romã, em toda a orla inferior do manto, para o serviço, como o Senhor o tinha ordenado a Moisés.

[[v2-39-27]]

^<<v2-39-27,27>>^ Fizeram-se túnicas de linho, tecidas, para Aarão e seus filhos;

[[v2-39-28]]

^<<v2-39-28,28>>^ o turbante de linho, e as tiaras de linho à guisa de ornato; os calções de linho fino retorcido;

[[v2-39-29]]

^<<v2-39-29,29>>^ o cinto de linho retorcido, bordado de púrpura violeta, púrpura escarlate e carmesim, como o Senhor o tinha ordenado a Moisés.

[[v2-39-30]]

^<<v2-39-30,30>>^ Foi feita a lâmina de ouro puro, o diadema sagrado, no qual foi gravado, como se grava um sinete: consagrado a Javé.

[[v2-39-31]]

^<<v2-39-31,31>>^ Prendeu-se com uma fita de púrpura violeta pela frente, na parte superior do turbante, como o Senhor havia ordenado a Moisés.

[[v2-39-32]]

^<<v2-39-32,32>>^ Assim foram concluídos todos os trabalhos do tabernáculo, da tenda de reunião. Os israelitas tinham executado tudo em conformidade com as ordens dadas pelo Senhor a Moisés.

[[v2-39-33]]

^<<v2-39-33,33>>^ Apresentaram o tabernáculo a Moisés: a tenda e todo o seu mobiliário, seus colchetes, suas tábuas, suas travessas, suas colunas, seus pedestais;

[[v2-39-34]]

^<<v2-39-34,34>>^ a coberta de peles de carneiro tingidas de vermelho, a coberta de peles de golfinho, o véu de separação,

[[v2-39-35]]

^<<v2-39-35,35>>^ a arca da aliança com seus varais e sua tampa;

[[v2-39-36]]

^<<v2-39-36,36>>^ a mesa com todos os seus utensílios e os pães da proposição;

[[v2-39-37]]

^<<v2-39-37,37>>^ o candelabro de ouro puro, suas lâmpadas, as lâmpadas que se deviam dispor nele, todos os seus acessórios e o óleo para o candelabro;

[[v2-39-38]]

^<<v2-39-38,38>>^ o altar de ouro, o óleo da unção, o perfume aromático e a cortina da entrada da tenda;

[[v2-39-39]]

^<<v2-39-39,39>>^ o altar de bronze, sua grelha de bronze, seus varais e todos os seus utensílios; a bacia com seu pedestal; as cortinas do átrio, suas colunas, seus pedestais, a cortina da porta do átrio,

[[v2-39-40]]

^<<v2-39-40,40>>^ seus cordões e suas estacas e todos os utensílios necessários ao culto do tabernáculo para a tenda de reunião;

[[v2-39-41]]

^<<v2-39-41,41>>^ as vestes litúrgicas para o serviço do santuário, os ornamentos sagrados para o sacerdote Aarão e as vestes de seus filhos para as funções sacerdotais.

[[v2-39-42]]

^<<v2-39-42,42>>^ Os israelitas tinham executado toda essa obra conformando-se exatamente às ordens dadas pelo Senhor a Moisés.

[[v2-39-43]]

^<<v2-39-43,43>>^ Moisés examinou todo o trabalho e viu que ele tinha sido executado segundo as ordens do Senhor. E Moisés os abençoou.

'''

xref:002-exodo/002-exodo-038.adoc#v2-38-0[&#60; Capítulo Anterior] | <<v2-39-0,Topo>> | xref:002-exodo/002-exodo-040.adoc#v2-40-0[Próximo Capítulo &#62;]