include::./index.adoc[]

[[v2-16-0]]
=== Êxodo, 16
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 16 de Êxodo descreve a provisão de Deus para o povo de Israel no deserto, através do maná e das codornizes. Além disso, há a instrução para a coleta do maná e a proibição de guardá-lo de um dia para o outro. Seguem abaixo cinco versículos relacionados com os temas abordados neste capítulo:
* Deuteronômio 8:3 - "E ele te humilhou, e te deixou ter fome, e te sustentou com o maná, que tu não conhecias, nem teus pais o conheciam; para te dar a entender que o homem não viverá só de pão, mas de tudo o que sai da boca do SENHOR viverá o homem." Este versículo faz referência ao maná fornecido por Deus no deserto e destaca que o povo de Israel precisava depender de Deus para sua provisão.
* João 6:31 - "Nossos pais comeram o maná no deserto, como está escrito: Deu-lhes a comer o pão do céu." Neste versículo, Jesus menciona o maná como um milagre realizado por Deus para prover alimento para o povo de Israel.
* 2 Coríntios 8:15 - "Assim como está escrito: O que muito colheu não teve de mais; e o que pouco colheu não teve de menos." Este versículo faz referência à instrução dada por Deus a respeito da coleta do maná, que deveria ser o suficiente para cada dia.
* Êxodo 16:4 - "Então disse o SENHOR a Moisés: Eis que vos farei chover pão dos céus, e o povo sairá, e colherá diariamente a porção para cada dia, para que eu o prove se anda em minha lei ou não." Este é um dos versículos que descrevem a provisão de Deus para o povo de Israel através do maná.
* Êxodo 16:19-20 - "E disse Moisés a eles: Ninguém deixe dele para a manhã seguinte. Mas eles não deram ouvidos a Moisés, e alguns deixaram dele para a manhã seguinte, e criou bichos e cheirou mal; e Moisés se indignou contra eles." Estes versículos descrevem a proibição de guardar o maná de um dia para o outro e a consequência da desobediência a esta ordem.
****

[[v2-16-1]]

^<<v2-16-1,1>>^ Toda a assembleia dos israelitas partiu de Elim e foi para o deserto de Sin, situado entre Elim e o Sinai. Era o décimo quinto dia do segundo mês após sua saída do Egito.

[[v2-16-2]]

^<<v2-16-2,2>>^ Toda a assembleia dos israelitas pôs-se a murmurar contra Moisés e Aarão no deserto.

[[v2-16-3]]

^<<v2-16-3,3>>^ Disseram-lhes: “Oxalá tivéssemos sido mortos pela mão do Senhor no Egito, quando nos assentávamos diante das panelas de carne e tínhamos pão em abundância! Vós nos conduzistes a este deserto, para matardes de fome toda esta multidão”.

[[v2-16-4]]

^<<v2-16-4,4>>^ O Senhor disse a Moisés: “Vou fazer chover pão do alto do céu. Sairá o povo e colherá diariamente a porção de cada dia. Eu o porei desse modo à prova, para ver se andará ou não segundo minhas ordens.

[[v2-16-5]]

^<<v2-16-5,5>>^ No sexto dia, quando prepararem o que tiverem ajuntado haverá o dobro do que recolhem cada dia”.

[[v2-16-6]]

^<<v2-16-6,6>>^ Moisés e Aarão disseram a todos os israelitas: “Esta tarde, sabereis que foi o Senhor quem vos tirou do Egito,

[[v2-16-7]]

^<<v2-16-7,7>>^ e amanhã pela manhã vereis a sua glória, porque ele ouviu as vossas murmurações contra ele. Nós, porém, quem somos para que murmureis contra nós?”.

[[v2-16-8]]

^<<v2-16-8,8>>^ Moisés disse: “Isso acontecerá quando o Senhor vos der, esta tarde, carne para comerdes e, amanhã pela manhã, pão em abundância, porque ele ouviu as murmurações que proferistes contra ele. Nós, porém, quem somos? Não é contra nós que murmurastes, mas contra o Senhor”.

[[v2-16-9]]

^<<v2-16-9,9>>^ Moisés disse a Aarão: “Dize a toda a assembleia dos israelitas: apresentai-vos diante do Senhor, porque ele ouviu vossas murmurações”.

[[v2-16-10]]

^<<v2-16-10,10>>^ Enquanto Aarão falava a toda a assembleia dos israelitas, olharam para o deserto e eis que apareceu na nuvem a glória do Senhor!

[[v2-16-11]]

^<<v2-16-11,11>>^ E o Senhor disse a Moisés:

[[v2-16-12]]

^<<v2-16-12,12>>^ “Ouvi as murmurações dos israelitas. Dize-lhes: Esta tarde, antes que escureça, comereis carne e, amanhã de manhã, vos fartareis de pão; e sabereis que sou o Senhor, vosso Deus”.

[[v2-16-13]]

^<<v2-16-13,13>>^ À tarde, com efeito, subiram codornizes (do horizonte) e cobriram o acampamento; e, no dia seguinte pela manhã, havia uma camada de orvalho em torno de todo o acampamento.

[[v2-16-14]]

^<<v2-16-14,14>>^ E, tendo evaporado esse orvalho, eis que sobre a superfície do deserto estava uma coisa miúda, granulosa, miúda como a geada sobre a terra!

[[v2-16-15]]

^<<v2-16-15,15>>^ Vendo isso, disseram os filhos de Israel uns aos outros: “Que é isso?”, pois não sabiam o que era. Moisés disse-lhes: “Este é o pão que o Senhor vos manda para comer.

[[v2-16-16]]

^<<v2-16-16,16>>^ Eis que vos ordena o Senhor: Ajunte cada um o quanto lhe for necessário para comer; para aqueles que estão em sua tenda, um gomor por cabeça, segundo o número das pessoas”.

[[v2-16-17]]

^<<v2-16-17,17>>^ Assim fizeram os israelitas: ajuntaram uns mais, outros menos.

[[v2-16-18]]

^<<v2-16-18,18>>^ Mas, quando se media com o gomor, aconteceu que o que tinha ajuntado muito não tinha demais e, ao que tinha ajuntado pouco, não lhe faltava: cada um havia recolhido segundo a sua necessidade.^&#42;1^

[[v2-16-19]]

^<<v2-16-19,19>>^ Moisés disse-lhes: “Ninguém reserve dele para o dia seguinte”.

[[v2-16-20]]

^<<v2-16-20,20>>^ Alguns não o ouviram e guardaram dele até pela manhã; mas criou vermes e cheirou mal. Moisés irritou-se contra eles.

[[v2-16-21]]

^<<v2-16-21,21>>^ Todas as manhãs fizeram a sua provisão, cada um segundo suas necessidades. E, quando vinha o calor do sol, derretia-se.

[[v2-16-22]]

^<<v2-16-22,22>>^ No sexto dia, recolheram uma dupla quantidade de alimento, dois gomores para cada um. Vieram todos os chefes da assembleia e contaram-no a Moisés.

[[v2-16-23]]

^<<v2-16-23,23>>^ Este lhes disse: “É isso o que o Senhor ordenou. Amanhã é um dia de repouso, o sábado consagrado ao Senhor. Por isso, o que tendes a cozer no forno, cozei-o, e o que tendes a cozer em água, cozei-o; e o que sobrar, ponde-o de lado até pela manhã”.

[[v2-16-24]]

^<<v2-16-24,24>>^ Guardaram-no até o dia seguinte, segundo a ordem de Moisés; e não cheirou mal, nem se acharam vermes nele.

[[v2-16-25]]

^<<v2-16-25,25>>^ “Comei-o hoje – disse Moisés – porque é o dia do sábado do Senhor; hoje não o achareis no campo.

[[v2-16-26]]

^<<v2-16-26,26>>^ Durante seis dias o ajuntareis; mas o sétimo é o sábado: nele não haverá.

[[v2-16-27]]

^<<v2-16-27,27>>^ (No sétimo dia alguns saíram para fazer sua provisão, mas nada encontraram.

[[v2-16-28]]

^<<v2-16-28,28>>^ Então o Senhor disse a Moisés: ‘Até quando vos recusareis a observar meus mandamentos e minhas leis?’.)

[[v2-16-29]]

^<<v2-16-29,29>>^ Considerai que, se o Senhor vos deu o sábado, vos dá ele no sexto dia alimento para dois dias. Fique cada um onde está, e ninguém saia de sua habitação no sétimo dia.”

[[v2-16-30]]

^<<v2-16-30,30>>^ Assim o povo repousou no sétimo dia.

[[v2-16-31]]

^<<v2-16-31,31>>^ Os israelitas deram a esse alimento o nome de maná. Assemelhava-se à semente de coentro: era branco e tinha o sabor de uma torta de mel.^&#42;1^

[[v2-16-32]]

^<<v2-16-32,32>>^ Moisés disse: “Eis o que ordena o Senhor: que se encha dele um gomor para ser conservado para vossas gerações futuras, a fim de que vejam o pão com que vos sustentei no deserto, depois de vos ter tirado do Egito”.

[[v2-16-33]]

^<<v2-16-33,33>>^ E Moisés disse a Aarão: “Toma uma vasilha e põe nela a quantia de um gomor de maná, e deposita-o diante do Senhor, a fim de conservá-lo para vossos descendentes”.

[[v2-16-34]]

^<<v2-16-34,34>>^ Aarão, segundo a ordem do Senhor a Moisés, depositou-o diante do Testemunho para ser conservado.

[[v2-16-35]]

^<<v2-16-35,35>>^ Os israelitas comeram o maná durante quarenta anos, até a sua chegada a uma terra habitada. Comeram o maná até que chegaram aos confins da terra de Canaã.

[[v2-16-36]]

^<<v2-16-36,36>>^ (O gomor é a décima parte do efá.)^&#42;1^

'''

xref:002-exodo/002-exodo-015.adoc#v2-15-0[&#60; Capítulo Anterior] | <<v2-16-0,Topo>> | xref:002-exodo/002-exodo-017.adoc#v2-17-0[Próximo Capítulo &#62;]