include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 35 do livro de Êxodo trata da contribuição voluntária do povo para a construção do tabernáculo e dos objetos sagrados que seriam utilizados nos rituais religiosos. Os versículos relacionados com os temas abordados neste capítulo são:
* 1 Crônicas 29:9 - "E o povo se alegrou com estas ofertas voluntárias, pois as fizeram de coração sincero para o SENHOR. E Davi, o rei, também se alegrou grandemente." Este versículo mostra a alegria do povo em contribuir voluntariamente para a obra do SENHOR, assim como aconteceu na construção do tabernáculo.
* 2 Coríntios 9:7 - "Cada um dê conforme propôs no seu coração, não com tristeza ou por necessidade; porque Deus ama ao que dá com alegria." Paulo instrui os coríntios a contribuírem voluntariamente para a obra de Deus, sem tristeza ou pressão, mas com alegria no coração.
* Provérbios 3:9-10 - "Honra ao SENHOR com os teus bens e com as primícias de toda a tua renda; e se encherão fartamente os teus celeiros, e transbordarão de vinho os teus lagares." Este versículo destaca a importância de honrar ao SENHOR com as nossas posses, e promete que aqueles que o fazem serão abençoados abundantemente.
* 1 Timóteo 6:17-19 - "Manda aos ricos deste mundo que não sejam altivos, nem depositem a sua esperança na incerteza das riquezas, mas em Deus, que nos concede abundantemente todas as coisas para delas gozarmos; que pratiquem o bem, sejam ricos de boas obras, generosos em dar e prontos a repartir; que acumulem para si mesmos tesouros que sirvam de alicerce para o futuro, a fim de se apoderarem da verdadeira vida." Paulo ensina que aqueles que são ricos devem ser generosos em dar e repartir, acumulando tesouros para si mesmos no céu.
* 2 Coríntios 8:1-5 - "Irmãos, fazemos-vos conhecer a graça de Deus concedida às igrejas da Macedônia; pois, no meio de muita prova de tribulação, manifestaram abundância de alegria, e a profunda pobreza deles superabundou em grande riqueza da sua generosidade; porque, dou testemunho, segundo as suas posses e mesmo acima delas, espontaneamente deram, pedindo-nos, com muito encarecimento, o privilégio de participarem deste serviço em favor dos santos. E não somente fizeram como nós esperávamos, mas a si mesmos se deram primeiro ao Senhor, e depois a nós, pela vontade de Deus." Este versículo relata a generosidade dos irmãos da Macedônia, que, mesmo em meio à pobreza e tribulação, contribuíram voluntariamente para a obra do SENHOR.
****

[[v2-35-1]]

^<<v2-35-1,1>>^ Moisés convocou toda a assem-bleia de Israel e disse-lhes: “Eis o que o Senhor ordenou:

[[v2-35-2]]

^<<v2-35-2,2>>^ Trabalharás durante seis dias, mas o sétimo será um dia de descanso completo consagrado ao Senhor. Todo o que trabalhar nesse dia será morto.

[[v2-35-3]]

^<<v2-35-3,3>>^ Não acendereis fogo em nenhuma de vossas casas nesse dia”.

[[v2-35-4]]

^<<v2-35-4,4>>^ Moisés disse a toda a assembleia dos israelitas: “Eis o que o Senhor ordenou:

[[v2-35-5]]

^<<v2-35-5,5>>^ Separai de entre vós uma oferta para o Senhor. Todo homem de coração reto trará esta oferta ao Senhor: ouro, prata, bronze,

[[v2-35-6]]

^<<v2-35-6,6>>^ púrpura violeta e escarlate, carmesim, linho fino, pele de cabra,

[[v2-35-7]]

^<<v2-35-7,7>>^ peles de carneiro tingidas de vermelho, peles de golfinho, madeira de acácia,

[[v2-35-8]]

^<<v2-35-8,8>>^ óleo para o candelabro, aromas para o óleo da unção e para o incenso odorífero,

[[v2-35-9]]

^<<v2-35-9,9>>^ pedras de ônix e pedras de engaste para o efod e o peitoral.

[[v2-35-10]]

^<<v2-35-10,10>>^ Venham todos aqueles dentre vós que são hábeis, e executem tudo o que o Senhor ordenou:

[[v2-35-11]]

^<<v2-35-11,11>>^ o tabernáculo, sua tenda, sua coberta, suas argolas, suas tábuas, suas travessas, suas colunas e seus pedestais;

[[v2-35-12]]

^<<v2-35-12,12>>^ a arca e seus varais; a tampa e o véu de separação;

[[v2-35-13]]

^<<v2-35-13,13>>^ a mesa com seus varais, todos os seus utensílios e os pães da proposição;

[[v2-35-14]]

^<<v2-35-14,14>>^ o candelabro e seus acessórios, suas lâmpadas e o óleo para a iluminação,

[[v2-35-15]]

^<<v2-35-15,15>>^ o altar dos perfumes e seus varais; o óleo para a unção e o perfume para as incensações; o véu para a porta de entrada do tabernáculo;

[[v2-35-16]]

^<<v2-35-16,16>>^ o altar dos holocaustos, sua grelha de bronze, seus varais e todos os seus acessórios; a bacia com seu pedestal;

[[v2-35-17]]

^<<v2-35-17,17>>^ as cortinas do átrio, suas colunas, seus pedestais e a cortina da porta do átrio;

[[v2-35-18]]

^<<v2-35-18,18>>^ as estacas do tabernáculo, as estacas do átrio com suas cordas;

[[v2-35-19]]

^<<v2-35-19,19>>^ as vestes litúrgicas para o serviço do santuário, os ornamentos sagrados do sumo sacerdote Aarão, e as vestes de seus filhos para as funções sacerdotais”.

[[v2-35-20]]

^<<v2-35-20,20>>^ Toda a assembleia dos israelitas retirou-se de diante de Moisés.

[[v2-35-21]]

^<<v2-35-21,21>>^ E então todas as pessoas de boa vontade e de coração generoso vieram trazer as suas ofertas ao Senhor, para a construção da tenda de reunião, para o seu culto e para a confecção dos ornamentos sagrados.

[[v2-35-22]]

^<<v2-35-22,22>>^ Homens e mulheres, todos aqueles que tinham o coração generoso trouxeram brincos, fivelas, anéis, colares, joias de ouro de toda a espécie, cada um apresentando a oferta de ouro que dedicava ao Senhor.

[[v2-35-23]]

^<<v2-35-23,23>>^ Todos os que tinham em sua casa púrpura violeta e escarlate, carmesim, linho fino, pele de cabra, peles de carneiro tingidas de vermelho e peles de golfinho, os trouxeram.

[[v2-35-24]]

^<<v2-35-24,24>>^ Todos os que puderam apresentar uma contribuição em prata ou em bronze, trouxeram-na ao Senhor. Todos os que tinham em sua casa madeira de acácia útil a serviço do culto, a trouxeram.

[[v2-35-25]]

^<<v2-35-25,25>>^ Todas as mulheres habilidosas fiaram com as suas próprias mãos e trouxeram seu trabalho: púrpura violeta e escarlate, carmesim e linho fino.

[[v2-35-26]]

^<<v2-35-26,26>>^ Todas as mulheres habilidosas que tinham o gosto de fiar os pelos de cabra, fizeram-no.

[[v2-35-27]]

^<<v2-35-27,27>>^ Os chefes do povo trouxeram pedras de ônix e outras pedras de engaste para o efod e o peitoral;

[[v2-35-28]]

^<<v2-35-28,28>>^ aromas e óleo para o candelabro, óleo da unção e incenso perfumado.

[[v2-35-29]]

^<<v2-35-29,29>>^ Todos os israelitas, homens ou mulheres, impelidos pelo seu coração a contribuir para alguma das obras que o Senhor tinha ordenado pela boca de Moisés, trouxeram espontaneamente suas ofertas ao Senhor.

[[v2-35-30]]

^<<v2-35-30,30>>^ Moisés disse aos israelitas: “Vede: o Senhor designou Beseleel, filho de Uri, filho de Hur, da tribo de Judá;

[[v2-35-31]]

^<<v2-35-31,31>>^ encheu-o de um espírito divino para dar-lhe sabedoria, inteligência e habilidade para toda a sorte de obras:

[[v2-35-32]]

^<<v2-35-32,32>>^ invenções, trabalho em ouro, em prata e em bronze,

[[v2-35-33]]

^<<v2-35-33,33>>^ gravação de pedras de engaste, trabalho em madeira, execução de toda a espécie de obras.

[[v2-35-34]]

^<<v2-35-34,34>>^ Concedeu-lhe também o dom de ensinar, assim como a Ooliab, filho de Aquisamec, da tribo de Dã.

[[v2-35-35]]

^<<v2-35-35,35>>^ Dotou-os de talento para executar toda a sorte de obras de escultura e de arte, de bordados em estofo de púrpura violeta e escarlate, de carmesim e de linho fino, e para a execução assim como o projeto de toda a espécie de trabalhos”.

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]