include::./index.adoc[]

[[v24-21-0]]
=== Provérbios, 21
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 21 do livro de Provérbios aborda temas relacionados à justiça, sabedoria e comportamento humano. Provérbios 21:3 destaca a importância de praticar a justiça e o direito, enquanto Provérbios 21:9 adverte sobre a dificuldade de conviver com pessoas briguentas e conflituosas. Já Provérbios 21:13 enfatiza a importância de ajudar os necessitados e Provérbios 21:21 ressalta que aqueles que buscam a justiça e a misericórdia encontrarão a vida, a justiça e a honra. Finalmente, Provérbios 21:23 destaca a importância de guardar a boca e manter a língua sob controle, evitando a fofoca e a difamação.
* Isaías 1:17: "Aprendei a fazer o bem; buscai a justiça, acabai com a opressão, fazei justiça ao órfão, defendei a causa da viúva." Este versículo incentiva a prática da justiça, assim como Provérbios 21:3.
* Provérbios 20:3: "Honra é do homem o desviar-se de questões, mas todo insensato é intrometido." Este versículo destaca a importância de evitar conflitos e brigas, assim como Provérbios 21:9.
* Salmos 112:9: "Ele espalhou, deu aos necessitados; a sua justiça subsiste para sempre, o seu poder será exaltado em glória." Este versículo enfatiza a importância de ajudar os necessitados, assim como Provérbios 21:13.
* Isaías 56:1: "Assim diz o Senhor: Mantende o juízo e fazei justiça, porque a minha salvação está prestes a vir, e a minha justiça, para se manifestar." Este versículo destaca a importância da justiça, assim como Provérbios 21:3 e 21:21.
* Salmos 34:13: "Guarda a tua língua do mal e os teus lábios de falarem o engano." Este versículo enfatiza a importância de controlar a língua, evitando fofocas e difamações, assim como Provérbios 21:23.
****

[[v24-21-1]]

^<<v24-21-1,1>>^ O coração do rei é uma água fluente nas mãos do Senhor: ele o inclina para qualquer parte que quiser.

[[v24-21-2]]

^<<v24-21-2,2>>^ Os caminhos do homem parecem retos aos seus olhos, mas cabe ao Senhor pesar os corações.

[[v24-21-3]]

^<<v24-21-3,3>>^ A prática da justiça e da equidade vale aos olhos do Senhor mais que os sacrifícios.

[[v24-21-4]]

^<<v24-21-4,4>>^ Olhares altivos ensoberbecem o coração; o luzeiro dos ímpios é o pecado.^&#42;1^

[[v24-21-5]]

^<<v24-21-5,5>>^ Os planos do homem ativo produzem abundância; a precipitação só traz penúria.

[[v24-21-6]]

^<<v24-21-6,6>>^ Tesouros adquiridos pela mentira: vaidade passageira para os que procuram a morte.

[[v24-21-7]]

^<<v24-21-7,7>>^ A violência dos ímpios os conduz à ruína, porque se recusam a praticar a justiça.

[[v24-21-8]]

^<<v24-21-8,8>>^ O caminho do perverso é tortuoso, mas o inocente age com retidão.

[[v24-21-9]]

^<<v24-21-9,9>>^ Melhor é habitar num canto do terraço do que conviver com uma mulher impertinente.

[[v24-21-10]]

^<<v24-21-10,10>>^ A alma do ímpio deseja o mal; nem mesmo seu amigo encontrará graça a seus olhos.

[[v24-21-11]]

^<<v24-21-11,11>>^ Quando se pune o zombador, o simples torna-se sábio; quando se adverte o sábio, ele adquire a ciência.

[[v24-21-12]]

^<<v24-21-12,12>>^ O justo observa a casa do ímpio e precipita os maus na desventura.^&#42;1^

[[v24-21-13]]

^<<v24-21-13,13>>^ Quem se faz de surdo aos gritos do pobre não será ouvido, quando ele mesmo clamar.

[[v24-21-14]]

^<<v24-21-14,14>>^ Um presente dado sob o manto extingue a cólera; uma oferta concebida às ocultas acalma um furor violento.

[[v24-21-15]]

^<<v24-21-15,15>>^ Para o justo é uma alegria a prática da justiça, mas é um terror para aqueles que praticam a iniquidade.

[[v24-21-16]]

^<<v24-21-16,16>>^ O homem que se desvia do caminho da prudência repousará na companhia das trevas.

[[v24-21-17]]

^<<v24-21-17,17>>^ O que ama os banquetes será um homem indigente; o que ama o vinho e o óleo não se enriquecerá.

[[v24-21-18]]

^<<v24-21-18,18>>^ O ímpio serve de resgate para o justo e o pérfido para os homens retos.

[[v24-21-19]]

^<<v24-21-19,19>>^ Melhor é habitar no deserto do que com uma mulher impertinente e intrigante.

[[v24-21-20]]

^<<v24-21-20,20>>^ Na casa do sábio há preciosas reservas e óleo; um homem imprudente, porém, os absorverá.

[[v24-21-21]]

^<<v24-21-21,21>>^ Quem segue a justiça e a misericórdia, achará vida, justiça e glória.

[[v24-21-22]]

^<<v24-21-22,22>>^ O sábio toma de assalto a cidade dos heróis: destrói a fortaleza em que depositava confiança.

[[v24-21-23]]

^<<v24-21-23,23>>^ Quem vigia sua boca e sua língua preserva sua vida da angústia.

[[v24-21-24]]

^<<v24-21-24,24>>^ Chamamos de zombador um soberbo arrogante, que age com orgulho desmedido.

[[v24-21-25]]

^<<v24-21-25,25>>^ Os desejos do preguiçoso o matam porque suas mãos recusam o trabalho;

[[v24-21-26]]

^<<v24-21-26,26>>^ passam todo o dia a desejar com ardor, mas quem é justo dá largamente.

[[v24-21-27]]

^<<v24-21-27,27>>^ O sacrifício dos ímpios é abominável, mormente quando o oferecem com má intenção.

[[v24-21-28]]

^<<v24-21-28,28>>^ A testemunha mentirosa perecerá, mas o homem que escuta sempre poderá falar.

[[v24-21-29]]

^<<v24-21-29,29>>^ O ímpio aparenta um ar firme; o homem correto consolida seu proceder.

[[v24-21-30]]

^<<v24-21-30,30>>^ Nem a sabedoria, nem prudência, nem conselho podem prevalescer contra o Senhor.

[[v24-21-31]]

^<<v24-21-31,31>>^ Prepara-se o cavalo para o dia da batalha, mas é do Senhor que depende a vitória.

'''

xref:024-proverbios/024-proverbios-020.adoc#v24-20-0[&#60; Capítulo Anterior] | <<v24-21-0,Topo>> | xref:024-proverbios/024-proverbios-022.adoc#v24-22-0[Próximo Capítulo &#62;]