include::./index.adoc[]

[[v24-31-0]]
=== Provérbios, 31
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Provérbios 31 é um capítulo que fala sobre as qualidades de uma esposa virtuosa, que é trabalhadora, confiável, compassiva e sábia. Além disso, o capítulo também destaca a importância da justiça social e da sabedoria na liderança. Seguem abaixo cinco versículos relacionados com os temas abordados em Provérbios 31:
* Provérbios 11:16: "A mulher graciosa alcança honra, e os homens violentos alcançam riquezas." Este versículo destaca a importância da graça e da bondade como características valiosas em uma mulher, em contraste com a ganância e a violência.
* Provérbios 12:4: "A mulher virtuosa é a coroa do seu marido, mas a que o envergonha é como podridão nos seus ossos." Esse versículo reforça a importância da virtude em uma esposa, que traz honra e respeito para o marido.
* Provérbios 14:1: "A mulher sábia edifica a sua casa, mas a tola a derruba com as próprias mãos." Esse versículo destaca a importância da sabedoria em uma mulher, que contribui para a estabilidade e crescimento do lar.
* Provérbios 21:21: "O que segue a justiça e a bondade achará a vida, a justiça e a honra." Esse versículo destaca a importância da justiça e da bondade, tanto em relacionamentos pessoais quanto em liderança.
* Provérbios 31:8-9: "Abre a tua boca a favor do mudo, pelo direito de todos que se acham desamparados. Abre a tua boca, julga retamente e faze justiça aos pobres e aos necessitados." Este versículo destaca a importância da justiça social e do cuidado com os mais vulneráveis na sociedade, que são responsabilidades de líderes sábios e compassivos.
****

[[v24-31-1]]

^<<v24-31-1,1>>^ Palavras de Lamuel, rei de Massa, que lhe foram ensinadas por sua mãe:

[[v24-31-2]]

^<<v24-31-2,2>>^ Meu filho, filho de minhas entranhas, que te direi eu? Não, ó filho de meus votos!

[[v24-31-3]]

^<<v24-31-3,3>>^ Não dês teu vigor às mulheres e teu caminho àquelas que perdem os reis.

[[v24-31-4]]

^<<v24-31-4,4>>^ Não é próprio dos reis, Lamuel, não convém aos reis beber vinho, nem aos príncipes dar-se aos licores,

[[v24-31-5]]

^<<v24-31-5,5>>^ para que, bebendo, eles não esqueçam a lei e não desconheçam o direito de todos os infelizes.

[[v24-31-6]]

^<<v24-31-6,6>>^ Dai a bebida forte àquele que desfalece e o vinho àquele que tem amargura no coração:

[[v24-31-7]]

^<<v24-31-7,7>>^ que ele beba e esquecerá sua miséria e já não se lembrará de suas mágoas.

[[v24-31-8]]

^<<v24-31-8,8>>^ Abre tua boca a favor do mundo, pela causa de todos os abandonados;

[[v24-31-9]]

^<<v24-31-9,9>>^ abre tua boca para pronunciar sentenças justas, faze justiça ao aflito e ao indigente.

[[v24-31-10]]

^<<v24-31-10,10>>^ Uma mulher virtuosa, quem pode encontrá-la? Superior ao das pérolas é o seu valor.

[[v24-31-11]]

^<<v24-31-11,11>>^ Confia nela o coração de seu marido, e jamais lhe faltará coisa alguma.

[[v24-31-12]]

^<<v24-31-12,12>>^ Ela lhe proporciona o bem, nunca o mal, em todos os dias de sua vida.

[[v24-31-13]]

^<<v24-31-13,13>>^ Ela procura lã e linho e trabalha com mão alegre.

[[v24-31-14]]

^<<v24-31-14,14>>^ Semelhante ao navio do mercador, manda vir seus víveres de longe.

[[v24-31-15]]

^<<v24-31-15,15>>^ Levanta-se, ainda de noite, distribui a comida à sua casa e a tarefa às suas servas.^&#42;1^

[[v24-31-16]]

^<<v24-31-16,16>>^ Ela encontra uma terra, adquire-a. Planta uma vinha com o ganho de suas mãos.

[[v24-31-17]]

^<<v24-31-17,17>>^ Cinge os rins de fortaleza, revigora seus braços.

[[v24-31-18]]

^<<v24-31-18,18>>^ Alegra-se com o seu lucro, e sua lâmpada não se apaga durante a noite.

[[v24-31-19]]

^<<v24-31-19,19>>^ Põe a mão na roca, seus dedos manejam o fuso.

[[v24-31-20]]

^<<v24-31-20,20>>^ Estende os braços ao infeliz e abre a mão ao indigente.

[[v24-31-21]]

^<<v24-31-21,21>>^ Ela não teme a neve em sua casa, porque toda a sua família tem vestes duplas.

[[v24-31-22]]

^<<v24-31-22,22>>^ Faz para si cobertas: suas vestes são de linho fino e de púrpura.

[[v24-31-23]]

^<<v24-31-23,23>>^ Seu marido é considerado nas portas da cidade, quando se senta com os anciãos da terra.

[[v24-31-24]]

^<<v24-31-24,24>>^ Tece linho e o vende, fornece cintos ao mercador.

[[v24-31-25]]

^<<v24-31-25,25>>^ Fortaleza e graça lhe servem de ornamentos; ri-se do dia de amanhã.

[[v24-31-26]]

^<<v24-31-26,26>>^ Abre a boca com sabedoria, amáveis instruções surgem de sua língua.

[[v24-31-27]]

^<<v24-31-27,27>>^ Vigia o andamento de sua casa e não come o pão da ociosidade.

[[v24-31-28]]

^<<v24-31-28,28>>^ Seus filhos se levantam para proclamá-la bem-aventurada e seu marido para elogiá-la.

[[v24-31-29]]

^<<v24-31-29,29>>^ “Muitas mulheres demonstram vigor, mas tu excedes a todas.”

[[v24-31-30]]

^<<v24-31-30,30>>^ A graça é falaz e a beleza é vã; a mulher inteligente é a que se deve louvar.^&#42;1^

[[v24-31-31]]

^<<v24-31-31,31>>^ Dai-lhe o fruto de suas mãos e que suas obras a louvem nas portas da cidade.

'''

xref:024-proverbios/024-proverbios-030.adoc#v24-30-0[&#60; Capítulo Anterior] | <<v24-31-0,Topo>> | xref:025-eclesiastes/025-eclesiastes-001.adoc#v25-1-0[Próximo Capítulo &#62;]