include::./index.adoc[]

[[v24-5-0]]
=== Provérbios, 5
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Provérbios 5 fala sobre a importância da fidelidade conjugal e do perigo da imoralidade sexual. O capítulo adverte que ceder à tentação da imoralidade pode ter graves consequências, incluindo a ruína pessoal e a destruição de relacionamentos.
* 1 Coríntios 6:18: "Fugi da imoralidade sexual. Todos os outros pecados que alguém comete, fora do corpo os comete; mas quem peca sexualmente, peca contra o seu próprio corpo." Este versículo destaca a seriedade do pecado sexual e a necessidade de evitar a tentação da imoralidade.
* Hebreus 13:4: "Digno de honra entre todos seja o matrimônio, bem como o leito sem mácula; porque Deus julgará os impuros e adúlteros." Este versículo enfatiza a importância da fidelidade conjugal e a responsabilidade de manter o casamento puro.
* 2 Samuel 11:2-4: "E aconteceu que, numa tarde, Davi levantou-se do seu leito, e andava passeando no terraço da casa real; e viu dalí uma mulher que se estava lavando; e era esta mulher mui formosa à vista. E enviou Davi, e perguntou a respeito da mulher. E disseram-lhe: Porventura não é esta Bate-Seba, filha de Eliã, mulher de Urias, o heteu?" Este versículo conta a história de Davi, que cedeu à tentação da imoralidade sexual e teve graves consequências em sua vida e em seu reinado.
* 1 Tessalonicenses 4:3-5: "Porque esta é a vontade de Deus, a vossa santificação; que vos abstenhais da prostituição; que cada um de vós saiba possuir o seu vaso em santificação e honra, não na paixão da concupiscência, como os gentios que não conhecem a Deus." Este versículo exorta os cristãos a viverem uma vida santa e a se absterem da imoralidade sexual.
* Mateus 5:28: "Eu, porém, vos digo que qualquer que olhar para uma mulher com intenção impura, em seu coração, já adulterou com ela." Este versículo destaca a importância do controle da mente e dos pensamentos, e que a fidelidade conjugal não se limita apenas às ações físicas, mas também aos pensamentos e desejos.
****

[[v24-5-1]]

^<<v24-5-1,1>>^ Meu filho, atende à minha sabedoria, presta atenção à minha razão,

[[v24-5-2]]

^<<v24-5-2,2>>^ a fim de conservares o sentido das coisas e guardares a ciência em teus lábios.

[[v24-5-3]]

^<<v24-5-3,3>>^ Porque os lábios da mulher alheia destilam o mel; seu paladar é mais oleoso que o azeite.

[[v24-5-4]]

^<<v24-5-4,4>>^ No fim, porém, é amarga como o absinto, aguda como a espada de dois gumes.

[[v24-5-5]]

^<<v24-5-5,5>>^ Seus pés se encaminham para a morte, seus passos atingem a região dos mortos.

[[v24-5-6]]

^<<v24-5-6,6>>^ Longe de andarem pela vereda da vida, seus passos se extraviam, sem saber para onde.

[[v24-5-7]]

^<<v24-5-7,7>>^ Escutai-me, pois, meus filhos, não vos aparteis das palavras de minha boca.

[[v24-5-8]]

^<<v24-5-8,8>>^ Afasta dela teu caminho, não te aproximes da porta de sua casa,

[[v24-5-9]]

^<<v24-5-9,9>>^ para que não seja entregue a outros tua fortuna e tua vida a um homem cruel;

[[v24-5-10]]

^<<v24-5-10,10>>^ para que estranhos não se fartem de teus haveres e o fruto de teu trabalho não passe para a casa alheia;

[[v24-5-11]]

^<<v24-5-11,11>>^ para que não gemas no fim, quando forem consumidas tuas carnes e teu corpo

[[v24-5-12]]

^<<v24-5-12,12>>^ e tiveres que dizer: “Por que odiei a disciplina, e meu coração desdenhou a correção?

[[v24-5-13]]

^<<v24-5-13,13>>^ Por que não ouvi a voz de meus mestres, nem dei ouvido aos meus educadores?

[[v24-5-14]]

^<<v24-5-14,14>>^ Por pouco eu chegaria ao cúmulo da desgraça no meio da assembleia do povo”.

[[v24-5-15]]

^<<v24-5-15,15>>^ Bebe a água do teu poço e das correntes de tua cisterna.^&#42;1^

[[v24-5-16]]

^<<v24-5-16,16>>^ Tuas fontes se derramarão por fora e teus arroios nas ruas?

[[v24-5-17]]

^<<v24-5-17,17>>^ Sejam eles só para ti, sem que os estranhos neles tomem parte.

[[v24-5-18]]

^<<v24-5-18,18>>^ Seja bendita a tua fonte! Regozija-te com a mulher de tua juventude,

[[v24-5-19]]

^<<v24-5-19,19>>^ corça de amor, serva encantadora. Que sejas sempre embriagado com seus encantos e que seus amores te embriaguem sem cessar!

[[v24-5-20]]

^<<v24-5-20,20>>^ Por que hás de te enamorar de uma alheia e abraçar o seio de uma estranha?

[[v24-5-21]]

^<<v24-5-21,21>>^ Pois o Senhor olha os caminhos dos homens e observa todas as suas veredas.

[[v24-5-22]]

^<<v24-5-22,22>>^ O homem será preso por suas próprias faltas e ligado com as cadeias de seu pecado.

[[v24-5-23]]

^<<v24-5-23,23>>^ Perecerá por falta de correção e se desviará pelo excesso de sua loucura.

'''

xref:024-proverbios/024-proverbios-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-proverbios/024-proverbios-006.adoc#v24-6-0[Próximo Capítulo &#62;]