include::./index.adoc[]

[[v24-23-0]]
=== Provérbios, 23
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 23 do livro de Provérbios trata sobre a importância da disciplina, a moderação na alimentação e o cuidado com as más companhias. Provérbios 23:4-5 adverte sobre a inutilidade de buscar riquezas e a importância de manter o foco nas coisas mais importantes. Já Provérbios 23:13-14 destaca a importância da disciplina e da correção, enquanto Provérbios 23:20-21 adverte sobre os perigos do excesso na bebida alcoólica e da má companhia. Finalmente, Provérbios 23:22-25 enfatiza a importância do respeito aos pais e a valorização da sabedoria.
* Provérbios 22:6: "Ensina a criança no caminho em que deve andar, e mesmo quando for velho não se desviará dele." Este versículo destaca a importância da disciplina e da correção, assim como Provérbios 23:13-14.
* 1 Coríntios 6:12: "Todas as coisas me são lícitas, mas nem todas as coisas convêm; todas as coisas me são lícitas, mas eu não me deixarei dominar por nenhuma." Este versículo adverte sobre a importância da moderação e do autocontrole, assim como Provérbios 23:1-3 e 23:20-21.
* Provérbios 1:10: "Filho meu, se os pecadores procuram te seduzir, não o consintas." Este versículo adverte sobre os perigos da má companhia, assim como Provérbios 23:20-21.
* Efésios 6:1-3: "Filhos, obedecei a vossos pais no Senhor, pois isto é justo. Honra a teu pai e a tua mãe (que é o primeiro mandamento com promessa), para que te vá bem, e sejas de longa vida sobre a terra." Este versículo enfatiza a importância do respeito aos pais, assim como Provérbios 23:22-25.
* Colossenses 3:23-24: "E tudo o que fizerdes, fazei-o de todo o coração, como para o Senhor e não para homens, sabendo que do Senhor recebereis como recompensa a herança. Servi a Cristo, o Senhor." Este versículo destaca a importância de manter o foco nas coisas mais importantes, assim como Provérbios 23:4-5.
****

[[v24-23-1]]

^<<v24-23-1,1>>^ Quando te assentares à mesa com um grande, considera com atenção quem está diante de ti:

[[v24-23-2]]

^<<v24-23-2,2>>^ põe uma faca na tua garganta, se tu sentes muito apetite;

[[v24-23-3]]

^<<v24-23-3,3>>^ não cobices seus manjares que são alimentos enganosos.

[[v24-23-4]]

^<<v24-23-4,4>>^ Não te afadigues para te enriqueceres, evita aplicar a isso teu espírito.

[[v24-23-5]]

^<<v24-23-5,5>>^ Mal fixas os olhos nos bens, e nada mais há, porque a riqueza tem asas como a águia que voa para o céu.

[[v24-23-6]]

^<<v24-23-6,6>>^ Não comas com homem invejoso, não cobices seus manjares,

[[v24-23-7]]

^<<v24-23-7,7>>^ porque ele se mostra tal qual se calculou em si mesmo. Ele te diz: “Come e bebe”, mas seu coração não está contigo.^&#42;1^

[[v24-23-8]]

^<<v24-23-8,8>>^ Comido o bocado, tu o vomitarás e desperdiçarás tuas amabilidades.

[[v24-23-9]]

^<<v24-23-9,9>>^ Não fales aos ouvidos do insensato porque ele desprezaria a sabedoria de tuas palavras.

[[v24-23-10]]

^<<v24-23-10,10>>^ Não toques no marco antigo, não penetres na terra dos órfãos,

[[v24-23-11]]

^<<v24-23-11,11>>^ porque seu vingador é poderoso e defenderá sua causa contra ti.^&#42;1^

[[v24-23-12]]

^<<v24-23-12,12>>^ Aplica teu coração à instrução e teus ouvidos às palavras da ciência.

[[v24-23-13]]

^<<v24-23-13,13>>^ Não poupes ao menino a correção: se tu o castigares com a vara, ele não morrerá,

[[v24-23-14]]

^<<v24-23-14,14>>^ castigando-o com a vara, salvarás sua vida da morada dos mortos.

[[v24-23-15]]

^<<v24-23-15,15>>^ Meu filho, se o teu espírito for sábio, meu coração se alegrará contigo!

[[v24-23-16]]

^<<v24-23-16,16>>^ Meus rins estremecerão de alegria, quando teus lábios proferirem palavras retas.^&#42;1^

[[v24-23-17]]

^<<v24-23-17,17>>^ Que teu coração não inveje os pecadores, mas permaneça sempre no temor do Senhor

[[v24-23-18]]

^<<v24-23-18,18>>^ porque então haverá certamente um futuro e tua esperança não será frustrada.

[[v24-23-19]]

^<<v24-23-19,19>>^ Ouve, meu filho: sê sabio, dirige teu coração pelo caminho reto,

[[v24-23-20]]

^<<v24-23-20,20>>^ não te ajuntes com os bebedores de vinho, com aqueles que devoram carnes,

[[v24-23-21]]

^<<v24-23-21,21>>^ pois o ébrio e o glutão se empobrecem e a sonolência veste-se com andrajos.^&#42;1^

[[v24-23-22]]

^<<v24-23-22,22>>^ Dá ouvidos a teu pai, àquele que te gerou e não desprezes tua mãe quando envelhecer.

[[v24-23-23]]

^<<v24-23-23,23>>^ Adquire a verdade e não a vendas, adquire sabedoria, instruções e inteligência.

[[v24-23-24]]

^<<v24-23-24,24>>^ O pai do justo exultará de alegria; aquele que gerou um sábio se alegrará nele.

[[v24-23-25]]

^<<v24-23-25,25>>^ Que teu pai se alegre por tua causa, que viva na alegria aquela que te deu à luz!

[[v24-23-26]]

^<<v24-23-26,26>>^ Meu filho, dá-me teu coração. Que teus olhos observem meus caminhos,

[[v24-23-27]]

^<<v24-23-27,27>>^ pois a meretriz é uma fossa profunda e a entranha, um poço estreito:

[[v24-23-28]]

^<<v24-23-28,28>>^ como um salteador ele fica de emboscada e, entre os homens, multiplica os infiéis.

[[v24-23-29]]

^<<v24-23-29,29>>^ Para quem os “ah”? Para quem os “ais”? Para quem as contendas? Para quem as queixas? Para quem as feridas sem motivo? Para quem o vermelho dos olhos?

[[v24-23-30]]

^<<v24-23-30,30>>^ Para aqueles que permanecem junto ao vinho, para aqueles que vão saborear o vinho misturado.

[[v24-23-31]]

^<<v24-23-31,31>>^ Não consideres o vinho: “como ele é vermelho, como brilha na taça, como corre suavemente!”.

[[v24-23-32]]

^<<v24-23-32,32>>^ Mas, no fim, morde como uma serpente e pica como um basilisco!

[[v24-23-33]]

^<<v24-23-33,33>>^ Os teus olhos verão coisas estranhas, teu coração pronunciará coisas incoerentes.

[[v24-23-34]]

^<<v24-23-34,34>>^ Serás como um homem adormecido no fundo do mar, ou deitado no cimo dum mastro:

[[v24-23-35]]

^<<v24-23-35,35>>^ “Feriram-me – dirás tu –; e não sinto dor!”. “Bateram-me... e não sinto nada. Quando despertei eu? Quero mais ainda!”

'''

xref:024-proverbios/024-proverbios-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-proverbios/024-proverbios-024.adoc#v24-24-0[Próximo Capítulo &#62;]