include::./index.adoc[]

[[v24-29-0]]
=== Provérbios, 29
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 29 do livro de Provérbios trata principalmente sobre a justiça e suas consequências, bem como a sabedoria e a tolice. Também aborda o tema da correção e disciplina dos filhos. Os seguintes versículos são relacionados com esses temas:
* Provérbios 11:18: "O ímpio recebe salário enganoso, mas o que semeia justiça terá galardão certo." Esse versículo enfatiza a importância da justiça e mostra a diferença entre as consequências para aqueles que agem justamente e para aqueles que são injustos.
* Provérbios 12:1: "O que ama a instrução ama o conhecimento, mas o que odeia a repreensão é estúpido." Este versículo destaca a importância da correção e disciplina para o crescimento e desenvolvimento pessoal, especialmente na busca de sabedoria.
* Provérbios 14:16: "O sábio teme, e desvia-se do mal, mas o tolo se encoleriza, e dá-se por seguro." Este versículo fala sobre a sabedoria de se evitar o mal e as consequências de agir impulsivamente.
* Provérbios 17:10: "A repreensão penetra mais profundamente no prudente do que cem açoites no tolo." Este versículo destaca a importância da correção em nossa vida e que ela é mais eficaz para aqueles que são sábios e procuram aprender.
* Provérbios 19:18: "Castiga o teu filho enquanto há esperança, mas não te deixes levar a que o matem." Este versículo fala sobre a importância da disciplina e correção dos filhos, mostrando que é melhor fazê-lo enquanto ainda há chance de mudança e crescimento.
****

[[v24-29-1]]

^<<v24-29-1,1>>^ O homem que, apesar das admoestações, se obstina será logo irremediavelmente arruinado.

[[v24-29-2]]

^<<v24-29-2,2>>^ Quando dominam os justos, alegra-se o povo; quando governa o ímpio, o povo geme.

[[v24-29-3]]

^<<v24-29-3,3>>^ Quem ama a sabedoria alegra seu pai; o que frequenta as prostitutas dissipa sua fortuna.

[[v24-29-4]]

^<<v24-29-4,4>>^ É pela justiça que um rei firma seu país, mas aquele que o sobrecarrega com muitos impostos o arruína.

[[v24-29-5]]

^<<v24-29-5,5>>^ O homem que adula seu próximo estende redes aos seus pés.

[[v24-29-6]]

^<<v24-29-6,6>>^ No delito do ímpio há um ardil, mas o justo corre alegremente.

[[v24-29-7]]

^<<v24-29-7,7>>^ O justo conhece a causa dos pobres; o ímpio a ignora.

[[v24-29-8]]

^<<v24-29-8,8>>^ Os escarnecedores ateiam fogo na cidade, mas os sábios acalmam o furor.

[[v24-29-9]]

^<<v24-29-9,9>>^ Discute um sábio com um tolo? Que ele se zangue ou que ele se ria não terá paz.

[[v24-29-10]]

^<<v24-29-10,10>>^ Os homens sanguinários odeiam o íntegro, mas os homens retos tomam cuidado com sua vida.

[[v24-29-11]]

^<<v24-29-11,11>>^ O insensato desafoga toda sua ira, mas o sábio a domina e a recalca.

[[v24-29-12]]

^<<v24-29-12,12>>^ Quando um soberano presta atenção às mentiras, todos os seus servidores tornam-se maus.

[[v24-29-13]]

^<<v24-29-13,13>>^ O pobre e o opressor se encontram: é o Senhor que ilumina os olhos de cada um.

[[v24-29-14]]

^<<v24-29-14,14>>^ Um rei que julga com equidade os humildes terá seu trono firmado para sempre.

[[v24-29-15]]

^<<v24-29-15,15>>^ Vara e correção dão a sabedoria; menino abandonado à sua vontade se torna a vergonha da mãe.

[[v24-29-16]]

^<<v24-29-16,16>>^ Quando se multiplicam os ímpios, multiplica-se o crime, mas os justos contemplarão sua queda.

[[v24-29-17]]

^<<v24-29-17,17>>^ Corrige teu filho e ele te dará repouso e será as delícias de tua vida.

[[v24-29-18]]

^<<v24-29-18,18>>^ Por falta de visão, o povo vive sem freios; ditoso o que observa a instrução!^&#42;1^

[[v24-29-19]]

^<<v24-29-19,19>>^ Não é com palavras que se corrige um escravo, porque ele compreende, mas não se atém a elas.

[[v24-29-20]]

^<<v24-29-20,20>>^ Viste um homem precipitado no falar: há mais esperança num tolo do que nele.

[[v24-29-21]]

^<<v24-29-21,21>>^ Um escravo mimado desde sua juventude, acaba por se tornar desobediente.

[[v24-29-22]]

^<<v24-29-22,22>>^ Um homem irascível excita contendas; o colérico acumula as faltas.

[[v24-29-23]]

^<<v24-29-23,23>>^ O orgulho de um homem leva-o à humilhação, mas o humilde de espírito obtém a glória.

[[v24-29-24]]

^<<v24-29-24,24>>^ Quem partilha com o ladrão, odeia-se a si mesmo; ouve a maldição e nada denuncia.^&#42;1^

[[v24-29-25]]

^<<v24-29-25,25>>^ O temor dos homens prepara um laço, mas quem confia no Senhor permanece seguro.

[[v24-29-26]]

^<<v24-29-26,26>>^ Muitos buscam o favor de um príncipe, mas é do Senhor que cada homem alcança justiça.

[[v24-29-27]]

^<<v24-29-27,27>>^ O homem iníquo é abominado pelos justos; o ímpio abomina aquele que anda pelo caminho certo.

'''

xref:024-proverbios/024-proverbios-028.adoc#v24-28-0[&#60; Capítulo Anterior] | <<v24-29-0,Topo>> | xref:024-proverbios/024-proverbios-030.adoc#v24-30-0[Próximo Capítulo &#62;]