include::./index.adoc[]

[[v24-25-0]]
=== Provérbios, 25
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 25 do livro de Provérbios contém uma coleção de provérbios que lidam com vários temas, como a humildade, a paciência, a sabedoria, a bondade e a honestidade. Provérbios 25:2 destaca a importância de se buscar a sabedoria e a honra. Já Provérbios 25:6-7 enfatiza a importância da humildade, e como é melhor ser convidado a um lugar de honra do que presumir um lugar que não nos pertence. Provérbios 25:11-12 destaca a beleza das palavras bem escolhidas e o efeito positivo que elas podem ter na vida de alguém. Provérbios 25:21-22 enfatiza a importância da bondade, e como ser gentil com os inimigos pode levá-los a mudar de atitude. Finalmente, Provérbios 25:28 destaca a importância da paciência e do autocontrole.
* Provérbios 4:7: "A sabedoria é a principal coisa; adquire pois a sabedoria, emprega tudo o que possuis na aquisição de entendimento." Este versículo destaca a importância de buscar a sabedoria, assim como Provérbios 25:2.
* Provérbios 16:32: "Melhor é o longânimo do que o valente, e o que governa o seu espírito do que o que toma uma cidade." Este versículo enfatiza a importância da paciência e do autocontrole, assim como Provérbios 25:28.
* Efésios 4:29: "Não saia da vossa boca nenhuma palavra torpe, e sim unicamente a que for boa para edificação, conforme a necessidade, e, assim, transmita graça aos que ouvem." Este versículo destaca a beleza das palavras bem escolhidas, assim como Provérbios 25:11-12.
* Romanos 12:20-21: "Pelo contrário, se o teu inimigo tiver fome, dá-lhe de comer; se tiver sede, dá-lhe de beber; porque, fazendo isto, amontoarás brasas vivas sobre a sua cabeça. Não te deixes vencer pelo mal, mas vence o mal com o bem." Este versículo enfatiza a importância da bondade, assim como Provérbios 25:21-22.
* Provérbios 11:2: "Vindo a soberba, sobrevém a desonra; mas com os humildes está a sabedoria." Este versículo destaca a importância da humildade, assim como Provérbios 25:6-7.
****

[[v24-25-1]]

^<<v24-25-1,1>>^ Ainda alguns provérbios de Salomão, recolhidos pelos homens de Ezequias, rei de Judá.

[[v24-25-2]]

^<<v24-25-2,2>>^ A glória de Deus é ocultar uma coisa; a glória dos reis é esquadrinhá-la.

[[v24-25-3]]

^<<v24-25-3,3>>^ A altura do céu, a profundeza da terra são impenetráveis, bem como o coração dos reis.

[[v24-25-4]]

^<<v24-25-4,4>>^ Tira as escórias da prata e terás um vaso para o ourives;

[[v24-25-5]]

^<<v24-25-5,5>>^ afasta o mau da presença do rei e seu trono se firmará na justiça.

[[v24-25-6]]

^<<v24-25-6,6>>^ Não te faças de pretensioso diante do rei, não te ponhas no lugar dos grandes.

[[v24-25-7]]

^<<v24-25-7,7>>^ É melhor que te digam: “Sobe aqui!”, do que seres humilhado diante de um personagem. O que teus olhos viram,^&#42;1^

[[v24-25-8]]

^<<v24-25-8,8>>^ não o descubras com precipitação numa contenda, pois, no final das contas, que farás tu quando o outro te houver confundido?

[[v24-25-9]]

^<<v24-25-9,9>>^ Trata teu negócio com teu próximo de maneira a não revelar o segredo de outro,

[[v24-25-10]]

^<<v24-25-10,10>>^ para que não sejas repreendido por aquele que o ouviu nem incorras em descrédito irreparável.

[[v24-25-11]]

^<<v24-25-11,11>>^ Maçãs de ouro sobre prata gravada: tais são as palavras oportunas.^&#42;1^

[[v24-25-12]]

^<<v24-25-12,12>>^ Anel de ouro, joia de ouro fino: tal é o sábio que admoesta um ouvido atento.

[[v24-25-13]]

^<<v24-25-13,13>>^ Frescor de neve no tempo da colheita, tal é um mensageiro fiel para quem o envia: ele restaura a alma de seu senhor.

[[v24-25-14]]

^<<v24-25-14,14>>^ Nuvens e vento sem chuva: tal é o homem que se gaba falsamente de dar.

[[v24-25-15]]

^<<v24-25-15,15>>^ Pela paciência o juiz se deixa aplacar: a língua que fala com brandura pode quebrantar ossos.

[[v24-25-16]]

^<<v24-25-16,16>>^ Achaste mel? Come o que for suficiente: se comeres demais, tu o vomitarás.

[[v24-25-17]]

^<<v24-25-17,17>>^ Põe raramente o pé na casa do vizinho: enfastiado de ti, ele te viria a aborrecer.

[[v24-25-18]]

^<<v24-25-18,18>>^ Clava, espada, flecha penetrante: tal é o que usa de falso testemunho contra seu próximo.

[[v24-25-19]]

^<<v24-25-19,19>>^ Dente arruinado, pé que resvala: tal é a confiança de um pérfido no dia da desventura.

[[v24-25-20]]

^<<v24-25-20,20>>^ Tirar a capa num dia de frio, derramar vinagre numa ferida: isso faz aquele que canta canções a um coração atribulado.^&#42;1^

[[v24-25-21]]

^<<v24-25-21,21>>^ Tem o teu inimigo fome? Dá-lhe de comer. Tem sede? Dá-lhe de beber:

[[v24-25-22]]

^<<v24-25-22,22>>^ assim amontoarás brasas ardentes sobre sua cabeça e o Senhor te recompensará.^&#42;1^

[[v24-25-23]]

^<<v24-25-23,23>>^ O vento norte traz chuva e a língua detratora anuvia os semblantes.

[[v24-25-24]]

^<<v24-25-24,24>>^ É melhor habitar um canto do terraço do que viver com uma mulher impertinente.

[[v24-25-25]]

^<<v24-25-25,25>>^ Água fresca para uma garganta sedenta: tal é uma boa-nova vinda de terra longínqua.

[[v24-25-26]]

^<<v24-25-26,26>>^ Fonte turva e manancial contaminado: tal é o justo que cede diante do ímpio.

[[v24-25-27]]

^<<v24-25-27,27>>^ Comer mel em demasia não é bom: usa de moderação nas palavras elogiosas.^&#42;1^

[[v24-25-28]]

^<<v24-25-28,28>>^ Como uma cidade desmantelada, sem muralhas: tal é o homem que não é senhor de si.

'''

xref:024-proverbios/024-proverbios-024.adoc#v24-24-0[&#60; Capítulo Anterior] | <<v24-25-0,Topo>> | xref:024-proverbios/024-proverbios-026.adoc#v24-26-0[Próximo Capítulo &#62;]