include::./index.adoc[]

[[v24-9-0]]
=== Provérbios, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Provérbios 9 apresenta a sabedoria personificada como uma mulher que convida os simples a comerem do seu banquete e a se tornarem sábios. O capítulo contrasta a sabedoria com a tolice, enfatizando a importância de seguir o caminho da sabedoria para se alcançar uma vida plena e satisfatória.
* Tiago 1:5: "E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente e não o lança em rosto; e ser-lhe-á dada." Este versículo destaca a importância de buscar a sabedoria de Deus em todas as situações e reconhecer que Ele é a fonte da verdadeira sabedoria.
* Provérbios 3:13-14: "Bem-aventurado o homem que acha sabedoria, e o homem que adquire conhecimento; porque é melhor a sua mercadoria do que a mercadoria de prata, e maior o seu lucro do que o ouro mais fino." Este versículo destaca a importância da sabedoria como um bem mais valioso do que o dinheiro e o ouro.
* Colossenses 2:2-3: "Para que os seus corações sejam consolados, e estejam unidos em amor e enriquecidos da plenitude da inteligência, para conhecimento do mistério de Deus e Pai, e de Cristo, em quem estão escondidos todos os tesouros da sabedoria e da ciência." Este versículo destaca a importância de conhecer a sabedoria de Deus em Cristo, como meio de se alcançar um entendimento pleno da verdade.
* Provérbios 10:14: "Os sábios entesouram o conhecimento, mas a boca do insensato é uma destruição iminente." Este versículo destaca a importância de valorizar e guardar a sabedoria, em contraste com a tolice que leva à destruição.
* Provérbios 16:16: "Quanto melhor é adquirir a sabedoria do que o ouro! e quanto mais excelente, adquirir a prudência do que a prata!" Este versículo enfatiza novamente a importância de se buscar a sabedoria e a prudência, como tesouros mais valiosos do que o dinheiro e as posses materiais.
****

[[v24-9-1]]

^<<v24-9-1,1>>^ A Sabedoria edificou sua casa, talhou sete colunas.^&#42;1^

[[v24-9-2]]

^<<v24-9-2,2>>^ Matou seus animais, preparou seu vinho e dispôs a mesa.

[[v24-9-3]]

^<<v24-9-3,3>>^ Enviou servas, para que anunciassem nos pontos mais elevados da cidade:

[[v24-9-4]]

^<<v24-9-4,4>>^ “Quem for simples apresente-se!”. Aos insensatos ela disse:

[[v24-9-5]]

^<<v24-9-5,5>>^ “Vinde comer o meu pão e beber o vinho que preparei.

[[v24-9-6]]

^<<v24-9-6,6>>^ Deixai a insensatez e vivereis; andai direito no caminho da inteligência!”.

[[v24-9-7]]

^<<v24-9-7,7>>^ Quem censura um mofador, atrai sobre si a zombaria; o que repreende o ímpio, arrisca-se a uma afronta.^&#42;1^

[[v24-9-8]]

^<<v24-9-8,8>>^ Não repreendas o mofador, pois ele te odiará. Repreende o sábio e ele te amará.

[[v24-9-9]]

^<<v24-9-9,9>>^ Dá ao sábio: ele se tornará mais sábio ainda, ensina ao justo e seu saber aumentará.

[[v24-9-10]]

^<<v24-9-10,10>>^ O temor do Senhor é o princípio da Sabedoria, e o conhecimento do Santo é a inteligência,^&#42;1^

[[v24-9-11]]

^<<v24-9-11,11>>^ porque por mim se multiplicarão teus dias e anos de vida te serão acrescentados.

[[v24-9-12]]

^<<v24-9-12,12>>^ Se tu és sábio, é para teu bem que o és, mas se tu és um “soberbo”, só tu sofrerás as consequências.

[[v24-9-13]]

^<<v24-9-13,13>>^ A senhora Loucura é irrequieta, uma tola que não sabe nada.

[[v24-9-14]]

^<<v24-9-14,14>>^ Ela se assenta à porta de sua casa, numa cadeira, nos pontos mais altos da cidade,

[[v24-9-15]]

^<<v24-9-15,15>>^ para convidar os viandantes que seguem direito seu caminho.

[[v24-9-16]]

^<<v24-9-16,16>>^ “Quem for simples venha para cá!” Aos insensatos, ela diz:

[[v24-9-17]]

^<<v24-9-17,17>>^ “As águas furtivas são mais doces e o pão tomado às escondidas é mais delicioso”.^&#42;1^

[[v24-9-18]]

^<<v24-9-18,18>>^ Ignora ele que ali há sombras e que os convidados da senhora Loucura jazem nas profundezas da região dos mortos.^&#42;1^

'''

xref:024-proverbios/024-proverbios-008.adoc#v24-8-0[&#60; Capítulo Anterior] | <<v24-9-0,Topo>> | xref:024-proverbios/024-proverbios-010.adoc#v24-10-0[Próximo Capítulo &#62;]