include::./index.adoc[]

[[v32-4-0]]
=== Baruc, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Baruc 4 é um capítulo do Antigo Testamento que fala sobre a restauração do povo de Israel após o exílio na Babilônia. O capítulo começa com uma exortação para que o povo de Israel se alegre e se regozije porque Deus os trouxe de volta para a terra de seus antepassados. Ele também destaca a importância da sabedoria e da obediência a Deus. A seguir estão cinco versículos relacionados aos temas abordados em Baruc 4, em ordem de proximidade com o capítulo:
* Isaías 40:1-2: "Consolai, consolai o meu povo, diz o vosso Deus. Falai confortavelmente a Jerusalém e clamai-lhe que já a sua malícia é acabada, que a sua iniquidade está expiada e que já recebeu em dobro da mão do Senhor por todos os seus pecados." Este versículo fala sobre a restauração do povo de Israel após o exílio na Babilônia, um tema central em Baruc 4.
* Deuteronômio 30:1-3: "Será que, quando todas estas coisas te acontecerem, a bênção e a maldição que pus diante de ti, meditares nelas no teu coração, entre todas as nações para onde te lançar o Senhor, teu Deus, e te converteres ao Senhor, teu Deus, e ouvires a sua voz conforme tudo o que te ordeno hoje, tu e teus filhos, com todo o teu coração e com toda a tua alma, então o Senhor, teu Deus, fará voltar do teu cativeiro e se compadecerá de ti." Este versículo também fala sobre a restauração do povo de Israel após o exílio na Babilônia, um tema central em Baruc 4.
* Salmos 126:1-2: "Quando o Senhor trouxe do cativeiro os que voltaram a Sião, estávamos como os que sonham. Então a nossa boca se encheu de riso e a nossa língua de cânticos; então se dizia entre os gentios: Grandes coisas fez o Senhor a estes." Este versículo fala sobre a alegria que o povo de Israel sentiu quando Deus os trouxe de volta para a terra de seus antepassados, um tema abordado em Baruc 4.
* Provérbios 3:5-6: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." Este versículo destaca a importância da sabedoria e da obediência a Deus, temas abordados em Baruc 4.
* Salmos 119:105: "Lâmpada para os meus pés é tua palavra e luz para o meu caminho." Este versículo também destaca a importância da sabedoria e da obediência a Deus, temas abordados em Baruc 4.
****

[[v32-4-1]]

^<<v32-4-1,1>>^ Ela é o livro dos mandamentos divinos e a Lei que subsiste para todo o sempre. Todos aqueles que a seguem adquirirão a vida, e os que a abandonam morrerão.

[[v32-4-2]]

^<<v32-4-2,2>>^ Volta para ela, Jacó, abraça-a. Caminha ao seu encontro, ao esplendor da sua luz.

[[v32-4-3]]

^<<v32-4-3,3>>^ Não entregues a outros esta glória, nem relegues esta salvação à nação estrangeira.^&#42;1^

[[v32-4-4]]

^<<v32-4-4,4>>^ Ditosos somos nós, Israel, porque a nós foi revelado o que agrada a Deus!

[[v32-4-5]]

^<<v32-4-5,5>>^ Coragem, povo meu, que trazeis o nome de Israel!

[[v32-4-6]]

^<<v32-4-6,6>>^ Fostes, em verdade, vendidos aos pagãos, não, porém, para serdes aniquilados. Por haverdes desencadeado a cólera divina é que fostes entregues aos inimigos.

[[v32-4-7]]

^<<v32-4-7,7>>^ Havíeis exasperado vosso Criador, ofertando sacrifícios aos demônios e não a Deus.

[[v32-4-8]]

^<<v32-4-8,8>>^ Esquecestes o vosso Criador, o Deus eterno, e contristastes Jerusalém, vossa nutriz.

[[v32-4-9]]

^<<v32-4-9,9>>^ Esta viu precipitar-se sobre vós a ira divina, e clamou: “Escutai, vizinhas de Sião! Fez-me Deus suportar cruel tormento.

[[v32-4-10]]

^<<v32-4-10,10>>^ Assisti à deportação de meus filhos e filhas, que o Eterno lhes infligiu.

[[v32-4-11]]

^<<v32-4-11,11>>^ Eu os educara com alegria e fui obrigada a deixá-los partir com lágrimas de luto.

[[v32-4-12]]

^<<v32-4-12,12>>^ Que ninguém se regozije com minha viuvez e meu desamparo! Por causa dos pecados de meus filhos vivo desolada, já que se afastaram da Lei de Deus,

[[v32-4-13]]

^<<v32-4-13,13>>^ negligenciando seus mandamentos, afastando-se dos caminhos de seus preceitos e não seguindo a vereda da disciplina segundo sua justiça.

[[v32-4-14]]

^<<v32-4-14,14>>^ Vinde, vizinhas de Sião! Pensai na deportação de meus filhos e filhas, que o Eterno lhes infligiu.

[[v32-4-15]]

^<<v32-4-15,15>>^ Lançou contra eles um povo longínquo, povo insolente, de linguagem bárbara, sem respeito pelo ancião, sem piedade para com o pequenino.

[[v32-4-16]]

^<<v32-4-16,16>>^ Roubou à viúva os bem-amados, deixando-me sozinha, sem as minhas filhas”.

[[v32-4-17]]

^<<v32-4-17,17>>^ E que posso eu fazer por vós?^&#42;1^

[[v32-4-18]]

^<<v32-4-18,18>>^ Somente aquele que vos infligiu estes males pode salvar-vos das mãos de vossos inimigos.

[[v32-4-19]]

^<<v32-4-19,19>>^ Ide, filhos meus! Ide! Quanto a mim, permanecerei na solidão.

[[v32-4-20]]

^<<v32-4-20,20>>^ Tirei minhas vestes dos dias de paz para revestir-me do saco dos suplicantes. Até meu último dia invocarei o Eterno.

[[v32-4-21]]

^<<v32-4-21,21>>^ Coragem, meus filhos! E vós também orai a Deus, a fim de que vos salve da mão poderosa de vossos inimigos!

[[v32-4-22]]

^<<v32-4-22,22>>^ Do Eterno espero a vossa libertação, espero que do Santo me venha a alegria, pela misericórdia que breve vos será concedida pelo Eterno, vosso Salvador.

[[v32-4-23]]

^<<v32-4-23,23>>^ Entre lágrimas e coberta de luto deixei-vos partir... Deus, porém, vos devolverá a mim para uma eterna alegria,

[[v32-4-24]]

^<<v32-4-24,24>>^ porque as vizinhas de Sião, que viram a vossa deportação, verão em breve Deus conceder-vos a libertação, seguida de imensa glória e de fulgor emanando do Eterno.

[[v32-4-25]]

^<<v32-4-25,25>>^ Suportai, filhos meus, com paciência o golpe da cólera divina. Fostes perseguidos por vossos inimigos; em breve, porém, assistireis à sua ruína, e sobre suas cervizes poreis os pés.

[[v32-4-26]]

^<<v32-4-26,26>>^ Meus delicados filhos tiveram de andar por ásperos caminhos, acossados, qual rebanho roubado pelo inimigo.

[[v32-4-27]]

^<<v32-4-27,27>>^ Coragem, porém, meus filhos. Orai a Deus, pois aquele que vos feriu, se lembrará de vós!

[[v32-4-28]]

^<<v32-4-28,28>>^ Quisestes apartar-vos de Deus; ponde agora dez vezes mais zelo em procurá-lo.

[[v32-4-29]]

^<<v32-4-29,29>>^ Porquanto, aquele que sobre vós precipitou a catástrofe vos concederá, com a libertação, eterno regozijo.

[[v32-4-30]]

^<<v32-4-30,30>>^ Coragem, Jerusalém! Aquele que te deu o nome te consolará.^&#42;1^

[[v32-4-31]]

^<<v32-4-31,31>>^ Miseráveis os que te maltrataram, e que se regozijaram com tua ruína!

[[v32-4-32]]

^<<v32-4-32,32>>^ Miseráveis as cidades em que teus filhos conheceram a servidão, miserável aquela que conservou teus cativos!

[[v32-4-33]]

^<<v32-4-33,33>>^ Em verdade, assim como se regozijou com tua queda, e triunfou, quando de tua ruína, assim também vai gemer com a própria desolação.

[[v32-4-34]]

^<<v32-4-34,34>>^ Aniquilarei a altivez de sua numerosa população, e sua arrogância se transformará em luto,

[[v32-4-35]]

^<<v32-4-35,35>>^ porque um fogo constante, vindo do Eterno, a atingirá e gênios maus vão persegui-la por muito tempo.

[[v32-4-36]]

^<<v32-4-36,36>>^ Jerusalém, volta o teu olhar para o Oriente, vê a alegria que te vem de Deus.

[[v32-4-37]]

^<<v32-4-37,37>>^ Olha! Eis que voltam os filhos que viras partir. Chegam do Oriente e do Ocidente, à voz do Altíssimo, repletos da alegria que lhes dá a glória de Deus.

'''

xref:032-baruc/032-baruc-003.adoc#v32-3-0[&#60; Capítulo Anterior] | <<v32-4-0,Topo>> | xref:032-baruc/032-baruc-005.adoc#v32-5-0[Próximo Capítulo &#62;]