include::./index.adoc[]

[[v21-68-0]]
=== Salmos, 68
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 68 é um poema que celebra a vitória de Deus sobre seus inimigos e a proteção que ele dá aos seus seguidores. O salmista canta louvores a Deus e o exalta como o protetor dos necessitados. Ele também fala da grandeza de Deus e de sua fidelidade ao seu povo. Abaixo estão cinco versículos relacionados com os temas abordados em Salmo 68:
* Deuteronômio 33:26-27: "Não há ninguém como o Deus de Jeshurun, que cavalga os céus para ajudá-lo, e monta nas nuvens para salvar você. O Deus eterno é a sua habitação, e sob seus braços eternos você está seguro. Ele expulsará o inimigo de diante de você e dirá: 'Destrua-o!'" - Esse versículo fala da proteção de Deus sobre o seu povo e da sua capacidade de derrotar os inimigos que se opõem a ele.
* Isaías 25:4: "Porque foste um refúgio para o pobre, um refúgio para o necessitado em sua angústia, um abrigo contra a tempestade e um abrigo contra o calor, quando o sopro dos opressores é como uma tempestade contra o muro." - Este versículo fala da proteção que Deus oferece aos necessitados e oprimidos, um tema que também é presente em Salmo 68.
* Isaías 40:28-31: "Você não sabe? Você não ouviu? O Senhor é o Deus eterno, o Criador de toda a terra. Ele não se cansa nem se fatiga; sua compreensão é insondável. Ele dá força ao cansado e aumenta o poder do fraco. Até os jovens se cansam e ficam exaustos, e os jovens tropeçam e caem; mas aqueles que esperam no Senhor renovarão suas forças. Eles vão subir com asas como águias; correrão e não se cansarão; caminharão e não desmaiarão." - Este versículo fala da força e proteção que Deus oferece aos seus seguidores.
* 2 Samuel 22:3-4: "O meu Deus é o meu rochedo, nele me refugio. Ele é o meu escudo e o poder que me salva, a minha torre alta. Clamo ao Senhor, que é digno de louvor, e sou salvo dos meus inimigos." - Esse versículo fala da proteção de Deus e da sua capacidade de salvar seus seguidores dos inimigos.
* Salmos 18:2-3: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio. Ele é o meu escudo e o poder que me salva, a minha torre alta. Clamo ao Senhor, que é digno de louvor, e sou salvo dos meus inimigos." - Este versículo é semelhante ao anterior e fala da proteção e refúgio que Deus oferece aos seus seguidores.
****

[[v21-68-1]]

^<<v21-68-1,1>>^ Ao mestre de canto. Segundo a melodia: “Os lírios”.^&#42;1^

[[v21-68-2]]

^<<v21-68-2,2>>^ Salvai-me, ó Deus, porque as águas me vão submergir.

[[v21-68-3]]

^<<v21-68-3,3>>^ Estou imerso num abismo de lodo, no qual não há onde firmar o pé. Vim a dar em águas profundas, encobrem-me as ondas.

[[v21-68-4]]

^<<v21-68-4,4>>^ Já cansado de tanto gritar, enrouqueceu-me a garganta. Enfraqueceram-se meus olhos, enquanto espero meu Deus.

[[v21-68-5]]

^<<v21-68-5,5>>^ Mais numerosos que os cabelos de minha cabeça são os que me detestam sem razão. São mais fortes que meus ossos os meus injustos inimigos.^&#42;1^ Porventura posso restituir o que não roubei?

[[v21-68-6]]

^<<v21-68-6,6>>^ Vós conheceis, ó Deus, a minha insipiência, e minhas faltas não vos são ocultas.

[[v21-68-7]]

^<<v21-68-7,7>>^ Os que esperam em vós, ó Senhor, Senhor dos exércitos, por minha causa não sejam confundidos. Que os que vos procuram, ó Deus de Israel, não tenham de que se envergonhar por minha causa,^&#42;1^

[[v21-68-8]]

^<<v21-68-8,8>>^ pois foi por vós que eu sofri afrontas, cobrindo-se meu o rosto de confusão.

[[v21-68-9]]

^<<v21-68-9,9>>^ Tornei-me um estranho para meus irmãos, um desconhecido para os filhos de minha mãe.

[[v21-68-10]]

^<<v21-68-10,10>>^ É que o zelo de vossa casa me consumiu, e os insultos dos que vos ultrajam caíram sobre mim.^&#42;1^

[[v21-68-11]]

^<<v21-68-11,11>>^ Por mortificar minha alma com jejuns, só recebi ultrajes.

[[v21-68-12]]

^<<v21-68-12,12>>^ Por trocar minhas roupas por um saco, tornei-me zombaria deles.

[[v21-68-13]]

^<<v21-68-13,13>>^ Falam de mim os que se assentam às portas da cidade, escarnecem-me os que bebem vinho.^&#42;1^

[[v21-68-14]]

^<<v21-68-14,14>>^ Minha oração, porém, sobe até vós, Senhor, na hora de vossa misericórdia, ó Deus. Na vossa imensa bondade, escutai-me, segundo a fidelidade de vosso socorro.

[[v21-68-15]]

^<<v21-68-15,15>>^ Tirai-me do lodo, para que não me afunde. Livrai-me dos que me detestam, salvai-me das águas profundas.

[[v21-68-16]]

^<<v21-68-16,16>>^ Não me deixeis submergir nas muitas águas, nem me devore o abismo. Nem se feche sobre mim a boca do poço.

[[v21-68-17]]

^<<v21-68-17,17>>^ Ouvi-me, Senhor, pois que vossa bondade é compassiva; em nome de vossa misericórdia, voltai-vos para mim.

[[v21-68-18]]

^<<v21-68-18,18>>^ Não escondais ao vosso servo a vista de vossa face; atendei-me depressa, pois estou muito atormentado.

[[v21-68-19]]

^<<v21-68-19,19>>^ Aproximai-vos de minha alma, livrai-me de meus inimigos.

[[v21-68-20]]

^<<v21-68-20,20>>^ Bem vedes minha vergonha, confusão e ignomínia. Ante vossos olhos estão os que me perseguem:

[[v21-68-21]]

^<<v21-68-21,21>>^ seus ultrajes abateram meu coração e desfaleci. Esperei em vão quem tivesse compaixão de mim, quem me consolasse, e não encontrei.

[[v21-68-22]]

^<<v21-68-22,22>>^ Puseram fel no meu alimento, na minha sede deram-me vinagre para beber.^&#42;1^

[[v21-68-23]]

^<<v21-68-23,23>>^ Torne-se a sua mesa um laço para eles, e uma armadilha para os seus amigos.

[[v21-68-24]]

^<<v21-68-24,24>>^ Que seus olhos se escureçam para não mais ver, que seus passos sejam sempre vacilantes.^&#42;1^

[[v21-68-25]]

^<<v21-68-25,25>>^ Despejai sobre eles a vossa cólera, e os atinja o fogo de vossa ira.

[[v21-68-26]]

^<<v21-68-26,26>>^ Seja devastada a sua morada, não haja quem habite em suas tendas,^&#42;1^

[[v21-68-27]]

^<<v21-68-27,27>>^ porque perseguiram aquele a quem atingistes, e aumentaram a dor daquele a quem feristes.

[[v21-68-28]]

^<<v21-68-28,28>>^ Deixai-os acumular falta sobre falta, e jamais sejam por vós reconhecidos como justos.

[[v21-68-29]]

^<<v21-68-29,29>>^ Sejam riscados do livro dos vivos, e não se inscrevam os seus nomes entre os justos.

[[v21-68-30]]

^<<v21-68-30,30>>^ Eu, porém, miserável e sofredor, seja protegido, ó Deus, pelo vosso auxílio.

[[v21-68-31]]

^<<v21-68-31,31>>^ Cantarei um cântico de louvor ao nome do Senhor, e o glorificarei com um hino de gratidão.

[[v21-68-32]]

^<<v21-68-32,32>>^ E isso a Deus será mais agradável que um touro, do que um novilho com chifres e unhas.

[[v21-68-33]]

^<<v21-68-33,33>>^ Ó vós, humildes, olhai e alegrai-vos; vós que buscais a Deus, reanime-se o vosso coração,

[[v21-68-34]]

^<<v21-68-34,34>>^ porque o Senhor ouve os necessitados, e seu povo cativo não despreza.

[[v21-68-35]]

^<<v21-68-35,35>>^ Louvem-no os céus e a terra, os mares e tudo o que neles se move.

[[v21-68-36]]

^<<v21-68-36,36>>^ Sim, Deus salvará Sião e reconstruirá as cidades de Judá. Para aí hão de voltar e a possuirão.

[[v21-68-37]]

^<<v21-68-37,37>>^ A linhagem de seus servos a receberá em herança, e os que amam o seu nome aí fixarão sua morada.

'''

xref:021-salmos/021-salmos-067.adoc#v21-67-0[&#60; Capítulo Anterior] | <<v21-68-0,Topo>> | xref:021-salmos/021-salmos-069.adoc#v21-69-0[Próximo Capítulo &#62;]