include::./index.adoc[]

[[v21-90-0]]
=== Salmos, 90
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 90 é uma oração atribuída a Moisés, que reflete sobre a brevidade da vida humana e a eternidade de Deus. Moisés implora a Deus para lembrar da fragilidade do ser humano e lhe conceder a sabedoria para viver cada dia como se fosse o último.
* Jó 14:5: "Uma vez que os seus dias estão marcados, o número dos seus meses está nas suas mãos; você estabeleceu os limites que não pode ultrapassar." Este versículo também fala sobre a limitação de tempo que cada pessoa tem nesta terra.
* Salmos 39:4-5: "Senhor, faze-me saber o meu fim e qual a medida dos meus dias, para que eu saiba quanto sou frágil. Deste aos meus dias o comprimento de um palmo; a duração da minha vida é nada diante de ti. De fato, cada pessoa, por mais firme que esteja, não passa de um sopro." Este salmo é semelhante ao Salmo 90, onde o salmista fala sobre a brevidade da vida humana e a necessidade de reconhecer nossa fragilidade diante de Deus.
* Salmos 102:24-27: "Eu digo: 'Ó meu Deus, não me leves no meio da minha vida, tu, cujos dias são de geração em geração. No princípio, fundaste a terra, e os céus são obras das tuas mãos. Eles perecerão, mas tu permanecerás; envelhecerão como roupa. Como roupas, tu os trocarás, e serão jogados fora." Este salmo é uma meditação sobre a eternidade de Deus e a temporalidade da criação.
* Tiago 4:14: "Vocês nem sabem o que lhes acontecerá amanhã! Que é a sua vida? Vocês são como a neblina que aparece por um pouco de tempo e depois se dissipa." Tiago faz uma exortação semelhante ao Salmo 90, lembrando-nos da incerteza da vida e da necessidade de confiar em Deus em todas as circunstâncias.
* Hebreus 9:27: "Da mesma forma, como o homem está destinado a morrer uma só vez e depois disso enfrentar o juízo." Este versículo fala sobre a certeza da morte e o julgamento que aguarda a todos. É uma lembrança da importância de viver com propósito e significado enquanto estamos aqui.
****

[[v21-90-1]]

^<<v21-90-1,1>>^ Tu que habitas sob a proteção do Altíssimo,^&#42;1^ que moras à sombra do Onipotente,

[[v21-90-2]]

^<<v21-90-2,2>>^ dize ao Senhor: “Sois meu refúgio e minha cidadela, meu Deus, em quem eu confio”.

[[v21-90-3]]

^<<v21-90-3,3>>^ É ele quem te livrará do laço do caçador, e da peste perniciosa.

[[v21-90-4]]

^<<v21-90-4,4>>^ Ele te cobrirá com suas plumas, sob suas asas encontrarás refúgio. Sua fidelidade te será um escudo de proteção.

[[v21-90-5]]

^<<v21-90-5,5>>^ Tu não temerás os terrores noturnos, nem a flecha que voa à luz do dia,

[[v21-90-6]]

^<<v21-90-6,6>>^ nem a peste que se propaga nas trevas, nem o mal que grassa ao meio-dia.

[[v21-90-7]]

^<<v21-90-7,7>>^ Caiam mil homens à tua esquerda e dez mil à tua direita: tu não serás atingido.

[[v21-90-8]]

^<<v21-90-8,8>>^ Porém, verás com teus próprios olhos, contemplarás o castigo dos pecadores,

[[v21-90-9]]

^<<v21-90-9,9>>^ porque o Senhor é teu refúgio. Escolheste, por asilo, o Altíssimo.

[[v21-90-10]]

^<<v21-90-10,10>>^ Nenhum mal te atingirá, nenhum flagelo chegará à tua tenda,

[[v21-90-11]]

^<<v21-90-11,11>>^ porque aos seus anjos ele mandou que te guardem em todos os teus caminhos.^&#42;1^

[[v21-90-12]]

^<<v21-90-12,12>>^ Eles te sustentarão em suas mãos, para que não tropeces em alguma pedra.^&#42;1^

[[v21-90-13]]

^<<v21-90-13,13>>^ Sobre serpente e víbora andarás, calcarás aos pés o leão e o dragão.

[[v21-90-14]]

^<<v21-90-14,14>>^ “Pois que se uniu a mim, eu o livrarei; e o protegerei, pois conhece o meu nome.

[[v21-90-15]]

^<<v21-90-15,15>>^ Quando me invocar, eu o atenderei; na tribulação estarei com ele. Hei de livrá-lo e o cobrirei de glória.

[[v21-90-16]]

^<<v21-90-16,16>>^ Será favorecido de longos dias, e eu lhe mostrarei a minha salvação.”

'''

xref:021-salmos/021-salmos-089.adoc#v21-89-0[&#60; Capítulo Anterior] | <<v21-90-0,Topo>> | xref:021-salmos/021-salmos-091.adoc#v21-91-0[Próximo Capítulo &#62;]