include::./index.adoc[]

[[v21-125-0]]
=== Salmos, 125
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 125 é um salmo de confiança em Deus e em sua proteção sobre seu povo. Ele fala sobre como aqueles que confiam em Deus são inabaláveis e como ele os protege de seus inimigos. Abaixo estão cinco versículos relacionados com os temas abordados em Salmo 125:
* Provérbios 3:26: "Porque o Senhor será a tua segurança, e guardará os teus pés de serem capturados." Este versículo enfatiza a proteção de Deus sobre aqueles que confiam nele e a segurança que ele traz.
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Este versículo fala sobre a presença constante de Deus com seu povo e sua disposição em ajudá-los e sustentá-los.
* Romanos 8:31: "Que diremos, pois, a estas coisas? Se Deus é por nós, quem será contra nós?" Este versículo destaca a proteção de Deus sobre seus filhos e como ele é mais poderoso do que qualquer um que se opõe a eles.
* Salmos 91:11: "Porque ele dará ordens aos seus anjos a teu respeito, para que te guardem em todos os teus caminhos." Este versículo fala sobre como Deus envia seus anjos para proteger e guardar aqueles que confiam nele.
* Provérbios 18:10: "O nome do Senhor é uma torre forte; os justos correm para ela, e estão seguros." Este versículo fala sobre como o nome de Deus é uma fonte de proteção e segurança para aqueles que confiam nele.
****

[[v21-125-1]]

^<<v21-125-1,1>>^ Cântico das peregrinações. Quando o Senhor reconduzia os cativos de Sião, estávamos como sonhando.^&#42;1^

[[v21-125-2]]

^<<v21-125-2,2>>^ Em nossa boca só havia expressões de alegria, e em nossos lábios canto de triunfo. Entre os pagãos se dizia: “O Senhor fez por eles grandes coisas”.

[[v21-125-3]]

^<<v21-125-3,3>>^ Sim, o Senhor fez por nós grandes coisas; ficamos exultantes de alegria!

[[v21-125-4]]

^<<v21-125-4,4>>^ Mudai, Senhor, a nossa sorte, como as torrentes nos desertos do sul.

[[v21-125-5]]

^<<v21-125-5,5>>^ Os que semeiam entre lágrimas, recolherão com alegria.

[[v21-125-6]]

^<<v21-125-6,6>>^ Na ida, caminham chorando os que levam a semente a aspergir. Na volta, virão com alegria, quando trouxerem os seus feixes.

'''

xref:021-salmos/021-salmos-124.adoc#v21-124-0[&#60; Capítulo Anterior] | <<v21-125-0,Topo>> | xref:021-salmos/021-salmos-126.adoc#v21-126-0[Próximo Capítulo &#62;]