include::./index.adoc[]

[[v21-101-0]]
=== Salmos, 101
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 101 é uma oração de um líder justo que busca viver de acordo com a vontade de Deus e governar com integridade. Ele se compromete a ser vigilante em sua conduta e a não permitir a presença do mal em sua vida. Alguns temas presentes nesse Salmo incluem justiça, integridade, fidelidade, pureza e liderança. Seguem abaixo cinco versículos relacionados com esses temas:
* Provérbios 20:28: "A bondade e a fidelidade preservam o rei; pela bondade ele mantém o seu trono." Este versículo destaca a importância da bondade e da fidelidade na liderança, o que está em consonância com o compromisso do salmista em ser um líder justo.
* Salmos 18:25: "Ao fiel te mostras fiel, ao íntegro, íntegro." A integridade é um valor muito importante para o salmista, que se esforça para governar com honestidade e justiça. Esse versículo afirma a promessa de Deus de recompensar a integridade daqueles que o seguem.
* Provérbios 4:23: "Sobre tudo o que se deve guardar, guarda o coração, porque dele procedem as fontes da vida." O salmista reconhece a importância de manter o coração puro e livre de pensamentos e atitudes más. Ele se compromete a vigiar sua conduta e a não permitir que o mal entre em sua vida.
* Salmos 26:1: "Faze-me justiça, Senhor, pois tenho andado na minha integridade; e confio no Senhor sem vacilar." O salmista confia em Deus para fazer justiça e reconhece sua própria integridade. Ele busca viver de acordo com a vontade de Deus e confia que será recompensado por isso.
* Tiago 1:27: "A religião pura e sem mácula, para com o nosso Deus e Pai, é esta: visitar os órfãos e as viúvas nas suas tribulações e guardar-se isento da corrupção do mundo." Esse versículo destaca a importância da pureza e da compaixão, valores que estão presentes no Salmo 101. O salmista se compromete a ser um líder justo e a não permitir que a corrupção do mundo o contamine.
****

[[v21-101-1]]

^<<v21-101-1,1>>^ Prece de um aflito que desabafa sua angústia diante do Senhor.^&#42;1^

[[v21-101-2]]

^<<v21-101-2,2>>^ Senhor, ouvi a minha oração, e chegue até vós o meu clamor.

[[v21-101-3]]

^<<v21-101-3,3>>^ Não oculteis de mim a vossa face no dia de minha angústia. Inclinai para mim o vosso ouvido. Quando vos invocar, acudi-me prontamente,

[[v21-101-4]]

^<<v21-101-4,4>>^ porque meus dias se dissipam como a fumaça, e como um tição consomem-se os meus ossos.

[[v21-101-5]]

^<<v21-101-5,5>>^ Queimando como erva, meu coração murcha, até me esqueço de comer meu pão.

[[v21-101-6]]

^<<v21-101-6,6>>^ A violência de meus gemidos faz com que se me peguem à pele os ossos.

[[v21-101-7]]

^<<v21-101-7,7>>^ Assemelho-me ao pelicano do deserto, sou como a coruja nas ruínas.

[[v21-101-8]]

^<<v21-101-8,8>>^ Perdi o sono e gemo, como pássaro solitário no telhado.

[[v21-101-9]]

^<<v21-101-9,9>>^ Insultam-me continuamente os inimigos, em seu furor me atiram imprecações.

[[v21-101-10]]

^<<v21-101-10,10>>^ Como cinza do mesmo modo que pão, lágrimas se misturam à minha bebida,

[[v21-101-11]]

^<<v21-101-11,11>>^ devido à vossa cólera indignada, pois me tomastes para me lançar ao longe.

[[v21-101-12]]

^<<v21-101-12,12>>^ Os meus dias se esvaecem como a sombra da noite e me vou murchando como a relva.

[[v21-101-13]]

^<<v21-101-13,13>>^ Vós, porém, Senhor, sois eterno, e vosso nome subsiste em todas as gerações.

[[v21-101-14]]

^<<v21-101-14,14>>^ Levantai-vos, pois, e sede propício a Sião; é tempo de compadecer-vos dela, chegou a hora...

[[v21-101-15]]

^<<v21-101-15,15>>^ porque vossos servos têm amor aos seus escombros e se condoem de suas ruínas.

[[v21-101-16]]

^<<v21-101-16,16>>^ E as nações pagãs reverenciarão o vosso nome, Senhor, e os reis da terra prestarão homenagens à vossa glória.

[[v21-101-17]]

^<<v21-101-17,17>>^ Quando o Senhor tiver reconstruído Sião, e aparecido em sua glória,

[[v21-101-18]]

^<<v21-101-18,18>>^ quando ele aceitar a oração dos desvalidos e não mais rejeitar as suas súplicas,

[[v21-101-19]]

^<<v21-101-19,19>>^ escrevam-se estes fatos para a geração futura, e louve o Senhor o povo que há de vir,

[[v21-101-20]]

^<<v21-101-20,20>>^ porque o Senhor olhou do alto de seu santuário, do céu ele contemplou a terra;

[[v21-101-21]]

^<<v21-101-21,21>>^ para escutar os gemidos dos cativos, para livrar da morte os condenados;

[[v21-101-22]]

^<<v21-101-22,22>>^ para que seja aclamado em Sião o nome do Senhor, e em Jerusalém o seu louvor,

[[v21-101-23]]

^<<v21-101-23,23>>^ no dia em que se hão de reunir os povos, e os reinos para servir o Senhor.

[[v21-101-24]]

^<<v21-101-24,24>>^ Deus esgotou-me as forças no meio do caminho, abreviou-me os dias.

[[v21-101-25]]

^<<v21-101-25,25>>^ “Meu Deus, peço, não me leveis no meio da minha vida, vós cujos anos são eternos.

[[v21-101-26]]

^<<v21-101-26,26>>^ No começo criastes a terra, e o céu é obra de vossas mãos.

[[v21-101-27]]

^<<v21-101-27,27>>^ Um e outro passarão, enquanto vós ficareis. Tudo se acaba pelo uso como um traje. Como uma veste, vós os substituís e eles hão de sumir.

[[v21-101-28]]

^<<v21-101-28,28>>^ Mas vós permaneceis o mesmo e vossos anos não têm fim.^&#42;1^

[[v21-101-29]]

^<<v21-101-29,29>>^ Os filhos de vossos servos habitarão seguros, e sua posteridade se perpetuará diante de vós.”

'''

xref:021-salmos/021-salmos-100.adoc#v21-100-0[&#60; Capítulo Anterior] | <<v21-101-0,Topo>> | xref:021-salmos/021-salmos-102.adoc#v21-102-0[Próximo Capítulo &#62;]