include::./index.adoc[]

[[v21-127-0]]
=== Salmos, 127
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 127 é um salmo de sabedoria que trata da importância de confiar em Deus para construir uma família e uma vida bem-sucedida. O salmista afirma que é em vão construir sem o auxílio de Deus, e que os filhos são um presente de Deus. Abaixo estão cinco versículos da Bíblia relacionados com os temas abordados no Salmo 127:
* Provérbios 3:5-6: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." Este verso incentiva a confiar em Deus em todas as coisas, incluindo a construção de uma família.
* Salmos 128:3: "A tua esposa será como a videira frutífera, no interior da tua casa; os teus filhos serão como plantas de oliveira, ao redor da tua mesa." Este verso fala sobre como a família é abençoada por Deus e como a esposa e os filhos são importantes para a construção da vida.
* Provérbios 22:6: "Instrui o menino no caminho em que deve andar, e, até quando envelhecer, não se desviará dele." Este verso enfatiza a importância da educação dos filhos e da sua formação de caráter.
* Salmos 121:1-2: "Elevo os meus olhos para os montes: de onde me virá o socorro? O meu socorro vem do Senhor, que fez o céu e a terra." Este verso encoraja a confiar em Deus em todos os momentos e a reconhecer a sua soberania em todas as coisas.
* Filipenses 4:6-7: "Não estejais inquietos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus, pela oração e súplicas, com ação de graças. E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus." Este verso incentiva a confiar em Deus em todas as situações e a buscar a sua paz por meio da oração.
****

[[v21-127-1]]

^<<v21-127-1,1>>^ Cântico das peregrinações. Felizes os que temem o Senhor, os que andam em seus caminhos^&#42;1^

[[v21-127-2]]

^<<v21-127-2,2>>^ Poderás viver, então, do trabalho de tuas mãos, serás feliz e terás bem-estar.

[[v21-127-3]]

^<<v21-127-3,3>>^ Tua mulher será em teu lar como uma vinha fecunda. Teus filhos em torno à tua mesa serão como brotos de oliveira.

[[v21-127-4]]

^<<v21-127-4,4>>^ Assim será abençoado aquele que teme o Senhor.

[[v21-127-5]]

^<<v21-127-5,5>>^ De Sião te abençoe o Senhor para que em todos os dias de tua vida gozes da prosperidade de Jerusalém,

[[v21-127-6]]

^<<v21-127-6,6>>^ e para que possas ver os filhos dos teus filhos. Reine a paz em Israel!

'''

xref:021-salmos/021-salmos-126.adoc#v21-126-0[&#60; Capítulo Anterior] | <<v21-127-0,Topo>> | xref:021-salmos/021-salmos-128.adoc#v21-128-0[Próximo Capítulo &#62;]