include::./index.adoc[]

[[v21-143-0]]
=== Salmos, 143
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 143 é um clamor de angústia e pedido de ajuda ao Senhor em meio a uma situação difícil. O salmista expressa sua confiança em Deus como sua única esperança e roga por sua orientação e livramento. Abaixo estão cinco versículos relacionados com os temas abordados neste Salmo:
* Salmos 18:2: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio. Ele é o meu escudo e o poder que me salva, a minha torre alta." Este versículo destaca a confiança do salmista em Deus como sua rocha e fortaleza, como alguém que lhe dá proteção e salvação.
* Salmos 142:5: "A ti, Senhor, clamo, dizendo: Tu és o meu refúgio; és tudo o que tenho na terra dos viventes." O salmista reconhece que Deus é seu refúgio e única esperança em meio à adversidade.
* Salmos 139:23-24: "Sonda-me, ó Deus, e conhece o meu coração; prova-me, e conhece as minhas inquietações. Vê se em minha conduta algo te ofende, e dirige-me pelo caminho eterno." Este versículo destaca o desejo do salmista por orientação divina e por ser purificado de quaisquer pensamentos ou atitudes que possam ofender a Deus.
* Salmos 34:18: "O Senhor está perto dos que têm o coração quebrantado e salva os de espírito abatido." Este versículo traz consolo para o salmista, lembrando que Deus está próximo dos que estão em sofrimento e se sentem desamparados.
* Salmos 25:4-5: "Mostra-me, Senhor, os teus caminhos, ensina-me as tuas veredas; guia-me com a tua verdade e ensina-me, pois tu és Deus, meu Salvador, e a minha esperança está em ti o tempo todo." O salmista pede a orientação de Deus em sua vida, reconhecendo que somente Ele é capaz de guiá-lo no caminho da verdade e ser sua esperança constante.
****

[[v21-143-1]]

^<<v21-143-1,1>>^ De Davi. Bendito seja o Senhor, meu rochedo, que adestra minhas mãos para o combate, meus dedos para a guerra;^&#42;1^

[[v21-143-2]]

^<<v21-143-2,2>>^ meu benfeitor e meu refúgio, minha cidadela e meu libertador, meu escudo e meu asilo, que submete a mim os povos.

[[v21-143-3]]

^<<v21-143-3,3>>^ Que é o homem, Senhor, para cuidardes dele, que é o Filho do Homem para que vos ocupeis dele?

[[v21-143-4]]

^<<v21-143-4,4>>^ O homem é semelhante ao sopro da brisa, seus dias são como a sombra que passa.

[[v21-143-5]]

^<<v21-143-5,5>>^ Inclinai, Senhor, os vossos céus e descei, tocai as montanhas para que se abrasem,

[[v21-143-6]]

^<<v21-143-6,6>>^ fulminai o raio e dispersai-os, lançai vossas setas e afugentai-os.

[[v21-143-7]]

^<<v21-143-7,7>>^ Estendei do alto a vossa mão, tirai-me do caudal, das mãos do estrangeiro,

[[v21-143-8]]

^<<v21-143-8,8>>^ cuja boca só diz mentiras e cuja mão só faz juramentos falsos.

[[v21-143-9]]

^<<v21-143-9,9>>^ Ó Deus, vou cantar-vos um cântico novo, vos louvarei com a harpa de dez cordas.

[[v21-143-10]]

^<<v21-143-10,10>>^ Vós que aos reis dais a vitória, que livrastes Davi, vosso servo;

[[v21-143-11]]

^<<v21-143-11,11>>^ salvai-me da espada da malícia, e livrai-me das mãos de estrangeiros, cuja boca só diz mentiras e cuja mão só faz juramentos falsos.

[[v21-143-12]]

^<<v21-143-12,12>>^ Sejam nossos filhos como as plantas novas, que crescem na sua juventude; sejam nossas filhas como as colunas angulares esculpidas, como os pilares do templo.

[[v21-143-13]]

^<<v21-143-13,13>>^ Encham-se os nossos celeiros de frutos variados e abundantes, multipliquem-se aos milhares nossos rebanhos, por miríades cresçam eles em nossos campos; sejam fecundas as nossas novilhas.

[[v21-143-14]]

^<<v21-143-14,14>>^ Não haja brechas em nossos muros, nem ruptura nem lamentações em nossas praças.

[[v21-143-15]]

^<<v21-143-15,15>>^ Feliz o povo agraciado com tais bens; feliz o povo cujo Deus é o Senhor.

'''

xref:021-salmos/021-salmos-142.adoc#v21-142-0[&#60; Capítulo Anterior] | <<v21-143-0,Topo>> | xref:021-salmos/021-salmos-144.adoc#v21-144-0[Próximo Capítulo &#62;]