include::./index.adoc[]

[[v21-131-0]]
=== Salmos, 131
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 131 é um salmo de humildade e confiança em Deus. Nele, o salmista expressa sua confiança em Deus e sua submissão à Sua vontade. Abaixo estão cinco versículos relacionados aos temas abordados neste salmo:
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." Este versículo fala sobre a confiança em Deus e a submissão à Sua vontade, que são temas importantes no Salmo 131.
* Mateus 18:4: "Portanto, quem se tornar humilde como este menino, este é o maior no Reino dos céus." A humildade é outro tema importante no Salmo 131, e este versículo enfatiza a importância da humildade para a vida cristã.
* Filipenses 4:6: "Não se preocupem com nada, mas em todas as orações peçam a Deus o que vocês precisam e orem sempre com o coração agradecido." A confiança em Deus e a importância da oração são temas abordados no Salmo 131, e este versículo destaca a importância de orar com gratidão e confiança.
* Tiago 4:10: "Humilhem-se diante do Senhor, e ele os exaltará." Este versículo enfatiza a importância da humildade e submissão diante de Deus, o que é um tema central do Salmo 131.
* 1 Pedro 5:6: "Portanto, humilhem-se debaixo da poderosa mão de Deus, para que ele os exalte no tempo devido." Este versículo novamente enfatiza a importância da humildade e submissão diante de Deus, e destaca que Deus é aquele que exalta no tempo certo.
****

[[v21-131-1]]

^<<v21-131-1,1>>^ Cântico das peregrinações. Senhor, lembrai-vos de Davi e de sua grande piedade,^&#42;1^

[[v21-131-2]]

^<<v21-131-2,2>>^ como ele fez ao Senhor este juramento, e este voto ao Poderoso de Jacó:

[[v21-131-3]]

^<<v21-131-3,3>>^ “Não entrarei na tenda em que moro, não me deitarei no leito de meu repouso,

[[v21-131-4]]

^<<v21-131-4,4>>^ não darei sono aos meus olhos, nem repouso às minhas pálpebras,

[[v21-131-5]]

^<<v21-131-5,5>>^ até que encontre uma residência para o Senhor, uma morada ao Poderoso de Jacó”.

[[v21-131-6]]

^<<v21-131-6,6>>^ Ouvimos dizer que a arca estava em Éfrata, nós a encontramos nas campinas de Jaar.^&#42;1^

[[v21-131-7]]

^<<v21-131-7,7>>^ Entremos em sua morada, prostremo-nos diante do escabelo de seus pés.

[[v21-131-8]]

^<<v21-131-8,8>>^ Levantai-vos, Senhor, para vir ao vosso repouso, vós e a arca de vossa majestade.

[[v21-131-9]]

^<<v21-131-9,9>>^ Vistam-se de justiça os vossos sacerdotes, e jubilosos cantem de alegria vossos fiéis.

[[v21-131-10]]

^<<v21-131-10,10>>^ Pelo nome de Davi, vosso servo, não rejeiteis a face daquele que vos é consagrado.

[[v21-131-11]]

^<<v21-131-11,11>>^ O Senhor fez a Davi um juramento, de que não há de se retratar: “Colocarei em teu trono um descendente de tua raça.

[[v21-131-12]]

^<<v21-131-12,12>>^ Se teus filhos guardarem minha aliança e os preceitos que eu lhes hei de ensinar, também os descendentes deles, para sempre, se sentarão em teu trono”.

[[v21-131-13]]

^<<v21-131-13,13>>^ Porque o Senhor escolheu Sião, ele a preferiu para sua morada.

[[v21-131-14]]

^<<v21-131-14,14>>^ “É aqui para sempre o lugar de meu repouso, é aqui que habitarei porque o escolhi.

[[v21-131-15]]

^<<v21-131-15,15>>^ Abençoarei copiosamente sua subsistência, fartarei de pão os seus pobres.

[[v21-131-16]]

^<<v21-131-16,16>>^ Revestirei de salvação seus sacerdotes, e seus fiéis exultarão de alegria.^&#42;1^

[[v21-131-17]]

^<<v21-131-17,17>>^ Aí farei crescer o poder de Davi, aí prepararei uma lâmpada para o que me é consagrado.

[[v21-131-18]]

^<<v21-131-18,18>>^ Cobrirei de confusão seus inimigos; em sua fronte, porém, brilhará meu diadema.”

'''

xref:021-salmos/021-salmos-130.adoc#v21-130-0[&#60; Capítulo Anterior] | <<v21-131-0,Topo>> | xref:021-salmos/021-salmos-132.adoc#v21-132-0[Próximo Capítulo &#62;]