include::./index.adoc[]

[[v21-58-0]]
=== Salmos, 58
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Salmo 58 é uma oração ao Senhor pedindo justiça e punição para os injustos e ímpios. O salmista expressa sua indignação diante das más ações dos ímpios e clama a Deus para que intervenha e traga justiça. Abaixo estão cinco versículos relacionados com os temas abordados neste salmo:
* Provérbios 11:18: "O ímpio recebe um salário enganador, mas quem semeia justiça colhe verdadeira recompensa." Este versículo fala sobre a diferença entre a recompensa do ímpio e do justo. O salmista de Salmo 58 pede por justiça, enquanto este provérbio afirma que a recompensa do ímpio é enganadora.
* Isaías 26:10: "Ainda que o ímpio seja favorecido, ele não aprenderá a justiça; mesmo em terra de retidão ele continuará agindo perversamente e não verá a majestade do Senhor." Este versículo destaca a tendência do ímpio de não aprender com suas más ações. O salmista de Salmo 58 clama por punição para os ímpios que não mudam seu comportamento.
* Jeremias 12:1: "Tu és justo, Senhor, mas ainda que eu apresente minha causa diante de ti, devo discutir contigo sobre a justiça. Por que o caminho dos ímpios prospera? Por que todos os traidores vivem em paz?" Este versículo expressa a dificuldade de entender por que os ímpios parecem prosperar e viver em paz, apesar de suas más ações. O salmista de Salmo 58 também questiona a aparente falta de justiça.
* Romanos 12:19: "Amados, nunca procurem vingança, mas deixem com Deus a ira, pois está escrito: 'Minha é a vingança; eu retribuirei', diz o Senhor." Este versículo fala sobre a importância de deixar a justiça nas mãos de Deus, em vez de buscar vingança por conta própria. O salmista de Salmo 58 clama por justiça divina em vez de tomar a justiça em suas próprias mãos.
* Apocalipse 22:11: "Quem é injusto, seja injusto ainda; quem é imundo, seja imundo ainda; quem é justo, seja justo ainda; e quem é santo, seja santo ainda." Este versículo fala sobre a importância de escolher um caminho justo e santo, em vez de seguir o caminho da injustiça e impureza. O salmista de Salmo 58 clama por justiça e punição para os ímpios que escolhem o caminho errado.
****

[[v21-58-1]]

^<<v21-58-1,1>>^ Para o mestre de canto. “Não destruas”. Cântico de Davi, quando Saul mandou cercar-lhe a casa para matá-lo.^&#42;1^

[[v21-58-2]]

^<<v21-58-2,2>>^ Livrai-me, ó meu Deus, dos meus inimigos, defendei-me dos meus adversários.

[[v21-58-3]]

^<<v21-58-3,3>>^ Livrai-me dos que praticam o mal, salvai-me dos homens sanguinários.

[[v21-58-4]]

^<<v21-58-4,4>>^ Vede: armam ciladas para me tirar a vida, homens poderosos conspiram contra mim.

[[v21-58-5]]

^<<v21-58-5,5>>^ Senhor, não há em mim crime nem pecado. Sem que eu tenha culpa, eles acorrem e atacam. Despertai-vos, vinde para mim e vede,

[[v21-58-6]]

^<<v21-58-6,6>>^ porque vós, Senhor dos exércitos, sois o Deus de Israel. Erguei-vos para castigar esses pagãos, não tenhais misericórdia desses pérfidos.

[[v21-58-7]]

^<<v21-58-7,7>>^ Eles voltam todas as noites, latindo como cães, e percorrem a cidade toda.

[[v21-58-8]]

^<<v21-58-8,8>>^ Eis que se jactam à boca cheia, tendo nos lábios só injúrias, e dizem: “Pois quem é que nos ouve?”.

[[v21-58-9]]

^<<v21-58-9,9>>^ Mas vós, Senhor, vós rides deles, zombais de todos os pagãos.

[[v21-58-10]]

^<<v21-58-10,10>>^ Ó vós que sois a minha força, é para vós que eu me volto. Porque vós, ó Deus, sois a minha defesa.

[[v21-58-11]]

^<<v21-58-11,11>>^ Ó meu Deus, vós sois todo bondade para mim. Venha Deus em meu auxílio, faça-me deleitar pela perda de meus inimigos.

[[v21-58-12]]

^<<v21-58-12,12>>^ Destruí-os, ó meu Deus, para que não percam o meu povo; conturbai-os, abatei-os com vosso poder, ó Deus, nosso escudo.

[[v21-58-13]]

^<<v21-58-13,13>>^ Cada palavra de seus lábios é um pecado. Que eles, surpreendidos em sua arrogância, sejam as vítimas de suas próprias calúnias e maldições.

[[v21-58-14]]

^<<v21-58-14,14>>^ Destruí-os em vossa cólera, destruí-os para que não subsistam, para que se saiba que Deus reina em Jacó e até os confins da terra.

[[v21-58-15]]

^<<v21-58-15,15>>^ Todas as noites eles voltam, latindo como cães, rondando pela cidade toda.

[[v21-58-16]]

^<<v21-58-16,16>>^ Vagueiam em busca de alimento; não se fartando, eles se põem a uivar.

[[v21-58-17]]

^<<v21-58-17,17>>^ Eu, porém, cantarei vosso poder, e desde o amanhecer celebrarei vossa bondade, porque vós sois o meu amparo, um refúgio no dia da tribulação.

[[v21-58-18]]

^<<v21-58-18,18>>^ Ó vós, que sois a minha força, a vós, meu Deus, cantarei salmos porque sois minha defesa. Ó meu Deus, vós sois todo bondade para mim.

'''

xref:021-salmos/021-salmos-057.adoc#v21-57-0[&#60; Capítulo Anterior] | <<v21-58-0,Topo>> | xref:021-salmos/021-salmos-059.adoc#v21-59-0[Próximo Capítulo &#62;]