include::./index.adoc[]

[[v21-45-0]]
=== Salmos, 45
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 45 é um poema em honra a um rei, provavelmente Salomão, mas com possíveis referências ao Messias. O capítulo exalta a beleza, a justiça, a sabedoria e o poder do rei, e o compara a Deus. O capítulo termina com uma exortação para que os povos e reis da terra prestem homenagem ao rei de Israel.
* Isaías 9:6: "Porque um menino nos nasceu, um filho nos foi dado, e o governo está sobre os seus ombros. E ele será chamado Maravilhoso Conselheiro, Deus Forte, Pai Eterno, Príncipe da Paz." Este versículo profetiza sobre o nascimento do Messias, que seria um líder sábio e poderoso.
* Provérbios 31:30: "A beleza é enganosa, e a formosura é passageira; mas a mulher que teme ao Senhor será elogiada." Este versículo destaca a importância de qualidades interiores como o temor a Deus, que são mais valiosas do que a beleza exterior.
* Hebreus 1:8-9: "Mas acerca do Filho ele diz: 'O teu trono, ó Deus, subsiste para todo o sempre; cetro de justiça é o cetro do teu Reino. Amaste a justiça e odiaste a iniqüidade; por isso Deus, o teu Deus, te escolheu dentre os teus companheiros ungindo-te com óleo de alegria'." Este versículo faz referência ao Salmo 45 e declara que o Messias é o próprio Deus.
* 1 Crônicas 29:11: "Teus, Senhor, são a grandeza, o poder, a glória, a majestade e o esplendor, pois tudo o que há nos céus e na terra é teu. Teu, Senhor, é o Reino; tu estás acima de tudo." Este versículo enfatiza que Deus é o Rei supremo e que todo poder e autoridade vem dele.
* Mateus 2:2: "E perguntaram: 'Onde está o recém-nascido Rei dos judeus? Vimos a sua estrela no oriente e viemos adorá-lo'." Este versículo se refere à visita dos magos a Jesus, que foram até ele para adorá-lo como um rei.
****

[[v21-45-1]]

^<<v21-45-1,1>>^ Ao mestre de canto. Dos filhos de Coré. Cântico para voz de soprano.^&#42;1^

[[v21-45-2]]

^<<v21-45-2,2>>^ Deus é nosso refúgio e nossa força; mostrou-se nosso amparo nas tribulações.

[[v21-45-3]]

^<<v21-45-3,3>>^ Por isso, a terra pode tremer, nada tememos: as próprias montanhas podem se afundar nos mares.

[[v21-45-4]]

^<<v21-45-4,4>>^ Ainda que as águas tumultuem e com sua fúria venham abalar os montes, está conosco o Senhor dos exércitos, nosso protetor é o Deus de Jacó.

[[v21-45-5]]

^<<v21-45-5,5>>^ Os braços de um rio alegram a cidade de Deus, o santuário do Altíssimo.^&#42;1^

[[v21-45-6]]

^<<v21-45-6,6>>^ Deus está no seu centro, ela é inabalável; desde o amanhecer, já Deus lhe vem em socorro.

[[v21-45-7]]

^<<v21-45-7,7>>^ Agitaram-se as nações, vacilaram os reinos; apenas ressoou sua voz, tremeu a terra.

[[v21-45-8]]

^<<v21-45-8,8>>^ Está conosco o Senhor dos exércitos, nosso protetor é o Deus de Jacó.

[[v21-45-9]]

^<<v21-45-9,9>>^ Vinde admirar as obras do Senhor, os prodígios que ele fez sobre a terra.

[[v21-45-10]]

^<<v21-45-10,10>>^ Reprimiu as guerras em toda a extensão da terra; partiu os arcos, quebrou as lanças, queimou os escudos.

[[v21-45-11]]

^<<v21-45-11,11>>^ “Parai – disse ele – e reconhecei que sou Deus; que domino sobre as nações e sobre toda a terra.”

[[v21-45-12]]

^<<v21-45-12,12>>^ Está conosco o Senhor dos exércitos, nosso protetor é o Deus de Jacó.

'''

xref:021-salmos/021-salmos-044.adoc#v21-44-0[&#60; Capítulo Anterior] | <<v21-45-0,Topo>> | xref:021-salmos/021-salmos-046.adoc#v21-46-0[Próximo Capítulo &#62;]