include::./index.adoc[]

[[v21-148-0]]
=== Salmos, 148
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 148 é um hino de louvor à grandeza e soberania de Deus, que é exaltado tanto nos céus quanto na terra. O salmista convoca todas as criaturas a adorarem a Deus, desde os anjos no céu até os peixes do mar. Abaixo estão cinco versículos relacionados com os temas abordados neste Salmo:
* Salmos 8:3-4: "Quando contemplo os teus céus, obra dos teus dedos, e a lua e as estrelas que estabeleceste, que é o homem mortal para que te lembres dele? E o filho do homem, para que o visites?" Este versículo fala sobre a admiração que o salmista tem pela criação de Deus, especialmente ao olhar para os céus.
* Isaías 42:10: "Cantai ao Senhor um cântico novo, e o seu louvor desde o fim da terra; vós, os que navegais pelo mar, e tudo quanto há nele; vós, ilhas, e seus habitantes." Neste versículo, Isaías exorta todas as criaturas a louvar a Deus, inclusive os marinheiros e aqueles que vivem em ilhas.
* Salmos 103:20-22: "Bendizei ao Senhor, vós, anjos seus, vós que excedeis em força, que guardais os seus mandamentos, obedecendo à voz da sua palavra. Bendizei ao Senhor, vós, todos os seus exércitos, vós, ministros seus, que executais o seu beneplácito. Bendizei ao Senhor, vós, todas as suas obras, em todos os lugares do seu domínio; bendizei ao Senhor, ó minha alma!" Este versículo mostra que todas as criaturas, incluindo os anjos, são chamadas a louvar a Deus.
* Salmos 33:8: "Tema ao Senhor toda a terra; temam-no todos os habitantes do mundo." Este versículo exorta todas as pessoas da terra a temerem a Deus.
* Apocalipse 5:13: "E ouvi a toda criatura que está no céu, e na terra, e debaixo da terra, e que estão no mar, e a todas as coisas que neles há, dizerem: Ao que está assentado sobre o trono e ao Cordeiro seja o louvor, e a honra, e a glória, e o domínio pelos séculos dos séculos." Este versículo descreve uma visão do céu, onde todas as criaturas estão louvando a Deus e ao Cordeiro.
****

[[v21-148-1]]

^<<v21-148-1,1>>^ Aleluia. Nos céus, louvai o Senhor, louvai-o nas alturas do firmamento.^&#42;1^

[[v21-148-2]]

^<<v21-148-2,2>>^ Louvai-o, todos os seus anjos. Louvai-o, todos os seus exércitos.

[[v21-148-3]]

^<<v21-148-3,3>>^ Louvai-o, sol e lua; louvai-o, astros brilhantes.

[[v21-148-4]]

^<<v21-148-4,4>>^ Louvai-o, céus do céu, e vós, ó oceanos dos espaços celestes.

[[v21-148-5]]

^<<v21-148-5,5>>^ Louvem o nome do Senhor, porque ele mandou e tudo foi criado.

[[v21-148-6]]

^<<v21-148-6,6>>^ Tudo estabeleceu pela eternidade dos séculos; fixou-lhes uma Lei que não será violada.

[[v21-148-7]]

^<<v21-148-7,7>>^ Na terra, louvai o Senhor: cetáceos e todos das profundezas do mar;

[[v21-148-8]]

^<<v21-148-8,8>>^ fogo e granizo, neve e neblina; vendaval proceloso dócil às suas ordens;

[[v21-148-9]]

^<<v21-148-9,9>>^ montanhas e colinas, árvores frutíferas, árvores silvestres;

[[v21-148-10]]

^<<v21-148-10,10>>^ feras e rebanhos, répteis e aves;

[[v21-148-11]]

^<<v21-148-11,11>>^ reis da terra e todos os seus povos; príncipes e juízes do mundo;

[[v21-148-12]]

^<<v21-148-12,12>>^ jovens e donzelas; velhos e crianças!

[[v21-148-13]]

^<<v21-148-13,13>>^ Louvem todos o nome do Senhor, porque só o seu nome é excelso. Sua majestade transcende a terra e o céu,

[[v21-148-14]]

^<<v21-148-14,14>>^ e conferiu a seu povo um grande poder. Louvem-no todos os seus fiéis, filhos de Israel, povo a ele mais chegado.

'''

xref:021-salmos/021-salmos-147.adoc#v21-147-0[&#60; Capítulo Anterior] | <<v21-148-0,Topo>> | xref:021-salmos/021-salmos-149.adoc#v21-149-0[Próximo Capítulo &#62;]