include::./index.adoc[]

[[v21-98-0]]
=== Salmos, 98
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 98 é um hino de louvor que celebra a grandeza de Deus e a sua fidelidade para com o seu povo. Ele destaca o poder de Deus para trazer salvação e justiça para a Terra e incentiva todas as pessoas a adorá-lo com alegria e gratidão. Aqui estão cinco versículos relacionados aos temas do Salmo 98:
* Salmos 96:1-2: "Cantem ao Senhor um novo cântico; cantem ao Senhor, todos os habitantes da terra! Cantem ao Senhor, bendigam o seu nome; cada dia proclamem a sua salvação". Este versículo é semelhante ao início do Salmo 98, pois incentiva todas as pessoas a cantar um novo cântico ao Senhor e louvá-lo pelo seu poder e graça.
* Salmos 96:11-12: "Alegre-se o céu, regozije-se a terra; ressoe o mar e tudo o que nele existe. Exulte o campo e tudo o que nele há; cantem de alegria todas as árvores da floresta". Este versículo se relaciona com o Salmo 98 ao destacar a alegria e a celebração que devem acompanhar a adoração a Deus. Toda a criação é convidada a se regozijar e louvar ao Senhor.
* Isaías 52:10: "O Senhor descobriu o seu santo braço diante dos olhos de todas as nações, e todos os confins da terra verão a salvação do nosso Deus". Este versículo se relaciona com o Salmo 98 ao destacar o poder de Deus para trazer salvação a todas as nações da Terra. Assim como no Salmo 98, Isaías enfatiza que Deus é digno de louvor e adoração por causa de sua salvação.
* Salmos 97:10-11: "Vós que amais ao Senhor, odiai o mal; ele guarda a vida dos seus santos, ele os livra das mãos dos ímpios. A luz se semeia para o justo, e alegria para os retos de coração". Este versículo se relaciona com o Salmo 98 ao destacar o amor de Deus por aqueles que o seguem e sua fidelidade em protegê-los do mal. Assim como no Salmo 98, este versículo incentiva os fiéis a se regozijarem no Senhor e na sua justiça.
* Salmos 100:1-2: "Aclamem com júbilo ao Senhor, todos os habitantes da terra! Prestem culto ao Senhor com alegria, apresentem-se diante dele com cânticos de júbilo!" Este versículo se relaciona com o Salmo 98 ao incentivar todas as pessoas a adorarem a Deus com alegria e júbilo. Ele destaca a importância de se aproximar do Senhor com um coração agradecido e cheio de louvor.
****

[[v21-98-1]]

^<<v21-98-1,1>>^ O Senhor reina, tremem os povos; seu trono está sobre os querubins: vacila a terra.

[[v21-98-2]]

^<<v21-98-2,2>>^ Grande é o Senhor em Sião, elevado acima de todos os povos.

[[v21-98-3]]

^<<v21-98-3,3>>^ Seja celebrado vosso grande e temível nome, porque ele é Santo.

[[v21-98-4]]

^<<v21-98-4,4>>^ Reina o rei poderoso que ama a justiça; sois vós que estabeleceis o que é reto, sois vós que exerceis em Jacó o direito e a justiça.

[[v21-98-5]]

^<<v21-98-5,5>>^ Exaltai ao Senhor, nosso Deus, e prostrai-vos ante o escabelo de seus pés, porque ele é Santo.^&#42;1^

[[v21-98-6]]

^<<v21-98-6,6>>^ Entre seus sacerdotes estavam Moisés e Aarão, e Samuel um dos que invocaram o seu nome: clamavam ao Senhor, que os atendia.

[[v21-98-7]]

^<<v21-98-7,7>>^ Falava-lhes na coluna de nuvem, eles guardavam os seus preceitos e a Lei que lhes havia dado.

[[v21-98-8]]

^<<v21-98-8,8>>^ Senhor, nosso Deus, vós os ouvistes, fostes para eles um Deus propício, ainda quando puníeis as suas injustiças.

[[v21-98-9]]

^<<v21-98-9,9>>^ Exaltai o Senhor, nosso Deus, e prostrai-vos ante sua montanha santa, porque santo é o Senhor, nosso Deus.

'''

xref:021-salmos/021-salmos-097.adoc#v21-97-0[&#60; Capítulo Anterior] | <<v21-98-0,Topo>> | xref:021-salmos/021-salmos-099.adoc#v21-99-0[Próximo Capítulo &#62;]