include::./index.adoc[]

[[v21-144-0]]
=== Salmos, 144
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 144 é um cântico de louvor e oração ao Senhor por sua fidelidade e bondade. Nele, o salmista reconhece a grandeza de Deus e sua ajuda constante nos momentos difíceis. Abaixo estão cinco versículos relacionados aos temas abordados no Salmo 144:
* Salmos 145:3: "Grande é o Senhor e digno de ser louvado; sua grandeza não tem limites." O Salmo 145 é outro cântico de louvor a Deus, reconhecendo sua grandeza e bondade. Esse versículo destaca a mesma ideia presente no Salmo 144, de que Deus é digno de louvor e adoração.
* Salmos 18:2: "O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio. Ele é o meu escudo e o poder que me salva, a minha torre alta." Esse versículo destaca a confiança que o salmista tem em Deus como seu protetor e libertador, um tema presente no Salmo 144.
* Salmos 146:5: "Feliz aquele que tem o Deus de Jacó por seu auxílio, cuja esperança está no Senhor, no seu Deus," Esse versículo enfatiza a importância de confiar em Deus e depositar nossa esperança nele, um tema presente no Salmo 144.
* Salmos 32:8: "Eu te instruirei e te ensinarei o caminho que deves seguir; eu te aconselharei e cuidarei de ti." Esse versículo destaca a ideia de que Deus nos guia e nos ajuda a tomar as decisões certas, um tema presente no Salmo 144.
* Salmos 119:105: "Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho." Esse versículo destaca a importância da palavra de Deus como guia para nossas vidas, um tema presente no Salmo 144, que fala sobre a lei de Deus e sua sabedoria.
****

[[v21-144-1]]

^<<v21-144-1,1>>^ Louvor. De Davi. Ó meu Deus, meu rei, eu vos glorificarei, e bendirei o vosso nome pelos séculos dos séculos.^&#42;1^

[[v21-144-2]]

^<<v21-144-2,2>>^ Dia a dia vos bendirei, e louvarei o vosso nome eternamente.

[[v21-144-3]]

^<<v21-144-3,3>>^ Grande é o Senhor e sumamente louvável, insondável é a sua grandeza.

[[v21-144-4]]

^<<v21-144-4,4>>^ Cada geração apregoa à outra as vossas obras, e proclama o vosso poder.

[[v21-144-5]]

^<<v21-144-5,5>>^ Elas falam do brilho esplendoroso de vossa majestade, e publicam as vossas maravilhas.

[[v21-144-6]]

^<<v21-144-6,6>>^ Anunciam o formidável poder de vossas obras e narram a vossa grandeza.

[[v21-144-7]]

^<<v21-144-7,7>>^ Proclamam o louvor de vossa bondade imensa, e aclamam a vossa justiça.

[[v21-144-8]]

^<<v21-144-8,8>>^ O Senhor é clemente e compassivo, generoso e cheio de bondade.

[[v21-144-9]]

^<<v21-144-9,9>>^ O Senhor é bom para com todos, e sua misericórdia se estende a todas as suas obras.

[[v21-144-10]]

^<<v21-144-10,10>>^ Glorifiquem-vos, Senhor, todas as vossas obras, e vos bendigam os vossos fiéis.

[[v21-144-11]]

^<<v21-144-11,11>>^ Que eles apregoem a glória de vosso reino, e anunciem o vosso poder,

[[v21-144-12]]

^<<v21-144-12,12>>^ para darem a conhecer aos homens a vossa força, e a glória de vosso reino maravilhoso.

[[v21-144-13]]

^<<v21-144-13,13>>^ Vosso reino é um reino eterno, e vosso império subsiste em todas as gerações. O Senhor é fiel em suas palavras, e santo em tudo o que faz.

[[v21-144-14]]

^<<v21-144-14,14>>^ O Senhor sustém os que vacilam, e soergue os abatidos.

[[v21-144-15]]

^<<v21-144-15,15>>^ Todos os olhos esperançosos se dirigem para vós, e a seu tempo vós os alimentais.

[[v21-144-16]]

^<<v21-144-16,16>>^ Basta abrirdes as mãos, para saciardes com benevolência todos os viventes.

[[v21-144-17]]

^<<v21-144-17,17>>^ O Senhor é justo em seus caminhos, e santo em tudo o que faz.

[[v21-144-18]]

^<<v21-144-18,18>>^ O Senhor se aproxima dos que o invocam, daqueles que o invocam com sinceridade.

[[v21-144-19]]

^<<v21-144-19,19>>^ Ele satisfará o desejo dos que o temem, ouvirá seus clamores e os salvará.

[[v21-144-20]]

^<<v21-144-20,20>>^ O Senhor vela por aqueles que o amam, mas exterminará todos os maus.

[[v21-144-21]]

^<<v21-144-21,21>>^ Que minha boca proclame o louvor do Senhor, e que todo ser vivo bendiga eternamente o seu santo nome.

'''

xref:021-salmos/021-salmos-143.adoc#v21-143-0[&#60; Capítulo Anterior] | <<v21-144-0,Topo>> | xref:021-salmos/021-salmos-145.adoc#v21-145-0[Próximo Capítulo &#62;]