include::./index.adoc[]

[[v21-61-0]]
=== Salmos, 61
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 61 é um salmo de Davi em que ele clama a Deus por ajuda e proteção. Davi se sente abatido e distante de Deus, mas confia em sua misericórdia e poder para ajudá-lo a superar seus problemas e fortalecê-lo. Ele pede para que Deus o conduza à rocha mais alta e para que o proteja sob as suas asas. Vasculhando toda a Bíblia, foram encontrados cinco versículos relacionados com os temas abordados em Salmo 61, apresentados a seguir em ordem de proximidade com os temas do capítulo:
* Salmos 27:5: "Pois no dia da adversidade ele me esconderá no seu pavilhão; no recôndito do seu tabernáculo me esconderá; sobre uma rocha me elevará." Este versículo mostra que Davi confia em Deus para protegê-lo e escondê-lo durante suas adversidades.
* Salmos 91:4: "Com suas penas te cobrirá, e debaixo das suas asas te refugiarás; sua verdade será o teu escudo e broquel." Este verso apresenta a imagem de Deus protegendo e cobrindo com suas asas aqueles que nele confiam, como Davi.
* Salmos 62:7: "Em Deus está a minha salvação e a minha glória; a rocha da minha fortaleza, e o meu refúgio estão em Deus." Davi confia em Deus para ser sua rocha, sua fortaleza e refúgio.
* Salmos 31:3: "Porque tu és a minha rocha e a minha fortaleza; assim, por amor do teu nome, guia-me e encaminha-me." Este versículo mostra que Davi confia em Deus como sua rocha e fortaleza, e pede a sua orientação.
* Salmos 46:1: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia." Este verso apresenta Deus como um refúgio e fortaleza para aqueles que precisam de ajuda em tempos de angústia, o que é exatamente o que Davi busca em Salmo 61.
****

[[v21-61-1]]

^<<v21-61-1,1>>^ Ao mestre de canto. Segundo Iditun. Salmo de Davi.^&#42;1^

[[v21-61-2]]

^<<v21-61-2,2>>^ Só em Deus repousa minha alma, só dele me vem a salvação.

[[v21-61-3]]

^<<v21-61-3,3>>^ Só ele é meu rochedo, minha salvação; minha fortaleza: jamais vacilarei.

[[v21-61-4]]

^<<v21-61-4,4>>^ Até quando, juntos, atacareis o próximo para derribá-lo como a uma parede já inclinada, como a um muro que se fendeu?

[[v21-61-5]]

^<<v21-61-5,5>>^ Sim, de meu excelso lugar pretendem derrubar-me; eles se comprazem na mentira. Enquanto me bendizem com os lábios, amaldiçoam-me no coração.

[[v21-61-6]]

^<<v21-61-6,6>>^ Só em Deus repousa a minha alma, é dele que me vem o que eu espero.

[[v21-61-7]]

^<<v21-61-7,7>>^ Só ele é meu rochedo e minha salvação; minha fortaleza: jamais vacilarei.

[[v21-61-8]]

^<<v21-61-8,8>>^ Só em Deus encontrarei glória e salvação. Ele é meu rochedo protetor, meu refúgio está nele.

[[v21-61-9]]

^<<v21-61-9,9>>^ Ó povo, confia nele de uma vez por todas; expandi, em sua presença, os vossos corações. Nosso refúgio está em Deus.

[[v21-61-10]]

^<<v21-61-10,10>>^ Os homens não passam de um sopro, e de uma mentira os filhos dos homens. Eles sobem na concha da balança, pois todos juntos são mais leves que o vento.

[[v21-61-11]]

^<<v21-61-11,11>>^ Não confieis na violência, nem espereis vãmente no roubo; crescendo vossas riquezas, não prendais nelas os vossos corações.

[[v21-61-12]]

^<<v21-61-12,12>>^ Numa só palavra de Deus compreendi duas coisas: a Deus pertence o poder,

[[v21-61-13]]

^<<v21-61-13,13>>^ ao Senhor pertence a bondade. Pois vós dais a cada um segundo suas obras.

'''

xref:021-salmos/021-salmos-060.adoc#v21-60-0[&#60; Capítulo Anterior] | <<v21-61-0,Topo>> | xref:021-salmos/021-salmos-062.adoc#v21-62-0[Próximo Capítulo &#62;]