include::./index.adoc[]

[[v21-93-0]]
=== Salmos, 93
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 93 é um hino que exalta a soberania e majestade do Senhor, que é descrito como aquele que reina acima de todas as coisas e mantém o mundo firmemente estabelecido. Os versículos selecionados abaixo destacam a grandeza de Deus e a sua autoridade sobre toda a criação.
* Salmos 24:1-2: "Do Senhor é a terra e tudo o que nela existe, o mundo e os que nele vivem; pois foi ele quem a fundou sobre os mares e a firmou sobre as águas." Esse versículo fala da autoridade e soberania de Deus sobre toda a criação, incluindo a terra e todos os seus habitantes.
* Salmos 47:7-8: "Pois Deus é o Rei de toda a terra; cantem louvores com harmonioso cântico. Deus reina sobre as nações; Deus está sentado em seu santo trono." Este versículo destaca a soberania de Deus sobre todas as nações da terra.
* Salmos 96:10: "Digam entre as nações: O Senhor reina! Dele são os céus, e a terra o seu domínio." Esse versículo enfatiza que o Senhor é o governante supremo de todo o universo, incluindo os céus e a terra.
* Isaías 6:1: "No ano em que o rei Uzias morreu, eu vi o Senhor assentado num trono alto e exaltado, e a aba de sua veste enchia o templo." Este versículo descreve uma visão de Isaías em que ele vê o Senhor sentado em um trono, o que é uma imagem semelhante à descrição do salmista no Salmo 93.
* Apocalipse 19:6: "Então ouvi o que parecia ser a voz de uma grande multidão, como o som de muitas águas e de fortes trovões, que clamava: Aleluia! Pois reina o Senhor, nosso Deus, o Todo-poderoso." Esse versículo retrata uma cena no céu em que uma multidão celebra a soberania de Deus e o fato de que Ele reina para sempre.
****

[[v21-93-1]]

^<<v21-93-1,1>>^ Senhor, Deus justiceiro, Deus das vinganças, aparecei em vosso esplendor.^&#42;1^

[[v21-93-2]]

^<<v21-93-2,2>>^ Levantai-vos, juiz da terra, castigai os soberbos como eles merecem.

[[v21-93-3]]

^<<v21-93-3,3>>^ Até quando, Senhor, triunfarão os ímpios?

[[v21-93-4]]

^<<v21-93-4,4>>^ Até quando se desmandarão em discursos arrogantes, e jactanciosos estarão esses obreiros do mal?

[[v21-93-5]]

^<<v21-93-5,5>>^ Eles esmagam vosso povo, Senhor, e oprimem vossa herança.

[[v21-93-6]]

^<<v21-93-6,6>>^ Trucidam a viúva e o estrangeiro, tiram a vida aos órfãos.

[[v21-93-7]]

^<<v21-93-7,7>>^ E dizem: “O Senhor não vê, o Deus de Jacó não presta atenção nisso!”.

[[v21-93-8]]

^<<v21-93-8,8>>^ Tratai de compreender, ó gente estulta. Insensatos, quando cobrareis juízo?

[[v21-93-9]]

^<<v21-93-9,9>>^ Pois não ouvirá quem fez o ouvido? O que formou o olho não verá?

[[v21-93-10]]

^<<v21-93-10,10>>^ Aquele que dá lições aos povos não há de punir, ele que ensina ao homem o saber...

[[v21-93-11]]

^<<v21-93-11,11>>^ O Senhor conhece os pensamentos dos homens, e sabe que são vãos.^&#42;1^

[[v21-93-12]]

^<<v21-93-12,12>>^ Feliz o homem a quem ensinais, Senhor, e instruís em vossa Lei,

[[v21-93-13]]

^<<v21-93-13,13>>^ para lhe dar a paz no dia do infortúnio, enquanto uma cova se abre para o ímpio,

[[v21-93-14]]

^<<v21-93-14,14>>^ porque o Senhor não rejeitará o seu povo, e não há de abandonar a sua herança.

[[v21-93-15]]

^<<v21-93-15,15>>^ Mas o julgamento com justiça se fará, e o seguirão os retos de coração.

[[v21-93-16]]

^<<v21-93-16,16>>^ Quem se erguerá por mim contra os malfeitores? Quem será meu defensor contra os artesãos do mal?

[[v21-93-17]]

^<<v21-93-17,17>>^ Se o Senhor não me socorresse, em breve a minha alma habitaria a região do silêncio.

[[v21-93-18]]

^<<v21-93-18,18>>^ Quando penso: “Vacilam-me os pés”, sustenta-me, Senhor, a vossa graça.

[[v21-93-19]]

^<<v21-93-19,19>>^ Quando em meu coração se multiplicam as angústias, vossas consolações alegram a minha alma.

[[v21-93-20]]

^<<v21-93-20,20>>^ Acaso poderá aliar-se a vós um tribunal iníquo, que pratica vexames sob a aparência de lei?^&#42;1^

[[v21-93-21]]

^<<v21-93-21,21>>^ Atentam contra a alma do justo, e condenam o sangue inocente.

[[v21-93-22]]

^<<v21-93-22,22>>^ Mas o Senhor certamente será o meu refúgio, e meu Deus o rochedo em que me abrigo.

[[v21-93-23]]

^<<v21-93-23,23>>^ Ele fará recair sobre eles suas próprias maldades, ele os fará perecer por sua própria malícia. O Senhor, nosso Deus, os destruirá.

'''

xref:021-salmos/021-salmos-092.adoc#v21-92-0[&#60; Capítulo Anterior] | <<v21-93-0,Topo>> | xref:021-salmos/021-salmos-094.adoc#v21-94-0[Próximo Capítulo &#62;]