include::./index.adoc[]

[[v21-83-0]]
=== Salmos, 83
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 83 é um salmo de súplica em que o salmista clama a Deus para que Ele venha em socorro do seu povo, que está sendo cercado pelos inimigos. O salmista enumera os vários povos que se uniram contra Israel, e suplica a Deus para que os derrote. A seguir, estão cinco versículos relacionados aos temas abordados em Salmo 83, em ordem de proximidade com o capítulo:
* Salmos 2:1-2: "Por que se amotinam os gentios, e os povos imaginam coisas vãs? Os reis da terra se levantam, e os governadores juntos se mancomunam contra o SENHOR e contra o seu ungido." Este trecho de Salmo 2 também fala da rebelião dos povos contra Deus e Seus ungidos, tal como o salmista de Salmo 83.
* Salmos 56:9: "Quando eu a ti clamar, então voltarão para trás os meus inimigos; isto sei eu, porque Deus é por mim." O salmista de Salmo 56 também clama a Deus para que os seus inimigos sejam derrotados.
* Salmos 35:1: "Pleiteia, SENHOR, com aqueles que pleiteiam comigo; peleja contra os que pelejam contra mim." Neste salmo, o salmista clama a Deus para que venha em seu socorro e lute contra os seus inimigos.
* Salmos 140:1-2: "Livra-me, ó SENHOR, do homem mau; guarda-me do homem violento, que pensa o mal no coração; continuamente se ajuntam para guerrear." O salmista de Salmo 140 também clama a Deus para que o proteja dos seus inimigos.
* Salmos 18:37-40: "Persegui os meus inimigos, e os alcancei; não voltei senão depois de os ter consumido. Atravessei-os, de sorte que não puderam levantar-se; caíram debaixo dos meus pés. Pois me cingiste de força para a peleja; fizeste abater debaixo de mim aqueles que contra mim se levantaram. Deste-me também o pescoço dos meus inimigos, para que eu pudesse destruir os que me odeiam." Este trecho de Salmo 18 fala da vitória de Deus sobre os inimigos do salmista, tal como o salmista de Salmo 83 suplica.
****

[[v21-83-1]]

^<<v21-83-1,1>>^ Ao mestre de canto. Com a Gitiena. Salmo dos filhos de Coré.^&#42;1^

[[v21-83-2]]

^<<v21-83-2,2>>^ Como são amáveis as vossas moradas, Senhor dos exércitos!

[[v21-83-3]]

^<<v21-83-3,3>>^ Minha alma desfalecida se consome suspirando pelos átrios do Senhor. Meu coração e minha carne exultam pelo Deus vivo.

[[v21-83-4]]

^<<v21-83-4,4>>^ Até o pássaro encontra um abrigo, e a andorinha faz um ninho para pôr seus filhos. Ah, vossos altares, Senhor dos exércitos, meu rei e meu Deus!

[[v21-83-5]]

^<<v21-83-5,5>>^ Felizes os que habitam em vossa casa, Senhor: aí eles vos louvam para sempre.

[[v21-83-6]]

^<<v21-83-6,6>>^ Feliz o homem cujo socorro está em vós, e só pensa em vossa santa peregrinação.

[[v21-83-7]]

^<<v21-83-7,7>>^ Quando atravessam o vale árido, eles o transformam em fontes, e a chuva do outono vem cobri-los de bênçãos.

[[v21-83-8]]

^<<v21-83-8,8>>^ Seu vigor aumenta à medida que avançam, porque logo verão o Deus dos deuses em Sião.

[[v21-83-9]]

^<<v21-83-9,9>>^ Senhor dos exércitos, escutai minha oração, prestai-me ouvidos, ó Deus de Jacó.

[[v21-83-10]]

^<<v21-83-10,10>>^ Ó Deus, nosso escudo, olhai; vede a face daquele que vos é consagrado.^&#42;1^

[[v21-83-11]]

^<<v21-83-11,11>>^ Verdadeiramente, um dia em vossos átrios vale mais que milhares fora deles. Prefiro deter-me no limiar da casa de meu Deus a morar nas tendas dos pecadores.

[[v21-83-12]]

^<<v21-83-12,12>>^ Porque o Senhor Deus é nosso sol e nosso escudo, o Senhor dá a graça e a glória. Ele não recusa os seus bens àqueles que caminham na inocência.

[[v21-83-13]]

^<<v21-83-13,13>>^ Ó Senhor dos exércitos, feliz o homem que em vós confia.

'''

xref:021-salmos/021-salmos-082.adoc#v21-82-0[&#60; Capítulo Anterior] | <<v21-83-0,Topo>> | xref:021-salmos/021-salmos-084.adoc#v21-84-0[Próximo Capítulo &#62;]