include::./index.adoc[]

[[v21-129-0]]
=== Salmos, 129
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 129 é um salmo de súplica por livramento do sofrimento. Nele, o salmista clama a Deus por justiça e libertação das mãos dos seus inimigos. Os versículos relacionados com os temas abordados nesse salmo são:
* Isaías 54:17: "Nenhuma arma forjada contra ti prosperará; e toda língua que se levantar contra ti em juízo, tu a condenarás; esta é a herança dos servos do Senhor, e a sua justiça que provém de mim, diz o Senhor." Esse versículo fala da proteção que Deus concede aos seus servos e da sua justiça, que é a base para o clamor do salmista por livramento.
* Salmo 34:19: "Muitas são as aflições do justo, mas o Senhor o livra de todas." Esse versículo mostra que, embora os justos passem por muitas aflições, Deus os livra de todas elas.
* Romanos 8:37: "Mas em todas estas coisas somos mais que vencedores, por aquele que nos amou." Esse versículo mostra que, por meio do amor de Deus, somos mais que vencedores em todas as nossas lutas.
* Salmo 124:8: "O nosso socorro está no nome do Senhor, que fez o céu e a terra." Esse versículo mostra que o salmista confia no Senhor como seu socorro e protetor.
* Salmo 86:7: "No dia da minha angústia clamarei a ti, pois tu me responderás." Esse versículo mostra a confiança do salmista de que Deus o ouvirá e responderá no dia da sua angústia.
****

[[v21-129-1]]

^<<v21-129-1,1>>^ Cântico das peregrinações. Do fundo do abismo, clamo a vós, Senhor;^&#42;1^

[[v21-129-2]]

^<<v21-129-2,2>>^ Senhor, ouvi minha oração. Que vossos ouvidos estejam atentos à voz de minha súplica.

[[v21-129-3]]

^<<v21-129-3,3>>^ Se tiverdes em conta nossos pecados, Senhor, Senhor, quem poderá subsistir diante de vós?

[[v21-129-4]]

^<<v21-129-4,4>>^ Mas em vós se encontra o perdão dos pecados, para que, reverentes, vos sirvamos.

[[v21-129-5]]

^<<v21-129-5,5>>^ Ponho a minha esperança no Senhor. Minha alma tem confiança em sua palavra.

[[v21-129-6]]

^<<v21-129-6,6>>^ Minha alma espera pelo Senhor, mais ansiosa do que os vigias pela manhã.

[[v21-129-7]]

^<<v21-129-7,7>>^ Mais do que os vigias que aguardam a manhã, espere Israel pelo Senhor, porque junto ao Senhor se acha a misericórdia; encontra-se nele copiosa redenção.

[[v21-129-8]]

^<<v21-129-8,8>>^ E ele mesmo há de remir Israel de todas as suas iniquidades.

'''

xref:021-salmos/021-salmos-128.adoc#v21-128-0[&#60; Capítulo Anterior] | <<v21-129-0,Topo>> | xref:021-salmos/021-salmos-130.adoc#v21-130-0[Próximo Capítulo &#62;]