include::./index.adoc[]

[[v21-134-0]]
=== Salmos, 134
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 134 é um breve cântico de adoração que exorta os servos do Senhor a bendizerem o Senhor no santuário durante a noite. É um chamado à adoração ao Deus verdadeiro e uma lembrança de que ele é o Criador de todas as coisas. Aqui estão cinco versículos da Bíblia que abordam temas semelhantes ao Salmo 134:
* Salmos 113:3: "Desde o nascer do sol até ao ocaso, seja louvado o nome do Senhor." Esse versículo é um chamado à adoração contínua do Senhor, do amanhecer ao anoitecer, sem cessar.
* Salmos 135:1-3: "Louvai ao Senhor. Louvai o nome do Senhor; louvai-o, servos do Senhor, que estais na casa do Senhor, nos átrios da casa do nosso Deus. Louvai ao Senhor, porque o Senhor é bom; cantai louvores ao seu nome, porque é agradável." Esses versículos exortam os servos do Senhor a louvá-lo em sua casa, nos átrios da casa do nosso Deus, por causa de sua bondade e graça.
* Salmos 136:1-3: "Louvai ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre. Louvai ao Deus dos deuses; porque a sua benignidade dura para sempre. Louvai ao Senhor dos senhores; porque a sua benignidade dura para sempre." Esse Salmo é uma oração de agradecimento e louvor pela bondade do Senhor em todas as coisas, do começo ao fim.
* Salmos 139:1-2: "Senhor, tu me sondaste, e me conheces. Tu conheces o meu sentar e o meu levantar; de longe entendes o meu pensamento." Esses versículos mostram que Deus conhece intimamente cada pessoa, e ele é digno de adoração e louvor.
* Apocalipse 4:11: "Digno és, Senhor, de receber glória, e honra, e poder; porque tu criaste todas as coisas, e por tua vontade são e foram criadas." Esse versículo é um cântico de adoração a Deus, reconhecendo sua soberania e poder como o criador de todas as coisas.
****

[[v21-134-1]]

^<<v21-134-1,1>>^ Aleluia. Louvai o nome do Senhor, louvai-o, servos do Senhor,^&#42;1^

[[v21-134-2]]

^<<v21-134-2,2>>^ vós que estais no Templo do Senhor, nos átrios da casa de nosso Deus.

[[v21-134-3]]

^<<v21-134-3,3>>^ Louvai o Senhor, porque ele é bom; cantai à glória de seu nome, porque ele é amável.

[[v21-134-4]]

^<<v21-134-4,4>>^ Pois o Senhor escolheu Jacó para si, ele tomou Israel por sua herança.

[[v21-134-5]]

^<<v21-134-5,5>>^ Em verdade, sei que o Senhor é grande, e nosso Deus é maior que todos os deuses.

[[v21-134-6]]

^<<v21-134-6,6>>^ O Senhor faz tudo o que lhe apraz, no céu e na terra, no mar e nas profundezas das águas.

[[v21-134-7]]

^<<v21-134-7,7>>^ Ele chama as nuvens dos confins da terra, faz chover em meio aos relâmpagos, solta o vento de seus reservatórios.

[[v21-134-8]]

^<<v21-134-8,8>>^ Foi ele que feriu os primogênitos do Egito, tanto dos homens como dos brutos.

[[v21-134-9]]

^<<v21-134-9,9>>^ Realizou em ti, Egito, sinais e prodígios, contra o faraó de todos os seus servos.

[[v21-134-10]]

^<<v21-134-10,10>>^ Abateu numerosas nações, e exterminou reis poderosos:

[[v21-134-11]]

^<<v21-134-11,11>>^ Seon, rei dos amorreus; Og, rei de Basã, assim como todos os reis de Canaã.

[[v21-134-12]]

^<<v21-134-12,12>>^ E deu a terra deles em herança, como patrimônio para Israel, seu povo.

[[v21-134-13]]

^<<v21-134-13,13>>^ Ó Senhor, vosso nome é eterno! Senhor, vossa lembrança passa de geração em geração,

[[v21-134-14]]

^<<v21-134-14,14>>^ pois o Senhor é o guarda de seu povo, e tem piedade de seus servos.

[[v21-134-15]]

^<<v21-134-15,15>>^ Os ídolos dos pagãos não passam de prata e ouro, são obras de mãos humanas.

[[v21-134-16]]

^<<v21-134-16,16>>^ Têm boca e não podem falar; têm olhos e não podem ver;

[[v21-134-17]]

^<<v21-134-17,17>>^ têm ouvidos e não podem ouvir. Não há respiração em sua boca.

[[v21-134-18]]

^<<v21-134-18,18>>^ Assemelhem-se a eles todos os que os fizeram, e todos os que neles confiam.

[[v21-134-19]]

^<<v21-134-19,19>>^ Casa de Israel, bendizei o Senhor; casa de Aarão, bendizei o Senhor;

[[v21-134-20]]

^<<v21-134-20,20>>^ casa de Levi, bendizei o Senhor. Vós todos que o servis, bendizei o Senhor.

[[v21-134-21]]

^<<v21-134-21,21>>^ De Sião seja bendito o Senhor, que habita em Jerusalém.

'''

xref:021-salmos/021-salmos-133.adoc#v21-133-0[&#60; Capítulo Anterior] | <<v21-134-0,Topo>> | xref:021-salmos/021-salmos-135.adoc#v21-135-0[Próximo Capítulo &#62;]