include::./index.adoc[]

[[v21-102-0]]
=== Salmos, 102
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 102 é um lamento de uma pessoa que está sofrendo e se sente distante de Deus. O salmista expressa sua tristeza, mas também confia na fidelidade de Deus e na sua capacidade de curar e restaurar. Abaixo estão cinco versículos que se relacionam com os temas do Salmo 102.
* Salmos 34:18: "Perto está o Senhor dos que têm o coração quebrantado e salva os de espírito oprimido." Este versículo fala sobre a proximidade de Deus com aqueles que estão sofrendo e se sentem oprimidos.
* Salmos 103:13: "Como um pai se compadece de seus filhos, assim o Senhor se compadece daqueles que o temem." Este versículo fala sobre a compaixão de Deus para com seus filhos, mostrando que ele se importa com o sofrimento deles.
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Este versículo mostra que Deus é um Deus de fortalecimento e ajuda, capaz de sustentar aqueles que confiam nele.
* 2 Coríntios 1:3-4: "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e Deus de toda a consolação, que nos consola em todas as nossas tribulações, para que também possamos consolar os que estiverem em alguma tribulação, com a consolação com que nós mesmos somos consolados por Deus." Este versículo fala sobre a capacidade de Deus de nos consolar em nossas tribulações e, por sua vez, capacita-nos a consolar os outros.
* Romanos 8:28: "Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito." Este versículo fala sobre a fidelidade de Deus em usar todas as coisas, inclusive o sofrimento, para o bem daqueles que o amam e são chamados segundo o seu propósito.
****

[[v21-102-1]]

^<<v21-102-1,1>>^ Salmo de Davi. Bendize, ó minha alma, o Senhor, e tudo o que existe em mim bendiga o seu santo nome.^&#42;1^

[[v21-102-2]]

^<<v21-102-2,2>>^ Bendize, ó minha alma, o Senhor, e jamais te esqueças de todos os seus benefícios.

[[v21-102-3]]

^<<v21-102-3,3>>^ É ele que perdoa as tuas faltas, e sara as tuas enfermidades.

[[v21-102-4]]

^<<v21-102-4,4>>^ É ele que salva tua vida da morte, e te coroa de bondade e de misericórdia.

[[v21-102-5]]

^<<v21-102-5,5>>^ É ele que cumula de benefícios a tua vida, e renova a tua juventude como a da águia.

[[v21-102-6]]

^<<v21-102-6,6>>^ O Senhor faz justiça, dá o direito aos oprimidos.

[[v21-102-7]]

^<<v21-102-7,7>>^ Revelou seus caminhos a Moisés, e suas obras aos filhos de Israel.

[[v21-102-8]]

^<<v21-102-8,8>>^ O Senhor é bom e misericordioso, lento para a cólera e cheio de clemência.^&#42;1^

[[v21-102-9]]

^<<v21-102-9,9>>^ Ele não está sempre a repreender, nem eterno é o seu ressentimento.

[[v21-102-10]]

^<<v21-102-10,10>>^ Não nos trata segundo os nossos pecados, nem nos castiga em proporção de nossas faltas,

[[v21-102-11]]

^<<v21-102-11,11>>^ porque tanto os céus distam da terra quanto sua misericórdia é grande para os que o temem;

[[v21-102-12]]

^<<v21-102-12,12>>^ tanto o oriente dista do ocidente quanto ele afasta de nós nossos pecados.

[[v21-102-13]]

^<<v21-102-13,13>>^ Como um pai tem piedade de seus filhos, assim o Senhor tem compaixão dos que o temem,

[[v21-102-14]]

^<<v21-102-14,14>>^ porque ele sabe de que é que somos feitos, e não se esquece de que somos pó.

[[v21-102-15]]

^<<v21-102-15,15>>^ Os dias do homem são semelhantes a erva, ele floresce como a flor dos campos.

[[v21-102-16]]

^<<v21-102-16,16>>^ Apenas sopra o vento, já não existe, e nem se conhece mais o seu lugar.

[[v21-102-17]]

^<<v21-102-17,17>>^ É eterna, porém, a misericórdia do Senhor para com os que o temem. E sua justiça se estende aos filhos de seus filhos,

[[v21-102-18]]

^<<v21-102-18,18>>^ sobre os que guardam a sua aliança, e, lembrando, cumprem seus mandamentos.

[[v21-102-19]]

^<<v21-102-19,19>>^ Nos céus estabeleceu o Senhor o seu trono, e o seu império se estende sobre o universo.

[[v21-102-20]]

^<<v21-102-20,20>>^ Bendizei o Senhor todos os seus anjos, valentes heróis que cumpris suas ordens, sempre dóceis à sua palavra.

[[v21-102-21]]

^<<v21-102-21,21>>^ Bendizei o Senhor todos os seus exércitos, ministros que executais sua vontade.

[[v21-102-22]]

^<<v21-102-22,22>>^ Bendizei o Senhor todas as suas obras, em todos os lugares onde ele domina. Bendize, ó minha alma, o Senhor.

'''

xref:021-salmos/021-salmos-101.adoc#v21-101-0[&#60; Capítulo Anterior] | <<v21-102-0,Topo>> | xref:021-salmos/021-salmos-103.adoc#v21-103-0[Próximo Capítulo &#62;]