include::./index.adoc[]

[[v21-88-0]]
=== Salmos, 88
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Salmo 88 é um salmo de lamento, no qual o salmista expressa sua angústia e desespero diante de Deus. Ele clama por ajuda e salvação, mas sente como se Deus o tivesse abandonado. Os versículos a seguir abordam temas semelhantes de sofrimento e angústia, bem como a busca pela ajuda e a presença de Deus.
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Este versículo fala sobre a presença de Deus e seu poder para ajudar e fortalecer aqueles que confiam nele. Isso pode trazer conforto para aqueles que estão passando por momentos difíceis, como o salmista em Salmo 88.
* Salmos 34:18: "Perto está o Senhor dos que têm o coração quebrantado e salva os contritos de espírito." Este versículo fala sobre como Deus está perto daqueles que estão sofrendo e têm um coração quebrantado. Ele é capaz de trazer salvação e conforto para aqueles que clamam por ajuda, como o salmista em Salmo 88.
* 2 Coríntios 1:3-4: "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e o Deus de toda a consolação, que nos consola em toda a nossa tribulação, para que também possamos consolar os que estiverem em alguma tribulação, com a consolação com que nós mesmos somos consolados por Deus." Este versículo fala sobre como Deus pode usar a tribulação e o sofrimento para nos ensinar a consolar e ajudar os outros que estão passando por dificuldades semelhantes. O salmista em Salmo 88 pode encontrar conforto em saber que sua experiência de sofrimento pode ser usada para ajudar outros no futuro.
* Salmos 42:5: "Por que estás abatida, ó minha alma? e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei pela salvação que há na sua presença." Este versículo encoraja o salmista a confiar em Deus e esperar pela sua salvação. Ele pode encontrar consolo em saber que Deus ainda é capaz de salvá-lo, apesar de sua situação atual.
* Romanos 8:38-39: "Porque estou certo de que, nem a morte, nem a vida, nem anjos, nem principados, nem coisas presentes, nem futuras, nem potestades, nem a altura, nem a profundidade, nem qualquer outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus nosso Senhor." Este versículo fala sobre a certeza do amor de Deus e como nada pode nos separar dele. Isso pode trazer conforto e esperança para aqueles que estão sofrendo, sabendo que Deus ainda os ama e está com eles, mesmo em meio à dor e ao sofrimento.
****

[[v21-88-1]]

^<<v21-88-1,1>>^ Hino de Etã, ezraíta.^&#42;1^

[[v21-88-2]]

^<<v21-88-2,2>>^ Cantarei, eternamente, as bondades do Senhor; minha boca publicará sua fidelidade de geração em geração.

[[v21-88-3]]

^<<v21-88-3,3>>^ Com efeito, vós dissestes: “A bondade é um edifício eterno”. Vossa fidelidade firmastes no céu.

[[v21-88-4]]

^<<v21-88-4,4>>^ “Concluí – dizeis vós –, uma aliança com o meu eleito; liguei-me por juramento a Davi, meu servo.^&#42;1^

[[v21-88-5]]

^<<v21-88-5,5>>^ Conservarei tua linhagem para sempre, manterei teu trono em todas as gerações.”

[[v21-88-6]]

^<<v21-88-6,6>>^ Senhor, os céus celebram as vossas maravilhosas obras, e na assembleia dos anjos, a vossas fidelidade.

[[v21-88-7]]

^<<v21-88-7,7>>^ Quem poderá, nas nuvens, igualar-se a Deus? Quem é semelhante ao Senhor entre os filhos de Deus?

[[v21-88-8]]

^<<v21-88-8,8>>^ Terrível é Deus na assembleia dos santos, maior e mais tremendo que todos os que o cercam.

[[v21-88-9]]

^<<v21-88-9,9>>^ Quem se compara a vós, Senhor, Deus dos exércitos? Sois forte, Senhor, e cheio de fidelidade.

[[v21-88-10]]

^<<v21-88-10,10>>^ Dominais o orgulho do mar, amainais suas ondas revoltas.

[[v21-88-11]]

^<<v21-88-11,11>>^ Calcastes Raab e o transportastes com poderoso braço dispersastes vossos inimigos.

[[v21-88-12]]

^<<v21-88-12,12>>^ Vossos são os céus e também a terra, vós que criastes o globo e tudo o que ele contém.

[[v21-88-13]]

^<<v21-88-13,13>>^ O norte e o sul vós os fizestes; Tabor e Hermon em vosso nome exultam.

[[v21-88-14]]

^<<v21-88-14,14>>^ Tendes o poder em vosso braço, a firmeza na mão, a autoridade em vossa destra.

[[v21-88-15]]

^<<v21-88-15,15>>^ A justiça e o direito são o fundamento de vosso trono, a bondade e a fidelidade vos precedem.

[[v21-88-16]]

^<<v21-88-16,16>>^ Feliz o povo que vos sabe louvar: caminha na luz de vossa face, Senhor.

[[v21-88-17]]

^<<v21-88-17,17>>^ Vosso nome lhe é causa de contínua alegria, pela vossa justiça ele se glorifica,

[[v21-88-18]]

^<<v21-88-18,18>>^ porque sois o esplendor de sua força, e é vosso favor que nos faz erguer a cabeça,

[[v21-88-19]]

^<<v21-88-19,19>>^ pois no Senhor está o nosso escudo, e nosso rei no Santo de Israel.

[[v21-88-20]]

^<<v21-88-20,20>>^ Outrora, em visão, falastes aos vossos santos e dissestes-lhes: “Impus a coroa a um herói, escolhi meu eleito dentre o povo.^&#42;1^

[[v21-88-21]]

^<<v21-88-21,21>>^ Encontrei Davi, meu servidor, e o sagrei com a minha santa unção.^&#42;1^

[[v21-88-22]]

^<<v21-88-22,22>>^ Minha mão sempre lhe assistirá, e meu braço o fortalecerá.

[[v21-88-23]]

^<<v21-88-23,23>>^ Não há de surpreendê-lo o inimigo, nem ousará oprimi-lo o malvado.

[[v21-88-24]]

^<<v21-88-24,24>>^ Sob seus olhos esmagarei os seus contrários, serão feridos aqueles que o odeiam.

[[v21-88-25]]

^<<v21-88-25,25>>^ Com ele ficarão minha fidelidade e bondade, pelo meu nome crescerá o seu poder.

[[v21-88-26]]

^<<v21-88-26,26>>^ Estenderei a sua mão por sobre o mar, e a sua destra acima dos rios.

[[v21-88-27]]

^<<v21-88-27,27>>^ Ele me invocará: ‘Vós sois meu Pai, vós sois meu Deus e meu rochedo protetor’.

[[v21-88-28]]

^<<v21-88-28,28>>^ Por isso, eu o constituirei meu primogênito, o mais excelso dentre todos os reis da terra.

[[v21-88-29]]

^<<v21-88-29,29>>^ Assegurado lhe estará o favor eterno, e indissolúvel será meu pacto com ele.

[[v21-88-30]]

^<<v21-88-30,30>>^ Eu lhe darei uma perpétua descendência, seu trono terá a duração do céu.

[[v21-88-31]]

^<<v21-88-31,31>>^ Se, porém, seus filhos abandonarem minha Lei, se não observarem os meus preceitos,

[[v21-88-32]]

^<<v21-88-32,32>>^ se violarem as minhas prescrições e não obedecerem às minhas ordens,

[[v21-88-33]]

^<<v21-88-33,33>>^ eu punirei com vara a sua transgressão, e a sua falta castigarei com açoite.

[[v21-88-34]]

^<<v21-88-34,34>>^ Mas não lhe retirarei o meu favor e não trairei minha promessa.

[[v21-88-35]]

^<<v21-88-35,35>>^ Não violarei minha aliança, não mudarei minha palavra dada.

[[v21-88-36]]

^<<v21-88-36,36>>^ Jurei uma vez por todas pela minha santidade: a Davi não faltarei jamais.

[[v21-88-37]]

^<<v21-88-37,37>>^ Sua posteridade permanecerá eternamente, e seu trono, como o sol, subsistirá diante de mim,

[[v21-88-38]]

^<<v21-88-38,38>>^ como a lua que existirá sem-fim, e o arco-íris, fiel testemunha nos céus”.^&#42;1^

[[v21-88-39]]

^<<v21-88-39,39>>^ E, contudo, vós o repelistes e rejeitastes, gravemente vos irritastes contra aquele que vos é consagrado.

[[v21-88-40]]

^<<v21-88-40,40>>^ Rompestes a aliança feita com o vosso servidor, lançastes por terra sua coroa,

[[v21-88-41]]

^<<v21-88-41,41>>^ derrubastes todos os seus muros, arruinastes as suas fortalezas.

[[v21-88-42]]

^<<v21-88-42,42>>^ Saquearam-no todos os transeuntes, e o escarneceram os seus vizinhos.

[[v21-88-43]]

^<<v21-88-43,43>>^ A mão de seus inimigos exaltastes, de gozo enchestes todos os seus contrários.

[[v21-88-44]]

^<<v21-88-44,44>>^ Embotastes o fio de sua espada, não o sustentastes na batalha.

[[v21-88-45]]

^<<v21-88-45,45>>^ Fizestes terminar seu esplendor, por terra derrubastes o seu trono.

[[v21-88-46]]

^<<v21-88-46,46>>^ Abreviastes a sua adolescência, e de ignomínia o cobristes.

[[v21-88-47]]

^<<v21-88-47,47>>^ Até quando, Senhor? Até quando continuareis escondido? Até quando estará acesa a vossa cólera?

[[v21-88-48]]

^<<v21-88-48,48>>^ Lembrai-vos como é curta a nossa vida, quão efêmeros os homens que criastes.

[[v21-88-49]]

^<<v21-88-49,49>>^ Qual é o vivo que se livra da morte, ou pode subtrair a sua alma ao poder da morada dos mortos?

[[v21-88-50]]

^<<v21-88-50,50>>^ Vossas bondades de outrora, ó Senhor, onde estão? E os juramentos que a Davi fizestes de fidelidade?

[[v21-88-51]]

^<<v21-88-51,51>>^ Considerai, Senhor, a vergonha imposta aos vossos servidores. Levo em meu seio ultrajes das nações pagãs,

[[v21-88-52]]

^<<v21-88-52,52>>^ insultos de vossos inimigos, Senhor, injúrias que lançam até nos passos daquele que vos é consagrado.

[[v21-88-53]]

^<<v21-88-53,53>>^ Bendito seja o Senhor, eternamente! Amém! Amém!^&#42;1^

'''

xref:021-salmos/021-salmos-087.adoc#v21-87-0[&#60; Capítulo Anterior] | <<v21-88-0,Topo>> | xref:021-salmos/021-salmos-089.adoc#v21-89-0[Próximo Capítulo &#62;]