include::./index.adoc[]

[[v21-20-0]]
=== Salmos, 20
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 20 é uma oração para o sucesso e proteção do rei e do povo de Israel em tempos de guerra. O salmista invoca a ajuda divina e pede que Deus ouça as suas preces. Abaixo estão cinco versículos relacionados com os temas abordados no Salmo 20:
* Isaías 31:5: "Como as aves voam, assim o Senhor dos Exércitos protegerá Jerusalém; ele a protegerá, ele a livrará, ele a poupará e a resgatará." Este versículo fala da proteção que Deus oferece ao seu povo em tempos de guerra, assim como o salmista pede no Salmo 20.
* 2 Crônicas 32:7: "Esforcem-se e sejam corajosos; não tenham medo nem desanimem diante do rei da Assíria e de todo o exército que está com ele, pois há um maior conosco do que com ele." Esse verso fala da confiança que o rei Ezequias tinha na ajuda divina em tempos de guerra, assim como o salmista no Salmo 20.
* Salmos 33:16: "Nenhum rei é salvo pelo tamanho do seu exército; nenhum guerreiro escapa pela sua grande força." Este versículo destaca a importância da ajuda divina na proteção do povo de Deus, independentemente do tamanho do exército ou da força militar.
* Deuteronômio 20:4: "Pois o Senhor, o seu Deus, os acompanhará e lutará por vocês contra os inimigos, para dar-lhes a vitória." Esse verso fala da confiança que o povo de Israel tinha na ajuda divina em tempos de guerra, assim como o salmista no Salmo 20.
* Salmo 144:1: "Bendito seja o Senhor, minha Rocha, que treina minhas mãos para a guerra e meus dedos para a batalha." Este verso fala da confiança do salmista na ajuda divina em tempos de guerra, assim como o salmo 20.
****

[[v21-20-1]]

^<<v21-20-1,1>>^ Ao mestre de canto. Salmo de Davi.^&#42;1^

[[v21-20-2]]

^<<v21-20-2,2>>^ Senhor, alegra-se o rei com o vosso poder, e muito exulta com o vosso auxílio!

[[v21-20-3]]

^<<v21-20-3,3>>^ Realizastes os anseios de seu coração, não rejeitastes a prece de seus lábios.

[[v21-20-4]]

^<<v21-20-4,4>>^ Com preciosas bênçãos fostes-lhe ao encontro, pusestes-lhe na cabeça coroa de puríssimo ouro.

[[v21-20-5]]

^<<v21-20-5,5>>^ Ele vos pediu a vida, vós lha concedestes, uma vida cujos dias serão eternos.

[[v21-20-6]]

^<<v21-20-6,6>>^ Grande é a sua glória, devida à vossa proteção; vós o cobristes de majestade e esplendor.

[[v21-20-7]]

^<<v21-20-7,7>>^ Sim, fizestes dele o objeto de vossas eternas bênçãos, de alegria o cobristes com a vossa presença,

[[v21-20-8]]

^<<v21-20-8,8>>^ pois o rei confiou no Senhor. Graças ao Altíssimo não será abalado.

[[v21-20-9]]

^<<v21-20-9,9>>^ Que tua mão, ó rei, apanhe teus inimigos, que tua mão atinja os que te odeiam.

[[v21-20-10]]

^<<v21-20-10,10>>^ Tu os tornarás como fornalha ardente, quando apareceres diante deles. Que o Senhor em sua cólera os consuma, e que o fogo os devore.

[[v21-20-11]]

^<<v21-20-11,11>>^ Faze desaparecer da terra a posteridade deles e a sua descendência dentre os filhos dos homens.

[[v21-20-12]]

^<<v21-20-12,12>>^ Se intentarem fazer-te mal, tramando algum plano, não o conseguirão,

[[v21-20-13]]

^<<v21-20-13,13>>^ porque os porás em fuga, dirigindo teu arco contra a face deles.

[[v21-20-14]]

^<<v21-20-14,14>>^ Erguei-vos, Senhor, em vossa potência! Cantaremos e celebraremos o vosso poder.

'''

xref:021-salmos/021-salmos-019.adoc#v21-19-0[&#60; Capítulo Anterior] | <<v21-20-0,Topo>> | xref:021-salmos/021-salmos-021.adoc#v21-21-0[Próximo Capítulo &#62;]