include::./index.adoc[]

[[v21-71-0]]
=== Salmos, 71
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 71 é um salmo de súplica e confiança em Deus em meio a dificuldades e perseguições. O salmista clama pela proteção e salvação de Deus e coloca a sua fé Nele como a sua esperança e refúgio. Os versículos escolhidos são:
* Isaías 46:4: "Até à vossa velhice, eu serei o mesmo e ainda até às cãs eu vos trarei; eu o fiz e eu vos levarei, e eu vos trarei e vos guardarei." Este versículo fala da fidelidade de Deus em cuidar e proteger o Seu povo, mesmo na velhice.
* Salmos 22:9-10: "Mas tu és aquele que me tiraste do ventre; tu me preservaste confiado aos seios de minha mãe. Sobre ti fui lançado desde a madre; tu és o meu Deus desde o ventre de minha mãe." Este versículo fala da confiança do salmista em Deus desde o seu nascimento e da sua dependência total em Deus.
* Salmos 31:1-2: "Em ti, SENHOR, confio; nunca me deixes confundido. Livra-me pela tua justiça e faze-me escapar; inclina os teus ouvidos para mim e salva-me." Este versículo expressa a confiança do salmista em Deus e o seu pedido por proteção e salvação.
* Salmos 46:1-3: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia. Pelo que não temeremos, ainda que a terra se mude e ainda que os montes se projetem para o meio dos mares; ainda que as águas rujam e espumem, ainda que os montes se abalem pela sua braveza." Este versículo fala da proteção e fortaleza de Deus em meio a situações difíceis e perigosas.
* Salmos 73:26: "A minha carne e o meu coração desfalecem; mas Deus é a fortaleza do meu coração e a minha porção para sempre." Este versículo fala da dependência do salmista em Deus mesmo em meio às suas fraquezas e dificuldades, reconhecendo que somente em Deus ele pode encontrar força e sustento.
****

[[v21-71-1]]

^<<v21-71-1,1>>^ De Salomão. Ó Deus, confiai ao rei os vossos juízos. Entregai a justiça nas mãos do filho real,^&#42;1^

[[v21-71-2]]

^<<v21-71-2,2>>^ para que ele governe com justiça vosso povo, e reine sobre vossos humildes servos com equidade.

[[v21-71-3]]

^<<v21-71-3,3>>^ Produzirão as montanhas frutos de paz ao vosso povo; e as colinas, frutos de justiça.

[[v21-71-4]]

^<<v21-71-4,4>>^ Ele protegerá os humildes do povo, salvará os filhos dos pobres e abaterá o opressor.

[[v21-71-5]]

^<<v21-71-5,5>>^ Ele viverá tão longamente como dura o sol, tanto quanto ilumina a lua, através das gerações.

[[v21-71-6]]

^<<v21-71-6,6>>^ Descerá como a chuva sobre a relva, como os aguaceiros que embebem a terra.

[[v21-71-7]]

^<<v21-71-7,7>>^ Florescerá em seus dias a justiça, e a abundância da paz até que cesse a lua de brilhar.

[[v21-71-8]]

^<<v21-71-8,8>>^ Ele dominará de um ao outro mar, desde o grande rio até os confins da terra.^&#42;1^

[[v21-71-9]]

^<<v21-71-9,9>>^ Diante dele se prosternarão seus inimigos, e seus adversários lamberão o pó.

[[v21-71-10]]

^<<v21-71-10,10>>^ Os reis de Társis e das ilhas lhe trarão presentes, os reis da Arábia e de Sabá lhe oferecerão seus dons.

[[v21-71-11]]

^<<v21-71-11,11>>^ Todos os reis hão de adorá-lo, hão de servi-lo todas as nações.

[[v21-71-12]]

^<<v21-71-12,12>>^ Porque ele livrará o infeliz que o invoca, e o miserável que não tem amparo.

[[v21-71-13]]

^<<v21-71-13,13>>^ Ele se apiedará do pobre e do indigente, e salvará a vida dos necessitados.

[[v21-71-14]]

^<<v21-71-14,14>>^ Ele o livrará da injustiça e da opressão, e preciosa será a sua vida ante seus olhos.

[[v21-71-15]]

^<<v21-71-15,15>>^ Assim ele viverá e o ouro da Arábia lhe será ofertado; por ele hão de rezar sempre e o bendirão perpetuamente.

[[v21-71-16]]

^<<v21-71-16,16>>^ Haverá na terra fartura de trigo, suas espigas ondularão no cume das colinas como as ramagens do Líbano; e o povo das cidades florescerá como as ervas dos campos.

[[v21-71-17]]

^<<v21-71-17,17>>^ Seu nome será eternamente bendito, e durará tanto quanto a luz do sol. Nele serão abençoadas todas as tribos da terra, bem-aventurado o proclamarão todas as nações.

[[v21-71-18]]

^<<v21-71-18,18>>^ Bendito seja o Senhor, Deus de Israel, que, só ele, faz maravilhas.

[[v21-71-19]]

^<<v21-71-19,19>>^ Bendito seja eternamente seu nome glorioso,^&#42;1^ e que toda a terra se encha de sua glória. Amém! Amém!

[[v21-71-20]]

^<<v21-71-20,20>>^ Aqui terminam as preces de Davi, filho de Jessé.

'''

xref:021-salmos/021-salmos-070.adoc#v21-70-0[&#60; Capítulo Anterior] | <<v21-71-0,Topo>> | xref:021-salmos/021-salmos-072.adoc#v21-72-0[Próximo Capítulo &#62;]