include::./index.adoc[]

[[v21-30-0]]
=== Salmos, 30
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 30 é um hino de agradecimento a Deus pela salvação, no qual o salmista expressa sua gratidão por ter sido curado e livrado da morte. Ele louva a Deus por ter transformado seu pranto em dança, seu luto em alegria e por ter removido seu cilício e cingido-o de alegria. Abaixo estão cinco versículos relacionados com os temas abordados em Salmo 30:
* Salmos 103:2: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios." Este versículo encoraja a gratidão a Deus por suas bênçãos e benefícios.
* Salmos 40:2: "Tirou-me dum lago horrível, dum charco de lodo, pôs os meus pés sobre uma rocha, firmou os meus passos." Este versículo descreve a salvação e libertação de Deus.
* Salmos 56:8: "Tu contas as minhas vagueações; põe as minhas lágrimas no teu odre; não estão elas no teu livro?" Este versículo destaca a preocupação de Deus com nossas aflições e tristezas.
* Salmos 126:5: "Os que semeiam em lágrimas, com cânticos de júbilo segarão." Este versículo fala da alegria e da colheita que vêm após um período de sofrimento e tristeza.
* Salmos 30:5: "Porque a sua ira dura só um momento; no seu favor está a vida. O choro pode durar uma noite; pela manhã, porém, vem o cântico de júbilo." Este versículo, que faz parte do próprio Salmo 30, enfatiza a transitoriedade do sofrimento e a promessa de alegria e vitória.
****

[[v21-30-1]]

^<<v21-30-1,1>>^ Ao mestre de canto. Salmo de Davi.^&#42;1^

[[v21-30-2]]

^<<v21-30-2,2>>^ Junto de vós, Senhor, me refugio. Não seja eu confundido para sempre; por vossa justiça, livrai-me!

[[v21-30-3]]

^<<v21-30-3,3>>^ Inclinai para mim vossos ouvidos, apressai-vos em me libertar. Sede para mim uma rocha de refúgio, uma fortaleza bem armada para me salvar.

[[v21-30-4]]

^<<v21-30-4,4>>^ Pois só vós sois minha rocha e fortaleza: haveis de me guiar e dirigir, por amor de vosso nome.

[[v21-30-5]]

^<<v21-30-5,5>>^ Vós me livrareis das ciladas que me armaram, porque sois minha defesa.

[[v21-30-6]]

^<<v21-30-6,6>>^ Em vossas mãos entrego meu espírito; livrai-me, ó Senhor, Deus fiel.^&#42;1^

[[v21-30-7]]

^<<v21-30-7,7>>^ Detestais os que adoram ídolos vãos. Eu, porém, confio no Senhor.

[[v21-30-8]]

^<<v21-30-8,8>>^ Exultarei e me alegrarei pela vossa compaixão, porque olhastes para minha miséria e ajudastes minha alma angustiada.

[[v21-30-9]]

^<<v21-30-9,9>>^ Não me entregastes às mãos do inimigo, mas alargastes o caminho sob meus pés.

[[v21-30-10]]

^<<v21-30-10,10>>^ Tende piedade de mim, Senhor, porque vivo atribulado, de tristeza definham meus olhos, minha alma e minhas entranhas.

[[v21-30-11]]

^<<v21-30-11,11>>^ Realmente, minha vida se consome em amargura, e meus anos em gemidos. Minhas forças se esgotaram na aflição, mirraram-se os meus ossos.

[[v21-30-12]]

^<<v21-30-12,12>>^ Tornei-me objeto de opróbrio para todos os inimigos, zombaria dos vizinhos e pavor dos conhecidos. Fogem de mim os que me vêem na rua.

[[v21-30-13]]

^<<v21-30-13,13>>^ Fui esquecido dos corações como um morto, fiquei rejeitado como um vaso partido.

[[v21-30-14]]

^<<v21-30-14,14>>^ Sim, eu ouvi o vozerio da multidão; em toda parte, o terror! Conspirando contra mim, tramam como me tirar a vida.

[[v21-30-15]]

^<<v21-30-15,15>>^ Mas eu, Senhor, em vós confio. Digo: “Sois vós o meu Deus”.

[[v21-30-16]]

^<<v21-30-16,16>>^ Meu destino está nas vossas mãos. Livrai-me do poder de meus inimigos e perseguidores.

[[v21-30-17]]

^<<v21-30-17,17>>^ Mostrai semblante sereno ao vosso servo, salvai-me pela vossa misericórdia.

[[v21-30-18]]

^<<v21-30-18,18>>^ Senhor, não fique eu envergonhado, porque vos invoquei: Confundidos sejam os ímpios e, mudos, lançados na região dos mortos.

[[v21-30-19]]

^<<v21-30-19,19>>^ Fazei calar os lábios mentirosos que falam contra o justo com insolência, desprezo e arrogância.

[[v21-30-20]]

^<<v21-30-20,20>>^ Quão grande é, Senhor, vossa bondade, que reservastes para os que vos temem e com que tratais aos que se refugiam em vós, aos olhos de todos.

[[v21-30-21]]

^<<v21-30-21,21>>^ Sob a proteção de vossa face os defendeis contra as conspirações dos homens. Vós os ocultais em vossa tenda contra as línguas maldizentes.

[[v21-30-22]]

^<<v21-30-22,22>>^ Bendito seja o Senhor, que usou de maravilhosa bondade, abrigando-me em cidade fortificada.

[[v21-30-23]]

^<<v21-30-23,23>>^ Eu, porém, tinha dito no meu temor: “Fui rejeitado de vossa presença”. Mas ouvistes antes o brado de minhas súplicas, quando clamava a vós.

[[v21-30-24]]

^<<v21-30-24,24>>^ Amai o Senhor todos os seus servos! Ele protege os que lhe são fiéis. Sabe, porém, retribuir, castigando com rigor os que procedem com soberba.

[[v21-30-25]]

^<<v21-30-25,25>>^ Animai-vos e sede fortes de coração todos vós, que esperais no Senhor.

'''

xref:021-salmos/021-salmos-029.adoc#v21-29-0[&#60; Capítulo Anterior] | <<v21-30-0,Topo>> | xref:021-salmos/021-salmos-031.adoc#v21-31-0[Próximo Capítulo &#62;]