include::./index.adoc[]

[[v21-33-0]]
=== Salmos, 33
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 33 é um hino de louvor a Deus como Criador e Sustentador do universo. O salmista celebra a grandeza de Deus e Sua fidelidade, e exorta o povo a confiar nEle em vez de confiar em coisas terrenas. A seguir estão cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em Salmo 33.
* Gênesis 1:1-2: "No princípio, criou Deus os céus e a terra. A terra, porém, estava sem forma e vazia; havia trevas sobre a face do abismo, e o Espírito de Deus pairava por sobre as águas." Este é o primeiro verso da Bíblia e descreve a criação do universo por Deus. O Salmo 33 também celebra a grandeza e poder de Deus como Criador.
* Neemias 9:6: "Só tu és o Senhor; fizeste o céu, o céu dos céus, e todo o seu exército, a terra e tudo quanto nela há, os mares e tudo quanto neles há; e tu os preservas a todos com vida, e o exército dos céus te adora." Este verso fala da grandeza de Deus como Criador e Sustentador do universo, e Sua fidelidade em preservar a vida. O Salmo 33 também celebra a fidelidade de Deus em sustentar e preservar tudo o que Ele criou.
* Isaías 40:28: "Não sabes, não ouviste que o eterno Deus, o Senhor, o Criador dos confins da terra, não se cansa, nem se fatiga? Não se pode esquadrinhar o seu entendimento." Este verso fala da infinitude e grandeza de Deus como Criador. O Salmo 33 também celebra a grandeza e poder de Deus como Criador.
* Jeremias 17:7-8: "Bendito o homem que confia no Senhor, e cuja confiança é o Senhor. Porque ele é como a árvore plantada junto às águas, que estende as suas raízes para o ribeiro, e não receia quando vem o calor, mas a sua folha fica verde; e no ano de sequidão não se afadiga, nem deixa de dar fruto." Este verso compara a pessoa que confia em Deus a uma árvore bem enraizada e resistente. O Salmo 33 exorta o povo a confiar em Deus em vez de confiar em coisas terrenas.
* 2 Coríntios 5:7: "Porque andamos por fé e não pelo que vemos." Este verso fala da importância de confiar em Deus, mesmo quando não podemos ver claramente o que Ele está fazendo. O Salmo 33 exorta o povo a confiar em Deus em vez de confiar em coisas terrenas.
****

[[v21-33-1]]

^<<v21-33-1,1>>^ De Davi. Quando simulou alienação na presença de Abimelec e, despedido por ele, partiu.^&#42;1^

[[v21-33-2]]

^<<v21-33-2,2>>^ Bendirei continuamente o Senhor, seu louvor não deixará meus lábios.

[[v21-33-3]]

^<<v21-33-3,3>>^ Glorie-se a minha alma no Senhor; ouçam-me os humildes, e se alegrem.

[[v21-33-4]]

^<<v21-33-4,4>>^ Glorificai comigo o Senhor, juntos exaltemos o seu nome.

[[v21-33-5]]

^<<v21-33-5,5>>^ Procurei o Senhor e ele me atendeu, livrou-me de todos os temores.

[[v21-33-6]]

^<<v21-33-6,6>>^ Olhai para ele a fim de vos alegrardes, e não se cobrir de vergonha o vosso rosto.

[[v21-33-7]]

^<<v21-33-7,7>>^ Vede, este miserável clamou e o Senhor o ouviu, de todas as angústias o livrou.

[[v21-33-8]]

^<<v21-33-8,8>>^ O anjo do Senhor acampa em redor dos que o temem e os salva.

[[v21-33-9]]

^<<v21-33-9,9>>^ Provai e vede como o Senhor é bom, feliz o homem que se refugia junto dele.

[[v21-33-10]]

^<<v21-33-10,10>>^ Reverenciai o Senhor, vós, seus fiéis, porque nada falta àqueles que o temem.

[[v21-33-11]]

^<<v21-33-11,11>>^ Os poderosos empobrecem e passam fome, mas aos que buscam o Senhor nada lhes falta.

[[v21-33-12]]

^<<v21-33-12,12>>^ Vinde, meus filhos, ouvi-me: eu vos ensinarei o temor do Senhor.

[[v21-33-13]]

^<<v21-33-13,13>>^ Qual é o homem que ama a vida e deseja longos dias para gozar de felicidade?

[[v21-33-14]]

^<<v21-33-14,14>>^ Guarda tua língua do mal, e teus lábios das palavras enganosas.

[[v21-33-15]]

^<<v21-33-15,15>>^ Aparta-te do mal e faze o bem, busca a paz e vai ao seu encalço.

[[v21-33-16]]

^<<v21-33-16,16>>^ Os olhos do Senhor estão voltados para os justos, e seus ouvidos atentos aos seus clamores.

[[v21-33-17]]

^<<v21-33-17,17>>^ O Senhor volta a sua face irritada contra os que fazem o mal, para apagar da terra a lembrança deles.

[[v21-33-18]]

^<<v21-33-18,18>>^ Apenas clamaram os justos, o Senhor os atendeu e os livrou de todas as suas angústias.

[[v21-33-19]]

^<<v21-33-19,19>>^ O Senhor está perto dos contritos de coração, e salva os que têm o espírito abatido.

[[v21-33-20]]

^<<v21-33-20,20>>^ São numerosas as tribulações do justo, mas de todas o livra o Senhor.

[[v21-33-21]]

^<<v21-33-21,21>>^ Ele protege cada um de seus ossos: nem um só deles será quebrado.

[[v21-33-22]]

^<<v21-33-22,22>>^ A malícia do ímpio o leva à morte, e os que odeiam o justo serão castigados.

[[v21-33-23]]

^<<v21-33-23,23>>^ O Senhor livra a alma de seus servos; não será punido quem a ele se acolhe.

'''

xref:021-salmos/021-salmos-032.adoc#v21-32-0[&#60; Capítulo Anterior] | <<v21-33-0,Topo>> | xref:021-salmos/021-salmos-034.adoc#v21-34-0[Próximo Capítulo &#62;]