include::./index.adoc[]

[[v21-50-0]]
=== Salmos, 50
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Salmo 50 é um salmo que fala sobre a justiça divina e a necessidade de oferecer sacrifícios verdadeiros ao Senhor. O Salmo começa com a declaração de que Deus, o Senhor, convoca a terra desde o nascer ao pôr-do-sol e que Ele vem para julgar o seu povo. A seguir, são mencionados os sacrifícios que o povo oferecia a Deus, e Deus chama a atenção para o fato de que Ele não precisa desses sacrifícios, mas sim de corações sinceros e oferece perdão aos que o buscam de verdade.
* 1 Reis 8:23: "e disse: “Senhor, Deus de Israel, não há Deus como tu nos céus acima ou na terra abaixo, tu que guardas a tua aliança de amor com os teus servos que te adoram de todo o coração." Este versículo fala sobre o amor de Deus pelos que o adoram de todo o coração.
* Salmos 51:16-17: "Pois não te deleitas em sacrifícios; do contrário, eu os traria; em holocaustos não te agradas. Os sacrifícios que agradam a Deus são um espírito quebrantado; um coração quebrantado e contrito, ó Deus, não desprezarás." Esse verso se relaciona com a ideia do Salmo 50 de que Deus não precisa dos sacrifícios, mas sim de corações sinceros e arrependidos.
* Isaías 1:11: "O que me importa o grande número de seus sacrifícios?”, diz o Senhor. “Já estou farto dos holocaustos de carneiros e da gordura de novilhos gordos. Não tenho nenhum prazer no sangue de touros, de cordeiros e de bodes." Este versículo reforça a ideia de que Deus não precisa dos sacrifícios, mas sim de corações verdadeiramente dedicados a Ele.
* Oséias 6:6: "Pois eu quero amor, e não sacrifícios; conhecimento de Deus, em vez de holocaustos." Este verso se relaciona com a ideia do Salmo 50 de que o Senhor não precisa dos sacrifícios, mas sim de corações sinceros e amorosos.
* Jeremias 7:22: "Pois quando os tirei do Egito, não falei com eles nem lhes dei ordens a respeito de holocaustos e sacrifícios." Este versículo reforça a ideia de que os sacrifícios não são a essência do relacionamento com Deus, mas sim uma expressão exterior da comunhão com Ele.
****

[[v21-50-1]]

^<<v21-50-1,1>>^ Ao mestre de canto. Salmo de Davi,^&#42;1^

[[v21-50-2]]

^<<v21-50-2,2>>^ quando o profeta Natã foi encontrá-lo, após o pecado com Betsabé.

[[v21-50-3]]

^<<v21-50-3,3>>^ Tende piedade de mim, Senhor, segundo a vossa bondade. E conforme a imensidade de vossa misericórdia, apagai a minha iniquidade.

[[v21-50-4]]

^<<v21-50-4,4>>^ Lavai-me totalmente de minha falta, e purificai-me de meu pecado.

[[v21-50-5]]

^<<v21-50-5,5>>^ Eu reconheço a minha iniquidade, diante de mim está sempre o meu pecado.

[[v21-50-6]]

^<<v21-50-6,6>>^ Só contra vós pequei, o que é mau fiz diante de vós. Vossa sentença assim se manifesta justa, e reto o vosso julgamento.^&#42;1^

[[v21-50-7]]

^<<v21-50-7,7>>^ Eis que nasci na culpa, minha mãe concebeu-me no pecado.

[[v21-50-8]]

^<<v21-50-8,8>>^ Não obstante, amais a sinceridade de coração. Infundi-me, pois, a sabedoria no mais íntimo de mim.

[[v21-50-9]]

^<<v21-50-9,9>>^ Aspergi-me com um ramo de hissope e ficarei puro. Lavai-me e me tornarei mais branco do que a neve.^&#42;1^

[[v21-50-10]]

^<<v21-50-10,10>>^ Fazei-me ouvir uma palavra de gozo e de alegria, para que exultem os ossos que triturastes.

[[v21-50-11]]

^<<v21-50-11,11>>^ Dos meus pecados desviai os olhos, e minhas culpas todas apagai.

[[v21-50-12]]

^<<v21-50-12,12>>^ Ó meu Deus, criai em mim um coração puro, e renovai-me o espírito de firmeza.

[[v21-50-13]]

^<<v21-50-13,13>>^ De vossa face não me rejeiteis, e nem me priveis de vosso santo Espírito.

[[v21-50-14]]

^<<v21-50-14,14>>^ Restituí-me a alegria da salvação, e sustentai-me com uma vontade generosa.

[[v21-50-15]]

^<<v21-50-15,15>>^ Então, aos maus ensinarei vossos caminhos, e voltarão a vós os pecadores.

[[v21-50-16]]

^<<v21-50-16,16>>^ Deus, ó Deus, meu salvador, livrai-me da pena desse sangue derramado, e a vossa misericórdia a minha língua exaltará.^&#42;1^

[[v21-50-17]]

^<<v21-50-17,17>>^ Senhor, abri meus lábios, a fim de que minha boca anuncie vossos louvores.

[[v21-50-18]]

^<<v21-50-18,18>>^ Vós não vos aplacais com sacrifícios rituais; e se eu vos ofertasse um sacrifício, não o aceitaríeis.

[[v21-50-19]]

^<<v21-50-19,19>>^ Meu sacrifício, ó Senhor, é um espírito contrito, um coração arrependido e humilhado, ó Deus, que não haveis de desprezar.

[[v21-50-20]]

^<<v21-50-20,20>>^ Senhor, pela vossa bondade, tratai Sião com benevolência, reconstruí os muros de Jerusalém.^&#42;1^

[[v21-50-21]]

^<<v21-50-21,21>>^ Então, aceitareis os sacrifícios prescritos, as oferendas e os holocaustos; e sobre vosso altar vítimas vos serão oferecidas.

'''

xref:021-salmos/021-salmos-049.adoc#v21-49-0[&#60; Capítulo Anterior] | <<v21-50-0,Topo>> | xref:021-salmos/021-salmos-051.adoc#v21-51-0[Próximo Capítulo &#62;]