include::./index.adoc[]

[[v21-140-0]]
=== Salmos, 140
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Salmo 140 é um salmo de lamentação e súplica a Deus para livrar o salmista daqueles que conspiram contra ele. Os temas principais incluem a maldade dos ímpios e a proteção de Deus sobre os justos.
* Provérbios 6:12: "O homem ímpio e fraudulento anda com a boca torta," Este versículo fala sobre os ímpios e sua natureza enganosa, o que é semelhante ao que o salmista descreve em relação aos seus inimigos no Salmo 140.
* Salmo 34:17: "Os justos clamam, e o Senhor os ouve e os livra de todas as suas angústias." O salmista de Salmo 140 clama a Deus para livrá-lo de seus inimigos e protegê-lo. Este versículo fala sobre a promessa de Deus de ouvir e livrar os justos de suas aflições.
* Salmo 121:7: "O Senhor guardará você de todo mal; ele guardará a sua vida." Este versículo fala sobre a proteção de Deus sobre a vida dos justos e é semelhante à petição do salmista em Salmo 140 para que Deus o proteja dos seus inimigos.
* Provérbios 24:17: "Não se alegre quando o seu inimigo cair, nem se regozije o seu coração quando ele tropeçar." Este versículo fala sobre a importância de não se alegrar com o mal dos outros, mesmo que sejam inimigos. É uma lição importante para lembrar quando se está enfrentando inimigos, como o salmista de Salmo 140.
* 2 Timóteo 4:18: "O Senhor me livrará de toda obra maligna e me levará salvo para o seu Reino celestial. A ele seja a glória para todo o sempre! Amém." Este versículo fala sobre a confiança do apóstolo Paulo na proteção de Deus contra todas as obras malignas e sua fé no Reino celestial de Deus. É uma afirmação semelhante à confiança do salmista em Salmo 140 na proteção de Deus.
****

[[v21-140-1]]

^<<v21-140-1,1>>^ Salmo de Davi. Senhor, eu vos chamo, vinde logo em meu socorro; escutai a minha voz quando vos invoco.^&#42;1^

[[v21-140-2]]

^<<v21-140-2,2>>^ Que minha oração suba até vós como a fumaça do incenso, que minhas mãos estendidas para vós sejam como a oferenda da tarde.

[[v21-140-3]]

^<<v21-140-3,3>>^ Ponde, Senhor, uma guarda em minha boca, uma sentinela à porta de meus lábios.

[[v21-140-4]]

^<<v21-140-4,4>>^ Não deixeis meu coração inclinar-se ao mal, para impiamente cometer alguma ação criminosa. Não permitais que eu tome parte nos festins dos homens que praticam o mal.

[[v21-140-5]]

^<<v21-140-5,5>>^ Se o justo me bate é um favor, se me repreende é como perfume em minha fronte. Minha cabeça não o rejeitará; porém, sob seus golpes, apenas rezarei.

[[v21-140-6]]

^<<v21-140-6,6>>^ Seus chefes foram precipitados pelas encostas do rochedo, e ouviram quão brandas eram as minhas palavras.

[[v21-140-7]]

^<<v21-140-7,7>>^ Como a terra fendida e sulcada pelo arado, assim seus ossos se dispersam à beira da região dos mortos.

[[v21-140-8]]

^<<v21-140-8,8>>^ Pois é para vós, Senhor, que se voltam os meus olhos; eu me refugio junto de vós, não me deixeis perecer.

[[v21-140-9]]

^<<v21-140-9,9>>^ Guardai-me do laço que me armaram, e das ciladas dos que praticam o mal.

[[v21-140-10]]

^<<v21-140-10,10>>^ Caiam os ímpios, de uma vez, nas próprias malhas; quanto a mim, que eu escape são e salvo.

'''

xref:021-salmos/021-salmos-139.adoc#v21-139-0[&#60; Capítulo Anterior] | <<v21-140-0,Topo>> | xref:021-salmos/021-salmos-141.adoc#v21-141-0[Próximo Capítulo &#62;]