include::./index.adoc[]

[[v21-114-0]]
=== Salmos, 114
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 114 é um hino de louvor que destaca a grandeza e o poder de Deus em relação à natureza. O salmista faz referência à época da libertação do povo de Israel da escravidão no Egito e à travessia do Mar Vermelho. Abaixo estão cinco versículos relacionados com os temas abordados no Salmo 114:
* Êxodo 14:21: "Então Moisés estendeu a mão sobre o mar, e o Senhor afastou o mar com um forte vento leste, que soprou toda a noite; e transformou o mar em terra seca, e as águas foram divididas." Este versículo descreve o momento em que Deus dividiu as águas do Mar Vermelho para que os israelitas pudessem passar a pé enxuto.
* Salmos 93:4: "Mas o Senhor nas alturas é mais poderoso do que o estrondo das grandes águas, do que as grandes ondas do mar." Este versículo destaca o poder de Deus em relação às águas e ao mar.
* Isaías 43:2: "Quando passares pelas águas, eu serei contigo; quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti." Este versículo fala sobre a presença de Deus e sua proteção em meio às dificuldades, incluindo a travessia das águas.
* Salmos 93:3: "As torrentes levantaram, ó Senhor, as torrentes levantaram a sua voz; as torrentes levantaram as suas ondas." Este versículo destaca a força das águas e como elas podem ser temidas, mas ressalta a superioridade de Deus sobre elas.
* Isaías 51:10: "Não és tu aquele que secou o mar, as águas do grande abismo, que fez do fundo do mar um caminho para que por ele passassem os remidos?" Este versículo faz referência à ação de Deus em secar o Mar Vermelho para permitir a fuga dos israelitas e destaca seu poder e domínio sobre as águas.
****

[[v21-114-1]]

^<<v21-114-1,1>>^ Aleluia. Amo o Senhor, porque ele ouviu a voz de minha súplica,^&#42;1^

[[v21-114-2]]

^<<v21-114-2,2>>^ porque inclinou para mim os seus ouvidos no dia em que o invoquei.

[[v21-114-3]]

^<<v21-114-3,3>>^ Os laços da morte me envolviam, a rede da habitação dos mortos me apanhou de improviso; estava abismado na aflição e na ansiedade.

[[v21-114-4]]

^<<v21-114-4,4>>^ Foi então que invoquei o nome do Senhor: “Ó Senhor, salvai-me a vida!”.

[[v21-114-5]]

^<<v21-114-5,5>>^ O Senhor é bom e justo, cheio de misericórdia é nosso Deus.

[[v21-114-6]]

^<<v21-114-6,6>>^ O Senhor cuida dos corações simples; achava-me na miséria e ele me salvou.

[[v21-114-7]]

^<<v21-114-7,7>>^ Volta, minha alma, à tua serenidade, porque o Senhor foi bom para contigo,

[[v21-114-8]]

^<<v21-114-8,8>>^ pois livrou-me a alma da morte, preservou-me os olhos do pranto, os pés da queda.

[[v21-114-9]]

^<<v21-114-9,9>>^ Na presença do Senhor continuarei o meu caminho na terra dos vivos.

'''

xref:021-salmos/021-salmos-113.adoc#v21-113-0[&#60; Capítulo Anterior] | <<v21-114-0,Topo>> | xref:021-salmos/021-salmos-115.adoc#v21-115-0[Próximo Capítulo &#62;]