include::./index.adoc[]

[[v21-123-0]]
=== Salmos, 123
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 123 é um cântico de súplica que expressa a confiança do salmista em Deus e sua expectativa pela misericórdia divina. O tema central do Salmo é a dependência do povo de Deus da sua ajuda. A seguir estão cinco versículos bíblicos relacionados com os temas abordados em Salmo 123:
* Salmos 121:1-2: "Elevo os olhos para os montes: de onde me virá o socorro? O meu socorro vem do SENHOR, que fez o céu e a terra." Este versículo fala da confiança do salmista na ajuda de Deus.
* Salmos 124:8: "O nosso socorro está no nome do SENHOR, que fez o céu e a terra." Este verso destaca novamente a dependência do povo de Deus em Deus para a sua ajuda e proteção.
* Salmos 125:1: "Os que confiam no SENHOR são como o monte Sião, que não se abala, firme para sempre." Este versículo fala da confiança e segurança daqueles que confiam em Deus.
* Isaías 25:9: "E, naquele dia, se dirá: Eis que este é o nosso Deus, em quem esperávamos, e ele nos salvará; este é o SENHOR, em quem esperávamos; na sua salvação exultaremos e nos alegraremos." Este verso fala da alegria e gratidão daqueles que esperam em Deus e experimentam a sua salvação.
* Filipenses 4:6-7: "Não estejais inquietos por coisa alguma; antes, as vossas petições sejam em tudo conhecidas diante de Deus, pela oração e súplicas, com ação de graças. E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus." Este versículo fala da importância da oração e da confiança em Deus para experimentar a paz interior e a tranquilidade mesmo em meio às adversidades.
****

[[v21-123-1]]

^<<v21-123-1,1>>^ Cântico das peregrinações. De Davi. Se o Senhor não tivesse estado conosco, sim, diga-o Israel,^&#42;1^

[[v21-123-2]]

^<<v21-123-2,2>>^ se o Senhor não tivesse estado conosco, os homens que se insurgiram contra nós

[[v21-123-3]]

^<<v21-123-3,3>>^ teriam então nos devorado vivos. Quando seu furor se desencadeou contra nós,

[[v21-123-4]]

^<<v21-123-4,4>>^ as águas nos teriam submergido. Uma torrente teria passado sobre nós.

[[v21-123-5]]

^<<v21-123-5,5>>^ Então, nos teriam recoberto as ondas intumescidas.

[[v21-123-6]]

^<<v21-123-6,6>>^ Bendito seja o Senhor, que não nos entregou como presa aos seus dentes.

[[v21-123-7]]

^<<v21-123-7,7>>^ Nossa alma escapou como um pássaro, dos laços do caçador. Rompeu-se a armadilha, e nos achamos livres.

[[v21-123-8]]

^<<v21-123-8,8>>^ Nosso socorro está no nome do Senhor, criador do céu e da terra.

'''

xref:021-salmos/021-salmos-122.adoc#v21-122-0[&#60; Capítulo Anterior] | <<v21-123-0,Topo>> | xref:021-salmos/021-salmos-124.adoc#v21-124-0[Próximo Capítulo &#62;]