include::./index.adoc[]

[[v21-117-0]]
=== Salmos, 117
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 117 é o capítulo mais curto da Bíblia e é uma convocação a todas as nações e povos para louvarem ao Senhor. Os versículos abaixo foram selecionados por abordarem temas semelhantes de adoração e louvor a Deus.
* Salmo 22:27: "Todos os confins da terra se lembrarão e se voltarão para o SENHOR, e todas as famílias das nações se prostrarão diante dele." Este versículo fala sobre como todas as nações e povos adorarão ao Senhor.
* Salmo 66:4: "Toda a terra te adora e canta louvores a ti, canta louvores ao teu nome." Este versículo também se refere ao louvor universal ao Senhor.
* Salmo 86:9: "Todas as nações que fizeste virão e adorarão diante de ti, Senhor, e glorificarão o teu nome." Esse versículo mostra que Deus é adorado não apenas pelos judeus, mas também por todas as nações.
* Salmo 96:1: "Cantem ao Senhor um novo cântico; cantem ao Senhor, todos os habitantes da terra!" Este versículo incentiva todas as pessoas a cantarem novas canções de louvor a Deus.
* Salmo 117:2: "Porque grande é o seu amor por nós, e a fidelidade do Senhor dura para sempre. Aleluia!" Este versículo reforça o motivo pelo qual todos os povos e nações devem louvar ao Senhor - porque Ele é amoroso e fiel.
****

[[v21-117-1]]

^<<v21-117-1,1>>^ Aleluia. Louvai o Senhor, porque ele é bom; porque eterna é a sua misericórdia.^&#42;1^

[[v21-117-2]]

^<<v21-117-2,2>>^ Diga a casa de Israel: “Eterna é sua misericórdia”.

[[v21-117-3]]

^<<v21-117-3,3>>^ Proclame a casa de Aarão: “Eterna é sua misericórdia”.

[[v21-117-4]]

^<<v21-117-4,4>>^ E vós, que temeis o Senhor, repeti: “Eterna é a sua misericórdia”.

[[v21-117-5]]

^<<v21-117-5,5>>^ Na tribulação invoquei o Senhor; ouviu-me o Senhor e me livrou.

[[v21-117-6]]

^<<v21-117-6,6>>^ Comigo está o Senhor, nada temo; que mal me poderia ainda fazer um homem?^&#42;1^

[[v21-117-7]]

^<<v21-117-7,7>>^ Comigo está o Senhor, meu amparo; verei logo a ruína dos meus inimigos.

[[v21-117-8]]

^<<v21-117-8,8>>^ Mais vale procurar refúgio no Senhor do que confiar no homem.

[[v21-117-9]]

^<<v21-117-9,9>>^ Mais vale procurar refúgio no Senhor do que confiar nos grandes da terra.

[[v21-117-10]]

^<<v21-117-10,10>>^ Ainda que me cercassem todas as nações pagãs, eu as esmagaria em nome do Senhor.

[[v21-117-11]]

^<<v21-117-11,11>>^ Ainda que me assediassem de todos os lados, eu as esmagaria em nome do Senhor.

[[v21-117-12]]

^<<v21-117-12,12>>^ Ainda que me envolvessem como um enxame de abelhas, como um braseiro de espinhos, eu as esmagaria em nome do Senhor.

[[v21-117-13]]

^<<v21-117-13,13>>^ Forçaram-me violentamente para eu cair, mas o Senhor veio em meu auxílio.

[[v21-117-14]]

^<<v21-117-14,14>>^ O Senhor é minha força, minha coragem; ele é meu Salvador.

[[v21-117-15]]

^<<v21-117-15,15>>^ Brados de alegria e de vitória ressoam nas tendas dos justos:^&#42;1^

[[v21-117-16]]

^<<v21-117-16,16>>^ “A destra do Senhor fez prodígios, levantou-me a destra do Senhor; fez maravilhas a destra do Senhor”.

[[v21-117-17]]

^<<v21-117-17,17>>^ Não hei de morrer; viverei para narrar as obras do Senhor.

[[v21-117-18]]

^<<v21-117-18,18>>^ O Senhor castigou-me duramente, mas poupou-me à morte.

[[v21-117-19]]

^<<v21-117-19,19>>^ Abri-me as portas santas, a fim de que eu entre para agradecer ao Senhor.^&#42;1^

[[v21-117-20]]

^<<v21-117-20,20>>^ Esta é a porta do Senhor: só os justos por ela podem passar.

[[v21-117-21]]

^<<v21-117-21,21>>^ Graças vos dou porque me ouvistes, e vos fizestes meu Salvador.

[[v21-117-22]]

^<<v21-117-22,22>>^ A pedra rejeitada pelos arquitetos tornou-se a pedra angular.^&#42;1^

[[v21-117-23]]

^<<v21-117-23,23>>^ Isto foi obra do Senhor, é um prodígio aos nossos olhos.^&#42;1^

[[v21-117-24]]

^<<v21-117-24,24>>^ Este é o dia que o Senhor fez: seja para nós dia de alegria e de felicidade.

[[v21-117-25]]

^<<v21-117-25,25>>^ Senhor, dai-nos a salvação; dai-nos a prosperidade, ó Senhor!

[[v21-117-26]]

^<<v21-117-26,26>>^ Bendito seja o que vem em nome do Senhor! Da casa do Senhor nós vos bendizemos.

[[v21-117-27]]

^<<v21-117-27,27>>^ O Senhor é nosso Deus, ele fez brilhar sobre nós a sua luz. Organizai uma festa com profusão de coroas. E cheguem até os ângulos do altar.

[[v21-117-28]]

^<<v21-117-28,28>>^ Sois o meu Deus, venho agradecer-vos. Venho glorificar-vos, sois o meu Deus.

[[v21-117-29]]

^<<v21-117-29,29>>^ Dai graças ao Senhor porque ele é bom, eterna é sua misericórdia.

'''

xref:021-salmos/021-salmos-116.adoc#v21-116-0[&#60; Capítulo Anterior] | <<v21-117-0,Topo>> | xref:021-salmos/021-salmos-118.adoc#v21-118-0[Próximo Capítulo &#62;]