include::./index.adoc[]

[[v21-56-0]]
=== Salmos, 56
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 56 é um salmo de lamentação no qual o salmista clama a Deus por ajuda e proteção contra seus inimigos. Ele expressa sua confiança em Deus e pede que Ele julgue os seus inimigos. Abaixo estão cinco versículos relacionados aos temas abordados neste salmo:
* Salmos 9:9: "O Senhor é um refúgio para os oprimidos, um refúgio em tempos de dificuldade." Este verso fala da proteção de Deus para aqueles que são oprimidos e estão passando por momentos difíceis, o que é uma das principais preocupações do salmista em Salmo 56.
* Salmos 27:1: "O Senhor é minha luz e minha salvação - quem eu deveria temer? O Senhor é a fortaleza da minha vida - de quem devo ter medo?" Neste verso, o salmista fala da sua confiança em Deus como sua salvação e fortaleza, o que é uma temática constante em Salmo 56.
* Salmos 118:6: "O Senhor está comigo, não tenho medo; o que pode me fazer um ser humano?" Este verso expressa a confiança do salmista em Deus e sua segurança em saber que Ele está com ele, mesmo diante de seus inimigos.
* Salmos 140:12: "Eu sei que o Senhor defenderá os direitos dos pobres e os interesses dos necessitados." Este verso fala da confiança do salmista de que Deus defenderá os pobres e necessitados, o que se relaciona com a preocupação do salmista em Salmo 56 em ser protegido de seus inimigos.
* Salmos 146:7: "Ele defende o oprimido e dá alimento aos famintos. O Senhor liberta os prisioneiros." Neste verso, o salmista fala da justiça de Deus em defender os oprimidos e libertar os prisioneiros, o que se relaciona com a sua busca por proteção e libertação em Salmo 56.
****

[[v21-56-1]]

^<<v21-56-1,1>>^ Ao mestre de canto. “Não destruas”. Cântico de Davi, quando fugiu para a caverna, perseguido por Saul.^&#42;1^

[[v21-56-2]]

^<<v21-56-2,2>>^ Tende piedade de mim, ó Deus, tende piedade de mim, porque a minha alma em vós procura o seu refúgio. Abrigo-me à sombra de vossas asas, até que a tormenta passe.

[[v21-56-3]]

^<<v21-56-3,3>>^ Clamo ao Deus Altíssimo, ao Deus que me cumula de benefícios.

[[v21-56-4]]

^<<v21-56-4,4>>^ Mande ele do céu auxílio que me salve, cubra de confusão meus perseguidores; envie-me Deus a sua graça e fidelidade.

[[v21-56-5]]

^<<v21-56-5,5>>^ Estou no meio de leões, que devoram os homens com avidez. Seus dentes são como lanças e flechas, suas línguas como espadas afiadas.

[[v21-56-6]]

^<<v21-56-6,6>>^ Elevai-vos, ó Deus, no mais alto do céu, e sobre toda a terra brilhe a vossa glória.

[[v21-56-7]]

^<<v21-56-7,7>>^ Ante meus pés armaram rede; fizeram-me perder a coragem; cavaram uma fossa diante de mim; caiam nela eles mesmos.

[[v21-56-8]]

^<<v21-56-8,8>>^ Meu coração está firme, ó Deus, meu coração está firme; vou cantar e salmodiar.

[[v21-56-9]]

^<<v21-56-9,9>>^ Desperta-te, ó minha alma; despertai, harpa e cítara! Quero acordar a aurora.

[[v21-56-10]]

^<<v21-56-10,10>>^ Entre os povos, Senhor, vos louvarei; eu vos salmodiarei entre as nações,

[[v21-56-11]]

^<<v21-56-11,11>>^ porque aos céus se eleva a vossa misericórdia, e até as nuvens a vossa fidelidade.

[[v21-56-12]]

^<<v21-56-12,12>>^ Elevai-vos, ó Deus, nas alturas do céu, e brilhe a vossa glória sobre a terra inteira.

'''

xref:021-salmos/021-salmos-055.adoc#v21-55-0[&#60; Capítulo Anterior] | <<v21-56-0,Topo>> | xref:021-salmos/021-salmos-057.adoc#v21-57-0[Próximo Capítulo &#62;]