include::./index.adoc[]

[[v21-23-0]]
=== Salmos, 23
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O Salmo 23 é um dos mais conhecidos e amados salmos da Bíblia. Nele, o salmista Davi expressa sua confiança em Deus como o seu pastor, provedor e protetor. Ele reconhece que Deus cuida dele em todas as áreas de sua vida e que nada lhe faltará. Abaixo estão cinco versículos relacionados aos temas abordados neste salmo:
* Salmos 28:9 - "Salva o teu povo, e abençoa a tua herança; apascenta-os e exalta-os para sempre." Este versículo fala sobre Deus como pastor do Seu povo, abençoando e cuidando deles para sempre.
* Isaías 40:11 - "Como pastor ele apascentará o seu rebanho, entre os seus braços recolherá os cordeirinhos e os levará no seu regaço; as que amamentam ele guiará mansamente." Este versículo retrata Deus como um pastor amoroso que cuida gentilmente de Seu rebanho.
* João 10:11 - "Eu sou o bom Pastor. O bom Pastor dá a vida pelas ovelhas." Este versículo fala sobre Jesus como o Bom Pastor, que dá a vida por suas ovelhas.
* Hebreus 13:20-21 - "Ora, o Deus de paz, que pelo sangue da aliança eterna tornou a trazer dos mortos a nosso Senhor Jesus Cristo, grande Pastor das ovelhas, vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade, operando em vós o que perante ele é agradável, por Jesus Cristo, a quem seja glória para todo o sempre. Amém!" Este versículo descreve Jesus como o Grande Pastor das ovelhas e pede que Deus aperfeiçoe Seu povo em toda boa obra.
* Apocalipse 7:17 - "Porque o Cordeiro que está no meio do trono os apascentará e lhes servirá de guia para as fontes da água da vida; e Deus limpará de seus olhos toda lágrima." Este versículo retrata Jesus como o Cordeiro no meio do trono, que apascenta e guia Seu povo para as fontes da água da vida.
****

[[v21-23-1]]

^<<v21-23-1,1>>^ Salmo de Davi. Do Senhor é a terra e tudo o que ela contém, a órbita terrestre e todos os que nela habitam,^&#42;1^

[[v21-23-2]]

^<<v21-23-2,2>>^ pois ele mesmo a assentou sobre as águas do mar e sobre as águas dos rios a consolidou.

[[v21-23-3]]

^<<v21-23-3,3>>^ Quem será digno de subir ao monte do Senhor? Ou de permanecer no seu lugar santo?

[[v21-23-4]]

^<<v21-23-4,4>>^ O que tem as mãos limpas e o coração puro, cujo espírito não busca as vaidades nem perjura para enganar seu próximo.

[[v21-23-5]]

^<<v21-23-5,5>>^ Este terá a bênção do Senhor, e a recompensa de Deus, seu Salvador.

[[v21-23-6]]

^<<v21-23-6,6>>^ Tal é a geração dos que o procuram, dos que buscam a face do Deus de Jacó.

[[v21-23-7]]

^<<v21-23-7,7>>^ Levantai, ó portas, os vossos dintéis! Levantai-vos, ó pórticos antigos, para que entre o rei da glória!

[[v21-23-8]]

^<<v21-23-8,8>>^ “Quem é este rei da glória?” É o Senhor forte e poderoso, o Senhor poderoso na batalha.

[[v21-23-9]]

^<<v21-23-9,9>>^ Levantai, ó portas, os vossos dintéis! Levantai-vos, ó pórticos antigos, para que entre o rei da glória!

[[v21-23-10]]

^<<v21-23-10,10>>^ “Quem é este rei da glória?” É o Senhor dos exércitos! É ele o rei da glória.^&#42;1^

'''

xref:021-salmos/021-salmos-022.adoc#v21-22-0[&#60; Capítulo Anterior] | <<v21-23-0,Topo>> | xref:021-salmos/021-salmos-024.adoc#v21-24-0[Próximo Capítulo &#62;]