include::./index.adoc[]

[[v10-15-0]]
=== II Samuel, 15
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Samuel 15 fala sobre a conspiração de Absalão para se tornar rei em lugar de Davi. Ele engana o povo, obtém seguidores e conquista o coração de muitos israelitas. Davi, ao tomar conhecimento da conspiração, foge de Jerusalém com sua família e seus seguidores. A seguir, são apresentados cinco versículos relacionados com os temas abordados em 2 Samuel 15:
* Salmos 3:1-2: "Ó Senhor, como se têm multiplicado os meus adversários! São muitos os que se levantam contra mim. Muitos dizem da minha alma: Não há salvação para ele em Deus." Este salmo, escrito por Davi, expressa sua angústia diante da conspiração de Absalão e da ameaça que ele representa ao seu reinado.
* Salmos 41:9: "Até o meu amigo íntimo, em quem eu confiava, que comia do meu pão, levantou contra mim o seu calcanhar." Davi lamenta a traição de Aitofel, um dos seus conselheiros, que passou para o lado de Absalão e conspirou contra ele.
* Salmos 55:12-14: "Porque não era um inimigo que me afrontava; então eu o teria suportado; nem era o que me odiava que se engrandecia contra mim, porque dele me teria escondido; mas eras tu, homem meu igual, meu guia e meu íntimo amigo. Consultávamos juntos suavemente, e andávamos na casa de Deus como companheiros." Davi se refere a Aitofel, seu antigo conselheiro e amigo, que se uniu à conspiração de Absalão e traiu a sua confiança.
* Salmos 59:1-3: "Livra-me, meu Deus, dos meus inimigos; defende-me daqueles que se levantam contra mim. Livra-me dos que praticam a iniquidade, e salva-me dos homens sanguinários. Pois eis que põem ciladas à minha alma; os fortes se ajuntam contra mim, não por transgressão minha ou por pecado meu, ó Senhor." Davi clama a Deus por proteção diante da ameaça representada por Absalão e seus seguidores.
* Salmos 63:1: "Ó Deus, tu és o meu Deus; cedo te buscarei; a minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água." Este salmo expressa a devoção de Davi a Deus, mesmo diante das dificuldades enfrentadas na fuga de Absalão.
****

[[v10-15-1]]

^<<v10-15-1,1>>^ Depois disso, Absalão adquiriu para si um carro, cavalos e cinquenta homens para o escoltarem.

[[v10-15-2]]

^<<v10-15-2,2>>^ Colocava-se desde cedo à beira do caminho, junto à grande porta e interpelava todos os que vinham procurar o rei para um julgamento, dizendo: “De que cidade és tu?”. O outro respondia: “Teu servo é de tal tribo de Israel”.

[[v10-15-3]]

^<<v10-15-3,3>>^ “Vê – dizia-lhe Absalão –; a tua causa é boa e justa; mas não há ninguém para te ouvir da parte do rei.”

[[v10-15-4]]

^<<v10-15-4,4>>^ E Absalão ajuntava: “Oh! Quem me dera ser juiz desta terra! Todo o que tivesse um processo ou uma questão e viesse ter comigo, eu lhe faria justiça”.

[[v10-15-5]]

^<<v10-15-5,5>>^ E se alguém se aproximava para se prostrar diante dele, estendia a mão, detinha-o e beijava-o.

[[v10-15-6]]

^<<v10-15-6,6>>^ Assim fazia Absalão com todos os israelitas que vinham procurar o rei para qualquer julgamento. E desse modo conquistou os corações dos israelitas.

[[v10-15-7]]

^<<v10-15-7,7>>^ Quatro anos se passaram. Absalão disse ao rei: “Deixa-me ir a Hebron para cumprir ali uma promessa que fiz ao Senhor.

[[v10-15-8]]

^<<v10-15-8,8>>^ Quando o teu servo estava em Gessur, fez este voto: Se o Senhor me reconduzir a Jerusalém, irei prestar-lhe culto em Hebron”.

[[v10-15-9]]

^<<v10-15-9,9>>^ “Vai em paz” – disse-lhe o rei. E ele foi para Hebron.

[[v10-15-10]]

^<<v10-15-10,10>>^ Absalão enviou emissários secretos a todas as tribos de Israel com esta mensagem: “Quando ouvirdes o som da trombeta, dizei: Absalão é rei em Hebron!”.

[[v10-15-11]]

^<<v10-15-11,11>>^ Ora, tinham partido de Jerusalém com Absalão duzentos homens, convidados por ele, que o seguiam com simplicidade de coração sem de nada suspeitar.

[[v10-15-12]]

^<<v10-15-12,12>>^ Enquanto oferecia os sacrifícios, Absalão mandou chamar também Aquitofel, gilonita, conselheiro de Davi, à sua cidade de Gilo. E assim a conjuração se fortificava e se tornava cada vez mais numerosa em torno de Absalão.

[[v10-15-13]]

^<<v10-15-13,13>>^ Vieram então anunciar a Davi: “Os israelitas aderem a Absalão!”.

[[v10-15-14]]

^<<v10-15-14,14>>^ Davi disse então a todos os que estavam com ele em Jerusalém: “Vamos, fujamos, porque não podemos de outro modo escapar a Absalão! Apressai-vos e parti, não suceda que ele nos surpreenda de repente e nos inflija a ruína, passando a cidade a fio de espada”.

[[v10-15-15]]

^<<v10-15-15,15>>^ Os servos do rei disseram-lhe: “Faça-se como ordenar o rei, meu senhor; somos teus servos”.

[[v10-15-16]]

^<<v10-15-16,16>>^ O rei partiu a pé com toda a sua família, mas deixou dez concubinas para guardar o palácio.

[[v10-15-17]]

^<<v10-15-17,17>>^ O rei saiu, pois, a pé com todos os seus servos e se detiveram na última casa.

[[v10-15-18]]

^<<v10-15-18,18>>^ Todo o seu exército desfilava ao seu lado; os cereteus, os feleteus e todos os geteus, em número de seiscentos homens que o tinham seguido desde Gat, todos marchavam diante do rei.

[[v10-15-19]]

^<<v10-15-19,19>>^ O rei disse a Etai, o geteu: “Por que vens também tu conosco? Volta e fica com o novo rei, pois és um estrangeiro e mesmo um exilado de tua terra.

[[v10-15-20]]

^<<v10-15-20,20>>^ Chegaste ontem e hoje vou fazer que andes errante conosco, não sabendo eu mesmo aonde vou? Volta. Toma os teus contigo e que o Senhor seja misericordioso e fiel para contigo”.

[[v10-15-21]]

^<<v10-15-21,21>>^ Mas Etai respondeu ao rei: “Pela vida do Senhor e pela vida do rei, meu senhor! Onde estiver o meu senhor e rei, lá estará também o teu servo, tanto para a morte como para a vida”.

[[v10-15-22]]

^<<v10-15-22,22>>^ “Está bem – disse Davi –, passa.” E Etai, o geteu, desfilou com todos os seus homens e com toda a sua comitiva.

[[v10-15-23]]

^<<v10-15-23,23>>^ E, estando o rei junto do Cedron, enquanto desfilava o povo diante dele, tomando o caminho da oliveira do deserto, toda a terra chorava em alta voz.

[[v10-15-24]]

^<<v10-15-24,24>>^ Veio também Sadoc com todos os seus levitas, trazendo a arca da aliança de Deus. Depuseram-na, enquanto Abiatar subia e até que tivesse passado todo o povo que tinha saído da cidade.

[[v10-15-25]]

^<<v10-15-25,25>>^ Disse então o rei a Sadoc: “Reconduz a arca de Deus à cidade. Se eu achar graça aos olhos do Senhor, ele me reconduzirá e me fará revê-la, bem como o lugar de sua habitação.

[[v10-15-26]]

^<<v10-15-26,26>>^ Mas se disser que não quer mais saber de mim, eis-me aqui; faça de mim o que lhe aprouver”.

[[v10-15-27]]

^<<v10-15-27,27>>^ O rei disse ainda a Sadoc: “Vede? Tu e Abiatar, voltai em paz para a cidade com Aquimaás, teu filho, e Jônatas, filho de Abiatar.

[[v10-15-28]]

^<<v10-15-28,28>>^ Eu vou arrastar-me pelas campinas do deserto, esperando que me mandeis notícias”.

[[v10-15-29]]

^<<v10-15-29,29>>^ Sadoc e Abiatar reconduziram, pois, a arca de Deus para Jerusalém e lá ficaram.

[[v10-15-30]]

^<<v10-15-30,30>>^ Davi subiu chorando o monte das Oliveiras, cabeça coberta e descalço. Todo o povo que o acompanhava subia também chorando, com a cabeça coberta.

[[v10-15-31]]

^<<v10-15-31,31>>^ Foi anunciado a Davi que Aquitofel estava também entre os conjurados de Absalão. Davi disse: “Fazei que se frustrem, ó Senhor, meu Deus, os desígnios de Aquitofel!”.

[[v10-15-32]]

^<<v10-15-32,32>>^ Ora, chegando Davi ao cume do monte, no lugar onde se adorava Deus, veio-lhe ao encontro Cusai, o araquita, com a túnica em farrapos e a cabeça coberta de pó.^&#42;1^

[[v10-15-33]]

^<<v10-15-33,33>>^ Davi disse-lhe: “Se vieres comigo, serás um peso para mim;

[[v10-15-34]]

^<<v10-15-34,34>>^ mas se voltares à cidade e disseres a Absalão: ‘Eu quero ser, ó rei, teu servo, como fui outrora servo de teu pai; doravante sirvo a ti’ – então desconcertarás a meu favor o desígnio de Aquitofel.

[[v10-15-35]]

^<<v10-15-35,35>>^ Terás lá contigo os sacerdotes Sadoc e Abiatar, a quem comunicarás tudo o que souberes no palácio real.

[[v10-15-36]]

^<<v10-15-36,36>>^ Com eles estão os seus dois filhos, Aquimaás, filho de Sadoc, e Jônatas, filho de Abiatar; por eles me transmitireis tudo o que ouvirdes”.

[[v10-15-37]]

^<<v10-15-37,37>>^ E Cusai, amigo de Davi, voltou para a cidade, no momento em que Absalão fazia a sua entrada em Jerusalém.

'''

xref:010-ii-samuel/010-ii-samuel-014.adoc#v10-14-0[&#60; Capítulo Anterior] | <<v10-15-0,Topo>> | xref:010-ii-samuel/010-ii-samuel-016.adoc#v10-16-0[Próximo Capítulo &#62;]