include::./index.adoc[]

[[v10-17-0]]
=== II Samuel, 17
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Samuel 17 descreve o plano de Aitofel para atacar Davi e seus seguidores enquanto estão em fuga. No entanto, o conselho de Husai, que se juntou a Davi, prevalece e o plano de Aitofel é frustrado. Em seguida, Davi e seus seguidores atravessam o rio Jordão e se preparam para enfrentar Absalão e seus seguidores. A seguir, são apresentados cinco versículos relacionados com os temas abordados em 2 Samuel 17:
* Salmos 3:6: "Não temerei dez milhares de pessoas que se puseram contra mim e me cercam." Este salmo, escrito por Davi, expressa sua confiança em Deus diante da ameaça representada por Absalão e seus seguidores, mesmo que sejam muitos.
* Salmos 27:1: "O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a fortaleza da minha vida; a quem temerei?" Davi reconhece a proteção e a ajuda de Deus em meio à adversidade e à conspiração de Absalão.
* Salmos 41:11: "Por isto conheço que tu te agradas de mim, que o meu inimigo não triunfa de mim." Davi se alegra na certeza de que Deus está do seu lado e não permitirá que seus inimigos triunfem sobre ele.
* Salmos 55:22: "Lança o teu cuidado sobre o Senhor, e ele te susterá; nunca permitirá que o justo seja abalado." Davi encoraja seus seguidores a confiarem em Deus e a lançarem suas preocupações sobre ele, confiantes de que ele os sustentará.
* Salmos 62:1-2: "Somente em Deus espera silenciosa a minha alma; dele vem a minha salvação. Só ele é a minha rocha e a minha salvação; é a minha defesa; não serei grandemente abalado." Este salmo expressa a confiança de Davi em Deus como sua salvação e proteção em meio à adversidade e aos ataques de seus inimigos.
****

[[v10-17-1]]

^<<v10-17-1,1>>^ Aquitofel disse a Absalão: “Dei-xa-me escolher doze mil homens e irei ainda esta noite perseguir Davi.

[[v10-17-2]]

^<<v10-17-2,2>>^ Vou atacá-lo no momento em que estiver extenuado de fadiga. Provocarei pânico e todos os que estão com ele fugirão. O rei ficará sozinho e então o ferirei.

[[v10-17-3]]

^<<v10-17-3,3>>^ Em seguida te reconduzirei todo o povo, assim como a esposa volta para o seu esposo. É só a um homem que procuras e todo o povo estará em paz”.^&#42;1^

[[v10-17-4]]

^<<v10-17-4,4>>^ Esse conselho agradou a Absalão e a todos os anciãos de Israel.

[[v10-17-5]]

^<<v10-17-5,5>>^ No entanto, Absalão disse: “Chamai Cusai, o araquita, e ouçamos também o que ele tem a nos dizer”.

[[v10-17-6]]

^<<v10-17-6,6>>^ Chegando Cusai, Absalão disse-lhe: “Eis o que propôs Aquitofel. Faremos o que ele disse? Se não, fala por tua vez!”.

[[v10-17-7]]

^<<v10-17-7,7>>^ “Desta vez – respondeu Cusai –, o conselho de Aquitofel não é bom.

[[v10-17-8]]

^<<v10-17-8,8>>^ Tu sabes – ajuntou ele – que teu pai e seus homens são valentes e estão furiosos como a ursa a quem roubaram a cria na estepe. Teu pai é um guerreiro e ele não permitirá que a tropa repouse de noite.

[[v10-17-9]]

^<<v10-17-9,9>>^ Ele deve estar agora escondido em alguma gruta ou em qualquer outro lugar. E se vierem a cair desde o começo alguns do nosso exército, isso será publicado e se dirá: houve uma derrota no partido de Absalão.

[[v10-17-10]]

^<<v10-17-10,10>>^ Então, mesmo o mais valente desanimaria, ainda que tivesse um coração de leão, pois todo o Israel sabe que o teu pai é um herói e que está acompanhado de homens valentes.

[[v10-17-11]]

^<<v10-17-11,11>>^ Eis o meu conselho: Que se mobilize todo o Israel, desde Dã até Bersabeia e se reúnam junto de ti tão numerosos como os grãos de areia na praia do mar, indo tu mesmo no meio deles.

[[v10-17-12]]

^<<v10-17-12,12>>^ Nós cairemos sobre ele em qualquer lugar onde esteja, caindo contra ele como o orvalho cai sobre a terra e não deixaremos vivos nem ele nem homem algum dos que estão com ele.

[[v10-17-13]]

^<<v10-17-13,13>>^ Se se refugiar nalguma cidade, todo o Israel trará cordas a essa cidade e a arrastaremos até a torrente, de maneira que não fique dela uma só pedra!”

[[v10-17-14]]

^<<v10-17-14,14>>^ Absalão e todos os israelitas acharam o conselho de Cusai melhor que o de Aquitofel. O Senhor decidira frustrar o bom conselho de Aquitofel, a fim de trazer a desgraça sobre Absalão.

[[v10-17-15]]

^<<v10-17-15,15>>^ Cusai disse aos sacerdotes Sadoc e Abiatar: “Aquitofel aconselhou a Absalão e aos anciãos de Israel desse e desse modo; eu, porém, aconselhei-o assim e assim.

[[v10-17-16]]

^<<v10-17-16,16>>^ Mandai, pois, imediatamente a Davi esta mensagem: ‘Não fiques esta noite nas planícies do deserto, mas atravessa-o sem demora, não suceda que sejam exterminados o rei e todo o povo que está com ele’.”

[[v10-17-17]]

^<<v10-17-17,17>>^ Jônatas e Aquimaás estavam em En-Roguel; uma criada foi dar-lhes as notícias, que eles mesmos levariam ao rei Davi, porque não deviam ser vistos entrando na cidade.

[[v10-17-18]]

^<<v10-17-18,18>>^ Mas um jovem os viu e avisou Absalão. Eles, porém, partiram apressados e entraram na casa de um homem em Baurim. Havia uma cisterna no pátio, onde se esconderam

[[v10-17-19]]

^<<v10-17-19,19>>^ e a mulher colocou uma tampa sobre a cisterna, espalhando por cima grãos socados, de sorte que não se notava coisa alguma.

[[v10-17-20]]

^<<v10-17-20,20>>^ Os enviados de Absalão entraram na casa dessa mulher e disseram: “Onde estão Aquimaás e Jônatas?”. Ela respondeu: “Atravessaram o regato”. Puseram-se a procurar, mas não encontrando ninguém, voltaram para Jerusalém.

[[v10-17-21]]

^<<v10-17-21,21>>^ Depois que partiram, saíram os jovens da cisterna e foram levar a notícia ao rei Davi, dizendo: “Ide! Passai depressa as águas, porque Aquitofel deu o seguinte conselho contra vós”.

[[v10-17-22]]

^<<v10-17-22,22>>^ Davi partiu com todos os seus homens e passaram o Jordão. Ao amanhecer, não havia um só homem que não tivesse atravessado o rio.

[[v10-17-23]]

^<<v10-17-23,23>>^ Aquitofel, vendo que seu conselho não fora seguido, selou o seu jumento e tomou o caminho de sua casa, na sua cidade. Pôs em ordem os seus negócios e se enforcou. Morto, foi enterrado no túmulo de seu pai.^&#42;1^

[[v10-17-24]]

^<<v10-17-24,24>>^ Davi chegou a Maanaim, quando Absalão passou o Jordão com os israelitas.

[[v10-17-25]]

^<<v10-17-25,25>>^ Absalão pusera Amasa à frente do exército em lugar de Joab. Esse Amasa era filho de um tal Jetra, ismaelita, que se unira a Abigail, filha de Naás, irmã de Sárvia, mãe de Joab.

[[v10-17-26]]

^<<v10-17-26,26>>^ Os israelitas e Absalão acamparam na terra de Galaad.

[[v10-17-27]]

^<<v10-17-27,27>>^ Quando Davi chegou a Maanaim, Sobi, filho de Naás, de Rabá dos amonitas, Maquir, filho de Amiel de Lo-Dabar, e Berzelai, o galaadita, de Rogelim,

[[v10-17-28]]

^<<v10-17-28,28>>^ vieram trazer-lhe camas, tapetes, copos e vasilhas, bem como trigo, cevada, farinha, grão torrado, favas, lentilhas,

[[v10-17-29]]

^<<v10-17-29,29>>^ mel, manteiga, ovelhas e queijos de leite de vaca. Trouxeram tudo isso a Davi e às suas tropas, para que se alimentassem, dizendo: “Estes homens sofreram certamente fome, fadiga e sede no deserto”.

'''

xref:010-ii-samuel/010-ii-samuel-016.adoc#v10-16-0[&#60; Capítulo Anterior] | <<v10-17-0,Topo>> | xref:010-ii-samuel/010-ii-samuel-018.adoc#v10-18-0[Próximo Capítulo &#62;]