include::./index.adoc[]

[[v10-19-0]]
=== II Samuel, 19
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Samuel 19 descreve a restauração de Davi como rei de Israel após a morte de Absalão. O capítulo começa com a dor e o luto de Davi pela morte de seu filho e, em seguida, apresenta a reunião de Davi com seus seguidores e líderes de Israel. A seguir, são apresentados cinco versículos relacionados com os temas abordados em 2 Samuel 19:
* Salmos 30:5: "Porque a sua ira dura só um momento; no seu favor está a vida. O choro pode durar uma noite, mas a alegria vem pela manhã." Este salmo expressa a confiança de Davi na restauração da alegria e na renovação da vida depois de um período de tristeza e dor.
* Salmos 51:12: "Restitui-me a alegria da tua salvação, e sustém-me com um espírito voluntário." Davi pede a Deus que o restaure e o renove em seu espírito depois de seu pecado com Bate-Seba e a morte de Urias.
* Salmos 85:6: "Não restaurarás tu, ó Deus, a nossa vida? Não reavivarás tu o teu povo?" Davi ora a Deus para que restaure a vida de Israel e reviva seu povo após a crise causada pela rebelião de Absalão.
* Salmos 103:8: "O Senhor é misericordioso e compassivo, paciente e abundante em amor." Este salmo expressa a bondade e a misericórdia de Deus, que perdoa e restaura aqueles que se voltam para ele.
* Salmos 126:5: "Os que semeiam em lágrimas segarão com alegria." Este salmo expressa a esperança de que Deus restaure a alegria e a colheita daqueles que passaram por um período de tristeza e dor.
****

[[v10-19-1]]

^<<v10-19-1,1>>^ Então, o rei comoveu-se, subiu ao quarto que estava por cima da porta e pôs-se a chorar. E enquanto ia, dizia assim: “Meu filho Absalão, meu filho, meu filho Absalão! Por que não morri em teu lugar? Absalão, meu filho, meu filho!”.

[[v10-19-2]]

^<<v10-19-2,2>>^ E foram dizer a Joab: “Eis que o rei chora e se lamenta por causa de Absalão”.

[[v10-19-3]]

^<<v10-19-3,3>>^ E a vitória se transformou em luto naquele dia para todo o exército, porque o povo ouvira dizer que o rei estava acabrunhado de dor por causa de seu filho.

[[v10-19-4]]

^<<v10-19-4,4>>^ Por isso, o exército entrou silenciosamente na cidade e, como faria um exército coberto de vergonha por ter fugido ao combate.

[[v10-19-5]]

^<<v10-19-5,5>>^ Entretanto o rei, cobrindo a cabeça, dizia em alta voz: “Meu filho Absalão! Absalão, meu filho, meu filho!”.

[[v10-19-6]]

^<<v10-19-6,6>>^ Veio então Joab à casa do rei e disse-lhe: “Tu cobres hoje de confusão a face de todos os teus servos que salvaram a tua vida, a vida de teus filhos e filhas, de tuas mulheres e concubinas.

[[v10-19-7]]

^<<v10-19-7,7>>^ Tu amas os que te odeiam e odeias os que te amam e mostras que os teus chefes e teus servos nada valem para ti. Estou vendo que te darias por satisfeito, se Absalão vivesse e nós fôssemos todos mortos!

[[v10-19-8]]

^<<v10-19-8,8>>^ Vamos! Sai e dirige aos teus servos palavras de reconforto, pois juro-te por Deus que, se não o fizeres, não ficará contigo esta noite homem algum. E isso seria para ti uma desgraça maior do que todas que vieram sobre ti desde a tua juventude!”.

[[v10-19-9]]

^<<v10-19-9,9>>^ Então levantou-se o rei e foi sentar-se à porta. Foi avisado a todo o exército: “Eis que o rei está sentado à porta”. E todo o exército veio apresentar-se a ele. Os israelitas tinham fugido cada qual para a sua casa.

[[v10-19-10]]

^<<v10-19-10,10>>^ Em todas as tribos se discutia, dizendo: “O rei que nos salvara das mãos de nossos inimigos e da mão dos filisteus, agora teve de fugir da terra diante de Absalão.

[[v10-19-11]]

^<<v10-19-11,11>>^ Ora, Absalão, a quem tínhamos sagrado rei sobre nós, morreu no combate. Por que tardais em fazer voltar o rei?”.^&#42;1^

[[v10-19-12]]

^<<v10-19-12,12>>^ E chegou aos ouvidos do rei o que se dizia em todo o Israel. O rei Davi mandou aos sacerdotes Sadoc e Abiatar a seguinte mensagem: “Eis o que direis aos anciãos de Judá: ‘Por que seríeis vós os últimos a reconduzir o rei para a sua casa?

[[v10-19-13]]

^<<v10-19-13,13>>^ Vós sois meus irmãos, meus ossos e minha carne. Por que seríeis vós os últimos a reconduzir o rei?’.^&#42;1^

[[v10-19-14]]

^<<v10-19-14,14>>^ Direis em seguida a Amasa: ‘Tu és meu osso e minha carne. Que Deus me trate com todo o rigor, se eu não te tornar para sempre o meu general em lugar de Joab’.”

[[v10-19-15]]

^<<v10-19-15,15>>^ Todos os homens de Judá sentiram unanimemente o seu coração voltar-se para o rei e mandaram-lhe dizer: “Volta com todos os teus!”.

[[v10-19-16]]

^<<v10-19-16,16>>^ O rei voltou. Chegando ao Jordão, eis que todo o Judá tinha acorrido a Gálgala para ir-lhe ao encontro e fazê-lo passar o Jordão.

[[v10-19-17]]

^<<v10-19-17,17>>^ Semei, filho de Gera, o benjaminita de Baurim, com seus quinze filhos e os vinte servos, apressou-se a vir ao encontro do rei Davi.

[[v10-19-18]]

^<<v10-19-18,18>>^ Levava consigo mil homens de Benjamim, assim como Siba, servo da família de Saul, com seus quinze filhos e vinte servos. E correram rumo ao Jordão antes do rei,^&#42;1^

[[v10-19-19]]

^<<v10-19-19,19>>^ e dispuseram tudo para fazer passar a família do rei e prestar-lhe todos os serviços que desejassem. Semei, filho de Gera, atirou-se aos pés do rei no momento em que ele ia passar o Jordão

[[v10-19-20]]

^<<v10-19-20,20>>^ e disse-lhe: “Que o meu senhor não me impute culpa, nem guarde em seu coração a lembrança do crime que cometeu o teu servo no dia em que o rei, meu senhor, deixou Jerusalém.

[[v10-19-21]]

^<<v10-19-21,21>>^ Teu servo reconhece o seu pecado. Por isso vim hoje, o primeiro de toda a casa de José, ao encontro do rei, meu senhor!”.

[[v10-19-22]]

^<<v10-19-22,22>>^ Abisaí, filho de Sárvia, tomou a palavra: “Não se deverá antes matar Semei, por ter amaldiçoado o ungido do Senhor?”.

[[v10-19-23]]

^<<v10-19-23,23>>^ “Que eu tenho convosco, ó filhos de Sárvia – respondeu Davi –; para que vos comporteis no dia de hoje como meus inimigos? Porventura um só israelita há de ser morto num dia como o de hoje? Ignoro acaso que sou agora rei de Israel?”

[[v10-19-24]]

^<<v10-19-24,24>>^ E disse a Semei: “Não morrerás!”. E prometeu isso com juramento.^&#42;1^

[[v10-19-25]]

^<<v10-19-25,25>>^ Mifiboset, filho de Saul, desceu também ao encontro do rei. Não tinha lavado os pés nem as mãos, nem feito a barba, nem lavado as suas vestes, desde o dia em que o rei partira até o dia em que ele voltou em paz.

[[v10-19-26]]

^<<v10-19-26,26>>^ Quando, pois, chegou de Jerusalém vindo ao encontro do rei, Davi disse-lhe: “Por que não partiste comigo, Mifiboset?”.

[[v10-19-27]]

^<<v10-19-27,27>>^ “Meu senhor e rei – respondeu ele –, o meu criado enganou-me. Pois eu, teu servo, dissera-lhe que me selasse a jumenta para que eu a montasse e partisse com o rei, porque o teu servo é paralítico.

[[v10-19-28]]

^<<v10-19-28,28>>^ Ele, porém, caluniou-me junto do rei, meu senhor. Mas o rei, meu senhor, é como um anjo de Deus. Faze o que te parecer bom.

[[v10-19-29]]

^<<v10-19-29,29>>^ Toda a família de meu pai merecia a morte, diante do meu senhor e rei e, no entanto, admitiste o teu servo entre os que comem à tua mesa. Com que direito posso eu ainda suplicar ao rei?”^&#42;1^

[[v10-19-30]]

^<<v10-19-30,30>>^ “Para que tantas palavras?” – respondeu o rei –. “Eu declaro que tu e Siba repartireis os bens.”

[[v10-19-31]]

^<<v10-19-31,31>>^ “Ele pode até mesmo ficar com tudo – replicou Mifiboset –, uma vez que o rei, meu senhor, voltou em paz para a sua casa.”

[[v10-19-32]]

^<<v10-19-32,32>>^ Berzelai, o galaadita, desceu de Rogelim e acompanhou o rei, escoltando-o até o Jordão.

[[v10-19-33]]

^<<v10-19-33,33>>^ Era já muito velho, com oitenta anos. Sendo muito rico, abastecera o rei durante todo o tempo que esteve em Maanaim.

[[v10-19-34]]

^<<v10-19-34,34>>^ O rei disse-lhe: “Vem comigo e te sustentarei junto de mim em Jerusalém!”.

[[v10-19-35]]

^<<v10-19-35,35>>^ Mas Berzelai disse ao rei: “Quantos anos viverei ainda, para que suba com o rei a Jerusalém?

[[v10-19-36]]

^<<v10-19-36,36>>^ Tenho agora oitenta anos e já não distingo entre o bom e o que não o é. Já não posso saborear o que como e o que bebo e não ouço mais a voz dos cantores e cantoras. Por que iria o teu servo servir de peso ao rei, meu senhor?

[[v10-19-37]]

^<<v10-19-37,37>>^ Teu servo só andou um pedaço de caminho com o rei e por que lhe haveria o rei de dar semelhante recompensa?^&#42;1^

[[v10-19-38]]

^<<v10-19-38,38>>^ Deixa que teu servo volte, para morrer em minha cidade, junto ao túmulo de meu pai e de minha mãe. Eis, porém, o teu servo Camaam; ele irá com o rei, meu senhor. Faze dele o que te parecer melhor”.

[[v10-19-39]]

^<<v10-19-39,39>>^ “Que ele venha comigo” – respondeu o rei –. “Farei por ele tudo o que te agradar; e a ti também te concederei tudo o que desejares de mim.”

[[v10-19-40]]

^<<v10-19-40,40>>^ Todos passaram o Jordão diante do rei que permaneceu de pé. Davi beijou Berzelai e o abençoou, e Berzelai voltou para a sua casa.

[[v10-19-41]]

^<<v10-19-41,41>>^ O rei chegou a Gálgala e Camaa passou com ele. Todo o povo de Judá e a metade do povo de Israel acompanharam o rei.

[[v10-19-42]]

^<<v10-19-42,42>>^ E eis que todos os homens de Israel vieram ter com o rei, dizendo-lhe: “Por que te tomaram os nossos irmãos, os filhos de Judá, fazendo-te passar o Jordão com toda a tua família, quando são todos os homens de Davi que formam o teu povo?”.

[[v10-19-43]]

^<<v10-19-43,43>>^ Então responderam os filhos de Judá aos israelitas: “É que o rei nos é mais próximo. Por que vos irritais com isso? Acaso temos comido algo do rei ou tirado para nós algum proveito?”.^&#42;1^

[[v10-19-44]]

^<<v10-19-44,44>>^ Mas os homens de Israel responderam aos de Judá: “Temos dez partes no rei, além disso somos vossos irmãos mais velhos. Por que nos desprezastes? Não fomos nós os primeiros a tomar a palavra e a mandar chamar o nosso rei?”. Os homens de Judá falaram mais duramente ainda que os de Israel.

'''

xref:010-ii-samuel/010-ii-samuel-018.adoc#v10-18-0[&#60; Capítulo Anterior] | <<v10-19-0,Topo>> | xref:010-ii-samuel/010-ii-samuel-020.adoc#v10-20-0[Próximo Capítulo &#62;]