include::./index.adoc[]

[[v10-11-0]]
=== II Samuel, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 11 do livro de 2 Samuel relata a queda do rei Davi, que pecou ao se envolver com Bate-Seba, esposa de Urias, um dos seus soldados. O capítulo também conta como Davi tentou encobrir o seu pecado, mandando Urias para a linha de frente da batalha, onde ele foi morto. Abaixo estão cinco versículos relacionados com os temas abordados em 2 Samuel 11:
* 2 Samuel 12:7-9: "Então, disse Natã a Davi: Tu és o homem! Assim diz o Senhor, Deus de Israel: Eu te ungi rei sobre Israel e te livrei das mãos de Saul; dei-te a casa do teu senhor e as mulheres do teu senhor em teus braços e ainda te dei a casa de Israel e de Judá; e, se isso é pouco, deveria acrescentar-te tais e tais coisas?" O profeta Natã confronta Davi sobre o seu pecado e o repreende por ter quebrado a aliança com Deus.
* 2 Samuel 12:13: "Então, disse Davi a Natã: Pequei contra o Senhor. E disse Natã a Davi: Também o Senhor perdoou o teu pecado; não morrerás." Davi reconhece o seu erro e pede perdão a Deus.
* 2 Samuel 12:14: "Todavia, porquanto com este feito deste lugar a que os inimigos do Senhor blasfemem, também o filho que te nasceu certamente morrerá." Mesmo perdoado, Davi ainda sofre as consequências do seu pecado.
* 2 Samuel 12:24-25: "E consolou Bate-Seba, mulher de Urias, pelo marido e tomou-a por sua mulher; ela lhe deu um filho, porém o Senhor não o permitiu viver. E deu-lhe um nome: Salomão. E o Senhor o amou." Davi casa com Bate-Seba e o filho deles, Salomão, se torna o futuro rei de Israel.
* 2 Samuel 12:26-27: "Joabe pelejou contra Rabá dos filhos de Amom e tomou a cidade real. Então, Joabe enviou mensageiros a Davi, dizendo: Pelejei contra Rabá e tomei as águas da cidade." O capítulo termina com Joabe vencendo a batalha contra Rabá, uma vitória que Davi provavelmente teria liderado se não tivesse pecado.
****

[[v10-11-1]]

^<<v10-11-1,1>>^ No ano seguinte, na época em que os reis saíam para a guerra, Davi enviou Joab com seus suboficiais e todo o Israel. Eles devastaram a terra dos amonitas e sitiaram Rabá. Davi ficou em Jerusalém.

[[v10-11-2]]

^<<v10-11-2,2>>^ Uma tarde, Davi, levantando-se da cama, passeava pelo terraço de seu palácio. Do alto do terraço avistou uma mulher que se banhava e que era muito formosa.^&#42;1^

[[v10-11-3]]

^<<v10-11-3,3>>^ Informando-se Davi a respeito dela, disseram-lhe: “É Betsabeia, filha de Elião, mulher de Urias, o hiteu”.

[[v10-11-4]]

^<<v10-11-4,4>>^ Então, Davi mandou mensageiros para a trazerem. Ela veio e Davi dormiu com ela. Ora, a mulher, depois de purificar-se de sua imundície menstrual, voltou para a sua casa,

[[v10-11-5]]

^<<v10-11-5,5>>^ e vendo que concebera, mandou dizer a Davi: “Estou grávida”.

[[v10-11-6]]

^<<v10-11-6,6>>^ Então, Davi enviou uma mensagem a Joab, dizendo-lhe: “Manda-me Urias, o hiteu”. Joab assim fez.

[[v10-11-7]]

^<<v10-11-7,7>>^ Quando Urias chegou, Davi pediu-lhe notícias de Joab, do exército e da guerra.

[[v10-11-8]]

^<<v10-11-8,8>>^ E, em seguida, disse-lhe: “Desce à tua casa e lava os teus pés”. Urias saiu do palácio do rei e este mandou que o seguissem com um presente seu.

[[v10-11-9]]

^<<v10-11-9,9>>^ Mas Urias não desceu à sua casa; dormiu à porta do palácio com os demais servos de seu amo.

[[v10-11-10]]

^<<v10-11-10,10>>^ Comunicaram-no a Davi: “Urias não foi à sua casa”. O rei então lhe disse: “Não voltaste porventura de uma viagem? Por que não vais à tua casa?”.

[[v10-11-11]]

^<<v10-11-11,11>>^ “A arca – respondeu Urias – se aloja debaixo de uma tenda, assim como Israel e Judá. Joab, meu chefe e seus suboficiais acampam ao relento e teria eu ainda a coragem de entrar em minha casa para comer, beber e dormir com minha mulher? Pela tua vida, não farei tal coisa.”

[[v10-11-12]]

^<<v10-11-12,12>>^ Davi disse-lhe: “Fica ainda hoje aqui; amanhã te despedirei”. E Urias permaneceu em Jerusalém naquele dia. No dia seguinte,

[[v10-11-13]]

^<<v10-11-13,13>>^ Davi o convidou, fê-lo comer e beber em sua presença e o embriagou. Mas à noite, Urias não desceu à sua casa; saiu e deitou-se com os demais servos de seu senhor.^&#42;1^

[[v10-11-14]]

^<<v10-11-14,14>>^ Na manhã seguinte, Davi escreve uma carta a Joab, enviando-a por Urias.

[[v10-11-15]]

^<<v10-11-15,15>>^ Dizia na carta: “Coloca Urias na frente, onde o combate for mais renhido e desamparai-o para que ele seja ferido e morra”.

[[v10-11-16]]

^<<v10-11-16,16>>^ Joab, que sitiava a cidade, pôs Urias no lugar onde sabia que estavam os mais valorosos guerreiros.

[[v10-11-17]]

^<<v10-11-17,17>>^ Saíram os assediados contra Joab e tombaram alguns dos homens de Davi, morreu, também Urias, o hiteu.

[[v10-11-18]]

^<<v10-11-18,18>>^ Joab mandou informar Davi de todas as peripécias do combate,

[[v10-11-19]]

^<<v10-11-19,19>>^ ordenando ao mensageiro: “Quando tiveres contado ao rei todos os pormenores do combate,

[[v10-11-20]]

^<<v10-11-20,20>>^ se ele se indignar e te disser: ‘Por que vos aproximastes da cidade para lutar? Não sabeis que atiram projéteis do alto da muralha?

[[v10-11-21]]

^<<v10-11-21,21>>^ Quem matou Abimelec, filho de Jerobaal? Não foi uma mulher quem lhe atirou uma pedra de moinho de cima do muro, morrendo ele em Tebes? Por que vos aproximastes dos muros? – dirás então: Morreu também o teu servo Urias, o hiteu’.”

[[v10-11-22]]

^<<v10-11-22,22>>^ Partiu, pois, o mensageiro e foi ter com o rei em Jerusalém; logo que chegou, contou-lhe tudo o que Joab lhe tinha mandado.^&#42;1^

[[v10-11-23]]

^<<v10-11-23,23>>^ Disse ele: “Os inimigos, levando vantagem sobre nós, saíram contra nós em pleno campo, mas nós os fizemos recuar até a porta da cidade.

[[v10-11-24]]

^<<v10-11-24,24>>^ Então, do alto da muralha, os arqueiros atiraram contra os teus servos e morreram dezoito dos servos do rei; morreu também o servo Urias, o hiteu”.

[[v10-11-25]]

^<<v10-11-25,25>>^ O rei respondeu ao mensageiro: “Dize a Joab que não se aflija por causa disso, pois a espada devasta ora aqui, ora ali. Mas que ele prossiga vigorosamente a sua luta contra a cidade, até destruí-la. Quanto a ti, encoraja-o”.

[[v10-11-26]]

^<<v10-11-26,26>>^ Ao saber da morte de seu marido, a mulher de Urias chorou-o.

[[v10-11-27]]

^<<v10-11-27,27>>^ Passado o luto, Davi mandou buscá-la e recolheu-a em sua casa. Ela se tornou sua mulher e lhe deu um filho. Mas o procedimento de Davi desagradara ao Senhor.

'''

xref:010-ii-samuel/010-ii-samuel-010.adoc#v10-10-0[&#60; Capítulo Anterior] | <<v10-11-0,Topo>> | xref:010-ii-samuel/010-ii-samuel-012.adoc#v10-12-0[Próximo Capítulo &#62;]