include::./index.adoc[]

[[v10-9-0]]
=== II Samuel, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Samuel 9 narra como o rei Davi mostrou bondade a um descendente de Saul chamado Mefibosete, filho de Jônatas. Davi queria honrar o relacionamento que tinha com Jônatas, que era o seu melhor amigo. Ele procurou por um descendente de Jônatas para mostrar bondade por amor ao amigo. Davi tratou Mefibosete com bondade e lhe deu um lugar à mesa do rei, restaurando a sua posição e a sua herança.
* Salmo 41:1: "Bem-aventurado aquele que atende ao pobre; o SENHOR o livrará no dia do mal." Este salmo fala sobre como o SENHOR ajuda os pobres e necessitados, e como aqueles que os ajudam também serão abençoados. Davi demonstrou isso com sua bondade a Mefibosete.
* Provérbios 19:17: "O que se compadece do pobre ao SENHOR empresta, e este lhe paga o seu benefício." Este provérbio fala sobre como ajudar os pobres é emprestar ao SENHOR, e que Ele irá recompensar aqueles que ajudam. Davi foi generoso com Mefibosete, e Deus recompensou a sua bondade.
* Isaías 61:1: "O Espírito do SENHOR Deus está sobre mim; porque o SENHOR me ungiu, para pregar boas novas aos mansos; enviou-me a restaurar os contritos de coração, a proclamar liberdade aos cativos e a abertura de prisão aos presos." Este verso fala sobre como Deus chama aqueles que são ungidos para ajudar os necessitados e os cativos. Davi, como ungido de Deus, mostrou bondade a Mefibosete e o libertou da sua prisão de pobreza e solidão.
* Mateus 5:7: "Bem-aventurados os misericordiosos, porque alcançarão misericórdia." Jesus ensinou que a misericórdia é uma virtude importante, e aqueles que a mostram serão recompensados. Davi mostrou misericórdia a Mefibosete e foi recompensado com a alegria de ver a felicidade dele.
* Tiago 2:14-17: "De que aproveita, irmãos, alguém dizer que tem fé, se não tiver obras? Porventura essa fé pode salvá-lo? E, se o irmão ou a irmã estiverem nus, e tiverem falta de mantimento quotidiano, e algum de vós lhes disser: Ide em paz, aquentai-vos, e fartai-vos; e não lhes derdes as coisas necessárias para o corpo, que proveito virá daí? Assim também a fé, se não tiver obras, é morta em si mesma." Tiago ensina que a fé sem obras é inútil, e que devemos agir em conformidade com nossa fé. Davi demonstrou sua fé em Deus agindo com bondade para com Mefibosete.
****

[[v10-9-1]]

^<<v10-9-1,1>>^ Davi disse: “Terá ficado alguém da casa de Saul a quem eu possa beneficiar em memória de Jônatas?”.

[[v10-9-2]]

^<<v10-9-2,2>>^ Ora, havia na família de Saul um servo chamado Siba. Levaram-no à presença de Davi, que lhe disse: “És tu mesmo Siba?”. “Para servir-te’’ – respondeu ele.

[[v10-9-3]]

^<<v10-9-3,3>>^ Tornou o rei: “Haverá ainda alguém da família de Saul a quem eu possa fazer misericórdia da parte de Deus?”. “Há ainda um filho de Jônatas – respondeu Siba –, aleijado dos dois pés”.

[[v10-9-4]]

^<<v10-9-4,4>>^ E o rei perguntou: “Onde está ele?”. Siba respondeu: “Está na casa de Maquir, filho de Amiel, de Lo-Dabar”.

[[v10-9-5]]

^<<v10-9-5,5>>^ E o rei mandou buscá-lo na casa de Maquir, filho de Amiel, de Lo-Dabar.

[[v10-9-6]]

^<<v10-9-6,6>>^ Quando Mifiboset, filho de Jônatas, neto de Saul, chegou diante de Davi, prostrou-se com o rosto por terra. Davi disse-lhe: “Mifiboset!”. “Para servir-te” – respondeu ele.

[[v10-9-7]]

^<<v10-9-7,7>>^ Davi disse-lhe: “Não temas. Quero fazer-te bem em memória de teu pai Jônatas e te restituirei todos os bens de Saul, teu avô. Comerás à minha mesa”.

[[v10-9-8]]

^<<v10-9-8,8>>^ Mifiboset prostrou-se, dizendo: “Quem é o teu servo para que dês atenção a um cão morto como eu?”.

[[v10-9-9]]

^<<v10-9-9,9>>^ O rei chamou Siba, servo de Saul, e lhe disse: “Tudo o que pertenceu a Saul e à sua casa, darei ao filho de teu senhor.

[[v10-9-10]]

^<<v10-9-10,10>>^ Lavrarás a terra para ele, tu, teus filhos e tua gente e levarás o produto de teu trabalho para servir de alimento à família de teu senhor. Quanto a Mifiboset, filho de teu senhor, ele comerá sempre à minha mesa”. Ora, Siba tinha quinze filhos e vinte escravos.

[[v10-9-11]]

^<<v10-9-11,11>>^ Siba disse ao rei: “Teu servo fará o que o rei, meu senhor, lhe ordenou”. Mifiboset comia, pois, à mesa do rei como um de seus filhos.

[[v10-9-12]]

^<<v10-9-12,12>>^ Tinha ele um filho menor chamado Micas. Todos os que pertenciam à casa de Siba estavam a serviço de Mifiboset.

[[v10-9-13]]

^<<v10-9-13,13>>^ Este habitava em Jerusalém, pois comia todos os dias à mesa do rei e era paralítico dos dois pés.

'''

xref:010-ii-samuel/010-ii-samuel-008.adoc#v10-8-0[&#60; Capítulo Anterior] | <<v10-9-0,Topo>> | xref:010-ii-samuel/010-ii-samuel-010.adoc#v10-10-0[Próximo Capítulo &#62;]