include::./index.adoc[]

[[v7-10-0]]
=== Juízes, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Juízes 10 narra a história dos juízes Tola e Jair, que lideraram Israel por um total de 45 anos após a morte de Jefté. No entanto, os israelitas novamente se afastam de Deus e começam a adorar ídolos estrangeiros, o que leva a opressão pelos amonitas. Eles finalmente clamam a Deus por ajuda e se arrependem de sua idolatria, levando Deus a levantar Jephthah para liderá-los à vitória. Aqui estão cinco versículos relacionados com os temas abordados em Juízes 10, excluindo versículos do próprio capítulo:
* Salmos 106:36-37: "Serviram a seus ídolos, que se tornaram um laço para eles. Sacrificaram seus filhos e suas filhas aos demônios." Este versículo fala sobre a idolatria e como ela pode ser prejudicial para as pessoas. Os israelitas em Juízes 10 se desviaram de Deus e começaram a adorar ídolos estrangeiros, levando à opressão pelos amonitas.
* Isaías 45:7: "Eu formo a luz e crio as trevas, promovo a paz e causo a desgraça; eu, o Senhor, faço todas essas coisas." Este versículo fala sobre a soberania de Deus sobre todas as coisas, incluindo a desgraça que pode vir sobre as pessoas. Os israelitas em Juízes 10 foram oprimidos pelos amonitas por causa de sua idolatria, mas eles clamaram a Deus por ajuda, e Deus levantou Jephthah para liderá-los à vitória.
* Romanos 12:21: "Não se deixem vencer pelo mal, mas vençam o mal com o bem." Este versículo fala sobre a importância de resistir ao mal e vencê-lo com o bem. Jephthah em Juízes 10 liderou Israel à vitória contra os amonitas e mostrou que é possível vencer o mal com o bem.
* Hebreus 11:32-34: "E que mais direi? Não tenho tempo para falar de Gideão, Baraque, Sansão, Jefté, Davi, Samuel e os profetas, os quais pela fé conquistaram reinos, praticaram a justiça, obtiveram o cumprimento de promessas, fecharam a boca de leões, apagaram a força do fogo e escaparam do fio da espada; da fraqueza tiraram força, tornaram-se poderosos na batalha e puseram em fuga exércitos estrangeiros." Este versículo fala sobre a fé dos heróis do Antigo Testamento que foram capazes de conquistar reinos e pôr em fuga exércitos estrangeiros. Jephthah em Juízes 10 é listado junto com outros heróis da fé por sua conquista sobre os amonitas.
* Apocalipse 3:19: "A todos a quem amo, repreendo e disciplino. Por isso, seja diligente e arrependa-se." Este versículo fala sobre como Deus disciplina aqueles a quem Ele ama e como é importante se arrepender.
****

[[v7-10-1]]

^<<v7-10-1,1>>^ Depois de Abimelec, Tola, filho de Fua, filho de Dodo, de Issacar, levantou-se para livrar Israel. Habitava em Samir, na montanha de Efraim,

[[v7-10-2]]

^<<v7-10-2,2>>^ e foi juiz em Israel durante vinte e três anos. Depois disso, morreu e foi sepultado em Samir.

[[v7-10-3]]

^<<v7-10-3,3>>^ A este sucedeu Jair, de Galaad, que foi juiz em Israel durante vinte e dois anos.

[[v7-10-4]]

^<<v7-10-4,4>>^ Tinha trinta filhos que montavam em trinta jumentinhos e possuíam trinta cidades que se chamam ainda hoje Havot-Jair, situadas em Galaad.

[[v7-10-5]]

^<<v7-10-5,5>>^ Jair morreu e foi sepultado em Camon.

[[v7-10-6]]

^<<v7-10-6,6>>^ Os filhos de Israel voltaram a ofender o Senhor, servindo os baals e os astarot, os deuses da Síria, de Sidon, de Moab, os deuses dos amonitas e dos filisteus. Abandonaram o culto do Senhor.

[[v7-10-7]]

^<<v7-10-7,7>>^ A cólera do Senhor inflamou-se contra Israel e ele entregou-os nas mãos dos filisteus e dos amonitas.

[[v7-10-8]]

^<<v7-10-8,8>>^ Estes últimos oprimiram e esmagaram os israelitas naquele ano. A opressão estendeu-se por dezoito anos sobre os israelitas de além do Jordão, na terra dos amorreus, em Galaad.

[[v7-10-9]]

^<<v7-10-9,9>>^ Os amonitas, tendo passado o Jordão, combateram contra Judá, Benjamim e a tribo de Efraim, e Israel viu-se numa extrema aflição.

[[v7-10-10]]

^<<v7-10-10,10>>^ Os israelitas clamaram ao Senhor, dizendo: “Pecamos contra vós, abandonando o nosso Deus e servindo aos baals”.

[[v7-10-11]]

^<<v7-10-11,11>>^ O Senhor respondeu-lhes: “Porventura não vos tenho eu livrado dos egípcios, dos amorreus, dos amonitas, dos filisteus?

[[v7-10-12]]

^<<v7-10-12,12>>^ E quando os sidônios, os amalecitas e Maon vos oprimiam e vós clamastes a mim, não vos libertei?

[[v7-10-13]]

^<<v7-10-13,13>>^ Vós, porém, me abandonastes para servir a outros deuses. Por isso, não mais vos livrarei.

[[v7-10-14]]

^<<v7-10-14,14>>^ Ide e invocai os deuses que escolhestes; eles que vos livrem de vossa angústia!”.

[[v7-10-15]]

^<<v7-10-15,15>>^ Os israelitas disseram ao Senhor: “Pecamos; tratai-nos como melhor vos parecer, contanto que nos livres hoje”.

[[v7-10-16]]

^<<v7-10-16,16>>^ Tiraram então do meio deles os deuses estranhos e serviram ao Senhor, que se compadeceu dos males de Israel.

[[v7-10-17]]

^<<v7-10-17,17>>^ Os amonitas juntaram-se e acamparam em Galaad, enquanto os israelitas faziam o mesmo em Masfa.

[[v7-10-18]]

^<<v7-10-18,18>>^ O povo e os chefes de Galaad diziam uns para os outros: “Quem começará a pelejar contra os amonitas? Esse será o chefe de todo o povo de Galaad”.

'''

xref:007-juizes/007-juizes-009.adoc#v7-9-0[&#60; Capítulo Anterior] | <<v7-10-0,Topo>> | xref:007-juizes/007-juizes-011.adoc#v7-11-0[Próximo Capítulo &#62;]