include::./index.adoc[]

[[v7-7-0]]
=== Juízes, 7
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Juízes 7 narra a história de Gideão, um líder israelita que é escolhido por Deus para liderar uma batalha contra o exército de Midiã. Deus instrui Gideão a reduzir seu exército de 32.000 para apenas 300 homens, para que a vitória seja claramente atribuída a Deus e não aos homens. Abaixo estão cinco versículos relacionados aos temas abordados em Juízes 7:
* 1 Coríntios 1:27: "Mas Deus escolheu as coisas loucas do mundo para envergonhar os sábios, e escolheu as coisas fracas do mundo para envergonhar as fortes." Este versículo fala sobre como Deus frequentemente escolhe as pessoas e os métodos que parecem fracos e insensatos para realizar seus propósitos. É relevante para Juízes 7, onde Deus instrui Gideão a reduzir seu exército a apenas 300 homens.
* Isaías 41:10: "Não tenha medo, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa." Este versículo fala sobre como Deus está com seu povo e os fortalece. É relevante para Juízes 7, onde Deus fortalece Gideão e seu exército de apenas 300 homens para vencer o exército de Midiã.
* Salmos 23:4: "Mesmo que eu ande por um vale escuro como a morte, não temerei mal algum, pois tu estás comigo; a tua vara e o teu cajado me protegem." Este versículo fala sobre como Deus protege seu povo mesmo em situações perigosas. É relevante para Juízes 7, onde Deus protege Gideão e seu exército de apenas 300 homens durante a batalha contra o exército de Midiã.
* 2 Coríntios 12:9: "Mas ele me disse: 'Minha graça é suficiente para você, pois o meu poder se aperfeiçoa na fraqueza'. Portanto, eu me gloriarei ainda mais alegremente em minhas fraquezas, para que o poder de Cristo repouse em mim." Este versículo fala sobre como a fraqueza humana pode ser um veículo para a manifestação do poder de Deus. É relevante para Juízes 7, onde Deus instrui Gideão a reduzir seu exército a apenas 300 homens para que a vitória seja claramente atribuída a Deus e não aos homens.
* Filipenses 4:13: "Tudo posso naquele que me fortalece." Este versículo fala sobre como podemos fazer todas as coisas por meio da força que Deus nos dá. É relevante para Juízes 7, onde Deus fortalece Gideão e seu exército de apenas 300 homens para vencer o exército de Midiã.
****

[[v7-7-1]]

^<<v7-7-1,1>>^ Jerobaal, isto é, Gedeão, levantando-se no dia seguinte bem cedo, foi acampar na fonte de Harod com todo o povo que o acompanhava. O acampamento madianita encontrava-se ao norte da colina de Moré, na planície.

[[v7-7-2]]

^<<v7-7-2,2>>^ O Senhor disse a Gedeão: “A gente que levas contigo é numerosa demais para que eu entregue Madiã em suas mãos. Israel poderia gloriar-se à minha custa, dizendo: ‘Foi a minha mão que me livrou’.

[[v7-7-3]]

^<<v7-7-3,3>>^ Manda, pois, publicar esse aviso para que todos o ouçam: quem for medroso ou tímido, volte para trás e deixe a montanha de Gelboé”. Vinte e dois mil homens voltaram, ficando ainda dez mil.

[[v7-7-4]]

^<<v7-7-4,4>>^ O Senhor disse a Gedeão: “Ainda há gente demais. Faze-os descer às águas e ali farei uma escolha. Aquele que eu te disser que irá contigo, este te seguirá; e aquele que eu não te designar, ficará”.

[[v7-7-5]]

^<<v7-7-5,5>>^ Gedeão fez, pois, descer o povo junto às águas e o Senhor disse-lhe: “Porás à parte todos aqueles que lamberem a água com a língua, como faz o cão, e de outro lado aqueles que se puserem de joelhos para beber”.

[[v7-7-6]]

^<<v7-7-6,6>>^ Ora, o número dos que lamberam a água, levando-a com a mão à boca, foi de trezentos homens; todo o resto do povo se pusera de joelhos para beber.

[[v7-7-7]]

^<<v7-7-7,7>>^ O Senhor disse a Gedeão: “Com os trezentos homens que lamberam a água, vos salvarei e entregarei Madiã nas tuas mãos. Todo o resto do povo volte para a sua casa”.

[[v7-7-8]]

^<<v7-7-8,8>>^ Gedeão guardou os víveres do povo e suas trombetas e despediu todos os israelitas, cada um para a sua tenda, só conservando os trezentos homens. O acampamento madianita estava embaixo, na planície.

[[v7-7-9]]

^<<v7-7-9,9>>^ Durante a noite seguinte, o Senhor disse a Gedeão: “Levanta-te e ataca o acampamento, pois eu entreguei em tuas mãos.

[[v7-7-10]]

^<<v7-7-10,10>>^ Todavia, se tens medo de descer só, leva contigo Fara, teu servo.

[[v7-7-11]]

^<<v7-7-11,11>>^ Ouvirás o que eles dizem, e te sentirás assim encorajado para atacar o acampamento”. Gedeão desceu, pois, com Fara, seu servo, até onde estavam os postos avançados do acampamento.

[[v7-7-12]]

^<<v7-7-12,12>>^ Ora, os madianitas, os amalecitas e todos os filhos do oriente estavam espalhados pelo vale, tão numerosos como gafanhotos e seus camelos eram também inumeráveis como a areia das praias.

[[v7-7-13]]

^<<v7-7-13,13>>^ No momento em que Gedeão se aproximou, um homem estava justamente contando um sonho ao seu companheiro: “Eis – dizia ele – o sonho que tive: Um pão de cevada rolava sobre o acampamento de Madiã e, chocando-se com a tenda, lançou-a completamente por terra”. O companheiro respondeu:

[[v7-7-14]]

^<<v7-7-14,14>>^ “Isso não é outra coisa senão a espada de Gedeão, filho de Joás, o israelita. Deus entregou em suas mãos Madiã e todo o acampamento”.

[[v7-7-15]]

^<<v7-7-15,15>>^ Tendo ouvido a narração e a interpretação desse sonho, Gedeão prostrou-se por terra. Voltou ao acampamento israelita e disse: “Levantai-vos, porque o Senhor vos entregou nas mãos o acampamento dos madianitas!”.

[[v7-7-16]]

^<<v7-7-16,16>>^ Dividiu os trezentos homens em três grupos e pôs nas mãos de todos trombetas e ânforas vazias, levando estas dentro uma tocha acesa.

[[v7-7-17]]

^<<v7-7-17,17>>^ “Olhai para mim – disse ele – e fazei como eu. Quando eu chegar aos limites do acampamento, fazei o que eu fizer.

[[v7-7-18]]

^<<v7-7-18,18>>^ Tocarei a trombeta com aqueles que me acompanham, e então tocareis também as vossas em volta de todo o acampamento, gritando: ‘Pelo Senhor e por Gedeão!’.”

[[v7-7-19]]

^<<v7-7-19,19>>^ Gedeão com seus cem homens chegaram aos limites do acampamento no princípio da segunda vigília, quando se rendiam as sentinelas, e começaram a tocar as trombetas, quebrando ao mesmo tempo as ânforas que tinham na mão.

[[v7-7-20]]

^<<v7-7-20,20>>^ Então os três batalhões tocaram (também) as trombetas e quebraram as ânforas. Tomando as tochas na mão esquerda e as trombetas na direita para tocar, gritaram: “À espada pelo Senhor e por Gedeão!”.

[[v7-7-21]]

^<<v7-7-21,21>>^ Cada um ficou em seu lugar, ao redor do acampamento; todo o acampamento se pôs a correr e fugiram, gritando.

[[v7-7-22]]

^<<v7-7-22,22>>^ Os trezentos homens continuavam a tocar as trombetas, enquanto, por todo o acampamento, o Senhor fez com que os madianitas voltassem a espada uns contra os outros, e o exército fugiu até Bet-Seta, para os lados de Sarera e até os limites de Abel-Meúla, junto de Tebat.

[[v7-7-23]]

^<<v7-7-23,23>>^ Juntaram-se então aos israelitas as tribos de Neftali e de Aser e todo o Manassés, e perseguiram os madianitas.

[[v7-7-24]]

^<<v7-7-24,24>>^ Gedeão enviou mensageiros por todo o monte de Efraim, para avisar: “Descei ao encontro dos madianitas e cortai-lhes a passagem das águas até Bet-Bera e até os vaus do Jordão”. Juntaram-se, pois, os homens de Efraim e ocuparam as passagens até Bet-Bera, e igualmente os vaus do Jordão.

[[v7-7-25]]

^<<v7-7-25,25>>^ Tendo capturado dois chefes madianitas, Oreb e Zeb, mataram Oreb no rochedo de Oreb, e Zeb no lagar de Zeb. E continuaram a perseguir os madianitas, levando as cabeças de Oreb e de Zeb a Gedeão, no outro lado do Jordão.

'''

xref:007-juizes/007-juizes-006.adoc#v7-6-0[&#60; Capítulo Anterior] | <<v7-7-0,Topo>> | xref:007-juizes/007-juizes-008.adoc#v7-8-0[Próximo Capítulo &#62;]