include::./index.adoc[]

[[v7-1-0]]
=== Juízes, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 1 do livro de Juízes descreve a conquista de várias cidades por parte das tribos de Israel após a morte de Josué. No entanto, o capítulo também destaca algumas falhas do povo de Israel, como a falta de completa destruição dos cananeus e a aliança com alguns deles. A seguir estão cinco versículos relacionados a esses temas:
* Números 33:55: "Mas, se não expulsardes os habitantes da terra de diante de vós, sucederá que os que deixardes ficar serão como aguilhões nos vossos olhos e como espinhos nas vossas ilhargas, e vos apertarão na terra em que habitardes." Este versículo destaca a importância da completa expulsão dos povos pagãos da terra prometida, algo que Israel falhou em fazer completamente.
* Josué 23:12-13: "Porque, se vos apartardes, e vos apegardes ao restante destas nações que ficaram entre vós, e se misturardes com elas, e vos unirdes com elas, e elas convosco, sabei com certeza que o Senhor, vosso Deus, não continuará a expulsar estas nações de diante de vós; antes, elas vos serão por laço e por rede, e por açoite às vossas ilhargas e por espinhos aos vossos olhos, até que pereçais desta boa terra que vos deu o Senhor, vosso Deus." Este versículo adverte contra a associação com os povos pagãos, uma prática que Israel falhou em evitar completamente.
* Números 32:23: "Porém, se não fizerdes assim, eis que pecastes contra o Senhor; e sabei que o vosso pecado vos há de achar." Este versículo destaca a importância da obediência a Deus e as consequências da desobediência.
* Êxodo 23:32-33: "Não farás aliança com eles, nem com os seus deuses. Não habitarão na tua terra, para que não te façam pecar contra mim; porque servirás a seus deuses, o que será para ti um laço." Este versículo adverte contra a aliança com povos pagãos, uma prática que Israel falhou em evitar completamente.
* Josué 23:16: "Quando violardes a aliança do Senhor, vosso Deus, que ele vos ordenou, e fordes e servirdes a outros deuses, e a eles vos inclinardes, então a ira do Senhor se acenderá contra vós, e logo perecereis da boa terra que ele vos deu." Este versículo destaca as consequências da infidelidade a Deus, algo que o povo de Israel experimentou em diversas ocasiões.
****

[[v7-1-1]]

^<<v7-1-1,1>>^ Depois da morte de Josué, os israelitas consultaram o Senhor: “Quem dentre nós será o primeiro a combater os cananeus?”.

[[v7-1-2]]

^<<v7-1-2,2>>^ O Senhor respondeu: “Judá, pois eu entregarei a terra nas suas mãos”.

[[v7-1-3]]

^<<v7-1-3,3>>^ Então, Judá disse a Simeão, seu irmão: “Vem comigo à terra que me coube por sorte, para combatermos contra os cananeus. Depois irei contigo à tua terra”. Simeão partiu com ele.

[[v7-1-4]]

^<<v7-1-4,4>>^ Judá travou combate e o Senhor entregou-lhe os cananeus e os ferezeus; derrotaram dez mil homens em Bezec.

[[v7-1-5]]

^<<v7-1-5,5>>^ Ali encontraram Adonibezec, atacaram-no e derrotaram os cananeus e os ferezeus.

[[v7-1-6]]

^<<v7-1-6,6>>^ Adonibezec fugiu, mas eles o perseguiram, prenderam-no e cortaram-lhe os polegares das mãos e dos pés.

[[v7-1-7]]

^<<v7-1-7,7>>^ Adonibezec disse: “Setenta reis, com os polegares das mãos e dos pés cortados, apanhavam debaixo de minha mesa as migalhas da comida. Como eu fiz, assim Deus me faz”. E conduziram-no a Jerusalém, onde morreu.

[[v7-1-8]]

^<<v7-1-8,8>>^ Os juditas atacaram Jerusalém e a tomaram. Passaram os seus habitantes a fio da espada e incendiaram a cidade.

[[v7-1-9]]

^<<v7-1-9,9>>^ Desceram dali e combateram os cananeus das montanhas, do Negueb e da planície.

[[v7-1-10]]

^<<v7-1-10,10>>^ Judá marchou contra os cananeus de Hebron (chamada antigamente Cariat-Arbe) e derrotou Sesai, Aimã e Tolmai.

[[v7-1-11]]

^<<v7-1-11,11>>^ Marchou depois contra os habitantes de Dabir, que antigamente se chamava Cariat-Sefer.

[[v7-1-12]]

^<<v7-1-12,12>>^ Caleb tinha dito: “Àquele que combater e tomar Cariat-Sefer darei por mulher minha filha Acsa”.

[[v7-1-13]]

^<<v7-1-13,13>>^ Otoniel, filho de Cenez, irmão mais novo de Caleb, tomou a cidade; e Caleb deu-lhe sua filha Acsa por mulher.

[[v7-1-14]]

^<<v7-1-14,14>>^ Chegando Acsa à casa de seu marido, ele moveu-a a que pedisse um campo ao seu pai. E pela segunda vez ela saltou de seu jumento e Caleb disse-lhe: “Que tens?”.

[[v7-1-15]]

^<<v7-1-15,15>>^ “Dá-me –, respondeu ela – um presente. Instalaste-me em uma terra árida; dá-me também fontes de água!” E Caleb deu-lhe as fontes superiores e inferiores.

[[v7-1-16]]

^<<v7-1-16,16>>^ Os filhos de Hobab, o quenita, cunhado de Moisés, subiram da cidade das Palmeiras com os juditas, no deserto de Judá, ao sul de Arad, e vieram estabelecer-se com o povo.^&#42;1^

[[v7-1-17]]

^<<v7-1-17,17>>^ Judá prosseguiu sua marcha com Simeão, seu irmão, e derrotaram os cananeus de Sefat. Votaram a cidade ao interdito e ela recebeu o nome de Horma.^&#42;1^

[[v7-1-18]]

^<<v7-1-18,18>>^ Judá tomou também Gaza e seu território, bem como Ascalon e Acaron com seus territórios.

[[v7-1-19]]

^<<v7-1-19,19>>^ O Senhor estava com Judá, e ele conquistou a montanha; porém, não pôde despojar os habitantes da planície que possuíam carros de ferro.

[[v7-1-20]]

^<<v7-1-20,20>>^ Conforme o que Moisés tinha dito, deram Hebron a Caleb, que expulsou dela os três filhos de Enac.

[[v7-1-21]]

^<<v7-1-21,21>>^ Os benjaminitas não exterminaram os jebuseus de Jerusalém; por isso, os jebuseus habitaram em Jerusalém com os benjaminitas até o presente.

[[v7-1-22]]

^<<v7-1-22,22>>^ A família de José marchou também contra Betel, e o Senhor esteve com eles.

[[v7-1-23]]

^<<v7-1-23,23>>^ E quando exploravam Betel, que antes se chamava Luza,

[[v7-1-24]]

^<<v7-1-24,24>>^ viram um homem que saía da cidade e disseram-lhe: “Mostra-nos por onde se pode entrar na cidade e usaremos de misericórdia contigo”.

[[v7-1-25]]

^<<v7-1-25,25>>^ Ele indicou-lhes a entrada. Eles passaram a localidade a fio de espada, poupando, porém, aquele homem com a sua família.

[[v7-1-26]]

^<<v7-1-26,26>>^ Esse emigrou para a terra dos hiteus, onde construiu uma cidade, à qual pôs o nome de Luza, como é chamada ainda hoje.

[[v7-1-27]]

^<<v7-1-27,27>>^ Manassés não expulsou os habitantes de Betsã com suas aldeias, nem os de Tanac, de Dora, de Jeblam, de Meguido, com suas aldeias, porque os cananeus estavam decididos a ocupar essa terra.

[[v7-1-28]]

^<<v7-1-28,28>>^ Quando se tornaram mais fortes, os israelitas fizeram-nos tributários, mas não os despojaram.

[[v7-1-29]]

^<<v7-1-29,29>>^ Efraim não expulsou os cananeus de Gezer, os quais continuaram a habitar em Gezer, no meio de Efraim.

[[v7-1-30]]

^<<v7-1-30,30>>^ Zabulon não expulsou os habitantes de Cetron, nem os de Naalol; e os cananeus continuaram a habitar no meio de Zabulon, embora sujeitos ao tributo.

[[v7-1-31]]

^<<v7-1-31,31>>^ Aser não expulsou os habitantes de Aco, nem os de Sidon, nem os de Aalab, de Acazib, de Helba, de Afec e de Roob;

[[v7-1-32]]

^<<v7-1-32,32>>^ os filhos de Aser estabeleceram-se entre os cananeus, habitantes daquela terra, não podendo expulsá-los.

[[v7-1-33]]

^<<v7-1-33,33>>^ Neftali não expulsou os habitantes de Bet-Sames, nem os de Bet-Anat, e estabeleceu-se entre os cananeus, habitantes daquela terra; os betsamitas e os betanitas ficaram-lhe tributários.

[[v7-1-34]]

^<<v7-1-34,34>>^ Os amorreus repeliram os danitas para a montanha, e não lhes permitindo descer para a planície.

[[v7-1-35]]

^<<v7-1-35,35>>^ Persistiram em ficar em Ar-Hares, em Aialon e em Salebim; mas a mão da casa de José prevaleceu sobre eles e tiveram de pagar o tributo.

[[v7-1-36]]

^<<v7-1-36,36>>^ O território dos amorreus estendia-se desde a costa de Acrabim e de Sela, para o norte.

'''

xref:006-josue/006-josue-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-juizes/007-juizes-002.adoc#v7-2-0[Próximo Capítulo &#62;]