include::./index.adoc[]

[[v7-19-0]]
=== Juízes, 19
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 19 de Juízes conta a história chocante de um levita que, viajando com sua concubina, decide passar a noite na cidade de Gibéia, em Benjamim. Lá, eles são hospedados por um velho, mas a cidade é cercada por homens perversos que exigem que o levita seja entregue para que eles possam abusá-lo sexualmente. Em vez disso, o velho oferece sua própria filha e a concubina do levita para os homens, que acabam violentando e matando a concubina. O levita então corta o corpo dela em pedaços e envia os pedaços para todas as tribos de Israel, provocando uma guerra contra a tribo de Benjamim.
* Deuteronômio 22:25-27: "Mas se um homem achar uma moça desposada no campo, e o homem a forçar, e se deitar com ela, então morrerá só o homem que se deitou com ela. Porém, à moça não farás nada; não há nela pecado digno de morte; pois, como quando alguém se levanta contra o seu próximo, e lhe tira a vida, assim é este caso. Porque ele a achou no campo; a moça desposada gritou, mas não houve quem a livrasse." Este versículo destaca a importância de proteger a dignidade e a integridade das mulheres e condena a violência sexual.
* Provérbios 16:29: "O homem violento persuade o seu companheiro, e guia-o por caminho não bom." Este versículo condena a violência e a influência negativa que os homens violentos podem ter sobre os outros.
* Isaías 1:15-17: "E, quando estenderdes as vossas mãos, esconderei de vós os meus olhos; sim, quando multiplicardes a oração, não ouvirei; porque as vossas mãos estão cheias de sangue. Lavai-vos, purificai-vos, tirai de diante dos meus olhos a maldade dos vossos atos; cessai de fazer mal, aprendei a fazer bem; buscai a justiça, acabai com a opressão; fazei justiça ao órfão, defendei a causa da viúva." Este versículo condena a injustiça e a violência e chama as pessoas a se arrependerem e a buscar a justiça.
* Salmo 82:3-4: "Fazei justiça ao pobre e ao órfão; justificai o aflito e o necessitado. Livrai o pobre e o necessitado; tirai-os das mãos dos ímpios." Este versículo chama as pessoas a defenderem os necessitados e a fazerem justiça, especialmente em face da opressão e violência.
* Amós 5:15: "Odeiai o mal e amai o bem, e estabelecei a justiça na porta; talvez o SENHOR Deus dos Exércitos se compadeça do remanescente de José." Este versículo enfatiza a importância de odiar o mal e amar o bem, e a necessidade de estabelecer a justiça em todas as áreas da vida.
****

[[v7-19-1]]

^<<v7-19-1,1>>^ Naquele tempo, como não havia rei em Israel, aconteceu que um levita, vindo fixar-se no fundo das montanhas de Efraim, tomou ali por concubina uma jovem de Belém de Judá.

[[v7-19-2]]

^<<v7-19-2,2>>^ Esta foi-lhe infiel, deixou-o e foi para junto de seu pai em Belém de Judá, onde ficou quatro meses.

[[v7-19-3]]

^<<v7-19-3,3>>^ Seu marido foi ter com ela para falar-lhe ao coração e reconduzi-la à sua casa. Levou consigo um servo e dois jumentos. Ela o introduziu na casa de seu pai. Quando o pai da mulher o viu, saiu a recebê-lo alegremente.

[[v7-19-4]]

^<<v7-19-4,4>>^ Retido pelo sogro, pai da jovem, ficou o levita com ele durante três dias; comeram, beberam e passaram a noite.

[[v7-19-5]]

^<<v7-19-5,5>>^ Na manhã do quarto dia, quando se levantaram e se dispunham a partir, o pai da jovem disse ao genro: “Restaura primeiro as tuas forças com um pouco de pão e depois disso partireis”.

[[v7-19-6]]

^<<v7-19-6,6>>^ Sentaram-se ambos, comeram e beberam. Então, o pai da jovem disse ao genro: “Peço-te que passes aqui ainda esta noite e alegre-se o teu coração”.

[[v7-19-7]]

^<<v7-19-7,7>>^ Devido à insistência do sogro, o homem que já se tinha levantado para partir, tornou a recostar-se e passou ali ainda aquela noite.

[[v7-19-8]]

^<<v7-19-8,8>>^ Chegada a manhã, preparando-se ele para se pôr a caminho, disse-lhe o pai da jovem: “Peço-te que restaures as tuas forças. Deixai a vossa partida para o declinar do dia”. E comeram ambos juntos.

[[v7-19-9]]

^<<v7-19-9,9>>^ Levantou-se então o homem e dispunha-se a partir com a sua concubina e o seu servo. O sogro, porém, pai da jovem, disse-lhe de novo: “Olha que o dia declina e a noite se aproxima. Passai a noite aqui. Sim, o dia se vai acabando, passa aqui a noite tranquilamente. Amanhã vos levantareis cedo e partireis, a fim de voltardes para a vossa casa”.

[[v7-19-10]]

^<<v7-19-10,10>>^ O levita, porém, não consentiu. Partiu e chegou a Jebus, que é Jerusalém, com a sua concubina e seus dois jumentos selados.

[[v7-19-11]]

^<<v7-19-11,11>>^ Quando chegaram, o dia ia declinando. Então, o criado disse a seu amo: “Vem, tomemos o caminho da cidade dos jebuseus para ali passarmos a noite”.

[[v7-19-12]]

^<<v7-19-12,12>>^ “Não – respondeu-lhe o amo – não entraremos numa cidade estrangeira, onde não há israelitas. Iremos até Gabaá.

[[v7-19-13]]

^<<v7-19-13,13>>^ Vamos – ajuntou ele – procuremos atingir um desses lugares, e nos alojaremos em Gabaá ou em Ramá.”

[[v7-19-14]]

^<<v7-19-14,14>>^ Prosseguiram, pois, o seu caminho. O sol se punha quando se encontravam perto de Gabaá de Benjamim.

[[v7-19-15]]

^<<v7-19-15,15>>^ Dirigiram-se para lá, a fim de passarem a noite. Tendo entrado na cidade, parou o levita na praça e ninguém lhe ofereceu hospitalidade.

[[v7-19-16]]

^<<v7-19-16,16>>^ Ao anoitecer, apareceu um homem idoso que voltava do seu trabalho no campo. Era também da montanha de Efraim e habitava como forasteiro em Gabaá, cujos habitantes eram benjaminitas.

[[v7-19-17]]

^<<v7-19-17,17>>^ O velho, levantando os olhos, viu o levita na praça da cidade: “Aonde vais? –, disse-lhe ele – e de onde vens?”.

[[v7-19-18]]

^<<v7-19-18,18>>^ “Nós partimos – respondeu o levita – de Belém de Judá e vamos até o fundo da montanha de Efraim, onde nasci. Acabo de deixar Belém de Judá para voltar à minha casa, mas ninguém me quer acolher,^&#42;1^

[[v7-19-19]]

^<<v7-19-19,19>>^ embora tenhamos palha e feno para os nossos jumentos, pão e vinho para mim, tua serva e o jovem, teu servo; nada nos falta.”

[[v7-19-20]]

^<<v7-19-20,20>>^ O velho respondeu: “A paz seja contigo. E te darei tudo o que for necessário. De modo algum deverás passar a noite na praça”.

[[v7-19-21]]

^<<v7-19-21,21>>^ Fê-lo entrar em sua casa, e deu de comer aos jumentos. Os viajantes lavaram os pés, e foi-lhes servida a refeição.

[[v7-19-22]]

^<<v7-19-22,22>>^ Enquanto restauravam as forças, vieram os habitantes da cidade, gente péssima, e, cercando a casa do velho, bateram violentamente à porta: “Faze sair – gritaram eles ao velho, dono da casa –, faze sair o homem que entrou em tua casa para que nós o conheçamos!”.

[[v7-19-23]]

^<<v7-19-23,23>>^ O velho saiu e foi ter com eles, dizendo: “Não queirais, irmãos, cometer semelhante maldade, pois esse homem é hóspede de minha casa. Não pratiqueis tal infâmia.

[[v7-19-24]]

^<<v7-19-24,24>>^ Eis aqui a minha filha virgem e a concubina desse homem. Eu vo-las trarei. Vós podereis violá-las e fazer delas o que quiserdes; somente vos peço que não cometais contra esse homem uma ação tão infame”.

[[v7-19-25]]

^<<v7-19-25,25>>^ Eles, porém, não o quiseram ouvir. Então o levita, vendo isso, trouxe-lhes sua concubina. Eles a conheceram e abusaram dela durante a noite até pela manhã e despediram-na ao amanhecer.

[[v7-19-26]]

^<<v7-19-26,26>>^ Ao romper do dia, veio a mulher e caiu à porta da casa onde estava o marido e ali ficou até que o dia clareasse.

[[v7-19-27]]

^<<v7-19-27,27>>^ Chegada a manhã, levantou-se o marido e, ao abrir a porta para continuar o seu caminho, eis que sua concubina jazia diante da porta, com as mãos estendidas sobre a soleira.

[[v7-19-28]]

^<<v7-19-28,28>>^ “Levanta-te – disse-lhe ele –, vamos embora.” Mas a mulher não lhe respondeu... tomou-a então, pô-la sobre o jumento e tomou o caminho de volta para a sua casa.

[[v7-19-29]]

^<<v7-19-29,29>>^ Chegando à sua casa, pegou um cutelo. Dividiu o cadáver de sua concubina, membro por membro, em doze partes, e enviou-as por todo o território de Israel.

[[v7-19-30]]

^<<v7-19-30,30>>^ Todos os que testemunharam aquilo, disseram: “Jamais se fez ou se viu tal coisa, desde que Israel subiu do Egito até este dia. Ponderai bem isto, deliberai e pronunciai-vos!”.

'''

xref:007-juizes/007-juizes-018.adoc#v7-18-0[&#60; Capítulo Anterior] | <<v7-19-0,Topo>> | xref:007-juizes/007-juizes-020.adoc#v7-20-0[Próximo Capítulo &#62;]