include::./index.adoc[]

[[v7-9-0]]
=== Juízes, 9
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Juízes 9 relata a história de Abimeleque, filho de Gideão, que conspira para se tornar rei de Israel matando seus setenta irmãos. Após consolidar seu poder em Siquém, Abimeleque é desafiado por um líder local chamado Gaal, o que leva a uma batalha sangrenta. Mais tarde, Abimeleque é morto por uma mulher que deixa cair uma pedra em sua cabeça do alto da torre de uma cidade.
* Gênesis 49:10: "O cetro não se apartará de Judá, nem o bastão de comando de seus descendentes, até que venha aquele a quem ele pertence, aquele a quem as nações obedecerão." Este versículo é uma profecia sobre o futuro rei de Israel, que viria da tribo de Judá. Abimeleque, no entanto, não era um descendente de Judá e, portanto, sua ascensão ao trono não estava de acordo com essa profecia.
* Provérbios 26:27: "Quem cava um buraco cai nele; quem rola uma pedra, esta rola de volta sobre ele." Este versículo é uma lição sobre as consequências de nossas ações. Abimeleque conspirou para matar seus irmãos e, finalmente, acabou morrendo devido a uma pedra que lhe foi lançada.
* Isaías 28:17: "Eu farei da justiça a linha de medir e da retidão o peso; o granizo varrerá o abrigo que oculta a mentira, e as águas inundarão o esconderijo." Este versículo fala sobre a importância da justiça e da verdade. Abimeleque governou por meio de mentiras e violência, mas no final, a justiça prevaleceu e ele foi derrotado.
* Jeremias 22:3: "Assim diz o Senhor: Pratiquem a justiça e a retidão, libertem o oprimido da mão do opressor, tratem o estrangeiro e o órfão com justiça, não os maltratem. Não derramem sangue inocente neste lugar." Este versículo é um chamado à justiça e à bondade. Abimeleque não cumpriu esses mandamentos e, como resultado, sua vida foi marcada pela violência e pelo derramamento de sangue.
* Eclesiastes 5:8: "Se você vir que o pobre é oprimido, que a justiça e o direito são violados em uma província, não fique perplexo diante disso. Um oficial superior observa tudo isso; e quem é superior a ele observa-os." Este versículo fala sobre a importância da justiça e da equidade na governança. Abimeleque, como líder, falhou em governar com justiça e equidade, o que levou à sua queda.
****

[[v7-9-1]]

^<<v7-9-1,1>>^ Abimelec, filho de Jerobaal, foi ter com os irmãos de sua mãe em Siquém, e disse-lhes, assim como a toda a família de sua mãe:

[[v7-9-2]]

^<<v7-9-2,2>>^ “Dizei, vo-lo peço, a todos os habitantes de Siquém: O que é melhor para vós: serdes dominados por setenta homens, todos filhos de Jerobaal, ou que um só homem seja vosso rei? Lembrai-vos de que eu sou de vosso sangue e de vossa carne”.

[[v7-9-3]]

^<<v7-9-3,3>>^ Os irmãos de sua mãe falaram dele aos habitantes de Siquém, referindo-lhes suas palavras e inclinaram o seu coração para Abimelec, “porque – diziam eles – é nosso irmão”.

[[v7-9-4]]

^<<v7-9-4,4>>^ E deram-lhe setenta siclos de prata tomados do templo de Baal-Berit, com os quais assalariou homens miseráveis e aventureiros que o seguiram.

[[v7-9-5]]

^<<v7-9-5,5>>^ Foi à casa de seu pai, em Efra, e matou sobre uma pedra os seus irmãos, filhos de Jerobaal, setenta homens; escapou somente Joatão, filho mais novo de Jerobaal, porque se tinha escondido.

[[v7-9-6]]

^<<v7-9-6,6>>^ Juntaram-se então todos os siquemitas com todos os de Bet-Melo e vieram junto do terebinto da coluna sagrada que havia em Siquém, onde proclamaram rei Abimelec.

[[v7-9-7]]

^<<v7-9-7,7>>^ Sabendo disso, subiu Joatão ao cimo do monte Garizim e exclamou: “Ouvi-me, homens de Siquém, para que Deus vos ouça!

[[v7-9-8]]

^<<v7-9-8,8>>^ As árvores resolveram um dia eleger um rei para governá-las e disseram à oliveira: reina sobre nós!

[[v7-9-9]]

^<<v7-9-9,9>>^ Mas ela respondeu: ‘Renunciarei, porventura, ao meu óleo que constitui minha glória aos olhos de Deus e dos homens, para colocar-me acima das outras árvores?’.

[[v7-9-10]]

^<<v7-9-10,10>>^ E as árvores disseram à figueira: ‘Vem tu e reina sobre nós!’

[[v7-9-11]]

^<<v7-9-11,11>>^ Mas a figueira disse-lhes: ‘Poderia eu, porventura, renunciar à doçura de meu delicioso fruto, para colocar-me acima das outras árvores?’.

[[v7-9-12]]

^<<v7-9-12,12>>^ E as árvores disseram à videira: ‘Vem tu, reina sobre nós!’.

[[v7-9-13]]

^<<v7-9-13,13>>^ Mas a videira respondeu: Poderia eu renunciar ao meu vinho que faz a alegria de Deus e dos homens, para colocar-me acima das outras árvores?’.

[[v7-9-14]]

^<<v7-9-14,14>>^ E todas as árvores disseram ao espinheiro: Vem tu, reina sobre nós!’.

[[v7-9-15]]

^<<v7-9-15,15>>^ E o espinheiro respondeu: ‘Se realmente me quereis escolher para reinar sobre vós, vinde e abrigai-vos debaixo de minha sombra; mas, se não o quereis, saia fogo do espinheiro e devore os cedros do Líbano!’.

[[v7-9-16]]

^<<v7-9-16,16>>^ Agora, pois, se com lealdade e boa-fé escolhestes Abimelec para vosso rei, se vos portastes bem com Jerobaal e sua casa, correspondendo aos benefícios que ele vos fez –

[[v7-9-17]]

^<<v7-9-17,17>>^ porque meu pai combateu por vós e livrou-vos dos madianitas arriscando a própria vida;

[[v7-9-18]]

^<<v7-9-18,18>>^ vós, que agora vos levantastes contra a casa de meu pai, matastes todos os seus setenta filhos sobre uma pedra e proclamastes rei dos habitantes de Siquém a Abimelec, filho de sua escrava, sob o pretexto de que ele é vosso irmão –,

[[v7-9-19]]

^<<v7-9-19,19>>^ se, pois, com lealdade e boa-fé procedestes bem com Jerobaal e sua casa, então que Abimelec vos faça felizes e que vós o façais feliz igualmente!

[[v7-9-20]]

^<<v7-9-20,20>>^ Do contrário, saia fogo de Abimelec e devore os homens de Siquém com os de Bet-Melo; e saia fogo dos habitantes de Siquém e de Bet-Melo e devore Abimelec!”.

[[v7-9-21]]

^<<v7-9-21,21>>^ Fugiu em seguida Joatão para Bera, onde habitou, longe de Abimelec, seu irmão.

[[v7-9-22]]

^<<v7-9-22,22>>^ Reinou Abimelec sobre Israel durante três anos.

[[v7-9-23]]

^<<v7-9-23,23>>^ E Deus suscitou um mau espírito entre ele e os habitantes de Siquém, que os fez se revoltarem.^&#42;1^

[[v7-9-24]]

^<<v7-9-24,24>>^ Isso aconteceu para que fosse vingado o homicídio dos setenta filhos de Jerobaal, e seu sangue caísse sobre Abimelec, seu irmão, que os havia matado, e sobre os siquemitas que tinham sido seus cúmplices.

[[v7-9-25]]

^<<v7-9-25,25>>^ Os homens de Siquém armaram contra ele emboscadas no alto dos montes e puseram-se a despojar todos aqueles que passavam por ali; e Abimelec foi informado disso.

[[v7-9-26]]

^<<v7-9-26,26>>^ Gaal, filho de Obed, foi com seus irmãos a Siquém e ganhou a confiança dos homens do lugar.

[[v7-9-27]]

^<<v7-9-27,27>>^ Saíram pelos campos, vindimaram as vinhas, pisaram as uvas, celebraram a festa. Foram ao templo do seu deus e ali fizeram um festim, amaldiçoando Abimelec.

[[v7-9-28]]

^<<v7-9-28,28>>^ Gaal, filho de Obed, disse: “Quem é Abimelec e o que é Siquém, para que lhe estejamos sujeitos? Não é ele filho de Jerobaal e não é Zebul o seu lugar-tenente? Servi a família de Emor, o pai de Siquém? Por que razão serviremos Abimelec?

[[v7-9-29]]

^<<v7-9-29,29>>^ Oxalá tivesse eu poder sobre esse povo! Eu arrasaria Abimelec e lhe diria: aumenta o teu exército e vem!”.

[[v7-9-30]]

^<<v7-9-30,30>>^ Zebul, governador da cidade, sabendo o que dissera Gaal, filho de Obed, encolerizou-se,

[[v7-9-31]]

^<<v7-9-31,31>>^ e mandou secretamente dizer a Abimelec: “Gaal, filho de Obed, veio a Siquém com seus irmãos e anda sublevando a cidade contra ti.

[[v7-9-32]]

^<<v7-9-32,32>>^ Levanta-te de noite tu e tua tropa e põe-te de emboscada no campo.

[[v7-9-33]]

^<<v7-9-33,33>>^ Amanhã cedo, ao nascer do sol, lança-te sobre a cidade; quando Gaal e sua tropa saírem contra ti, tu farás o que as circunstâncias te permitirem”.

[[v7-9-34]]

^<<v7-9-34,34>>^ Abimelec, pois, partiu durante a noite com toda a sua gente e pôs emboscadas em quatro grupos junto de Siquém.

[[v7-9-35]]

^<<v7-9-35,35>>^ Entretanto Gaal, filho de Obed, saiu e instalou-se diante das portas da cidade. Então, Abimelec com todos os seus deixou a emboscada.

[[v7-9-36]]

^<<v7-9-36,36>>^ Vendo aquela tropa, Gaal disse a Zebul: “Eis uma multidão que desce das colinas”. “Tu vês – respondeu Zebul – as sombras das colinas como se fossem homens.”

[[v7-9-37]]

^<<v7-9-37,37>>^ Gaal replicou: “Está descendo uma tropa do alto; e eis uma outra que vem pelo caminho do carvalho do Adivinho”.

[[v7-9-38]]

^<<v7-9-38,38>>^ Zebul disse-lhe então: “Onde está agora a tua arrogância, tu que dizias: ‘Quem é Abimelec para que nós o sirvamos?’. Eis o povo que tu desprezavas! Vai agora e combate contra ele!”.

[[v7-9-39]]

^<<v7-9-39,39>>^ Saiu Gaal à frente dos siquemitas e combateu contra Abimelec.

[[v7-9-40]]

^<<v7-9-40,40>>^ Mas foi derrotado por Abimelec e fugiu. Muitos homens, que estavam mortalmente feridos, caíram antes de terem atingido o limiar da porta.

[[v7-9-41]]

^<<v7-9-41,41>>^ Abimelec deteve-se em Aruma; Zebul, porém, lançou Gaal e seus irmãos fora de Siquém.

[[v7-9-42]]

^<<v7-9-42,42>>^ No dia seguinte, o povo saiu ao campo. Tendo sabido disso, Abimelec

[[v7-9-43]]

^<<v7-9-43,43>>^ tomou sua tropa, dividiu-a em três grupos e os pôs de emboscada no campo. Ao ver que o povo saía da cidade, atacou-o e derrotou-o,

[[v7-9-44]]

^<<v7-9-44,44>>^ vindo em seguida com o seu grupo tomar posição à entrada da cidade, enquanto os dois outros grupos perseguiam os que estavam no campo e os massacravam.

[[v7-9-45]]

^<<v7-9-45,45>>^ Abimelec combateu a cidade durante todo aquele dia e tomou-a. Matou toda a população, arrasou a cidade e semeou-a de sal.

[[v7-9-46]]

^<<v7-9-46,46>>^ Ao ouvirem isso, todos os habitantes da torre de Siquém retiraram-se para a fortaleza do templo de El-Berit.^&#42;1^

[[v7-9-47]]

^<<v7-9-47,47>>^ E foi noticiado a Abimelec que todos os habitantes da torre de Siquém se tinham retirado para esse lugar.

[[v7-9-48]]

^<<v7-9-48,48>>^ Subiu então Abimelec com sua tropa ao monte Selmon, tomou um machado e cortou um galho de árvore. Pondo-o aos ombros, disse à sua gente: “Vistes o que fiz? Apressai-vos a fazer o mesmo”.

[[v7-9-49]]

^<<v7-9-49,49>>^ Cortou cada um deles um galho e todos seguiram Abimelec; puseram esses galhos contra a fortaleza e puseram-lhes fogo, sendo a fortaleza, com todos os seus ocupantes, devorada pelas chamas. Desse modo pereceram todos os que habitavam na torre de Siquém, cerca de mil pessoas, tanto homens como mulheres.

[[v7-9-50]]

^<<v7-9-50,50>>^ Depois disso, Abimelec marchou contra Tebes. Assediou Tebes e a conquistou.

[[v7-9-51]]

^<<v7-9-51,51>>^ Havia no meio da cidade uma torre forte, na qual se tinham refugiado todos os habitantes, homens e mulheres. Fechando bem a porta, subiram ao terraço da torre.

[[v7-9-52]]

^<<v7-9-52,52>>^ Abimelec, chegando ao pé da torre, aproximou-se da porta para lhe pôr fogo.

[[v7-9-53]]

^<<v7-9-53,53>>^ Então uma mulher, lançando de cima uma pedra de moinho, feriu-lhe a cabeça, fraturando-lhe o crânio.

[[v7-9-54]]

^<<v7-9-54,54>>^ Chamou imediatamente seu escudeiro e disse-lhe: “Tira a tua espada e acaba de matar-me, para que se não diga que fui morto por uma mulher!”. Seu escudeiro o feriu e Abimelec morreu.

[[v7-9-55]]

^<<v7-9-55,55>>^ Morto Abimelec, todos os israelitas voltaram para suas casas.

[[v7-9-56]]

^<<v7-9-56,56>>^ Assim Deus fez recair sobre Abimelec o mal que tinha feito a seu pai, matando seus setenta irmãos.

[[v7-9-57]]

^<<v7-9-57,57>>^ E do mesmo modo Deus fez recair sobre os siquemitas os seus crimes. Assim se cumpriu sobre ele a maldição de Joatão, filho de Jerobaal.

'''

xref:007-juizes/007-juizes-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-juizes/007-juizes-010.adoc#v7-10-0[Próximo Capítulo &#62;]