include::./index.adoc[]

[[v7-2-0]]
=== Juízes, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Juízes 2 relata a morte de Josué e a falta de liderança que se seguiu, levando o povo à apostasia e idolatria. Deus se ira com a desobediência do povo e permite que eles sofram nas mãos de seus inimigos. Em resposta às suas orações, Deus levanta juízes para libertá-los da opressão.
* Deuteronômio 31:16: "E disse o Senhor a Moisés: Eis que tu estás para dormir com teus pais; e este povo se levantará, e se prostituirá com os deuses estranhos da terra, para onde vai, no meio dela; e me deixará, e anulará o meu pacto, que tenho feito com ele." Este versículo retrata a previsão de Deus de que o povo de Israel se afastaria Dele e se voltaria para os deuses estranhos, que é precisamente o que acontece em Juízes 2.
* Juízes 2:11-12: "Então, os filhos de Israel fizeram o que era mau aos olhos do Senhor e serviram aos baalins. E deixaram ao Senhor, Deus de seus pais, que os tinha tirado da terra do Egito, e foram após outros deuses, dentre os deuses dos povos que havia ao seu redor, e se prostraram a eles, e provocaram a ira do Senhor." Estes versículos são uma descrição direta da desobediência do povo de Israel a Deus e de como eles se voltaram para outros deuses, o que provocou a ira do Senhor.
* Juízes 2:14: "Então, a ira do Senhor se acendeu contra Israel, e ele os entregou nas mãos dos despojadores que os despojaram; e os vendeu nas mãos de seus inimigos ao redor, para que não pudessem mais resistir diante de seus inimigos." Aqui vemos a resposta de Deus à desobediência de Israel: Ele permite que eles sofram nas mãos de seus inimigos.
* Juízes 2:16: "E levantou o Senhor juízes que os livraram da mão daqueles que os despojaram." Aqui vemos a resposta de Deus às orações de Israel: Ele levanta juízes para libertá-los da opressão.
* 1 Samuel 12:10: "E clamaram ao Senhor e disseram: Pecamos, porque deixamos ao Senhor e servimos aos baalins e astarotes; agora, pois, livra-nos da mão de nossos inimigos, e te serviremos." Este versículo retrata a resposta correta do povo de Israel à opressão: eles clamam a Deus e se arrependem de sua desobediência, prometendo servi-lo.
****

[[v7-2-1]]

^<<v7-2-1,1>>^ O anjo do Senhor subiu de Gálgala a Boquim e disse: “Eu vos fiz subir do Egito e vos conduzi a esta terra que eu tinha prometido com juramento a vossos pais. E vos tinha dito: ‘Jamais hei de romper a aliança que fiz convosco;

[[v7-2-2]]

^<<v7-2-2,2>>^ vós, porém, não fareis aliança com os habitantes desta terra e lançareis por terra os seus altares!’. Ora, vós não obedecestes à minha voz.

[[v7-2-3]]

^<<v7-2-3,3>>^ Por que fizestes isso? Por essa razão eu disse: ‘Não os expulsarei de diante de vós; eles permanecerão ao vosso lado e os seus deuses vos serão um laço’.”

[[v7-2-4]]

^<<v7-2-4,4>>^ Ao dizer o anjo do Senhor essas palavras aos filhos de Israel, o povo pôs-se a chorar.

[[v7-2-5]]

^<<v7-2-5,5>>^ Pelo que chamaram àquele lugar Boquim, e ofereceram ali sacrifícios ao Senhor.^&#42;1^

[[v7-2-6]]

^<<v7-2-6,6>>^ Josué despediu o povo, e os israelitas foram cada um para a sua herança, a fim de tomar posse da terra.

[[v7-2-7]]

^<<v7-2-7,7>>^ Durante toda a vida de Josué e dos anciãos que lhe sobreviveram, e que tinham testemunhado a grande obra que o Senhor tinha feito em favor de Israel, o povo serviu o Senhor.

[[v7-2-8]]

^<<v7-2-8,8>>^ Josué, filho de Nun, servo do Senhor, morreu com a idade de cento e dez anos.

[[v7-2-9]]

^<<v7-2-9,9>>^ Sepultaram-no no território de sua possessão, em Tamnat-Hares, na montanha de Efraim, ao norte do monte de Gaás.

[[v7-2-10]]

^<<v7-2-10,10>>^ Toda aquela geração foi também se unir a seus pais, e sucedeu-lhe outra que não conhecia o Senhor, nem o que ele tinha feito em favor de Israel.

[[v7-2-11]]

^<<v7-2-11,11>>^ Os israelitas fizeram então o mal aos olhos do Senhor e serviram a Baal.^&#42;1^

[[v7-2-12]]

^<<v7-2-12,12>>^ Abandonaram o Senhor, Deus de seus pais, que os tinha tirado do Egito, e seguiram outros deuses, os dos povos que habitavam em torno deles; prostraram-se diante deles, excitando assim a cólera do Senhor.

[[v7-2-13]]

^<<v7-2-13,13>>^ Abandonaram o Senhor para servirem a Baal e às Astarot.^&#42;1^

[[v7-2-14]]

^<<v7-2-14,14>>^ A cólera do Senhor inflamou-se contra Israel, e ele entregou-os nas mãos de piratas, que os despojaram, e vendeu-os aos inimigos dos arredores, de sorte que não puderam mais resistir-lhes.

[[v7-2-15]]

^<<v7-2-15,15>>^ Para onde quer que fossem, a mão do Senhor estava contra eles para fazer-lhes mal, como o Senhor lhes tinha dito e jurado e, com isso, viram-se em grande aflição.

[[v7-2-16]]

^<<v7-2-16,16>>^ (Entretanto), o Senhor suscitava-lhes juízes que os livraram das mãos dos opressores,

[[v7-2-17]]

^<<v7-2-17,17>>^ mas nem mesmo os seus juízes ouviam e continuavam prostituindo-se a outros deuses, adorando-os. Abandonaram depressa o caminho que tinham seguido seus pais, na obediência aos mandamentos do Senhor e não os imitaram.

[[v7-2-18]]

^<<v7-2-18,18>>^ Ora, quando o Senhor suscitava juízes, ele estava com o juiz para livrá-los de seus inimigos enquanto vivesse o juiz: o Senhor compadecia-se dos gemidos que soltavam diante de seus inimigos e de seus opressores.

[[v7-2-19]]

^<<v7-2-19,19>>^ Mas, depois que o juiz morria, corrompiam-se e se tornavam ainda piores do que seus pais, seguindo outros deuses, servindo-os e adorando-os; e não renunciavam aos seus crimes e à sua obstinação.

[[v7-2-20]]

^<<v7-2-20,20>>^ Inflamou-se, pois, contra Israel a cólera do Senhor: “Visto que este povo violou o meu pacto – dizia ele – a aliança que eu tinha feito com seus pais, e não obedeceram à minha voz,

[[v7-2-21]]

^<<v7-2-21,21>>^ também eu não expulsarei de diante deles nenhuma das nações que Josué deixou ao morrer”.

[[v7-2-22]]

^<<v7-2-22,22>>^ Por elas, queria o Senhor provar os israelitas, e ver se eles seguiriam ou não o caminho do Senhor, como o tinham feito seus pais.

[[v7-2-23]]

^<<v7-2-23,23>>^ E o Senhor deixou subsistir todas essas nações que não tinha entregue nas mãos de Josué, e não as quis expulsar logo.

'''

xref:007-juizes/007-juizes-001.adoc#v7-1-0[&#60; Capítulo Anterior] | <<v7-2-0,Topo>> | xref:007-juizes/007-juizes-003.adoc#v7-3-0[Próximo Capítulo &#62;]