include::./index.adoc[]

[[v7-13-0]]
=== Juízes, 13
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 13 do livro de Juízes conta a história do nascimento de Sansão. Um anjo do Senhor apareceu à esposa de Manoá, que era estéril, e anunciou que ela daria à luz um filho que seria consagrado a Deus desde o ventre e começaria a libertar Israel do jugo dos filisteus. Depois disso, o anjo se foi e Manoá e sua esposa reconheceram que haviam visto o próprio Deus.
* Ezequiel 16:6: "E passei por ti, e te vi a revolver-te no teu sangue, e disse-te: Ainda que estejas no teu sangue, vive; sim, disse-te: Ainda que estejas no teu sangue, vive." Este versículo fala da misericórdia de Deus ao salvar alguém que estava à beira da morte, assim como Sansão foi escolhido por Deus antes mesmo de nascer.
* Isaías 49:1: "Ouvi-me, ilhas, e escutai, povos de longe: O SENHOR me chamou desde o ventre; desde as entranhas de minha mãe fez menção do meu nome." Este versículo mostra que Deus já tem um plano para a vida de alguém desde o ventre materno, assim como aconteceu com Sansão.
* Jeremias 1:5: "Antes que te formasse no ventre te conheci, e antes que saísses da madre te santifiquei; às nações te dei por profeta." Este versículo mostra que Deus tem um propósito para a vida de cada pessoa desde antes de seu nascimento, assim como com Sansão.
* Salmos 22:10: "Desde o ventre minha mãe me sustentaste; tu és aquele que me tiraste das entranhas de minha mãe; o meu louvor será sempre para ti." Este versículo fala da proteção e cuidado que Deus tem para com seus filhos, assim como aconteceu com Sansão desde antes de seu nascimento.
* Mateus 1:21: "E dará à luz um filho e chamarás o seu nome JESUS, porque ele salvará o seu povo dos seus pecados." Este versículo fala sobre o nascimento de Jesus, que também foi anunciado por um anjo e teve um propósito especial, assim como com Sansão.
****

[[v7-13-1]]

^<<v7-13-1,1>>^ Os israelitas continuaram a fazer o mal aos olhos do Senhor, que os entregou nas mãos dos filisteus durante quarenta anos.

[[v7-13-2]]

^<<v7-13-2,2>>^ Ora, havia em Saraá um homem da família dos danitas, chamado Manué. Sua mulher, sendo estéril, não tinha ainda gerado filhos.

[[v7-13-3]]

^<<v7-13-3,3>>^ O anjo do Senhor apareceu a essa mulher e disse-lhe: “Tu és estéril, e nunca tiveste filhos, mas conceberás e darás à luz um filho.

[[v7-13-4]]

^<<v7-13-4,4>>^ Toma, pois, muito cuidado de não beber doravante nem vinho, nem bebida forte. Não comas coisa alguma impura, porque vais conceber e dar à luz um filho.

[[v7-13-5]]

^<<v7-13-5,5>>^ A navalha não tocará a sua cabeça, porque esse menino será nazareno de Deus desde o seio de sua mãe. Será ele quem livrará Israel da mão dos filisteus”.^&#42;1^

[[v7-13-6]]

^<<v7-13-6,6>>^ A mulher foi ter com o seu marido: “Apresentou-se a mim um homem de Deus – disse ela – que tinha o aspecto de um anjo de Deus, em extremo terrível. Não lhe perguntei de onde era, nem ele me deu o seu nome,

[[v7-13-7]]

^<<v7-13-7,7>>^ mas disse-me: ‘Vais conceber e dar à luz um filho; não bebas, pois, nem vinho nem bebida forte e não comas coisa alguma impura, porque esse menino será nazareno desde o seio de sua mãe até o dia de sua morte’.”

[[v7-13-8]]

^<<v7-13-8,8>>^ Então Manué invocou o Senhor, dizendo: “Rogo-vos, Senhor, que o homem de Deus que nos enviastes volte novamente e nos ensine o que devemos fazer acerca do menino que há de nascer”.

[[v7-13-9]]

^<<v7-13-9,9>>^ Deus ouviu essa oração, e o anjo de Deus veio de novo visitar a mulher, quando esta se achava no campo; Manué, seu marido, não estava com ela.

[[v7-13-10]]

^<<v7-13-10,10>>^ Ela correu imediatamente a dar ao seu marido a notícia, dizendo: “O homem que vi outro dia apareceu-me novamente”.

[[v7-13-11]]

^<<v7-13-11,11>>^ Manué levantou-se e seguiu a sua mulher até junto do homem: “És tu – disse ele – o homem que falou à minha mulher?”.

[[v7-13-12]]

^<<v7-13-12,12>>^ “Sou eu mesmo” – respondeu o desconhecido. Manué replicou: “Quando se cumprir a tua palavra, de que maneira havemos de criar esse menino e o que teremos de fazer por ele?”.

[[v7-13-13]]

^<<v7-13-13,13>>^ O anjo do Senhor respondeu: “Abstenha-se tua mulher de tudo o que eu lhe disse.

[[v7-13-14]]

^<<v7-13-14,14>>^ Não prove nada do que venha da videira; não beba nem vinho, nem bebida forte, nada coma que seja impuro e observe tudo o que lhe prescrevi”.

[[v7-13-15]]

^<<v7-13-15,15>>^ Manué disse ao anjo do Senhor: “Rogo-te que te detenhas até que te ofereçamos um cabrito que vamos preparar”.

[[v7-13-16]]

^<<v7-13-16,16>>^ “Ainda que tu me retivesses – respondeu o anjo do Senhor – eu não comeria de tua mesa; mas se queres fazer um holocausto, oferece-o ao Senhor.” Manué ignorava que era o anjo do Senhor.

[[v7-13-17]]

^<<v7-13-17,17>>^ “Qual é o teu nome – perguntou-lhe ele – para que te honremos quando se cumprir tua promessa?”

[[v7-13-18]]

^<<v7-13-18,18>>^ O anjo do Senhor disse-lhe: “Por que me perguntas o meu nome? Ele é Magnífico”.

[[v7-13-19]]

^<<v7-13-19,19>>^ Tomou, pois, Manué o cabrito com uma oferta e ofereceu-o ao Senhor sobre a rocha. Coisa maravilhosa! Enquanto Manué e sua mulher olhavam

[[v7-13-20]]

^<<v7-13-20,20>>^ subir para o céu a chama do sacrifício que estava sobre o altar, viu que o anjo do Senhor subia na chama. À vista disso, Manué e sua mulher caíram com o rosto em terra.

[[v7-13-21]]

^<<v7-13-21,21>>^ E o anjo do Senhor desapareceu diante dos olhos de Manué e sua mulher. Manué compreendeu logo que era o anjo do Senhor,

[[v7-13-22]]

^<<v7-13-22,22>>^ e disse à sua mulher: “Vamos morrer seguramente, porque vimos Deus!”.

[[v7-13-23]]

^<<v7-13-23,23>>^ Sua mulher respondeu-lhe: “Se o Senhor nos quisesse matar, não teria aceito de nossas mãos o holocausto e a oferta; não nos teria mostrado tudo o que vimos, nem nos teria dito o que hoje nos revelou”.

[[v7-13-24]]

^<<v7-13-24,24>>^ Ela deu à luz um filho e pôs-lhe o nome de Sansão. O menino cresceu e o Senhor o abençoou.

[[v7-13-25]]

^<<v7-13-25,25>>^ E o Espírito do Senhor começou a incitá-lo, em Maané-Dã, entre Saraá e Estaol.

'''

xref:007-juizes/007-juizes-012.adoc#v7-12-0[&#60; Capítulo Anterior] | <<v7-13-0,Topo>> | xref:007-juizes/007-juizes-014.adoc#v7-14-0[Próximo Capítulo &#62;]