include::./index.adoc[]

[[v17-11-0]]
=== Tobias, 11
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Tobias 11 conta a história de Tobias e Sara se casando e a cura da cegueira do pai de Tobias por meio do uso do fel do peixe que ele havia capturado. Alguns temas que podem ser abordados nesse capítulo incluem o casamento, a cura divina e a importância de manter a fé em Deus. Abaixo estão cinco versículos relacionados a esses temas:
* Gênesis 2:24: "Por essa razão, o homem deixará pai e mãe e se unirá à sua mulher, e eles se tornarão uma só carne." Este versículo fala sobre o casamento e a união entre homem e mulher.
* Tiago 5:15: "E a oração feita com fé curará o doente, e o Senhor o levantará; e se tiver cometido pecados, ser-lhe-ão perdoados." Este versículo fala sobre a cura divina por meio da oração e da fé em Deus.
* Mateus 19:6: "Assim, já não são dois, mas uma só carne. Portanto, o que Deus uniu, ninguém o separe." Este versículo fala sobre a importância da união matrimonial e do compromisso entre o casal.
* João 14:1: "Não se turbe o vosso coração; credes em Deus, crede também em mim." Este versículo fala sobre manter a fé em Deus, mesmo diante de dificuldades e incertezas.
* Tiago 1:6: "Peça-a, porém, com fé, sem duvidar; pois aquele que duvida é semelhante à onda do mar, que é levada e agitada pelo vento." Este versículo fala sobre a importância de ter fé em Deus e não duvidar de sua capacidade de realizar milagres e curas.
****

[[v17-11-1]]

^<<v17-11-1,1>>^ De regresso, chegaram no décimo primeiro dia de viagem a Caserin, que está a meio caminho na direção de Nínive.^&#42;1^

[[v17-11-2]]

^<<v17-11-2,2>>^ O anjo disse então: “Tobias, meu irmão, tu sabes em que estado deixaste o teu pai.

[[v17-11-3]]

^<<v17-11-3,3>>^ Se for do teu agrado, poderíamos tomar a dianteira, deixando a tua mulher, os servos e os rebanhos seguirem devagar pelo caminho”.

[[v17-11-4]]

^<<v17-11-4,4>>^ Tendo Tobias concordado com esse parecer, Rafael disse-lhe: “Leva contigo o fel do peixe, porque vais precisar dele”. Tomou, pois, Tobias o fel e partiram.

[[v17-11-5]]

^<<v17-11-5,5>>^ Ana, por sua vez, ia todos os dias assentar-se perto do caminho, no cimo de uma colina, de onde podia ver ao longe.

[[v17-11-6]]

^<<v17-11-6,6>>^ Ela espreitava ali a volta de seu filho, quando o viu de longe que voltava e o reconheceu. Correu ao seu marido e disse-lhe: “Eis que aí vem o teu filho!”.

[[v17-11-7]]

^<<v17-11-7,7>>^ Ora, Rafael tinha dito a Tobias: “Logo que entrares em tua casa, adorarás o Senhor, teu Deus, e lhe darás graças. Irás em seguida beijar teu pai

[[v17-11-8]]

^<<v17-11-8,8>>^ e lhe porá imediatamente nos olhos o fel do peixe que tens contigo. Sabe que seus olhos se abrirão instantaneamente e que teu pai verá a luz do céu. E, vendo-te, ficará cheio de alegria”.

[[v17-11-9]]

^<<v17-11-9,9>>^ O cão, que os tinha acompanhado durante a viagem, correu então adiante como um mensageiro e mostrava o seu contentamento fazendo festas e abanando a cauda.

[[v17-11-10]]

^<<v17-11-10,10>>^ O pai cego levantou-se e pôs-se a correr, tropeçando. Dando então a mão a um criado, foi ao encontro de seu filho.

[[v17-11-11]]

^<<v17-11-11,11>>^ Abraçou-o e beijou-o, fazendo o mesmo sua mulher e ambos começaram a chorar de alegria.

[[v17-11-12]]

^<<v17-11-12,12>>^ Só se assentaram depois de terem adorado e agradecido a Deus.

[[v17-11-13]]

^<<v17-11-13,13>>^ Tobias tomou então o fel do peixe e o pôs nos olhos de seu pai.

[[v17-11-14]]

^<<v17-11-14,14>>^ Depois de ter esperado cerca de meia hora, começou a sair-lhe dos olhos uma belida branca como a membrana de um ovo.

[[v17-11-15]]

^<<v17-11-15,15>>^ Tobias tomou-a e a arrancou dos olhos de seu pai, o qual recobrou instantaneamente a vista.

[[v17-11-16]]

^<<v17-11-16,16>>^ E louvaram a Deus, ele, sua mulher e todos os que o conheciam.

[[v17-11-17]]

^<<v17-11-17,17>>^ “Bendigo-vos, Senhor, Deus de Israel” –, dizia ele – porque depois de me terdes provado, me salvastes: eis que vejo o meu filho Tobias!”

[[v17-11-18]]

^<<v17-11-18,18>>^ Sete dias depois, chegou também Sara, mulher de seu filho, com todos os seus servos, em boa saúde, com os rebanhos, os camelos, o grande dote da esposa e mais o dinheiro recebido de Gabael.

[[v17-11-19]]

^<<v17-11-19,19>>^ Tobias contou a seus pais todos os benefícios que Deus lhe tinha feito por intermédio de seu guia.

[[v17-11-20]]

^<<v17-11-20,20>>^ Chegaram também Aicar e Nadab, primos de Tobit, felizes de poderem congratular-se com ele pelos benefícios que Deus lhe tinha prodigalizado.^&#42;1^

[[v17-11-21]]

^<<v17-11-21,21>>^ Durante sete dias houve festa e grande regozijo.

'''

xref:017-tobias/017-tobias-010.adoc#v17-10-0[&#60; Capítulo Anterior] | <<v17-11-0,Topo>> | xref:017-tobias/017-tobias-012.adoc#v17-12-0[Próximo Capítulo &#62;]