include::./index.adoc[]

[[v17-2-0]]
=== Tobias, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* No capítulo 2 do livro de Tobias, vemos Tobias deixando sua casa e partindo em uma jornada para recuperar uma dívida de um amigo. Durante sua viagem, Tobias encontra um estranho que ele não reconhece como sendo um anjo disfarçado de Rafael. Juntos, eles viajam para a cidade de Media, onde Tobias recupera a dívida de seu amigo e encontra sua futura esposa, Sara. Aqui estão cinco versículos relacionados aos temas abordados em Tobias 2:
* Provérbios 16:7 - "Quando os caminhos de um homem agradam ao Senhor, até os seus inimigos fazem as pazes com ele." Tobias viajou em busca de uma dívida, mas seu comportamento virtuoso e piedoso resultou em uma bênção maior do que ele esperava.
* Isaías 41:10 - "Não tenha medo, pois estou com você; não tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa." Tobias enfrentou muitos desafios em sua jornada, mas ele confiou em Deus e foi recompensado por sua fé.
* Tiago 2:17 - "Da mesma forma, a fé por si só, sem obras, está morta." Tobias era um homem de fé, mas também estava disposto a agir em sua fé, como ao ajudar o cego em sua jornada.
* 1 Pedro 4:8 - "Acima de tudo, amem-se sinceramente uns aos outros, porque o amor cobre uma multidão de pecados." A esposa de Tobias, Sara, era atormentada por um demônio e, com a ajuda de Rafael, Tobias foi capaz de libertá-la. Esse amor e fidelidade um pelo outro foram fundamentais para superar esse desafio.
* Eclesiastes 3:1 - "Para tudo há uma ocasião certa; há um tempo certo para cada propósito debaixo do céu." A jornada de Tobias não foi fácil, mas ele foi recompensado por sua perseverança e paciência. Esses versículos mostram como a fé, a perseverança e a confiança em Deus podem ajudar a superar desafios e receber bênçãos além do esperado.
****

[[v17-2-1]]

^<<v17-2-1,1>>^ Algum tempo depois, em um dia de festa religiosa, foi preparado um grande banquete na casa de Tobit.

[[v17-2-2]]

^<<v17-2-2,2>>^ Ele disse então ao seu filho: “Vai buscar alguns homens piedosos de nossa tribo para comerem conosco”.

[[v17-2-3]]

^<<v17-2-3,3>>^ Ele saiu, mas logo voltou, anunciando ao pai que um dos filhos de Israel jazia degolado na praça. Tobit levantou-se imediatamente da mesa, sem nada haver comido e foi aonde estava o cadáver.

[[v17-2-4]]

^<<v17-2-4,4>>^ Tomou-o e levou-o clandestinamente para a sua casa, a fim de sepultá-lo com cuidado depois do sol posto.

[[v17-2-5]]

^<<v17-2-5,5>>^ Tendo escondido o cadáver, começou a comer com pranto e tremor,

[[v17-2-6]]

^<<v17-2-6,6>>^ lembrando-se do oráculo que o Senhor tinha pronunciado pela boca do profeta Amós: “Converterei vossas festas em luto, e vossos cânticos em elegias fúnebres” (Am 8,10a).

[[v17-2-7]]

^<<v17-2-7,7>>^ Quando o sol se pôs, ele foi e o sepultou.

[[v17-2-8]]

^<<v17-2-8,8>>^ Seus vizinhos criticavam-no unanimemente, dizendo: “Já uma vez ordenaram que te matassem, precisamente por isso e mal escapaste dessa sentença de morte, recomeças a enterrar os cadáveres!”.

[[v17-2-9]]

^<<v17-2-9,9>>^ Mas Tobit temia mais a Deus que ao rei e continuava a levar para a sua casa os corpos daqueles que eram assassinados, onde os escondia e os inumava durante a noite.

[[v17-2-10]]

^<<v17-2-10,10>>^ Ora, aconteceu que um dia, cansado desse trabalho, foi para a sua casa e deitou-se junto à parede onde adormeceu.

[[v17-2-11]]

^<<v17-2-11,11>>^ Enquanto dormia, caiu-lhe, de um ninho de andorinhas, esterco quente nos olhos e ele tornou-se cego.

[[v17-2-12]]

^<<v17-2-12,12>>^ Deus permitiu que lhe acontecesse essa prova, para que a sua paciência, como a do santo homem Jó, servisse de exemplo à posteridade.

[[v17-2-13]]

^<<v17-2-13,13>>^ Como havia sempre temido a Deus, desde a sua infância e guardado seus mandamentos, ele não se afligiu (nem murmurou) contra Deus por ter sido atingido pela cegueira.

[[v17-2-14]]

^<<v17-2-14,14>>^ Mas perseverou firme no temor de Deus e continuou a dar-lhe graças em todos os dias de sua vida.

[[v17-2-15]]

^<<v17-2-15,15>>^ Assim como o bem-aventurado Jó foi insultado por outros chefes, assim seus parentes e amigos escarneciam de seu comportamento:

[[v17-2-16]]

^<<v17-2-16,16>>^ “Onde está – diziam eles – essa esperança por cujo amor deste esmolas e sepultaste os mortos?”.

[[v17-2-17]]

^<<v17-2-17,17>>^ Porém, Tobit repreendia-os, dizendo: “Não faleis assim;

[[v17-2-18]]

^<<v17-2-18,18>>^ somos filhos dos santos (patriarcas) e esperamos aquela vida que Deus há de dar aos que não perdem jamais a sua confiança nele”.^&#42;1^

[[v17-2-19]]

^<<v17-2-19,19>>^ Ora, Ana, sua mulher, ia todos os dias tecer e trazia o que ela ganhava com o trabalho de suas mãos.

[[v17-2-20]]

^<<v17-2-20,20>>^ Foi assim que, tendo trazido para casa um cabrito que recebera (como gratificação),

[[v17-2-21]]

^<<v17-2-21,21>>^ seu marido ouviu-o balir e disse: “Vê que ele não tenha sido roubado; restitui-o ao seu proprietário, porque não nos é permitido comer e nem mesmo tocar, o que foi roubado”.

[[v17-2-22]]

^<<v17-2-22,22>>^ Ao que lhe respondeu sua mulher com indignação: “Tua esperança é manifestamente vã; agora tuas esmolas mostram bem o que valem!”. Com essas e outras palavras semelhantes ela censurava-o duramente.

'''

xref:017-tobias/017-tobias-001.adoc#v17-1-0[&#60; Capítulo Anterior] | <<v17-2-0,Topo>> | xref:017-tobias/017-tobias-003.adoc#v17-3-0[Próximo Capítulo &#62;]