include::./index.adoc[]

[[v17-8-0]]
=== Tobias, 8
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* No capítulo 8 do livro de Tobias, Tobias e Sara se casam e oferecem uma oração a Deus. Os versículos a seguir estão relacionados aos temas deste capítulo:
* Gênesis 2:24: "Por isso deixará o homem a seu pai e a sua mãe, e unir-se-á à sua mulher, e serão ambos uma carne." Este versículo fala sobre a união matrimonial, que é o que acontece entre Tobias e Sara em Tobias 8.
* Eclesiastes 9:9: "Goza a vida com a mulher que amas, todos os dias da tua vida vã, os quais Deus te deu debaixo do sol, todos os dias da tua vaidade; porque esta é a tua porção nesta vida, e no teu trabalho, que tu fizeste debaixo do sol." Este versículo fala sobre desfrutar a vida com a esposa, o que é o que Tobias e Sara fazem ao se casarem.
* Provérbios 5:18-19: "Seja bendito o teu manancial, e alegra-te com a mulher da tua mocidade. Como cerva amorosa, e gazela graciosa, os seus seios te saciem todo o tempo; e pelo seu amor sejas atraído perpetuamente." Este versículo fala sobre a alegria e satisfação que se pode encontrar no casamento.
* Eclesiástico 26:1-4: "Feliz é o marido de uma boa mulher, porque o número dos seus dias será em dobro. Uma mulher virtuosa alegra seu marido, e ele cumprirá os dias de sua vida em paz. Uma boa mulher é uma boa parte de sua herança, dada em graça aos que temem ao Senhor. Rico ou pobre, o coração do marido está contente, e em todo tempo seu rosto é alegre." Este versículo fala sobre a importância de encontrar uma esposa virtuosa e como ela pode trazer felicidade e paz ao marido.
* Efésios 5:25-28: "Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja, e a si mesmo se entregou por ela, a fim de a santificar, tendo-a purificado por meio da lavagem de água pela palavra, para a apresentar a si mesmo igreja gloriosa, sem mácula, nem ruga, nem coisa semelhante, mas santa e irrepreensível. Assim devem os maridos amar a suas próprias mulheres, como a seus próprios corpos. Quem ama a sua mulher, ama-se a si mesmo." Este versículo fala sobre o amor que um marido deve ter por sua esposa, assim como Cristo amou a igreja.
****

[[v17-8-1]]

^<<v17-8-1,1>>^ Depois do jantar, introduziram o jovem no aposento de Sara.

[[v17-8-2]]

^<<v17-8-2,2>>^ E Tobias, fiel às indicações do anjo, tirou do seu alforje uma parte do fígado e o pôs sobre brasas acesas.

[[v17-8-3]]

^<<v17-8-3,3>>^ Nesse momento, o anjo Rafael tomou o demônio e prendeu-o no deserto do Alto Egito.

[[v17-8-4]]

^<<v17-8-4,4>>^ Então, Tobias encorajou a jovem com estas palavras: “Levanta-te, Sara, e roguemos a Deus, hoje, amanhã e depois de amanhã. Estaremos unidos a Deus durante essas três noites. Depois da terceira noite, consumaremos nossa união;

[[v17-8-5]]

^<<v17-8-5,5>>^ porque somos filhos dos santos patriarcas e não nos devemos casar como os pagãos que não conhecem a Deus”.

[[v17-8-6]]

^<<v17-8-6,6>>^ Levantaram-se, pois, ambos e oraram juntos fervorosamente para que lhes fosse conservada a vida.

[[v17-8-7]]

^<<v17-8-7,7>>^ Tobias disse: “Senhor, Deus de nossos pais, bendigam-vos o céu, a terra, o mar, as fontes e os rios, com todas as criaturas que neles existem.

[[v17-8-8]]

^<<v17-8-8,8>>^ Vós fizestes Adão do limo da terra e destes-lhe Eva por companheira.

[[v17-8-9]]

^<<v17-8-9,9>>^ Ora, vós sabeis, ó Senhor, que não é para satisfazer a minha paixão que recebo a minha prima como esposa, mas unicamente com o desejo de suscitar uma posteridade, pela qual o vosso nome seja eternamente bendito”.

[[v17-8-10]]

^<<v17-8-10,10>>^ E Sara acrescentou: “Tende piedade de nós, Senhor; tende piedade de nós e fazei que cheguemos juntos a uma ditosa velhice!”.

[[v17-8-11]]

^<<v17-8-11,11>>^ Ora, ao cantar do galo, Raguel chamou os seus criados e foram juntos cavar uma sepultura.

[[v17-8-12]]

^<<v17-8-12,12>>^ “Quem sabe – dizia ele – se não aconteceu a esse o mesmo que aos outros sete homens que se aproximaram dela?”

[[v17-8-13]]

^<<v17-8-13,13>>^ Cavada a fossa, voltou para junto de sua mulher e disse:

[[v17-8-14]]

^<<v17-8-14,14>>^ “Manda uma de tuas escravas ver se ele morreu, a fim de que eu possa enterrá-lo antes de clarear o dia”.

[[v17-8-15]]

^<<v17-8-15,15>>^ Ela o fez. E a serva, tendo entrado no aposento, encontrou-os bem vivos, dormindo juntos.

[[v17-8-16]]

^<<v17-8-16,16>>^ Ela voltou e deu essa boa notícia; e Raguel com sua mulher louvaram o Senhor, dizendo:

[[v17-8-17]]

^<<v17-8-17,17>>^ “Nós vos bendizemos, Senhor, Deus de Israel, porque não se realizou o que temíamos.

[[v17-8-18]]

^<<v17-8-18,18>>^ Usastes conosco de vossa misericórdia, expulsando para longe de nós o inimigo que nos perseguia,

[[v17-8-19]]

^<<v17-8-19,19>>^ e tivestes piedade de dois filhos únicos. Fazei, ó Senhor, que eles vos bendigam sempre mais e vos ofereçam um sacrifício de louvor pela sua conservação, a fim de que todas as nações pagãs conheçam que vós sois o único Deus de toda a terra”.

[[v17-8-20]]

^<<v17-8-20,20>>^ Raguel ordenou imediatamente aos seus criados que fechassem a cova, antes do amanhecer.

[[v17-8-21]]

^<<v17-8-21,21>>^ Disse à sua mulher que aprontasse um banquete e preparasse todos os víveres necessários aos viajantes.

[[v17-8-22]]

^<<v17-8-22,22>>^ Mandou também matar duas vacas gordas e quatro carneiros, destinados a um festim para todos os seus vizinhos e amigos.

[[v17-8-23]]

^<<v17-8-23,23>>^ E instou com Tobias que ficasse com ele durante duas semanas.

[[v17-8-24]]

^<<v17-8-24,24>>^ Presenteou Tobias com a metade de seus bens e redigiu um documento estipulando que a outra metade se tornaria também, depois de sua morte, propriedade de Tobias.

'''

xref:017-tobias/017-tobias-007.adoc#v17-7-0[&#60; Capítulo Anterior] | <<v17-8-0,Topo>> | xref:017-tobias/017-tobias-009.adoc#v17-9-0[Próximo Capítulo &#62;]