include::./index.adoc[]

[[v72-1-0]]
=== São Judas, 1
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* São Judas 1 trata principalmente sobre a necessidade de se defender a fé cristã contra os falsos ensinamentos e os falsos mestres que estavam infiltrados na comunidade cristã. É enfatizado o perigo dessas pessoas que distorcem a verdade e corrompem a fé dos crentes. Abaixo estão cinco versículos da Bíblia que tratam de temas relacionados ao livro de São Judas:
* 2 Pedro 2:1: "Entretanto, surgiram falsos profetas no meio do povo, como também surgirão entre vós falsos mestres, os quais introduzirão, dissimuladamente, heresias destruidoras, até ao ponto de renegarem o Soberano Senhor que os resgatou, trazendo sobre si mesmos repentina destruição." Este versículo fala sobre o surgimento de falsos mestres e profetas, assim como descrito em São Judas 1, que introduzem heresias que podem corromper a fé dos crentes.
* 1 João 4:1: "Amados, não creiais a todo espírito, mas provai se os espíritos vêm de Deus; porque muitos falsos profetas têm saído pelo mundo fora." Este versículo exorta os cristãos a examinar cuidadosamente as doutrinas que são apresentadas a eles e a testar os espíritos, para evitar serem enganados por falsos profetas.
* Mateus 7:15: "Acautelai-vos dos falsos profetas, que se vos apresentam disfarçados em ovelhas, mas por dentro são lobos roubadores." Este versículo adverte os crentes a estarem atentos aos falsos profetas, que podem parecer inofensivos, mas na verdade estão disfarçados para enganá-los.
* 1 Timóteo 4:1: "O Espírito Santo afirma expressamente que, nos últimos tempos, alguns apostatarão da fé, por obedecerem a espíritos enganadores e a ensinos de demônios." Este versículo alerta sobre a possibilidade de alguns abandonarem a fé por causa de doutrinas falsas e ensinos enganosos.
* 2 Coríntios 11:13-15: "Porque tais falsos apóstolos são obreiros fraudulentos, transfigurando-se em apóstolos de Cristo. E não é de admirar, porque o próprio Satanás se transfigura em anjo de luz. Não é muito, pois, que os seus próprios ministros se transfigurem em ministros da justiça; e o fim deles será conforme as suas obras." Este versículo descreve os falsos apóstolos e ministros que se disfarçam como trabalhadores da justiça, mas na verdade são fraudulentos e seguem os ensinamentos de Satanás.
****

[[v72-1-1]]

^<<v72-1-1,1>>^ Judas, servo de Jesus Cristo e irmão de Tiago, aos eleitos bem-amados em Deus Pai e reservados para Jesus Cristo.

[[v72-1-2]]

^<<v72-1-2,2>>^ Que a misericórdia, a paz e o amor se realizem em vós copiosamente.

[[v72-1-3]]

^<<v72-1-3,3>>^ Caríssimos, estando eu muito preocupado em vos escrever a respeito da nossa comum salvação, senti a necessidade de dirigir-vos esta carta para exortar-vos a pelejar pela fé, confiada de uma vez para sempre aos santos.

[[v72-1-4]]

^<<v72-1-4,4>>^ Pois certos homens ímpios se introduziram furtivamente entre nós, os quais desde muito tempo estão destinados para este julgamento; eles transformam em dissolução a graça de nosso Deus e negam Jesus Cristo, nosso único Mestre e Senhor.

[[v72-1-5]]

^<<v72-1-5,5>>^ Quisera trazer-vos à memória, embora saibais todas estas coisas: o Senhor, depois de ter salvo o povo da terra do Egito, fez em seguida perecer os incrédulos.

[[v72-1-6]]

^<<v72-1-6,6>>^ Os anjos que não tinham guardado a dignidade de sua classe, mas abandonado os seus tronos, ele os guardou com laços eternos nas trevas para o julgamento do Grande Dia.

[[v72-1-7]]

^<<v72-1-7,7>>^ Da mesma forma Sodoma, Gomorra e as cidades circunvizinhas, que praticaram as mesmas impurezas e se entregaram a vícios contra a natureza, jazem lá como exemplo, sofrendo a pena do fogo eterno.

[[v72-1-8]]

^<<v72-1-8,8>>^ Assim também estes homens, em seu louco desvario, contaminam igualmente a carne, desprezam a soberania e maldizem as glórias.^&#42;1^

[[v72-1-9]]

^<<v72-1-9,9>>^ Ora, quando o arcanjo Miguel discutia com o demônio e lhe disputava o corpo de Moisés, não ousou fulminar contra ele uma sentença de execração, mas disse somente: Que o próprio Senhor te repreenda!^&#42;1^

[[v72-1-10]]

^<<v72-1-10,10>>^ Estes, porém, falam mal do que ignoram. Encontram eles a sua perdição naquilo que não conhecem, senão de um modo natural, à maneira dos animais destituídos de razão.

[[v72-1-11]]

^<<v72-1-11,11>>^ Ai deles, porque andaram pelo caminho de Caim, e por amor do lucro caíram no erro de Balaão e pereceram na revolta de Coré.^&#42;1^

[[v72-1-12]]

^<<v72-1-12,12>>^ Esses fazem escândalos nos vossos ágapes. Banqueteiam-se convosco despudoradamente e se saciam a si mesmos. São nuvens sem água, que os ventos levam! Árvores de fim de outono, sem fruto, duas vezes mortas, desarraigadas!

[[v72-1-13]]

^<<v72-1-13,13>>^ Ondas furiosas do mar, que arrojam as espumas da sua torpeza! Estrelas errantes, para as quais está reservada a escuridão das trevas para toda a eternidade!

[[v72-1-14]]

^<<v72-1-14,14>>^ Também Henoc, que foi o oitavo patriarca depois de Adão, profetizou a respeito deles, dizendo: Eis que veio o Senhor entre milhares de seus santos^&#42;1^

[[v72-1-15]]

^<<v72-1-15,15>>^ para julgar a todos e confundir a todos os ímpios por causa das obras de impiedade que praticaram, e por causa de todas as palavras injuriosas que eles, ímpios, têm proferido contra Deus.

[[v72-1-16]]

^<<v72-1-16,16>>^ Estes são murmuradores descontentes, homens que vivem segundo as suas paixões, cuja boca profere palavras soberbas e que admiram os demais por interesse.

[[v72-1-17]]

^<<v72-1-17,17>>^ Mas vós, caríssimos, lembrai-vos das palavras que vos foram preditas pelos apóstolos de nosso Senhor Jesus Cristo,

[[v72-1-18]]

^<<v72-1-18,18>>^ os quais vos diziam: “No fim dos tempos virão impostores, que viverão segundo as suas ímpias paixões;

[[v72-1-19]]

^<<v72-1-19,19>>^ homens que semeiam a discórdia, homens sensuais que não têm o Espírito”.^&#42;1^

[[v72-1-20]]

^<<v72-1-20,20>>^ Mas vós, caríssimos, edificai-vos mutuamente sobre o fundamento da vossa santíssima fé. Orai no Espírito Santo.

[[v72-1-21]]

^<<v72-1-21,21>>^ Conservai-vos no amor de Deus, aguardando a misericórdia de nosso Senhor Jesus Cristo, para a vida eterna.

[[v72-1-22]]

^<<v72-1-22,22>>^ Para com uns exercei a vossa misericórdia, repreendendo-os,^&#42;1^

[[v72-1-23]]

^<<v72-1-23,23>>^ e salvai-os, arrebatando-os do fogo. Dos demais tende compaixão, repassada de temor, detestando até a túnica manchada pela carne.

[[v72-1-24]]

^<<v72-1-24,24>>^ Àquele, que é poderoso para nos preservar de toda queda e nos apresentar diante de sua glória, imaculados e cheios de alegria,

[[v72-1-25]]

^<<v72-1-25,25>>^ ao Deus único, Salvador nosso, por Jesus Cristo, Senhor nosso, sejam dadas glória, magnificência, império e poder desde antes de todos os tempos, agora e para sempre. Amém.

'''

xref:071-iii-sao-joao/071-iii-sao-joao-001.adoc#v71-1-0[&#60; Capítulo Anterior] | <<v72-1-0,Topo>> | xref:073-apocalipse/073-apocalipse-001.adoc#v73-1-0[Próximo Capítulo &#62;]