include::./index.adoc[]

[[v12-10-0]]
=== II Reis, 10
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 10 de 2 Reis narra a vingança de Jeú contra a descendência de Acabe e Jezabel, incluindo a execução dos setenta filhos de Acabe e a matança dos adoradores de Baal em Israel. Jeú é retratado como um líder implacável e zeloso, mas também como alguém que se desvia da Lei de Deus em sua busca pelo poder. A seguir, estão cinco versículos que tratam dos temas presentes nesse capítulo:
* Salmos 94:1: "Ó Senhor Deus, a quem a vingança pertence, ó Deus, a quem a vingança pertence, mostra-te resplandecente!" Esse salmo clama pela justiça divina e pela vingança contra os ímpios que oprimem os justos. O desejo de Jeú de punir os adoradores de Baal pode ser visto como uma busca pela justiça divina, mas suas ações também podem ser vistas como excessivamente violentas.
* Jeremias 9:24: "Mas o que se gloriar, glorie-se nisto: em me entender e me conhecer, que eu sou o Senhor, que faço beneficência, juízo e justiça na terra; porque destas coisas me agrado, diz o Senhor." Esse versículo destaca a importância do conhecimento e compreensão de Deus e de suas ações. Jeú pode ter se desviado da Lei de Deus em sua busca pelo poder e vingança, e isso pode ser visto como uma falta de compreensão da vontade divina.
* Provérbios 28:1: "O ímpio foge, sem que haja ninguém a persegui-lo; mas o justo está confiante como um leão." Esse provérbio enfatiza a confiança e segurança dos justos, mesmo diante de ameaças e perseguições. Jeú pode ser visto como alguém que busca a segurança e o poder por meio da eliminação de seus inimigos, enquanto os justos confiam em Deus e em sua proteção.
* Isaías 59:7-8: "Os seus pés correm para o mal, e se apressam para derramarem o sangue inocente; os seus pensamentos são pensamentos de iniquidade; destruição e quebrantamento há nas suas estradas. Não conhecem caminho de paz, nem há justiça nos seus caminhos; torcem as suas veredas para eles mesmos; qualquer que anda por elas não tem conhecimento da paz." Esses versículos descrevem a maldade dos ímpios e sua falta de conhecimento da paz e da justiça. A busca de Jeú pela vingança e poder pode ser vista como uma manifestação dessa maldade e ignorância.
* Ezequiel 18:30: "Portanto, eu vos julgarei a cada um conforme os seus caminhos, ó casa de Israel, diz o Senhor Deus. Tornai-vos e convertei-vos de todas as vossas transgressões, para que a iniquidade não vos leve à perdição." Esse versículo destaca a importância do arrependimento e da conversão diante do julgamento divino. A busca de Jeú pela justiça pode ser vista como positiva, mas sua falta de arrependimento e conversão em relação à sua violência e desvio da Lei de Deus pode ser vista como uma falha em seguir o caminho da justiça divina. Assim, esse versículo destaca a importância de reconhecer as próprias transgressões e buscar a mudança de comportamento, para evitar a perdição e o julgamento divino.
****

[[v12-10-1]]

^<<v12-10-1,1>>^ Havia em Samaria setenta filhos de Acab. Jeú escreveu uma carta e mandou-a à Samaria aos magistrados da cidade, aos anciãos e aos preceptores dos filhos de Acab.

[[v12-10-2]]

^<<v12-10-2,2>>^ Dizia na carta: “Logo que receberdes esta carta, vós que tendes convosco os filhos de vosso soberano, como também carros, cavalos, uma cidade fortificada e armas,

[[v12-10-3]]

^<<v12-10-3,3>>^ escolhei o melhor e o mais qualificado dos filhos de vosso soberano e ponde-o no trono de seu pai. Em seguida, começai a luta pela casa de vosso soberano”.

[[v12-10-4]]

^<<v12-10-4,4>>^ Eles, porém, muito atemorizados, disseram: “Dois reis não o puderam enfrentar, como poderíamos nós resistir-lhe?”.

[[v12-10-5]]

^<<v12-10-5,5>>^ O prefeito do palácio, o comandante da cidade, os anciãos e os preceptores dos filhos de Acab mandaram a Jeú a seguinte resposta: “Nós somos teus servos. Faremos tudo o que nos disseres; não elegeremos rei sobre nós. Faze como melhor te parecer”.

[[v12-10-6]]

^<<v12-10-6,6>>^ Escreveu-lhes Jeú uma segunda carta, na qual dizia: “Se estais do meu lado, se quereis obedecer às minhas ordens, tomai as cabeças dos filhos de vosso soberano e apresentai-vos a mim amanhã a esta hora em Jezrael”. Os filhos do rei, que eram em número de setenta, encontravam-se na casa dos grandes da cidade, que os educavam.

[[v12-10-7]]

^<<v12-10-7,7>>^ Logo que lhes chegou a carta de Jeú, tomaram os setenta príncipes e os massacraram. Puseram em seguida as suas cabeças em cestos e as mandaram a Jeú, em Jezrael.

[[v12-10-8]]

^<<v12-10-8,8>>^ Um mensageiro viera anunciar que tinham trazido as cabeças dos filhos do rei. Jeú disse: “Colocai-as em dois montes, à porta da cidade até amanhã cedo”.

[[v12-10-9]]

^<<v12-10-9,9>>^ Chegando a manhã, saiu e, diante de todo o povo, disse: “Vós sois justos. Eu conspirei contra o meu soberano e o matei. Mas, estes aqui, quem os feriu?

[[v12-10-10]]

^<<v12-10-10,10>>^ Ficai, pois, sabendo que não se perde nenhuma das palavras pronunciadas pelo Senhor contra a casa de Acab. O Senhor realizou o que ele havia predito pelo seu servo Elias”.

[[v12-10-11]]

^<<v12-10-11,11>>^ Jeú feriu também todos os que restavam da casa de Acab em Jezrael, todos os seus principais oficiais, seus servos e seus sacerdotes, sem deixar sobreviver um sequer dentre eles.

[[v12-10-12]]

^<<v12-10-12,12>>^ Depois encaminhou-se para a Samaria. Chegando a Bet-Equed-Haroim, que está junto do caminho,

[[v12-10-13]]

^<<v12-10-13,13>>^ encontrou os irmãos de Ocozias, rei de Judá, e perguntou-lhes: “Quem sois vós?”. “Nós somos irmãos de Ocozias” – responderam eles –. “Descemos para fazer uma visita aos filhos do rei e aos filhos da rainha.”

[[v12-10-14]]

^<<v12-10-14,14>>^ Jeú ordenou: “Tomai-os vivos!”. Eles os prenderam vivos e os massacraram junto da cisterna de Bet-Equed. De quarenta e dois que eram, Jeú não deixou sobreviver um sequer.

[[v12-10-15]]

^<<v12-10-15,15>>^ Deixando aquele lugar, Jeú encontrou Jonadab, filho de Recab, que vinha ao seu encontro. E saudou-o, dizendo: “Teu coração é leal para comigo, como o é o meu para contigo?”. “Sim” – respondeu Jonadab –. “Então, dá-me tua mão.” Ele deu a mão, e então Jeú fê-lo montar no seu carro junto dele.

[[v12-10-16]]

^<<v12-10-16,16>>^ Disse-lhe: “Vem comigo e verás o zelo que tenho pelo Senhor”.

[[v12-10-17]]

^<<v12-10-17,17>>^ E levou-o em seu carro. Tendo entrado em Samaria, exterminou todos os que restavam da casa de Acab. E destruiu-a completamente, como o Senhor tinha dito a Elias.

[[v12-10-18]]

^<<v12-10-18,18>>^ Jeú convocou todo o povo e dirigiu-lhe a palavra nestes termos: “Acab serviu um pouco a Baal, Jeú o servirá muito mais.

[[v12-10-19]]

^<<v12-10-19,19>>^ Convocai junto de mim todos os profetas de Baal, todos os seus fiéis, todos os seus sacerdotes. Não falte um só deles, pois quero oferecer a Baal um grande sacrifício. Todo aquele que faltar perderá a vida”. Mas isso era simplesmente um laço, para destruir todos os adoradores de Baal.

[[v12-10-20]]

^<<v12-10-20,20>>^ Depois dessa publicação, Jeú deu esta ordem: “Publicai uma assembleia solene em honra de Baal”.

[[v12-10-21]]

^<<v12-10-21,21>>^ Depois mandou mensageiros por todo o Israel para chamá-los e os adoradores de Baal compareceram todos; não faltou nenhum. Reuniram-se no templo de Baal, que ficou lotado de uma extremidade à outra.

[[v12-10-22]]

^<<v12-10-22,22>>^ Jeú disse ao guarda do vestiário: “Dá vestes a todos os adoradores de Baal”. O guarda distribuiu vestes a todos eles.

[[v12-10-23]]

^<<v12-10-23,23>>^ Jeú entrou no templo com Jonadab, filho de Recab e disse aos adoradores de Baal: “Vede bem que não haja convosco nenhum dos que servem ao Senhor, mas somente os adoradores de Baal”.

[[v12-10-24]]

^<<v12-10-24,24>>^ Eles entraram, pois, para oferecer sacrifícios e holocaustos. Ora, Jeú postara oitenta homens do lado de fora e dissera-lhes: “Aquele dentre vós que deixar escapar um só destes homens que entrego nas vossas mãos, responderá com a própria vida pela do outro”.

[[v12-10-25]]

^<<v12-10-25,25>>^ Terminados os holocaustos, ordenou Jeú aos guardas e aos oficiais: “Entrai e feri-os! Não deixeis escapar nenhum deles!”. E assim caíram todos a fio de espada. Depois disso, os guardas e oficiais lançaram fora os cadáveres, entraram no santuário do templo de Baal,

[[v12-10-26]]

^<<v12-10-26,26>>^ tiraram dali o ídolo e o queimaram.

[[v12-10-27]]

^<<v12-10-27,27>>^ Derrubaram a estela de Baal e demoliram o templo, transformando-o em privadas, que existem ainda hoje.

[[v12-10-28]]

^<<v12-10-28,28>>^ Foi assim que Jeú exterminou Baal de Israel.

[[v12-10-29]]

^<<v12-10-29,29>>^ Todavia, não se desviou dos pecados de Jeroboão, filho de Nabat, que levara Israel ao pecado, pois deixou subsistir os bezerros de ouro de Betel e de Dã.

[[v12-10-30]]

^<<v12-10-30,30>>^ O Senhor disse-lhe: “Pois que fizeste o que é agradável aos meus olhos, tratando a casa de Acab como eu o queria, teus filhos ocuparão o trono de Israel durante quatro gerações”.

[[v12-10-31]]

^<<v12-10-31,31>>^ Entretanto, Jeú não cuidou de seguir de todo o coração a Lei do Senhor, Deus de Israel. Não se desviou dos pecados que Jeroboão levara Israel a cometer.

[[v12-10-32]]

^<<v12-10-32,32>>^ Por aquele tempo, o Senhor começou a diminuir o território de Israel. Hazael derrotou-o em toda a fronteira,

[[v12-10-33]]

^<<v12-10-33,33>>^ desde o Jordão até o oriente. Submeteu toda a terra de Galaad, os gadenses, os rubenitas e os manasseítas, desde Aroer, que estava sobre a torrente do Arnon, isto é, a terra de Galaad e Basã.

[[v12-10-34]]

^<<v12-10-34,34>>^ O restante da história de Jeú, tudo o que ele fez, todos os seus feitos, tudo se acha consignado no Livro das Crônicas dos reis de Israel.

[[v12-10-35]]

^<<v12-10-35,35>>^ Jeú adormeceu com seus pais e foi sepultado em Samaria. Seu filho Joacaz sucedeu-lhe no trono.

[[v12-10-36]]

^<<v12-10-36,36>>^ Jeú reinou vinte e oito anos em Samaria.

'''

xref:012-ii-reis/012-ii-reis-009.adoc#v12-9-0[&#60; Capítulo Anterior] | <<v12-10-0,Topo>> | xref:012-ii-reis/012-ii-reis-011.adoc#v12-11-0[Próximo Capítulo &#62;]