include::./index.adoc[]

[[v12-19-0]]
=== II Reis, 19
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 19 de 2 Reis narra a história do rei Ezequias, que recebeu uma carta ameaçadora do rei da Assíria, Senaqueribe, ordenando que ele se rendesse ou enfrentasse a destruição. Ezequias buscou ajuda em Deus e recebeu a resposta do profeta Isaías, que assegurou que Deus protegeria Jerusalém. Deus cumpriu sua promessa, e um anjo do Senhor matou 185.000 soldados assírios durante a noite. Abaixo estão cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em 2 Reis 19:
* Salmos 20:7-8: "Uns confiam em carros, outros em cavalos, mas nós faremos menção do nome do Senhor nosso Deus. Uns encurvam-se e caem, mas nós nos levantamos e estamos de pé." Este salmo destaca a importância de confiar em Deus em tempos de crise, em vez de depender de recursos humanos ou materiais.
* Isaías 37:35: "Porque eu defenderei esta cidade, para a livrar, por amor de mim e por amor do meu servo Davi." Este versículo é parte da resposta de Deus ao rei Ezequias, assegurando que ele protegeria Jerusalém dos assírios por causa de sua fidelidade e do seu amor por Davi.
* Salmos 91:11-12: "Porque aos seus anjos dará ordem a teu respeito, para te guardarem em todos os teus caminhos. Eles te sustentarão nas suas mãos, para que não tropeces com o teu pé em pedra." Este salmo destaca a proteção de Deus sobre aqueles que o amam e confiam nele.
* Isaías 54:17: "Nenhuma arma forjada contra ti prosperará; e toda a língua que se levantar contra ti em juízo, tu a condenarás; esta é a herança dos servos do Senhor, e a sua justiça que de mim procede, diz o Senhor." Este versículo destaca a promessa de proteção de Deus para aqueles que o servem, e a garantia de que qualquer acusação injusta contra eles será refutada.
* 2 Timóteo 4:18: "E o Senhor me livrará de toda a obra maligna, e me levará salvo para o seu reino celestial; a quem seja glória para todo o sempre. Amém." Este versículo destaca a confiança do apóstolo Paulo na proteção e livramento de Deus em meio às suas tribulações, uma confiança que também foi demonstrada pelo rei Ezequias em 2 Reis 19.
****

[[v12-19-1]]

^<<v12-19-1,1>>^ Ouvindo isso, o rei Ezequias rasgou as vestes, cobriu-se de um saco e foi ao Templo do Senhor.

[[v12-19-2]]

^<<v12-19-2,2>>^ Mandou o prefeito do palácio, Eliacim, o escriba Sobna e os deões dos sacerdotes, revestidos de sacos, ao profeta Isaías, filho de Amós,

[[v12-19-3]]

^<<v12-19-3,3>>^ para dizer-lhe: “Eis o que diz Ezequias: ‘Hoje é um dia de angústia, de castigo e de opróbrio. Os filhos estão a ponto de nascer e não há força para dá-los à luz.

[[v12-19-4]]

^<<v12-19-4,4>>^ O Senhor, teu Deus, talvez tenha ouvido as palavras do copeiro-mor, enviado pelo rei da Assíria, seu soberano, para insultar o Deus vivo e talvez o castigue pelas palavras que ele ouviu. Roga, pois, por esse resto que ainda subsiste!”.

[[v12-19-5]]

^<<v12-19-5,5>>^ Os servos do rei Ezequias foram ter com Isaías e este lhes respondeu: “Eis o que diz o Senhor:

[[v12-19-6]]

^<<v12-19-6,6>>^ ‘Não te assustes com as palavras que ouviste e com os ultrajes que proferiram contra mim os servos do rei da Assíria.

[[v12-19-7]]

^<<v12-19-7,7>>^ Vou enviar ao rei um espírito que, ao receber uma certa notícia, o fará voltar à sua terra, onde o farei perecer pela espada’.”

[[v12-19-8]]

^<<v12-19-8,8>>^ O copeiro-mor, sabendo que o rei da Assíria tinha deixado Laquis, voltou para junto do seu soberano e o encontrou sitiando Lebna.

[[v12-19-9]]

^<<v12-19-9,9>>^ O rei ouviu dizer de Taraca, rei da Etiópia: “Ele acaba de sair para combater contra ti”. Senaquerib mandou novamente mensageiros a Ezequias para dizer-lhe:

[[v12-19-10]]

^<<v12-19-10,10>>^ “Isto direis a Ezequias, rei de Judá: ‘Não te deixes enganar pelo Deus, no qual puseste a tua confiança, pensando que Jerusalém não será entregue nas mãos do rei da Assíria.

[[v12-19-11]]

^<<v12-19-11,11>>^ Ouviste contar como os reis da Assíria trataram todos os países e como os devastaram: só tu, pois, haverias de escapar?

[[v12-19-12]]

^<<v12-19-12,12>>^ As nações que meus antepassados aniquilaram, Gozã, Harã, Resef e os filhos de Eden, que estavam em Telasar, foram, porventura, libertados pelos seus deuses?

[[v12-19-13]]

^<<v12-19-13,13>>^ Onde estão o rei de Emat, o rei de Arfad, os reis de Sefarvaim, de Ana e de Ava?’.”

[[v12-19-14]]

^<<v12-19-14,14>>^ Ezequias tomou a carta das mãos dos mensageiros e a leu. Depois subiu ao templo e abriu-a diante do Senhor,

[[v12-19-15]]

^<<v12-19-15,15>>^ rogando-lhe: “Senhor, Deus de Israel, que estais sentado sobre querubins, só vós sois o Deus de todos os reinos da terra. Vós fizestes o céu e a terra.

[[v12-19-16]]

^<<v12-19-16,16>>^ Inclinai, Senhor, os vossos ouvidos e ouvi! Abri, Senhor, os vossos olhos e vede! Ouvi a mensagem de Senaquerib, que mandou blasfemar o Deus vivo!

[[v12-19-17]]

^<<v12-19-17,17>>^ É verdade, Senhor, que os reis da Assíria destruíram as nações e devastaram os seus territórios,

[[v12-19-18]]

^<<v12-19-18,18>>^ atirando ao fogo os seus deuses, mas isso porque não eram deuses e sim objetos feitos pelas mãos do homem, objetos de madeira e de pedra; por isso, foram destruídos.

[[v12-19-19]]

^<<v12-19-19,19>>^ Mas vós, Senhor, nosso Deus, salvai-nos agora das mãos de Senaquerib, a fim de que todos os povos da terra saibam que vós, o Senhor, sois o único Deus”.

[[v12-19-20]]

^<<v12-19-20,20>>^ Isaías, filho de Amós, mandou dizer a Ezequias: “Eis o que diz o Senhor, Deus de Israel: Ouvi a oração que me fizeste a respeito de Senaquerib, rei da Assíria.

[[v12-19-21]]

^<<v12-19-21,21>>^ Eis o oráculo do Senhor contra ele: A virgem, filha de Sião, despreza-te e zomba de ti. A filha de Jerusalém meneia a cabeça por trás de ti.

[[v12-19-22]]

^<<v12-19-22,22>>^ A quem insultaste e ultrajaste? Contra quem elevaste a voz e olhaste por cima dos ombros? Contra o Santo de Israel!^&#42;1^

[[v12-19-23]]

^<<v12-19-23,23>>^ Por meio de teus mensageiros insultaste o Senhor e disseste: ‘Com a multidão dos meus carros subirei ao cimo dos montes, aos cumes longínquos do Líbano. Abaterei os seus cedros mais altos, seus ciprestes mais belos. Penetrarei até os últimos limites do seu bosque mais espesso.

[[v12-19-24]]

^<<v12-19-24,24>>^ Cavarei e beberei água estrangeira. Com a planta de meus pés ressecarei todos os canais do Egito’.

[[v12-19-25]]

^<<v12-19-25,25>>^ Ignoras que desde o princípio preparei o que acontecerá? Desde tempos remotos decidi o que agora realizarei: Reduzirei cidades fortificadas a ruínas e escombros.

[[v12-19-26]]

^<<v12-19-26,26>>^ Seus habitantes ficarão sem forças; serão tomados de pavor e confusão, ficarão semelhantes à erva das pastagens, ao capim dos telhados, aos frutos atingidos pela longa estiagem.

[[v12-19-27]]

^<<v12-19-27,27>>^ Eu sei quando te sentas, quando sais e quando entras; e conheço teus furores contra mim.

[[v12-19-28]]

^<<v12-19-28,28>>^ Porque ficaste furioso contra mim, e subiram aos meus ouvidos as tuas insolências, porei argola em teu nariz e freio em tua boca, e te forçarei a voltar pelo caminho por onde vieste.

[[v12-19-29]]

^<<v12-19-29,29>>^ E eis o que te servirá de sinal: Neste ano se come restolhos; no ano que vem, aquilo que nascer sozinho; no terceiro ano, porém, semeareis e colhereis, plantareis vinhas e comereis os seus frutos.

[[v12-19-30]]

^<<v12-19-30,30>>^ O resto, que subsistir da casa de Judá, lançará novas raízes no solo e produzirá frutos no alto.

[[v12-19-31]]

^<<v12-19-31,31>>^ Pois de Jerusalém surgirá um resto e do monte Sião sobreviventes. Eis o que fará o zelo do Senhor dos exércitos.

[[v12-19-32]]

^<<v12-19-32,32>>^ Por isso, eis o oráculo do Senhor ao rei da Assíria: Não entrará nesta cidade nem atirará flechas contra ela, não lhe oporá escudo nem a cercará de trincheiras.

[[v12-19-33]]

^<<v12-19-33,33>>^ Mas voltará pelo caminho por onde veio, sem entrar na cidade – oráculo do Senhor.

[[v12-19-34]]

^<<v12-19-34,34>>^ Protegerei esta cidade para salvá-la, por minha causa e de Davi, meu servo”.

[[v12-19-35]]

^<<v12-19-35,35>>^ Ora, nessa mesma noite o anjo do Senhor apareceu no campo dos assírios e feriu cento e oitenta e cinco mil homens. No dia seguinte, pela manhã, só havia cadáveres.^&#42;1^

[[v12-19-36]]

^<<v12-19-36,36>>^ Senaquerib, rei da Assíria, retirou-se, tomou o caminho de sua terra e deteve-se em Nínive.

[[v12-19-37]]

^<<v12-19-37,37>>^ Certo dia, estando ele prostrado no templo de Nesroc, seu deus, seus filhos Adramelec e Sarasar o assassinaram a golpes de espada e fugiram para a terra de Ararat. Seu filho Asaradon sucedeu-lhe no trono.

'''

xref:012-ii-reis/012-ii-reis-018.adoc#v12-18-0[&#60; Capítulo Anterior] | <<v12-19-0,Topo>> | xref:012-ii-reis/012-ii-reis-020.adoc#v12-20-0[Próximo Capítulo &#62;]