include::./index.adoc[]

[[v12-17-0]]
=== II Reis, 17
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 17 do livro de 2 Reis descreve a queda do reino de Israel, que havia se afastado de Deus e adotado práticas pagãs. Em consequência, o povo foi deportado para a Assíria e outras nações foram assentadas em sua terra. Abaixo estão cinco versículos de outros livros da Bíblia que se relacionam com os temas abordados em 2 Reis 17:
* Deuteronômio 28:64: "E o Senhor vos espalhará entre todos os povos, desde uma extremidade da terra até à outra." Este versículo prevê que, se o povo de Israel se afastar de Deus, ele será disperso entre as nações.
* Salmos 106:34-35: "Não destruíram os povos que o Senhor lhes tinha dito; antes se misturaram com os gentios, e aprenderam as suas obras." Este salmo narra a história de Israel desde a libertação do Egito até a época dos reis, e destaca a tendência do povo de se desviar de Deus e seguir as práticas pagãs das nações vizinhas.
* Jeremias 3:6-7: "Disse o Senhor nos dias do rei Josias: Viste o que fez Israel, a adúltera, como ela se foi sobre todo o monte alto e debaixo de toda a árvore verde." Este versículo destaca a infidelidade de Israel a Deus, e a tendência do povo de buscar a adoração de ídolos em lugares altos e debaixo de árvores.
* Oséias 10:1: "Israel era uma videira luxuriante, que dava frutos para si mesmo. Conforme a abundância dos seus frutos, assim multiplicou os altares; conforme a bondade da sua terra, assim fizeram boas as suas estátuas." Este versículo descreve a prosperidade material de Israel, que levou o povo a multiplicar seus altares e estátuas de ídolos.
* Amós 5:26-27: "Mas levastes o tabernáculo de vosso Moloch, e a imagem das vossas imagens, a estrela do vosso deus, que fizestes para vós mesmos. Portanto vos levarei cativos, além de Damasco, diz o Senhor, cujo nome é Deus dos Exércitos." Este versículo se refere à adoração de ídolos em Israel, incluindo a veneração da estrela de deus de Remfã, o que contribuiu para a queda do reino de Israel.
****

[[v12-17-1]]

^<<v12-17-1,1>>^ No décimo segundo ano do reinado de Acaz, rei de Judá, Oseias, filho de Ela, tornou-se rei de Israel em Samaria. Seu reinado durou nove anos.

[[v12-17-2]]

^<<v12-17-2,2>>^ Fez o mal aos olhos do Senhor, mas não tanto como seus predecessores no trono de Israel.

[[v12-17-3]]

^<<v12-17-3,3>>^ Salmanasar, rei da Assíria, atacou-o e Oseias ficou-lhe submisso, pagando-lhe tributo.

[[v12-17-4]]

^<<v12-17-4,4>>^ Mas tendo o rei da Assíria descoberto uma conspiração tramada por Oseias, o qual enviara mensageiros a Sais, rei do Egito, e cessara de pagar o tributo anual ao rei da Assíria, tomou-o e o pôs em grilhões numa prisão.

[[v12-17-5]]

^<<v12-17-5,5>>^ Depois atacou Samaria e assediou-a por três anos.

[[v12-17-6]]

^<<v12-17-6,6>>^ No ano nono do reinado de Oseias, o rei da Assíria apoderou-se de Samaria e deportou os israelitas para a Assíria, estabelecendo-os em Hala, às margens do Habor, rio de Gozã, e nas cidades da Média.

[[v12-17-7]]

^<<v12-17-7,7>>^ Assim aconteceu porque os filhos de Israel tinham pecado contra o Senhor, seu Deus, que os tinha tirado do Egito e libertado da opressão do faraó, rei dos egípcios. Eles adoraram outros deuses,

[[v12-17-8]]

^<<v12-17-8,8>>^ adotaram os costumes das nações que o Senhor tinha expulsado diante dos israelitas e seguiram os costumes estabelecidos pelos reis de Israel.

[[v12-17-9]]

^<<v12-17-9,9>>^ Os israelitas ofenderam o Senhor, seu Deus, com ações más e estabeleceram lugares altos em todas as suas localidades, desde a simples torre de guarda até a cidade fortificada.

[[v12-17-10]]

^<<v12-17-10,10>>^ Erigiram estelas e ídolos asserás em todos os outeiros e debaixo de toda árvore frondosa.

[[v12-17-11]]

^<<v12-17-11,11>>^ Queimaram incenso nesses lugares altos, como as nações que o Senhor tinha despojado diante deles e irritaram o Senhor com suas práticas abomináveis,

[[v12-17-12]]

^<<v12-17-12,12>>^ adorando ídolos, embora o Senhor lhes tivesse dito: “Não fareis tal coisa”.

[[v12-17-13]]

^<<v12-17-13,13>>^ O Senhor tinha advertido Israel e Judá pela boca de seus profetas e videntes: “Renunciai às vossas más ações; guardai meus mandamentos e minhas leis; observai toda a lei que prescrevi a vossos pais e que vos transmiti pelos meus servos, os profetas”.

[[v12-17-14]]

^<<v12-17-14,14>>^ Mas eles não o quiseram ouvir e endureceram o seu coração, como o tinham feito seus pais, que se tornaram infiéis ao Senhor, seu Deus.

[[v12-17-15]]

^<<v12-17-15,15>>^ Desprezaram os seus preceitos e a aliança estabelecida com seus pais, não atenderam às advertências que lhes tinha feito e seguiram as vaidades, tornando-se eles mesmos vaidades; apesar de ter-lhes o Senhor proibido seguir as pisadas dos povos que os cercavam,

[[v12-17-16]]

^<<v12-17-16,16>>^ abandonaram todos os mandamentos do Senhor, seu Deus, fabricaram para si dois bezerros de metal fundido e ídolos asserás, prostraram-se diante de todo o exército dos céus, prestaram culto a Baal,

[[v12-17-17]]

^<<v12-17-17,17>>^ fizeram passar pelo fogo seus filhos e filhas, entregaram-se à adivinhação, à bruxaria; enfim, abandonaram-se inteiramente a tudo o que desagradava ao Senhor, irritando-o.

[[v12-17-18]]

^<<v12-17-18,18>>^ Por isso, o Senhor ficou profundamente indignado contra os israelitas e lançou-os para longe de sua face. Só a tribo de Judá subsistiu.

[[v12-17-19]]

^<<v12-17-19,19>>^ Mas nem mesmo Judá observou os mandamentos do Senhor, seu Deus, e seguiu os costumes de Israel.

[[v12-17-20]]

^<<v12-17-20,20>>^ O Senhor rejeitou, pois, toda a linhagem de Israel, humilhou-a e a entregou nas mãos dos saqueadores até que fosse completamente banida de sua presença.

[[v12-17-21]]

^<<v12-17-21,21>>^ Israel tinha se separado da casa de Davi e tinha proclamado como seu rei a Jeroboão, filho de Nabat, que desviara o seu povo do culto do Senhor e o fizera cair num grande pecado.

[[v12-17-22]]

^<<v12-17-22,22>>^ Os israelitas andaram em todos os pecados que Jeroboão tinha cometido e não se afastaram deles,

[[v12-17-23]]

^<<v12-17-23,23>>^ até o dia em que o Senhor os baniu de sua presença, como tinha anunciado pela boca dos profetas, seus servos. Os israelitas foram, pois, deportados para longe de sua terra, para a Assíria, onde ainda estão atualmente.

[[v12-17-24]]

^<<v12-17-24,24>>^ O rei da Assíria mandou vir gente da Babilônia, de Cuta, de Ava, de Emat, de Sefarvaim e os estabeleceu nas cidades de Samaria no lugar dos israelitas. Estes colonos tomaram posse da Samaria e instalaram-se em suas cidades.

[[v12-17-25]]

^<<v12-17-25,25>>^ Mas como eles não prestavam culto ao Senhor, quando começaram a habitar ali, o Senhor mandou leões contra eles que os devoravam.

[[v12-17-26]]

^<<v12-17-26,26>>^ Foram então avisar o rei da Assíria: “Os povos que transferiste para as cidades da Samaria não sabem como honrar o deus daquela terra. Por isso, esse deus mandou contra eles leões que os devoram, porque ignoram o culto do deus da terra”.

[[v12-17-27]]

^<<v12-17-27,27>>^ O rei da Assíria ordenou o seguinte: “Mandai para lá um dos sacerdotes que deportastes, a fim de que ele se estabeleça ali e ensine ao povo a maneira de servir o deus da região”.

[[v12-17-28]]

^<<v12-17-28,28>>^ Foi, pois, um dos sacerdotes deportados da Samaria e instalou-se em Betel, onde ensinava ao povo como devia adorar o Senhor.

[[v12-17-29]]

^<<v12-17-29,29>>^ Apesar disso cada nação conservou o seu próprio deus, que colocou nos santuários dos lugares altos estabelecidos pelos samaritanos. Cada povo colocou os seus deuses no lugar em que habitava.

[[v12-17-30]]

^<<v12-17-30,30>>^ Os babilônios fizeram uma estátua de Sucot-Benot; os de Cuta, uma de Nergel; os de Emat, uma de Asima;

[[v12-17-31]]

^<<v12-17-31,31>>^ os de Ava, uma de Nebaaz e uma de Tartac; os de Sefarvaim queimavam seus filhos em honra de Adramelec e de Anamelec, seus deuses.

[[v12-17-32]]

^<<v12-17-32,32>>^ Adoravam também o Senhor, mas constituíram sacerdotes para os lugares altos, tirados dentre o povo, os quais oficiavam por eles nos santuários dos lugares altos.

[[v12-17-33]]

^<<v12-17-33,33>>^ Desse modo, adoravam o Senhor e ao mesmo tempo prestavam culto aos seus próprios deuses, segundo o costume das nações de onde tinham sido transportados.

[[v12-17-34]]

^<<v12-17-34,34>>^ Ainda hoje seguem os seus antigos costumes. Não temem o Senhor, não observam suas leis, nem suas ordenações, nem a lei e os mandamentos que o Senhor deu aos filhos de Jacó, a quem deu o nome de Israel.

[[v12-17-35]]

^<<v12-17-35,35>>^ O Senhor tinha feito com eles uma aliança e lhes tinha dado a seguinte ordem: “Não adorareis outros deuses, nem vos prostrareis diante deles. Não lhes prestareis culto e não lhes oferecereis sacrifícios.

[[v12-17-36]]

^<<v12-17-36,36>>^ Mas temei ao Senhor que vos tirou do Egito com o poder de seu braço. A ele temereis, diante dele vos prostrareis e a ele oferecereis os vossos sacrifícios.

[[v12-17-37]]

^<<v12-17-37,37>>^ Obedecereis sempre e cuidadosamente os preceitos, os estatutos, a lei e os mandamentos que ele vos deu por escrito. Não adorareis outros deuses.

[[v12-17-38]]

^<<v12-17-38,38>>^ Não vos esquecereis do tratado que fiz convosco: não adorareis outros deuses.

[[v12-17-39]]

^<<v12-17-39,39>>^ Ao Senhor, vosso Deus, temereis e ele vos livrará das mãos de todos os vossos inimigos”.

[[v12-17-40]]

^<<v12-17-40,40>>^ Eles, porém, não obedeceram e seguiram os seus antigos costumes.

[[v12-17-41]]

^<<v12-17-41,41>>^ Adoraram o Senhor, mas honravam ao mesmo tempo os seus ídolos. Ainda hoje fazem seus filhos e seus netos como fizeram seus pais.

'''

xref:012-ii-reis/012-ii-reis-016.adoc#v12-16-0[&#60; Capítulo Anterior] | <<v12-17-0,Topo>> | xref:012-ii-reis/012-ii-reis-018.adoc#v12-18-0[Próximo Capítulo &#62;]