include::./index.adoc[]

[[v12-12-0]]
=== II Reis, 12
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* Descobrimos em 2 Reis 12 que o sumo sacerdote Joiada convocou os sacerdotes para arrecadar dinheiro do povo e consertar o templo do Senhor, que estava em estado de deterioração. Abaixo estão cinco versículos bíblicos relacionados aos temas abordados neste capítulo:
* Deuteronômio 15:10: "Certamente, lhe darás, e não será mau grado no teu coração, quando lhe deres; pois, por isso, te abençoará o Senhor, teu Deus, em toda a tua obra e em tudo o que empreenderes." Esse versículo destaca a importância de ser generoso e ajudar os outros sem relutância, o que se relaciona com o espírito de contribuição para a reforma do templo que é apresentado em 2 Reis 12.
* Provérbios 3:9-10: "Honra ao Senhor com os teus bens e com as primícias de toda a tua renda; e se encherão fartamente os teus celeiros, e transbordarão de vinho os teus lagares." Esse versículo destaca a importância de honrar o Senhor com as nossas riquezas e ofertas. Essa atitude é ilustrada em 2 Reis 12, onde o dinheiro arrecadado é usado para o conserto do templo.
* 1 Coríntios 16:2: "No primeiro dia da semana, cada um de vós ponha de parte o que puder ajuntar, conforme a sua prosperidade, para que não se façam coletas quando eu chegar." Esse versículo destaca a importância de planejar nossas ofertas e contribuições com antecedência. Em 2 Reis 12, vemos um exemplo dessa prática quando o sumo sacerdote convoca os sacerdotes para arrecadar dinheiro para o templo.
* Malaquias 3:10: "Trazei todos os dízimos à casa do tesouro, para que haja mantimento na minha casa; e provai-me nisto, diz o Senhor dos Exércitos, se eu não vos abrir as janelas do céu e não derramar sobre vós bênção sem medida." Esse versículo destaca a importância de trazer nossos dízimos e ofertas para a casa do Senhor. Isso se relaciona com o esforço de Joiada para arrecadar dinheiro e consertar o templo em 2 Reis 12.
* 2 Coríntios 9:7: "Cada um contribua segundo propôs no seu coração, não com tristeza ou por necessidade; porque Deus ama ao que dá com alegria." Esse versículo destaca a importância de dar com alegria e gratidão. Isso se relaciona com o espírito de generosidade e gratidão que é apresentado em 2 Reis 12, quando o povo contribui para o conserto do templo.
****

[[v12-12-1]]

^<<v12-12-1,1>>^ Joás tinha sete anos quando subiu ao trono. Começou a reinar no sétimo ano de Jeú e reinou durante quarenta anos em Jerusalém. Sua mãe chamava-se Sébia e era natural de Bersabeia.

[[v12-12-2]]

^<<v12-12-2,2>>^ Joás fez o que era bom aos olhos do Senhor, durante todo o tempo em que esteve sob a direção do sacerdote Joiada.

[[v12-12-3]]

^<<v12-12-3,3>>^ Todavia, não destruiu os lugares altos e ali o povo continuava sacrificando e queimando incenso.

[[v12-12-4]]

^<<v12-12-4,4>>^ Joás disse aos sacerdotes: “Todo o dinheiro consagrado que for trazido ao Templo do Senhor, assim como o dinheiro que for entregue por todo israelita recenseado e o que provir do resgate das pessoas, após avaliação, como também os dons espontâneos oferecidos ao Templo do Senhor,

[[v12-12-5]]

^<<v12-12-5,5>>^ recebam-no os sacerdotes, cada um receba-o dos seus clientes e empreguem-no na reparação do edifício, onde quer que se façam necessários”.

[[v12-12-6]]

^<<v12-12-6,6>>^ Ora, no vigésimo terceiro ano do reinado de Joás, os sacerdotes não tinham ainda feito restauração alguma no templo.

[[v12-12-7]]

^<<v12-12-7,7>>^ O rei chamou o sacerdote Joiada e os outros sacerdotes e disse-lhes: “Por que não fazeis vós a reparação do templo? Doravante não recebereis mais o dinheiro de vossos clientes, mas o entregareis para os reparos do templo”.

[[v12-12-8]]

^<<v12-12-8,8>>^ Os sacerdotes consentiram em não mais receber o dinheiro do povo e declinaram do cargo das reparações do edifício.

[[v12-12-9]]

^<<v12-12-9,9>>^ O sacerdote Joiada tomou um cofre, fez-lhe um buraco na tampa e colocou-o junto do altar, à direita da entrada do Templo do Senhor. Os sacerdotes que guardavam a entrada do templo ali depositavam todo o dinheiro que era levado ao Templo do Senhor.

[[v12-12-10]]

^<<v12-12-10,10>>^ Quando viam que havia muito dinheiro no cofre, vinha um escriba do rei com o sumo sacerdote, que recolhia e contava todo o dinheiro que se encontrava no Templo do Senhor.

[[v12-12-11]]

^<<v12-12-11,11>>^ E uma vez pesado o dinheiro, era o mesmo entregue nas mãos dos que presidiam as obras do Templo do Senhor que com ele pagavam os carpinteiros e operários que trabalhavam nas reparações, bem como

[[v12-12-12]]

^<<v12-12-12,12>>^ os pedreiros e canteiros, comprando a madeira e as pedras de cantaria necessárias às reparações e cobrindo todas as despesas decorrentes dos trabalhos.

[[v12-12-13]]

^<<v12-12-13,13>>^ Não se faziam, porém, com esse dinheiro que era trazido ao Templo do Senhor, taças, nem facas, nem bacias, nem trombetas, nem utensílio algum de ouro ou de prata;

[[v12-12-14]]

^<<v12-12-14,14>>^ mas era dado aos empreiteiros, que o empregavam nas reparações do Templo do Senhor.

[[v12-12-15]]

^<<v12-12-15,15>>^ Não se pediam contas àqueles que recebiam o dinheiro destinado à paga dos operários, porque eram homens honestos.

[[v12-12-16]]

^<<v12-12-16,16>>^ Quanto ao dinheiro dos sacrifícios pelos delitos ou pelos pecados, não era levado à casa do Senhor, mas era dos sacerdotes.

[[v12-12-17]]

^<<v12-12-17,17>>^ Naquele tempo, Hazael, rei da Síria, sitiou Gat e apoderou-se dela. Depois foi atacar Jerusalém.

[[v12-12-18]]

^<<v12-12-18,18>>^ Porém, Joás, rei de Judá, tomando os objetos sagrados oferecidos pelos seus pais, Josafá, Jorão e Ocozias, reis de Judá, e os que ele mesmo tinha oferecido, assim como todo o ouro que se achava nas reservas do Templo do Senhor e do palácio real, mandou tudo isso a Hazael, rei da Síria, o qual desistiu de sua campanha contra Jerusalém.

[[v12-12-19]]

^<<v12-12-19,19>>^ O restante da história de Joás, seus atos e seus grandes feitos, tudo se acha consignado no Livro das Crônicas dos reis de Judá.

[[v12-12-20]]

^<<v12-12-20,20>>^ Seus servos levantaram-se, fizeram uma conspiração e assassinaram o rei em Bet-Melo, no declive de Sela.

[[v12-12-21]]

^<<v12-12-21,21>>^ Josacar, filho de Semaat e Jozabad, filho de Somer, seus criados, o feriram de morte. Joás foi sepultado com seus pais na Cidade de Davi. Seu filho Amasias sucedeu-lhe no trono.

'''

xref:012-ii-reis/012-ii-reis-011.adoc#v12-11-0[&#60; Capítulo Anterior] | <<v12-12-0,Topo>> | xref:012-ii-reis/012-ii-reis-013.adoc#v12-13-0[Próximo Capítulo &#62;]