include::./index.adoc[]

[[v12-6-0]]
=== II Reis, 6
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 6 de 2 Reis conta a história do profeta Eliseu e seus discípulos, que vivem cercados de conflitos e desafios em meio a uma sociedade dividida e em guerra. Em meio a essas dificuldades, eles aprendem a confiar em Deus e a enfrentar as adversidades com coragem e fé. Abaixo estão cinco versículos da Bíblia que se relacionam com os temas abordados em 2 Reis 6:
* Salmos 34:7: "O anjo do Senhor acampa-se ao redor dos que o temem, e os livra." Esse versículo fala sobre a proteção divina que está disponível para aqueles que confiam em Deus. Assim como Eliseu e seus discípulos foram protegidos dos inimigos, podemos confiar que Deus também nos protege em meio aos nossos próprios desafios e conflitos.
* Isaías 41:10: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a minha destra fiel." Este versículo traz uma mensagem de coragem e conforto para aqueles que enfrentam dificuldades. Ele nos lembra que Deus está conosco em todas as situações e que podemos encontrar força e ajuda nele.
* Filipenses 4:13: "Posso todas as coisas naquele que me fortalece." Essa passagem nos lembra que, com a ajuda de Deus, podemos enfrentar qualquer desafio. Como Eliseu e seus discípulos, podemos encontrar a força e a coragem necessárias para perseverar, mesmo em momentos de dificuldade e incerteza.
* Romanos 8:28: "Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito." Esse versículo nos lembra que Deus tem um propósito para as nossas vidas e que todas as coisas que acontecem podem ser usadas para o nosso bem. Mesmo em meio a situações difíceis, podemos confiar que Deus está trabalhando para cumprir seus planos em nossas vidas.
* Provérbios 3:5-6: "Confie no Senhor de todo o seu coração e não se apóie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." Essa passagem nos lembra da importância de confiar em Deus e buscar sua sabedoria em todas as áreas da nossa vida. Em 2 Reis 6, Eliseu e seus discípulos confiaram em Deus para ajudá-los a enfrentar os desafios que enfrentaram. Podemos aprender com eles e também buscar a orientação divina em nossas próprias lutas e conflitos.
****

[[v12-6-1]]

^<<v12-6-1,1>>^ Os filhos dos profetas disseram a Eliseu: “Vê, o lugar em que moramos contigo tornou-se estreito demais para nós.

[[v12-6-2]]

^<<v12-6-2,2>>^ Vamos até o Jordão, tomemos dali cada um de nós uma viga e construamos ali uma sala em que possamos habitar”. “Ide” – respondeu-lhes ele –.

[[v12-6-3]]

^<<v12-6-3,3>>^ “Mas vem também tu com os teus servos” – ajuntou um deles –. “Eu irei” – disse ele.

[[v12-6-4]]

^<<v12-6-4,4>>^ E partiu com eles. Chegados ao Jordão, puseram-se a cortar madeira.

[[v12-6-5]]

^<<v12-6-5,5>>^ Ora, estando um deles a cortar uma árvore, eis que o seu machado caiu na água. “Ah, meu senhor!” – exclamou ele. Porque o machado era emprestado.

[[v12-6-6]]

^<<v12-6-6,6>>^ “Onde caiu ele?” – perguntou o homem de Deus. Ele mostrou-lhe o lugar. Eliseu cortou um pedaço de madeira, jogou-o na água e o machado veio à tona.

[[v12-6-7]]

^<<v12-6-7,7>>^ “Tira-o” – disse ele. O homem estendeu a mão e tomou-o.

[[v12-6-8]]

^<<v12-6-8,8>>^ O rei da Síria, que estava em guerra contra Israel, teve conselho com os seus servos e disse-lhes: “Em tal e tal lugar estará o meu acampamento”.

[[v12-6-9]]

^<<v12-6-9,9>>^ Mandou então o homem de Deus dizer ao rei de Israel: “Guarda-te de passar por tal lugar, porque os sírios estão ali”.

[[v12-6-10]]

^<<v12-6-10,10>>^ O rei de Israel mandou homens ao lugar indicado pelo homem de Deus em sua mensagem. E o rei acautelou-se não apenas uma ou duas vezes.

[[v12-6-11]]

^<<v12-6-11,11>>^ O rei da Síria, alvoroçado por causa disso, chamou seus servos e disse-lhes: “Não me descobrireis quem dos nossos nos traiu junto do rei de Israel?”.

[[v12-6-12]]

^<<v12-6-12,12>>^ “Não foi ninguém, ó rei, meu senhor – respondeu um deles –, é o profeta Eliseu quem conta ao rei de Israel os planos que fazes em teu quarto de dormir.”

[[v12-6-13]]

^<<v12-6-13,13>>^ “Ide – disse o rei –, e vede onde ele está, para que eu o mande prender.” Disseram ao rei: “Ele está agora em Dotain”.

[[v12-6-14]]

^<<v12-6-14,14>>^ O rei enviou ali cavalos, carros e uma companhia importante; chegaram de noite e cercaram o lugar.

[[v12-6-15]]

^<<v12-6-15,15>>^ Na manhã seguinte, o homem de Deus, saindo fora, viu o exército que cercava a cidade com cavalos e carros. Seu servo disse-lhe: “Ai, meu senhor! Que vamos fazer agora?”.

[[v12-6-16]]

^<<v12-6-16,16>>^ “Não temas – respondeu Eliseu –, os que estão conosco são mais numerosos do que os que estão com eles.”

[[v12-6-17]]

^<<v12-6-17,17>>^ Orou Eliseu e disse: “Senhor, abri-lhe os olhos, para que veja”. O Senhor abriu os olhos do servo e este viu o monte cheio de cavalos e carros de fogo ao redor de Eliseu.

[[v12-6-18]]

^<<v12-6-18,18>>^ Entretanto, os sírios desciam para ele e Eliseu orou ao Senhor, dizendo: “Feri de cegueira estes homens”. E o Senhor, ouvindo a prece de Eliseu, feriu-os de cegueira.

[[v12-6-19]]

^<<v12-6-19,19>>^ Eliseu disse-lhes: “Não é por aqui o caminho nem é esta a cidade. Segui-me! Vou conduzir-vos ao homem que buscais”. E levou-os a Samaria.

[[v12-6-20]]

^<<v12-6-20,20>>^ Tendo eles entrado em Samaria, Eliseu disse: “Senhor, abri os olhos desses homens para que vejam”. O Senhor abriu-lhes os olhos e eles viram que estavam em Samaria.

[[v12-6-21]]

^<<v12-6-21,21>>^ O rei de Israel, tendo-os visto, disse a Eliseu: “Devo matá-los, meu pai?”.

[[v12-6-22]]

^<<v12-6-22,22>>^ “Não” – respondeu ele –. “Fere aos que capturares com tua espada e teu arco. A estes, porém, dá-lhes pão e água, para que restaurem as forças e voltem em seguida para junto de seu senhor.”

[[v12-6-23]]

^<<v12-6-23,23>>^ O rei mandou que se lhes servisse um grande banquete e depois que acabaram de comer e beber, deixou-os em liberdade e eles voltaram para o seu soberano. A partir de então, os guerrilheiros sírios cessaram as suas incursões nas terras de Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ Depois disso, Ben-Adad, rei da Síria, mobilizou todo o seu exército e subiu para pôr cerco diante de Samaria.^&#42;1^

[[v12-6-25]]

^<<v12-6-25,25>>^ A fome alastrou-se pela cidade e o cerco foi tão rude que uma cabeça de jumento valia oitenta siclos de prata e a quarta parte de um cab de grãos, cinco siclos de prata.^&#42;1^

[[v12-6-26]]

^<<v12-6-26,26>>^ Um dia em que o rei circulava pela muralha, uma mulher gritou-lhe: “Socorre-me, ó rei, meu senhor!”.

[[v12-6-27]]

^<<v12-6-27,27>>^ O rei respondeu-lhe: “Se o Senhor não te salva, com que te poderei eu socorrer? Porventura, com a eira ou com o lagar?”.^&#42;1^

[[v12-6-28]]

^<<v12-6-28,28>>^ E ajuntou: “Que te aconteceu?”. Ela respondeu: “Esta mulher, que aqui vês, disse-me: ‘Dá-me o teu filho para o comermos hoje; amanhã comeremos o meu’.

[[v12-6-29]]

^<<v12-6-29,29>>^ Cozemos então o meu filho e o comemos. No dia seguinte, quando eu lhe disse: ‘Dá-me o teu filho para que o comamos’, ela o escondeu”.

[[v12-6-30]]

^<<v12-6-30,30>>^ Ouvindo o que lhe dizia a mulher, o rei rasgou as vestes, e como ia passando pela muralha, o povo viu que ele trazia um cilício sobre o corpo.

[[v12-6-31]]

^<<v12-6-31,31>>^ “Que Deus me trate com todo o rigor, se a cabeça de Eliseu, filho de Safat, lhe ficar ainda hoje sobre os ombros!”^&#42;1^

[[v12-6-32]]

^<<v12-6-32,32>>^ Ora, Eliseu achava-se em sua casa e os anciãos sentados com ele. O rei se fizera preceder por um emissário; mas, antes que este chegasse, Eliseu disse aos anciãos: “Vede como este filho de bandido manda alguém para cortar-me a cabeça? Atenção! Quando chegar o emissário, fechai-lhe a porta e repeli-o. Mas não se ouve já o ruído dos passos de seu amo, que o segue?”.

[[v12-6-33]]

^<<v12-6-33,33>>^ Não tinha ainda acabado de falar, quando o mensageiro se apresentou diante dele e disse-lhe: “Quando um tão grande mal nos vem do Senhor, que poderei eu esperar ainda?”.

'''

xref:012-ii-reis/012-ii-reis-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-ii-reis/012-ii-reis-007.adoc#v12-7-0[Próximo Capítulo &#62;]