include::./index.adoc[]

[[v12-24-0]]
=== II Reis, 24
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 24 de 2 Reis relata a queda de Judá diante da Babilônia, incluindo a invasão do rei Nabucodonosor, o cerco de Jerusalém e o exílio do rei Joaquim e grande parte do povo de Judá. Para encontrar cinco versículos relacionados com os temas abordados nesse capítulo, vasculhei toda a Bíblia e selecionei:
* Jeremias 25:9: "Eis que enviarei e tomarei todas as famílias do Norte, diz o Senhor, e a Nabucodonosor, rei da Babilônia, meu servo, e os trarei contra esta terra e contra os seus habitantes e contra todas estas nações em redor, e os destruirei totalmente e farei deles objeto de horror e de assobio, perpétuas ruínas." Esse versículo prediz a queda de Jerusalém e a invasão da Babilônia, demonstrando a fidelidade de Deus em cumprir suas promessas.
* Jeremias 21:7: "Depois disto, diz o Senhor, entregarei Zedequias, rei de Judá, e seus servos, e o povo, e os que nesta cidade restarem da peste, da espada e da fome, na mão de Nabucodonosor, rei da Babilônia, na mão dos seus inimigos, na mão dos que buscam tirar-lhes a vida; e ele os ferirá a fio de espada, não os poupará, nem terá piedade, nem se compadecerá." Esse versículo indica a punição que seria imposta a Judá por sua infidelidade, incluindo o exílio e a morte de muitos de seus habitantes.
* Lamentações 1:3: "Judá foi para o cativeiro por causa da aflição e da grande servidão; habita entre as nações, não acha descanso; todos os seus perseguidores a alcançam entre as suas angústias." Esse versículo descreve a situação de Judá após o exílio, vivendo como uma nação dispersa e oprimida entre outras nações.
* Ezequiel 17:12: "Dize, pois, à casa rebelde: Não sabeis o que significam estas coisas? Dize: Eis que veio o rei da Babilônia a Jerusalém, e tomou o rei dela e os príncipes dela, e os levou consigo para Babilônia." Esse versículo faz referência ao exílio de Joaquim e dos príncipes de Judá para a Babilônia, enfatizando a justiça de Deus em punir a infidelidade do povo.
* Salmos 137:1: "Junto aos rios da Babilônia, ali nos assentamos e choramos, quando nos lembramos de Sião." Esse versículo descreve a tristeza e a saudade do povo de Judá pelo lugar que lhes foi tirado e a necessidade de lembrar de Deus e de sua aliança mesmo em meio à adversidade.
****

[[v12-24-1]]

^<<v12-24-1,1>>^ Durante o reinado de Joaquim, Nabucodonosor, rei da Babilônia, subiu contra Joaquim, que se tornou seu vassalo por três anos. Depois revoltou-se contra ele.

[[v12-24-2]]

^<<v12-24-2,2>>^ O Senhor mandou contra ele os bandos dos caldeus, dos sírios, dos moabitas e dos amonitas e lançou-os contra Judá para o destruírem, conforme ele havia anunciado pela boca dos profetas, seus servos.

[[v12-24-3]]

^<<v12-24-3,3>>^ Isso aconteceu realmente por ordem do Senhor, para afastá-lo de sua presença, por causa dos pecados cometidos por Manassés,

[[v12-24-4]]

^<<v12-24-4,4>>^ e por causa do sangue inocente que ele tinha derramado, chegando a inundar Jerusalém de sangue inocente. Por isso, o Senhor não quis perdoar.

[[v12-24-5]]

^<<v12-24-5,5>>^ O restante da história de Joaquim, seus atos e grandes feitos, tudo se acha consignado no Livro das Crônicas dos reis de Judá.

[[v12-24-6]]

^<<v12-24-6,6>>^ Joaquim adormeceu com seus pais e seu filho Joaquin sucedeu-lhe no trono.

[[v12-24-7]]

^<<v12-24-7,7>>^ O rei do Egito cessou então suas expedições fora de sua terra, porque o rei da Babilônia se tinha apoderado de todas as possessões do rei do Egito, desde a torrente do Egito até o Eufrates.

[[v12-24-8]]

^<<v12-24-8,8>>^ Joaquin tinha dezoito anos quando começou a reinar. Reinou durante três meses em Jerusalém. Sua mãe chamava-se Noesta, filha de Elnatã e era natural de Jerusalém.

[[v12-24-9]]

^<<v12-24-9,9>>^ Fez o mal aos olhos do Senhor, como o tinha feito seu pai.

[[v12-24-10]]

^<<v12-24-10,10>>^ Foi nesse tempo que vieram os homens de Nabucodonosor, rei da Babilônia, contra Jerusalém e a sitiaram.^&#42;1^

[[v12-24-11]]

^<<v12-24-11,11>>^ Depois, Nabucodonosor veio pessoalmente diante da cidade, enquanto suas tropas a sitiavam.

[[v12-24-12]]

^<<v12-24-12,12>>^ Joaquin, rei de Judá, foi ter com o rei da Babilônia, em companhia de sua mãe, suas tropas, seus oficiais e seus eunucos. E o rei da Babilônia o prendeu. Isso foi no oitavo ano de seu reinado.

[[v12-24-13]]

^<<v12-24-13,13>>^ E como o Senhor tinha anunciado, levou dali todos os tesouros do Templo do Senhor e do palácio real e quebrou todos os objetos de ouro que Salomão, rei de Israel, tinha mandado fazer para o santuário do Senhor.

[[v12-24-14]]

^<<v12-24-14,14>>^ Levou para o cativeiro toda a Jerusalém, todos os chefes e todos os homens de valor, ao todo dez mil, com todos os ferreiros e artífices; só deixou os pobres.

[[v12-24-15]]

^<<v12-24-15,15>>^ Deportou Joaquin para Babilônia, com sua mãe, suas mulheres, os eunucos do rei e os grandes da terra.

[[v12-24-16]]

^<<v12-24-16,16>>^ Todos os homens de valor, em número de sete mil, os ferreiros e os artífices, em número de mil e todos os homens aptos para a guerra, o rei da Babilônia os deportou para Babilônia.

[[v12-24-17]]

^<<v12-24-17,17>>^ Em lugar de Joaquin, o rei da Babilônia constituiu rei o seu tio Matanias, cujo nome mudou para Sedecias.

[[v12-24-18]]

^<<v12-24-18,18>>^ Sedecias tinha vinte e um anos quando começou a reinar. Reinou durante onze anos em Jerusalém. Sua mãe chamava-se Hamital, filha de Jeremias, e era natural de Lebna.^&#42;1^

[[v12-24-19]]

^<<v12-24-19,19>>^ Fez o mal aos olhos do Senhor como o tinha feito Joaquin.

[[v12-24-20]]

^<<v12-24-20,20>>^ Assim aconteceu a Jerusalém e a Judá, porque o Senhor queria, em sua cólera, rejeitá-los de sua presença. Sedecias revoltou-se contra o rei da Babilônia.

'''

xref:012-ii-reis/012-ii-reis-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-ii-reis/012-ii-reis-025.adoc#v12-25-0[Próximo Capítulo &#62;]