include::./index.adoc[]

[[v12-8-0]]
=== II Reis, 8
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 8 de 2 Reis relata a história de Hazael, um homem que acabaria se tornando rei da Síria, e sua interação com o profeta Eliseu e o rei Jeorão de Israel. Hazael visita Eliseu disfarçado e pergunta sobre a saúde do rei Jeorão, enquanto na verdade ele estava interessado em saber se seria capaz de se tornar rei. Mais tarde, Eliseu envia um de seus discípulos para ungir Hazael como rei da Síria, mas também profetiza que ele causará muita destruição. Abaixo estão cinco versículos relacionados com os temas abordados em 2 Reis 8:
* Isaías 7:16: "Pois antes que o menino saiba dizer ‘Papai’ ou ‘Mamãe’, o poder de Damasco e o despojo de Samaria serão levados pelo rei da Assíria". Este versículo fala sobre a queda de Damasco, que é mencionada em 2 Reis 8:7.
* 2 Reis 9:14: "Então Jeú, filho de Jeosafá e neto de Ninsi, conspirou contra Jorão". Este versículo começa a história de Jeú, que mais tarde se torna rei de Israel. A história de Jeú é importante porque ele é o escolhido por Deus para punir a casa de Acabe por sua idolatria e maldade, um tema recorrente em 2 Reis.
* Isaías 7:8: "Porque a cabeça da Síria é Damasco, e a cabeça de Damasco é Rezim". Este versículo também fala sobre a queda de Damasco e a derrota da Síria.
* Oséias 1:4: "Então o Senhor disse a Oseias: "Dê-lhe o nome de Jezreel, porque em pouco tempo castigarei a dinastia de Jeú pelo massacre em Jezreel, e acabarei com o reino de Israel". Este versículo fala sobre a punição que Deus planeja para a casa de Jeú, que é mencionado em 2 Reis 9:7.
* 2 Reis 10:32: "Naqueles dias, o Senhor começou a reduzir o território de Israel. Hazael derrotou os israelitas em toda a extensão leste do Jordão". Este versículo fala sobre as ações de Hazael, que é apresentado em 2 Reis 8 como um futuro rei da Síria e que acaba causando destruição em Israel, cumprindo a profecia de Eliseu.
****

[[v12-8-1]]

^<<v12-8-1,1>>^ Eliseu dissera à mulher, cujo filho ele ressuscitara: “Parte com todos os teus e habita no estrangeiro, porque o Senhor fez vir a fome e ela virá sobre a terra durante sete anos”.

[[v12-8-2]]

^<<v12-8-2,2>>^ Essa mulher fez o que lhe disse o homem de Deus: emigrou com sua família e habitou sete anos na terra dos filisteus.

[[v12-8-3]]

^<<v12-8-3,3>>^ Passados os sete anos, voltou da terra dos filisteus e foi falar ao rei a respeito de sua casa e de sua terra.^&#42;1^

[[v12-8-4]]

^<<v12-8-4,4>>^ O rei estava conversando com Giezi, servo do homem de Deus, e pedia-lhe que lhe contasse os prodígios que Eliseu tinha feito.

[[v12-8-5]]

^<<v12-8-5,5>>^ Giezi estava justamente contando como Eliseu havia ressuscitado um morto, quando a mulher, cujo filho ressuscitara, chegou para implorar ao rei a respeito de sua casa e de sua terra. Giezi exclamou: “Ó rei, meu senhor! Eis a mulher com o filho que Eliseu ressuscitou”.

[[v12-8-6]]

^<<v12-8-6,6>>^ O rei interrogou a mulher e esta narrou-lhe o acontecido. Então, o rei fê-la acompanhar por um eunuco com a seguinte ordem: “Faze-lhe restituir tudo o que lhe pertence, assim como todos os rendimentos de sua terra, desde o dia em que ela a deixou até o dia de hoje”.

[[v12-8-7]]

^<<v12-8-7,7>>^ Eliseu foi a Damasco. Ben-Adad, rei da Síria, estava doente. Avisaram-no, dizendo: “O homem de Deus está aqui”.

[[v12-8-8]]

^<<v12-8-8,8>>^ Disse então o rei a Hazael: “Toma contigo um presente e vai ao encontro do homem de Deus. Consultarás o Senhor, por seu intermédio, se ficarei curado desta enfermidade”.

[[v12-8-9]]

^<<v12-8-9,9>>^ Hazael partiu e foi ao encontro do homem de Deus, levando-lhe presentes, o que havia de melhor em Damasco, em quarenta camelos carregados. Chegando aonde ele estava, disse-lhe: “Teu filho Ben-Adad, rei da Síria, mandou-me ter contigo para perguntar-te se sairá vivo de sua enfermidade”.

[[v12-8-10]]

^<<v12-8-10,10>>^ Eliseu respondeu-lhe: “Vai e dize-lhe que ele será certamente curado. Mas o Senhor revelou-me que ele morrerá”.

[[v12-8-11]]

^<<v12-8-11,11>>^ Depois o homem de Deus olhou-o fixamente, de modo que Hazael se sentiu perturbado; e o homem de Deus pôs-se a chorar.

[[v12-8-12]]

^<<v12-8-12,12>>^ “Por que chora o meu senhor?” – perguntou Hazael. Ele respondeu: “Porque sei os males que farás aos israelitas: incendiarás as suas cidades fortes, passarás a fio de espada os seus jovens, esmagarás as suas crianças e rasgarás pelo meio o ventre de suas mulheres grávidas”.

[[v12-8-13]]

^<<v12-8-13,13>>^ “Será o teu servo, porventura, um cão – disse-lhe Hazael –, para fazer tais coisas?” Eliseu respondeu: “O Senhor mostrou-me em uma visão que serás rei da Síria”.

[[v12-8-14]]

^<<v12-8-14,14>>^ Deixando Eliseu, voltou Hazael para junto de seu amo, o qual lhe perguntou: “Que te disse Eliseu?”. “Disse-me – respondeu ele – que serás certamente curado”.

[[v12-8-15]]

^<<v12-8-15,15>>^ No dia seguinte, Hazael tomou uma cobertura, molhou-a em água e aplicou-a sobre o rosto do rei e este morreu. E Hazael sucedeu-lhe no trono.

[[v12-8-16]]

^<<v12-8-16,16>>^ No quinto ano de Jorão, filho de Acab, rei de Israel, Jorão, filho de Josafá, tornou-se rei de Judá.

[[v12-8-17]]

^<<v12-8-17,17>>^ Tinha trinta e dois anos quando começou a reinar. Reinou oito anos em Jerusalém.

[[v12-8-18]]

^<<v12-8-18,18>>^ Andou pelos caminhos dos reis de Israel, como fizera a casa de Acab, cuja filha desposou. E fez o mal aos olhos do Senhor.^&#42;1^

[[v12-8-19]]

^<<v12-8-19,19>>^ Apesar disso, o Senhor não quis destruir a casa de Judá, por causa de Davi, seu servo, a quem prometera conservar sempre uma lâmpada na sua descendência.

[[v12-8-20]]

^<<v12-8-20,20>>^ No tempo de Jorão, os edomitas sacudiram o jugo de Judá e constituíram um rei para si.

[[v12-8-21]]

^<<v12-8-21,21>>^ Jorão foi a Seira com todos os seus carros e, durante a noite, feriu os edomitas que o tinham cercado; e os chefes dos carros com as tropas fugiram para as suas tendas.^&#42;1^

[[v12-8-22]]

^<<v12-8-22,22>>^ E assim Edom sacudiu o jugo de Judá até o dia de hoje. Naquele mesmo tempo, Lebna libertou-se igualmente.

[[v12-8-23]]

^<<v12-8-23,23>>^ Os outros atos e grandes feitos de Jorão estão consignados no Livro das Crônicas dos reis de Judá.

[[v12-8-24]]

^<<v12-8-24,24>>^ Jorão adormeceu com os seus pais e foi sepultado junto deles na Cidade de Davi. Seu filho Ocozias sucedeu-lhe no trono.

[[v12-8-25]]

^<<v12-8-25,25>>^ No décimo segundo ano de Jorão, filho de Acab, rei de Israel, Ocozias, filho de Jorão, tornou-se rei de Judá.

[[v12-8-26]]

^<<v12-8-26,26>>^ Ocozias tinha vinte e dois anos quando começou a reinar e reinou um ano em Jerusalém. Sua mãe chamava-se Atalia e era filha (neta) de Amri, rei de Israel.

[[v12-8-27]]

^<<v12-8-27,27>>^ Andou nos caminhos da casa de Acab e fez o mal aos olhos do Senhor, como a casa de Acab, porque lhe era aliado.

[[v12-8-28]]

^<<v12-8-28,28>>^ Saiu com Jorão, filho de Acab, a combater Hazael, rei da Síria, em Ramot de Galaad e foi ferido pelos sírios.

[[v12-8-29]]

^<<v12-8-29,29>>^ E voltou então a Jezrael para se curar dos ferimentos recebidos dos sírios no combate contra Hazael, rei da Síria. Ocozias, filho de Jorão, rei de Judá, desceu a Jezrael para visitar Jorão, filho de Acab, que estava enfermo.

'''

xref:012-ii-reis/012-ii-reis-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-ii-reis/012-ii-reis-009.adoc#v12-9-0[Próximo Capítulo &#62;]