include::./index.adoc[]

[[v12-4-0]]
=== II Reis, 4
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* O capítulo 4 de 2 Reis conta diversas histórias relacionadas a Eliseu, o sucessor de Elias. Neste capítulo, Eliseu realiza muitos milagres, incluindo a multiplicação do azeite de uma viúva, a ressurreição do filho de outra viúva e a cura da panela envenenada de seus discípulos. Abaixo estão cinco versículos relacionados aos temas abordados neste capítulo:
* Salmos 68:5: "Pai dos órfãos e juiz das viúvas é Deus em sua santa habitação." Este versículo fala sobre o cuidado de Deus pelas viúvas e órfãos, um tema presente em 2 Reis 4, onde Eliseu ajuda duas viúvas em necessidade.
* Mateus 10:8: "Curem os doentes, ressuscitem os mortos, purifiquem os leprosos, expulsem os demônios. Vocês receberam de graça; deem também de graça." Esse versículo fala sobre os milagres que Jesus ordenou que Seus discípulos fizessem, incluindo a ressurreição de mortos, um milagre que Eliseu realiza em 2 Reis 4:18-37.
* Tiago 5:14-15: "Algum de vocês está doente? Chame os presbíteros da igreja, orem sobre ele e unjam com óleo em nome do Senhor. E a oração da fé salvará o doente, e o Senhor o levantará. Se ele tiver pecados, eles serão perdoados." Este versículo fala sobre como a oração e a unção com óleo podem trazer cura e perdão de pecados, como acontece quando Eliseu cura a panela envenenada em 2 Reis 4:38-41.
* Romanos 8:28: "E sabemos que todas as coisas trabalham juntas para o bem daqueles que amam a Deus, daqueles que são chamados segundo o Seu propósito." Este versículo fala sobre como Deus pode usar as situações difíceis para o nosso bem, um tema presente em 2 Reis 4:1-7, onde a viúva que não tinha dinheiro para pagar suas dívidas é milagrosamente ajudada por Deus através de Eliseu.
* 2 Coríntios 12:9: "Mas Ele me disse: 'Minha graça é suficiente para você, pois meu poder é aperfeiçoado na fraqueza'. Portanto, eu me gloriarei ainda mais alegremente em minhas fraquezas, para que o poder de Cristo possa descansar sobre mim." Este versículo fala sobre como a graça de Deus é suficiente para nós em nossas fraquezas, um tema presente em 2 Reis 4:38-41, onde Eliseu usa um método incomum (farinha) para curar a panela envenenada, mostrando que Deus pode usar meios inesperados para realizar Seus milagres.
****

[[v12-4-1]]

^<<v12-4-1,1>>^ A mulher de um dos filhos dos profetas clamou a Eliseu, dizendo: “Meu marido, teu servo, morreu e sabes que ele temia o Senhor. Ora, eis que veio o credor tomar os meus dois filhos para fazê-los seus escravos”.

[[v12-4-2]]

^<<v12-4-2,2>>^ Eliseu disse-lhe: “Que posso eu fazer por ti? Dize-me: ‘O que tens em tua casa?’.” Ela respondeu: “Tua serva só tem em sua casa uma garrafa de óleo”.

[[v12-4-3]]

^<<v12-4-3,3>>^ “Vai – replicou Eliseu –, pede emprestadas às tuas vizinhas ânforas vazias em grande quantidade.

[[v12-4-4]]

^<<v12-4-4,4>>^ Depois entra, fecha a porta atrás de ti e de teus filhos e enche com o óleo estas ânforas, pondo-as de lado à medida que estiverem cheias!”

[[v12-4-5]]

^<<v12-4-5,5>>^ Partiu a mulher e fechou a porta atrás de si e de seus filhos. Estes traziam-lhe as ânforas e ela as enchia.

[[v12-4-6]]

^<<v12-4-6,6>>^ Tendo enchido as ânforas, disse ela ao seu filho: “Dá-me mais uma ânfora”. “Não há mais” – respondeu ele. E o óleo cessou de correr.

[[v12-4-7]]

^<<v12-4-7,7>>^ A mulher foi e contou tudo ao homem de Deus. Este disse-lhe: “Vai e vende esse óleo para pagar a tua dívida. Depois disso, tu e teus filhos vivereis do resto”.

[[v12-4-8]]

^<<v12-4-8,8>>^ Certo dia em que Eliseu atravessava Sunão, veio uma mulher rica do lugar e insistiu com ele para comer em sua casa. Depois disso, cada vez que ele passava por aquele lugar, dirigia-se à casa daquela mulher para tomar ali a sua refeição.

[[v12-4-9]]

^<<v12-4-9,9>>^ Ela disse ao seu marido: “Escuta, eu sei que esse homem que passa sempre por nossa casa é um santo homem de Deus.

[[v12-4-10]]

^<<v12-4-10,10>>^ Preparemos-lhe em cima um quarto, obra de pedreiro, onde poremos uma cama, uma mesa, uma cadeira e uma lâmpada; assim poderá acomodar-se ali quando vier à nossa casa”.

[[v12-4-11]]

^<<v12-4-11,11>>^ Ora, aconteceu que um dia, passando Eliseu por Sunão, retirou-se ao quarto de cima para dormir.

[[v12-4-12]]

^<<v12-4-12,12>>^ E disse a Giezi, seu servo: “Chama essa sunamita”. Giezi chamou-a e ela apresentou-se diante dele.

[[v12-4-13]]

^<<v12-4-13,13>>^ “Pergunta-lhe – disse Eliseu – o que posso fazer por ela em reconhecimento do desvelo com que nos tem tratado. Talvez ela queira que se fale ao rei ou ao general do exército sobre algum negócio seu.” “Eu habito no meio de meu povo” – respondeu ela.

[[v12-4-14]]

^<<v12-4-14,14>>^ Eliseu então disse: “Que se pode fazer por ela?”. “Ela não tem filhos – respondeu Giezi – e seu marido é idoso.”

[[v12-4-15]]

^<<v12-4-15,15>>^ “Chama-a’’ – disse Eliseu. Giezi chamou-a e ela apareceu à porta.

[[v12-4-16]]

^<<v12-4-16,16>>^ Eliseu disse-lhe: “Por esse tempo, daqui a um ano, acariciarás um filho”. “Não, meu senhor – respondeu ela –, não zombes de tua escrava, ó homem de Deus!”

[[v12-4-17]]

^<<v12-4-17,17>>^ E a mulher, no ano seguinte, à mesma época, como tinha predito Eliseu, deu à luz um filho.

[[v12-4-18]]

^<<v12-4-18,18>>^ O menino cresceu. Um dia em que ele fora ter com seu pai junto dos ceifadores,

[[v12-4-19]]

^<<v12-4-19,19>>^ disse-lhe: “Ai, minha cabeça, minha cabeça!”. “Leva-o à sua mãe” – disse o pai a um escravo.

[[v12-4-20]]

^<<v12-4-20,20>>^ Este levou-o e entregou-o à sua mãe. O menino ficou nos joelhos da mãe até meio-dia e morreu.

[[v12-4-21]]

^<<v12-4-21,21>>^ Ela subiu, colocou o menino na cama do homem de Deus, fechou a porta e saiu.

[[v12-4-22]]

^<<v12-4-22,22>>^ Chamou o marido e disse-lhe: “Manda comigo um escravo e uma jumenta para que eu vá à casa do homem de Deus e volte”.

[[v12-4-23]]

^<<v12-4-23,23>>^ Ele disse-lhe: “Por que vais ter com ele hoje? Não é lua nova nem sábado”. “Fica tranquilo” – respondeu ela.

[[v12-4-24]]

^<<v12-4-24,24>>^ Mandou selar a jumenta e disse ao escravo: “Conduze-me, apressa-te, não me detenhas em caminho sem que eu te diga”.

[[v12-4-25]]

^<<v12-4-25,25>>^ Ela partiu e chegou aonde estava o homem de Deus, no monte Carmelo. O homem de Deus, vendo-a de longe, disse ao seu servo Giezi: “Aí vem a sunamita;

[[v12-4-26]]

^<<v12-4-26,26>>^ corre-lhe ao encontro e pergunta-lhe se ela vai bem, como vai o seu marido e o seu filho”. Ela respondeu: “Tudo vai bem”.

[[v12-4-27]]

^<<v12-4-27,27>>^ Mas chegando junto do homem de Deus na montanha, pegou-lhe os pés. Giezi aproximou-se para afastá-la, mas o homem de Deus disse-lhe: “Deixa-a; sua alma está cheia de amargura e o Senhor me oculta o motivo, nada me revelou”.^&#42;1^

[[v12-4-28]]

^<<v12-4-28,28>>^ A mulher disse: “Pedi eu, porventura, um filho ao meu senhor? Não te disse que não zombasses de mim?”.

[[v12-4-29]]

^<<v12-4-29,29>>^ Eliseu disse a Giezi: “Põe o teu cinto, toma na mão o meu bastão e parte. Se encontrares alguém, não o saúdes; e se alguém te saudar, não lhe respondas. Porás o meu bastão no rosto do menino”.^&#42;1^

[[v12-4-30]]

^<<v12-4-30,30>>^ A mãe do menino exclamou: “Por Deus e pela tua vida, não te deixarei!”. Então, Eliseu seguiu-a.

[[v12-4-31]]

^<<v12-4-31,31>>^ Entretanto, Giezi, que os tinha precedido, pôs o bastão no rosto do menino; mas não houve voz, nem sinal de vida. Ele voltou a Eliseu e disse-lhe: “O menino não despertou”.

[[v12-4-32]]

^<<v12-4-32,32>>^ Eliseu entrou na casa, onde estava o menino morto em cima da cama.

[[v12-4-33]]

^<<v12-4-33,33>>^ Entrou, fechou a porta atrás de si e do morto e orou ao Senhor.

[[v12-4-34]]

^<<v12-4-34,34>>^ Depois, subiu à cama, deitou-se em cima do menino, colocou seus olhos sobre os olhos dele, suas mãos sobre as mãos dele e enquanto estava assim estendido, o corpo do menino aqueceu-se.

[[v12-4-35]]

^<<v12-4-35,35>>^ Eliseu levantou-se, deu algumas voltas pelo quarto, tornou a subir e estendeu-se sobre o menino. Este espirrou sete vezes e abriu os olhos.

[[v12-4-36]]

^<<v12-4-36,36>>^ Eliseu chamou Giezi e disse-lhe: “Chama a sunamita”. Ele a chamou. Ela entrou e Eliseu disse-lhe: “Toma o teu filho”.

[[v12-4-37]]

^<<v12-4-37,37>>^ Então, ela veio e lançou-se aos pés de Eliseu, prostrando-se por terra. Em seguida, tomou o filho e saiu.

[[v12-4-38]]

^<<v12-4-38,38>>^ Quando Eliseu voltou a Gálgala, a fome devastava a terra. Estando os filhos dos profetas sentados diante dele, disse ao seu servo: “Toma uma panela grande e prepara uma sopa para os filhos dos profetas”.

[[v12-4-39]]

^<<v12-4-39,39>>^ Foi um deles ao campo para colher legumes e encontrou uma planta silvestre. Colheu dela coloquíntidas selvagens, encheu o manto, voltou para casa e cortou-as em pedaços dentro da panela da sopa, sem saber o que era.

[[v12-4-40]]

^<<v12-4-40,40>>^ Serviu-se a refeição aos homens. Logo, porém, que provaram da sopa, puseram-se a gritar: “Homem de Deus, a morte está na panela!”. E não puderam comer.

[[v12-4-41]]

^<<v12-4-41,41>>^ Eliseu disse-lhes: “Trazei-me farinha”. Jogou farinha na panela e disse: “Serve agora, para que todos comam”. E não havia mais nada ruim na panela.

[[v12-4-42]]

^<<v12-4-42,42>>^ Veio um homem de Baal-Salisa, que trazia ao homem de Deus, à guisa de primícias, vinte pães de cevada e trigo novo no seu saco. “Dá-os a esses homens – disse Eliseu –, para que comam.”

[[v12-4-43]]

^<<v12-4-43,43>>^ Seu servo respondeu: “Como poderei servir com isso a cem pessoas?”. “Dá-os a esses homens – repetiu Eliseu –, para que comam. Eis o que diz o Senhor: ‘Comerão e ainda sobrará’.”

[[v12-4-44]]

^<<v12-4-44,44>>^ E deu-os ao povo. Comeram e ainda sobrou, como o Senhor tinha dito.^&#42;1^

'''

xref:012-ii-reis/012-ii-reis-003.adoc#v12-3-0[&#60; Capítulo Anterior] | <<v12-4-0,Topo>> | xref:012-ii-reis/012-ii-reis-005.adoc#v12-5-0[Próximo Capítulo &#62;]