include::./index.adoc[]

[[v12-5-0]]
=== II Reis, 5
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Reis 5 narra a história de Naamã, um oficial sírio que tinha lepra e foi curado por Deus por meio do profeta Eliseu. Os temas abordados neste capítulo incluem fé, humildade, obediência e cura divina.
* Tiago 2:14-17: "De que adianta, meus irmãos, alguém dizer que tem fé se não tem obras? Acaso a fé pode salvá-lo? Se um irmão ou irmã estiver necessitando de roupas e do alimento de cada dia e um de vocês lhe disser: "Vá em paz, aqueça-se e alimente-se até satisfazer-se", sem porém lhe dar nada, de que adianta isso? Assim também a fé, por si só, se não for acompanhada de obras, está morta." Este versículo destaca a importância de não apenas professar fé, mas também colocá-la em ação através de boas obras, como a humildade e obediência de Naamã ao seguir as instruções de Eliseu.
* Salmos 103:3: "Ele perdoa todos os seus pecados e cura todas as suas enfermidades." Este versículo fala sobre a cura divina e o poder de Deus para curar todas as doenças, como a lepra de Naamã.
* Mateus 8:2-3: "Eis que um leproso aproximou-se dele e, prostrando-se de joelhos, disse: 'Senhor, se quiseres, podes purificar-me'. Jesus estendeu a mão, tocou nele e disse: 'Quero. Seja purificado!' Imediatamente ele foi purificado da lepra." Este versículo mostra outro exemplo de cura divina por meio do toque de Jesus, que é semelhante ao toque de Eliseu em Naamã.
* Lucas 17:11-19: "Aconteceu que, quando se dirigia para Jerusalém, Jesus passou entre Samaria e Galileia. Ao entrar em uma aldeia, dez homens leprosos dirigiram-se a ele. Ficaram a certa distância e gritaram em alta voz: 'Jesus, Mestre, tem misericórdia de nós!' Ao vê-los, ele disse: 'Vão mostrar-se aos sacerdotes'. E, enquanto iam, foram purificados. Um deles, quando viu que estava curado, voltou, louvando a Deus em alta voz. Prostrou-se aos pés de Jesus e lhe agradeceu. Era samaritano." Este versículo conta a história de dez homens leprosos que foram curados por Jesus, mas apenas um deles voltou para agradecer. É uma lição sobre a importância da gratidão e da fé na cura divina.
* Tiago 5:14: "Algum de vocês está doente? Chame os presbíteros da igreja, para que orem por ele e o unjam com óleo em nome do Senhor." Esse versículo fala sobre a importância da oração na cura de doenças e na busca por ajuda espiritual. Na história de Naamã, ele busca a cura física para a sua lepra, mas a lição que podemos aprender é que devemos confiar em Deus e buscar ajuda espiritual para todas as nossas necessidades, incluindo a saúde. Através da oração e do apoio da comunidade de fé, podemos encontrar a cura e a força para enfrentar os desafios da vida.
****

[[v12-5-1]]

^<<v12-5-1,1>>^ Naamã, general do exército do rei da Síria, gozava de grande prestígio diante de seu amo e era muito considerado, porque, por meio dele, o Senhor salvou a Síria. Era um homem valente, mas leproso.

[[v12-5-2]]

^<<v12-5-2,2>>^ Ora, tendo os sírios feito uma incursão no território de Israel, levaram consigo uma jovem, a qual ficou a serviço da mulher de Naamã.

[[v12-5-3]]

^<<v12-5-3,3>>^ Ela disse à sua senhora: “Ah, se meu amo fosse ter com o profeta que reside em Samaria, ele o curaria da lepra!”.

[[v12-5-4]]

^<<v12-5-4,4>>^ Ouvindo isso, Naamã foi e contou ao seu soberano o que dissera a jovem israelita.

[[v12-5-5]]

^<<v12-5-5,5>>^ O rei da Síria respondeu-lhe: “Vai, que eu enviarei uma carta ao rei de Israel”. Naamã partiu com dez talentos de prata, seis mil siclos de ouro e dez vestes de festa.

[[v12-5-6]]

^<<v12-5-6,6>>^ Levou ao rei de Israel uma carta concebida nestes termos: “Ao receberes esta carta, saberás que te mando Naamã, meu servo, para que o cures da lepra”.

[[v12-5-7]]

^<<v12-5-7,7>>^ Tendo lido a missiva, o rei de Israel rasgou as vestes e exclamou: “Sou eu, porventura, um deus, que possa dar a morte ou a vida, para que esse me mande dizer que cure um homem da lepra? Vede bem que ele anda buscando pretextos contra mim”.

[[v12-5-8]]

^<<v12-5-8,8>>^ Quando Eliseu, o homem de Deus, soube que o rei tinha rasgado as vestes, mandou-lhe dizer: “Por que rasgaste as tuas vestes? Que ele venha a mim e saberá que há um profeta em Israel”.

[[v12-5-9]]

^<<v12-5-9,9>>^ Naamã veio com seu carro e seus cavalos e parou à porta de Eliseu.

[[v12-5-10]]

^<<v12-5-10,10>>^ Este mandou-lhe dizer por um mensageiro: “Vai, lava-te sete vezes no Jordão e tua carne ficará limpa”.

[[v12-5-11]]

^<<v12-5-11,11>>^ Naamã se foi, despeitado, dizendo: “Eu pensava que ele viria em pessoa e, diante de mim, invocaria o Senhor, seu Deus, poria a mão no lugar afetado e me curaria da lepra.

[[v12-5-12]]

^<<v12-5-12,12>>^ Porventura, os rios de Damasco, o Abana e o Farfar, não são melhores do que todas as águas de Israel? Não me poderia eu lavar neles e ficar limpo?”. E, voltando-se, retirou-se encolerizado.

[[v12-5-13]]

^<<v12-5-13,13>>^ Mas seus servos, aproximando-se dele, disseram-lhe: “Meu pai, mesmo que o profeta te tivesse ordenado algo difícil, não o deverias fazer? Quanto mais agora que ele te disse: ‘Lava-te e serás curado’.”

[[v12-5-14]]

^<<v12-5-14,14>>^ Naamã desceu ao Jordão e banhou-se ali sete vezes, como lhe ordenara o homem de Deus e sua carne tornou-se tenra como a de uma criança.

[[v12-5-15]]

^<<v12-5-15,15>>^ Voltando então para o homem de Deus, com toda a sua comitiva, entrou, apresentou-se diante dele e disse: “Reconheço que não há outro Deus em toda a terra, senão o de Israel. Aceita este presente do teu servo”.

[[v12-5-16]]

^<<v12-5-16,16>>^ “Pela vida do Senhor a quem sirvo – replicou Eliseu –, não aceitarei nada.” E, apesar da instância de Naamã, ele recusou.

[[v12-5-17]]

^<<v12-5-17,17>>^ Então Naamã disse: “Se não o aceitas, permite ao menos que se dê ao teu servo da terra deste país, tanto quanto possam carregar duas mulas, porque doravante este teu servo não oferecerá mais holocausto nem sacrifício a outros deuses, mas só ao Senhor.

[[v12-5-18]]

^<<v12-5-18,18>>^ Entretanto, que o Senhor perdoe ao teu servo o seguinte: Quando o meu soberano entrar no templo de Remon para adorar, apoiando-se no meu braço seja-me permitido também me prostrar no templo de Remon. E que o Senhor perdoe esse gesto ao teu servo”.

[[v12-5-19]]

^<<v12-5-19,19>>^ Eliseu respondeu: “Faze-o tranquilamente”. E Naamã o deixou.^&#42;1^

[[v12-5-20]]

^<<v12-5-20,20>>^ Naamã estava já a certa distância, quando Giezi, servo de Eliseu, disse consigo: “Eis que meu amo poupou a esse sírio, Naamã, recusando aceitar de sua mão o que ele tinha trazido. Pela vida de Deus! Vou correr atrás dele e obterei dele alguma coisa”.

[[v12-5-21]]

^<<v12-5-21,21>>^ E Giezi foi ao alcance de Naamã, o qual, vendo-o correr, desceu do carro e veio-lhe ao encontro. E disse-lhe: “Tudo vai bem?”.

[[v12-5-22]]

^<<v12-5-22,22>>^ “Sim – respondeu Giezi –, meu senhor manda-me dizer-te: ‘Acabam de chegar à minha casa, da montanha de Efraim, dois jovens, filhos de profetas. Rogo-te que me dês para eles um talento de prata e dois hábitos de festa’.”

[[v12-5-23]]

^<<v12-5-23,23>>^ Naamã respondeu: “É melhor que leves dois talentos”. Naamã insistiu e, atando dois talentos e dois hábitos de festa em dois sacos, entregou-os a dois de seus escravos para que os levassem a Giezi.

[[v12-5-24]]

^<<v12-5-24,24>>^ Quando atingiram a colina, Giezi tomou os objetos de suas mãos e guardou-os na sua casa. Depois disso, despediu os dois homens e estes se retiraram.

[[v12-5-25]]

^<<v12-5-25,25>>^ E, tendo entrado, apresentou-se ao seu amo. Eliseu disse-lhe: “De onde vens, Giezi?”. “Teu servo não foi a parte alguma” – respondeu ele.

[[v12-5-26]]

^<<v12-5-26,26>>^ Mas Eliseu replicou: “Não estava, porventura, presente o meu espírito, quando um homem saltou de seu carro ao teu encontro? É este o momento de aceitar dinheiro, adquirir vestes, oliveiras e vinhas, ovelhas e bois, servos e servas?

[[v12-5-27]]

^<<v12-5-27,27>>^ A lepra de Naamã se pegará a ti e a toda a tua descendência para sempre”. E Giezi saiu da presença de Eliseu coberto de uma lepra branca como a neve.

'''

xref:012-ii-reis/012-ii-reis-004.adoc#v12-4-0[&#60; Capítulo Anterior] | <<v12-5-0,Topo>> | xref:012-ii-reis/012-ii-reis-006.adoc#v12-6-0[Próximo Capítulo &#62;]