include::./index.adoc[]

[[v12-2-0]]
=== II Reis, 2
// ave-maria 2005-02-05, Ave Maria

.Notas do capítulo
****
* 2 Reis 2 relata a ascensão de Elias ao céu em um redemoinho de fogo e a sucessão profética de Eliseu. Elias é levado por um carro de fogo e Eliseu herda o manto de Elias como seu sucessor profético. Aqui estão cinco versículos relacionados aos temas abordados em 2 Reis 2:
* Êxodo 13:21: "E o Senhor ia adiante deles, de dia numa coluna de nuvem para os guiar pelo caminho, e de noite numa coluna de fogo para os iluminar, para que caminhassem de dia e de noite." Este versículo lembra a manifestação de Deus em uma coluna de nuvem e fogo, semelhante ao redemoinho de fogo que levou Elias, sugerindo a presença e proteção divina.
* 2 Reis 1:10: "Respondeu Elias, dizendo ao capitão de cinquenta: Se eu sou homem de Deus, desça fogo do céu e o devore a ti e aos teus cinquenta. Então desceu fogo do céu e o devorou a ele e aos seus cinquenta." Este versículo destaca o poder de Elias como profeta de Deus, que é capaz de invocar fogo do céu para proteger sua autoridade divina.
* 2 Reis 4:14: "Então ele disse: Que faremos por ela? Respondeu Geazi: Na verdade ela não tem filho, e seu marido é velho." Este versículo introduz a história de uma mulher que hospeda Eliseu e sua conexão com o tema da sucessão profética, já que ela é recompensada com um filho por hospedar o profeta e, posteriormente, busca ajuda de Eliseu quando o filho adoece.
* 2 Reis 13:14: "E Eliseu estava doente da enfermidade de que morreu; e veio a ele Joás, rei de Israel, e chorou sobre o seu rosto, dizendo: Meu pai, meu pai! o carro de Israel, e seus cavaleiros!" Este versículo registra a morte de Eliseu e sua importância como um profeta para Israel, chamando-o de "carro de Israel" e evidenciando seu papel como uma figura significativa para o rei Joás.
* 1 Reis 19:19: "E partindo dali, achou Eliseu, filho de Safate, que lavrava com doze juntas de bois adiante dele, e ele estava com a duodécima; e Elias passou por ele e lançou sobre ele a sua capa." Este versículo conta como Elias encontrou Eliseu e o escolheu como seu sucessor profético, preparando o terreno para a sucessão profética que ocorre em 2 Reis 2.
****

[[v12-2-1]]

^<<v12-2-1,1>>^ Eis o que se passou no dia em que o Senhor arrebatou Elias ao céu num turbilhão: Elias e Eliseu partiram de Gálgala.

[[v12-2-2]]

^<<v12-2-2,2>>^ Elias disse a Eliseu: “Fica aqui, porque o Senhor me mandou a Betel”. “Por Deus e por tua vida – respondeu Eliseu –, não te deixarei.” E desceram a Betel.

[[v12-2-3]]

^<<v12-2-3,3>>^ Os filhos dos profetas, que estavam em Betel, saíram ao encontro de Eliseu e disseram-lhe: “Sabes que o Senhor vai tirar hoje o teu amo de sobre a tua cabeça?”. “Sim, eu o sei! Ficai calados!”

[[v12-2-4]]

^<<v12-2-4,4>>^ Elias disse-lhe: “Fica aqui, Eliseu, porque o Senhor manda-me a Jericó”. “Por Deus e por tua vida – respondeu ele –, não te deixarei.” E chegaram a Jericó.

[[v12-2-5]]

^<<v12-2-5,5>>^ Os filhos dos profetas que estavam em Jericó foram ter com Eliseu e disseram-lhe: “Sabes que o Senhor vai tirar hoje o teu amo de sobre a tua cabeça?”. “Sim, eu o sei. Calai-vos.”

[[v12-2-6]]

^<<v12-2-6,6>>^ Elias disse-lhe: “Fica aqui, porque o Senhor manda-me ao Jordão”. “Por Deus e pela tua vida – respondeu Eliseu –, não te deixarei.” E partiram juntos.

[[v12-2-7]]

^<<v12-2-7,7>>^ Seguiram-nos cinquenta filhos de profetas os quais pararam ao longe, diante deles, enquanto Elias e Eliseu se detinham à beira do Jordão.

[[v12-2-8]]

^<<v12-2-8,8>>^ Elias tomou o seu manto, dobrou-o e feriu com ele as águas, que se separaram para as duas bandas, de modo que atravessaram ambos a pé enxuto.

[[v12-2-9]]

^<<v12-2-9,9>>^ Tendo passado, Elias disse a Eliseu: “Pede-me algo antes que eu seja arrebatado de ti: que posso eu fazer por ti?”. Eliseu respondeu: “Seja-me concedida uma porção dobrada do teu espírito”.

[[v12-2-10]]

^<<v12-2-10,10>>^ “Pedes uma coisa difícil – replicou Elias –. “Entretanto, se me vires quando eu for arrebatado de ti, isso te será dado: mas se não me vires, não te será dado.”

[[v12-2-11]]

^<<v12-2-11,11>>^ Continuando o seu caminho, entretidos a conversar, eis que de repente um carro de fogo com cavalos de fogo os separou um do outro e Elias subiu ao céu num turbilhão.

[[v12-2-12]]

^<<v12-2-12,12>>^ Vendo isso, Eliseu exclamou: “Meu pai, meu pai! Carro e cavalaria de Israel!”. E não o viu mais. Tomando então as suas vestes, rasgou-as em duas partes.

[[v12-2-13]]

^<<v12-2-13,13>>^ Apanhou o manto que Elias deixara cair e, voltando até o Jordão, parou à beira do rio.

[[v12-2-14]]

^<<v12-2-14,14>>^ Tomou o manto que Elias deixara cair, bateu com ele nas águas, dizendo: “Onde está o Senhor, o Deus de Elias? Onde está ele?”. Tendo ferido as águas, estas separaram-se para um e outro lado e Eliseu o atravessou.

[[v12-2-15]]

^<<v12-2-15,15>>^ Os filhos dos profetas que estavam em Jericó, vendo o que acontecera defronte deles, disseram: “O espírito de Elias repousa em Eliseu’’. Foram-lhe ao encontro, prostraram-se por terra diante dele,

[[v12-2-16]]

^<<v12-2-16,16>>^ e disseram: “Sabe que entre os teus servos há cinquenta homens valentes, que podem ir em busca do teu amo. Talvez o tenha arrebatado o Espírito do Senhor e atirado com ele para algum monte ou para algum vale”. “Não os mandeis” – respondeu Eliseu.

[[v12-2-17]]

^<<v12-2-17,17>>^ Eles, porém, tanto insistiram que Eliseu teve vergonha (de recusar): “Mandai-os” – disse ele. Mandaram, pois, cinquenta homens, os quais procuraram Elias durante três dias, mas sem resultado.

[[v12-2-18]]

^<<v12-2-18,18>>^ Quando voltaram para Eliseu, que estava em Jericó, este disse-lhes: “Não vos disse eu que não fôsseis?’’.

[[v12-2-19]]

^<<v12-2-19,19>>^ Os habitantes da cidade disseram a Eliseu: “A cidade está muito bem situada, como o pode ver o meu senhor, mas as águas são más e tornam a terra estéril”.

[[v12-2-20]]

^<<v12-2-20,20>>^ Eliseu disse-lhes: “Trazei-me um prato novo e ponde nele sal”. Eles lhe trouxeram.

[[v12-2-21]]

^<<v12-2-21,21>>^ Eliseu foi à fonte e deitou sal nela, dizendo: “Eis o que diz o Senhor: ‘Sanei estas águas e elas não causarão mais nem mortes nem esterilidade’.”

[[v12-2-22]]

^<<v12-2-22,22>>^ Ficaram as águas sadias e ainda o são, segundo a palavra que o Senhor tinha dito por Eliseu.

[[v12-2-23]]

^<<v12-2-23,23>>^ Dali subiu a Betel. Enquanto ia pelo caminho, saíram da cidade alguns rapazes e puseram-se a zombar dele, dizendo: “Sobe, careca! Sobe, careca!”.

[[v12-2-24]]

^<<v12-2-24,24>>^ Eliseu, voltando-se para eles, olhou-os e amaldiçoou-os em nome do Senhor. Imediatamente saíram da floresta dois ursos e despedaçaram quarenta e dois daqueles rapazes.

[[v12-2-25]]

^<<v12-2-25,25>>^ Dali se retirou para o monte Carmelo, de onde voltou para Samaria.

'''

xref:012-ii-reis/012-ii-reis-001.adoc#v12-1-0[&#60; Capítulo Anterior] | <<v12-2-0,Topo>> | xref:012-ii-reis/012-ii-reis-003.adoc#v12-3-0[Próximo Capítulo &#62;]